Doxygen: TemplateBlockContext Class Reference
TemplateBlockContext Class Reference
Class holding stacks of blocks available in the context.
Public Member Functions
TemplateBlockContext ()
TemplateNodeBlock * get (const QCString &name) const
TemplateNodeBlock * pop (const QCString &name) const
void add (TemplateNodeBlock *block)
void add (TemplateBlockContext *ctx)
void push (TemplateNodeBlock *block)
void clear ()
Private Attributes
QDict< QList< TemplateNodeBlock > > m_blocks
Detailed Description
Class holding stacks of blocks available in the context.
Definition at line 487 of file template.cpp.
Constructor & Destructor Documentation
TemplateBlockContext()
TemplateBlockContext::TemplateBlockContext ()
Definition at line 4559 of file template.cpp.
References m_blocks.
Member Function Documentation
add() [1/2]
void TemplateBlockContext::add (TemplateNodeBlock * block)
Definition at line 4590 of file template.cpp.
References m_blocks, and TemplateNodeBlock::name().
Referenced by add(), TemplateImpl::render(), and TemplateNodeExtend::render().
add() [2/2]
void TemplateBlockContext::add (TemplateBlockContext * ctx)
Definition at line 4601 of file template.cpp.
References add(), and m_blocks.
clear()
void TemplateBlockContext::clear ()
Definition at line 4616 of file template.cpp.
References m_blocks.
Referenced by TemplateNodeExtend::render().
get()
TemplateNodeBlock * TemplateBlockContext::get (const QCString & name) const
Definition at line 4564 of file template.cpp.
References m_blocks.
Referenced by TemplateNodeBlock::render().
pop()
TemplateNodeBlock * TemplateBlockContext::pop (const QCString & name) const
Definition at line 4577 of file template.cpp.
References m_blocks.
Referenced by TemplateNodeBlock::render().
push()
void TemplateBlockContext::push (TemplateNodeBlock * block)
Definition at line 4621 of file template.cpp.
References m_blocks, and TemplateNodeBlock::name().
Referenced by TemplateNodeBlock::render().
Member Data Documentation
m_blocks
QDict< QList<TemplateNodeBlock> > TemplateBlockContext::m_blocks private
Definition at line 498 of file template.cpp.
Referenced by add(), clear(), get(), pop(), push(), and TemplateBlockContext().
The documentation for this class was generated from the following file:
src/template.cpp