Doxygen: FileTreeContext Class Reference
FileTreeContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static FileTreeContext * alloc ()
Private Member Functions
FileTreeContext ()
~FileTreeContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 668 of file context.h.
Constructor & Destructor Documentation
FileTreeContext()
FileTreeContext::FileTreeContext () private
Definition at line 7259 of file context.cpp.
References p, and Private.
Referenced by alloc().
~FileTreeContext()
FileTreeContext::~FileTreeContext () private
Definition at line 7264 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int FileTreeContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 675 of file context.h.
References RefCountedContext::addRef().
alloc()
static FileTreeContext* FileTreeContext::alloc () inline static
Definition at line 671 of file context.h.
References FileTreeContext().
Referenced by generateOutputViaTemplate().
get()
TemplateVariant FileTreeContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 7269 of file context.cpp.
References FileTreeContext::Private::get(), and p.
release()
virtual int FileTreeContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 676 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* FileTreeContext::p private
Definition at line 681 of file context.h.
Referenced by FileTreeContext(), get(), and ~FileTreeContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp