Doxygen: src/dia.cpp File Reference
dia.cpp File Reference
#include "dia.h"
#include "portable.h"
#include "config.h"
#include "message.h"
#include "util.h"
#include <qdir.h>
Functions
void writeDiaGraphFromFile (const char *inFile, const char *outDir, const char *outFile, DiaOutputFormat format)
Variables
static const int maxCmdLine = 40960
Function Documentation
writeDiaGraphFromFile()
void writeDiaGraphFromFile (const char * inFile, const char * outDir, const char * outFile, DiaOutputFormat format)
Definition at line 28 of file dia.cpp.
References Config_getBool, Config_getString, DIA_BITMAP, DIA_EPS, err(), maxCmdLine, portable_commandExtension(), portable_pathSeparator(), portable_system(), portable_sysTimerStart(), and portable_sysTimerStop().
Referenced by DocbookDocVisitor::startDiaFile(), LatexDocVisitor::startDiaFile(), DocbookDocVisitor::writeDiaFile(), HtmlDocVisitor::writeDiaFile(), RTFDocVisitor::writeDiaFile(), and LatexDocVisitor::writeDiaFile().
Variable Documentation
maxCmdLine
const int maxCmdLine = 40960 static
Definition at line 26 of file dia.cpp.
Referenced by writeDiaGraphFromFile().