Doxygen: SIntDict< T >::Iterator Class Reference
SIntDict< T >::Iterator Class Reference
#include <sortdict.h>
Public Member Functions
Iterator (const SIntDict< T > &dict)
virtual ~Iterator ()
T * toFirst () const
T * toLast () const
T * current () const
T * operator++ ()
T * operator-- ()
Private Attributes
QListIterator< T > * m_li
Detailed Description
template<class T>
class SIntDict< T >::Iterator
Simple iterator for SDict. It iterates in the order in which the elements are stored.
Definition at line 603 of file sortdict.h.
Constructor & Destructor Documentation
Iterator()
template<class T> SIntDict< T >::Iterator::Iterator (const SIntDict< T > & dict) inline
Create an iterator given the dictionary.
Definition at line 607 of file sortdict.h.
References SIntDict< T >::Iterator::m_li, and SIntDict< T >::m_list.
~Iterator()
template<class T> virtual SIntDict< T >::Iterator::~Iterator () inline virtual
Destroys the dictionary
Definition at line 613 of file sortdict.h.
References SIntDict< T >::Iterator::m_li.
Member Function Documentation
current()
template<class T> T* SIntDict< T >::Iterator::current () const inline
Returns the current compound
Definition at line 635 of file sortdict.h.
References SIntDict< T >::Iterator::m_li.
Referenced by renderMemberIndicesAsJs(), writeAlphabeticalClassList(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeMemberList(), writeNamespaceMemberIndexFiltered(), and writeQuickMemberIndex().
operator++()
template<class T> T* SIntDict< T >::Iterator::operator++ () inline
Moves the iterator to the next element.
Returns
the new "current" element, or zero if the iterator was already pointing at the last element.
Definition at line 644 of file sortdict.h.
References SIntDict< T >::Iterator::m_li.
operator--()
template<class T> T* SIntDict< T >::Iterator::operator-- () inline
Moves the iterator to the previous element.
Returns
the new "current" element, or zero if the iterator was already pointing at the first element.
Definition at line 653 of file sortdict.h.
References SIntDict< T >::Iterator::m_li.
toFirst()
template<class T> T* SIntDict< T >::Iterator::toFirst () const inline
Set the iterator to the first element in the list.
Returns
The first compound, or zero if the list was empty.
Definition at line 621 of file sortdict.h.
References SIntDict< T >::Iterator::m_li.
Referenced by renderMemberIndicesAsJs(), writeAlphabeticalClassList(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeMemberList(), writeNamespaceMemberIndexFiltered(), and writeQuickMemberIndex().
toLast()
template<class T> T* SIntDict< T >::Iterator::toLast () const inline
Set the iterator to the last element in the list.
Returns
The first compound, or zero if the list was empty.
Definition at line 629 of file sortdict.h.
References SIntDict< T >::Iterator::m_li.
Referenced by writeMemberList().
Member Data Documentation
m_li
template<class T> QListIterator<T>* SIntDict< T >::Iterator::m_li private
Definition at line 659 of file sortdict.h.
Referenced by SIntDict< T >::Iterator::current(), SIntDict< T >::Iterator::Iterator(), SIntDict< T >::Iterator::operator++(), SIntDict< T >::Iterator::operator--(), SIntDict< T >::Iterator::toFirst(), SIntDict< T >::Iterator::toLast(), and SIntDict< T >::Iterator::~Iterator().
The documentation for this class was generated from the following file:
src/sortdict.h