Doxygen: MemberDef Class Reference
MemberDef Class Reference
A model of a class/file/namespace member symbol.
#include <memberdef.h>
Public Member Functions
MemberDef (const char *defFileName, int defLine, int defColumn, const char *type, const char *name, const char *args, const char *excp, Protection prot, Specifier virt, bool stat, Relationship related, MemberType t, const ArgumentList *tal, const ArgumentList *al)
~MemberDef ()
DefType definitionType () const
MemberDef * deepCopy () const
void moveTo (Definition *)
QCString getOutputFileBase () const
QCString getReference () const
QCString anchor () const
const char * declaration () const
const char * definition () const
const char * typeString () const
const char * argsString () const
const char * excpString () const
const char * bitfieldString () const
const char * extraTypeChars () const
const QCString & initializer () const
int initializerLines () const
uint64 getMemberSpecifiers () const
MemberList * getSectionList (Definition *d) const
QCString displayDefinition () const
ClassDef * getClassDef () const
FileDef * getFileDef () const
NamespaceDef * getNamespaceDef () const
ClassDef * accessorClass () const
const char * getReadAccessor () const
const char * getWriteAccessor () const
GroupDef * getGroupDef () const
Grouping::GroupPri_t getGroupPri () const
const char * getGroupFileName () const
int getGroupStartLine () const
bool getGroupHasDocs () const
QCString qualifiedName () const
QCString objCMethodName (bool localLink, bool showStatic) const
Protection protection () const
Specifier virtualness (int count=0) const
MemberType memberType () const
QCString memberTypeName () const
bool isSignal () const
bool isSlot () const
bool isVariable () const
bool isEnumerate () const
bool isEnumValue () const
bool isTypedef () const
bool isFunction () const
bool isFunctionPtr () const
bool isDefine () const
bool isFriend () const
bool isDCOP () const
bool isProperty () const
bool isEvent () const
bool isRelated () const
bool isForeign () const
bool isStatic () const
bool isInline () const
bool isExplicit () const
bool isMutable () const
bool isGettable () const
bool isPrivateGettable () const
bool isProtectedGettable () const
bool isSettable () const
bool isPrivateSettable () const
bool isProtectedSettable () const
bool isReadable () const
bool isWritable () const
bool isAddable () const
bool isRemovable () const
bool isRaisable () const
bool isFinal () const
bool isAbstract () const
bool isOverride () const
bool isInitonly () const
bool isOptional () const
bool isRequired () const
bool isNonAtomic () const
bool isCopy () const
bool isAssign () const
bool isRetain () const
bool isWeak () const
bool isStrong () const
bool isUnretained () const
bool isNew () const
bool isSealed () const
bool isImplementation () const
bool isExternal () const
bool isAlias () const
bool isDefault () const
bool isDelete () const
bool isNoExcept () const
bool isAttribute () const
bool isUNOProperty () const
bool isReadonly () const
bool isBound () const
bool isConstrained () const
bool isTransient () const
bool isMaybeVoid () const
bool isMaybeDefault () const
bool isMaybeAmbiguous () const
bool isPublished () const
bool isTemplateSpecialization () const
bool hasDocumentedParams () const
bool hasDocumentedReturnType () const
bool isObjCMethod () const
bool isObjCProperty () const
bool isConstructor () const
bool isDestructor () const
bool hasOneLineInitializer () const
bool hasMultiLineInitializer () const
bool protectionVisible () const
bool showInCallGraph () const
bool isStrongEnumValue () const
bool livesInsideEnum () const
bool isFriendToHide () const
bool isNotFriend () const
bool isFunctionOrSignalSlot () const
bool isRelatedOrFriend () const
bool isLinkableInProject () const
bool isLinkable () const
bool hasDocumentation () const
bool isDeleted () const
bool isBriefSectionVisible () const
bool isDetailedSectionVisible (bool inGroup, bool inFile) const
bool isDetailedSectionLinkable () const
bool isFriendClass () const
bool isDocumentedFriendClass () const
MemberDef * reimplements () const
MemberList * reimplementedBy () const
bool isReimplementedBy (ClassDef *cd) const
ClassDef * relatedAlso () const
bool hasDocumentedEnumValues () const
MemberDef * getAnonymousEnumType () const
bool isDocsForDefinition () const
MemberDef * getEnumScope () const
MemberList * enumFieldList () const
void setEnumBaseType (const QCString &type)
QCString enumBaseType () const
bool hasExamples ()
ExampleSDict * getExamples () const
bool isPrototype () const
ArgumentList * argumentList () const
ArgumentList * declArgumentList () const
ArgumentList * templateArguments () const
QList< ArgumentList > * definitionTemplateParameterLists () const
int getMemberGroupId () const
MemberGroup * getMemberGroup () const
bool fromAnonymousScope () const
bool anonymousDeclShown () const
MemberDef * fromAnonymousMember () const
bool hasCallGraph () const
bool hasCallerGraph () const
bool visibleMemberGroup (bool hideNoHeader)
MemberDef * templateMaster () const
QCString getScopeString () const
ClassDef * getClassDefOfAnonymousType ()
bool isTypedefValCached () const
ClassDef * getCachedTypedefVal () const
QCString getCachedTypedefTemplSpec () const
QCString getCachedResolvedTypedef () const
MemberDef * memberDefinition () const
MemberDef * memberDeclaration () const
MemberDef * inheritsDocsFrom () const
MemberDef * getGroupAlias () const
ClassDef * category () const
MemberDef * categoryRelation () const
QCString displayName (bool=TRUE) const
QCString getDeclType () const
void getLabels (QStrList &sl, Definition *container) const
const ArgumentList * typeConstraints () const
QCString documentation () const
QCString briefDescription (bool abbr=FALSE) const
QCString fieldType () const
bool isReference () const
void setMemberType (MemberType t)
void setDefinition (const char *d)
void setFileDef (FileDef *fd)
void setAnchor ()
void setProtection (Protection p)
void setMemberSpecifiers (uint64 s)
void mergeMemberSpecifiers (uint64 s)
void setInitializer (const char *i)
void setBitfields (const char *s)
void setMaxInitLines (int lines)
void setMemberClass (ClassDef *cd)
void setSectionList (Definition *d, MemberList *sl)
void setGroupDef (GroupDef *gd, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs, MemberDef *member=0)
void setExplicitExternal (bool b)
void setReadAccessor (const char *r)
void setWriteAccessor (const char *w)
void setTemplateSpecialization (bool b)
void makeRelated ()
void makeForeign ()
void setHasDocumentedParams (bool b)
void setHasDocumentedReturnType (bool b)
void setInheritsDocsFrom (MemberDef *md)
void setTagInfo (TagInfo *i)
void setArgsString (const char *as)
void setReimplements (MemberDef *md)
void insertReimplementedBy (MemberDef *md)
void setRelatedAlso (ClassDef *cd)
void insertEnumField (MemberDef *md)
void setEnumScope (MemberDef *md, bool livesInsideEnum=FALSE)
void setEnumClassScope (ClassDef *cd)
void setDocumentedEnumValues (bool value)
void setAnonymousEnumType (MemberDef *md)
bool addExample (const char *anchor, const char *name, const char *file)
void setPrototype (bool p)
void setArgumentList (ArgumentList *al)
void setDeclArgumentList (ArgumentList *al)
void setDefinitionTemplateParameterLists (QList< ArgumentList > *lists)
void setTypeConstraints (ArgumentList *al)
void setType (const char *t)
void setAccessorType (ClassDef *cd, const char *t)
void setNamespace (NamespaceDef *nd)
void setMemberGroup (MemberGroup *grp)
void setMemberGroupId (int id)
void makeImplementationDetail ()
void setFromAnonymousScope (bool b)
void setFromAnonymousMember (MemberDef *m)
void enableCallGraph (bool e)
void enableCallerGraph (bool e)
void setTemplateMaster (MemberDef *mt)
void addListReference (Definition *d)
void setDocsForDefinition (bool b)
void setGroupAlias (MemberDef *md)
void cacheTypedefVal (ClassDef *val, const QCString &templSpec, const QCString &resolvedType)
void invalidateTypedefValCache ()
void invalidateCachedArgumentTypes ()
void setMemberDefinition (MemberDef *md)
void setMemberDeclaration (MemberDef *md)
void setAnonymousUsed ()
void copyArgumentNames (MemberDef *bmd)
void setCategory (ClassDef *)
void setCategoryRelation (MemberDef *)
void setDocumentation (const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
void setBriefDescription (const char *b, const char *briefFile, int briefLine)
void setInbodyDocumentation (const char *d, const char *inbodyFile, int inbodyLine)
void setHidden (bool b)
void writeDeclaration (OutputList &ol, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, bool inGroup, ClassDef *inheritFrom=0, const char *inheritId=0)
void writeDocumentation (MemberList *ml, int memCount, int memTotal, OutputList &ol, const char *scopeName, Definition *container, bool inGroup, bool showEnumValues=FALSE, bool showInline=FALSE)
void writeMemberDocSimple (OutputList &ol, Definition *container)
void writeEnumDeclaration (OutputList &typeDecl, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd)
void writeTagFile (FTextStream &)
void warnIfUndocumented ()
void warnIfUndocumentedParams ()
MemberDef * createTemplateInstanceMember (ArgumentList *formalArgs, ArgumentList *actualArgs)
void findSectionsInDocumentation ()
Public Member Functions inherited from Definition
Definition (const char *defFileName, int defLine, int defColumn, const char *name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~Definition ()
const QCString & name () const
QCString localName () const
QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
int docLine () const
QCString docFile () const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
bool isHidden () const
bool isArtificial () const
QCString externalReference (const QCString &relPath) const
int getStartBodyLine () const
int getEndBodyLine () const
FileDef * getBodyDef () const
SrcLangExt getLanguage () const
Returns the programming language this definition was written in.
GroupList * partOfGroups () const
bool isLinkableViaGroup () const
QList< ListItemInfo > * xrefListItems () const
virtual Definition * findInnerCompound (const char *name)
virtual Definition * getOuterScope () const
MemberSDict * getReferencesMembers () const
MemberSDict * getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
returns TRUE if this class has a brief description
QCString id () const
virtual void setName (const char *name)
void setId (const char *name)
void setReference (const char *r)
void addSectionsToDefinition (QList< SectionInfo > *anchorList)
void setBodySegment (int bls, int ble)
void setBodyDef (FileDef *fd)
void addSourceReferencedBy (MemberDef *d)
void addSourceReferences (MemberDef *d)
void setRefItems (const QList< ListItemInfo > *sli)
void mergeRefItems (Definition *d)
virtual void addInnerCompound (Definition *d)
virtual void setOuterScope (Definition *d)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const char *scopeName)
void writeInlineCode (OutputList &ol, const char *scopeName)
void writeSourceRefs (OutputList &ol, const char *scopeName)
void writeSourceReffedBy (OutputList &ol, const char *scopeName)
void makePartOfGroup (GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
virtual void writeQuickMemberLinks (OutputList &, MemberDef *) const
virtual void writeSummaryLinks (OutputList &)
QCString pathFragment () const
void writeDocAnchorsToTagFile (FTextStream &)
void setLocalName (const QCString name)
void addSectionsToIndex ()
void writeToc (OutputList &ol)
void setCookie (Cookie *cookie)
Cookie * cookie () const
Public Member Functions inherited from DefinitionIntf
DefinitionIntf ()
virtual ~DefinitionIntf ()
Public Attributes
bool visited
Protected Member Functions
void flushToDisk () const
void loadFromDisk () const
Protected Member Functions inherited from Definition
Definition (const Definition &d)
Private Member Functions
void lock () const
void unlock () const
void saveToDisk () const
void makeResident () const
void _computeLinkableInProject ()
void _computeIsConstructor ()
void _computeIsDestructor ()
void _writeGroupInclude (OutputList &ol, bool inGroup)
void _writeCallGraph (OutputList &ol)
void _writeCallerGraph (OutputList &ol)
void _writeReimplements (OutputList &ol)
void _writeReimplementedBy (OutputList &ol)
void _writeExamples (OutputList &ol)
void _writeTypeConstraints (OutputList &ol)
void _writeEnumValues (OutputList &ol, Definition *container, const QCString &cfname, const QCString &ciname, const QCString &cname)
void _writeCategoryRelation (OutputList &ol)
void _writeTagData (const DefType)
void _addToSearchIndex ()
MemberDef (const MemberDef &)
MemberDef & operator= (const MemberDef &)
void writeLink (OutputList &ol, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, bool onlyText=FALSE)
Private Attributes
MemberDefImpl * m_impl
uchar m_isLinkableCached
uchar m_isConstructorCached
uchar m_isDestructorCached
Static Private Attributes
static int s_indentLevel = 0
Additional Inherited Members
Public Types inherited from DefinitionIntf
enum DefType {
TypeClass = 0, TypeFile = 1, TypeNamespace = 2, TypeMember = 3,
TypeGroup = 4, TypePackage = 5, TypePage = 6, TypeDir = 7,
TypeSymbolList = 8
}
Detailed Description
A model of a class/file/namespace member symbol.
Definition at line 43 of file memberdef.h.
Constructor & Destructor Documentation
MemberDef() [1/2]
MemberDef::MemberDef (const char * df, int dl, int dc, const char * t, const char * na, const char * a, const char * e, Protection p, Specifier v, bool s, Relationship r, MemberType mt, const ArgumentList * tal, const ArgumentList * al)
Creates a new member definition.
Parameters
df File containing the definition of this member.
dl Line at which the member definition was found.
dc Column at which the member definition was found.
t A string representing the type of the member.
na A string representing the name of the member.
a A string representing the arguments of the member.
e A string representing the throw clause of the members.
p The protection context of the member, possible values are: Public, Protected, Private.
v The degree of `virtualness' of the member, possible values are: Normal, Virtual, Pure.
s A boolean that is true iff the member is static.
r The relationship between the class and the member.
mt The kind of member. See MemberType for a list of all types.
tal The template arguments of this member.
al The arguments of this member. This is a structured form of the string past as argument a.
Definition at line 744 of file memberdef.cpp.
References MemberDefImpl::init(), m_impl, m_isConstructorCached, m_isDestructorCached, and m_isLinkableCached.
Referenced by addInstance(), createTemplateInstanceMember(), and deepCopy().
~MemberDef()
MemberDef::~MemberDef ()
Destroys the member definition.
Definition at line 861 of file memberdef.cpp.
References m_impl.
MemberDef() [2/2]
MemberDef::MemberDef (const MemberDef & md) private
Definition at line 758 of file memberdef.cpp.
References m_impl, m_isConstructorCached, m_isDestructorCached, and m_isLinkableCached.
Member Function Documentation
_addToSearchIndex()
void MemberDef::_addToSearchIndex () private
Definition at line 4921 of file memberdef.cpp.
References SearchIndexIntf::addWord(), anchor(), displayName(), getClassDef(), getNamespaceDef(), isLinkableInProject(), Definition::localName(), qualifiedName(), Doxygen::searchIndex, and SearchIndexIntf::setCurrentDoc().
Referenced by writeDeclaration(), and writeEnumDeclaration().
_computeIsConstructor()
void MemberDef::_computeIsConstructor () private
Definition at line 3688 of file memberdef.cpp.
References MemberDefImpl::classDef, Definition::getLanguage(), MemberDefImpl::isDMember, Definition::localName(), m_impl, m_isConstructorCached, Definition::name(), SrcLangExt_PHP, SrcLangExt_Python, and SrcLangExt_Tcl.
Referenced by isConstructor().
_computeIsDestructor()
void MemberDef::_computeIsDestructor () private
Definition at line 3743 of file memberdef.cpp.
References Definition::getLanguage(), isDestructor(), MemberDefImpl::isDMember, m_impl, m_isDestructorCached, Definition::name(), SrcLangExt_PHP, SrcLangExt_Python, and SrcLangExt_Tcl.
Referenced by isDestructor().
_computeLinkableInProject()
void MemberDef::_computeLinkableInProject () private
Definition at line 1062 of file memberdef.cpp.
References MemberDefImpl::classDef, Config_getBool, MemberDefImpl::fileDef, MemberDefImpl::group, hasDocumentation(), Definition::isHidden(), GroupDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), FileDef::isLinkableInProject(), ClassDef::isLinkableInProject(), isLinkableInProject(), isReference(), m_impl, m_isLinkableCached, MemberType_Friend, MemberDefImpl::mtype, Definition::name(), MemberDefImpl::nspace, MemberDefImpl::prot, protectionLevelVisible(), MemberDefImpl::related, MemberDefImpl::stat, and MemberDefImpl::templateMaster.
Referenced by isLinkableInProject().
_writeCallerGraph()
void MemberDef::_writeCallerGraph (OutputList & ol) private
Definition at line 2096 of file memberdef.cpp.
References Config_getBool, OutputList::disable(), OutputList::enableAll(), OutputList::endCallGraph(), MemberDefImpl::hasCallerGraph, isFunction(), isSignal(), isSlot(), DotCallGraph::isTooBig(), DotCallGraph::isTrivial(), m_impl, OutputGenerator::Man, msg(), OutputList::parseText(), qualifiedName(), OutputList::startCallGraph(), theTranslator, Translator::trCallerGraph(), and warn_uncond().
Referenced by writeDocumentation().
_writeCallGraph()
void MemberDef::_writeCallGraph (OutputList & ol) private
Definition at line 2072 of file memberdef.cpp.
References Config_getBool, OutputList::disable(), OutputList::enableAll(), OutputList::endCallGraph(), MemberDefImpl::hasCallGraph, isFunction(), isSignal(), isSlot(), DotCallGraph::isTooBig(), DotCallGraph::isTrivial(), m_impl, OutputGenerator::Man, msg(), OutputList::parseText(), qualifiedName(), OutputList::startCallGraph(), theTranslator, Translator::trCallGraph(), and warn_uncond().
Referenced by writeDocumentation().
_writeCategoryRelation()
void MemberDef::_writeCategoryRelation (OutputList & ol) private
Definition at line 2253 of file memberdef.cpp.
References anchor(), MemberDefImpl::category, ClassDef::categoryOf(), MemberDefImpl::categoryRelation, MemberDefImpl::classDef, ClassDef::displayName(), OutputList::endParagraph(), getOutputFileBase(), getReference(), isLinkable(), m_impl, Definition::name(), OutputList::parseText(), OutputList::startParagraph(), theTranslator, Translator::trExtendsClass(), Translator::trProvidedByCategory(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
_writeEnumValues()
void MemberDef::_writeEnumValues (OutputList & ol, Definition * container, const QCString & cfname, const QCString & ciname, const QCString & cname) private
Definition at line 2327 of file memberdef.cpp.
References IndexList::addIndexItem(), OutputList::addIndexItem(), anchor(), argsString(), briefDescription(), Definition::briefFile(), Definition::briefLine(), OutputList::disableAllBut(), Definition::docFile(), OutputList::docify(), Definition::docLine(), documentation(), OutputList::enableAll(), OutputList::endDescTable(), OutputList::endDescTableData(), OutputList::endDescTableRow(), OutputList::endDescTableTitle(), OutputList::endDoxyAnchor(), enumFieldList(), OutputList::generateDoc(), Definition::getOuterScope(), Doxygen::indexList, isEnumerate(), isLinkable(), OutputGenerator::Man, Definition::name(), OutputList::startDescTable(), OutputList::startDescTableData(), OutputList::startDescTableRow(), OutputList::startDescTableTitle(), OutputList::startDoxyAnchor(), theTranslator, Translator::trEnumerationValues(), and OutputList::writeString().
Referenced by writeDocumentation().
_writeExamples()
void MemberDef::_writeExamples (OutputList & ol) private
Definition at line 2306 of file memberdef.cpp.
References OutputList::endDescForItem(), OutputList::endSimpleSect(), BaseOutputDocInterface::Examples, MemberDefImpl::exampleSDict, hasExamples(), m_impl, OutputList::startDescForItem(), OutputList::startSimpleSect(), theTranslator, Translator::trExamples(), and writeExample().
Referenced by writeDocumentation().
_writeGroupInclude()
void MemberDef::_writeGroupInclude (OutputList & ol, bool inGroup) private
Definition at line 2497 of file memberdef.cpp.
References FileDef::anchor(), Config_getBool, OutputList::docify(), FileDef::docName(), OutputList::endParagraph(), OutputList::endTypewriter(), getFileDef(), Definition::getLanguage(), FileDef::getOutputFileBase(), Definition::getReference(), FileDef::isLinkable(), SrcLangExt_IDL, SrcLangExt_Java, OutputList::startParagraph(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
_writeReimplementedBy()
void MemberDef::_writeReimplementedBy (OutputList & ol) private
Definition at line 2178 of file memberdef.cpp.
References anchor(), MemberDefImpl::classDef, ClassDef::compoundType(), ClassDef::displayName(), OutputList::endParagraph(), getClassDef(), getOutputFileBase(), getReference(), ClassDef::Interface, ClassDef::isLinkable(), isLinkable(), isLinkableInProject(), m_impl, OutputList::parseText(), Pure, reimplementedBy(), OutputList::startParagraph(), theTranslator, Translator::trImplementedInList(), Translator::trReimplementedInList(), MemberDefImpl::virt, OutputList::writeObjectLink(), and writePageRef().
Referenced by writeDocumentation().
_writeReimplements()
void MemberDef::_writeReimplements (OutputList & ol) private
Definition at line 2119 of file memberdef.cpp.
References anchor(), ClassDef::anchor(), ClassDef::compoundType(), ClassDef::displayName(), OutputList::endParagraph(), err(), getClassDef(), getOutputFileBase(), ClassDef::getOutputFileBase(), getReference(), ClassDef::getReference(), ClassDef::Interface, ClassDef::isLinkable(), isLinkable(), ClassDef::isLinkableInProject(), isLinkableInProject(), OutputList::parseText(), Pure, reimplements(), OutputList::startParagraph(), theTranslator, Translator::trImplementedFromList(), Translator::trReimplementedFromList(), virtualness(), OutputList::writeObjectLink(), and writePageRef().
Referenced by writeDocumentation().
_writeTagData()
void MemberDef::_writeTagData (const DefType) private
_writeTypeConstraints()
void MemberDef::_writeTypeConstraints (OutputList & ol) private
Definition at line 2319 of file memberdef.cpp.
References m_impl, MemberDefImpl::typeConstraints, and writeTypeConstraints().
Referenced by writeDocumentation().
accessorClass()
ClassDef * MemberDef::accessorClass () const
Definition at line 3942 of file memberdef.cpp.
References MemberDefImpl::accessorClass, and m_impl.
addExample()
bool MemberDef::addExample (const char * anchor, const char * name, const char * file)
Definition at line 923 of file memberdef.cpp.
References Example::anchor, anchor(), MemberDefImpl::exampleSDict, Example::file, SDict< T >::find(), SDict< T >::inSort(), m_impl, and Example::name.
Referenced by deepCopy().
addListReference()
void MemberDef::addListReference (Definition * d)
Definition at line 3510 of file memberdef.cpp.
References addRefItem(), anchor(), argsString(), Config_getBool, DefinitionIntf::definitionType(), Definition::getLanguage(), getLanguageSpecificSeparator(), Definition::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, isLinkableInProject(), isObjCMethod(), isRelated(), Definition::name(), qualifiedName(), SrcLangExt_Fortran, theTranslator, Translator::trGlobal(), Translator::trMember(), Translator::trSubprogram(), DefinitionIntf::TypeClass, visited, and Definition::xrefListItems().
Referenced by MemberList::addListReferences().
anchor()
QCString MemberDef::anchor () const virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 1039 of file memberdef.cpp.
References MemberDefImpl::anc, anchor(), MemberDefImpl::enumScope, getReference(), MemberDefImpl::group, MemberDefImpl::groupAlias, MemberDefImpl::groupMember, m_impl, and MemberDefImpl::templateMaster.
Referenced by _addToSearchIndex(), _writeCategoryRelation(), _writeEnumValues(), _writeReimplementedBy(), _writeReimplements(), Definition::_writeSourceRefList(), addExample(), Qhp::addIndexItem(), DocSets::addIndexItem(), HtmlHelp::addIndexItem(), addListReference(), DotGroupCollaboration::addMemberList(), addMembersToIndex(), anchor(), DotCallGraph::buildGraph(), DotCallGraph::DotCallGraph(), dumpSymbol(), generateDEFForMember(), generateDocbookForMember(), generateXMLForMember(), getOutputFileBase(), handleLinkedWord(), linkifyText(), resolveLink(), validatingParseDoc(), HtmlDocVisitor::visit(), writeClassLinkForMember(), writeColumn(), writeDeclaration(), ClassDef::writeDeclaration(), writeDocumentation(), writeFileLinkForMember(), writeGroupTreeNode(), writeLink(), writeLink(), writeListOfAllMembers(), writeMemberDocSimple(), ClassDef::writeMemberList(), writeMemberReference(), writeNamespaceLinkForMember(), MemberList::writePlainDeclarations(), NamespaceDef::writeQuickMemberLinks(), GroupDef::writeQuickMemberLinks(), FileDef::writeQuickMemberLinks(), ClassDef::writeQuickMemberLinks(), VhdlDocGen::writeTagFile(), writeTagFile(), and VhdlDocGen::writeVHDLDeclaration().
anonymousDeclShown()
bool MemberDef::anonymousDeclShown () const
Definition at line 4576 of file memberdef.cpp.
References MemberDefImpl::annUsed, and m_impl.
Referenced by MemberList::writePlainDeclarations().
argsString()
const char * MemberDef::argsString () const
Definition at line 4069 of file memberdef.cpp.
References MemberDefImpl::args, and m_impl.
Referenced by _writeEnumValues(), addListReference(), addVariableToFile(), combineDeclarationAndDefinition(), MemberList::countDecMembers(), createTagLessInstance(), MemberContext::Private::declArgs(), findMember(), findUsedClassesForClass(), findUsingDeclImports(), generateDEFForMember(), generateDocbookForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getResolvedSymbol(), isFunctionPtr(), resolveTypeDef(), SymbolContext::Private::scope(), setGlobalType(), warnIfUndocumented(), writeColumn(), writeDeclaration(), writeDocumentation(), writeJavascriptSearchIndex(), writeMemberDocSimple(), ClassDef::writeMemberList(), VhdlDocGen::writeTagFile(), writeTagFile(), writeUCFLink(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLTypeDocumentation().
argumentList()
ArgumentList * MemberDef::argumentList () const
Definition at line 4541 of file memberdef.cpp.
References MemberDefImpl::defArgList, and m_impl.
Referenced by addMemberDocs(), checkArgumentName(), checkUndocumentedParams(), combineDeclarationAndDefinition(), computeMemberRelations(), copyArgumentNames(), detectNoDocumentedParams(), findFriends(), VhdlDocGen::findFunction(), findGlobalMember(), findMember(), findMembersWithSpecificName(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), MemberContext::Private::getDefArgList(), getDefs(), GroupDef::insertMember(), ClassDef::mergeMembers(), MemberContext::Private::paramDocs(), transferFunctionReferences(), transferRelatedFunctionDocumentation(), writeDefArgumentList(), writeDocumentation(), VhdlDocGen::writeTagFile(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLTypeDocumentation().
bitfieldString()
const char * MemberDef::bitfieldString () const
Definition at line 4079 of file memberdef.cpp.
References MemberDefImpl::bitfields, and m_impl.
Referenced by MemberContext::Private::bitfields(), createTagLessInstance(), findUsingDeclImports(), and generateXMLForMember().
briefDescription()
QCString MemberDef::briefDescription (bool abbreviate = FALSE) const virtual
Returns the brief description of this definition. This can include commands.
Reimplemented from Definition.
Definition at line 5102 of file memberdef.cpp.
References Definition::briefDescription(), briefDescription(), m_impl, and MemberDefImpl::templateMaster.
Referenced by _writeEnumValues(), ClassDef::addMembersToTemplateInstance(), briefDescription(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findDefineDocumentation(), findDocsForMemberOrCompound(), findEnumDocumentation(), findFriends(), findUsingDeclImports(), generateDEFForMember(), generateDocbookForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), DocPara::handleInheritDoc(), inheritDocumentation(), isDetailedSectionLinkable(), writeDeclaration(), writeDocumentation(), writeMemberDocSimple(), MemberList::writePlainDeclarations(), and VhdlDocGen::writeVHDLDeclaration().
cacheTypedefVal()
void MemberDef::cacheTypedefVal (ClassDef * val, const QCString & templSpec, const QCString & resolvedType)
Definition at line 4856 of file memberdef.cpp.
References MemberDefImpl::cachedResolvedType, MemberDefImpl::cachedTypedefTemplSpec, MemberDefImpl::cachedTypedefValue, MemberDefImpl::isTypedefValCached, and m_impl.
Referenced by newResolveTypedef().
category()
ClassDef * MemberDef::category () const
Definition at line 4825 of file memberdef.cpp.
References MemberDefImpl::category, and m_impl.
Referenced by MemberContext::Private::category(), and ClassDef::writeMemberList().
categoryRelation()
MemberDef * MemberDef::categoryRelation () const
Definition at line 4835 of file memberdef.cpp.
References MemberDefImpl::categoryRelation, and m_impl.
Referenced by MemberContext::Private::categoryRelation().
copyArgumentNames()
void MemberDef::copyArgumentNames (MemberDef * bmd)
Definition at line 4865 of file memberdef.cpp.
References argumentList(), MemberDefImpl::declArgList, declArgumentList(), MemberDefImpl::defArgList, m_impl, and Argument::name.
Referenced by inheritDocumentation().
createTemplateInstanceMember()
MemberDef * MemberDef::createTemplateInstanceMember (ArgumentList * formalArgs, ArgumentList * actualArgs)
Definition at line 3435 of file memberdef.cpp.
References MemberDefImpl::args, ArgumentList::deepCopy(), MemberDefImpl::def, MemberDefImpl::defArgList, MemberDefImpl::exception, Definition::getBodyDef(), Definition::getDefColumn(), Definition::getDefFileName(), Definition::getDefLine(), Definition::getEndBodyLine(), Definition::getStartBodyLine(), m_impl, MemberDef(), MemberDefImpl::mtype, Definition::name(), MemberDefImpl::prot, MemberDefImpl::related, setArgumentList(), Definition::setBodyDef(), Definition::setBodySegment(), setDefinition(), MemberDefImpl::stat, substituteTemplateArgumentsInString(), ArgumentList::trailingReturnType, Argument::type, MemberDefImpl::type, and MemberDefImpl::virt.
Referenced by ClassDef::addMembersToTemplateInstance().
declaration()
const char * MemberDef::declaration () const
Definition at line 4049 of file memberdef.cpp.
References MemberDefImpl::decl, and m_impl.
Referenced by findGlobalMember(), generateDocbookForMember(), and TooltipManager::writeTooltips().
declArgumentList()
ArgumentList * MemberDef::declArgumentList () const
Definition at line 4546 of file memberdef.cpp.
References MemberDefImpl::declArgList, and m_impl.
Referenced by checkArgumentName(), checkUndocumentedParams(), copyArgumentNames(), detectNoDocumentedParams(), generateDocbookForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), MemberContext::Private::getDefArgList(), and writeDefArgumentList().
deepCopy()
MemberDef * MemberDef::deepCopy () const
Definition at line 766 of file memberdef.cpp.
References addExample(), Example::anchor, SDict< T >::append(), MemberDefImpl::classSectionSDict, MemberDefImpl::declArgList, ArgumentList::deepCopy(), MemberDefImpl::defArgList, MemberDefImpl::defTmpArgLists, MemberDefImpl::enumFields, MemberDefImpl::exampleSDict, Example::file, insertEnumField(), insertReimplementedBy(), SDict< Example >::Iterator, m_impl, MemberDef(), Example::name, MemberDefImpl::redefinedBy, setDefinitionTemplateParameterLists(), MemberDefImpl::tArgList, and MemberDefImpl::typeConstraints.
Referenced by ClassDef::mergeCategory().
definition()
const char * MemberDef::definition () const
Definition at line 4054 of file memberdef.cpp.
References MemberDefImpl::def, and m_impl.
Referenced by displayDefinition(), findUsingDeclImports(), generateDocbookForMember(), generateXMLForMember(), setAnchor(), and writeDocumentation().
definitionTemplateParameterLists()
QList< ArgumentList > * MemberDef::definitionTemplateParameterLists () const
Definition at line 4556 of file memberdef.cpp.
References MemberDefImpl::defTmpArgLists, and m_impl.
Referenced by MemberContext::Private::addTemplateDecls().
definitionType()
DefType MemberDef::definitionType () const inline virtual
Use this for dynamic inspection of the type of the derived class
Implements DefinitionIntf.
Definition at line 53 of file memberdef.h.
References DefinitionIntf::TypeMember.
Referenced by isAccessibleFrom().
displayDefinition()
QCString MemberDef::displayDefinition () const
Definition at line 2418 of file memberdef.cpp.
References definition(), MemberDefImpl::enumBaseType, getClassDef(), Definition::getLanguage(), getLanguageSpecificSeparator(), isEnumerate(), isEnumValue(), isId(), ClassDef::isObjectiveC(), isStatic(), m_impl, Definition::name(), and substitute().
Referenced by MemberContext::Private::definition().
displayName()
QCString MemberDef::displayName (bool includeScope = TRUE) const virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 4916 of file memberdef.cpp.
References Definition::name().
Referenced by _addToSearchIndex(), MemberContext::Private::handleNameWithContextFor(), and writeLink().
documentation()
QCString MemberDef::documentation () const virtual
Returns the detailed description of this definition
Reimplemented from Definition.
Definition at line 5114 of file memberdef.cpp.
References Definition::documentation(), documentation(), m_impl, and MemberDefImpl::templateMaster.
Referenced by _writeEnumValues(), ClassDef::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), documentation(), findDefineDocumentation(), findDocsForMemberOrCompound(), findEnumDocumentation(), findFriends(), findSectionsInDocumentation(), findUsingDeclImports(), generateDEFForMember(), generateDocbookForMember(), generateDocbookSection(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), DocPara::handleInheritDoc(), inheritDocumentation(), isBriefSectionVisible(), isDetailedSectionLinkable(), writeDocumentation(), writeMemberDocSimple(), and VhdlDocGen::writeSource().
enableCallerGraph()
void MemberDef::enableCallerGraph (bool e)
Definition at line 3958 of file memberdef.cpp.
References MemberDefImpl::hasCallerGraph, m_impl, and Doxygen::parseSourcesNeeded.
Referenced by addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addVariableToClass(), buildFunctionList(), combineDeclarationAndDefinition(), findEnums(), findFriends(), findMember(), and findUsingDeclImports().
enableCallGraph()
void MemberDef::enableCallGraph (bool e)
Definition at line 3952 of file memberdef.cpp.
References MemberDefImpl::hasCallGraph, m_impl, and Doxygen::parseSourcesNeeded.
Referenced by addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addVariableToClass(), buildFunctionList(), combineDeclarationAndDefinition(), findEnums(), findFriends(), findMember(), and findUsingDeclImports().
enumBaseType()
QCString MemberDef::enumBaseType () const
Definition at line 4850 of file memberdef.cpp.
References MemberDefImpl::enumBaseType, and m_impl.
Referenced by MemberContext::Private::enumBaseType().
enumFieldList()
MemberList * MemberDef::enumFieldList () const
Definition at line 4526 of file memberdef.cpp.
References MemberDefImpl::enumFields, and m_impl.
Referenced by _writeEnumValues(), MemberList::addListReferences(), addMembersToIndex(), addMembersToMemberGroup(), MemberContext::Private::enumValues(), findDEV(), generateDEFForMember(), generateDocbookForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getDefs(), writeGroupTreeNode(), and MemberList::writeTagFile().
excpString()
const char * MemberDef::excpString () const
Definition at line 4074 of file memberdef.cpp.
References MemberDefImpl::exception, and m_impl.
Referenced by createTagLessInstance(), MemberContext::Private::exception(), findUsingDeclImports(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), writeDeclaration(), writeDocumentation(), writeExceptionList(), and VhdlDocGen::writeFunctionProto().
extraTypeChars()
const char * MemberDef::extraTypeChars () const
Definition at line 4059 of file memberdef.cpp.
References MemberDefImpl::extraTypeChars, and m_impl.
Referenced by MemberContext::Private::extraTypeChars(), and writeDefArgumentList().
fieldType()
QCString MemberDef::fieldType () const
Definition at line 3083 of file memberdef.cpp.
References MemberDefImpl::accessorType, isTypedef(), m_impl, simplifyTypeForTable(), and MemberDefImpl::type.
Referenced by MemberContext::Private::fieldType(), and writeMemberDocSimple().
findSectionsInDocumentation()
void MemberDef::findSectionsInDocumentation ()
Definition at line 3947 of file memberdef.cpp.
References Definition::docFile(), docFindSections(), and documentation().
Referenced by MemberList::findSectionsInDocumentation().
flushToDisk()
void MemberDef::flushToDisk () const protected
fromAnonymousMember()
MemberDef * MemberDef::fromAnonymousMember () const
Definition at line 4789 of file memberdef.cpp.
References MemberDefImpl::annMemb, and m_impl.
Referenced by MemberContext::Private::anonymousMember().
fromAnonymousScope()
bool MemberDef::fromAnonymousScope () const
Definition at line 4571 of file memberdef.cpp.
References MemberDefImpl::annScope, and m_impl.
Referenced by MemberList::writePlainDeclarations().
getAnonymousEnumType()
MemberDef * MemberDef::getAnonymousEnumType () const
Definition at line 4506 of file memberdef.cpp.
References MemberDefImpl::annEnumType, and m_impl.
Referenced by writeDeclaration().
getCachedResolvedTypedef()
QCString MemberDef::getCachedResolvedTypedef () const
Definition at line 4616 of file memberdef.cpp.
References MemberDefImpl::cachedResolvedType, and m_impl.
Referenced by newResolveTypedef().
getCachedTypedefTemplSpec()
QCString MemberDef::getCachedTypedefTemplSpec () const
Definition at line 4611 of file memberdef.cpp.
References MemberDefImpl::cachedTypedefTemplSpec, and m_impl.
Referenced by newResolveTypedef().
getCachedTypedefVal()
ClassDef * MemberDef::getCachedTypedefVal () const
Definition at line 4606 of file memberdef.cpp.
References MemberDefImpl::cachedTypedefValue, and m_impl.
Referenced by flushCachedTemplateRelations(), and newResolveTypedef().
getClassDef()
ClassDef * MemberDef::getClassDef () const
Definition at line 4099 of file memberdef.cpp.
References MemberDefImpl::classDef, and m_impl.
Referenced by _addToSearchIndex(), _writeReimplementedBy(), _writeReimplements(), addClassMemberNameToIndex(), addEnumValuesToEnums(), DocSets::addIndexItem(), PerlModGenerator::addListOfAllMembers(), addMemberDocs(), addMemberToSearchIndex(), MemberContext::Private::addTemplateDecls(), addVariableToClass(), MemberName::compareValues(), MemberNameInfo::compareValues(), computeMemberRelations(), MemberList::countDecMembers(), displayDefinition(), DocRef::DocRef(), findEnumDocumentation(), findMember(), generateDEFForMember(), generateDocbookForMember(), generateXMLForMember(), MemberContext::Private::getClass(), getClassDefOfAnonymousType(), getDefs(), ClassDef::getMemberByName(), ClassMembersIndexContext::Private::getMembersFiltered(), getScopeString(), handleLinkedWord(), MemberContext::Private::handleNameWithContextFor(), MemberContext::Private::implementedBy(), MemberContext::Private::implements(), MemberContext::Private::initializerAsCode(), NamespaceDef::insertMember(), GroupDef::insertMember(), FileDef::insertMember(), ClassDef::isAccessibleMember(), isBriefSectionVisible(), isDetailedSectionLinkable(), isDetailedSectionVisible(), isReimplementedBy(), ClassDef::mergeMembers(), newResolveTypedef(), AllMembersListContext::Private::Private(), MemberContext::Private::reimplementedBy(), MemberContext::Private::reimplements(), SymbolContext::Private::scope(), MemberContext::Private::sourceCode(), warnIfUndocumented(), writeBoxMemberList(), writeClassLinkForMember(), writeDeclaration(), writeDocumentation(), writeJavascriptSearchIndex(), ClassDef::writeMemberList(), writeMemberTemplateLists(), ClassDef::writeQuickMemberLinks(), and VhdlDocGen::writeStringLink().
getClassDefOfAnonymousType()
ClassDef * MemberDef::getClassDefOfAnonymousType ()
If this member has an anonymous class/struct/union as its type, then this method will return the ClassDef that describes this return type.
Definition at line 1244 of file memberdef.cpp.
References MemberDefImpl::cachedAnonymousType, getClass(), getClassDef(), getNamespaceDef(), isId(), m_impl, Definition::name(), stripAnonymousNamespaceScope(), and MemberDefImpl::type.
Referenced by addMemberToGroups(), MemberContext::Private::anonymousType(), ClassDef::setGroupDefForAllMembers(), writeDeclaration(), and VhdlDocGen::writeVHDLDeclaration().
getDeclType()
QCString MemberDef::getDeclType () const
Definition at line 1391 of file memberdef.cpp.
References isAlias(), isObjCMethod(), m_impl, MemberType_Typedef, MemberDefImpl::mtype, and MemberDefImpl::type.
Referenced by MemberContext::Private::declType().
getEnumScope()
MemberDef * MemberDef::getEnumScope () const
Definition at line 4516 of file memberdef.cpp.
References MemberDefImpl::enumScope, and m_impl.
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), addNamespaceMemberNameToIndex(), getDefs(), getOutputFileBase(), MemberContext::Private::handleNameWithContextFor(), and writeLink().
getExamples()
ExampleSDict * MemberDef::getExamples () const
Definition at line 4531 of file memberdef.cpp.
References MemberDefImpl::exampleSDict, and m_impl.
Referenced by MemberContext::Private::addExamples().
getFileDef()
FileDef * MemberDef::getFileDef () const
Definition at line 4104 of file memberdef.cpp.
References MemberDefImpl::fileDef, and m_impl.
Referenced by _writeGroupInclude(), addEnumValuesToEnums(), addFileMemberNameToIndex(), Qhp::addIndexItem(), DocSets::addIndexItem(), HtmlHelp::addIndexItem(), addMemberDocs(), addMemberToSearchIndex(), addVariableToFile(), combineDeclarationAndDefinition(), MemberName::compareValues(), MemberNameInfo::compareValues(), computeMemberRelations(), VhdlDocGen::createFlowChart(), findDefineDocumentation(), findFriends(), findGlobalMember(), findMember(), findMembersWithSpecificName(), getDefs(), MemberContext::Private::getFile(), GlobalsIndexContext::Private::getMembersFiltered(), GroupDef::insertMember(), ClassDef::mergeMembers(), SymbolContext::Private::scope(), transferFunctionReferences(), transferRelatedFunctionDocumentation(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), writeFileLinkForMember(), writeJavascriptSearchIndex(), writeMemberTemplateLists(), FileDef::writeQuickMemberLinks(), and VhdlDocGen::writeSource().
getGroupAlias()
MemberDef * MemberDef::getGroupAlias () const
Definition at line 4637 of file memberdef.cpp.
References MemberDefImpl::groupAlias, and m_impl.
Referenced by GroupDef::insertMember().
getGroupDef()
GroupDef * MemberDef::getGroupDef () const
Definition at line 4124 of file memberdef.cpp.
References MemberDefImpl::group, and m_impl.
Referenced by Qhp::addIndexItem(), DocSets::addIndexItem(), HtmlHelp::addIndexItem(), PerlModGenerator::addListOfAllMembers(), MemberList::addListReferences(), addMemberToGroups(), addMemberToSearchIndex(), combineDeclarationAndDefinition(), findEnumDocumentation(), findMembersWithSpecificName(), generateDocbookForMember(), generateXMLForMember(), getDefs(), MemberGroup::insertMember(), isDetailedSectionVisible(), setEnumScope(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), writeLink(), and GroupDef::writeQuickMemberLinks().
getGroupFileName()
const char * MemberDef::getGroupFileName () const
Definition at line 4134 of file memberdef.cpp.
References MemberDefImpl::groupFileName, and m_impl.
Referenced by addMemberToGroups(), MemberGroup::insertMember(), and setEnumScope().
getGroupHasDocs()
bool MemberDef::getGroupHasDocs () const
Definition at line 4144 of file memberdef.cpp.
References MemberDefImpl::groupHasDocs, and m_impl.
Referenced by addMemberToGroups(), MemberGroup::insertMember(), and setEnumScope().
getGroupPri()
Grouping::GroupPri_t MemberDef::getGroupPri () const
Definition at line 4129 of file memberdef.cpp.
References MemberDefImpl::grouppri, and m_impl.
Referenced by addMemberToGroups(), combineDeclarationAndDefinition(), MemberGroup::insertMember(), and setEnumScope().
getGroupStartLine()
int MemberDef::getGroupStartLine () const
Definition at line 4139 of file memberdef.cpp.
References MemberDefImpl::groupStartLine, and m_impl.
Referenced by addMemberToGroups(), MemberGroup::insertMember(), and setEnumScope().
getLabels()
void MemberDef::getLabels (QStrList & sl, Definition * container) const
Definition at line 1955 of file memberdef.cpp.
References MemberDefImpl::classDef, Config_getBool, DefinitionIntf::definitionType(), Definition::getLanguage(), getMemberSpecifiers(), Entry::Inline, isAbstract(), isAddable(), isAssign(), isAttribute(), isBound(), isConstrained(), isCopy(), isDefault(), isDelete(), isExplicit(), isFinal(), isFriend(), isGettable(), isImplementation(), isInitonly(), isInline(), isMaybeAmbiguous(), isMaybeDefault(), isMaybeVoid(), isMutable(), isNew(), isNoExcept(), isNonAtomic(), isObjCMethod(), isObjCProperty(), isOptional(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProtectedGettable(), isProtectedSettable(), isPublished(), isRaisable(), isReadable(), isReadonly(), isRelated(), isRemovable(), isRequired(), isRetain(), isSealed(), isSettable(), isSignal(), isSlot(), isStatic(), isStrong(), isTransient(), isUNOProperty(), isUnretained(), isWeak(), isWritable(), m_impl, MemberDefImpl::memSpec, Normal, Package, Private, Protected, protection(), Public, Pure, SrcLangExt_VHDL, VhdlDocGen::trTypeString(), DefinitionIntf::TypeClass, Virtual, and virtualness().
Referenced by MemberContext::Private::labels(), and writeDocumentation().
getMemberGroup()
MemberGroup * MemberDef::getMemberGroup () const
Definition at line 4566 of file memberdef.cpp.
References m_impl, and MemberDefImpl::memberGroup.
getMemberGroupId()
int MemberDef::getMemberGroupId () const
Definition at line 4561 of file memberdef.cpp.
References MemberDefImpl::grpId, and m_impl.
Referenced by addMemberDocs(), addMembersToMemberGroup(), ClassDef::addMembersToTemplateInstance(), createTagLessInstance(), and findEnumDocumentation().
getMemberSpecifiers()
uint64 MemberDef::getMemberSpecifiers () const
Definition at line 4094 of file memberdef.cpp.
References m_impl, and MemberDefImpl::memSpec.
Referenced by ClassDef::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), createTagLessInstance(), findUsingDeclImports(), getLabels(), getPorts(), ClassDef::internalInsertMember(), VhdlDocGen::isAlias(), VhdlDocGen::isArchitecture(), VhdlDocGen::isAttribute(), VhdlDocGen::isCompInst(), VhdlDocGen::isComponent(), VhdlDocGen::isConfig(), VhdlDocGen::isConstant(), VhdlDocGen::isConstraint(), VhdlDocGen::isEntity(), VhdlDocGen::isFile(), VhdlDocGen::isGeneric(), VhdlDocGen::isGroup(), VhdlDocGen::isLibrary(), VhdlDocGen::isMisc(), VhdlDocGen::isPackage(), VhdlDocGen::isPackageBody(), VhdlDocGen::isPort(), VhdlDocGen::isProcedure(), VhdlDocGen::isProcess(), VhdlDocGen::isRecord(), VhdlDocGen::isSignal(), VhdlDocGen::isSignals(), VhdlDocGen::isSubType(), VhdlDocGen::isUnit(), VhdlDocGen::isVariable(), VhdlDocGen::isVhdlFunction(), VhdlDocGen::isVType(), membersHaveSpecificType(), ClassDef::writeMemberList(), VhdlDocGen::writePlainVHDLDeclarations(), and VhdlDocGen::writeVHDLDeclaration().
getNamespaceDef()
NamespaceDef * MemberDef::getNamespaceDef () const
Definition at line 4109 of file memberdef.cpp.
References m_impl, and MemberDefImpl::nspace.
Referenced by _addToSearchIndex(), addEnumValuesToEnums(), DocSets::addIndexItem(), addMemberDocs(), addMembersToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), addVariableToFile(), findGlobalMember(), findMembersWithSpecificName(), generateDEFForMember(), generateDocbookForMember(), generateDocbookSection(), generateXMLForMember(), generateXMLSection(), getClassDefOfAnonymousType(), getDefs(), GlobalsIndexContext::Private::getMembersFiltered(), NamespaceMembersIndexContext::Private::getMembersFiltered(), MemberContext::Private::getNamespace(), getScopeString(), MemberContext::Private::handleNameWithContextFor(), MemberContext::Private::initializerAsCode(), isDetailedSectionVisible(), SymbolContext::Private::scope(), MemberContext::Private::sourceCode(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), writeJavascriptSearchIndex(), writeNamespaceLinkForMember(), NamespaceDef::writeQuickMemberLinks(), and FileDef::writeQuickMemberLinks().
getOutputFileBase()
QCString MemberDef::getOutputFileBase () const virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 949 of file memberdef.cpp.
References anchor(), MemberDefImpl::classDef, Config_getBool, MemberDefImpl::explicitOutputFileBase, MemberDefImpl::fileDef, Definition::getDefFileName(), Definition::getDefLine(), getEnumScope(), NamespaceDef::getOutputFileBase(), GroupDef::getOutputFileBase(), getOutputFileBase(), FileDef::getOutputFileBase(), ClassDef::getOutputFileBase(), MemberDefImpl::group, isDetailedSectionLinkable(), NamespaceDef::isLinkableInProject(), ClassDef::isSimple(), m_impl, Definition::name(), MemberDefImpl::nspace, MemberDefImpl::templateMaster, and warn().
Referenced by _writeCategoryRelation(), _writeReimplementedBy(), _writeReimplements(), Definition::_writeSourceRefList(), Qhp::addIndexItem(), HtmlHelp::addIndexItem(), addListReference(), DotGroupCollaboration::addMemberList(), addMembersToIndex(), DotCallGraph::buildGraph(), MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), DotCallGraph::DotCallGraph(), generateDEFForMember(), getOutputFileBase(), handleLinkedWord(), linkifyText(), memberOutputFileBase(), validatingParseDoc(), writeClassLinkForMember(), writeColumn(), writeDeclaration(), writeDocumentation(), MemberList::writeDocumentationPage(), writeFileLinkForMember(), writeGroupTreeNode(), writeLink(), writeLink(), writeMemberDocSimple(), ClassDef::writeMemberList(), writeMemberReference(), writeNamespaceLinkForMember(), MemberList::writePlainDeclarations(), NamespaceDef::writeQuickMemberLinks(), GroupDef::writeQuickMemberLinks(), FileDef::writeQuickMemberLinks(), ClassDef::writeQuickMemberLinks(), VhdlDocGen::writeTagFile(), and writeTagFile().
getReadAccessor()
const char * MemberDef::getReadAccessor () const
Definition at line 4114 of file memberdef.cpp.
References m_impl, and MemberDefImpl::read.
Referenced by generateXMLForMember().
getReference()
QCString MemberDef::getReference () const virtual
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented from Definition.
Definition at line 1009 of file memberdef.cpp.
References MemberDefImpl::classDef, MemberDefImpl::fileDef, getReference(), ClassDef::getReference(), Definition::getReference(), MemberDefImpl::group, m_impl, MemberDefImpl::nspace, and MemberDefImpl::templateMaster.
Referenced by _writeCategoryRelation(), _writeReimplementedBy(), _writeReimplements(), Definition::_writeSourceRefList(), DotGroupCollaboration::addMemberList(), addMembersToIndex(), anchor(), DotCallGraph::buildGraph(), DotCallGraph::DotCallGraph(), findMembersWithSpecificName(), getReference(), handleLinkedWord(), linkifyText(), writeClassLinkForMember(), writeFileLinkForMember(), writeGroupTreeNode(), writeLink(), writeLink(), ClassDef::writeMemberList(), writeNamespaceLinkForMember(), and VhdlDocGen::writeVHDLDeclaration().
getScopeString()
QCString MemberDef::getScopeString () const
Definition at line 3330 of file memberdef.cpp.
References NamespaceDef::displayName(), ClassDef::displayName(), getClassDef(), and getNamespaceDef().
Referenced by Definition::_writeSourceRefList(), Definition::addSourceReferencedBy(), Definition::addSourceReferences(), checkArgumentName(), generateDEFForMember(), and writeMemberReference().
getSectionList()
MemberList * MemberDef::getSectionList (Definition * d) const
Definition at line 3570 of file memberdef.cpp.
References MemberDefImpl::classSectionSDict, SDict< T >::find(), and m_impl.
Referenced by MemberGroup::addGroupedInheritedMembers(), MemberGroup::countGroupedInheritedMembers(), and MemberGroup::insertMember().
getWriteAccessor()
const char * MemberDef::getWriteAccessor () const
Definition at line 4119 of file memberdef.cpp.
References m_impl, and MemberDefImpl::write.
Referenced by generateXMLForMember().
hasCallerGraph()
bool MemberDef::hasCallerGraph () const
Definition at line 4591 of file memberdef.cpp.
References MemberDefImpl::hasCallerGraph, and m_impl.
Referenced by addDocCrossReference(), addMemberDocs(), combineDeclarationAndDefinition(), findFriends(), and MemberContext::Private::hasCallerGraph().
hasCallGraph()
bool MemberDef::hasCallGraph () const
Definition at line 4586 of file memberdef.cpp.
References MemberDefImpl::hasCallGraph, and m_impl.
Referenced by addDocCrossReference(), addMemberDocs(), combineDeclarationAndDefinition(), findFriends(), and MemberContext::Private::hasCallGraph().
hasDocumentation()
bool MemberDef::hasDocumentation () const virtual
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Reimplemented from Definition.
Definition at line 3303 of file memberdef.cpp.
References MemberDefImpl::defArgList, MemberDefImpl::docEnumValues, ArgumentList::hasDocumentation(), Definition::hasDocumentation(), m_impl, MemberType_Enumeration, and MemberDefImpl::mtype.
Referenced by _computeLinkableInProject(), addMembersToIndex(), combineDeclarationAndDefinition(), MemberList::countDecMembers(), isBriefSectionVisible(), warnIfUndocumentedParams(), writeDeclaration(), and writeEnumDeclaration().
hasDocumentedEnumValues()
bool MemberDef::hasDocumentedEnumValues () const
Definition at line 4501 of file memberdef.cpp.
References MemberDefImpl::docEnumValues, and m_impl.
Referenced by writeEnumDeclaration().
hasDocumentedParams()
bool MemberDef::hasDocumentedParams () const
Definition at line 4477 of file memberdef.cpp.
References MemberDefImpl::hasDocumentedParams, and m_impl.
Referenced by detectNoDocumentedParams(), and warnIfUndocumentedParams().
hasDocumentedReturnType()
bool MemberDef::hasDocumentedReturnType () const
Definition at line 4482 of file memberdef.cpp.
References MemberDefImpl::hasDocumentedReturnType, and m_impl.
Referenced by detectNoDocumentedParams(), and warnIfUndocumentedParams().
hasExamples()
bool MemberDef::hasExamples ()
Definition at line 941 of file memberdef.cpp.
References SDict< T >::count(), MemberDefImpl::exampleSDict, and m_impl.
Referenced by _writeExamples(), and MemberContext::Private::addExamples().
hasMultiLineInitializer()
bool MemberDef::hasMultiLineInitializer () const
Definition at line 3489 of file memberdef.cpp.
References MemberDefImpl::initLines, m_impl, MemberDefImpl::maxInitLines, and MemberDefImpl::userInitLines.
Referenced by generateXMLForMember(), MemberContext::Private::hasMultiLineInitializer(), isDetailedSectionLinkable(), and writeDocumentation().
hasOneLineInitializer()
bool MemberDef::hasOneLineInitializer () const
Definition at line 3480 of file memberdef.cpp.
References MemberDefImpl::initializer, MemberDefImpl::initLines, m_impl, MemberDefImpl::maxInitLines, and MemberDefImpl::userInitLines.
Referenced by generateXMLForMember(), MemberContext::Private::hasOneLineInitializer(), writeDeclaration(), writeDocumentation(), and writeEnumDeclaration().
inheritsDocsFrom()
MemberDef * MemberDef::inheritsDocsFrom () const
Definition at line 4632 of file memberdef.cpp.
References MemberDefImpl::docProvider, and m_impl.
Referenced by checkArgumentName().
initializer()
const QCString & MemberDef::initializer () const
Definition at line 4084 of file memberdef.cpp.
References MemberDefImpl::initializer, and m_impl.
Referenced by addMemberDocs(), MemberList::countDecMembers(), createTagLessInstance(), findMember(), findUsingDeclImports(), generateDEFForMember(), generateDocbookForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), MemberContext::Private::initializer(), MemberContext::Private::initializerAsCode(), setInitializer(), and writeEnumDeclaration().
initializerLines()
int MemberDef::initializerLines () const
Definition at line 4089 of file memberdef.cpp.
References MemberDefImpl::initLines, and m_impl.
Referenced by createTagLessInstance(), and findUsingDeclImports().
insertEnumField()
void MemberDef::insertEnumField (MemberDef * md)
Definition at line 917 of file memberdef.cpp.
References MemberList::append(), MemberDefImpl::enumFields, m_impl, and MemberListType_enumFields.
Referenced by addEnumValuesToEnums(), and deepCopy().
insertReimplementedBy()
void MemberDef::insertReimplementedBy (MemberDef * md)
Definition at line 873 of file memberdef.cpp.
References MemberList::findRef(), insertReimplementedBy(), MemberList::inSort(), m_impl, MemberListType_redefinedBy, MemberDefImpl::redefinedBy, and MemberDefImpl::templateMaster.
Referenced by computeMemberRelations(), deepCopy(), and insertReimplementedBy().
invalidateCachedArgumentTypes()
void MemberDef::invalidateCachedArgumentTypes ()
Definition at line 4908 of file memberdef.cpp.
References MemberDefImpl::declArgList, MemberDefImpl::defArgList, invalidateCachedTypesInArgumentList(), and m_impl.
Referenced by flushUnresolvedRelations().
invalidateTypedefValCache()
void MemberDef::invalidateTypedefValCache ()
Definition at line 4810 of file memberdef.cpp.
References MemberDefImpl::isTypedefValCached, and m_impl.
Referenced by flushCachedTemplateRelations().
isAbstract()
bool MemberDef::isAbstract () const
Definition at line 4334 of file memberdef.cpp.
References Entry::Abstract, m_impl, and MemberDefImpl::memSpec.
Referenced by getLabels(), and MemberContext::Private::isAbstract().
isAddable()
bool MemberDef::isAddable () const
Definition at line 4284 of file memberdef.cpp.
References Entry::Addable, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isAddable(), MemberContext::Private::Private(), and writeDeclaration().
isAlias()
bool MemberDef::isAlias () const
Definition at line 4391 of file memberdef.cpp.
References Entry::Alias, m_impl, and MemberDefImpl::memSpec.
Referenced by getDeclType(), MemberContext::Private::isAlias(), MemberContext::Private::templateAlias(), and writeDeclaration().
isAssign()
bool MemberDef::isAssign () const
Definition at line 4359 of file memberdef.cpp.
References Entry::Assign, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isAssign().
isAttribute()
bool MemberDef::isAttribute () const
Definition at line 4411 of file memberdef.cpp.
References Entry::Attribute, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isAttribute(), and ClassDef::writeMemberList().
isBound()
bool MemberDef::isBound () const
Definition at line 4426 of file memberdef.cpp.
References Entry::Bound, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isBound(), and ClassDef::writeMemberList().
isBriefSectionVisible()
bool MemberDef::isBriefSectionVisible () const
This methods returns TRUE iff the brief section (also known as declaration section) is visible in the documentation.
Definition at line 1297 of file memberdef.cpp.
References MemberDefImpl::annScope, Config_getBool, MemberDefImpl::defArgList, MemberGroupInfo::doc, documentation(), getClassDef(), MemberDefImpl::grpId, hasDocumentation(), MemberGroupInfo::header, isConstructor(), isDestructor(), isDocumentedFriendClass(), isFriend(), Definition::isHidden(), isStatic(), m_impl, MemberType_Friend, Doxygen::memGrpInfoDict, MemberDefImpl::mtype, protection(), protectionLevelVisible(), and MemberDefImpl::type.
Referenced by InheritedMemberInfoListContext::Private::addMemberList(), ClassContext::Private::addMembers(), MemberList::countDecMembers(), MemberList::countInheritableMembers(), MemberList::declVisible(), MemberListContext::MemberListContext(), writeEnumDeclaration(), MemberList::writePlainDeclarations(), and VhdlDocGen::writePlainVHDLDeclarations().
isConstrained()
bool MemberDef::isConstrained () const
Definition at line 4431 of file memberdef.cpp.
References Entry::Constrained, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isConstrained(), and ClassDef::writeMemberList().
isConstructor()
bool MemberDef::isConstructor () const
Definition at line 3731 of file memberdef.cpp.
References _computeIsConstructor(), and m_isConstructorCached.
Referenced by MemberList::compareValues(), detectNoDocumentedParams(), ClassDef::internalInsertMember(), isBriefSectionVisible(), isStandardFunc(), and showInCallGraph().
isCopy()
bool MemberDef::isCopy () const
Definition at line 4354 of file memberdef.cpp.
References Entry::Copy, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isCopy().
isDCOP()
bool MemberDef::isDCOP () const
Definition at line 4209 of file memberdef.cpp.
References m_impl, MemberType_DCOP, and MemberDefImpl::mtype.
isDefault()
bool MemberDef::isDefault () const
Definition at line 4396 of file memberdef.cpp.
References Entry::Default, m_impl, and MemberDefImpl::memSpec.
Referenced by getLabels(), and MemberContext::Private::isDefault().
isDefine()
bool MemberDef::isDefine () const
Definition at line 4199 of file memberdef.cpp.
References m_impl, MemberType_Define, and MemberDefImpl::mtype.
Referenced by addFileMemberNameToIndex(), addMemberToSearchIndex(), addVariableToFile(), checkArgumentName(), checkUndocumentedParams(), definitionToName(), findMember(), findMembersWithSpecificName(), MemberContext::Private::isDefine(), GlobalsIndexContext::Private::macros(), writeDeclaration(), writeDefArgumentList(), and writeDocumentation().
isDelete()
bool MemberDef::isDelete () const
Definition at line 4401 of file memberdef.cpp.
References Entry::Delete, m_impl, and MemberDefImpl::memSpec.
Referenced by getLabels(), and MemberContext::Private::isDelete().
isDeleted()
bool MemberDef::isDeleted () const
Definition at line 3298 of file memberdef.cpp.
References MemberDefImpl::defArgList, ArgumentList::isDeleted, and m_impl.
Referenced by warnIfUndocumented().
isDestructor()
bool MemberDef::isDestructor () const
Definition at line 3772 of file memberdef.cpp.
References _computeIsDestructor(), and m_isDestructorCached.
Referenced by _computeIsDestructor(), MemberList::compareValues(), detectNoDocumentedParams(), ClassDef::internalInsertMember(), isBriefSectionVisible(), isStandardFunc(), and showInCallGraph().
isDetailedSectionLinkable()
bool MemberDef::isDetailedSectionLinkable () const
Definition at line 1869 of file memberdef.cpp.
References Entry::Attribute, briefDescription(), Config_getBool, MemberDefImpl::defArgList, MemberDefImpl::docEnumValues, documentation(), getClassDef(), ArgumentList::hasDocumentation(), hasMultiLineInitializer(), Definition::inbodyDocumentation(), isFriend(), Definition::isHidden(), isStatic(), m_impl, MemberType_Enumeration, MemberType_EnumValue, MemberType_Friend, MemberDefImpl::memSpec, MemberDefImpl::mtype, Entry::Property, protection(), protectionLevelVisible(), MemberDefImpl::type, and Doxygen::userComments.
Referenced by getOutputFileBase(), MemberContext::Private::hasDetails(), isDetailedSectionVisible(), MemberListContext::MemberListContext(), warnIfUndocumented(), writeDeclaration(), MemberList::writeDocumentationPage(), MemberList::writePlainDeclarations(), and VhdlDocGen::writeVHDLDeclaration().
isDetailedSectionVisible()
bool MemberDef::isDetailedSectionVisible (bool inGroup, bool inFile) const
Definition at line 1937 of file memberdef.cpp.
References Config_getBool, getClassDef(), getGroupDef(), getNamespaceDef(), Definition::hasBriefDescription(), isDetailedSectionLinkable(), NamespaceDef::isLinkable(), isReference(), and ClassDef::isSimple().
Referenced by MemberList::countDocMembers(), MemberContext::Private::handleDetailsVisibleFor(), MemberList::writeDocumentation(), and writeDocumentation().
isDocsForDefinition()
bool MemberDef::isDocsForDefinition () const
Definition at line 4511 of file memberdef.cpp.
References MemberDefImpl::docsForDefinition, and m_impl.
Referenced by checkArgumentName(), checkUndocumentedParams(), combineDeclarationAndDefinition(), findFriends(), MemberContext::Private::getDefArgList(), inheritDocumentation(), and writeDefArgumentList().
isDocumentedFriendClass()
bool MemberDef::isDocumentedFriendClass () const
Definition at line 3288 of file memberdef.cpp.
References getClass(), isFriendClass(), ClassDef::isLinkable(), and Definition::name().
Referenced by isBriefSectionVisible(), and writeDeclaration().
isEnumerate()
bool MemberDef::isEnumerate () const
Definition at line 4174 of file memberdef.cpp.
References m_impl, MemberType_Enumeration, and MemberDefImpl::mtype.
Referenced by _writeEnumValues(), addClassMemberNameToIndex(), addDocCrossReference(), addEnumValuesToEnums(), addFileMemberNameToIndex(), addMembersToIndex(), addMembersToMemberGroup(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), addVariableToFile(), definitionToName(), displayDefinition(), GlobalsIndexContext::Private::enums(), ClassMembersIndexContext::Private::enums(), NamespaceMembersIndexContext::Private::enums(), findDEV(), findEnumDocumentation(), getCanonicalTypeForIdentifier(), getDefs(), getResolvedSymbol(), ClassDef::internalInsertMember(), MemberContext::Private::isEnumeration(), writeDeclaration(), writeDocumentation(), writeGroupTreeNode(), and ClassDef::writeMemberList().
isEnumValue()
bool MemberDef::isEnumValue () const
Definition at line 4179 of file memberdef.cpp.
References m_impl, MemberType_EnumValue, and MemberDefImpl::mtype.
Referenced by addClassMemberNameToIndex(), addEnumValuesToEnums(), addFileMemberNameToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), definitionToName(), displayDefinition(), GlobalsIndexContext::Private::enumValues(), ClassMembersIndexContext::Private::enumValues(), NamespaceMembersIndexContext::Private::enumValues(), ClassDef::internalInsertMember(), MemberContext::Private::isEnumValue(), MemberList::writeDocumentation(), writeDocumentation(), ClassDef::writeMemberList(), NamespaceDef::writeQuickMemberLinks(), GroupDef::writeQuickMemberLinks(), FileDef::writeQuickMemberLinks(), and ClassDef::writeQuickMemberLinks().
isEvent()
bool MemberDef::isEvent () const
Definition at line 4219 of file memberdef.cpp.
References m_impl, MemberType_Event, and MemberDefImpl::mtype.
Referenced by addClassMemberNameToIndex(), addMemberToSearchIndex(), definitionToName(), ClassMembersIndexContext::Private::events(), MemberContext::Private::isEvent(), MemberContext::Private::Private(), and writeDeclaration().
isExplicit()
bool MemberDef::isExplicit () const
Definition at line 4244 of file memberdef.cpp.
References Entry::Explicit, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isExplicit(), and ClassDef::writeMemberList().
isExternal()
bool MemberDef::isExternal () const
Definition at line 4467 of file memberdef.cpp.
References MemberDefImpl::explExt, and m_impl.
Referenced by combineDeclarationAndDefinition(), MemberContext::Private::isExternal(), and transferFunctionReferences().
isFinal()
bool MemberDef::isFinal () const
Definition at line 4309 of file memberdef.cpp.
References Entry::Final, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isFinal().
isForeign()
bool MemberDef::isForeign () const
Definition at line 4229 of file memberdef.cpp.
References Foreign, m_impl, and MemberDefImpl::related.
Referenced by addClassMemberNameToIndex(), addMemberToSearchIndex(), definitionToName(), getDefs(), MemberContext::Private::isForeign(), isRelatedOrFriend(), and transferRelatedFunctionDocumentation().
isFriend()
bool MemberDef::isFriend () const
Definition at line 4204 of file memberdef.cpp.
References m_impl, MemberType_Friend, and MemberDefImpl::mtype.
Referenced by addClassMemberNameToIndex(), addMemberToSearchIndex(), definitionToName(), findFriends(), getLabels(), ClassDef::internalInsertMember(), isBriefSectionVisible(), isDetailedSectionLinkable(), MemberContext::Private::isFriend(), isFriendClass(), isNotFriend(), isRelatedOrFriend(), ClassDef::mergeMembers(), AllMembersListContext::Private::Private(), and ClassDef::writeMemberList().
isFriendClass()
bool MemberDef::isFriendClass () const
Definition at line 3281 of file memberdef.cpp.
References isFriend(), m_impl, and MemberDefImpl::type.
Referenced by isDocumentedFriendClass(), and warnIfUndocumented().
isFriendToHide()
bool MemberDef::isFriendToHide () const
Definition at line 5131 of file memberdef.cpp.
References Config_getBool, m_impl, and MemberDefImpl::type.
Referenced by isNotFriend(), and isRelatedOrFriend().
isFunction()
bool MemberDef::isFunction () const
Definition at line 4189 of file memberdef.cpp.
References m_impl, MemberType_Function, and MemberDefImpl::mtype.
Referenced by _writeCallerGraph(), _writeCallGraph(), Definition::_writeSourceRefList(), addClassMemberNameToIndex(), addFileMemberNameToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), combineDeclarationAndDefinition(), computeMemberRelations(), definitionToName(), findFriends(), MemberContext::Private::functionQualifier(), GlobalsIndexContext::Private::functions(), NamespaceMembersIndexContext::Private::functions(), MemberContext::Private::hasCallerGraph(), MemberContext::Private::hasCallGraph(), GroupDef::insertMember(), MemberContext::Private::isFunction(), isFunctionOrSignalSlot(), isObjCMethod(), SymbolContext::Private::scope(), showInCallGraph(), transferFunctionReferences(), warnIfUndocumentedParams(), writeBoxMemberList(), writeDocumentation(), writeJavascriptSearchIndex(), ClassDef::writeMemberList(), and writeMemberList().
isFunctionOrSignalSlot()
bool MemberDef::isFunctionOrSignalSlot () const
Definition at line 5146 of file memberdef.cpp.
References isFunction(), isSignal(), and isSlot().
Referenced by ClassMembersIndexContext::Private::functions().
isFunctionPtr()
bool MemberDef::isFunctionPtr () const
Definition at line 4194 of file memberdef.cpp.
References argsString(), m_impl, MemberType_Variable, and MemberDefImpl::mtype.
Referenced by ClassDef::internalInsertMember(), and MemberContext::Private::isFunctionPtr().
isGettable()
bool MemberDef::isGettable () const
Definition at line 4254 of file memberdef.cpp.
References Entry::Gettable, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isGettable(), MemberContext::Private::Private(), and writeDeclaration().
isImplementation()
bool MemberDef::isImplementation () const
Definition at line 4462 of file memberdef.cpp.
References MemberDefImpl::implOnly, and m_impl.
Referenced by getLabels(), MemberContext::Private::isImplementation(), and writeDeclaration().
isInitonly()
bool MemberDef::isInitonly () const
Definition at line 4329 of file memberdef.cpp.
References Entry::Initonly, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isInitonly().
isInline()
bool MemberDef::isInline () const
Definition at line 4239 of file memberdef.cpp.
References Entry::Inline, m_impl, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isInline(), and ClassDef::writeMemberList().
isLinkable()
bool MemberDef::isLinkable () const virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 1169 of file memberdef.cpp.
References isLinkable(), isLinkableInProject(), isReference(), m_impl, and MemberDefImpl::templateMaster.
Referenced by _writeCategoryRelation(), _writeEnumValues(), _writeReimplementedBy(), _writeReimplements(), Definition::_writeSourceRefList(), DocSets::addIndexItem(), addMemberToSearchIndex(), findMembersWithSpecificName(), getDefs(), handleLinkedWord(), isLinkable(), linkifyText(), AllMembersListContext::Private::Private(), writeLink(), ClassDef::writeMemberList(), NamespaceDef::writeQuickMemberLinks(), GroupDef::writeQuickMemberLinks(), FileDef::writeQuickMemberLinks(), ClassDef::writeQuickMemberLinks(), VhdlDocGen::writeStringLink(), and VhdlDocGen::writeVHDLTypeDocumentation().
isLinkableInProject()
bool MemberDef::isLinkableInProject () const virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 1158 of file memberdef.cpp.
References _computeLinkableInProject(), and m_isLinkableCached.
Referenced by _addToSearchIndex(), _computeLinkableInProject(), _writeReimplementedBy(), _writeReimplements(), addClassMemberNameToIndex(), addFileMemberNameToIndex(), addListReference(), addNamespaceMemberNameToIndex(), addSourceReferences(), findDEV(), GlobalsIndexContext::Private::getMembersFiltered(), ClassMembersIndexContext::Private::getMembersFiltered(), NamespaceMembersIndexContext::Private::getMembersFiltered(), isLinkable(), linkifyText(), writeEnumDeclaration(), NamespaceDef::writeQuickMemberLinks(), GroupDef::writeQuickMemberLinks(), FileDef::writeQuickMemberLinks(), ClassDef::writeQuickMemberLinks(), and writeTagFile().
isMaybeAmbiguous()
bool MemberDef::isMaybeAmbiguous () const
Definition at line 4451 of file memberdef.cpp.
References m_impl, Entry::MaybeAmbiguous, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isMaybeAmbiguous(), and ClassDef::writeMemberList().
isMaybeDefault()
bool MemberDef::isMaybeDefault () const
Definition at line 4446 of file memberdef.cpp.
References m_impl, Entry::MaybeDefault, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isMaybeDefault(), and ClassDef::writeMemberList().
isMaybeVoid()
bool MemberDef::isMaybeVoid () const
Definition at line 4441 of file memberdef.cpp.
References m_impl, Entry::MaybeVoid, and MemberDefImpl::memSpec.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isMaybeVoid(), and ClassDef::writeMemberList().
isMutable()
bool MemberDef::isMutable () const
Definition at line 4249 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Mutable.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isMutable(), and ClassDef::writeMemberList().
isNew()
bool MemberDef::isNew () const
Definition at line 4314 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::New.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isNew().
isNoExcept()
bool MemberDef::isNoExcept () const
Definition at line 4406 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::NoExcept.
Referenced by getLabels(), and MemberContext::Private::isNoExcept().
isNonAtomic()
bool MemberDef::isNonAtomic () const
Definition at line 4349 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::NonAtomic.
Referenced by getLabels(), and MemberContext::Private::isNonAtomic().
isNotFriend()
bool MemberDef::isNotFriend () const
Definition at line 5141 of file memberdef.cpp.
References isFriend(), and isFriendToHide().
Referenced by ClassMembersIndexContext::Private::all().
isObjCMethod()
bool MemberDef::isObjCMethod () const
Definition at line 3985 of file memberdef.cpp.
References MemberDefImpl::classDef, isFunction(), ClassDef::isObjectiveC(), and m_impl.
Referenced by Definition::_writeSourceRefList(), DocSets::addIndexItem(), addListReference(), MemberContext::Private::functionQualifier(), getDeclType(), getLabels(), handleLinkedWord(), MemberContext::Private::isObjCMethod(), qualifiedName(), showInCallGraph(), writeBoxMemberList(), writeDeclaration(), writeDefArgumentList(), writeDocumentation(), writeLink(), writeMemberDocSimple(), ClassDef::writeMemberList(), and writeMemberList().
isObjCProperty()
bool MemberDef::isObjCProperty () const
Definition at line 3991 of file memberdef.cpp.
References MemberDefImpl::classDef, ClassDef::isObjectiveC(), isProperty(), and m_impl.
Referenced by DocSets::addIndexItem(), findUsedClassesForClass(), getLabels(), MemberContext::Private::isObjCProperty(), and writeDeclaration().
isOptional()
bool MemberDef::isOptional () const
Definition at line 4339 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Optional.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isOptional(), and ClassDef::writeMemberList().
isOverride()
bool MemberDef::isOverride () const
Definition at line 4324 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Override.
Referenced by getLabels(), and MemberContext::Private::isOverride().
isPrivateGettable()
bool MemberDef::isPrivateGettable () const
Definition at line 4259 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::PrivateGettable.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isPrivateGettable(), MemberContext::Private::Private(), and writeDeclaration().
isPrivateSettable()
bool MemberDef::isPrivateSettable () const
Definition at line 4274 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::PrivateSettable.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isPrivateSettable(), MemberContext::Private::Private(), and writeDeclaration().
isProperty()
bool MemberDef::isProperty () const
Definition at line 4214 of file memberdef.cpp.
References m_impl, MemberType_Property, and MemberDefImpl::mtype.
Referenced by addClassMemberNameToIndex(), addMemberToSearchIndex(), definitionToName(), isObjCProperty(), MemberContext::Private::isProperty(), MemberContext::Private::parameters(), MemberContext::Private::Private(), ClassMembersIndexContext::Private::properties(), writeDeclaration(), and writeDefArgumentList().
isProtectedGettable()
bool MemberDef::isProtectedGettable () const
Definition at line 4264 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::ProtectedGettable.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isProtectedGettable(), MemberContext::Private::Private(), and writeDeclaration().
isProtectedSettable()
bool MemberDef::isProtectedSettable () const
Definition at line 4279 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::ProtectedSettable.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isProtectedSettable(), MemberContext::Private::Private(), and writeDeclaration().
isPrototype()
bool MemberDef::isPrototype () const
Definition at line 4536 of file memberdef.cpp.
References m_impl, and MemberDefImpl::proto.
Referenced by Definition::_writeSourceRefList(), combineDeclarationAndDefinition(), MemberContext::Private::functionQualifier(), and transferFunctionReferences().
isPublished()
bool MemberDef::isPublished () const
Definition at line 4456 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Published.
Referenced by getLabels(), and MemberContext::Private::isPublished().
isRaisable()
bool MemberDef::isRaisable () const
Definition at line 4294 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Raisable.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isRaisable(), MemberContext::Private::Private(), and writeDeclaration().
isReadable()
bool MemberDef::isReadable () const
Definition at line 4299 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Readable.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isReadable().
isReadonly()
bool MemberDef::isReadonly () const
Definition at line 4421 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Readonly.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isReadonly(), and ClassDef::writeMemberList().
isReference()
bool MemberDef::isReference () const virtual
Returns TRUE if this definition is imported via a tag file.
Reimplemented from Definition.
Definition at line 5156 of file memberdef.cpp.
References Definition::isReference(), isReference(), m_impl, and MemberDefImpl::templateMaster.
Referenced by _computeLinkableInProject(), findMembersWithSpecificName(), getResolvedSymbol(), isDetailedSectionVisible(), isLinkable(), isReference(), setAnchors(), warnIfUndocumented(), writeDeclaration(), and writeTagFile().
isReimplementedBy()
bool MemberDef::isReimplementedBy (ClassDef * cd) const
Definition at line 896 of file memberdef.cpp.
References getClassDef(), ClassDef::isBaseClass(), m_impl, and MemberDefImpl::redefinedBy.
Referenced by InheritedMemberInfoListContext::Private::addMemberList(), MemberList::countInheritableMembers(), and MemberList::writePlainDeclarations().
isRelated()
bool MemberDef::isRelated () const
Definition at line 4224 of file memberdef.cpp.
References m_impl, Related, and MemberDefImpl::related.
Referenced by addClassMemberNameToIndex(), addListReference(), addMemberToSearchIndex(), MemberContext::Private::addTemplateDecls(), MemberList::countDecMembers(), definitionToName(), findFriends(), getDefs(), getLabels(), MemberContext::Private::handleNameWithContextFor(), ClassDef::internalInsertMember(), MemberContext::Private::isRelated(), isRelatedOrFriend(), ClassMembersIndexContext::Private::related(), transferRelatedFunctionDocumentation(), writeLink(), and ClassDef::writeMemberList().
isRelatedOrFriend()
bool MemberDef::isRelatedOrFriend () const
Definition at line 5151 of file memberdef.cpp.
References isForeign(), isFriend(), isFriendToHide(), and isRelated().
isRemovable()
bool MemberDef::isRemovable () const
Definition at line 4289 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Removable.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isRemovable(), MemberContext::Private::Private(), writeDeclaration(), and ClassDef::writeMemberList().
isRequired()
bool MemberDef::isRequired () const
Definition at line 4344 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Required.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isRequired().
isRetain()
bool MemberDef::isRetain () const
Definition at line 4364 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Retain.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isRetain().
isSealed()
bool MemberDef::isSealed () const
Definition at line 4319 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Sealed.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isSealed().
isSettable()
bool MemberDef::isSettable () const
Definition at line 4269 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Settable.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isSettable(), MemberContext::Private::Private(), and writeDeclaration().
isSignal()
bool MemberDef::isSignal () const
Definition at line 4159 of file memberdef.cpp.
References m_impl, MemberType_Signal, and MemberDefImpl::mtype.
Referenced by _writeCallerGraph(), _writeCallGraph(), Definition::_writeSourceRefList(), addClassMemberNameToIndex(), addMemberToSearchIndex(), definitionToName(), MemberContext::Private::functionQualifier(), getLabels(), MemberContext::Private::hasCallerGraph(), MemberContext::Private::hasCallGraph(), isFunctionOrSignalSlot(), MemberContext::Private::isSignal(), SymbolContext::Private::scope(), writeBoxMemberList(), ClassDef::writeMemberList(), and writeMemberList().
isSlot()
bool MemberDef::isSlot () const
Definition at line 4164 of file memberdef.cpp.
References m_impl, MemberType_Slot, and MemberDefImpl::mtype.
Referenced by _writeCallerGraph(), _writeCallGraph(), Definition::_writeSourceRefList(), addClassMemberNameToIndex(), addMemberToSearchIndex(), definitionToName(), MemberContext::Private::functionQualifier(), getLabels(), MemberContext::Private::hasCallerGraph(), MemberContext::Private::hasCallGraph(), isFunctionOrSignalSlot(), MemberContext::Private::isSlot(), SymbolContext::Private::scope(), showInCallGraph(), writeBoxMemberList(), writeJavascriptSearchIndex(), ClassDef::writeMemberList(), and writeMemberList().
isStatic()
bool MemberDef::isStatic () const
Definition at line 4234 of file memberdef.cpp.
References m_impl, and MemberDefImpl::stat.
Referenced by DocSets::addIndexItem(), addMembersToIndex(), addVariableToFile(), combineDeclarationAndDefinition(), createTagLessInstance(), displayDefinition(), findGlobalMember(), findMembersWithSpecificName(), findUsingDeclImports(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getLabels(), ClassDef::internalInsertMember(), isBriefSectionVisible(), isDetailedSectionLinkable(), MemberContext::Private::isStatic(), objCMethodName(), qualifiedName(), transferFunctionReferences(), writeDeclaration(), writeDocumentation(), FlowChart::writeFlowChart(), writeLink(), ClassDef::writeMemberList(), and writeTagFile().
isStrong()
bool MemberDef::isStrong () const
Definition at line 4374 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Strong.
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), addNamespaceMemberNameToIndex(), generateXMLForMember(), getDefs(), getLabels(), MemberContext::Private::isStrong(), isStrongEnumValue(), qualifiedName(), MemberList::writeTagFile(), and writeTagFile().
isStrongEnumValue()
bool MemberDef::isStrongEnumValue () const
Definition at line 4379 of file memberdef.cpp.
References MemberDefImpl::enumScope, isStrong(), m_impl, MemberType_EnumValue, and MemberDefImpl::mtype.
Referenced by getDefs(), and resolveRef().
isTemplateSpecialization()
bool MemberDef::isTemplateSpecialization () const
Definition at line 4472 of file memberdef.cpp.
References m_impl, and MemberDefImpl::tspec.
Referenced by MemberContext::Private::addTemplateDecls(), MemberContext::Private::isTemplateSpecialization(), and writeDocumentation().
isTransient()
bool MemberDef::isTransient () const
Definition at line 4436 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Transient.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isTransient(), and ClassDef::writeMemberList().
isTypedef()
bool MemberDef::isTypedef () const
Definition at line 4184 of file memberdef.cpp.
References m_impl, MemberType_Typedef, and MemberDefImpl::mtype.
Referenced by addClassMemberNameToIndex(), addDocCrossReference(), addFileMemberNameToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), checkIfTypedef(), definitionToName(), fieldType(), findGlobalMember(), getCanonicalTypeForIdentifier(), getResolvedSymbol(), ClassDef::internalInsertMember(), MemberContext::Private::isTypedef(), resolveTypeDef(), substTypedef(), GlobalsIndexContext::Private::typedefs(), ClassMembersIndexContext::Private::typedefs(), NamespaceMembersIndexContext::Private::typedefs(), writeDeclaration(), writeDocumentation(), and ClassDef::writeMemberList().
isTypedefValCached()
bool MemberDef::isTypedefValCached () const
Definition at line 4601 of file memberdef.cpp.
References MemberDefImpl::isTypedefValCached, and m_impl.
Referenced by flushCachedTemplateRelations(), and newResolveTypedef().
isUNOProperty()
bool MemberDef::isUNOProperty () const
Definition at line 4416 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Property.
Referenced by generateXMLForMember(), getLabels(), MemberContext::Private::isUNOProperty(), and ClassDef::writeMemberList().
isUnretained()
bool MemberDef::isUnretained () const
Definition at line 4386 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Unretained.
Referenced by getLabels(), and MemberContext::Private::isUnretained().
isVariable()
bool MemberDef::isVariable () const
Definition at line 4169 of file memberdef.cpp.
References m_impl, MemberType_Variable, and MemberDefImpl::mtype.
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), combineDeclarationAndDefinition(), definitionToName(), findGlobalMember(), findUsedClassesForClass(), ClassDef::internalInsertMember(), MemberContext::Private::isVariable(), transferFunctionReferences(), GlobalsIndexContext::Private::variables(), ClassMembersIndexContext::Private::variables(), NamespaceMembersIndexContext::Private::variables(), writeDocumentation(), writeMemberDocSimple(), and VhdlDocGen::writeVHDLTypeDocumentation().
isWeak()
bool MemberDef::isWeak () const
Definition at line 4369 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Weak.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isWeak().
isWritable()
bool MemberDef::isWritable () const
Definition at line 4304 of file memberdef.cpp.
References m_impl, MemberDefImpl::memSpec, and Entry::Writable.
Referenced by generateXMLForMember(), getLabels(), and MemberContext::Private::isWritable().
livesInsideEnum()
bool MemberDef::livesInsideEnum () const
Definition at line 4521 of file memberdef.cpp.
References MemberDefImpl::livesInsideEnum, and m_impl.
Referenced by MemberContext::Private::handleNameWithContextFor(), and setEnumScope().
loadFromDisk()
void MemberDef::loadFromDisk () const protected
lock()
void MemberDef::lock () const private
makeForeign()
void MemberDef::makeForeign ()
Definition at line 4716 of file memberdef.cpp.
References Foreign, m_impl, m_isLinkableCached, and MemberDefImpl::related.
Referenced by transferRelatedFunctionDocumentation().
makeImplementationDetail()
void MemberDef::makeImplementationDetail ()
Definition at line 4774 of file memberdef.cpp.
References MemberDefImpl::implOnly, and m_impl.
Referenced by findMember(), and ClassDef::mergeCategory().
makeRelated()
void MemberDef::makeRelated ()
Definition at line 4710 of file memberdef.cpp.
References m_impl, m_isLinkableCached, Related, and MemberDefImpl::related.
Referenced by addEnumValuesToEnums(), and transferRelatedFunctionDocumentation().
makeResident()
void MemberDef::makeResident () const private
memberDeclaration()
MemberDef * MemberDef::memberDeclaration () const
Definition at line 4627 of file memberdef.cpp.
References m_impl, and MemberDefImpl::memDec.
Referenced by addDocCrossReference(), and DocSets::addIndexItem().
memberDefinition()
MemberDef * MemberDef::memberDefinition () const
Definition at line 4622 of file memberdef.cpp.
References m_impl, and MemberDefImpl::memDef.
Referenced by addDocCrossReference().
memberType()
MemberType MemberDef::memberType () const
Definition at line 4154 of file memberdef.cpp.
References m_impl, and MemberDefImpl::mtype.
Referenced by DocSets::addIndexItem(), MemberList::addListReferences(), addVariableToClass(), MemberList::countDecMembers(), MemberList::countDocMembers(), MemberList::countInheritableMembers(), createTagLessInstance(), MemberList::declVisible(), findDefineDocumentation(), findUsingDeclImports(), generateDEFForMember(), generateDocbookForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), NamespaceDef::insertMember(), GroupDef::insertMember(), FileDef::insertMember(), ClassDef::internalInsertMember(), GroupDef::removeMember(), MemberList::writePlainDeclarations(), and MemberList::writeTagFile().
memberTypeName()
QCString MemberDef::memberTypeName () const
Definition at line 3191 of file memberdef.cpp.
References m_impl, MemberType_DCOP, MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, and MemberDefImpl::mtype.
Referenced by warnIfUndocumented().
mergeMemberSpecifiers()
void MemberDef::mergeMemberSpecifiers (uint64 s)
Definition at line 4672 of file memberdef.cpp.
References m_impl, and MemberDefImpl::memSpec.
Referenced by addMemberDocs(), and combineDeclarationAndDefinition().
moveTo()
void MemberDef::moveTo (Definition * scope)
Definition at line 840 of file memberdef.cpp.
References MemberDefImpl::classDef, DefinitionIntf::definitionType(), MemberDefImpl::fileDef, m_impl, m_isConstructorCached, m_isLinkableCached, MemberDefImpl::nspace, Definition::setOuterScope(), DefinitionIntf::TypeClass, DefinitionIntf::TypeFile, and DefinitionIntf::TypeNamespace.
Referenced by ClassDef::mergeCategory().
objCMethodName()
QCString MemberDef::objCMethodName (bool localLink, bool showStatic) const
Definition at line 4032 of file memberdef.cpp.
References MemberDefImpl::classDef, isStatic(), m_impl, and Definition::name().
Referenced by DocRef::DocRef(), and handleLinkedWord().
operator=()
MemberDef& MemberDef::operator= (const MemberDef &) private
protection()
Protection MemberDef::protection () const
Definition at line 4149 of file memberdef.cpp.
References m_impl, and MemberDefImpl::prot.
Referenced by createTagLessInstance(), findMember(), findUsedClassesForClass(), findUsingDeclImports(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getLabels(), GroupDef::insertMember(), ClassDef::insertMember(), isBriefSectionVisible(), isDetailedSectionLinkable(), ClassDef::mergeMembers(), AllMembersListContext::Private::Private(), GroupDef::removeMember(), and ClassDef::writeMemberList().
protectionVisible()
bool MemberDef::protectionVisible () const
qualifiedName()
QCString MemberDef::qualifiedName () const virtual
Returns the fully qualified name of this definition
Reimplemented from Definition.
Definition at line 3997 of file memberdef.cpp.
References MemberDefImpl::classDef, MemberDefImpl::enumScope, Definition::getLanguage(), getLanguageSpecificSeparator(), isObjCMethod(), isStatic(), isStrong(), Definition::localName(), m_impl, Definition::name(), qualifiedName(), and Definition::qualifiedName().
Referenced by _addToSearchIndex(), _writeCallerGraph(), _writeCallGraph(), addEnumValuesToEnums(), addListReference(), DotCallGraph::buildGraph(), checkUndocumentedParams(), MemberIndexList::compareValues(), DotCallGraph::DotCallGraph(), getCanonicalTypeForIdentifier(), getResolvedSymbol(), newResolveTypedef(), qualifiedName(), validatingParseDoc(), warnIfUndocumentedParams(), MemberList::writeDocumentationPage(), and VhdlDocGen::writeVHDLDeclaration().
reimplementedBy()
MemberList * MemberDef::reimplementedBy () const
Definition at line 891 of file memberdef.cpp.
References m_impl, and MemberDefImpl::redefinedBy.
Referenced by _writeReimplementedBy(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), MemberContext::Private::implementedBy(), and MemberContext::Private::reimplementedBy().
reimplements()
MemberDef * MemberDef::reimplements () const
Definition at line 886 of file memberdef.cpp.
References m_impl, and MemberDefImpl::redefines.
Referenced by _writeReimplements(), computeMemberRelations(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), DocPara::handleInheritDoc(), MemberContext::Private::implements(), inheritDocumentation(), MemberContext::Private::reimplements(), and virtualness().
relatedAlso()
ClassDef * MemberDef::relatedAlso () const
Definition at line 4496 of file memberdef.cpp.
References m_impl, and MemberDefImpl::relatedAlso.
Referenced by transferRelatedFunctionDocumentation().
saveToDisk()
void MemberDef::saveToDisk () const private
setAccessorType()
void MemberDef::setAccessorType (ClassDef * cd, const char * t)
Definition at line 3936 of file memberdef.cpp.
References MemberDefImpl::accessorClass, MemberDefImpl::accessorType, and m_impl.
Referenced by processTagLessClasses().
setAnchor()
void MemberDef::setAnchor ()
Definition at line 3363 of file memberdef.cpp.
References MemberDefImpl::anc, MemberDefImpl::args, definition(), m_impl, Definition::name(), and MemberDefImpl::tArgList.
Referenced by addEnumValuesToEnums(), and setAnchors().
setAnonymousEnumType()
void MemberDef::setAnonymousEnumType (MemberDef * md)
Definition at line 4759 of file memberdef.cpp.
References MemberDefImpl::annEnumType, and m_impl.
Referenced by MemberList::countEnumValues().
setAnonymousUsed()
void MemberDef::setAnonymousUsed ()
Definition at line 4581 of file memberdef.cpp.
References MemberDefImpl::annUsed, and m_impl.
Referenced by writeDeclaration().
setArgsString()
void MemberDef::setArgsString (const char * as)
Definition at line 4737 of file memberdef.cpp.
References MemberDefImpl::args, and m_impl.
Referenced by VhdlDocGen::writeVHDLDeclaration().
setArgumentList()
void MemberDef::setArgumentList (ArgumentList * al)
Definition at line 3905 of file memberdef.cpp.
References MemberDefImpl::defArgList, and m_impl.
Referenced by combineDeclarationAndDefinition(), and createTemplateInstanceMember().
setBitfields()
void MemberDef::setBitfields (const char * s)
Definition at line 4677 of file memberdef.cpp.
References MemberDefImpl::bitfields, and m_impl.
Referenced by addVariableToClass(), createTagLessInstance(), and findUsingDeclImports().
setBriefDescription()
void MemberDef::setBriefDescription (const char * b, const char * briefFile, int briefLine) virtual
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Reimplemented from Definition.
Definition at line 1140 of file memberdef.cpp.
References m_isLinkableCached, and Definition::setBriefDescription().
Referenced by addEnumValuesToEnums(), addInstance(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), ClassDef::addMembersToTemplateInstance(), addMethodToClass(), addVariableToClass(), buildFunctionList(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findDefineDocumentation(), findEnumDocumentation(), findEnums(), findFriends(), findMember(), findUsingDeclImports(), and inheritDocumentation().
setCategory()
void MemberDef::setCategory (ClassDef * def)
Definition at line 4830 of file memberdef.cpp.
References MemberDefImpl::category, and m_impl.
Referenced by ClassDef::mergeCategory().
setCategoryRelation()
void MemberDef::setCategoryRelation (MemberDef * md)
Definition at line 4840 of file memberdef.cpp.
References MemberDefImpl::categoryRelation, and m_impl.
Referenced by ClassDef::mergeCategory().
setDeclArgumentList()
void MemberDef::setDeclArgumentList (ArgumentList * al)
Definition at line 3911 of file memberdef.cpp.
References MemberDefImpl::declArgList, and m_impl.
Referenced by combineDeclarationAndDefinition().
setDefinition()
void MemberDef::setDefinition (const char * d)
Definition at line 4648 of file memberdef.cpp.
References MemberDefImpl::def, and m_impl.
Referenced by addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addVariableToClass(), buildFunctionList(), createTemplateInstanceMember(), findEnums(), findMember(), and findUsingDeclImports().
setDefinitionTemplateParameterLists()
void MemberDef::setDefinitionTemplateParameterLists (QList< ArgumentList > * lists)
Definition at line 1182 of file memberdef.cpp.
References copyArgumentLists(), MemberDefImpl::defTmpArgLists, and m_impl.
Referenced by deepCopy(), and findMember().
setDocsForDefinition()
void MemberDef::setDocsForDefinition (bool b)
Definition at line 4800 of file memberdef.cpp.
References MemberDefImpl::docsForDefinition, and m_impl.
Referenced by addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), buildFunctionList(), combineDeclarationAndDefinition(), findDefineDocumentation(), findEnumDocumentation(), findEnums(), findFriends(), findMember(), and inheritDocumentation().
setDocumentation()
void MemberDef::setDocumentation (const char * d, const char * docFile, int docLine, bool stripWhiteSpace = TRUE) virtual
Sets the documentation of this definition to d.
Reimplemented from Definition.
Definition at line 1134 of file memberdef.cpp.
References m_isLinkableCached, and Definition::setDocumentation().
Referenced by addEnumValuesToEnums(), addInstance(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), ClassDef::addMembersToTemplateInstance(), addMethodToClass(), addVariableToClass(), buildFunctionList(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findDefineDocumentation(), findEnumDocumentation(), findEnums(), findFriends(), findMember(), findUsingDeclImports(), and inheritDocumentation().
setDocumentedEnumValues()
void MemberDef::setDocumentedEnumValues (bool value)
Definition at line 4754 of file memberdef.cpp.
References MemberDefImpl::docEnumValues, and m_impl.
Referenced by findDEV().
setEnumBaseType()
void MemberDef::setEnumBaseType (const QCString & type)
Definition at line 4845 of file memberdef.cpp.
References MemberDefImpl::enumBaseType, and m_impl.
Referenced by findEnums().
setEnumClassScope()
void MemberDef::setEnumClassScope (ClassDef * cd)
Definition at line 4747 of file memberdef.cpp.
References MemberDefImpl::classDef, m_impl, m_isConstructorCached, and m_isLinkableCached.
Referenced by addEnumValuesToEnums().
setEnumScope()
void MemberDef::setEnumScope (MemberDef * md, bool livesInsideEnum = FALSE)
Definition at line 3406 of file memberdef.cpp.
References MemberDefImpl::enumScope, getGroupDef(), getGroupFileName(), getGroupHasDocs(), getGroupPri(), getGroupStartLine(), MemberDefImpl::group, MemberDefImpl::groupFileName, MemberDefImpl::groupHasDocs, MemberDefImpl::grouppri, MemberDefImpl::groupStartLine, livesInsideEnum(), MemberDefImpl::livesInsideEnum, m_impl, and m_isLinkableCached.
Referenced by addEnumValuesToEnums().
setExplicitExternal()
void MemberDef::setExplicitExternal (bool b)
Definition at line 4690 of file memberdef.cpp.
References MemberDefImpl::explExt, and m_impl.
Referenced by addEnumValuesToEnums().
setFileDef()
void MemberDef::setFileDef (FileDef * fd)
Definition at line 4653 of file memberdef.cpp.
References MemberDefImpl::fileDef, m_impl, m_isConstructorCached, m_isDestructorCached, and m_isLinkableCached.
Referenced by addEnumValuesToEnums(), addInterfaceOrServiceToServiceOrSingleton(), addMethodToClass(), buildFunctionList(), findDefineDocumentation(), and findEnums().
setFromAnonymousMember()
void MemberDef::setFromAnonymousMember (MemberDef * m)
Definition at line 4784 of file memberdef.cpp.
References MemberDefImpl::annMemb, and m_impl.
Referenced by addVariableToClass().
setFromAnonymousScope()
void MemberDef::setFromAnonymousScope (bool b)
Definition at line 4779 of file memberdef.cpp.
References MemberDefImpl::annScope, and m_impl.
Referenced by addVariableToClass(), and MemberList::writePlainDeclarations().
setGroupAlias()
void MemberDef::setGroupAlias (MemberDef * md)
Definition at line 4805 of file memberdef.cpp.
References MemberDefImpl::groupAlias, and m_impl.
Referenced by GroupDef::insertMember().
setGroupDef()
void MemberDef::setGroupDef (GroupDef * gd, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs, MemberDef * member = 0)
Definition at line 3392 of file memberdef.cpp.
References MemberDefImpl::group, MemberDefImpl::groupFileName, MemberDefImpl::groupHasDocs, MemberDefImpl::groupMember, MemberDefImpl::grouppri, MemberDefImpl::groupStartLine, m_impl, and m_isLinkableCached.
Referenced by addMemberToGroups(), combineDeclarationAndDefinition(), MemberGroup::insertMember(), and ClassDef::setGroupDefForAllMembers().
setHasDocumentedParams()
void MemberDef::setHasDocumentedParams (bool b)
Definition at line 4722 of file memberdef.cpp.
References MemberDefImpl::hasDocumentedParams, and m_impl.
Referenced by detectNoDocumentedParams().
setHasDocumentedReturnType()
void MemberDef::setHasDocumentedReturnType (bool b)
Definition at line 4727 of file memberdef.cpp.
References MemberDefImpl::hasDocumentedReturnType, and m_impl.
Referenced by detectNoDocumentedParams().
setHidden()
void MemberDef::setHidden (bool b) virtual
Reimplemented from Definition.
Definition at line 1152 of file memberdef.cpp.
References m_isLinkableCached, and Definition::setHidden().
Referenced by addVariableToClass(), and findMember().
setInbodyDocumentation()
void MemberDef::setInbodyDocumentation (const char * d, const char * docFile, int docLine) virtual
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Reimplemented from Definition.
Definition at line 1146 of file memberdef.cpp.
References m_isLinkableCached, and Definition::setInbodyDocumentation().
Referenced by addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), ClassDef::addMembersToTemplateInstance(), addMethodToClass(), addVariableToClass(), buildFunctionList(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findDefineDocumentation(), findEnumDocumentation(), findEnums(), findFriends(), findMember(), findUsingDeclImports(), and inheritDocumentation().
setInheritsDocsFrom()
void MemberDef::setInheritsDocsFrom (MemberDef * md)
Definition at line 4732 of file memberdef.cpp.
References MemberDefImpl::docProvider, and m_impl.
Referenced by inheritDocumentation().
setInitializer()
void MemberDef::setInitializer (const char * i)
Definition at line 3499 of file memberdef.cpp.
References initializer(), MemberDefImpl::initializer, MemberDefImpl::initLines, and m_impl.
Referenced by addEnumValuesToEnums(), addMemberDocs(), addVariableToClass(), createTagLessInstance(), findMember(), and findUsingDeclImports().
setMaxInitLines()
void MemberDef::setMaxInitLines (int lines)
Definition at line 4682 of file memberdef.cpp.
References m_impl, and MemberDefImpl::userInitLines.
Referenced by addEnumValuesToEnums(), addMemberDocs(), addVariableToClass(), createTagLessInstance(), findDefineDocumentation(), and findUsingDeclImports().
setMemberClass()
void MemberDef::setMemberClass (ClassDef * cd)
Definition at line 3421 of file memberdef.cpp.
References MemberDefImpl::classDef, m_impl, m_isConstructorCached, m_isLinkableCached, and Definition::setOuterScope().
Referenced by addEnumValuesToEnums(), addInterfaceOrServiceToServiceOrSingleton(), ClassDef::addMembersToTemplateInstance(), addMethodToClass(), addVariableToClass(), createTagLessInstance(), findEnums(), findMember(), and findUsingDeclImports().
setMemberDeclaration()
void MemberDef::setMemberDeclaration (MemberDef * md)
Definition at line 4820 of file memberdef.cpp.
References m_impl, and MemberDefImpl::memDec.
Referenced by combineDeclarationAndDefinition().
setMemberDefinition()
void MemberDef::setMemberDefinition (MemberDef * md)
Definition at line 4815 of file memberdef.cpp.
References m_impl, and MemberDefImpl::memDef.
Referenced by combineDeclarationAndDefinition().
setMemberGroup()
void MemberDef::setMemberGroup (MemberGroup * grp)
Definition at line 3319 of file memberdef.cpp.
References m_impl, and MemberDefImpl::memberGroup.
Referenced by addMembersToMemberGroup().
setMemberGroupId()
void MemberDef::setMemberGroupId (int id)
Definition at line 4769 of file memberdef.cpp.
References MemberDefImpl::grpId, Definition::id(), and m_impl.
Referenced by addEnumValuesToEnums(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), ClassDef::addMembersToTemplateInstance(), addMethodToClass(), addVariableToClass(), buildFunctionList(), createTagLessInstance(), findDefineDocumentation(), findEnumDocumentation(), findEnums(), findMember(), and findUsingDeclImports().
setMemberSpecifiers()
void MemberDef::setMemberSpecifiers (uint64 s)
Definition at line 4667 of file memberdef.cpp.
References m_impl, and MemberDefImpl::memSpec.
Referenced by addInstance(), addInterfaceOrServiceToServiceOrSingleton(), ClassDef::addMembersToTemplateInstance(), addMethodToClass(), addVariableToClass(), buildFunctionList(), createTagLessInstance(), findEnums(), findMember(), findUsingDeclImports(), and setGlobalType().
setMemberType()
void MemberDef::setMemberType (MemberType t)
Definition at line 4642 of file memberdef.cpp.
References m_impl, m_isLinkableCached, and MemberDefImpl::mtype.
Referenced by ClassDef::reclassifyMember().
setNamespace()
void MemberDef::setNamespace (NamespaceDef * nd)
Definition at line 3429 of file memberdef.cpp.
References m_impl, MemberDefImpl::nspace, and Definition::setOuterScope().
Referenced by addEnumValuesToEnums(), buildFunctionList(), and findEnums().
setProtection()
void MemberDef::setProtection (Protection p)
Definition at line 4661 of file memberdef.cpp.
References m_impl, m_isLinkableCached, and MemberDefImpl::prot.
Referenced by addVariableToClass().
setPrototype()
void MemberDef::setPrototype (bool p)
Definition at line 4764 of file memberdef.cpp.
References m_impl, and MemberDefImpl::proto.
Referenced by buildFunctionList(), and findMember().
setReadAccessor()
void MemberDef::setReadAccessor (const char * r)
Definition at line 4695 of file memberdef.cpp.
References m_impl, and MemberDefImpl::read.
Referenced by addVariableToClass().
setReimplements()
void MemberDef::setReimplements (MemberDef * md)
Definition at line 868 of file memberdef.cpp.
References m_impl, and MemberDefImpl::redefines.
Referenced by computeMemberRelations().
setRelatedAlso()
void MemberDef::setRelatedAlso (ClassDef * cd)
Definition at line 4742 of file memberdef.cpp.
References m_impl, and MemberDefImpl::relatedAlso.
Referenced by findMember(), and transferRelatedFunctionDocumentation().
setSectionList()
void MemberDef::setSectionList (Definition * d, MemberList * sl)
Definition at line 3577 of file memberdef.cpp.
References SDict< T >::append(), MemberDefImpl::classSectionSDict, and m_impl.
Referenced by NamespaceDef::addMemberToList(), FileDef::addMemberToList(), and ClassDef::addMemberToList().
setTagInfo()
void MemberDef::setTagInfo (TagInfo * i)
Definition at line 4021 of file memberdef.cpp.
References MemberDefImpl::anc, TagInfo::anchor, MemberDefImpl::explicitOutputFileBase, TagInfo::fileName, m_impl, Definition::setReference(), stripExtension(), and TagInfo::tagName.
Referenced by addEnumValuesToEnums(), addInstance(), addInterfaceOrServiceToServiceOrSingleton(), addMethodToClass(), addVariableToClass(), addVariableToFile(), buildFunctionList(), findDefineDocumentation(), findEnums(), and findMember().
setTemplateMaster()
void MemberDef::setTemplateMaster (MemberDef * mt)
Definition at line 4794 of file memberdef.cpp.
References m_impl, m_isLinkableCached, and MemberDefImpl::templateMaster.
Referenced by ClassDef::addMembersToTemplateInstance().
setTemplateSpecialization()
void MemberDef::setTemplateSpecialization (bool b)
Definition at line 4705 of file memberdef.cpp.
References m_impl, and MemberDefImpl::tspec.
Referenced by findMember().
setType()
void MemberDef::setType (const char * t)
Definition at line 3931 of file memberdef.cpp.
References m_impl, and MemberDefImpl::type.
Referenced by VhdlDocGen::writeVHDLDeclaration().
setTypeConstraints()
void MemberDef::setTypeConstraints (ArgumentList * al)
Definition at line 3917 of file memberdef.cpp.
References m_impl, and MemberDefImpl::typeConstraints.
Referenced by addInterfaceOrServiceToServiceOrSingleton(), addMethodToClass(), buildFunctionList(), and findMember().
setWriteAccessor()
void MemberDef::setWriteAccessor (const char * w)
Definition at line 4700 of file memberdef.cpp.
References m_impl, and MemberDefImpl::write.
Referenced by addVariableToClass().
showInCallGraph()
bool MemberDef::showInCallGraph () const
Definition at line 4487 of file memberdef.cpp.
References isConstructor(), isDestructor(), isFunction(), isObjCMethod(), and isSlot().
Referenced by addDocCrossReference(), and DotCallGraph::buildGraph().
templateArguments()
ArgumentList * MemberDef::templateArguments () const
Definition at line 4551 of file memberdef.cpp.
References m_impl, and MemberDefImpl::tArgList.
Referenced by MemberContext::Private::addTemplateDecls(), findGlobalMember(), findUsingDeclImports(), GroupDef::insertMember(), MemberContext::Private::templateArgs(), and writeMemberTemplateLists().
templateMaster()
MemberDef * MemberDef::templateMaster () const
Definition at line 4596 of file memberdef.cpp.
References m_impl, and MemberDefImpl::templateMaster.
typeConstraints()
const ArgumentList * MemberDef::typeConstraints () const
Definition at line 5126 of file memberdef.cpp.
References m_impl, and MemberDefImpl::typeConstraints.
Referenced by MemberContext::Private::typeConstraints().
typeString()
const char * MemberDef::typeString () const
Definition at line 4064 of file memberdef.cpp.
References m_impl, and MemberDefImpl::type.
Referenced by addClassMemberNameToIndex(), FlowChart::addFlowChart(), addMemberToSearchIndex(), addVariableToClass(), MemberList::countEnumValues(), createTagLessInstance(), detectNoDocumentedParams(), findGlobalMember(), findUsedClassesForClass(), findUsingDeclImports(), generateDEFForMember(), generateDocbookForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getCanonicalTypeForIdentifier(), ClassDef::internalInsertMember(), newResolveTypedef(), processTagLessClasses(), resolveTypeDef(), setGlobalType(), substTypedef(), MemberContext::Private::templateAlias(), MemberContext::Private::type(), writeColumn(), ClassDef::writeMemberList(), writeTable(), VhdlDocGen::writeTagFile(), writeTagFile(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLTypeDocumentation().
unlock()
void MemberDef::unlock () const private
virtualness()
Specifier MemberDef::virtualness (int count = 0) const
Definition at line 3589 of file memberdef.cpp.
References Definition::getDefFileName(), Definition::getDefLine(), m_impl, Definition::name(), Normal, reimplements(), MemberDefImpl::virt, Virtual, virtualness(), and warn().
Referenced by _writeReimplements(), PerlModGenerator::addListOfAllMembers(), computeMemberRelations(), createTagLessInstance(), generateDEFForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getLabels(), MemberContext::Private::implementedBy(), MemberContext::Private::implements(), GroupDef::insertMember(), ClassDef::internalInsertMember(), MemberContext::Private::reimplementedBy(), MemberContext::Private::reimplements(), virtualness(), writeListOfAllMembers(), and ClassDef::writeMemberList().
visibleMemberGroup()
bool MemberDef::visibleMemberGroup (bool hideNoHeader)
Definition at line 3324 of file memberdef.cpp.
References MemberGroup::header(), m_impl, and MemberDefImpl::memberGroup.
warnIfUndocumented()
void MemberDef::warnIfUndocumented ()
Definition at line 3213 of file memberdef.cpp.
References argsString(), Config_getBool, getClassDef(), Definition::getDefFileName(), Definition::getDefLine(), getFileDef(), getGroupDef(), Definition::getLanguage(), getNamespaceDef(), Definition::hasUserDocumentation(), isDeleted(), isDetailedSectionLinkable(), isFriendClass(), isReference(), m_impl, MemberDefImpl::memberGroup, memberTypeName(), Definition::name(), MemberDefImpl::prot, protectionLevelVisible(), SrcLangExt_Fortran, warn_undoc(), and warnIfUndocumentedParams().
Referenced by writeDeclaration(), MemberList::writePlainDeclarations(), and VhdlDocGen::writeVHDLDeclaration().
warnIfUndocumentedParams()
void MemberDef::warnIfUndocumentedParams ()
Definition at line 3258 of file memberdef.cpp.
References Config_getBool, Definition::getDefFileName(), Definition::getDefLine(), hasDocumentation(), hasDocumentedParams(), hasDocumentedReturnType(), isFunction(), qualifiedName(), Doxygen::suppressDocWarnings, and warn_doc_error().
Referenced by warnIfUndocumented(), and writeDocumentation().
writeDeclaration()
void MemberDef::writeDeclaration (OutputList & ol, ClassDef * cd, NamespaceDef * nd, FileDef * fd, GroupDef * gd, bool inGroup, ClassDef * inheritFrom = 0, const char * inheritId = 0)
printf("startMemberItem for %s\n",name().data());
init.isEmpty() && initLines==0 && // one line initializer
Definition at line 1419 of file memberdef.cpp.
References _addToSearchIndex(), IndexList::addIndexItem(), anchor(), MemberDefImpl::annEnumType, MemberDefImpl::annMemb, argsString(), MemberDefImpl::bitfields, briefDescription(), Definition::briefFile(), Definition::briefLine(), MemberDefImpl::classDef, Config_getBool, OutputList::disable(), OutputList::disableAllBut(), Definition::displayName(), OutputList::docify(), OutputList::enable(), OutputList::endAnonTypeScope(), OutputList::endDoxyAnchor(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberItem(), OutputList::endMemberTemplateParams(), OutputList::endParagraph(), OutputList::endTextLink(), OutputList::endTypewriter(), excpString(), MemberDefImpl::fileDef, getAnonymousEnumType(), Definition::getBodyDef(), getClass(), getClassDef(), getClassDefOfAnonymousType(), getFileDef(), getGroupDef(), Definition::getLanguage(), getLanguageSpecificSeparator(), getNamespaceDef(), Definition::getOuterScope(), getOutputFileBase(), MemberDefImpl::group, hasDocumentation(), hasOneLineInitializer(), OutputGenerator::Html, Doxygen::indexList, MemberDefImpl::initializer, OutputList::insertMemberAlign(), isAddable(), isAlias(), isDefine(), isDetailedSectionLinkable(), isDocumentedFriendClass(), DocRoot::isEmpty(), OutputList::isEnabled(), isEnumerate(), isEvent(), isGettable(), isImplementation(), isObjCMethod(), isObjCProperty(), isPrivateGettable(), isPrivateSettable(), isProperty(), isProtectedGettable(), isProtectedSettable(), isRaisable(), isReference(), isRemovable(), isSettable(), isStatic(), isTypedef(), OutputGenerator::Latex, linkifyText(), m_impl, OutputGenerator::Man, MemberType_EnumValue, MemberType_Friend, MemberType_Typedef, MemberDefImpl::mtype, Definition::name(), MemberDefImpl::nspace, OutputList::parseText(), OutputList::popGeneratorState(), Private, MemberDefImpl::prot, OutputList::pushGeneratorState(), removeAnonymousScopes(), OutputGenerator::RTF, s_indentLevel, setAnonymousUsed(), SrcLangExt_Cpp, OutputList::startAnonTypeScope(), OutputList::startDoxyAnchor(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberItem(), OutputList::startMemberTemplateParams(), OutputList::startParagraph(), OutputList::startTextLink(), OutputList::startTypewriter(), substitute(), MemberDefImpl::tArgList, theTranslator, Translator::trMore(), MemberDefImpl::type, validatingParseDoc(), varName, warnIfUndocumented(), ClassDef::writeDeclaration(), OutputList::writeDoc(), writeEnumDeclaration(), OutputList::writeLatexSpacing(), writeLink(), OutputList::writeNonBreakableSpace(), OutputList::writeString(), and writeTemplatePrefix().
Referenced by MemberList::writePlainDeclarations().
writeDocumentation()
void MemberDef::writeDocumentation (MemberList * ml, int memCount, int memTotal, OutputList & ol, const char * scName, Definition * container, bool inGroup, bool showEnumValues = FALSE, bool showInline = FALSE)
Writes the "detailed documentation" section of this member to all active output formats.
Definition at line 2541 of file memberdef.cpp.
References _writeCallerGraph(), _writeCallGraph(), _writeCategoryRelation(), _writeEnumValues(), _writeExamples(), _writeGroupInclude(), _writeReimplementedBy(), _writeReimplements(), _writeTypeConstraints(), anchor(), argsString(), argumentList(), brief, briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, MemberDefImpl::defArgList, definition(), DefinitionIntf::definitionType(), MemberDefImpl::defTmpArgLists, OutputList::disable(), OutputList::disableAll(), OutputList::disableAllBut(), NamespaceDef::displayName(), FileDef::displayName(), ClassDef::displayName(), Definition::docFile(), OutputList::docify(), Definition::docLine(), Argument::docs, documentation(), OutputList::enable(), OutputList::endBold(), OutputList::endCodeFragment(), OutputList::endDoxyAnchor(), OutputList::endIndent(), OutputList::endLabels(), OutputList::endMemberDoc(), OutputList::endMemberDocName(), OutputList::endMemberDocPrefixItem(), OutputList::endParagraph(), OutputList::endParameterList(), MemberDefImpl::enumBaseType, excpString(), extractDirection(), OutputList::generateDoc(), Definition::getBodyDef(), getClassDef(), Definition::getDefFileExtension(), getFileDef(), getGroupDef(), getLabels(), Definition::getLanguage(), getLanguageSpecificSeparator(), getNamespaceDef(), getOutputFileBase(), ParserManager::getParser(), ClassDef::getTemplateParameterLists(), Argument::hasDocumentation(), ArgumentList::hasDocumentation(), hasMultiLineInitializer(), hasOneLineInitializer(), OutputGenerator::Html, Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), Config::init(), MemberDefImpl::initializer, isDefine(), isDetailedSectionVisible(), isEnumerate(), isEnumValue(), isFunction(), isId(), VhdlDocGen::isMisc(), isObjCMethod(), ClassDef::isObjectiveC(), isStatic(), isTemplateSpecialization(), isTypedef(), isVariable(), linkifyText(), m_impl, MemberType_Define, MemberDefImpl::mtype, Argument::name, Definition::name(), ParserInterface::parseCode(), Doxygen::parserManager, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), ParserInterface::resetCodeParserState(), SrcLangExt_Cpp, SrcLangExt_VHDL, OutputList::startBold(), OutputList::startCodeFragment(), OutputList::startDoxyAnchor(), OutputList::startIndent(), OutputList::startLabels(), OutputList::startMemberDoc(), OutputList::startMemberDocName(), OutputList::startMemberDocPrefixItem(), OutputList::startParagraph(), substitute(), MemberDefImpl::tArgList, MemberDefImpl::templateMaster, theTranslator, Translator::trDefineValue(), Translator::trInitialValue(), DefinitionIntf::TypeFile, DefinitionIntf::TypeGroup, Doxygen::userComments, warnIfUndocumentedParams(), writeDefArgumentList(), writeEnumDeclaration(), writeExceptionList(), Definition::writeInlineCode(), OutputList::writeLabel(), OutputList::writeNonBreakableSpace(), VhdlDocGen::writeSource(), Definition::writeSourceDef(), Definition::writeSourceReffedBy(), Definition::writeSourceRefs(), OutputList::writeString(), writeTemplatePrefix(), and VhdlDocGen::writeVHDLTypeDocumentation().
Referenced by MemberList::writeDocumentation(), and MemberList::writeDocumentationPage().
writeEnumDeclaration()
void MemberDef::writeEnumDeclaration (OutputList & typeDecl, ClassDef * cd, NamespaceDef * nd, FileDef * fd, GroupDef * gd)
Definition at line 3783 of file memberdef.cpp.
References _addToSearchIndex(), Config_getInt, OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enable(), OutputList::endBold(), MemberDefImpl::enumBaseType, MemberDefImpl::enumFields, hasDocumentation(), hasDocumentedEnumValues(), hasOneLineInitializer(), OutputGenerator::Html, initializer(), isBriefSectionVisible(), isLinkableInProject(), OutputGenerator::Latex, OutputList::lineBreak(), m_impl, OutputGenerator::Man, Definition::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startBold(), OutputList::writeChar(), writeLink(), and OutputList::writeString().
Referenced by writeDeclaration(), writeDocumentation(), and MemberList::writePlainDeclarations().
writeLink()
void MemberDef::writeLink (OutputList & ol, ClassDef * cd, NamespaceDef * nd, FileDef * fd, GroupDef * gd, bool onlyText = FALSE) private
Definition at line 1191 of file memberdef.cpp.
References anchor(), MemberDefImpl::classDef, Config_getBool, NamespaceDef::displayName(), ClassDef::displayName(), displayName(), OutputList::docify(), OutputList::endBold(), MemberDefImpl::enumScope, getEnumScope(), getGroupDef(), Definition::getLanguage(), getLanguageSpecificSeparator(), GroupDef::getOutputFileBase(), getOutputFileBase(), getReference(), Definition::getReference(), isLinkable(), isObjCMethod(), isRelated(), isStatic(), MemberDefImpl::livesInsideEnum, m_impl, MemberType_EnumValue, MemberDefImpl::mtype, Definition::name(), MemberDefImpl::nspace, OutputList::startBold(), and OutputList::writeObjectLink().
Referenced by writeDeclaration(), and writeEnumDeclaration().
writeMemberDocSimple()
void MemberDef::writeMemberDocSimple (OutputList & ol, Definition * container)
Definition at line 3095 of file memberdef.cpp.
References MemberDefImpl::accessorClass, anchor(), ClassDef::anchor(), argsString(), MemberDefImpl::bitfields, brief, briefDescription(), Definition::briefFile(), Definition::briefLine(), DefinitionIntf::definitionType(), Definition::docFile(), OutputList::docify(), Definition::docLine(), documentation(), OutputList::endDoxyAnchor(), OutputList::endInlineMemberDoc(), OutputList::endInlineMemberName(), OutputList::endInlineMemberType(), fieldType(), OutputList::generateDoc(), Definition::getBodyDef(), Definition::getOuterScope(), getOutputFileBase(), ClassDef::getOutputFileBase(), ClassDef::getReference(), isObjCMethod(), isVariable(), linkifyText(), m_impl, Definition::name(), OutputList::startDoxyAnchor(), OutputList::startInlineMemberDoc(), OutputList::startInlineMemberName(), OutputList::startInlineMemberType(), DefinitionIntf::TypeClass, OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by MemberList::writeSimpleDocumentation().
writeTagFile()
void MemberDef::writeTagFile (FTextStream & tagFile)
Definition at line 3609 of file memberdef.cpp.
References anchor(), argsString(), convertToXML(), endl(), MemberDefImpl::enumFields, getOutputFileBase(), Doxygen::htmlFileExtension, Definition::id(), isLinkableInProject(), isReference(), isStatic(), isStrong(), m_impl, MemberType_DCOP, MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, MemberDefImpl::mtype, Definition::name(), Normal, Package, MemberDefImpl::prot, Protected, Public, typeString(), MemberDefImpl::virt, Virtual, and Definition::writeDocAnchorsToTagFile().
Referenced by MemberList::writeTagFile().
Member Data Documentation
m_impl
MemberDefImpl* MemberDef::m_impl private
Definition at line 435 of file memberdef.h.
Referenced by _computeIsConstructor(), _computeIsDestructor(), _computeLinkableInProject(), _writeCallerGraph(), _writeCallGraph(), _writeCategoryRelation(), _writeExamples(), _writeReimplementedBy(), _writeTypeConstraints(), accessorClass(), addExample(), anchor(), anonymousDeclShown(), argsString(), argumentList(), bitfieldString(), briefDescription(), cacheTypedefVal(), category(), categoryRelation(), copyArgumentNames(), createTemplateInstanceMember(), declaration(), declArgumentList(), deepCopy(), definition(), definitionTemplateParameterLists(), displayDefinition(), documentation(), enableCallerGraph(), enableCallGraph(), enumBaseType(), enumFieldList(), excpString(), extraTypeChars(), fieldType(), fromAnonymousMember(), fromAnonymousScope(), getAnonymousEnumType(), getCachedResolvedTypedef(), getCachedTypedefTemplSpec(), getCachedTypedefVal(), getClassDef(), getClassDefOfAnonymousType(), getDeclType(), getEnumScope(), getExamples(), getFileDef(), getGroupAlias(), getGroupDef(), getGroupFileName(), getGroupHasDocs(), getGroupPri(), getGroupStartLine(), getLabels(), getMemberGroup(), getMemberGroupId(), getMemberSpecifiers(), getNamespaceDef(), getOutputFileBase(), getReadAccessor(), getReference(), getSectionList(), getWriteAccessor(), hasCallerGraph(), hasCallGraph(), hasDocumentation(), hasDocumentedEnumValues(), hasDocumentedParams(), hasDocumentedReturnType(), hasExamples(), hasMultiLineInitializer(), hasOneLineInitializer(), inheritsDocsFrom(), initializer(), initializerLines(), insertEnumField(), insertReimplementedBy(), invalidateCachedArgumentTypes(), invalidateTypedefValCache(), isAbstract(), isAddable(), isAlias(), isAssign(), isAttribute(), isBound(), isBriefSectionVisible(), isConstrained(), isCopy(), isDCOP(), isDefault(), isDefine(), isDelete(), isDeleted(), isDetailedSectionLinkable(), isDocsForDefinition(), isEnumerate(), isEnumValue(), isEvent(), isExplicit(), isExternal(), isFinal(), isForeign(), isFriend(), isFriendClass(), isFriendToHide(), isFunction(), isFunctionPtr(), isGettable(), isImplementation(), isInitonly(), isInline(), isLinkable(), isMaybeAmbiguous(), isMaybeDefault(), isMaybeVoid(), isMutable(), isNew(), isNoExcept(), isNonAtomic(), isObjCMethod(), isObjCProperty(), isOptional(), isOverride(), isPrivateGettable(), isPrivateSettable(), isProperty(), isProtectedGettable(), isProtectedSettable(), isPrototype(), isPublished(), isRaisable(), isReadable(), isReadonly(), isReference(), isReimplementedBy(), isRelated(), isRemovable(), isRequired(), isRetain(), isSealed(), isSettable(), isSignal(), isSlot(), isStatic(), isStrong(), isStrongEnumValue(), isTemplateSpecialization(), isTransient(), isTypedef(), isTypedefValCached(), isUNOProperty(), isUnretained(), isVariable(), isWeak(), isWritable(), livesInsideEnum(), makeForeign(), makeImplementationDetail(), makeRelated(), memberDeclaration(), MemberDef(), memberDefinition(), memberType(), memberTypeName(), mergeMemberSpecifiers(), moveTo(), objCMethodName(), protection(), qualifiedName(), reimplementedBy(), reimplements(), relatedAlso(), setAccessorType(), setAnchor(), setAnonymousEnumType(), setAnonymousUsed(), setArgsString(), setArgumentList(), setBitfields(), setCategory(), setCategoryRelation(), setDeclArgumentList(), setDefinition(), setDefinitionTemplateParameterLists(), setDocsForDefinition(), setDocumentedEnumValues(), setEnumBaseType(), setEnumClassScope(), setEnumScope(), setExplicitExternal(), setFileDef(), setFromAnonymousMember(), setFromAnonymousScope(), setGroupAlias(), setGroupDef(), setHasDocumentedParams(), setHasDocumentedReturnType(), setInheritsDocsFrom(), setInitializer(), setMaxInitLines(), setMemberClass(), setMemberDeclaration(), setMemberDefinition(), setMemberGroup(), setMemberGroupId(), setMemberSpecifiers(), setMemberType(), setNamespace(), setProtection(), setPrototype(), setReadAccessor(), setReimplements(), setRelatedAlso(), setSectionList(), setTagInfo(), setTemplateMaster(), setTemplateSpecialization(), setType(), setTypeConstraints(), setWriteAccessor(), templateArguments(), templateMaster(), typeConstraints(), typeString(), virtualness(), visibleMemberGroup(), warnIfUndocumented(), writeDeclaration(), writeDocumentation(), writeEnumDeclaration(), writeLink(), writeMemberDocSimple(), writeTagFile(), and ~MemberDef().
m_isConstructorCached
uchar MemberDef::m_isConstructorCached private
Definition at line 437 of file memberdef.h.
Referenced by _computeIsConstructor(), isConstructor(), MemberDef(), moveTo(), setEnumClassScope(), setFileDef(), and setMemberClass().
m_isDestructorCached
uchar MemberDef::m_isDestructorCached private
Definition at line 438 of file memberdef.h.
Referenced by _computeIsDestructor(), isDestructor(), MemberDef(), and setFileDef().
m_isLinkableCached
uchar MemberDef::m_isLinkableCached private
Definition at line 436 of file memberdef.h.
Referenced by _computeLinkableInProject(), isLinkableInProject(), makeForeign(), makeRelated(), MemberDef(), moveTo(), setBriefDescription(), setDocumentation(), setEnumClassScope(), setEnumScope(), setFileDef(), setGroupDef(), setHidden(), setInbodyDocumentation(), setMemberClass(), setMemberType(), setProtection(), and setTemplateMaster().
s_indentLevel
int MemberDef::s_indentLevel = 0 static private
Definition at line 426 of file memberdef.h.
Referenced by writeDeclaration().
visited
bool MemberDef::visited
Definition at line 399 of file memberdef.h.
Referenced by addListReference(), and addListReferences().
The documentation for this class was generated from the following files:
src/memberdef.h
src/memberdef.cpp