Doxygen: NamespaceMembersIndexContext::Private Class Reference
NamespaceMembersIndexContext::Private Class Reference
Classes
struct Cachable
Public Types
typedef bool(MemberDef::* MemberFunc) () const
Public Member Functions
Private ()
TemplateVariant get (const char *n) const
TemplateVariant getMembersFiltered (SharedPtr< TemplateList > &listRef, MemberFunc filter) const
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
Private Attributes
Cachable m_cache
Static Private Attributes
static PropertyMapper< NamespaceMembersIndexContext::Private > s_inst
Detailed Description
Definition at line 8158 of file context.cpp.
Member Typedef Documentation
MemberFunc
typedef bool(MemberDef::* NamespaceMembersIndexContext::Private::MemberFunc) () const
Definition at line 8188 of file context.cpp.
Constructor & Destructor Documentation
Private()
NamespaceMembersIndexContext::Private::Private () inline
Definition at line 8161 of file context.cpp.
References PropertyMapper< T >::addProperty(), all(), enums(), enumValues(), events(), fileName(), functions(), highlight(), Config::init(), macros(), properties(), related(), relPath(), s_inst, subhighlight(), title(), typedefs(), and variables().
Member Function Documentation
all()
TemplateVariant NamespaceMembersIndexContext::Private::all () const inline
Definition at line 8217 of file context.cpp.
References NamespaceMembersIndexContext::Private::Cachable::all, getMembersFiltered(), and m_cache.
Referenced by Private().
enums()
TemplateVariant NamespaceMembersIndexContext::Private::enums () const inline
Definition at line 8233 of file context.cpp.
References NamespaceMembersIndexContext::Private::Cachable::enums, getMembersFiltered(), MemberDef::isEnumerate(), and m_cache.
Referenced by Private().
enumValues()
TemplateVariant NamespaceMembersIndexContext::Private::enumValues () const inline
Definition at line 8237 of file context.cpp.
References NamespaceMembersIndexContext::Private::Cachable::enumValues, getMembersFiltered(), MemberDef::isEnumValue(), and m_cache.
Referenced by Private().
events()
TemplateVariant NamespaceMembersIndexContext::Private::events () const inline
Definition at line 8249 of file context.cpp.
Referenced by Private().
fileName()
TemplateVariant NamespaceMembersIndexContext::Private::fileName () const inline
Definition at line 8257 of file context.cpp.
Referenced by Private().
functions()
TemplateVariant NamespaceMembersIndexContext::Private::functions () const inline
Definition at line 8221 of file context.cpp.
References NamespaceMembersIndexContext::Private::Cachable::functions, getMembersFiltered(), MemberDef::isFunction(), and m_cache.
Referenced by Private().
get()
TemplateVariant NamespaceMembersIndexContext::Private::get (const char * n) const inline
Definition at line 8184 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by NamespaceMembersIndexContext::get().
getMembersFiltered()
TemplateVariant NamespaceMembersIndexContext::Private::getMembersFiltered (SharedPtr< TemplateList > & listRef, MemberFunc filter) const inline
Definition at line 8189 of file context.cpp.
References MemberContext::alloc(), TemplateList::alloc(), TemplateList::append(), Doxygen::functionNameSDict, SharedPtr< T >::get(), MemberDef::getNamespaceDef(), NamespaceDef::isLinkableInProject(), MemberDef::isLinkableInProject(), SDict< MemberName >::Iterator, Definition::name(), and SharedPtr< T >::reset().
Referenced by all(), enums(), enumValues(), functions(), typedefs(), and variables().
highlight()
TemplateVariant NamespaceMembersIndexContext::Private::highlight () const inline
Definition at line 8265 of file context.cpp.
Referenced by Private().
macros()
TemplateVariant NamespaceMembersIndexContext::Private::macros () const inline
Definition at line 8241 of file context.cpp.
Referenced by Private().
properties()
TemplateVariant NamespaceMembersIndexContext::Private::properties () const inline
Definition at line 8245 of file context.cpp.
Referenced by Private().
related()
TemplateVariant NamespaceMembersIndexContext::Private::related () const inline
Definition at line 8253 of file context.cpp.
Referenced by Private().
relPath()
TemplateVariant NamespaceMembersIndexContext::Private::relPath () const inline
Definition at line 8261 of file context.cpp.
Referenced by Private().
subhighlight()
TemplateVariant NamespaceMembersIndexContext::Private::subhighlight () const inline
Definition at line 8269 of file context.cpp.
Referenced by Private().
title()
TemplateVariant NamespaceMembersIndexContext::Private::title () const inline
Definition at line 8273 of file context.cpp.
References theTranslator, and Translator::trNamespaceMembers().
Referenced by Private().
typedefs()
TemplateVariant NamespaceMembersIndexContext::Private::typedefs () const inline
Definition at line 8229 of file context.cpp.
References getMembersFiltered(), MemberDef::isTypedef(), m_cache, and NamespaceMembersIndexContext::Private::Cachable::typedefs.
Referenced by Private().
variables()
TemplateVariant NamespaceMembersIndexContext::Private::variables () const inline
Definition at line 8225 of file context.cpp.
References getMembersFiltered(), MemberDef::isVariable(), m_cache, and NamespaceMembersIndexContext::Private::Cachable::variables.
Referenced by Private().
Member Data Documentation
m_cache
Cachable NamespaceMembersIndexContext::Private::m_cache mutable private
Definition at line 8288 of file context.cpp.
Referenced by all(), enums(), enumValues(), functions(), typedefs(), and variables().
s_inst
PropertyMapper< NamespaceMembersIndexContext::Private > NamespaceMembersIndexContext::Private::s_inst static private
Definition at line 8289 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp