Doxygen: SymbolGroupListContext Class Reference
SymbolGroupListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static SymbolGroupListContext * alloc (const SearchIndexList *sil)
Private Member Functions
SymbolGroupListContext (const SearchIndexList *sil)
~SymbolGroupListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1244 of file context.h.
Constructor & Destructor Documentation
SymbolGroupListContext()
SymbolGroupListContext::SymbolGroupListContext (const SearchIndexList * sil) private
Definition at line 9709 of file context.cpp.
References p, and Private.
Referenced by alloc().
~SymbolGroupListContext()
SymbolGroupListContext::~SymbolGroupListContext () private
Definition at line 9715 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int SymbolGroupListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 1254 of file context.h.
References RefCountedContext::addRef().
alloc()
static SymbolGroupListContext* SymbolGroupListContext::alloc (const SearchIndexList * sil) inline static
Definition at line 1247 of file context.h.
References SymbolGroupListContext().
Referenced by SymbolIndexContext::Private::symbolGroups().
at()
TemplateVariant SymbolGroupListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 9726 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int SymbolGroupListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 9721 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * SymbolGroupListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 9731 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int SymbolGroupListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 1255 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* SymbolGroupListContext::p private
Definition at line 1260 of file context.h.
Referenced by at(), count(), createIterator(), SymbolGroupListContext(), and ~SymbolGroupListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp