Doxygen: LayoutErrorHandler Class Reference
LayoutErrorHandler Class Reference
Public Member Functions
LayoutErrorHandler (const char *fn)
bool warning (const QXmlParseException &exception)
bool error (const QXmlParseException &exception)
bool fatalError (const QXmlParseException &exception)
QString errorString ()
Private Attributes
QString errorMsg
QString fileName
Detailed Description
Definition at line 1287 of file layout.cpp.
Constructor & Destructor Documentation
LayoutErrorHandler()
LayoutErrorHandler::LayoutErrorHandler (const char * fn) inline
Definition at line 1290 of file layout.cpp.
Member Function Documentation
error()
bool LayoutErrorHandler::error (const QXmlParseException & exception) inline
Definition at line 1298 of file layout.cpp.
References err(), and fileName.
errorString()
QString LayoutErrorHandler::errorString () inline
Definition at line 1312 of file layout.cpp.
fatalError()
bool LayoutErrorHandler::fatalError (const QXmlParseException & exception) inline
Definition at line 1305 of file layout.cpp.
References err(), and fileName.
warning()
bool LayoutErrorHandler::warning (const QXmlParseException & exception) inline
Definition at line 1291 of file layout.cpp.
References fileName, and warn_uncond().
Member Data Documentation
errorMsg
QString LayoutErrorHandler::errorMsg private
Definition at line 1315 of file layout.cpp.
fileName
QString LayoutErrorHandler::fileName private
Definition at line 1316 of file layout.cpp.
Referenced by error(), fatalError(), and warning().
The documentation for this class was generated from the following file:
src/layout.cpp