Doxygen: FilterGroupBy Class Reference
FilterGroupBy Class Reference
The implementation of the "groupBy" filter.
Classes
struct ListElem
class SortList
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
Static Private Member Functions
static QCString determineSortKey (TemplateStructIntf *s, const QCString &attribName)
Detailed Description
The implementation of the "groupBy" filter.
Definition at line 957 of file template.cpp.
Member Function Documentation
apply()
static TemplateVariant FilterGroupBy::apply (const TemplateVariant & v, const TemplateVariant & args) inline static
Definition at line 976 of file template.cpp.
References TemplateList::alloc(), TemplateList::append(), TemplateListIntf::createIterator(), TemplateListIntf::ConstIterator::current(), determineSortKey(), FilterGroupBy::ListElem::key, TemplateVariant::List, TemplateVariant::String, TemplateListIntf::ConstIterator::toFirst(), TemplateVariant::toList(), TemplateListIntf::ConstIterator::toNext(), TemplateVariant::toString(), TemplateVariant::toStruct(), TemplateVariant::type(), and FilterGroupBy::ListElem::value.
determineSortKey()
static QCString FilterGroupBy::determineSortKey (TemplateStructIntf * s, const QCString & attribName) inline static private
Definition at line 1024 of file template.cpp.
References TemplateStructIntf::get(), and TemplateVariant::toString().
Referenced by apply().
The documentation for this class was generated from the following file:
src/template.cpp