Doxygen: PerlModOutputStream Class Reference
PerlModOutputStream Class Reference
Public Member Functions
PerlModOutputStream (FTextStream *t=0)
void add (char c)
void add (const char *s)
void add (QCString &s)
void add (int n)
void add (unsigned int n)
Public Attributes
QCString m_s
FTextStream * m_t
Detailed Description
Definition at line 49 of file perlmodgen.cpp.
Constructor & Destructor Documentation
PerlModOutputStream()
PerlModOutputStream::PerlModOutputStream (FTextStream * t = 0) inline
Definition at line 56 of file perlmodgen.cpp.
Member Function Documentation
add() [1/5]
void PerlModOutputStream::add (char c)
Definition at line 65 of file perlmodgen.cpp.
References m_s, and m_t.
Referenced by PerlModOutput::add(), PerlModOutput::continueBlock(), PerlModOutput::iaddField(), PerlModOutput::iaddFieldQuotedChar(), PerlModOutput::iaddFieldQuotedString(), PerlModOutput::iaddQuoted(), PerlModOutput::iclose(), PerlModOutput::indent(), and PerlModOutput::iopen().
add() [2/5]
void PerlModOutputStream::add (const char * s)
Definition at line 73 of file perlmodgen.cpp.
References m_s, and m_t.
add() [3/5]
void PerlModOutputStream::add (QCString & s)
Definition at line 81 of file perlmodgen.cpp.
References m_s, and m_t.
add() [4/5]
void PerlModOutputStream::add (int n)
Definition at line 89 of file perlmodgen.cpp.
References m_s, and m_t.
add() [5/5]
void PerlModOutputStream::add (unsigned int n)
Definition at line 97 of file perlmodgen.cpp.
References m_s, and m_t.
Member Data Documentation
m_s
QCString PerlModOutputStream::m_s
Definition at line 53 of file perlmodgen.cpp.
Referenced by add(), and PerlModOutput::icloseSave().
m_t
FTextStream* PerlModOutputStream::m_t
Definition at line 54 of file perlmodgen.cpp.
Referenced by add().
The documentation for this class was generated from the following file:
src/perlmodgen.cpp