Doxygen: GenericsSDict Class Reference
GenericsSDict Class Reference
#include <classlist.h>
Public Member Functions
GenericsSDict ()
~GenericsSDict ()
void insert (const QCString &key, ClassDef *cd)
ClassDef * find (const QCString &key)
Private Attributes
SDict< GenericsCollection > m_dict
Detailed Description
Definition at line 76 of file classlist.h.
Constructor & Destructor Documentation
GenericsSDict()
GenericsSDict::GenericsSDict () inline
Definition at line 79 of file classlist.h.
References m_dict, and SDict< T >::setAutoDelete().
~GenericsSDict()
GenericsSDict::~GenericsSDict () inline
Definition at line 80 of file classlist.h.
Member Function Documentation
find()
ClassDef * GenericsSDict::find (const QCString & key)
Definition at line 183 of file classlist.cpp.
References SDict< T >::find(), m_dict, and stringToArgumentList().
Referenced by findClassRelation(), and findClassWithinClassContext().
insert()
void GenericsSDict::insert (const QCString & key, ClassDef * cd)
Definition at line 163 of file classlist.cpp.
References SDict< T >::append(), SDict< T >::find(), m_dict, and stringToArgumentList().
Referenced by addClassToContext().
Member Data Documentation
m_dict
SDict<GenericsCollection> GenericsSDict::m_dict private
Definition at line 84 of file classlist.h.
Referenced by find(), GenericsSDict(), and insert().
The documentation for this class was generated from the following files:
src/classlist.h
src/classlist.cpp