Doxygen: TemplateListIntf::ConstIterator Class Reference
TemplateListIntf::ConstIterator Class Reference abstract
Abstract interface for a iterator of a list.
#include <template.h>
Public Member Functions
virtual ~ConstIterator ()
Destructor for the iterator.
virtual void toFirst ()=0
Moves iterator to the first element in the list.
virtual void toLast ()=0
Moves iterator to the last element in the list.
virtual void toNext ()=0
Moves iterator to the next element in the list.
virtual void toPrev ()=0
Moves iterator to the previous element in the list.
virtual bool current (TemplateVariant &v) const =0
Detailed Description
Abstract interface for a iterator of a list.
Definition at line 333 of file template.h.
Constructor & Destructor Documentation
~ConstIterator()
virtual TemplateListIntf::ConstIterator::~ConstIterator () inline virtual
Destructor for the iterator.
Definition at line 337 of file template.h.
Member Function Documentation
current()
virtual bool TemplateListIntf::ConstIterator::current (TemplateVariant & v) const pure virtual
Implemented in TemplateListConstIterator, and GenericConstIterator.
Referenced by FilterListSort::apply(), FilterGroupBy::apply(), FilterPaginate::apply(), FilterAlphaIndex::apply(), computeMaxDepth(), computeNumNodesAtLevel(), computePreferredDepth(), FilterFlatten::flatten(), TemplateNodeFor::render(), TemplateNodeMarkers::render(), and TemplateNodeTree::renderChildren().
toFirst()
virtual void TemplateListIntf::ConstIterator::toFirst () pure virtual
Moves iterator to the first element in the list.
Implemented in TemplateListConstIterator, and GenericConstIterator.
Referenced by FilterListSort::apply(), FilterGroupBy::apply(), FilterPaginate::apply(), FilterAlphaIndex::apply(), computeMaxDepth(), computeNumNodesAtLevel(), computePreferredDepth(), FilterFlatten::flatten(), TemplateNodeFor::render(), TemplateNodeMarkers::render(), and TemplateNodeTree::renderChildren().
toLast()
virtual void TemplateListIntf::ConstIterator::toLast () pure virtual
Moves iterator to the last element in the list.
Implemented in TemplateListConstIterator, and GenericConstIterator.
Referenced by TemplateNodeFor::render().
toNext()
virtual void TemplateListIntf::ConstIterator::toNext () pure virtual
Moves iterator to the next element in the list.
Implemented in TemplateListConstIterator, and GenericConstIterator.
Referenced by FilterListSort::apply(), FilterGroupBy::apply(), FilterPaginate::apply(), FilterAlphaIndex::apply(), computeMaxDepth(), computeNumNodesAtLevel(), computePreferredDepth(), FilterFlatten::flatten(), TemplateNodeFor::render(), and TemplateNodeTree::renderChildren().
toPrev()
virtual void TemplateListIntf::ConstIterator::toPrev () pure virtual
Moves iterator to the previous element in the list.
Implemented in TemplateListConstIterator, and GenericConstIterator.
Referenced by TemplateNodeFor::render().
The documentation for this class was generated from the following file:
src/template.h