Doxygen: MemberIndexList Class Reference
MemberIndexList Class Reference
Public Types
typedef MemberDef ElementType
Public Member Functions
MemberIndexList (uint letter)
~MemberIndexList ()
int compareValues (const MemberDef *md1, const MemberDef *md2) const
uint letter () const
Private Attributes
uint m_letter
Detailed Description
Definition at line 119 of file index.cpp.
Member Typedef Documentation
ElementType
typedef MemberDef MemberIndexList::ElementType
Definition at line 122 of file index.cpp.
Constructor & Destructor Documentation
MemberIndexList()
MemberIndexList::MemberIndexList (uint letter) inline
Definition at line 123 of file index.cpp.
~MemberIndexList()
MemberIndexList::~MemberIndexList () inline
Definition at line 124 of file index.cpp.
Member Function Documentation
compareValues()
int MemberIndexList::compareValues (const MemberDef * md1, const MemberDef * md2) const inline
Definition at line 125 of file index.cpp.
References Definition::name(), and MemberDef::qualifiedName().
letter()
uint MemberIndexList::letter () const inline
Definition at line 134 of file index.cpp.
References m_letter.
Referenced by renderMemberIndicesAsJs(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeMemberList(), writeNamespaceMemberIndexFiltered(), and writeQuickMemberIndex().
Member Data Documentation
m_letter
uint MemberIndexList::m_letter private
Definition at line 136 of file index.cpp.
Referenced by letter().
The documentation for this class was generated from the following file:
src/index.cpp