Doxygen: CompAccept< T > Class Template Reference
CompAccept< T > Class Template Reference
Default accept implementation for compound nodes in the abstract syntax tree.
#include <docparser.h>
Public Member Functions
CompAccept ()
virtual ~CompAccept ()
void accept (T *obj, DocVisitor *v)
const QList< DocNode > & children () const
QList< DocNode > & children ()
Protected Attributes
QList< DocNode > m_children
Detailed Description
template<class T>
class CompAccept< T >
Default accept implementation for compound nodes in the abstract syntax tree.
Definition at line 172 of file docparser.h.
Constructor & Destructor Documentation
CompAccept()
template<class T> CompAccept< T >::CompAccept () inline
Definition at line 175 of file docparser.h.
~CompAccept()
template<class T> virtual CompAccept< T >::~CompAccept () inline virtual
Definition at line 176 of file docparser.h.
Member Function Documentation
accept()
template<class T> void CompAccept< T >::accept (T * obj, DocVisitor * v) inline
Definition at line 177 of file docparser.h.
Referenced by DocAutoList::accept(), DocAutoListItem::accept(), DocTitle::accept(), DocXRefItem::accept(), DocImage::accept(), DocDotFile::accept(), DocMscFile::accept(), DocDiaFile::accept(), DocVhdlFlow::accept(), DocLink::accept(), DocRef::accept(), DocInternalRef::accept(), DocHRef::accept(), DocHtmlHeader::accept(), DocHtmlDescTitle::accept(), DocHtmlDescList::accept(), DocSection::accept(), DocSecRefItem::accept(), DocSecRefList::accept(), DocInternal::accept(), DocParBlock::accept(), DocSimpleList::accept(), DocHtmlList::accept(), DocParamSect::accept(), DocPara::accept(), DocHtmlListItem::accept(), DocHtmlDescData::accept(), DocHtmlCell::accept(), DocHtmlCaption::accept(), DocHtmlRow::accept(), DocHtmlBlockQuote::accept(), DocText::accept(), and DocRoot::accept().
children() [1/2]
template<class T> const QList<DocNode>& CompAccept< T >::children () const inline
Definition at line 185 of file docparser.h.
Referenced by DocHtmlTable::computeTableGrid(), flattenParagraphs(), HtmlDocVisitor::forceEndParagraph(), HtmlDocVisitor::forceStartParagraph(), insideStyleChangeThatIsOutsideParagraph(), isSeparatedParagraph(), HtmlDocVisitor::visitPost(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and XmlDocVisitor::visitPre().
children() [2/2]
template<class T> QList<DocNode>& CompAccept< T >::children () inline
Definition at line 186 of file docparser.h.
Member Data Documentation
m_children
template<class T> QList<DocNode> CompAccept< T >::m_children protected
Definition at line 189 of file docparser.h.
Referenced by CompAccept< DocHtmlTable >::accept(), CompAccept< DocHtmlTable >::children(), and CompAccept< DocHtmlTable >::CompAccept().
The documentation for this class was generated from the following file:
src/docparser.h