Doxygen: src/searchindex.h File Reference
searchindex.h File Reference
#include <qintdict.h>
#include <qlist.h>
#include <qdict.h>
#include <qvector.h>
#include "sortdict.h"
#include "definition.h"
#include "util.h"
Classes
struct URL
struct URLInfo
class IndexWord
class SearchIndexIntf
class SearchIndex
class SearchIndexExternal
class SearchDefinitionList
class SearchIndexList
struct SearchIndexInfo
Macros
#define SEARCH_INDEX_ALL 0
#define SEARCH_INDEX_CLASSES 1
#define SEARCH_INDEX_NAMESPACES 2
#define SEARCH_INDEX_FILES 3
#define SEARCH_INDEX_FUNCTIONS 4
#define SEARCH_INDEX_VARIABLES 5
#define SEARCH_INDEX_TYPEDEFS 6
#define SEARCH_INDEX_ENUMS 7
#define SEARCH_INDEX_ENUMVALUES 8
#define SEARCH_INDEX_PROPERTIES 9
#define SEARCH_INDEX_EVENTS 10
#define SEARCH_INDEX_RELATED 11
#define SEARCH_INDEX_DEFINES 12
#define SEARCH_INDEX_GROUPS 13
#define SEARCH_INDEX_PAGES 14
#define NUM_SEARCH_INDICES 15
Functions
void initSearchIndexer ()
void finializeSearchIndexer ()
void createJavascriptSearchIndex ()
void writeJavascriptSearchIndex ()
const SearchIndexInfo * getSearchIndices ()
Macro Definition Documentation
NUM_SEARCH_INDICES
#define NUM_SEARCH_INDICES 15
Definition at line 130 of file searchindex.h.
Referenced by createJavascriptSearchIndex(), SearchIndicesContext::Private::Private(), and writeJavascriptSearchIndex().
SEARCH_INDEX_ALL
#define SEARCH_INDEX_ALL 0
Definition at line 115 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
SEARCH_INDEX_CLASSES
#define SEARCH_INDEX_CLASSES 1
Definition at line 116 of file searchindex.h.
Referenced by createJavascriptSearchIndex().
SEARCH_INDEX_DEFINES
#define SEARCH_INDEX_DEFINES 12
Definition at line 127 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
SEARCH_INDEX_ENUMS
#define SEARCH_INDEX_ENUMS 7
Definition at line 122 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
SEARCH_INDEX_ENUMVALUES
#define SEARCH_INDEX_ENUMVALUES 8
Definition at line 123 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
SEARCH_INDEX_EVENTS
#define SEARCH_INDEX_EVENTS 10
Definition at line 125 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
SEARCH_INDEX_FILES
#define SEARCH_INDEX_FILES 3
Definition at line 118 of file searchindex.h.
Referenced by createJavascriptSearchIndex().
SEARCH_INDEX_FUNCTIONS
#define SEARCH_INDEX_FUNCTIONS 4
Definition at line 119 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
SEARCH_INDEX_GROUPS
#define SEARCH_INDEX_GROUPS 13
Definition at line 128 of file searchindex.h.
Referenced by createJavascriptSearchIndex().
SEARCH_INDEX_NAMESPACES
#define SEARCH_INDEX_NAMESPACES 2
Definition at line 117 of file searchindex.h.
Referenced by createJavascriptSearchIndex().
SEARCH_INDEX_PAGES
#define SEARCH_INDEX_PAGES 14
Definition at line 129 of file searchindex.h.
Referenced by createJavascriptSearchIndex().
SEARCH_INDEX_PROPERTIES
#define SEARCH_INDEX_PROPERTIES 9
Definition at line 124 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
SEARCH_INDEX_RELATED
#define SEARCH_INDEX_RELATED 11
Definition at line 126 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
SEARCH_INDEX_TYPEDEFS
#define SEARCH_INDEX_TYPEDEFS 6
Definition at line 121 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
SEARCH_INDEX_VARIABLES
#define SEARCH_INDEX_VARIABLES 5
Definition at line 120 of file searchindex.h.
Referenced by addMemberToSearchIndex(), and createJavascriptSearchIndex().
Function Documentation
createJavascriptSearchIndex()
void createJavascriptSearchIndex ()
Definition at line 718 of file searchindex.cpp.
References addMemberToSearchIndex(), LetterToIndexMap< T >::append(), Doxygen::classSDict, Doxygen::functionNameSDict, getUtf8CodeToLower(), Doxygen::groupSDict, GroupDef::groupTitle(), Doxygen::inputNameList, isId(), PageDef::isLinkable(), GroupDef::isLinkable(), NamespaceDef::isLinkable(), FileDef::isLinkable(), ClassDef::isLinkable(), SDict< ClassDef >::Iterator, SDict< NamespaceDef >::Iterator, SDict< MemberName >::Iterator, SDict< GroupDef >::Iterator, SDict< PageDef >::Iterator, Definition::localName(), Doxygen::mainPage, Doxygen::memberNameSDict, FileDef::name(), Definition::name(), SearchIndexInfo::name, Doxygen::namespaceSDict, NUM_SEARCH_INDICES, Doxygen::pageSDict, SEARCH_INDEX_ALL, SEARCH_INDEX_CLASSES, SEARCH_INDEX_DEFINES, SEARCH_INDEX_ENUMS, SEARCH_INDEX_ENUMVALUES, SEARCH_INDEX_EVENTS, SEARCH_INDEX_FILES, SEARCH_INDEX_FUNCTIONS, SEARCH_INDEX_GROUPS, SEARCH_INDEX_NAMESPACES, SEARCH_INDEX_PAGES, SEARCH_INDEX_PROPERTIES, SEARCH_INDEX_RELATED, SEARCH_INDEX_TYPEDEFS, SEARCH_INDEX_VARIABLES, SDict< T >::sort(), SearchIndexInfo::symbolList, SearchIndexInfo::text, theTranslator, PageDef::title(), Translator::trAll(), Translator::trClasses(), Translator::trDefines(), Translator::trEnumerations(), Translator::trEnumerationValues(), Translator::trEvents(), Translator::trFile(), Translator::trFriends(), Translator::trFunctions(), Translator::trGroup(), Translator::trNamespace(), Translator::trPage(), Translator::trProperties(), Translator::trTypedefs(), and Translator::trVariables().
Referenced by generateOutput().
finializeSearchIndexer()
void finializeSearchIndexer ()
Cleanup the search indexer
Definition at line 1324 of file searchindex.cpp.
References Doxygen::searchIndex.
Referenced by generateOutput().
getSearchIndices()
const SearchIndexInfo* getSearchIndices ()
Definition at line 1251 of file searchindex.cpp.
References g_searchIndexInfo.
Referenced by SearchIndicesContext::Private::Private().
initSearchIndexer()
void initSearchIndexer ()
Initialize the search indexer
Definition at line 1302 of file searchindex.cpp.
References Config_getBool, and Doxygen::searchIndex.
Referenced by generateOutput().
writeJavascriptSearchIndex()
void writeJavascriptSearchIndex ()
Definition at line 903 of file searchindex.cpp.
References IndexList::addStyleSheetFile(), Definition::anchor(), MemberDef::argsString(), Config_getBool, Config_getString, convertToXML(), ResourceMgr::copyResource(), DefinitionIntf::definitionType(), endl(), err(), externalRef(), Definition::getBodyDef(), MemberDef::getClassDef(), MemberDef::getFileDef(), Definition::getLanguage(), getLanguageSpecificSeparator(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), Definition::getOutputFileBase(), Definition::getReference(), Doxygen::globalScope, Doxygen::htmlFileExtension, SearchDefinitionList::id(), Doxygen::indexList, ResourceMgr::instance(), MemberDef::isFunction(), MemberDef::isSlot(), SearchIndexList::letter(), Definition::localName(), Definition::name(), SearchDefinitionList::name(), SearchIndexInfo::name, NUM_SEARCH_INDICES, Definition::qualifiedName(), theTranslator, Translator::trGlobalNamespace(), Translator::trLoading(), Translator::trNoMatches(), Translator::trSearching(), DefinitionIntf::TypeClass, DefinitionIntf::TypeMember, DefinitionIntf::TypeNamespace, and versionString.
Referenced by generateOutput().