Doxygen: ArgumentListContext Class Reference
ArgumentListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static ArgumentListContext * alloc ()
static ArgumentListContext * alloc (const ArgumentList *al, Definition *def, const QCString &relPath)
Private Member Functions
ArgumentListContext ()
ArgumentListContext (const ArgumentList *al, Definition *def, const QCString &relPath)
~ArgumentListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1158 of file context.h.
Constructor & Destructor Documentation
ArgumentListContext() [1/2]
ArgumentListContext::ArgumentListContext () private
Definition at line 9389 of file context.cpp.
References p, and Private.
Referenced by alloc().
ArgumentListContext() [2/2]
ArgumentListContext::ArgumentListContext (const ArgumentList * al, Definition * def, const QCString & relPath) private
Definition at line 9394 of file context.cpp.
References ArgumentListContext::Private::addArgument(), p, and Private.
~ArgumentListContext()
ArgumentListContext::~ArgumentListContext () private
Definition at line 9409 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int ArgumentListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 1169 of file context.h.
References RefCountedContext::addRef().
alloc() [1/2]
static ArgumentListContext* ArgumentListContext::alloc () inline static
Definition at line 1161 of file context.h.
References ArgumentListContext().
Referenced by ClassContext::Private::addTemplateDecls(), MemberContext::Private::addTemplateDecls(), MemberContext::Private::parameters(), MemberContext::Private::templateArgs(), ClassContext::Private::typeConstraints(), and MemberContext::Private::typeConstraints().
alloc() [2/2]
static ArgumentListContext* ArgumentListContext::alloc (const ArgumentList * al, Definition * def, const QCString & relPath) inline static
Definition at line 1162 of file context.h.
References ArgumentListContext().
at()
TemplateVariant ArgumentListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 9420 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int ArgumentListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 9415 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * ArgumentListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 9425 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int ArgumentListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 1170 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ArgumentListContext::p private
Definition at line 1176 of file context.h.
Referenced by ArgumentListContext(), at(), count(), createIterator(), and ~ArgumentListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp