Doxygen: src/filedef.h File Reference
filedef.h File Reference
#include "index.h"
#include <qlist.h>
#include <qintdict.h>
#include <qdict.h>
#include "definition.h"
#include "sortdict.h"
#include "memberlist.h"
Classes
struct IncludeInfo
Class representing the data associated with a #include statement.
class FileDef
A model of a file symbol.
class FileList
Class representing a list of FileDef objects.
class OutputNameList
class OutputNameDict
class DirEntry
Class representing an entry (file or sub directory) in a directory.
class Directory
Class representing a directory tree of DirEntry objects.
Functions
void generateFileTree ()
Function Documentation
generateFileTree()
void generateFileTree ()
Definition at line 1687 of file filedef.cpp.
References addDirsAsGroups(), Doxygen::inputNameList, mergeFileDef(), and DirEntry::setLast().