Doxygen: DocLinkedWord Class Reference
DocLinkedWord Class Reference
Node representing a word that can be linked to something.
#include <docparser.h>
Public Member Functions
DocLinkedWord (DocNode *parent, const QCString &word, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &tooltip)
QCString word () const
Kind kind () const
QCString file () const
QCString relPath () const
QCString ref () const
QCString anchor () const
QCString tooltip () const
void accept (DocVisitor *v)
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Attributes
QCString m_word
QCString m_ref
QCString m_file
QCString m_relPath
QCString m_anchor
QCString m_tooltip
Additional Inherited Members
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Node representing a word that can be linked to something.
Definition at line 209 of file docparser.h.
Constructor & Destructor Documentation
DocLinkedWord()
DocLinkedWord::DocLinkedWord (DocNode * parent, const QCString & word, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & tooltip)
Definition at line 1827 of file docparser.cpp.
References SearchIndexIntf::addWord(), g_searchUrl, DocNode::m_parent, DocNode::parent(), and Doxygen::searchIndex.
Member Function Documentation
accept()
void DocLinkedWord::accept (DocVisitor * v) inline virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 222 of file docparser.h.
References DocVisitor::visit().
anchor()
QCString DocLinkedWord::anchor () const inline
Definition at line 220 of file docparser.h.
References m_anchor.
Referenced by DocbookDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), LatexDocVisitor::visit(), HtmlDocVisitor::visit(), and PerlModDocVisitor::visit().
file()
QCString DocLinkedWord::file () const inline
Definition at line 217 of file docparser.h.
References m_file.
Referenced by DocbookDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), LatexDocVisitor::visit(), HtmlDocVisitor::visit(), and PerlModDocVisitor::visit().
kind()
Kind DocLinkedWord::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 216 of file docparser.h.
References DocNode::Kind_LinkedWord.
ref()
QCString DocLinkedWord::ref () const inline
Definition at line 219 of file docparser.h.
References m_ref.
Referenced by RTFDocVisitor::visit(), XmlDocVisitor::visit(), LatexDocVisitor::visit(), HtmlDocVisitor::visit(), and PerlModDocVisitor::visit().
relPath()
QCString DocLinkedWord::relPath () const inline
Definition at line 218 of file docparser.h.
References m_relPath.
Referenced by HtmlDocVisitor::visit().
tooltip()
QCString DocLinkedWord::tooltip () const inline
Definition at line 221 of file docparser.h.
References m_tooltip.
Referenced by HtmlDocVisitor::visit().
word()
QCString DocLinkedWord::word () const inline
Definition at line 215 of file docparser.h.
References m_word.
Referenced by DocbookDocVisitor::visit(), ManDocVisitor::visit(), TextDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), PrintDocVisitor::visit(), HtmlDocVisitor::visit(), LatexDocVisitor::visit(), and PerlModDocVisitor::visit().
Member Data Documentation
m_anchor
QCString DocLinkedWord::m_anchor private
Definition at line 229 of file docparser.h.
Referenced by anchor().
m_file
QCString DocLinkedWord::m_file private
Definition at line 227 of file docparser.h.
Referenced by file().
m_ref
QCString DocLinkedWord::m_ref private
Definition at line 226 of file docparser.h.
Referenced by ref().
m_relPath
QCString DocLinkedWord::m_relPath private
Definition at line 228 of file docparser.h.
Referenced by relPath().
m_tooltip
QCString DocLinkedWord::m_tooltip private
Definition at line 230 of file docparser.h.
Referenced by tooltip().
m_word
QCString DocLinkedWord::m_word private
Definition at line 225 of file docparser.h.
Referenced by word().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp