Doxygen: DocMscFile Class Reference
DocMscFile Class Reference
Node representing a msc file.
#include <docparser.h>
Public Member Functions
DocMscFile (DocNode *parent, const QCString &name, const QCString &context)
void parse ()
Kind kind () const
QCString name () const
QCString file () const
QCString relPath () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString context () const
void accept (DocVisitor *v)
Public Member Functions inherited from CompAccept< DocMscFile >
CompAccept ()
virtual ~CompAccept ()
void accept (DocMscFile *obj, DocVisitor *v)
const QList< DocNode > & children () const
QList< DocNode > & children ()
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Attributes
QCString m_name
QCString m_file
QCString m_relPath
QCString m_width
QCString m_height
QCString m_context
Additional Inherited Members
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from CompAccept< DocMscFile >
QList< DocNode > m_children
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Node representing a msc file.
Definition at line 741 of file docparser.h.
Constructor & Destructor Documentation
DocMscFile()
DocMscFile::DocMscFile (DocNode * parent, const QCString & name, const QCString & context)
Definition at line 2815 of file docparser.cpp.
References DocNode::m_parent, and DocNode::parent().
Member Function Documentation
accept()
void DocMscFile::accept (DocVisitor * v) inline virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 754 of file docparser.h.
References CompAccept< T >::accept().
context()
QCString DocMscFile::context () const inline
Definition at line 753 of file docparser.h.
References m_context.
Referenced by HtmlDocVisitor::visitPre().
file()
QCString DocMscFile::file () const inline
Definition at line 748 of file docparser.h.
References m_file.
Referenced by DocbookDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), XmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and RTFDocVisitor::writeMscFile().
hasCaption()
bool DocMscFile::hasCaption () const inline
Definition at line 750 of file docparser.h.
References CompAccept< DocMscFile >::m_children.
Referenced by DocbookDocVisitor::visitPost(), RTFDocVisitor::visitPost(), HtmlDocVisitor::visitPost(), LatexDocVisitor::visitPost(), DocbookDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and RTFDocVisitor::writeMscFile().
height()
QCString DocMscFile::height () const inline
Definition at line 752 of file docparser.h.
References m_height.
Referenced by DocbookDocVisitor::visitPre(), XmlDocVisitor::visitPre(), and LatexDocVisitor::visitPre().
kind()
Kind DocMscFile::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 746 of file docparser.h.
References DocNode::Kind_MscFile.
name()
QCString DocMscFile::name () const inline
Definition at line 747 of file docparser.h.
References m_name.
Referenced by PrintDocVisitor::visitPre().
parse()
void DocMscFile::parse ()
Definition at line 2821 of file docparser.cpp.
References FileDef::absFilePath(), CMD_MSCFILE, defaultHandleTitleAndSize(), doctokenizerYYlineno, Doxygen::exampleNameDict, findFileDef(), g_fileName, CompAccept< DocMscFile >::m_children, m_file, m_height, m_name, m_width, Doxygen::mscFileNameDict, showFileDefMatches(), and warn_doc_error().
relPath()
QCString DocMscFile::relPath () const inline
Definition at line 749 of file docparser.h.
References m_relPath.
Referenced by HtmlDocVisitor::visitPre().
width()
QCString DocMscFile::width () const inline
Definition at line 751 of file docparser.h.
References m_width.
Referenced by DocbookDocVisitor::visitPre(), XmlDocVisitor::visitPre(), and LatexDocVisitor::visitPre().
Member Data Documentation
m_context
QCString DocMscFile::m_context private
Definition at line 761 of file docparser.h.
Referenced by context().
m_file
QCString DocMscFile::m_file private
Definition at line 757 of file docparser.h.
Referenced by file(), and parse().
m_height
QCString DocMscFile::m_height private
Definition at line 760 of file docparser.h.
Referenced by height(), and parse().
m_name
QCString DocMscFile::m_name private
Definition at line 756 of file docparser.h.
Referenced by name(), and parse().
m_relPath
QCString DocMscFile::m_relPath private
Definition at line 758 of file docparser.h.
Referenced by relPath().
m_width
QCString DocMscFile::m_width private
Definition at line 759 of file docparser.h.
Referenced by parse(), and width().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp