Doxygen: OutputDocInterface Class Reference
OutputDocInterface Class Reference abstract
Interface used for generating documentation.
#include <outputgen.h>
Public Member Functions
virtual ~OutputDocInterface ()
virtual void disableAllBut (OutputGenerator::OutputType o)=0
virtual void enableAll ()=0
virtual void disableAll ()=0
virtual void disable (OutputGenerator::OutputType o)=0
virtual void enable (OutputGenerator::OutputType o)=0
virtual bool isEnabled (OutputGenerator::OutputType o)=0
virtual void pushGeneratorState ()=0
virtual void popGeneratorState ()=0
Public Member Functions inherited from BaseOutputDocInterface
virtual ~BaseOutputDocInterface ()
virtual bool parseText (const QCString &s)
virtual void startItemList ()=0
virtual void startItemListItem ()=0
virtual void endItemListItem ()=0
virtual void endItemList ()=0
virtual void docify (const char *s)=0
virtual void writeChar (char c)=0
virtual void writeString (const char *text)=0
virtual void startParagraph (const char *classDef)=0
virtual void endParagraph ()=0
virtual void writeObjectLink (const char *ref, const char *file, const char *anchor, const char *name)=0
virtual void startHtmlLink (const char *url)=0
virtual void endHtmlLink ()=0
virtual void startBold ()=0
virtual void endBold ()=0
virtual void startTypewriter ()=0
virtual void endTypewriter ()=0
virtual void startEmphasis ()=0
virtual void endEmphasis ()=0
virtual void startCodeFragment ()=0
virtual void endCodeFragment ()=0
virtual void writeRuler ()=0
virtual void startDescription ()=0
virtual void endDescription ()=0
virtual void startDescItem ()=0
virtual void startDescForItem ()=0
virtual void endDescForItem ()=0
virtual void endDescItem ()=0
virtual void startCenter ()=0
virtual void endCenter ()=0
virtual void startSmall ()=0
virtual void endSmall ()=0
virtual void startSimpleSect (SectionTypes t, const char *file, const char *anchor, const char *title)=0
virtual void endSimpleSect ()=0
virtual void startParamList (ParamListTypes t, const char *title)=0
virtual void endParamList ()=0
virtual void startTitle ()=0
virtual void endTitle ()=0
virtual void writeAnchor (const char *fileName, const char *name)=0
virtual void startSection (const char *, const char *, SectionInfo::SectionType)=0
virtual void endSection (const char *, SectionInfo::SectionType)=0
virtual void lineBreak (const char *style)=0
virtual void addIndexItem (const char *s1, const char *s2)=0
virtual void writeNonBreakableSpace (int)=0
virtual void startDescTable (const char *title)=0
virtual void endDescTable ()=0
virtual void startDescTableRow ()=0
virtual void endDescTableRow ()=0
virtual void startDescTableTitle ()=0
virtual void endDescTableTitle ()=0
virtual void startDescTableData ()=0
virtual void endDescTableData ()=0
virtual void startTextLink (const char *file, const char *anchor)=0
virtual void endTextLink ()=0
virtual void startPageRef ()=0
virtual void endPageRef (const char *, const char *)=0
virtual void startSubsection ()=0
virtual void endSubsection ()=0
virtual void startSubsubsection ()=0
virtual void endSubsubsection ()=0
Public Member Functions inherited from CodeOutputInterface
virtual ~CodeOutputInterface ()
virtual void codify (const char *s)=0
virtual void writeCodeLink (const char *ref, const char *file, const char *anchor, const char *name, const char *tooltip)=0
virtual void writeLineNumber (const char *ref, const char *file, const char *anchor, int lineNumber)=0
virtual void writeTooltip (const char *id, const DocLinkInfo &docInfo, const char *decl, const char *desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)=0
virtual void startCodeLine (bool hasLineNumbers)=0
virtual void endCodeLine ()=0
virtual void startFontClass (const char *clsName)=0
virtual void endFontClass ()=0
virtual void writeCodeAnchor (const char *name)=0
virtual void setCurrentDoc (Definition *context, const char *anchor, bool isSourceFile)=0
virtual void addWord (const char *word, bool hiPriority)=0
Additional Inherited Members
Public Types inherited from BaseOutputDocInterface
enum ParamListTypes { Param, RetVal, Exception }
enum SectionTypes { EnumValues, Examples }
Detailed Description
Interface used for generating documentation.
This abstract class is used by several functions to generate the output for a specific format. This interface contains some state saving and changing functions for dealing with format specific output.
Definition at line 507 of file outputgen.h.
Constructor & Destructor Documentation
~OutputDocInterface()
virtual OutputDocInterface::~OutputDocInterface () inline virtual
Definition at line 510 of file outputgen.h.
Member Function Documentation
disable()
virtual void OutputDocInterface::disable (OutputGenerator::OutputType o) pure virtual
Disables a specific output format (useful for OutputList only)
Implemented in OutputList.
Referenced by writePageRef().
disableAll()
virtual void OutputDocInterface::disableAll () pure virtual
Disables all output formats (useful for OutputList only)
Implemented in OutputList.
disableAllBut()
virtual void OutputDocInterface::disableAllBut (OutputGenerator::OutputType o) pure virtual
Create a new output generator. This can later by appended to the current one using append().
Disables all output formats except format o (useful for OutputList only)
Implemented in OutputList.
enable()
virtual void OutputDocInterface::enable (OutputGenerator::OutputType o) pure virtual
Enables a specific output format (useful for OutputList only)
Implemented in OutputList.
enableAll()
virtual void OutputDocInterface::enableAll () pure virtual
Enables all output formats as far as they have been enabled in the config file. (useful for OutputList only)
Implemented in OutputList.
isEnabled()
virtual bool OutputDocInterface::isEnabled (OutputGenerator::OutputType o) pure virtual
Check whether a specific output format is currently enabled (useful for OutputList only)
Implemented in OutputList.
popGeneratorState()
virtual void OutputDocInterface::popGeneratorState () pure virtual
Pops the state of the current generator (or list of generators) on a stack. Should be preceded by a call the pushGeneratorState().
Implemented in OutputList.
Referenced by writePageRef().
pushGeneratorState()
virtual void OutputDocInterface::pushGeneratorState () pure virtual
Appends the output generated by generator g to this generator.
Pushes the state of the current generator (or list of generators) on a stack.
Implemented in OutputList.
Referenced by writePageRef().
The documentation for this class was generated from the following file:
src/outputgen.h