Doxygen: InheritanceListContext Class Reference
InheritanceListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static InheritanceListContext * alloc (const BaseClassList *list, bool baseClasses)
Private Member Functions
InheritanceListContext (const BaseClassList *list, bool baseClasses)
~InheritanceListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 929 of file context.h.
Constructor & Destructor Documentation
InheritanceListContext()
InheritanceListContext::InheritanceListContext (const BaseClassList * list, bool baseClasses) private
Definition at line 8443 of file context.cpp.
References InheritanceListContext::Private::addClass(), BaseClassDef::classDef, ClassDef::displayName(), insertTemplateSpecifierInScope(), p, Private, and BaseClassDef::templSpecifiers.
Referenced by alloc().
~InheritanceListContext()
InheritanceListContext::~InheritanceListContext () private
Definition at line 8469 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int InheritanceListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 939 of file context.h.
References RefCountedContext::addRef().
alloc()
static InheritanceListContext* InheritanceListContext::alloc (const BaseClassList * list, bool baseClasses) inline static
Definition at line 932 of file context.h.
References InheritanceListContext().
Referenced by ClassContext::Private::inheritedBy(), and ClassContext::Private::inherits().
at()
TemplateVariant InheritanceListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 8480 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int InheritanceListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 8475 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * InheritanceListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 8485 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int InheritanceListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 940 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* InheritanceListContext::p private
Definition at line 945 of file context.h.
Referenced by at(), count(), createIterator(), InheritanceListContext(), and ~InheritanceListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp