Doxygen: IndexList Class Reference
IndexList Class Reference
A list of index interfaces.
#include <index.h>
Public Member Functions
IndexList ()
Creates a list of indexes.
void addIndex (IndexIntf *intf)
Add an index generator to the list.
void disable ()
void enable ()
bool isEnabled () const
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const char *name, const char *ref, const char *file, const char *anchor, bool separateIndex=FALSE, bool addToNavIndex=FALSE, Definition *def=0)
void addIndexItem (Definition *context, MemberDef *md, const char *sectionAnchor=0, const char *title=0)
void addIndexFile (const char *name)
void addImageFile (const char *name)
void addStyleSheetFile (const char *name)
Public Member Functions inherited from IndexIntf
virtual ~IndexIntf ()
Private Member Functions
void foreach (void(IndexIntf::*methodPtr)())
template<typename A1 >
void foreach (void(IndexIntf::*methodPtr)(A1), A1 a1)
template<typename A1 , typename A2 , typename A3 >
void foreach (void(IndexIntf::*methodPtr)(A1, A2, A3), A1 a1, A2 a2, A3 a3)
template<typename A1 , typename A2 , typename A3 , typename A4 >
void foreach (void(IndexIntf::*methodPtr)(A1, A2, A3, A4), A1 a1, A2 a2, A3 a3, A4 a4)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 >
void foreach (void(IndexIntf::*methodPtr)(A1, A2, A3, A4, A5), A1 a1, A2 a2, A3 a3, A4 a4, A5 a5)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 >
void foreach (void(IndexIntf::*methodPtr)(A1, A2, A3, A4, A5, A6), A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 >
void foreach (void(IndexIntf::*methodPtr)(A1, A2, A3, A4, A5, A6, A7, A8), A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8)
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 >
void foreach (void(IndexIntf::*methodPtr)(A1, A2, A3, A4, A5, A6, A7, A8, A9), A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9)
Private Attributes
QList< IndexIntf > m_intfs
bool m_enabled
Detailed Description
A list of index interfaces.
This class itself implements all methods of IndexIntf and just forwards the calls to all items in the list.
Definition at line 53 of file index.h.
Constructor & Destructor Documentation
IndexList()
IndexList::IndexList () inline
Creates a list of indexes.
Definition at line 117 of file index.h.
References m_enabled.
Member Function Documentation
addContentsItem()
void IndexList::addContentsItem (bool isDir, const char * name, const char * ref, const char * file, const char * anchor, bool separateIndex = FALSE, bool addToNavIndex = FALSE, Definition * def = 0) inline virtual
Implements IndexIntf.
Definition at line 137 of file index.h.
References IndexIntf::addContentsItem(), and m_enabled.
Referenced by addMembersToIndex(), Definition::addSectionsToIndex(), writeAlphabeticalIndex(), writeAnnotatedIndex(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeClassTree(), writeClassTreeForList(), writeDirHierarchy(), writeDirTreeNode(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeGroupTreeNode(), writeHierarchicalIndex(), writeIndex(), writeIndexHierarchyEntries(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writeNamespaceTree(), and writePages().
addImageFile()
void IndexList::addImageFile (const char * name) inline virtual
Implements IndexIntf.
Definition at line 147 of file index.h.
References IndexIntf::addImageFile(), and m_enabled.
Referenced by copyExtraFiles(), copyLogo(), DotGfxHierarchyTable::createGraph(), findAndCopyImage(), FormulaList::generateBitmaps(), generateGraphLegend(), generatePlantUMLOutput(), writeColoredImgData(), writeDotGraphFromFile(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), ClassDiagram::writeImage(), writeMscGraphFromFile(), and HtmlGenerator::writeSearchData().
addIndex()
void IndexList::addIndex (IndexIntf * intf) inline
Add an index generator to the list.
Definition at line 119 of file index.h.
Referenced by generateOutput().
addIndexFile()
void IndexList::addIndexFile (const char * name) inline virtual
Implements IndexIntf.
Definition at line 145 of file index.h.
References IndexIntf::addIndexFile(), and m_enabled.
Referenced by HtmlGenerator::startFile().
addIndexItem()
void IndexList::addIndexItem (Definition * context, MemberDef * md, const char * sectionAnchor = 0, const char * title = 0) inline virtual
Implements IndexIntf.
Definition at line 142 of file index.h.
References IndexIntf::addIndexItem(), and m_enabled.
Referenced by MemberDef::_writeEnumValues(), HtmlDocVisitor::visit(), MemberDef::writeDeclaration(), NamespaceDef::writeDocumentation(), PageDef::writeDocumentation(), GroupDef::writeDocumentation(), and ClassDef::writeDocumentationContents().
addStyleSheetFile()
void IndexList::addStyleSheetFile (const char * name) inline virtual
Implements IndexIntf.
Definition at line 149 of file index.h.
References IndexIntf::addStyleSheetFile(), and m_enabled.
Referenced by writeJavascriptSearchIndex(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeStyleInfo(), and HtmlGenerator::writeTabData().
decContentsDepth()
void IndexList::decContentsDepth () inline virtual
Implements IndexIntf.
Definition at line 135 of file index.h.
References IndexIntf::decContentsDepth(), and m_enabled.
Referenced by addMembersToIndex(), Definition::addSectionsToIndex(), writeAnnotatedIndex(), writeClassHierarchy(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeClassTree(), writeDirTreeNode(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeGroupTreeNode(), writeIndexHierarchyEntries(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writeNamespaceTree(), and writePages().
disable()
void IndexList::disable () inline
Definition at line 121 of file index.h.
References m_enabled.
Referenced by writeAnnotatedIndex(), writeGroupIndex(), and writeHierarchicalIndex().
enable()
void IndexList::enable () inline
Definition at line 123 of file index.h.
References m_enabled.
Referenced by writeAnnotatedIndex(), writeGroupIndex(), and writeHierarchicalIndex().
finalize()
void IndexList::finalize () inline virtual
Implements IndexIntf.
Definition at line 131 of file index.h.
References IndexIntf::finalize().
Referenced by generateOutput().
foreach() [1/8]
void IndexList::foreach (void(IndexIntf::*)() methodPtr) inline private
Definition at line 60 of file index.h.
foreach() [2/8]
template<typename A1 > void IndexList::foreach (void(IndexIntf::*)(A1) methodPtr, A1 a1) inline private
Definition at line 67 of file index.h.
foreach() [3/8]
template<typename A1 , typename A2 , typename A3 > void IndexList::foreach (void(IndexIntf::*)(A1, A2, A3) methodPtr, A1 a1, A2 a2, A3 a3) inline private
Definition at line 74 of file index.h.
foreach() [4/8]
template<typename A1 , typename A2 , typename A3 , typename A4 > void IndexList::foreach (void(IndexIntf::*)(A1, A2, A3, A4) methodPtr, A1 a1, A2 a2, A3 a3, A4 a4) inline private
Definition at line 81 of file index.h.
foreach() [5/8]
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 > void IndexList::foreach (void(IndexIntf::*)(A1, A2, A3, A4, A5) methodPtr, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5) inline private
Definition at line 88 of file index.h.
foreach() [6/8]
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 > void IndexList::foreach (void(IndexIntf::*)(A1, A2, A3, A4, A5, A6) methodPtr, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6) inline private
Definition at line 95 of file index.h.
foreach() [7/8]
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 > void IndexList::foreach (void(IndexIntf::*)(A1, A2, A3, A4, A5, A6, A7, A8) methodPtr, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8) inline private
Definition at line 102 of file index.h.
foreach() [8/8]
template<typename A1 , typename A2 , typename A3 , typename A4 , typename A5 , typename A6 , typename A7 , typename A8 , typename A9 > void IndexList::foreach (void(IndexIntf::*)(A1, A2, A3, A4, A5, A6, A7, A8, A9) methodPtr, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) inline private
Definition at line 109 of file index.h.
incContentsDepth()
void IndexList::incContentsDepth () inline virtual
Implements IndexIntf.
Definition at line 133 of file index.h.
References IndexIntf::incContentsDepth(), and m_enabled.
Referenced by addMembersToIndex(), Definition::addSectionsToIndex(), writeAnnotatedIndex(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeClassTree(), writeClassTreeForList(), writeDirTreeNode(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeGroupTreeNode(), writeIndexHierarchyEntries(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writeNamespaceTree(), and writePages().
initialize()
void IndexList::initialize () inline virtual
Implements IndexIntf.
Definition at line 129 of file index.h.
References IndexIntf::initialize().
Referenced by generateOutput().
isEnabled()
bool IndexList::isEnabled () const inline
Definition at line 125 of file index.h.
References m_enabled.
Member Data Documentation
m_enabled
bool IndexList::m_enabled private
Definition at line 153 of file index.h.
Referenced by addContentsItem(), addImageFile(), addIndexFile(), addIndexItem(), addStyleSheetFile(), decContentsDepth(), disable(), enable(), incContentsDepth(), IndexList(), and isEnabled().
m_intfs
QList<IndexIntf> IndexList::m_intfs private
Definition at line 56 of file index.h.
The documentation for this class was generated from the following file:
src/index.h