Doxygen: GlobalsIndexContext::Private Class Reference
GlobalsIndexContext::Private Class Reference
Classes
struct Cachable
Public Types
typedef bool(MemberDef::* MemberFunc) () const
Public Member Functions
Private ()
TemplateVariant get (const char *n) const
TemplateVariant getMembersFiltered (SharedPtr< TemplateList > &listRef, MemberFunc filter) const
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
Private Attributes
Cachable m_cache
Static Private Attributes
static PropertyMapper< GlobalsIndexContext::Private > s_inst
Detailed Description
Definition at line 7842 of file context.cpp.
Member Typedef Documentation
MemberFunc
typedef bool(MemberDef::* GlobalsIndexContext::Private::MemberFunc) () const
Definition at line 7872 of file context.cpp.
Constructor & Destructor Documentation
Private()
GlobalsIndexContext::Private::Private () inline
Definition at line 7845 of file context.cpp.
References PropertyMapper< T >::addProperty(), all(), enums(), enumValues(), events(), fileName(), functions(), highlight(), Config::init(), macros(), properties(), related(), relPath(), s_inst, subhighlight(), title(), typedefs(), and variables().
Member Function Documentation
all()
TemplateVariant GlobalsIndexContext::Private::all () const inline
Definition at line 7901 of file context.cpp.
References GlobalsIndexContext::Private::Cachable::all, getMembersFiltered(), and m_cache.
Referenced by Private().
enums()
TemplateVariant GlobalsIndexContext::Private::enums () const inline
Definition at line 7917 of file context.cpp.
References GlobalsIndexContext::Private::Cachable::enums, getMembersFiltered(), MemberDef::isEnumerate(), and m_cache.
Referenced by Private().
enumValues()
TemplateVariant GlobalsIndexContext::Private::enumValues () const inline
Definition at line 7921 of file context.cpp.
References GlobalsIndexContext::Private::Cachable::enumValues, getMembersFiltered(), MemberDef::isEnumValue(), and m_cache.
Referenced by Private().
events()
TemplateVariant GlobalsIndexContext::Private::events () const inline
Definition at line 7933 of file context.cpp.
Referenced by Private().
fileName()
TemplateVariant GlobalsIndexContext::Private::fileName () const inline
Definition at line 7941 of file context.cpp.
Referenced by Private().
functions()
TemplateVariant GlobalsIndexContext::Private::functions () const inline
Definition at line 7905 of file context.cpp.
References GlobalsIndexContext::Private::Cachable::functions, getMembersFiltered(), MemberDef::isFunction(), and m_cache.
Referenced by Private().
get()
TemplateVariant GlobalsIndexContext::Private::get (const char * n) const inline
Definition at line 7868 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by GlobalsIndexContext::get().
getMembersFiltered()
TemplateVariant GlobalsIndexContext::Private::getMembersFiltered (SharedPtr< TemplateList > & listRef, MemberFunc filter) const inline
Definition at line 7873 of file context.cpp.
References MemberContext::alloc(), TemplateList::alloc(), TemplateList::append(), Doxygen::functionNameSDict, SharedPtr< T >::get(), MemberDef::getFileDef(), MemberDef::getNamespaceDef(), FileDef::isLinkableInProject(), MemberDef::isLinkableInProject(), SDict< MemberName >::Iterator, Definition::name(), and SharedPtr< T >::reset().
Referenced by all(), enums(), enumValues(), functions(), macros(), typedefs(), and variables().
highlight()
TemplateVariant GlobalsIndexContext::Private::highlight () const inline
Definition at line 7949 of file context.cpp.
Referenced by Private().
macros()
TemplateVariant GlobalsIndexContext::Private::macros () const inline
Definition at line 7925 of file context.cpp.
References getMembersFiltered(), MemberDef::isDefine(), m_cache, and GlobalsIndexContext::Private::Cachable::macros.
Referenced by Private().
properties()
TemplateVariant GlobalsIndexContext::Private::properties () const inline
Definition at line 7929 of file context.cpp.
Referenced by Private().
related()
TemplateVariant GlobalsIndexContext::Private::related () const inline
Definition at line 7937 of file context.cpp.
Referenced by Private().
relPath()
TemplateVariant GlobalsIndexContext::Private::relPath () const inline
Definition at line 7945 of file context.cpp.
Referenced by Private().
subhighlight()
TemplateVariant GlobalsIndexContext::Private::subhighlight () const inline
Definition at line 7953 of file context.cpp.
Referenced by Private().
title()
TemplateVariant GlobalsIndexContext::Private::title () const inline
Definition at line 7957 of file context.cpp.
References theTranslator, and Translator::trFileMembers().
Referenced by Private().
typedefs()
TemplateVariant GlobalsIndexContext::Private::typedefs () const inline
Definition at line 7913 of file context.cpp.
References getMembersFiltered(), MemberDef::isTypedef(), m_cache, and GlobalsIndexContext::Private::Cachable::typedefs.
Referenced by Private().
variables()
TemplateVariant GlobalsIndexContext::Private::variables () const inline
Definition at line 7909 of file context.cpp.
References getMembersFiltered(), MemberDef::isVariable(), m_cache, and GlobalsIndexContext::Private::Cachable::variables.
Referenced by Private().
Member Data Documentation
m_cache
Cachable GlobalsIndexContext::Private::m_cache mutable private
Definition at line 7973 of file context.cpp.
Referenced by all(), enums(), enumValues(), functions(), macros(), typedefs(), and variables().
s_inst
PropertyMapper< GlobalsIndexContext::Private > GlobalsIndexContext::Private::s_inst static private
Definition at line 7974 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp