Doxygen: src/tagreader.cpp File Reference
tagreader.cpp File Reference
#include "tagreader.h"
#include <stdio.h>
#include <stdarg.h>
#include <qxml.h>
#include <qstack.h>
#include <qdict.h>
#include <qfileinfo.h>
#include <qlist.h>
#include <qstring.h>
#include <qstringlist.h>
#include "entry.h"
#include "classdef.h"
#include "doxygen.h"
#include "util.h"
#include "message.h"
#include "defargs.h"
#include "arguments.h"
#include "filedef.h"
#include "filename.h"
#include "section.h"
Classes
class TagAnchorInfo
Information about an linkable anchor.
class TagAnchorInfoList
List of TagAnchorInfo objects.
class TagEnumValueInfo
Container for enum values that are scoped within an enum.
class TagMemberInfo
Container for member specific info that can be read from a tagfile.
class TagClassInfo
Container for class specific info that can be read from a tagfile.
class TagNamespaceInfo
Container for namespace specific info that can be read from a tagfile.
class TagPackageInfo
Container for package specific info that can be read from a tagfile.
class TagIncludeInfo
Container for include info that can be read from a tagfile.
class TagFileInfo
Container for file specific info that can be read from a tagfile.
class TagGroupInfo
Container for group specific info that can be read from a tagfile.
class TagPageInfo
Container for page specific info that can be read from a tagfile.
class TagDirInfo
Container for directory specific info that can be read from a tagfile.
class TagFileParser
Tag file parser.
class TagFileParser::StartElementHandler
class TagFileParser::EndElementHandler
class TagFileErrorHandler
Error handler for the XML tag file parser.
Functions
static QCString stripPath (const QCString &s)
void parseTagFile (Entry *root, const char *fullName)
Function Documentation
parseTagFile()
void parseTagFile (Entry * root, const char * fullName)
Definition at line 1527 of file tagreader.cpp.
References TagFileParser::addIncludes(), TagFileParser::buildLists(), and TagFileParser::setFileName().
Referenced by readTagFile().
stripPath()
static QCString stripPath (const QCString & s) static
Definition at line 1287 of file tagreader.cpp.
Referenced by TagFileParser::buildLists(), LatexGenerator::endIndexItem(), LatexGenerator::endIndexValue(), LatexGenerator::endTitleHead(), generateDocbookForClass(), generateDocbookForFile(), generateDocbookForMember(), generateDocbookForNamespace(), InheritedMemberInfoContext::Private::id(), DotFilePatcher::run(), SearchIndexExternal::setCurrentDoc(), LatexGenerator::startDoxyAnchor(), LatexGenerator::startFile(), LatexDocVisitor::startLink(), LatexGenerator::startSection(), LatexGenerator::startTextLink(), LatexGenerator::startTitleHead(), substituteHtmlKeywords(), LatexDocVisitor::visit(), LatexDocVisitor::visitPre(), LatexGenerator::writeAnchor(), LatexCodeGenerator::writeCodeLink(), MemberList::writeDeclarations(), LatexGenerator::writeEndAnnoItem(), LatexCodeGenerator::writeLineNumber(), TextGeneratorLatex::writeLink(), and LatexGenerator::writeObjectLink().