Doxygen: RefCountedContext Class Reference
RefCountedContext Class Reference
Helper class to support reference counting.
#include <context.h>
Inherited by AllMembersListContext, ArgumentContext, ArgumentListContext, ClassContext, ClassHierarchyContext, ClassIndexContext, ClassInheritanceContext, ClassInheritanceNodeContext, ClassListContext, ClassMembersIndexContext, ClassTreeContext, ConfigContext, DirContext, DirListContext, DoxygenContext, ExampleListContext, ExampleTreeContext, FileContext, FileListContext, FileTreeContext, GlobalsIndexContext, IncludeInfoContext, IncludeInfoListContext, InheritanceGraphContext, InheritanceListContext, InheritanceNodeContext, InheritedMemberInfoContext, InheritedMemberInfoListContext, MemberContext, MemberGroupInfoContext, MemberGroupListContext, MemberInfoContext, MemberListContext, MemberListInfoContext, ModuleContext, ModuleListContext, ModuleNodeContext, ModuleTreeContext, NamespaceContext, NamespaceListContext, NamespaceMembersIndexContext, NamespaceTreeContext, NavPathElemContext, NestingContext, NestingNodeContext, PageContext, PageListContext, PageTreeContext, SearchIndexContext, SearchIndicesContext, SymbolContext, SymbolGroupContext, SymbolGroupListContext, SymbolIndexContext, SymbolIndicesContext, SymbolListContext, TranslateContext, and UsedFilesContext.
Public Member Functions
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Private Attributes
int m_refCount
Detailed Description
Helper class to support reference counting.
Definition at line 106 of file context.h.
Constructor & Destructor Documentation
RefCountedContext()
RefCountedContext::RefCountedContext (const char *) inline
Definition at line 109 of file context.h.
~RefCountedContext()
virtual RefCountedContext::~RefCountedContext () inline virtual
Definition at line 110 of file context.h.
Member Function Documentation
addRef()
int RefCountedContext::addRef () inline
Definition at line 111 of file context.h.
References m_refCount.
Referenced by ConfigContext::addRef(), DoxygenContext::addRef(), TranslateContext::addRef(), UsedFilesContext::addRef(), IncludeInfoContext::addRef(), IncludeInfoListContext::addRef(), ClassContext::addRef(), NamespaceContext::addRef(), FileContext::addRef(), DirContext::addRef(), PageContext::addRef(), MemberContext::addRef(), ModuleContext::addRef(), ClassListContext::addRef(), ClassIndexContext::addRef(), InheritanceGraphContext::addRef(), ClassInheritanceNodeContext::addRef(), ClassInheritanceContext::addRef(), ClassHierarchyContext::addRef(), NestingNodeContext::addRef(), NestingContext::addRef(), ClassTreeContext::addRef(), NamespaceListContext::addRef(), NamespaceTreeContext::addRef(), DirListContext::addRef(), FileListContext::addRef(), FileTreeContext::addRef(), PageListContext::addRef(), PageTreeContext::addRef(), ModuleNodeContext::addRef(), ModuleListContext::addRef(), ModuleTreeContext::addRef(), ExampleListContext::addRef(), ExampleTreeContext::addRef(), GlobalsIndexContext::addRef(), ClassMembersIndexContext::addRef(), NamespaceMembersIndexContext::addRef(), NavPathElemContext::addRef(), InheritanceNodeContext::addRef(), InheritanceListContext::addRef(), MemberListContext::addRef(), MemberGroupInfoContext::addRef(), MemberGroupListContext::addRef(), MemberListInfoContext::addRef(), MemberInfoContext::addRef(), InheritedMemberInfoContext::addRef(), InheritedMemberInfoListContext::addRef(), AllMembersListContext::addRef(), ArgumentContext::addRef(), ArgumentListContext::addRef(), SymbolContext::addRef(), SymbolListContext::addRef(), SymbolGroupContext::addRef(), SymbolGroupListContext::addRef(), SymbolIndexContext::addRef(), SymbolIndicesContext::addRef(), SearchIndexContext::addRef(), and SearchIndicesContext::addRef().
release()
int RefCountedContext::release () inline
Definition at line 112 of file context.h.
References m_refCount.
Referenced by ConfigContext::release(), DoxygenContext::release(), TranslateContext::release(), UsedFilesContext::release(), IncludeInfoContext::release(), IncludeInfoListContext::release(), ClassContext::release(), NamespaceContext::release(), FileContext::release(), DirContext::release(), PageContext::release(), MemberContext::release(), ModuleContext::release(), ClassListContext::release(), ClassIndexContext::release(), InheritanceGraphContext::release(), ClassInheritanceNodeContext::release(), ClassInheritanceContext::release(), ClassHierarchyContext::release(), NestingNodeContext::release(), NestingContext::release(), ClassTreeContext::release(), NamespaceListContext::release(), NamespaceTreeContext::release(), DirListContext::release(), FileListContext::release(), FileTreeContext::release(), PageListContext::release(), PageTreeContext::release(), ModuleNodeContext::release(), ModuleListContext::release(), ModuleTreeContext::release(), ExampleListContext::release(), ExampleTreeContext::release(), GlobalsIndexContext::release(), ClassMembersIndexContext::release(), NamespaceMembersIndexContext::release(), NavPathElemContext::release(), InheritanceNodeContext::release(), InheritanceListContext::release(), MemberListContext::release(), MemberGroupInfoContext::release(), MemberGroupListContext::release(), MemberListInfoContext::release(), MemberInfoContext::release(), InheritedMemberInfoContext::release(), InheritedMemberInfoListContext::release(), AllMembersListContext::release(), ArgumentContext::release(), ArgumentListContext::release(), SymbolContext::release(), SymbolListContext::release(), SymbolGroupContext::release(), SymbolGroupListContext::release(), SymbolIndexContext::release(), SymbolIndicesContext::release(), SearchIndexContext::release(), and SearchIndicesContext::release().
Member Data Documentation
m_refCount
int RefCountedContext::m_refCount private
Definition at line 122 of file context.h.
Referenced by addRef(), and release().
The documentation for this class was generated from the following file:
src/context.h