Doxygen: MemberInfoContext Class Reference
MemberInfoContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static MemberInfoContext * alloc (const MemberInfo *mi)
Private Member Functions
MemberInfoContext (const MemberInfo *mi)
~MemberInfoContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1052 of file context.h.
Constructor & Destructor Documentation
MemberInfoContext()
MemberInfoContext::MemberInfoContext (const MemberInfo * mi) private
Definition at line 8642 of file context.cpp.
References p, and Private.
Referenced by alloc().
~MemberInfoContext()
MemberInfoContext::~MemberInfoContext () private
Definition at line 8647 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int MemberInfoContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 1059 of file context.h.
References RefCountedContext::addRef().
alloc()
static MemberInfoContext* MemberInfoContext::alloc (const MemberInfo * mi) inline static
Definition at line 1055 of file context.h.
References MemberInfoContext().
Referenced by AllMembersListContext::Private::Private().
get()
TemplateVariant MemberInfoContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 8652 of file context.cpp.
References MemberInfoContext::Private::get(), and p.
release()
virtual int MemberInfoContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 1060 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* MemberInfoContext::p private
Definition at line 1065 of file context.h.
Referenced by get(), MemberInfoContext(), and ~MemberInfoContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp