Doxygen: src/diagram.cpp File Reference
diagram.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <qlist.h>
#include <qarray.h>
#include "ftextstream.h"
#include <qfile.h>
#include "diagram.h"
#include "image.h"
#include "classdef.h"
#include "config.h"
#include "message.h"
#include "util.h"
#include "doxygen.h"
#include "portable.h"
#include "index.h"
#include "classlist.h"
Classes
class DiagramItem
Class representing a single node in the built-in class diagram.
class DiagramItemList
Class representing a list of DiagramItem object.
class DiagramRow
Class representing a row in the built-in class diagram.
class DiagramRowIterator
Class representing iterator for the rows in the built-in class diagram.
class TreeDiagram
Class represeting the tree layout for the built-in class diagram.
Macros
#define IMAGE_EXT ".png"
Functions
static uint protToMask (Protection p)
static uint protToColor (Protection p)
static QCString protToString (Protection p)
static uint virtToMask (Specifier p)
static Protection getMinProtectionLevel (DiagramItemList *dil)
static void writeBitmapBox (DiagramItem *di, Image *image, int x, int y, int w, int h, bool firstRow, bool hasDocs, bool children=FALSE)
static void writeVectorBox (FTextStream &t, DiagramItem *di, float x, float y, bool children=FALSE)
static void writeMapArea (FTextStream &t, ClassDef *cd, QCString relPath, int x, int y, int w, int h)
void clearVisitFlags ()
Variables
const uint maxTreeWidth = 8
const int gridWidth = 100
const int gridHeight = 100
const uint labelHorSpacing = 10
const uint labelVertSpacing = 32
const uint labelHorMargin = 6
const uint fontHeight = 12
Macro Definition Documentation
IMAGE_EXT
#define IMAGE_EXT ".png"
Referenced by ClassDiagram::writeImage().
Function Documentation
clearVisitFlags()
void clearVisitFlags ()
Definition at line 1017 of file diagram.cpp.
References Doxygen::classSDict, SDict< ClassDef >::Iterator, and ClassDef::visited.
Referenced by ClassDiagram::ClassDiagram().
getMinProtectionLevel()
static Protection getMinProtectionLevel (DiagramItemList * dil) static
Definition at line 210 of file diagram.cpp.
References Private, Protected, DiagramItem::protection(), and Public.
Referenced by TreeDiagram::drawConnectors().
protToColor()
static uint protToColor (Protection p) static
Definition at line 174 of file diagram.cpp.
References Package, Private, Protected, and Public.
Referenced by TreeDiagram::drawConnectors().
protToMask()
static uint protToMask (Protection p) static
Definition at line 162 of file diagram.cpp.
References Package, Private, Protected, and Public.
Referenced by TreeDiagram::drawConnectors().
protToString()
static QCString protToString (Protection p) static
Definition at line 186 of file diagram.cpp.
References Package, Private, Protected, and Public.
Referenced by TreeDiagram::drawConnectors().
virtToMask()
static uint virtToMask (Specifier p) static
Definition at line 198 of file diagram.cpp.
References Normal, and Virtual.
Referenced by writeBitmapBox().
writeBitmapBox()
static void writeBitmapBox (DiagramItem * di, Image * image, int x, int y, int w, int h, bool firstRow, bool hasDocs, bool children = FALSE) static
Definition at line 227 of file diagram.cpp.
References Image::drawHorzLine(), Image::drawRect(), Image::fillRect(), fontHeight, DiagramItem::label(), Image::stringLength, virtToMask(), DiagramItem::virtualness(), and Image::writeString().
Referenced by TreeDiagram::drawBoxes().
writeMapArea()
static void writeMapArea (FTextStream & t, ClassDef * cd, QCString relPath, int x, int y, int w, int h) static
Definition at line 255 of file diagram.cpp.
References ClassDef::anchor(), Definition::briefDescriptionAsTooltip(), convertToHtml(), convertToXML(), ClassDef::displayName(), endl(), externalLinkTarget(), externalRef(), ClassDef::getOutputFileBase(), ClassDef::getReference(), Doxygen::htmlFileExtension, and ClassDef::isLinkable().
Referenced by TreeDiagram::drawBoxes().
writeVectorBox()
static void writeVectorBox (FTextStream & t, DiagramItem * di, float x, float y, bool children = FALSE) static
Definition at line 246 of file diagram.cpp.
References DiagramItem::label(), Virtual, and DiagramItem::virtualness().
Referenced by TreeDiagram::drawBoxes().
Variable Documentation
fontHeight
const uint fontHeight = 12
Definition at line 148 of file diagram.cpp.
Referenced by writeBitmapBox(), and ClassDiagram::writeImage().
gridHeight
const int gridHeight = 100
Definition at line 143 of file diagram.cpp.
Referenced by TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), and DiagramRow::insertClass().
gridWidth
const int gridWidth = 100
Definition at line 142 of file diagram.cpp.
Referenced by TreeDiagram::computeLayout(), TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), DiagramRow::insertClass(), ClassDiagram::writeFigure(), and ClassDiagram::writeImage().
labelHorMargin
const uint labelHorMargin = 6
Definition at line 147 of file diagram.cpp.
Referenced by ClassDiagram::writeImage().
labelHorSpacing
const uint labelHorSpacing = 10
Definition at line 145 of file diagram.cpp.
Referenced by TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), and ClassDiagram::writeImage().
labelVertSpacing
const uint labelVertSpacing = 32
Definition at line 146 of file diagram.cpp.
Referenced by TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), and ClassDiagram::writeImage().
maxTreeWidth
const uint maxTreeWidth = 8
Definition at line 141 of file diagram.cpp.
Referenced by TreeDiagram::computeLayout().