Doxygen: DotFilePatcher Class Reference
DotFilePatcher Class Reference
Helper class to insert a set of map file into an output file.
#include <dot.h>
Classes
struct Map
Public Member Functions
DotFilePatcher (const char *patchFile)
int addMap (const QCString &mapFile, const QCString &relPath, bool urlOnly, const QCString &context, const QCString &label)
int addFigure (const QCString &baseName, const QCString &figureName, bool heightCheck)
int addSVGConversion (const QCString &relPath, bool urlOnly, const QCString &context, bool zoomable, int graphId)
int addSVGObject (const QCString &baseName, const QCString &figureName, const QCString &relPath)
bool run ()
QCString file () const
Private Attributes
QList< Map > m_maps
QCString m_patchFile
Detailed Description
Helper class to insert a set of map file into an output file.
Definition at line 406 of file dot.h.
Constructor & Destructor Documentation
DotFilePatcher()
DotFilePatcher::DotFilePatcher (const char * patchFile)
Definition at line 833 of file dot.cpp.
References m_maps.
Member Function Documentation
addFigure()
int DotFilePatcher::addFigure (const QCString & baseName, const QCString & figureName, bool heightCheck)
Definition at line 860 of file dot.cpp.
References DotFilePatcher::Map::graphId, DotFilePatcher::Map::label, m_maps, DotFilePatcher::Map::mapFile, DotFilePatcher::Map::urlOnly, and DotFilePatcher::Map::zoomable.
Referenced by DotManager::addFigure().
addMap()
int DotFilePatcher::addMap (const QCString & mapFile, const QCString & relPath, bool urlOnly, const QCString & context, const QCString & label)
Definition at line 844 of file dot.cpp.
References DotFilePatcher::Map::context, DotFilePatcher::Map::graphId, DotFilePatcher::Map::label, m_maps, DotFilePatcher::Map::mapFile, DotFilePatcher::Map::relPath, DotFilePatcher::Map::urlOnly, and DotFilePatcher::Map::zoomable.
Referenced by DotManager::addMap().
addSVGConversion()
int DotFilePatcher::addSVGConversion (const QCString & relPath, bool urlOnly, const QCString & context, bool zoomable, int graphId)
Definition at line 874 of file dot.cpp.
References DotFilePatcher::Map::context, DotFilePatcher::Map::graphId, m_maps, DotFilePatcher::Map::relPath, DotFilePatcher::Map::urlOnly, and DotFilePatcher::Map::zoomable.
Referenced by DotManager::addSVGConversion(), and writeDotImageMapFromFile().
addSVGObject()
int DotFilePatcher::addSVGObject (const QCString & baseName, const QCString & figureName, const QCString & relPath)
Definition at line 889 of file dot.cpp.
References DotFilePatcher::Map::graphId, DotFilePatcher::Map::label, m_maps, DotFilePatcher::Map::mapFile, DotFilePatcher::Map::relPath, and DotFilePatcher::Map::zoomable.
Referenced by DotManager::addSVGObject().
file()
QCString DotFilePatcher::file () const
Definition at line 839 of file dot.cpp.
References m_patchFile.
Referenced by DotManager::run().
run()
bool DotFilePatcher::run ()
Definition at line 904 of file dot.cpp.
References Config_getBool, DotFilePatcher::Map::context, convertMapFile(), endl(), err(), DotFilePatcher::Map::graphId, DotFilePatcher::Map::label, m_maps, m_patchFile, DotFilePatcher::Map::mapFile, DotFilePatcher::Map::relPath, replaceRef(), stripPath(), substitute(), svgZoomFooter, svgZoomHeader, DotFilePatcher::Map::urlOnly, writeSVGFigureLink(), writeVecGfxFigure(), and DotFilePatcher::Map::zoomable.
Referenced by DotManager::run(), and writeDotImageMapFromFile().
Member Data Documentation
m_maps
QList<Map> DotFilePatcher::m_maps private
Definition at line 432 of file dot.h.
Referenced by addFigure(), addMap(), addSVGConversion(), addSVGObject(), DotFilePatcher(), and run().
m_patchFile
QCString DotFilePatcher::m_patchFile private
Definition at line 433 of file dot.h.
Referenced by file(), and run().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp