Doxygen: PerlModDocVisitor Class Reference
PerlModDocVisitor Class Reference
Concrete visitor implementation for PerlMod output.
Public Member Functions
PerlModDocVisitor (PerlModOutput &)
virtual ~PerlModDocVisitor ()
void finish ()
void visit (DocWord *)
void visit (DocLinkedWord *)
void visit (DocWhiteSpace *)
void visit (DocSymbol *)
void visit (DocURL *)
void visit (DocLineBreak *)
void visit (DocHorRuler *)
void visit (DocStyleChange *)
void visit (DocVerbatim *)
void visit (DocAnchor *)
void visit (DocInclude *)
void visit (DocIncOperator *)
void visit (DocFormula *)
void visit (DocIndexEntry *)
void visit (DocSimpleSectSep *)
void visit (DocCite *)
void visitPre (DocAutoList *)
void visitPost (DocAutoList *)
void visitPre (DocAutoListItem *)
void visitPost (DocAutoListItem *)
void visitPre (DocPara *)
void visitPost (DocPara *)
void visitPre (DocRoot *)
void visitPost (DocRoot *)
void visitPre (DocSimpleSect *)
void visitPost (DocSimpleSect *)
void visitPre (DocTitle *)
void visitPost (DocTitle *)
void visitPre (DocSimpleList *)
void visitPost (DocSimpleList *)
void visitPre (DocSimpleListItem *)
void visitPost (DocSimpleListItem *)
void visitPre (DocSection *)
void visitPost (DocSection *)
void visitPre (DocHtmlList *)
void visitPost (DocHtmlList *)
void visitPre (DocHtmlListItem *)
void visitPost (DocHtmlListItem *)
void visitPre (DocHtmlDescList *)
void visitPost (DocHtmlDescList *)
void visitPre (DocHtmlDescTitle *)
void visitPost (DocHtmlDescTitle *)
void visitPre (DocHtmlDescData *)
void visitPost (DocHtmlDescData *)
void visitPre (DocHtmlTable *)
void visitPost (DocHtmlTable *)
void visitPre (DocHtmlRow *)
void visitPost (DocHtmlRow *)
void visitPre (DocHtmlCell *)
void visitPost (DocHtmlCell *)
void visitPre (DocHtmlCaption *)
void visitPost (DocHtmlCaption *)
void visitPre (DocInternal *)
void visitPost (DocInternal *)
void visitPre (DocHRef *)
void visitPost (DocHRef *)
void visitPre (DocHtmlHeader *)
void visitPost (DocHtmlHeader *)
void visitPre (DocImage *)
void visitPost (DocImage *)
void visitPre (DocDotFile *)
void visitPost (DocDotFile *)
void visitPre (DocMscFile *)
void visitPost (DocMscFile *)
void visitPre (DocDiaFile *)
void visitPost (DocDiaFile *)
void visitPre (DocLink *)
void visitPost (DocLink *)
void visitPre (DocRef *)
void visitPost (DocRef *)
void visitPre (DocSecRefItem *)
void visitPost (DocSecRefItem *)
void visitPre (DocSecRefList *)
void visitPost (DocSecRefList *)
void visitPre (DocParamSect *)
void visitPost (DocParamSect *)
void visitPre (DocParamList *)
void visitPost (DocParamList *)
void visitPre (DocXRefItem *)
void visitPost (DocXRefItem *)
void visitPre (DocInternalRef *)
void visitPost (DocInternalRef *)
void visitPre (DocCopy *)
void visitPost (DocCopy *)
void visitPre (DocText *)
void visitPost (DocText *)
void visitPre (DocHtmlBlockQuote *)
void visitPost (DocHtmlBlockQuote *)
void visitPre (DocVhdlFlow *)
void visitPost (DocVhdlFlow *)
void visitPre (DocParBlock *)
void visitPost (DocParBlock *)
Public Member Functions inherited from DocVisitor
DocVisitor (int id)
virtual ~DocVisitor ()
int id () const
Private Member Functions
void addLink (const QCString &ref, const QCString &file, const QCString &anchor)
void enterText ()
void leaveText ()
void openItem (const char *)
void closeItem ()
void singleItem (const char *)
void openSubBlock (const char *=0)
void closeSubBlock ()
void openOther ()
void closeOther ()
Private Attributes
PerlModOutput & m_output
bool m_textmode
bool m_textblockstart
QCString m_other
Detailed Description
Concrete visitor implementation for PerlMod output.
Definition at line 286 of file perlmodgen.cpp.
Constructor & Destructor Documentation
PerlModDocVisitor()
PerlModDocVisitor::PerlModDocVisitor (PerlModOutput & output)
Definition at line 430 of file perlmodgen.cpp.
References m_output, and PerlModOutput::openList().
~PerlModDocVisitor()
virtual PerlModDocVisitor::~PerlModDocVisitor () inline virtual
Definition at line 290 of file perlmodgen.cpp.
Member Function Documentation
addLink()
void PerlModDocVisitor::addLink (const QCString & ref, const QCString & file, const QCString & anchor) private
Definition at line 443 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), and m_output.
Referenced by visit(), and visitPre().
closeItem()
void PerlModDocVisitor::closeItem () private
Definition at line 457 of file perlmodgen.cpp.
References PerlModOutput::closeHash(), leaveText(), and m_output.
Referenced by singleItem(), visit(), and visitPost().
closeOther()
void PerlModDocVisitor::closeOther () private
Definition at line 511 of file perlmodgen.cpp.
Referenced by visitPost().
closeSubBlock()
void PerlModDocVisitor::closeSubBlock () private
Definition at line 495 of file perlmodgen.cpp.
References PerlModOutput::closeList(), leaveText(), and m_output.
Referenced by visit(), and visitPost().
enterText()
void PerlModDocVisitor::enterText () private
Definition at line 463 of file perlmodgen.cpp.
References PerlModOutput::add(), PerlModOutput::addField(), m_output, m_textmode, and openItem().
Referenced by visit().
finish()
void PerlModDocVisitor::finish ()
Definition at line 436 of file perlmodgen.cpp.
References PerlModOutput::add(), PerlModOutput::closeList(), leaveText(), m_other, and m_output.
Referenced by addPerlModDocBlock().
leaveText()
void PerlModDocVisitor::leaveText () private
Definition at line 472 of file perlmodgen.cpp.
References PerlModOutput::add(), PerlModOutput::closeHash(), m_output, and m_textmode.
Referenced by closeItem(), closeSubBlock(), finish(), openItem(), openSubBlock(), visit(), visitPost(), and visitPre().
openItem()
void PerlModDocVisitor::openItem (const char * name) private
Definition at line 451 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), leaveText(), m_output, and PerlModOutput::openHash().
Referenced by enterText(), singleItem(), visit(), and visitPre().
openOther()
void PerlModDocVisitor::openOther () private
Definition at line 501 of file perlmodgen.cpp.
Referenced by visitPre().
openSubBlock()
void PerlModDocVisitor::openSubBlock (const char * s = 0) private
Definition at line 488 of file perlmodgen.cpp.
References leaveText(), m_output, m_textblockstart, and PerlModOutput::openList().
Referenced by visit(), and visitPre().
singleItem()
void PerlModDocVisitor::singleItem (const char * name) private
Definition at line 482 of file perlmodgen.cpp.
References closeItem(), and openItem().
Referenced by visit(), and visitPre().
visit() [1/16]
void PerlModDocVisitor::visit (DocWord * w) virtual
Implements DocVisitor.
Definition at line 523 of file perlmodgen.cpp.
References PerlModOutput::addQuoted(), enterText(), m_output, and DocWord::word().
visit() [2/16]
void PerlModDocVisitor::visit (DocLinkedWord * w) virtual
Implements DocVisitor.
Definition at line 529 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), addLink(), DocLinkedWord::anchor(), closeItem(), DocLinkedWord::file(), m_output, openItem(), DocLinkedWord::ref(), and DocLinkedWord::word().
visit() [3/16]
void PerlModDocVisitor::visit (DocWhiteSpace *) virtual
Implements DocVisitor.
Definition at line 537 of file perlmodgen.cpp.
References PerlModOutput::add(), enterText(), and m_output.
visit() [4/16]
void PerlModDocVisitor::visit (DocSymbol * sy) virtual
Implements DocVisitor.
Definition at line 543 of file perlmodgen.cpp.
References PerlModOutput::add(), PerlModOutput::addFieldQuotedChar(), PerlModOutput::addFieldQuotedString(), closeItem(), enterText(), err(), HtmlEntityMapper::instance(), leaveText(), m_output, openItem(), HtmlEntityMapper::perl(), DocSymbol::Perl_acute, DocSymbol::Perl_cedilla, DocSymbol::Perl_char, DocSymbol::Perl_circ, DocSymbol::Perl_grave, DocSymbol::Perl_ring, DocSymbol::Perl_slash, DocSymbol::Perl_string, DocSymbol::Perl_symbol, DocSymbol::Perl_tilde, DocSymbol::Perl_umlaut, DocSymbol::PerlSymb::symb, DocSymbol::symbol(), and DocSymbol::PerlSymb::type.
visit() [5/16]
void PerlModDocVisitor::visit (DocURL * u) virtual
Implements DocVisitor.
Definition at line 613 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), closeItem(), m_output, openItem(), and DocURL::url().
visit() [6/16]
void PerlModDocVisitor::visit (DocLineBreak *) virtual
Implements DocVisitor.
Definition at line 620 of file perlmodgen.cpp.
References singleItem().
visit() [7/16]
void PerlModDocVisitor::visit (DocHorRuler *) virtual
Implements DocVisitor.
Definition at line 621 of file perlmodgen.cpp.
References singleItem().
visit() [8/16]
void PerlModDocVisitor::visit (DocStyleChange * s) virtual
Implements DocVisitor.
Definition at line 623 of file perlmodgen.cpp.
References PerlModOutput::addFieldBoolean(), PerlModOutput::addFieldQuotedString(), DocStyleChange::Bold, DocStyleChange::Center, closeItem(), DocStyleChange::Code, DocStyleChange::Div, DocStyleChange::enable(), DocStyleChange::Italic, m_output, openItem(), DocStyleChange::Preformatted, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::style(), DocStyleChange::Subscript, and DocStyleChange::Superscript.
visit() [9/16]
void PerlModDocVisitor::visit (DocVerbatim * s) virtual
Implements DocVisitor.
Definition at line 646 of file perlmodgen.cpp.
References DocNode::accept(), PerlModOutput::add(), PerlModOutput::addFieldQuotedString(), DocVerbatim::children(), closeItem(), closeSubBlock(), DocVerbatim::Code, DocVerbatim::context(), DocVerbatim::DocbookOnly, DocVerbatim::Dot, DocVerbatim::hasCaption(), DocVerbatim::HtmlOnly, DocVerbatim::LatexOnly, m_output, DocVerbatim::ManOnly, DocVerbatim::Msc, openItem(), openSubBlock(), parseCode(), DocVerbatim::PlantUML, DocVerbatim::RtfOnly, DocVerbatim::text(), DocVerbatim::type(), DocVerbatim::Verbatim, and DocVerbatim::XmlOnly.
visit() [10/16]
void PerlModDocVisitor::visit (DocAnchor * anc) virtual
Implements DocVisitor.
Definition at line 682 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), DocAnchor::anchor(), closeItem(), DocAnchor::file(), m_output, and openItem().
visit() [11/16]
void PerlModDocVisitor::visit (DocInclude * inc) virtual
Implements DocVisitor.
Definition at line 690 of file perlmodgen.cpp.
References PerlModOutput::add(), PerlModOutput::addFieldQuotedString(), closeItem(), DocInclude::context(), DocInclude::DontInclude, err(), DocInclude::exampleFile(), DocInclude::file(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, m_output, openItem(), parseCode(), DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::text(), DocInclude::type(), and DocInclude::VerbInclude.
visit() [12/16]
void PerlModDocVisitor::visit (DocIncOperator *) virtual
Implements DocVisitor.
Definition at line 731 of file perlmodgen.cpp.
References PerlModOutput::add(), m_output, parseCode(), and DocIncOperator::Skip.
visit() [13/16]
void PerlModDocVisitor::visit (DocFormula * f) virtual
Implements DocVisitor.
Definition at line 755 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), closeItem(), DocVisitor::id(), DocFormula::id(), m_output, openItem(), and DocFormula::text().
visit() [14/16]
void PerlModDocVisitor::visit (DocIndexEntry *) virtual
Implements DocVisitor.
Definition at line 764 of file perlmodgen.cpp.
References PerlModOutput::add(), PerlModOutput::addQuoted(), and m_output.
visit() [15/16]
void PerlModDocVisitor::visit (DocSimpleSectSep *) virtual
Implements DocVisitor.
Definition at line 776 of file perlmodgen.cpp.
visit() [16/16]
void PerlModDocVisitor::visit (DocCite * cite) virtual
Implements DocVisitor.
Definition at line 780 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), closeItem(), m_output, openItem(), and DocCite::text().
visitPost() [1/38]
void PerlModDocVisitor::visitPost (DocAutoList *) virtual
Implements DocVisitor.
Definition at line 799 of file perlmodgen.cpp.
References closeItem(), and closeSubBlock().
visitPost() [2/38]
void PerlModDocVisitor::visitPost (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 810 of file perlmodgen.cpp.
References closeSubBlock().
visitPost() [3/38]
void PerlModDocVisitor::visitPost (DocPara *) virtual
Implements DocVisitor.
Definition at line 827 of file perlmodgen.cpp.
visitPost() [4/38]
void PerlModDocVisitor::visitPost (DocRoot *) virtual
Implements DocVisitor.
Definition at line 839 of file perlmodgen.cpp.
visitPost() [5/38]
void PerlModDocVisitor::visitPost (DocSimpleSect *) virtual
Implements DocVisitor.
Definition at line 875 of file perlmodgen.cpp.
References PerlModOutput::closeHash(), closeOther(), closeSubBlock(), and m_output.
visitPost() [6/38]
void PerlModDocVisitor::visitPost (DocTitle *) virtual
Implements DocVisitor.
Definition at line 888 of file perlmodgen.cpp.
References closeItem(), and closeSubBlock().
visitPost() [7/38]
void PerlModDocVisitor::visitPost (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 901 of file perlmodgen.cpp.
References closeItem(), and closeSubBlock().
visitPost() [8/38]
void PerlModDocVisitor::visitPost (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 908 of file perlmodgen.cpp.
References closeSubBlock().
visitPost() [9/38]
void PerlModDocVisitor::visitPost (DocSection *) virtual
Implements DocVisitor.
Definition at line 918 of file perlmodgen.cpp.
References closeItem(), and closeSubBlock().
visitPost() [10/38]
void PerlModDocVisitor::visitPost (DocHtmlList *) virtual
Implements DocVisitor.
Definition at line 931 of file perlmodgen.cpp.
References closeItem(), and closeSubBlock().
visitPost() [11/38]
void PerlModDocVisitor::visitPost (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 938 of file perlmodgen.cpp.
References closeSubBlock().
visitPost() [12/38]
void PerlModDocVisitor::visitPost (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 961 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [13/38]
void PerlModDocVisitor::visitPost (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 975 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [14/38]
void PerlModDocVisitor::visitPost (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 989 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [15/38]
void PerlModDocVisitor::visitPost (DocHtmlTable *) virtual
Implements DocVisitor.
Definition at line 1004 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [16/38]
void PerlModDocVisitor::visitPost (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 1018 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [17/38]
void PerlModDocVisitor::visitPost (DocHtmlCell *) virtual
Implements DocVisitor.
Definition at line 1032 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [18/38]
void PerlModDocVisitor::visitPost (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 1046 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [19/38]
void PerlModDocVisitor::visitPost (DocInternal *) virtual
Implements DocVisitor.
Definition at line 1060 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [20/38]
void PerlModDocVisitor::visitPost (DocHRef *) virtual
Implements DocVisitor.
Definition at line 1074 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [21/38]
void PerlModDocVisitor::visitPost (DocHtmlHeader *) virtual
Implements DocVisitor.
Definition at line 1088 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [22/38]
void PerlModDocVisitor::visitPost (DocImage *) virtual
Implements DocVisitor.
Definition at line 1130 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [23/38]
void PerlModDocVisitor::visitPost (DocDotFile *) virtual
Implements DocVisitor.
Definition at line 1144 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [24/38]
void PerlModDocVisitor::visitPost (DocMscFile *) virtual
Implements DocVisitor.
Definition at line 1157 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [25/38]
void PerlModDocVisitor::visitPost (DocDiaFile *) virtual
Implements DocVisitor.
Definition at line 1171 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [26/38]
void PerlModDocVisitor::visitPost (DocLink *) virtual
Implements DocVisitor.
Definition at line 1185 of file perlmodgen.cpp.
References closeItem().
visitPost() [27/38]
void PerlModDocVisitor::visitPost (DocRef *) virtual
Implements DocVisitor.
Definition at line 1198 of file perlmodgen.cpp.
References closeItem(), and closeSubBlock().
visitPost() [28/38]
void PerlModDocVisitor::visitPost (DocSecRefItem *) virtual
Implements DocVisitor.
Definition at line 1211 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [29/38]
void PerlModDocVisitor::visitPost (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 1225 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPost() [30/38]
void PerlModDocVisitor::visitPost (DocParamSect *) virtual
Implements DocVisitor.
Definition at line 1261 of file perlmodgen.cpp.
References closeOther(), and closeSubBlock().
visitPost() [31/38]
void PerlModDocVisitor::visitPost (DocParamList *) virtual
Implements DocVisitor.
Definition at line 1321 of file perlmodgen.cpp.
References PerlModOutput::closeHash(), PerlModOutput::closeList(), leaveText(), and m_output.
visitPost() [32/38]
void PerlModDocVisitor::visitPost (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1344 of file perlmodgen.cpp.
References PerlModOutput::add(), closeItem(), closeSubBlock(), m_output, and DocXRefItem::title().
visitPost() [33/38]
void PerlModDocVisitor::visitPost (DocInternalRef *) virtual
Implements DocVisitor.
Definition at line 1362 of file perlmodgen.cpp.
References closeItem(), and closeSubBlock().
visitPost() [34/38]
void PerlModDocVisitor::visitPost (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1372 of file perlmodgen.cpp.
visitPost() [35/38]
void PerlModDocVisitor::visitPost (DocText *) virtual
Implements DocVisitor.
Definition at line 1380 of file perlmodgen.cpp.
visitPost() [36/38]
void PerlModDocVisitor::visitPost (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1390 of file perlmodgen.cpp.
References closeItem(), and closeSubBlock().
visitPost() [37/38]
void PerlModDocVisitor::visitPost (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1400 of file perlmodgen.cpp.
visitPost() [38/38]
void PerlModDocVisitor::visitPost (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1408 of file perlmodgen.cpp.
visitPre() [1/38]
void PerlModDocVisitor::visitPre (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 792 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), DocAutoList::isEnumList(), m_output, openItem(), and openSubBlock().
visitPre() [2/38]
void PerlModDocVisitor::visitPre (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 805 of file perlmodgen.cpp.
References openSubBlock().
visitPre() [3/38]
void PerlModDocVisitor::visitPre (DocPara *) virtual
Implements DocVisitor.
Definition at line 815 of file perlmodgen.cpp.
References m_textblockstart, and singleItem().
visitPre() [4/38]
void PerlModDocVisitor::visitPre (DocRoot *) virtual
Implements DocVisitor.
Definition at line 835 of file perlmodgen.cpp.
visitPre() [5/38]
void PerlModDocVisitor::visitPre (DocSimpleSect * s) virtual
Implements DocVisitor.
Definition at line 843 of file perlmodgen.cpp.
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, err(), DocSimpleSect::Invar, leaveText(), m_output, DocSimpleSect::Note, PerlModOutput::openHash(), openOther(), openSubBlock(), DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, DocSimpleSect::See, DocSimpleSect::Since, DocSimpleSect::type(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
visitPre() [6/38]
void PerlModDocVisitor::visitPre (DocTitle *) virtual
Implements DocVisitor.
Definition at line 882 of file perlmodgen.cpp.
References openItem(), and openSubBlock().
visitPre() [7/38]
void PerlModDocVisitor::visitPre (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 894 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), m_output, openItem(), and openSubBlock().
visitPre() [8/38]
void PerlModDocVisitor::visitPre (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 907 of file perlmodgen.cpp.
References openSubBlock().
visitPre() [9/38]
void PerlModDocVisitor::visitPre (DocSection * s) virtual
Implements DocVisitor.
Definition at line 910 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), DocSection::level(), m_output, openItem(), openSubBlock(), and DocSection::title().
visitPre() [10/38]
void PerlModDocVisitor::visitPre (DocHtmlList * l) virtual
Implements DocVisitor.
Definition at line 924 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), m_output, openItem(), openSubBlock(), DocHtmlList::Ordered, and DocHtmlList::type().
visitPre() [11/38]
void PerlModDocVisitor::visitPre (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 937 of file perlmodgen.cpp.
References openSubBlock().
visitPre() [12/38]
void PerlModDocVisitor::visitPre (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 954 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [13/38]
void PerlModDocVisitor::visitPre (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 968 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [14/38]
void PerlModDocVisitor::visitPre (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 982 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [15/38]
void PerlModDocVisitor::visitPre (DocHtmlTable *) virtual
Implements DocVisitor.
Definition at line 996 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [16/38]
void PerlModDocVisitor::visitPre (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 1011 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [17/38]
void PerlModDocVisitor::visitPre (DocHtmlCell *) virtual
Implements DocVisitor.
Definition at line 1025 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [18/38]
void PerlModDocVisitor::visitPre (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 1039 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [19/38]
void PerlModDocVisitor::visitPre (DocInternal *) virtual
Implements DocVisitor.
Definition at line 1053 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [20/38]
void PerlModDocVisitor::visitPre (DocHRef *) virtual
Implements DocVisitor.
Definition at line 1067 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [21/38]
void PerlModDocVisitor::visitPre (DocHtmlHeader *) virtual
Implements DocVisitor.
Definition at line 1081 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [22/38]
void PerlModDocVisitor::visitPre (DocImage *) virtual
Implements DocVisitor.
Definition at line 1095 of file perlmodgen.cpp.
References PerlModOutput::add(), PerlModOutput::addQuoted(), DocImage::Html, DocImage::Latex, m_output, and DocImage::Rtf.
visitPre() [23/38]
void PerlModDocVisitor::visitPre (DocDotFile *) virtual
Implements DocVisitor.
Definition at line 1137 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [24/38]
void PerlModDocVisitor::visitPre (DocMscFile *) virtual
Implements DocVisitor.
Definition at line 1150 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [25/38]
void PerlModDocVisitor::visitPre (DocDiaFile *) virtual
Implements DocVisitor.
Definition at line 1164 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [26/38]
void PerlModDocVisitor::visitPre (DocLink * lnk) virtual
Implements DocVisitor.
Definition at line 1179 of file perlmodgen.cpp.
References addLink(), DocLink::anchor(), DocLink::file(), openItem(), and DocLink::ref().
visitPre() [27/38]
void PerlModDocVisitor::visitPre (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 1190 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), DocRef::hasLinkText(), m_output, openItem(), openSubBlock(), and DocRef::targetTitle().
visitPre() [28/38]
void PerlModDocVisitor::visitPre (DocSecRefItem *) virtual
Implements DocVisitor.
Definition at line 1204 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [29/38]
void PerlModDocVisitor::visitPre (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 1218 of file perlmodgen.cpp.
References PerlModOutput::add(), and m_output.
visitPre() [30/38]
void PerlModDocVisitor::visitPre (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 1243 of file perlmodgen.cpp.
References err(), DocParamSect::Exception, leaveText(), openOther(), openSubBlock(), DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, DocParamSect::type(), and DocParamSect::Unknown.
visitPre() [31/38]
void PerlModDocVisitor::visitPre (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 1267 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), PerlModOutput::closeHash(), PerlModOutput::closeList(), DocParamList::direction(), DocParamSect::hasInOutSpecifier(), DocParamSect::In, DocParamSect::InOut, DocNode::kind(), DocNode::Kind_LinkedWord, DocNode::Kind_ParamSect, DocNode::Kind_Word, leaveText(), m_output, PerlModOutput::openHash(), PerlModOutput::openList(), DocParamSect::Out, DocParamList::parameters(), DocNode::parent(), and DocParamSect::Unspecified.
visitPre() [32/38]
void PerlModDocVisitor::visitPre (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1328 of file perlmodgen.cpp.
References PerlModOutput::add(), PerlModOutput::addQuoted(), DocXRefItem::anchor(), DocXRefItem::file(), m_output, openItem(), openSubBlock(), and DocXRefItem::title().
visitPre() [33/38]
void PerlModDocVisitor::visitPre (DocInternalRef * ref) virtual
Implements DocVisitor.
Definition at line 1355 of file perlmodgen.cpp.
References addLink(), DocInternalRef::anchor(), DocInternalRef::file(), openItem(), and openSubBlock().
visitPre() [34/38]
void PerlModDocVisitor::visitPre (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1368 of file perlmodgen.cpp.
visitPre() [35/38]
void PerlModDocVisitor::visitPre (DocText *) virtual
Implements DocVisitor.
Definition at line 1376 of file perlmodgen.cpp.
visitPre() [36/38]
void PerlModDocVisitor::visitPre (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1384 of file perlmodgen.cpp.
References openItem(), and openSubBlock().
visitPre() [37/38]
void PerlModDocVisitor::visitPre (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1396 of file perlmodgen.cpp.
visitPre() [38/38]
void PerlModDocVisitor::visitPre (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1404 of file perlmodgen.cpp.
Member Data Documentation
m_other
QCString PerlModDocVisitor::m_other private
Definition at line 427 of file perlmodgen.cpp.
Referenced by finish().
m_output
PerlModOutput& PerlModDocVisitor::m_output private
Definition at line 424 of file perlmodgen.cpp.
Referenced by addLink(), closeItem(), closeSubBlock(), enterText(), finish(), leaveText(), openItem(), openSubBlock(), PerlModDocVisitor(), visit(), visitPost(), and visitPre().
m_textblockstart
bool PerlModDocVisitor::m_textblockstart private
Definition at line 426 of file perlmodgen.cpp.
Referenced by openSubBlock(), and visitPre().
m_textmode
bool PerlModDocVisitor::m_textmode private
Definition at line 425 of file perlmodgen.cpp.
Referenced by enterText(), and leaveText().
The documentation for this class was generated from the following file:
src/perlmodgen.cpp