Doxygen: NestingContext::Private Class Reference
NestingContext::Private Class Reference
Public Member Functions
Private (const NestingNodeContext *parent, int level)
void addNamespaces (const NamespaceSDict &nsDict, bool rootOnly, bool addClasses)
void addClasses (const ClassSDict &clDict, bool rootOnly)
void addDirs (const DirSDict &dirDict)
void addDirs (const DirList &dirList)
void addFiles (const FileNameList &fnList)
void addFiles (const FileList &fList)
void addPages (const PageSDict &pages, bool rootOnly)
void addModules (const GroupSDict &groups)
void addModules (const GroupList &list)
void addDerivedClasses (const BaseClassList *bcl, bool hideSuper)
void addClassHierarchy (const ClassSDict &classSDict, bool)
Public Member Functions inherited from GenericNodeListContext
GenericNodeListContext ()
int count () const
Returns the number of elements in the list.
TemplateVariant at (int index) const
Returns the element at index position index.
TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
void append (const TemplateVariant &ctn)
bool isEmpty () const
int addRef ()
Increase object's reference count.
int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Private Attributes
const NestingNodeContext * m_parent
int m_level
int m_index
Additional Inherited Members
Static Public Member Functions inherited from GenericNodeListContext
static GenericNodeListContext * alloc ()
Detailed Description
Definition at line 6416 of file context.cpp.
Constructor & Destructor Documentation
Private()
NestingContext::Private::Private (const NestingNodeContext * parent, int level) inline
Definition at line 6419 of file context.cpp.
Member Function Documentation
addClasses()
void NestingContext::Private::addClasses (const ClassSDict & clDict, bool rootOnly) inline
Definition at line 6442 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), classVisibleInIndex(), Definition::getLanguage(), Definition::getOuterScope(), Doxygen::globalScope, SDict< ClassDef >::Iterator, m_index, m_level, m_parent, VhdlDocGen::PACKAGECLASS, VhdlDocGen::PACKBODYCLASS, ClassDef::protection(), SrcLangExt_VHDL, and ClassDef::templateMaster().
Referenced by NestingContext::addClasses().
addClassHierarchy()
void NestingContext::Private::addClassHierarchy (const ClassSDict & classSDict, bool) inline
Definition at line 6597 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), ClassDef::baseClasses(), VhdlDocGen::ENTITYCLASS, Definition::getLanguage(), hasVisibleRoot(), ClassDef::isVisibleInHierarchy(), SDict< ClassDef >::Iterator, m_index, m_level, m_parent, ClassDef::protection(), SrcLangExt_VHDL, ClassDef::subClasses(), and ClassDef::visited.
Referenced by NestingContext::addClassHierarchy().
addDerivedClasses()
void NestingContext::Private::addDerivedClasses (const BaseClassList * bcl, bool hideSuper) inline
Definition at line 6566 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), ClassDef::baseClasses(), BaseClassDef::classDef, VhdlDocGen::ENTITYCLASS, Definition::getLanguage(), hasVisibleRoot(), ClassDef::isVisibleInHierarchy(), m_index, m_level, m_parent, ClassDef::protection(), SrcLangExt_VHDL, and ClassDef::subClasses().
Referenced by NestingContext::addDerivedClasses().
addDirs() [1/2]
void NestingContext::Private::addDirs (const DirSDict & dirDict) inline
Definition at line 6471 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), Definition::getOuterScope(), Doxygen::globalScope, m_index, m_level, and m_parent.
Referenced by NestingContext::addDirs().
addDirs() [2/2]
void NestingContext::Private::addDirs (const DirList & dirList) inline
Definition at line 6484 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), m_index, m_level, and m_parent.
addFiles() [1/2]
void NestingContext::Private::addFiles (const FileNameList & fnList) inline
Definition at line 6494 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), FileDef::getDirDef(), m_index, m_level, and m_parent.
Referenced by NestingContext::addFiles().
addFiles() [2/2]
void NestingContext::Private::addFiles (const FileList & fList) inline
Definition at line 6512 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), m_index, m_level, and m_parent.
addModules() [1/2]
void NestingContext::Private::addModules (const GroupSDict & groups) inline
Definition at line 6537 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), Config_getBool, GroupDef::isASubGroup(), Definition::isReference(), Definition::isVisible(), SDict< GroupDef >::Iterator, m_index, m_level, and m_parent.
Referenced by NestingContext::addModules().
addModules() [2/2]
void NestingContext::Private::addModules (const GroupList & list) inline
Definition at line 6553 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), Definition::isVisible(), m_index, m_level, and m_parent.
addNamespaces()
void NestingContext::Private::addNamespaces (const NamespaceSDict & nsDict, bool rootOnly, bool addClasses) inline
Definition at line 6422 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), Definition::getOuterScope(), Doxygen::globalScope, NamespaceDef::isLinkableInProject(), SDict< NamespaceDef >::Iterator, NamespaceDef::localName(), m_index, m_level, m_parent, and namespaceHasVisibleChild().
Referenced by NestingContext::addNamespaces().
addPages()
void NestingContext::Private::addPages (const PageSDict & pages, bool rootOnly) inline
Definition at line 6522 of file context.cpp.
References NestingNodeContext::alloc(), GenericNodeListContext::append(), DefinitionIntf::definitionType(), Definition::getOuterScope(), m_index, m_level, m_parent, and DefinitionIntf::TypePage.
Referenced by NestingContext::addPages().
Member Data Documentation
m_index
int NestingContext::Private::m_index private
Definition at line 6632 of file context.cpp.
Referenced by addClasses(), addClassHierarchy(), addDerivedClasses(), addDirs(), addFiles(), addModules(), addNamespaces(), and addPages().
m_level
int NestingContext::Private::m_level private
Definition at line 6631 of file context.cpp.
Referenced by addClasses(), addClassHierarchy(), addDerivedClasses(), addDirs(), addFiles(), addModules(), addNamespaces(), and addPages().
m_parent
const NestingNodeContext* NestingContext::Private::m_parent private
Definition at line 6630 of file context.cpp.
Referenced by addClasses(), addClassHierarchy(), addDerivedClasses(), addDirs(), addFiles(), addModules(), addNamespaces(), and addPages().
The documentation for this class was generated from the following file:
src/context.cpp