Doxygen: LatexGenerator Class Reference
LatexGenerator Class Reference
Generator for LaTeX output.
#include <latexgen.h>
Public Member Functions
LatexGenerator ()
~LatexGenerator ()
void enable ()
void disable ()
void enableIf (OutputType o)
void disableIf (OutputType o)
void disableIfNot (OutputType o)
bool isEnabled (OutputType o)
OutputGenerator * get (OutputType o)
void codify (const char *text)
void writeCodeLink (const char *ref, const char *file, const char *anchor, const char *name, const char *tooltip)
void writeLineNumber (const char *ref, const char *file, const char *anchor, int lineNumber)
void writeTooltip (const char *id, const DocLinkInfo &docInfo, const char *decl, const char *desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void startFontClass (const char *s)
void endFontClass ()
void writeCodeAnchor (const char *anchor)
void writeDoc (DocNode *, Definition *ctx, MemberDef *)
void startFile (const char *name, const char *manName, const char *title)
void writeSearchInfo ()
void writeFooter (const char *)
void endFile ()
void clearBuffer ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const char *, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startTitleHead (const char *)
void startTitle ()
void endTitleHead (const char *, const char *name)
void endTitle ()
void newParagraph ()
void startParagraph (const char *classDef)
void endParagraph ()
void writeString (const char *text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const char *, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const char *ref, const char *file)
void endIndexItem (const char *ref, const char *file)
void docify (const char *text)
void writeObjectLink (const char *ref, const char *file, const char *anchor, const char *name)
void startTextLink (const char *, const char *)
void endTextLink ()
void startHtmlLink (const char *url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const char *)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const char *, int, const char *)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const char *, const char *)
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void insertMemberAlign (bool)
void writeRuler ()
void writeAnchor (const char *fileName, const char *name)
void startCodeFragment ()
void endCodeFragment ()
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void lineBreak (const char *style=0)
void startMemberDoc (const char *, const char *, const char *, const char *, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const char *, const char *, const char *, const char *, const char *)
void endDoxyAnchor (const char *, const char *)
void writeChar (char c)
void writeLatexSpacing ()
void writeStartAnnoItem (const char *type, const char *file, const char *path, const char *name)
void writeEndAnnoItem (const char *name)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startMemberDescription (const char *, const char *)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const char *, const char *)
void writeInheritedSectionTitle (const char *, const char *, const char *, const char *, const char *, const char *)
void startDescList (SectionTypes)
void endDescList ()
void startSimpleSect (SectionTypes, const char *, const char *, const char *)
void endSimpleSect ()
void startParamList (ParamListTypes, const char *title)
void endParamList ()
void startDescForItem ()
void endDescForItem ()
void startSection (const char *, const char *, SectionInfo::SectionType)
void endSection (const char *, SectionInfo::SectionType)
void addIndexItem (const char *, const char *)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const char *, const char *)
void startPageRef ()
void endPageRef (const char *, const char *)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const char *)
void writeNavigationPath (const char *)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const char *)
void writeSummaryLink (const char *, const char *, const char *, bool)
void startContents ()
void endContents ()
void writeNonBreakableSpace (int)
void startDescTable (const char *title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void lastIndexPage ()
void startDotGraph ()
void endDotGraph (const DotClassGraph &)
void startInclDepGraph ()
void endInclDepGraph (const DotInclDepGraph &)
void startCallGraph ()
void startGroupCollaboration ()
void endGroupCollaboration (const DotGroupCollaboration &g)
void endCallGraph (const DotCallGraph &)
void startDirDepGraph ()
void endDirDepGraph (const DotDirDeps &g)
void writeGraphicalHierarchy (const DotGfxHierarchyTable &)
void startTextBlock (bool)
void endTextBlock (bool)
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const char *)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const char *, bool)
void startConstraintList (const char *)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const char *l, bool isLast)
void endLabels ()
void setCurrentDoc (Definition *, const char *, bool)
void addWord (const char *, bool)
Public Member Functions inherited from OutputGenerator
OutputGenerator ()
virtual ~OutputGenerator ()
void startPlainFile (const char *name)
void endPlainFile ()
bool isEnabled () const
void pushGeneratorState ()
void popGeneratorState ()
Public Member Functions inherited from BaseOutputDocInterface
virtual ~BaseOutputDocInterface ()
virtual bool parseText (const QCString &s)
Public Member Functions inherited from CodeOutputInterface
virtual ~CodeOutputInterface ()
Static Public Member Functions
static void init ()
static void writeStyleSheetFile (QFile &f)
static void writeHeaderFile (QFile &f)
static void writeFooterFile (QFile &f)
Private Member Functions
LatexGenerator (const LatexGenerator &)
LatexGenerator & operator= (const LatexGenerator &)
Private Attributes
bool insideTabbing
bool firstDescItem
bool disableLinks
QCString relPath
int m_indent
bool templateMemberItem
bool m_prettyCode
LatexCodeGenerator m_codeGen
Additional Inherited Members
Public Types inherited from OutputGenerator
enum OutputType {
Html, Latex, Man, RTF,
XML, DEF, Perl
}
Public Types inherited from BaseOutputDocInterface
enum ParamListTypes { Param, RetVal, Exception }
enum SectionTypes { EnumValues, Examples }
Protected Attributes inherited from OutputGenerator
FTextStream t
QFile * file
QCString fileName
QCString dir
bool active
QStack< bool > * genStack
Detailed Description
Generator for LaTeX output.
Definition at line 70 of file latexgen.h.
Constructor & Destructor Documentation
LatexGenerator() [1/2]
LatexGenerator::LatexGenerator ()
Definition at line 246 of file latexgen.cpp.
References Config_getBool, Config_getString, OutputGenerator::dir, disableLinks, firstDescItem, insideTabbing, m_indent, m_prettyCode, and templateMemberItem.
~LatexGenerator()
LatexGenerator::~LatexGenerator ()
Definition at line 258 of file latexgen.cpp.
LatexGenerator() [2/2]
LatexGenerator::LatexGenerator (const LatexGenerator &) private
Member Function Documentation
addIndexItem()
void LatexGenerator::addIndexItem (const char * s1, const char * s2) virtual
Implements BaseOutputDocInterface.
Definition at line 1642 of file latexgen.cpp.
References insideTabbing, latexEscapeIndexChars(), latexEscapeLabelName(), and OutputGenerator::t.
addWord()
void LatexGenerator::addWord (const char * , bool) inline virtual
Implements CodeOutputInterface.
Definition at line 323 of file latexgen.h.
clearBuffer()
void LatexGenerator::clearBuffer ()
codify()
void LatexGenerator::codify (const char * s) inline virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 93 of file latexgen.h.
References LatexCodeGenerator::codify(), and m_codeGen.
disable()
void LatexGenerator::disable () inline virtual
Implements OutputGenerator.
Definition at line 85 of file latexgen.h.
References OutputGenerator::active.
Referenced by disableIf(), and disableIfNot().
disableIf()
void LatexGenerator::disableIf (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 87 of file latexgen.h.
References disable(), and OutputGenerator::Latex.
disableIfNot()
void LatexGenerator::disableIfNot (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 88 of file latexgen.h.
References disable(), and OutputGenerator::Latex.
docify()
void LatexGenerator::docify (const char * s) virtual
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 1707 of file latexgen.cpp.
References filterLatexString(), insideTabbing, and OutputGenerator::t.
Referenced by startConstraintList(), startMemberDocSimple(), startParamList(), startSimpleSect(), writeChar(), writeObjectLink(), and writeStartAnnoItem().
enable()
void LatexGenerator::enable () inline virtual
Implements OutputGenerator.
Definition at line 83 of file latexgen.h.
References OutputGenerator::active, and OutputGenerator::genStack.
Referenced by enableIf().
enableIf()
void LatexGenerator::enableIf (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 86 of file latexgen.h.
References enable(), and OutputGenerator::Latex.
endAnonTypeScope()
void LatexGenerator::endAnonTypeScope (int indent) virtual
Implements OutputGenerator.
Definition at line 1744 of file latexgen.cpp.
References endl(), insideTabbing, m_indent, and OutputGenerator::t.
endBold()
void LatexGenerator::endBold () inline virtual
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 205 of file latexgen.h.
References OutputGenerator::t.
endCallGraph()
void LatexGenerator::endCallGraph (const DotCallGraph & g) virtual
Implements OutputGenerator.
Definition at line 1981 of file latexgen.cpp.
References Config_getString, EOF_LaTeX, OutputGenerator::fileName, GOF_EPS, relPath, OutputGenerator::t, and DotCallGraph::writeGraph().
endCenter()
void LatexGenerator::endCenter () inline virtual
Implements BaseOutputDocInterface.
Definition at line 225 of file latexgen.h.
References endl(), and OutputGenerator::t.
endClassDiagram()
void LatexGenerator::endClassDiagram (const ClassDiagram & d, const char * fileName, const char *) virtual
Implements OutputGenerator.
Definition at line 1726 of file latexgen.cpp.
References OutputGenerator::dir, OutputGenerator::t, and ClassDiagram::writeFigure().
endCodeFragment()
void LatexGenerator::endCodeFragment () virtual
Ends a source code fragment
Implements BaseOutputDocInterface.
Definition at line 2157 of file latexgen.cpp.
References OutputGenerator::t.
endCodeLine()
void LatexGenerator::endCodeLine () inline virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 107 of file latexgen.h.
References LatexCodeGenerator::endCodeLine(), and m_codeGen.
endConstraintDocs()
void LatexGenerator::endConstraintDocs () virtual
Implements OutputGenerator.
Definition at line 2142 of file latexgen.cpp.
endConstraintList()
void LatexGenerator::endConstraintList () virtual
Implements OutputGenerator.
Definition at line 2146 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endConstraintParam()
void LatexGenerator::endConstraintParam () virtual
Implements OutputGenerator.
Definition at line 2124 of file latexgen.cpp.
endConstraintType()
void LatexGenerator::endConstraintType () virtual
Implements OutputGenerator.
Definition at line 2133 of file latexgen.cpp.
References OutputGenerator::t.
endContents()
void LatexGenerator::endContents () inline virtual
Implements OutputGenerator.
Definition at line 260 of file latexgen.h.
endDescForItem()
void LatexGenerator::endDescForItem () inline virtual
Implements BaseOutputDocInterface.
Definition at line 241 of file latexgen.h.
endDescItem()
void LatexGenerator::endDescItem () virtual
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 2012 of file latexgen.cpp.
References endl(), firstDescItem, lineBreak(), and OutputGenerator::t.
endDescList()
void LatexGenerator::endDescList () inline
Definition at line 235 of file latexgen.h.
References endl(), and OutputGenerator::t.
endDescription()
void LatexGenerator::endDescription () virtual
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 2000 of file latexgen.cpp.
References endl(), firstDescItem, and OutputGenerator::t.
endDescTable()
void LatexGenerator::endDescTable () virtual
Implements BaseOutputDocInterface.
Definition at line 1849 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endDescTableData()
void LatexGenerator::endDescTableData () virtual
Implements BaseOutputDocInterface.
Definition at line 1879 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endDescTableRow()
void LatexGenerator::endDescTableRow () virtual
Implements BaseOutputDocInterface.
Definition at line 1861 of file latexgen.cpp.
endDescTableTitle()
void LatexGenerator::endDescTableTitle () virtual
Implements BaseOutputDocInterface.
Definition at line 1870 of file latexgen.cpp.
endDirDepGraph()
void LatexGenerator::endDirDepGraph (const DotDirDeps & g) virtual
Implements OutputGenerator.
Definition at line 1990 of file latexgen.cpp.
References Config_getString, EOF_LaTeX, OutputGenerator::fileName, GOF_EPS, relPath, OutputGenerator::t, and DotDirDeps::writeGraph().
endDotGraph()
void LatexGenerator::endDotGraph (const DotClassGraph & g) virtual
Implements OutputGenerator.
Definition at line 1954 of file latexgen.cpp.
References Config_getString, EOF_LaTeX, OutputGenerator::fileName, GOF_EPS, relPath, OutputGenerator::t, and DotClassGraph::writeGraph().
endDoxyAnchor()
void LatexGenerator::endDoxyAnchor (const char * fName, const char * anchor) virtual
Implements OutputGenerator.
Definition at line 1613 of file latexgen.cpp.
endEmphasis()
void LatexGenerator::endEmphasis () inline virtual
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 203 of file latexgen.h.
References OutputGenerator::t.
endFile()
void LatexGenerator::endFile () virtual
Implements OutputGenerator.
Definition at line 796 of file latexgen.cpp.
References OutputGenerator::endPlainFile(), m_codeGen, and LatexCodeGenerator::setSourceFileName().
endFontClass()
void LatexGenerator::endFontClass () inline virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 111 of file latexgen.h.
References LatexCodeGenerator::endFontClass(), and m_codeGen.
endGroupCollaboration()
void LatexGenerator::endGroupCollaboration (const DotGroupCollaboration & g) virtual
Implements OutputGenerator.
Definition at line 1972 of file latexgen.cpp.
References Config_getString, EOF_LaTeX, OutputGenerator::fileName, GOF_EPS, relPath, OutputGenerator::t, and DotGroupCollaboration::writeGraph().
endGroupHeader()
void LatexGenerator::endGroupHeader (int) virtual
Implements OutputGenerator.
Definition at line 1496 of file latexgen.cpp.
References disableLinks, endl(), and OutputGenerator::t.
endHeaderSection()
void LatexGenerator::endHeaderSection () inline virtual
Implements OutputGenerator.
Definition at line 171 of file latexgen.h.
endHtmlLink()
void LatexGenerator::endHtmlLink () virtual
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 1310 of file latexgen.cpp.
References OutputGenerator::t.
endInclDepGraph()
void LatexGenerator::endInclDepGraph (const DotInclDepGraph & g) virtual
Implements OutputGenerator.
Definition at line 1963 of file latexgen.cpp.
References Config_getString, EOF_LaTeX, OutputGenerator::fileName, GOF_EPS, relPath, OutputGenerator::t, and DotInclDepGraph::writeGraph().
endIndent()
void LatexGenerator::endIndent () inline virtual
Implements OutputGenerator.
Definition at line 246 of file latexgen.h.
endIndexItem()
void LatexGenerator::endIndexItem (const char * ref, const char * file) virtual
Implements OutputGenerator.
Definition at line 1283 of file latexgen.cpp.
References endl(), stripPath(), and OutputGenerator::t.
endIndexKey()
void LatexGenerator::endIndexKey () virtual
Implements OutputGenerator.
Definition at line 1347 of file latexgen.cpp.
endIndexList()
void LatexGenerator::endIndexList () inline virtual
Implements OutputGenerator.
Definition at line 144 of file latexgen.h.
References endl(), and OutputGenerator::t.
endIndexListItem()
void LatexGenerator::endIndexListItem () inline virtual
Implements OutputGenerator.
Definition at line 142 of file latexgen.h.
endIndexSection()
void LatexGenerator::endIndexSection (IndexSections is) virtual
Implements OutputGenerator.
Definition at line 987 of file latexgen.cpp.
References Doxygen::classSDict, Config_getBool, Config_getString, convertToLaTeX(), Doxygen::directories, Doxygen::exampleSDict, fileToString(), FileDef::generateSourceFile(), PageDef::getGroupDef(), NamespaceDef::getOutputFileBase(), GroupDef::getOutputFileBase(), PageDef::getOutputFileBase(), DirDef::getOutputFileBase(), FileDef::getOutputFileBase(), ClassDef::getOutputFileBase(), FileDef::getSourceFileBase(), Doxygen::groupSDict, Doxygen::inputNameList, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isDirDocumentation, isDirIndex, ClassDef::isEmbeddedInOuterScope(), isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, DirDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), FileDef::isLinkableInProject(), ClassDef::isLinkableInProject(), isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, Definition::isReference(), isTitlePageAuthor, isTitlePageStart, SDict< GroupDef >::Iterator, SDict< NamespaceDef >::Iterator, SDict< PageDef >::Iterator, SDict< ClassDef >::Iterator, m_prettyCode, Doxygen::namespaceSDict, Doxygen::pageSDict, substituteKeywords(), OutputGenerator::t, ClassDef::templateMaster(), PageDef::title(), writeDefaultFooter(), and writeDefaultHeaderPart3().
endIndexValue()
void LatexGenerator::endIndexValue (const char * name, bool) virtual
Implements OutputGenerator.
Definition at line 1357 of file latexgen.cpp.
References endl(), stripPath(), and OutputGenerator::t.
endInlineHeader()
void LatexGenerator::endInlineHeader () virtual
Implements OutputGenerator.
Definition at line 2174 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endInlineMemberDoc()
void LatexGenerator::endInlineMemberDoc () virtual
Implements OutputGenerator.
Definition at line 2244 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endInlineMemberName()
void LatexGenerator::endInlineMemberName () virtual
Implements OutputGenerator.
Definition at line 2234 of file latexgen.cpp.
References endl(), insideTabbing, and OutputGenerator::t.
endInlineMemberType()
void LatexGenerator::endInlineMemberType () virtual
Implements OutputGenerator.
Definition at line 2223 of file latexgen.cpp.
References endl(), insideTabbing, and OutputGenerator::t.
endItemList()
void LatexGenerator::endItemList () inline virtual
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 150 of file latexgen.h.
References endl(), and OutputGenerator::t.
endItemListItem()
void LatexGenerator::endItemListItem () inline virtual
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 166 of file latexgen.h.
endLabels()
void LatexGenerator::endLabels () virtual
Implements OutputGenerator.
Definition at line 2260 of file latexgen.cpp.
endMemberDeclaration()
void LatexGenerator::endMemberDeclaration (const char * , const char *) inline virtual
Implements OutputGenerator.
Definition at line 231 of file latexgen.h.
endMemberDescription()
void LatexGenerator::endMemberDescription () virtual
Implements OutputGenerator.
Definition at line 1803 of file latexgen.cpp.
References insideTabbing, and OutputGenerator::t.
endMemberDoc()
void LatexGenerator::endMemberDoc (bool) virtual
Implements OutputGenerator.
Definition at line 1586 of file latexgen.cpp.
References disableLinks, and OutputGenerator::t.
endMemberDocList()
void LatexGenerator::endMemberDocList () inline virtual
Implements OutputGenerator.
Definition at line 177 of file latexgen.h.
endMemberDocName()
void LatexGenerator::endMemberDocName () inline virtual
Implements OutputGenerator.
Definition at line 291 of file latexgen.h.
endMemberDocPrefixItem()
void LatexGenerator::endMemberDocPrefixItem () inline virtual
Implements OutputGenerator.
Definition at line 289 of file latexgen.h.
References endl(), and OutputGenerator::t.
endMemberDocSimple()
void LatexGenerator::endMemberDocSimple (bool isEnum) virtual
Implements OutputGenerator.
Definition at line 2206 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endMemberGroup()
void LatexGenerator::endMemberGroup (bool hasHeader) virtual
Implements OutputGenerator.
Definition at line 1943 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endMemberGroupDocs()
void LatexGenerator::endMemberGroupDocs () virtual
Implements OutputGenerator.
Definition at line 1934 of file latexgen.cpp.
References OutputGenerator::t.
endMemberGroupHeader()
void LatexGenerator::endMemberGroupHeader () virtual
Implements OutputGenerator.
Definition at line 1922 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endMemberHeader()
void LatexGenerator::endMemberHeader () virtual
Implements OutputGenerator.
Definition at line 1515 of file latexgen.cpp.
References disableLinks, endl(), and OutputGenerator::t.
endMemberItem()
void LatexGenerator::endMemberItem () virtual
Implements OutputGenerator.
Definition at line 1780 of file latexgen.cpp.
References endl(), insideTabbing, OutputGenerator::t, and templateMemberItem.
endMemberList()
void LatexGenerator::endMemberList () virtual
Implements OutputGenerator.
Definition at line 1897 of file latexgen.cpp.
References endl(), insideTabbing, and OutputGenerator::t.
endMemberSections()
void LatexGenerator::endMemberSections () inline virtual
Implements OutputGenerator.
Definition at line 169 of file latexgen.h.
endMemberSubtitle()
void LatexGenerator::endMemberSubtitle () inline virtual
Implements OutputGenerator.
Definition at line 175 of file latexgen.h.
endMemberTemplateParams()
void LatexGenerator::endMemberTemplateParams (const char * , const char *) virtual
Implements OutputGenerator.
Definition at line 1762 of file latexgen.cpp.
References OutputGenerator::t, and templateMemberItem.
endPageRef()
void LatexGenerator::endPageRef (const char * clname, const char * anchor) virtual
Implements BaseOutputDocInterface.
Definition at line 1418 of file latexgen.cpp.
References OutputGenerator::t.
endParagraph()
void LatexGenerator::endParagraph () virtual
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 1264 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endParameterList()
void LatexGenerator::endParameterList () virtual
Implements OutputGenerator.
Definition at line 2064 of file latexgen.cpp.
endParameterName()
void LatexGenerator::endParameterName (bool last, bool , bool closeBracket) virtual
Implements OutputGenerator.
Definition at line 2084 of file latexgen.cpp.
References OutputGenerator::t.
endParameterType()
void LatexGenerator::endParameterType () virtual
Implements OutputGenerator.
Definition at line 2074 of file latexgen.cpp.
References OutputGenerator::t.
endParamList()
void LatexGenerator::endParamList () virtual
Implements BaseOutputDocInterface.
Definition at line 2052 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endProjectNumber()
void LatexGenerator::endProjectNumber () inline virtual
Implements OutputGenerator.
Definition at line 130 of file latexgen.h.
endQuickIndices()
void LatexGenerator::endQuickIndices () inline virtual
Implements OutputGenerator.
Definition at line 253 of file latexgen.h.
endSection()
void LatexGenerator::endSection (const char * lab, SectionInfo::SectionType) virtual
Implements BaseOutputDocInterface.
Definition at line 1701 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endSimpleSect()
void LatexGenerator::endSimpleSect () virtual
Implements BaseOutputDocInterface.
Definition at line 2040 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
endSmall()
void LatexGenerator::endSmall () inline virtual
Implements BaseOutputDocInterface.
Definition at line 227 of file latexgen.h.
References OutputGenerator::t.
endSubsection()
void LatexGenerator::endSubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 221 of file latexgen.h.
References endl(), and OutputGenerator::t.
endSubsubsection()
void LatexGenerator::endSubsubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 223 of file latexgen.h.
References endl(), and OutputGenerator::t.
endTextBlock()
void LatexGenerator::endTextBlock (bool) inline virtual
Implements OutputGenerator.
Definition at line 286 of file latexgen.h.
endTextLink()
void LatexGenerator::endTextLink () virtual
Implements BaseOutputDocInterface.
Definition at line 1386 of file latexgen.cpp.
References OutputGenerator::t.
endTitle()
void LatexGenerator::endTitle () inline virtual
Implements BaseOutputDocInterface.
Definition at line 135 of file latexgen.h.
References OutputGenerator::t.
endTitleHead()
void LatexGenerator::endTitleHead (const char * fileName, const char * name) virtual
Implements OutputGenerator.
Definition at line 1445 of file latexgen.cpp.
References endl(), insideTabbing, latexEscapeIndexChars(), latexEscapeLabelName(), stripPath(), and OutputGenerator::t.
endTypewriter()
void LatexGenerator::endTypewriter () inline virtual
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 162 of file latexgen.h.
References OutputGenerator::t.
exceptionEntry()
void LatexGenerator::exceptionEntry (const char * prefix, bool closeBracket) virtual
Implements OutputGenerator.
Definition at line 2094 of file latexgen.cpp.
References OutputGenerator::t.
get()
OutputGenerator* LatexGenerator::get (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 90 of file latexgen.h.
References OutputGenerator::Latex.
init()
void LatexGenerator::init () static
Definition at line 437 of file latexgen.cpp.
References Config_getString, createSubDirs(), OutputGenerator::dir, err(), writeLatexMakefile(), and writeMakeBat().
Referenced by generateOutput().
insertMemberAlign()
void LatexGenerator::insertMemberAlign (bool) inline virtual
Implements OutputGenerator.
Definition at line 196 of file latexgen.h.
isEnabled()
bool LatexGenerator::isEnabled (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 89 of file latexgen.h.
References OutputGenerator::active, and OutputGenerator::Latex.
lastIndexPage()
void LatexGenerator::lastIndexPage () virtual
Implements OutputGenerator.
Definition at line 1884 of file latexgen.cpp.
lineBreak()
void LatexGenerator::lineBreak (const char * style = 0) virtual
Implements BaseOutputDocInterface.
Definition at line 2179 of file latexgen.cpp.
References insideTabbing, and OutputGenerator::t.
Referenced by endDescItem().
newParagraph()
void LatexGenerator::newParagraph ()
Definition at line 1254 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
Referenced by startDotGraph().
operator=()
LatexGenerator& LatexGenerator::operator= (const LatexGenerator &) private
setCurrentDoc()
void LatexGenerator::setCurrentDoc (Definition * , const char * , bool) inline virtual
Implements CodeOutputInterface.
Definition at line 322 of file latexgen.h.
startAnonTypeScope()
void LatexGenerator::startAnonTypeScope (int indent) virtual
Implements OutputGenerator.
Definition at line 1733 of file latexgen.cpp.
References endl(), insideTabbing, m_indent, and OutputGenerator::t.
startBold()
void LatexGenerator::startBold () inline virtual
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 204 of file latexgen.h.
References OutputGenerator::t.
startCallGraph()
void LatexGenerator::startCallGraph () virtual
Implements OutputGenerator.
Definition at line 1977 of file latexgen.cpp.
startCenter()
void LatexGenerator::startCenter () inline virtual
Implements BaseOutputDocInterface.
Definition at line 224 of file latexgen.h.
References endl(), and OutputGenerator::t.
startClassDiagram()
void LatexGenerator::startClassDiagram () virtual
Implements OutputGenerator.
Definition at line 1720 of file latexgen.cpp.
startCodeFragment()
void LatexGenerator::startCodeFragment () virtual
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Implements BaseOutputDocInterface.
Definition at line 2152 of file latexgen.cpp.
References OutputGenerator::t.
startCodeLine()
void LatexGenerator::startCodeLine (bool hasLineNumbers) inline virtual
Implements CodeOutputInterface.
Definition at line 105 of file latexgen.h.
References m_codeGen, and LatexCodeGenerator::startCodeLine().
startConstraintDocs()
void LatexGenerator::startConstraintDocs () virtual
Implements OutputGenerator.
Definition at line 2138 of file latexgen.cpp.
startConstraintList()
void LatexGenerator::startConstraintList (const char * header) virtual
Implements OutputGenerator.
Definition at line 2111 of file latexgen.cpp.
References docify(), endl(), and OutputGenerator::t.
startConstraintParam()
void LatexGenerator::startConstraintParam () virtual
Implements OutputGenerator.
Definition at line 2119 of file latexgen.cpp.
References OutputGenerator::t.
startConstraintType()
void LatexGenerator::startConstraintType () virtual
Implements OutputGenerator.
Definition at line 2128 of file latexgen.cpp.
References OutputGenerator::t.
startContents()
void LatexGenerator::startContents () inline virtual
Implements OutputGenerator.
Definition at line 259 of file latexgen.h.
startDescForItem()
void LatexGenerator::startDescForItem () inline virtual
Implements BaseOutputDocInterface.
Definition at line 240 of file latexgen.h.
References endl(), and OutputGenerator::t.
startDescItem()
void LatexGenerator::startDescItem () virtual
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 2006 of file latexgen.cpp.
References firstDescItem, and OutputGenerator::t.
startDescList()
void LatexGenerator::startDescList (SectionTypes) inline
Definition at line 234 of file latexgen.h.
References OutputGenerator::t.
startDescription()
void LatexGenerator::startDescription () virtual
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 1995 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
startDescTable()
void LatexGenerator::startDescTable (const char * title) virtual
Implements BaseOutputDocInterface.
Definition at line 1844 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
startDescTableData()
void LatexGenerator::startDescTableData () virtual
Implements BaseOutputDocInterface.
Definition at line 1874 of file latexgen.cpp.
References OutputGenerator::t.
startDescTableRow()
void LatexGenerator::startDescTableRow () virtual
Implements BaseOutputDocInterface.
Definition at line 1854 of file latexgen.cpp.
References OutputGenerator::t.
startDescTableTitle()
void LatexGenerator::startDescTableTitle () virtual
Implements BaseOutputDocInterface.
Definition at line 1865 of file latexgen.cpp.
References OutputGenerator::t.
startDirDepGraph()
void LatexGenerator::startDirDepGraph () virtual
Implements OutputGenerator.
Definition at line 1986 of file latexgen.cpp.
startDotGraph()
void LatexGenerator::startDotGraph () virtual
Implements OutputGenerator.
Definition at line 1949 of file latexgen.cpp.
References newParagraph().
startDoxyAnchor()
void LatexGenerator::startDoxyAnchor (const char * fName, const char * , const char * anchor, const char * , const char *) virtual
Implements OutputGenerator.
Definition at line 1593 of file latexgen.cpp.
References Config_getBool, endl(), stripPath(), and OutputGenerator::t.
startEmphasis()
void LatexGenerator::startEmphasis () inline virtual
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 202 of file latexgen.h.
References OutputGenerator::t.
startFile()
void LatexGenerator::startFile (const char * name, const char * manName, const char * title) virtual
Implements OutputGenerator.
Definition at line 782 of file latexgen.cpp.
References Config_getString, OutputGenerator::fileName, m_codeGen, relativePathToRoot(), relPath, LatexCodeGenerator::setRelativePath(), LatexCodeGenerator::setSourceFileName(), LatexCodeGenerator::setTextStream(), OutputGenerator::startPlainFile(), stripPath(), and OutputGenerator::t.
startFontClass()
void LatexGenerator::startFontClass (const char * clsName) inline virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 109 of file latexgen.h.
References m_codeGen, and LatexCodeGenerator::startFontClass().
startGroupCollaboration()
void LatexGenerator::startGroupCollaboration () virtual
Implements OutputGenerator.
Definition at line 1968 of file latexgen.cpp.
startGroupHeader()
void LatexGenerator::startGroupHeader (int extraIndentLevel) virtual
Implements OutputGenerator.
Definition at line 1470 of file latexgen.cpp.
References Config_getBool, disableLinks, and OutputGenerator::t.
startHeaderSection()
void LatexGenerator::startHeaderSection () inline virtual
Implements OutputGenerator.
Definition at line 170 of file latexgen.h.
startHtmlLink()
void LatexGenerator::startHtmlLink (const char * url) virtual
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 1299 of file latexgen.cpp.
References Config_getBool, and OutputGenerator::t.
startInclDepGraph()
void LatexGenerator::startInclDepGraph () virtual
Implements OutputGenerator.
Definition at line 1959 of file latexgen.cpp.
startIndent()
void LatexGenerator::startIndent () inline virtual
Implements OutputGenerator.
Definition at line 245 of file latexgen.h.
startIndexItem()
void LatexGenerator::startIndexItem (const char * ref, const char * file) virtual
Implements OutputGenerator.
Definition at line 1274 of file latexgen.cpp.
References OutputGenerator::t.
startIndexKey()
void LatexGenerator::startIndexKey () virtual
Implements OutputGenerator.
Definition at line 1342 of file latexgen.cpp.
References OutputGenerator::t.
startIndexList()
void LatexGenerator::startIndexList () inline virtual
Implements OutputGenerator.
Definition at line 143 of file latexgen.h.
References endl(), and OutputGenerator::t.
startIndexListItem()
void LatexGenerator::startIndexListItem () inline virtual
Implements OutputGenerator.
Definition at line 141 of file latexgen.h.
startIndexSection()
void LatexGenerator::startIndexSection (IndexSections is) virtual
Implements OutputGenerator.
Definition at line 812 of file latexgen.cpp.
References Doxygen::classSDict, Config_getBool, Config_getString, convertToLaTeX(), Doxygen::directories, fileToString(), Doxygen::groupSDict, Doxygen::inputNameList, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isDirDocumentation, isDirIndex, ClassDef::isEmbeddedInOuterScope(), isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, DirDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), FileDef::isLinkableInProject(), ClassDef::isLinkableInProject(), isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, Definition::isReference(), isTitlePageAuthor, isTitlePageStart, SDict< GroupDef >::Iterator, SDict< ClassDef >::Iterator, SDict< NamespaceDef >::Iterator, Doxygen::namespaceSDict, substituteKeywords(), OutputGenerator::t, ClassDef::templateMaster(), writeDefaultHeaderPart1(), and writeDefaultHeaderPart2().
startIndexValue()
void LatexGenerator::startIndexValue (bool hasBrief) virtual
Implements OutputGenerator.
Definition at line 1351 of file latexgen.cpp.
References OutputGenerator::t.
startInlineHeader()
void LatexGenerator::startInlineHeader () virtual
Implements OutputGenerator.
Definition at line 2162 of file latexgen.cpp.
References Config_getBool, and OutputGenerator::t.
startInlineMemberDoc()
void LatexGenerator::startInlineMemberDoc () virtual
Implements OutputGenerator.
Definition at line 2240 of file latexgen.cpp.
startInlineMemberName()
void LatexGenerator::startInlineMemberName () virtual
Implements OutputGenerator.
Definition at line 2229 of file latexgen.cpp.
References insideTabbing.
startInlineMemberType()
void LatexGenerator::startInlineMemberType () virtual
Implements OutputGenerator.
Definition at line 2218 of file latexgen.cpp.
References insideTabbing.
startItemList()
void LatexGenerator::startItemList () inline virtual
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 149 of file latexgen.h.
References endl(), and OutputGenerator::t.
startItemListItem()
void LatexGenerator::startItemListItem () inline virtual
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 165 of file latexgen.h.
References endl(), and OutputGenerator::t.
startLabels()
void LatexGenerator::startLabels () virtual
Implements OutputGenerator.
Definition at line 2249 of file latexgen.cpp.
References OutputGenerator::t.
startMemberDeclaration()
void LatexGenerator::startMemberDeclaration () inline virtual
Implements OutputGenerator.
Definition at line 230 of file latexgen.h.
startMemberDescription()
void LatexGenerator::startMemberDescription (const char * , const char *) virtual
Implements OutputGenerator.
Definition at line 1790 of file latexgen.cpp.
References insideTabbing, m_indent, and OutputGenerator::t.
startMemberDoc()
void LatexGenerator::startMemberDoc (const char * clname, const char * memname, const char * , const char * title, int memCount, int memTotal, bool showInline) virtual
Implements OutputGenerator.
Definition at line 1521 of file latexgen.cpp.
References Config_getBool, endl(), insideTabbing, latexEscapeIndexChars(), latexEscapeLabelName(), latexEscapePDFString(), and OutputGenerator::t.
startMemberDocList()
void LatexGenerator::startMemberDocList () inline virtual
Implements OutputGenerator.
Definition at line 176 of file latexgen.h.
startMemberDocName()
void LatexGenerator::startMemberDocName (bool) inline virtual
Implements OutputGenerator.
Definition at line 290 of file latexgen.h.
startMemberDocPrefixItem()
void LatexGenerator::startMemberDocPrefixItem () inline virtual
Implements OutputGenerator.
Definition at line 288 of file latexgen.h.
startMemberDocSimple()
void LatexGenerator::startMemberDocSimple (bool isEnum) virtual
Implements OutputGenerator.
Definition at line 2191 of file latexgen.cpp.
References docify(), endl(), OutputGenerator::t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberGroup()
void LatexGenerator::startMemberGroup () virtual
Implements OutputGenerator.
Definition at line 1939 of file latexgen.cpp.
startMemberGroupDocs()
void LatexGenerator::startMemberGroupDocs () virtual
Implements OutputGenerator.
Definition at line 1929 of file latexgen.cpp.
References OutputGenerator::t.
startMemberGroupHeader()
void LatexGenerator::startMemberGroupHeader (bool hasHeader) virtual
Implements OutputGenerator.
Definition at line 1907 of file latexgen.cpp.
References OutputGenerator::t.
startMemberHeader()
void LatexGenerator::startMemberHeader (const char *) virtual
Implements OutputGenerator.
Definition at line 1502 of file latexgen.cpp.
References Config_getBool, disableLinks, and OutputGenerator::t.
startMemberItem()
void LatexGenerator::startMemberItem (const char * , int annoType, const char *) virtual
Implements OutputGenerator.
Definition at line 1770 of file latexgen.cpp.
References endl(), insideTabbing, OutputGenerator::t, and templateMemberItem.
startMemberList()
void LatexGenerator::startMemberList () virtual
Implements OutputGenerator.
Definition at line 1889 of file latexgen.cpp.
References endl(), insideTabbing, and OutputGenerator::t.
startMemberSections()
void LatexGenerator::startMemberSections () inline virtual
Implements OutputGenerator.
Definition at line 168 of file latexgen.h.
startMemberSubtitle()
void LatexGenerator::startMemberSubtitle () inline virtual
Implements OutputGenerator.
Definition at line 174 of file latexgen.h.
startMemberTemplateParams()
void LatexGenerator::startMemberTemplateParams () virtual
Implements OutputGenerator.
Definition at line 1754 of file latexgen.cpp.
References OutputGenerator::t, and templateMemberItem.
startPageRef()
void LatexGenerator::startPageRef () virtual
Implements BaseOutputDocInterface.
Definition at line 1413 of file latexgen.cpp.
References OutputGenerator::t.
startParagraph()
void LatexGenerator::startParagraph (const char * classDef) virtual
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 1259 of file latexgen.cpp.
References endl(), and OutputGenerator::t.
startParameterList()
void LatexGenerator::startParameterList (bool openBracket) virtual
Implements OutputGenerator.
Definition at line 2057 of file latexgen.cpp.
References OutputGenerator::t.
startParameterName()
void LatexGenerator::startParameterName (bool) virtual
Implements OutputGenerator.
Definition at line 2079 of file latexgen.cpp.
References OutputGenerator::t.
startParameterType()
void LatexGenerator::startParameterType (bool first, const char * key) virtual
Implements OutputGenerator.
Definition at line 2068 of file latexgen.cpp.
References OutputGenerator::t.
startParamList()
void LatexGenerator::startParamList (ParamListTypes , const char * title) virtual
Implements BaseOutputDocInterface.
Definition at line 2045 of file latexgen.cpp.
References docify(), and OutputGenerator::t.
startProjectNumber()
void LatexGenerator::startProjectNumber () virtual
Implements OutputGenerator.
Definition at line 807 of file latexgen.cpp.
References OutputGenerator::t.
startQuickIndices()
void LatexGenerator::startQuickIndices () inline virtual
Implements OutputGenerator.
Definition at line 252 of file latexgen.h.
startSection()
void LatexGenerator::startSection (const char * lab, const char * , SectionInfo::SectionType type) virtual
Implements BaseOutputDocInterface.
Definition at line 1664 of file latexgen.cpp.
References Config_getBool, SectionInfo::Page, SectionInfo::Paragraph, SectionInfo::Section, stripPath(), SectionInfo::Subsection, SectionInfo::Subsubsection, and OutputGenerator::t.
startSimpleSect()
void LatexGenerator::startSimpleSect (SectionTypes , const char * file, const char * anchor, const char * title) virtual
Implements BaseOutputDocInterface.
Definition at line 2025 of file latexgen.cpp.
References docify(), OutputGenerator::t, and writeObjectLink().
startSmall()
void LatexGenerator::startSmall () inline virtual
Implements BaseOutputDocInterface.
Definition at line 226 of file latexgen.h.
References OutputGenerator::t.
startSubsection()
void LatexGenerator::startSubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 220 of file latexgen.h.
References OutputGenerator::t.
startSubsubsection()
void LatexGenerator::startSubsubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 222 of file latexgen.h.
References OutputGenerator::t.
startTextBlock()
void LatexGenerator::startTextBlock (bool) inline virtual
Implements OutputGenerator.
Definition at line 285 of file latexgen.h.
startTextLink()
void LatexGenerator::startTextLink (const char * f, const char * anchor) virtual
Implements BaseOutputDocInterface.
Definition at line 1371 of file latexgen.cpp.
References Config_getBool, disableLinks, stripPath(), and OutputGenerator::t.
startTitle()
void LatexGenerator::startTitle () virtual
Implements BaseOutputDocInterface.
Definition at line 1458 of file latexgen.cpp.
References Config_getBool, and OutputGenerator::t.
startTitleHead()
void LatexGenerator::startTitleHead (const char * fileName) virtual
Implements OutputGenerator.
Definition at line 1427 of file latexgen.cpp.
References Config_getBool, stripPath(), and OutputGenerator::t.
startTypewriter()
void LatexGenerator::startTypewriter () inline virtual
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 161 of file latexgen.h.
References OutputGenerator::t.
writeAnchor()
void LatexGenerator::writeAnchor (const char * fileName, const char * name) virtual
Implements BaseOutputDocInterface.
Definition at line 1617 of file latexgen.cpp.
References Config_getBool, endl(), stripPath(), and OutputGenerator::t.
writeChar()
void LatexGenerator::writeChar (char c) virtual
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 1712 of file latexgen.cpp.
References docify().
writeCodeAnchor()
void LatexGenerator::writeCodeAnchor (const char * name) inline virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 113 of file latexgen.h.
References m_codeGen, and LatexCodeGenerator::writeCodeAnchor().
writeCodeLink()
void LatexGenerator::writeCodeLink (const char * ref, const char * file, const char * anchor, const char * name, const char * tooltip) inline virtual
Writes a link to an object in a code fragment.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 95 of file latexgen.h.
References m_codeGen, and LatexCodeGenerator::writeCodeLink().
writeDoc()
void LatexGenerator::writeDoc (DocNode * n, Definition * ctx, MemberDef *) virtual
Implements OutputGenerator.
Definition at line 2103 of file latexgen.cpp.
References DocNode::accept(), Definition::getDefFileExtension(), insideTabbing, and OutputGenerator::t.
writeEndAnnoItem()
void LatexGenerator::writeEndAnnoItem (const char * name) virtual
Implements OutputGenerator.
Definition at line 1337 of file latexgen.cpp.
References endl(), stripPath(), and OutputGenerator::t.
writeFooter()
void LatexGenerator::writeFooter (const char *) inline virtual
Implements OutputGenerator.
Definition at line 122 of file latexgen.h.
writeFooterFile()
void LatexGenerator::writeFooterFile (QFile & f) static
Definition at line 768 of file latexgen.cpp.
References endl(), OutputGenerator::t, versionString, and writeDefaultFooter().
Referenced by readConfiguration().
writeGraphicalHierarchy()
void LatexGenerator::writeGraphicalHierarchy (const DotGfxHierarchyTable &) inline virtual
Implements OutputGenerator.
Definition at line 283 of file latexgen.h.
writeHeaderFile()
void LatexGenerator::writeHeaderFile (QFile & f) static
Definition at line 757 of file latexgen.cpp.
References endl(), OutputGenerator::t, versionString, writeDefaultHeaderPart1(), writeDefaultHeaderPart2(), and writeDefaultHeaderPart3().
Referenced by readConfiguration().
writeInheritedSectionTitle()
void LatexGenerator::writeInheritedSectionTitle (const char * , const char * , const char * , const char * , const char * , const char *) inline virtual
Implements OutputGenerator.
Definition at line 232 of file latexgen.h.
writeLabel()
void LatexGenerator::writeLabel (const char * l, bool isLast) virtual
Implements OutputGenerator.
Definition at line 2254 of file latexgen.cpp.
References OutputGenerator::t.
writeLatexSpacing()
void LatexGenerator::writeLatexSpacing () inline virtual
Implements OutputGenerator.
Definition at line 216 of file latexgen.h.
References OutputGenerator::t.
writeLineNumber()
void LatexGenerator::writeLineNumber (const char * ref, const char * file, const char * anchor, int lineNumber) inline virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
Implements CodeOutputInterface.
Definition at line 99 of file latexgen.h.
References m_codeGen, and LatexCodeGenerator::writeLineNumber().
writeLogo()
void LatexGenerator::writeLogo () inline virtual
Implements OutputGenerator.
Definition at line 256 of file latexgen.h.
writeNavigationPath()
void LatexGenerator::writeNavigationPath (const char *) inline virtual
Implements OutputGenerator.
Definition at line 255 of file latexgen.h.
writeNonBreakableSpace()
void LatexGenerator::writeNonBreakableSpace (int) virtual
Implements BaseOutputDocInterface.
Definition at line 1817 of file latexgen.cpp.
References insideTabbing, and OutputGenerator::t.
writeObjectLink()
void LatexGenerator::writeObjectLink (const char * ref, const char * file, const char * anchor, const char * name) virtual
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 1391 of file latexgen.cpp.
References Config_getBool, disableLinks, docify(), stripPath(), and OutputGenerator::t.
Referenced by startSimpleSect().
writePageLink()
void LatexGenerator::writePageLink (const char * name, bool) virtual
Implements OutputGenerator.
Definition at line 1234 of file latexgen.cpp.
References OutputGenerator::t.
writeQuickLinks()
void LatexGenerator::writeQuickLinks (bool , HighlightedItem , const char *) inline virtual
Implements OutputGenerator.
Definition at line 257 of file latexgen.h.
writeRuler()
void LatexGenerator::writeRuler () inline virtual
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 198 of file latexgen.h.
References endl(), and OutputGenerator::t.
writeSearchInfo()
void LatexGenerator::writeSearchInfo () inline virtual
Implements OutputGenerator.
Definition at line 121 of file latexgen.h.
writeSplitBar()
void LatexGenerator::writeSplitBar (const char *) inline virtual
Implements OutputGenerator.
Definition at line 254 of file latexgen.h.
writeStartAnnoItem()
void LatexGenerator::writeStartAnnoItem (const char * type, const char * file, const char * path, const char * name) virtual
Implements OutputGenerator.
Definition at line 1328 of file latexgen.cpp.
References docify(), and OutputGenerator::t.
writeString()
void LatexGenerator::writeString (const char * text) virtual
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 1269 of file latexgen.cpp.
References OutputGenerator::t.
writeStyleInfo()
void LatexGenerator::writeStyleInfo (int part) virtual
Implements OutputGenerator.
Definition at line 1244 of file latexgen.cpp.
References OutputGenerator::endPlainFile(), OutputGenerator::startPlainFile(), OutputGenerator::t, and writeDefaultStyleSheet().
writeStyleSheetFile()
void LatexGenerator::writeStyleSheetFile (QFile & f) static
Definition at line 775 of file latexgen.cpp.
References endl(), OutputGenerator::t, versionString, and writeDefaultStyleSheet().
Referenced by readConfiguration().
writeSummaryLink()
void LatexGenerator::writeSummaryLink (const char * , const char * , const char * , bool) inline virtual
Implements OutputGenerator.
Definition at line 258 of file latexgen.h.
writeSynopsis()
void LatexGenerator::writeSynopsis () inline virtual
Implements OutputGenerator.
Definition at line 247 of file latexgen.h.
writeTooltip()
void LatexGenerator::writeTooltip (const char * id, const DocLinkInfo & docInfo, const char * decl, const char * desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) inline virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 101 of file latexgen.h.
References m_codeGen, and LatexCodeGenerator::writeTooltip().
Member Data Documentation
disableLinks
bool LatexGenerator::disableLinks private
Definition at line 331 of file latexgen.h.
Referenced by endGroupHeader(), endMemberDoc(), endMemberHeader(), LatexGenerator(), startGroupHeader(), startMemberHeader(), startTextLink(), and writeObjectLink().
firstDescItem
bool LatexGenerator::firstDescItem private
Definition at line 330 of file latexgen.h.
Referenced by endDescItem(), endDescription(), LatexGenerator(), and startDescItem().
insideTabbing
bool LatexGenerator::insideTabbing private
Definition at line 329 of file latexgen.h.
Referenced by addIndexItem(), docify(), endAnonTypeScope(), endInlineMemberName(), endInlineMemberType(), endMemberDescription(), endMemberItem(), endMemberList(), endTitleHead(), LatexGenerator(), lineBreak(), startAnonTypeScope(), startInlineMemberName(), startInlineMemberType(), startMemberDescription(), startMemberDoc(), startMemberItem(), startMemberList(), writeDoc(), and writeNonBreakableSpace().
m_codeGen
LatexCodeGenerator LatexGenerator::m_codeGen private
Definition at line 336 of file latexgen.h.
Referenced by codify(), endCodeLine(), endFile(), endFontClass(), startCodeLine(), startFile(), startFontClass(), writeCodeAnchor(), writeCodeLink(), writeLineNumber(), and writeTooltip().
m_indent
int LatexGenerator::m_indent private
Definition at line 333 of file latexgen.h.
Referenced by endAnonTypeScope(), LatexGenerator(), startAnonTypeScope(), and startMemberDescription().
m_prettyCode
bool LatexGenerator::m_prettyCode private
Definition at line 335 of file latexgen.h.
Referenced by endIndexSection(), and LatexGenerator().
relPath
QCString LatexGenerator::relPath private
Definition at line 332 of file latexgen.h.
Referenced by endCallGraph(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), and startFile().
templateMemberItem
bool LatexGenerator::templateMemberItem private
Definition at line 334 of file latexgen.h.
Referenced by endMemberItem(), endMemberTemplateParams(), LatexGenerator(), startMemberItem(), and startMemberTemplateParams().
The documentation for this class was generated from the following files:
src/latexgen.h
src/latexgen.cpp