Doxygen: MemberListContext Class Reference
MemberListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static MemberListContext * alloc ()
static MemberListContext * alloc (const MemberList *ml)
static MemberListContext * alloc (MemberSDict *ml, bool doSort)
Private Member Functions
MemberListContext ()
MemberListContext (const MemberList *ml)
MemberListContext (MemberSDict *ml, bool doSort)
~MemberListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 951 of file context.h.
Constructor & Destructor Documentation
MemberListContext() [1/3]
MemberListContext::MemberListContext () private
Definition at line 8502 of file context.cpp.
References p, and Private.
Referenced by alloc().
MemberListContext() [2/3]
MemberListContext::MemberListContext (const MemberList * ml) private
Definition at line 8507 of file context.cpp.
References MemberListContext::Private::addMember(), MemberDef::isBriefSectionVisible(), MemberDef::isDetailedSectionLinkable(), MemberList::listType(), MemberListType_detailedLists, p, and Private.
MemberListContext() [3/3]
MemberListContext::MemberListContext (MemberSDict * ml, bool doSort) private
Definition at line 8527 of file context.cpp.
References MemberListContext::Private::addMember(), SDict< MemberDef >::Iterator, p, Private, and SDict< T >::sort().
~MemberListContext()
MemberListContext::~MemberListContext () private
Definition at line 8545 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int MemberListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 965 of file context.h.
References RefCountedContext::addRef().
alloc() [1/3]
static MemberListContext* MemberListContext::alloc () inline static
Definition at line 954 of file context.h.
References MemberListContext().
Referenced by MemberContext::Private::enumValues(), ClassContext::Private::members(), MemberGroupInfoContext::Private::members(), MemberListInfoContext::Private::members(), InheritedMemberInfoContext::Private::members(), MemberContext::Private::sourceRefBys(), and MemberContext::Private::sourceRefs().
alloc() [2/3]
static MemberListContext* MemberListContext::alloc (const MemberList * ml) inline static
Definition at line 956 of file context.h.
References MemberListContext().
alloc() [3/3]
static MemberListContext* MemberListContext::alloc (MemberSDict * ml, bool doSort) inline static
Definition at line 958 of file context.h.
References MemberListContext().
at()
TemplateVariant MemberListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 8556 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int MemberListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 8551 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * MemberListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 8561 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int MemberListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 966 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* MemberListContext::p private
Definition at line 973 of file context.h.
Referenced by at(), count(), createIterator(), MemberListContext(), and ~MemberListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp