Doxygen: src/context.h File Reference
context.h File Reference
#include "types.h"
#include "template.h"
#include <qlist.h>
#include <stdio.h>
Classes
class RefCountedContext
Helper class to support reference counting.
class ConfigContext
class DoxygenContext
class TranslateContext
class UsedFilesContext
class IncludeInfoContext
class IncludeInfoListContext
class ClassContext
class NamespaceContext
class FileContext
class DirContext
class PageContext
class MemberContext
class ModuleContext
class ClassListContext
class ClassIndexContext
class InheritanceGraphContext
class ClassInheritanceNodeContext
class ClassInheritanceContext
class ClassHierarchyContext
class NestingNodeContext
class NestingContext
class ClassTreeContext
class NamespaceListContext
class NamespaceTreeContext
class DirListContext
class FileListContext
class FileTreeContext
class PageListContext
class PageTreeContext
class ModuleNodeContext
class ModuleListContext
class ModuleTreeContext
class ExampleListContext
class ExampleTreeContext
class GlobalsIndexContext
class ClassMembersIndexContext
class NamespaceMembersIndexContext
class NavPathElemContext
class InheritanceNodeContext
class InheritanceListContext
class MemberListContext
class MemberGroupInfoContext
class MemberGroupListContext
class MemberListInfoContext
class MemberInfoContext
class InheritedMemberInfoContext
class InheritedMemberInfoListContext
class AllMembersListContext
class ArgumentContext
class ArgumentListContext
class SymbolContext
class SymbolListContext
class SymbolGroupContext
class SymbolGroupListContext
class SymbolIndexContext
class SymbolIndicesContext
class SearchIndexContext
class SearchIndicesContext
Macros
#define DEBUG_REF 0
Functions
void generateOutputViaTemplate ()
void generateTemplateFiles (const char *templateDir)
Macro Definition Documentation
DEBUG_REF
#define DEBUG_REF 0
Definition at line 62 of file context.h.
Function Documentation
generateOutputViaTemplate()
void generateOutputViaTemplate ()
Definition at line 10096 of file context.cpp.
References ConfigContext::alloc(), DoxygenContext::alloc(), TranslateContext::alloc(), PageContext::alloc(), ClassListContext::alloc(), ClassIndexContext::alloc(), ClassHierarchyContext::alloc(), ClassTreeContext::alloc(), NamespaceListContext::alloc(), NamespaceTreeContext::alloc(), DirListContext::alloc(), FileListContext::alloc(), FileTreeContext::alloc(), PageListContext::alloc(), PageTreeContext::alloc(), ModuleListContext::alloc(), ModuleTreeContext::alloc(), ExampleListContext::alloc(), ExampleTreeContext::alloc(), GlobalsIndexContext::alloc(), ClassMembersIndexContext::alloc(), NamespaceMembersIndexContext::alloc(), SearchIndicesContext::alloc(), Config_getString, ContextOutputFormat_Html, ContextOutputFormat_Latex, TemplateEngine::createContext(), createSubDirs(), DefinitionIntf::definitionType(), TemplateEngine::destroyContext(), ContextGlobals::dynSectionId, g_globals, SharedPtr< T >::get(), TemplateEngine::loadByName(), Doxygen::mainPage, msg(), ContextGlobals::outputDir, ContextGlobals::outputFormat, Doxygen::pageSDict, Template::render(), TemplateContext::set(), Definition::setCookie(), TemplateContext::setEscapeIntf(), PageDef::setFileName(), TemplateContext::setOutputDirectory(), TemplateContext::setSpacelessIntf(), TemplateEngine::setTemplateDir(), Doxygen::symbolMap, theTranslator, Translator::trMainPage(), DefinitionIntf::TypeSymbolList, and TemplateEngine::unload().
Referenced by generateOutput().
generateTemplateFiles()
void generateTemplateFiles (const char * templateDir)
Definition at line 10265 of file context.cpp.
References err(), ResourceMgr::instance(), and ResourceMgr::writeCategory().
Referenced by readConfiguration().