Doxygen: src/dirdef.cpp File Reference
dirdef.cpp File Reference
#include "md5.h"
#include "dirdef.h"
#include "filename.h"
#include "doxygen.h"
#include "util.h"
#include "outputlist.h"
#include "language.h"
#include "message.h"
#include "dot.h"
#include "layout.h"
#include "ftextstream.h"
#include "config.h"
#include "docparser.h"
Functions
static QCString encodeDirName (const QCString &anchor)
static void writePartialDirPath (OutputList &ol, const DirDef *root, const DirDef *target)
static void writePartialFilePath (OutputList &ol, const DirDef *root, const FileDef *fd)
static void computeCommonDirPrefix ()
In order to create stable, but unique directory names, we compute the common part of the path shared by all directories.
void buildDirectories ()
void computeDirDependencies ()
void generateDirDocs (OutputList &ol)
Variables
static int g_dirCount =0
Function Documentation
buildDirectories()
void buildDirectories ()
Definition at line 921 of file dirdef.cpp.
References DirDef::addFile(), DirDef::addSubDir(), computeCommonDirPrefix(), Doxygen::directories, SDict< T >::find(), FileDef::getPath(), Definition::getReference(), Doxygen::inputNameList, FileDef::isDocumentationFile(), SDict< DirDef >::Iterator, DirDef::mergeDirectoryInTree(), Definition::name(), DirDef::sort(), and SDict< T >::sort().
Referenced by parseInput().
computeCommonDirPrefix()
static void computeCommonDirPrefix () static
In order to create stable, but unique directory names, we compute the common part of the path shared by all directories.
Definition at line 843 of file dirdef.cpp.
References Doxygen::directories, SDict< DirDef >::Iterator, Definition::name(), and DirDef::setDiskName().
Referenced by buildDirectories().
computeDirDependencies()
void computeDirDependencies ()
Definition at line 977 of file dirdef.cpp.
References DirDef::computeDependencies(), Doxygen::directories, SDict< DirDef >::Iterator, and DirDef::setLevel().
Referenced by parseInput().
encodeDirName()
static QCString encodeDirName (const QCString & anchor) static
Definition at line 87 of file dirdef.cpp.
Referenced by DirDef::getOutputFileBase().
generateDirDocs()
void generateDirDocs (OutputList & ol)
Definition at line 995 of file dirdef.cpp.
References Config_getBool, Doxygen::directories, Doxygen::dirRelations, SDict< DirDef >::Iterator, DirDef::writeDocumentation(), and DirRelation::writeDocumentation().
Referenced by generateOutput().
writePartialDirPath()
static void writePartialDirPath (OutputList & ol, const DirDef * root, const DirDef * target) static
Definition at line 752 of file dirdef.cpp.
References DirDef::getOutputFileBase(), Definition::getReference(), DirDef::parent(), DirDef::shortName(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writePartialFilePath().
writePartialFilePath()
static void writePartialFilePath (OutputList & ol, const DirDef * root, const FileDef * fd) static
Definition at line 762 of file dirdef.cpp.
References OutputList::docify(), OutputList::endBold(), FileDef::getDirDef(), FileDef::getOutputFileBase(), Definition::getReference(), FileDef::isLinkable(), FileDef::name(), OutputList::startBold(), OutputList::writeObjectLink(), writePartialDirPath(), and OutputList::writeString().
Referenced by DirRelation::writeDocumentation().
Variable Documentation
g_dirCount
int g_dirCount =0 static
Definition at line 19 of file dirdef.cpp.
Referenced by DirDef::DirDef().