Doxygen: SearchIndexContext::Private Class Reference
SearchIndexContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const SearchIndexInfo *info)
TemplateVariant get (const char *n) const
TemplateVariant name () const
TemplateVariant text () const
TemplateVariant symbolIndices () const
Private Attributes
const SearchIndexInfo * m_info
Cachable m_cache
Static Private Attributes
static PropertyMapper< SearchIndexContext::Private > s_inst
Detailed Description
Definition at line 9852 of file context.cpp.
Constructor & Destructor Documentation
Private()
SearchIndexContext::Private::Private (const SearchIndexInfo * info) inline
Definition at line 9855 of file context.cpp.
References PropertyMapper< T >::addProperty(), Config::init(), name(), s_inst, symbolIndices(), and text().
Member Function Documentation
get()
TemplateVariant SearchIndexContext::Private::get (const char * n) const inline
Definition at line 9866 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by SearchIndexContext::get().
name()
TemplateVariant SearchIndexContext::Private::name () const inline
Definition at line 9870 of file context.cpp.
References m_info, and SearchIndexInfo::name.
Referenced by Private().
symbolIndices()
TemplateVariant SearchIndexContext::Private::symbolIndices () const inline
Definition at line 9878 of file context.cpp.
References SymbolIndicesContext::alloc(), SharedPtr< T >::get(), m_cache, m_info, SharedPtr< T >::reset(), and SearchIndexContext::Private::Cachable::symbolIndices.
Referenced by Private().
text()
TemplateVariant SearchIndexContext::Private::text () const inline
Definition at line 9874 of file context.cpp.
References m_info, and SearchIndexInfo::text.
Referenced by Private().
Member Data Documentation
m_cache
Cachable SearchIndexContext::Private::m_cache mutable private
Definition at line 9892 of file context.cpp.
Referenced by symbolIndices().
m_info
const SearchIndexInfo* SearchIndexContext::Private::m_info private
Definition at line 9887 of file context.cpp.
Referenced by name(), symbolIndices(), and text().
s_inst
PropertyMapper< SearchIndexContext::Private > SearchIndexContext::Private::s_inst static private
Definition at line 9893 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp