Doxygen: SDict< T > Class Template Reference
SDict< T > Class Template Reference
Ordered dictionary of elements of type T.
#include <sortdict.h>
Classes
class Iterator
class IteratorDict
Public Member Functions
SDict (int size=17, bool caseSensitive=TRUE)
virtual ~SDict ()
void append (const char *key, const T *d)
void prepend (const char *key, const T *d)
bool remove (const char *key)
T * take (const char *key)
void sort ()
void inSort (const char *key, const T *d)
void insertAt (int i, const char *key, const T *d)
void setAutoDelete (bool val)
T * find (const char *key)
T * find (const QCString &key)
T * find (const QString &key)
int findAt (const QCString &key)
T * operator[] (const char *key) const
T * at (uint i)
virtual int compareValues (const T *item1, const T *item2) const
void clear ()
int count () const
Private Attributes
SList< T > * m_list
QDict< T > * m_dict
int m_sizeIndex
Friends
class Iterator
class IteratorDict
Detailed Description
template<class T>
class SDict< T >
Ordered dictionary of elements of type T.
Internally uses a QList<T> and a QDict<T>.
Definition at line 73 of file sortdict.h.
Constructor & Destructor Documentation
SDict()
template<class T> SDict< T >::SDict (int size = 17, bool caseSensitive = TRUE) inline
Create an ordered dictionary.
Parameters
size The size of the dictionary. Should be a prime number for best distribution of elements.
caseSensitive indicated whether the keys should be sorted in a case sensitive way.
Definition at line 111 of file sortdict.h.
~SDict()
template<class T> virtual SDict< T >::~SDict () inline virtual
Destroys the dictionary
Definition at line 123 of file sortdict.h.
Member Function Documentation
append()
template<class T> void SDict< T >::append (const char * key, const T * d) inline
Appends an element to the dictionary. The element is owned by the dictionary.
Parameters
key The unique key to use to quicky find the item later on.
d The compound to add.
See also
find()
Definition at line 135 of file sortdict.h.
Referenced by GroupDef::addClass(), addClassToContext(), addDirsAsGroups(), TagFileParser::addDocAnchors(), addEnumValuesToEnums(), GroupDef::addExample(), DotManager::addFigure(), UsedDir::addFileDep(), DocSets::addIndexItem(), PageDef::addInnerCompound(), NamespaceDef::addInnerCompound(), addInterfaceOrServiceToServiceOrSingleton(), HtmlHelpIndex::addItem(), DotManager::addMap(), ClassDef::addMembersToTemplateInstance(), addMethodToClass(), GroupDef::addNamespace(), GroupDef::addPage(), addRelatedPage(), Definition::addSectionsToDefinition(), Definition::addSourceReferencedBy(), Definition::addSourceReferences(), DotManager::addSVGConversion(), DotManager::addSVGObject(), ClassDef::addTypeConstraint(), NamespaceDef::addUsingDeclaration(), FileDef::addUsingDeclaration(), NamespaceDef::addUsingDirective(), FileDef::addUsingDirective(), addVariableToClass(), addVariableToFile(), SearchIndexList::append(), buildFunctionList(), buildGroupListFiltered(), DirDef::createNewDir(), createTagLessInstance(), MemberDef::deepCopy(), Definition::Definition(), DocAnchor::DocAnchor(), DocHtmlCaption::DocHtmlCaption(), findClassRelation(), findDefineDocumentation(), findEnums(), findMainPage(), findMember(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsingDeclarations(), GenericsSDict::insert(), NamespaceDef::insertClass(), FileDef::insertClass(), RefList::insertIntoList(), NamespaceDef::insertMember(), GroupDef::insertMember(), NamespaceDef::insertNamespace(), FileDef::insertNamespace(), ClassDef::internalInsertMember(), ClassDef::mergeCategory(), ClassDef::mergeMembers(), DocSection::parse(), DocSecRefItem::parse(), processBlocks(), SearchIndexExternal::setCurrentDoc(), MemberDef::setSectionList(), unmarshalMemberLists(), unmarshalMemberSDict(), unmarshalSectionDict(), writeDotDirDepGraph(), writeOneLineHeaderOrRuler(), and VhdlDocGen::writePlainVHDLDeclarations().
at()
template<class T> T* SDict< T >::at (uint i) inline
Returns the item at position i in the sorted dictionary
Definition at line 258 of file sortdict.h.
Referenced by Definition::_writeSourceRefList(), GroupDef::addClass(), and writeExample().
clear()
template<class T> void SDict< T >::clear () inline
Clears the dictionary. Will delete items if setAutoDelete() was set to TRUE.
See also
setAutoDelete
Definition at line 276 of file sortdict.h.
Referenced by clearAll(), and VhdlDocGen::writePlainVHDLDeclarations().
compareValues()
template<class T> virtual int SDict< T >::compareValues (const T * item1, const T * item2) const inline virtual
Function that is used to compare two items when sorting. Overload this to properly sort items.
See also
inSort()
Reimplemented in NamespaceSDict, DirSDict, GroupSDict, SearchIndexList, MemberSDict, FilePairDict, MemberNameInfoSDict, PageSDict, ClassSDict, IndexFieldSDict, MemberNameSDict, SortedRefItems, and ExampleSDict.
Definition at line 267 of file sortdict.h.
count()
template<class T> int SDict< T >::count () const inline
Returns the number of items stored in the dictionary
Definition at line 284 of file sortdict.h.
Referenced by Definition::_writeSourceRefList(), GroupDef::addClass(), DotGroupCollaboration::buildGraph(), computeClassRelations(), NamespaceDef::countMembers(), GroupDef::countMembers(), getResolvedClassRec(), MemberDef::hasExamples(), ClassDef::hasExamples(), PageDef::hasSubPages(), marshalExampleSDict(), marshalMemberLists(), marshalMemberSDict(), marshalSectionDict(), matchArgument(), quickLinkVisible(), DotManager::run(), GroupDef::writeDetailedDescription(), writeExample(), and writeGroupTreeNode().
find() [1/3]
template<class T> T* SDict< T >::find (const char * key) inline
Looks up a compound given its key.
Parameters
key The key to identify this element.
Returns
The requested compound or zero if it cannot be found.
See also
append()
Definition at line 232 of file sortdict.h.
Referenced by accessibleViaUsingNamespace(), GroupDef::addClass(), addClassToGroups(), addDirToGroups(), addEnumValuesToEnums(), MemberDef::addExample(), ClassDef::addExample(), addExampleToGroups(), DotManager::addFigure(), addGroupToGroups(), FileDef::addIncludedUsingDirectives(), DocSets::addIndexItem(), HtmlHelpIndex::addItem(), DotManager::addMap(), ClassDef::addMembersToTemplateInstance(), addMemberToGroups(), GroupDef::addNamespace(), addNamespaceToGroups(), addRelatedPage(), Definition::addSectionsToDefinition(), Definition::addSourceReferencedBy(), Definition::addSourceReferences(), DotManager::addSVGConversion(), DotManager::addSVGObject(), NamespaceDef::addUsingDeclaration(), FileDef::addUsingDeclaration(), NamespaceDef::addUsingDirective(), FileDef::addUsingDirective(), addVariableToClass(), addVariableToFile(), buildDirectories(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildScopeFromQualifiedName(), computePageRelations(), VhdlDocGen::computeVhdlComponentRelations(), DirDef::createNewDir(), DotNode::deleteNode(), DocAnchor::DocAnchor(), DocHtmlCaption::DocHtmlCaption(), DocRef::DocRef(), GenericsSDict::find(), SIntDict< SearchIndexList >::find(), SDict< Example >::findAt(), findClassRelation(), findDefineDocumentation(), findDocsForMemberOrCompound(), findEnumDocumentation(), UsedDir::findFilePair(), findGlobalMember(), NamespaceDef::findInnerCompound(), ClassDef::findInnerCompound(), findMainPage(), findMember(), findUsedClassesForClass(), findUsingDeclarations(), findUsingDeclImports(), findUsingDirectives(), generateDocbookForPage(), PerlModGenerator::generatePerlModForPage(), generateXMLForPage(), VhdlDocGen::getClass(), getClass(), getDefs(), NamespaceDef::getMemberByName(), ClassDef::getMemberByName(), getResolvedNamespace(), MemberDef::getSectionList(), getTemplateArgumentsFromName(), GenericsSDict::insert(), NamespaceDef::insertClass(), RefList::insertIntoList(), NamespaceDef::insertNamespace(), FileDef::insertNamespace(), ClassDef::internalInsertMember(), isVarWithConstructor(), mergeCategories(), ClassDef::mergeCategory(), ClassDef::mergeMembers(), SIntDict< SearchIndexList >::operator[](), DocSection::parse(), DocSecRefItem::parse(), DocRoot::parse(), processBlocks(), GroupDef::removeMember(), resolveRef(), resolveTypeDef(), resolveUserReferences(), SearchIndexExternal::setCurrentDoc(), transferFunctionReferences(), PageDef::writeDocumentation(), writeOneLineHeaderOrRuler(), GroupDef::writePageDocumentation(), and VhdlDocGen::writePlainVHDLDeclarations().
find() [2/3]
template<class T> T* SDict< T >::find (const QCString & key) inline
Definition at line 236 of file sortdict.h.
find() [3/3]
template<class T> T* SDict< T >::find (const QString & key) inline
Definition at line 240 of file sortdict.h.
findAt()
template<class T> int SDict< T >::findAt (const QCString & key) inline
Definition at line 244 of file sortdict.h.
Referenced by GroupDef::addClass().
insertAt()
template<class T> void SDict< T >::insertAt (int i, const char * key, const T * d) inline
Definition at line 209 of file sortdict.h.
Referenced by GroupDef::addClass().
inSort()
template<class T> void SDict< T >::inSort (const char * key, const T * d) inline
Inserts a compound into the dictionary in a sorted way.
Parameters
key The unique key to use to quicky find the item later on.
d The compound to add.
See also
find()
Definition at line 197 of file sortdict.h.
Referenced by GroupDef::addClass(), MemberDef::addExample(), ClassDef::addExample(), ClassDef::addInnerCompound(), GroupDef::addNamespace(), buildExampleList(), buildNamespaceList(), buildScopeFromQualifiedName(), findUsingDirectives(), NamespaceDef::insertClass(), FileDef::insertClass(), NamespaceDef::insertNamespace(), FileDef::insertNamespace(), and unmarshalExampleSDict().
operator[]()
template<class T> T* SDict< T >::operator[] (const char * key) const inline
Equavalent to find().
Definition at line 252 of file sortdict.h.
prepend()
template<class T> void SDict< T >::prepend (const char * key, const T * d) inline
Prepends an element to the dictionary. The element is owned by the dictionary.
Parameters
key The unique key to use to quicky find the item later on.
d The compound to add.
See also
find()
Definition at line 153 of file sortdict.h.
Referenced by FileDef::addIncludedUsingDirectives().
remove()
template<class T> bool SDict< T >::remove (const char * key) inline
Remove an item from the dictionary
Definition at line 166 of file sortdict.h.
Referenced by GroupDef::removeMember().
setAutoDelete()
template<class T> void SDict< T >::setAutoDelete (bool val) inline
Indicates whether or not the dictionary owns its elements
Definition at line 222 of file sortdict.h.
Referenced by ClassDef::addExample(), ClassDefImpl::ClassDefImpl(), DotManager::DotManager(), GenericsSDict::GenericsSDict(), GroupDef::GroupDef(), HtmlHelpIndex::HtmlHelpIndex(), initDoxygen(), ClassDef::internalInsertMember(), ClassDef::mergeMembers(), SearchIndexExternal::SearchIndexExternal(), UsedDir::UsedDir(), and VhdlDocGen::writePlainVHDLDeclarations().
sort()
template<class T> void SDict< T >::sort () inline
Sorts the members of the dictionary. First appending a number of members and then sorting them is faster (O(NlogN) than using inSort() for each member (O(N^2)).
Definition at line 188 of file sortdict.h.
Referenced by Definition::_writeSourceRefList(), buildCompleteMemberLists(), buildDirectories(), createJavascriptSearchIndex(), generateOutput(), RefList::generatePage(), MemberListContext::MemberListContext(), parseInput(), UsedDir::sort(), NamespaceDef::sortMemberLists(), ClassDef::sortMemberLists(), and HtmlHelpIndex::writeFields().
take()
template<class T> T* SDict< T >::take (const char * key) inline
Take an item out of the dictionary without deleting it
Definition at line 173 of file sortdict.h.
Friends And Related Function Documentation
Iterator
template<class T> friend class Iterator friend
Definition at line 289 of file sortdict.h.
IteratorDict
template<class T> friend class IteratorDict friend
Definition at line 353 of file sortdict.h.
Member Data Documentation
m_dict
template<class T> QDict<T>* SDict< T >::m_dict private
Definition at line 101 of file sortdict.h.
Referenced by SDict< T >::IteratorDict::IteratorDict(), and SDict< Example >::~SDict().
m_list
template<class T> SList<T>* SDict< T >::m_list private
Definition at line 100 of file sortdict.h.
Referenced by SDict< T >::Iterator::Iterator(), and SDict< Example >::~SDict().
m_sizeIndex
template<class T> int SDict< T >::m_sizeIndex private
Definition at line 102 of file sortdict.h.
Referenced by SDict< Example >::append(), SDict< Example >::insertAt(), SDict< Example >::inSort(), SDict< Example >::prepend(), and SDict< Example >::SDict().
The documentation for this class was generated from the following file:
src/sortdict.h