Doxygen: TemplateNodeCycle Class Reference
TemplateNodeCycle Class Reference
Class representing an 'cycle' tag in a template.
Public Member Functions
TemplateNodeCycle (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (FTextStream &ts, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeCycle >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Private Attributes
uint m_index
QList< ExprAst > m_args
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeCycle >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeCycle >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeCycle >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'cycle' tag in a template.
Definition at line 4064 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeCycle()
TemplateNodeCycle::TemplateNodeCycle (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 4067 of file template.cpp.
References m_args, m_index, ExpressionParser::parse(), split(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
Member Function Documentation
render()
void TemplateNodeCycle::render (FTextStream & ts, TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 4091 of file template.cpp.
References TemplateVariant::call(), TemplateEscapeIntf::escape(), TemplateContextImpl::escapeIntf(), TemplateVariant::Function, m_args, m_index, TemplateNodeCreator< TemplateNodeCycle >::m_line, TemplateNodeCreator< TemplateNodeCycle >::m_templateName, TemplateContextImpl::needsRecoding(), TemplateVariant::raw(), TemplateContextImpl::recode(), TemplateContextImpl::setLocation(), TemplateVariant::toString(), and TemplateVariant::type().
Member Data Documentation
m_args
QList<ExprAst> TemplateNodeCycle::m_args private
Definition at line 4132 of file template.cpp.
Referenced by render(), and TemplateNodeCycle().
m_index
uint TemplateNodeCycle::m_index private
Definition at line 4131 of file template.cpp.
Referenced by render(), and TemplateNodeCycle().
The documentation for this class was generated from the following file:
src/template.cpp