Doxygen: DirContext Class Reference
DirContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static DirContext * alloc (DirDef *dd)
Private Member Functions
DirContext (DirDef *)
~DirContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 309 of file context.h.
Constructor & Destructor Documentation
DirContext()
DirContext::DirContext (DirDef * fd) private
Definition at line 3564 of file context.cpp.
References p, and Private.
Referenced by alloc(), and DirContext::Private::dirs().
~DirContext()
DirContext::~DirContext () private
Definition at line 3569 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int DirContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 316 of file context.h.
References RefCountedContext::addRef().
alloc()
static DirContext* DirContext::alloc (DirDef * dd) inline static
Definition at line 312 of file context.h.
References DirContext().
Referenced by ModuleContext::Private::dirs(), NestingNodeContext::Private::getDir(), and DirListContext::Private::Private().
get()
TemplateVariant DirContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 3574 of file context.cpp.
References DirContext::Private::get(), and p.
release()
virtual int DirContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 317 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* DirContext::p private
Definition at line 322 of file context.h.
Referenced by DirContext(), get(), and ~DirContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp