Doxygen: src/message.h File Reference
message.h File Reference
#include <stdio.h>
#include <stdarg.h>
Functions
void msg (const char *fmt,...)
void warn (const char *file, int line, const char *fmt,...)
void va_warn (const char *file, int line, const char *fmt, va_list args)
void warn_simple (const char *file, int line, const char *text)
void warn_undoc (const char *file, int line, const char *fmt,...)
void warn_doc_error (const char *file, int line, const char *fmt,...)
void warn_uncond (const char *fmt,...)
void err (const char *fmt,...)
void err_full (const char *file, int line, const char *fmt,...)
void initWarningFormat ()
void printlex (int dbg, bool enter, const char *lexName, const char *fileName)
Function Documentation
err()
void err (const char * fmt, ...)
Definition at line 226 of file message.cpp.
References error_str, and warnFile.
Referenced by MemberDef::_writeReimplements(), FileDef::acquireFileVersion(), Definition::addInnerCompound(), PropertyMapper< NestingNodeContext::Private >::addProperty(), adjustConfiguration(), MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), checkDotResult(), checkPageRelations(), classInheritedProtectionLevel(), ClassContext::Private::collaborationDiagram(), convertMapFile(), copyExtraFiles(), copyFile(), copyLatexStyleSheet(), copyLogo(), ResourceMgr::copyResourceAs(), copyStyleSheet(), MemberList::countDecMembers(), PerlModGenerator::createOutputDir(), createOutputDirectory(), PerlModGenerator::createOutputFile(), HtmlHelp::createProjectFile(), createSVG(), FlowChart::createSVG(), RTFGenerator::decrementIndentLevel(), DirContext::Private::dirGraph(), elemIsVisible(), LayoutErrorHandler::error(), Htags::execute(), TagFileErrorHandler::fatalError(), LayoutErrorHandler::fatalError(), fileToString(), Qhp::finalize(), findAndCopyImage(), FlowChart::findLabel(), FormulaList::generateBitmaps(), generateConfigFile(), generateDEF(), generateDocbook(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForNamespace(), generateDocbookForPage(), generateGraphLegend(), generateLink(), generateOutput(), CiteDict::generatePage(), generatePlantUMLOutput(), generateSqlite3(), generateTemplateFiles(), generateXML(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), generateXMLForPage(), ModuleContext::Private::groupGraph(), TranslateContext::Private::handleCollaborationDiagramFor(), MemberContext::Private::handleDetailsVisibleFor(), TranslateContext::Private::handleDirDependencyGraphFor(), TranslateContext::Private::handleGeneratedAt(), TranslateContext::Private::handleImplementedBy(), TranslateContext::Private::handleIncludeDependencyGraph(), TranslateContext::Private::handleInheritanceDiagramFor(), TranslateContext::Private::handleInheritedByList(), TranslateContext::Private::handleInheritsList(), MemberContext::Private::handleNameWithContextFor(), TranslateContext::Private::handleReimplementedBy(), TranslateContext::Private::handleSourceRefBys(), TranslateContext::Private::handleSourceRefs(), TranslateContext::Private::handleWriteList(), FileContext::Private::includedByGraph(), FileContext::Private::includeGraph(), RTFGenerator::incrementIndentLevel(), ClassContext::Private::inheritanceDiagram(), RTFGenerator::init(), ManGenerator::init(), LatexGenerator::init(), HtmlGenerator::init(), DocSets::initialize(), EclipseHelp::initialize(), HtmlHelp::initialize(), NamespaceDef::insertMember(), GroupDef::insertMember(), FileDef::insertMember(), ClassDef::internalInsertMember(), ClassDef::isBaseClass(), VhdlDocGen::isSubClass(), ClassDef::isSubClass(), TemplateEngine::Private::loadByName(), loadExtensions(), Htags::loadFilemap(), loadStylesheet(), TemplateNodeCreator< TemplateNodeBlock >::mkpath(), DocInclude::parse(), parseCode(), parseDoc(), parseInput(), preProcessFile(), RTFGenerator::preProcessFileInplace(), readBoundingBox(), readConfiguration(), readInputFile(), readTagFile(), GroupDef::removeMember(), DotRunner::run(), DotFilePatcher::run(), StyleData::setStyle(), LayoutParser::startElement(), LayoutParser::startNavEntry(), OutputGenerator::startPlainFile(), testRTFOutput(), transcodeCharacterBuffer(), transcodeCharacterStringToUTF8(), updateLanguageMapping(), DocbookDocVisitor::visit(), TextDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), LatexDocVisitor::visit(), HtmlDocVisitor::visit(), ManDocVisitor::visit(), PrintDocVisitor::visit(), PerlModDocVisitor::visit(), PerlModDocVisitor::visitPre(), SearchIndexExternal::write(), ResourceMgr::writeCategory(), writeCombineScript(), NamespaceSDict::writeDeclaration(), writeDefaultLayoutFile(), FileDef::writeDetailedDescription(), writeDiaGraphFromFile(), NamespaceDef::writeDocumentation(), GroupDef::writeDocumentation(), DirDef::writeDocumentation(), FileDef::writeDocumentation(), ClassDef::writeDocumentationContents(), writeDotGraphFromFile(), writeDotImageMapFromFile(), HtmlGenerator::writeExternalSearchPage(), ClassDiagram::writeFigure(), FlowChart::writeFlowChart(), DotGfxHierarchyTable::writeGraph(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), DotGroupCollaboration::writeGraph(), ClassDef::writeInheritanceGraph(), writeJavascriptSearchIndex(), writeLatexMakefile(), writeMakeBat(), writeMscGraphFromFile(), writePlantUMLSource(), HtmlGenerator::writeSearchPage(), Definition::writeSourceDef(), HtmlGenerator::writeStyleInfo(), and writeTagFile().
err_full()
void err_full (const char * file, int line, const char * fmt, ...)
Definition at line 234 of file message.cpp.
References do_warn(), and error_str.
Referenced by NamespaceDef::compoundTypeString().
initWarningFormat()
void initWarningFormat ()
Definition at line 38 of file message.cpp.
References Config_getBool, Config_getString, error_str, outputFormat, portable_fopen(), warnFile, and warning_str.
Referenced by checkConfiguration().
msg()
void msg (const char * fmt, ...)
Definition at line 107 of file message.cpp.
References Config_getBool, Debug::isFlagSet(), Doxygen::runningTime, and Debug::Time.
Referenced by MemberDef::_writeCallerGraph(), MemberDef::_writeCallGraph(), FileDef::acquireFileVersion(), adjustConfiguration(), Statistics::begin(), RTFGenerator::beginRTFDocument(), PerlModGenerator::createOutputDir(), devUsage(), TagFileParser::dump(), exitDoxygen(), FormulaList::generateBitmaps(), generateClassList(), generateConfigFile(), generateDEF(), generateDocbook(), generateDocbookForClass(), generateExampleDocs(), generateFileDocs(), generateFileSources(), generateNamespaceDocs(), generateOutput(), generateOutputViaTemplate(), generatePageDocs(), generatePlantUMLOutput(), generateXML(), generateXMLForClass(), loadExtensions(), loadStylesheet(), parseFile(), parseInput(), Statistics::print(), Debug::printFlags(), printNavTree(), readConfiguration(), readDir(), readFormulaRepository(), readTagFile(), TemplateNodeExtend::render(), DotManager::run(), setTranslator(), stopDoxygen(), LayoutNavEntry::url(), usage(), DirDef::writeDirectoryGraph(), ClassDef::writeDocumentationForInnerClasses(), GroupDef::writeGroupGraph(), and writeIndexHierarchyEntries().
printlex()
void printlex (int dbg, bool enter, const char * lexName, const char * fileName)
Definition at line 242 of file message.cpp.
References Debug::Lex, and Debug::print().
va_warn()
void va_warn (const char * file, int line, const char * fmt, va_list args)
Definition at line 191 of file message.cpp.
References Config_getBool, do_warn(), and warning_str.
Referenced by TemplateContextImpl::warn(), and TemplateParser::warn().
warn()
void warn (const char * file, int line, const char * fmt, ...)
Definition at line 183 of file message.cpp.
References Config_getBool, do_warn(), and warning_str.
Referenced by addGroupToGroups(), addIncludeFile(), addMemberDocs(), addMemberToGroups(), addRelatedPage(), buildExampleList(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildInterfaceAndServiceList(), findClassRelation(), findDefineDocumentation(), findDirDocumentation(), findEnumDocumentation(), findGlobalMember(), findMainPage(), findMember(), ExpressionParser::getNextToken(), MemberDef::getOutputFileBase(), loadExtensions(), loadStylesheet(), CondParser::parse(), ExpressionParser::parseNotExpression(), ExpressionParser::parsePrimaryExpression(), TemplateEngine::Private::printIncludeContext(), processBlocks(), resolveClassNestingRelations(), TemplateLexer::tokenize(), MemberDef::virtualness(), writeDirTreeNode(), writeExceptionListImpl(), writeGroupTreeNode(), and writeOneLineHeaderOrRuler().
warn_doc_error()
void warn_doc_error (const char * file, int line, const char * fmt, ...)
Definition at line 210 of file message.cpp.
References Config_getBool, do_warn(), and warning_str.
Referenced by checkArgumentName(), checkUndocumentedParams(), defaultHandleTitleAndSize(), defaultHandleToken(), detectNoDocumentedParams(), DocAnchor::DocAnchor(), DocCite::DocCite(), DocFormula::DocFormula(), DocHtmlCaption::DocHtmlCaption(), DocLink::DocLink(), DocRef::DocRef(), findAndCopyImage(), handleAHref(), handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocPara::handleImage(), handleImg(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), handleInternalRef(), DocPara::handleLink(), handleLinkedWord(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleStartCode(), handleStyleArgument(), handleStyleLeave(), handleUnclosedStyleCommands(), DocInclude::parse(), DocIndexEntry::parse(), DocCopy::parse(), DocTitle::parse(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocInternal::parse(), DocHtmlList::parse(), DocPara::parse(), DocParamList::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocText::parse(), DocRoot::parse(), DocHtmlList::parseXml(), DocParamList::parseXml(), DocHtmlRow::parseXml(), processCopyDoc(), readTextFileByName(), and MemberDef::warnIfUndocumentedParams().
warn_simple()
void warn_simple (const char * file, int line, const char * text)
Definition at line 196 of file message.cpp.
References Config_getBool, format_warn(), and warning_str.
Referenced by findMember().
warn_uncond()
void warn_uncond (const char * fmt, ...)
Definition at line 218 of file message.cpp.
References warnFile, and warning_str.
Referenced by MemberDef::_writeCallerGraph(), MemberDef::_writeCallGraph(), adjustConfiguration(), dateToString(), getResolvedNamespace(), minClassDistance(), parseInput(), readConfiguration(), readDir(), readFileOrDirectory(), readFormulaRepository(), setTranslator(), HtmlEntityMapper::validate(), LayoutErrorHandler::warning(), FileDef::writeIncludedByGraph(), and FileDef::writeIncludeGraph().
warn_undoc()
void warn_undoc (const char * file, int line, const char * fmt, ...)
Definition at line 202 of file message.cpp.
References Config_getBool, do_warn(), and warning_str.
Referenced by computeClassRelations(), findMember(), and MemberDef::warnIfUndocumented().