Doxygen: DirDef Class Reference
DirDef Class Reference
A model of a directory symbol.
#include <dirdef.h>
Public Member Functions
DirDef (const char *path)
virtual ~DirDef ()
DefType definitionType () const
QCString getOutputFileBase () const
QCString anchor () const
bool isLinkableInProject () const
bool isLinkable () const
QCString displayName (bool=TRUE) const
const QCString & shortName () const
void addSubDir (DirDef *subdir)
FileList * getFiles () const
void addFile (FileDef *fd)
const DirList & subDirs () const
bool isCluster () const
int level () const
DirDef * parent () const
int dirCount () const
const QDict< UsedDir > * usedDirs () const
bool isParentOf (DirDef *dir) const
bool depGraphIsTrivial () const
QCString shortTitle () const
bool hasDetailedDescription () const
void writeDocumentation (OutputList &ol)
void writeTagFile (FTextStream &t)
void setDiskName (const QCString &name)
void sort ()
Public Member Functions inherited from Definition
Definition (const char *defFileName, int defLine, int defColumn, const char *name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~Definition ()
const QCString & name () const
QCString localName () const
virtual QCString qualifiedName () const
QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
int docLine () const
QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
bool isHidden () const
bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
QCString externalReference (const QCString &relPath) const
int getStartBodyLine () const
int getEndBodyLine () const
FileDef * getBodyDef () const
SrcLangExt getLanguage () const
Returns the programming language this definition was written in.
GroupList * partOfGroups () const
bool isLinkableViaGroup () const
QList< ListItemInfo > * xrefListItems () const
virtual Definition * findInnerCompound (const char *name)
virtual Definition * getOuterScope () const
MemberSDict * getReferencesMembers () const
MemberSDict * getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
returns TRUE if this class has a brief description
QCString id () const
virtual void setName (const char *name)
void setId (const char *name)
virtual void setDocumentation (const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const char *b, const char *briefFile, int briefLine)
virtual void setInbodyDocumentation (const char *d, const char *docFile, int docLine)
void setReference (const char *r)
void addSectionsToDefinition (QList< SectionInfo > *anchorList)
void setBodySegment (int bls, int ble)
void setBodyDef (FileDef *fd)
void addSourceReferencedBy (MemberDef *d)
void addSourceReferences (MemberDef *d)
void setRefItems (const QList< ListItemInfo > *sli)
void mergeRefItems (Definition *d)
virtual void addInnerCompound (Definition *d)
virtual void setOuterScope (Definition *d)
virtual void setHidden (bool b)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const char *scopeName)
void writeInlineCode (OutputList &ol, const char *scopeName)
void writeSourceRefs (OutputList &ol, const char *scopeName)
void writeSourceReffedBy (OutputList &ol, const char *scopeName)
void makePartOfGroup (GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
virtual void writeQuickMemberLinks (OutputList &, MemberDef *) const
virtual void writeSummaryLinks (OutputList &)
QCString pathFragment () const
void writeDocAnchorsToTagFile (FTextStream &)
void setLocalName (const QCString name)
void addSectionsToIndex ()
void writeToc (OutputList &ol)
void setCookie (Cookie *cookie)
Cookie * cookie () const
Public Member Functions inherited from DefinitionIntf
DefinitionIntf ()
virtual ~DefinitionIntf ()
Static Public Member Functions
static DirDef * mergeDirectoryInTree (const QCString &path)
Public Attributes
bool visited
Private Member Functions
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeDirectoryGraph (OutputList &ol)
void writeSubDirList (OutputList &ol)
void writeFileList (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void setLevel ()
void addUsesDependency (DirDef *usedDir, FileDef *srcFd, FileDef *dstFd, bool inherited)
Add as "uses" dependency between this dir and dir, that was caused by a dependency on file fd.
void computeDependencies ()
Computes the dependencies between directories.
Static Private Member Functions
static DirDef * createNewDir (const char *path)
static bool matchPath (const QCString &path, QStrList &l)
Private Attributes
DirList m_subdirs
QCString m_dispName
QCString m_shortName
QCString m_diskName
FileList * m_fileList
int m_dirCount
int m_level
DirDef * m_parent
QDict< UsedDir > * m_usedDirs
Friends
void computeDirDependencies ()
Additional Inherited Members
Public Types inherited from DefinitionIntf
enum DefType {
TypeClass = 0, TypeFile = 1, TypeNamespace = 2, TypeMember = 3,
TypeGroup = 4, TypePackage = 5, TypePage = 6, TypeDir = 7,
TypeSymbolList = 8
}
Protected Member Functions inherited from Definition
Definition (const Definition &d)
Detailed Description
A model of a directory symbol.
Definition at line 44 of file dirdef.h.
Constructor & Destructor Documentation
DirDef()
DirDef::DirDef (const char * path)
Definition at line 21 of file dirdef.cpp.
References Config_getBool, g_dirCount, m_dirCount, m_diskName, m_dispName, m_fileList, m_level, m_parent, m_shortName, m_usedDirs, Definition::setLocalName(), and stripFromPath().
Referenced by createNewDir().
~DirDef()
DirDef::~DirDef () virtual
Definition at line 52 of file dirdef.cpp.
References m_fileList, and m_usedDirs.
Member Function Documentation
addFile()
void DirDef::addFile (FileDef * fd)
Definition at line 75 of file dirdef.cpp.
References m_fileList, and FileDef::setDirDef().
Referenced by buildDirectories().
addSubDir()
void DirDef::addSubDir (DirDef * subdir)
Definition at line 68 of file dirdef.cpp.
References m_parent, m_subdirs, and Definition::setOuterScope().
Referenced by buildDirectories().
addUsesDependency()
void DirDef::addUsesDependency (DirDef * usedDir, FileDef * srcFd, FileDef * dstFd, bool inherited) private
Add as "uses" dependency between this dir and dir, that was caused by a dependency on file fd.
Definition at line 546 of file dirdef.cpp.
References UsedDir::addFileDep(), addUsesDependency(), UsedDir::findFilePair(), getOutputFileBase(), FileDef::getOutputFileBase(), m_usedDirs, and parent().
Referenced by addUsesDependency(), and computeDependencies().
anchor()
QCString DirDef::anchor () const inline virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 53 of file dirdef.h.
computeDependencies()
void DirDef::computeDependencies () private
Computes the dependencies between directories.
Definition at line 600 of file dirdef.cpp.
References addUsesDependency(), IncludeInfo::fileDef, FileDef::getDirDef(), FileDef::includeFileList(), FileDef::isLinkable(), m_fileList, m_usedDirs, and UsedDir::sort().
Referenced by computeDirDependencies().
createNewDir()
DirDef * DirDef::createNewDir (const char * path) static private
Definition at line 701 of file dirdef.cpp.
References SDict< T >::append(), DirDef(), Doxygen::directories, and SDict< T >::find().
Referenced by mergeDirectoryInTree().
definitionType()
DefType DirDef::definitionType () const inline virtual
Use this for dynamic inspection of the type of the derived class
Implements DefinitionIntf.
Definition at line 51 of file dirdef.h.
References DefinitionIntf::TypeDir.
depGraphIsTrivial()
bool DirDef::depGraphIsTrivial () const
Definition at line 656 of file dirdef.cpp.
References m_usedDirs.
Referenced by DotDirDeps::isTrivial().
dirCount()
int DirDef::dirCount () const inline
Definition at line 65 of file dirdef.h.
References m_dirCount.
Referenced by writeDotDirDepGraph().
displayName()
QCString DirDef::displayName (bool includeScope = TRUE) const inline virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 56 of file dirdef.h.
References m_dispName.
Referenced by addListReferences(), generateDocbookForDir(), generateXMLForDir(), writeDirectoryGraph(), DirRelation::writeDocumentation(), writeDotDirDepGraph(), DotDirDeps::writeGraph(), writeInnerDirs(), GroupDef::writeTagFile(), and writeTagFile().
endMemberDeclarations()
void DirDef::endMemberDeclarations (OutputList & ol) private
Definition at line 355 of file dirdef.cpp.
References OutputList::endMemberSections().
Referenced by writeDocumentation().
getFiles()
FileList* DirDef::getFiles () const inline
Definition at line 59 of file dirdef.h.
References m_fileList.
Referenced by NestingNodeContext::Private::addDirFiles(), dirHasVisibleChildren(), DirContext::Private::files(), generateDocbookForDir(), generateXMLForDir(), writeDirTreeNode(), and writeSubDirList().
getOutputFileBase()
QCString DirDef::getOutputFileBase () const virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 119 of file dirdef.cpp.
References encodeDirName(), and m_diskName.
Referenced by addListReferences(), addUsesDependency(), DirContext::Private::dirGraph(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateDocbookForDir(), generateXMLForDir(), GroupDef::writeDirs(), writeDirTreeNode(), writeDocumentation(), DirRelation::writeDocumentation(), writeDotDirDepGraph(), DotDirDeps::writeGraph(), writeInnerDirs(), writePartialDirPath(), writeSubDirList(), and writeTagFile().
hasDetailedDescription()
bool DirDef::hasDetailedDescription () const
Definition at line 365 of file dirdef.cpp.
References Definition::briefDescription(), Config_getBool, and Definition::documentation().
Referenced by DirContext::Private::hasDetails().
isCluster()
bool DirDef::isCluster () const inline
Definition at line 62 of file dirdef.h.
References m_subdirs.
Referenced by writeDotDirDepGraph().
isLinkable()
bool DirDef::isLinkable () const virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 63 of file dirdef.cpp.
References isLinkableInProject(), and Definition::isReference().
Referenced by resolveLink().
isLinkableInProject()
bool DirDef::isLinkableInProject () const virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 58 of file dirdef.cpp.
References Definition::isReference().
Referenced by countDirs(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), isLinkable(), RTFGenerator::startIndexSection(), LatexGenerator::startIndexSection(), and GroupDef::writeTagFile().
isParentOf()
bool DirDef::isParentOf (DirDef * dir) const
Definition at line 646 of file dirdef.cpp.
References parent().
Referenced by writeDotDirDepGraph().
level()
int DirDef::level () const inline
Definition at line 63 of file dirdef.h.
References m_level.
Referenced by setLevel().
matchPath()
bool DirDef::matchPath (const QCString & path, QStrList & l) static private
Definition at line 715 of file dirdef.cpp.
Referenced by mergeDirectoryInTree().
mergeDirectoryInTree()
DirDef * DirDef::mergeDirectoryInTree (const QCString & path) static
strip part of path if it matches one of the paths in the Config_getList(STRIP_FROM_PATH) list
Definition at line 733 of file dirdef.cpp.
References Config_getList, createNewDir(), and matchPath().
Referenced by buildDirectories().
parent()
DirDef* DirDef::parent () const inline
Definition at line 64 of file dirdef.h.
References m_parent.
Referenced by addUsesDependency(), isParentOf(), setLevel(), writeDotDirDepGraph(), and writePartialDirPath().
setDiskName()
void DirDef::setDiskName (const QCString & name) inline
Definition at line 78 of file dirdef.h.
References m_diskName, and Definition::name().
Referenced by computeCommonDirPrefix().
setLevel()
void DirDef::setLevel () private
Definition at line 526 of file dirdef.cpp.
References level(), m_level, parent(), and setLevel().
Referenced by computeDirDependencies(), and setLevel().
shortName()
const QCString& DirDef::shortName () const inline
Definition at line 57 of file dirdef.h.
References m_shortName.
Referenced by DirList::compareValues(), DirSDict::compareValues(), DirContext::Private::dirName(), writeDirectoryGraph(), GroupDef::writeDirs(), writeDirTreeNode(), DirRelation::writeDocumentation(), writeDotDirDepGraph(), writePartialDirPath(), and writeSubDirList().
shortTitle()
QCString DirDef::shortTitle () const
Definition at line 360 of file dirdef.cpp.
References m_shortName, theTranslator, and Translator::trDirReference().
Referenced by DirContext::Private::title(), and writeDocumentation().
sort()
void DirDef::sort ()
Definition at line 81 of file dirdef.cpp.
References m_fileList, and m_subdirs.
Referenced by buildDirectories().
startMemberDeclarations()
void DirDef::startMemberDeclarations (OutputList & ol) private
Definition at line 350 of file dirdef.cpp.
References OutputList::startMemberSections().
Referenced by writeDocumentation().
subDirs()
const DirList& DirDef::subDirs () const inline
Definition at line 61 of file dirdef.h.
References m_subdirs.
Referenced by NestingNodeContext::Private::addDirFiles(), dirHasVisibleChildren(), DirContext::Private::dirs(), generateDocbookForDir(), generateXMLForDir(), writeDirTreeNode(), and writeDotDirDepGraph().
usedDirs()
const QDict<UsedDir>* DirDef::usedDirs () const inline
Definition at line 66 of file dirdef.h.
References m_usedDirs.
Referenced by writeDotDirDepGraph().
writeBriefDescription()
void DirDef::writeBriefDescription (OutputList & ol) private
Definition at line 171 of file dirdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), Definition::documentation(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), Definition::hasBriefDescription(), OutputGenerator::Html, DocRoot::isEmpty(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeDetailedDescription()
void DirDef::writeDetailedDescription (OutputList & ol, const QCString & title) private
Definition at line 126 of file dirdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), Definition::docFile(), Definition::docLine(), Definition::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), OutputList::generateDoc(), OutputGenerator::Html, OutputGenerator::Latex, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startGroupHeader(), OutputList::writeAnchor(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDirectoryGraph()
void DirDef::writeDirectoryGraph (OutputList & ol) private
Definition at line 208 of file dirdef.cpp.
References Config_getBool, OutputList::disable(), displayName(), OutputList::enableAll(), OutputList::endDirDepGraph(), DotDirDeps::isTrivial(), OutputGenerator::Man, msg(), OutputList::parseText(), shortName(), OutputList::startDirDepGraph(), theTranslator, and Translator::trDirDepGraph().
Referenced by writeDocumentation().
writeDocumentation()
void DirDef::writeDocumentation (OutputList & ol)
Definition at line 418 of file dirdef.cpp.
References LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocManager::Directory, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::disable(), OutputList::disableAllBut(), OutputList::enableAll(), OutputList::endContents(), endFileWithNavPath(), endMemberDeclarations(), OutputList::endQuickIndices(), endTitle(), err(), LayoutDocEntry::FileClasses, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, Definition::getLanguage(), getOutputFileBase(), LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, HLI_Files, OutputGenerator::Html, LayoutDocManager::instance(), LayoutDocEntry::kind(), m_dispName, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, Definition::name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), shortTitle(), OutputList::startContents(), startFile(), startMemberDeclarations(), startTitle(), theTranslator, LayoutDocEntrySection::title(), Translator::trDirReference(), writeBriefDescription(), writeDetailedDescription(), writeDirectoryGraph(), writeFileList(), Definition::writeNavigationPath(), and writeSubDirList().
Referenced by generateDirDocs().
writeFileList()
void DirDef::writeFileList (OutputList & ol) private
Definition at line 278 of file dirdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::disableAllBut(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), OutputList::endTextLink(), OutputList::generateDoc(), FileDef::generateSourceFile(), FileDef::getOutputFileBase(), Definition::getReference(), Definition::hasDocumentation(), OutputGenerator::Html, FileDef::includeName(), OutputList::insertMemberAlign(), FileDef::isLinkable(), m_fileList, FileDef::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), OutputList::startTextLink(), theTranslator, Translator::trCode(), Translator::trFile(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeSubDirList()
void DirDef::writeSubDirList (OutputList & ol) private
Definition at line 228 of file dirdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), OutputList::generateDoc(), getFiles(), getOutputFileBase(), Definition::getReference(), Definition::hasDocumentation(), OutputList::insertMemberAlign(), m_subdirs, OutputList::parseText(), shortName(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trDir(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeTagFile()
void DirDef::writeTagFile (FTextStream & t)
Definition at line 371 of file dirdef.cpp.
References convertToXML(), LayoutDocManager::Directory, LayoutDocEntry::DirFiles, LayoutDocEntry::DirSubDirs, displayName(), endl(), getOutputFileBase(), Doxygen::htmlFileExtension, LayoutDocManager::instance(), LayoutDocEntry::kind(), m_fileList, m_subdirs, FileDef::name(), Definition::name(), and Definition::writeDocAnchorsToTagFile().
Friends And Related Function Documentation
computeDirDependencies
void computeDirDependencies () friend
Definition at line 977 of file dirdef.cpp.
Member Data Documentation
m_dirCount
int DirDef::m_dirCount private
Definition at line 104 of file dirdef.h.
Referenced by dirCount(), and DirDef().
m_diskName
QCString DirDef::m_diskName private
Definition at line 102 of file dirdef.h.
Referenced by DirDef(), getOutputFileBase(), and setDiskName().
m_dispName
QCString DirDef::m_dispName private
Definition at line 100 of file dirdef.h.
Referenced by DirDef(), displayName(), and writeDocumentation().
m_fileList
FileList* DirDef::m_fileList private
Definition at line 103 of file dirdef.h.
Referenced by addFile(), computeDependencies(), DirDef(), getFiles(), sort(), writeFileList(), writeTagFile(), and ~DirDef().
m_level
int DirDef::m_level private
Definition at line 105 of file dirdef.h.
Referenced by DirDef(), level(), and setLevel().
m_parent
DirDef* DirDef::m_parent private
Definition at line 106 of file dirdef.h.
Referenced by addSubDir(), DirDef(), and parent().
m_shortName
QCString DirDef::m_shortName private
Definition at line 101 of file dirdef.h.
Referenced by DirDef(), shortName(), and shortTitle().
m_subdirs
DirList DirDef::m_subdirs private
Definition at line 99 of file dirdef.h.
Referenced by addSubDir(), isCluster(), sort(), subDirs(), writeSubDirList(), and writeTagFile().
m_usedDirs
QDict<UsedDir>* DirDef::m_usedDirs private
Definition at line 107 of file dirdef.h.
Referenced by addUsesDependency(), computeDependencies(), depGraphIsTrivial(), DirDef(), usedDirs(), and ~DirDef().
visited
bool DirDef::visited
Definition at line 77 of file dirdef.h.
Referenced by countDirs().
The documentation for this class was generated from the following files:
src/dirdef.h
src/dirdef.cpp