Doxygen: TemplateVariant Class Reference
TemplateVariant Class Reference
Template API
Variant type which can hold one value of a fixed set of types.
#include <template.h>
Classes
class Delegate
Helper class to create a delegate that can store a function/method call.
Public Types
enum Type {
None, Bool, Integer, String,
Struct, List, Function
}
Types of data that can be stored in a TemplateVariant.
Public Member Functions
Type type () const
Returns the type of the value stored in the variant.
QCString typeAsString () const
Return a string representation of the type of the value stored in the variant.
bool isValid () const
Returns TRUE if the variant holds a valid value, or FALSE otherwise.
TemplateVariant ()
Constructs an invalid variant.
TemplateVariant (bool b)
Constructs a new variant with a boolean value b.
TemplateVariant (int v)
Constructs a new variant with a integer value v.
TemplateVariant (const char *s, bool raw=FALSE)
Constructs a new variant with a string value s.
TemplateVariant (const QCString &s, bool raw=FALSE)
Constructs a new variant with a string value s.
TemplateVariant (TemplateStructIntf *s)
Constructs a new variant with a struct value s.
TemplateVariant (TemplateListIntf *l)
Constructs a new variant with a list value l.
TemplateVariant (const Delegate &delegate)
Constructs a new variant which represents a method call.
~TemplateVariant ()
Destroys the Variant object.
TemplateVariant (const TemplateVariant &v)
Constructs a copy of the variant, v, passed as the argument to this constructor.
TemplateVariant & operator= (const TemplateVariant &v)
Assigns the value of the variant v to this variant.
bool operator== (TemplateVariant &other)
Compares this QVariant with v and returns true if they are equal; otherwise returns false.
QCString toString () const
Returns the variant as a string.
bool toBool () const
Returns the variant as a boolean.
int toInt () const
Returns the variant as an integer.
TemplateListIntf * toList () const
Returns the pointer to list referenced by this variant or 0 if this variant does not have list type.
TemplateStructIntf * toStruct () const
Returns the pointer to struct referenced by this variant or 0 if this variant does not have struct type.
TemplateVariant call (const QValueList< TemplateVariant > &args)
Return the result of apply this function with args.
void setRaw (bool b)
Sets whether or not the value of the Variant should be escaped or written as-is (raw).
bool raw () const
Returns whether or not the value of the Value is raw.
Private Attributes
Type m_type
QCString m_strVal
union {
int m_intVal
bool m_boolVal
TemplateStructIntf * m_strukt
TemplateListIntf * m_list
};
Delegate m_delegate
bool m_raw
Detailed Description
Variant type which can hold one value of a fixed set of types.
Definition at line 90 of file template.h.
Member Enumeration Documentation
Type
enum TemplateVariant::Type
Types of data that can be stored in a TemplateVariant.
Enumerator
None
Bool
Integer
String
Struct
List
Function
Definition at line 139 of file template.h.
Constructor & Destructor Documentation
TemplateVariant() [1/9]
TemplateVariant::TemplateVariant () inline
Constructs an invalid variant.
Definition at line 164 of file template.h.
Referenced by call().
TemplateVariant() [2/9]
TemplateVariant::TemplateVariant (bool b) inline explicit
Constructs a new variant with a boolean value b.
Definition at line 167 of file template.h.
TemplateVariant() [3/9]
TemplateVariant::TemplateVariant (int v) inline
Constructs a new variant with a integer value v.
Definition at line 170 of file template.h.
TemplateVariant() [4/9]
TemplateVariant::TemplateVariant (const char * s, bool raw = FALSE) inline
Constructs a new variant with a string value s.
Definition at line 173 of file template.h.
TemplateVariant() [5/9]
TemplateVariant::TemplateVariant (const QCString & s, bool raw = FALSE) inline
Constructs a new variant with a string value s.
Definition at line 176 of file template.h.
TemplateVariant() [6/9]
TemplateVariant::TemplateVariant (TemplateStructIntf * s)
Constructs a new variant with a struct value s.
Note
. The variant will hold a reference to the object.
Definition at line 147 of file template.cpp.
References TemplateStructIntf::addRef(), and m_strukt.
TemplateVariant() [7/9]
TemplateVariant::TemplateVariant (TemplateListIntf * l)
Constructs a new variant with a list value l.
Note
. The variant will hold a reference to the object.
Definition at line 153 of file template.cpp.
References TemplateListIntf::addRef(), and m_list.
TemplateVariant() [8/9]
TemplateVariant::TemplateVariant (const Delegate & delegate) inline
Constructs a new variant which represents a method call.
Parameters
[in] delegate Delegate object to invoke when calling call() on this variant.
Note
Use TemplateVariant::Delegate::fromMethod() and TemplateVariant::Delegate::fromFunction() to create Delegate objects.
Definition at line 195 of file template.h.
~TemplateVariant()
TemplateVariant::~TemplateVariant ()
Destroys the Variant object.
Definition at line 159 of file template.cpp.
References List, m_list, m_strukt, m_type, TemplateListIntf::release(), TemplateStructIntf::release(), and Struct.
TemplateVariant() [9/9]
TemplateVariant::TemplateVariant (const TemplateVariant & v)
Constructs a copy of the variant, v, passed as the argument to this constructor.
Definition at line 165 of file template.cpp.
References TemplateListIntf::addRef(), TemplateStructIntf::addRef(), Bool, Function, Integer, List, m_boolVal, m_delegate, m_intVal, m_list, m_raw, m_strukt, m_strVal, m_type, None, String, and Struct.
Member Function Documentation
call()
TemplateVariant TemplateVariant::call (const QValueList< TemplateVariant > & args) inline
Return the result of apply this function with args.
Returns an empty string if the variant type is not a function.
Definition at line 272 of file template.h.
References Function, m_delegate, m_type, and TemplateVariant().
Referenced by TemplateNodeVariable::render(), TemplateNodeFor::render(), TemplateNodeCycle::render(), and ExprAstFunctionVariable::resolve().
isValid()
bool TemplateVariant::isValid () const inline
Returns TRUE if the variant holds a valid value, or FALSE otherwise.
Definition at line 161 of file template.h.
References m_type, and None.
Referenced by FilterAdd::apply(), FilterGet::apply(), FilterRaw::apply(), FilterList::apply(), FilterTexLabel::apply(), FilterTexIndex::apply(), FilterLength::apply(), FilterDefault::apply(), FilterFlatten::apply(), FilterRelative::apply(), FilterPaginate::apply(), FilterStripPath::apply(), FilterNoWrap::apply(), FilterDivisibleBy::apply(), FilterIsRelativeURL::apply(), FilterIsAbsoluteURL::apply(), FilterDecodeURL::apply(), FilterFlatten::flatten(), TemplateContextImpl::get(), TemplateNodeTree::renderChildren(), and ExprAstVariable::resolve().
operator=()
TemplateVariant & TemplateVariant::operator= (const TemplateVariant & v)
Assigns the value of the variant v to this variant.
Definition at line 181 of file template.cpp.
References TemplateListIntf::addRef(), TemplateStructIntf::addRef(), Bool, Function, Integer, List, m_boolVal, m_delegate, m_intVal, m_list, m_raw, m_strukt, m_strVal, m_type, None, TemplateListIntf::release(), TemplateStructIntf::release(), String, and Struct.
operator==()
bool TemplateVariant::operator== (TemplateVariant & other) inline
Compares this QVariant with v and returns true if they are equal; otherwise returns false.
Definition at line 211 of file template.h.
References List, m_list, m_strukt, m_type, None, Struct, and toString().
raw()
bool TemplateVariant::raw () const inline
Returns whether or not the value of the Value is raw.
See also
setRaw()
Definition at line 287 of file template.h.
References m_raw.
Referenced by TemplateNodeVariable::render(), and TemplateNodeCycle::render().
setRaw()
void TemplateVariant::setRaw (bool b) inline
Sets whether or not the value of the Variant should be escaped or written as-is (raw).
Parameters
[in] b TRUE means write as-is, FALSE means apply escaping.
Definition at line 282 of file template.h.
References m_raw.
Referenced by TemplateNodeTree::renderChildren().
toBool()
bool TemplateVariant::toBool () const
Returns the variant as a boolean.
Definition at line 208 of file template.cpp.
References Bool, TemplateListIntf::count(), Function, Integer, List, m_boolVal, m_intVal, m_list, m_strVal, m_type, None, String, and Struct.
Referenced by TemplateNodeIf::render(), ExprAstNegate::resolve(), and ExprAstBinary::resolve().
toInt()
int TemplateVariant::toInt () const
Returns the variant as an integer.
Definition at line 223 of file template.cpp.
References Bool, TemplateListIntf::count(), Function, Integer, List, m_boolVal, m_intVal, m_list, m_strVal, m_type, None, String, and Struct.
Referenced by FilterPaginate::apply(), FilterDivisibleBy::apply(), ClassHierarchyContext::Private::preferredDepth(), ClassTreeContext::Private::preferredDepth(), NamespaceTreeContext::Private::preferredDepth(), FileTreeContext::Private::preferredDepth(), PageTreeContext::Private::preferredDepth(), ModuleTreeContext::Private::preferredDepth(), ExampleTreeContext::Private::preferredDepth(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), ExprAstUnary::resolve(), ExprAstBinary::resolve(), and FilterAdd::variantIntValue().
toList()
TemplateListIntf* TemplateVariant::toList () const inline
Returns the pointer to list referenced by this variant or 0 if this variant does not have list type.
Definition at line 256 of file template.h.
References List, m_list, and m_type.
Referenced by FilterLength::apply(), FilterFlatten::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterPaginate::apply(), FilterAlphaIndex::apply(), computeMaxDepth(), computeNumNodesAtLevel(), FilterFlatten::flatten(), TemplateContextImpl::get(), TemplateNodeFor::render(), TemplateNodeTree::render(), TemplateNodeMarkers::render(), and TemplateNodeTree::renderChildren().
toString()
QCString TemplateVariant::toString () const inline
Returns the variant as a string.
Definition at line 232 of file template.h.
References Bool, Function, Integer, List, m_boolVal, m_intVal, m_strVal, m_type, None, String, and Struct.
Referenced by FilterAdd::apply(), FilterGet::apply(), FilterRaw::apply(), FilterTexLabel::apply(), FilterTexIndex::apply(), FilterAppend::apply(), FilterPrepend::apply(), FilterLength::apply(), FilterDefault::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterRelative::apply(), FilterAlphaIndex::apply(), FilterStripPath::apply(), FilterNoWrap::apply(), FilterIsRelativeURL::apply(), FilterIsAbsoluteURL::apply(), FilterDecodeURL::apply(), ExprAstFilter::apply(), FilterListSort::determineSortKey(), FilterGroupBy::determineSortKey(), FilterAlphaIndex::determineSortKey(), NestingNodeContext::id(), operator==(), TemplateNodeVariable::render(), TemplateNodeExtend::render(), TemplateNodeInclude::render(), TemplateNodeCreate::render(), TemplateNodeCycle::render(), TemplateNodeMarkers::render(), TemplateNodeResource::render(), TemplateNodeEncoding::render(), ExprAstBinary::resolve(), and FilterAdd::variantIntValue().
toStruct()
TemplateStructIntf* TemplateVariant::toStruct () const inline
Returns the pointer to struct referenced by this variant or 0 if this variant does not have struct type.
Definition at line 264 of file template.h.
References m_strukt, m_type, and Struct.
Referenced by FilterGet::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterAlphaIndex::apply(), computeMaxDepth(), computeNumNodesAtLevel(), computePreferredDepth(), FilterFlatten::flatten(), TemplateContextImpl::get(), getPathListFunc(), TemplateNodeFor::render(), and TemplateNodeTree::renderChildren().
type()
Type TemplateVariant::type () const inline
Returns the type of the value stored in the variant.
Definition at line 142 of file template.h.
References m_type.
Referenced by TemplateContextImpl::addIndexEntry(), FilterAdd::apply(), FilterGet::apply(), FilterRaw::apply(), FilterList::apply(), FilterTexLabel::apply(), FilterTexIndex::apply(), FilterAppend::apply(), FilterPrepend::apply(), FilterLength::apply(), FilterDefault::apply(), FilterFlatten::apply(), FilterListSort::apply(), FilterGroupBy::apply(), FilterRelative::apply(), FilterPaginate::apply(), FilterAlphaIndex::apply(), FilterStripPath::apply(), FilterNoWrap::apply(), FilterDivisibleBy::apply(), FilterIsRelativeURL::apply(), FilterIsAbsoluteURL::apply(), FilterDecodeURL::apply(), ExprAstFilter::apply(), FilterFlatten::flatten(), TemplateContextImpl::get(), getPathListFunc(), TemplateNodeVariable::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeCycle::render(), TemplateNodeMarkers::render(), ExprAstFunctionVariable::resolve(), ExprAstBinary::resolve(), and FilterAdd::variantIntValue().
typeAsString()
QCString TemplateVariant::typeAsString () const inline
Return a string representation of the type of the value stored in the variant.
Definition at line 145 of file template.h.
References Bool, Function, Integer, List, m_type, None, String, and Struct.
Referenced by TemplateNodeFor::render(), and TemplateNodeTree::renderChildren().
Member Data Documentation
@4
union { ... }
m_boolVal
bool TemplateVariant::m_boolVal
Definition at line 295 of file template.h.
Referenced by operator=(), TemplateVariant(), toBool(), toInt(), and toString().
m_delegate
Delegate TemplateVariant::m_delegate private
Definition at line 299 of file template.h.
Referenced by call(), operator=(), and TemplateVariant().
m_intVal
int TemplateVariant::m_intVal
Definition at line 294 of file template.h.
Referenced by operator=(), TemplateVariant(), toBool(), toInt(), and toString().
m_list
TemplateListIntf* TemplateVariant::m_list
Definition at line 297 of file template.h.
Referenced by operator=(), operator==(), TemplateVariant(), toBool(), toInt(), toList(), and ~TemplateVariant().
m_raw
bool TemplateVariant::m_raw private
Definition at line 300 of file template.h.
Referenced by operator=(), raw(), setRaw(), and TemplateVariant().
m_strukt
TemplateStructIntf* TemplateVariant::m_strukt
Definition at line 296 of file template.h.
Referenced by operator=(), operator==(), TemplateVariant(), toStruct(), and ~TemplateVariant().
m_strVal
QCString TemplateVariant::m_strVal private
Definition at line 291 of file template.h.
Referenced by operator=(), TemplateVariant(), toBool(), toInt(), and toString().
m_type
Type TemplateVariant::m_type private
Definition at line 290 of file template.h.
Referenced by call(), isValid(), operator=(), operator==(), TemplateVariant(), toBool(), toInt(), toList(), toString(), toStruct(), type(), typeAsString(), and ~TemplateVariant().
The documentation for this class was generated from the following files:
src/template.h
src/template.cpp