Doxygen: DotRunner Class Reference
DotRunner Class Reference
Helper class to run dot from doxygen.
#include <dot.h>
Classes
struct CleanupItem
Public Member Functions
DotRunner (const QCString &file, const QCString &fontPath, bool checkResult, const QCString &imageName=QCString())
Creates a runner for a dot file.
void addJob (const char *format, const char *output)
Adds an additional job to the run.
void addPostProcessing (const char *cmd, const char *args)
void preventCleanUp ()
bool run ()
Runs dot for all jobs added.
const CleanupItem & cleanup () const
Private Attributes
DotConstString m_dotExe
bool m_multiTargets
QList< DotConstString > m_jobs
DotConstString m_postArgs
DotConstString m_postCmd
DotConstString m_file
DotConstString m_path
bool m_checkResult
DotConstString m_imageName
DotConstString m_imgExt
bool m_cleanUp
CleanupItem m_cleanupItem
Detailed Description
Helper class to run dot from doxygen.
Definition at line 364 of file dot.h.
Constructor & Destructor Documentation
DotRunner()
DotRunner::DotRunner (const QCString & file, const QCString & fontPath, bool checkResult, const QCString & imageName = QCString())
Creates a runner for a dot file.
Definition at line 751 of file dot.cpp.
References Config_getBool, m_cleanUp, m_jobs, and m_multiTargets.
Member Function Documentation
addJob()
void DotRunner::addJob (const char * format, const char * output)
Adds an additional job to the run.
Performing multiple jobs one file can be faster.
Definition at line 765 of file dot.cpp.
References m_jobs.
Referenced by DotGfxHierarchyTable::createGraph(), generateGraphLegend(), writeDotGraphFromFile(), writeDotImageMapFromFile(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), and DotGroupCollaboration::writeGraph().
addPostProcessing()
void DotRunner::addPostProcessing (const char * cmd, const char * args)
Definition at line 771 of file dot.cpp.
References m_postArgs, m_postCmd, and DotConstString::set().
cleanup()
const CleanupItem& DotRunner::cleanup () const inline
Definition at line 388 of file dot.h.
References m_cleanupItem.
Referenced by DotWorkerThread::run().
preventCleanUp()
void DotRunner::preventCleanUp () inline
Definition at line 384 of file dot.h.
References m_cleanUp.
run()
bool DotRunner::run ()
Runs dot for all jobs added.
Definition at line 777 of file dot.cpp.
References checkDotResult(), DotConstString::data(), err(), DotRunner::CleanupItem::file, DotConstString::isEmpty(), m_checkResult, m_cleanUp, m_cleanupItem, m_dotExe, m_file, m_imageName, m_imgExt, m_jobs, m_multiTargets, m_path, m_postArgs, m_postCmd, DotRunner::CleanupItem::path, portable_system(), and DotConstString::set().
Referenced by DotWorkerThread::run(), and DotManager::run().
Member Data Documentation
m_checkResult
bool DotRunner::m_checkResult private
Definition at line 398 of file dot.h.
Referenced by run().
m_cleanUp
bool DotRunner::m_cleanUp private
Definition at line 401 of file dot.h.
Referenced by DotRunner(), preventCleanUp(), and run().
m_cleanupItem
CleanupItem DotRunner::m_cleanupItem private
Definition at line 402 of file dot.h.
Referenced by cleanup(), and run().
m_dotExe
DotConstString DotRunner::m_dotExe private
Definition at line 391 of file dot.h.
Referenced by run().
m_file
DotConstString DotRunner::m_file private
Definition at line 396 of file dot.h.
Referenced by run().
m_imageName
DotConstString DotRunner::m_imageName private
Definition at line 399 of file dot.h.
Referenced by run().
m_imgExt
DotConstString DotRunner::m_imgExt private
Definition at line 400 of file dot.h.
Referenced by run().
m_jobs
QList<DotConstString> DotRunner::m_jobs private
Definition at line 393 of file dot.h.
Referenced by addJob(), DotRunner(), and run().
m_multiTargets
bool DotRunner::m_multiTargets private
Definition at line 392 of file dot.h.
Referenced by DotRunner(), and run().
m_path
DotConstString DotRunner::m_path private
Definition at line 397 of file dot.h.
Referenced by run().
m_postArgs
DotConstString DotRunner::m_postArgs private
Definition at line 394 of file dot.h.
Referenced by addPostProcessing(), and run().
m_postCmd
DotConstString DotRunner::m_postCmd private
Definition at line 395 of file dot.h.
Referenced by addPostProcessing(), and run().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp