Doxygen: HtmlCodeGenerator Class Reference
HtmlCodeGenerator Class Reference
#include <htmlgen.h>
Public Member Functions
HtmlCodeGenerator (FTextStream &t, const QCString &relPath)
HtmlCodeGenerator ()
void setTextStream (FTextStream &t)
void setRelativePath (const QCString &path)
void codify (const char *text)
void writeCodeLink (const char *ref, const char *file, const char *anchor, const char *name, const char *tooltip)
void writeTooltip (const char *id, const DocLinkInfo &docInfo, const char *decl, const char *desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void writeLineNumber (const char *, const char *, const char *, int)
void startCodeLine (bool)
void endCodeLine ()
void startFontClass (const char *s)
void endFontClass ()
void writeCodeAnchor (const char *anchor)
void setCurrentDoc (Definition *, const char *, bool)
void addWord (const char *, bool)
Public Member Functions inherited from CodeOutputInterface
virtual ~CodeOutputInterface ()
Private Member Functions
void _writeCodeLink (const char *className, const char *ref, const char *file, const char *anchor, const char *name, const char *tooltip)
void docify (const char *str)
Private Attributes
bool m_streamSet
FTextStream m_t
int m_col
QCString m_relPath
Detailed Description
Definition at line 31 of file htmlgen.h.
Constructor & Destructor Documentation
HtmlCodeGenerator() [1/2]
HtmlCodeGenerator::HtmlCodeGenerator (FTextStream & t, const QCString & relPath)
Definition at line 421 of file htmlgen.cpp.
References setTextStream().
HtmlCodeGenerator() [2/2]
HtmlCodeGenerator::HtmlCodeGenerator ()
Definition at line 416 of file htmlgen.cpp.
Member Function Documentation
_writeCodeLink()
void HtmlCodeGenerator::_writeCodeLink (const char * className, const char * ref, const char * file, const char * anchor, const char * name, const char * tooltip) private
Definition at line 548 of file htmlgen.cpp.
References convertToHtml(), docify(), externalLinkTarget(), externalRef(), Doxygen::htmlFileExtension, m_col, m_relPath, and m_t.
Referenced by writeCodeLink(), and writeLineNumber().
addWord()
void HtmlCodeGenerator::addWord (const char * , bool) inline virtual
Implements CodeOutputInterface.
Definition at line 56 of file htmlgen.h.
codify()
void HtmlCodeGenerator::codify (const char * s) virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 438 of file htmlgen.cpp.
References Config_getInt, m_col, m_streamSet, m_t, Doxygen::spaces, and writeUtf8Char().
Referenced by HtmlGenerator::codify(), and writeLineNumber().
docify()
void HtmlCodeGenerator::docify (const char * str) private
Definition at line 486 of file htmlgen.cpp.
References m_streamSet, and m_t.
Referenced by _writeCodeLink(), and writeTooltip().
endCodeLine()
void HtmlCodeGenerator::endCodeLine () virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 665 of file htmlgen.cpp.
References m_streamSet, and m_t.
Referenced by HtmlGenerator::endCodeLine().
endFontClass()
void HtmlCodeGenerator::endFontClass () virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 675 of file htmlgen.cpp.
References m_streamSet, and m_t.
Referenced by HtmlGenerator::endFontClass().
setCurrentDoc()
void HtmlCodeGenerator::setCurrentDoc (Definition * , const char * , bool) inline virtual
Implements CodeOutputInterface.
Definition at line 55 of file htmlgen.h.
setRelativePath()
void HtmlCodeGenerator::setRelativePath (const QCString & path)
Definition at line 433 of file htmlgen.cpp.
References m_relPath.
Referenced by HtmlGenerator::startFile().
setTextStream()
void HtmlCodeGenerator::setTextStream (FTextStream & t)
Definition at line 427 of file htmlgen.cpp.
References FTextStream::device(), m_streamSet, m_t, and FTextStream::setDevice().
Referenced by HtmlCodeGenerator(), and HtmlGenerator::startFile().
startCodeLine()
void HtmlCodeGenerator::startCodeLine (bool hasLineNumbers) virtual
Implements CodeOutputInterface.
Definition at line 656 of file htmlgen.cpp.
References m_col, m_streamSet, and m_t.
Referenced by HtmlGenerator::startCodeLine().
startFontClass()
void HtmlCodeGenerator::startFontClass (const char * clsName) virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 670 of file htmlgen.cpp.
References m_streamSet, and m_t.
Referenced by HtmlGenerator::startFontClass().
writeCodeAnchor()
void HtmlCodeGenerator::writeCodeAnchor (const char * name) virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 680 of file htmlgen.cpp.
References m_streamSet, and m_t.
Referenced by HtmlGenerator::writeCodeAnchor().
writeCodeLink()
void HtmlCodeGenerator::writeCodeLink (const char * ref, const char * file, const char * anchor, const char * name, const char * tooltip) virtual
Writes a link to an object in a code fragment.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 539 of file htmlgen.cpp.
References _writeCodeLink(), and m_streamSet.
Referenced by HtmlGenerator::writeCodeLink().
writeLineNumber()
void HtmlCodeGenerator::writeLineNumber (const char * ref, const char * file, const char * anchor, int lineNumber) virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
Implements CodeOutputInterface.
Definition at line 515 of file htmlgen.cpp.
References _writeCodeLink(), codify(), m_streamSet, and m_t.
Referenced by HtmlGenerator::writeLineNumber().
writeTooltip()
void HtmlCodeGenerator::writeTooltip (const char * id, const DocLinkInfo & docInfo, const char * decl, const char * desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 574 of file htmlgen.cpp.
References DocLinkInfo::anchor, SourceLinkInfo::anchor, docify(), endl(), externalRef(), SourceLinkInfo::file, Doxygen::htmlFileExtension, SourceLinkInfo::line, m_relPath, m_t, DocLinkInfo::name, DocLinkInfo::ref, SourceLinkInfo::ref, DocLinkInfo::url, and SourceLinkInfo::url.
Referenced by HtmlGenerator::writeTooltip().
Member Data Documentation
m_col
int HtmlCodeGenerator::m_col private
Definition at line 66 of file htmlgen.h.
Referenced by _writeCodeLink(), codify(), and startCodeLine().
m_relPath
QCString HtmlCodeGenerator::m_relPath private
Definition at line 67 of file htmlgen.h.
Referenced by _writeCodeLink(), setRelativePath(), and writeTooltip().
m_streamSet
bool HtmlCodeGenerator::m_streamSet private
Definition at line 64 of file htmlgen.h.
Referenced by codify(), docify(), endCodeLine(), endFontClass(), setTextStream(), startCodeLine(), startFontClass(), writeCodeAnchor(), writeCodeLink(), and writeLineNumber().
m_t
FTextStream HtmlCodeGenerator::m_t private
Definition at line 65 of file htmlgen.h.
Referenced by _writeCodeLink(), codify(), docify(), endCodeLine(), endFontClass(), setTextStream(), startCodeLine(), startFontClass(), writeCodeAnchor(), writeLineNumber(), and writeTooltip().
The documentation for this class was generated from the following files:
src/htmlgen.h
src/htmlgen.cpp