Doxygen: src/layout.cpp File Reference
layout.cpp File Reference
#include "layout.h"
#include "message.h"
#include "language.h"
#include "vhdldocgen.h"
#include "util.h"
#include "doxygen.h"
#include "version.h"
#include "config.h"
#include <assert.h>
#include <qxml.h>
#include <qfile.h>
#include <qstring.h>
#include <qfileinfo.h>
#include <qtextstream.h>
#include "layout_default.xml.h"
Classes
class LayoutParser
class LayoutParser::StartElementHandler
class LayoutParser::StartElementHandlerKind
class LayoutParser::StartElementHandlerSection
class LayoutParser::StartElementHandlerMember
class LayoutParser::StartElementHandlerNavEntry
class LayoutParser::EndElementHandler
class LayoutErrorHandler
class LayoutDocManager::Private
Macros
#define ADD_OPTION(langId, text) "|"+QCString().setNum(langId)+"="+text
#define COMPILE_FOR_1_OPTION(def, langId1, text1) def+ADD_OPTION(langId1,text1)
#define COMPILE_FOR_2_OPTIONS(def, langId1, text1, langId2, text2) COMPILE_FOR_1_OPTION(def,langId1,text1)+ADD_OPTION(langId2,text2)
#define COMPILE_FOR_3_OPTIONS(def, langId1, text1, langId2, text2, langId3, text3) COMPILE_FOR_2_OPTIONS(def,langId1,text1,langId2,text2)+ADD_OPTION(langId3,text3)
#define COMPILE_FOR_4_OPTIONS(def, langId1, text1, langId2, text2, langId3, text3, langId4, text4) COMPILE_FOR_3_OPTIONS(def,langId1,text1,langId2,text2,langId3,text3)+ADD_OPTION(langId4,text4)
Functions
static bool elemIsVisible (const QXmlAttributes &attrib, bool defVal=TRUE)
void writeDefaultLayoutFile (const char *fileName)
QCString extractLanguageSpecificTitle (const QCString &input, SrcLangExt lang)
Variables
static const char layout_default [] =
Macro Definition Documentation
ADD_OPTION
#define ADD_OPTION (langId, text) "|"+QCString().setNum(langId)+"="+text
Definition at line 39 of file layout.cpp.
COMPILE_FOR_1_OPTION
#define COMPILE_FOR_1_OPTION (def, langId1, text1) def+ADD_OPTION(langId1,text1)
Definition at line 41 of file layout.cpp.
Referenced by LayoutParser::init().
COMPILE_FOR_2_OPTIONS
#define COMPILE_FOR_2_OPTIONS (def, langId1, text1, langId2, text2) COMPILE_FOR_1_OPTION(def,langId1,text1)+ADD_OPTION(langId2,text2)
Definition at line 44 of file layout.cpp.
Referenced by LayoutParser::init().
COMPILE_FOR_3_OPTIONS
#define COMPILE_FOR_3_OPTIONS (def, langId1, text1, langId2, text2, langId3, text3) COMPILE_FOR_2_OPTIONS(def,langId1,text1,langId2,text2)+ADD_OPTION(langId3,text3)
Definition at line 47 of file layout.cpp.
Referenced by LayoutParser::init().
COMPILE_FOR_4_OPTIONS
#define COMPILE_FOR_4_OPTIONS (def, langId1, text1, langId2, text2, langId3, text3, langId4, text4) COMPILE_FOR_3_OPTIONS(def,langId1,text1,langId2,text2,langId3,text3)+ADD_OPTION(langId4,text4)
Definition at line 50 of file layout.cpp.
Referenced by LayoutParser::init().
Function Documentation
elemIsVisible()
static bool elemIsVisible (const QXmlAttributes & attrib, bool defVal = TRUE) static
Definition at line 53 of file layout.cpp.
References err().
Referenced by LayoutParser::startNavEntry(), LayoutParser::startSectionEntry(), and LayoutParser::startSimpleEntry().
extractLanguageSpecificTitle()
QCString extractLanguageSpecificTitle (const QCString & input, SrcLangExt lang)
Definition at line 1417 of file layout.cpp.
Referenced by LayoutDocEntryMemberDecl::subtitle(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), and LayoutDocEntryMemberDef::title().
writeDefaultLayoutFile()
void writeDefaultLayoutFile (const char * fileName)
Definition at line 1397 of file layout.cpp.
References err(), layout_default, openOutputFile(), substitute(), and versionString.
Referenced by readConfiguration().
Variable Documentation
layout_default
const char layout_default[] = static
Definition at line 35 of file layout.cpp.
Referenced by LayoutDocManager::init(), and writeDefaultLayoutFile().