Doxygen: src/msc.cpp File Reference
msc.cpp File Reference
#include "msc.h"
#include "portable.h"
#include "config.h"
#include "message.h"
#include "docparser.h"
#include "doxygen.h"
#include "index.h"
#include "util.h"
#include "ftextstream.h"
#include <qdir.h>
Functions
static bool convertMapFile (FTextStream &t, const char *mapName, const QCString relPath, const QCString &context)
void writeMscGraphFromFile (const char *inFile, const char *outDir, const char *outFile, MscOutputFormat format)
QCString getMscImageMapFromFile (const QCString &inFile, const QCString &outDir, const QCString &relPath, const QCString &context)
void writeMscImageMapFromFile (FTextStream &t, const QCString &inFile, const QCString &outDir, const QCString &relPath, const QCString &baseName, const QCString &context, MscOutputFormat format)
Variables
static const int maxCmdLine = 40960
Function Documentation
convertMapFile()
static bool convertMapFile (FTextStream & t, const char * mapName, const QCString relPath, const QCString & context) static
Definition at line 32 of file msc.cpp.
References DocRef::anchor(), endl(), err(), externalRef(), DocRef::file(), Doxygen::htmlFileExtension, and DocRef::ref().
Referenced by getMscImageMapFromFile().
getMscImageMapFromFile()
QCString getMscImageMapFromFile (const QCString & inFile, const QCString & outDir, const QCString & relPath, const QCString & context)
Definition at line 158 of file msc.cpp.
References Config_getString, convertMapFile(), portable_commandExtension(), portable_system(), portable_sysTimerStart(), and portable_sysTimerStop().
Referenced by writeMscImageMapFromFile().
writeMscGraphFromFile()
void writeMscGraphFromFile (const char * inFile, const char * outDir, const char * outFile, MscOutputFormat format)
Definition at line 93 of file msc.cpp.
References IndexList::addImageFile(), Config_getBool, Config_getString, err(), Doxygen::indexList, maxCmdLine, MSC_BITMAP, MSC_EPS, MSC_SVG, portable_commandExtension(), portable_pathSeparator(), portable_system(), portable_sysTimerStart(), and portable_sysTimerStop().
Referenced by DocbookDocVisitor::startMscFile(), LatexDocVisitor::startMscFile(), DocbookDocVisitor::writeMscFile(), HtmlDocVisitor::writeMscFile(), RTFDocVisitor::writeMscFile(), and LatexDocVisitor::writeMscFile().
writeMscImageMapFromFile()
void writeMscImageMapFromFile (FTextStream & t, const QCString & inFile, const QCString & outDir, const QCString & relPath, const QCString & baseName, const QCString & context, MscOutputFormat format)
Definition at line 196 of file msc.cpp.
References endl(), getMscImageMapFromFile(), MSC_BITMAP, MSC_EPS, and MSC_SVG.
Referenced by HtmlDocVisitor::writeMscFile().
Variable Documentation
maxCmdLine
const int maxCmdLine = 40960 static
Definition at line 30 of file msc.cpp.
Referenced by writeMscGraphFromFile().