Doxygen: src/portable.h File Reference
portable.h File Reference
Portable versions of functions that are platform dependent.
#include <sys/types.h>
#include <stdio.h>
#include <qglobal.h>
Typedefs
typedef off_t portable_off_t
Functions
int portable_system (const char *command, const char *args, bool commandHasConsole=TRUE)
uint portable_pid ()
const char * portable_getenv (const char *variable)
void portable_setenv (const char *variable, const char *value)
void portable_unsetenv (const char *variable)
portable_off_t portable_fseek (FILE *f, portable_off_t offset, int whence)
portable_off_t portable_ftell (FILE *f)
FILE * portable_fopen (const char *fileName, const char *mode)
char portable_pathSeparator ()
char portable_pathListSeparator ()
const char * portable_ghostScriptCommand ()
const char * portable_commandExtension ()
bool portable_fileSystemIsCaseSensitive ()
FILE * portable_popen (const char *name, const char *type)
int portable_pclose (FILE *stream)
void portable_sysTimerStart ()
void portable_sysTimerStop ()
double portable_getSysElapsedTime ()
void portable_sleep (int ms)
bool portable_isAbsolutePath (const char *fileName)
void portable_correct_path (void)
Correct a possible wrong PATH variable.
void * portable_iconv_open (const char *tocode, const char *fromcode)
size_t portable_iconv (void *cd, char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft)
int portable_iconv_close (void *cd)
Detailed Description
Portable versions of functions that are platform dependent.
Definition in file portable.h.
Typedef Documentation
portable_off_t
typedef off_t portable_off_t
Definition at line 11 of file portable.h.
Function Documentation
portable_commandExtension()
const char* portable_commandExtension ()
Definition at line 382 of file portable.cpp.
Referenced by getMscImageMapFromFile(), writeDiaGraphFromFile(), and writeMscGraphFromFile().
portable_correct_path()
void portable_correct_path (void)
Correct a possible wrong PATH variable.
This routine was inspired by the cause for bug 766059 was that in the Windows path there were forward slahes.
Definition at line 456 of file portable.cpp.
References portable_getenv(), and portable_setenv().
Referenced by initDoxygen().
portable_fileSystemIsCaseSensitive()
bool portable_fileSystemIsCaseSensitive ()
Definition at line 391 of file portable.cpp.
Referenced by getFilterFromList().
portable_fopen()
FILE* portable_fopen (const char * fileName, const char * mode)
Definition at line 344 of file portable.cpp.
Referenced by checkDotResult(), initWarningFormat(), Store::open(), and readCodeFragment().
portable_fseek()
portable_off_t portable_fseek (FILE * f, portable_off_t offset, int whence)
Definition at line 322 of file portable.cpp.
Referenced by Store::alloc(), Store::dumpBlock(), Store::read(), Store::release(), Store::seek(), and Store::write().
portable_ftell()
portable_off_t portable_ftell (FILE * f)
Definition at line 333 of file portable.cpp.
Referenced by Store::alloc(), Store::end(), Store::read(), and Store::write().
portable_getenv()
const char* portable_getenv (const char * variable)
Definition at line 317 of file portable.cpp.
Referenced by dateToString(), initDoxygen(), parseInput(), portable_correct_path(), and setDotFontPath().
portable_getSysElapsedTime()
double portable_getSysElapsedTime ()
Definition at line 420 of file portable.cpp.
References g_sysElapsedTime.
Referenced by generateOutput().
portable_ghostScriptCommand()
const char* portable_ghostScriptCommand ()
Definition at line 373 of file portable.cpp.
Referenced by FormulaList::generateBitmaps().
portable_iconv()
size_t portable_iconv (void * cd, char ** inbuf, size_t * inbytesleft, char ** outbuf, size_t * outbytesleft)
Referenced by encodeForOutput(), HtmlHelp::recode(), TemplateContextImpl::recode(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().
portable_iconv_close()
int portable_iconv_close (void * cd)
Referenced by encodeForOutput(), TemplateContextImpl::setEncoding(), transcodeCharacterBuffer(), transcodeCharacterStringToUTF8(), and HtmlHelp::~HtmlHelp().
portable_iconv_open()
void* portable_iconv_open (const char * tocode, const char * fromcode)
Referenced by encodeForOutput(), HtmlHelp::initialize(), TemplateContextImpl::setEncoding(), transcodeCharacterBuffer(), and transcodeCharacterStringToUTF8().
portable_isAbsolutePath()
bool portable_isAbsolutePath (const char * fileName)
Definition at line 434 of file portable.cpp.
Referenced by generateOutput(), and readTextFileByName().
portable_pathListSeparator()
char portable_pathListSeparator ()
Definition at line 364 of file portable.cpp.
Referenced by generatePlantUMLOutput(), parseInput(), and setDotFontPath().
portable_pathSeparator()
char portable_pathSeparator ()
Definition at line 355 of file portable.cpp.
Referenced by MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), ClassContext::Private::collaborationDiagram(), DirContext::Private::dirGraph(), InheritanceGraphContext::Private::graph(), ModuleContext::Private::groupGraph(), FileContext::Private::includedByGraph(), FileContext::Private::includeGraph(), ClassContext::Private::inheritanceDiagram(), readTextFileByName(), writeDiaGraphFromFile(), and writeMscGraphFromFile().
portable_pclose()
int portable_pclose (FILE * stream)
Definition at line 405 of file portable.cpp.
Referenced by FileDef::acquireFileVersion(), readCodeFragment(), and readInputFile().
portable_pid()
uint portable_pid ()
Definition at line 186 of file portable.cpp.
Referenced by parseInput().
portable_popen()
FILE* portable_popen (const char * name, const char * type)
Definition at line 400 of file portable.cpp.
Referenced by FileDef::acquireFileVersion(), readCodeFragment(), and readInputFile().
portable_setenv()
void portable_setenv (const char * variable, const char * value)
Definition at line 202 of file portable.cpp.
References environ, and last_environ.
Referenced by initDoxygen(), parseInput(), portable_correct_path(), setDotFontPath(), and unsetDotFontPath().
portable_sleep()
void portable_sleep (int ms)
Definition at line 425 of file portable.cpp.
Referenced by DotManager::run().
portable_system()
int portable_system (const char * command, const char * args, bool commandHasConsole = TRUE)
taken from the system() manpage on my Linux box
Definition at line 33 of file portable.cpp.
References environ, Debug::ExtCmd, and Debug::print().
Referenced by createSVG(), FlowChart::createSVG(), Htags::execute(), findAndCopyImage(), FormulaList::generateBitmaps(), generateOutput(), CiteDict::generatePage(), generatePlantUMLOutput(), getMscImageMapFromFile(), DotRunner::run(), writeDiaGraphFromFile(), ClassDiagram::writeFigure(), and writeMscGraphFromFile().
portable_sysTimerStart()
void portable_sysTimerStart ()
Definition at line 410 of file portable.cpp.
References g_time.
Referenced by Htags::execute(), findAndCopyImage(), FormulaList::generateBitmaps(), generateOutput(), generatePlantUMLOutput(), getMscImageMapFromFile(), DotManager::run(), writeDiaGraphFromFile(), ClassDiagram::writeFigure(), and writeMscGraphFromFile().
portable_sysTimerStop()
void portable_sysTimerStop ()
Definition at line 415 of file portable.cpp.
References g_sysElapsedTime, and g_time.
Referenced by Htags::execute(), findAndCopyImage(), FormulaList::generateBitmaps(), generateOutput(), CiteDict::generatePage(), generatePlantUMLOutput(), getMscImageMapFromFile(), DotManager::run(), writeDiaGraphFromFile(), ClassDiagram::writeFigure(), and writeMscGraphFromFile().
portable_unsetenv()
void portable_unsetenv (const char * variable)
Definition at line 283 of file portable.cpp.
References environ.
Referenced by setDotFontPath(), and unsetDotFontPath().