Doxygen: EntryNav Class Reference
EntryNav Class Reference
Wrapper for a node in the Entry tree.
#include <entry.h>
Public Member Functions
EntryNav (EntryNav *parent, Entry *e)
~EntryNav ()
void addChild (EntryNav *)
bool loadEntry (FileStorage *storage)
bool saveEntry (Entry *e, FileStorage *storage)
void setEntry (Entry *e)
void releaseEntry ()
void changeSection (int section)
void setFileDef (FileDef *fd)
Entry * entry () const
int section () const
SrcLangExt lang () const
const QCString & type () const
const QCString & name () const
TagInfo * tagInfo () const
const QList< EntryNav > * children () const
EntryNav * parent () const
FileDef * fileDef () const
Private Attributes
EntryNav * m_parent
parent node in the tree
QList< EntryNav > * m_subList
entries that are children of this one
int m_section
entry type (see Sections);
QCString m_type
member type
QCString m_name
member name
TagInfo * m_tagInfo
tag file info
FileDef * m_fileDef
SrcLangExt m_lang
programming language in which this entry was found
Entry * m_info
int64 m_offset
bool m_noLoad
Detailed Description
Wrapper for a node in the Entry tree.
Allows navigating through the Entry tree and load and storing Entry objects persistently to disk.
Definition at line 333 of file entry.h.
Constructor & Destructor Documentation
EntryNav()
EntryNav::EntryNav (EntryNav * parent, Entry * e)
Definition at line 331 of file entry.cpp.
References TagInfo::anchor, TagInfo::fileName, m_tagInfo, Entry::tagInfo, and TagInfo::tagName.
~EntryNav()
EntryNav::~EntryNav ()
Definition at line 357 of file entry.cpp.
References m_info, m_subList, and m_tagInfo.
Member Function Documentation
addChild()
void EntryNav::addChild (EntryNav * e)
Definition at line 364 of file entry.cpp.
References m_subList.
Referenced by addSTLClasses(), addSTLIterator(), addSTLMember(), and Entry::createSubtreeIndex().
changeSection()
void EntryNav::changeSection (int section) inline
Definition at line 343 of file entry.h.
References m_section, and section().
Referenced by addInterfaceOrServiceToServiceOrSingleton(), addMethodToClass(), addVariableToClass(), addVariableToFile(), and buildFunctionList().
children()
const QList<EntryNav>* EntryNav::children () const inline
Definition at line 352 of file entry.h.
References m_subList.
Referenced by addEnumValuesToEnums(), buildGroupListFiltered(), buildTypedefList(), buildVarList(), findMemberDocumentation(), findObjCMethodDefinitions(), organizeSubGroupsFiltered(), and printNavTree().
entry()
Entry* EntryNav::entry () const inline
Definition at line 346 of file entry.h.
References m_info.
Referenced by addClassToContext(), addEnumValuesToEnums(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addRelatedPage(), addVariable(), addVariableToClass(), addVariableToFile(), buildExampleList(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildInterfaceAndServiceList(), buildListOfUsingDecls(), buildNamespaceList(), buildPageList(), computeClassRelations(), computePageRelations(), computeTemplateClassRelations(), filterMemberDocumentation(), findBaseClassesForClass(), findClassRelation(), findDefineDocumentation(), findDirDocumentation(), findEnumDocumentation(), findEnums(), findGlobalMember(), findMainPage(), findMainPageTagFiles(), findMember(), findTemplateInstanceRelation(), findUsingDeclarations(), findUsingDeclImports(), findUsingDirectives(), isClassSection(), isVarWithConstructor(), and organizeSubGroupsFiltered().
fileDef()
FileDef* EntryNav::fileDef () const inline
Definition at line 354 of file entry.h.
References m_fileDef.
Referenced by addClassToContext(), addEnumValuesToEnums(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addVariableToClass(), addVariableToFile(), buildFunctionList(), buildListOfUsingDecls(), buildNamespaceList(), findClassRelation(), findDefineDocumentation(), findEnums(), findGlobalMember(), findMember(), findUsingDeclarations(), findUsingDirectives(), and isVarWithConstructor().
lang()
SrcLangExt EntryNav::lang () const inline
Definition at line 348 of file entry.h.
References m_lang.
Referenced by addEnumValuesToEnums(), buildInterfaceAndServiceList(), buildVarList(), extractClassName(), findClassRelation(), and findUsedClassesForClass().
loadEntry()
bool EntryNav::loadEntry (FileStorage * storage)
Definition at line 374 of file entry.cpp.
References m_info, m_name, m_noLoad, m_offset, m_section, m_type, Entry::name, Entry::section, FileStorage::seek(), Entry::type, and unmarshalEntry().
Referenced by addClassToContext(), addEnumValuesToEnums(), addVariable(), buildExampleList(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildInterfaceAndServiceList(), buildListOfUsingDecls(), buildNamespaceList(), buildPageList(), computeClassRelations(), computePageRelations(), computeTemplateClassRelations(), findDefineDocumentation(), findDirDocumentation(), findEnumDocumentation(), findEnums(), findInheritedTemplateInstances(), findMainPage(), findMainPageTagFiles(), findMemberDocumentation(), findObjCMethodDefinitions(), findTemplateInstanceRelation(), findUsedTemplateInstances(), findUsingDeclarations(), findUsingDeclImports(), findUsingDirectives(), isClassSection(), isVarWithConstructor(), and organizeSubGroupsFiltered().
name()
const QCString& EntryNav::name () const inline
Definition at line 350 of file entry.h.
References m_name.
Referenced by addClassToContext(), addEnumValuesToEnums(), addMemberDocs(), addPageToContext(), addVariable(), buildClassDocList(), buildClassList(), buildExampleList(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildInterfaceAndServiceList(), buildNamespaceList(), buildTypedefList(), buildVarList(), computePageRelations(), extractClassName(), findClassEntries(), findClassRelation(), findDefineDocumentation(), findEnumDocumentation(), findEnums(), findGroupScope(), findMember(), findUsingDeclarations(), findUsingDeclImports(), findUsingDirectives(), isClassSection(), isVarWithConstructor(), organizeSubGroupsFiltered(), and printNavTree().
parent()
EntryNav* EntryNav::parent () const inline
Definition at line 353 of file entry.h.
References m_parent.
Referenced by addClassToContext(), addEnumValuesToEnums(), addMemberDocs(), addPageToContext(), addVariable(), buildFunctionList(), buildInterfaceAndServiceList(), buildListOfUsingDecls(), findClassRelation(), findDefineDocumentation(), findEnumDocumentation(), findEnums(), findGroupScope(), findMember(), findUsingDeclarations(), findUsingDeclImports(), findUsingDirectives(), and isVarWithConstructor().
releaseEntry()
void EntryNav::releaseEntry ()
Definition at line 415 of file entry.cpp.
References m_info, and m_noLoad.
Referenced by addClassToContext(), addEnumValuesToEnums(), addVariable(), buildExampleList(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildInterfaceAndServiceList(), buildListOfUsingDecls(), buildNamespaceList(), buildPageList(), computeClassRelations(), computePageRelations(), computeTemplateClassRelations(), findDefineDocumentation(), findDirDocumentation(), findEnumDocumentation(), findEnums(), findInheritedTemplateInstances(), findMainPage(), findMemberDocumentation(), findTemplateInstanceRelation(), findUsedTemplateInstances(), findUsingDeclarations(), findUsingDeclImports(), findUsingDirectives(), isClassSection(), isVarWithConstructor(), and organizeSubGroupsFiltered().
saveEntry()
bool EntryNav::saveEntry (Entry * e, FileStorage * storage)
Definition at line 407 of file entry.cpp.
References m_offset, marshalEntry(), and FileStorage::pos().
Referenced by Entry::createSubtreeIndex().
section()
int EntryNav::section () const inline
Definition at line 347 of file entry.h.
References m_section.
Referenced by addClassToContext(), addEnumValuesToEnums(), addInterfaceOrServiceToServiceOrSingleton(), addPageToContext(), addVariable(), buildClassDocList(), buildClassList(), buildExampleList(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildInterfaceAndServiceList(), buildListOfUsingDecls(), buildNamespaceList(), buildPageList(), buildTypedefList(), buildVarList(), changeSection(), computePageRelations(), findClassRelation(), findDefineDocumentation(), findDirDocumentation(), findEnumDocumentation(), findEnums(), findGroupScope(), findMainPage(), findMainPageTagFiles(), findMember(), findMemberDocumentation(), findUsingDeclarations(), findUsingDeclImports(), findUsingDirectives(), isClassSection(), isVarWithConstructor(), organizeSubGroupsFiltered(), and printNavTree().
setEntry()
void EntryNav::setEntry (Entry * e)
Definition at line 425 of file entry.cpp.
References m_info, and m_noLoad.
Referenced by addSTLClasses(), addSTLIterator(), addSTLMember(), and parseInput().
setFileDef()
void EntryNav::setFileDef (FileDef * fd) inline
Definition at line 344 of file entry.h.
References m_fileDef.
Referenced by Entry::createSubtreeIndex().
tagInfo()
TagInfo* EntryNav::tagInfo () const inline
Definition at line 351 of file entry.h.
References m_tagInfo.
Referenced by addClassToContext(), addEnumValuesToEnums(), addInterfaceOrServiceToServiceOrSingleton(), addMethodToClass(), addPageToContext(), addRelatedPage(), addVariableToClass(), addVariableToFile(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildNamespaceList(), findClassRelation(), findDefineDocumentation(), findEnums(), findGroupScope(), findMainPage(), findMainPageTagFiles(), findMember(), and findUsingDeclImports().
type()
const QCString& EntryNav::type () const inline
Definition at line 349 of file entry.h.
References m_type.
Referenced by buildTypedefList(), and buildVarList().
Member Data Documentation
m_fileDef
FileDef* EntryNav::m_fileDef private
Definition at line 367 of file entry.h.
Referenced by fileDef(), and setFileDef().
m_info
Entry* EntryNav::m_info private
Definition at line 370 of file entry.h.
Referenced by entry(), loadEntry(), releaseEntry(), setEntry(), and ~EntryNav().
m_lang
SrcLangExt EntryNav::m_lang private
programming language in which this entry was found
Definition at line 368 of file entry.h.
Referenced by lang().
m_name
QCString EntryNav::m_name private
member name
Definition at line 365 of file entry.h.
Referenced by loadEntry(), and name().
m_noLoad
bool EntryNav::m_noLoad private
Definition at line 372 of file entry.h.
Referenced by loadEntry(), releaseEntry(), and setEntry().
m_offset
int64 EntryNav::m_offset private
Definition at line 371 of file entry.h.
Referenced by loadEntry(), and saveEntry().
m_parent
EntryNav* EntryNav::m_parent private
parent node in the tree
Definition at line 359 of file entry.h.
Referenced by parent().
m_section
int EntryNav::m_section private
entry type (see Sections);
Definition at line 363 of file entry.h.
Referenced by changeSection(), loadEntry(), and section().
m_subList
QList<EntryNav>* EntryNav::m_subList private
entries that are children of this one
Definition at line 360 of file entry.h.
Referenced by addChild(), children(), and ~EntryNav().
m_tagInfo
TagInfo* EntryNav::m_tagInfo private
tag file info
Definition at line 366 of file entry.h.
Referenced by EntryNav(), tagInfo(), and ~EntryNav().
m_type
QCString EntryNav::m_type private
member type
Definition at line 364 of file entry.h.
Referenced by loadEntry(), and type().
The documentation for this class was generated from the following files:
src/entry.h
src/entry.cpp