Doxygen: src/cite.cpp File Reference
cite.cpp File Reference
#include "cite.h"
#include "portable.h"
#include "config.h"
#include "message.h"
#include "util.h"
#include "language.h"
#include "ftextstream.h"
#include "resourcemgr.h"
#include <qdir.h>
Functions
const QCString bibTmpFile ("bibTmpFile_")
const QCString bibTmpDir ("bibTmpDir/")
Function Documentation
bibTmpDir()
const QCString bibTmpDir ("bibTmpDir/")
Referenced by CiteDict::generatePage().
bibTmpFile()
const QCString bibTmpFile ("bibTmpFile_")
Referenced by CiteDict::generatePage(), and CiteDict::writeLatexBibliography().