Doxygen: SearchIndexIntf Class Reference
SearchIndexIntf Class Reference abstract
#include <searchindex.h>
Public Types
enum Kind { Internal, External }
Public Member Functions
SearchIndexIntf (Kind k)
virtual ~SearchIndexIntf ()
virtual void setCurrentDoc (Definition *ctx, const char *anchor, bool isSourceFile)=0
virtual void addWord (const char *word, bool hiPriority)=0
virtual void write (const char *file)=0
Kind kind () const
Private Attributes
Kind m_kind
Detailed Description
Definition at line 69 of file searchindex.h.
Member Enumeration Documentation
Kind
enum SearchIndexIntf::Kind
Enumerator
Internal
External
Definition at line 72 of file searchindex.h.
Constructor & Destructor Documentation
SearchIndexIntf()
SearchIndexIntf::SearchIndexIntf (Kind k) inline
Definition at line 73 of file searchindex.h.
~SearchIndexIntf()
virtual SearchIndexIntf::~SearchIndexIntf () inline virtual
Definition at line 74 of file searchindex.h.
Member Function Documentation
addWord()
virtual void SearchIndexIntf::addWord (const char * word, bool hiPriority) pure virtual
Implemented in SearchIndexExternal, and SearchIndex.
Referenced by MemberDef::_addToSearchIndex(), HtmlGenerator::addWord(), DocLinkedWord::DocLinkedWord(), DocWord::DocWord(), NamespaceDef::writeDocumentation(), GroupDef::writeDocumentation(), FileDef::writeDocumentation(), ClassDef::writeDocumentationContents(), and VhdlDocGen::writeVHDLDeclaration().
kind()
Kind SearchIndexIntf::kind () const inline
Definition at line 78 of file searchindex.h.
References m_kind.
setCurrentDoc()
virtual void SearchIndexIntf::setCurrentDoc (Definition * ctx, const char * anchor, bool isSourceFile) pure virtual
Implemented in SearchIndexExternal, and SearchIndex.
Referenced by MemberDef::_addToSearchIndex(), HtmlGenerator::setCurrentDoc(), validatingParseDoc(), NamespaceDef::writeDocumentation(), GroupDef::writeDocumentation(), FileDef::writeDocumentation(), ClassDef::writeDocumentationContents(), and VhdlDocGen::writeVHDLDeclaration().
write()
virtual void SearchIndexIntf::write (const char * file) pure virtual
Implemented in SearchIndexExternal, and SearchIndex.
Referenced by generateOutput().
Member Data Documentation
m_kind
Kind SearchIndexIntf::m_kind private
Definition at line 80 of file searchindex.h.
Referenced by kind().
The documentation for this class was generated from the following file:
src/searchindex.h