Doxygen: TemplateListIntf Class Reference
TemplateListIntf Class Reference abstract
Template API
Abstract read-only interface for a context value of type list.
#include <template.h>
Classes
class ConstIterator
Abstract interface for a iterator of a list.
Public Member Functions
virtual ~TemplateListIntf ()
Destroys the list.
virtual int count () const =0
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const =0
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const =0
Creates a new iterator for this list.
virtual int addRef ()=0
Increase object's reference count.
virtual int release ()=0
Decreases object's referenc count, destroy object if 0.
Detailed Description
Abstract read-only interface for a context value of type list.
Note
The values of the list are TemplateVariants.
Definition at line 329 of file template.h.
Constructor & Destructor Documentation
~TemplateListIntf()
virtual TemplateListIntf::~TemplateListIntf () inline virtual
Destroys the list.
Definition at line 355 of file template.h.
Member Function Documentation
addRef()
virtual int TemplateListIntf::addRef () pure virtual
Increase object's reference count.
Implemented in SearchIndicesContext, SymbolIndicesContext, SymbolGroupListContext, SymbolListContext, ArgumentListContext, AllMembersListContext, InheritedMemberInfoListContext, MemberGroupListContext, MemberListContext, InheritanceListContext, ExampleListContext, ModuleListContext, PageListContext, FileListContext, DirListContext, NamespaceListContext, NestingContext, ClassInheritanceContext, ClassListContext, TemplateList, IncludeInfoListContext, GenericNodeListContext, and UsedFilesContext.
Referenced by TemplateVariant::operator=(), and TemplateVariant::TemplateVariant().
at()
virtual TemplateVariant TemplateListIntf::at (int index) const pure virtual
Returns the element at index position index.
Implemented in SearchIndicesContext, SymbolIndicesContext, SymbolGroupListContext, SymbolListContext, ArgumentListContext, AllMembersListContext, InheritedMemberInfoListContext, MemberGroupListContext, MemberListContext, InheritanceListContext, ExampleListContext, ModuleListContext, PageListContext, FileListContext, DirListContext, NamespaceListContext, NestingContext, ClassInheritanceContext, ClassListContext, TemplateList, IncludeInfoListContext, UsedFilesContext, and GenericNodeListContext.
Referenced by TemplateContextImpl::get().
count()
virtual int TemplateListIntf::count () const pure virtual
Returns the number of elements in the list.
Implemented in SearchIndicesContext, SymbolIndicesContext, SymbolGroupListContext, SymbolListContext, ArgumentListContext, AllMembersListContext, InheritedMemberInfoListContext, MemberGroupListContext, MemberListContext, InheritanceListContext, ExampleListContext, ModuleListContext, PageListContext, FileListContext, DirListContext, NamespaceListContext, NestingContext, ClassInheritanceContext, ClassListContext, TemplateList, IncludeInfoListContext, UsedFilesContext, and GenericNodeListContext.
Referenced by FilterLength::apply(), TemplateNodeFor::render(), TemplateNodeTree::renderChildren(), TemplateVariant::toBool(), and TemplateVariant::toInt().
createIterator()
virtual TemplateListIntf::ConstIterator* TemplateListIntf::createIterator () const pure virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implemented in SearchIndicesContext, SymbolIndicesContext, SymbolGroupListContext, SymbolListContext, ArgumentListContext, AllMembersListContext, InheritedMemberInfoListContext, MemberGroupListContext, MemberListContext, InheritanceListContext, ExampleListContext, ModuleListContext, PageListContext, FileListContext, DirListContext, NamespaceListContext, NestingContext, ClassInheritanceContext, ClassListContext, TemplateList, IncludeInfoListContext, UsedFilesContext, and GenericNodeListContext.
Referenced by FilterListSort::apply(), FilterGroupBy::apply(), FilterPaginate::apply(), FilterAlphaIndex::apply(), computeMaxDepth(), computeNumNodesAtLevel(), computePreferredDepth(), FilterFlatten::flatten(), TemplateNodeFor::render(), TemplateNodeMarkers::render(), and TemplateNodeTree::renderChildren().
release()
virtual int TemplateListIntf::release () pure virtual
Decreases object's referenc count, destroy object if 0.
Implemented in SearchIndicesContext, SymbolIndicesContext, SymbolGroupListContext, SymbolListContext, ArgumentListContext, AllMembersListContext, InheritedMemberInfoListContext, MemberGroupListContext, MemberListContext, InheritanceListContext, ExampleListContext, ModuleListContext, PageListContext, FileListContext, DirListContext, NamespaceListContext, NestingContext, ClassInheritanceContext, ClassListContext, TemplateList, IncludeInfoListContext, GenericNodeListContext, and UsedFilesContext.
Referenced by TemplateVariant::operator=(), and TemplateVariant::~TemplateVariant().
The documentation for this class was generated from the following file:
src/template.h