Doxygen: Operator Class Reference
Operator Class Reference
Class representing operators that can appear in template expressions.
Public Types
enum Type {
Or, And, Not, In,
Equal, NotEqual, Less, Greater,
LessEqual, GreaterEqual, Plus, Minus,
Multiply, Divide, Modulo, Filter,
Colon, Comma, LeftParen, RightParen,
Last
}
Static Public Member Functions
static const char * toString (Type op)
Detailed Description
Class representing operators that can appear in template expressions.
Definition at line 429 of file template.cpp.
Member Enumeration Documentation
Type
enum Operator::Type
Enumerator
Or
And
Not
In
Equal
NotEqual
Less
Greater
LessEqual
GreaterEqual
Plus
Minus
Multiply
Divide
Modulo
Filter
Colon
Comma
LeftParen
RightParen
Last
Definition at line 444 of file template.cpp.
Member Function Documentation
toString()
static const char* Operator::toString (Type op) inline static
Definition at line 452 of file template.cpp.
References And, Colon, Comma, Divide, Equal, Filter, Greater, GreaterEqual, In, Last, LeftParen, Less, LessEqual, Minus, Modulo, Multiply, Not, NotEqual, Or, Plus, and RightParen.
Referenced by ExprAstBinary::ExprAstBinary(), ExprAstUnary::ExprAstUnary(), and ExpressionParser::parsePrimaryExpression().
The documentation for this class was generated from the following file:
src/template.cpp