Doxygen: src/docparser.cpp File Reference
docparser.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <qcstring.h>
#include <qstack.h>
#include <qdict.h>
#include <qregexp.h>
#include <ctype.h>
#include "doxygen.h"
#include "debug.h"
#include "util.h"
#include "pagedef.h"
#include "docparser.h"
#include "doctokenizer.h"
#include "cmdmapper.h"
#include "printdocvisitor.h"
#include "message.h"
#include "section.h"
#include "searchindex.h"
#include "language.h"
#include "portable.h"
#include "cite.h"
#include "arguments.h"
#include "vhdldocgen.h"
#include "groupdef.h"
#include "classlist.h"
#include "filedef.h"
#include "memberdef.h"
#include "namespacedef.h"
#include "reflist.h"
#include "formula.h"
#include "config.h"
#include "growbuf.h"
#include "markdown.h"
#include "htmlentity.h"
Classes
struct DocParserContext
Parser's context to store all global variables.
struct ActiveRowSpan
Helper class to compute the grid for an HTML style table.
Macros
#define DBG(x) do {} while(0)
#define INTERNAL_ASSERT(x) do {} while(0)
#define CHECK_FOR_COMMAND(str, action)
Typedefs
typedef QList< ActiveRowSpan > RowSpanList
List of ActiveRowSpan classes.
Functions
static void docParserPushContext (bool saveParamInfo=TRUE)
static void docParserPopContext (bool keepParamInfo=FALSE)
static void unescapeCRef (QCString &s)
static QCString findAndCopyImage (const char *fileName, DocImage::Type type)
static void checkArgumentName (const QCString &name, bool isParam)
static void checkUndocumentedParams ()
static void detectNoDocumentedParams ()
static QCString stripKnownExtensions (const char *text)
static bool insidePRE (DocNode *n)
static bool insideLI (DocNode *n)
static bool insideUL (DocNode *n)
static bool insideOL (DocNode *n)
static bool insideTable (DocNode *n)
static bool findDocsForMemberOrCompound (const char *commandName, QCString *pDoc, QCString *pBrief, Definition **pDef)
static bool defaultHandleToken (DocNode *parent, int tok, QList< DocNode > &children, bool handleWord=TRUE)
static int handleStyleArgument (DocNode *parent, QList< DocNode > &children, const QCString &cmdName)
static void handleStyleEnter (DocNode *parent, QList< DocNode > &children, DocStyleChange::Style s, const HtmlAttribList *attribs)
static void handleStyleLeave (DocNode *parent, QList< DocNode > &children, DocStyleChange::Style s, const char *tagName)
static void handlePendingStyleCommands (DocNode *parent, QList< DocNode > &children)
static void handleInitialStyleCommands (DocPara *parent, QList< DocNode > &children)
static int handleAHref (DocNode *parent, QList< DocNode > &children, const HtmlAttribList &tagHtmlAttribs)
static void handleUnclosedStyleCommands ()
static void handleLinkedWord (DocNode *parent, QList< DocNode > &children, bool ignoreAutoLinkFlag=FALSE)
static void handleParameterType (DocNode *parent, QList< DocNode > &children, const QCString &paramTypes)
static DocInternalRef * handleInternalRef (DocNode *parent)
static DocAnchor * handleAnchor (DocNode *parent)
static void defaultHandleTitleAndSize (const int cmd, DocNode *parent, QList< DocNode > &children, QCString &width, QCString &height)
static void handleImg (DocNode *parent, QList< DocNode > &children, const HtmlAttribList &tagHtmlAttribs)
static int internalValidatingParseDoc (DocNode *parent, QList< DocNode > &children, const QCString &doc)
static void readTextFileByName (const QCString &file, QCString &text)
static void flattenParagraphs (DocNode *root, QList< DocNode > &children)
static bool findAttribute (const HtmlAttribList &tagHtmlAttribs, const char *attrName, QCString *result)
static QCString extractCopyDocId (const char *data, uint &j, uint len)
static uint isCopyBriefOrDetailsCmd (const char *data, uint i, uint len, bool &brief)
static uint isVerbatimSection (const char *data, uint i, uint len, QCString &endMarker)
static uint skipToEndMarker (const char *data, uint i, uint len, const QCString &endMarker)
static QCString processCopyDoc (const char *data, uint &len)
DocRoot * validatingParseDoc (const char *fileName, int startLine, Definition *ctx, MemberDef *md, const char *input, bool indexWords, bool isExample, const char *exampleName, bool singleLine, bool linkFromIndex)
DocText * validatingParseText (const char *input)
void docFindSections (const char *input, Definition *d, MemberGroup *mg, const char *fileName)
Variables
static const char * sectionLevelToName []
static Definition * g_scope
static QCString g_context
static bool g_inSeeBlock
static bool g_xmlComment
static bool g_insideHtmlLink
static QStack< DocNode > g_nodeStack
static QStack< DocStyleChange > g_styleStack
static QStack< DocStyleChange > g_initialStyleStack
static QList< Definition > g_copyStack
static QCString g_fileName
static QCString g_relPath
static bool g_hasParamCommand
static bool g_hasReturnCommand
static QDict< void > g_paramsFound
static MemberDef * g_memberDef
static bool g_isExample
static QCString g_exampleName
static SectionDict * g_sectionDict
static QCString g_searchUrl
static QCString g_includeFileText
static uint g_includeFileOffset
static uint g_includeFileLength
static QStack< DocParserContext > g_parserStack
Macro Definition Documentation
CHECK_FOR_COMMAND
#define CHECK_FOR_COMMAND (str, action)
Value:
do if ((i+sizeof(str)<len) && qstrncmp(data+i+1,str,sizeof(str)-1)==0) \
   { j=i+sizeof(str); action; } while(0)
Definition at line 7085 of file docparser.cpp.
Referenced by isCopyBriefOrDetailsCmd(), and isVerbatimSection().
DBG
#define DBG (x) do {} while(0)
Definition at line 59 of file docparser.cpp.
Referenced by DocSymbol::decodeSymbol(), defaultHandleToken(), DocPara::handleCommand(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocPara::handleRef(), handleStyleArgument(), handleStyleEnter(), handleStyleLeave(), DocInclude::parse(), DocIncOperator::parse(), DocIndexEntry::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocInternal::parse(), DocParBlock::parse(), DocHtmlList::parse(), DocSimpleSect::parse(), DocParamSect::parse(), DocPara::parse(), DocParamList::parse(), DocHtmlListItem::parse(), DocHtmlDescData::parse(), DocHtmlCell::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlBlockQuote::parse(), DocText::parse(), DocRoot::parse(), DocSimpleSect::parseRcs(), DocHtmlList::parseXml(), DocSimpleSect::parseXml(), DocParamList::parseXml(), DocHtmlListItem::parseXml(), DocHtmlCell::parseXml(), DocHtmlRow::parseXml(), and DocHtmlTable::parseXml().
INTERNAL_ASSERT
#define INTERNAL_ASSERT (x) do {} while(0)
Definition at line 68 of file docparser.cpp.
Referenced by DocPara::handleCommand(), DocSection::parse(), and DocPara::parse().
Typedef Documentation
RowSpanList
typedef QList<ActiveRowSpan> RowSpanList
List of ActiveRowSpan classes.
Definition at line 3756 of file docparser.cpp.
Function Documentation
checkArgumentName()
static void checkArgumentName (const QCString & name, bool isParam) static
Collects the parameters found with @param or @retval commands in a global list g_paramsFound. If isParam is set to TRUE and the parameter is not an actual parameter of the current member g_memberDef, then a warning is raised (unless warnings are disabled altogether).
Definition at line 388 of file docparser.cpp.
References argListToString(), MemberDef::argumentList(), Config_getBool, MemberDef::declArgumentList(), Definition::docFile(), Definition::docLine(), g_paramsFound, Definition::getDefFileName(), Definition::getDefLine(), Definition::getLanguage(), MemberDef::getScopeString(), MemberDef::inheritsDocsFrom(), MemberDef::isDefine(), MemberDef::isDocsForDefinition(), Argument::name, Definition::name(), SrcLangExt_Fortran, Argument::type, and warn_doc_error().
Referenced by DocParamList::parse(), and DocParamList::parseXml().
checkUndocumentedParams()
static void checkUndocumentedParams () static
Checks if the parameters that have been specified using @param are indeed all parameters. Must be called after checkArgumentName() has been called for each argument.
Definition at line 457 of file docparser.cpp.
References argListToString(), MemberDef::argumentList(), Config_getBool, MemberDef::declArgumentList(), Argument::docs, g_hasParamCommand, g_paramsFound, Definition::getDefFileName(), Definition::getDefLine(), Definition::getLanguage(), MemberDef::isDefine(), MemberDef::isDocsForDefinition(), Argument::name, MemberDef::qualifiedName(), SrcLangExt_Fortran, SrcLangExt_Python, substitute(), Argument::type, and warn_doc_error().
Referenced by validatingParseDoc().
defaultHandleTitleAndSize()
static void defaultHandleTitleAndSize (const int cmd, DocNode * parent, QList< DocNode > & children, QCString & width, QCString & height) static
Definition at line 1257 of file docparser.cpp.
References TokenInfo::chars, Mappers::cmdMapper, defaultHandleToken(), doctokenizerYYlex(), doctokenizerYYlineno, doctokenizerYYsetStatePara(), doctokenizerYYsetStateTitle(), doctokenizerYYsetStateTitleAttrValue(), Mapper::find(), g_fileName, g_nodeStack, g_token, handlePendingStyleCommands(), TokenInfo::name, TK_COMMAND, TK_SYMBOL, TK_WHITESPACE, TK_WORD, tokToString(), and warn_doc_error().
Referenced by DocPara::handleCommand(), DocImage::parse(), DocDotFile::parse(), DocMscFile::parse(), and DocDiaFile::parse().
defaultHandleToken()
static bool defaultHandleToken (DocNode * parent, int tok, QList< DocNode > & children, bool handleWord = TRUE) static
Definition at line 1341 of file docparser.cpp.
References TokenInfo::attribs, DocStyleChange::Bold, DocStyleChange::Center, TokenInfo::chars, CMD_AMP, CMD_ANCHOR, CMD_AT, CMD_BOLD, CMD_BSLASH, CMD_CODE, CMD_DBONLY, CMD_DCOLON, CMD_DOLLAR, CMD_EMPHASIS, CMD_FORMULA, CMD_GREATER, CMD_HASH, CMD_HTMLONLY, CMD_INTERNALREF, CMD_LATEXONLY, CMD_LESS, CMD_MANONLY, CMD_MDASH, CMD_MINUS, CMD_NDASH, CMD_PERCENT, CMD_PLUS, CMD_PUNT, CMD_QUOTE, CMD_RTFONLY, CMD_SETSCOPE, CMD_XMLONLY, Mappers::cmdMapper, DocStyleChange::Code, DBG, DocSymbol::decodeSymbol(), DocVerbatim::DocbookOnly, doctokenizerYYlex(), doctokenizerYYlineno, doctokenizerYYsetStateDbOnly(), doctokenizerYYsetStateHtmlOnly(), doctokenizerYYsetStateLatexOnly(), doctokenizerYYsetStateManOnly(), doctokenizerYYsetStatePara(), doctokenizerYYsetStateRtfOnly(), doctokenizerYYsetStateSetScope(), doctokenizerYYsetStateXmlOnly(), TokenInfo::endTag, g_context, g_exampleName, g_fileName, g_insideHtmlLink, g_isExample, g_nodeStack, g_token, handleAnchor(), handleInternalRef(), handleLinkedWord(), handleStyleArgument(), handleStyleEnter(), handleStyleLeave(), HTML_BOLD, HTML_CENTER, HTML_CODE, HTML_DIV, HTML_EMPHASIS, HTML_PRE, HTML_SMALL, HTML_SUB, HTML_SUP, DocVerbatim::HtmlOnly, Mappers::htmlTagMapper, TokenInfo::id, insidePRE(), TokenInfo::isEMailAddr, DocStyleChange::Italic, DocVerbatim::LatexOnly, DocVerbatim::ManOnly, TokenInfo::name, DocInternalRef::parse(), DocVerbatim::RtfOnly, DocStyleChange::Small, DocStyleChange::Subscript, DocStyleChange::Superscript, DocSymbol::Sym_Amp, DocSymbol::Sym_At, DocSymbol::Sym_BSlash, DocSymbol::Sym_Dollar, DocSymbol::Sym_Dot, DocSymbol::Sym_DoubleColon, DocSymbol::Sym_Greater, DocSymbol::Sym_Hash, DocSymbol::Sym_Less, DocSymbol::Sym_Minus, DocSymbol::Sym_Percent, DocSymbol::Sym_Plus, DocSymbol::Sym_Quot, DocSymbol::Sym_Unknown, TK_COMMAND, TK_HTMLTAG, TK_LNKWORD, TK_NEWPARA, TK_SYMBOL, TK_URL, TK_WHITESPACE, TK_WORD, tokToString(), TokenInfo::verb, warn_doc_error(), XML_C, and DocVerbatim::XmlOnly.
Referenced by defaultHandleTitleAndSize(), handleStyleArgument(), DocPara::injectToken(), DocTitle::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocSecRefItem::parse(), and DocHtmlCaption::parse().
detectNoDocumentedParams()
static void detectNoDocumentedParams () static
Check if a member has documentation for its parameter and or return type, if applicable. If found this will be stored in the member, this is needed as a member can have brief and detailed documentation, while only one of these needs to document the parameters.
Definition at line 529 of file docparser.cpp.
References MemberDef::argumentList(), Config_getBool, MemberDef::declArgumentList(), Argument::docs, doctokenizerYYlineno, g_fileName, g_hasParamCommand, g_hasReturnCommand, Definition::getLanguage(), MemberDef::hasDocumentedParams(), MemberDef::hasDocumentedReturnType(), MemberDef::isConstructor(), MemberDef::isDestructor(), Argument::name, MemberDef::setHasDocumentedParams(), MemberDef::setHasDocumentedReturnType(), SrcLangExt_Python, Argument::type, MemberDef::typeString(), and warn_doc_error().
Referenced by validatingParseDoc().
docFindSections()
void docFindSections (const char * input, Definition * d, MemberGroup * m, const char * fileName)
Searches for section and anchor commands in the input
Definition at line 7479 of file docparser.cpp.
References doctokenizerYYFindSections().
Referenced by PageDef::findSectionsInDocumentation(), MemberGroup::findSectionsInDocumentation(), GroupDef::findSectionsInDocumentation(), NamespaceDef::findSectionsInDocumentation(), FileDef::findSectionsInDocumentation(), ClassDef::findSectionsInDocumentation(), and MemberDef::findSectionsInDocumentation().
docParserPopContext()
static void docParserPopContext (bool keepParamInfo = FALSE) static
Definition at line 192 of file docparser.cpp.
References DocParserContext::context, DocParserContext::copyStack, doctokenizerYYlineno, doctokenizerYYpopContext(), DocParserContext::exampleName, DocParserContext::fileName, g_context, g_copyStack, g_exampleName, g_fileName, g_hasParamCommand, g_hasReturnCommand, g_includeFileLength, g_includeFileOffset, g_includeFileText, g_initialStyleStack, g_inSeeBlock, g_insideHtmlLink, g_isExample, g_nodeStack, g_paramsFound, g_parserStack, g_relPath, g_searchUrl, g_styleStack, g_token, g_xmlComment, DocParserContext::hasParamCommand, DocParserContext::hasReturnCommand, DocParserContext::includeFileLength, DocParserContext::includeFileOffset, DocParserContext::includeFileText, DocParserContext::initialStyleStack, DocParserContext::inSeeBlock, DocParserContext::insideHtmlLink, DocParserContext::isExample, DocParserContext::lineNo, DocParserContext::memberDef, DocParserContext::nodeStack, DocParserContext::paramsFound, DocParserContext::relPath, DocParserContext::scope, DocParserContext::searchUrl, DocParserContext::sectionDict, DocParserContext::styleStack, DocParserContext::token, and DocParserContext::xmlComment.
Referenced by DocPara::handleInclude(), DocPara::handleInheritDoc(), DocCopy::parse(), DocXRefItem::parse(), DocRef::parse(), DocSimpleSect::parseRcs(), validatingParseDoc(), and validatingParseText().
docParserPushContext()
static void docParserPushContext (bool saveParamInfo = TRUE) static
Definition at line 148 of file docparser.cpp.
References DocParserContext::context, DocParserContext::copyStack, doctokenizerYYlineno, doctokenizerYYpushContext(), DocParserContext::exampleName, DocParserContext::fileName, g_context, g_copyStack, g_exampleName, g_fileName, g_hasParamCommand, g_hasReturnCommand, g_includeFileLength, g_includeFileOffset, g_includeFileText, g_initialStyleStack, g_inSeeBlock, g_insideHtmlLink, g_isExample, g_memberDef, g_nodeStack, g_paramsFound, g_parserStack, g_relPath, g_scope, g_searchUrl, g_sectionDict, g_styleStack, g_token, g_xmlComment, DocParserContext::hasParamCommand, DocParserContext::hasReturnCommand, DocParserContext::includeFileLength, DocParserContext::includeFileOffset, DocParserContext::includeFileText, DocParserContext::initialStyleStack, DocParserContext::inSeeBlock, DocParserContext::insideHtmlLink, DocParserContext::isExample, DocParserContext::lineNo, DocParserContext::memberDef, DocParserContext::nodeStack, DocParserContext::paramsFound, DocParserContext::relPath, DocParserContext::scope, DocParserContext::searchUrl, DocParserContext::sectionDict, DocParserContext::styleStack, DocParserContext::token, and DocParserContext::xmlComment.
Referenced by DocPara::handleInclude(), DocPara::handleInheritDoc(), DocCopy::parse(), DocXRefItem::parse(), DocRef::parse(), DocSimpleSect::parseRcs(), validatingParseDoc(), and validatingParseText().
extractCopyDocId()
static QCString extractCopyDocId (const char * data, uint & j, uint len) static
Definition at line 7024 of file docparser.cpp.
Referenced by processCopyDoc().
findAndCopyImage()
static QCString findAndCopyImage (const char * fileName, DocImage::Type type) static
search for an image in the imageNameDict and if found copies the image to the output directory (which depends on the type parameter).
Definition at line 264 of file docparser.cpp.
References FileDef::absFilePath(), IndexList::addImageFile(), Config_getBool, Config_getString, DocImage::DocBook, doctokenizerYYlineno, err(), findFileDef(), g_fileName, DocImage::Html, Doxygen::imageNameDict, Doxygen::indexList, DocImage::Latex, FileDef::name(), portable_system(), portable_sysTimerStart(), portable_sysTimerStop(), DocImage::Rtf, showFileDefMatches(), and warn_doc_error().
Referenced by DocPara::handleImage().
findAttribute()
static bool findAttribute (const HtmlAttribList & tagHtmlAttribs, const char * attrName, QCString * result) static
Definition at line 5806 of file docparser.cpp.
References HtmlAttrib::name, and HtmlAttrib::value.
Referenced by DocPara::handleHtmlStartTag().
findDocsForMemberOrCompound()
static bool findDocsForMemberOrCompound (const char * commandName, QCString * pDoc, QCString * pBrief, Definition ** pDef) static
Looks for a documentation block with name commandName in the current context (g_context). The resulting documentation string is put in pDoc, the definition in which the documentation was found is put in pDef.
Return values
TRUE if name was found.
FALSE if name was not found.
Definition at line 718 of file docparser.cpp.
References Definition::briefDescription(), MemberDef::briefDescription(), Doxygen::classSDict, Definition::documentation(), MemberDef::documentation(), SDict< T >::find(), findFileDef(), g_context, getDefs(), Doxygen::groupSDict, Doxygen::inputNameDict, Doxygen::namespaceSDict, Doxygen::pageSDict, removeRedundantWhiteSpace(), and substitute().
Referenced by DocCopy::parse(), and processCopyDoc().
flattenParagraphs()
static void flattenParagraphs (DocNode * root, QList< DocNode > & children) static
Definition at line 2539 of file docparser.cpp.
References CompAccept< T >::children(), DocNode::kind(), DocNode::Kind_Para, and DocNode::setParent().
Referenced by DocRef::parse().
handleAHref()
static int handleAHref (DocNode * parent, QList< DocNode > & children, const HtmlAttribList & tagHtmlAttribs) static
Definition at line 983 of file docparser.cpp.
References doctokenizerYYlineno, g_fileName, g_insideHtmlLink, g_relPath, HtmlAttrib::name, DocHRef::parse(), RetVal_OK, HtmlAttrib::value, and warn_doc_error().
Referenced by DocPara::handleHtmlStartTag(), DocHtmlHeader::parse(), and DocHtmlDescTitle::parse().
handleAnchor()
static DocAnchor* handleAnchor (DocNode * parent) static
Definition at line 1220 of file docparser.cpp.
References doctokenizerYYlex(), doctokenizerYYlineno, doctokenizerYYsetStateAnchor(), doctokenizerYYsetStatePara(), g_fileName, g_token, TokenInfo::name, TK_LNKWORD, TK_WHITESPACE, TK_WORD, tokToString(), and warn_doc_error().
Referenced by defaultHandleToken(), and DocPara::handleCommand().
handleImg()
static void handleImg (DocNode * parent, QList< DocNode > & children, const HtmlAttribList & tagHtmlAttribs) static
Definition at line 1686 of file docparser.cpp.
References doctokenizerYYlineno, g_fileName, DocImage::Html, HtmlAttrib::name, HtmlAttrib::value, and warn_doc_error().
Referenced by DocPara::handleHtmlStartTag().
handleInitialStyleCommands()
static void handleInitialStyleCommands (DocPara * parent, QList< DocNode > & children) static
Definition at line 974 of file docparser.cpp.
References DocStyleChange::attribs(), g_initialStyleStack, handleStyleEnter(), and DocStyleChange::style().
Referenced by DocPara::parse().
handleInternalRef()
static DocInternalRef* handleInternalRef (DocNode * parent) static
Definition at line 1198 of file docparser.cpp.
References doctokenizerYYlex(), doctokenizerYYlineno, doctokenizerYYsetStateInternalRef(), g_fileName, g_token, TokenInfo::name, TK_LNKWORD, TK_WHITESPACE, TK_WORD, tokToString(), and warn_doc_error().
Referenced by defaultHandleToken(), and DocPara::handleCommand().
handleLinkedWord()
static void handleLinkedWord (DocNode * parent, QList< DocNode > & children, bool ignoreAutoLinkFlag = FALSE) static
Definition at line 1056 of file docparser.cpp.
References MemberDef::anchor(), Definition::anchor(), ClassDef::anchor(), Definition::briefDescriptionAsTooltip(), Config_getBool, DefinitionIntf::definitionType(), doctokenizerYYlineno, findFileDef(), g_context, g_fileName, g_inSeeBlock, g_insideHtmlLink, g_token, getClass(), MemberDef::getClassDef(), MemberDef::getOutputFileBase(), ClassDef::getOutputFileBase(), Definition::getOutputFileBase(), MemberDef::getReference(), ClassDef::getReference(), Definition::getReference(), Doxygen::inputNameDict, MemberDef::isLinkable(), Definition::isLinkable(), MemberDef::isObjCMethod(), linkToText(), TokenInfo::name, MemberDef::objCMethodName(), resolveRef(), SrcLangExt_Unknown, DefinitionIntf::TypeFile, DefinitionIntf::TypeGroup, and warn_doc_error().
Referenced by defaultHandleToken(), DocPara::handleHtmlStartTag(), handleParameterType(), DocPara::parse(), DocParamList::parse(), and DocParamList::parseXml().
handleParameterType()
static void handleParameterType (DocNode * parent, QList< DocNode > & children, const QCString & paramTypes) static
Definition at line 1183 of file docparser.cpp.
References g_token, handleLinkedWord(), and TokenInfo::name.
Referenced by DocParamList::parse().
handlePendingStyleCommands()
static void handlePendingStyleCommands (DocNode * parent, QList< DocNode > & children) static
Called at the end of a paragraph to close all open style changes (e.g. a without a). The closed styles are pushed onto a stack and entered again at the start of a new paragraph.
Definition at line 959 of file docparser.cpp.
References g_initialStyleStack, g_nodeStack, g_styleStack, DocStyleChange::position(), and DocStyleChange::style().
Referenced by defaultHandleTitleAndSize(), DocTitle::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocSecRefItem::parse(), DocPara::parse(), and DocHtmlCaption::parse().
handleStyleArgument()
static int handleStyleArgument (DocNode * parent, QList< DocNode > & children, const QCString & cmdName) static
Definition at line 850 of file docparser.cpp.
References DBG, defaultHandleToken(), doctokenizerYYlex(), doctokenizerYYlineno, TokenInfo::endTag, g_fileName, g_token, Mappers::htmlTagMapper, insideLI(), TokenInfo::name, RetVal_OK, TK_COMMAND, TK_ENDLIST, TK_HTMLTAG, TK_LISTITEM, TK_NEWPARA, TK_SYMBOL, TK_WHITESPACE, TK_WORD, tokToString(), and warn_doc_error().
Referenced by defaultHandleToken(), and DocPara::handleCommand().
handleStyleEnter()
static void handleStyleEnter (DocNode * parent, QList< DocNode > & children, DocStyleChange::Style s, const HtmlAttribList * attribs) static
Called when a style change starts. For instance a <b> command is encountered.
Definition at line 910 of file docparser.cpp.
References DBG, g_nodeStack, and g_styleStack.
Referenced by defaultHandleToken(), DocPara::handleHtmlStartTag(), and handleInitialStyleCommands().
handleStyleLeave()
static void handleStyleLeave (DocNode * parent, QList< DocNode > & children, DocStyleChange::Style s, const char * tagName) static
Called when a style change ends. For instance a </b> command is encountered.
Definition at line 922 of file docparser.cpp.
References DBG, doctokenizerYYlineno, g_fileName, g_nodeStack, g_styleStack, and warn_doc_error().
Referenced by defaultHandleToken(), and DocPara::handleHtmlEndTag().
handleUnclosedStyleCommands()
static void handleUnclosedStyleCommands () static
Definition at line 1043 of file docparser.cpp.
References doctokenizerYYlineno, g_fileName, g_initialStyleStack, DocStyleChange::styleString(), and warn_doc_error().
Referenced by DocText::parse(), and DocRoot::parse().
insideLI()
static bool insideLI (DocNode * n) static
Returns TRUE iff node n is a child of a html list item node
Definition at line 659 of file docparser.cpp.
References DocNode::kind(), DocNode::Kind_HtmlListItem, and DocNode::parent().
Referenced by DocPara::handleHtmlEndTag(), and handleStyleArgument().
insideOL()
static bool insideOL (DocNode * n) static
Returns TRUE iff node n is a child of a ordered html list node
Definition at line 686 of file docparser.cpp.
References DocNode::kind(), DocNode::Kind_HtmlList, and DocHtmlList::Ordered.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
insidePRE()
static bool insidePRE (DocNode * n) static
Returns TRUE iff node n is a child of a preformatted node
Definition at line 646 of file docparser.cpp.
References DocNode::isPreformatted(), and DocNode::parent().
Referenced by defaultHandleToken(), and DocPara::parse().
insideTable()
static bool insideTable (DocNode * n) static
Definition at line 699 of file docparser.cpp.
References DocNode::kind(), DocNode::Kind_HtmlTable, and DocNode::parent().
Referenced by DocPara::handleHtmlStartTag().
insideUL()
static bool insideUL (DocNode * n) static
Returns TRUE iff node n is a child of a unordered html list node
Definition at line 672 of file docparser.cpp.
References DocNode::kind(), DocNode::Kind_HtmlList, and DocHtmlList::Unordered.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
internalValidatingParseDoc()
static int internalValidatingParseDoc (DocNode * parent, QList< DocNode > & children, const QCString & doc) static
Definition at line 1723 of file docparser.cpp.
References doctokenizerYYinit(), g_fileName, DocPara::isEmpty(), DocNode::Kind_Para, DocPara::markFirst(), DocPara::markLast(), DocPara::parse(), RetVal_OK, and TK_NEWPARA.
Referenced by DocPara::handleInclude(), DocPara::handleInheritDoc(), DocCopy::parse(), DocXRefItem::parse(), DocRef::parse(), and DocSimpleSect::parseRcs().
isCopyBriefOrDetailsCmd()
static uint isCopyBriefOrDetailsCmd (const char * data, uint i, uint len, bool & brief) static
Definition at line 7089 of file docparser.cpp.
References CHECK_FOR_COMMAND.
Referenced by processCopyDoc().
isVerbatimSection()
static uint isVerbatimSection (const char * data, uint i, uint len, QCString & endMarker) static
Definition at line 7100 of file docparser.cpp.
References CHECK_FOR_COMMAND.
Referenced by processCopyDoc().
processCopyDoc()
static QCString processCopyDoc (const char * data, uint & len) static
Definition at line 7139 of file docparser.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), brief, doc, doctokenizerYYlineno, extractCopyDocId(), findDocsForMemberOrCompound(), g_copyStack, g_fileName, GrowBuf::get(), GrowBuf::getPos(), isCopyBriefOrDetailsCmd(), isVerbatimSection(), skipToEndMarker(), and warn_doc_error().
Referenced by validatingParseDoc().
readTextFileByName()
static void readTextFileByName (const QCString & file, QCString & text) static
Definition at line 1766 of file docparser.cpp.
References FileDef::absFilePath(), Config_getBool, Config_getList, doctokenizerYYlineno, Doxygen::exampleNameDict, fileToString(), findFileDef(), g_fileName, portable_isAbsolutePath(), portable_pathSeparator(), showFileDefMatches(), and warn_doc_error().
Referenced by DocPara::handleInclude(), and DocInclude::parse().
skipToEndMarker()
static uint skipToEndMarker (const char * data, uint i, uint len, const QCString & endMarker) static
Definition at line 7121 of file docparser.cpp.
Referenced by processCopyDoc().
stripKnownExtensions()
static QCString stripKnownExtensions (const char * text) static
Strips known html and tex extensions from text.
Definition at line 627 of file docparser.cpp.
References Doxygen::htmlFileExtension.
Referenced by DocLink::DocLink(), and DocRef::DocRef().
unescapeCRef()
static void unescapeCRef (QCString & s) static
Definition at line 239 of file docparser.cpp.
References substitute().
Referenced by DocPara::handleHtmlStartTag().
validatingParseDoc()
DocRoot* validatingParseDoc (const char * fileName, int startLine, Definition * context, MemberDef * md, const char * input, bool indexWords, bool isExample, const char * exampleName = 0, bool singleLine = FALSE, bool linkFromIndex = FALSE)
Main entry point for the documentation parser.
Parameters
fileName File in which the documentation block is found (or the name of the example file in case isExample is TRUE).
startLine Line at which the documentation block is found.
context Class or namespace to which this block belongs.
md Member definition to which the documentation belongs. Can be 0.
input String representation of the documentation block.
indexWords Indicates whether or not words should be put in the search index.
isExample TRUE if the documentation belongs to an example.
exampleName Base name of the example file (0 if isExample is FALSE).
singleLine Output should be presented on a single line, so without starting a new paragraph at the end.
linkFromIndex TRUE if the documentation is generated from an index page. In this case context is not used to determine the relative path when making a link.
Returns
Root node of the abstract syntax tree. Ownership of the pointer is handed over to the caller.
Definition at line 7224 of file docparser.cpp.
References DocRoot::accept(), MemberDef::anchor(), Definition::anchor(), checkUndocumentedParams(), ClassDef::compoundTypeString(), DefinitionIntf::definitionType(), detectNoDocumentedParams(), docParserPopContext(), docParserPushContext(), doctokenizerYYinit(), doctokenizerYYlineno, g_context, g_exampleName, g_fileName, g_hasParamCommand, g_hasReturnCommand, g_includeFileLength, g_includeFileOffset, g_includeFileText, g_initialStyleStack, g_inSeeBlock, g_insideHtmlLink, g_isExample, g_nodeStack, g_paramsFound, g_relPath, g_searchUrl, g_styleStack, g_xmlComment, Definition::getLanguage(), getLanguageSpecificSeparator(), MemberDef::getOutputFileBase(), Definition::getOutputFileBase(), Doxygen::globalScope, GroupDef::groupTitle(), Debug::isFlagSet(), Definition::name(), DocRoot::parse(), Debug::PrintTree, processCopyDoc(), MemberDef::qualifiedName(), Definition::qualifiedName(), relativePathToRoot(), Doxygen::searchIndex, SearchIndexIntf::setCurrentDoc(), SrcLangExt_CSharp, SrcLangExt_Fortran, SrcLangExt_Java, substitute(), theTranslator, PageDef::title(), Translator::trGroup(), Translator::trMember(), Translator::trModule(), Translator::trNamespace(), Translator::trPackage(), Translator::trPage(), Translator::trSubprogram(), DefinitionIntf::TypeClass, DefinitionIntf::TypeGroup, DefinitionIntf::TypeNamespace, and DefinitionIntf::TypePage.
Referenced by addPerlModDocBlock(), generateBriefDoc(), OutputList::generateDoc(), parseCommentAsText(), parseDoc(), DirDef::writeBriefDescription(), NamespaceDef::writeBriefDescription(), GroupDef::writeBriefDescription(), FileDef::writeBriefDescription(), MemberDef::writeDeclaration(), ClassDef::writeDeclarationLink(), writeDocbookDocBlock(), MemberList::writePlainDeclarations(), and writeXMLDocBlock().
validatingParseText()
DocText* validatingParseText (const char * input)
Main entry point for parsing simple text fragments. These fragments are limited to words, whitespace and symbols.
Definition at line 7426 of file docparser.cpp.
References DocText::accept(), docParserPopContext(), docParserPushContext(), doctokenizerYYinit(), doctokenizerYYlineno, g_context, g_exampleName, g_fileName, g_hasParamCommand, g_hasReturnCommand, g_includeFileLength, g_includeFileOffset, g_includeFileText, g_initialStyleStack, g_inSeeBlock, g_insideHtmlLink, g_isExample, g_nodeStack, g_paramsFound, g_relPath, g_searchUrl, g_styleStack, g_xmlComment, Debug::isFlagSet(), DocText::parse(), and Debug::PrintTree.
Referenced by RTFGenerator::endIndexSection(), and OutputList::parseText().
Variable Documentation
g_context
QCString g_context static
Definition at line 87 of file docparser.cpp.
Referenced by defaultHandleToken(), DocLink::DocLink(), docParserPopContext(), docParserPushContext(), findDocsForMemberOrCompound(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocPara::handleInheritDoc(), handleLinkedWord(), DocPara::handleRef(), DocPara::handleStartCode(), DocCopy::parse(), DocHtmlDescTitle::parse(), validatingParseDoc(), and validatingParseText().
g_copyStack
QList<Definition> g_copyStack static
Definition at line 94 of file docparser.cpp.
Referenced by docParserPopContext(), docParserPushContext(), DocPara::handleInheritDoc(), DocCopy::parse(), and processCopyDoc().
g_exampleName
QCString g_exampleName static
Definition at line 103 of file docparser.cpp.
Referenced by defaultHandleToken(), docParserPopContext(), docParserPushContext(), DocPara::handleCommand(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocPara::handleStartCode(), validatingParseDoc(), and validatingParseText().
g_fileName
QCString g_fileName static
Definition at line 95 of file docparser.cpp.
Referenced by defaultHandleTitleAndSize(), defaultHandleToken(), detectNoDocumentedParams(), DocAnchor::DocAnchor(), DocCite::DocCite(), DocFormula::DocFormula(), DocHtmlCaption::DocHtmlCaption(), DocLink::DocLink(), docParserPopContext(), docParserPushContext(), DocRef::DocRef(), findAndCopyImage(), handleAHref(), handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocPara::handleImage(), handleImg(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), handleInternalRef(), DocPara::handleLink(), handleLinkedWord(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleStartCode(), handleStyleArgument(), handleStyleLeave(), handleUnclosedStyleCommands(), internalValidatingParseDoc(), DocInclude::parse(), DocIndexEntry::parse(), DocCopy::parse(), DocTitle::parse(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocInternal::parse(), DocHtmlList::parse(), DocPara::parse(), DocParamList::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocText::parse(), DocRoot::parse(), DocHtmlList::parseXml(), DocParamList::parseXml(), DocHtmlRow::parseXml(), processCopyDoc(), readTextFileByName(), validatingParseDoc(), and validatingParseText().
g_hasParamCommand
bool g_hasParamCommand static
Definition at line 98 of file docparser.cpp.
Referenced by checkUndocumentedParams(), detectNoDocumentedParams(), docParserPopContext(), docParserPushContext(), DocCopy::parse(), DocParamList::parse(), DocParamList::parseXml(), validatingParseDoc(), and validatingParseText().
g_hasReturnCommand
bool g_hasReturnCommand static
Definition at line 99 of file docparser.cpp.
Referenced by detectNoDocumentedParams(), docParserPopContext(), docParserPushContext(), DocPara::handleCommand(), DocPara::handleHtmlStartTag(), DocCopy::parse(), DocParamList::parse(), DocParamList::parseXml(), validatingParseDoc(), and validatingParseText().
g_includeFileLength
uint g_includeFileLength static
Definition at line 109 of file docparser.cpp.
Referenced by docParserPopContext(), docParserPushContext(), DocInclude::parse(), DocIncOperator::parse(), validatingParseDoc(), and validatingParseText().
g_includeFileOffset
uint g_includeFileOffset static
Definition at line 108 of file docparser.cpp.
Referenced by docParserPopContext(), docParserPushContext(), DocInclude::parse(), DocIncOperator::parse(), validatingParseDoc(), and validatingParseText().
g_includeFileText
QCString g_includeFileText static
Definition at line 107 of file docparser.cpp.
Referenced by docParserPopContext(), docParserPushContext(), DocInclude::parse(), DocIncOperator::parse(), validatingParseDoc(), and validatingParseText().
g_initialStyleStack
QStack<DocStyleChange> g_initialStyleStack static
Definition at line 93 of file docparser.cpp.
Referenced by docParserPopContext(), docParserPushContext(), handleInitialStyleCommands(), handlePendingStyleCommands(), handleUnclosedStyleCommands(), validatingParseDoc(), and validatingParseText().
g_inSeeBlock
bool g_inSeeBlock static
Definition at line 88 of file docparser.cpp.
Referenced by DocSimpleSect::appendLinkWord(), DocLink::DocLink(), docParserPopContext(), docParserPushContext(), DocRef::DocRef(), DocPara::handleCommand(), DocPara::handleHtmlStartTag(), handleLinkedWord(), validatingParseDoc(), and validatingParseText().
g_insideHtmlLink
bool g_insideHtmlLink static
Definition at line 90 of file docparser.cpp.
Referenced by defaultHandleToken(), docParserPopContext(), docParserPushContext(), handleAHref(), handleLinkedWord(), DocRef::parse(), validatingParseDoc(), and validatingParseText().
g_isExample
bool g_isExample static
Definition at line 102 of file docparser.cpp.
Referenced by defaultHandleToken(), docParserPopContext(), docParserPushContext(), DocPara::handleCommand(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocPara::handleStartCode(), validatingParseDoc(), and validatingParseText().
g_memberDef
MemberDef* g_memberDef static
Definition at line 101 of file docparser.cpp.
Referenced by docParserPushContext(), and DocPara::handleInheritDoc().
g_nodeStack
QStack<DocNode> g_nodeStack static
Definition at line 91 of file docparser.cpp.
Referenced by defaultHandleTitleAndSize(), defaultHandleToken(), docParserPopContext(), docParserPushContext(), DocPara::handleCommand(), DocPara::handleHtmlStartTag(), DocPara::handleInheritDoc(), handlePendingStyleCommands(), handleStyleEnter(), handleStyleLeave(), DocIndexEntry::parse(), DocCopy::parse(), DocAutoList::parse(), DocAutoListItem::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocInternal::parse(), DocParBlock::parse(), DocSimpleList::parse(), DocHtmlList::parse(), DocSimpleSect::parse(), DocParamSect::parse(), DocPara::parse(), DocParamList::parse(), DocSimpleListItem::parse(), DocHtmlListItem::parse(), DocHtmlDescData::parse(), DocHtmlCell::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlBlockQuote::parse(), DocText::parse(), DocRoot::parse(), DocSimpleSect::parseRcs(), DocHtmlList::parseXml(), DocSimpleSect::parseXml(), DocParamList::parseXml(), DocHtmlListItem::parseXml(), DocHtmlCell::parseXml(), DocHtmlRow::parseXml(), DocHtmlTable::parseXml(), validatingParseDoc(), and validatingParseText().
g_paramsFound
QDict<void> g_paramsFound static
Definition at line 100 of file docparser.cpp.
Referenced by checkArgumentName(), checkUndocumentedParams(), docParserPopContext(), docParserPushContext(), DocCopy::parse(), validatingParseDoc(), and validatingParseText().
g_parserStack
QStack<DocParserContext> g_parserStack static
Definition at line 145 of file docparser.cpp.
Referenced by docParserPopContext(), and docParserPushContext().
g_relPath
QCString g_relPath static
Definition at line 96 of file docparser.cpp.
Referenced by DocCite::DocCite(), DocLink::DocLink(), docParserPopContext(), docParserPushContext(), DocRef::DocRef(), handleAHref(), validatingParseDoc(), and validatingParseText().
g_scope
Definition* g_scope static
Definition at line 86 of file docparser.cpp.
Referenced by docParserPushContext().
g_searchUrl
QCString g_searchUrl static
Definition at line 105 of file docparser.cpp.
Referenced by DocLinkedWord::DocLinkedWord(), docParserPopContext(), docParserPushContext(), DocWord::DocWord(), validatingParseDoc(), and validatingParseText().
g_sectionDict
SectionDict* g_sectionDict static
Definition at line 104 of file docparser.cpp.
Referenced by docParserPushContext().
g_styleStack
QStack<DocStyleChange> g_styleStack static
Definition at line 92 of file docparser.cpp.
Referenced by docParserPopContext(), docParserPushContext(), DocPara::handleInheritDoc(), handlePendingStyleCommands(), handleStyleEnter(), handleStyleLeave(), DocCopy::parse(), validatingParseDoc(), and validatingParseText().
g_xmlComment
bool g_xmlComment static
Definition at line 89 of file docparser.cpp.
Referenced by docParserPopContext(), docParserPushContext(), DocPara::handleHtmlStartTag(), DocPara::handleStartCode(), validatingParseDoc(), and validatingParseText().
sectionLevelToName
const char* sectionLevelToName[] static
Initial value:
=
{
  "page",
  "section",
  "subsection",
  "subsubsection",
  "paragraph",
  "subparagraph"
}
Definition at line 73 of file docparser.cpp.
Referenced by DocSection::parse().