Doxygen: TemplateStruct Class Reference
TemplateStruct Class Reference
Template API
Default implementation of a context value of type struct.
#include <template.h>
Classes
class Private
Private data of a template struct object.
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
virtual void set (const char *name, const TemplateVariant &v)
Sets the value the field of a struct.
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static TemplateStruct * alloc ()
Creates an instance with ref count set to 0.
Private Member Functions
TemplateStruct ()
Creates a struct.
virtual ~TemplateStruct ()
Destroys the struct.
Private Attributes
Private * p
Detailed Description
Default implementation of a context value of type struct.
Definition at line 426 of file template.h.
Constructor & Destructor Documentation
TemplateStruct()
TemplateStruct::TemplateStruct () private
Creates a struct.
Definition at line 251 of file template.cpp.
References p, and Private.
Referenced by alloc().
~TemplateStruct()
TemplateStruct::~TemplateStruct () private virtual
Destroys the struct.
Definition at line 256 of file template.cpp.
References p.
Member Function Documentation
addRef()
int TemplateStruct::addRef () virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 261 of file template.cpp.
References p, and TemplateStruct::Private::refCount.
alloc()
TemplateStruct * TemplateStruct::alloc () static
Creates an instance with ref count set to 0.
Definition at line 295 of file template.cpp.
References TemplateStruct().
Referenced by ClassContext::Private::addExamples(), MemberContext::Private::addExamples(), TemplateContextImpl::addIndexEntry(), FilterAlphaIndex::apply(), DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeBlock::render(), and TemplateNodeMarkers::render().
get()
TemplateVariant TemplateStruct::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 289 of file template.cpp.
References TemplateStruct::Private::fields, and p.
release()
int TemplateStruct::release () virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 266 of file template.cpp.
References p, and TemplateStruct::Private::refCount.
set()
void TemplateStruct::set (const char * name, const TemplateVariant & v) virtual
Sets the value the field of a struct.
Parameters
[in] name The name of the field.
[in] v The value to set.
Definition at line 276 of file template.cpp.
References TemplateStruct::Private::fields, and p.
Referenced by ClassContext::Private::addExamples(), MemberContext::Private::addExamples(), TemplateContextImpl::addIndexEntry(), FilterAlphaIndex::apply(), DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), TemplateContextImpl::closeSubIndex(), TemplateContextImpl::openSubIndex(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeBlock::render(), and TemplateNodeMarkers::render().
Member Data Documentation
p
Private* TemplateStruct::p private
Definition at line 450 of file template.h.
Referenced by addRef(), get(), release(), set(), TemplateStruct(), and ~TemplateStruct().
The documentation for this class was generated from the following files:
src/template.h
src/template.cpp