Doxygen: InheritanceNodeContext Class Reference
InheritanceNodeContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static InheritanceNodeContext * alloc (ClassDef *cd, const QCString &name)
Private Member Functions
InheritanceNodeContext (ClassDef *cd, const QCString &name)
~InheritanceNodeContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 909 of file context.h.
Constructor & Destructor Documentation
InheritanceNodeContext()
InheritanceNodeContext::InheritanceNodeContext (ClassDef * cd, const QCString & name) private
Definition at line 8416 of file context.cpp.
References p, and Private.
Referenced by alloc().
~InheritanceNodeContext()
InheritanceNodeContext::~InheritanceNodeContext () private
Definition at line 8421 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int InheritanceNodeContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 917 of file context.h.
References RefCountedContext::addRef().
alloc()
static InheritanceNodeContext* InheritanceNodeContext::alloc (ClassDef * cd, const QCString & name) inline static
Definition at line 912 of file context.h.
References InheritanceNodeContext().
Referenced by InheritanceListContext::Private::addClass().
get()
TemplateVariant InheritanceNodeContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 8426 of file context.cpp.
References InheritanceNodeContext::Private::get(), and p.
release()
virtual int InheritanceNodeContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 918 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* InheritanceNodeContext::p private
Definition at line 923 of file context.h.
Referenced by get(), InheritanceNodeContext(), and ~InheritanceNodeContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp