Doxygen: TemplateNodeWith Class Reference
TemplateNodeWith Class Reference
Class representing an 'with' tag in a template.
Classes
struct Mapping
Public Member Functions
TemplateNodeWith (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeWith ()
void render (FTextStream &ts, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeWith >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Private Attributes
TemplateNodeList m_nodes
QList< Mapping > m_args
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeWith >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeWith >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeWith >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'with' tag in a template.
Definition at line 3994 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeWith()
TemplateNodeWith::TemplateNodeWith (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 4004 of file template.cpp.
References m_args, m_nodes, TemplateParser::parse(), ExpressionParser::parse(), TemplateParser::removeNextToken(), removeSpacesAroundEquals(), split(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
~TemplateNodeWith()
TemplateNodeWith::~TemplateNodeWith () inline
Definition at line 4037 of file template.cpp.
Member Function Documentation
render()
void TemplateNodeWith::render (FTextStream & ts, TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 4040 of file template.cpp.
References m_args, TemplateNodeCreator< TemplateNodeWith >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeWith >::m_templateName, TemplateNodeWith::Mapping::name, TemplateContext::pop(), TemplateContext::push(), TemplateNodeList::render(), ExprAst::resolve(), TemplateContextImpl::set(), TemplateContextImpl::setLocation(), and TemplateNodeWith::Mapping::value.
Member Data Documentation
m_args
QList<Mapping> TemplateNodeWith::m_args private
Definition at line 4058 of file template.cpp.
Referenced by render(), and TemplateNodeWith().
m_nodes
TemplateNodeList TemplateNodeWith::m_nodes private
Definition at line 4057 of file template.cpp.
Referenced by render(), and TemplateNodeWith().
The documentation for this class was generated from the following file:
src/template.cpp