Doxygen: TextGeneratorFactory Class Reference
TextGeneratorFactory Class Reference
Public Member Functions
TextGeneratorIntf * create (FTextStream &ts, const QCString &relPath)
Static Public Member Functions
static TextGeneratorFactory * instance ()
Private Member Functions
TextGeneratorFactory ()
virtual ~TextGeneratorFactory ()
Detailed Description
Definition at line 3829 of file context.cpp.
Constructor & Destructor Documentation
TextGeneratorFactory()
TextGeneratorFactory::TextGeneratorFactory () inline private
Definition at line 3852 of file context.cpp.
Referenced by instance().
~TextGeneratorFactory()
virtual TextGeneratorFactory::~TextGeneratorFactory () inline private virtual
Definition at line 3853 of file context.cpp.
Member Function Documentation
create()
TextGeneratorIntf* TextGeneratorFactory::create (FTextStream & ts, const QCString & relPath) inline
Definition at line 3838 of file context.cpp.
References ContextOutputFormat_Html, ContextOutputFormat_Latex, g_globals, and ContextGlobals::outputFormat.
Referenced by createLinkedText().
instance()
static TextGeneratorFactory* TextGeneratorFactory::instance () inline static
Definition at line 3832 of file context.cpp.
References TextGeneratorFactory().
Referenced by createLinkedText().
The documentation for this class was generated from the following file:
src/context.cpp