Doxygen: SearchDefinitionList Class Reference
SearchDefinitionList Class Reference
#include <searchindex.h>
Public Member Functions
SearchDefinitionList (const QCString &id, const QCString &name)
QCString id () const
QCString name () const
Private Attributes
QCString m_id
QCString m_name
Detailed Description
Definition at line 132 of file searchindex.h.
Constructor & Destructor Documentation
SearchDefinitionList()
SearchDefinitionList::SearchDefinitionList (const QCString & id, const QCString & name) inline
Definition at line 135 of file searchindex.h.
Member Function Documentation
id()
QCString SearchDefinitionList::id () const inline
Definition at line 136 of file searchindex.h.
References m_id.
Referenced by SymbolGroupContext::Private::id(), and writeJavascriptSearchIndex().
name()
QCString SearchDefinitionList::name () const inline
Definition at line 137 of file searchindex.h.
References m_name.
Referenced by SymbolGroupContext::Private::name(), and writeJavascriptSearchIndex().
Member Data Documentation
m_id
QCString SearchDefinitionList::m_id private
Definition at line 139 of file searchindex.h.
Referenced by id().
m_name
QCString SearchDefinitionList::m_name private
Definition at line 140 of file searchindex.h.
Referenced by name().
The documentation for this class was generated from the following file:
src/searchindex.h