Doxygen: SymbolIndicesContext Class Reference
SymbolIndicesContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static SymbolIndicesContext * alloc (const SearchIndexInfo *info)
Private Member Functions
SymbolIndicesContext (const SearchIndexInfo *info)
~SymbolIndicesContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1286 of file context.h.
Constructor & Destructor Documentation
SymbolIndicesContext()
SymbolIndicesContext::SymbolIndicesContext (const SearchIndexInfo * info) private
Definition at line 9822 of file context.cpp.
References p, and Private.
Referenced by alloc().
~SymbolIndicesContext()
SymbolIndicesContext::~SymbolIndicesContext () private
Definition at line 9827 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int SymbolIndicesContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 1296 of file context.h.
References RefCountedContext::addRef().
alloc()
static SymbolIndicesContext* SymbolIndicesContext::alloc (const SearchIndexInfo * info) inline static
Definition at line 1289 of file context.h.
References SymbolIndicesContext().
Referenced by SearchIndexContext::Private::symbolIndices().
at()
TemplateVariant SymbolIndicesContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 9838 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int SymbolIndicesContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 9833 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * SymbolIndicesContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 9843 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int SymbolIndicesContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 1297 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* SymbolIndicesContext::p private
Definition at line 1302 of file context.h.
Referenced by at(), count(), createIterator(), SymbolIndicesContext(), and ~SymbolIndicesContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp