Doxygen: RTFGenerator Class Reference
RTFGenerator Class Reference
Generator for RTF output.
#include <rtfgen.h>
Public Member Functions
RTFGenerator ()
~RTFGenerator ()
void enable ()
void disable ()
void enableIf (OutputType o)
void disableIf (OutputType o)
void disableIfNot (OutputType o)
bool isEnabled (OutputType o)
OutputGenerator * get (OutputType o)
void writeDoc (DocNode *, Definition *, MemberDef *)
void startFile (const char *name, const char *manName, const char *title)
void writeSearchInfo ()
void writeFooter (const char *)
void endFile ()
void clearBuffer ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const char *, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startTitleHead (const char *)
void startTitle ()
void endTitleHead (const char *, const char *name)
void endTitle ()
void newParagraph ()
void startParagraph (const char *classDef)
void endParagraph ()
void writeString (const char *text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const char *, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const char *ref, const char *file)
void endIndexItem (const char *ref, const char *file)
void docify (const char *text)
void codify (const char *text)
void writeObjectLink (const char *ref, const char *file, const char *anchor, const char *name)
void writeCodeLink (const char *ref, const char *file, const char *anchor, const char *name, const char *tooltip)
void writeTooltip (const char *, const DocLinkInfo &, const char *, const char *, const SourceLinkInfo &, const SourceLinkInfo &)
void startTextLink (const char *f, const char *anchor)
void endTextLink ()
void startHtmlLink (const char *url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const char *)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const char *, int, const char *)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const char *, const char *)
void insertMemberAlign (bool)
void writeRuler ()
void writeAnchor (const char *fileName, const char *name)
void startCodeFragment ()
void endCodeFragment ()
void writeLineNumber (const char *, const char *, const char *, int l)
void startCodeLine (bool)
void endCodeLine ()
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void lineBreak (const char *style=0)
void startMemberDoc (const char *, const char *, const char *, const char *, int, int, bool)
void endMemberDoc (bool)
void startDoxyAnchor (const char *, const char *, const char *, const char *, const char *)
void endDoxyAnchor (const char *, const char *)
void writeChar (char c)
void writeLatexSpacing ()
void writeStartAnnoItem (const char *type, const char *file, const char *path, const char *name)
void writeEndAnnoItem (const char *name)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startMemberDescription (const char *, const char *)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const char *, const char *)
void writeInheritedSectionTitle (const char *, const char *, const char *, const char *, const char *, const char *)
void startDescList (SectionTypes)
void startSimpleSect (SectionTypes, const char *, const char *, const char *)
void endSimpleSect ()
void startParamList (ParamListTypes, const char *)
void endParamList ()
void startDescForItem ()
void endDescForItem ()
void startSection (const char *, const char *, SectionInfo::SectionType)
void endSection (const char *, SectionInfo::SectionType)
void addIndexItem (const char *, const char *)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const char *filename, const char *name)
void startPageRef ()
void endPageRef (const char *, const char *)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const char *)
void writeNavigationPath (const char *)
void writeLogo ()
void writeQuickLinks (bool, HighlightedItem, const char *)
void writeSummaryLink (const char *, const char *, const char *, bool)
void startContents ()
void endContents ()
void writeNonBreakableSpace (int)
void startDescTable (const char *title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (const DotClassGraph &)
void startInclDepGraph ()
void endInclDepGraph (const DotInclDepGraph &)
void startGroupCollaboration ()
void endGroupCollaboration (const DotGroupCollaboration &g)
void startCallGraph ()
void endCallGraph (const DotCallGraph &)
void startDirDepGraph ()
void endDirDepGraph (const DotDirDeps &g)
void writeGraphicalHierarchy (const DotGfxHierarchyTable &)
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void startTextBlock (bool dense)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool, const char *)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool, bool, bool)
void startParameterList (bool)
void endParameterList ()
void exceptionEntry (const char *, bool)
void startConstraintList (const char *)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const char *l, bool isLast)
void endLabels ()
void startFontClass (const char *)
void endFontClass ()
void writeCodeAnchor (const char *)
void setCurrentDoc (Definition *, const char *, bool)
void addWord (const char *, bool)
Public Member Functions inherited from OutputGenerator
OutputGenerator ()
virtual ~OutputGenerator ()
void startPlainFile (const char *name)
void endPlainFile ()
bool isEnabled () const
void pushGeneratorState ()
void popGeneratorState ()
Public Member Functions inherited from BaseOutputDocInterface
virtual ~BaseOutputDocInterface ()
virtual bool parseText (const QCString &s)
Public Member Functions inherited from CodeOutputInterface
virtual ~CodeOutputInterface ()
Static Public Member Functions
static void init ()
static void writeStyleSheetFile (QFile &f)
static void writeExtensionsFile (QFile &file)
static bool preProcessFileInplace (const char *path, const char *name)
This is an API to a VERY brittle RTF preprocessor that combines nested RTF files.
Private Member Functions
RTFGenerator (const RTFGenerator &)
RTFGenerator & operator= (const RTFGenerator &)
const char * rtf_BList_DepthStyle ()
const char * rtf_CList_DepthStyle ()
const char * rtf_EList_DepthStyle ()
const char * rtf_LCList_DepthStyle ()
const char * rtf_DList_DepthStyle ()
const char * rtf_Code_DepthStyle ()
void incrementIndentLevel ()
void decrementIndentLevel ()
void beginRTFDocument ()
void beginRTFChapter ()
void beginRTFSection ()
void rtfwriteRuler_doubleline ()
void rtfwriteRuler_emboss ()
void rtfwriteRuler_thick ()
void rtfwriteRuler_thin ()
void writeRTFReference (const char *label)
Private Attributes
int col
bool m_prettyCode
bool m_bstartedBody
int m_listLevel
bool m_omitParagraph
int m_numCols
QCString relPath
Additional Inherited Members
Public Types inherited from OutputGenerator
enum OutputType {
Html, Latex, Man, RTF,
XML, DEF, Perl
}
Public Types inherited from BaseOutputDocInterface
enum ParamListTypes { Param, RetVal, Exception }
enum SectionTypes { EnumValues, Examples }
Protected Attributes inherited from OutputGenerator
FTextStream t
QFile * file
QCString fileName
QCString dir
bool active
QStack< bool > * genStack
Detailed Description
Generator for RTF output.
Definition at line 26 of file rtfgen.h.
Constructor & Destructor Documentation
RTFGenerator() [1/2]
RTFGenerator::RTFGenerator ()
Definition at line 60 of file rtfgen.cpp.
References col, Config_getBool, Config_getString, OutputGenerator::dir, m_bstartedBody, m_listLevel, m_numCols, m_omitParagraph, and m_prettyCode.
~RTFGenerator()
RTFGenerator::~RTFGenerator ()
Definition at line 72 of file rtfgen.cpp.
RTFGenerator() [2/2]
RTFGenerator::RTFGenerator (const RTFGenerator &) private
Member Function Documentation
addIndexItem()
void RTFGenerator::addIndexItem (const char * s1, const char * s2) virtual
Implements BaseOutputDocInterface.
Definition at line 1571 of file rtfgen.cpp.
References docify(), endl(), and OutputGenerator::t.
Referenced by endTitleHead(), and startMemberDoc().
addWord()
void RTFGenerator::addWord (const char * , bool) inline virtual
Implements CodeOutputInterface.
Definition at line 265 of file rtfgen.h.
beginRTFChapter()
void RTFGenerator::beginRTFChapter () private
Definition at line 313 of file rtfgen.cpp.
References Config_getBool, DBG_RTF, rtf_Style, rtf_Style_Reset, rtfwriteRuler_thick(), and OutputGenerator::t.
Referenced by endIndexSection(), startIndexSection(), and startTitle().
beginRTFDocument()
void RTFGenerator::beginRTFDocument () private
Definition at line 212 of file rtfgen.cpp.
References Config_getEnum, DBG_RTF, StyleData::definition, endl(), StyleData::index, msg(), StyleData::reference, rtf_Style, OutputGenerator::t, theTranslator, Translator::trRTFansicp(), and Translator::trRTFCharSet().
Referenced by startFile().
beginRTFSection()
void RTFGenerator::beginRTFSection () private
Definition at line 333 of file rtfgen.cpp.
References Config_getBool, DBG_RTF, rtf_Style, rtf_Style_Reset, rtfwriteRuler_emboss(), and OutputGenerator::t.
Referenced by endIndexSection(), and startTitle().
clearBuffer()
void RTFGenerator::clearBuffer ()
codify()
void RTFGenerator::codify (const char * s) virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 1810 of file rtfgen.cpp.
References col, Config_getInt, newParagraph(), Doxygen::spaces, OutputGenerator::t, and writeUtf8Char().
Referenced by writeCodeLink().
decrementIndentLevel()
void RTFGenerator::decrementIndentLevel () private
Definition at line 2085 of file rtfgen.cpp.
References err(), and m_listLevel.
Referenced by endConstraintList(), endIndent(), endIndexList(), endItemList(), endMemberDescription(), endMemberGroup(), endParamList(), and endSimpleSect().
disable()
void RTFGenerator::disable () inline virtual
Implements OutputGenerator.
Definition at line 37 of file rtfgen.h.
References OutputGenerator::active.
Referenced by disableIf(), and disableIfNot().
disableIf()
void RTFGenerator::disableIf (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 39 of file rtfgen.h.
References disable(), and OutputGenerator::RTF.
disableIfNot()
void RTFGenerator::disableIfNot (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 40 of file rtfgen.h.
References disable(), and OutputGenerator::RTF.
docify()
void RTFGenerator::docify (const char * s) virtual
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 1765 of file rtfgen.cpp.
References m_omitParagraph, and OutputGenerator::t.
Referenced by addIndexItem(), endTitleHead(), startConstraintList(), startDescTable(), startParamList(), startSection(), startSimpleSect(), writeChar(), writeObjectLink(), and writeStartAnnoItem().
enable()
void RTFGenerator::enable () inline virtual
Implements OutputGenerator.
Definition at line 35 of file rtfgen.h.
References OutputGenerator::active, and OutputGenerator::genStack.
Referenced by enableIf().
enableIf()
void RTFGenerator::enableIf (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 38 of file rtfgen.h.
References enable(), and OutputGenerator::RTF.
endAnonTypeScope()
void RTFGenerator::endAnonTypeScope (int) inline virtual
Implements OutputGenerator.
Definition at line 117 of file rtfgen.h.
endBold()
void RTFGenerator::endBold () inline virtual
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 135 of file rtfgen.h.
References OutputGenerator::t.
Referenced by endInlineHeader(), endMemberDoc(), startConstraintList(), startParamList(), startSimpleSect(), and writeObjectLink().
endCallGraph()
void RTFGenerator::endCallGraph (const DotCallGraph & g) virtual
Implements OutputGenerator.
Definition at line 2538 of file rtfgen.cpp.
References Config_getString, DBG_RTF, endl(), EOF_Rtf, OutputGenerator::fileName, getDotImageExtension(), GOF_BITMAP, newParagraph(), relPath, rtf_Style_Reset, OutputGenerator::t, and DotCallGraph::writeGraph().
endCenter()
void RTFGenerator::endCenter () inline virtual
Implements BaseOutputDocInterface.
Definition at line 155 of file rtfgen.h.
References OutputGenerator::t.
endClassDiagram()
void RTFGenerator::endClassDiagram (const ClassDiagram & d, const char * filename, const char * name) virtual
Implements OutputGenerator.
Definition at line 1858 of file rtfgen.cpp.
References OutputGenerator::dir, endl(), newParagraph(), relPath, rtf_Style_Reset, OutputGenerator::t, and ClassDiagram::writeImage().
endCodeFragment()
void RTFGenerator::endCodeFragment () virtual
Ends a source code fragment
Implements BaseOutputDocInterface.
Definition at line 1929 of file rtfgen.cpp.
References DBG_RTF, endl(), m_omitParagraph, and OutputGenerator::t.
endCodeLine()
void RTFGenerator::endCodeLine () inline virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 131 of file rtfgen.h.
References lineBreak().
endConstraintDocs()
void RTFGenerator::endConstraintDocs () virtual
Implements OutputGenerator.
Definition at line 2905 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), and OutputGenerator::t.
endConstraintList()
void RTFGenerator::endConstraintList () virtual
Implements OutputGenerator.
Definition at line 2911 of file rtfgen.cpp.
References DBG_RTF, decrementIndentLevel(), endl(), m_omitParagraph, newParagraph(), and OutputGenerator::t.
endConstraintParam()
void RTFGenerator::endConstraintParam () virtual
Implements OutputGenerator.
Definition at line 2880 of file rtfgen.cpp.
References DBG_RTF, endEmphasis(), endl(), and OutputGenerator::t.
endConstraintType()
void RTFGenerator::endConstraintType () virtual
Implements OutputGenerator.
Definition at line 2893 of file rtfgen.cpp.
References DBG_RTF, endEmphasis(), endl(), and OutputGenerator::t.
endContents()
void RTFGenerator::endContents () inline virtual
Implements OutputGenerator.
Definition at line 191 of file rtfgen.h.
endDescForItem()
void RTFGenerator::endDescForItem () virtual
Implements BaseOutputDocInterface.
Definition at line 1673 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endDescItem()
void RTFGenerator::endDescItem () virtual
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 1622 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), and OutputGenerator::t.
endDescription()
void RTFGenerator::endDescription () virtual
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 1608 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), and OutputGenerator::t.
endDescTable()
void RTFGenerator::endDescTable () virtual
Implements BaseOutputDocInterface.
Definition at line 2035 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endDescTableData()
void RTFGenerator::endDescTableData () virtual
Implements BaseOutputDocInterface.
Definition at line 2067 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endDescTableRow()
void RTFGenerator::endDescTableRow () virtual
Implements BaseOutputDocInterface.
Definition at line 2045 of file rtfgen.cpp.
endDescTableTitle()
void RTFGenerator::endDescTableTitle () virtual
Implements BaseOutputDocInterface.
Definition at line 2055 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endDirDepGraph()
void RTFGenerator::endDirDepGraph (const DotDirDeps & g) virtual
Implements OutputGenerator.
Definition at line 2561 of file rtfgen.cpp.
References Config_getString, DBG_RTF, endl(), EOF_Rtf, OutputGenerator::fileName, getDotImageExtension(), GOF_BITMAP, newParagraph(), relPath, rtf_Style_Reset, OutputGenerator::t, and DotDirDeps::writeGraph().
endDotGraph()
void RTFGenerator::endDotGraph (const DotClassGraph & g) virtual
Implements OutputGenerator.
Definition at line 2483 of file rtfgen.cpp.
References Config_getString, DBG_RTF, endl(), EOF_Rtf, OutputGenerator::fileName, getDotImageExtension(), GOF_BITMAP, newParagraph(), relPath, rtf_Style_Reset, OutputGenerator::t, and DotClassGraph::writeGraph().
endDoxyAnchor()
void RTFGenerator::endDoxyAnchor (const char * fName, const char * anchor) virtual
Implements OutputGenerator.
Definition at line 1543 of file rtfgen.cpp.
References DBG_RTF, endl(), rtfFormatBmkStr(), and OutputGenerator::t.
endEmphasis()
void RTFGenerator::endEmphasis () inline virtual
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 133 of file rtfgen.h.
References OutputGenerator::t.
Referenced by endConstraintParam(), endConstraintType(), endMemberDescription(), endMemberGroupDocs(), and endPageRef().
endFile()
void RTFGenerator::endFile () virtual
Implements OutputGenerator.
Definition at line 364 of file rtfgen.cpp.
References DBG_RTF, OutputGenerator::endPlainFile(), and OutputGenerator::t.
endFontClass()
void RTFGenerator::endFontClass () inline virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 261 of file rtfgen.h.
endGroupCollaboration()
void RTFGenerator::endGroupCollaboration (const DotGroupCollaboration & g) virtual
Implements OutputGenerator.
Definition at line 2529 of file rtfgen.cpp.
endGroupHeader()
void RTFGenerator::endGroupHeader (int) virtual
Implements OutputGenerator.
Definition at line 1495 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_Style_Reset, and OutputGenerator::t.
Referenced by endMemberHeader().
endHeaderSection()
void RTFGenerator::endHeaderSection () inline virtual
Implements OutputGenerator.
Definition at line 105 of file rtfgen.h.
endHtmlLink()
void RTFGenerator::endHtmlLink () virtual
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 1112 of file rtfgen.cpp.
References Config_getBool, endl(), endTypewriter(), and OutputGenerator::t.
endInclDepGraph()
void RTFGenerator::endInclDepGraph (const DotInclDepGraph & g) virtual
Implements OutputGenerator.
Definition at line 2507 of file rtfgen.cpp.
References Config_getString, DBG_RTF, endl(), EOF_Rtf, OutputGenerator::fileName, getDotImageExtension(), GOF_BITMAP, newParagraph(), relPath, rtf_Style_Reset, OutputGenerator::t, and DotInclDepGraph::writeGraph().
endIndent()
void RTFGenerator::endIndent () virtual
Implements OutputGenerator.
Definition at line 1594 of file rtfgen.cpp.
References decrementIndentLevel(), endl(), and OutputGenerator::t.
endIndexItem()
void RTFGenerator::endIndexItem (const char * ref, const char * file) virtual
Implements OutputGenerator.
Definition at line 1073 of file rtfgen.cpp.
References DBG_RTF, endl(), m_omitParagraph, OutputGenerator::t, and writeRTFReference().
endIndexKey()
void RTFGenerator::endIndexKey () virtual
Implements OutputGenerator.
Definition at line 1177 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endIndexList()
void RTFGenerator::endIndexList () virtual
Implements OutputGenerator.
Definition at line 986 of file rtfgen.cpp.
References DBG_RTF, decrementIndentLevel(), endl(), m_omitParagraph, and OutputGenerator::t.
endIndexListItem()
void RTFGenerator::endIndexListItem () virtual
Implements OutputGenerator.
Definition at line 2925 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endIndexSection()
void RTFGenerator::endIndexSection (IndexSections is) virtual
Implements OutputGenerator.
Definition at line 560 of file rtfgen.cpp.
References beginRTFChapter(), beginRTFSection(), Doxygen::classSDict, Config_getBool, Config_getString, dateToRTFDateString(), dateToString(), DBG_RTF, Doxygen::directories, endl(), Doxygen::exampleSDict, FileDef::generateSourceFile(), NamespaceDef::getOutputFileBase(), PageDef::getOutputFileBase(), GroupDef::getOutputFileBase(), DirDef::getOutputFileBase(), FileDef::getOutputFileBase(), ClassDef::getOutputFileBase(), FileDef::getSourceFileBase(), Doxygen::groupSDict, Doxygen::inputNameList, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isDirDocumentation, isDirIndex, ClassDef::isEmbeddedInOuterScope(), isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, DirDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), FileDef::isLinkableInProject(), ClassDef::isLinkableInProject(), isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, Definition::isReference(), isTitlePageAuthor, isTitlePageStart, SDict< PageDef >::Iterator, SDict< GroupDef >::Iterator, SDict< NamespaceDef >::Iterator, SDict< ClassDef >::Iterator, m_prettyCode, Doxygen::mainPage, Doxygen::namespaceSDict, rtf_author, rtf_company, rtf_documentId, rtf_documentType, rtf_logoFilename, rtf_Style, rtf_Style_Reset, rtf_title, substitute(), OutputGenerator::t, ClassDef::templateMaster(), theTranslator, Translator::trClassDocumentation(), Translator::trCompoundIndex(), Translator::trCompoundIndexFortran(), VhdlDocGen::trDesignUnitIndex(), Translator::trDirDocumentation(), Translator::trDirIndex(), Translator::trExampleDocumentation(), Translator::trFileDocumentation(), Translator::trFileIndex(), Translator::trHierarchicalIndex(), Translator::trMainPage(), Translator::trModuleDocumentation(), Translator::trModuleIndex(), Translator::trModulesIndex(), Translator::trNamespaceIndex(), Translator::trPageIndex(), Translator::trRTFGeneralIndex(), Translator::trRTFTableOfContents(), Translator::trTypeDocumentation(), Translator::trVersion(), validatingParseText(), and writeDoc().
endIndexValue()
void RTFGenerator::endIndexValue (const char * name, bool hasBrief) virtual
Implements OutputGenerator.
Definition at line 1189 of file rtfgen.cpp.
References DBG_RTF, endl(), m_omitParagraph, newParagraph(), OutputGenerator::t, and writeRTFReference().
endInlineHeader()
void RTFGenerator::endInlineHeader () virtual
Implements OutputGenerator.
Definition at line 2939 of file rtfgen.cpp.
References DBG_RTF, endBold(), endl(), and OutputGenerator::t.
endInlineMemberDoc()
void RTFGenerator::endInlineMemberDoc () virtual
Implements OutputGenerator.
Definition at line 3024 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endInlineMemberName()
void RTFGenerator::endInlineMemberName () virtual
Implements OutputGenerator.
Definition at line 3012 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endInlineMemberType()
void RTFGenerator::endInlineMemberType () virtual
Implements OutputGenerator.
Definition at line 3000 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endItemList()
void RTFGenerator::endItemList () virtual
end bullet list
Implements BaseOutputDocInterface.
Definition at line 1009 of file rtfgen.cpp.
References DBG_RTF, decrementIndentLevel(), endl(), m_listLevel, m_omitParagraph, newParagraph(), and OutputGenerator::t.
endItemListItem()
void RTFGenerator::endItemListItem () virtual
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 1057 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endLabels()
void RTFGenerator::endLabels () virtual
Implements OutputGenerator.
Definition at line 3040 of file rtfgen.cpp.
endMemberDeclaration()
void RTFGenerator::endMemberDeclaration (const char * , const char *) inline virtual
Implements OutputGenerator.
Definition at line 162 of file rtfgen.h.
endMemberDescription()
void RTFGenerator::endMemberDescription () virtual
Implements OutputGenerator.
Definition at line 1638 of file rtfgen.cpp.
References DBG_RTF, decrementIndentLevel(), endEmphasis(), endl(), newParagraph(), and OutputGenerator::t.
endMemberDoc()
void RTFGenerator::endMemberDoc (bool) virtual
Implements OutputGenerator.
Definition at line 1524 of file rtfgen.cpp.
References DBG_RTF, endBold(), endl(), newParagraph(), and OutputGenerator::t.
endMemberDocList()
void RTFGenerator::endMemberDocList () inline virtual
Implements OutputGenerator.
Definition at line 111 of file rtfgen.h.
endMemberDocName()
void RTFGenerator::endMemberDocName () inline virtual
Implements OutputGenerator.
Definition at line 229 of file rtfgen.h.
endMemberDocPrefixItem()
void RTFGenerator::endMemberDocPrefixItem () inline virtual
Implements OutputGenerator.
Definition at line 227 of file rtfgen.h.
endMemberDocSimple()
void RTFGenerator::endMemberDocSimple (bool) virtual
Implements OutputGenerator.
Definition at line 2988 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endMemberGroup()
void RTFGenerator::endMemberGroup (bool hasHeader) virtual
Implements OutputGenerator.
Definition at line 2708 of file rtfgen.cpp.
References DBG_RTF, decrementIndentLevel(), endl(), and OutputGenerator::t.
endMemberGroupDocs()
void RTFGenerator::endMemberGroupDocs () virtual
Implements OutputGenerator.
Definition at line 2695 of file rtfgen.cpp.
References DBG_RTF, endEmphasis(), endl(), newParagraph(), and OutputGenerator::t.
endMemberGroupHeader()
void RTFGenerator::endMemberGroupHeader () virtual
Implements OutputGenerator.
Definition at line 2682 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), rtf_CList_DepthStyle(), rtf_Style_Reset, and OutputGenerator::t.
endMemberHeader()
void RTFGenerator::endMemberHeader () inline virtual
Implements OutputGenerator.
Definition at line 107 of file rtfgen.h.
References endGroupHeader().
endMemberItem()
void RTFGenerator::endMemberItem () virtual
Implements OutputGenerator.
Definition at line 1886 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), and OutputGenerator::t.
endMemberList()
void RTFGenerator::endMemberList () virtual
Implements OutputGenerator.
Definition at line 1957 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endMemberSections()
void RTFGenerator::endMemberSections () inline virtual
Implements OutputGenerator.
Definition at line 103 of file rtfgen.h.
endMemberSubtitle()
void RTFGenerator::endMemberSubtitle () virtual
Implements OutputGenerator.
Definition at line 2189 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), and OutputGenerator::t.
endMemberTemplateParams()
void RTFGenerator::endMemberTemplateParams (const char * , const char *) inline virtual
Implements OutputGenerator.
Definition at line 121 of file rtfgen.h.
endPageRef()
void RTFGenerator::endPageRef (const char * clname, const char * anchor) virtual
Implements BaseOutputDocInterface.
Definition at line 1383 of file rtfgen.cpp.
References endEmphasis(), OutputGenerator::t, and writeRTFReference().
endParagraph()
void RTFGenerator::endParagraph () virtual
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 2175 of file rtfgen.cpp.
References DBG_RTF, endl(), m_omitParagraph, and OutputGenerator::t.
endParameterList()
void RTFGenerator::endParameterList () inline virtual
Implements OutputGenerator.
Definition at line 235 of file rtfgen.h.
endParameterName()
void RTFGenerator::endParameterName (bool , bool , bool) inline virtual
Implements OutputGenerator.
Definition at line 233 of file rtfgen.h.
endParameterType()
void RTFGenerator::endParameterType () virtual
Implements OutputGenerator.
Definition at line 2780 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endParamList()
void RTFGenerator::endParamList () virtual
Implements BaseOutputDocInterface.
Definition at line 2762 of file rtfgen.cpp.
References DBG_RTF, decrementIndentLevel(), endl(), m_omitParagraph, newParagraph(), and OutputGenerator::t.
endProjectNumber()
void RTFGenerator::endProjectNumber () virtual
Implements OutputGenerator.
Definition at line 378 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
endQuickIndices()
void RTFGenerator::endQuickIndices () inline virtual
Implements OutputGenerator.
Definition at line 184 of file rtfgen.h.
endSection()
void RTFGenerator::endSection (const char * lab, SectionInfo::SectionType) virtual
Implements BaseOutputDocInterface.
Definition at line 1713 of file rtfgen.cpp.
References DBG_RTF, endl(), m_omitParagraph, newParagraph(), OutputGenerator::t, and writeAnchor().
endSimpleSect()
void RTFGenerator::endSimpleSect () virtual
Implements BaseOutputDocInterface.
Definition at line 2737 of file rtfgen.cpp.
References DBG_RTF, decrementIndentLevel(), endl(), m_omitParagraph, newParagraph(), and OutputGenerator::t.
endSmall()
void RTFGenerator::endSmall () inline virtual
Implements BaseOutputDocInterface.
Definition at line 157 of file rtfgen.h.
References OutputGenerator::t.
endSubsection()
void RTFGenerator::endSubsection () virtual
Implements BaseOutputDocInterface.
Definition at line 1217 of file rtfgen.cpp.
References endl(), newParagraph(), rtf_Style_Reset, and OutputGenerator::t.
endSubsubsection()
void RTFGenerator::endSubsubsection () virtual
Implements BaseOutputDocInterface.
Definition at line 1232 of file rtfgen.cpp.
References endl(), newParagraph(), and OutputGenerator::t.
endTextBlock()
void RTFGenerator::endTextBlock (bool) virtual
Implements OutputGenerator.
Definition at line 2150 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), and OutputGenerator::t.
endTextLink()
void RTFGenerator::endTextLink () virtual
Implements BaseOutputDocInterface.
Definition at line 1336 of file rtfgen.cpp.
References Config_getBool, endl(), and OutputGenerator::t.
endTitle()
void RTFGenerator::endTitle () inline virtual
Implements BaseOutputDocInterface.
Definition at line 62 of file rtfgen.h.
endTitleHead()
void RTFGenerator::endTitleHead (const char * fileName, const char * name) virtual
Implements OutputGenerator.
Definition at line 1440 of file rtfgen.cpp.
References addIndexItem(), DBG_RTF, docify(), endl(), rtf_Style_Reset, OutputGenerator::t, and writeAnchor().
endTypewriter()
void RTFGenerator::endTypewriter () inline virtual
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 95 of file rtfgen.h.
References OutputGenerator::t.
Referenced by endHtmlLink().
exceptionEntry()
void RTFGenerator::exceptionEntry (const char * prefix, bool closeBracket) virtual
Implements OutputGenerator.
Definition at line 2786 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
get()
OutputGenerator* RTFGenerator::get (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 42 of file rtfgen.h.
References OutputGenerator::RTF.
incrementIndentLevel()
void RTFGenerator::incrementIndentLevel () private
Definition at line 2075 of file rtfgen.cpp.
References err(), m_listLevel, and rtf_maxIndentLevels.
Referenced by startConstraintList(), startIndent(), startIndexList(), startItemList(), startMemberDescription(), startMemberGroupHeader(), startParamList(), and startSimpleSect().
init()
void RTFGenerator::init () static
Definition at line 166 of file rtfgen.cpp.
References Config_getString, createSubDirs(), Rtf_Style_Default::definition, OutputGenerator::dir, err(), loadExtensions(), loadStylesheet(), Rtf_Style_Default::name, Rtf_Style_Default::reference, rtf_Style, and rtf_Style_Default.
Referenced by generateOutput().
insertMemberAlign()
void RTFGenerator::insertMemberAlign (bool) inline virtual
Implements OutputGenerator.
Definition at line 122 of file rtfgen.h.
isEnabled()
bool RTFGenerator::isEnabled (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 41 of file rtfgen.h.
References OutputGenerator::active, and OutputGenerator::RTF.
lastIndexPage()
void RTFGenerator::lastIndexPage () virtual
Implements OutputGenerator.
Definition at line 947 of file rtfgen.cpp.
References DBG_RTF, rtf_Style, and OutputGenerator::t.
lineBreak()
void RTFGenerator::lineBreak (const char * style = 0) virtual
Implements BaseOutputDocInterface.
Definition at line 964 of file rtfgen.cpp.
References DBG_RTF, endl(), m_omitParagraph, and OutputGenerator::t.
Referenced by endCodeLine().
newParagraph()
void RTFGenerator::newParagraph ()
Definition at line 2158 of file rtfgen.cpp.
References DBG_RTF, endl(), m_omitParagraph, and OutputGenerator::t.
Referenced by codify(), endCallGraph(), endClassDiagram(), endConstraintDocs(), endConstraintList(), endDescItem(), endDescription(), endDirDepGraph(), endDotGraph(), endInclDepGraph(), endIndexValue(), endItemList(), endMemberDescription(), endMemberDoc(), endMemberGroupDocs(), endMemberGroupHeader(), endMemberItem(), endMemberSubtitle(), endParamList(), endSection(), endSimpleSect(), endSubsection(), endSubsubsection(), endTextBlock(), startConstraintList(), startDescItem(), startDescList(), startItemList(), startItemListItem(), startParagraph(), startParamList(), startSimpleSect(), and writeEndAnnoItem().
operator=()
RTFGenerator& RTFGenerator::operator= (const RTFGenerator &) private
preProcessFileInplace()
bool RTFGenerator::preProcessFileInplace (const char * path, const char * name) static
This is an API to a VERY brittle RTF preprocessor that combines nested RTF files.
This version replaces the infile with the new file
Definition at line 2627 of file rtfgen.cpp.
References err(), preProcessFile(), and testRTFOutput().
Referenced by generateOutput().
rtf_BList_DepthStyle()
const char * RTFGenerator::rtf_BList_DepthStyle () private
Definition at line 2110 of file rtfgen.cpp.
References m_listLevel, makeIndexName(), and rtf_Style.
Referenced by startItemListItem(), startMemberGroup(), and startMemberItem().
rtf_CList_DepthStyle()
const char * RTFGenerator::rtf_CList_DepthStyle () private
Definition at line 2096 of file rtfgen.cpp.
References m_listLevel, makeIndexName(), and rtf_Style.
Referenced by endMemberGroupHeader(), startIndent(), startMemberDescription(), and startMemberSubtitle().
rtf_Code_DepthStyle()
const char * RTFGenerator::rtf_Code_DepthStyle () private
Definition at line 2129 of file rtfgen.cpp.
References m_listLevel, makeIndexName(), and rtf_Style.
Referenced by startCodeFragment().
rtf_DList_DepthStyle()
const char * RTFGenerator::rtf_DList_DepthStyle () private
Definition at line 2123 of file rtfgen.cpp.
References m_listLevel, makeIndexName(), and rtf_Style.
Referenced by startConstraintList(), startDescription(), startDescTable(), startMemberDocSimple(), startParamList(), and startSimpleSect().
rtf_EList_DepthStyle()
const char * RTFGenerator::rtf_EList_DepthStyle () private
Definition at line 2117 of file rtfgen.cpp.
References m_listLevel, makeIndexName(), and rtf_Style.
Referenced by startItemListItem().
rtf_LCList_DepthStyle()
const char * RTFGenerator::rtf_LCList_DepthStyle () private
Definition at line 2103 of file rtfgen.cpp.
References m_listLevel, makeIndexName(), and rtf_Style.
Referenced by startIndexList().
rtfwriteRuler_doubleline()
void RTFGenerator::rtfwriteRuler_doubleline () private
Definition at line 2804 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
rtfwriteRuler_emboss()
void RTFGenerator::rtfwriteRuler_emboss () private
Definition at line 2810 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
Referenced by beginRTFSection().
rtfwriteRuler_thick()
void RTFGenerator::rtfwriteRuler_thick () private
Definition at line 2816 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
Referenced by beginRTFChapter().
rtfwriteRuler_thin()
void RTFGenerator::rtfwriteRuler_thin () private
Definition at line 2822 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
Referenced by writeRuler().
setCurrentDoc()
void RTFGenerator::setCurrentDoc (Definition * , const char * , bool) inline virtual
Implements CodeOutputInterface.
Definition at line 264 of file rtfgen.h.
startAnonTypeScope()
void RTFGenerator::startAnonTypeScope (int) inline virtual
Implements OutputGenerator.
Definition at line 116 of file rtfgen.h.
startBold()
void RTFGenerator::startBold () inline virtual
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 134 of file rtfgen.h.
References OutputGenerator::t.
Referenced by startConstraintList(), startDescList(), startInlineHeader(), startMemberDoc(), startParamList(), startSimpleSect(), and writeObjectLink().
startCallGraph()
void RTFGenerator::startCallGraph () virtual
Implements OutputGenerator.
Definition at line 2533 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startCenter()
void RTFGenerator::startCenter () inline virtual
Implements BaseOutputDocInterface.
Definition at line 154 of file rtfgen.h.
References endl(), and OutputGenerator::t.
startClassDiagram()
void RTFGenerator::startClassDiagram () virtual
Implements OutputGenerator.
Definition at line 1853 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startCodeFragment()
void RTFGenerator::startCodeFragment () virtual
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Implements BaseOutputDocInterface.
Definition at line 1920 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_Code_DepthStyle(), rtf_Style_Reset, and OutputGenerator::t.
startCodeLine()
void RTFGenerator::startCodeLine (bool) inline virtual
Implements CodeOutputInterface.
Definition at line 130 of file rtfgen.h.
References col.
startConstraintDocs()
void RTFGenerator::startConstraintDocs () virtual
Implements OutputGenerator.
Definition at line 2900 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startConstraintList()
void RTFGenerator::startConstraintList (const char * header) virtual
Implements OutputGenerator.
Definition at line 2859 of file rtfgen.cpp.
References DBG_RTF, docify(), endBold(), endl(), incrementIndentLevel(), newParagraph(), rtf_DList_DepthStyle(), rtf_Style_Reset, startBold(), and OutputGenerator::t.
startConstraintParam()
void RTFGenerator::startConstraintParam () virtual
Implements OutputGenerator.
Definition at line 2874 of file rtfgen.cpp.
References DBG_RTF, endl(), startEmphasis(), and OutputGenerator::t.
startConstraintType()
void RTFGenerator::startConstraintType () virtual
Implements OutputGenerator.
Definition at line 2887 of file rtfgen.cpp.
References DBG_RTF, endl(), startEmphasis(), and OutputGenerator::t.
startContents()
void RTFGenerator::startContents () inline virtual
Implements OutputGenerator.
Definition at line 190 of file rtfgen.h.
startDescForItem()
void RTFGenerator::startDescForItem () virtual
Implements BaseOutputDocInterface.
Definition at line 1668 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startDescItem()
void RTFGenerator::startDescItem () virtual
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 1615 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), and OutputGenerator::t.
startDescList()
void RTFGenerator::startDescList (SectionTypes)
Definition at line 1649 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), startBold(), and OutputGenerator::t.
startDescription()
void RTFGenerator::startDescription () virtual
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 1601 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_DList_DepthStyle(), rtf_Style_Reset, and OutputGenerator::t.
startDescTable()
void RTFGenerator::startDescTable (const char * title) virtual
Implements BaseOutputDocInterface.
Definition at line 2007 of file rtfgen.cpp.
References DBG_RTF, docify(), endl(), rtf_DList_DepthStyle(), rtf_pageWidth, rtf_Style, rtf_Style_Reset, and OutputGenerator::t.
startDescTableData()
void RTFGenerator::startDescTableData () virtual
Implements BaseOutputDocInterface.
Definition at line 2061 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startDescTableRow()
void RTFGenerator::startDescTableRow () virtual
Implements BaseOutputDocInterface.
Definition at line 2041 of file rtfgen.cpp.
startDescTableTitle()
void RTFGenerator::startDescTableTitle () virtual
Implements BaseOutputDocInterface.
Definition at line 2049 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startDirDepGraph()
void RTFGenerator::startDirDepGraph () virtual
Implements OutputGenerator.
Definition at line 2556 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startDotGraph()
void RTFGenerator::startDotGraph () virtual
Implements OutputGenerator.
Definition at line 2478 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startDoxyAnchor()
void RTFGenerator::startDoxyAnchor (const char * , const char * , const char * , const char * , const char *) virtual
Implements OutputGenerator.
Definition at line 1535 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startEmphasis()
void RTFGenerator::startEmphasis () inline virtual
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 132 of file rtfgen.h.
References OutputGenerator::t.
Referenced by startConstraintParam(), startConstraintType(), startMemberDescription(), startMemberGroupDocs(), and startPageRef().
startFile()
void RTFGenerator::startFile (const char * name, const char * manName, const char * title) virtual
Implements OutputGenerator.
Definition at line 353 of file rtfgen.cpp.
References beginRTFDocument(), OutputGenerator::fileName, Rtf_Style_Default::name, relativePathToRoot(), relPath, and OutputGenerator::startPlainFile().
startFontClass()
void RTFGenerator::startFontClass (const char * clsName) inline virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 260 of file rtfgen.h.
startGroupCollaboration()
void RTFGenerator::startGroupCollaboration () virtual
Implements OutputGenerator.
Definition at line 2525 of file rtfgen.cpp.
startGroupHeader()
void RTFGenerator::startGroupHeader (int extraIndent) virtual
Implements OutputGenerator.
Definition at line 1475 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_Style, rtf_Style_Reset, and OutputGenerator::t.
Referenced by startMemberHeader().
startHeaderSection()
void RTFGenerator::startHeaderSection () inline virtual
Implements OutputGenerator.
Definition at line 104 of file rtfgen.h.
startHtmlLink()
void RTFGenerator::startHtmlLink (const char * url) virtual
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 1096 of file rtfgen.cpp.
References Config_getBool, startTypewriter(), and OutputGenerator::t.
startInclDepGraph()
void RTFGenerator::startInclDepGraph () virtual
Implements OutputGenerator.
Definition at line 2502 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startIndent()
void RTFGenerator::startIndent () virtual
Implements OutputGenerator.
Definition at line 1586 of file rtfgen.cpp.
References DBG_RTF, endl(), incrementIndentLevel(), rtf_CList_DepthStyle(), rtf_Style_Reset, and OutputGenerator::t.
startIndexItem()
void RTFGenerator::startIndexItem (const char * ref, const char * file) virtual
Implements OutputGenerator.
Definition at line 1062 of file rtfgen.cpp.
References DBG_RTF, endl(), m_omitParagraph, and OutputGenerator::t.
startIndexKey()
void RTFGenerator::startIndexKey () virtual
Implements OutputGenerator.
Definition at line 1171 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startIndexList()
void RTFGenerator::startIndexList () virtual
Implements OutputGenerator.
Definition at line 976 of file rtfgen.cpp.
References DBG_RTF, endl(), incrementIndentLevel(), m_omitParagraph, rtf_LCList_DepthStyle(), rtf_Style_Reset, and OutputGenerator::t.
startIndexListItem()
void RTFGenerator::startIndexListItem () virtual
Implements OutputGenerator.
Definition at line 2920 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startIndexSection()
void RTFGenerator::startIndexSection (IndexSections is) virtual
Implements OutputGenerator.
Definition at line 383 of file rtfgen.cpp.
References beginRTFChapter(), Doxygen::classSDict, DBG_RTF, Doxygen::directories, Doxygen::groupSDict, Doxygen::inputNameList, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isDirDocumentation, isDirIndex, ClassDef::isEmbeddedInOuterScope(), isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, DirDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), FileDef::isLinkableInProject(), ClassDef::isLinkableInProject(), isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, isPageIndex, Definition::isReference(), isTitlePageAuthor, isTitlePageStart, SDict< ClassDef >::Iterator, SDict< GroupDef >::Iterator, SDict< NamespaceDef >::Iterator, m_listLevel, Doxygen::namespaceSDict, rtf_author, rtf_comments, rtf_company, rtf_documentType, rtf_keywords, rtf_manager, rtf_subject, OutputGenerator::t, and ClassDef::templateMaster().
startIndexValue()
void RTFGenerator::startIndexValue (bool hasBrief) virtual
Implements OutputGenerator.
Definition at line 1182 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startInlineHeader()
void RTFGenerator::startInlineHeader () virtual
Implements OutputGenerator.
Definition at line 2931 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_Style, rtf_Style_Reset, startBold(), and OutputGenerator::t.
startInlineMemberDoc()
void RTFGenerator::startInlineMemberDoc () virtual
Implements OutputGenerator.
Definition at line 3018 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startInlineMemberName()
void RTFGenerator::startInlineMemberName () virtual
Implements OutputGenerator.
Definition at line 3006 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startInlineMemberType()
void RTFGenerator::startInlineMemberType () virtual
Implements OutputGenerator.
Definition at line 2994 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startItemList()
void RTFGenerator::startItemList () virtual
start bullet list
Implements BaseOutputDocInterface.
Definition at line 999 of file rtfgen.cpp.
References DBG_RTF, endl(), incrementIndentLevel(), RTFListItemInfo::isEnum, m_listLevel, newParagraph(), rtf_listItemInfo, and OutputGenerator::t.
startItemListItem()
void RTFGenerator::startItemListItem () virtual
start enumeration list
end enumeration list
write bullet or enum item
Implements BaseOutputDocInterface.
Definition at line 1039 of file rtfgen.cpp.
References DBG_RTF, endl(), m_listLevel, m_omitParagraph, newParagraph(), RTFListItemInfo::number, rtf_BList_DepthStyle(), rtf_EList_DepthStyle(), rtf_listItemInfo, rtf_Style_Reset, and OutputGenerator::t.
startLabels()
void RTFGenerator::startLabels () virtual
Implements OutputGenerator.
Definition at line 3030 of file rtfgen.cpp.
startMemberDeclaration()
void RTFGenerator::startMemberDeclaration () inline virtual
Implements OutputGenerator.
Definition at line 161 of file rtfgen.h.
startMemberDescription()
void RTFGenerator::startMemberDescription (const char * , const char *) virtual
Implements OutputGenerator.
Definition at line 1629 of file rtfgen.cpp.
References DBG_RTF, endl(), incrementIndentLevel(), rtf_CList_DepthStyle(), rtf_Style_Reset, startEmphasis(), and OutputGenerator::t.
startMemberDoc()
void RTFGenerator::startMemberDoc (const char * clname, const char * memname, const char * , const char * , int , int , bool showInline) virtual
Implements OutputGenerator.
Definition at line 1502 of file rtfgen.cpp.
References addIndexItem(), DBG_RTF, endl(), rtf_Style, rtf_Style_Reset, startBold(), and OutputGenerator::t.
startMemberDocList()
void RTFGenerator::startMemberDocList () inline virtual
Implements OutputGenerator.
Definition at line 110 of file rtfgen.h.
startMemberDocName()
void RTFGenerator::startMemberDocName (bool) inline virtual
Implements OutputGenerator.
Definition at line 228 of file rtfgen.h.
startMemberDocPrefixItem()
void RTFGenerator::startMemberDocPrefixItem () inline virtual
Implements OutputGenerator.
Definition at line 226 of file rtfgen.h.
startMemberDocSimple()
void RTFGenerator::startMemberDocSimple (bool isEnum) virtual
Implements OutputGenerator.
Definition at line 2947 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_DList_DepthStyle(), rtf_pageWidth, rtf_Style, rtf_Style_Reset, OutputGenerator::t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberGroup()
void RTFGenerator::startMemberGroup () virtual
Implements OutputGenerator.
Definition at line 2702 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_BList_DepthStyle(), rtf_Style_Reset, and OutputGenerator::t.
startMemberGroupDocs()
void RTFGenerator::startMemberGroupDocs () virtual
Implements OutputGenerator.
Definition at line 2689 of file rtfgen.cpp.
References DBG_RTF, endl(), startEmphasis(), and OutputGenerator::t.
startMemberGroupHeader()
void RTFGenerator::startMemberGroupHeader (bool hasHeader) virtual
Implements OutputGenerator.
Definition at line 2674 of file rtfgen.cpp.
References DBG_RTF, endl(), incrementIndentLevel(), rtf_Style, rtf_Style_Reset, and OutputGenerator::t.
startMemberHeader()
void RTFGenerator::startMemberHeader (const char *) inline virtual
Implements OutputGenerator.
Definition at line 106 of file rtfgen.h.
References startGroupHeader().
startMemberItem()
void RTFGenerator::startMemberItem (const char * , int , const char *) virtual
Implements OutputGenerator.
Definition at line 1880 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_BList_DepthStyle(), rtf_Style_Reset, and OutputGenerator::t.
startMemberList()
void RTFGenerator::startMemberList () virtual
Implements OutputGenerator.
Definition at line 1946 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startMemberSections()
void RTFGenerator::startMemberSections () inline virtual
Implements OutputGenerator.
Definition at line 102 of file rtfgen.h.
startMemberSubtitle()
void RTFGenerator::startMemberSubtitle () virtual
Implements OutputGenerator.
Definition at line 2182 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_CList_DepthStyle(), rtf_Style_Reset, and OutputGenerator::t.
startMemberTemplateParams()
void RTFGenerator::startMemberTemplateParams () inline virtual
Implements OutputGenerator.
Definition at line 120 of file rtfgen.h.
startPageRef()
void RTFGenerator::startPageRef () virtual
Implements BaseOutputDocInterface.
Definition at line 1377 of file rtfgen.cpp.
References startEmphasis(), and OutputGenerator::t.
startParagraph()
void RTFGenerator::startParagraph (const char * classDef) virtual
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 2168 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), and OutputGenerator::t.
startParameterList()
void RTFGenerator::startParameterList (bool) inline virtual
Implements OutputGenerator.
Definition at line 234 of file rtfgen.h.
startParameterName()
void RTFGenerator::startParameterName (bool) inline virtual
Implements OutputGenerator.
Definition at line 232 of file rtfgen.h.
startParameterType()
void RTFGenerator::startParameterType (bool first, const char * key) virtual
Implements OutputGenerator.
Definition at line 2771 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startParamList()
void RTFGenerator::startParamList (ParamListTypes , const char * title) virtual
Implements BaseOutputDocInterface.
Definition at line 2747 of file rtfgen.cpp.
References DBG_RTF, docify(), endBold(), endl(), incrementIndentLevel(), newParagraph(), rtf_DList_DepthStyle(), rtf_Style_Reset, startBold(), and OutputGenerator::t.
startProjectNumber()
void RTFGenerator::startProjectNumber () virtual
Implements OutputGenerator.
Definition at line 372 of file rtfgen.cpp.
References DBG_RTF, endl(), and OutputGenerator::t.
startQuickIndices()
void RTFGenerator::startQuickIndices () inline virtual
Implements OutputGenerator.
Definition at line 183 of file rtfgen.h.
startSection()
void RTFGenerator::startSection (const char * , const char * title, SectionInfo::SectionType type) virtual
Implements BaseOutputDocInterface.
Definition at line 1688 of file rtfgen.cpp.
References DBG_RTF, docify(), endl(), SectionInfo::Page, SectionInfo::Paragraph, rtf_Style, rtf_Style_Reset, SectionInfo::Section, SectionInfo::Subsection, SectionInfo::Subsubsection, and OutputGenerator::t.
startSimpleSect()
void RTFGenerator::startSimpleSect (SectionTypes , const char * file, const char * anchor, const char * title) virtual
Implements BaseOutputDocInterface.
Definition at line 2715 of file rtfgen.cpp.
References DBG_RTF, docify(), endBold(), endl(), incrementIndentLevel(), newParagraph(), rtf_DList_DepthStyle(), rtf_Style_Reset, startBold(), OutputGenerator::t, and writeObjectLink().
startSmall()
void RTFGenerator::startSmall () inline virtual
Implements BaseOutputDocInterface.
Definition at line 156 of file rtfgen.h.
References OutputGenerator::t.
startSubsection()
void RTFGenerator::startSubsection () virtual
Implements BaseOutputDocInterface.
Definition at line 1208 of file rtfgen.cpp.
References DBG_RTF, rtf_Style, rtf_Style_Reset, and OutputGenerator::t.
startSubsubsection()
void RTFGenerator::startSubsubsection () virtual
Implements BaseOutputDocInterface.
Definition at line 1223 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_Style, rtf_Style_Reset, and OutputGenerator::t.
startTextBlock()
void RTFGenerator::startTextBlock (bool dense) virtual
Implements OutputGenerator.
Definition at line 2135 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_Style, rtf_Style_Reset, and OutputGenerator::t.
startTextLink()
void RTFGenerator::startTextLink (const char * f, const char * anchor) virtual
Implements BaseOutputDocInterface.
Definition at line 1314 of file rtfgen.cpp.
References Config_getBool, rtfFormatBmkStr(), and OutputGenerator::t.
startTitle()
void RTFGenerator::startTitle () virtual
Implements BaseOutputDocInterface.
Definition at line 1466 of file rtfgen.cpp.
References beginRTFChapter(), beginRTFSection(), Config_getBool, DBG_RTF, endl(), and OutputGenerator::t.
startTitleHead()
void RTFGenerator::startTitleHead (const char *) virtual
Implements OutputGenerator.
Definition at line 1432 of file rtfgen.cpp.
References DBG_RTF, endl(), rtf_Style, rtf_Style_Reset, and OutputGenerator::t.
startTypewriter()
void RTFGenerator::startTypewriter () inline virtual
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 94 of file rtfgen.h.
References OutputGenerator::t.
Referenced by startHtmlLink().
writeAnchor()
void RTFGenerator::writeAnchor (const char * fileName, const char * name) virtual
Implements BaseOutputDocInterface.
Definition at line 1892 of file rtfgen.cpp.
References DBG_RTF, endl(), OutputGenerator::fileName, Rtf_Style_Default::name, rtfFormatBmkStr(), and OutputGenerator::t.
Referenced by endSection(), and endTitleHead().
writeChar()
void RTFGenerator::writeChar (char c) virtual
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 1845 of file rtfgen.cpp.
References docify().
writeCodeAnchor()
void RTFGenerator::writeCodeAnchor (const char * name) inline virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 263 of file rtfgen.h.
writeCodeLink()
void RTFGenerator::writeCodeLink (const char * ref, const char * file, const char * anchor, const char * name, const char * tooltip) virtual
Writes a link to an object in a code fragment.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 1400 of file rtfgen.cpp.
References codify(), Config_getBool, endl(), rtfFormatBmkStr(), and OutputGenerator::t.
writeDoc()
void RTFGenerator::writeDoc (DocNode * n, Definition * ctx, MemberDef *) virtual
Implements OutputGenerator.
Definition at line 2796 of file rtfgen.cpp.
References DocNode::accept(), Definition::getDefFileExtension(), m_omitParagraph, and OutputGenerator::t.
Referenced by endIndexSection().
writeEndAnnoItem()
void RTFGenerator::writeEndAnnoItem (const char * name) virtual
Implements OutputGenerator.
Definition at line 1155 of file rtfgen.cpp.
References DBG_RTF, endl(), newParagraph(), OutputGenerator::t, and writeRTFReference().
writeExtensionsFile()
void RTFGenerator::writeExtensionsFile (QFile & file) static
Definition at line 113 of file rtfgen.cpp.
References OutputGenerator::t, and versionString.
Referenced by readConfiguration().
writeFooter()
void RTFGenerator::writeFooter (const char *) inline virtual
Implements OutputGenerator.
Definition at line 48 of file rtfgen.h.
writeGraphicalHierarchy()
void RTFGenerator::writeGraphicalHierarchy (const DotGfxHierarchyTable &) inline virtual
Implements OutputGenerator.
Definition at line 213 of file rtfgen.h.
writeInheritedSectionTitle()
void RTFGenerator::writeInheritedSectionTitle (const char * , const char * , const char * , const char * , const char * , const char *) inline virtual
Implements OutputGenerator.
Definition at line 163 of file rtfgen.h.
writeLabel()
void RTFGenerator::writeLabel (const char * l, bool isLast) virtual
Implements OutputGenerator.
Definition at line 3034 of file rtfgen.cpp.
References OutputGenerator::t.
writeLatexSpacing()
void RTFGenerator::writeLatexSpacing () inline virtual
Implements OutputGenerator.
Definition at line 146 of file rtfgen.h.
writeLineNumber()
void RTFGenerator::writeLineNumber (const char * ref, const char * file, const char * anchor, int lineNumber) inline virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
Implements CodeOutputInterface.
Definition at line 129 of file rtfgen.h.
References OutputGenerator::t.
writeLogo()
void RTFGenerator::writeLogo () inline virtual
Implements OutputGenerator.
Definition at line 187 of file rtfgen.h.
writeNavigationPath()
void RTFGenerator::writeNavigationPath (const char *) inline virtual
Implements OutputGenerator.
Definition at line 186 of file rtfgen.h.
writeNonBreakableSpace()
void RTFGenerator::writeNonBreakableSpace (int) virtual
Implements BaseOutputDocInterface.
Definition at line 1940 of file rtfgen.cpp.
References OutputGenerator::t.
writeObjectLink()
void RTFGenerator::writeObjectLink (const char * ref, const char * file, const char * anchor, const char * name) virtual
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 1344 of file rtfgen.cpp.
References Config_getBool, docify(), endBold(), endl(), rtfFormatBmkStr(), startBold(), and OutputGenerator::t.
Referenced by startSimpleSect().
writePageLink()
void RTFGenerator::writePageLink (const char * name, bool first) virtual
Implements OutputGenerator.
Definition at line 939 of file rtfgen.cpp.
References endl(), Rtf_Style_Default::name, rtf_Style_Reset, and OutputGenerator::t.
writeQuickLinks()
void RTFGenerator::writeQuickLinks (bool , HighlightedItem , const char *) inline virtual
Implements OutputGenerator.
Definition at line 188 of file rtfgen.h.
writeRTFReference()
void RTFGenerator::writeRTFReference (const char * label) private
Definition at line 1913 of file rtfgen.cpp.
References rtfFormatBmkStr(), and OutputGenerator::t.
Referenced by endIndexItem(), endIndexValue(), endPageRef(), and writeEndAnnoItem().
writeRuler()
void RTFGenerator::writeRuler () inline virtual
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 124 of file rtfgen.h.
References rtfwriteRuler_thin().
writeSearchInfo()
void RTFGenerator::writeSearchInfo () inline virtual
Implements OutputGenerator.
Definition at line 47 of file rtfgen.h.
writeSplitBar()
void RTFGenerator::writeSplitBar (const char *) inline virtual
Implements OutputGenerator.
Definition at line 185 of file rtfgen.h.
writeStartAnnoItem()
void RTFGenerator::writeStartAnnoItem (const char * type, const char * file, const char * path, const char * name) virtual
Implements OutputGenerator.
Definition at line 1131 of file rtfgen.cpp.
References Config_getBool, DBG_RTF, docify(), endl(), rtfFormatBmkStr(), and OutputGenerator::t.
writeString()
void RTFGenerator::writeString (const char * text) virtual
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 971 of file rtfgen.cpp.
References OutputGenerator::t.
writeStyleInfo()
void RTFGenerator::writeStyleInfo (int part) virtual
Implements OutputGenerator.
Definition at line 960 of file rtfgen.cpp.
writeStyleSheetFile()
void RTFGenerator::writeStyleSheetFile (QFile & f) static
Definition at line 96 of file rtfgen.cpp.
References Rtf_Style_Default::definition, endl(), Rtf_Style_Default::name, Rtf_Style_Default::reference, rtf_Style_Default, OutputGenerator::t, and versionString.
Referenced by readConfiguration().
writeSummaryLink()
void RTFGenerator::writeSummaryLink (const char * , const char * , const char * , bool) inline virtual
Implements OutputGenerator.
Definition at line 189 of file rtfgen.h.
writeSynopsis()
void RTFGenerator::writeSynopsis () inline virtual
Implements OutputGenerator.
Definition at line 178 of file rtfgen.h.
writeTooltip()
void RTFGenerator::writeTooltip (const char * id, const DocLinkInfo & docInfo, const char * decl, const char * desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) inline virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 87 of file rtfgen.h.
Member Data Documentation
col
int RTFGenerator::col private
Definition at line 281 of file rtfgen.h.
Referenced by codify(), RTFGenerator(), and startCodeLine().
m_bstartedBody
bool RTFGenerator::m_bstartedBody private
Definition at line 284 of file rtfgen.h.
Referenced by RTFGenerator().
m_listLevel
int RTFGenerator::m_listLevel private
Definition at line 285 of file rtfgen.h.
Referenced by decrementIndentLevel(), endItemList(), incrementIndentLevel(), rtf_BList_DepthStyle(), rtf_CList_DepthStyle(), rtf_Code_DepthStyle(), rtf_DList_DepthStyle(), rtf_EList_DepthStyle(), rtf_LCList_DepthStyle(), RTFGenerator(), startIndexSection(), startItemList(), and startItemListItem().
m_numCols
int RTFGenerator::m_numCols private
Definition at line 287 of file rtfgen.h.
Referenced by RTFGenerator().
m_omitParagraph
bool RTFGenerator::m_omitParagraph private
Definition at line 286 of file rtfgen.h.
Referenced by docify(), endCodeFragment(), endConstraintList(), endIndexItem(), endIndexList(), endIndexValue(), endItemList(), endParagraph(), endParamList(), endSection(), endSimpleSect(), lineBreak(), newParagraph(), RTFGenerator(), startIndexItem(), startIndexList(), startItemListItem(), and writeDoc().
m_prettyCode
bool RTFGenerator::m_prettyCode private
Definition at line 282 of file rtfgen.h.
Referenced by endIndexSection(), and RTFGenerator().
relPath
QCString RTFGenerator::relPath private
Definition at line 288 of file rtfgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endInclDepGraph(), and startFile().
The documentation for this class was generated from the following files:
src/rtfgen.h
src/rtfgen.cpp