Doxygen: UsedDir Class Reference
UsedDir Class Reference
Usage information of a directory.
#include <dirdef.h>
Public Member Functions
UsedDir (DirDef *dir, bool inherited)
virtual ~UsedDir ()
void addFileDep (FileDef *srcFd, FileDef *dstFd)
FilePair * findFilePair (const char *name)
const FilePairDict & filePairs () const
const DirDef * dir () const
bool inherited () const
void sort ()
Private Attributes
DirDef * m_dir
FilePairDict m_filePairs
bool m_inherited
Detailed Description
Usage information of a directory.
Definition at line 132 of file dirdef.h.
Constructor & Destructor Documentation
UsedDir()
UsedDir::UsedDir (DirDef * dir, bool inherited)
Definition at line 673 of file dirdef.cpp.
References m_filePairs, and SDict< T >::setAutoDelete().
~UsedDir()
UsedDir::~UsedDir () virtual
Definition at line 679 of file dirdef.cpp.
Member Function Documentation
addFileDep()
void UsedDir::addFileDep (FileDef * srcFd, FileDef * dstFd)
Definition at line 684 of file dirdef.cpp.
References SDict< T >::append(), FileDef::getOutputFileBase(), and m_filePairs.
Referenced by DirDef::addUsesDependency().
dir()
const DirDef* UsedDir::dir () const inline
Definition at line 140 of file dirdef.h.
References m_dir.
Referenced by DirRelation::writeDocumentation().
filePairs()
const FilePairDict& UsedDir::filePairs () const inline
Definition at line 139 of file dirdef.h.
References m_filePairs.
Referenced by DirRelation::writeDocumentation().
findFilePair()
FilePair * UsedDir::findFilePair (const char * name)
Definition at line 695 of file dirdef.cpp.
References SDict< T >::find(), and m_filePairs.
Referenced by DirDef::addUsesDependency().
inherited()
bool UsedDir::inherited () const inline
Definition at line 141 of file dirdef.h.
References m_inherited.
sort()
void UsedDir::sort ()
Definition at line 690 of file dirdef.cpp.
References m_filePairs, and SDict< T >::sort().
Referenced by DirDef::computeDependencies().
Member Data Documentation
m_dir
DirDef* UsedDir::m_dir private
Definition at line 145 of file dirdef.h.
Referenced by dir().
m_filePairs
FilePairDict UsedDir::m_filePairs private
Definition at line 146 of file dirdef.h.
Referenced by addFileDep(), filePairs(), findFilePair(), sort(), and UsedDir().
m_inherited
bool UsedDir::m_inherited private
Definition at line 147 of file dirdef.h.
Referenced by inherited().
The documentation for this class was generated from the following files:
src/dirdef.h
src/dirdef.cpp