Doxygen: FTVHelp Class Reference
FTVHelp Class Reference
A class that generates a dynamic tree view side panel.
#include <ftvhelp.h>
Public Member Functions
FTVHelp (bool LTI)
~FTVHelp ()
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const char *name, const char *ref, const char *file, const char *anchor, bool separateIndex, bool addToNavIndex, Definition *def)
void addIndexItem (Definition *, MemberDef *, const char *, const char *)
void addIndexFile (const char *)
void addImageFile (const char *)
void addStyleSheetFile (const char *)
void generateTreeView ()
void generateTreeViewInline (FTextStream &t)
void generateTreeViewScripts ()
Public Member Functions inherited from IndexIntf
virtual ~IndexIntf ()
Static Public Member Functions
static void generateTreeViewImages ()
Private Member Functions
void generateTree (FTextStream &t, const QList< FTVNode > &nl, int level, int maxLevel, int &index)
QCString generateIndentLabel (FTVNode *n, int level)
void generateIndent (FTextStream &t, FTVNode *n, bool opened)
void generateLink (FTextStream &t, FTVNode *n)
Private Attributes
QList< FTVNode > * m_indentNodes
int m_indent
bool m_topLevelIndex
Detailed Description
A class that generates a dynamic tree view side panel.
Definition at line 37 of file ftvhelp.h.
Constructor & Destructor Documentation
FTVHelp()
FTVHelp::FTVHelp (bool TLI)
Constructs an ftv help object. The object has to be initialized before it can be used.
Definition at line 106 of file ftvhelp.cpp.
References m_indent, m_indentNodes, m_topLevelIndex, and MAX_INDENT.
~FTVHelp()
FTVHelp::~FTVHelp ()
Destroys the ftv help object.
Definition at line 116 of file ftvhelp.cpp.
References m_indentNodes.
Member Function Documentation
addContentsItem()
void FTVHelp::addContentsItem (bool isDir, const char * name, const char * ref, const char * file, const char * anchor, bool separateIndex, bool addToNavIndex, Definition * def) virtual
Add a list item to the contents file.
Parameters
isDir TRUE if the item is a directory, FALSE if it is a text
name The name of the item.
ref the URL of to the item.
file the file containing the definition of the item
anchor the anchor within the file.
name the name of the item.
separateIndex put the entries in a separate index file
addToNavIndex add this entry to the quick navigation index
def Definition corresponding to this entry
Implements IndexIntf.
Definition at line 183 of file ftvhelp.cpp.
References FTVNode::index, m_indent, m_indentNodes, and FTVNode::parent.
Referenced by writeClassTree(), writeClassTreeForList(), writeDirHierarchy(), writeDirTreeNode(), writeGroupTreeNode(), writeNamespaceTree(), and writePages().
addImageFile()
void FTVHelp::addImageFile (const char *) inline virtual
Implements IndexIntf.
Definition at line 56 of file ftvhelp.h.
addIndexFile()
void FTVHelp::addIndexFile (const char *) inline virtual
Implements IndexIntf.
Definition at line 55 of file ftvhelp.h.
addIndexItem()
void FTVHelp::addIndexItem (Definition * , MemberDef * , const char * , const char *) inline virtual
Implements IndexIntf.
Definition at line 54 of file ftvhelp.h.
addStyleSheetFile()
void FTVHelp::addStyleSheetFile (const char *) inline virtual
Implements IndexIntf.
Definition at line 57 of file ftvhelp.h.
decContentsDepth()
void FTVHelp::decContentsDepth () virtual
Decrease the level of the contents hierarchy. This will end the current sublist.
See also
incContentsDepth()
Implements IndexIntf.
Definition at line 152 of file ftvhelp.cpp.
References FTVNode::children, m_indent, and m_indentNodes.
Referenced by writeClassTree(), writeDirTreeNode(), writeGroupTreeNode(), writeNamespaceTree(), and writePages().
finalize()
void FTVHelp::finalize () virtual
Finalizes the FTV help. This will finish and close the contents file (index.js).
See also
initialize()
Implements IndexIntf.
Definition at line 132 of file ftvhelp.cpp.
References generateTreeView().
generateIndent()
void FTVHelp::generateIndent (FTextStream & t, FTVNode * n, bool opened) private
Definition at line 253 of file ftvhelp.cpp.
References generateIndentLabel(), FTVNode::isDir, and FTVNode::parent.
Referenced by generateTree().
generateIndentLabel()
QCString FTVHelp::generateIndentLabel (FTVNode * n, int level) private
Definition at line 242 of file ftvhelp.cpp.
References FTVNode::index, and FTVNode::parent.
Referenced by generateIndent(), and generateTree().
generateLink()
void FTVHelp::generateLink (FTextStream & t, FTVNode * n) private
Definition at line 273 of file ftvhelp.cpp.
References convertToHtml(), externalLinkTarget(), externalRef(), FTVNode::file, m_topLevelIndex, FTVNode::name, node2URL(), and FTVNode::ref.
Referenced by generateTree().
generateTree()
void FTVHelp::generateTree (FTextStream & t, const QList< FTVNode > & nl, int level, int maxLevel, int & index) private
Definition at line 325 of file ftvhelp.cpp.
References FTVNode::children, FTVNode::def, DefinitionIntf::definitionType(), endl(), folderId, generateBriefDoc(), generateIndent(), generateIndentLabel(), generateLink(), FileDef::getSourceFileBase(), Doxygen::htmlFileExtension, FTVNode::isDir, DefinitionIntf::TypeClass, DefinitionIntf::TypeFile, DefinitionIntf::TypeGroup, DefinitionIntf::TypeNamespace, and DefinitionIntf::TypePage.
Referenced by generateTreeViewInline().
generateTreeView()
void FTVHelp::generateTreeView ()
Definition at line 793 of file ftvhelp.cpp.
References generateTreeViewImages(), and generateTreeViewScripts().
Referenced by finalize().
generateTreeViewImages()
void FTVHelp::generateTreeViewImages () static
Definition at line 706 of file ftvhelp.cpp.
References Config_getString, ResourceMgr::copyResource(), and ResourceMgr::instance().
Referenced by generateOutput(), and generateTreeView().
generateTreeViewInline()
void FTVHelp::generateTreeViewInline (FTextStream & t)
Definition at line 730 of file ftvhelp.cpp.
References FTVNode::children, FTVNode::computeTreeDepth(), Config_getInt, generateTree(), m_indentNodes, FTVNode::numNodesAtLevel(), theTranslator, and Translator::trDetailLevel().
Referenced by writeAnnotatedIndex(), writeFileIndex(), writeGroupIndex(), writeHierarchicalIndex(), writeNamespaceIndex(), and writePageIndex().
generateTreeViewScripts()
void FTVHelp::generateTreeViewScripts ()
Definition at line 717 of file ftvhelp.cpp.
References Config_getString, ResourceMgr::copyResource(), generateJSNavTree(), ResourceMgr::instance(), and m_indentNodes.
Referenced by generateTreeView().
incContentsDepth()
void FTVHelp::incContentsDepth () virtual
Increase the level of the contents hierarchy. This will start a new sublist in contents file.
See also
decContentsDepth()
Implements IndexIntf.
Definition at line 141 of file ftvhelp.cpp.
References m_indent, and MAX_INDENT.
Referenced by writeClassTree(), writeDirTreeNode(), writeGroupTreeNode(), writeNamespaceTree(), and writePages().
initialize()
void FTVHelp::initialize () virtual
This will create a folder tree view table of contents file (tree.js).
See also
finalize()
Implements IndexIntf.
Definition at line 124 of file ftvhelp.cpp.
Member Data Documentation
m_indent
int FTVHelp::m_indent private
Definition at line 71 of file ftvhelp.h.
Referenced by addContentsItem(), decContentsDepth(), FTVHelp(), and incContentsDepth().
m_indentNodes
QList<FTVNode>* FTVHelp::m_indentNodes private
Definition at line 70 of file ftvhelp.h.
Referenced by addContentsItem(), decContentsDepth(), FTVHelp(), generateTreeViewInline(), generateTreeViewScripts(), and ~FTVHelp().
m_topLevelIndex
bool FTVHelp::m_topLevelIndex private
Definition at line 72 of file ftvhelp.h.
Referenced by FTVHelp(), and generateLink().
The documentation for this class was generated from the following files:
src/ftvhelp.h
src/ftvhelp.cpp