Doxygen: SymbolIndexContext::Private Class Reference
SymbolIndexContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const SearchIndexList *sl, const QCString &name)
TemplateVariant get (const char *n) const
TemplateVariant name () const
TemplateVariant letter () const
TemplateVariant symbolGroups () const
Private Attributes
const SearchIndexList * m_searchList
QCString m_name
Cachable m_cache
Static Private Attributes
static PropertyMapper< SymbolIndexContext::Private > s_inst
Detailed Description
Definition at line 9740 of file context.cpp.
Constructor & Destructor Documentation
Private()
SymbolIndexContext::Private::Private (const SearchIndexList * sl, const QCString & name) inline
Definition at line 9743 of file context.cpp.
References PropertyMapper< T >::addProperty(), Config::init(), letter(), name(), s_inst, and symbolGroups().
Member Function Documentation
get()
TemplateVariant SymbolIndexContext::Private::get (const char * n) const inline
Definition at line 9754 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by SymbolIndexContext::get().
letter()
TemplateVariant SymbolIndexContext::Private::letter () const inline
Definition at line 9762 of file context.cpp.
References SearchIndexList::letter(), and m_searchList.
Referenced by Private().
name()
TemplateVariant SymbolIndexContext::Private::name () const inline
Definition at line 9758 of file context.cpp.
References m_name.
Referenced by Private().
symbolGroups()
TemplateVariant SymbolIndexContext::Private::symbolGroups () const inline
Definition at line 9766 of file context.cpp.
References SymbolGroupListContext::alloc(), SharedPtr< T >::get(), m_cache, m_searchList, SharedPtr< T >::reset(), and SymbolIndexContext::Private::Cachable::symbolGroups.
Referenced by Private().
Member Data Documentation
m_cache
Cachable SymbolIndexContext::Private::m_cache mutable private
Definition at line 9781 of file context.cpp.
Referenced by symbolGroups().
m_name
QCString SymbolIndexContext::Private::m_name private
Definition at line 9776 of file context.cpp.
Referenced by name().
m_searchList
const SearchIndexList* SymbolIndexContext::Private::m_searchList private
Definition at line 9775 of file context.cpp.
Referenced by letter(), and symbolGroups().
s_inst
PropertyMapper< SymbolIndexContext::Private > SymbolIndexContext::Private::s_inst static private
Definition at line 9782 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp