Doxygen: ClassHierarchyContext Class Reference
ClassHierarchyContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static ClassHierarchyContext * alloc ()
Private Member Functions
ClassHierarchyContext ()
~ClassHierarchyContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 490 of file context.h.
Constructor & Destructor Documentation
ClassHierarchyContext()
ClassHierarchyContext::ClassHierarchyContext () private
Definition at line 6070 of file context.cpp.
References p, and Private.
Referenced by alloc().
~ClassHierarchyContext()
ClassHierarchyContext::~ClassHierarchyContext () private
Definition at line 6075 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int ClassHierarchyContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 497 of file context.h.
References RefCountedContext::addRef().
alloc()
static ClassHierarchyContext* ClassHierarchyContext::alloc () inline static
Definition at line 493 of file context.h.
References ClassHierarchyContext().
Referenced by generateOutputViaTemplate().
get()
TemplateVariant ClassHierarchyContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 6080 of file context.cpp.
References ClassHierarchyContext::Private::get(), and p.
release()
virtual int ClassHierarchyContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 498 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ClassHierarchyContext::p private
Definition at line 503 of file context.h.
Referenced by ClassHierarchyContext(), get(), and ~ClassHierarchyContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp