Doxygen: ConfigContext::Private Class Reference
ConfigContext::Private Class Reference
Public Member Functions
Private ()
virtual ~Private ()
TemplateVariant fetchList (const QCString &name, const QStrList *list)
Private Attributes
QDict< TemplateVariant > m_cachedLists
Detailed Description
Definition at line 290 of file context.cpp.
Constructor & Destructor Documentation
Private()
ConfigContext::Private::Private () inline
Definition at line 293 of file context.cpp.
References m_cachedLists.
~Private()
virtual ConfigContext::Private::~Private () inline virtual
Definition at line 294 of file context.cpp.
Member Function Documentation
fetchList()
TemplateVariant ConfigContext::Private::fetchList (const QCString & name, const QStrList * list) inline
Definition at line 295 of file context.cpp.
References TemplateList::alloc(), TemplateList::append(), and m_cachedLists.
Referenced by ConfigContext::get().
Member Data Documentation
m_cachedLists
QDict<TemplateVariant> ConfigContext::Private::m_cachedLists private
Definition at line 316 of file context.cpp.
Referenced by fetchList(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp