Doxygen: src/markdown.cpp File Reference
markdown.cpp File Reference
#include <stdio.h>
#include <qglobal.h>
#include <qregexp.h>
#include <qfileinfo.h>
#include <qdict.h>
#include <qvector.h>
#include "markdown.h"
#include "growbuf.h"
#include "debug.h"
#include "util.h"
#include "doxygen.h"
#include "commentscan.h"
#include "entry.h"
#include "bufstr.h"
#include "commentcnv.h"
#include "config.h"
#include "section.h"
#include "message.h"
Classes
struct LinkRef
struct TableCell
Macros
#define USE_ORIGINAL_TABLES
#define isIdChar(i)
#define extraChar(i)
#define isOpenEmphChar(i)
#define ignoreCloseEmphChar(i)
#define isLiTag(i)
Typedefs
typedef int(* action_t) (GrowBuf &out, const char *data, int offset, int size)
Enumerations
enum Alignment { AlignNone, AlignLeft, AlignCenter, AlignRight }
Functions
static QDict< LinkRef > g_linkRefs (257)
static void processInline (GrowBuf &out, const char *data, int size)
static QCString escapeSpecialChars (const QCString &s)
static void convertStringFragment (QCString &result, const char *data, int size)
static Alignment markersToAlignment (bool leftMarker, bool rightMarker)
helper function to convert presence of left and/or right alignment markers to a alignment value
static QCString isBlockCommand (const char *data, int offset, int size)
static int findEmphasisChar (const char *data, int size, char c, int c_size)
looks for the next emph char, skipping other constructs, and stopping when either it is found, or we are at the end of a paragraph.
static int processEmphasis1 (GrowBuf &out, const char *data, int size, char c)
process single emphasis
static int processEmphasis2 (GrowBuf &out, const char *data, int size, char c)
process double emphasis
static int processEmphasis3 (GrowBuf &out, const char *data, int size, char c)
Parsing tripple emphasis.
static int processNmdash (GrowBuf &out, const char *data, int off, int size)
Process ndash and mdashes.
static int processQuoted (GrowBuf &out, const char *data, int, int size)
Process quoted section "...", can contain one embedded newline.
static int processHtmlTag (GrowBuf &out, const char *data, int offset, int size)
Process a HTML tag.
static int processEmphasis (GrowBuf &out, const char *data, int offset, int size)
static int processLink (GrowBuf &out, const char *data, int, int size)
static int processCodeSpan (GrowBuf &out, const char *data, int, int size)
'`' parsing a code span (assuming codespan != 0)
static int processSpecialCommand (GrowBuf &out, const char *data, int offset, int size)
static int isHeaderline (const char *data, int size)
returns whether the line is a setext-style hdr underline
static bool isBlockQuote (const char *data, int size, int indent)
returns TRUE if this line starts a block quote
static int isLinkRef (const char *data, int size, QCString &refid, QCString &link, QCString &title)
returns end of the link ref if this is indeed a link reference.
static int isHRuler (const char *data, int size)
static QCString extractTitleId (QCString &title, int level)
static int isAtxHeader (const char *data, int size, QCString &header, QCString &id)
static int isEmptyLine (const char *data, int size)
static int computeIndentExcludingListMarkers (const char *data, int size)
static bool isFencedCodeBlock (const char *data, int size, int refIndent, QCString &lang, int &start, int &end, int &offset)
static bool isCodeBlock (const char *data, int offset, int size, int &indent)
int findTableColumns (const char *data, int size, int &start, int &end, int &columns)
Finds the location of the table's contains in the string data.
static bool isTableBlock (const char *data, int size)
Returns TRUE iff data points to the start of a table block.
static int writeTableBlock (GrowBuf &out, const char *data, int size)
void writeOneLineHeaderOrRuler (GrowBuf &out, const char *data, int size)
static int writeBlockQuote (GrowBuf &out, const char *data, int size)
static int writeCodeBlock (GrowBuf &out, const char *data, int size, int refIndent)
static void findEndOfLine (GrowBuf &out, const char *data, int size, int &pi, int &i, int &end)
static void writeFencedCodeBlock (GrowBuf &out, const char *data, const char *lng, int blockStart, int blockEnd)
static QCString processQuotations (const QCString &s, int refIndent)
static QCString processBlocks (const QCString &s, int indent)
static bool isExplicitPage (const QCString &docs)
returns TRUE if input string docs starts with @page or @mainpage command
static QCString extractPageTitle (QCString &docs, QCString &id)
static QCString detab (const QCString &s, int &refIndent)
QCString processMarkdown (const QCString &fileName, const int lineNr, Entry *e, const QCString &input)
processes string s and converts markdown into doxygen/html commands.
QCString markdownFileNameToId (const QCString &fileName)
Variables
static action_t g_actions [256]
static Entry * g_current
static QCString g_fileName
static int g_lineNr
const int codeBlockIndent = 4
Macro Definition Documentation
extraChar
#define extraChar (i)
Value:
(data[i]=='-' || data[i]=='+' || data[i]=='!' || \
   data[i]=='?' || data[i]=='$' || data[i]=='@' || \
   data[i]=='&' || data[i]=='*' || data[i]=='%')
Definition at line 64 of file markdown.cpp.
Referenced by processEmphasis().
ignoreCloseEmphChar
#define ignoreCloseEmphChar (i)
Value:
(data[i]=='('  || data[i]=='{' || data[i]=='[' || data[i]=='<' || \
   data[i]=='='  || data[i]=='+' || data[i]=='-' || data[i]=='\\' || \
   data[i]=='@')
Definition at line 77 of file markdown.cpp.
Referenced by findEmphasisChar().
isIdChar
#define isIdChar (i)
Value:
((data[i]>='a' && data[i]<='z') || \
   (data[i]>='A' && data[i]<='Z') || \
   (data[i]>='0' && data[i]<='9') || \
   (((unsigned char)data[i])>=0x80))
Definition at line 58 of file markdown.cpp.
Referenced by findEmphasisChar(), processCodeSpan(), processEmphasis(), and processHtmlTag().
isLiTag
#define isLiTag (i)
Value:
(data[(i)]=='<' && \
   (data[(i)+1]=='l' || data[(i)+1]=='L') && \
   (data[(i)+2]=='i' || data[(i)+2]=='I') && \
   (data[(i)+3]=='>'))
Definition at line 1321 of file markdown.cpp.
Referenced by computeIndentExcludingListMarkers().
isOpenEmphChar
#define isOpenEmphChar (i)
Value:
(data[i]=='\n' || data[i]==' ' || data[i]=='\'' || data[i]=='<' || \
   data[i]=='{'  || data[i]=='(' || data[i]=='['  || data[i]==',' || \
   data[i]==':'  || data[i]==';')
Definition at line 70 of file markdown.cpp.
Referenced by processEmphasis().
USE_ORIGINAL_TABLES
#define USE_ORIGINAL_TABLES
Definition at line 40 of file markdown.cpp.
Typedef Documentation
action_t
typedef int(* action_t) (GrowBuf &out, const char *data, int offset, int size)
Definition at line 98 of file markdown.cpp.
Enumeration Type Documentation
Alignment
enum Alignment
Enumerator
AlignNone
AlignLeft
AlignCenter
AlignRight
Definition at line 100 of file markdown.cpp.
Function Documentation
computeIndentExcludingListMarkers()
static int computeIndentExcludingListMarkers (const char * data, int size) static
Definition at line 1329 of file markdown.cpp.
References isLiTag.
Referenced by isCodeBlock().
convertStringFragment()
static void convertStringFragment (QCString & result, const char * data, int size) static
Definition at line 149 of file markdown.cpp.
Referenced by extractPageTitle(), isAtxHeader(), isBlockCommand(), isFencedCodeBlock(), isLinkRef(), processBlocks(), processCodeSpan(), processHtmlTag(), and processLink().
detab()
static QCString detab (const QCString & s, int & refIndent) static
Definition at line 2443 of file markdown.cpp.
References GrowBuf::addChar(), Config_getInt, and GrowBuf::get().
Referenced by processMarkdown().
escapeSpecialChars()
static QCString escapeSpecialChars (const QCString & s) static
Definition at line 125 of file markdown.cpp.
References GrowBuf::addChar(), and GrowBuf::get().
Referenced by processCodeSpan().
extractPageTitle()
static QCString extractPageTitle (QCString & docs, QCString & id) static
Definition at line 2400 of file markdown.cpp.
References convertStringFragment(), extractTitleId(), isAtxHeader(), and isHeaderline().
Referenced by MarkdownFileParser::parseInput().
extractTitleId()
static QCString extractTitleId (QCString & title, int level) static
Definition at line 1246 of file markdown.cpp.
References Config_getInt.
Referenced by extractPageTitle(), isAtxHeader(), and processBlocks().
findEmphasisChar()
static int findEmphasisChar (const char * data, int size, char c, int c_size) static
looks for the next emph char, skipping other constructs, and stopping when either it is found, or we are at the end of a paragraph.
Definition at line 254 of file markdown.cpp.
References ignoreCloseEmphChar, isBlockCommand(), and isIdChar.
Referenced by processEmphasis1(), processEmphasis2(), and processEmphasis3().
findEndOfLine()
static void findEndOfLine (GrowBuf & out, const char * data, int size, int & pi, int & i, int & end) static
Definition at line 2054 of file markdown.cpp.
References GrowBuf::addStr(), isBlockCommand(), and processHtmlTag().
Referenced by processBlocks(), and processQuotations().
findTableColumns()
int findTableColumns (const char * data, int size, int & start, int & end, int & columns)
Finds the location of the table's contains in the string data.
Only one line will be inspected.
Parameters
[in] data pointer to the string buffer.
[in] size the size of the buffer.
[out] start offset of the first character of the table content
[out] end offset of the last character of the table content
[out] columns number of table columns found
Returns
The offset until the next line in the buffer.
Definition at line 1511 of file markdown.cpp.
References eol.
Referenced by isTableBlock(), and writeTableBlock().
g_linkRefs()
static QDict<LinkRef> g_linkRefs (257) static
Referenced by processBlocks(), processLink(), and processMarkdown().
isAtxHeader()
static int isAtxHeader (const char * data, int size, QCString & header, QCString & id) static
Definition at line 1272 of file markdown.cpp.
References convertStringFragment(), and extractTitleId().
Referenced by extractPageTitle(), and writeOneLineHeaderOrRuler().
isBlockCommand()
static QCString isBlockCommand (const char * data, int offset, int size) static
Definition at line 200 of file markdown.cpp.
References convertStringFragment().
Referenced by findEmphasisChar(), findEndOfLine(), and processSpecialCommand().
isBlockQuote()
static bool isBlockQuote (const char * data, int size, int indent) static
returns TRUE if this line starts a block quote
Definition at line 1104 of file markdown.cpp.
References codeBlockIndent.
Referenced by processQuotations().
isCodeBlock()
static bool isCodeBlock (const char * data, int offset, int size, int & indent) static
Definition at line 1435 of file markdown.cpp.
References codeBlockIndent, computeIndentExcludingListMarkers(), and isEmptyLine().
Referenced by processBlocks().
isEmptyLine()
static int isEmptyLine (const char * data, int size) static
Definition at line 1309 of file markdown.cpp.
Referenced by isCodeBlock().
isExplicitPage()
static bool isExplicitPage (const QCString & docs) static
returns TRUE if input string docs starts with @page or @mainpage command
Definition at line 2378 of file markdown.cpp.
Referenced by MarkdownFileParser::parseInput().
isFencedCodeBlock()
static bool isFencedCodeBlock (const char * data, int size, int refIndent, QCString & lang, int & start, int & end, int & offset) static
Definition at line 1396 of file markdown.cpp.
References convertStringFragment().
Referenced by processBlocks(), and processQuotations().
isHeaderline()
static int isHeaderline (const char * data, int size) static
returns whether the line is a setext-style hdr underline
Definition at line 1081 of file markdown.cpp.
Referenced by extractPageTitle(), and processBlocks().
isHRuler()
static int isHRuler (const char * data, int size) static
Definition at line 1219 of file markdown.cpp.
Referenced by writeOneLineHeaderOrRuler().
isLinkRef()
static int isLinkRef (const char * data, int size, QCString & refid, QCString & link, QCString & title) static
returns end of the link ref if this is indeed a link reference.
Definition at line 1129 of file markdown.cpp.
References convertStringFragment(), and eol.
Referenced by processBlocks().
isTableBlock()
static bool isTableBlock (const char * data, int size) static
Returns TRUE iff data points to the start of a table block.
Definition at line 1550 of file markdown.cpp.
References findTableColumns().
Referenced by processBlocks().
markdownFileNameToId()
QCString markdownFileNameToId (const QCString & fileName)
Definition at line 2546 of file markdown.cpp.
References stripFromPath(), and substitute().
Referenced by DocRef::DocRef(), and MarkdownFileParser::parseInput().
markersToAlignment()
static Alignment markersToAlignment (bool leftMarker, bool rightMarker) static
helper function to convert presence of left and/or right alignment markers to a alignment value
Definition at line 160 of file markdown.cpp.
References AlignCenter, AlignLeft, AlignNone, and AlignRight.
Referenced by writeTableBlock().
processBlocks()
static QCString processBlocks (const QCString & s, int indent) static
Definition at line 2213 of file markdown.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), Entry::anchors, SDict< T >::append(), codeBlockIndent, convertStringFragment(), extractTitleId(), SectionInfo::fileName, SDict< T >::find(), findEndOfLine(), g_fileName, g_lineNr, g_linkRefs(), GrowBuf::get(), isCodeBlock(), isFencedCodeBlock(), isHeaderline(), isLinkRef(), isTableBlock(), SectionInfo::lineNr, SectionInfo::Section, Doxygen::sectionDict, SectionInfo::Subsection, warn(), writeCodeBlock(), writeFencedCodeBlock(), writeOneLineHeaderOrRuler(), and writeTableBlock().
Referenced by processMarkdown().
processCodeSpan()
static int processCodeSpan (GrowBuf & out, const char * data, int , int size) static
'`' parsing a code span (assuming codespan != 0)
Definition at line 935 of file markdown.cpp.
References GrowBuf::addStr(), convertStringFragment(), escapeSpecialChars(), and isIdChar.
Referenced by processMarkdown().
processEmphasis()
static int processEmphasis (GrowBuf & out, const char * data, int offset, int size) static
Definition at line 606 of file markdown.cpp.
References extraChar, isIdChar, isOpenEmphChar, processEmphasis1(), processEmphasis2(), and processEmphasis3().
Referenced by processMarkdown().
processEmphasis1()
static int processEmphasis1 (GrowBuf & out, const char * data, int size, char c) static
process single emphasis
Definition at line 352 of file markdown.cpp.
References GrowBuf::addStr(), findEmphasisChar(), and processInline().
Referenced by processEmphasis(), and processEmphasis3().
processEmphasis2()
static int processEmphasis2 (GrowBuf & out, const char * data, int size, char c) static
process double emphasis
Definition at line 383 of file markdown.cpp.
References GrowBuf::addStr(), findEmphasisChar(), and processInline().
Referenced by processEmphasis(), and processEmphasis3().
processEmphasis3()
static int processEmphasis3 (GrowBuf & out, const char * data, int size, char c) static
Parsing tripple emphasis.
Finds the first closing tag, and delegates to the other emph
Definition at line 412 of file markdown.cpp.
References GrowBuf::addStr(), findEmphasisChar(), processEmphasis1(), processEmphasis2(), and processInline().
Referenced by processEmphasis().
processHtmlTag()
static int processHtmlTag (GrowBuf & out, const char * data, int offset, int size) static
Process a HTML tag.
Note that
..
are treated specially, in the sense that all code inside is written unprocessed
Definition at line 522 of file markdown.cpp.
References GrowBuf::addStr(), convertStringFragment(), and isIdChar.
Referenced by findEndOfLine(), and processMarkdown().
processInline()
static void processInline (GrowBuf & out, const char * data, int size) static
Definition at line 1057 of file markdown.cpp.
References GrowBuf::addStr(), and g_actions.
Referenced by processEmphasis1(), processEmphasis2(), processEmphasis3(), processLink(), and processMarkdown().
processLink()
static int processLink (GrowBuf & out, const char * data, int , int size) static
Definition at line 648 of file markdown.cpp.
References GrowBuf::addStr(), convertStringFragment(), findFileDef(), g_linkRefs(), getLanguageFromFileName(), Doxygen::imageNameDict, LinkRef::link, processInline(), SrcLangExt_Markdown, Entry::stat, substitute(), and LinkRef::title.
Referenced by processMarkdown().
processMarkdown()
QCString processMarkdown (const QCString & fileName, const int lineNr, Entry * e, const QCString & s)
processes string s and converts markdown into doxygen/html commands.
Definition at line 2500 of file markdown.cpp.
References GrowBuf::addChar(), GrowBuf::clear(), detab(), g_actions, g_fileName, g_lineNr, g_linkRefs(), GrowBuf::get(), Config::init(), Debug::Markdown, Debug::print(), processBlocks(), processCodeSpan(), processEmphasis(), processHtmlTag(), processInline(), processLink(), processNmdash(), processQuotations(), processQuoted(), and processSpecialCommand().
processNmdash()
static int processNmdash (GrowBuf & out, const char * data, int off, int size) static
Process ndash and mdashes.
Definition at line 469 of file markdown.cpp.
References GrowBuf::addStr().
Referenced by processMarkdown().
processQuotations()
static QCString processQuotations (const QCString & s, int refIndent) static
Definition at line 2155 of file markdown.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), findEndOfLine(), GrowBuf::get(), isBlockQuote(), isFencedCodeBlock(), writeBlockQuote(), and writeFencedCodeBlock().
Referenced by processMarkdown().
processQuoted()
static int processQuoted (GrowBuf & out, const char * data, int , int size) static
Process quoted section "...", can contain one embedded newline.
Definition at line 501 of file markdown.cpp.
References GrowBuf::addStr().
Referenced by processMarkdown().
processSpecialCommand()
static int processSpecialCommand (GrowBuf & out, const char * data, int offset, int size) static
Definition at line 1013 of file markdown.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), and isBlockCommand().
Referenced by processMarkdown().
writeBlockQuote()
static int writeBlockQuote (GrowBuf & out, const char * data, int size) static
Definition at line 1947 of file markdown.cpp.
References GrowBuf::addStr().
Referenced by processQuotations().
writeCodeBlock()
static int writeCodeBlock (GrowBuf & out, const char * data, int size, int refIndent) static
Definition at line 2003 of file markdown.cpp.
References GrowBuf::addStr(), and codeBlockIndent.
Referenced by processBlocks().
writeFencedCodeBlock()
static void writeFencedCodeBlock (GrowBuf & out, const char * data, const char * lng, int blockStart, int blockEnd) static
Definition at line 2140 of file markdown.cpp.
References GrowBuf::addStr().
Referenced by processBlocks(), and processQuotations().
writeOneLineHeaderOrRuler()
void writeOneLineHeaderOrRuler (GrowBuf & out, const char * data, int size)
Definition at line 1871 of file markdown.cpp.
References GrowBuf::addStr(), SectionInfo::Anchor, Entry::anchors, SDict< T >::append(), SectionInfo::fileName, SDict< T >::find(), g_fileName, g_lineNr, isAtxHeader(), isHRuler(), SectionInfo::lineNr, SectionInfo::Paragraph, SectionInfo::Section, Doxygen::sectionDict, SectionInfo::Subsection, SectionInfo::Subsubsection, and warn().
Referenced by processBlocks().
writeTableBlock()
static int writeTableBlock (GrowBuf & out, const char * data, int size) static
Definition at line 1588 of file markdown.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), AlignCenter, AlignLeft, AlignNone, AlignRight, findTableColumns(), and markersToAlignment().
Referenced by processBlocks().
Variable Documentation
codeBlockIndent
const int codeBlockIndent = 4
Definition at line 120 of file markdown.cpp.
Referenced by isBlockQuote(), isCodeBlock(), processBlocks(), and writeCodeBlock().
g_actions
action_t g_actions[256] static
Definition at line 106 of file markdown.cpp.
Referenced by processInline(), and processMarkdown().
g_current
Entry* g_current static
Definition at line 107 of file markdown.cpp.
g_fileName
QCString g_fileName static
Definition at line 108 of file markdown.cpp.
Referenced by processBlocks(), processMarkdown(), and writeOneLineHeaderOrRuler().
g_lineNr
int g_lineNr static
Definition at line 109 of file markdown.cpp.
Referenced by processBlocks(), processMarkdown(), and writeOneLineHeaderOrRuler().