Doxygen: UsedFilesContext Class Reference
UsedFilesContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
void addFile (FileDef *fd)
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static UsedFilesContext * alloc (ClassDef *cd)
Private Member Functions
UsedFilesContext (ClassDef *cd)
~UsedFilesContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 186 of file context.h.
Constructor & Destructor Documentation
UsedFilesContext()
UsedFilesContext::UsedFilesContext (ClassDef * cd) private
Definition at line 7121 of file context.cpp.
References UsedFilesContext::Private::addFile(), p, Private, and ClassDef::usedFiles().
Referenced by alloc().
~UsedFilesContext()
UsedFilesContext::~UsedFilesContext () private
Definition at line 7135 of file context.cpp.
References p.
Member Function Documentation
addFile()
void UsedFilesContext::addFile (FileDef * fd)
Definition at line 7156 of file context.cpp.
References UsedFilesContext::Private::addFile(), and p.
addRef()
virtual int UsedFilesContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 195 of file context.h.
References RefCountedContext::addRef().
alloc()
static UsedFilesContext* UsedFilesContext::alloc (ClassDef * cd) inline static
Definition at line 189 of file context.h.
References UsedFilesContext().
Referenced by ClassContext::Private::usedFiles().
at()
TemplateVariant UsedFilesContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7146 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int UsedFilesContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 7141 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * UsedFilesContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7151 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int UsedFilesContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 196 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* UsedFilesContext::p private
Definition at line 204 of file context.h.
Referenced by addFile(), at(), count(), createIterator(), UsedFilesContext(), and ~UsedFilesContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp