Doxygen: PageDef Class Reference
PageDef Class Reference
A model of a page symbol.
#include <pagedef.h>
Public Member Functions
PageDef (const char *f, int l, const char *n, const char *d, const char *t)
~PageDef ()
void setFileName (const char *name)
void setShowToc (bool b)
DefType definitionType () const
bool isLinkableInProject () const
bool isLinkable () const
QCString getOutputFileBase () const
QCString anchor () const
void findSectionsInDocumentation ()
QCString title () const
GroupDef * getGroupDef () const
PageSDict * getSubPages () const
void addInnerCompound (Definition *d)
bool visibleInIndex () const
bool documentedPage () const
bool hasSubPages () const
bool hasParentPage () const
bool showToc () const
void setPageScope (Definition *d)
Definition * getPageScope () const
QCString displayName (bool=TRUE) const
void writeDocumentation (OutputList &ol)
void writeTagFile (FTextStream &)
Public Member Functions inherited from Definition
Definition (const char *defFileName, int defLine, int defColumn, const char *name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~Definition ()
const QCString & name () const
QCString localName () const
virtual QCString qualifiedName () const
QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
int docLine () const
QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
bool isHidden () const
bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
QCString externalReference (const QCString &relPath) const
int getStartBodyLine () const
int getEndBodyLine () const
FileDef * getBodyDef () const
SrcLangExt getLanguage () const
Returns the programming language this definition was written in.
GroupList * partOfGroups () const
bool isLinkableViaGroup () const
QList< ListItemInfo > * xrefListItems () const
virtual Definition * findInnerCompound (const char *name)
virtual Definition * getOuterScope () const
MemberSDict * getReferencesMembers () const
MemberSDict * getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
returns TRUE if this class has a brief description
QCString id () const
virtual void setName (const char *name)
void setId (const char *name)
virtual void setDocumentation (const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const char *b, const char *briefFile, int briefLine)
virtual void setInbodyDocumentation (const char *d, const char *docFile, int docLine)
void setReference (const char *r)
void addSectionsToDefinition (QList< SectionInfo > *anchorList)
void setBodySegment (int bls, int ble)
void setBodyDef (FileDef *fd)
void addSourceReferencedBy (MemberDef *d)
void addSourceReferences (MemberDef *d)
void setRefItems (const QList< ListItemInfo > *sli)
void mergeRefItems (Definition *d)
virtual void setOuterScope (Definition *d)
virtual void setHidden (bool b)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const char *scopeName)
void writeInlineCode (OutputList &ol, const char *scopeName)
void writeSourceRefs (OutputList &ol, const char *scopeName)
void writeSourceReffedBy (OutputList &ol, const char *scopeName)
void makePartOfGroup (GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
virtual void writeQuickMemberLinks (OutputList &, MemberDef *) const
virtual void writeSummaryLinks (OutputList &)
QCString pathFragment () const
void writeDocAnchorsToTagFile (FTextStream &)
void setLocalName (const QCString name)
void addSectionsToIndex ()
void writeToc (OutputList &ol)
void setCookie (Cookie *cookie)
Cookie * cookie () const
Public Member Functions inherited from DefinitionIntf
DefinitionIntf ()
virtual ~DefinitionIntf ()
Private Member Functions
void setNestingLevel (int l)
void writePageDocumentation (OutputList &ol)
Private Attributes
QCString m_fileName
QCString m_title
PageSDict * m_subPageDict
Definition * m_pageScope
int m_nestingLevel
bool m_showToc
Additional Inherited Members
Public Types inherited from DefinitionIntf
enum DefType {
TypeClass = 0, TypeFile = 1, TypeNamespace = 2, TypeMember = 3,
TypeGroup = 4, TypePackage = 5, TypePage = 6, TypeDir = 7,
TypeSymbolList = 8
}
Protected Member Functions inherited from Definition
Definition (const Definition &d)
Detailed Description
A model of a page symbol.
Definition at line 29 of file pagedef.h.
Constructor & Destructor Documentation
PageDef()
PageDef::PageDef (const char * f, int l, const char * n, const char * d, const char * t)
Definition at line 29 of file pagedef.cpp.
References convertNameToFile(), m_fileName, m_nestingLevel, m_pageScope, m_showToc, m_subPageDict, and Definition::setDocumentation().
~PageDef()
PageDef::~PageDef ()
Definition at line 41 of file pagedef.cpp.
References m_subPageDict.
Member Function Documentation
addInnerCompound()
void PageDef::addInnerCompound (Definition * d) virtual
Reimplemented from Definition.
Definition at line 70 of file pagedef.cpp.
References SDict< T >::append(), DefinitionIntf::definitionType(), m_nestingLevel, m_subPageDict, Doxygen::mainPage, Definition::name(), setNestingLevel(), Definition::setOuterScope(), and DefinitionIntf::TypePage.
Referenced by computePageRelations().
anchor()
QCString PageDef::anchor () const inline virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 52 of file pagedef.h.
definitionType()
DefType PageDef::definitionType () const inline virtual
Use this for dynamic inspection of the type of the derived class
Implements DefinitionIntf.
Definition at line 40 of file pagedef.h.
References DefinitionIntf::TypePage.
displayName()
QCString PageDef::displayName (bool includeScope = TRUE) const inline virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 65 of file pagedef.h.
References m_title, and Definition::name().
documentedPage()
bool PageDef::documentedPage () const
Definition at line 299 of file pagedef.cpp.
References getGroupDef(), and Definition::isReference().
Referenced by countRelatedPages().
findSectionsInDocumentation()
void PageDef::findSectionsInDocumentation ()
Definition at line 46 of file pagedef.cpp.
References Definition::docFile(), docFindSections(), and Definition::documentation().
Referenced by findSectionsInDocumentation().
getGroupDef()
GroupDef * PageDef::getGroupDef () const
Definition at line 51 of file pagedef.cpp.
References Definition::partOfGroups().
Referenced by addListReferences(), PageListContext::Private::addPages(), documentedPage(), LatexGenerator::endIndexSection(), generateDocbookForPage(), generatePageDocs(), generateXMLForPage(), getOutputFileBase(), ExampleListContext::Private::Private(), resolveLink(), resolveUserReferences(), visibleInIndex(), writeIndex(), and writeInnerPages().
getOutputFileBase()
QCString PageDef::getOutputFileBase () const virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 57 of file pagedef.cpp.
References getGroupDef(), GroupDef::getOutputFileBase(), and m_fileName.
Referenced by addListReferences(), addRelatedPage(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateDocbookForPage(), generateExampleDocs(), generateXMLForPage(), writeDocumentation(), writeExampleIndex(), writeIndex(), writeInnerPages(), writePages(), writeTagFile(), and GroupDef::writeTagFile().
getPageScope()
Definition* PageDef::getPageScope () const inline
Definition at line 64 of file pagedef.h.
References m_pageScope.
getSubPages()
PageSDict* PageDef::getSubPages () const inline
Definition at line 56 of file pagedef.h.
References m_subPageDict.
Referenced by NestingNodeContext::Private::addPages(), generateDocbookForPage(), generateXMLForPage(), and writePages().
hasParentPage()
bool PageDef::hasParentPage () const
Definition at line 88 of file pagedef.cpp.
References DefinitionIntf::definitionType(), Definition::getOuterScope(), and DefinitionIntf::TypePage.
Referenced by DocRef::DocRef(), generateDocbookForPage(), and writeIndex().
hasSubPages()
bool PageDef::hasSubPages () const
Definition at line 307 of file pagedef.cpp.
References SDict< T >::count(), and m_subPageDict.
Referenced by writePageDocumentation(), and writePages().
isLinkable()
bool PageDef::isLinkable () const inline virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 45 of file pagedef.h.
References isLinkableInProject(), and Definition::isReference().
Referenced by createJavascriptSearchIndex().
isLinkableInProject()
bool PageDef::isLinkableInProject () const inline virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 41 of file pagedef.h.
References Definition::isReference().
Referenced by isLinkable(), GroupDef::writeTagFile(), and writeTagFile().
setFileName()
void PageDef::setFileName (const char * name)
Definition at line 65 of file pagedef.cpp.
References m_fileName, and Definition::name().
Referenced by addRelatedPage(), buildExampleList(), findMainPage(), and generateOutputViaTemplate().
setNestingLevel()
void PageDef::setNestingLevel (int l) private
Definition at line 312 of file pagedef.cpp.
References m_nestingLevel.
Referenced by addInnerCompound().
setPageScope()
void PageDef::setPageScope (Definition * d) inline
Definition at line 63 of file pagedef.h.
References m_pageScope.
Referenced by addPageToContext().
setShowToc()
void PageDef::setShowToc (bool b)
Definition at line 317 of file pagedef.cpp.
References m_showToc.
Referenced by addRelatedPage(), and findMainPage().
showToc()
bool PageDef::showToc () const inline
Definition at line 62 of file pagedef.h.
References m_showToc.
title()
QCString PageDef::title () const inline
Definition at line 54 of file pagedef.h.
References m_title.
Referenced by addListReferences(), addRelatedPage(), createJavascriptSearchIndex(), LatexGenerator::endIndexSection(), findMainPage(), PerlModGenerator::generatePerlModForGroup(), generateXMLForPage(), SearchIndex::setCurrentDoc(), PageContext::Private::title(), validatingParseDoc(), writeDocumentation(), writeExampleIndex(), writeIndex(), writeInnerPages(), writePageDocumentation(), GroupDef::writePageDocumentation(), writePages(), and writeTagFile().
visibleInIndex()
bool PageDef::visibleInIndex () const
Definition at line 289 of file pagedef.cpp.
References Config_getBool, getGroupDef(), and Definition::isReference().
Referenced by countRelatedPages(), and writePages().
writeDocumentation()
void PageDef::writeDocumentation (OutputList & ol)
Definition at line 118 of file pagedef.cpp.
References IndexList::addIndexItem(), Config_getBool, OutputList::disable(), OutputList::disableAll(), OutputList::disableAllBut(), Definition::docFile(), Definition::docLine(), OutputList::enable(), OutputList::enableAll(), OutputList::endContents(), endFile(), endFileWithNavPath(), OutputList::endQuickIndices(), OutputList::endSection(), endTitle(), OutputList::endTitleHead(), escapeCharsInString(), filterTitle(), SDict< T >::find(), OutputList::generateDoc(), Definition::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, Definition::hasSections(), HLI_Pages, OutputGenerator::Html, Doxygen::indexList, SectionInfo::label, OutputGenerator::Latex, m_nestingLevel, m_showToc, OutputGenerator::Man, Definition::name(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, Doxygen::sectionDict, OutputList::startContents(), startFile(), startTitle(), OutputList::startTitleHead(), title(), SectionInfo::title, SectionInfo::type, Definition::writeNavigationPath(), writePageDocumentation(), and Definition::writeToc().
Referenced by generatePageDocs().
writePageDocumentation()
void PageDef::writePageDocumentation (OutputList & ol) private
Definition at line 222 of file pagedef.cpp.
References OutputList::disableAll(), OutputList::disableAllBut(), Definition::docFile(), Definition::docLine(), Definition::documentation(), OutputList::enable(), OutputList::endSection(), OutputList::endTextBlock(), OutputList::generateDoc(), Definition::getLanguage(), hasSubPages(), Definition::inbodyDocumentation(), SDict< PageDef >::Iterator, OutputGenerator::Latex, m_nestingLevel, m_subPageDict, OutputGenerator::Man, Doxygen::markdownSupport, Definition::name(), SectionInfo::Page, SectionInfo::Paragraph, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, SectionInfo::Section, SrcLangExt_Markdown, OutputList::startSection(), OutputList::startTextBlock(), Doxygen::subpageNestingLevel, SectionInfo::Subsection, SectionInfo::Subsubsection, title(), writePageDocumentation(), and OutputList::writeString().
Referenced by writeDocumentation(), and writePageDocumentation().
writeTagFile()
void PageDef::writeTagFile (FTextStream & tagFile)
Definition at line 94 of file pagedef.cpp.
References convertToXML(), endl(), getOutputFileBase(), RefList::listName(), Definition::name(), title(), Definition::writeDocAnchorsToTagFile(), and Doxygen::xrefLists.
Referenced by writeTagFile().
Member Data Documentation
m_fileName
QCString PageDef::m_fileName private
Definition at line 73 of file pagedef.h.
Referenced by getOutputFileBase(), PageDef(), and setFileName().
m_nestingLevel
int PageDef::m_nestingLevel private
Definition at line 77 of file pagedef.h.
Referenced by addInnerCompound(), PageDef(), setNestingLevel(), writeDocumentation(), and writePageDocumentation().
m_pageScope
Definition* PageDef::m_pageScope private
Definition at line 76 of file pagedef.h.
Referenced by getPageScope(), PageDef(), and setPageScope().
m_showToc
bool PageDef::m_showToc private
Definition at line 78 of file pagedef.h.
Referenced by PageDef(), setShowToc(), showToc(), and writeDocumentation().
m_subPageDict
PageSDict* PageDef::m_subPageDict private
Definition at line 75 of file pagedef.h.
Referenced by addInnerCompound(), getSubPages(), hasSubPages(), PageDef(), writePageDocumentation(), and ~PageDef().
m_title
QCString PageDef::m_title private
Definition at line 74 of file pagedef.h.
Referenced by displayName(), and title().
The documentation for this class was generated from the following files:
src/pagedef.h
src/pagedef.cpp