Doxygen: NamespaceDef Class Reference
NamespaceDef Class Reference
A model of a namespace symbol.
#include <namespacedef.h>
Public Member Functions
NamespaceDef (const char *defFileName, int defLine, int defColumn, const char *name, const char *ref=0, const char *refFile=0, const char *type=0, bool isPublished=false)
~NamespaceDef ()
DefType definitionType () const
QCString getOutputFileBase () const
QCString anchor () const
void insertUsedFile (FileDef *fd)
void writeDocumentation (OutputList &ol)
void writeMemberPages (OutputList &ol)
void writeQuickMemberLinks (OutputList &ol, MemberDef *currentMd) const
void writeTagFile (FTextStream &)
void insertClass (ClassDef *cd)
void insertNamespace (NamespaceDef *nd)
void insertMember (MemberDef *md)
void computeAnchors ()
int countMembers ()
void addUsingDirective (NamespaceDef *nd)
NamespaceSDict * getUsedNamespaces () const
void addUsingDeclaration (Definition *def)
SDict< Definition > * getUsedClasses () const
void combineUsingRelations ()
QCString displayName (bool=TRUE) const
QCString localName () const
bool isConstantGroup () const
bool isModule () const
bool isLibrary () const
bool isLinkableInProject () const
bool isLinkable () const
bool hasDetailedDescription () const
void addMembersToMemberGroup ()
void distributeMemberGroupDocumentation ()
void findSectionsInDocumentation ()
void sortMemberLists ()
virtual Definition * findInnerCompound (const char *name)
void addInnerCompound (Definition *d)
void addListReferences ()
void setFileName (const QCString &fn)
bool subGrouping () const
MemberList * getMemberList (MemberListType lt) const
const QList< MemberList > & getMemberLists () const
MemberDef * getMemberByName (const QCString &) const
MemberGroupSDict * getMemberGroupSDict () const
ClassSDict * getClassSDict () const
NamespaceSDict * getNamespaceSDict () const
QCString title () const
QCString compoundTypeString () const
Public Member Functions inherited from Definition
Definition (const char *defFileName, int defLine, int defColumn, const char *name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~Definition ()
const QCString & name () const
QCString localName () const
virtual QCString qualifiedName () const
QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
int docLine () const
QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
bool isHidden () const
bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
QCString externalReference (const QCString &relPath) const
int getStartBodyLine () const
int getEndBodyLine () const
FileDef * getBodyDef () const
SrcLangExt getLanguage () const
Returns the programming language this definition was written in.
GroupList * partOfGroups () const
bool isLinkableViaGroup () const
QList< ListItemInfo > * xrefListItems () const
virtual Definition * getOuterScope () const
MemberSDict * getReferencesMembers () const
MemberSDict * getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
returns TRUE if this class has a brief description
QCString id () const
virtual void setName (const char *name)
void setId (const char *name)
virtual void setDocumentation (const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const char *b, const char *briefFile, int briefLine)
virtual void setInbodyDocumentation (const char *d, const char *docFile, int docLine)
void setReference (const char *r)
void addSectionsToDefinition (QList< SectionInfo > *anchorList)
void setBodySegment (int bls, int ble)
void setBodyDef (FileDef *fd)
void addSourceReferencedBy (MemberDef *d)
void addSourceReferences (MemberDef *d)
void setRefItems (const QList< ListItemInfo > *sli)
void mergeRefItems (Definition *d)
virtual void setOuterScope (Definition *d)
virtual void setHidden (bool b)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const char *scopeName)
void writeInlineCode (OutputList &ol, const char *scopeName)
void writeSourceRefs (OutputList &ol, const char *scopeName)
void writeSourceReffedBy (OutputList &ol, const char *scopeName)
void makePartOfGroup (GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
QCString pathFragment () const
void writeDocAnchorsToTagFile (FTextStream &)
void setLocalName (const QCString name)
void addSectionsToIndex ()
void writeToc (OutputList &ol)
void setCookie (Cookie *cookie)
Cookie * cookie () const
Public Member Functions inherited from DefinitionIntf
DefinitionIntf ()
virtual ~DefinitionIntf ()
Public Attributes
bool visited
Private Types
enum { NAMESPACE, MODULE, CONSTANT_GROUP, LIBRARY }
Private Member Functions
MemberList * createMemberList (MemberListType lt)
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void writeClassDeclarations (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void writeNamespaceDeclarations (OutputList &ol, const QCString &title, bool isConstantGroup=false)
void writeMemberGroups (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeSummaryLinks (OutputList &ol)
void addNamespaceAttributes (OutputList &ol)
Private Attributes
QCString fileName
FileList files
NamespaceSDict * usingDirList
SDict< Definition > * usingDeclList
SDict< Definition > * m_innerCompounds
MemberSDict * m_allMembersDict
QList< MemberList > m_memberLists
MemberGroupSDict * memberGroupSDict
ClassSDict * classSDict
NamespaceSDict * namespaceSDict
bool m_subGrouping
enum NamespaceDef:: { ... } m_type
bool m_isPublished
Additional Inherited Members
Public Types inherited from DefinitionIntf
enum DefType {
TypeClass = 0, TypeFile = 1, TypeNamespace = 2, TypeMember = 3,
TypeGroup = 4, TypePackage = 5, TypePage = 6, TypeDir = 7,
TypeSymbolList = 8
}
Protected Member Functions inherited from Definition
Definition (const Definition &d)
Detailed Description
A model of a namespace symbol.
Definition at line 39 of file namespacedef.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
NAMESPACE
MODULE
CONSTANT_GROUP
LIBRARY
Definition at line 141 of file namespacedef.h.
Constructor & Destructor Documentation
NamespaceDef()
NamespaceDef::NamespaceDef (const char * defFileName, int defLine, int defColumn, const char * name, const char * ref = 0, const char * refFile = 0, const char * type = 0, bool isPublished = false)
Definition at line 36 of file namespacedef.cpp.
References classSDict, Config_getBool, CONSTANT_GROUP, convertNameToFile(), fileName, LIBRARY, m_allMembersDict, m_innerCompounds, m_subGrouping, m_type, memberGroupSDict, MODULE, NAMESPACE, namespaceSDict, SIntDict< T >::setAutoDelete(), setFileName(), Definition::setReference(), stripExtension(), usingDeclList, usingDirList, and visited.
~NamespaceDef()
NamespaceDef::~NamespaceDef ()
Definition at line 87 of file namespacedef.cpp.
References classSDict, m_allMembersDict, m_innerCompounds, memberGroupSDict, namespaceSDict, usingDeclList, and usingDirList.
Member Function Documentation
addInnerCompound()
void NamespaceDef::addInnerCompound (Definition * d) virtual
Reimplemented from Definition.
Definition at line 152 of file namespacedef.cpp.
References SDict< T >::append(), DefinitionIntf::definitionType(), insertClass(), insertNamespace(), Definition::localName(), m_innerCompounds, DefinitionIntf::TypeClass, and DefinitionIntf::TypeNamespace.
addListReferences()
void NamespaceDef::addListReferences ()
Definition at line 839 of file namespacedef.cpp.
References MemberList::addListReferences(), MemberGroup::addListReferences(), addRefItem(), displayName(), Definition::getLanguage(), getOutputFileBase(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_memberLists, memberGroupSDict, MemberListType_documentationLists, Definition::qualifiedName(), SrcLangExt_Fortran, theTranslator, Translator::trModule(), Translator::trNamespace(), and Definition::xrefListItems().
Referenced by addListReferences().
addMembersToMemberGroup()
void NamespaceDef::addMembersToMemberGroup ()
Definition at line 188 of file namespacedef.cpp.
References MemberGroup::addToDeclarationSection(), MemberGroup::allMembersInSameSection(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_memberLists, m_subGrouping, memberGroupSDict, and MemberListType_declarationLists.
Referenced by addMembersToMemberGroup().
addMemberToList()
void NamespaceDef::addMemberToList (MemberListType lt, MemberDef * md) private
Definition at line 1049 of file namespacedef.cpp.
References MemberList::append(), Config_getBool, createMemberList(), MemberList::inSort(), MemberList::listType(), MemberListType_declarationLists, MemberListType_documentationLists, MemberList::needsSorting(), MemberList::setNeedsSorting(), and MemberDef::setSectionList().
Referenced by insertMember().
addNamespaceAttributes()
void NamespaceDef::addNamespaceAttributes (OutputList & ol) private
Definition at line 555 of file namespacedef.cpp.
References OutputList::disableAllBut(), OutputList::endLabels(), Definition::getLanguage(), OutputGenerator::Html, isConstantGroup(), m_isPublished, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_IDL, OutputList::startLabels(), and OutputList::writeLabel().
Referenced by writeDocumentation().
addUsingDeclaration()
void NamespaceDef::addUsingDeclaration (Definition * def)
Definition at line 804 of file namespacedef.cpp.
References SDict< T >::append(), SDict< T >::find(), Definition::qualifiedName(), and usingDeclList.
Referenced by combineUsingRelations(), and findUsingDeclarations().
addUsingDirective()
void NamespaceDef::addUsingDirective (NamespaceDef * nd)
Definition at line 785 of file namespacedef.cpp.
References SDict< T >::append(), SDict< T >::find(), Definition::qualifiedName(), and usingDirList.
Referenced by combineUsingRelations(), and findUsingDirectives().
anchor()
QCString NamespaceDef::anchor () const inline virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 49 of file namespacedef.h.
Referenced by writeDocumentation().
combineUsingRelations()
void NamespaceDef::combineUsingRelations ()
Definition at line 895 of file namespacedef.cpp.
References addUsingDeclaration(), addUsingDirective(), combineUsingRelations(), getUsedClasses(), getUsedNamespaces(), SDict< NamespaceDef >::Iterator, usingDirList, and visited.
Referenced by combineUsingRelations(), FileDef::combineUsingRelations(), and combineUsingRelations().
compoundTypeString()
QCString NamespaceDef::compoundTypeString () const
Definition at line 1175 of file namespacedef.cpp.
References err_full(), Definition::getDefFileName(), Definition::getDefLine(), Definition::getLanguage(), isConstantGroup(), isLibrary(), isModule(), SrcLangExt_CSharp, SrcLangExt_Fortran, SrcLangExt_IDL, and SrcLangExt_Java.
Referenced by NamespaceContext::Private::compoundType(), and NamespaceSDict::writeDeclaration().
computeAnchors()
void NamespaceDef::computeAnchors ()
Definition at line 267 of file namespacedef.cpp.
References getMemberList(), MemberListType_allMembersList, and setAnchors().
Referenced by computeMemberReferences().
countMembers()
int NamespaceDef::countMembers ()
Definition at line 778 of file namespacedef.cpp.
References classSDict, SDict< T >::count(), MemberList::countDocMembers(), getMemberList(), MemberListType_allMembersList, and MemberList::numDocMembers().
createMemberList()
MemberList * NamespaceDef::createMemberList (MemberListType lt) private
Definition at line 1031 of file namespacedef.cpp.
References MemberList::listType(), and m_memberLists.
Referenced by addMemberToList().
definitionType()
DefType NamespaceDef::definitionType () const inline virtual
Use this for dynamic inspection of the type of the derived class
Implements DefinitionIntf.
Definition at line 47 of file namespacedef.h.
References DefinitionIntf::TypeNamespace.
displayName()
QCString NamespaceDef::displayName (bool includeScope = TRUE) const virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 871 of file namespacedef.cpp.
References Definition::getLanguage(), getLanguageSpecificSeparator(), localName(), Definition::name(), and substitute().
Referenced by addListReferences(), MemberDef::getScopeString(), MemberContext::Private::handleNameWithContextFor(), title(), NamespaceSDict::writeDeclaration(), writeDocumentation(), MemberDef::writeDocumentation(), MemberDef::writeLink(), writeMemberDocumentation(), writeMemberPages(), writeNamespaceIndex(), and writeNamespaceLinkForMember().
distributeMemberGroupDocumentation()
void NamespaceDef::distributeMemberGroupDocumentation ()
Definition at line 110 of file namespacedef.cpp.
References MemberGroup::distributeMemberGroupDocumentation(), SIntDict< MemberGroup >::Iterator, and memberGroupSDict.
Referenced by distributeMemberGroupDocumentation().
endMemberDeclarations()
void NamespaceDef::endMemberDeclarations (OutputList & ol) private
Definition at line 447 of file namespacedef.cpp.
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDocumentation()
void NamespaceDef::endMemberDocumentation (OutputList & ol) private
Definition at line 461 of file namespacedef.cpp.
References Config_getBool, OutputList::enable(), OutputGenerator::Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
findInnerCompound()
Definition * NamespaceDef::findInnerCompound (const char * name) virtual
Reimplemented from Definition.
Definition at line 821 of file namespacedef.cpp.
References SDict< T >::find(), m_innerCompounds, usingDeclList, and usingDirList.
findSectionsInDocumentation()
void NamespaceDef::findSectionsInDocumentation ()
Definition at line 120 of file namespacedef.cpp.
References Definition::docFile(), docFindSections(), Definition::documentation(), MemberGroup::findSectionsInDocumentation(), MemberList::findSectionsInDocumentation(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_memberLists, memberGroupSDict, and MemberListType_declarationLists.
Referenced by findSectionsInDocumentation().
getClassSDict()
ClassSDict* NamespaceDef::getClassSDict () const inline
Returns the classes contained in this namespace
Definition at line 98 of file namespacedef.h.
References classSDict.
Referenced by NestingNodeContext::Private::addNamespaces(), NamespaceContext::Private::classes(), generateDocbookForNamespace(), generateNamespaceDocs(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForNamespace(), NamespaceContext::Private::inlineClasses(), namespaceHasVisibleChild(), and writeNamespaceTree().
getMemberByName()
MemberDef * NamespaceDef::getMemberByName (const QCString & n) const
Definition at line 1139 of file namespacedef.cpp.
References SDict< T >::find(), and m_allMembersDict.
getMemberGroupSDict()
MemberGroupSDict* NamespaceDef::getMemberGroupSDict () const inline
Returns the user defined member groups
Definition at line 95 of file namespacedef.h.
References memberGroupSDict.
Referenced by generateDocbookForNamespace(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForNamespace(), and NamespaceContext::Private::memberGroups().
getMemberList()
MemberList * NamespaceDef::getMemberList (MemberListType lt) const
Definition at line 1089 of file namespacedef.cpp.
References MemberList::listType(), and m_memberLists.
Referenced by computeAnchors(), countMembers(), generateDEFForNamespace(), PerlModGenerator::generatePerlModForNamespace(), NamespaceContext::Private::getMemberList(), insertMember(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), writeQuickMemberLinks(), writeSummaryLinks(), and writeTagFile().
getMemberLists()
const QList<MemberList>& NamespaceDef::getMemberLists () const inline
Definition at line 91 of file namespacedef.h.
References m_memberLists.
Referenced by generateDocbookForNamespace(), and generateXMLForNamespace().
getNamespaceSDict()
NamespaceSDict* NamespaceDef::getNamespaceSDict () const inline
Returns the namespaces contained in this namespace
Definition at line 101 of file namespacedef.h.
References namespaceSDict.
Referenced by NestingNodeContext::Private::addNamespaces(), NamespaceContext::Private::constantgroups(), generateDocbookForNamespace(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForNamespace(), namespaceHasVisibleChild(), NamespaceContext::Private::namespaces(), and writeNamespaceTree().
getOutputFileBase()
QCString NamespaceDef::getOutputFileBase () const virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 816 of file namespacedef.cpp.
References fileName.
Referenced by addListReferences(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateDEFForNamespace(), generateDocbookForNamespace(), generateXMLForNamespace(), MemberDef::getOutputFileBase(), writeAlphabeticalClassList(), NamespaceSDict::writeDeclaration(), writeDocumentation(), writeInnerNamespaces(), writeNamespaceIndex(), writeNamespaceTree(), and writeTagFile().
getUsedClasses()
SDict<Definition>* NamespaceDef::getUsedClasses () const inline
Definition at line 66 of file namespacedef.h.
References usingDeclList.
Referenced by combineUsingRelations(), FileDef::combineUsingRelations(), isAccessibleFrom(), and isAccessibleFromWithExpScope().
getUsedNamespaces()
NamespaceSDict * NamespaceDef::getUsedNamespaces () const
Definition at line 798 of file namespacedef.cpp.
References usingDirList.
Referenced by accessibleViaUsingNamespace(), combineUsingRelations(), FileDef::combineUsingRelations(), findUsingDirectives(), isAccessibleFrom(), and isAccessibleFromWithExpScope().
hasDetailedDescription()
bool NamespaceDef::hasDetailedDescription () const
Definition at line 273 of file namespacedef.cpp.
References Definition::briefDescription(), Config_getBool, and Definition::documentation().
Referenced by NamespaceContext::Private::hasDetails(), writeBriefDescription(), and writeDetailedDescription().
insertClass()
void NamespaceDef::insertClass (ClassDef * cd)
Definition at line 165 of file namespacedef.cpp.
References SDict< T >::append(), classSDict, Config_getBool, SDict< T >::find(), SDict< T >::inSort(), and Definition::name().
Referenced by addInnerCompound().
insertMember()
void NamespaceDef::insertMember (MemberDef * md)
Definition at line 216 of file namespacedef.cpp.
References addMemberToList(), MemberList::append(), SDict< T >::append(), err(), MemberDef::getClassDef(), getMemberList(), Definition::isHidden(), Definition::localName(), m_allMembersDict, m_memberLists, MemberListType_allMembersList, MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decFuncMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docEnumMembers, MemberListType_docFuncMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Function, MemberType_Typedef, MemberType_Variable, and Definition::name().
Referenced by addVariableToFile(), buildFunctionList(), and findEnums().
insertNamespace()
void NamespaceDef::insertNamespace (NamespaceDef * nd)
Definition at line 176 of file namespacedef.cpp.
References SDict< T >::append(), Config_getBool, SDict< T >::find(), SDict< T >::inSort(), Definition::name(), and namespaceSDict.
Referenced by addInnerCompound().
insertUsedFile()
void NamespaceDef::insertUsedFile (FileDef * fd)
Definition at line 140 of file namespacedef.cpp.
References Config_getBool, and files.
Referenced by buildNamespaceList(), and findUsingDirectives().
isConstantGroup()
bool NamespaceDef::isConstantGroup () const inline
Definition at line 71 of file namespacedef.h.
References CONSTANT_GROUP, and m_type.
Referenced by addNamespaceAttributes(), compoundTypeString(), title(), and NamespaceSDict::writeDeclaration().
isLibrary()
bool NamespaceDef::isLibrary () const inline
Definition at line 73 of file namespacedef.h.
References LIBRARY, and m_type.
Referenced by compoundTypeString().
isLinkable()
bool NamespaceDef::isLinkable () const virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 1134 of file namespacedef.cpp.
References isLinkableInProject(), and Definition::isReference().
Referenced by addMemberToSearchIndex(), createJavascriptSearchIndex(), NamespaceSDict::declVisible(), getDefs(), getScopeDefs(), MemberDef::isDetailedSectionVisible(), writeAlphabeticalClassList(), and NamespaceSDict::writeDeclaration().
isLinkableInProject()
bool NamespaceDef::isLinkableInProject () const virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 1116 of file namespacedef.cpp.
References Config_getBool, Definition::getLanguage(), Definition::hasDocumentation(), Definition::isArtificial(), Definition::isHidden(), Definition::isReference(), Definition::name(), and SrcLangExt_CSharp.
Referenced by MemberDef::_computeLinkableInProject(), addNamespaceMemberNameToIndex(), NestingContext::Private::addNamespaces(), NamespaceListContext::Private::addNamespaces(), addSourceReferences(), countNamespaces(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateNamespaceDocs(), NamespaceMembersIndexContext::Private::getMembersFiltered(), MemberDef::getOutputFileBase(), isLinkable(), RTFGenerator::startIndexSection(), LatexGenerator::startIndexSection(), writeNamespaceIndex(), writeNamespaceTree(), writeTagFile(), GroupDef::writeTagFile(), FileDef::writeTagFile(), and writeTagFile().
isModule()
bool NamespaceDef::isModule () const inline
Definition at line 72 of file namespacedef.h.
References m_type, and MODULE.
Referenced by compoundTypeString().
localName()
QCString NamespaceDef::localName () const
Definition at line 884 of file namespacedef.cpp.
References Definition::name().
Referenced by NestingContext::Private::addNamespaces(), displayName(), NamespaceSDict::writeDeclaration(), writeDocumentation(), and writeNamespaceTree().
setFileName()
void NamespaceDef::setFileName (const QCString & fn)
Definition at line 98 of file namespacedef.cpp.
References convertNameToFile(), fileName, and Definition::isReference().
Referenced by buildNamespaceList(), and NamespaceDef().
sortMemberLists()
void NamespaceDef::sortMemberLists ()
Definition at line 1069 of file namespacedef.cpp.
References classSDict, m_memberLists, namespaceSDict, MemberList::needsSorting(), MemberList::setNeedsSorting(), MemberList::sort(), and SDict< T >::sort().
Referenced by sortMemberLists().
startMemberDeclarations()
void NamespaceDef::startMemberDeclarations (OutputList & ol) private
Definition at line 442 of file namespacedef.cpp.
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDocumentation()
void NamespaceDef::startMemberDocumentation (OutputList & ol) private
Definition at line 452 of file namespacedef.cpp.
References Config_getBool, OutputList::disable(), OutputGenerator::Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
subGrouping()
bool NamespaceDef::subGrouping () const inline
Definition at line 88 of file namespacedef.h.
References m_subGrouping.
Referenced by NamespaceContext::Private::memberGroups().
title()
QCString NamespaceDef::title () const
Definition at line 1150 of file namespacedef.cpp.
References displayName(), Definition::getLanguage(), isConstantGroup(), SrcLangExt_Fortran, SrcLangExt_IDL, SrcLangExt_Java, theTranslator, Translator::trConstantGroupReference(), Translator::trModuleReference(), Translator::trNamespaceReference(), and Translator::trPackage().
Referenced by NamespaceContext::Private::title(), and writeDocumentation().
writeAuthorSection()
void NamespaceDef::writeAuthorSection (OutputList & ol) private
Definition at line 505 of file namespacedef.cpp.
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), and Translator::trGeneratedAutomatically().
Referenced by writeDocumentation().
writeBriefDescription()
void NamespaceDef::writeBriefDescription (OutputList & ol) private
Definition at line 402 of file namespacedef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), Definition::hasBriefDescription(), hasDetailedDescription(), OutputGenerator::Html, DocRoot::isEmpty(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeClassDeclarations()
void NamespaceDef::writeClassDeclarations (OutputList & ol, const QCString & title) private
Definition at line 470 of file namespacedef.cpp.
References classSDict, and ClassSDict::writeDeclaration().
Referenced by writeDocumentation().
writeDetailedDescription()
void NamespaceDef::writeDetailedDescription (OutputList & ol, const QCString & title) private
Definition at line 360 of file namespacedef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), Definition::docFile(), Definition::docLine(), Definition::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), OutputList::endTextBlock(), OutputList::generateDoc(), hasDetailedDescription(), OutputGenerator::Html, OutputGenerator::Latex, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startGroupHeader(), OutputList::startTextBlock(), OutputList::writeAnchor(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDocumentation()
void NamespaceDef::writeDocumentation (OutputList & ol)
Definition at line 569 of file namespacedef.cpp.
References addGroupListToTitle(), IndexList::addIndexItem(), addNamespaceAttributes(), SearchIndexIntf::addWord(), anchor(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, displayName(), OutputList::endContents(), endFileWithNavPath(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endQuickIndices(), endTitle(), err(), LayoutDocEntry::FileClasses, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, Definition::getLanguage(), getMemberList(), Definition::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, HLI_NamespaceVisible, Doxygen::indexList, LayoutDocManager::instance(), LayoutDocEntry::kind(), localName(), LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, MemberListType_allMembersList, Definition::name(), LayoutDocManager::Namespace, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, OutputList::parseText(), Doxygen::searchIndex, SearchIndexIntf::setCurrentDoc(), MemberList::sort(), OutputList::startContents(), startFile(), startMemberDeclarations(), startMemberDocumentation(), startTitle(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), title(), LayoutDocEntryMemberDef::title(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClassDeclarations(), writeDetailedDescription(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeMemberPages(), writeNamespaceDeclarations(), and Definition::writeNavigationPath().
Referenced by generateNamespaceDocs().
writeInlineClasses()
void NamespaceDef::writeInlineClasses (OutputList & ol) private
Definition at line 475 of file namespacedef.cpp.
References classSDict, and ClassSDict::writeDocumentation().
Referenced by writeDocumentation().
writeMemberDeclarations()
void NamespaceDef::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1103 of file namespacedef.cpp.
References getMemberList(), and MemberList::writeDeclarations().
Referenced by writeDocumentation().
writeMemberDocumentation()
void NamespaceDef::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1109 of file namespacedef.cpp.
References displayName(), getMemberList(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberGroups()
void NamespaceDef::writeMemberGroups (OutputList & ol) private
Definition at line 486 of file namespacedef.cpp.
References MemberGroup::allMembersInSameSection(), MemberGroup::header(), SIntDict< MemberGroup >::Iterator, m_subGrouping, memberGroupSDict, SIntDict< T >::sort(), and MemberGroup::writeDeclarations().
Referenced by writeDocumentation().
writeMemberPages()
void NamespaceDef::writeMemberPages (OutputList & ol)
Definition at line 718 of file namespacedef.cpp.
References OutputList::disableAllBut(), displayName(), OutputGenerator::Html, MemberList::listType(), m_memberLists, MemberListType_documentationLists, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), and MemberList::writeDocumentationPage().
Referenced by writeDocumentation().
writeNamespaceDeclarations()
void NamespaceDef::writeNamespaceDeclarations (OutputList & ol, const QCString & title, bool isConstantGroup = false) private
Definition at line 480 of file namespacedef.cpp.
References namespaceSDict, and NamespaceSDict::writeDeclaration().
Referenced by writeDocumentation().
writeQuickMemberLinks()
void NamespaceDef::writeQuickMemberLinks (OutputList & ol, MemberDef * currentMd) const virtual
Reimplemented from Definition.
Definition at line 735 of file namespacedef.cpp.
References MemberDef::anchor(), Config_getBool, convertToHtml(), createSubDirs(), getMemberList(), MemberDef::getNamespaceDef(), MemberDef::getOutputFileBase(), Doxygen::htmlFileExtension, MemberDef::isEnumValue(), MemberDef::isLinkable(), MemberDef::isLinkableInProject(), Definition::localName(), MemberListType_allMembersList, and OutputList::writeString().
writeSummaryLinks()
void NamespaceDef::writeSummaryLinks (OutputList & ol) private virtual
Reimplemented from Definition.
Definition at line 517 of file namespacedef.cpp.
References classSDict, ClassSDict::declVisible(), MemberList::declVisible(), NamespaceSDict::declVisible(), OutputList::disableAllBut(), Definition::getLanguage(), getMemberList(), OutputGenerator::Html, LayoutDocManager::instance(), LayoutDocEntry::kind(), MemberList::listType(), MemberList::listTypeAsString(), LayoutDocEntry::MemberDecl, LayoutDocManager::Namespace, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceNestedNamespaces, namespaceSDict, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
writeTagFile()
void NamespaceDef::writeTagFile (FTextStream & tagFile)
Definition at line 280 of file namespacedef.cpp.
References classSDict, ClassDef::compoundTypeString(), convertToXML(), endl(), getMemberList(), getOutputFileBase(), Doxygen::htmlFileExtension, Definition::id(), LayoutDocManager::instance(), isLinkableInProject(), ClassDef::isLinkableInProject(), SIntDict< MemberGroup >::Iterator, LayoutDocEntry::kind(), LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, memberGroupSDict, Definition::name(), LayoutDocManager::Namespace, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceNestedNamespaces, namespaceSDict, LayoutDocEntryMemberDecl::type, Definition::writeDocAnchorsToTagFile(), MemberGroup::writeTagFile(), and MemberList::writeTagFile().
Referenced by writeTagFile().
Member Data Documentation
classSDict
ClassSDict* NamespaceDef::classSDict private
Definition at line 138 of file namespacedef.h.
Referenced by countMembers(), getClassSDict(), insertClass(), NamespaceDef(), sortMemberLists(), writeClassDeclarations(), writeInlineClasses(), writeSummaryLinks(), writeTagFile(), and ~NamespaceDef().
fileName
QCString NamespaceDef::fileName private
Definition at line 128 of file namespacedef.h.
Referenced by getOutputFileBase(), NamespaceDef(), and setFileName().
files
FileList NamespaceDef::files private
Definition at line 129 of file namespacedef.h.
Referenced by insertUsedFile().
m_allMembersDict
MemberSDict* NamespaceDef::m_allMembersDict private
Definition at line 135 of file namespacedef.h.
Referenced by getMemberByName(), insertMember(), NamespaceDef(), and ~NamespaceDef().
m_innerCompounds
SDict<Definition>* NamespaceDef::m_innerCompounds private
Definition at line 133 of file namespacedef.h.
Referenced by addInnerCompound(), findInnerCompound(), NamespaceDef(), and ~NamespaceDef().
m_isPublished
bool NamespaceDef::m_isPublished private
Definition at line 142 of file namespacedef.h.
Referenced by addNamespaceAttributes().
m_memberLists
QList<MemberList> NamespaceDef::m_memberLists private
Definition at line 136 of file namespacedef.h.
Referenced by addListReferences(), addMembersToMemberGroup(), createMemberList(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), insertMember(), sortMemberLists(), and writeMemberPages().
m_subGrouping
bool NamespaceDef::m_subGrouping private
Definition at line 140 of file namespacedef.h.
Referenced by addMembersToMemberGroup(), NamespaceDef(), subGrouping(), and writeMemberGroups().
m_type
enum { ... } NamespaceDef::m_type
Referenced by isConstantGroup(), isLibrary(), isModule(), and NamespaceDef().
memberGroupSDict
MemberGroupSDict* NamespaceDef::memberGroupSDict private
Definition at line 137 of file namespacedef.h.
Referenced by addListReferences(), addMembersToMemberGroup(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), getMemberGroupSDict(), NamespaceDef(), writeMemberGroups(), writeTagFile(), and ~NamespaceDef().
namespaceSDict
NamespaceSDict* NamespaceDef::namespaceSDict private
Definition at line 139 of file namespacedef.h.
Referenced by getNamespaceSDict(), insertNamespace(), NamespaceDef(), sortMemberLists(), writeNamespaceDeclarations(), writeSummaryLinks(), writeTagFile(), and ~NamespaceDef().
usingDeclList
SDict<Definition>* NamespaceDef::usingDeclList private
Definition at line 132 of file namespacedef.h.
Referenced by addUsingDeclaration(), findInnerCompound(), getUsedClasses(), NamespaceDef(), and ~NamespaceDef().
usingDirList
NamespaceSDict* NamespaceDef::usingDirList private
Definition at line 131 of file namespacedef.h.
Referenced by addUsingDirective(), combineUsingRelations(), findInnerCompound(), getUsedNamespaces(), NamespaceDef(), and ~NamespaceDef().
visited
bool NamespaceDef::visited
Definition at line 106 of file namespacedef.h.
Referenced by combineUsingRelations(), combineUsingRelations(), and NamespaceDef().
The documentation for this class was generated from the following files:
src/namespacedef.h
src/namespacedef.cpp