Doxygen: src/debug.cpp File Reference
debug.cpp File Reference
#include <stdarg.h>
#include <stdio.h>
#include <qdict.h>
#include "debug.h"
#include "message.h"
Classes
struct LabelMap
Helper struct representing a mapping from debug label to a debug ID.
class LabelMapper
Class representing a mapping from debug labels to debug IDs.
Functions
static int labelToEnumValue (const char *l)
Variables
static LabelMap s_labels []
static LabelMapper g_labelMapper
Function Documentation
labelToEnumValue()
static int labelToEnumValue (const char * l) static
Definition at line 95 of file debug.cpp.
References LabelMapper::find().
Referenced by Debug::clearFlag(), and Debug::setFlag().
Variable Documentation
g_labelMapper
LabelMapper g_labelMapper static
Definition at line 77 of file debug.cpp.
s_labels
LabelMap s_labels[] static
Initial value:
=
{
  { "findmembers",  Debug::FindMembers  },
  { "functions",    Debug::Functions    },
  { "variables",    Debug::Variables    },
  { "preprocessor", Debug::Preprocessor },
  { "classes",      Debug::Classes      },
  { "commentcnv",   Debug::CommentCnv   },
  { "commentscan",  Debug::CommentScan  },
  { "validate",     Debug::Validate     },
  { "printtree",    Debug::PrintTree    },
  { "time",         Debug::Time         },
  { "extcmd",       Debug::ExtCmd       },
  { "markdown",     Debug::Markdown     },
  { "filteroutput", Debug::FilterOutput },
  { "lex",          Debug::Lex },
  { 0,             (Debug::DebugMask)0  }
}
Definition at line 35 of file debug.cpp.
Referenced by LabelMapper::LabelMapper().