Doxygen: TemplateNodeIndexEntry Class Reference
TemplateNodeIndexEntry Class Reference
Class representing an 'indexentry' tag in a template.
Classes
struct Mapping
Public Member Functions
TemplateNodeIndexEntry (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
void render (FTextStream &, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeIndexEntry >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Private Attributes
QCString m_name
QList< Mapping > m_args
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeIndexEntry >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeIndexEntry >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeIndexEntry >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'indexentry' tag in a template.
Definition at line 3849 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeIndexEntry()
TemplateNodeIndexEntry::TemplateNodeIndexEntry (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 3859 of file template.cpp.
References m_args, m_name, ExpressionParser::parse(), split(), TemplateParser::templateName(), TRACE, and TemplateParser::warn().
Member Function Documentation
render()
void TemplateNodeIndexEntry::render (FTextStream & , TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 3896 of file template.cpp.
References TemplateContextImpl::addIndexEntry(), m_args, TemplateNodeCreator< TemplateNodeIndexEntry >::m_line, m_name, TemplateNodeCreator< TemplateNodeIndexEntry >::m_templateName, TemplateNodeIndexEntry::Mapping::name, ExprAst::resolve(), TemplateContextImpl::setLocation(), and TemplateNodeIndexEntry::Mapping::value.
Member Data Documentation
m_args
QList<Mapping> TemplateNodeIndexEntry::m_args private
Definition at line 3915 of file template.cpp.
Referenced by render(), and TemplateNodeIndexEntry().
m_name
QCString TemplateNodeIndexEntry::m_name private
Definition at line 3914 of file template.cpp.
Referenced by render(), and TemplateNodeIndexEntry().
The documentation for this class was generated from the following file:
src/template.cpp