Doxygen: Definition Class Reference
Definition Class Reference abstract
The common base class of all entity definitions found in the sources.
#include <definition.h>
Classes
struct Cookie
Public Member Functions
Definition (const char *defFileName, int defLine, int defColumn, const char *name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~Definition ()
const QCString & name () const
virtual QCString displayName (bool includeScope=TRUE) const =0
QCString localName () const
virtual QCString qualifiedName () const
QCString symbolName () const
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
int docLine () const
QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInProject () const
virtual bool isVisible () const
bool isHidden () const
bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
QCString externalReference (const QCString &relPath) const
int getStartBodyLine () const
int getEndBodyLine () const
FileDef * getBodyDef () const
SrcLangExt getLanguage () const
Returns the programming language this definition was written in.
GroupList * partOfGroups () const
bool isLinkableViaGroup () const
QList< ListItemInfo > * xrefListItems () const
virtual Definition * findInnerCompound (const char *name)
virtual Definition * getOuterScope () const
MemberSDict * getReferencesMembers () const
MemberSDict * getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
returns TRUE if this class has a brief description
QCString id () const
virtual void setName (const char *name)
void setId (const char *name)
virtual void setDocumentation (const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const char *b, const char *briefFile, int briefLine)
virtual void setInbodyDocumentation (const char *d, const char *docFile, int docLine)
void setReference (const char *r)
void addSectionsToDefinition (QList< SectionInfo > *anchorList)
void setBodySegment (int bls, int ble)
void setBodyDef (FileDef *fd)
void addSourceReferencedBy (MemberDef *d)
void addSourceReferences (MemberDef *d)
void setRefItems (const QList< ListItemInfo > *sli)
void mergeRefItems (Definition *d)
virtual void addInnerCompound (Definition *d)
virtual void setOuterScope (Definition *d)
virtual void setHidden (bool b)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const char *scopeName)
void writeInlineCode (OutputList &ol, const char *scopeName)
void writeSourceRefs (OutputList &ol, const char *scopeName)
void writeSourceReffedBy (OutputList &ol, const char *scopeName)
void makePartOfGroup (GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
virtual void writeQuickMemberLinks (OutputList &, MemberDef *) const
virtual void writeSummaryLinks (OutputList &)
QCString pathFragment () const
void writeDocAnchorsToTagFile (FTextStream &)
void setLocalName (const QCString name)
void addSectionsToIndex ()
void writeToc (OutputList &ol)
void setCookie (Cookie *cookie)
Cookie * cookie () const
Public Member Functions inherited from DefinitionIntf
DefinitionIntf ()
virtual ~DefinitionIntf ()
virtual DefType definitionType () const =0
Protected Member Functions
Definition (const Definition &d)
Private Member Functions
void _setSymbolName (const QCString &name)
int _getXRefListId (const char *listName) const
void _writeSourceRefList (OutputList &ol, const char *scopeName, const QCString &text, MemberSDict *members, bool)
void _setBriefDescription (const char *b, const char *briefFile, int briefLine)
void _setDocumentation (const char *d, const char *docFile, int docLine, bool stripWhiteSpace, bool atTop)
void _setInbodyDocumentation (const char *d, const char *docFile, int docLine)
bool _docsAlreadyAdded (const QCString &doc, QCString &sigList)
Static Private Member Functions
static void addToMap (const char *name, Definition *d)
static void removeFromMap (Definition *d)
Private Attributes
DefinitionImpl * m_impl
QCString m_name
bool m_isSymbol
QCString m_symbolName
int m_defLine
int m_defColumn
Cookie * m_cookie
Additional Inherited Members
Public Types inherited from DefinitionIntf
enum DefType {
TypeClass = 0, TypeFile = 1, TypeNamespace = 2, TypeMember = 3,
TypeGroup = 4, TypePackage = 5, TypePage = 6, TypeDir = 7,
TypeSymbolList = 8
}
Detailed Description
The common base class of all entity definitions found in the sources.
This can be a class or a member function, or a file, or a namespace, etc. Use definitionType() to find which type of definition this is.
Definition at line 92 of file definition.h.
Constructor & Destructor Documentation
Definition() [1/2]
Definition::Definition (const char * defFileName, int defLine, int defColumn, const char * name, const char * b = 0, const char * d = 0, bool isSymbol = TRUE)
Create a new definition
Definition at line 283 of file definition.cpp.
References _setBriefDescription(), _setDocumentation(), addToMap(), DefinitionImpl::hidden, DefinitionImpl::init(), m_defColumn, m_defLine, m_impl, m_isSymbol, m_name, matchExcludedSymbols(), and name().
~Definition()
Definition::~Definition () virtual
Destroys the definition
Definition at line 381 of file definition.cpp.
References m_cookie, m_impl, m_isSymbol, and removeFromMap().
Definition() [2/2]
Definition::Definition (const Definition & d) protected
Definition at line 302 of file definition.cpp.
References addToMap(), SDict< T >::append(), DefinitionImpl::body, DefinitionImpl::brief, DefinitionImpl::details, DefinitionImpl::inbodyDocs, SDict< MemberDef >::IteratorDict, SectionInfo::label, m_defLine, m_impl, m_isSymbol, m_name, makePartOfGroup(), DefinitionImpl::partOfGroups, DefinitionImpl::sectionDict, setRefItems(), DefinitionImpl::sourceRefByDict, DefinitionImpl::sourceRefsDict, and DefinitionImpl::xrefListItems.
Member Function Documentation
_docsAlreadyAdded()
bool Definition::_docsAlreadyAdded (const QCString & doc, QCString & sigList) private
Definition at line 544 of file definition.cpp.
Referenced by _setBriefDescription(), and _setDocumentation().
_getXRefListId()
int Definition::_getXRefListId (const char * listName) const private
Definition at line 1489 of file definition.cpp.
References ListItemInfo::itemId, m_impl, ListItemInfo::type, and DefinitionImpl::xrefListItems.
Referenced by mergeRefItems().
_setBriefDescription()
void Definition::_setBriefDescription (const char * b, const char * briefFile, int briefLine) private
Definition at line 632 of file definition.cpp.
References _docsAlreadyAdded(), _setDocumentation(), DefinitionImpl::brief, brief, briefFile(), briefLine(), DefinitionImpl::briefSignatures, Config_getEnum, BriefInfo::doc, BriefInfo::file, lastCharIsMultibyte(), BriefInfo::line, m_impl, and uni_isupper.
Referenced by Definition(), and setBriefDescription().
_setDocumentation()
void Definition::_setDocumentation (const char * d, const char * docFile, int docLine, bool stripWhiteSpace, bool atTop) private
Definition at line 566 of file definition.cpp.
References _docsAlreadyAdded(), DefinitionImpl::details, DocInfo::doc, doc, docFile(), docLine(), DefinitionImpl::docSignatures, DocInfo::file, DocInfo::line, m_impl, and stripLeadingAndTrailingEmptyLines().
Referenced by _setBriefDescription(), Definition(), and setDocumentation().
_setInbodyDocumentation()
void Definition::_setInbodyDocumentation (const char * d, const char * docFile, int docLine) private
Definition at line 693 of file definition.cpp.
References DocInfo::doc, doc, DocInfo::file, DefinitionImpl::inbodyDocs, inbodyFile(), inbodyLine(), DocInfo::line, and m_impl.
Referenced by setInbodyDocumentation().
_setSymbolName()
void Definition::_setSymbolName (const QCString & name) private
Definition at line 1940 of file definition.cpp.
References m_symbolName, and name().
Referenced by addToMap().
_writeSourceRefList()
void Definition::_writeSourceRefList (OutputList & ol, const char * scopeName, const QCString & text, MemberSDict * members, bool) private
Write a reference to the source code fragments in which this definition is used.
Definition at line 1143 of file definition.cpp.
References MemberDef::anchor(), SDict< T >::at(), Config_getBool, SDict< T >::count(), OutputList::disable(), OutputList::docify(), OutputList::endParagraph(), getBodyDef(), getLanguageSpecificSeparator(), MemberDef::getOutputFileBase(), MemberDef::getReference(), MemberDef::getScopeString(), FileDef::getSourceFileBase(), getStartBodyLine(), OutputGenerator::Html, MemberDef::isFunction(), MemberDef::isLinkable(), MemberDef::isObjCMethod(), MemberDef::isPrototype(), MemberDef::isSignal(), MemberDef::isSlot(), DefinitionImpl::lang, OutputGenerator::Latex, m_impl, OutputGenerator::Man, name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, SDict< T >::sort(), OutputList::startParagraph(), theTranslator, Translator::trWriteList(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writeSourceReffedBy(), and writeSourceRefs().
addInnerCompound()
void Definition::addInnerCompound (Definition * d) virtual
Reimplemented in ClassDef, NamespaceDef, and PageDef.
Definition at line 1370 of file definition.cpp.
References err().
Referenced by buildNamespaceList(), buildScopeFromQualifiedName(), createTagLessInstance(), and resolveClassNestingRelations().
addSectionsToDefinition()
void Definition::addSectionsToDefinition (QList< SectionInfo > * anchorList)
Add the list of anchors that mark the sections that are found in the documentation.
Definition at line 418 of file definition.cpp.
References SDict< T >::append(), SectionInfo::definition, SDict< T >::find(), SectionInfo::label, m_impl, DefinitionImpl::sectionDict, and Doxygen::sectionDict.
Referenced by addClassToContext(), addEnumValuesToEnums(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addRelatedPage(), addVariableToClass(), buildExampleList(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildNamespaceList(), findDefineDocumentation(), findEnumDocumentation(), findEnums(), findMainPage(), findMainPageTagFiles(), findMember(), findUsingDeclImports(), and findUsingDirectives().
addSectionsToIndex()
void Definition::addSectionsToIndex ()
Definition at line 467 of file definition.cpp.
References IndexList::addContentsItem(), IndexList::decContentsDepth(), getOutputFileBase(), getReference(), IndexList::incContentsDepth(), Doxygen::indexList, SectionInfo::label, m_impl, SectionInfo::Paragraph, SectionInfo::Section, DefinitionImpl::sectionDict, SectionInfo::Subsection, SectionInfo::Subsubsection, SectionInfo::title, and SectionInfo::type.
Referenced by writePages().
addSourceReferencedBy()
void Definition::addSourceReferencedBy (MemberDef * d)
Definition at line 1319 of file definition.cpp.
References SDict< T >::append(), SDict< T >::find(), MemberDef::getScopeString(), m_impl, name(), and DefinitionImpl::sourceRefByDict.
Referenced by addDocCrossReference(), and transferFunctionReferences().
addSourceReferences()
void Definition::addSourceReferences (MemberDef * d)
Definition at line 1342 of file definition.cpp.
References SDict< T >::append(), SDict< T >::find(), MemberDef::getScopeString(), m_impl, name(), and DefinitionImpl::sourceRefsDict.
Referenced by addDocCrossReference(), and transferFunctionReferences().
addToMap()
void Definition::addToMap (const char * name, Definition * d) static private
Definition at line 207 of file definition.cpp.
References _setSymbolName(), computeQualifiedIndex(), Config_getBool, DefinitionIntf::definitionType(), name(), SDict_primes, Doxygen::symbolMap, symbolName(), and DefinitionIntf::TypeSymbolList.
Referenced by Definition().
anchor()
virtual QCString Definition::anchor () const pure virtual
Returns the anchor within a page where this item can be found
Implemented in ClassDef, FileDef, MemberDef, DirDef, GroupDef, PageDef, and NamespaceDef.
Referenced by TooltipManager::addTooltip(), DefinitionContext< FileContext::Private >::anchor(), NestingNodeContext::Private::anchor(), NavPathElemContext::Private::anchor(), SymbolContext::Private::anchor(), handleLinkedWord(), navigationPathAsString(), validatingParseDoc(), writeJavascriptSearchIndex(), and TooltipManager::writeTooltips().
briefDescription()
QCString Definition::briefDescription (bool abbreviate = FALSE) const virtual
Returns the brief description of this definition. This can include commands.
Reimplemented in MemberDef.
Definition at line 1756 of file definition.cpp.
References abbreviate(), DefinitionImpl::brief, displayName(), BriefInfo::doc, and m_impl.
Referenced by DefinitionContext< FileContext::Private >::brief(), NestingNodeContext::Private::brief(), MemberDef::briefDescription(), buildFileList(), createTagLessInstance(), findDocsForMemberOrCompound(), generateBriefDoc(), generateDEFForClass(), generateDEFForFile(), generateDEFForNamespace(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForNamespace(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), hasBriefDescription(), DirDef::hasDetailedDescription(), NamespaceDef::hasDetailedDescription(), GroupDef::hasDetailedDescription(), ClassDef::hasDetailedDescription(), FileDef::hasDetailedDescription(), writeAnnotatedClassList(), DirDef::writeBriefDescription(), NamespaceDef::writeBriefDescription(), GroupDef::writeBriefDescription(), FileDef::writeBriefDescription(), ClassDef::writeBriefDescription(), NamespaceSDict::writeDeclaration(), ClassDef::writeDeclarationLink(), DirDef::writeDetailedDescription(), NamespaceDef::writeDetailedDescription(), GroupDef::writeDetailedDescription(), FileDef::writeDetailedDescription(), ClassDef::writeDetailedDocumentationBody(), GroupDef::writeDirs(), DirDef::writeFileList(), GroupDef::writeFiles(), writeInnerClasses(), writeNamespaceIndex(), GroupDef::writeNestedGroups(), writeSingleFileIndex(), DirDef::writeSubDirList(), and writeVhdlEntityToolTip().
briefDescriptionAsTooltip()
QCString Definition::briefDescriptionAsTooltip () const
Returns a plain text version of the brief description suitable for use as a tool tip.
Definition at line 1764 of file definition.cpp.
References DefinitionImpl::brief, DefinitionIntf::definitionType(), BriefInfo::doc, BriefInfo::file, getOuterScope(), BriefInfo::line, m_impl, parseCommentAsText(), BriefInfo::tooltip, and DefinitionIntf::TypeMember.
Referenced by DotClassGraph::addClass(), DotGfxHierarchyTable::addClassList(), DotGfxHierarchyTable::addHierarchy(), DotInclDepGraph::buildGraph(), DotCallGraph::buildGraph(), DotGroupCollaboration::buildGraph(), DotClassGraph::DotClassGraph(), handleLinkedWord(), writeColumn(), writeMapArea(), DocSets::writeToken(), and TooltipManager::writeTooltips().
briefFile()
QCString Definition::briefFile () const
Returns the file in which the brief description was found. This can differ from getDefFileName().
Definition at line 1794 of file definition.cpp.
References DefinitionImpl::brief, BriefInfo::file, m_impl, and m_name.
Referenced by _setBriefDescription(), MemberDef::_writeEnumValues(), ClassDef::addMembersToTemplateInstance(), DefinitionContext< FileContext::Private >::brief(), NestingNodeContext::Private::brief(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findFriends(), findUsingDeclImports(), generateBriefDoc(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForNamespace(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), inheritDocumentation(), writeAnnotatedClassList(), DirDef::writeBriefDescription(), NamespaceDef::writeBriefDescription(), GroupDef::writeBriefDescription(), FileDef::writeBriefDescription(), ClassDef::writeBriefDescription(), NamespaceSDict::writeDeclaration(), MemberDef::writeDeclaration(), ClassDef::writeDeclarationLink(), DirDef::writeDetailedDescription(), NamespaceDef::writeDetailedDescription(), GroupDef::writeDetailedDescription(), FileDef::writeDetailedDescription(), ClassDef::writeDetailedDocumentationBody(), GroupDef::writeDirs(), MemberDef::writeDocumentation(), DirDef::writeFileList(), GroupDef::writeFiles(), MemberDef::writeMemberDocSimple(), writeNamespaceIndex(), GroupDef::writeNestedGroups(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), DirDef::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
briefLine()
int Definition::briefLine () const
Returns the line number at which the brief description was found.
Definition at line 1789 of file definition.cpp.
References DefinitionImpl::brief, BriefInfo::line, and m_impl.
Referenced by _setBriefDescription(), MemberDef::_writeEnumValues(), ClassDef::addMembersToTemplateInstance(), DefinitionContext< FileContext::Private >::brief(), NestingNodeContext::Private::brief(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findFriends(), findUsingDeclImports(), formatBriefNote(), generateBriefDoc(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForNamespace(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), inheritDocumentation(), writeAnnotatedClassList(), DirDef::writeBriefDescription(), NamespaceDef::writeBriefDescription(), GroupDef::writeBriefDescription(), FileDef::writeBriefDescription(), ClassDef::writeBriefDescription(), NamespaceSDict::writeDeclaration(), MemberDef::writeDeclaration(), ClassDef::writeDeclarationLink(), DirDef::writeDetailedDescription(), NamespaceDef::writeDetailedDescription(), GroupDef::writeDetailedDescription(), FileDef::writeDetailedDescription(), ClassDef::writeDetailedDocumentationBody(), GroupDef::writeDirs(), MemberDef::writeDocumentation(), DirDef::writeFileList(), GroupDef::writeFiles(), MemberDef::writeMemberDocSimple(), writeNamespaceIndex(), GroupDef::writeNestedGroups(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), DirDef::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
cookie()
Cookie* Definition::cookie () const inline
Definition at line 352 of file definition.h.
References m_cookie.
Referenced by DefinitionContext< FileContext::Private >::getCache(), ClassContext::Private::getCache(), NamespaceContext::Private::getCache(), FileContext::Private::getCache(), DirContext::Private::getCache(), PageContext::Private::getCache(), MemberContext::Private::getCache(), ModuleContext::Private::getCache(), ClassContext::Private::Private(), NamespaceContext::Private::Private(), FileContext::Private::Private(), DirContext::Private::Private(), PageContext::Private::Private(), MemberContext::Private::Private(), ModuleContext::Private::Private(), and setCookie().
displayName()
virtual QCString Definition::displayName (bool includeScope = TRUE) const pure virtual
Returns the name of the definition as it appears in the output
Implemented in MemberDef, ClassDef, FileDef, NamespaceDef, PageDef, DirDef, and GroupDef.
Referenced by DefinitionContext< FileContext::Private >::bareName(), briefDescription(), DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), DefinitionContext< FileContext::Private >::name(), NestingNodeContext::Private::name(), SymbolContext::Private::scope(), and MemberDef::writeDeclaration().
docFile()
QCString Definition::docFile () const
Returns the file in which the detailed documentation block was found. This can differ from getDefFileName().
Definition at line 1700 of file definition.cpp.
References DefinitionImpl::details, DocInfo::file, m_impl, and m_name.
Referenced by _setDocumentation(), MemberDef::_writeEnumValues(), ClassDef::addMembersToTemplateInstance(), checkArgumentName(), checkPageRelations(), combineDeclarationAndDefinition(), createTagLessInstance(), DefinitionContext< FileContext::Private >::details(), MemberGroup::distributeMemberGroupDocumentation(), ArgumentContext::Private::docs(), PageContext::Private::example(), findFriends(), findMainPage(), PageDef::findSectionsInDocumentation(), NamespaceDef::findSectionsInDocumentation(), GroupDef::findSectionsInDocumentation(), FileDef::findSectionsInDocumentation(), ClassDef::findSectionsInDocumentation(), MemberDef::findSectionsInDocumentation(), findUsingDeclImports(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForMember(), generateDocbookForNamespace(), generateDocbookForPage(), generateDocbookSection(), generateExampleDocs(), PerlModGenerator::generatePerlModForPage(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), generateXMLSection(), inheritDocumentation(), MemberContext::Private::paramDocs(), parseCode(), DirDef::writeDetailedDescription(), NamespaceDef::writeDetailedDescription(), GroupDef::writeDetailedDescription(), FileDef::writeDetailedDescription(), ClassDef::writeDetailedDocumentationBody(), PageDef::writeDocumentation(), MemberDef::writeDocumentation(), writeIndex(), MemberDef::writeMemberDocSimple(), PageDef::writePageDocumentation(), GroupDef::writePageDocumentation(), and writeTypeConstraints().
docLine()
int Definition::docLine () const
Returns the line number at which the detailed documentation was found.
Definition at line 1695 of file definition.cpp.
References DefinitionImpl::details, DocInfo::line, and m_impl.
Referenced by _setDocumentation(), MemberDef::_writeEnumValues(), ClassDef::addMembersToTemplateInstance(), checkArgumentName(), checkPageRelations(), combineDeclarationAndDefinition(), createTagLessInstance(), DefinitionContext< FileContext::Private >::details(), MemberGroup::distributeMemberGroupDocumentation(), ArgumentContext::Private::docs(), PageContext::Private::example(), findFriends(), findMainPage(), findUsingDeclImports(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForMember(), generateDocbookForNamespace(), generateDocbookForPage(), generateDocbookSection(), generateExampleDocs(), PerlModGenerator::generatePerlModForPage(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), generateXMLSection(), inheritDocumentation(), MemberContext::Private::paramDocs(), DirDef::writeDetailedDescription(), NamespaceDef::writeDetailedDescription(), GroupDef::writeDetailedDescription(), FileDef::writeDetailedDescription(), ClassDef::writeDetailedDocumentationBody(), PageDef::writeDocumentation(), MemberDef::writeDocumentation(), writeIndex(), MemberDef::writeMemberDocSimple(), PageDef::writePageDocumentation(), GroupDef::writePageDocumentation(), and writeTypeConstraints().
documentation()
QCString Definition::documentation () const virtual
Returns the detailed description of this definition
Reimplemented in MemberDef.
Definition at line 1690 of file definition.cpp.
References DefinitionImpl::details, DocInfo::doc, and m_impl.
Referenced by buildFileList(), createTagLessInstance(), DefinitionContext< FileContext::Private >::details(), MemberDef::documentation(), findDocsForMemberOrCompound(), PageDef::findSectionsInDocumentation(), GroupDef::findSectionsInDocumentation(), NamespaceDef::findSectionsInDocumentation(), FileDef::findSectionsInDocumentation(), ClassDef::findSectionsInDocumentation(), generateDEFForClass(), generateDEFForFile(), generateDEFForNamespace(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForNamespace(), generateDocbookForPage(), generateExampleDocs(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), generateXMLForPage(), DirDef::hasDetailedDescription(), NamespaceDef::hasDetailedDescription(), GroupDef::hasDetailedDescription(), ClassDef::hasDetailedDescription(), FileDef::hasDetailedDescription(), DirDef::writeBriefDescription(), GroupDef::writeBriefDescription(), FileDef::writeBriefDescription(), DirDef::writeDetailedDescription(), NamespaceDef::writeDetailedDescription(), GroupDef::writeDetailedDescription(), FileDef::writeDetailedDescription(), ClassDef::writeDetailedDocumentationBody(), PageDef::writePageDocumentation(), and GroupDef::writePageDocumentation().
externalReference()
QCString Definition::externalReference (const QCString & relPath) const
Convenience method to return a resolved external link
Definition at line 1951 of file definition.cpp.
References getReference(), and Doxygen::tagDestinationDict.
Referenced by DefinitionContext< FileContext::Private >::externalReference(), NestingNodeContext::Private::externalReference(), and NavPathElemContext::Private::externalReference().
findInnerCompound()
Definition * Definition::findInnerCompound (const char * name) virtual
Reimplemented in ClassDef, and NamespaceDef.
Definition at line 1365 of file definition.cpp.
Referenced by findScopeFromQualifiedName(), followPath(), and resolveTypeDef().
getBodyDef()
FileDef * Definition::getBodyDef () const
Returns the file in which the body of this item is located or 0 if no body is available.
Definition at line 1869 of file definition.cpp.
References DefinitionImpl::body, BodyInfo::fileDef, and m_impl.
Referenced by _writeSourceRefList(), addSourceReferences(), DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), combineDeclarationAndDefinition(), createLinkedText(), createTagLessInstance(), MemberDef::createTemplateInstanceMember(), findFriends(), findMember(), findUsingDeclImports(), generateDEFForMember(), generateDocbookForMember(), generateXMLForClass(), generateXMLForMember(), ClassDef::hasDetailedDescription(), FileDef::hasDetailedDescription(), parseCode(), SymbolContext::Private::scope(), MemberContext::Private::sourceCode(), MemberDef::writeDeclaration(), writeDefArgumentList(), MemberDef::writeDocumentation(), writeExceptionListImpl(), writeJavascriptSearchIndex(), MemberDef::writeMemberDocSimple(), writeMemberReference(), and TooltipManager::writeTooltips().
getDefColumn()
int Definition::getDefColumn () const inline
returns the column number at which the definition was found
Definition at line 191 of file definition.h.
References m_defColumn.
Referenced by ClassDef::addTypeConstraint(), createTagLessInstance(), MemberDef::createTemplateInstanceMember(), findUsedClassesForClass(), generateXMLForClass(), generateXMLForMember(), and generateXMLForNamespace().
getDefFileExtension()
QCString Definition::getDefFileExtension () const
returns the extension of the file in which this definition was found
Definition at line 1824 of file definition.cpp.
References DefinitionImpl::defFileExt, and m_impl.
Referenced by HtmlDocVisitor::HtmlDocVisitor(), parseCode(), parseDoc(), FileDef::parseSource(), ManGenerator::writeDoc(), RTFGenerator::writeDoc(), LatexGenerator::writeDoc(), writeDocbookCodeBlock(), MemberDef::writeDocumentation(), FileDef::writeSource(), and writeXMLCodeBlock().
getDefFileName()
QCString Definition::getDefFileName () const
returns the file in which this definition was found
Definition at line 1819 of file definition.cpp.
References DefinitionImpl::defFileName, and m_impl.
Referenced by addInstance(), ClassDef::addTypeConstraint(), addVariableToFile(), checkArgumentName(), checkUndocumentedParams(), NamespaceDef::compoundTypeString(), createTagLessInstance(), MemberDef::createTemplateInstanceMember(), dumpSymbol(), findGlobalMember(), findUsedClassesForClass(), formatBriefNote(), generateDEFForClass(), generateDEFForFile(), generateDEFForMember(), generateDEFForNamespace(), generateDocbookForClass(), generateDocbookForFile(), generateDocbookForMember(), generateDocbookForNamespace(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForClass(), generateXMLForFile(), generateXMLForMember(), generateXMLForNamespace(), MemberDef::getOutputFileBase(), MemberDefImpl::init(), newResolveTypedef(), resolveClassNestingRelations(), MemberDef::virtualness(), MemberDef::warnIfUndocumented(), MemberDef::warnIfUndocumentedParams(), writeDirTreeNode(), writeExceptionListImpl(), and writeGroupTreeNode().
getDefLine()
int Definition::getDefLine () const inline
returns the line number at which the definition was found
Definition at line 188 of file definition.h.
References m_defLine.
Referenced by ClassDef::addTypeConstraint(), checkArgumentName(), checkUndocumentedParams(), MemberList::compareValues(), MemberSDict::compareValues(), NamespaceDef::compoundTypeString(), createTagLessInstance(), MemberDef::createTemplateInstanceMember(), dumpSymbol(), findGlobalMember(), findUsedClassesForClass(), generateDEFForClass(), generateDEFForFile(), generateDEFForMember(), generateDEFForNamespace(), generateDocbookForClass(), generateDocbookForMember(), generateDocbookForNamespace(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), generateXMLForClass(), generateXMLForMember(), generateXMLForNamespace(), MemberDef::getOutputFileBase(), resolveClassNestingRelations(), MemberDef::virtualness(), MemberDef::warnIfUndocumented(), MemberDef::warnIfUndocumentedParams(), writeDirTreeNode(), writeExceptionListImpl(), and writeGroupTreeNode().
getEndBodyLine()
int Definition::getEndBodyLine () const
Returns the last line of the body of this item (applicable to classes and functions).
Definition at line 1864 of file definition.cpp.
References DefinitionImpl::body, BodyInfo::endLine, and m_impl.
Referenced by combineDeclarationAndDefinition(), VhdlDocGen::createFlowChart(), createTagLessInstance(), MemberDef::createTemplateInstanceMember(), findFriends(), findMember(), findUsingDeclImports(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), generateXMLForMember(), MemberContext::Private::sourceCode(), writeMemberReference(), and VhdlDocGen::writeSource().
getLanguage()
SrcLangExt Definition::getLanguage () const
Returns the programming language this definition was written in.
Definition at line 1914 of file definition.cpp.
References DefinitionImpl::lang, and m_impl.
Referenced by MemberDef::_computeIsConstructor(), MemberDef::_computeIsDestructor(), MemberDef::_writeGroupInclude(), ClassDef::addClassAttributes(), ClassListContext::Private::addClasses(), NestingNodeContext::Private::addClasses(), NestingContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), NestingContext::Private::addDerivedClasses(), DocSets::addIndexItem(), ClassContext::Private::additionalInheritedMembers(), MemberDef::addListReference(), NamespaceDef::addListReferences(), ClassDef::addListReferences(), addMethodToClass(), NamespaceDef::addNamespaceAttributes(), ClassDef::addTypeConstraint(), addVariableToClass(), addVariableToFile(), buildFunctionList(), DotCallGraph::buildGraph(), buildNamespaceList(), checkArgumentName(), checkUndocumentedParams(), classHasVisibleChildren(), NamespaceDef::compoundTypeString(), ClassDef::compoundTypeString(), ClassDef::countMemberDeclarations(), createTagLessInstance(), NamespaceContext::Private::detailedFunctions(), FileContext::Private::detailedFunctions(), ModuleContext::Private::detailedFunctions(), detectNoDocumentedParams(), MemberDef::displayDefinition(), NamespaceDef::displayName(), ClassDef::displayName(), DocRef::DocRef(), DotCallGraph::DotCallGraph(), findClassWithinClassContext(), findScopeFromQualifiedName(), findUsedClassesForClass(), findUsingDirectives(), NamespaceContext::Private::functions(), FileContext::Private::functions(), ModuleContext::Private::functions(), ClassDef::generatedFromFiles(), generateLink(), generateXMLForClass(), generateXMLForFile(), generateXMLForNamespace(), MemberDef::getLabels(), getResolvedClass(), ClassDef::getTitleForMemberListType(), MemberContext::Private::handleNameWithContextFor(), ClassContext::Private::includeInfo(), FileContext::Private::includeList(), ClassDef::includeStatement(), ClassDef::internalInsertMember(), ClassDef::isCSharp(), NamespaceDef::isLinkableInProject(), ClassDef::isObjectiveC(), DefinitionContext< FileContext::Private >::language(), ClassIndexContext::Private::list(), ClassDef::mergeMembers(), parseCode(), FileDef::parseSource(), ClassContext::Private::publicMethods(), ClassContext::Private::publicStaticMethods(), MemberDef::qualifiedName(), qualifiedName(), ClassDef::qualifiedNameWithTemplateParameters(), resolveClassNestingRelations(), SymbolContext::Private::scope(), SearchIndex::setCurrentDoc(), NamespaceDef::title(), ClassDef::title(), GroupDef::updateLanguage(), validatingParseDoc(), MemberDef::warnIfUndocumented(), ClassDef::writeAdditionalInheritedMembers(), writeAlphabeticalClassList(), writeAnnotatedClassList(), DotNode::writeBox(), writeClassTree(), writeClassTreeForList(), NamespaceSDict::writeDeclaration(), MemberDef::writeDeclaration(), ClassDef::writeDeclarationLink(), writeDefArgumentList(), ClassDef::writeDetailedDocumentationBody(), NamespaceDef::writeDocumentation(), GroupDef::writeDocumentation(), DirDef::writeDocumentation(), FileDef::writeDocumentation(), MemberDef::writeDocumentation(), ClassDef::writeDocumentationContents(), FileDef::writeIncludeFiles(), ClassDef::writeIncludeFiles(), ClassDef::writeInlineDocumentation(), writeJavascriptSearchIndex(), MemberDef::writeLink(), ClassDef::writeMemberDeclarations(), ClassDef::writeMemberList(), writeMemberReference(), writeNamespaceIndex(), writeNamespaceTree(), PageDef::writePageDocumentation(), FileDef::writeSource(), NamespaceDef::writeSummaryLinks(), GroupDef::writeSummaryLinks(), FileDef::writeSummaryLinks(), ClassDef::writeSummaryLinks(), MemberList::writeTagFile(), and FileDef::writeTagFile().
getOuterScope()
Definition * Definition::getOuterScope () const virtual
Definition at line 1894 of file definition.cpp.
References m_impl, and DefinitionImpl::outerScope.
Referenced by MemberDef::_writeEnumValues(), accessibleViaUsingNamespace(), NestingContext::Private::addClasses(), NestingContext::Private::addDirs(), addEnumValuesToEnums(), MemberDef::addListReference(), addMemberDocs(), addMembersToIndex(), NestingContext::Private::addNamespaces(), NestingContext::Private::addPages(), addSourceReferences(), ClassContext::Private::addTemplateDecls(), addVariableToFile(), briefDescriptionAsTooltip(), DotCallGraph::buildGraph(), checkPageRelations(), combineDeclarationAndDefinition(), computeMemberRelations(), createLinkedText(), createTagLessInstance(), DotCallGraph::DotCallGraph(), dumpSymbol(), DefinitionContext< FileContext::Private >::fillPath(), findFriends(), findGlobalMember(), VhdlDocGen::findMember(), findMember(), findMembersWithSpecificName(), findTagLessClasses(), findUsingDirectives(), generateClassList(), generateDocbookForMember(), PerlModGenerator::generatePerlModForMember(), generateXMLForMember(), getDefs(), ClassDef::getOutputFileBase(), getResolvedSymbol(), ClassDef::getTemplateParameterLists(), DocPara::handleInheritDoc(), PageDef::hasParentPage(), GroupDef::insertMember(), ClassDef::insertTemplateInstance(), isAccessibleFrom(), isAccessibleFromWithExpScope(), ClassDef::isEmbeddedInOuterScope(), MemberContext::Private::labels(), linkifyText(), ClassDef::mergeMembers(), DefinitionContext< FileContext::Private >::navigationPath(), navigationPathAsString(), newResolveTypedef(), DocCopy::parse(), ClassDef::qualifiedNameWithTemplateParameters(), resolveRef(), resolveTypeDef(), SymbolContext::Private::scope(), scopeIsTemplate(), searchTemplateSpecs(), transferFunctionReferences(), transferRelatedFunctionDocumentation(), writeClassTree(), MemberDef::writeDeclaration(), writeDirHierarchy(), NamespaceDef::writeDocumentation(), PageDef::writeDocumentation(), ClassDef::writeDocumentation(), writeIndex(), writeJavascriptSearchIndex(), MemberDef::writeMemberDocSimple(), ClassDef::writeMemberList(), writeNamespaceTree(), writePageIndex(), and VhdlDocGen::writeVHDLDeclaration().
getOutputFileBase()
virtual QCString Definition::getOutputFileBase () const pure virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implemented in ClassDef, FileDef, MemberDef, DirDef, GroupDef, PageDef, and NamespaceDef.
Referenced by Qhp::addIndexItem(), DocSets::addIndexItem(), HtmlHelp::addIndexItem(), MemberGroup::addListReferences(), addSectionsToIndex(), TooltipManager::addTooltip(), DocLink::DocLink(), dumpSymbol(), DefinitionContext< FileContext::Private >::fileName(), NestingNodeContext::Private::fileName(), NavPathElemContext::Private::fileName(), SymbolContext::Private::fileName(), generateBriefDoc(), generateLink(), ClassDef::getOutputFileBase(), handleLinkedWord(), navigationPathAsString(), LayoutNavEntry::url(), validatingParseDoc(), writeJavascriptSearchIndex(), DocSets::writeToken(), TooltipManager::writeTooltips(), and VhdlDocGen::writeVHDLDeclaration().
getReference()
QCString Definition::getReference () const virtual
If this definition was imported via a tag file, this function returns the tagfile for the external project. This can be translated into an external link target via Doxygen::tagDestinationDict
Reimplemented in ClassDef, and MemberDef.
Definition at line 1849 of file definition.cpp.
References m_impl, and DefinitionImpl::ref.
Referenced by MemberDef::_writeGroupInclude(), addRelatedPage(), addSectionsToIndex(), buildDirectories(), DotInclDepGraph::buildGraph(), DotGroupCollaboration::buildGraph(), DocLink::DocLink(), DotGroupCollaboration::DotGroupCollaboration(), DotInclDepGraph::DotInclDepGraph(), externalReference(), generateFileRef(), generateLink(), MemberDef::getReference(), ClassDef::getReference(), handleLinkedWord(), recursivelyAddGroupListToTitle(), SymbolContext::Private::relPath(), ClassDef::showUsedFiles(), writeAlphabeticalClassList(), NamespaceSDict::writeDeclaration(), writeDirHierarchy(), GroupDef::writeDirs(), writeDirTreeNode(), writeExampleIndex(), DirDef::writeFileList(), GroupDef::writeFiles(), writeGroupTreeNode(), FileDef::writeIncludeFiles(), writeJavascriptSearchIndex(), MemberDef::writeLink(), writeNamespaceTree(), GroupDef::writeNestedGroups(), writePages(), writePartialDirPath(), writePartialFilePath(), DirDef::writeSubDirList(), and TooltipManager::writeTooltips().
getReferencedByMembers()
MemberSDict * Definition::getReferencedByMembers () const
Definition at line 1904 of file definition.cpp.
References m_impl, and DefinitionImpl::sourceRefByDict.
Referenced by DotCallGraph::buildGraph(), generateDEFForMember(), generateXMLForMember(), MemberContext::Private::sourceRefBys(), and transferFunctionReferences().
getReferencesMembers()
MemberSDict * Definition::getReferencesMembers () const
Definition at line 1899 of file definition.cpp.
References m_impl, and DefinitionImpl::sourceRefsDict.
Referenced by DotCallGraph::buildGraph(), generateDEFForMember(), generateXMLForMember(), MemberContext::Private::sourceRefs(), and transferFunctionReferences().
getSourceAnchor()
QCString Definition::getSourceAnchor () const virtual
Returns the anchor of the source listing of this definition.
Definition at line 899 of file definition.cpp.
References DefinitionImpl::body, m_impl, BodyInfo::startLine, and Htags::useHtags.
Referenced by DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), writeSourceDef(), and TooltipManager::writeTooltips().
getSourceFileBase()
QCString Definition::getSourceFileBase () const virtual
Returns the name of the source listing of this definition.
Reimplemented in ClassDef, and FileDef.
Definition at line 886 of file definition.cpp.
References DefinitionImpl::body, Config_getBool, DefinitionIntf::definitionType(), BodyInfo::fileDef, FileDef::getSourceFileBase(), m_impl, BodyInfo::startLine, and DefinitionIntf::TypeFile.
Referenced by DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), ClassDef::getSourceFileBase(), DefinitionContext< FileContext::Private >::sourceFileName(), writeSourceDef(), and TooltipManager::writeTooltips().
getStartBodyLine()
int Definition::getStartBodyLine () const
Returns the first line of the body of this item (applicable to classes and functions).
Definition at line 1859 of file definition.cpp.
References DefinitionImpl::body, m_impl, and BodyInfo::startLine.
Referenced by _writeSourceRefList(), addClassToContext(), addMemberDocs(), addSourceReferences(), DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), combineDeclarationAndDefinition(), VhdlDocGen::createFlowChart(), createTagLessInstance(), MemberDef::createTemplateInstanceMember(), findFriends(), findMember(), findMemFlow(), findUsingDeclImports(), generateDEFForMember(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), generateXMLForMember(), ClassDef::hasDetailedDescription(), FileDef::hasDetailedDescription(), MemberContext::Private::sourceCode(), writeMemberReference(), VhdlDocGen::writeSource(), and TooltipManager::writeTooltips().
hasBriefDescription()
bool Definition::hasBriefDescription () const
returns TRUE if this class has a brief description
Definition at line 1945 of file definition.cpp.
References briefDescription(), and Config_getBool.
Referenced by DefinitionContext< FileContext::Private >::brief(), NestingNodeContext::Private::brief(), MemberDef::isDetailedSectionVisible(), DirDef::writeBriefDescription(), NamespaceDef::writeBriefDescription(), GroupDef::writeBriefDescription(), FileDef::writeBriefDescription(), and ClassDef::writeBriefDescription().
hasDocumentation()
bool Definition::hasDocumentation () const virtual
Returns TRUE iff the definition is documented (which could be generated documentation)
See also
hasUserDocumentation()
Reimplemented in MemberDef, and ClassDef.
Definition at line 1294 of file definition.cpp.
References DefinitionImpl::brief, Config_getBool, DefinitionImpl::details, DocInfo::doc, BriefInfo::doc, DefinitionImpl::inbodyDocs, and m_impl.
Referenced by dirHasVisibleChildren(), ClassDef::hasDocumentation(), MemberDef::hasDocumentation(), NamespaceDef::isLinkableInProject(), FileDef::isLinkableInProject(), NamespaceSDict::writeDeclaration(), GroupDef::writeDirs(), DirDef::writeFileList(), GroupDef::writeFiles(), GroupDef::writeNestedGroups(), and DirDef::writeSubDirList().
hasSections()
bool Definition::hasSections () const
Definition at line 447 of file definition.cpp.
References m_impl, SectionInfo::Paragraph, SectionInfo::Section, DefinitionImpl::sectionDict, SectionInfo::Subsection, SectionInfo::Subsubsection, and SectionInfo::type.
Referenced by PageDef::writeDocumentation(), and writePages().
hasSources()
bool Definition::hasSources () const
Definition at line 1090 of file definition.cpp.
References DefinitionImpl::body, BodyInfo::endLine, BodyInfo::fileDef, m_impl, and BodyInfo::startLine.
Referenced by MemberContext::Private::hasSources(), and writeInlineCode().
hasUserDocumentation()
bool Definition::hasUserDocumentation () const virtual
Returns TRUE iff the definition is documented by the user.
Definition at line 1309 of file definition.cpp.
References DefinitionImpl::brief, DefinitionImpl::details, DocInfo::doc, BriefInfo::doc, DefinitionImpl::inbodyDocs, and m_impl.
Referenced by GroupDef::isLinkable(), and MemberDef::warnIfUndocumented().
id()
QCString Definition::id () const
Definition at line 413 of file definition.cpp.
References DefinitionImpl::id, and m_impl.
Referenced by setId(), MemberDef::setMemberGroupId(), NamespaceDef::writeTagFile(), MemberDef::writeTagFile(), and ClassDef::writeTagFile().
inbodyDocumentation()
QCString Definition::inbodyDocumentation () const
Returns the documentation found inside the body of a member
Definition at line 1801 of file definition.cpp.
References DocInfo::doc, DefinitionImpl::inbodyDocs, and m_impl.
Referenced by addMemberDocs(), ClassDef::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findDefineDocumentation(), findEnumDocumentation(), findFriends(), findUsingDeclImports(), generateXMLForMember(), DefinitionContext< FileContext::Private >::inbodyDocs(), inheritDocumentation(), MemberDef::isDetailedSectionLinkable(), GroupDef::writeDetailedDescription(), MemberDef::writeDocumentation(), PageDef::writePageDocumentation(), and GroupDef::writePageDocumentation().
inbodyFile()
QCString Definition::inbodyFile () const
Returns the file in which the in body documentation was found
Definition at line 1811 of file definition.cpp.
References DocInfo::file, DefinitionImpl::inbodyDocs, m_impl, and m_name.
Referenced by _setInbodyDocumentation(), ClassDef::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findFriends(), findUsingDeclImports(), DefinitionContext< FileContext::Private >::inbodyDocs(), inheritDocumentation(), GroupDef::writeDetailedDescription(), and MemberDef::writeDocumentation().
inbodyLine()
int Definition::inbodyLine () const
Returns the line at which the first in body documentation part was found
Definition at line 1806 of file definition.cpp.
References DefinitionImpl::inbodyDocs, DocInfo::line, and m_impl.
Referenced by _setInbodyDocumentation(), ClassDef::addMembersToTemplateInstance(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberGroup::distributeMemberGroupDocumentation(), findFriends(), findUsingDeclImports(), generateXMLForMember(), DefinitionContext< FileContext::Private >::inbodyDocs(), inheritDocumentation(), GroupDef::writeDetailedDescription(), and MemberDef::writeDocumentation().
isArtificial()
bool Definition::isArtificial () const
returns TRUE if this entity was artificially introduced, for instance because it is used to show a template instantiation relation.
Definition at line 1844 of file definition.cpp.
References DefinitionImpl::isArtificial, and m_impl.
Referenced by generateXMLForClass(), NamespaceDef::isLinkableInProject(), ClassDef::isLinkableInProject(), AllMembersListContext::Private::Private(), and ClassDef::writeMemberList().
isHidden()
bool Definition::isHidden () const
Returns TRUE iff this item is supposed to be hidden from the output.
Definition at line 1829 of file definition.cpp.
References DefinitionImpl::hidden, and m_impl.
Referenced by MemberDef::_computeLinkableInProject(), GroupDef::addClass(), DotClassGraph::addClass(), ClassListContext::Private::addClasses(), DotGfxHierarchyTable::addClassList(), GroupDef::addDir(), GroupDef::addExample(), GroupDef::addFile(), DotGfxHierarchyTable::addHierarchy(), GroupDef::addNamespace(), GroupDef::addPage(), DotInclDepGraph::buildGraph(), DotClassGraph::DotClassGraph(), generateClassList(), generateDocbookForClass(), generateDocbookForMember(), generateDocbookForNamespace(), generateXMLForClass(), generateXMLForMember(), generateXMLForNamespace(), getResolvedClass(), ClassDef::hasNonReferenceSuperClass(), FileDef::insertClass(), NamespaceDef::insertMember(), GroupDef::insertMember(), FileDef::insertMember(), FileDef::insertNamespace(), ClassDef::insertTemplateInstance(), ClassDef::internalInsertMember(), MemberDef::isBriefSectionVisible(), MemberDef::isDetailedSectionLinkable(), NamespaceDef::isLinkableInProject(), ClassDef::isLinkableInProject(), setOuterScope(), writeInnerClasses(), and writeInnerNamespaces().
isLinkable()
virtual bool Definition::isLinkable () const pure virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implemented in MemberDef, ClassDef, FileDef, NamespaceDef, GroupDef, DirDef, and PageDef.
Referenced by DocSets::addIndexItem(), DocLink::DocLink(), DocRef::DocRef(), handleLinkedWord(), DefinitionContext< FileContext::Private >::isLinkable(), NestingNodeContext::Private::isLinkable(), NavPathElemContext::Private::isLinkable(), isVisible(), navigationPathAsString(), and pathFragment().
isLinkableInProject()
virtual bool Definition::isLinkableInProject () const pure virtual
Returns TRUE iff it is possible to link to this item within this project.
Implemented in MemberDef, ClassDef, FileDef, NamespaceDef, GroupDef, DirDef, and PageDef.
Referenced by ClassDef::getOutputFileBase(), DefinitionContext< FileContext::Private >::isLinkableInProject(), and isVisibleInProject().
isLinkableViaGroup()
bool Definition::isLinkableViaGroup () const
Definition at line 1879 of file definition.cpp.
References GroupDef::isLinkable(), and partOfGroups().
Referenced by FileDef::isLinkableInProject().
isReference()
bool Definition::isReference () const virtual
Returns TRUE if this definition is imported via a tag file.
Reimplemented in MemberDef, and ClassDef.
Definition at line 1854 of file definition.cpp.
References m_impl, and DefinitionImpl::ref.
Referenced by FileListContext::Private::addFiles(), NestingContext::Private::addModules(), ModuleListContext::Private::addModules(), PageListContext::Private::addPages(), countGroups(), PageDef::documentedPage(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateDEFForFile(), generateDEFForNamespace(), FileName::generateDiskNames(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForNamespace(), generateDocbookForPage(), generateFileSources(), generateGroupDocs(), generateLink(), generatePageDocs(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), FileDef::generateSourceFile(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), generateXMLForPage(), PageDef::isLinkable(), DirDef::isLinkable(), NamespaceDef::isLinkable(), FileDef::isLinkable(), PageDef::isLinkableInProject(), DirDef::isLinkableInProject(), GroupDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), FileDef::isLinkableInProject(), ClassDef::isReference(), MemberDef::isReference(), DefinitionContext< FileContext::Private >::isReference(), NestingNodeContext::Private::isReference(), NavPathElemContext::Private::isReference(), parseFiles(), ExampleListContext::Private::Private(), FileDef::setDiskName(), NamespaceDef::setFileName(), RTFGenerator::startIndexSection(), LatexGenerator::startIndexSection(), PageDef::visibleInIndex(), writeDirTreeNode(), writeGroupTreeNode(), writeIndex(), GroupDef::writePageDocumentation(), writePageIndex(), writeSingleFileIndex(), and FileDef::writeTagFile().
isVisible()
bool Definition::isVisible () const virtual
Returns TRUE iff the name may appear in the output
Definition at line 1839 of file definition.cpp.
References DefinitionImpl::hidden, isLinkable(), and m_impl.
Referenced by NestingContext::Private::addModules(), writeGroupTreeNode(), GroupDef::writeNestedGroups(), and GroupDef::writeTagFile().
isVisibleInProject()
bool Definition::isVisibleInProject () const virtual
Returns TRUE iff the name is part of this project and may appear in the output
Definition at line 1834 of file definition.cpp.
References DefinitionImpl::hidden, isLinkableInProject(), and m_impl.
localName()
QCString Definition::localName () const
Returns the local name without any scope qualifiers.
Definition at line 1434 of file definition.cpp.
References DefinitionImpl::localName, and m_impl.
Referenced by MemberDef::_addToSearchIndex(), MemberDef::_computeIsConstructor(), NamespaceDef::addInnerCompound(), ClassDef::addInnerCompound(), SearchIndexList::append(), ClassDef::className(), createJavascriptSearchIndex(), endOfPathIsUsedClass(), getDefs(), NamespaceDef::insertMember(), ClassDef::insertTemplateInstance(), navigationPathAsString(), MemberDef::qualifiedName(), ClassDef::qualifiedNameWithTemplateParameters(), SymbolContext::Private::scope(), searchTemplateSpecs(), NavPathElemContext::Private::text(), FileDef::writeDocumentation(), ClassDef::writeDocumentationContents(), writeJavascriptSearchIndex(), NamespaceDef::writeQuickMemberLinks(), GroupDef::writeQuickMemberLinks(), FileDef::writeQuickMemberLinks(), and VhdlDocGen::writeVHDLDeclaration().
makePartOfGroup()
void Definition::makePartOfGroup (GroupDef * gd)
Definition at line 1439 of file definition.cpp.
References m_impl, and DefinitionImpl::partOfGroups.
Referenced by addClassToGroups(), addDirsAsGroups(), addDirToGroups(), addExampleToGroups(), addGroupToGroups(), addNamespaceToGroups(), GroupDef::addPage(), buildFileList(), createTagLessInstance(), and Definition().
mergeRefItems()
void Definition::mergeRefItems (Definition * d)
Definition at line 1465 of file definition.cpp.
References _getXRefListId(), m_impl, ListItemInfo::type, DefinitionImpl::xrefListItems, and xrefListItems().
Referenced by combineDeclarationAndDefinition().
name()
const QCString& Definition::name () const inline
Returns the name of the definition
Definition at line 114 of file definition.h.
References m_name.
Referenced by MemberDef::_computeIsConstructor(), MemberDef::_computeIsDestructor(), MemberDef::_computeLinkableInProject(), _setSymbolName(), MemberDef::_writeCategoryRelation(), MemberDef::_writeEnumValues(), _writeSourceRefList(), accessibleViaUsingNamespace(), GroupDef::addClass(), DotClassGraph::addClass(), DotGfxHierarchyTable::addClassList(), addClassMemberNameToIndex(), addClassToContext(), addEnumValuesToEnums(), GroupDef::addExample(), addFileMemberNameToIndex(), addGroupToGroups(), DotGfxHierarchyTable::addHierarchy(), Qhp::addIndexItem(), DocSets::addIndexItem(), HtmlHelp::addIndexItem(), PageDef::addInnerCompound(), addInstance(), PerlModGenerator::addListOfAllMembers(), MemberDef::addListReference(), GroupDef::addListReferences(), addMemberDocs(), addMembersToIndex(), ClassDef::addMembersToTemplateInstance(), addMemberToGroups(), addMemberToSearchIndex(), GroupDef::addNamespace(), addNamespaceMemberNameToIndex(), GroupDef::addPage(), addPageToContext(), addRelatedPage(), addSourceReferencedBy(), addSourceReferences(), addTemplateList(), addToMap(), ClassDef::addUsedByClass(), ClassDef::addUsedClass(), addVariableToFile(), FlowChart::alignFuncProc(), assignBinding(), buildDirectories(), buildExampleList(), buildFunctionList(), DotCallGraph::buildGraph(), DotGroupCollaboration::buildGraph(), DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), checkArgumentName(), checkPageRelations(), ClassDef::ClassDef(), classInheritedProtectionLevel(), MemberName::compareValues(), MemberNameInfo::compareValues(), PageSDict::compareValues(), MemberList::compareValues(), MemberIndexList::compareValues(), MemberSDict::compareValues(), NamespaceList::compareValues(), NamespaceSDict::compareValues(), DefinitionList::compareValues(), BaseClassList::compareValues(), compItems(), computeCommonDirPrefix(), computeTemplateClassRelations(), VhdlDocGen::convertFileNameToClassName(), FlowChart::convertNameToFileName(), MemberList::countDecMembers(), MemberList::countEnumValues(), createJavascriptSearchIndex(), createTagLessInstance(), MemberDef::createTemplateInstanceMember(), ClassSDict::declVisible(), Definition(), MemberDef::displayDefinition(), GroupDef::displayName(), PageDef::displayName(), NamespaceDef::displayName(), MemberDef::displayName(), DotCallGraph::DotCallGraph(), DotGroupCollaboration::DotGroupCollaboration(), dumpSymbol(), PageContext::Private::example(), extractNamespaceName(), VhdlDocGen::findAllPackages(), VhdlDocGen::findArchitecture(), findClassRelation(), findDirDocumentation(), findEnumDocumentation(), findEnums(), VhdlDocGen::findFunction(), findGlobalMember(), findGroupScope(), findMainPage(), VhdlDocGen::findMember(), findMember(), VhdlDocGen::findMemberDef(), findMemFlow(), findScopeFromQualifiedName(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsedNamespace(), findUsingDeclarations(), VhdlDocGen::findVhdlClass(), generateClassList(), generateDEFForClass(), generateDEFForMember(), generateDEFForNamespace(), generateDocbook(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForMember(), generateDocbookForNamespace(), generateDocbookForPage(), generateExampleDocs(), generateNamespaceDocs(), RefList::generatePage(), generatePageDocs(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), generateXML(), generateXMLForClass(), generateXMLForDir(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), getCanonicalTypeForIdentifier(), MemberDef::getClassDefOfAnonymousType(), VhdlDocGen::getClassName(), getDefs(), GlobalsIndexContext::Private::getMembersFiltered(), ClassMembersIndexContext::Private::getMembersFiltered(), NamespaceMembersIndexContext::Private::getMembersFiltered(), MemberDef::getOutputFileBase(), getResolvedClassRec(), ClassDef::getVariableInstance(), DocPara::handleInheritDoc(), MemberContext::Private::handleNameWithContextFor(), MemberDefImpl::init(), MemberContext::Private::initializerAsCode(), NamespaceDef::insertClass(), FileDef::insertClass(), NamespaceDef::insertMember(), GroupDef::insertMember(), FileDef::insertMember(), NamespaceDef::insertNamespace(), FileDef::insertNamespace(), ClassDef::insertTemplateInstance(), ClassDef::internalInsertMember(), isAccessibleFromWithExpScope(), MemberContext::Private::isAnonymous(), ClassDef::isBaseClass(), MemberDef::isDocumentedFriendClass(), ClassDef::isExtension(), NamespaceDef::isLinkableInProject(), ClassDef::isLinkableInProject(), isStandardFunc(), VhdlDocGen::isSubClass(), ClassDef::isSubClass(), DiagramItem::label(), linkifyText(), NamespaceDef::localName(), matchArgument(), mergeCategories(), ClassDef::mergeCategory(), ClassDef::mergeMembers(), minClassDistance(), FileDef::name(), navigationPathAsString(), normalizeNonTemplateArgumentsInString(), MemberDef::objCMethodName(), DocCopy::parse(), DocXRefItem::parse(), AllMembersListContext::Private::Private(), processTagLessClasses(), MemberDef::qualifiedName(), qualifiedName(), GroupDef::removeMember(), resolveClassNestingRelations(), resolveLink(), SymbolContext::Private::scope(), MemberDef::setAnchor(), ClassDef::setClassName(), SearchIndex::setCurrentDoc(), DirDef::setDiskName(), PageDef::setFileName(), GroupDef::setGroupTitle(), setLocalName(), setName(), MemberContext::Private::sourceCode(), PageContext::Private::title(), transferFunctionReferences(), transferRelatedFunctionDocumentation(), trimBaseClassScope(), trimTemplateSpecifiers(), validatingParseDoc(), MemberDef::virtualness(), HtmlDocVisitor::visitPre(), MemberDef::warnIfUndocumented(), writeAlphabeticalClassList(), writeBoxMemberList(), writeClassToDot(), writeClassTree(), writeColumn(), ClassSDict::writeDeclaration(), MemberDef::writeDeclaration(), writeDefArgumentList(), ClassDef::writeDetailedDocumentationBody(), writeDirTreeNode(), NamespaceDef::writeDocumentation(), ClassSDict::writeDocumentation(), PageDef::writeDocumentation(), GroupDef::writeDocumentation(), DirDef::writeDocumentation(), MemberList::writeDocumentation(), MemberDef::writeDocumentation(), ClassDef::writeDocumentation(), ClassDef::writeDocumentationForInnerClasses(), MemberList::writeDocumentationPage(), MemberDef::writeEnumDeclaration(), writeExampleIndex(), writeExceptionListImpl(), writeGroupTreeNode(), writeIndex(), ClassDef::writeInlineDocumentation(), writeInnerClasses(), writeInnerNamespaces(), writeInnerPages(), writeJavascriptSearchIndex(), writeLink(), MemberDef::writeLink(), writeListOfAllMembers(), MemberDef::writeMemberDocSimple(), GroupDef::writeMemberDocumentation(), ClassDef::writeMemberList(), writeMemberList(), GroupDef::writeMemberPages(), writeMemberReference(), VhdlDocGen::writeOverview(), PageDef::writePageDocumentation(), GroupDef::writePageDocumentation(), writePages(), MemberList::writePlainDeclarations(), VhdlDocGen::writePlainVHDLDeclarations(), ClassDef::writeQuickMemberLinks(), VhdlDocGen::writeStringLink(), NamespaceDef::writeTagFile(), PageDef::writeTagFile(), GroupDef::writeTagFile(), DirDef::writeTagFile(), VhdlDocGen::writeTagFile(), FileDef::writeTagFile(), MemberDef::writeTagFile(), ClassDef::writeTagFile(), DocSets::writeToken(), writeUCFLink(), VhdlDocGen::writeVHDLDeclaration(), writeVhdlEntityToolTip(), and VhdlDocGen::writeVHDLTypeDocumentation().
navigationPathAsString()
QCString Definition::navigationPathAsString () const
Returns the string used in the footer for $navpath when GENERATE_TREEVIEW is enabled
Definition at line 1547 of file definition.cpp.
References anchor(), convertToHtml(), DefinitionIntf::definitionType(), getOuterScope(), getOutputFileBase(), Doxygen::globalScope, Doxygen::htmlFileExtension, isLinkable(), localName(), name(), navigationPathAsString(), DefinitionIntf::TypeClass, DefinitionIntf::TypeFile, DefinitionIntf::TypeGroup, and DefinitionIntf::TypePage.
Referenced by endFileWithNavPath(), navigationPathAsString(), and writeNavigationPath().
partOfGroups()
GroupList * Definition::partOfGroups () const
Definition at line 1874 of file definition.cpp.
References m_impl, and DefinitionImpl::partOfGroups.
Referenced by DotGroupCollaboration::addCollaborationMember(), addMembersToIndex(), DotGroupCollaboration::buildGraph(), createTagLessInstance(), distributeClassGroupRelations(), PageDef::getGroupDef(), ClassDef::getOutputFileBase(), GroupDef::isASubGroup(), ClassDef::isEmbeddedInOuterScope(), isLinkableViaGroup(), recursivelyAddGroupListToTitle(), writeClassTree(), and ClassSDict::writeDocumentation().
pathFragment()
QCString Definition::pathFragment () const
Definition at line 1511 of file definition.cpp.
References DefinitionIntf::definitionType(), Doxygen::globalScope, isLinkable(), DefinitionImpl::localName, m_impl, DefinitionImpl::outerScope, pathFragment(), DefinitionIntf::TypeGroup, and DefinitionIntf::TypePage.
Referenced by pathFragment(), and DirRelation::writeDocumentation().
qualifiedName()
QCString Definition::qualifiedName () const virtual
Returns the fully qualified name of this definition
Reimplemented in MemberDef.
Definition at line 1375 of file definition.cpp.
References getLanguage(), getLanguageSpecificSeparator(), DefinitionImpl::localName, m_impl, name(), DefinitionImpl::outerScope, DefinitionImpl::qualifiedName, and qualifiedName().
Referenced by GroupDef::addClass(), DotGroupCollaboration::addCollaborationMember(), FileDef::addIncludedUsingDirectives(), DocSets::addIndexItem(), NamespaceDef::addListReferences(), ClassDef::addListReferences(), NamespaceDef::addUsingDeclaration(), FileDef::addUsingDeclaration(), NamespaceDef::addUsingDirective(), FileDef::addUsingDirective(), findGlobalMember(), getCanonicalTypeForIdentifier(), getResolvedSymbol(), newResolveTypedef(), MemberDef::qualifiedName(), qualifiedName(), ClassDef::qualifiedNameWithTemplateParameters(), SymbolContext::Private::scope(), searchTemplateSpecs(), validatingParseDoc(), GroupDef::writeGroupGraph(), writeJavascriptSearchIndex(), and TooltipManager::writeTooltips().
removeFromMap()
void Definition::removeFromMap (Definition * d) static private
Definition at line 254 of file definition.cpp.
References m_symbolName, Doxygen::symbolMap, and symbolName().
Referenced by ~Definition().
setArtificial()
void Definition::setArtificial (bool b)
Definition at line 1924 of file definition.cpp.
References DefinitionImpl::isArtificial, and m_impl.
Referenced by addClassToContext(), addVariableToClass(), buildNamespaceList(), findClassRelation(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsingDirectives(), and ClassDef::mergeCategory().
setBodyDef()
void Definition::setBodyDef (FileDef * fd)
Definition at line 1084 of file definition.cpp.
References DefinitionImpl::body, BodyInfo::fileDef, and m_impl.
Referenced by addClassToContext(), addInstance(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addVariableToClass(), buildFunctionList(), buildNamespaceList(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberDef::createTemplateInstanceMember(), findDefineDocumentation(), findEnums(), findFriends(), findMember(), and findUsingDeclImports().
setBodySegment()
void Definition::setBodySegment (int bls, int ble)
Definition at line 1076 of file definition.cpp.
References DefinitionImpl::body, BodyInfo::endLine, m_impl, and BodyInfo::startLine.
Referenced by addClassToContext(), addInstance(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addVariableToClass(), buildFunctionList(), buildNamespaceList(), combineDeclarationAndDefinition(), createTagLessInstance(), MemberDef::createTemplateInstanceMember(), findDefineDocumentation(), findEnums(), findFriends(), findMember(), and findUsingDeclImports().
setBriefDescription()
void Definition::setBriefDescription (const char * b, const char * briefFile, int briefLine) virtual
Sets the brief description of this definition to b. A dot is added to the sentence if not available.
Reimplemented in MemberDef.
Definition at line 687 of file definition.cpp.
References _setBriefDescription().
Referenced by addClassToContext(), addRelatedPage(), addVariableToFile(), buildExampleList(), buildFileList(), buildGroupListFiltered(), buildNamespaceList(), createTagLessInstance(), findDirDocumentation(), findMainPage(), findUsingDirectives(), and MemberDef::setBriefDescription().
setCookie()
void Definition::setCookie (Cookie * cookie) inline
Definition at line 351 of file definition.h.
References cookie(), and m_cookie.
Referenced by generateOutputViaTemplate(), ClassContext::Private::Private(), NamespaceContext::Private::Private(), FileContext::Private::Private(), DirContext::Private::Private(), PageContext::Private::Private(), MemberContext::Private::Private(), and ModuleContext::Private::Private().
setDocumentation()
void Definition::setDocumentation (const char * d, const char * docFile, int docLine, bool stripWhiteSpace = TRUE) virtual
Sets the documentation of this definition to d.
Reimplemented in MemberDef.
Definition at line 612 of file definition.cpp.
References _setDocumentation().
Referenced by addClassToContext(), addRelatedPage(), addVariableToFile(), buildFileList(), buildGroupListFiltered(), buildNamespaceList(), createTagLessInstance(), findDirDocumentation(), findUsingDirectives(), PageDef::PageDef(), and MemberDef::setDocumentation().
setHidden()
void Definition::setHidden (bool b) virtual
Reimplemented in MemberDef.
Definition at line 1919 of file definition.cpp.
References DefinitionImpl::hidden, and m_impl.
Referenced by addClassToContext(), buildNamespaceList(), findUsingDirectives(), ClassDef::insertTemplateInstance(), and MemberDef::setHidden().
setId()
void Definition::setId (const char * name)
Sets a unique id for the symbol. Used for libclang integration.
Definition at line 402 of file definition.cpp.
References Doxygen::clangUsrMap, DefinitionImpl::id, id(), and m_impl.
Referenced by addClassToContext(), addEnumValuesToEnums(), addMethodToClass(), addVariableToClass(), buildFunctionList(), buildNamespaceList(), findEnums(), findMember(), findUsingDeclImports(), and findUsingDirectives().
setInbodyDocumentation()
void Definition::setInbodyDocumentation (const char * d, const char * docFile, int docLine) virtual
Set the documentation that was found inside the body of an item. If there was already some documentation set, the new documentation will be appended.
Reimplemented in MemberDef.
Definition at line 711 of file definition.cpp.
References _setInbodyDocumentation().
Referenced by buildGroupListFiltered(), and MemberDef::setInbodyDocumentation().
setLanguage()
void Definition::setLanguage (SrcLangExt lang)
Definition at line 1934 of file definition.cpp.
References DefinitionImpl::lang, and m_impl.
Referenced by addClassToContext(), addEnumValuesToEnums(), addInstance(), addInterfaceOrServiceToServiceOrSingleton(), addMethodToClass(), addRelatedPage(), ClassDef::addTypeConstraint(), addVariableToClass(), buildExampleList(), buildFunctionList(), buildGroupListFiltered(), buildNamespaceList(), buildScopeFromQualifiedName(), createTagLessInstance(), FileDef::FileDef(), findClassRelation(), findDefineDocumentation(), findEnums(), findMember(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsingDeclImports(), findUsingDirectives(), and GroupDef::updateLanguage().
setLocalName()
void Definition::setLocalName (const QCString name)
Definition at line 1929 of file definition.cpp.
References DefinitionImpl::localName, m_impl, and name().
Referenced by DirDef::DirDef().
setName()
void Definition::setName (const char * name) virtual
Sets a new name for the definition
Reimplemented in ClassDef.
Definition at line 396 of file definition.cpp.
References m_name, and name().
Referenced by buildNamespaceList(), FileName::generateDiskNames(), ClassDef::setName(), and VhdlDocGen::writeVHDLDeclaration().
setOuterScope()
void Definition::setOuterScope (Definition * d) virtual
Definition at line 1415 of file definition.cpp.
References DefinitionImpl::hidden, isHidden(), m_impl, DefinitionImpl::outerScope, and DefinitionImpl::qualifiedName.
Referenced by addEnumValuesToEnums(), PageDef::addInnerCompound(), DirDef::addSubDir(), buildNamespaceList(), buildScopeFromQualifiedName(), createTagLessInstance(), findClassRelation(), ClassDef::insertTemplateInstance(), MemberDef::moveTo(), resolveClassNestingRelations(), MemberDef::setMemberClass(), and MemberDef::setNamespace().
setReference()
void Definition::setReference (const char * r)
Sets the tag file id via which this definition was imported.
Definition at line 1909 of file definition.cpp.
References m_impl, and DefinitionImpl::ref.
Referenced by addRelatedPage(), buildGroupListFiltered(), buildNamespaceList(), ClassDef::ClassDef(), FileDef::FileDef(), NamespaceDef::NamespaceDef(), and MemberDef::setTagInfo().
setRefItems()
void Definition::setRefItems (const QList< ListItemInfo > * sli)
Definition at line 1445 of file definition.cpp.
References m_impl, and DefinitionImpl::xrefListItems.
Referenced by addClassToContext(), addEnumValuesToEnums(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addRelatedPage(), addVariableToClass(), addVariableToFile(), buildFileList(), buildFunctionList(), buildGroupListFiltered(), buildNamespaceList(), Definition(), findDefineDocumentation(), findDirDocumentation(), findEnumDocumentation(), findEnums(), findMember(), and findUsingDirectives().
symbolName()
QCString Definition::symbolName () const
Returns the name of this definition as it appears in the symbol map.
Definition at line 1683 of file definition.cpp.
References m_symbolName.
Referenced by addToMap(), VhdlDocGen::findMemberDef(), and removeFromMap().
writeDocAnchorsToTagFile()
void Definition::writeDocAnchorsToTagFile (FTextStream & tagFile)
Writes the documentation anchors of the definition to the Doxygen::tagFile stream.
Definition at line 520 of file definition.cpp.
References convertToXML(), DefinitionIntf::definitionType(), endl(), SectionInfo::fileName, SectionInfo::generated, SectionInfo::label, m_impl, SectionInfo::ref, DefinitionImpl::sectionDict, SectionInfo::title, and DefinitionIntf::TypeMember.
Referenced by NamespaceDef::writeTagFile(), PageDef::writeTagFile(), GroupDef::writeTagFile(), DirDef::writeTagFile(), VhdlDocGen::writeTagFile(), FileDef::writeTagFile(), MemberDef::writeTagFile(), and ClassDef::writeTagFile().
writeInlineCode()
void Definition::writeInlineCode (OutputList & ol, const char * scopeName)
Write code of this definition into the documentation
Definition at line 1098 of file definition.cpp.
References FileDef::absFilePath(), DefinitionImpl::body, Config_getBool, DefinitionImpl::defFileExt, DefinitionIntf::definitionType(), OutputList::endCodeFragment(), BodyInfo::endLine, BodyInfo::fileDef, ParserManager::getParser(), hasSources(), DefinitionImpl::lang, m_impl, ParserInterface::parseCode(), Doxygen::parserManager, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), readCodeFragment(), ParserInterface::resetCodeParserState(), OutputList::startCodeFragment(), BodyInfo::startLine, and DefinitionIntf::TypeMember.
Referenced by MemberDef::writeDocumentation().
writeNavigationPath()
void Definition::writeNavigationPath (OutputList & ol) const
Definition at line 1599 of file definition.cpp.
References OutputList::disableAllBut(), OutputGenerator::Html, navigationPathAsString(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), and OutputList::writeNavigationPath().
Referenced by NamespaceDef::writeDocumentation(), PageDef::writeDocumentation(), DirDef::writeDocumentation(), FileDef::writeDocumentation(), DirRelation::writeDocumentation(), ClassDef::writeDocumentation(), MemberList::writeDocumentationPage(), ClassDef::writeMemberList(), and FileDef::writeSource().
writeQuickMemberLinks()
virtual void Definition::writeQuickMemberLinks (OutputList & , MemberDef *) const inline virtual
Reimplemented in ClassDef, FileDef, GroupDef, and NamespaceDef.
Definition at line 338 of file definition.h.
Referenced by MemberList::writeDocumentationPage().
writeSourceDef()
void Definition::writeSourceDef (OutputList & ol, const char * scopeName)
Write a reference to the source code defining this definition
Definition at line 919 of file definition.cpp.
References DefinitionImpl::body, Config_getBool, OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enableAll(), OutputList::endParagraph(), err(), BodyInfo::fileDef, getSourceAnchor(), getSourceFileBase(), OutputGenerator::Html, OutputGenerator::Latex, m_impl, OutputGenerator::Man, FileDef::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, BodyInfo::startLine, OutputList::startParagraph(), theTranslator, Translator::trDefinedAtLineInSourceFile(), and OutputList::writeObjectLink().
Referenced by ClassDef::writeDetailedDocumentationBody(), and MemberDef::writeDocumentation().
writeSourceReffedBy()
void Definition::writeSourceReffedBy (OutputList & ol, const char * scopeName)
Definition at line 1278 of file definition.cpp.
References _writeSourceRefList(), Config_getBool, m_impl, DefinitionImpl::sourceRefByDict, theTranslator, and Translator::trReferencedBy().
Referenced by MemberDef::writeDocumentation().
writeSourceRefs()
void Definition::writeSourceRefs (OutputList & ol, const char * scopeName)
Definition at line 1286 of file definition.cpp.
References _writeSourceRefList(), Config_getBool, m_impl, DefinitionImpl::sourceRefsDict, theTranslator, and Translator::trReferences().
Referenced by MemberDef::writeDocumentation().
writeSummaryLinks()
virtual void Definition::writeSummaryLinks (OutputList &) inline virtual
Reimplemented in ClassDef, FileDef, GroupDef, and NamespaceDef.
Definition at line 339 of file definition.h.
Referenced by startTitle().
writeToc()
void Definition::writeToc (OutputList & ol)
Definition at line 1616 of file definition.cpp.
References convertToHtml(), OutputList::disableAllBut(), OutputGenerator::Html, SectionInfo::label, m_impl, SectionInfo::Paragraph, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SectionInfo::Section, DefinitionImpl::sectionDict, SectionInfo::Subsection, SectionInfo::Subsubsection, theTranslator, SectionInfo::title, Translator::trRTFTableOfContents(), SectionInfo::type, and OutputList::writeString().
Referenced by PageDef::writeDocumentation(), and writeIndex().
xrefListItems()
QList< ListItemInfo > * Definition::xrefListItems () const
Definition at line 1506 of file definition.cpp.
References m_impl, and DefinitionImpl::xrefListItems.
Referenced by MemberDef::addListReference(), GroupDef::addListReferences(), NamespaceDef::addListReferences(), FileDef::addListReferences(), ClassDef::addListReferences(), addListReferences(), and mergeRefItems().
Member Data Documentation
m_cookie
Cookie* Definition::m_cookie private
Definition at line 377 of file definition.h.
Referenced by cookie(), setCookie(), and ~Definition().
m_defColumn
int Definition::m_defColumn private
Definition at line 376 of file definition.h.
Referenced by Definition(), and getDefColumn().
m_defLine
int Definition::m_defLine private
Definition at line 375 of file definition.h.
Referenced by Definition(), and getDefLine().
m_impl
DefinitionImpl* Definition::m_impl private
Definition at line 371 of file definition.h.
Referenced by _getXRefListId(), _setBriefDescription(), _setDocumentation(), _setInbodyDocumentation(), _writeSourceRefList(), addSectionsToDefinition(), addSectionsToIndex(), addSourceReferencedBy(), addSourceReferences(), briefDescription(), briefDescriptionAsTooltip(), briefFile(), briefLine(), Definition(), docFile(), docLine(), documentation(), getBodyDef(), getDefFileExtension(), getDefFileName(), getEndBodyLine(), getLanguage(), getOuterScope(), getReference(), getReferencedByMembers(), getReferencesMembers(), getSourceAnchor(), getSourceFileBase(), getStartBodyLine(), hasDocumentation(), hasSections(), hasSources(), hasUserDocumentation(), id(), inbodyDocumentation(), inbodyFile(), inbodyLine(), isArtificial(), isHidden(), isReference(), isVisible(), isVisibleInProject(), localName(), makePartOfGroup(), mergeRefItems(), partOfGroups(), pathFragment(), qualifiedName(), setArtificial(), setBodyDef(), setBodySegment(), setHidden(), setId(), setLanguage(), setLocalName(), setOuterScope(), setReference(), setRefItems(), writeDocAnchorsToTagFile(), writeInlineCode(), writeSourceDef(), writeSourceReffedBy(), writeSourceRefs(), writeToc(), xrefListItems(), and ~Definition().
m_isSymbol
bool Definition::m_isSymbol private
Definition at line 373 of file definition.h.
Referenced by Definition(), and ~Definition().
m_name
QCString Definition::m_name private
Definition at line 372 of file definition.h.
Referenced by briefFile(), Definition(), docFile(), inbodyFile(), name(), and setName().
m_symbolName
QCString Definition::m_symbolName private
Definition at line 374 of file definition.h.
Referenced by _setSymbolName(), removeFromMap(), and symbolName().
The documentation for this class was generated from the following files:
src/definition.h
src/definition.cpp