Doxygen: BufStr Class Reference
BufStr Class Reference
Buffer used to store strings.
#include <bufstr.h>
Public Member Functions
BufStr (int size)
~BufStr ()
void addChar (char c)
void addArray (const char *a, int len)
void skip (uint s)
void shrink (uint newlen)
void resize (uint newlen)
int size () const
char * data () const
char & at (uint i) const
bool isEmpty () const
operator const char * () const
uint curPos () const
void dropFromStart (uint bytes)
Private Member Functions
void makeRoomFor (uint size)
Private Attributes
uint m_size
uint m_writeOffset
const int m_spareRoom
char * m_buf
Detailed Description
Buffer used to store strings.
This buffer is used append characters and strings. It will automatically resize itself, yet provide efficient random access to the content.
Definition at line 30 of file bufstr.h.
Constructor & Destructor Documentation
BufStr()
BufStr::BufStr (int size) inline
Definition at line 33 of file bufstr.h.
References m_buf.
~BufStr()
BufStr::~BufStr () inline
Definition at line 38 of file bufstr.h.
References m_buf.
Member Function Documentation
addArray()
void BufStr::addArray (const char * a, int len) inline
Definition at line 47 of file bufstr.h.
References m_buf, m_writeOffset, and makeRoomFor().
Referenced by readInputFile().
addChar()
void BufStr::addChar (char c) inline
Definition at line 42 of file bufstr.h.
References m_buf, m_writeOffset, and makeRoomFor().
Referenced by readInputFile().
at()
char& BufStr::at (uint i) const inline
Definition at line 85 of file bufstr.h.
References m_buf.
Referenced by readInputFile().
curPos()
uint BufStr::curPos () const inline
Definition at line 97 of file bufstr.h.
References m_writeOffset.
Referenced by readInputFile().
data()
char* BufStr::data () const inline
Definition at line 81 of file bufstr.h.
References m_buf.
Referenced by readInputFile(), removeEmptyLines(), and transcodeCharacterBuffer().
dropFromStart()
void BufStr::dropFromStart (uint bytes) inline
Definition at line 101 of file bufstr.h.
References m_buf, m_size, and m_writeOffset.
Referenced by readInputFile().
isEmpty()
bool BufStr::isEmpty () const inline
Definition at line 89 of file bufstr.h.
References m_writeOffset.
makeRoomFor()
void BufStr::makeRoomFor (uint size) inline private
Definition at line 109 of file bufstr.h.
References m_size, m_spareRoom, m_writeOffset, and resize().
Referenced by addArray(), addChar(), and skip().
operator const char *()
BufStr::operator const char * () const inline
Definition at line 93 of file bufstr.h.
References m_buf.
resize()
void BufStr::resize (uint newlen) inline
Definition at line 63 of file bufstr.h.
References m_buf, m_size, m_spareRoom, and m_writeOffset.
Referenced by makeRoomFor(), and shrink().
shrink()
void BufStr::shrink (uint newlen) inline
Definition at line 58 of file bufstr.h.
References m_writeOffset, and resize().
Referenced by readInputFile(), and transcodeCharacterBuffer().
size()
int BufStr::size () const inline
Definition at line 77 of file bufstr.h.
References m_size.
skip()
void BufStr::skip (uint s) inline
Definition at line 53 of file bufstr.h.
References m_writeOffset, and makeRoomFor().
Referenced by readInputFile().
Member Data Documentation
m_buf
char* BufStr::m_buf private
Definition at line 119 of file bufstr.h.
Referenced by addArray(), addChar(), at(), BufStr(), data(), dropFromStart(), operator const char *(), resize(), and ~BufStr().
m_size
uint BufStr::m_size private
Definition at line 116 of file bufstr.h.
Referenced by dropFromStart(), makeRoomFor(), resize(), and size().
m_spareRoom
const int BufStr::m_spareRoom private
Definition at line 118 of file bufstr.h.
Referenced by makeRoomFor(), and resize().
m_writeOffset
uint BufStr::m_writeOffset private
Definition at line 117 of file bufstr.h.
Referenced by addArray(), addChar(), curPos(), dropFromStart(), isEmpty(), makeRoomFor(), resize(), shrink(), and skip().
The documentation for this class was generated from the following file:
src/bufstr.h