Doxygen: DocRoot Class Reference
DocRoot Class Reference
Root node of documentation tree.
#include <docparser.h>
Public Member Functions
DocRoot (bool indent, bool sl)
Kind kind () const
void accept (DocVisitor *v)
void parse ()
bool indent () const
bool singleLine () const
bool isEmpty () const
Public Member Functions inherited from CompAccept< DocRoot >
CompAccept ()
virtual ~CompAccept ()
void accept (DocRoot *obj, DocVisitor *v)
const QList< DocNode > & children () const
QList< DocNode > & children ()
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Attributes
bool m_indent
bool m_singleLine
Additional Inherited Members
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from CompAccept< DocRoot >
QList< DocNode > m_children
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Root node of documentation tree.
Definition at line 1401 of file docparser.h.
Constructor & Destructor Documentation
DocRoot()
DocRoot::DocRoot (bool indent, bool sl) inline
Definition at line 1404 of file docparser.h.
Member Function Documentation
accept()
void DocRoot::accept (DocVisitor * v) inline virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 1406 of file docparser.h.
References CompAccept< T >::accept().
Referenced by parseDoc(), and validatingParseDoc().
indent()
bool DocRoot::indent () const inline
Definition at line 1408 of file docparser.h.
References m_indent.
Referenced by RTFDocVisitor::visitPost(), and RTFDocVisitor::visitPre().
isEmpty()
bool DocRoot::isEmpty () const inline
Definition at line 1410 of file docparser.h.
References CompAccept< DocRoot >::m_children.
Referenced by OutputList::generateDoc(), parseDoc(), DirDef::writeBriefDescription(), NamespaceDef::writeBriefDescription(), GroupDef::writeBriefDescription(), FileDef::writeBriefDescription(), MemberDef::writeDeclaration(), ClassDef::writeDeclarationLink(), and MemberList::writePlainDeclarations().
kind()
Kind DocRoot::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 1405 of file docparser.h.
References DocNode::Kind_Root.
parse()
void DocRoot::parse ()
Definition at line 6949 of file docparser.cpp.
References DBG, doctokenizerYYlineno, doctokenizerYYsetStatePara(), SDict< T >::find(), g_fileName, g_nodeStack, g_token, handleUnclosedStyleCommands(), DocPara::isEmpty(), CompAccept< DocRoot >::m_children, DocPara::markFirst(), DocPara::markLast(), DocSection::parse(), DocInternal::parse(), DocPara::parse(), RetVal_Internal, RetVal_Paragraph, RetVal_Section, RetVal_Subsection, RetVal_Subsubsection, Doxygen::sectionDict, TokenInfo::sectionId, Doxygen::subpageNestingLevel, TK_LISTITEM, and warn_doc_error().
Referenced by validatingParseDoc().
singleLine()
bool DocRoot::singleLine () const inline
Definition at line 1409 of file docparser.h.
References m_singleLine.
Referenced by RTFDocVisitor::visitPost().
Member Data Documentation
m_indent
bool DocRoot::m_indent private
Definition at line 1413 of file docparser.h.
Referenced by indent().
m_singleLine
bool DocRoot::m_singleLine private
Definition at line 1414 of file docparser.h.
Referenced by singleLine().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp