Doxygen: PropertyMapper< T > Class Template Reference
PropertyMapper< T > Class Template Reference
Helper class to map a property name to a handler member function.
Classes
struct PropertyFunc
struct PropertyFuncIntf
Public Member Functions
PropertyMapper ()
void addProperty (const char *name, typename PropertyFunc::Handler handle)
Add a property to the map.
TemplateVariant get (const T *obj, const char *name) const
Gets the value of a property.
Private Attributes
QDict< PropertyFuncIntf > m_map
Detailed Description
template<typename T>
class PropertyMapper< T >
Helper class to map a property name to a handler member function.
Definition at line 225 of file context.cpp.
Constructor & Destructor Documentation
PropertyMapper()
template<typename T> PropertyMapper< T >::PropertyMapper () inline
Definition at line 245 of file context.cpp.
Member Function Documentation
addProperty()
template<typename T> void PropertyMapper< T >::addProperty (const char * name, typename PropertyFunc::Handler handle) inline
Add a property to the map.
Parameters
[in] name The name of the property to add.
[in] obj The object handling access to the property.
[in] handle The method to call when the property is accessed.
Definition at line 252 of file context.cpp.
Referenced by DefinitionContext< FileContext::Private >::addBaseProperties(), DoxygenContext::Private::Private(), TranslateContext::Private::Private(), IncludeInfoContext::Private::Private(), ClassContext::Private::Private(), NamespaceContext::Private::Private(), FileContext::Private::Private(), DirContext::Private::Private(), PageContext::Private::Private(), MemberContext::Private::Private(), ModuleContext::Private::Private(), ClassIndexContext::Private::Private(), ClassHierarchyContext::Private::Private(), NestingNodeContext::Private::Private(), ClassTreeContext::Private::Private(), NamespaceTreeContext::Private::Private(), FileTreeContext::Private::Private(), PageTreeContext::Private::Private(), ModuleTreeContext::Private::Private(), NavPathElemContext::Private::Private(), ExampleTreeContext::Private::Private(), GlobalsIndexContext::Private::Private(), ClassMembersIndexContext::Private::Private(), NamespaceMembersIndexContext::Private::Private(), InheritanceGraphContext::Private::Private(), InheritanceNodeContext::Private::Private(), MemberInfoContext::Private::Private(), MemberGroupInfoContext::Private::Private(), MemberListInfoContext::Private::Private(), InheritedMemberInfoContext::Private::Private(), ArgumentContext::Private::Private(), SymbolContext::Private::Private(), SymbolGroupContext::Private::Private(), SymbolIndexContext::Private::Private(), and SearchIndexContext::Private::Private().
get()
template<typename T> TemplateVariant PropertyMapper< T >::get (const T * obj, const char * name) const inline
Gets the value of a property.
Parameters
[in] name The name of the property.
Returns
A variant representing the properties value or an invalid variant if it was not found.
Definition at line 269 of file context.cpp.
Referenced by DoxygenContext::Private::get(), TranslateContext::Private::get(), IncludeInfoContext::Private::get(), ClassContext::Private::get(), NamespaceContext::Private::get(), FileContext::Private::get(), DirContext::Private::get(), PageContext::Private::get(), MemberContext::Private::get(), ModuleContext::Private::get(), ClassIndexContext::Private::get(), ClassHierarchyContext::Private::get(), NestingNodeContext::Private::get(), ClassTreeContext::Private::get(), NamespaceTreeContext::Private::get(), FileTreeContext::Private::get(), PageTreeContext::Private::get(), ModuleTreeContext::Private::get(), NavPathElemContext::Private::get(), ExampleTreeContext::Private::get(), GlobalsIndexContext::Private::get(), ClassMembersIndexContext::Private::get(), NamespaceMembersIndexContext::Private::get(), InheritanceGraphContext::Private::get(), InheritanceNodeContext::Private::get(), MemberInfoContext::Private::get(), MemberGroupInfoContext::Private::get(), MemberListInfoContext::Private::get(), InheritedMemberInfoContext::Private::get(), ArgumentContext::Private::get(), SymbolContext::Private::get(), SymbolGroupContext::Private::get(), SymbolIndexContext::Private::get(), and SearchIndexContext::Private::get().
Member Data Documentation
m_map
template<typename T> QDict<PropertyFuncIntf> PropertyMapper< T >::m_map private
Definition at line 282 of file context.cpp.
Referenced by PropertyMapper< NestingNodeContext::Private >::addProperty(), PropertyMapper< NestingNodeContext::Private >::get(), and PropertyMapper< NestingNodeContext::Private >::PropertyMapper().
The documentation for this class was generated from the following file:
src/context.cpp