Doxygen: ClassInheritanceNodeContext Class Reference
ClassInheritanceNodeContext Class Reference
#include <context.h>
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
void addChildren (const BaseClassList *bcl, bool hideSuper)
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static ClassInheritanceNodeContext * alloc (ClassDef *cd)
Private Member Functions
ClassInheritanceNodeContext (ClassDef *)
~ClassInheritanceNodeContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 447 of file context.h.
Constructor & Destructor Documentation
ClassInheritanceNodeContext()
ClassInheritanceNodeContext::ClassInheritanceNodeContext (ClassDef *) private
Referenced by alloc().
~ClassInheritanceNodeContext()
ClassInheritanceNodeContext::~ClassInheritanceNodeContext () private
Member Function Documentation
addChildren()
void ClassInheritanceNodeContext::addChildren (const BaseClassList * bcl, bool hideSuper)
addRef()
virtual int ClassInheritanceNodeContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 455 of file context.h.
References RefCountedContext::addRef().
alloc()
static ClassInheritanceNodeContext* ClassInheritanceNodeContext::alloc (ClassDef * cd) inline static
Definition at line 450 of file context.h.
References ClassInheritanceNodeContext().
get()
virtual TemplateVariant ClassInheritanceNodeContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
release()
virtual int ClassInheritanceNodeContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 456 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ClassInheritanceNodeContext::p private
Definition at line 463 of file context.h.
The documentation for this class was generated from the following file:
src/context.h