Doxygen: Formula Class Reference
Formula Class Reference
Class representing a formula in the output.
#include <formula.h>
Public Member Functions
Formula (const char *text)
~Formula ()
int getId ()
QCString getFormulaText () const
Private Attributes
int number
QCString form
Detailed Description
Class representing a formula in the output.
Definition at line 25 of file formula.h.
Constructor & Destructor Documentation
Formula()
Formula::Formula (const char * text)
Definition at line 33 of file formula.cpp.
References form, and number.
~Formula()
Formula::~Formula ()
Definition at line 40 of file formula.cpp.
Member Function Documentation
getFormulaText()
QCString Formula::getFormulaText () const inline
Definition at line 31 of file formula.h.
References form.
Referenced by DocFormula::DocFormula(), and FormulaList::generateBitmaps().
getId()
int Formula::getId ()
Definition at line 44 of file formula.cpp.
References number.
Referenced by DocFormula::DocFormula(), and FormulaList::generateBitmaps().
Member Data Documentation
form
QCString Formula::form private
Definition at line 35 of file formula.h.
Referenced by Formula(), and getFormulaText().
number
int Formula::number private
Definition at line 34 of file formula.h.
Referenced by Formula(), and getId().
The documentation for this class was generated from the following files:
src/formula.h
src/formula.cpp