Doxygen: DotGroupCollaboration Class Reference
DotGroupCollaboration Class Reference
Representation of a group collaboration graph.
#include <dot.h>
Classes
class Edge
class Link
Public Types
enum EdgeType {
tmember = 0, tclass, tnamespace, tfile,
tpages, tdir, thierarchy
}
Public Member Functions
DotGroupCollaboration (GroupDef *gd)
~DotGroupCollaboration ()
QCString writeGraph (FTextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const char *path, const char *fileName, const char *relPath, bool writeImageMap=TRUE, int graphId=-1) const
void buildGraph (GroupDef *gd)
bool isTrivial () const
Static Public Member Functions
static void resetNumbering ()
Private Member Functions
void addCollaborationMember (Definition *def, QCString &url, EdgeType eType)
void addMemberList (class MemberList *ml)
void writeGraphHeader (FTextStream &t, const QCString &title) const
Edge * addEdge (DotNode *_pNStart, DotNode *_pNEnd, EdgeType _eType, const QCString &_label, const QCString &_url)
Private Attributes
DotNode * m_rootNode
QDict< DotNode > * m_usedNodes
QCString m_diskName
QList< Edge > m_edges
Static Private Attributes
static int m_curNodeNumber = 0
Detailed Description
Representation of a group collaboration graph.
Definition at line 278 of file dot.h.
Member Enumeration Documentation
EdgeType
enum DotGroupCollaboration::EdgeType
Enumerator
tmember
tclass
tnamespace
tfile
tpages
tdir
thierarchy
Definition at line 281 of file dot.h.
Constructor & Destructor Documentation
DotGroupCollaboration()
DotGroupCollaboration::DotGroupCollaboration (GroupDef * gd)
Definition at line 4258 of file dot.cpp.
References buildGraph(), GroupDef::getOutputFileBase(), Definition::getReference(), GroupDef::groupTitle(), m_curNodeNumber, m_diskName, m_edges, m_rootNode, m_usedNodes, DotNode::markAsVisible(), and Definition::name().
~DotGroupCollaboration()
DotGroupCollaboration::~DotGroupCollaboration ()
Definition at line 4272 of file dot.cpp.
References m_usedNodes.
Member Function Documentation
addCollaborationMember()
void DotGroupCollaboration::addCollaborationMember (Definition * def, QCString & url, EdgeType eType) private
Definition at line 4441 of file dot.cpp.
References addEdge(), m_curNodeNumber, m_rootNode, m_usedNodes, DotNode::markAsVisible(), Definition::partOfGroups(), and Definition::qualifiedName().
Referenced by addMemberList(), and buildGraph().
addEdge()
DotGroupCollaboration::Edge * DotGroupCollaboration::addEdge (DotNode * _pNStart, DotNode * _pNEnd, EdgeType _eType, const QCString & _label, const QCString & _url) private
Definition at line 4410 of file dot.cpp.
References DotGroupCollaboration::Edge::eType, DotGroupCollaboration::Edge::links, m_edges, DotGroupCollaboration::Edge::pNEnd, and DotGroupCollaboration::Edge::pNStart.
Referenced by addCollaborationMember(), and buildGraph().
addMemberList()
void DotGroupCollaboration::addMemberList (class MemberList * ml) private
Definition at line 4397 of file dot.cpp.
References addCollaborationMember(), MemberDef::anchor(), MemberList::count(), MemberDef::getOutputFileBase(), MemberDef::getReference(), Doxygen::htmlFileExtension, and tmember.
Referenced by buildGraph().
buildGraph()
void DotGroupCollaboration::buildGraph (GroupDef * gd)
Definition at line 4277 of file dot.cpp.
References addCollaborationMember(), addEdge(), addMemberList(), Definition::briefDescriptionAsTooltip(), SDict< T >::count(), GroupDef::getClasses(), GroupDef::getDirs(), GroupDef::getFiles(), GroupDef::getMemberList(), GroupDef::getNamespaces(), GroupDef::getOutputFileBase(), GroupDef::getPages(), ClassDef::getReference(), Definition::getReference(), GroupDef::getSubGroups(), GroupDef::groupTitle(), Doxygen::htmlFileExtension, SDict< PageDef >::Iterator, SDict< ClassDef >::Iterator, SDict< NamespaceDef >::Iterator, m_curNodeNumber, m_rootNode, m_usedNodes, DotNode::markAsVisible(), MemberListType_allMembersList, Definition::name(), Definition::partOfGroups(), tclass, tdir, tfile, thierarchy, tnamespace, and tpages.
Referenced by DotGroupCollaboration().
isTrivial()
bool DotGroupCollaboration::isTrivial () const
Definition at line 4690 of file dot.cpp.
References m_usedNodes.
Referenced by ModuleContext::Private::hasGroupGraph(), and GroupDef::writeGroupGraph().
resetNumbering()
void DotGroupCollaboration::resetNumbering () static
Definition at line 4253 of file dot.cpp.
References m_curNodeNumber.
Referenced by resetDotNodeNumbering().
writeGraph()
QCString DotGroupCollaboration::writeGraph (FTextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const char * path, const char * fileName, const char * relPath, bool writeImageMap = TRUE, int graphId = -1) const
Definition at line 4470 of file dot.cpp.
References DotManager::addFigure(), DotRunner::addJob(), DotManager::addMap(), DotManager::addRun(), DotManager::addSVGConversion(), DotManager::addSVGObject(), checkAndUpdateMd5Signature(), checkDeliverables(), DotNode::clearWriteFlag(), Config_getBool, Config_getEnum, endl(), EOF_DocBook, err(), escapeCharsInString(), getDotImageExtension(), GOF_BITMAP, GOF_EPS, DotNode::Inheritance, insertMapFile(), DotManager::instance(), DotNode::label(), m_diskName, m_edges, m_rootNode, m_usedNodes, MAP_CMD, removeDotGraph(), DotNode::write(), DotGroupCollaboration::Edge::write(), writeGraphFooter(), writeGraphHeader(), writeSVGFigureLink(), and writeVecGfxFigure().
Referenced by LatexGenerator::endGroupCollaboration(), HtmlGenerator::endGroupCollaboration(), and ModuleContext::Private::groupGraph().
writeGraphHeader()
void DotGroupCollaboration::writeGraphHeader (FTextStream & t, const QCString & title) const private
Definition at line 4695 of file dot.cpp.
References Config_getBool, convertToXML(), endl(), FONTNAME, and FONTSIZE.
Referenced by writeGraph().
Member Data Documentation
m_curNodeNumber
int DotGroupCollaboration::m_curNodeNumber = 0 static private
Definition at line 331 of file dot.h.
Referenced by addCollaborationMember(), buildGraph(), DotGroupCollaboration(), and resetNumbering().
m_diskName
QCString DotGroupCollaboration::m_diskName private
Definition at line 333 of file dot.h.
Referenced by DotGroupCollaboration(), and writeGraph().
m_edges
QList<Edge> DotGroupCollaboration::m_edges private
Definition at line 334 of file dot.h.
Referenced by addEdge(), DotGroupCollaboration(), and writeGraph().
m_rootNode
DotNode* DotGroupCollaboration::m_rootNode private
Definition at line 330 of file dot.h.
Referenced by addCollaborationMember(), buildGraph(), DotGroupCollaboration(), and writeGraph().
m_usedNodes
QDict<DotNode>* DotGroupCollaboration::m_usedNodes private
Definition at line 332 of file dot.h.
Referenced by addCollaborationMember(), buildGraph(), DotGroupCollaboration(), isTrivial(), writeGraph(), and ~DotGroupCollaboration().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp