Doxygen: InheritedMemberInfoContext::Private Class Reference
InheritedMemberInfoContext::Private Class Reference
Public Member Functions
Private (ClassDef *cd, MemberList *ml, const QCString &title)
TemplateVariant get (const char *n) const
virtual ~Private ()
TemplateVariant getClass () const
TemplateVariant title () const
TemplateVariant members () const
TemplateVariant id () const
TemplateVariant inheritedFrom () const
Private Attributes
ClassDef * m_class
MemberList * m_memberList
QCString m_title
SharedPtr< ClassContext > m_classCtx
SharedPtr< MemberListContext > m_memberListCtx
SharedPtr< TemplateList > m_inheritedFrom
Static Private Attributes
static PropertyMapper< InheritedMemberInfoContext::Private > s_inst
Detailed Description
Definition at line 9026 of file context.cpp.
Constructor & Destructor Documentation
Private()
InheritedMemberInfoContext::Private::Private (ClassDef * cd, MemberList * ml, const QCString & title) inline
Definition at line 9029 of file context.cpp.
References PropertyMapper< T >::addProperty(), getClass(), id(), inheritedFrom(), Config::init(), members(), s_inst, and title().
~Private()
virtual InheritedMemberInfoContext::Private::~Private () inline virtual
Definition at line 9047 of file context.cpp.
References m_memberList.
Member Function Documentation
get()
TemplateVariant InheritedMemberInfoContext::Private::get (const char * n) const inline
Definition at line 9043 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by InheritedMemberInfoContext::get().
getClass()
TemplateVariant InheritedMemberInfoContext::Private::getClass () const inline
Definition at line 9051 of file context.cpp.
References ClassContext::alloc(), SharedPtr< T >::get(), m_class, m_classCtx, and SharedPtr< T >::reset().
Referenced by inheritedFrom(), and Private().
id()
TemplateVariant InheritedMemberInfoContext::Private::id () const inline
Definition at line 9071 of file context.cpp.
References ClassDef::getOutputFileBase(), MemberList::listType(), MemberList::listTypeAsString(), m_class, m_memberList, stripPath(), and substitute().
Referenced by Private().
inheritedFrom()
TemplateVariant InheritedMemberInfoContext::Private::inheritedFrom () const inline
Definition at line 9076 of file context.cpp.
References TemplateList::alloc(), TemplateList::append(), SharedPtr< T >::get(), getClass(), m_inheritedFrom, SharedPtr< T >::reset(), and title().
Referenced by Private().
members()
TemplateVariant InheritedMemberInfoContext::Private::members () const inline
Definition at line 9063 of file context.cpp.
References MemberListContext::alloc(), SharedPtr< T >::get(), m_memberList, m_memberListCtx, and SharedPtr< T >::reset().
Referenced by Private().
title()
TemplateVariant InheritedMemberInfoContext::Private::title () const inline
Definition at line 9059 of file context.cpp.
References m_title.
Referenced by inheritedFrom(), and Private().
Member Data Documentation
m_class
ClassDef* InheritedMemberInfoContext::Private::m_class private
Definition at line 9088 of file context.cpp.
Referenced by getClass(), and id().
m_classCtx
SharedPtr<ClassContext> InheritedMemberInfoContext::Private::m_classCtx mutable private
Definition at line 9091 of file context.cpp.
Referenced by getClass().
m_inheritedFrom
SharedPtr<TemplateList> InheritedMemberInfoContext::Private::m_inheritedFrom mutable private
Definition at line 9093 of file context.cpp.
Referenced by inheritedFrom().
m_memberList
MemberList* InheritedMemberInfoContext::Private::m_memberList private
Definition at line 9089 of file context.cpp.
Referenced by id(), members(), and ~Private().
m_memberListCtx
SharedPtr<MemberListContext> InheritedMemberInfoContext::Private::m_memberListCtx mutable private
Definition at line 9092 of file context.cpp.
Referenced by members().
m_title
QCString InheritedMemberInfoContext::Private::m_title private
Definition at line 9090 of file context.cpp.
Referenced by title().
s_inst
PropertyMapper< InheritedMemberInfoContext::Private > InheritedMemberInfoContext::Private::s_inst static private
Definition at line 9094 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp