Doxygen: IndexIntf Class Reference
IndexIntf Class Reference abstract
Abstract interface for index generators.
#include <index.h>
Public Member Functions
virtual ~IndexIntf ()
virtual void initialize ()=0
virtual void finalize ()=0
virtual void incContentsDepth ()=0
virtual void decContentsDepth ()=0
virtual void addContentsItem (bool isDir, const char *name, const char *ref, const char *file, const char *anchor, bool separateIndex, bool addToNavIndex, Definition *def)=0
virtual void addIndexItem (Definition *context, MemberDef *md, const char *sectionAnchor, const char *title)=0
virtual void addIndexFile (const char *name)=0
virtual void addImageFile (const char *name)=0
virtual void addStyleSheetFile (const char *name)=0
Detailed Description
Abstract interface for index generators.
Definition at line 30 of file index.h.
Constructor & Destructor Documentation
~IndexIntf()
virtual IndexIntf::~IndexIntf () inline virtual
Definition at line 33 of file index.h.
Member Function Documentation
addContentsItem()
virtual void IndexIntf::addContentsItem (bool isDir, const char * name, const char * ref, const char * file, const char * anchor, bool separateIndex, bool addToNavIndex, Definition * def) pure virtual
Implemented in IndexList, HtmlHelp, EclipseHelp, FTVHelp, DocSets, and Qhp.
Referenced by IndexList::addContentsItem().
addImageFile()
virtual void IndexIntf::addImageFile (const char * name) pure virtual
Implemented in IndexList, HtmlHelp, EclipseHelp, FTVHelp, DocSets, and Qhp.
Referenced by IndexList::addImageFile().
addIndexFile()
virtual void IndexIntf::addIndexFile (const char * name) pure virtual
Implemented in IndexList, HtmlHelp, EclipseHelp, FTVHelp, DocSets, and Qhp.
Referenced by IndexList::addIndexFile().
addIndexItem()
virtual void IndexIntf::addIndexItem (Definition * context, MemberDef * md, const char * sectionAnchor, const char * title) pure virtual
Implemented in IndexList, HtmlHelp, EclipseHelp, FTVHelp, DocSets, and Qhp.
Referenced by IndexList::addIndexItem().
addStyleSheetFile()
virtual void IndexIntf::addStyleSheetFile (const char * name) pure virtual
Implemented in IndexList, HtmlHelp, EclipseHelp, FTVHelp, DocSets, and Qhp.
Referenced by IndexList::addStyleSheetFile().
decContentsDepth()
virtual void IndexIntf::decContentsDepth () pure virtual
Implemented in IndexList, HtmlHelp, EclipseHelp, FTVHelp, DocSets, and Qhp.
Referenced by IndexList::decContentsDepth().
finalize()
virtual void IndexIntf::finalize () pure virtual
Implemented in IndexList, HtmlHelp, EclipseHelp, FTVHelp, DocSets, and Qhp.
Referenced by IndexList::finalize().
incContentsDepth()
virtual void IndexIntf::incContentsDepth () pure virtual
Implemented in IndexList, HtmlHelp, EclipseHelp, FTVHelp, DocSets, and Qhp.
Referenced by IndexList::incContentsDepth().
initialize()
virtual void IndexIntf::initialize () pure virtual
Implemented in IndexList, HtmlHelp, EclipseHelp, FTVHelp, DocSets, and Qhp.
Referenced by IndexList::initialize().
The documentation for this class was generated from the following file:
src/index.h