Doxygen: DirEntry Class Reference
DirEntry Class Reference
Class representing an entry (file or sub directory) in a directory.
#include <filedef.h>
Public Types
enum EntryKind { Dir, File }
Public Member Functions
DirEntry (DirEntry *parent, FileDef *fd)
DirEntry (DirEntry *parent, QCString name)
virtual ~DirEntry ()
EntryKind kind () const
FileDef * file () const
bool isLast () const
void setLast (bool b)
DirEntry * parent () const
QCString name () const
QCString path () const
Protected Attributes
DirEntry * m_parent
QCString m_name
Private Attributes
EntryKind m_kind
FileDef * m_fd
bool m_isLast
Detailed Description
Class representing an entry (file or sub directory) in a directory.
Definition at line 277 of file filedef.h.
Member Enumeration Documentation
EntryKind
enum DirEntry::EntryKind
Enumerator
Dir
File
Definition at line 280 of file filedef.h.
Constructor & Destructor Documentation
DirEntry() [1/2]
DirEntry::DirEntry (DirEntry * parent, FileDef * fd) inline
Definition at line 281 of file filedef.h.
DirEntry() [2/2]
DirEntry::DirEntry (DirEntry * parent, QCString name) inline
Definition at line 284 of file filedef.h.
~DirEntry()
virtual DirEntry::~DirEntry () inline virtual
Definition at line 287 of file filedef.h.
Member Function Documentation
file()
FileDef* DirEntry::file () const inline
Definition at line 289 of file filedef.h.
References m_fd.
isLast()
bool DirEntry::isLast () const inline
Definition at line 290 of file filedef.h.
References m_isLast.
kind()
EntryKind DirEntry::kind () const inline
Definition at line 288 of file filedef.h.
References m_kind.
Referenced by addDirsAsGroups().
name()
QCString DirEntry::name () const inline
Definition at line 293 of file filedef.h.
References m_name.
Referenced by addDirsAsGroups(), findDirNode(), path(), and Directory::rename().
parent()
DirEntry* DirEntry::parent () const inline
Definition at line 292 of file filedef.h.
References m_parent.
Referenced by path(), and Directory::reParent().
path()
QCString DirEntry::path () const inline
Definition at line 294 of file filedef.h.
References name(), parent(), and path().
Referenced by addDirsAsGroups(), and path().
setLast()
void DirEntry::setLast (bool b) inline
Definition at line 291 of file filedef.h.
References m_isLast.
Referenced by Directory::addChild(), findDirNode(), and generateFileTree().
Member Data Documentation
m_fd
FileDef* DirEntry::m_fd private
Definition at line 302 of file filedef.h.
Referenced by file().
m_isLast
bool DirEntry::m_isLast private
Definition at line 303 of file filedef.h.
Referenced by isLast(), and setLast().
m_kind
EntryKind DirEntry::m_kind private
Definition at line 301 of file filedef.h.
Referenced by kind().
m_name
QCString DirEntry::m_name protected
Definition at line 298 of file filedef.h.
Referenced by name(), and Directory::rename().
m_parent
DirEntry* DirEntry::m_parent protected
Definition at line 297 of file filedef.h.
Referenced by parent(), and Directory::reParent().
The documentation for this class was generated from the following file:
src/filedef.h