Doxygen: DocParamList Class Reference
DocParamList Class Reference
Node representing a parameter list.
#include <docparser.h>
Public Member Functions
DocParamList (DocNode *parent, DocParamSect::Type t, DocParamSect::Direction d)
virtual ~DocParamList ()
Kind kind () const
const QList< DocNode > & parameters ()
const QList< DocNode > & paramTypes ()
DocParamSect::Type type () const
DocParamSect::Direction direction () const
void markFirst (bool b=TRUE)
void markLast (bool b=TRUE)
bool isFirst () const
bool isLast () const
void accept (DocVisitor *v)
int parse (const QCString &cmdName)
int parseXml (const QCString &paramName)
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Attributes
QList< DocPara > m_paragraphs
QList< DocNode > m_params
QList< DocNode > m_paramTypes
DocParamSect::Type m_type
DocParamSect::Direction m_dir
bool m_isFirst
bool m_isLast
Additional Inherited Members
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Node representing a parameter list.
Definition at line 1158 of file docparser.h.
Constructor & Destructor Documentation
DocParamList()
DocParamList::DocParamList (DocNode * parent, DocParamSect::Type t, DocParamSect::Direction d) inline
Definition at line 1161 of file docparser.h.
References m_paragraphs, m_params, m_paramTypes, DocNode::m_parent, and DocNode::parent().
~DocParamList()
virtual DocParamList::~DocParamList () inline virtual
Definition at line 1168 of file docparser.h.
Member Function Documentation
accept()
void DocParamList::accept (DocVisitor * v) inline virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 1178 of file docparser.h.
References DocNode::accept(), m_paragraphs, DocVisitor::visitPost(), and DocVisitor::visitPre().
direction()
DocParamSect::Direction DocParamList::direction () const inline
Definition at line 1173 of file docparser.h.
References m_dir.
Referenced by RTFDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), XmlDocVisitor::visitPre(), and PerlModDocVisitor::visitPre().
isFirst()
bool DocParamList::isFirst () const inline
Definition at line 1176 of file docparser.h.
References m_isFirst.
isLast()
bool DocParamList::isLast () const inline
Definition at line 1177 of file docparser.h.
References m_isLast.
Referenced by ManDocVisitor::visitPost().
kind()
Kind DocParamList::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 1169 of file docparser.h.
References DocNode::Kind_ParamList.
markFirst()
void DocParamList::markFirst (bool b = TRUE) inline
Definition at line 1174 of file docparser.h.
References m_isFirst.
Referenced by DocParamSect::parse().
markLast()
void DocParamList::markLast (bool b = TRUE) inline
Definition at line 1175 of file docparser.h.
References m_isLast.
Referenced by DocParamSect::parse().
parameters()
const QList<DocNode>& DocParamList::parameters () inline
Definition at line 1170 of file docparser.h.
References m_params.
Referenced by DocbookDocVisitor::visitPre(), RTFDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), ManDocVisitor::visitPre(), LatexDocVisitor::visitPre(), XmlDocVisitor::visitPre(), PerlModDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
paramTypes()
const QList<DocNode>& DocParamList::paramTypes () inline
Definition at line 1171 of file docparser.h.
References m_paramTypes.
Referenced by RTFDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and XmlDocVisitor::visitPre().
parse()
int DocParamList::parse (const QCString & cmdName)
Definition at line 4666 of file docparser.cpp.
References checkArgumentName(), DBG, doctokenizerYYlex(), doctokenizerYYlineno, doctokenizerYYsetStatePara(), doctokenizerYYsetStateParam(), g_fileName, g_hasParamCommand, g_hasReturnCommand, g_nodeStack, g_token, handleLinkedWord(), handleParameterType(), m_paragraphs, m_params, m_paramTypes, m_type, DocPara::markFirst(), DocPara::markLast(), TokenInfo::name, DocParamSect::Param, DocNode::parent(), DocPara::parse(), DocParamSect::RetVal, RetVal_OK, TK_WHITESPACE, TK_WORD, and warn_doc_error().
Referenced by DocParamSect::parse().
parseXml()
int DocParamList::parseXml (const QCString & paramName)
Definition at line 4741 of file docparser.cpp.
References checkArgumentName(), DBG, doctokenizerYYlineno, g_fileName, g_hasParamCommand, g_hasReturnCommand, g_nodeStack, g_token, handleLinkedWord(), Mappers::htmlTagMapper, DocPara::isEmpty(), m_paragraphs, m_params, m_type, Mapper::map(), DocPara::markFirst(), DocPara::markLast(), TokenInfo::name, DocParamSect::Param, DocPara::parse(), DocParamSect::RetVal, RetVal_CloseXml, RetVal_OK, warn_doc_error(), XML_EXCEPTION, XML_PARAM, and XML_TYPEPARAM.
Referenced by DocParamSect::parse().
type()
DocParamSect::Type DocParamList::type () const inline
Definition at line 1172 of file docparser.h.
References m_type.
Member Data Documentation
m_dir
DocParamSect::Direction DocParamList::m_dir private
Definition at line 1194 of file docparser.h.
Referenced by direction().
m_isFirst
bool DocParamList::m_isFirst private
Definition at line 1195 of file docparser.h.
Referenced by isFirst(), and markFirst().
m_isLast
bool DocParamList::m_isLast private
Definition at line 1196 of file docparser.h.
Referenced by isLast(), and markLast().
m_paragraphs
QList<DocPara> DocParamList::m_paragraphs private
Definition at line 1190 of file docparser.h.
Referenced by accept(), DocParamList(), parse(), and parseXml().
m_params
QList<DocNode> DocParamList::m_params private
Definition at line 1191 of file docparser.h.
Referenced by DocParamList(), parameters(), parse(), and parseXml().
m_paramTypes
QList<DocNode> DocParamList::m_paramTypes private
Definition at line 1192 of file docparser.h.
Referenced by DocParamList(), paramTypes(), and parse().
m_type
DocParamSect::Type DocParamList::m_type private
Definition at line 1193 of file docparser.h.
Referenced by parse(), parseXml(), and type().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp