Doxygen: src/memberdef.h File Reference
memberdef.h File Reference
#include <qlist.h>
#include <sys/types.h>
#include "types.h"
#include "definition.h"
Classes
class MemberDef
A model of a class/file/namespace member symbol.
Functions
void combineDeclarationAndDefinition (MemberDef *mdec, MemberDef *mdef)
Function Documentation
combineDeclarationAndDefinition()
void combineDeclarationAndDefinition (MemberDef * mdec, MemberDef * mdef)
Definition at line 4975 of file memberdef.cpp.
References MemberDef::argsString(), MemberDef::argumentList(), MemberDef::briefDescription(), Definition::briefFile(), Definition::briefLine(), Definition::docFile(), Definition::docLine(), MemberDef::documentation(), MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), Definition::getBodyDef(), Definition::getEndBodyLine(), MemberDef::getFileDef(), MemberDef::getGroupDef(), MemberDef::getGroupPri(), MemberDef::getMemberSpecifiers(), Definition::getOuterScope(), Definition::getStartBodyLine(), MemberDef::hasCallerGraph(), MemberDef::hasCallGraph(), MemberDef::hasDocumentation(), Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), MemberDef::isDocsForDefinition(), MemberDef::isExternal(), MemberDef::isFunction(), MemberDef::isPrototype(), MemberDef::isStatic(), MemberDef::isVariable(), matchArguments2(), MemberDef::mergeMemberSpecifiers(), Definition::mergeRefItems(), MemberDef::setArgumentList(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDeclArgumentList(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setGroupDef(), MemberDef::setInbodyDocumentation(), MemberDef::setMemberDeclaration(), MemberDef::setMemberDefinition(), stringToArgumentList(), and transferArgumentDocumentation().
Referenced by ClassDef::mergeCategory(), and transferFunctionDocumentation().