Doxygen: Statistics Class Reference
Statistics Class Reference
Classes
struct stat
Public Member Functions
Statistics ()
void begin (const char *name)
void end ()
void print ()
Private Attributes
QList< stat > stats
QTime time
Detailed Description
Definition at line 213 of file doxygen.cpp.
Constructor & Destructor Documentation
Statistics()
Statistics::Statistics () inline
Definition at line 216 of file doxygen.cpp.
References stats.
Member Function Documentation
begin()
void Statistics::begin (const char * name) inline
Definition at line 217 of file doxygen.cpp.
References msg(), stats, and time.
Referenced by generateOutput(), parseInput(), and searchInputFiles().
end()
void Statistics::end () inline
Definition at line 224 of file doxygen.cpp.
References stats, and time.
Referenced by generateOutput(), parseInput(), and searchInputFiles().
print()
void Statistics::print () inline
Definition at line 228 of file doxygen.cpp.
References Debug::clearFlag(), Statistics::stat::elapsed, Debug::isFlagSet(), msg(), Statistics::stat::name, Debug::setFlag(), stats, and Debug::Time.
Referenced by generateOutput().
Member Data Documentation
stats
QList<stat> Statistics::stats private
Definition at line 253 of file doxygen.cpp.
Referenced by begin(), end(), print(), and Statistics().
time
QTime Statistics::time private
Definition at line 254 of file doxygen.cpp.
Referenced by begin(), and end().
The documentation for this class was generated from the following file:
src/doxygen.cpp