Doxygen: DotDirDeps Class Reference
DotDirDeps Class Reference
Representation of an directory dependency graph.
#include <dot.h>
Public Member Functions
DotDirDeps (DirDef *dir)
~DotDirDeps ()
bool isTrivial () const
QCString writeGraph (FTextStream &out, GraphOutputFormat gf, EmbeddedOutputFormat ef, const char *path, const char *fileName, const char *relPath, bool writeImageMap=TRUE, int graphId=-1, bool linkRelations=TRUE) const
Private Attributes
DirDef * m_dir
Detailed Description
Representation of an directory dependency graph.
Definition at line 258 of file dot.h.
Constructor & Destructor Documentation
DotDirDeps()
DotDirDeps::DotDirDeps (DirDef * dir)
Definition at line 3914 of file dot.cpp.
~DotDirDeps()
DotDirDeps::~DotDirDeps ()
Definition at line 3918 of file dot.cpp.
Member Function Documentation
isTrivial()
bool DotDirDeps::isTrivial () const
Definition at line 4065 of file dot.cpp.
References DirDef::depGraphIsTrivial(), and m_dir.
Referenced by DirContext::Private::hasDirGraph(), and DirDef::writeDirectoryGraph().
writeGraph()
QCString DotDirDeps::writeGraph (FTextStream & out, GraphOutputFormat gf, EmbeddedOutputFormat ef, const char * path, const char * fileName, const char * relPath, bool writeImageMap = TRUE, int graphId = -1, bool linkRelations = TRUE) const
Definition at line 3922 of file dot.cpp.
References DotManager::addFigure(), IndexList::addImageFile(), DotRunner::addJob(), DotManager::addMap(), DotManager::addRun(), DotManager::addSVGConversion(), DotManager::addSVGObject(), checkAndUpdateMd5Signature(), checkDeliverables(), Config_getBool, Config_getEnum, convertToXML(), DirDef::displayName(), endl(), EOF_DocBook, err(), escapeCharsInString(), getDotImageExtension(), DirDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, Doxygen::indexList, insertMapFile(), DotManager::instance(), m_dir, MAP_CMD, removeDotGraph(), writeDotDirDepGraph(), writeSVGFigureLink(), and writeVecGfxFigure().
Referenced by DirContext::Private::dirGraph(), RTFGenerator::endDirDepGraph(), LatexGenerator::endDirDepGraph(), and HtmlGenerator::endDirDepGraph().
Member Data Documentation
m_dir
DirDef* DotDirDeps::m_dir private
Definition at line 274 of file dot.h.
Referenced by isTrivial(), and writeGraph().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp