Doxygen: DocHtmlHeader Class Reference
DocHtmlHeader Class Reference
Node Html heading.
#include <docparser.h>
Public Member Functions
DocHtmlHeader (DocNode *parent, const HtmlAttribList &attribs, int level)
int level () const
Kind kind () const
const HtmlAttribList & attribs () const
void accept (DocVisitor *v)
int parse ()
Public Member Functions inherited from CompAccept< DocHtmlHeader >
CompAccept ()
virtual ~CompAccept ()
void accept (DocHtmlHeader *obj, DocVisitor *v)
const QList< DocNode > & children () const
QList< DocNode > & children ()
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Attributes
int m_level
HtmlAttribList m_attribs
Additional Inherited Members
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from CompAccept< DocHtmlHeader >
QList< DocNode > m_children
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Node Html heading.
Definition at line 890 of file docparser.h.
Constructor & Destructor Documentation
DocHtmlHeader()
DocHtmlHeader::DocHtmlHeader (DocNode * parent, const HtmlAttribList & attribs, int level) inline
Definition at line 893 of file docparser.h.
References DocNode::m_parent, and DocNode::parent().
Member Function Documentation
accept()
void DocHtmlHeader::accept (DocVisitor * v) inline virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 898 of file docparser.h.
References CompAccept< T >::accept().
attribs()
const HtmlAttribList& DocHtmlHeader::attribs () const inline
Definition at line 897 of file docparser.h.
References m_attribs.
Referenced by HtmlDocVisitor::visitPre().
kind()
Kind DocHtmlHeader::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 896 of file docparser.h.
References DocNode::Kind_HtmlHeader.
level()
int DocHtmlHeader::level () const inline
Definition at line 895 of file docparser.h.
References m_level.
Referenced by ManDocVisitor::visitPost(), HtmlDocVisitor::visitPost(), PrintDocVisitor::visitPost(), RTFDocVisitor::visitPre(), ManDocVisitor::visitPre(), XmlDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
parse()
int DocHtmlHeader::parse ()
Definition at line 2951 of file docparser.cpp.
References TokenInfo::attribs, DBG, defaultHandleToken(), doctokenizerYYlex(), doctokenizerYYlineno, TokenInfo::endTag, g_fileName, g_nodeStack, g_token, handleAHref(), handlePendingStyleCommands(), HTML_A, HTML_BR, HTML_H1, HTML_H2, HTML_H3, HTML_H4, HTML_H5, HTML_H6, Mappers::htmlTagMapper, CompAccept< DocHtmlHeader >::m_children, m_level, Mapper::map(), TokenInfo::name, RetVal_OK, TK_COMMAND, TK_HTMLTAG, TK_SYMBOL, tokToString(), and warn_doc_error().
Referenced by DocPara::handleHtmlHeader().
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlHeader::m_attribs private
Definition at line 903 of file docparser.h.
Referenced by attribs().
m_level
int DocHtmlHeader::m_level private
Definition at line 902 of file docparser.h.
Referenced by level(), and parse().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp