Doxygen: DoxygenContext::Private Class Reference
DoxygenContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
TemplateVariant version () const
TemplateVariant date () const
TemplateVariant maxJaxCodeFile () const
Private ()
TemplateVariant get (const char *n) const
Private Attributes
Cachable m_cache
Static Private Attributes
static PropertyMapper< DoxygenContext::Private > s_inst
Detailed Description
Definition at line 372 of file context.cpp.
Constructor & Destructor Documentation
Private()
DoxygenContext::Private::Private () inline
Definition at line 387 of file context.cpp.
References PropertyMapper< T >::addProperty(), date(), Config::init(), maxJaxCodeFile(), s_inst, and version().
Member Function Documentation
date()
TemplateVariant DoxygenContext::Private::date () const inline
Definition at line 379 of file context.cpp.
References dateToString().
Referenced by Private().
get()
TemplateVariant DoxygenContext::Private::get (const char * n) const inline
Definition at line 401 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by DoxygenContext::get().
maxJaxCodeFile()
TemplateVariant DoxygenContext::Private::maxJaxCodeFile () const inline
Definition at line 383 of file context.cpp.
References m_cache, and DoxygenContext::Private::Cachable::maxJaxCodeFile.
Referenced by Private().
version()
TemplateVariant DoxygenContext::Private::version () const inline
Definition at line 375 of file context.cpp.
References versionString.
Referenced by Private().
Member Data Documentation
m_cache
Cachable DoxygenContext::Private::m_cache mutable private
Definition at line 411 of file context.cpp.
Referenced by maxJaxCodeFile().
s_inst
PropertyMapper< DoxygenContext::Private > DoxygenContext::Private::s_inst static private
Definition at line 412 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp