Doxygen: LatexDocVisitor Class Reference
LatexDocVisitor Class Reference
Concrete visitor implementation for LaTeX output.
#include <latexdocvisitor.h>
Classes
struct ActiveRowSpan
struct TableState
Public Member Functions
LatexDocVisitor (FTextStream &t, CodeOutputInterface &ci, const char *langExt, bool insideTabbing)
void visit (DocWord *)
void visit (DocLinkedWord *)
void visit (DocWhiteSpace *)
void visit (DocSymbol *)
void visit (DocURL *)
void visit (DocLineBreak *)
void visit (DocHorRuler *)
void visit (DocStyleChange *)
void visit (DocVerbatim *)
void visit (DocAnchor *)
void visit (DocInclude *)
void visit (DocIncOperator *)
void visit (DocFormula *)
void visit (DocIndexEntry *)
void visit (DocSimpleSectSep *)
void visit (DocCite *)
void visitPre (DocAutoList *)
void visitPost (DocAutoList *)
void visitPre (DocAutoListItem *)
void visitPost (DocAutoListItem *)
void visitPre (DocPara *)
void visitPost (DocPara *)
void visitPre (DocRoot *)
void visitPost (DocRoot *)
void visitPre (DocSimpleSect *)
void visitPost (DocSimpleSect *)
void visitPre (DocTitle *)
void visitPost (DocTitle *)
void visitPre (DocSimpleList *)
void visitPost (DocSimpleList *)
void visitPre (DocSimpleListItem *)
void visitPost (DocSimpleListItem *)
void visitPre (DocSection *s)
void visitPost (DocSection *)
void visitPre (DocHtmlList *s)
void visitPost (DocHtmlList *s)
void visitPre (DocHtmlListItem *)
void visitPost (DocHtmlListItem *)
void visitPre (DocHtmlDescList *)
void visitPost (DocHtmlDescList *)
void visitPre (DocHtmlDescTitle *)
void visitPost (DocHtmlDescTitle *)
void visitPre (DocHtmlDescData *)
void visitPost (DocHtmlDescData *)
void visitPre (DocHtmlTable *t)
void visitPost (DocHtmlTable *t)
void visitPre (DocHtmlCaption *)
void visitPost (DocHtmlCaption *)
void visitPre (DocHtmlRow *)
void visitPost (DocHtmlRow *)
void visitPre (DocHtmlCell *)
void visitPost (DocHtmlCell *)
void visitPre (DocInternal *)
void visitPost (DocInternal *)
void visitPre (DocHRef *)
void visitPost (DocHRef *)
void visitPre (DocHtmlHeader *)
void visitPost (DocHtmlHeader *)
void visitPre (DocImage *)
void visitPost (DocImage *)
void visitPre (DocDotFile *)
void visitPost (DocDotFile *)
void visitPre (DocMscFile *)
void visitPost (DocMscFile *)
void visitPre (DocDiaFile *)
void visitPost (DocDiaFile *)
void visitPre (DocLink *lnk)
void visitPost (DocLink *)
void visitPre (DocRef *ref)
void visitPost (DocRef *)
void visitPre (DocSecRefItem *)
void visitPost (DocSecRefItem *)
void visitPre (DocSecRefList *)
void visitPost (DocSecRefList *)
void visitPre (DocParamSect *)
void visitPost (DocParamSect *)
void visitPre (DocParamList *)
void visitPost (DocParamList *)
void visitPre (DocXRefItem *)
void visitPost (DocXRefItem *)
void visitPre (DocInternalRef *)
void visitPost (DocInternalRef *)
void visitPre (DocCopy *)
void visitPost (DocCopy *)
void visitPre (DocText *)
void visitPost (DocText *)
void visitPre (DocHtmlBlockQuote *)
void visitPost (DocHtmlBlockQuote *)
void visitPre (DocVhdlFlow *)
void visitPost (DocVhdlFlow *)
void visitPre (DocParBlock *)
void visitPost (DocParBlock *)
Public Member Functions inherited from DocVisitor
DocVisitor (int id)
virtual ~DocVisitor ()
int id () const
Private Types
typedef QList< ActiveRowSpan > RowSpanList
Private Member Functions
void filter (const char *str)
void startLink (const QCString &ref, const QCString &file, const QCString &anchor, bool refToTable=FALSE)
void endLink (const QCString &ref, const QCString &file, const QCString &anchor)
QCString escapeMakeIndexChars (const char *s)
void startDotFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption)
void endDotFile (bool hasCaption)
void startMscFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption)
void endMscFile (bool hasCaption)
void writeMscFile (const QCString &fileName, DocVerbatim *s)
void startDiaFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption)
void endDiaFile (bool hasCaption)
void writeDiaFile (const QCString &fileName, DocVerbatim *s)
void writePlantUMLFile (const QCString &fileName, DocVerbatim *s)
void pushEnabled ()
void popEnabled ()
void pushTableState ()
void popTableState ()
int currentColumn () const
void setCurrentColumn (int col)
int numCols () const
void setNumCols (int num)
bool inRowSpan () const
void setInRowSpan (bool b)
bool inColSpan () const
void setInColSpan (bool b)
bool firstRow () const
void setFirstRow (bool b)
const RowSpanList & rowSpans ()
void addRowSpan (ActiveRowSpan *span)
bool insideTable () const
Private Attributes
FTextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre
bool m_insideItem
bool m_hide
bool m_hideCaption
bool m_insideTabbing
QStack< bool > m_enabled
QCString m_langExt
QStack< TableState > m_tableStateStack
RowSpanList m_emptyRowSpanList
Detailed Description
Concrete visitor implementation for LaTeX output.
Definition at line 32 of file latexdocvisitor.h.
Member Typedef Documentation
RowSpanList
typedef QList<ActiveRowSpan> LatexDocVisitor::RowSpanList private
Definition at line 154 of file latexdocvisitor.h.
Constructor & Destructor Documentation
LatexDocVisitor()
LatexDocVisitor::LatexDocVisitor (FTextStream & t, CodeOutputInterface & ci, const char * langExt, bool insideTabbing)
Definition at line 147 of file latexdocvisitor.cpp.
References m_tableStateStack.
Member Function Documentation
addRowSpan()
void LatexDocVisitor::addRowSpan (ActiveRowSpan * span) inline private
Definition at line 265 of file latexdocvisitor.h.
Referenced by visitPre().
currentColumn()
int LatexDocVisitor::currentColumn () const inline private
Definition at line 221 of file latexdocvisitor.h.
Referenced by visitPost(), and visitPre().
endDiaFile()
void LatexDocVisitor::endDiaFile (bool hasCaption) private
Definition at line 1806 of file latexdocvisitor.cpp.
References m_hide, m_t, and visitPostEnd().
Referenced by visitPost().
endDotFile()
void LatexDocVisitor::endDotFile (bool hasCaption) private
Definition at line 1731 of file latexdocvisitor.cpp.
References m_hide, m_t, and visitPostEnd().
Referenced by visit(), and visitPost().
endLink()
void LatexDocVisitor::endLink (const QCString & ref, const QCString & file, const QCString & anchor) private
Definition at line 1681 of file latexdocvisitor.cpp.
References Config_getBool, filter(), m_t, theTranslator, and Translator::trPageAbbreviation().
Referenced by visit(), and visitPost().
endMscFile()
void LatexDocVisitor::endMscFile (bool hasCaption) private
Definition at line 1760 of file latexdocvisitor.cpp.
References m_hide, m_t, and visitPostEnd().
Referenced by visitPost().
escapeMakeIndexChars()
QCString LatexDocVisitor::escapeMakeIndexChars (const char * s) private
Definition at line 119 of file latexdocvisitor.cpp.
References filter(), and m_t.
filter()
void LatexDocVisitor::filter (const char * str) private
Definition at line 1644 of file latexdocvisitor.cpp.
References filterLatexString(), m_insideItem, m_insidePre, m_insideTabbing, and m_t.
Referenced by endLink(), escapeMakeIndexChars(), visit(), and visitPre().
firstRow()
bool LatexDocVisitor::firstRow () const inline private
Definition at line 253 of file latexdocvisitor.h.
Referenced by visitPost(), and visitPre().
inColSpan()
bool LatexDocVisitor::inColSpan () const inline private
Definition at line 245 of file latexdocvisitor.h.
Referenced by visitPost().
inRowSpan()
bool LatexDocVisitor::inRowSpan () const inline private
Definition at line 237 of file latexdocvisitor.h.
Referenced by visitPost().
insideTable()
bool LatexDocVisitor::insideTable () const inline private
Definition at line 269 of file latexdocvisitor.h.
numCols()
int LatexDocVisitor::numCols () const inline private
Definition at line 229 of file latexdocvisitor.h.
Referenced by visitPost(), and visitPre().
popEnabled()
void LatexDocVisitor::popEnabled () private
Definition at line 1700 of file latexdocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit(), and visitPost().
popTableState()
void LatexDocVisitor::popTableState () inline private
Definition at line 217 of file latexdocvisitor.h.
Referenced by visitPost().
pushEnabled()
void LatexDocVisitor::pushEnabled () private
Definition at line 1695 of file latexdocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit(), and visitPre().
pushTableState()
void LatexDocVisitor::pushTableState () inline private
Definition at line 213 of file latexdocvisitor.h.
Referenced by visitPre().
rowSpans()
const RowSpanList& LatexDocVisitor::rowSpans () inline private
Definition at line 261 of file latexdocvisitor.h.
References m_emptyRowSpanList.
Referenced by visitPost(), and visitPre().
setCurrentColumn()
void LatexDocVisitor::setCurrentColumn (int col) inline private
Definition at line 225 of file latexdocvisitor.h.
Referenced by visitPre().
setFirstRow()
void LatexDocVisitor::setFirstRow (bool b) inline private
Definition at line 257 of file latexdocvisitor.h.
Referenced by visitPre().
setInColSpan()
void LatexDocVisitor::setInColSpan (bool b) inline private
Definition at line 249 of file latexdocvisitor.h.
Referenced by visitPost(), and visitPre().
setInRowSpan()
void LatexDocVisitor::setInRowSpan (bool b) inline private
Definition at line 241 of file latexdocvisitor.h.
Referenced by visitPost(), and visitPre().
setNumCols()
void LatexDocVisitor::setNumCols (int num) inline private
Definition at line 233 of file latexdocvisitor.h.
Referenced by visitPre().
startDiaFile()
void LatexDocVisitor::startDiaFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption) private
Definition at line 1783 of file latexdocvisitor.cpp.
References Config_getString, DIA_EPS, m_t, visitPreStart(), and writeDiaGraphFromFile().
Referenced by visitPre().
startDotFile()
void LatexDocVisitor::startDotFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption) private
Definition at line 1708 of file latexdocvisitor.cpp.
References Config_getString, GOF_EPS, m_t, visitPreStart(), and writeDotGraphFromFile().
Referenced by visit(), and visitPre().
startLink()
void LatexDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & anchor, bool refToTable = FALSE) private
Definition at line 1649 of file latexdocvisitor.cpp.
References Config_getBool, m_t, and stripPath().
Referenced by visit(), and visitPre().
startMscFile()
void LatexDocVisitor::startMscFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption) private
Definition at line 1737 of file latexdocvisitor.cpp.
References Config_getString, m_t, MSC_EPS, visitPreStart(), and writeMscGraphFromFile().
Referenced by visitPre().
visit() [1/16]
void LatexDocVisitor::visit (DocWord * w) virtual
Implements DocVisitor.
Definition at line 160 of file latexdocvisitor.cpp.
References filter(), m_hide, and DocWord::word().
Referenced by visitPre().
visit() [2/16]
void LatexDocVisitor::visit (DocLinkedWord * w) virtual
Implements DocVisitor.
Definition at line 166 of file latexdocvisitor.cpp.
References DocLinkedWord::anchor(), endLink(), DocLinkedWord::file(), filter(), m_hide, DocLinkedWord::ref(), startLink(), and DocLinkedWord::word().
visit() [3/16]
void LatexDocVisitor::visit (DocWhiteSpace * w) virtual
Implements DocVisitor.
Definition at line 174 of file latexdocvisitor.cpp.
References DocWhiteSpace::chars(), m_hide, m_insidePre, and m_t.
visit() [4/16]
void LatexDocVisitor::visit (DocSymbol * s) virtual
Implements DocVisitor.
Definition at line 187 of file latexdocvisitor.cpp.
References err(), HtmlEntityMapper::instance(), HtmlEntityMapper::latex(), m_hide, m_insidePre, m_t, DocSymbol::Sym_Greater, DocSymbol::Sym_gt, DocSymbol::Sym_Less, DocSymbol::Sym_lt, and DocSymbol::symbol().
visit() [5/16]
void LatexDocVisitor::visit (DocURL * u) virtual
Implements DocVisitor.
Definition at line 212 of file latexdocvisitor.cpp.
References Config_getBool, filter(), DocURL::isEmail(), m_hide, m_t, and DocURL::url().
visit() [6/16]
void LatexDocVisitor::visit (DocLineBreak *) virtual
Implements DocVisitor.
Definition at line 226 of file latexdocvisitor.cpp.
References m_hide, and m_t.
visit() [7/16]
void LatexDocVisitor::visit (DocHorRuler *) virtual
Implements DocVisitor.
Definition at line 232 of file latexdocvisitor.cpp.
References m_hide, and m_t.
visit() [8/16]
void LatexDocVisitor::visit (DocStyleChange * s) virtual
Implements DocVisitor.
Definition at line 238 of file latexdocvisitor.cpp.
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Code, DocStyleChange::Div, DocStyleChange::enable(), DocStyleChange::Italic, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::style(), DocStyleChange::Subscript, and DocStyleChange::Superscript.
visit() [9/16]
void LatexDocVisitor::visit (DocVerbatim * s) virtual
Implements DocVisitor.
Definition at line 281 of file latexdocvisitor.cpp.
References DocVerbatim::children(), DocVerbatim::Code, Config_getBool, Config_getString, DocVerbatim::context(), DocVerbatim::DocbookOnly, DocVerbatim::Dot, endDotFile(), err(), DocVerbatim::exampleFile(), getLanguageFromFileName(), ParserManager::getParser(), DocVerbatim::hasCaption(), DocVerbatim::height(), DocVerbatim::HtmlOnly, DocVerbatim::isExample(), DocVerbatim::language(), DocVerbatim::LatexOnly, m_ci, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, ParserInterface::parseCode(), Doxygen::parserManager, DocVerbatim::PlantUML, DocVerbatim::RtfOnly, startDotFile(), DocVerbatim::text(), DocVerbatim::type(), DocVerbatim::Verbatim, visitCaption(), DocVerbatim::width(), writeMscFile(), writePlantUMLFile(), writePlantUMLSource(), and DocVerbatim::XmlOnly.
visit() [10/16]
void LatexDocVisitor::visit (DocAnchor * anc) virtual
Implements DocVisitor.
Definition at line 383 of file latexdocvisitor.cpp.
References DocAnchor::anchor(), Config_getBool, endl(), DocAnchor::file(), m_hide, m_t, and stripPath().
visit() [11/16]
void LatexDocVisitor::visit (DocInclude * inc) virtual
Implements DocVisitor.
Definition at line 394 of file latexdocvisitor.cpp.
References DocInclude::blockId(), DocInclude::context(), DocInclude::DontInclude, endl(), err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), DocInclude::file(), getLanguageFromFileName(), ParserManager::getParser(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_hide, m_t, parseCode(), Doxygen::parserManager, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::text(), DocInclude::type(), and DocInclude::VerbInclude.
visit() [12/16]
void LatexDocVisitor::visit (DocIncOperator * op) virtual
Implements DocVisitor.
Definition at line 492 of file latexdocvisitor.cpp.
References DocIncOperator::context(), endl(), DocIncOperator::exampleFile(), getLanguageFromFileName(), ParserManager::getParser(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), m_ci, m_hide, m_langExt, m_t, ParserInterface::parseCode(), Doxygen::parserManager, popEnabled(), pushEnabled(), DocIncOperator::Skip, DocIncOperator::text(), and DocIncOperator::type().
visit() [13/16]
void LatexDocVisitor::visit (DocFormula * f) virtual
Implements DocVisitor.
Definition at line 526 of file latexdocvisitor.cpp.
References m_hide, m_t, and DocFormula::text().
visit() [14/16]
void LatexDocVisitor::visit (DocIndexEntry * i) virtual
Implements DocVisitor.
Definition at line 532 of file latexdocvisitor.cpp.
References DocIndexEntry::entry(), latexEscapeIndexChars(), latexEscapeLabelName(), m_hide, and m_t.
visit() [15/16]
void LatexDocVisitor::visit (DocSimpleSectSep *) virtual
Implements DocVisitor.
Definition at line 542 of file latexdocvisitor.cpp.
visit() [16/16]
void LatexDocVisitor::visit (DocCite * cite) virtual
Implements DocVisitor.
Definition at line 546 of file latexdocvisitor.cpp.
References DocCite::anchor(), CiteConsts::anchorPrefix, DocCite::file(), filter(), m_hide, m_t, and DocCite::text().
visitPost() [1/38]
void LatexDocVisitor::visitPost (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 581 of file latexdocvisitor.cpp.
References DocAutoList::isEnumList(), m_hide, and m_t.
visitPost() [2/38]
void LatexDocVisitor::visitPost (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 600 of file latexdocvisitor.cpp.
visitPost() [3/38]
void LatexDocVisitor::visitPost (DocPara * p) virtual
Implements DocVisitor.
Definition at line 608 of file latexdocvisitor.cpp.
References endl(), DocPara::isLast(), DocNode::kind(), DocNode::Kind_ParamSect, m_hide, m_t, and DocNode::parent().
visitPost() [4/38]
void LatexDocVisitor::visitPost (DocRoot *) virtual
Implements DocVisitor.
Definition at line 622 of file latexdocvisitor.cpp.
visitPost() [5/38]
void LatexDocVisitor::visitPost (DocSimpleSect * s) virtual
Implements DocVisitor.
Definition at line 711 of file latexdocvisitor.cpp.
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, DocSimpleSect::Invar, m_hide, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, DocSimpleSect::See, DocSimpleSect::Since, DocSimpleSect::type(), DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
visitPost() [6/38]
void LatexDocVisitor::visitPost (DocTitle *) virtual
Implements DocVisitor.
Definition at line 776 of file latexdocvisitor.cpp.
References m_hide, m_insideItem, and m_t.
visitPost() [7/38]
void LatexDocVisitor::visitPost (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 789 of file latexdocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [8/38]
void LatexDocVisitor::visitPost (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 801 of file latexdocvisitor.cpp.
visitPost() [9/38]
void LatexDocVisitor::visitPost (DocSection *) virtual
Implements DocVisitor.
Definition at line 817 of file latexdocvisitor.cpp.
visitPost() [10/38]
void LatexDocVisitor::visitPost (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 830 of file latexdocvisitor.cpp.
References m_hide, m_t, DocHtmlList::Ordered, and DocHtmlList::type().
visitPost() [11/38]
void LatexDocVisitor::visitPost (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 845 of file latexdocvisitor.cpp.
visitPost() [12/38]
void LatexDocVisitor::visitPost (DocHtmlDescList * dl) virtual
Implements DocVisitor.
Definition at line 875 of file latexdocvisitor.cpp.
References DocHtmlDescList::attribs(), HtmlAttribList::find(), m_hide, and m_t.
visitPost() [13/38]
void LatexDocVisitor::visitPost (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 896 of file latexdocvisitor.cpp.
References m_hide, m_insideItem, and m_t.
visitPost() [14/38]
void LatexDocVisitor::visitPost (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 907 of file latexdocvisitor.cpp.
visitPost() [15/38]
void LatexDocVisitor::visitPost (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 991 of file latexdocvisitor.cpp.
References m_hide, m_t, DocNode::parent(), popTableState(), and writeEndTableCommand().
visitPost() [16/38]
void LatexDocVisitor::visitPost (DocHtmlCaption * c) virtual
Implements DocVisitor.
Definition at line 1004 of file latexdocvisitor.cpp.
References m_hide, and m_hideCaption.
visitPost() [17/38]
void LatexDocVisitor::visitPost (DocHtmlRow * row) virtual
Implements DocVisitor.
Definition at line 1015 of file latexdocvisitor.cpp.
References LatexDocVisitor::ActiveRowSpan::cell, LatexDocVisitor::ActiveRowSpan::colSpan, LatexDocVisitor::ActiveRowSpan::column, currentColumn(), endl(), firstRow(), DocHtmlRow::isHeading(), m_hide, m_t, numCols(), DocHtmlCell::rowIndex(), DocHtmlRow::rowIndex(), LatexDocVisitor::ActiveRowSpan::rowSpan, rowSpans(), and DocHtmlRow::visibleCells().
visitPost() [18/38]
void LatexDocVisitor::visitPost (DocHtmlCell * c) virtual
Implements DocVisitor.
Definition at line 1180 of file latexdocvisitor.cpp.
References inColSpan(), inRowSpan(), DocHtmlCell::isHeading(), DocHtmlCell::isLast(), m_hide, m_t, setInColSpan(), and setInRowSpan().
visitPost() [19/38]
void LatexDocVisitor::visitPost (DocInternal *) virtual
Implements DocVisitor.
Definition at line 1208 of file latexdocvisitor.cpp.
References m_hide.
visitPost() [20/38]
void LatexDocVisitor::visitPost (DocHRef *) virtual
Implements DocVisitor.
Definition at line 1226 of file latexdocvisitor.cpp.
References m_hide, and m_t.
visitPost() [21/38]
void LatexDocVisitor::visitPost (DocHtmlHeader *) virtual
Implements DocVisitor.
Definition at line 1238 of file latexdocvisitor.cpp.
References m_hide, and m_t.
visitPost() [22/38]
void LatexDocVisitor::visitPost (DocImage * img) virtual
Implements DocVisitor.
Definition at line 1263 of file latexdocvisitor.cpp.
References DocImage::hasCaption(), DocImage::Latex, m_hide, m_t, popEnabled(), DocImage::type(), and visitPostEnd().
visitPost() [23/38]
void LatexDocVisitor::visitPost (DocDotFile * df) virtual
Implements DocVisitor.
Definition at line 1282 of file latexdocvisitor.cpp.
References endDotFile(), DocDotFile::hasCaption(), and m_hide.
visitPost() [24/38]
void LatexDocVisitor::visitPost (DocMscFile * df) virtual
Implements DocVisitor.
Definition at line 1293 of file latexdocvisitor.cpp.
References endMscFile(), DocMscFile::hasCaption(), and m_hide.
visitPost() [25/38]
void LatexDocVisitor::visitPost (DocDiaFile * df) virtual
Implements DocVisitor.
Definition at line 1305 of file latexdocvisitor.cpp.
References endDiaFile(), DocDiaFile::hasCaption(), and m_hide.
visitPost() [26/38]
void LatexDocVisitor::visitPost (DocLink * lnk) virtual
Implements DocVisitor.
Definition at line 1316 of file latexdocvisitor.cpp.
References DocLink::anchor(), endLink(), DocLink::file(), m_hide, and DocLink::ref().
visitPost() [27/38]
void LatexDocVisitor::visitPost (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 1338 of file latexdocvisitor.cpp.
References DocRef::anchor(), endLink(), DocRef::file(), DocRef::isSubPage(), m_hide, and DocRef::ref().
visitPost() [28/38]
void LatexDocVisitor::visitPost (DocSecRefItem * ref) virtual
Implements DocVisitor.
Definition at line 1362 of file latexdocvisitor.cpp.
References DocSecRefItem::anchor(), Config_getBool, endl(), DocSecRefItem::file(), m_hide, and m_t.
visitPost() [29/38]
void LatexDocVisitor::visitPost (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 1381 of file latexdocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [30/38]
void LatexDocVisitor::visitPost (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 1424 of file latexdocvisitor.cpp.
References DocParamSect::Exception, m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, and DocParamSect::type().
visitPost() [31/38]
void LatexDocVisitor::visitPost (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 1535 of file latexdocvisitor.cpp.
References endl(), DocParamSect::Exception, DocNode::kind(), DocNode::Kind_ParamSect, m_hide, m_t, DocParamSect::Param, DocNode::parent(), DocParamSect::RetVal, DocParamSect::TemplateParam, and DocParamSect::Unknown.
visitPost() [32/38]
void LatexDocVisitor::visitPost (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1577 of file latexdocvisitor.cpp.
References endl(), m_hide, m_t, and DocXRefItem::title().
visitPost() [33/38]
void LatexDocVisitor::visitPost (DocInternalRef * ref) virtual
Implements DocVisitor.
Definition at line 1590 of file latexdocvisitor.cpp.
References DocInternalRef::anchor(), endLink(), DocInternalRef::file(), and m_hide.
visitPost() [34/38]
void LatexDocVisitor::visitPost (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1600 of file latexdocvisitor.cpp.
visitPost() [35/38]
void LatexDocVisitor::visitPost (DocText *) virtual
Implements DocVisitor.
Definition at line 1608 of file latexdocvisitor.cpp.
visitPost() [36/38]
void LatexDocVisitor::visitPost (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1618 of file latexdocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [37/38]
void LatexDocVisitor::visitPost (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1629 of file latexdocvisitor.cpp.
References m_hide.
visitPost() [38/38]
void LatexDocVisitor::visitPost (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1639 of file latexdocvisitor.cpp.
References m_hide.
visitPre() [1/38]
void LatexDocVisitor::visitPre (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 568 of file latexdocvisitor.cpp.
References DocAutoList::isEnumList(), m_hide, and m_t.
visitPre() [2/38]
void LatexDocVisitor::visitPre (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 594 of file latexdocvisitor.cpp.
References m_hide, and m_t.
visitPre() [3/38]
void LatexDocVisitor::visitPre (DocPara *) virtual
Implements DocVisitor.
Definition at line 604 of file latexdocvisitor.cpp.
visitPre() [4/38]
void LatexDocVisitor::visitPre (DocRoot *) virtual
Implements DocVisitor.
Definition at line 618 of file latexdocvisitor.cpp.
visitPre() [5/38]
void LatexDocVisitor::visitPre (DocSimpleSect * s) virtual
Implements DocVisitor.
Definition at line 626 of file latexdocvisitor.cpp.
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, filter(), DocSimpleSect::Invar, m_hide, m_insideItem, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), Translator::trVersion(), Translator::trWarning(), DocSimpleSect::type(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
visitPre() [6/38]
void LatexDocVisitor::visitPre (DocTitle *) virtual
Implements DocVisitor.
Definition at line 772 of file latexdocvisitor.cpp.
visitPre() [7/38]
void LatexDocVisitor::visitPre (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 783 of file latexdocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPre() [8/38]
void LatexDocVisitor::visitPre (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 795 of file latexdocvisitor.cpp.
References m_hide, and m_t.
visitPre() [9/38]
void LatexDocVisitor::visitPre (DocSection * s) virtual
Implements DocVisitor.
Definition at line 805 of file latexdocvisitor.cpp.
References DocSection::anchor(), Config_getBool, convertCharEntitiesToUTF8(), endl(), DocSection::file(), filter(), getSectionName(), DocSection::level(), m_hide, m_t, stripPath(), and DocSection::title().
visitPre() [10/38]
void LatexDocVisitor::visitPre (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 821 of file latexdocvisitor.cpp.
References m_hide, m_t, DocHtmlList::Ordered, and DocHtmlList::type().
visitPre() [11/38]
void LatexDocVisitor::visitPre (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 839 of file latexdocvisitor.cpp.
References m_hide, and m_t.
visitPre() [12/38]
void LatexDocVisitor::visitPre (DocHtmlDescList * dl) virtual
Implements DocVisitor.
Definition at line 861 of file latexdocvisitor.cpp.
References DocHtmlDescList::attribs(), HtmlAttribList::find(), m_hide, and m_t.
visitPre() [13/38]
void LatexDocVisitor::visitPre (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 889 of file latexdocvisitor.cpp.
References m_hide, m_insideItem, and m_t.
visitPre() [14/38]
void LatexDocVisitor::visitPre (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 903 of file latexdocvisitor.cpp.
visitPre() [15/38]
void LatexDocVisitor::visitPre (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 948 of file latexdocvisitor.cpp.
References DocHtmlRow::accept(), DocHtmlCaption::anchor(), DocHtmlTable::caption(), CompAccept< T >::children(), Config_getBool, endl(), DocHtmlCaption::file(), firstRow(), DocHtmlTable::firstRow(), DocHtmlTable::hasCaption(), DocHtmlRow::isHeading(), m_hide, m_t, DocHtmlTable::numColumns(), DocNode::parent(), pushTableState(), setFirstRow(), setNumCols(), stripPath(), visitCaption(), and writeStartTableCommand().
visitPre() [16/38]
void LatexDocVisitor::visitPre (DocHtmlCaption * c) virtual
Implements DocVisitor.
Definition at line 998 of file latexdocvisitor.cpp.
References m_hide, and m_hideCaption.
visitPre() [17/38]
void LatexDocVisitor::visitPre (DocHtmlRow * r) virtual
Implements DocVisitor.
Definition at line 1009 of file latexdocvisitor.cpp.
References DocHtmlRow::isHeading(), m_t, and setCurrentColumn().
visitPre() [18/38]
void LatexDocVisitor::visitPre (DocHtmlCell * c) virtual
Implements DocVisitor.
Definition at line 1096 of file latexdocvisitor.cpp.
References addRowSpan(), DocHtmlCell::alignment(), DocHtmlCell::Center, LatexDocVisitor::ActiveRowSpan::colSpan, DocHtmlCell::colSpan(), LatexDocVisitor::ActiveRowSpan::column, DocHtmlCell::columnIndex(), currentColumn(), DocHtmlCell::isHeading(), DocNode::kind(), DocNode::Kind_HtmlRow, m_hide, m_t, numCols(), DocNode::parent(), DocHtmlCell::Right, LatexDocVisitor::ActiveRowSpan::rowSpan, DocHtmlCell::rowSpan(), rowSpans(), setCurrentColumn(), setInColSpan(), setInRowSpan(), and DocHtmlRow::visibleCells().
visitPre() [19/38]
void LatexDocVisitor::visitPre (DocInternal *) virtual
Implements DocVisitor.
Definition at line 1200 of file latexdocvisitor.cpp.
References m_hide.
visitPre() [20/38]
void LatexDocVisitor::visitPre (DocHRef * href) virtual
Implements DocVisitor.
Definition at line 1214 of file latexdocvisitor.cpp.
References Config_getBool, m_hide, m_t, and DocHRef::url().
visitPre() [21/38]
void LatexDocVisitor::visitPre (DocHtmlHeader * header) virtual
Implements DocVisitor.
Definition at line 1232 of file latexdocvisitor.cpp.
References getSectionName(), DocHtmlHeader::level(), m_hide, and m_t.
visitPre() [22/38]
void LatexDocVisitor::visitPre (DocImage * img) virtual
Implements DocVisitor.
Definition at line 1243 of file latexdocvisitor.cpp.
References DocImage::hasCaption(), DocImage::height(), DocImage::Latex, m_hide, m_t, DocImage::name(), pushEnabled(), DocImage::type(), visitPreStart(), and DocImage::width().
visitPre() [23/38]
void LatexDocVisitor::visitPre (DocDotFile * df) virtual
Implements DocVisitor.
Definition at line 1276 of file latexdocvisitor.cpp.
References DocDotFile::file(), DocDotFile::hasCaption(), DocDotFile::height(), m_hide, startDotFile(), and DocDotFile::width().
visitPre() [24/38]
void LatexDocVisitor::visitPre (DocMscFile * df) virtual
Implements DocVisitor.
Definition at line 1287 of file latexdocvisitor.cpp.
References DocMscFile::file(), DocMscFile::hasCaption(), DocMscFile::height(), m_hide, startMscFile(), and DocMscFile::width().
visitPre() [25/38]
void LatexDocVisitor::visitPre (DocDiaFile * df) virtual
Implements DocVisitor.
Definition at line 1299 of file latexdocvisitor.cpp.
References DocDiaFile::file(), DocDiaFile::hasCaption(), DocDiaFile::height(), m_hide, startDiaFile(), and DocDiaFile::width().
visitPre() [26/38]
void LatexDocVisitor::visitPre (DocLink * lnk) virtual
Implements DocVisitor.
Definition at line 1310 of file latexdocvisitor.cpp.
References DocLink::anchor(), DocLink::file(), m_hide, DocLink::ref(), and startLink().
visitPre() [27/38]
void LatexDocVisitor::visitPre (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 1322 of file latexdocvisitor.cpp.
References DocRef::anchor(), DocRef::file(), filter(), DocRef::hasLinkText(), DocRef::isSubPage(), m_hide, DocRef::ref(), DocRef::refToTable(), startLink(), and DocRef::targetTitle().
visitPre() [28/38]
void LatexDocVisitor::visitPre (DocSecRefItem * ref) virtual
Implements DocVisitor.
Definition at line 1351 of file latexdocvisitor.cpp.
References DocSecRefItem::anchor(), Config_getBool, DocSecRefItem::file(), m_hide, and m_t.
visitPre() [29/38]
void LatexDocVisitor::visitPre (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 1373 of file latexdocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPre() [30/38]
void LatexDocVisitor::visitPre (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 1389 of file latexdocvisitor.cpp.
References DocParamSect::Exception, filter(), DocParamSect::hasInOutSpecifier(), DocParamSect::hasTypeSpecifier(), m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), and DocParamSect::type().
visitPre() [31/38]
void LatexDocVisitor::visitPre (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 1446 of file latexdocvisitor.cpp.
References DocParamList::direction(), DocParamSect::Exception, DocParamSect::hasInOutSpecifier(), DocParamSect::hasTypeSpecifier(), DocParamSect::In, DocParamSect::InOut, DocNode::kind(), DocNode::Kind_LinkedWord, DocNode::Kind_ParamSect, DocNode::Kind_Word, m_hide, m_insideItem, m_t, DocParamSect::Out, DocParamSect::Param, DocParamList::parameters(), DocParamList::paramTypes(), DocNode::parent(), DocParamSect::RetVal, DocParamSect::TemplateParam, DocParamSect::Unknown, DocParamSect::Unspecified, and visit().
visitPre() [32/38]
void LatexDocVisitor::visitPre (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1554 of file latexdocvisitor.cpp.
References DocXRefItem::anchor(), Config_getBool, endl(), DocXRefItem::file(), filter(), m_hide, m_insideItem, m_t, stripPath(), and DocXRefItem::title().
visitPre() [33/38]
void LatexDocVisitor::visitPre (DocInternalRef * ref) virtual
Implements DocVisitor.
Definition at line 1584 of file latexdocvisitor.cpp.
References DocInternalRef::anchor(), DocInternalRef::file(), m_hide, and startLink().
visitPre() [34/38]
void LatexDocVisitor::visitPre (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1596 of file latexdocvisitor.cpp.
visitPre() [35/38]
void LatexDocVisitor::visitPre (DocText *) virtual
Implements DocVisitor.
Definition at line 1604 of file latexdocvisitor.cpp.
visitPre() [36/38]
void LatexDocVisitor::visitPre (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1612 of file latexdocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPre() [37/38]
void LatexDocVisitor::visitPre (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1624 of file latexdocvisitor.cpp.
References m_hide.
visitPre() [38/38]
void LatexDocVisitor::visitPre (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1634 of file latexdocvisitor.cpp.
References m_hide.
writeDiaFile()
void LatexDocVisitor::writeDiaFile (const QCString & fileName, DocVerbatim * s) private
Definition at line 1813 of file latexdocvisitor.cpp.
References DocVerbatim::children(), Config_getString, DIA_EPS, DocVerbatim::hasCaption(), DocVerbatim::height(), m_t, visitCaption(), visitPostEnd(), visitPreStart(), DocVerbatim::width(), and writeDiaGraphFromFile().
writeMscFile()
void LatexDocVisitor::writeMscFile (const QCString & fileName, DocVerbatim * s) private
Definition at line 1767 of file latexdocvisitor.cpp.
References DocVerbatim::children(), Config_getString, DocVerbatim::hasCaption(), DocVerbatim::height(), m_t, MSC_EPS, visitCaption(), visitPostEnd(), visitPreStart(), DocVerbatim::width(), and writeMscGraphFromFile().
Referenced by visit().
writePlantUMLFile()
void LatexDocVisitor::writePlantUMLFile (const QCString & fileName, DocVerbatim * s) private
Definition at line 1828 of file latexdocvisitor.cpp.
References DocVerbatim::children(), Config_getString, generatePlantUMLOutput(), DocVerbatim::hasCaption(), DocVerbatim::height(), m_t, PUML_EPS, visitCaption(), visitPostEnd(), visitPreStart(), and DocVerbatim::width().
Referenced by visit().
Member Data Documentation
m_ci
CodeOutputInterface& LatexDocVisitor::m_ci private
Definition at line 189 of file latexdocvisitor.h.
Referenced by visit().
m_emptyRowSpanList
RowSpanList LatexDocVisitor::m_emptyRowSpanList private
Definition at line 211 of file latexdocvisitor.h.
Referenced by rowSpans().
m_enabled
QStack<bool> LatexDocVisitor::m_enabled private
Definition at line 195 of file latexdocvisitor.h.
Referenced by popEnabled(), and pushEnabled().
m_hide
bool LatexDocVisitor::m_hide private
Definition at line 192 of file latexdocvisitor.h.
Referenced by endDiaFile(), endDotFile(), endMscFile(), popEnabled(), pushEnabled(), visit(), visitPost(), and visitPre().
m_hideCaption
bool LatexDocVisitor::m_hideCaption private
Definition at line 193 of file latexdocvisitor.h.
Referenced by visitPost(), and visitPre().
m_insideItem
bool LatexDocVisitor::m_insideItem private
Definition at line 191 of file latexdocvisitor.h.
Referenced by filter(), visitPost(), and visitPre().
m_insidePre
bool LatexDocVisitor::m_insidePre private
Definition at line 190 of file latexdocvisitor.h.
Referenced by filter(), and visit().
m_insideTabbing
bool LatexDocVisitor::m_insideTabbing private
Definition at line 194 of file latexdocvisitor.h.
Referenced by filter().
m_langExt
QCString LatexDocVisitor::m_langExt private
Definition at line 196 of file latexdocvisitor.h.
Referenced by visit().
m_t
FTextStream& LatexDocVisitor::m_t private
Definition at line 188 of file latexdocvisitor.h.
Referenced by endDiaFile(), endDotFile(), endLink(), endMscFile(), escapeMakeIndexChars(), filter(), startDiaFile(), startDotFile(), startLink(), startMscFile(), visit(), visitPost(), visitPre(), writeDiaFile(), writeMscFile(), and writePlantUMLFile().
m_tableStateStack
QStack<TableState> LatexDocVisitor::m_tableStateStack private
Definition at line 210 of file latexdocvisitor.h.
Referenced by LatexDocVisitor().
The documentation for this class was generated from the following files:
src/latexdocvisitor.h
src/latexdocvisitor.cpp