Doxygen: LatexCodeGenerator Class Reference
LatexCodeGenerator Class Reference
#include <latexgen.h>
Public Member Functions
LatexCodeGenerator (FTextStream &t, const QCString &relPath, const QCString &sourceFile)
LatexCodeGenerator ()
void setTextStream (FTextStream &t)
void setRelativePath (const QCString &path)
void setSourceFileName (const QCString &sourceFileName)
void codify (const char *text)
void writeCodeLink (const char *ref, const char *file, const char *anchor, const char *name, const char *tooltip)
void writeTooltip (const char *, const DocLinkInfo &, const char *, const char *, const SourceLinkInfo &, const SourceLinkInfo &)
void writeLineNumber (const char *, const char *, const char *, int)
void startCodeLine (bool)
void endCodeLine ()
void startFontClass (const char *)
void endFontClass ()
void writeCodeAnchor (const char *)
void setCurrentDoc (Definition *, const char *, bool)
void addWord (const char *, bool)
Public Member Functions inherited from CodeOutputInterface
virtual ~CodeOutputInterface ()
Private Member Functions
void _writeCodeLink (const char *className, const char *ref, const char *file, const char *anchor, const char *name, const char *tooltip)
void docify (const char *str)
Private Attributes
bool m_streamSet
FTextStream m_t
QCString m_relPath
QCString m_sourceFileName
int m_col
bool m_prettyCode
Detailed Description
Definition at line 27 of file latexgen.h.
Constructor & Destructor Documentation
LatexCodeGenerator() [1/2]
LatexCodeGenerator::LatexCodeGenerator (FTextStream & t, const QCString & relPath, const QCString & sourceFile)
Definition at line 43 of file latexgen.cpp.
References Config_getBool, m_prettyCode, and setTextStream().
LatexCodeGenerator() [2/2]
LatexCodeGenerator::LatexCodeGenerator ()
Definition at line 50 of file latexgen.cpp.
References Config_getBool, and m_prettyCode.
Member Function Documentation
_writeCodeLink()
void LatexCodeGenerator::_writeCodeLink (const char * className, const char * ref, const char * file, const char * anchor, const char * name, const char * tooltip) private
addWord()
void LatexCodeGenerator::addWord (const char * , bool) inline virtual
Implements CodeOutputInterface.
Definition at line 53 of file latexgen.h.
codify()
void LatexCodeGenerator::codify (const char * s) virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 71 of file latexgen.cpp.
References Config_getInt, COPYCHAR, filterLatexString(), m_col, m_t, and Doxygen::spaces.
Referenced by LatexGenerator::codify(), endCodeLine(), writeCodeLink(), and writeLineNumber().
docify()
void LatexCodeGenerator::docify (const char * str) private
endCodeLine()
void LatexCodeGenerator::endCodeLine () virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 228 of file latexgen.cpp.
References codify().
Referenced by LatexGenerator::endCodeLine().
endFontClass()
void LatexCodeGenerator::endFontClass () virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 238 of file latexgen.cpp.
References m_t.
Referenced by LatexGenerator::endFontClass().
setCurrentDoc()
void LatexCodeGenerator::setCurrentDoc (Definition * , const char * , bool) inline virtual
Implements CodeOutputInterface.
Definition at line 52 of file latexgen.h.
setRelativePath()
void LatexCodeGenerator::setRelativePath (const QCString & path)
Definition at line 61 of file latexgen.cpp.
References m_relPath.
Referenced by LatexGenerator::startFile().
setSourceFileName()
void LatexCodeGenerator::setSourceFileName (const QCString & sourceFileName)
Definition at line 66 of file latexgen.cpp.
References m_sourceFileName.
Referenced by LatexGenerator::endFile(), and LatexGenerator::startFile().
setTextStream()
void LatexCodeGenerator::setTextStream (FTextStream & t)
Definition at line 55 of file latexgen.cpp.
References FTextStream::device(), m_streamSet, m_t, and FTextStream::setDevice().
Referenced by LatexCodeGenerator(), and LatexGenerator::startFile().
startCodeLine()
void LatexCodeGenerator::startCodeLine (bool) virtual
Implements CodeOutputInterface.
Definition at line 223 of file latexgen.cpp.
References m_col.
Referenced by LatexGenerator::startCodeLine().
startFontClass()
void LatexCodeGenerator::startFontClass (const char * clsName) virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 233 of file latexgen.cpp.
References m_t.
Referenced by LatexGenerator::startFontClass().
writeCodeAnchor()
void LatexCodeGenerator::writeCodeAnchor (const char * name) inline virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 51 of file latexgen.h.
Referenced by LatexGenerator::writeCodeAnchor().
writeCodeLink()
void LatexCodeGenerator::writeCodeLink (const char * ref, const char * file, const char * anchor, const char * name, const char * tooltip) virtual
Writes a link to an object in a code fragment.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 160 of file latexgen.cpp.
References codify(), Config_getBool, m_col, m_t, and stripPath().
Referenced by LatexGenerator::writeCodeLink(), and writeLineNumber().
writeLineNumber()
void LatexCodeGenerator::writeLineNumber (const char * ref, const char * file, const char * anchor, int lineNumber) virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
Implements CodeOutputInterface.
Definition at line 189 of file latexgen.cpp.
References codify(), Config_getBool, m_prettyCode, m_sourceFileName, m_t, stripExtensionGeneral(), stripPath(), and writeCodeLink().
Referenced by LatexGenerator::writeLineNumber().
writeTooltip()
void LatexCodeGenerator::writeTooltip (const char * id, const DocLinkInfo & docInfo, const char * decl, const char * desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) inline virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 39 of file latexgen.h.
Referenced by LatexGenerator::writeTooltip().
Member Data Documentation
m_col
int LatexCodeGenerator::m_col private
Definition at line 65 of file latexgen.h.
Referenced by codify(), startCodeLine(), and writeCodeLink().
m_prettyCode
bool LatexCodeGenerator::m_prettyCode private
Definition at line 66 of file latexgen.h.
Referenced by LatexCodeGenerator(), and writeLineNumber().
m_relPath
QCString LatexCodeGenerator::m_relPath private
Definition at line 63 of file latexgen.h.
Referenced by setRelativePath().
m_sourceFileName
QCString LatexCodeGenerator::m_sourceFileName private
Definition at line 64 of file latexgen.h.
Referenced by setSourceFileName(), and writeLineNumber().
m_streamSet
bool LatexCodeGenerator::m_streamSet private
Definition at line 61 of file latexgen.h.
Referenced by setTextStream().
m_t
FTextStream LatexCodeGenerator::m_t private
Definition at line 62 of file latexgen.h.
Referenced by codify(), endFontClass(), setTextStream(), startFontClass(), writeCodeLink(), and writeLineNumber().
The documentation for this class was generated from the following files:
src/latexgen.h
src/latexgen.cpp