Doxygen: ParserManager Class Reference
ParserManager Class Reference
Manages programming language parsers.
#include <parserintf.h>
Public Member Functions
ParserManager ()
Creates the parser manager object.
~ParserManager ()
void registerDefaultParser (ParserInterface *parser)
void registerParser (const char *name, ParserInterface *parser)
Registers an additional parser.
bool registerExtension (const char *extension, const char *parserName)
Registers a file extension with a parser with name parserName.
ParserInterface * getParser (const char *extension)
Gets the interface to the parser associated with given extension.
Private Attributes
QDict< ParserInterface > m_parsers
QDict< ParserInterface > m_extensions
ParserInterface * m_defaultParser
Detailed Description
Manages programming language parsers.
This class manages the language parsers in the system. One can register parsers, and obtain a parser given a file extension.
Definition at line 143 of file parserintf.h.
Constructor & Destructor Documentation
ParserManager()
ParserManager::ParserManager () inline
Creates the parser manager object.
Definition at line 148 of file parserintf.h.
References m_parsers.
~ParserManager()
ParserManager::~ParserManager () inline
Definition at line 150 of file parserintf.h.
References m_defaultParser.
Member Function Documentation
getParser()
ParserInterface* ParserManager::getParser (const char * extension) inline
Gets the interface to the parser associated with given extension.
If there is no parser explicitly registered for the supplied extension, the interface to the default parser will be returned.
Definition at line 191 of file parserintf.h.
References m_defaultParser, and m_extensions.
Referenced by getParserForFile(), MarkdownFileParser::parseCode(), parseCode(), MarkdownFileParser::parsePrototype(), FileDef::parseSource(), MarkdownFileParser::resetCodeParserState(), DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), LatexDocVisitor::visit(), writeDocbookCodeBlock(), MemberDef::writeDocumentation(), Definition::writeInlineCode(), FileDef::writeSource(), VhdlDocGen::writeSource(), and writeXMLCodeBlock().
registerDefaultParser()
void ParserManager::registerDefaultParser (ParserInterface * parser) inline
Definition at line 155 of file parserintf.h.
References m_defaultParser.
Referenced by initDoxygen().
registerExtension()
bool ParserManager::registerExtension (const char * extension, const char * parserName) inline
Registers a file extension with a parser with name parserName.
Returns TRUE if the extension was successfully registered.
Definition at line 174 of file parserintf.h.
References m_extensions, and m_parsers.
registerParser()
void ParserManager::registerParser (const char * name, ParserInterface * parser) inline
Registers an additional parser.
Parameters
[in] name A symbolic name of the parser, i.e. "c", "python", "fortran", "vhdl", ...
[in] parser The parser that is to be used for the given name.
Definition at line 166 of file parserintf.h.
References m_parsers.
Referenced by initDoxygen().
Member Data Documentation
m_defaultParser
ParserInterface* ParserManager::m_defaultParser private
Definition at line 206 of file parserintf.h.
Referenced by getParser(), registerDefaultParser(), and ~ParserManager().
m_extensions
QDict<ParserInterface> ParserManager::m_extensions private
Definition at line 205 of file parserintf.h.
Referenced by getParser(), and registerExtension().
m_parsers
QDict<ParserInterface> ParserManager::m_parsers private
Definition at line 204 of file parserintf.h.
Referenced by ParserManager(), registerExtension(), and registerParser().
The documentation for this class was generated from the following file:
src/parserintf.h