Doxygen: NestingNodeContext::Private Class Reference
NestingNodeContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const NestingNodeContext *parent, const NestingNodeContext *thisNode, Definition *d, int index, int level, bool addCls, bool inherit, bool hideSuper)
TemplateVariant get (const char *n) const
TemplateVariant isLeafNode () const
TemplateVariant children () const
TemplateVariant getClass () const
TemplateVariant getNamespace () const
TemplateVariant getDir () const
TemplateVariant getFile () const
TemplateVariant getPage () const
TemplateVariant getModule () const
TemplateVariant level () const
TemplateVariant id () const
TemplateVariant name () const
QCString relPathAsString () const
TemplateVariant brief () const
TemplateVariant isLinkable () const
TemplateVariant anchor () const
TemplateVariant fileName () const
TemplateVariant isReference () const
TemplateVariant externalReference () const
void addClasses (bool inherit, bool hideSuper)
void addNamespaces (bool addClasses)
void addDirFiles ()
void addPages ()
void addModules ()
Private Attributes
const NestingNodeContext * m_parent
Definition * m_def
SharedPtr< NestingContext > m_children
int m_level
int m_index
Cachable m_cache
Static Private Attributes
static PropertyMapper< NestingNodeContext::Private > s_inst
Detailed Description
Definition at line 6089 of file context.cpp.
Constructor & Destructor Documentation
Private()
NestingNodeContext::Private::Private (const NestingNodeContext * parent, const NestingNodeContext * thisNode, Definition * d, int index, int level, bool addCls, bool inherit, bool hideSuper) inline
Definition at line 6092 of file context.cpp.
References addClasses(), addDirFiles(), addModules(), addNamespaces(), addPages(), PropertyMapper< T >::addProperty(), NestingContext::alloc(), anchor(), brief(), children(), externalReference(), fileName(), getClass(), getDir(), getFile(), getModule(), getNamespace(), getPage(), id(), Config::init(), isLeafNode(), isLinkable(), isReference(), level(), m_children, name(), SharedPtr< T >::reset(), and s_inst.
Member Function Documentation
addClasses()
void NestingNodeContext::Private::addClasses (bool inherit, bool hideSuper) inline
Definition at line 6300 of file context.cpp.
References NestingContext::addClasses(), NestingContext::addDerivedClasses(), ClassDef::baseClasses(), classHasVisibleChildren(), DefinitionIntf::definitionType(), ClassDef::getClassSDict(), Definition::getLanguage(), m_children, m_def, SrcLangExt_VHDL, ClassDef::subClasses(), DefinitionIntf::TypeClass, and ClassDef::visited.
Referenced by addNamespaces(), and Private().
addDirFiles()
void NestingNodeContext::Private::addDirFiles () inline
Definition at line 6340 of file context.cpp.
References NestingContext::addDirs(), NestingContext::addFiles(), DefinitionIntf::definitionType(), DirDef::getFiles(), m_children, m_def, DirDef::subDirs(), and DefinitionIntf::TypeDir.
Referenced by Private().
addModules()
void NestingNodeContext::Private::addModules () inline
Definition at line 6360 of file context.cpp.
References NestingContext::addModules(), DefinitionIntf::definitionType(), GroupDef::getSubGroups(), m_children, m_def, and DefinitionIntf::TypeGroup.
Referenced by Private().
addNamespaces()
void NestingNodeContext::Private::addNamespaces (bool addClasses) inline
Definition at line 6328 of file context.cpp.
References NestingContext::addClasses(), addClasses(), NestingContext::addNamespaces(), DefinitionIntf::definitionType(), NamespaceDef::getClassSDict(), NamespaceDef::getNamespaceSDict(), m_children, m_def, and DefinitionIntf::TypeNamespace.
Referenced by Private().
addPages()
void NestingNodeContext::Private::addPages () inline
Definition at line 6352 of file context.cpp.
References NestingContext::addPages(), DefinitionIntf::definitionType(), PageDef::getSubPages(), m_children, m_def, and DefinitionIntf::TypePage.
Referenced by Private().
anchor()
TemplateVariant NestingNodeContext::Private::anchor () const inline
Definition at line 6281 of file context.cpp.
References Definition::anchor(), and m_def.
Referenced by Private().
brief()
TemplateVariant NestingNodeContext::Private::brief () const inline
Definition at line 6261 of file context.cpp.
References NestingNodeContext::Private::Cachable::brief, Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Definition::hasBriefDescription(), m_cache, m_def, parseDoc(), and ScopedPtr< T >::reset().
Referenced by Private().
children()
TemplateVariant NestingNodeContext::Private::children () const inline
Definition at line 6147 of file context.cpp.
References SharedPtr< T >::get(), and m_children.
Referenced by Private().
externalReference()
TemplateVariant NestingNodeContext::Private::externalReference () const inline
Definition at line 6293 of file context.cpp.
References Definition::externalReference(), m_def, and relPathAsString().
Referenced by Private().
fileName()
TemplateVariant NestingNodeContext::Private::fileName () const inline
Definition at line 6285 of file context.cpp.
References Definition::getOutputFileBase(), and m_def.
Referenced by Private().
get()
TemplateVariant NestingNodeContext::Private::get (const char * n) const inline
Definition at line 6139 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by NestingNodeContext::get().
getClass()
TemplateVariant NestingNodeContext::Private::getClass () const inline
Definition at line 6151 of file context.cpp.
References ClassContext::alloc(), NestingNodeContext::Private::Cachable::classContext, DefinitionIntf::definitionType(), SharedPtr< T >::get(), m_cache, m_def, SharedPtr< T >::reset(), and DefinitionIntf::TypeClass.
Referenced by Private().
getDir()
TemplateVariant NestingNodeContext::Private::getDir () const inline
Definition at line 6181 of file context.cpp.
References DirContext::alloc(), DefinitionIntf::definitionType(), NestingNodeContext::Private::Cachable::dirContext, SharedPtr< T >::get(), m_cache, m_def, SharedPtr< T >::reset(), and DefinitionIntf::TypeDir.
Referenced by Private().
getFile()
TemplateVariant NestingNodeContext::Private::getFile () const inline
Definition at line 6196 of file context.cpp.
References FileContext::alloc(), DefinitionIntf::definitionType(), NestingNodeContext::Private::Cachable::fileContext, SharedPtr< T >::get(), m_cache, m_def, SharedPtr< T >::reset(), and DefinitionIntf::TypeFile.
Referenced by Private().
getModule()
TemplateVariant NestingNodeContext::Private::getModule () const inline
Definition at line 6226 of file context.cpp.
References ModuleContext::alloc(), DefinitionIntf::definitionType(), SharedPtr< T >::get(), m_cache, m_def, NestingNodeContext::Private::Cachable::moduleContext, SharedPtr< T >::reset(), and DefinitionIntf::TypeGroup.
Referenced by Private().
getNamespace()
TemplateVariant NestingNodeContext::Private::getNamespace () const inline
Definition at line 6166 of file context.cpp.
References NamespaceContext::alloc(), DefinitionIntf::definitionType(), SharedPtr< T >::get(), m_cache, m_def, NestingNodeContext::Private::Cachable::namespaceContext, SharedPtr< T >::reset(), and DefinitionIntf::TypeNamespace.
Referenced by Private().
getPage()
TemplateVariant NestingNodeContext::Private::getPage () const inline
Definition at line 6211 of file context.cpp.
References PageContext::alloc(), DefinitionIntf::definitionType(), SharedPtr< T >::get(), m_cache, m_def, NestingNodeContext::Private::Cachable::pageContext, SharedPtr< T >::reset(), and DefinitionIntf::TypePage.
Referenced by Private().
id()
TemplateVariant NestingNodeContext::Private::id () const inline
Definition at line 6245 of file context.cpp.
References NestingNodeContext::id(), m_index, and m_parent.
Referenced by NestingNodeContext::id(), and Private().
isLeafNode()
TemplateVariant NestingNodeContext::Private::isLeafNode () const inline
Definition at line 6143 of file context.cpp.
References NestingContext::count(), and m_children.
Referenced by Private().
isLinkable()
TemplateVariant NestingNodeContext::Private::isLinkable () const inline
Definition at line 6277 of file context.cpp.
References Definition::isLinkable(), and m_def.
Referenced by Private().
isReference()
TemplateVariant NestingNodeContext::Private::isReference () const inline
Definition at line 6289 of file context.cpp.
References Definition::isReference(), and m_def.
Referenced by Private().
level()
TemplateVariant NestingNodeContext::Private::level () const inline
Definition at line 6241 of file context.cpp.
References m_level.
Referenced by Private().
name()
TemplateVariant NestingNodeContext::Private::name () const inline
Definition at line 6252 of file context.cpp.
References Definition::displayName(), and m_def.
Referenced by Private().
relPathAsString()
QCString NestingNodeContext::Private::relPathAsString () const inline
Definition at line 6256 of file context.cpp.
References Config_getBool.
Referenced by externalReference().
Member Data Documentation
m_cache
Cachable NestingNodeContext::Private::m_cache mutable private
Definition at line 6384 of file context.cpp.
Referenced by brief(), getClass(), getDir(), getFile(), getModule(), getNamespace(), and getPage().
m_children
SharedPtr<NestingContext> NestingNodeContext::Private::m_children private
Definition at line 6371 of file context.cpp.
Referenced by addClasses(), addDirFiles(), addModules(), addNamespaces(), addPages(), children(), isLeafNode(), and Private().
m_def
Definition* NestingNodeContext::Private::m_def private
Definition at line 6370 of file context.cpp.
Referenced by addClasses(), addDirFiles(), addModules(), addNamespaces(), addPages(), anchor(), brief(), externalReference(), fileName(), getClass(), getDir(), getFile(), getModule(), getNamespace(), getPage(), isLinkable(), isReference(), and name().
m_index
int NestingNodeContext::Private::m_index private
Definition at line 6373 of file context.cpp.
Referenced by id().
m_level
int NestingNodeContext::Private::m_level private
Definition at line 6372 of file context.cpp.
Referenced by level().
m_parent
const NestingNodeContext* NestingNodeContext::Private::m_parent private
Definition at line 6369 of file context.cpp.
Referenced by id().
s_inst
PropertyMapper< NestingNodeContext::Private > NestingNodeContext::Private::s_inst static private
Definition at line 6385 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp