Doxygen: RTFDocVisitor Class Reference
RTFDocVisitor Class Reference
Concrete visitor implementation for RTF output.
#include <rtfdocvisitor.h>
Public Member Functions
RTFDocVisitor (FTextStream &t, CodeOutputInterface &ci, const char *langExt)
void visit (DocWord *)
void visit (DocLinkedWord *)
void visit (DocWhiteSpace *)
void visit (DocSymbol *)
void visit (DocURL *)
void visit (DocLineBreak *)
void visit (DocHorRuler *)
void visit (DocStyleChange *)
void visit (DocVerbatim *)
void visit (DocAnchor *)
void visit (DocInclude *)
void visit (DocIncOperator *)
void visit (DocFormula *)
void visit (DocIndexEntry *)
void visit (DocSimpleSectSep *)
void visit (DocCite *)
void visitPre (DocAutoList *)
void visitPost (DocAutoList *)
void visitPre (DocAutoListItem *)
void visitPost (DocAutoListItem *)
void visitPre (DocPara *)
void visitPost (DocPara *)
void visitPre (DocRoot *)
void visitPost (DocRoot *)
void visitPre (DocSimpleSect *)
void visitPost (DocSimpleSect *)
void visitPre (DocTitle *)
void visitPost (DocTitle *)
void visitPre (DocSimpleList *)
void visitPost (DocSimpleList *)
void visitPre (DocSimpleListItem *)
void visitPost (DocSimpleListItem *)
void visitPre (DocSection *s)
void visitPost (DocSection *)
void visitPre (DocHtmlList *s)
void visitPost (DocHtmlList *s)
void visitPre (DocHtmlListItem *)
void visitPost (DocHtmlListItem *)
void visitPre (DocHtmlDescList *)
void visitPost (DocHtmlDescList *)
void visitPre (DocHtmlDescTitle *)
void visitPost (DocHtmlDescTitle *)
void visitPre (DocHtmlDescData *)
void visitPost (DocHtmlDescData *)
void visitPre (DocHtmlTable *t)
void visitPost (DocHtmlTable *t)
void visitPre (DocHtmlCaption *)
void visitPost (DocHtmlCaption *)
void visitPre (DocHtmlRow *)
void visitPost (DocHtmlRow *)
void visitPre (DocHtmlCell *)
void visitPost (DocHtmlCell *)
void visitPre (DocInternal *)
void visitPost (DocInternal *)
void visitPre (DocHRef *)
void visitPost (DocHRef *)
void visitPre (DocHtmlHeader *)
void visitPost (DocHtmlHeader *)
void visitPre (DocImage *)
void visitPost (DocImage *)
void visitPre (DocDotFile *)
void visitPost (DocDotFile *)
void visitPre (DocMscFile *)
void visitPost (DocMscFile *)
void visitPre (DocDiaFile *)
void visitPost (DocDiaFile *)
void visitPre (DocLink *)
void visitPost (DocLink *)
void visitPre (DocRef *ref)
void visitPost (DocRef *)
void visitPre (DocSecRefItem *)
void visitPost (DocSecRefItem *)
void visitPre (DocSecRefList *)
void visitPost (DocSecRefList *)
void visitPre (DocParamSect *)
void visitPost (DocParamSect *)
void visitPre (DocParamList *)
void visitPost (DocParamList *)
void visitPre (DocXRefItem *)
void visitPost (DocXRefItem *)
void visitPre (DocInternalRef *)
void visitPost (DocInternalRef *)
void visitPre (DocCopy *)
void visitPost (DocCopy *)
void visitPre (DocText *)
void visitPost (DocText *)
void visitPre (DocHtmlBlockQuote *)
void visitPost (DocHtmlBlockQuote *)
void visitPre (DocVhdlFlow *)
void visitPost (DocVhdlFlow *)
void visitPre (DocParBlock *)
void visitPost (DocParBlock *)
Public Member Functions inherited from DocVisitor
DocVisitor (int id)
virtual ~DocVisitor ()
int id () const
Private Member Functions
void filter (const char *str, bool verbatim=FALSE)
void startLink (const QCString &ref, const QCString &file, const QCString &anchor)
void endLink (const QCString &ref)
QCString getStyle (const char *name)
void incIndentLevel ()
void decIndentLevel ()
void pushEnabled ()
void popEnabled ()
void includePicturePreRTF (const QCString name, const bool isTypeRTF, const bool hasCaption)
void includePicturePostRTF (const bool isTypeRTF, const bool hasCaption)
void writeDotFile (const QCString &fileName, const bool hasCaption)
void writeDotFile (DocDotFile *)
void writeMscFile (const QCString &fileName, const bool hasCaption)
void writeMscFile (DocMscFile *)
void writeDiaFile (DocDiaFile *)
void writePlantUMLFile (const QCString &fileName, const bool hasCaption)
Private Attributes
FTextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre
bool m_hide
int m_indentLevel
QStack< bool > m_enabled
bool m_lastIsPara
QCString m_langExt
Detailed Description
Concrete visitor implementation for RTF output.
Definition at line 30 of file rtfdocvisitor.h.
Constructor & Destructor Documentation
RTFDocVisitor()
RTFDocVisitor::RTFDocVisitor (FTextStream & t, CodeOutputInterface & ci, const char * langExt)
Definition at line 60 of file rtfdocvisitor.cpp.
Member Function Documentation
decIndentLevel()
void RTFDocVisitor::decIndentLevel () private
Definition at line 81 of file rtfdocvisitor.cpp.
References m_indentLevel.
Referenced by visitPost().
endLink()
void RTFDocVisitor::endLink (const QCString & ref) private
Definition at line 1712 of file rtfdocvisitor.cpp.
References Config_getBool, m_lastIsPara, and m_t.
Referenced by visit(), and visitPost().
filter()
void RTFDocVisitor::filter (const char * str, bool verbatim = FALSE) private
Definition at line 1636 of file rtfdocvisitor.cpp.
References endl(), and m_t.
Referenced by visit(), and visitPre().
getStyle()
QCString RTFDocVisitor::getStyle (const char * name) private
Definition at line 67 of file rtfdocvisitor.cpp.
References m_indentLevel, StyleData::reference, and rtf_Style.
Referenced by visit(), visitPost(), and visitPre().
incIndentLevel()
void RTFDocVisitor::incIndentLevel () private
Definition at line 76 of file rtfdocvisitor.cpp.
References m_indentLevel, and rtf_maxIndentLevels.
Referenced by visitPost(), and visitPre().
includePicturePostRTF()
void RTFDocVisitor::includePicturePostRTF (const bool isTypeRTF, const bool hasCaption) private
Definition at line 1114 of file rtfdocvisitor.cpp.
References endl(), m_hide, m_t, and popEnabled().
Referenced by visit(), and visitPost().
includePicturePreRTF()
void RTFDocVisitor::includePicturePreRTF (const QCString name, const bool isTypeRTF, const bool hasCaption) private
Definition at line 1082 of file rtfdocvisitor.cpp.
References endl(), m_hide, m_lastIsPara, m_t, pushEnabled(), and rtf_Style_Reset.
Referenced by visitPre(), writeDiaFile(), writeDotFile(), writeMscFile(), and writePlantUMLFile().
popEnabled()
void RTFDocVisitor::popEnabled () private
Definition at line 1730 of file rtfdocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by includePicturePostRTF(), and visit().
pushEnabled()
void RTFDocVisitor::pushEnabled () private
Definition at line 1725 of file rtfdocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by includePicturePreRTF(), and visit().
startLink()
void RTFDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & anchor) private
Definition at line 1682 of file rtfdocvisitor.cpp.
References Config_getBool, m_lastIsPara, m_t, and rtfFormatBmkStr().
Referenced by visit(), and visitPre().
visit() [1/16]
void RTFDocVisitor::visit (DocWord * w) virtual
Implements DocVisitor.
Definition at line 90 of file rtfdocvisitor.cpp.
References DBG_RTF, filter(), m_hide, m_lastIsPara, and DocWord::word().
Referenced by visitPre().
visit() [2/16]
void RTFDocVisitor::visit (DocLinkedWord * w) virtual
Implements DocVisitor.
Definition at line 98 of file rtfdocvisitor.cpp.
References DocLinkedWord::anchor(), DBG_RTF, endLink(), DocLinkedWord::file(), filter(), m_hide, m_lastIsPara, DocLinkedWord::ref(), startLink(), and DocLinkedWord::word().
visit() [3/16]
void RTFDocVisitor::visit (DocWhiteSpace * w) virtual
Implements DocVisitor.
Definition at line 108 of file rtfdocvisitor.cpp.
References DocWhiteSpace::chars(), DBG_RTF, m_hide, m_insidePre, m_lastIsPara, and m_t.
visit() [4/16]
void RTFDocVisitor::visit (DocSymbol * s) virtual
Implements DocVisitor.
Definition at line 123 of file rtfdocvisitor.cpp.
References DBG_RTF, err(), HtmlEntityMapper::instance(), m_hide, m_lastIsPara, m_t, HtmlEntityMapper::rtf(), and DocSymbol::symbol().
visit() [5/16]
void RTFDocVisitor::visit (DocURL * u) virtual
Implements DocVisitor.
Definition at line 139 of file rtfdocvisitor.cpp.
References Config_getBool, DBG_RTF, endl(), filter(), DocURL::isEmail(), m_hide, m_lastIsPara, m_t, and DocURL::url().
visit() [6/16]
void RTFDocVisitor::visit (DocLineBreak *) virtual
Implements DocVisitor.
Definition at line 169 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visit() [7/16]
void RTFDocVisitor::visit (DocHorRuler *) virtual
Implements DocVisitor.
Definition at line 177 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visit() [8/16]
void RTFDocVisitor::visit (DocStyleChange * s) virtual
Implements DocVisitor.
Definition at line 185 of file rtfdocvisitor.cpp.
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Code, DBG_RTF, DocStyleChange::Div, DocStyleChange::enable(), endl(), getStyle(), DocStyleChange::Italic, m_hide, m_insidePre, m_lastIsPara, m_t, DocStyleChange::Preformatted, rtf_Style_Reset, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::style(), DocStyleChange::Subscript, and DocStyleChange::Superscript.
visit() [9/16]
void RTFDocVisitor::visit (DocVerbatim * s) virtual
Implements DocVisitor.
Definition at line 241 of file rtfdocvisitor.cpp.
References DocVerbatim::children(), DocVerbatim::Code, Config_getBool, Config_getString, DocVerbatim::context(), DBG_RTF, DocVerbatim::DocbookOnly, DocVerbatim::Dot, endl(), err(), DocVerbatim::exampleFile(), filter(), getLanguageFromFileName(), ParserManager::getParser(), getStyle(), DocVerbatim::hasCaption(), DocVerbatim::HtmlOnly, includePicturePostRTF(), DocVerbatim::isExample(), DocVerbatim::language(), DocVerbatim::LatexOnly, m_ci, m_hide, m_langExt, m_lastIsPara, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, ParserInterface::parseCode(), Doxygen::parserManager, DocVerbatim::PlantUML, rtf_Style_Reset, DocVerbatim::RtfOnly, DocVerbatim::text(), DocVerbatim::type(), DocVerbatim::Verbatim, visitCaption(), writeDotFile(), writeMscFile(), writePlantUMLFile(), writePlantUMLSource(), and DocVerbatim::XmlOnly.
visit() [10/16]
void RTFDocVisitor::visit (DocAnchor * anc) virtual
Implements DocVisitor.
Definition at line 348 of file rtfdocvisitor.cpp.
References DocAnchor::anchor(), DBG_RTF, endl(), DocAnchor::file(), m_hide, m_lastIsPara, m_t, and rtfFormatBmkStr().
visit() [11/16]
void RTFDocVisitor::visit (DocInclude * inc) virtual
Implements DocVisitor.
Definition at line 370 of file rtfdocvisitor.cpp.
References DocInclude::blockId(), DocInclude::context(), DBG_RTF, DocInclude::DontInclude, endl(), err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), DocInclude::file(), filter(), getLanguageFromFileName(), ParserManager::getParser(), getStyle(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_hide, m_lastIsPara, m_t, parseCode(), Doxygen::parserManager, rtf_Style_Reset, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::text(), DocInclude::type(), and DocInclude::VerbInclude.
visit() [12/16]
void RTFDocVisitor::visit (DocIncOperator * op) virtual
Implements DocVisitor.
Definition at line 480 of file rtfdocvisitor.cpp.
References DocIncOperator::context(), DBG_RTF, endl(), DocIncOperator::exampleFile(), getLanguageFromFileName(), ParserManager::getParser(), getStyle(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), m_ci, m_hide, m_langExt, m_lastIsPara, m_t, ParserInterface::parseCode(), Doxygen::parserManager, popEnabled(), pushEnabled(), rtf_Style_Reset, DocIncOperator::Skip, DocIncOperator::text(), and DocIncOperator::type().
visit() [13/16]
void RTFDocVisitor::visit (DocFormula * f) virtual
Implements DocVisitor.
Definition at line 526 of file rtfdocvisitor.cpp.
References DBG_RTF, m_hide, m_lastIsPara, m_t, and DocFormula::text().
visit() [14/16]
void RTFDocVisitor::visit (DocIndexEntry * i) virtual
Implements DocVisitor.
Definition at line 535 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), DocIndexEntry::entry(), m_hide, m_lastIsPara, and m_t.
visit() [15/16]
void RTFDocVisitor::visit (DocSimpleSectSep *) virtual
Implements DocVisitor.
Definition at line 543 of file rtfdocvisitor.cpp.
visit() [16/16]
void RTFDocVisitor::visit (DocCite * cite) virtual
Implements DocVisitor.
Definition at line 547 of file rtfdocvisitor.cpp.
References DocCite::anchor(), DBG_RTF, endLink(), DocCite::file(), filter(), m_hide, m_t, DocCite::ref(), startLink(), and DocCite::text().
visitPost() [1/38]
void RTFDocVisitor::visitPost (DocAutoList *) virtual
Implements DocVisitor.
Definition at line 585 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [2/38]
void RTFDocVisitor::visitPost (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 614 of file rtfdocvisitor.cpp.
References DBG_RTF, and decIndentLevel().
visitPost() [3/38]
void RTFDocVisitor::visitPost (DocPara * p) virtual
Implements DocVisitor.
Definition at line 625 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), DocPara::isLast(), DocNode::kind(), DocNode::Kind_ParamSect, m_hide, m_lastIsPara, m_t, and DocNode::parent().
visitPost() [4/38]
void RTFDocVisitor::visitPost (DocRoot * r) virtual
Implements DocVisitor.
Definition at line 649 of file rtfdocvisitor.cpp.
References DBG_RTF, decIndentLevel(), endl(), DocRoot::indent(), m_hide, m_lastIsPara, m_t, and DocRoot::singleLine().
visitPost() [5/38]
void RTFDocVisitor::visitPost (DocSimpleSect *) virtual
Implements DocVisitor.
Definition at line 716 of file rtfdocvisitor.cpp.
References DBG_RTF, decIndentLevel(), endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [6/38]
void RTFDocVisitor::visitPost (DocTitle *) virtual
Implements DocVisitor.
Definition at line 731 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, and rtf_Style_Reset.
visitPost() [7/38]
void RTFDocVisitor::visitPost (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 751 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [8/38]
void RTFDocVisitor::visitPost (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 769 of file rtfdocvisitor.cpp.
References DBG_RTF, and decIndentLevel().
visitPost() [9/38]
void RTFDocVisitor::visitPost (DocSection *) virtual
Implements DocVisitor.
Definition at line 798 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [10/38]
void RTFDocVisitor::visitPost (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 816 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [11/38]
void RTFDocVisitor::visitPost (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 844 of file rtfdocvisitor.cpp.
References DBG_RTF, and decIndentLevel().
visitPost() [12/38]
void RTFDocVisitor::visitPost (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 859 of file rtfdocvisitor.cpp.
References DBG_RTF, and m_hide.
visitPost() [13/38]
void RTFDocVisitor::visitPost (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 878 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [14/38]
void RTFDocVisitor::visitPost (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 895 of file rtfdocvisitor.cpp.
References DBG_RTF, decIndentLevel(), endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [15/38]
void RTFDocVisitor::visitPost (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 913 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [16/38]
void RTFDocVisitor::visitPost (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 927 of file rtfdocvisitor.cpp.
References DBG_RTF.
visitPost() [17/38]
void RTFDocVisitor::visitPost (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 961 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [18/38]
void RTFDocVisitor::visitPost (DocHtmlCell *) virtual
Implements DocVisitor.
Definition at line 979 of file rtfdocvisitor.cpp.
References DBG_RTF, m_hide, m_lastIsPara, and m_t.
visitPost() [19/38]
void RTFDocVisitor::visitPost (DocInternal *) virtual
Implements DocVisitor.
Definition at line 1001 of file rtfdocvisitor.cpp.
References m_hide.
visitPost() [20/38]
void RTFDocVisitor::visitPost (DocHRef *) virtual
Implements DocVisitor.
Definition at line 1033 of file rtfdocvisitor.cpp.
References Config_getBool, DBG_RTF, m_hide, m_lastIsPara, and m_t.
visitPost() [21/38]
void RTFDocVisitor::visitPost (DocHtmlHeader *) virtual
Implements DocVisitor.
Definition at line 1066 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [22/38]
void RTFDocVisitor::visitPost (DocImage * img) virtual
Implements DocVisitor.
Definition at line 1108 of file rtfdocvisitor.cpp.
References DBG_RTF, DocImage::hasCaption(), includePicturePostRTF(), DocImage::Rtf, and DocImage::type().
visitPost() [23/38]
void RTFDocVisitor::visitPost (DocDotFile * df) virtual
Implements DocVisitor.
Definition at line 1141 of file rtfdocvisitor.cpp.
References DBG_RTF, DocDotFile::hasCaption(), and includePicturePostRTF().
visitPost() [24/38]
void RTFDocVisitor::visitPost (DocMscFile * df) virtual
Implements DocVisitor.
Definition at line 1152 of file rtfdocvisitor.cpp.
References DBG_RTF, DocMscFile::hasCaption(), and includePicturePostRTF().
visitPost() [25/38]
void RTFDocVisitor::visitPost (DocDiaFile * df) virtual
Implements DocVisitor.
Definition at line 1164 of file rtfdocvisitor.cpp.
References DBG_RTF, DocDiaFile::hasCaption(), and includePicturePostRTF().
visitPost() [26/38]
void RTFDocVisitor::visitPost (DocLink * lnk) virtual
Implements DocVisitor.
Definition at line 1177 of file rtfdocvisitor.cpp.
References DBG_RTF, endLink(), m_hide, and DocLink::ref().
visitPost() [27/38]
void RTFDocVisitor::visitPost (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 1201 of file rtfdocvisitor.cpp.
References DBG_RTF, endLink(), DocRef::file(), m_hide, and DocRef::ref().
visitPost() [28/38]
void RTFDocVisitor::visitPost (DocSecRefItem *) virtual
Implements DocVisitor.
Definition at line 1215 of file rtfdocvisitor.cpp.
References DBG_RTF.
visitPost() [29/38]
void RTFDocVisitor::visitPost (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 1231 of file rtfdocvisitor.cpp.
References DBG_RTF, decIndentLevel(), endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [30/38]
void RTFDocVisitor::visitPost (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 1301 of file rtfdocvisitor.cpp.
References DBG_RTF, decIndentLevel(), endl(), DocParamSect::Exception, m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, and DocParamSect::type().
visitPost() [31/38]
void RTFDocVisitor::visitPost (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 1454 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), DocParamSect::Exception, DocNode::kind(), DocNode::Kind_ParamSect, m_hide, m_lastIsPara, m_t, DocParamSect::Param, DocNode::parent(), DocParamSect::RetVal, DocParamSect::TemplateParam, and DocParamSect::Unknown.
visitPost() [32/38]
void RTFDocVisitor::visitPost (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1538 of file rtfdocvisitor.cpp.
References DBG_RTF, decIndentLevel(), endl(), m_hide, m_lastIsPara, m_t, and DocXRefItem::title().
visitPost() [33/38]
void RTFDocVisitor::visitPost (DocInternalRef *) virtual
Implements DocVisitor.
Definition at line 1556 of file rtfdocvisitor.cpp.
References DBG_RTF, endLink(), m_hide, and m_t.
visitPost() [34/38]
void RTFDocVisitor::visitPost (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1570 of file rtfdocvisitor.cpp.
References DBG_RTF, and m_hide.
visitPost() [35/38]
void RTFDocVisitor::visitPost (DocText *) virtual
Implements DocVisitor.
Definition at line 1582 of file rtfdocvisitor.cpp.
References DBG_RTF, and m_hide.
visitPost() [36/38]
void RTFDocVisitor::visitPost (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1598 of file rtfdocvisitor.cpp.
References DBG_RTF, decIndentLevel(), endl(), m_hide, m_lastIsPara, and m_t.
visitPost() [37/38]
void RTFDocVisitor::visitPost (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1613 of file rtfdocvisitor.cpp.
References m_hide.
visitPost() [38/38]
void RTFDocVisitor::visitPost (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1623 of file rtfdocvisitor.cpp.
References m_hide.
visitPre() [1/38]
void RTFDocVisitor::visitPre (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 575 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), RTFListItemInfo::isEnum, DocAutoList::isEnumList(), m_hide, m_indentLevel, m_lastIsPara, m_t, RTFListItemInfo::number, and rtf_listItemInfo.
visitPre() [2/38]
void RTFDocVisitor::visitPre (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 594 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), getStyle(), incIndentLevel(), m_hide, m_indentLevel, m_lastIsPara, m_t, RTFListItemInfo::number, rtf_listItemInfo, and rtf_Style_Reset.
visitPre() [3/38]
void RTFDocVisitor::visitPre (DocPara *) virtual
Implements DocVisitor.
Definition at line 620 of file rtfdocvisitor.cpp.
References DBG_RTF.
visitPre() [4/38]
void RTFDocVisitor::visitPre (DocRoot * r) virtual
Implements DocVisitor.
Definition at line 641 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), incIndentLevel(), DocRoot::indent(), m_hide, m_t, and rtf_Style.
visitPre() [5/38]
void RTFDocVisitor::visitPre (DocSimpleSect * s) virtual
Implements DocVisitor.
Definition at line 659 of file rtfdocvisitor.cpp.
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, DBG_RTF, endl(), getStyle(), incIndentLevel(), DocSimpleSect::Invar, m_hide, m_lastIsPara, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, rtf_Style, rtf_Style_Reset, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), Translator::trVersion(), Translator::trWarning(), DocSimpleSect::type(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
visitPre() [6/38]
void RTFDocVisitor::visitPre (DocTitle *) virtual
Implements DocVisitor.
Definition at line 726 of file rtfdocvisitor.cpp.
References DBG_RTF.
visitPre() [7/38]
void RTFDocVisitor::visitPre (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 742 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), RTFListItemInfo::isEnum, m_hide, m_indentLevel, m_lastIsPara, m_t, and rtf_listItemInfo.
visitPre() [8/38]
void RTFDocVisitor::visitPre (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 760 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, and rtf_Style_Reset.
visitPre() [9/38]
void RTFDocVisitor::visitPre (DocSection * s) virtual
Implements DocVisitor.
Definition at line 775 of file rtfdocvisitor.cpp.
References DocSection::anchor(), DBG_RTF, endl(), DocSection::file(), filter(), DocSection::level(), m_hide, m_lastIsPara, m_t, rtf_Style, rtf_Style_Reset, rtfFormatBmkStr(), and DocSection::title().
visitPre() [10/38]
void RTFDocVisitor::visitPre (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 806 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), RTFListItemInfo::isEnum, m_hide, m_indentLevel, m_lastIsPara, m_t, RTFListItemInfo::number, DocHtmlList::Ordered, rtf_listItemInfo, and DocHtmlList::type().
visitPre() [11/38]
void RTFDocVisitor::visitPre (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 824 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), getStyle(), incIndentLevel(), m_hide, m_indentLevel, m_lastIsPara, m_t, RTFListItemInfo::number, rtf_listItemInfo, and rtf_Style_Reset.
visitPre() [12/38]
void RTFDocVisitor::visitPre (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 850 of file rtfdocvisitor.cpp.
References DBG_RTF, and m_hide.
visitPre() [13/38]
void RTFDocVisitor::visitPre (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 868 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, m_t, and rtf_Style.
visitPre() [14/38]
void RTFDocVisitor::visitPre (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 887 of file rtfdocvisitor.cpp.
References DBG_RTF, getStyle(), incIndentLevel(), m_hide, m_t, and rtf_Style_Reset.
visitPre() [15/38]
void RTFDocVisitor::visitPre (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 905 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), m_hide, m_lastIsPara, and m_t.
visitPre() [16/38]
void RTFDocVisitor::visitPre (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 922 of file rtfdocvisitor.cpp.
References DBG_RTF.
visitPre() [17/38]
void RTFDocVisitor::visitPre (DocHtmlRow * r) virtual
Implements DocVisitor.
Definition at line 932 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), DocHtmlRow::isHeading(), m_hide, m_lastIsPara, m_t, DocHtmlRow::numCells(), and rtf_pageWidth.
visitPre() [18/38]
void RTFDocVisitor::visitPre (DocHtmlCell * c) virtual
Implements DocVisitor.
Definition at line 971 of file rtfdocvisitor.cpp.
References align(), DBG_RTF, m_hide, m_lastIsPara, and m_t.
visitPre() [19/38]
void RTFDocVisitor::visitPre (DocInternal *) virtual
Implements DocVisitor.
Definition at line 987 of file rtfdocvisitor.cpp.
References m_hide.
visitPre() [20/38]
void RTFDocVisitor::visitPre (DocHRef * href) virtual
Implements DocVisitor.
Definition at line 1011 of file rtfdocvisitor.cpp.
References Config_getBool, DBG_RTF, m_hide, m_lastIsPara, m_t, and DocHRef::url().
visitPre() [21/38]
void RTFDocVisitor::visitPre (DocHtmlHeader * header) virtual
Implements DocVisitor.
Definition at line 1050 of file rtfdocvisitor.cpp.
References DBG_RTF, DocHtmlHeader::level(), m_hide, m_lastIsPara, m_t, rtf_Style, and rtf_Style_Reset.
visitPre() [22/38]
void RTFDocVisitor::visitPre (DocImage * img) virtual
Implements DocVisitor.
Definition at line 1076 of file rtfdocvisitor.cpp.
References DBG_RTF, DocImage::hasCaption(), includePicturePreRTF(), DocImage::name(), DocImage::Rtf, and DocImage::type().
visitPre() [23/38]
void RTFDocVisitor::visitPre (DocDotFile * df) virtual
Implements DocVisitor.
Definition at line 1135 of file rtfdocvisitor.cpp.
References DBG_RTF, and writeDotFile().
visitPre() [24/38]
void RTFDocVisitor::visitPre (DocMscFile * df) virtual
Implements DocVisitor.
Definition at line 1146 of file rtfdocvisitor.cpp.
References DBG_RTF, and writeMscFile().
visitPre() [25/38]
void RTFDocVisitor::visitPre (DocDiaFile * df) virtual
Implements DocVisitor.
Definition at line 1158 of file rtfdocvisitor.cpp.
References DBG_RTF, and writeDiaFile().
visitPre() [26/38]
void RTFDocVisitor::visitPre (DocLink * lnk) virtual
Implements DocVisitor.
Definition at line 1170 of file rtfdocvisitor.cpp.
References DocLink::anchor(), DBG_RTF, DocLink::file(), m_hide, DocLink::ref(), and startLink().
visitPre() [27/38]
void RTFDocVisitor::visitPre (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 1184 of file rtfdocvisitor.cpp.
References DocRef::anchor(), DBG_RTF, DocRef::file(), filter(), DocRef::hasLinkText(), DocRef::isSubPage(), m_hide, DocRef::ref(), startLink(), and DocRef::targetTitle().
visitPre() [28/38]
void RTFDocVisitor::visitPre (DocSecRefItem *) virtual
Implements DocVisitor.
Definition at line 1210 of file rtfdocvisitor.cpp.
References DBG_RTF.
visitPre() [29/38]
void RTFDocVisitor::visitPre (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 1220 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, and rtf_Style_Reset.
visitPre() [30/38]
void RTFDocVisitor::visitPre (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 1262 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), DocParamSect::Exception, getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, DocParamSect::Param, DocParamSect::RetVal, rtf_Style, rtf_Style_Reset, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), and DocParamSect::type().
visitPre() [31/38]
void RTFDocVisitor::visitPre (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 1317 of file rtfdocvisitor.cpp.
References DBG_RTF, DocParamList::direction(), endl(), DocParamSect::Exception, DocParamSect::hasInOutSpecifier(), DocParamSect::hasTypeSpecifier(), DocParamSect::In, DocParamSect::InOut, DocNode::kind(), DocNode::Kind_LinkedWord, DocNode::Kind_ParamSect, DocNode::Kind_Word, m_hide, m_lastIsPara, m_t, DocParamSect::Out, DocParamSect::Param, DocParamList::parameters(), DocParamList::paramTypes(), DocNode::parent(), DocParamSect::RetVal, rtf_pageWidth, DocParamSect::TemplateParam, DocParamSect::Unknown, DocParamSect::Unspecified, and visit().
visitPre() [32/38]
void RTFDocVisitor::visitPre (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1484 of file rtfdocvisitor.cpp.
References DocXRefItem::anchor(), Config_getBool, DBG_RTF, endl(), DocXRefItem::file(), filter(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, rtf_Style, rtf_Style_Reset, and DocXRefItem::title().
visitPre() [33/38]
void RTFDocVisitor::visitPre (DocInternalRef * ref) virtual
Implements DocVisitor.
Definition at line 1549 of file rtfdocvisitor.cpp.
References DocInternalRef::anchor(), DBG_RTF, DocInternalRef::file(), m_hide, and startLink().
visitPre() [34/38]
void RTFDocVisitor::visitPre (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1564 of file rtfdocvisitor.cpp.
References DBG_RTF, and m_hide.
visitPre() [35/38]
void RTFDocVisitor::visitPre (DocText *) virtual
Implements DocVisitor.
Definition at line 1576 of file rtfdocvisitor.cpp.
References DBG_RTF, and m_hide.
visitPre() [36/38]
void RTFDocVisitor::visitPre (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1588 of file rtfdocvisitor.cpp.
References DBG_RTF, endl(), getStyle(), incIndentLevel(), m_hide, m_lastIsPara, m_t, and rtf_Style_Reset.
visitPre() [37/38]
void RTFDocVisitor::visitPre (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1608 of file rtfdocvisitor.cpp.
References m_hide.
visitPre() [38/38]
void RTFDocVisitor::visitPre (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1618 of file rtfdocvisitor.cpp.
References m_hide.
writeDiaFile()
void RTFDocVisitor::writeDiaFile (DocDiaFile * df) private
Definition at line 1773 of file rtfdocvisitor.cpp.
References Config_getString, DIA_BITMAP, DocDiaFile::file(), DocDiaFile::hasCaption(), includePicturePreRTF(), and writeDiaGraphFromFile().
Referenced by visitPre().
writeDotFile() [1/2]
void RTFDocVisitor::writeDotFile (const QCString & fileName, const bool hasCaption) private
Definition at line 1742 of file rtfdocvisitor.cpp.
References Config_getString, getDotImageExtension(), GOF_BITMAP, includePicturePreRTF(), and writeDotGraphFromFile().
Referenced by visit(), visitPre(), and writeDotFile().
writeDotFile() [2/2]
void RTFDocVisitor::writeDotFile (DocDotFile * df) private
Definition at line 1738 of file rtfdocvisitor.cpp.
References DocDotFile::file(), DocDotFile::hasCaption(), and writeDotFile().
writeMscFile() [1/2]
void RTFDocVisitor::writeMscFile (const QCString & fileName, const bool hasCaption) private
Definition at line 1760 of file rtfdocvisitor.cpp.
References Config_getString, includePicturePreRTF(), MSC_BITMAP, and writeMscGraphFromFile().
Referenced by visit(), visitPre(), and writeMscFile().
writeMscFile() [2/2]
void RTFDocVisitor::writeMscFile (DocMscFile * df) private
Definition at line 1756 of file rtfdocvisitor.cpp.
References DocMscFile::file(), DocMscFile::hasCaption(), and writeMscFile().
writePlantUMLFile()
void RTFDocVisitor::writePlantUMLFile (const QCString & fileName, const bool hasCaption) private
Definition at line 1786 of file rtfdocvisitor.cpp.
References Config_getString, generatePlantUMLOutput(), includePicturePreRTF(), and PUML_BITMAP.
Referenced by visit().
Member Data Documentation
m_ci
CodeOutputInterface& RTFDocVisitor::m_ci private
Definition at line 169 of file rtfdocvisitor.h.
Referenced by visit().
m_enabled
QStack<bool> RTFDocVisitor::m_enabled private
Definition at line 173 of file rtfdocvisitor.h.
Referenced by popEnabled(), and pushEnabled().
m_hide
bool RTFDocVisitor::m_hide private
Definition at line 171 of file rtfdocvisitor.h.
Referenced by includePicturePostRTF(), includePicturePreRTF(), popEnabled(), pushEnabled(), visit(), visitPost(), and visitPre().
m_indentLevel
int RTFDocVisitor::m_indentLevel private
Definition at line 172 of file rtfdocvisitor.h.
Referenced by decIndentLevel(), getStyle(), incIndentLevel(), and visitPre().
m_insidePre
bool RTFDocVisitor::m_insidePre private
Definition at line 170 of file rtfdocvisitor.h.
Referenced by visit().
m_langExt
QCString RTFDocVisitor::m_langExt private
Definition at line 175 of file rtfdocvisitor.h.
Referenced by visit().
m_lastIsPara
bool RTFDocVisitor::m_lastIsPara private
Definition at line 174 of file rtfdocvisitor.h.
Referenced by endLink(), includePicturePreRTF(), startLink(), visit(), visitPost(), and visitPre().
m_t
FTextStream& RTFDocVisitor::m_t private
Definition at line 168 of file rtfdocvisitor.h.
Referenced by endLink(), filter(), includePicturePostRTF(), includePicturePreRTF(), startLink(), visit(), visitPost(), and visitPre().
The documentation for this class was generated from the following files:
src/rtfdocvisitor.h
src/rtfdocvisitor.cpp