Doxygen: TemplateContext Class Reference
TemplateContext Class Reference abstract
Template API
Abstract interface for a template context.
#include <template.h>
Public Member Functions
virtual ~TemplateContext ()
virtual void push ()=0
Push a new scope on the stack.
virtual void pop ()=0
Pop the current scope from the stack.
virtual void set (const char *name, const TemplateVariant &v)=0
Sets a value in the current scope.
virtual TemplateVariant get (const QCString &name) const =0
Gets the value for a given key.
virtual const TemplateVariant * getRef (const QCString &name) const =0
Returns a pointer to the value corresponding to a given key.
virtual void setOutputDirectory (const QCString &dir)=0
When files are created (i.e.
virtual void setEscapeIntf (const QCString &extension, TemplateEscapeIntf *intf)=0
Sets the interface that will be used for escaping the result of variable expansion before writing it to the output.
virtual void setSpacelessIntf (TemplateSpacelessIntf *intf)=0
Sets the interface that will be used inside a spaceless block to remove any redundant whitespace.
Detailed Description
Abstract interface for a template context.
A Context consists of a stack of dictionaries. A dictionary consists of a mapping of string keys onto TemplateVariant values. A key is searched starting with the dictionary at the top of the stack and searching downwards until it is found. The stack is used to create local scopes.
Note
This object must be created by TemplateEngine::createContext()
Definition at line 489 of file template.h.
Constructor & Destructor Documentation
~TemplateContext()
virtual TemplateContext::~TemplateContext () inline virtual
Definition at line 492 of file template.h.
Member Function Documentation
get()
virtual TemplateVariant TemplateContext::get (const QCString & name) const pure virtual
Gets the value for a given key.
Parameters
[in] name The name of key.
Returns
The value, which can be an invalid variant in case the key was not found.
Implemented in TemplateContextImpl.
Referenced by ExprAstVariable::resolve().
getRef()
virtual const TemplateVariant* TemplateContext::getRef (const QCString & name) const pure virtual
Returns a pointer to the value corresponding to a given key.
Parameters
[in] name The name of key.
Returns
A pointer to the value, or 0 in case the key was not found.
Implemented in TemplateContextImpl.
Referenced by TemplateNodeRange::render(), and TemplateNodeFor::render().
pop()
virtual void TemplateContext::pop () pure virtual
Pop the current scope from the stack.
Implemented in TemplateContextImpl.
Referenced by TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeWith::render(), TemplateNodeMarkers::render(), and TemplateNodeTree::renderChildren().
push()
virtual void TemplateContext::push () pure virtual
Push a new scope on the stack.
Implemented in TemplateContextImpl.
Referenced by TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeWith::render(), TemplateNodeMarkers::render(), and TemplateNodeTree::renderChildren().
set()
virtual void TemplateContext::set (const char * name, const TemplateVariant & v) pure virtual
Sets a value in the current scope.
Parameters
[in] name The name of the value; the key in the dictionary.
[in] v The value associated with the key.
Note
When a given key is already present, its value will be replaced by v
Implemented in TemplateContextImpl.
Referenced by generateOutputViaTemplate(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeMarkers::render(), and TemplateNodeTree::renderChildren().
setEscapeIntf()
virtual void TemplateContext::setEscapeIntf (const QCString & extension, TemplateEscapeIntf * intf) pure virtual
Sets the interface that will be used for escaping the result of variable expansion before writing it to the output.
Implemented in TemplateContextImpl.
Referenced by generateOutputViaTemplate().
setOutputDirectory()
virtual void TemplateContext::setOutputDirectory (const QCString & dir) pure virtual
When files are created (i.e.
by {% create ... %}) they written to the directory dir.
Implemented in TemplateContextImpl.
Referenced by generateOutputViaTemplate().
setSpacelessIntf()
virtual void TemplateContext::setSpacelessIntf (TemplateSpacelessIntf * intf) pure virtual
Sets the interface that will be used inside a spaceless block to remove any redundant whitespace.
Implemented in TemplateContextImpl.
Referenced by generateOutputViaTemplate().
The documentation for this class was generated from the following file:
src/template.h