Doxygen: FilterAlphaIndex Class Reference
FilterAlphaIndex Class Reference
The implementation of the "alphaIndex" filter.
Classes
struct ListElem
class SortList
Static Public Member Functions
static TemplateVariant apply (const TemplateVariant &v, const TemplateVariant &args)
Static Private Member Functions
static QCString keyToLetter (uint startLetter)
static QCString keyToLabel (uint startLetter)
static uint determineSortKey (TemplateStructIntf *s, const QCString &attribName)
Detailed Description
The implementation of the "alphaIndex" filter.
Definition at line 1096 of file template.cpp.
Member Function Documentation
apply()
static TemplateVariant FilterAlphaIndex::apply (const TemplateVariant & v, const TemplateVariant & args) inline static
Definition at line 1166 of file template.cpp.
References TemplateList::alloc(), TemplateStruct::alloc(), TemplateList::append(), TemplateListIntf::createIterator(), TemplateListIntf::ConstIterator::current(), determineSortKey(), FilterAlphaIndex::ListElem::key, keyToLabel(), keyToLetter(), TemplateVariant::List, TemplateStruct::set(), TemplateVariant::String, TemplateListIntf::ConstIterator::toFirst(), TemplateVariant::toList(), TemplateListIntf::ConstIterator::toNext(), TemplateVariant::toString(), TemplateVariant::toStruct(), TemplateVariant::type(), and FilterAlphaIndex::ListElem::value.
determineSortKey()
static uint FilterAlphaIndex::determineSortKey (TemplateStructIntf * s, const QCString & attribName) inline static private
Definition at line 1158 of file template.cpp.
References TemplateStructIntf::get(), getPrefixIndex(), getUtf8CodeToUpper(), and TemplateVariant::toString().
Referenced by apply().
keyToLabel()
static QCString FilterAlphaIndex::keyToLabel (uint startLetter) inline static private
Definition at line 1119 of file template.cpp.
Referenced by apply().
keyToLetter()
static QCString FilterAlphaIndex::keyToLetter (uint startLetter) inline static private
Definition at line 1115 of file template.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
src/template.cpp