Doxygen: CiteDict Class Reference
CiteDict Class Reference
Cite database access class.
#include <cite.h>
Public Member Functions
CiteDict (int size)
Create the database, with an expected maximum of size entries.
void insert (const char *label)
Resolve references to citations.
CiteInfo * find (const char *label) const
Return the citation info for a given label.
void generatePage () const
Generate the citations page.
void clear ()
clears the database
bool isEmpty () const
return TRUE if there are no citations.
void writeLatexBibliography (FTextStream &t)
writes the latex code for the standard bibliography section to text stream t
Private Attributes
QDict< CiteInfo > m_entries
QCString m_baseFileName
Detailed Description
Cite database access class.
This class provides access do the database of bibliographic references through the bibtex backend.
Definition at line 56 of file cite.h.
Constructor & Destructor Documentation
CiteDict()
CiteDict::CiteDict (int size)
Create the database, with an expected maximum of size entries.
Definition at line 36 of file cite.cpp.
References m_entries.
Member Function Documentation
clear()
void CiteDict::clear ()
clears the database
Definition at line 103 of file cite.cpp.
References m_entries.
find()
CiteInfo * CiteDict::find (const char * label) const
Return the citation info for a given label.
Definition at line 98 of file cite.cpp.
References m_entries.
Referenced by DocAnchor::DocAnchor(), and DocCite::DocCite().
generatePage()
void CiteDict::generatePage () const
Generate the citations page.
Definition at line 114 of file cite.cpp.
References addRelatedPage(), bibTmpDir(), bibTmpFile(), Config_getBool, Config_getList, Config_getString, copyFile(), ResourceMgr::copyResource(), doc, endl(), err(), CiteConsts::fileName, ResourceMgr::instance(), isEmpty(), CiteInfo::label, m_entries, portable_system(), portable_sysTimerStop(), CiteInfo::text, theTranslator, and Translator::trCiteReferences().
Referenced by parseInput().
insert()
void CiteDict::insert (const char * label)
Resolve references to citations.
Insert a citation identified by label into the database
Definition at line 93 of file cite.cpp.
References m_entries.
isEmpty()
bool CiteDict::isEmpty () const
return TRUE if there are no citations.
Only valid after calling resolve()
Definition at line 108 of file cite.cpp.
References Config_getList, and m_entries.
Referenced by generatePage(), writeLatexMakefile(), and writeMakeBat().
writeLatexBibliography()
void CiteDict::writeLatexBibliography (FTextStream & t)
writes the latex code for the standard bibliography section to text stream t
Definition at line 41 of file cite.cpp.
References bibTmpFile(), Config_getBool, Config_getList, Config_getString, m_entries, theTranslator, and Translator::trCiteReferences().
Referenced by writeDefaultFooter().
Member Data Documentation
m_baseFileName
QCString CiteDict::m_baseFileName private
Definition at line 95 of file cite.h.
m_entries
QDict<CiteInfo> CiteDict::m_entries private
Definition at line 93 of file cite.h.
Referenced by CiteDict(), clear(), find(), generatePage(), insert(), isEmpty(), and writeLatexBibliography().
The documentation for this class was generated from the following files:
src/cite.h
src/cite.cpp