Doxygen: ExprAst Class Reference
ExprAst Class Reference
Base class for all nodes in the abstract syntax tree of an expression.
Public Member Functions
virtual ~ExprAst ()
virtual TemplateVariant resolve (TemplateContext *)
Detailed Description
Base class for all nodes in the abstract syntax tree of an expression.
Definition at line 1432 of file template.cpp.
Constructor & Destructor Documentation
~ExprAst()
virtual ExprAst::~ExprAst () inline virtual
Definition at line 1435 of file template.cpp.
Member Function Documentation
resolve()
virtual TemplateVariant ExprAst::resolve (TemplateContext *) inline virtual
Reimplemented in ExprAstBinary, ExprAstUnary, ExprAstNegate, ExprAstLiteral, ExprAstFilterAppl, ExprAstFunctionVariable, ExprAstVariable, and ExprAstNumber.
Definition at line 1436 of file template.cpp.
Referenced by ExprAstFilter::apply(), TemplateNodeVariable::render(), TemplateNodeIf::render(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeExtend::render(), TemplateNodeInclude::render(), TemplateNodeCreate::render(), TemplateNodeTree::render(), TemplateNodeIndexEntry::render(), TemplateNodeWith::render(), TemplateNodeSet::render(), TemplateNodeMarkers::render(), TemplateNodeResource::render(), TemplateNodeEncoding::render(), ExprAstFunctionVariable::resolve(), ExprAstFilterAppl::resolve(), ExprAstNegate::resolve(), ExprAstUnary::resolve(), and ExprAstBinary::resolve().
The documentation for this class was generated from the following file:
src/template.cpp