Doxygen: TextGeneratorIntf Class Reference
TextGeneratorIntf Class Reference abstract
Abstract interface for a hyperlinked text fragment.
#include <util.h>
Public Member Functions
virtual ~TextGeneratorIntf ()
virtual void writeString (const char *, bool) const =0
virtual void writeBreak (int indent) const =0
virtual void writeLink (const char *extRef, const char *file, const char *anchor, const char *text) const =0
Detailed Description
Abstract interface for a hyperlinked text fragment.
Definition at line 65 of file util.h.
Constructor & Destructor Documentation
~TextGeneratorIntf()
virtual TextGeneratorIntf::~TextGeneratorIntf () inline virtual
Definition at line 68 of file util.h.
Member Function Documentation
writeBreak()
virtual void TextGeneratorIntf::writeBreak (int indent) const pure virtual
Implemented in TextGeneratorLatex, TextGeneratorHtml, TextGeneratorXMLImpl, TextGeneratorDocbookImpl, and TextGeneratorOLImpl.
Referenced by linkifyText().
writeLink()
virtual void TextGeneratorIntf::writeLink (const char * extRef, const char * file, const char * anchor, const char * text) const pure virtual
Implemented in TextGeneratorLatex, TextGeneratorHtml, TextGeneratorXMLImpl, TextGeneratorDocbookImpl, and TextGeneratorOLImpl.
Referenced by linkifyText().
writeString()
virtual void TextGeneratorIntf::writeString (const char * , bool) const pure virtual
Implemented in TextGeneratorLatex, TextGeneratorHtml, TextGeneratorXMLImpl, TextGeneratorDocbookImpl, and TextGeneratorOLImpl.
Referenced by linkifyText().
The documentation for this class was generated from the following file:
src/util.h