Doxygen: DirContext::Private Class Reference
DirContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (DirDef *dd)
virtual ~Private ()
TemplateVariant get (const char *n) const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant dirName () const
TemplateVariant dirs () const
TemplateVariant files () const
TemplateVariant hasDetails () const
TemplateVariant compoundType () const
TemplateVariant relPath () const
DotDirDeps * getDirDepsGraph () const
TemplateVariant hasDirGraph () const
TemplateVariant dirGraph () const
Public Member Functions inherited from DefinitionContext< DirContext::Private >
DefinitionContext (Definition *d)
void addBaseProperties (PropertyMapper< DirContext::Private > &inst)
TemplateVariant fileName () const
TemplateVariant anchor () const
TemplateVariant sourceFileName () const
TemplateVariant isLinkable () const
TemplateVariant isLinkableInProject () const
TemplateVariant name () const
TemplateVariant bareName () const
QCString relPathAsString () const
TemplateVariant details () const
TemplateVariant brief () const
TemplateVariant inbodyDocs () const
TemplateVariant dynSectionId () const
TemplateVariant language () const
TemplateVariant compoundKind () const
TemplateVariant sourceDef () const
void fillPath (Definition *def, TemplateList *list) const
TemplateVariant navigationPath () const
TemplateVariant isReference () const
TemplateVariant externalReference () const
Private Member Functions
Cachable & getCache () const
Private Attributes
DirDef * m_dirDef
Static Private Attributes
static PropertyMapper< DirContext::Private > s_inst
Detailed Description
Definition at line 3384 of file context.cpp.
Constructor & Destructor Documentation
Private()
DirContext::Private::Private (DirDef * dd) inline
Definition at line 3387 of file context.cpp.
References DefinitionContext< DirContext::Private >::addBaseProperties(), PropertyMapper< T >::addProperty(), compoundType(), Definition::cookie(), dirGraph(), dirName(), dirs(), files(), hasDetails(), hasDirGraph(), highlight(), Config::init(), s_inst, Definition::setCookie(), subHighlight(), and title().
~Private()
virtual DirContext::Private::~Private () inline virtual
Definition at line 3407 of file context.cpp.
Member Function Documentation
compoundType()
TemplateVariant DirContext::Private::compoundType () const inline
Definition at line 3469 of file context.cpp.
References theTranslator, and Translator::trDir().
Referenced by Private().
dirGraph()
TemplateVariant DirContext::Private::dirGraph () const inline
Definition at line 3498 of file context.cpp.
References Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextGlobals::dynSectionId, EOF_Html, EOF_LaTeX, err(), g_globals, getDirDepsGraph(), DirDef::getOutputFileBase(), GOF_BITMAP, GOF_EPS, Doxygen::htmlFileExtension, m_dirDef, ContextGlobals::outputDir, ContextGlobals::outputFormat, portable_pathSeparator(), DefinitionContext< DirContext::Private >::relPathAsString(), and DotDirDeps::writeGraph().
Referenced by hasDirGraph(), and Private().
dirName()
TemplateVariant DirContext::Private::dirName () const inline
Definition at line 3424 of file context.cpp.
References m_dirDef, and DirDef::shortName().
Referenced by Private().
dirs()
TemplateVariant DirContext::Private::dirs () const inline
Definition at line 3428 of file context.cpp.
References TemplateList::alloc(), TemplateList::append(), DirContext::DirContext(), DirContext::Private::Cachable::dirs, SharedPtr< T >::get(), getCache(), m_dirDef, SharedPtr< T >::reset(), and DirDef::subDirs().
Referenced by Private().
files()
TemplateVariant DirContext::Private::files () const inline
Definition at line 3445 of file context.cpp.
References FileContext::alloc(), TemplateList::alloc(), TemplateList::append(), DirContext::Private::Cachable::files, SharedPtr< T >::get(), getCache(), DirDef::getFiles(), m_dirDef, and SharedPtr< T >::reset().
Referenced by Private().
get()
TemplateVariant DirContext::Private::get (const char * n) const inline
Definition at line 3408 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by DirContext::get().
getCache()
Cachable& DirContext::Private::getCache () const inline private
Definition at line 3552 of file context.cpp.
References Definition::cookie().
Referenced by dirs(), files(), and getDirDepsGraph().
getDirDepsGraph()
DotDirDeps* DirContext::Private::getDirDepsGraph () const inline
Definition at line 3477 of file context.cpp.
References DirContext::Private::Cachable::dirDepsGraph, ScopedPtr< T >::get(), getCache(), m_dirDef, and ScopedPtr< T >::reset().
Referenced by dirGraph(), and hasDirGraph().
hasDetails()
TemplateVariant DirContext::Private::hasDetails () const inline
Definition at line 3465 of file context.cpp.
References DirDef::hasDetailedDescription(), and m_dirDef.
Referenced by Private().
hasDirGraph()
TemplateVariant DirContext::Private::hasDirGraph () const inline
Definition at line 3486 of file context.cpp.
References Config_getBool, dirGraph(), getDirDepsGraph(), and DotDirDeps::isTrivial().
Referenced by Private().
highlight()
TemplateVariant DirContext::Private::highlight () const inline
Definition at line 3416 of file context.cpp.
Referenced by Private().
relPath()
TemplateVariant DirContext::Private::relPath () const inline virtual
Reimplemented from DefinitionContext< DirContext::Private >.
Definition at line 3473 of file context.cpp.
subHighlight()
TemplateVariant DirContext::Private::subHighlight () const inline
Definition at line 3420 of file context.cpp.
Referenced by Private().
title()
TemplateVariant DirContext::Private::title () const inline
Definition at line 3412 of file context.cpp.
References m_dirDef, and DirDef::shortTitle().
Referenced by Private().
Member Data Documentation
m_dirDef
DirDef* DirContext::Private::m_dirDef private
Definition at line 3544 of file context.cpp.
Referenced by dirGraph(), dirName(), dirs(), files(), getDirDepsGraph(), hasDetails(), and title().
s_inst
PropertyMapper< DirContext::Private > DirContext::Private::s_inst static private
Definition at line 3558 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp