Doxygen: FileDef Class Reference
FileDef Class Reference
A model of a file symbol.
#include <filedef.h>
Public Member Functions
FileDef (const char *p, const char *n, const char *ref=0, const char *dn=0)
~FileDef ()
DefType definitionType () const
QCString name () const
QCString displayName (bool=TRUE) const
QCString fileName () const
QCString getOutputFileBase () const
QCString anchor () const
QCString getSourceFileBase () const
QCString includeName () const
QCString includeDependencyGraphFileName () const
QCString includedByDependencyGraphFileName () const
QCString absFilePath () const
const QCString & docName () const
bool isSource () const
bool isDocumentationFile () const
Definition * getSourceDefinition (int lineNr) const
MemberDef * getSourceMember (int lineNr) const
QCString getPath () const
QCString getVersion () const
bool isLinkableInProject () const
bool isLinkable () const
bool isIncluded (const QCString &name) const
PackageDef * packageDef () const
DirDef * getDirDef () const
NamespaceSDict * getUsedNamespaces () const
SDict< Definition > * getUsedClasses () const
QList< IncludeInfo > * includeFileList () const
QList< IncludeInfo > * includedByFileList () const
void getAllIncludeFilesRecursively (QStrList &incFiles) const
MemberList * getMemberList (MemberListType lt) const
const QList< MemberList > & getMemberLists () const
MemberGroupSDict * getMemberGroupSDict () const
NamespaceSDict * getNamespaceSDict () const
ClassSDict * getClassSDict () const
QCString title () const
bool hasDetailedDescription () const
QCString fileVersion () const
bool subGrouping () const
void addSourceRef (int line, Definition *d, MemberDef *md)
void writeDocumentation (OutputList &ol)
void writeMemberPages (OutputList &ol)
void writeQuickMemberLinks (OutputList &ol, MemberDef *currentMd) const
void writeSummaryLinks (OutputList &ol)
void writeTagFile (FTextStream &t)
void startParsing ()
void writeSource (OutputList &ol, bool sameTu, QStrList &filesInSameTu)
void parseSource (bool sameTu, QStrList &filesInSameTu)
void finishParsing ()
void setDiskName (const QCString &name)
void insertMember (MemberDef *md)
void insertClass (ClassDef *cd)
void insertNamespace (NamespaceDef *nd)
void computeAnchors ()
void setPackageDef (PackageDef *pd)
void setDirDef (DirDef *dd)
void addUsingDirective (NamespaceDef *nd)
void addUsingDeclaration (Definition *def)
void combineUsingRelations ()
bool generateSourceFile () const
void sortMemberLists ()
void addIncludeDependency (FileDef *fd, const char *incName, bool local, bool imported, bool indirect)
void addIncludedByDependency (FileDef *fd, const char *incName, bool local, bool imported)
void addMembersToMemberGroup ()
void distributeMemberGroupDocumentation ()
void findSectionsInDocumentation ()
void addIncludedUsingDirectives ()
void addListReferences ()
Public Member Functions inherited from Definition
Definition (const char *defFileName, int defLine, int defColumn, const char *name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~Definition ()
const QCString & name () const
QCString localName () const
virtual QCString qualifiedName () const
QCString symbolName () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
int docLine () const
QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
bool isHidden () const
bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
QCString externalReference (const QCString &relPath) const
int getStartBodyLine () const
int getEndBodyLine () const
FileDef * getBodyDef () const
SrcLangExt getLanguage () const
Returns the programming language this definition was written in.
GroupList * partOfGroups () const
bool isLinkableViaGroup () const
QList< ListItemInfo > * xrefListItems () const
virtual Definition * findInnerCompound (const char *name)
virtual Definition * getOuterScope () const
MemberSDict * getReferencesMembers () const
MemberSDict * getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
returns TRUE if this class has a brief description
QCString id () const
virtual void setName (const char *name)
void setId (const char *name)
virtual void setDocumentation (const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const char *b, const char *briefFile, int briefLine)
virtual void setInbodyDocumentation (const char *d, const char *docFile, int docLine)
void setReference (const char *r)
void addSectionsToDefinition (QList< SectionInfo > *anchorList)
void setBodySegment (int bls, int ble)
void setBodyDef (FileDef *fd)
void addSourceReferencedBy (MemberDef *d)
void addSourceReferences (MemberDef *d)
void setRefItems (const QList< ListItemInfo > *sli)
void mergeRefItems (Definition *d)
virtual void addInnerCompound (Definition *d)
virtual void setOuterScope (Definition *d)
virtual void setHidden (bool b)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const char *scopeName)
void writeInlineCode (OutputList &ol, const char *scopeName)
void writeSourceRefs (OutputList &ol, const char *scopeName)
void writeSourceReffedBy (OutputList &ol, const char *scopeName)
void makePartOfGroup (GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
QCString pathFragment () const
void writeDocAnchorsToTagFile (FTextStream &)
void setLocalName (const QCString name)
void addSectionsToIndex ()
void writeToc (OutputList &ol)
void setCookie (Cookie *cookie)
Cookie * cookie () const
Public Member Functions inherited from DefinitionIntf
DefinitionIntf ()
virtual ~DefinitionIntf ()
Public Attributes
bool visited
Protected Member Functions
void acquireFileVersion ()
Retrieves the file version from version control system.
Protected Member Functions inherited from Definition
Definition (const Definition &d)
Private Member Functions
MemberList * createMemberList (MemberListType lt)
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void writeIncludeFiles (OutputList &ol)
void writeIncludeGraph (OutputList &ol)
void writeIncludedByGraph (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void writeSourceLink (OutputList &ol)
void writeNamespaceDeclarations (OutputList &ol, const QCString &title, bool isConstantGroup)
void writeClassDeclarations (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
Private Attributes
QDict< IncludeInfo > * m_includeDict
QList< IncludeInfo > * m_includeList
QDict< IncludeInfo > * m_includedByDict
QList< IncludeInfo > * m_includedByList
NamespaceSDict * m_usingDirList
SDict< Definition > * m_usingDeclList
QCString m_path
QCString m_filePath
QCString m_inclDepFileName
QCString m_inclByDepFileName
QCString m_outputDiskName
QCString m_fileName
QCString m_docname
QIntDict< Definition > * m_srcDefDict
QIntDict< MemberDef > * m_srcMemberDict
bool m_isSource
QCString m_fileVersion
PackageDef * m_package
DirDef * m_dir
QList< MemberList > m_memberLists
MemberGroupSDict * m_memberGroupSDict
NamespaceSDict * m_namespaceSDict
ClassSDict * m_classSDict
bool m_subGrouping
Additional Inherited Members
Public Types inherited from DefinitionIntf
enum DefType {
TypeClass = 0, TypeFile = 1, TypeNamespace = 2, TypeMember = 3,
TypeGroup = 4, TypePackage = 5, TypePage = 6, TypeDir = 7,
TypeSymbolList = 8
}
Detailed Description
A model of a file symbol.
An object of this class contains all file information that is gathered. This includes the members and compounds defined in the file.
The member writeDocumentation() can be used to generate the page of documentation to HTML and LaTeX.
Definition at line 64 of file filedef.h.
Constructor & Destructor Documentation
FileDef()
FileDef::FileDef (const char * p, const char * nm, const char * lref = 0, const char * dn = 0)
create a new file definition, where p is the file path, nm the file name, and lref is an HTML anchor name if the file was read from a tag file or 0 otherwise
Definition at line 78 of file filedef.cpp.
References acquireFileVersion(), Config_getBool, getLanguageFromFileName(), guessSection(), m_classSDict, m_dir, m_docname, m_fileName, m_filePath, m_includedByDict, m_includedByList, m_includeDict, m_includeList, m_isSource, m_memberGroupSDict, m_namespaceSDict, m_package, m_path, m_srcDefDict, m_srcMemberDict, m_subGrouping, m_usingDeclList, m_usingDirList, name(), setDiskName(), Definition::setLanguage(), Definition::setReference(), Entry::SOURCE_SEC, and stripFromPath().
~FileDef()
FileDef::~FileDef ()
destroy the file definition
Definition at line 112 of file filedef.cpp.
References m_classSDict, m_includedByDict, m_includedByList, m_includeDict, m_includeList, m_memberGroupSDict, m_namespaceSDict, m_srcDefDict, m_srcMemberDict, m_usingDeclList, and m_usingDirList.
Member Function Documentation
absFilePath()
QCString FileDef::absFilePath () const inline
Returns the absolute path including the file name.
Definition at line 95 of file filedef.h.
References m_filePath.
Referenced by addIncludedByDependency(), addIncludeDependency(), addIncludeFile(), addVariableToFile(), buildFunctionList(), DotInclDepGraph::buildGraph(), VhdlDocGen::createFlowChart(), DotInclDepGraph::DotInclDepGraph(), findAndCopyImage(), findDefineDocumentation(), generateFileSources(), generateXMLForClass(), generateXMLForMember(), getResolvedClassRec(), mergeFileDef(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), parseCode(), parseSource(), readTextFileByName(), showFileDefMatches(), MemberContext::Private::sourceCode(), DocbookDocVisitor::visitPost(), writeDocbookCodeBlock(), Definition::writeInlineCode(), writeSource(), and writeXMLCodeBlock().
acquireFileVersion()
void FileDef::acquireFileVersion () protected
Retrieves the file version from version control system.
Definition at line 1760 of file filedef.cpp.
References Config_getString, err(), Debug::ExtCmd, m_filePath, m_fileVersion, msg(), portable_pclose(), portable_popen(), and Debug::print().
Referenced by FileDef().
addIncludedByDependency()
void FileDef::addIncludedByDependency (FileDef * fd, const char * incName, bool local, bool imported)
Definition at line 1389 of file filedef.cpp.
References absFilePath(), IncludeInfo::fileDef, IncludeInfo::imported, IncludeInfo::includeName, IncludeInfo::indirect, IncludeInfo::local, m_includedByDict, and m_includedByList.
addIncludeDependency()
void FileDef::addIncludeDependency (FileDef * fd, const char * incName, bool local, bool imported, bool indirect)
Definition at line 1292 of file filedef.cpp.
References absFilePath(), IncludeInfo::fileDef, IncludeInfo::imported, IncludeInfo::includeName, IncludeInfo::indirect, IncludeInfo::local, m_includeDict, and m_includeList.
Referenced by TagFileParser::addIncludes().
addIncludedUsingDirectives()
void FileDef::addIncludedUsingDirectives ()
Definition at line 1316 of file filedef.cpp.
References addIncludedUsingDirectives(), IncludeInfo::fileDef, SDict< T >::find(), SDict< NamespaceDef >::Iterator, m_includeList, m_usingDeclList, m_usingDirList, SDict< T >::prepend(), Definition::qualifiedName(), and visited.
Referenced by addIncludedUsingDirectives(), and findIncludedUsingDirectives().
addListReferences()
void FileDef::addListReferences ()
Definition at line 1433 of file filedef.cpp.
References MemberList::addListReferences(), MemberGroup::addListReferences(), addRefItem(), getOutputFileBase(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_memberGroupSDict, m_memberLists, MemberListType_documentationLists, name(), theTranslator, Translator::trFile(), and Definition::xrefListItems().
Referenced by addListReferences().
addMembersToMemberGroup()
void FileDef::addMembersToMemberGroup ()
Definition at line 1094 of file filedef.cpp.
References MemberGroup::addToDeclarationSection(), MemberGroup::allMembersInSameSection(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_memberGroupSDict, m_memberLists, m_subGrouping, and MemberListType_declarationLists.
Referenced by addMembersToMemberGroup().
addMemberToList()
void FileDef::addMemberToList (MemberListType lt, MemberDef * md) private
Definition at line 1835 of file filedef.cpp.
References MemberList::append(), Config_getBool, createMemberList(), MemberList::inSort(), MemberList::listType(), MemberListType_declarationLists, MemberListType_documentationLists, MemberList::needsSorting(), MemberList::setInFile(), MemberList::setNeedsSorting(), and MemberDef::setSectionList().
Referenced by insertMember().
addSourceRef()
void FileDef::addSourceRef (int line, Definition * d, MemberDef * md)
Definition at line 1224 of file filedef.cpp.
References m_srcDefDict, and m_srcMemberDict.
Referenced by addSourceReferences().
addUsingDeclaration()
void FileDef::addUsingDeclaration (Definition * def)
Definition at line 1280 of file filedef.cpp.
References SDict< T >::append(), SDict< T >::find(), m_usingDeclList, and Definition::qualifiedName().
Referenced by combineUsingRelations(), and findUsingDeclarations().
addUsingDirective()
void FileDef::addUsingDirective (NamespaceDef * nd)
Definition at line 1261 of file filedef.cpp.
References SDict< T >::append(), SDict< T >::find(), m_usingDirList, and Definition::qualifiedName().
Referenced by combineUsingRelations().
anchor()
QCString FileDef::anchor () const inline virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 83 of file filedef.h.
Referenced by MemberDef::_writeGroupInclude(), and writeDocumentation().
combineUsingRelations()
void FileDef::combineUsingRelations ()
Definition at line 1711 of file filedef.cpp.
References addUsingDeclaration(), addUsingDirective(), NamespaceDef::combineUsingRelations(), NamespaceDef::getUsedClasses(), NamespaceDef::getUsedNamespaces(), SDict< NamespaceDef >::Iterator, m_usingDirList, and visited.
Referenced by combineUsingRelations().
computeAnchors()
void FileDef::computeAnchors ()
Compute the HTML anchor names for all members in the class
Definition at line 144 of file filedef.cpp.
References getMemberList(), MemberListType_allMembersList, and setAnchors().
Referenced by computeMemberReferences().
createMemberList()
MemberList * FileDef::createMemberList (MemberListType lt) private
Definition at line 1817 of file filedef.cpp.
References MemberList::listType(), and m_memberLists.
Referenced by addMemberToList().
definitionType()
DefType FileDef::definitionType () const inline virtual
Use this for dynamic inspection of the type of the derived class
Implements DefinitionIntf.
Definition at line 74 of file filedef.h.
References DefinitionIntf::TypeFile.
displayName()
QCString FileDef::displayName (bool includeScope = TRUE) const inline virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 78 of file filedef.h.
References name().
Referenced by writeDirHierarchy(), writeDirTreeNode(), and MemberDef::writeDocumentation().
distributeMemberGroupDocumentation()
void FileDef::distributeMemberGroupDocumentation ()
Definition at line 150 of file filedef.cpp.
References MemberGroup::distributeMemberGroupDocumentation(), SIntDict< MemberGroup >::Iterator, and m_memberGroupSDict.
Referenced by distributeMemberGroupDocumentation().
docName()
const QCString& FileDef::docName () const inline
Returns the name as it is used in the documentation
Definition at line 98 of file filedef.h.
References m_docname.
Referenced by MemberDef::_writeGroupInclude(), DotInclDepGraph::DotInclDepGraph(), generateDocbookForClass(), generateFileDocs(), generateFileSources(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), and ClassDef::writeIncludeFiles().
endMemberDeclarations()
void FileDef::endMemberDeclarations (OutputList & ol) private
Definition at line 580 of file filedef.cpp.
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDocumentation()
void FileDef::endMemberDocumentation (OutputList & ol) private
Definition at line 594 of file filedef.cpp.
References Config_getBool, OutputList::enable(), OutputGenerator::Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
fileName()
QCString FileDef::fileName () const inline
Definition at line 79 of file filedef.h.
References m_fileName.
Referenced by addInstance(), and FileName::compareValues().
fileVersion()
QCString FileDef::fileVersion () const
Definition at line 1943 of file filedef.cpp.
References m_fileVersion.
Referenced by FileContext::Private::version().
findSectionsInDocumentation()
void FileDef::findSectionsInDocumentation ()
Definition at line 164 of file filedef.cpp.
References Definition::docFile(), docFindSections(), Definition::documentation(), MemberGroup::findSectionsInDocumentation(), MemberList::findSectionsInDocumentation(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_memberGroupSDict, m_memberLists, and MemberListType_declarationLists.
Referenced by findSectionsInDocumentation().
finishParsing()
void FileDef::finishParsing ()
Definition at line 1089 of file filedef.cpp.
References ClangParser::finish(), and ClangParser::instance().
Referenced by generateFileSources().
generateSourceFile()
bool FileDef::generateSourceFile () const
Definition at line 1419 of file filedef.cpp.
References Config_getBool, guessSection(), Entry::HEADER_SEC, Definition::isReference(), and name().
Referenced by FileListContext::Private::addFiles(), addIncludeFile(), addSourceReferences(), DotInclDepGraph::buildGraph(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), fileVisibleInIndex(), generateFileSources(), FileContext::Private::hasSourceFile(), ClassDef::showUsedFiles(), FileContext::Private::sources(), DirDef::writeFileList(), writeIncludeFiles(), writeSingleFileIndex(), writeSource(), and writeSourceLink().
getAllIncludeFilesRecursively()
void FileDef::getAllIncludeFilesRecursively (QStrList & incFiles) const
Definition at line 1932 of file filedef.cpp.
Referenced by generateFileSources(), and parseFile().
getClassSDict()
ClassSDict* FileDef::getClassSDict () const inline
Definition at line 133 of file filedef.h.
References m_classSDict.
Referenced by FileContext::Private::classes(), generateDocbookForFile(), generateXMLForFile(), and FileContext::Private::inlineClasses().
getDirDef()
DirDef* FileDef::getDirDef () const inline
Definition at line 120 of file filedef.h.
References m_dir.
Referenced by NestingContext::Private::addFiles(), DirDef::computeDependencies(), writeDirHierarchy(), writeDocumentation(), writePartialFilePath(), and writeSource().
getMemberGroupSDict()
MemberGroupSDict* FileDef::getMemberGroupSDict () const inline
Definition at line 131 of file filedef.h.
References m_memberGroupSDict.
Referenced by generateDocbookForFile(), generateXMLForFile(), and FileContext::Private::memberGroups().
getMemberList()
MemberList * FileDef::getMemberList (MemberListType lt) const
Definition at line 1867 of file filedef.cpp.
References MemberList::listType(), and m_memberLists.
Referenced by computeAnchors(), generateDEFForFile(), PerlModGenerator::generatePerlModForFile(), FileContext::Private::getMemberList(), insertMember(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), writeQuickMemberLinks(), writeSummaryLinks(), and writeTagFile().
getMemberLists()
const QList<MemberList>& FileDef::getMemberLists () const inline
Definition at line 128 of file filedef.h.
References m_memberLists.
Referenced by generateDocbookForFile(), and generateXMLForFile().
getNamespaceSDict()
NamespaceSDict* FileDef::getNamespaceSDict () const inline
Definition at line 132 of file filedef.h.
References m_namespaceSDict.
Referenced by FileContext::Private::constantgroups(), generateDocbookForFile(), generateXMLForFile(), and FileContext::Private::namespaces().
getOutputFileBase()
QCString FileDef::getOutputFileBase () const virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 1806 of file filedef.cpp.
References m_outputDiskName.
Referenced by MemberDef::_writeGroupInclude(), UsedDir::addFileDep(), TagFileParser::addIncludes(), addListReferences(), DirDef::addUsesDependency(), DotInclDepGraph::buildGraph(), DotInclDepGraph::DotInclDepGraph(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateDEFForFile(), generateDEFForMember(), generateDocbookForClass(), generateDocbookForFile(), generateFileRef(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), generateXMLForClass(), generateXMLForFile(), MemberDef::getOutputFileBase(), ClassDef::getOutputFileBase(), FileContext::Private::includedByGraph(), FileContext::Private::includeGraph(), node2URL(), ClassDef::showUsedFiles(), writeDirHierarchy(), writeDirTreeNode(), writeDocumentation(), DirDef::writeFileList(), GroupDef::writeFiles(), writeIncludeFiles(), writeInnerFiles(), writeMemberReference(), writePartialFilePath(), writeSingleFileIndex(), writeSource(), and writeTagFile().
getPath()
QCString FileDef::getPath () const inline
Returns the absolute path of this file.
Definition at line 109 of file filedef.h.
References m_path.
Referenced by TagFileParser::addIncludes(), buildDirectories(), findFileDef(), FileName::generateDiskNames(), showFileDefMatches(), ClassDef::showUsedFiles(), writeFileIndex(), writeSingleFileIndex(), and writeTagFile().
getSourceDefinition()
Definition * FileDef::getSourceDefinition (int lineNr) const
Definition at line 1238 of file filedef.cpp.
References m_srcDefDict.
getSourceFileBase()
QCString FileDef::getSourceFileBase () const virtual
Returns the name of the source listing of this definition.
Reimplemented from Definition.
Definition at line 1794 of file filedef.cpp.
References m_filePath, m_outputDiskName, Htags::path2URL(), and Htags::useHtags.
Referenced by Definition::_writeSourceRefList(), DotInclDepGraph::buildGraph(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), FTVHelp::generateTree(), Definition::getSourceFileBase(), includeName(), node2URL(), ClassDef::showUsedFiles(), writeDetailedDescription(), writeDirHierarchy(), writeDirTreeNode(), and writeSource().
getSourceMember()
MemberDef * FileDef::getSourceMember (int lineNr) const
Definition at line 1249 of file filedef.cpp.
References m_srcMemberDict.
getUsedClasses()
SDict<Definition>* FileDef::getUsedClasses () const inline
Definition at line 122 of file filedef.h.
References m_usingDeclList.
Referenced by getResolvedClassRec(), and isAccessibleFrom().
getUsedNamespaces()
NamespaceSDict * FileDef::getUsedNamespaces () const
Definition at line 1274 of file filedef.cpp.
References m_usingDirList.
Referenced by findGlobalMember(), findMember(), findScopeFromQualifiedName(), getResolvedClassRec(), getResolvedSymbol(), isAccessibleFrom(), and isAccessibleFromWithExpScope().
getVersion()
QCString FileDef::getVersion () const inline
Returns version of this file.
Definition at line 112 of file filedef.h.
References m_fileVersion.
Referenced by format_warn(), ClassDef::showUsedFiles(), and FileContext::Private::versionInfo().
hasDetailedDescription()
bool FileDef::hasDetailedDescription () const
Definition at line 188 of file filedef.cpp.
References Definition::briefDescription(), Config_getBool, Definition::documentation(), Definition::getBodyDef(), and Definition::getStartBodyLine().
Referenced by FileContext::Private::hasDetails(), and writeDetailedDescription().
includedByDependencyGraphFileName()
QCString FileDef::includedByDependencyGraphFileName () const
Definition at line 1953 of file filedef.cpp.
References m_inclByDepFileName.
Referenced by DotInclDepGraph::DotInclDepGraph().
includedByFileList()
QList<IncludeInfo>* FileDef::includedByFileList () const inline
Definition at line 124 of file filedef.h.
References m_includedByList.
Referenced by DotInclDepGraph::buildGraph(), PerlModGenerator::generatePerlModForFile(), and generateXMLForFile().
includeDependencyGraphFileName()
QCString FileDef::includeDependencyGraphFileName () const
Definition at line 1948 of file filedef.cpp.
References m_inclDepFileName.
Referenced by DotInclDepGraph::DotInclDepGraph().
includeFileList()
QList<IncludeInfo>* FileDef::includeFileList () const inline
Definition at line 123 of file filedef.h.
References m_includeList.
Referenced by DotInclDepGraph::buildGraph(), DirDef::computeDependencies(), generateDocbookForFile(), PerlModGenerator::generatePerlModForFile(), generateXMLForFile(), getAllIncludeFilesRecursively(), and FileContext::Private::includeList().
includeName()
QCString FileDef::includeName () const
Returns the name of the verbatim copy of this file (if any).
Definition at line 1812 of file filedef.cpp.
References getSourceFileBase().
Referenced by DirDef::writeFileList(), writeIncludeFiles(), ClassDef::writeIncludeFiles(), writeSingleFileIndex(), and writeSourceLink().
insertClass()
void FileDef::insertClass (ClassDef * cd)
Adds compound definition cd to the list of all compounds of this file
Definition at line 1177 of file filedef.cpp.
References SDict< T >::append(), Config_getBool, SDict< T >::inSort(), Definition::isHidden(), m_classSDict, and Definition::name().
Referenced by addClassToContext(), and createTagLessInstance().
insertMember()
void FileDef::insertMember (MemberDef * md)
Adds member definition md to the list of all members of this file
Definition at line 1123 of file filedef.cpp.
References addMemberToList(), MemberList::append(), err(), MemberList::findRef(), MemberDef::getClassDef(), getMemberList(), Definition::isHidden(), m_memberLists, MemberListType_allMembersList, MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decFuncMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docEnumMembers, MemberListType_docFuncMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Function, MemberType_Property, MemberType_Typedef, MemberType_Variable, name(), and Definition::name().
Referenced by addVariableToFile(), buildFunctionList(), and findEnums().
insertNamespace()
void FileDef::insertNamespace (NamespaceDef * nd)
Adds namespace definition nd to the list of all compounds of this file
Definition at line 1195 of file filedef.cpp.
References SDict< T >::append(), Config_getBool, SDict< T >::find(), SDict< T >::inSort(), Definition::isHidden(), m_namespaceSDict, and Definition::name().
Referenced by buildNamespaceList().
isDocumentationFile()
bool FileDef::isDocumentationFile () const
Definition at line 1751 of file filedef.cpp.
References name().
Referenced by FileListContext::Private::addFiles(), buildDirectories(), fileVisibleInIndex(), writeSingleFileIndex(), and writeSource().
isIncluded()
bool FileDef::isIncluded (const QCString & name) const
Definition at line 1413 of file filedef.cpp.
References m_includeDict.
isLinkable()
bool FileDef::isLinkable () const inline virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 116 of file filedef.h.
References isLinkableInProject(), and Definition::isReference().
Referenced by MemberDef::_writeGroupInclude(), addMemberToSearchIndex(), DotInclDepGraph::buildGraph(), DirDef::computeDependencies(), createJavascriptSearchIndex(), fileVisibleInIndex(), findMembersWithSpecificName(), generateFileRef(), getDefs(), resolveLink(), ClassDef::showUsedFiles(), DirDef::writeFileList(), writeIncludeFiles(), writePartialFilePath(), writeSource(), and writeTagFile().
isLinkableInProject()
bool FileDef::isLinkableInProject () const virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 1905 of file filedef.cpp.
References Config_getBool, Definition::hasDocumentation(), Definition::isLinkableViaGroup(), and Definition::isReference().
Referenced by MemberDef::_computeLinkableInProject(), addFileMemberNameToIndex(), FileListContext::Private::addFiles(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), fileVisibleInIndex(), generateFileDocs(), GlobalsIndexContext::Private::getMembersFiltered(), ClassDef::isEmbeddedInOuterScope(), isLinkable(), RTFGenerator::startIndexSection(), LatexGenerator::startIndexSection(), writeSingleFileIndex(), GroupDef::writeTagFile(), and writeTagFile().
isSource()
bool FileDef::isSource () const inline
Returns TRUE if this file is a source file.
Definition at line 101 of file filedef.h.
References m_isSource.
Referenced by generateFileSources(), and parseFiles().
name()
QCString FileDef::name () const
Returns the unique file name (this may include part of the path).
Definition at line 1216 of file filedef.cpp.
References Config_getBool, m_fileName, and Definition::name().
Referenced by addIncludeFile(), DocSets::addIndexItem(), addListReferences(), DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), MemberName::compareValues(), MemberNameInfo::compareValues(), FilePairDict::compareValues(), FileList::compareValues(), createJavascriptSearchIndex(), displayName(), FileDef(), findAndCopyImage(), VhdlDocGen::findConstraintFile(), findUsingDeclarations(), generateDEFForFile(), generateDocbook(), generateDocbookForFile(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), generateSourceFile(), generateXML(), generateXMLForFile(), getDefs(), insertMember(), isDocumentationFile(), isVarWithConstructor(), setDiskName(), ClassDef::showUsedFiles(), title(), writeDetailedDescription(), writeDirHierarchy(), writeDirTreeNode(), writeDocumentation(), writeFileLinkForMember(), DirDef::writeFileList(), GroupDef::writeFiles(), writeIncludedByGraph(), writeIncludeGraph(), writeInnerFiles(), writeMemberDocumentation(), writeMemberPages(), writePartialFilePath(), writeSingleFileIndex(), writeSource(), Definition::writeSourceDef(), GroupDef::writeTagFile(), DirDef::writeTagFile(), writeTagFile(), and TooltipManager::writeTooltips().
packageDef()
PackageDef* FileDef::packageDef () const inline
Definition at line 119 of file filedef.h.
References m_package.
parseSource()
void FileDef::parseSource (bool sameTu, QStrList & filesInSameTu)
Definition at line 1050 of file filedef.cpp.
References absFilePath(), Config_getBool, fileToString(), Definition::getDefFileExtension(), Definition::getLanguage(), ParserManager::getParser(), ClangParser::instance(), ParserInterface::parseCode(), Doxygen::parserManager, ParserInterface::resetCodeParserState(), SrcLangExt_Cpp, SrcLangExt_ObjC, ClangParser::start(), ClangParser::switchToFile(), and ClangParser::writeSources().
Referenced by generateFileSources().
setDirDef()
void FileDef::setDirDef (DirDef * dd) inline
Definition at line 163 of file filedef.h.
References m_dir.
Referenced by DirDef::addFile().
setDiskName()
void FileDef::setDiskName (const QCString & name)
Definition at line 127 of file filedef.cpp.
References convertNameToFile(), Definition::isReference(), m_inclByDepFileName, m_inclDepFileName, m_outputDiskName, and name().
Referenced by FileDef(), and FileName::generateDiskNames().
setPackageDef()
void FileDef::setPackageDef (PackageDef * pd) inline
Definition at line 162 of file filedef.h.
References m_package.
sortMemberLists()
void FileDef::sortMemberLists ()
Definition at line 1857 of file filedef.cpp.
References m_memberLists, MemberList::needsSorting(), MemberList::setNeedsSorting(), and MemberList::sort().
Referenced by sortMemberLists().
startMemberDeclarations()
void FileDef::startMemberDeclarations (OutputList & ol) private
Definition at line 575 of file filedef.cpp.
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDocumentation()
void FileDef::startMemberDocumentation (OutputList & ol) private
Definition at line 585 of file filedef.cpp.
References Config_getBool, OutputList::disable(), OutputGenerator::Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
startParsing()
void FileDef::startParsing ()
Definition at line 1085 of file filedef.cpp.
Referenced by generateFileSources().
subGrouping()
bool FileDef::subGrouping () const inline
Definition at line 139 of file filedef.h.
References m_subGrouping.
Referenced by FileContext::Private::memberGroups().
title()
QCString FileDef::title () const
Definition at line 1938 of file filedef.cpp.
References name(), theTranslator, and Translator::trFileReference().
Referenced by FileContext::Private::title(), writeDocumentation(), and writeSource().
writeAuthorSection()
void FileDef::writeAuthorSection (OutputList & ol) private
Definition at line 622 of file filedef.cpp.
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), and Translator::trGeneratedAutomatically().
Referenced by writeDocumentation().
writeBriefDescription()
void FileDef::writeBriefDescription (OutputList & ol) private
Definition at line 379 of file filedef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), Definition::documentation(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), Definition::hasBriefDescription(), OutputGenerator::Html, DocRoot::isEmpty(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeClassDeclarations()
void FileDef::writeClassDeclarations (OutputList & ol, const QCString & title) private
Definition at line 556 of file filedef.cpp.
References m_classSDict, and ClassSDict::writeDeclaration().
Referenced by writeDocumentation().
writeDetailedDescription()
void FileDef::writeDetailedDescription (OutputList & ol, const QCString & title) private
Definition at line 304 of file filedef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), Definition::docFile(), Definition::docLine(), Definition::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), OutputList::endParagraph(), OutputList::endTextBlock(), err(), OutputList::generateDoc(), getSourceFileBase(), hasDetailedDescription(), OutputGenerator::Html, OutputList::isEnabled(), OutputGenerator::Latex, OutputGenerator::Man, name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startGroupHeader(), OutputList::startParagraph(), OutputList::startTextBlock(), theTranslator, Translator::trDefinedInSourceFile(), OutputList::writeAnchor(), OutputList::writeObjectLink(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDocumentation()
void FileDef::writeDocumentation (OutputList & ol)
Write the documentation page for this file to the file of output generators ol.
Definition at line 677 of file filedef.cpp.
References addGroupListToTitle(), SearchIndexIntf::addWord(), anchor(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enableAll(), OutputList::endContents(), endFileWithNavPath(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endProjectNumber(), OutputList::endQuickIndices(), endTitle(), err(), LayoutDocManager::File, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, getDirDef(), Definition::getLanguage(), getMemberList(), getOutputFileBase(), LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, HLI_FileVisible, OutputGenerator::Html, LayoutDocManager::instance(), LayoutDocEntry::kind(), Definition::localName(), m_docname, m_fileVersion, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, MemberListType_allMembersList, name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), Doxygen::searchIndex, SearchIndexIntf::setCurrentDoc(), MemberList::sort(), OutputList::startContents(), startFile(), startMemberDeclarations(), startMemberDocumentation(), OutputList::startProjectNumber(), startTitle(), theTranslator, LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), title(), Translator::trFileReference(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClassDeclarations(), writeDetailedDescription(), writeIncludedByGraph(), writeIncludeFiles(), writeIncludeGraph(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeMemberPages(), writeNamespaceDeclarations(), Definition::writeNavigationPath(), and writeSourceLink().
Referenced by generateFileDocs().
writeIncludedByGraph()
void FileDef::writeIncludedByGraph (OutputList & ol) private
Definition at line 509 of file filedef.cpp.
References Config_getBool, OutputList::disable(), OutputList::enableAll(), OutputList::endInclDepGraph(), OutputList::endTextBlock(), DotInclDepGraph::isTooBig(), DotInclDepGraph::isTrivial(), OutputGenerator::Man, name(), OutputList::parseText(), OutputList::startInclDepGraph(), OutputList::startTextBlock(), theTranslator, Translator::trInclByDepGraph(), and warn_uncond().
Referenced by writeDocumentation().
writeIncludeFiles()
void FileDef::writeIncludeFiles (OutputList & ol) private
Definition at line 416 of file filedef.cpp.
References OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enableAll(), OutputList::endTextBlock(), OutputList::endTypewriter(), IncludeInfo::fileDef, generateSourceFile(), Definition::getLanguage(), getOutputFileBase(), Definition::getReference(), OutputGenerator::Html, IncludeInfo::imported, IncludeInfo::includeName, includeName(), IncludeInfo::indirect, isLinkable(), OutputList::lineBreak(), IncludeInfo::local, m_includeList, SrcLangExt_IDL, SrcLangExt_Java, OutputList::startTextBlock(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeIncludeGraph()
void FileDef::writeIncludeGraph (OutputList & ol) private
Definition at line 485 of file filedef.cpp.
References Config_getBool, OutputList::disable(), OutputList::enableAll(), OutputList::endInclDepGraph(), OutputList::endTextBlock(), DotInclDepGraph::isTooBig(), DotInclDepGraph::isTrivial(), OutputGenerator::Man, name(), OutputList::parseText(), OutputList::startInclDepGraph(), OutputList::startTextBlock(), theTranslator, Translator::trInclDepGraph(), and warn_uncond().
Referenced by writeDocumentation().
writeInlineClasses()
void FileDef::writeInlineClasses (OutputList & ol) private
Definition at line 562 of file filedef.cpp.
References OutputList::disable(), OutputList::enable(), OutputGenerator::Html, OutputList::isEnabled(), m_classSDict, and ClassSDict::writeDocumentation().
Referenced by writeDocumentation().
writeMemberDeclarations()
void FileDef::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1881 of file filedef.cpp.
References Config_getBool, getMemberList(), MemberList::writeDeclarations(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by writeDocumentation().
writeMemberDocumentation()
void FileDef::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1899 of file filedef.cpp.
References getMemberList(), name(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberGroups()
void FileDef::writeMemberGroups (OutputList & ol) private
Definition at line 603 of file filedef.cpp.
References MemberGroup::allMembersInSameSection(), MemberGroup::header(), SIntDict< MemberGroup >::Iterator, m_memberGroupSDict, m_subGrouping, SIntDict< T >::sort(), and MemberGroup::writeDeclarations().
Referenced by writeDocumentation().
writeMemberPages()
void FileDef::writeMemberPages (OutputList & ol)
Definition at line 873 of file filedef.cpp.
References OutputList::disableAllBut(), OutputGenerator::Html, MemberList::listType(), m_memberLists, MemberListType_documentationLists, name(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), and MemberList::writeDocumentationPage().
Referenced by writeDocumentation().
writeNamespaceDeclarations()
void FileDef::writeNamespaceDeclarations (OutputList & ol, const QCString & title, bool isConstantGroup) private
Definition at line 549 of file filedef.cpp.
References m_namespaceSDict, and NamespaceSDict::writeDeclaration().
Referenced by writeDocumentation().
writeQuickMemberLinks()
void FileDef::writeQuickMemberLinks (OutputList & ol, MemberDef * currentMd) const virtual
Reimplemented from Definition.
Definition at line 891 of file filedef.cpp.
References MemberDef::anchor(), Config_getBool, convertToHtml(), createSubDirs(), MemberDef::getFileDef(), getMemberList(), MemberDef::getNamespaceDef(), MemberDef::getOutputFileBase(), Doxygen::htmlFileExtension, MemberDef::isEnumValue(), MemberDef::isLinkable(), MemberDef::isLinkableInProject(), Definition::localName(), MemberListType_allMembersList, and OutputList::writeString().
writeSource()
void FileDef::writeSource (OutputList & ol, bool sameTu, QStrList & filesInSameTu)
Write a source listing of this file to the output
Definition at line 935 of file filedef.cpp.
References absFilePath(), Config_getBool, OutputList::disable(), OutputList::enable(), OutputList::enableAll(), OutputList::endCodeFragment(), OutputList::endContents(), endFileWithNavPath(), OutputList::endQuickIndices(), OutputList::endTextLink(), endTitle(), fileToString(), generateSourceFile(), Definition::getDefFileExtension(), getDirDef(), getFileFilter(), Definition::getLanguage(), getOutputFileBase(), ParserManager::getParser(), getSourceFileBase(), HLI_FileVisible, ClangParser::instance(), isDocumentationFile(), isLinkable(), OutputGenerator::Latex, m_docname, m_fileVersion, OutputGenerator::Man, name(), ParserInterface::parseCode(), Doxygen::parserManager, Doxygen::parseSourcesNeeded, OutputList::parseText(), ParserInterface::resetCodeParserState(), OutputGenerator::RTF, SrcLangExt_Cpp, SrcLangExt_ObjC, ClangParser::start(), OutputList::startCodeFragment(), OutputList::startContents(), startFile(), OutputList::startTextLink(), startTitle(), ClangParser::switchToFile(), theTranslator, title(), Translator::trGotoDocumentation(), Translator::trSourceFile(), Definition::writeNavigationPath(), and ClangParser::writeSources().
Referenced by generateFileSources().
writeSourceLink()
void FileDef::writeSourceLink (OutputList & ol) private
Definition at line 534 of file filedef.cpp.
References OutputList::disableAllBut(), OutputList::enableAll(), OutputList::endParagraph(), OutputList::endTextLink(), generateSourceFile(), OutputGenerator::Html, includeName(), OutputList::parseText(), OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, and Translator::trGotoSourceCode().
Referenced by writeDocumentation().
writeSummaryLinks()
void FileDef::writeSummaryLinks (OutputList & ol) virtual
Reimplemented from Definition.
Definition at line 634 of file filedef.cpp.
References ClassSDict::declVisible(), MemberList::declVisible(), NamespaceSDict::declVisible(), OutputList::disableAllBut(), LayoutDocManager::File, LayoutDocEntry::FileClasses, LayoutDocEntry::FileNamespaces, Definition::getLanguage(), getMemberList(), OutputGenerator::Html, LayoutDocManager::instance(), LayoutDocEntry::kind(), MemberList::listType(), MemberList::listTypeAsString(), m_classSDict, m_namespaceSDict, LayoutDocEntry::MemberDecl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
writeTagFile()
void FileDef::writeTagFile (FTextStream & t)
Definition at line 198 of file filedef.cpp.
References ClassDef::compoundTypeString(), convertToXML(), endl(), LayoutDocManager::File, LayoutDocEntry::FileClasses, IncludeInfo::fileDef, LayoutDocEntry::FileNamespaces, Definition::getLanguage(), getMemberList(), getOutputFileBase(), getPath(), IncludeInfo::imported, IncludeInfo::includeName, IncludeInfo::indirect, LayoutDocManager::instance(), isLinkable(), NamespaceDef::isLinkableInProject(), ClassDef::isLinkableInProject(), Definition::isReference(), SIntDict< MemberGroup >::Iterator, LayoutDocEntry::kind(), IncludeInfo::local, m_classSDict, m_includeList, m_memberGroupSDict, m_namespaceSDict, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, name(), Definition::name(), SrcLangExt_IDL, SrcLangExt_Java, LayoutDocEntryMemberDecl::type, Definition::writeDocAnchorsToTagFile(), MemberGroup::writeTagFile(), and MemberList::writeTagFile().
Referenced by writeTagFile().
Member Data Documentation
m_classSDict
ClassSDict* FileDef::m_classSDict private
Definition at line 235 of file filedef.h.
Referenced by FileDef(), getClassSDict(), insertClass(), writeClassDeclarations(), writeInlineClasses(), writeSummaryLinks(), writeTagFile(), and ~FileDef().
m_dir
DirDef* FileDef::m_dir private
Definition at line 231 of file filedef.h.
Referenced by FileDef(), getDirDef(), and setDirDef().
m_docname
QCString FileDef::m_docname private
Definition at line 225 of file filedef.h.
Referenced by docName(), FileDef(), writeDocumentation(), and writeSource().
m_fileName
QCString FileDef::m_fileName private
Definition at line 224 of file filedef.h.
Referenced by FileDef(), fileName(), and name().
m_filePath
QCString FileDef::m_filePath private
Definition at line 220 of file filedef.h.
Referenced by absFilePath(), acquireFileVersion(), FileDef(), and getSourceFileBase().
m_fileVersion
QCString FileDef::m_fileVersion private
Definition at line 229 of file filedef.h.
Referenced by acquireFileVersion(), fileVersion(), getVersion(), writeDocumentation(), and writeSource().
m_inclByDepFileName
QCString FileDef::m_inclByDepFileName private
Definition at line 222 of file filedef.h.
Referenced by includedByDependencyGraphFileName(), and setDiskName().
m_inclDepFileName
QCString FileDef::m_inclDepFileName private
Definition at line 221 of file filedef.h.
Referenced by includeDependencyGraphFileName(), and setDiskName().
m_includedByDict
QDict<IncludeInfo>* FileDef::m_includedByDict private
Definition at line 215 of file filedef.h.
Referenced by addIncludedByDependency(), FileDef(), and ~FileDef().
m_includedByList
QList<IncludeInfo>* FileDef::m_includedByList private
Definition at line 216 of file filedef.h.
Referenced by addIncludedByDependency(), FileDef(), includedByFileList(), and ~FileDef().
m_includeDict
QDict<IncludeInfo>* FileDef::m_includeDict private
Definition at line 213 of file filedef.h.
Referenced by addIncludeDependency(), FileDef(), isIncluded(), and ~FileDef().
m_includeList
QList<IncludeInfo>* FileDef::m_includeList private
Definition at line 214 of file filedef.h.
Referenced by addIncludeDependency(), addIncludedUsingDirectives(), FileDef(), includeFileList(), writeIncludeFiles(), writeTagFile(), and ~FileDef().
m_isSource
bool FileDef::m_isSource private
Definition at line 228 of file filedef.h.
Referenced by FileDef(), and isSource().
m_memberGroupSDict
MemberGroupSDict* FileDef::m_memberGroupSDict private
Definition at line 233 of file filedef.h.
Referenced by addListReferences(), addMembersToMemberGroup(), distributeMemberGroupDocumentation(), FileDef(), findSectionsInDocumentation(), getMemberGroupSDict(), writeMemberGroups(), writeTagFile(), and ~FileDef().
m_memberLists
QList<MemberList> FileDef::m_memberLists private
Definition at line 232 of file filedef.h.
Referenced by addListReferences(), addMembersToMemberGroup(), createMemberList(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), insertMember(), sortMemberLists(), and writeMemberPages().
m_namespaceSDict
NamespaceSDict* FileDef::m_namespaceSDict private
Definition at line 234 of file filedef.h.
Referenced by FileDef(), getNamespaceSDict(), insertNamespace(), writeNamespaceDeclarations(), writeSummaryLinks(), writeTagFile(), and ~FileDef().
m_outputDiskName
QCString FileDef::m_outputDiskName private
Definition at line 223 of file filedef.h.
Referenced by getOutputFileBase(), getSourceFileBase(), and setDiskName().
m_package
PackageDef* FileDef::m_package private
Definition at line 230 of file filedef.h.
Referenced by FileDef(), packageDef(), and setPackageDef().
m_path
QCString FileDef::m_path private
Definition at line 219 of file filedef.h.
Referenced by FileDef(), and getPath().
m_srcDefDict
QIntDict<Definition>* FileDef::m_srcDefDict private
Definition at line 226 of file filedef.h.
Referenced by addSourceRef(), FileDef(), getSourceDefinition(), and ~FileDef().
m_srcMemberDict
QIntDict<MemberDef>* FileDef::m_srcMemberDict private
Definition at line 227 of file filedef.h.
Referenced by addSourceRef(), FileDef(), getSourceMember(), and ~FileDef().
m_subGrouping
bool FileDef::m_subGrouping private
Definition at line 236 of file filedef.h.
Referenced by addMembersToMemberGroup(), FileDef(), subGrouping(), and writeMemberGroups().
m_usingDeclList
SDict<Definition>* FileDef::m_usingDeclList private
Definition at line 218 of file filedef.h.
Referenced by addIncludedUsingDirectives(), addUsingDeclaration(), FileDef(), getUsedClasses(), and ~FileDef().
m_usingDirList
NamespaceSDict* FileDef::m_usingDirList private
Definition at line 217 of file filedef.h.
Referenced by addIncludedUsingDirectives(), addUsingDirective(), combineUsingRelations(), FileDef(), getUsedNamespaces(), and ~FileDef().
visited
bool FileDef::visited
Definition at line 183 of file filedef.h.
Referenced by addIncludedUsingDirectives(), combineUsingRelations(), combineUsingRelations(), and findIncludedUsingDirectives().
The documentation for this class was generated from the following files:
src/filedef.h
src/filedef.cpp