Doxygen: src/marshal.h File Reference
marshal.h File Reference
#include <qlist.h>
#include <qfile.h>
#include "sortdict.h"
#include "store.h"
Macros
#define NULL_LIST 0xffffffff
Functions
void marshalInt (StorageIntf *s, int v)
void marshalUInt (StorageIntf *s, uint v)
void marshalUInt64 (StorageIntf *s, uint64 v)
void marshalBool (StorageIntf *s, bool b)
void marshalQCString (StorageIntf *s, const QCString &str)
void marshalQGString (StorageIntf *s, const QGString &str)
void marshalArgumentList (StorageIntf *s, ArgumentList *argList)
void marshalArgumentLists (StorageIntf *s, QList< ArgumentList > *argLists)
void marshalBaseInfoList (StorageIntf *s, QList< BaseInfo > *baseList)
void marshalGroupingList (StorageIntf *s, QList< Grouping > *groups)
void marshalSectionInfoList (StorageIntf *s, QList< SectionInfo > *anchors)
void marshalItemInfoList (StorageIntf *s, QList< ListItemInfo > *sli)
void marshalObjPointer (StorageIntf *s, void *obj)
void marshalSectionDict (StorageIntf *s, SectionDict *sections)
void marshalMemberSDict (StorageIntf *s, MemberSDict *memberSDict)
void marshalDocInfo (StorageIntf *s, DocInfo *docInfo)
void marshalBriefInfo (StorageIntf *s, BriefInfo *briefInfo)
void marshalBodyInfo (StorageIntf *s, BodyInfo *bodyInfo)
void marshalGroupList (StorageIntf *s, GroupList *groupList)
void marshalMemberList (StorageIntf *s, MemberList *ml)
void marshalExampleSDict (StorageIntf *s, ExampleSDict *ed)
void marshalMemberLists (StorageIntf *s, SDict< MemberList > *mls)
void marshalEntry (StorageIntf *s, Entry *e)
void marshalEntryTree (StorageIntf *s, Entry *e)
int unmarshalInt (StorageIntf *s)
uint unmarshalUInt (StorageIntf *s)
uint64 unmarshalUInt64 (StorageIntf *s)
bool unmarshalBool (StorageIntf *s)
QCString unmarshalQCString (StorageIntf *s)
QGString unmarshalQGString (StorageIntf *s)
ArgumentList * unmarshalArgumentList (StorageIntf *s)
QList< ArgumentList > * unmarshalArgumentLists (StorageIntf *s)
QList< BaseInfo > * unmarshalBaseInfoList (StorageIntf *s)
QList< Grouping > * unmarshalGroupingList (StorageIntf *s)
QList< SectionInfo > * unmarshalSectionInfoList (StorageIntf *s)
QList< ListItemInfo > * unmarshalItemInfoList (StorageIntf *s)
void * unmarshalObjPointer (StorageIntf *s)
SectionDict * unmarshalSectionDict (StorageIntf *s)
MemberSDict * unmarshalMemberSDict (StorageIntf *s)
DocInfo * unmarshalDocInfo (StorageIntf *s)
BriefInfo * unmarshalBriefInfo (StorageIntf *s)
BodyInfo * unmarshalBodyInfo (StorageIntf *s)
GroupList * unmarshalGroupList (StorageIntf *s)
MemberList * unmarshalMemberList (StorageIntf *s)
ExampleSDict * unmarshalExampleSDict (StorageIntf *s)
SDict< MemberList > * unmarshalMemberLists (StorageIntf *s)
Entry * unmarshalEntry (StorageIntf *s)
Entry * unmarshalEntryTree (StorageIntf *s)
Macro Definition Documentation
NULL_LIST
#define NULL_LIST 0xffffffff
Definition at line 41 of file marshal.h.
Referenced by MemberList::marshal(), ArgumentList::marshal(), marshalArgumentLists(), marshalBaseInfoList(), marshalBodyInfo(), marshalBriefInfo(), marshalDocInfo(), marshalExampleSDict(), marshalGroupingList(), marshalGroupList(), marshalItemInfoList(), marshalMemberList(), marshalMemberLists(), marshalMemberSDict(), marshalSectionDict(), marshalSectionInfoList(), MemberList::unmarshal(), ArgumentList::unmarshal(), unmarshalArgumentLists(), unmarshalBaseInfoList(), unmarshalBodyInfo(), unmarshalBriefInfo(), unmarshalDocInfo(), unmarshalExampleSDict(), unmarshalGroupingList(), unmarshalGroupList(), unmarshalItemInfoList(), unmarshalMemberList(), unmarshalMemberLists(), unmarshalMemberSDict(), unmarshalSectionDict(), and unmarshalSectionInfoList().
Function Documentation
marshalArgumentList()
void marshalArgumentList (StorageIntf * s, ArgumentList * argList)
Definition at line 62 of file marshal.cpp.
References ArgumentList::marshal().
Referenced by marshalArgumentLists(), and marshalEntry().
marshalArgumentLists()
void marshalArgumentLists (StorageIntf * s, QList< ArgumentList > * argLists)
Definition at line 67 of file marshal.cpp.
References marshalArgumentList(), marshalUInt(), and NULL_LIST.
Referenced by marshalEntry().
marshalBaseInfoList()
void marshalBaseInfoList (StorageIntf * s, QList< BaseInfo > * baseList)
Definition at line 85 of file marshal.cpp.
References marshalInt(), marshalQCString(), marshalUInt(), BaseInfo::name, NULL_LIST, BaseInfo::prot, and BaseInfo::virt.
Referenced by marshalEntry().
marshalBodyInfo()
void marshalBodyInfo (StorageIntf * s, BodyInfo * bodyInfo)
Definition at line 247 of file marshal.cpp.
References BodyInfo::endLine, BodyInfo::fileDef, marshalInt(), marshalObjPointer(), marshalUInt(), NULL_LIST, and BodyInfo::startLine.
marshalBool()
void marshalBool (StorageIntf * s, bool b)
Definition at line 42 of file marshal.cpp.
References StorageIntf::write().
Referenced by MemberList::marshal(), MemberGroup::marshal(), ArgumentList::marshal(), and marshalEntry().
marshalBriefInfo()
void marshalBriefInfo (StorageIntf * s, BriefInfo * briefInfo)
Definition at line 231 of file marshal.cpp.
References BriefInfo::doc, BriefInfo::file, BriefInfo::line, marshalInt(), marshalQCString(), marshalUInt(), NULL_LIST, and BriefInfo::tooltip.
marshalDocInfo()
void marshalDocInfo (StorageIntf * s, DocInfo * docInfo)
Definition at line 216 of file marshal.cpp.
References DocInfo::doc, DocInfo::file, DocInfo::line, marshalInt(), marshalQCString(), marshalUInt(), and NULL_LIST.
marshalEntry()
void marshalEntry (StorageIntf * s, Entry * e)
Definition at line 347 of file marshal.cpp.
References Entry::anchors, Entry::argList, Entry::args, Entry::artificial, Entry::bitfields, Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, Entry::doc, Entry::docFile, Entry::docLine, Entry::endBodyLine, Entry::exception, Entry::explicitExternal, Entry::extends, Entry::fileName, Entry::groupDocType, Entry::groups, HEADER, Entry::hidden, Entry::id, Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, Entry::includeFile, Entry::includeName, Entry::initializer, Entry::initLines, Entry::inside, Entry::lang, marshalArgumentList(), marshalArgumentLists(), marshalBaseInfoList(), marshalBool(), marshalGroupingList(), marshalInt(), marshalItemInfoList(), marshalQCString(), marshalQGString(), marshalSectionInfoList(), marshalUInt(), marshalUInt64(), Entry::mGrpId, Entry::mtype, Entry::name, Entry::program, Entry::protection, Entry::proto, Entry::read, Entry::relates, Entry::relatesType, Entry::section, Entry::sli, Entry::spec, Entry::startLine, Entry::stat, Entry::subGrouping, Entry::tArgLists, Entry::type, Entry::typeConstr, Entry::virt, and Entry::write.
Referenced by marshalEntryTree(), and EntryNav::saveEntry().
marshalEntryTree()
void marshalEntryTree (StorageIntf * s, Entry * e)
Definition at line 404 of file marshal.cpp.
References Entry::children(), marshalEntry(), marshalEntryTree(), and marshalUInt().
Referenced by marshalEntryTree().
marshalExampleSDict()
void marshalExampleSDict (StorageIntf * s, ExampleSDict * ed)
Definition at line 303 of file marshal.cpp.
References Example::anchor, SDict< T >::count(), Example::file, marshalQCString(), marshalUInt(), Example::name, and NULL_LIST.
marshalGroupingList()
void marshalGroupingList (StorageIntf * s, QList< Grouping > * groups)
Definition at line 105 of file marshal.cpp.
References Grouping::groupname, marshalInt(), marshalQCString(), marshalUInt(), NULL_LIST, and Grouping::pri.
Referenced by marshalEntry().
marshalGroupList()
void marshalGroupList (StorageIntf * s, GroupList * groupList)
Definition at line 262 of file marshal.cpp.
References marshalObjPointer(), marshalUInt(), and NULL_LIST.
marshalInt()
void marshalInt (StorageIntf * s, int v)
Definition at line 16 of file marshal.cpp.
References StorageIntf::write().
Referenced by MemberList::marshal(), MemberGroup::marshal(), ArgumentList::marshal(), marshalBaseInfoList(), marshalBodyInfo(), marshalBriefInfo(), marshalDocInfo(), marshalEntry(), marshalGroupingList(), marshalItemInfoList(), and marshalSectionInfoList().
marshalItemInfoList()
void marshalItemInfoList (StorageIntf * s, QList< ListItemInfo > * sli)
Definition at line 148 of file marshal.cpp.
References ListItemInfo::itemId, marshalInt(), marshalQCString(), marshalUInt(), NULL_LIST, and ListItemInfo::type.
Referenced by MemberGroup::marshal(), and marshalEntry().
marshalMemberList()
void marshalMemberList (StorageIntf * s, MemberList * ml)
Definition at line 280 of file marshal.cpp.
References MemberList::count(), MemberList::marshal(), marshalObjPointer(), marshalUInt(), and NULL_LIST.
Referenced by MemberGroup::marshal().
marshalMemberLists()
void marshalMemberLists (StorageIntf * s, SDict< MemberList > * mls)
Definition at line 326 of file marshal.cpp.
References SDict< T >::count(), marshalObjPointer(), marshalQCString(), marshalUInt(), and NULL_LIST.
marshalMemberSDict()
void marshalMemberSDict (StorageIntf * s, MemberSDict * memberSDict)
Definition at line 192 of file marshal.cpp.
References SDict< T >::count(), marshalObjPointer(), marshalQCString(), marshalUInt(), and NULL_LIST.
marshalObjPointer()
void marshalObjPointer (StorageIntf * s, void * obj)
Definition at line 167 of file marshal.cpp.
References StorageIntf::write().
Referenced by MemberGroup::marshal(), marshalBodyInfo(), marshalGroupList(), marshalMemberList(), marshalMemberLists(), marshalMemberSDict(), and marshalSectionDict().
marshalQCString()
void marshalQCString (StorageIntf * s, const QCString & str)
Definition at line 48 of file marshal.cpp.
References marshalUInt(), and StorageIntf::write().
Referenced by MemberGroup::marshal(), ArgumentList::marshal(), marshalBaseInfoList(), marshalBriefInfo(), marshalDocInfo(), marshalEntry(), marshalExampleSDict(), marshalGroupingList(), marshalItemInfoList(), marshalMemberLists(), marshalMemberSDict(), marshalSectionDict(), and marshalSectionInfoList().
marshalQGString()
void marshalQGString (StorageIntf * s, const QGString & str)
Definition at line 55 of file marshal.cpp.
References marshalUInt(), and StorageIntf::write().
Referenced by marshalEntry().
marshalSectionDict()
void marshalSectionDict (StorageIntf * s, SectionDict * sections)
Definition at line 173 of file marshal.cpp.
References SDict< T >::count(), marshalObjPointer(), marshalQCString(), marshalUInt(), and NULL_LIST.
marshalSectionInfoList()
void marshalSectionInfoList (StorageIntf * s, QList< SectionInfo > * anchors)
Definition at line 124 of file marshal.cpp.
References SectionInfo::fileName, SectionInfo::label, SectionInfo::level, SectionInfo::lineNr, marshalInt(), marshalQCString(), marshalUInt(), NULL_LIST, SectionInfo::ref, SectionInfo::title, and SectionInfo::type.
Referenced by marshalEntry().
marshalUInt()
void marshalUInt (StorageIntf * s, uint v)
Definition at line 26 of file marshal.cpp.
References StorageIntf::write().
Referenced by MemberList::marshal(), ArgumentList::marshal(), marshalArgumentLists(), marshalBaseInfoList(), marshalBodyInfo(), marshalBriefInfo(), marshalDocInfo(), marshalEntry(), marshalEntryTree(), marshalExampleSDict(), marshalGroupingList(), marshalGroupList(), marshalItemInfoList(), marshalMemberList(), marshalMemberLists(), marshalMemberSDict(), marshalQCString(), marshalQGString(), marshalSectionDict(), marshalSectionInfoList(), and marshalUInt64().
marshalUInt64()
void marshalUInt64 (StorageIntf * s, uint64 v)
Definition at line 36 of file marshal.cpp.
References marshalUInt().
Referenced by marshalEntry().
unmarshalArgumentList()
ArgumentList* unmarshalArgumentList (StorageIntf * s)
Definition at line 479 of file marshal.cpp.
References ArgumentList::unmarshal().
Referenced by unmarshalArgumentLists(), and unmarshalEntry().
unmarshalArgumentLists()
QList<ArgumentList>* unmarshalArgumentLists (StorageIntf * s)
Definition at line 484 of file marshal.cpp.
References NULL_LIST, unmarshalArgumentList(), and unmarshalUInt().
Referenced by unmarshalEntry().
unmarshalBaseInfoList()
QList<BaseInfo>* unmarshalBaseInfoList (StorageIntf * s)
Definition at line 500 of file marshal.cpp.
References NULL_LIST, unmarshalInt(), unmarshalQCString(), and unmarshalUInt().
Referenced by unmarshalEntry().
unmarshalBodyInfo()
BodyInfo* unmarshalBodyInfo (StorageIntf * s)
Definition at line 650 of file marshal.cpp.
References BodyInfo::endLine, BodyInfo::fileDef, NULL_LIST, BodyInfo::startLine, unmarshalInt(), unmarshalObjPointer(), and unmarshalUInt().
unmarshalBool()
bool unmarshalBool (StorageIntf * s)
Definition at line 443 of file marshal.cpp.
References StorageIntf::read().
Referenced by MemberList::unmarshal(), MemberGroup::unmarshal(), ArgumentList::unmarshal(), and unmarshalEntry().
unmarshalBriefInfo()
BriefInfo* unmarshalBriefInfo (StorageIntf * s)
Definition at line 638 of file marshal.cpp.
References BriefInfo::doc, BriefInfo::file, BriefInfo::line, NULL_LIST, BriefInfo::tooltip, unmarshalInt(), unmarshalQCString(), and unmarshalUInt().
unmarshalDocInfo()
DocInfo* unmarshalDocInfo (StorageIntf * s)
Definition at line 627 of file marshal.cpp.
References DocInfo::doc, DocInfo::file, DocInfo::line, NULL_LIST, unmarshalInt(), unmarshalQCString(), and unmarshalUInt().
unmarshalEntry()
Entry* unmarshalEntry (StorageIntf * s)
Definition at line 727 of file marshal.cpp.
References Entry::anchors, Entry::argList, Entry::args, Entry::artificial, Entry::bitfields, Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, Entry::doc, Entry::docFile, Entry::docLine, Entry::endBodyLine, Entry::exception, Entry::explicitExternal, Entry::extends, Entry::fileName, Entry::groupDocType, Entry::groups, HEADER, Entry::hidden, Entry::id, Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, Entry::includeFile, Entry::includeName, Entry::initializer, Entry::initLines, Entry::inside, Entry::lang, Entry::mGrpId, Entry::mtype, Entry::name, Entry::program, Entry::protection, Entry::proto, Entry::read, Entry::relates, Entry::relatesType, Entry::section, Entry::sli, Entry::spec, Entry::startLine, Entry::stat, Entry::subGrouping, Entry::tArgLists, Entry::type, Entry::typeConstr, unmarshalArgumentList(), unmarshalArgumentLists(), unmarshalBaseInfoList(), unmarshalBool(), unmarshalGroupingList(), unmarshalInt(), unmarshalItemInfoList(), unmarshalQCString(), unmarshalQGString(), unmarshalSectionInfoList(), unmarshalUInt(), unmarshalUInt64(), Entry::virt, and Entry::write.
Referenced by EntryNav::loadEntry(), and unmarshalEntryTree().
unmarshalEntryTree()
Entry* unmarshalEntryTree (StorageIntf * s)
Definition at line 791 of file marshal.cpp.
References Entry::addSubEntry(), unmarshalEntry(), unmarshalEntryTree(), and unmarshalUInt().
Referenced by unmarshalEntryTree().
unmarshalExampleSDict()
ExampleSDict* unmarshalExampleSDict (StorageIntf * s)
Definition at line 692 of file marshal.cpp.
References Example::anchor, Example::file, SDict< T >::inSort(), Example::name, NULL_LIST, unmarshalQCString(), and unmarshalUInt().
unmarshalGroupingList()
QList<Grouping>* unmarshalGroupingList (StorageIntf * s)
Definition at line 518 of file marshal.cpp.
References NULL_LIST, unmarshalInt(), unmarshalQCString(), and unmarshalUInt().
Referenced by unmarshalEntry().
unmarshalGroupList()
GroupList* unmarshalGroupList (StorageIntf * s)
Definition at line 661 of file marshal.cpp.
References NULL_LIST, unmarshalObjPointer(), and unmarshalUInt().
unmarshalInt()
int unmarshalInt (StorageIntf * s)
Definition at line 418 of file marshal.cpp.
References StorageIntf::read().
Referenced by MemberList::unmarshal(), MemberGroup::unmarshal(), ArgumentList::unmarshal(), unmarshalBaseInfoList(), unmarshalBodyInfo(), unmarshalBriefInfo(), unmarshalDocInfo(), unmarshalEntry(), unmarshalGroupingList(), unmarshalItemInfoList(), and unmarshalSectionInfoList().
unmarshalItemInfoList()
QList<ListItemInfo>* unmarshalItemInfoList (StorageIntf * s)
Definition at line 557 of file marshal.cpp.
References ListItemInfo::itemId, NULL_LIST, ListItemInfo::type, unmarshalInt(), unmarshalQCString(), and unmarshalUInt().
Referenced by MemberGroup::unmarshal(), and unmarshalEntry().
unmarshalMemberList()
MemberList* unmarshalMemberList (StorageIntf * s)
Definition at line 676 of file marshal.cpp.
References MemberList::append(), NULL_LIST, MemberList::unmarshal(), unmarshalObjPointer(), and unmarshalUInt().
Referenced by MemberGroup::unmarshal().
unmarshalMemberLists()
SDict<MemberList>* unmarshalMemberLists (StorageIntf * s)
Definition at line 711 of file marshal.cpp.
References SDict< T >::append(), NULL_LIST, unmarshalObjPointer(), unmarshalQCString(), and unmarshalUInt().
unmarshalMemberSDict()
MemberSDict* unmarshalMemberSDict (StorageIntf * s)
Definition at line 600 of file marshal.cpp.
References SDict< T >::append(), NULL_LIST, unmarshalObjPointer(), unmarshalQCString(), and unmarshalUInt().
unmarshalObjPointer()
void* unmarshalObjPointer (StorageIntf * s)
Definition at line 575 of file marshal.cpp.
References StorageIntf::read().
Referenced by MemberGroup::unmarshal(), unmarshalBodyInfo(), unmarshalGroupList(), unmarshalMemberList(), unmarshalMemberLists(), unmarshalMemberSDict(), and unmarshalSectionDict().
unmarshalQCString()
QCString unmarshalQCString (StorageIntf * s)
Definition at line 451 of file marshal.cpp.
References StorageIntf::read(), and unmarshalUInt().
Referenced by MemberGroup::unmarshal(), ArgumentList::unmarshal(), unmarshalBaseInfoList(), unmarshalBriefInfo(), unmarshalDocInfo(), unmarshalEntry(), unmarshalExampleSDict(), unmarshalGroupingList(), unmarshalItemInfoList(), unmarshalMemberLists(), unmarshalMemberSDict(), unmarshalSectionDict(), and unmarshalSectionInfoList().
unmarshalQGString()
QGString unmarshalQGString (StorageIntf * s)
Definition at line 465 of file marshal.cpp.
References StorageIntf::read(), and unmarshalUInt().
Referenced by unmarshalEntry().
unmarshalSectionDict()
SectionDict* unmarshalSectionDict (StorageIntf * s)
Definition at line 582 of file marshal.cpp.
References SDict< T >::append(), NULL_LIST, unmarshalObjPointer(), unmarshalQCString(), and unmarshalUInt().
unmarshalSectionInfoList()
QList<SectionInfo>* unmarshalSectionInfoList (StorageIntf * s)
Definition at line 535 of file marshal.cpp.
References NULL_LIST, unmarshalInt(), unmarshalQCString(), and unmarshalUInt().
Referenced by unmarshalEntry().
unmarshalUInt()
uint unmarshalUInt (StorageIntf * s)
Definition at line 427 of file marshal.cpp.
References StorageIntf::read().
Referenced by MemberList::unmarshal(), ArgumentList::unmarshal(), unmarshalArgumentLists(), unmarshalBaseInfoList(), unmarshalBodyInfo(), unmarshalBriefInfo(), unmarshalDocInfo(), unmarshalEntry(), unmarshalEntryTree(), unmarshalExampleSDict(), unmarshalGroupingList(), unmarshalGroupList(), unmarshalItemInfoList(), unmarshalMemberList(), unmarshalMemberLists(), unmarshalMemberSDict(), unmarshalQCString(), unmarshalQGString(), unmarshalSectionDict(), unmarshalSectionInfoList(), and unmarshalUInt64().
unmarshalUInt64()
uint64 unmarshalUInt64 (StorageIntf * s)
Definition at line 436 of file marshal.cpp.
References unmarshalUInt().
Referenced by unmarshalEntry().