Doxygen: DocSection Class Reference
DocSection Class Reference
Node representing a normal section.
#include <docparser.h>
Public Member Functions
DocSection (DocNode *parent, int level, const QCString &id)
Kind kind () const
int level () const
QCString title () const
QCString anchor () const
QCString id () const
QCString file () const
void accept (DocVisitor *v)
int parse ()
Public Member Functions inherited from CompAccept< DocSection >
CompAccept ()
virtual ~CompAccept ()
void accept (DocSection *obj, DocVisitor *v)
const QList< DocNode > & children () const
QList< DocNode > & children ()
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Attributes
int m_level
QCString m_id
QCString m_title
QCString m_anchor
QCString m_file
Additional Inherited Members
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from CompAccept< DocSection >
QList< DocNode > m_children
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Node representing a normal section.
Definition at line 937 of file docparser.h.
Constructor & Destructor Documentation
DocSection()
DocSection::DocSection (DocNode * parent, int level, const QCString & id) inline
Definition at line 940 of file docparser.h.
References DocNode::m_parent, and DocNode::parent().
Referenced by parse().
Member Function Documentation
accept()
void DocSection::accept (DocVisitor * v) inline virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 948 of file docparser.h.
References CompAccept< T >::accept().
anchor()
QCString DocSection::anchor () const inline
Definition at line 945 of file docparser.h.
References m_anchor.
Referenced by DocbookDocVisitor::visitPre(), RTFDocVisitor::visitPre(), XmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and HtmlDocVisitor::visitPre().
file()
QCString DocSection::file () const inline
Definition at line 947 of file docparser.h.
References m_file.
Referenced by DocbookDocVisitor::visitPre(), RTFDocVisitor::visitPre(), XmlDocVisitor::visitPre(), and LatexDocVisitor::visitPre().
id()
QCString DocSection::id () const inline
Definition at line 946 of file docparser.h.
References m_id.
kind()
Kind DocSection::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 942 of file docparser.h.
References DocNode::Kind_Section.
level()
int DocSection::level () const inline
Definition at line 943 of file docparser.h.
References m_level.
Referenced by parse(), XmlDocVisitor::visitPost(), PrintDocVisitor::visitPost(), RTFDocVisitor::visitPre(), ManDocVisitor::visitPre(), XmlDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), PerlModDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
parse()
int DocSection::parse ()
Definition at line 6711 of file docparser.cpp.
References SDict< T >::append(), DBG, DocSection(), doctokenizerYYlineno, SectionInfo::fileName, SDict< T >::find(), g_fileName, g_nodeStack, g_token, INTERNAL_ASSERT, DocPara::isEmpty(), SectionInfo::label, level(), m_anchor, CompAccept< DocSection >::m_children, m_file, m_id, m_level, m_title, DocPara::markFirst(), DocPara::markLast(), parse(), DocInternal::parse(), DocPara::parse(), RetVal_EndInternal, RetVal_Internal, RetVal_OK, RetVal_Paragraph, RetVal_Section, RetVal_Subsection, RetVal_Subsubsection, Doxygen::sectionDict, TokenInfo::sectionId, sectionLevelToName, Doxygen::subpageNestingLevel, SectionInfo::title, TK_LISTITEM, and warn_doc_error().
Referenced by parse(), DocInternal::parse(), and DocRoot::parse().
title()
QCString DocSection::title () const inline
Definition at line 944 of file docparser.h.
References m_title.
Referenced by DocbookDocVisitor::visitPre(), ManDocVisitor::visitPre(), RTFDocVisitor::visitPre(), XmlDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and PerlModDocVisitor::visitPre().
Member Data Documentation
m_anchor
QCString DocSection::m_anchor private
Definition at line 955 of file docparser.h.
Referenced by anchor(), and parse().
m_file
QCString DocSection::m_file private
Definition at line 956 of file docparser.h.
Referenced by file(), and parse().
m_id
QCString DocSection::m_id private
Definition at line 953 of file docparser.h.
Referenced by id(), and parse().
m_level
int DocSection::m_level private
Definition at line 952 of file docparser.h.
Referenced by level(), and parse().
m_title
QCString DocSection::m_title private
Definition at line 954 of file docparser.h.
Referenced by parse(), and title().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp