Doxygen: DotWorkerThread Class Reference
DotWorkerThread Class Reference
Worker thread to execute a dot run.
#include <dot.h>
Public Member Functions
DotWorkerThread (DotRunnerQueue *queue)
void run ()
void cleanup ()
Private Attributes
DotRunnerQueue * m_queue
QList< DotRunner::CleanupItem > m_cleanupItems
Detailed Description
Worker thread to execute a dot run.
Definition at line 450 of file dot.h.
Constructor & Destructor Documentation
DotWorkerThread()
DotWorkerThread::DotWorkerThread (DotRunnerQueue * queue)
Definition at line 1145 of file dot.cpp.
References m_cleanupItems.
Member Function Documentation
cleanup()
void DotWorkerThread::cleanup ()
Definition at line 1165 of file dot.cpp.
References DotConstString::data(), DotRunner::CleanupItem::file, m_cleanupItems, and DotRunner::CleanupItem::path.
Referenced by run().
run()
void DotWorkerThread::run ()
Definition at line 1151 of file dot.cpp.
References DotRunner::cleanup(), cleanup(), DotRunnerQueue::dequeue(), DotRunner::CleanupItem::file, DotConstString::isEmpty(), m_cleanupItems, m_queue, and DotRunner::run().
Member Data Documentation
m_cleanupItems
QList<DotRunner::CleanupItem> DotWorkerThread::m_cleanupItems private
Definition at line 458 of file dot.h.
Referenced by cleanup(), DotWorkerThread(), and run().
m_queue
DotRunnerQueue* DotWorkerThread::m_queue private
Definition at line 457 of file dot.h.
Referenced by run().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp