Doxygen: HtmlAttribList Class Reference
HtmlAttribList Class Reference
A list of Html attributes.
#include <htmlattrib.h>
Public Member Functions
HtmlAttribList ()
~HtmlAttribList ()
HtmlAttribList (const HtmlAttribList &l)
HtmlAttribList & operator= (const HtmlAttribList &l)
QCString find (const QCString name) const
QCString toString () const
Private Member Functions
HtmlAttrib * newValue (HtmlAttrib *v) const
void deleteValue (HtmlAttrib *v) const
Detailed Description
A list of Html attributes.
The Html attributes are deeply copied into the list.
Definition at line 32 of file htmlattrib.h.
Constructor & Destructor Documentation
HtmlAttribList() [1/2]
HtmlAttribList::HtmlAttribList () inline
Definition at line 35 of file htmlattrib.h.
~HtmlAttribList()
HtmlAttribList::~HtmlAttribList () inline
Definition at line 36 of file htmlattrib.h.
HtmlAttribList() [2/2]
HtmlAttribList::HtmlAttribList (const HtmlAttribList & l) inline
Definition at line 37 of file htmlattrib.h.
References operator=().
Member Function Documentation
deleteValue()
void HtmlAttribList::deleteValue (HtmlAttrib * v) const inline private
Definition at line 66 of file htmlattrib.h.
find()
QCString HtmlAttribList::find (const QCString name) const inline
Definition at line 41 of file htmlattrib.h.
References HtmlAttrib::name, and HtmlAttrib::value.
Referenced by LatexDocVisitor::visitPost(), and LatexDocVisitor::visitPre().
newValue()
HtmlAttrib* HtmlAttribList::newValue (HtmlAttrib * v) const inline private
Definition at line 64 of file htmlattrib.h.
operator=()
HtmlAttribList& HtmlAttribList::operator= (const HtmlAttribList & l) inline
Definition at line 39 of file htmlattrib.h.
Referenced by HtmlAttribList().
toString()
QCString HtmlAttribList::toString () const inline
Definition at line 52 of file htmlattrib.h.
References HtmlAttrib::name, and HtmlAttrib::value.
Referenced by DocPara::handleHtmlStartTag().
The documentation for this class was generated from the following file:
src/htmlattrib.h