Doxygen: TranslatorAdapter_1_5_4 Class Reference
TranslatorAdapter_1_5_4 Class Reference
Adapter class for languages that only contain translations up to version 1.5.4.
#include <translator_adapter.h>
Public Member Functions
virtual QCString updateNeededMessage ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const char *clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const char *namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
Public Member Functions inherited from TranslatorAdapter_1_6_0
virtual QCString trDirRelation (const char *name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
Public Member Functions inherited from TranslatorAdapter_1_6_3
virtual QCString trFileIn (const char *name)
virtual QCString trIncludesFileIn (const char *name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
Public Member Functions inherited from TranslatorAdapter_1_7_5
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const char *name)
Public Member Functions inherited from TranslatorAdapter_1_8_0
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const char *name)
virtual QCString trInheritedFrom (const char *members, const char *what)
virtual QCString trAdditionalInheritedMembers ()
Public Member Functions inherited from TranslatorAdapter_1_8_2
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trDesignOverview ()
Public Member Functions inherited from TranslatorAdapter_1_8_4
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const char *namespaceName)
virtual QCString trServiceReference (const char *sName)
virtual QCString trSingletonReference (const char *sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Public Member Functions inherited from Translator
virtual ~Translator ()
virtual QCString idLanguage ()=0
virtual QCString latexLanguageSupportCommand ()=0
virtual QCString trRelatedFunctions ()=0
virtual QCString trRelatedSubscript ()=0
virtual QCString trDetailedDescription ()=0
virtual QCString trMemberTypedefDocumentation ()=0
virtual QCString trMemberEnumerationDocumentation ()=0
virtual QCString trMemberFunctionDocumentation ()=0
virtual QCString trMemberDataDocumentation ()=0
virtual QCString trMore ()=0
virtual QCString trListOfAllMembers ()=0
virtual QCString trMemberList ()=0
virtual QCString trThisIsTheListOfAllMembers ()=0
virtual QCString trIncludingInheritedMembers ()=0
virtual QCString trGeneratedAutomatically (const char *s)=0
virtual QCString trEnumName ()=0
virtual QCString trEnumValue ()=0
virtual QCString trDefinedIn ()=0
virtual QCString trModules ()=0
virtual QCString trClassHierarchy ()=0
virtual QCString trCompoundList ()=0
virtual QCString trFileList ()=0
virtual QCString trCompoundMembers ()=0
virtual QCString trFileMembers ()=0
virtual QCString trRelatedPages ()=0
virtual QCString trExamples ()=0
virtual QCString trSearch ()=0
virtual QCString trClassHierarchyDescription ()=0
virtual QCString trFileListDescription (bool extractAll)=0
virtual QCString trCompoundListDescription ()=0
virtual QCString trCompoundMembersDescription (bool extractAll)=0
virtual QCString trFileMembersDescription (bool extractAll)=0
virtual QCString trExamplesDescription ()=0
virtual QCString trRelatedPagesDescription ()=0
virtual QCString trModulesDescription ()=0
virtual QCString trDocumentation ()=0
virtual QCString trModuleIndex ()=0
virtual QCString trHierarchicalIndex ()=0
virtual QCString trCompoundIndex ()=0
virtual QCString trFileIndex ()=0
virtual QCString trModuleDocumentation ()=0
virtual QCString trClassDocumentation ()=0
virtual QCString trFileDocumentation ()=0
virtual QCString trExampleDocumentation ()=0
virtual QCString trPageDocumentation ()=0
virtual QCString trReferenceManual ()=0
virtual QCString trDefines ()=0
virtual QCString trTypedefs ()=0
virtual QCString trEnumerations ()=0
virtual QCString trFunctions ()=0
virtual QCString trVariables ()=0
virtual QCString trEnumerationValues ()=0
virtual QCString trDefineDocumentation ()=0
virtual QCString trTypedefDocumentation ()=0
virtual QCString trEnumerationTypeDocumentation ()=0
virtual QCString trFunctionDocumentation ()=0
virtual QCString trVariableDocumentation ()=0
virtual QCString trCompounds ()=0
virtual QCString trGeneratedAt (const char *date, const char *projName)=0
virtual QCString trClassDiagram (const char *clName)=0
virtual QCString trForInternalUseOnly ()=0
virtual QCString trWarning ()=0
virtual QCString trVersion ()=0
virtual QCString trDate ()=0
virtual QCString trReturns ()=0
virtual QCString trSeeAlso ()=0
virtual QCString trParameters ()=0
virtual QCString trExceptions ()=0
virtual QCString trGeneratedBy ()=0
virtual QCString trNamespaceList ()=0
virtual QCString trNamespaceListDescription (bool extractAll)=0
virtual QCString trFriends ()=0
virtual QCString trRelatedFunctionDocumentation ()=0
virtual QCString trCompoundReference (const char *clName, ClassDef::CompoundType compType, bool isTemplate)=0
virtual QCString trFileReference (const char *fileName)=0
virtual QCString trNamespaceReference (const char *namespaceName)=0
virtual QCString trPublicMembers ()=0
virtual QCString trPublicSlots ()=0
virtual QCString trSignals ()=0
virtual QCString trStaticPublicMembers ()=0
virtual QCString trProtectedMembers ()=0
virtual QCString trProtectedSlots ()=0
virtual QCString trStaticProtectedMembers ()=0
virtual QCString trPrivateMembers ()=0
virtual QCString trPrivateSlots ()=0
virtual QCString trStaticPrivateMembers ()=0
virtual QCString trWriteList (int numEntries)=0
virtual QCString trInheritsList (int numEntries)=0
virtual QCString trInheritedByList (int numEntries)=0
virtual QCString trReimplementedFromList (int numEntries)=0
virtual QCString trReimplementedInList (int numEntries)=0
virtual QCString trNamespaceMembers ()=0
virtual QCString trNamespaceMemberDescription (bool extractAll)=0
virtual QCString trNamespaceIndex ()=0
virtual QCString trNamespaceDocumentation ()=0
virtual QCString trNamespaces ()=0
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)=0
virtual QCString trReturnValues ()=0
virtual QCString trMainPage ()=0
virtual QCString trPageAbbreviation ()=0
virtual QCString trDefinedAtLineInSourceFile ()=0
virtual QCString trDefinedInSourceFile ()=0
virtual QCString trDeprecated ()=0
virtual QCString trCollaborationDiagram (const char *clName)=0
virtual QCString trInclDepGraph (const char *fName)=0
virtual QCString trConstructorDocumentation ()=0
virtual QCString trGotoSourceCode ()=0
virtual QCString trGotoDocumentation ()=0
virtual QCString trPrecondition ()=0
virtual QCString trPostcondition ()=0
virtual QCString trInvariant ()=0
virtual QCString trInitialValue ()=0
virtual QCString trCode ()=0
virtual QCString trGraphicalHierarchy ()=0
virtual QCString trGotoGraphicalHierarchy ()=0
virtual QCString trGotoTextualHierarchy ()=0
virtual QCString trPageIndex ()=0
virtual QCString trNote ()=0
virtual QCString trPublicTypes ()=0
virtual QCString trPublicAttribs ()=0
virtual QCString trStaticPublicAttribs ()=0
virtual QCString trProtectedTypes ()=0
virtual QCString trProtectedAttribs ()=0
virtual QCString trStaticProtectedAttribs ()=0
virtual QCString trPrivateTypes ()=0
virtual QCString trPrivateAttribs ()=0
virtual QCString trStaticPrivateAttribs ()=0
virtual QCString trTodo ()=0
virtual QCString trTodoList ()=0
virtual QCString trReferencedBy ()=0
virtual QCString trRemarks ()=0
virtual QCString trAttention ()=0
virtual QCString trInclByDepGraph ()=0
virtual QCString trSince ()=0
virtual QCString trLegendTitle ()=0
virtual QCString trLegendDocs ()=0
virtual QCString trLegend ()=0
virtual QCString trTest ()=0
virtual QCString trTestList ()=0
virtual QCString trProperties ()=0
virtual QCString trPropertyDocumentation ()=0
virtual QCString trClasses ()=0
virtual QCString trPackage (const char *name)=0
virtual QCString trPackageList ()=0
virtual QCString trPackageListDescription ()=0
virtual QCString trPackages ()=0
virtual QCString trDefineValue ()=0
virtual QCString trBug ()=0
virtual QCString trBugList ()=0
virtual QCString trRTFansicp ()=0
virtual QCString trRTFCharSet ()=0
virtual QCString trRTFGeneralIndex ()=0
virtual QCString trClass (bool first_capital, bool singular)=0
virtual QCString trFile (bool first_capital, bool singular)=0
virtual QCString trNamespace (bool first_capital, bool singular)=0
virtual QCString trGroup (bool first_capital, bool singular)=0
virtual QCString trPage (bool first_capital, bool singular)=0
virtual QCString trMember (bool first_capital, bool singular)=0
virtual QCString trGlobal (bool first_capital, bool singular)=0
virtual QCString trAuthor (bool first_capital, bool singular)=0
virtual QCString trReferences ()=0
virtual QCString trImplementedFromList (int numEntries)=0
virtual QCString trImplementedInList (int numEntries)=0
virtual QCString trRTFTableOfContents ()=0
virtual QCString trDeprecatedList ()=0
virtual QCString trEvents ()=0
virtual QCString trEventDocumentation ()=0
virtual QCString trPackageTypes ()=0
virtual QCString trPackageMembers ()=0
virtual QCString trStaticPackageMembers ()=0
virtual QCString trPackageAttribs ()=0
virtual QCString trStaticPackageAttribs ()=0
virtual QCString trAll ()=0
virtual QCString trCallGraph ()=0
virtual QCString trSearchResultsTitle ()=0
virtual QCString trSearchResults (int numDocuments)=0
virtual QCString trSearchMatches ()=0
virtual QCString trSourceFile (QCString &filename)=0
virtual QCString trDirIndex ()=0
virtual QCString trDirDocumentation ()=0
virtual QCString trDirectories ()=0
virtual QCString trDirDescription ()=0
virtual QCString trDirReference (const char *dirName)=0
virtual QCString trDir (bool first_capital, bool singular)=0
virtual QCString trOverloadText ()=0
virtual QCString trCallerGraph ()=0
virtual QCString trEnumerationValueDocumentation ()=0
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
virtual ~TranslatorAdapterBase ()
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Adapter class for languages that only contain translations up to version 1.5.4.
Definition at line 202 of file translator_adapter.h.
Member Function Documentation
trCompoundIndexFortran()
virtual QCString TranslatorAdapter_1_5_4::trCompoundIndexFortran () inline virtual
Implements Translator.
Definition at line 223 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundIndexFortran().
trCompoundListDescriptionFortran()
virtual QCString TranslatorAdapter_1_5_4::trCompoundListDescriptionFortran () inline virtual
Implements Translator.
Definition at line 217 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundListDescriptionFortran().
trCompoundListFortran()
virtual QCString TranslatorAdapter_1_5_4::trCompoundListFortran () inline virtual
Implements Translator.
Definition at line 211 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundListFortran().
trCompoundMembersDescriptionFortran()
virtual QCString TranslatorAdapter_1_5_4::trCompoundMembersDescriptionFortran (bool extractAll) inline virtual
Implements Translator.
Definition at line 220 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundMembersDescriptionFortran().
trCompoundMembersFortran()
virtual QCString TranslatorAdapter_1_5_4::trCompoundMembersFortran () inline virtual
Implements Translator.
Definition at line 214 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundMembersFortran().
trCompoundReferenceFortran()
virtual QCString TranslatorAdapter_1_5_4::trCompoundReferenceFortran (const char * clName, ClassDef::CompoundType compType, bool isTemplate) inline virtual
Implements Translator.
Definition at line 244 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trCompoundReferenceFortran().
trDataTypes()
virtual QCString TranslatorAdapter_1_5_4::trDataTypes () inline virtual
Implements Translator.
Definition at line 235 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trDataTypes().
trGeneratedFromFilesFortran()
virtual QCString TranslatorAdapter_1_5_4::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline virtual
Implements Translator.
Definition at line 264 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trGeneratedFromFilesFortran().
trMemberFunctionDocumentationFortran()
virtual QCString TranslatorAdapter_1_5_4::trMemberFunctionDocumentationFortran () inline virtual
Implements Translator.
Definition at line 208 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trMemberFunctionDocumentationFortran().
trModule()
virtual QCString TranslatorAdapter_1_5_4::trModule (bool first_capital, bool singular) inline virtual
Implements Translator.
Definition at line 261 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trModule().
trModuleReference()
virtual QCString TranslatorAdapter_1_5_4::trModuleReference (const char * namespaceName) inline virtual
Implements Translator.
Definition at line 249 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trModuleReference().
trModulesIndex()
virtual QCString TranslatorAdapter_1_5_4::trModulesIndex () inline virtual
Implements Translator.
Definition at line 258 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesIndex().
trModulesList()
virtual QCString TranslatorAdapter_1_5_4::trModulesList () inline virtual
Implements Translator.
Definition at line 238 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesList().
trModulesListDescription()
virtual QCString TranslatorAdapter_1_5_4::trModulesListDescription (bool extractAll) inline virtual
Implements Translator.
Definition at line 241 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesListDescription().
trModulesMemberDescription()
virtual QCString TranslatorAdapter_1_5_4::trModulesMemberDescription (bool extractAll) inline virtual
Implements Translator.
Definition at line 255 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesMemberDescription().
trModulesMembers()
virtual QCString TranslatorAdapter_1_5_4::trModulesMembers () inline virtual
Implements Translator.
Definition at line 252 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trModulesMembers().
trSubprogram()
virtual QCString TranslatorAdapter_1_5_4::trSubprogram (bool first_capital, bool singular) inline virtual
Implements Translator.
Definition at line 271 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trSubprogram().
trSubprogramDocumentation()
virtual QCString TranslatorAdapter_1_5_4::trSubprogramDocumentation () inline virtual
Implements Translator.
Definition at line 232 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trSubprogramDocumentation().
trSubprograms()
virtual QCString TranslatorAdapter_1_5_4::trSubprograms () inline virtual
Implements Translator.
Definition at line 229 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trSubprograms().
trType()
virtual QCString TranslatorAdapter_1_5_4::trType (bool first_capital, bool singular) inline virtual
Implements Translator.
Definition at line 268 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trType().
trTypeConstraints()
virtual QCString TranslatorAdapter_1_5_4::trTypeConstraints () inline virtual
Implements Translator.
Definition at line 274 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trTypeConstraints().
trTypeDocumentation()
virtual QCString TranslatorAdapter_1_5_4::trTypeDocumentation () inline virtual
Implements Translator.
Definition at line 226 of file translator_adapter.h.
References TranslatorAdapterBase::english, and TranslatorEnglish::trTypeDocumentation().
updateNeededMessage()
virtual QCString TranslatorAdapter_1_5_4::updateNeededMessage () inline virtual
This method is used to generate a warning message to signal the user that the translation of his/her language of choice needs updating. It must be implemented by the translator adapter class (pure virtual).
See also
createUpdateNeededMessage()
Reimplemented from TranslatorAdapter_1_6_0.
Reimplemented in TranslatorAdapter_1_4_6.
Definition at line 205 of file translator_adapter.h.
References TranslatorAdapterBase::createUpdateNeededMessage(), and Translator::idLanguage().
The documentation for this class was generated from the following file:
src/translator_adapter.h