Doxygen: ModuleListContext Class Reference
ModuleListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
void addModules (const GroupSDict &)
void addModules (const GroupList &)
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static ModuleListContext * alloc ()
Private Member Functions
ModuleListContext ()
~ModuleListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 748 of file context.h.
Constructor & Destructor Documentation
ModuleListContext()
ModuleListContext::ModuleListContext () private
Definition at line 7499 of file context.cpp.
References ModuleListContext::Private::addModules(), p, and Private.
Referenced by alloc().
~ModuleListContext()
ModuleListContext::~ModuleListContext () private
Definition at line 7505 of file context.cpp.
References p.
Member Function Documentation
addModules() [1/2]
void ModuleListContext::addModules (const GroupSDict &)
addModules() [2/2]
void ModuleListContext::addModules (const GroupList &)
addRef()
virtual int ModuleListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 757 of file context.h.
References RefCountedContext::addRef().
alloc()
static ModuleListContext* ModuleListContext::alloc () inline static
Definition at line 751 of file context.h.
References ModuleListContext().
Referenced by generateOutputViaTemplate().
at()
TemplateVariant ModuleListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7516 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int ModuleListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 7511 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * ModuleListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7521 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int ModuleListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 758 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ModuleListContext::p private
Definition at line 766 of file context.h.
Referenced by at(), count(), createIterator(), ModuleListContext(), and ~ModuleListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp