Doxygen: SIntDict< T > Class Template Reference
SIntDict< T > Class Template Reference
Ordered dictionary of elements of type T.
#include <sortdict.h>
Classes
class Iterator
class IteratorDict
Public Member Functions
SIntDict (int size=17)
virtual ~SIntDict ()
void append (int key, const T *d)
void prepend (int key, const T *d)
bool remove (int key)
void sort ()
void inSort (int key, const T *d)
void setAutoDelete (bool val)
T * find (int key)
T * operator[] (int key) const
T * at (uint i)
virtual int compareValues (const T *item1, const T *item2) const
void clear ()
int count () const
Private Attributes
SIntList< T > * m_list
QIntDict< T > * m_dict
int m_sizeIndex
Friends
class Iterator
class IteratorDict
Detailed Description
template<class T>
class SIntDict< T >
Ordered dictionary of elements of type T.
Internally uses a QList<T> and a QIntDict<T>.
Definition at line 74 of file sortdict.h.
Constructor & Destructor Documentation
SIntDict()
template<class T> SIntDict< T >::SIntDict (int size = 17) inline
Create an ordered dictionary.
Parameters
size The size of the dictionary. Should be a prime number for best distribution of elements.
Definition at line 457 of file sortdict.h.
~SIntDict()
template<class T> virtual SIntDict< T >::~SIntDict () inline virtual
Destroys the dictionary
Definition at line 469 of file sortdict.h.
Member Function Documentation
append()
template<class T> void SIntDict< T >::append (int key, const T * d) inline
Appends a compound to the dictionary. The element is owned by the dictionary.
Parameters
key The unique key to use to quicky find the item later on.
d The compound to add.
See also
find()
Definition at line 481 of file sortdict.h.
at()
template<class T> T* SIntDict< T >::at (uint i) inline
Returns the item at position i in the sorted dictionary
Definition at line 567 of file sortdict.h.
clear()
template<class T> void SIntDict< T >::clear () inline
Clears the dictionary. Will delete items if setAutoDelete() was set to TRUE.
See also
setAutoDelete
Definition at line 585 of file sortdict.h.
Referenced by initClassMemberIndices(), initFileMemberIndices(), and initNamespaceMemberIndices().
compareValues()
template<class T> virtual int SIntDict< T >::compareValues (const T * item1, const T * item2) const inline virtual
Function that is used to compare two items when sorting. Overload this to properly sort items.
See also
inSort()
Reimplemented in UsedIndexLetters, MemberGroupSDict, LetterToIndexMap< T >, and LetterToIndexMap< SearchIndexList >.
Definition at line 576 of file sortdict.h.
count()
template<class T> int SIntDict< T >::count () const inline
Returns the number of items stored in the dictionary
Definition at line 593 of file sortdict.h.
find()
template<class T> T* SIntDict< T >::find (int key) inline
Looks up a compound given its key.
Parameters
key The key to identify this element.
Returns
The requested compound or zero if it cannot be found.
See also
append()
Definition at line 555 of file sortdict.h.
Referenced by LetterToIndexMap< SearchIndexList >::append().
inSort()
template<class T> void SIntDict< T >::inSort (int key, const T * d) inline
Inserts a compound into the dictionary in a sorted way.
Parameters
key The unique key to use to quicky find the item later on.
d The compound to add.
See also
find()
Definition at line 532 of file sortdict.h.
Referenced by LetterToIndexMap< SearchIndexList >::append().
operator[]()
template<class T> T* SIntDict< T >::operator[] (int key) const inline
Equavalent to find().
Definition at line 561 of file sortdict.h.
prepend()
template<class T> void SIntDict< T >::prepend (int key, const T * d) inline
Prepend a compound to the dictionary. The element is owned by the dictionary.
Parameters
key The unique key to use to quicky find the item later on.
d The compound to add.
See also
find()
Definition at line 499 of file sortdict.h.
remove()
template<class T> bool SIntDict< T >::remove (int key) inline
Remove an item from the dictionary
Definition at line 512 of file sortdict.h.
setAutoDelete()
template<class T> void SIntDict< T >::setAutoDelete (bool val) inline
Indicates whether or not the dictionary owns its elements
Definition at line 545 of file sortdict.h.
Referenced by addMembersToMemberGroup(), GroupDef::GroupDef(), LetterToIndexMap< SearchIndexList >::LetterToIndexMap(), and NamespaceDef::NamespaceDef().
sort()
template<class T> void SIntDict< T >::sort () inline
Sorts the members of the dictionary. First appending a number of members and then sorting them is faster (O(NlogN) than using inSort() for each member (O(N^2)).
Definition at line 522 of file sortdict.h.
Referenced by writeAlphabeticalClassList(), NamespaceDef::writeMemberGroups(), GroupDef::writeMemberGroups(), FileDef::writeMemberGroups(), and ClassDef::writeMemberGroups().
Friends And Related Function Documentation
Iterator
template<class T> friend class Iterator friend
Definition at line 598 of file sortdict.h.
IteratorDict
template<class T> friend class IteratorDict friend
Definition at line 662 of file sortdict.h.
Member Data Documentation
m_dict
template<class T> QIntDict<T>* SIntDict< T >::m_dict private
Definition at line 449 of file sortdict.h.
Referenced by SIntDict< T >::IteratorDict::IteratorDict(), and SIntDict< SearchIndexList >::~SIntDict().
m_list
template<class T> SIntList<T>* SIntDict< T >::m_list private
Definition at line 448 of file sortdict.h.
Referenced by SIntDict< T >::Iterator::Iterator(), and SIntDict< SearchIndexList >::~SIntDict().
m_sizeIndex
template<class T> int SIntDict< T >::m_sizeIndex private
Definition at line 450 of file sortdict.h.
Referenced by SIntDict< SearchIndexList >::append(), SIntDict< SearchIndexList >::inSort(), SIntDict< SearchIndexList >::prepend(), and SIntDict< SearchIndexList >::SIntDict().
The documentation for this class was generated from the following file:
src/sortdict.h