Doxygen: src/index.cpp File Reference
index.cpp File Reference
This file contains functions for the various index pages.
#include <stdlib.h>
#include <qtextstream.h>
#include <qdatetime.h>
#include <qdir.h>
#include <qregexp.h>
#include "message.h"
#include "index.h"
#include "doxygen.h"
#include "config.h"
#include "filedef.h"
#include "outputlist.h"
#include "util.h"
#include "groupdef.h"
#include "language.h"
#include "htmlgen.h"
#include "htmlhelp.h"
#include "ftvhelp.h"
#include "dot.h"
#include "pagedef.h"
#include "dirdef.h"
#include "vhdldocgen.h"
#include "layout.h"
#include "memberlist.h"
#include "classlist.h"
#include "namespacedef.h"
#include "filename.h"
Classes
class MemberIndexList
class PrefixIgnoreClassList
Special class list where sorting takes IGNORE_PREFIX into account.
class AlphaIndexTableCell
Class representing a cell in the alphabetical class index.
class AlphaIndexTableRows
Class representing a row in the alphabetical class index.
class AlphaIndexTableRowsIterator
Iterator for the cells in a row of the alphabetical class index.
class AlphaIndexTableColumns
Class representing the columns in the alphabetical class index.
class UsedIndexLetters
struct CmhlInfo
Helper class representing a class member in the navigation menu.
struct FmhlInfo
Helper class representing a file member in the navigation menu.
struct NmhlInfo
Helper class representing a namespace member in the navigation menu.
Macros
#define MAX_ITEMS_BEFORE_MULTIPAGE_INDEX 200
#define MAX_ITEMS_BEFORE_QUICK_INDEX 30
#define NEXT_ROW()
Functions
static int countClassHierarchy ()
static void countFiles (int &htmlFiles, int &files)
static int countGroups ()
static int countDirs ()
static int countNamespaces ()
static int countAnnotatedClasses (int *cp)
static void countRelatedPages (int &docPages, int &indexPages)
void countDataStructures ()
static void startIndexHierarchy (OutputList &ol, int level)
static void endIndexHierarchy (OutputList &ol, int level)
static void startQuickIndexList (OutputList &ol, bool letterTabs=FALSE)
static void endQuickIndexList (OutputList &ol)
static void startQuickIndexItem (OutputList &ol, const char *l, bool hl, bool compact, bool &first)
static void endQuickIndexItem (OutputList &ol)
QCString fixSpaces (const QCString &s)
void startTitle (OutputList &ol, const char *fileName, Definition *def)
void endTitle (OutputList &ol, const char *fileName, const char *name)
void startFile (OutputList &ol, const char *name, const char *manName, const char *title, HighlightedItem hli, bool additionalIndices, const char *altSidebarName)
void endFile (OutputList &ol, bool skipNavIndex, bool skipEndContents, const QCString &navPath)
void endFileWithNavPath (Definition *d, OutputList &ol)
template<class T >
void addMembersToIndex (T *def, LayoutDocManager::LayoutPart part, const QCString &name, const QCString &anchor, bool addToIndex=TRUE, bool preventSeparateIndex=FALSE)
static void writeClassTree (OutputList &ol, const BaseClassList *bcl, bool hideSuper, int level, FTVHelp *ftv, bool addToIndex)
static bool dirHasVisibleChildren (DirDef *dd)
static void writeDirTreeNode (OutputList &ol, DirDef *dd, int level, FTVHelp *ftv, bool addToIndex)
static void writeDirHierarchy (OutputList &ol, FTVHelp *ftv, bool addToIndex)
static void writeClassTreeForList (OutputList &ol, ClassSDict *cl, bool &started, FTVHelp *ftv, bool addToIndex)
static void writeClassHierarchy (OutputList &ol, FTVHelp *ftv, bool addToIndex)
static int countClassesInTreeList (const ClassSDict &cl)
static void writeHierarchicalIndex (OutputList &ol)
static void writeGraphicalClassHierarchy (OutputList &ol)
static void writeSingleFileIndex (OutputList &ol, FileDef *fd)
static void writeFileIndex (OutputList &ol)
void writeClassTree (ClassSDict *clDict, FTVHelp *ftv, bool addToIndex, bool globalOnly)
static void writeNamespaceTree (NamespaceSDict *nsDict, FTVHelp *ftv, bool rootOnly, bool showClasses, bool addToIndex)
static void writeNamespaceIndex (OutputList &ol)
static void writeAnnotatedClassList (OutputList &ol)
static QCString letterToLabel (uint startLetter)
static void writeAlphabeticalClassList (OutputList &ol)
static void writeAlphabeticalIndex (OutputList &ol)
static void writeAnnotatedIndex (OutputList &ol)
static void writeClassLinkForMember (OutputList &ol, MemberDef *md, const char *separator, QCString &prevClassName)
static void writeFileLinkForMember (OutputList &ol, MemberDef *md, const char *separator, QCString &prevFileName)
static void writeNamespaceLinkForMember (OutputList &ol, MemberDef *md, const char *separator, QCString &prevNamespaceName)
static void writeMemberList (OutputList &ol, bool useSections, int page, const LetterToIndexMap< MemberIndexList > &memberLists, DefinitionIntf::DefType type)
void initClassMemberIndices ()
void addClassMemberNameToIndex (MemberDef *md)
void initNamespaceMemberIndices ()
void addNamespaceMemberNameToIndex (MemberDef *md)
void initFileMemberIndices ()
void addFileMemberNameToIndex (MemberDef *md)
static void writeQuickMemberIndex (OutputList &ol, const LetterToIndexMap< MemberIndexList > &charUsed, uint page, QCString fullName, bool multiPage)
static const CmhlInfo * getCmhlInfo (int hl)
static void writeClassMemberIndexFiltered (OutputList &ol, ClassMemberHighlight hl)
static void writeClassMemberIndex (OutputList &ol)
static const FmhlInfo * getFmhlInfo (int hl)
static void writeFileMemberIndexFiltered (OutputList &ol, FileMemberHighlight hl)
static void writeFileMemberIndex (OutputList &ol)
static const NmhlInfo * getNmhlInfo (int hl)
static void writeNamespaceMemberIndexFiltered (OutputList &ol, NamespaceMemberHighlight hl)
static void writeNamespaceMemberIndex (OutputList &ol)
static void writeExampleIndex (OutputList &ol)
static bool mainPageHasOwnTitle ()
static void writePages (PageDef *pd, FTVHelp *ftv)
static void writePageIndex (OutputList &ol)
void writeGraphInfo (OutputList &ol)
static void writeGroupTreeNode (OutputList &ol, GroupDef *gd, int level, FTVHelp *ftv, bool addToIndex)
static void writeGroupHierarchy (OutputList &ol, FTVHelp *ftv, bool addToIndex)
static void writeGroupIndex (OutputList &ol)
static void writeUserGroupStubPage (OutputList &ol, LayoutNavEntry *lne)
static void writeIndex (OutputList &ol)
static void writeIndexHierarchyEntries (OutputList &ol, const QList< LayoutNavEntry > &entries)
static bool quickLinkVisible (LayoutNavEntry::Kind kind)
template<class T >
void renderMemberIndicesAsJs (FTextStream &t, int total, const int *numDocumented, const LetterToIndexMap< MemberIndexList > *memberLists, const T *(*getInfo)(int hl))
static bool renderQuickLinksAsJs (FTextStream &t, LayoutNavEntry *root, bool first)
static void writeMenuData ()
void writeIndexHierarchy (OutputList &ol)
Variables
int annotatedClasses
int annotatedClassesPrinted
int hierarchyClasses
int documentedFiles
int documentedGroups
int documentedNamespaces
int indexedPages
int documentedClassMembers [CMHL_Total]
int documentedFileMembers [FMHL_Total]
int documentedNamespaceMembers [NMHL_Total]
int documentedHtmlFiles
int documentedPages
int documentedDirs
static LetterToIndexMap< MemberIndexList > g_memberIndexLetterUsed [CMHL_Total]
static LetterToIndexMap< MemberIndexList > g_fileIndexLetterUsed [FMHL_Total]
static LetterToIndexMap< MemberIndexList > g_namespaceIndexLetterUsed [NMHL_Total]
const int maxItemsBeforeQuickIndex = MAX_ITEMS_BEFORE_QUICK_INDEX
static QArray< bool > indexWritten
Detailed Description
This file contains functions for the various index pages.
Definition in file index.cpp.
Macro Definition Documentation
MAX_ITEMS_BEFORE_MULTIPAGE_INDEX
#define MAX_ITEMS_BEFORE_MULTIPAGE_INDEX 200
Definition at line 51 of file index.cpp.
Referenced by renderMemberIndicesAsJs(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), and writeNamespaceMemberIndexFiltered().
MAX_ITEMS_BEFORE_QUICK_INDEX
#define MAX_ITEMS_BEFORE_QUICK_INDEX 30
Definition at line 52 of file index.cpp.
NEXT_ROW
#define NEXT_ROW ()
Value:
do                                         \
    {                                          \
      if (row>maxRows) maxRows=row;            \
      if (row>=rows && col<columns)            \
      {                                        \
        col++;                                 \
        row=0;                                 \
        tableRows = new AlphaIndexTableRows;   \
        tableColumns.append(tableRows);        \
      }                                        \
    }                                          \
    while(0)                                   \
Referenced by writeAlphabeticalClassList().
Function Documentation
addClassMemberNameToIndex()
void addClassMemberNameToIndex (MemberDef * md)
Definition at line 2265 of file index.cpp.
References LetterToIndexMap< T >::append(), CMHL_All, CMHL_Enums, CMHL_EnumValues, CMHL_Events, CMHL_Functions, CMHL_Properties, CMHL_Related, CMHL_Typedefs, CMHL_Variables, Config_getBool, documentedClassMembers, MemberDef::getClassDef(), MemberDef::getEnumScope(), getPrefixIndex(), getUtf8CodeToLower(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isEvent(), MemberDef::isForeign(), MemberDef::isFriend(), MemberDef::isFunction(), ClassDef::isLinkableInProject(), MemberDef::isLinkableInProject(), MemberDef::isProperty(), MemberDef::isRelated(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), Definition::name(), ClassDef::templateMaster(), and MemberDef::typeString().
Referenced by addMembersToIndex().
addFileMemberNameToIndex()
void addFileMemberNameToIndex (MemberDef * md)
Definition at line 2407 of file index.cpp.
References LetterToIndexMap< T >::append(), documentedFileMembers, FMHL_All, FMHL_Defines, FMHL_Enums, FMHL_EnumValues, FMHL_Functions, FMHL_Typedefs, FMHL_Variables, MemberDef::getEnumScope(), MemberDef::getFileDef(), getPrefixIndex(), getUtf8CodeToLower(), MemberDef::isDefine(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFunction(), FileDef::isLinkableInProject(), MemberDef::isLinkableInProject(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), and Definition::name().
Referenced by addMembersToIndex().
addMembersToIndex()
template<class T > void addMembersToIndex (T * def, LayoutDocManager::LayoutPart part, const QCString & name, const QCString & anchor, bool addToIndex = TRUE, bool preventSeparateIndex = FALSE)
Definition at line 300 of file index.cpp.
References IndexList::addContentsItem(), MemberDef::anchor(), ClassDef::anchor(), LayoutDocManager::Class, LayoutDocEntry::ClassNestedClasses, Config_getBool, IndexList::decContentsDepth(), ClassDef::displayName(), MemberDef::enumFieldList(), LayoutDocEntry::FileClasses, Definition::getOuterScope(), MemberDef::getOutputFileBase(), MemberDef::getReference(), Doxygen::globalScope, MemberDef::hasDocumentation(), IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), ClassDef::isEmbeddedInOuterScope(), MemberDef::isEnumerate(), ClassDef::isLinkable(), ClassDef::isSimple(), MemberDef::isStatic(), SDict< ClassDef >::Iterator, LayoutDocEntry::kind(), LayoutDocEntry::MemberDef, Definition::name(), LayoutDocEntry::NamespaceClasses, Definition::partOfGroups(), LayoutDocEntryMemberDef::type, DefinitionIntf::TypeClass, and DefinitionIntf::TypeGroup.
Referenced by writeClassTree(), writeDirHierarchy(), writeDirTreeNode(), and writeGroupTreeNode().
addNamespaceMemberNameToIndex()
void addNamespaceMemberNameToIndex (MemberDef * md)
Definition at line 2350 of file index.cpp.
References LetterToIndexMap< T >::append(), documentedNamespaceMembers, MemberDef::getEnumScope(), MemberDef::getNamespaceDef(), getPrefixIndex(), getUtf8CodeToLower(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFunction(), NamespaceDef::isLinkableInProject(), MemberDef::isLinkableInProject(), MemberDef::isStrong(), MemberDef::isTypedef(), MemberDef::isVariable(), Definition::name(), NMHL_All, NMHL_Enums, NMHL_EnumValues, NMHL_Functions, NMHL_Typedefs, and NMHL_Variables.
Referenced by addMembersToIndex().
countAnnotatedClasses()
static int countAnnotatedClasses (int * cp) static
Definition at line 1556 of file index.cpp.
References Doxygen::classSDict, ClassDef::isEmbeddedInOuterScope(), ClassDef::isLinkableInProject(), SDict< ClassDef >::Iterator, and ClassDef::templateMaster().
Referenced by countDataStructures().
countClassesInTreeList()
static int countClassesInTreeList (const ClassSDict & cl) static
Definition at line 923 of file index.cpp.
References ClassDef::baseClasses(), hasVisibleRoot(), ClassDef::isVisibleInHierarchy(), SDict< ClassDef >::Iterator, and ClassDef::subClasses().
Referenced by countClassHierarchy().
countClassHierarchy()
static int countClassHierarchy () static
Definition at line 944 of file index.cpp.
References Doxygen::classSDict, countClassesInTreeList(), Doxygen::hiddenClasses, and initClassHierarchy().
Referenced by countDataStructures().
countDataStructures()
void countDataStructures ()
Definition at line 77 of file index.cpp.
References annotatedClasses, annotatedClassesPrinted, countAnnotatedClasses(), countClassHierarchy(), countDirs(), countFiles(), countGroups(), countNamespaces(), countRelatedPages(), documentedDirs, documentedFiles, documentedGroups, documentedHtmlFiles, documentedNamespaces, documentedPages, hierarchyClasses, and indexedPages.
Referenced by parseInput().
countDirs()
static int countDirs () static
Definition at line 3237 of file index.cpp.
References Doxygen::directories, DirDef::isLinkableInProject(), and DirDef::visited.
Referenced by countDataStructures().
countFiles()
static void countFiles (int & htmlFiles, int & files) static
Definition at line 1063 of file index.cpp.
References doc, fileVisibleInIndex(), and Doxygen::inputNameList.
Referenced by countDataStructures().
countGroups()
static int countGroups () static
Definition at line 3219 of file index.cpp.
References Doxygen::groupSDict, Definition::isReference(), SDict< GroupDef >::Iterator, and GroupDef::visited.
Referenced by countDataStructures().
countNamespaces()
static int countNamespaces () static
Definition at line 1306 of file index.cpp.
References NamespaceDef::isLinkableInProject(), SDict< NamespaceDef >::Iterator, and Doxygen::namespaceSDict.
Referenced by countDataStructures().
countRelatedPages()
static void countRelatedPages (int & docPages, int & indexPages) static
Definition at line 3076 of file index.cpp.
References PageDef::documentedPage(), SDict< PageDef >::Iterator, Doxygen::pageSDict, and PageDef::visibleInIndex().
Referenced by countDataStructures().
dirHasVisibleChildren()
static bool dirHasVisibleChildren (DirDef * dd) static
Definition at line 541 of file index.cpp.
References fileVisibleInIndex(), DirDef::getFiles(), Definition::hasDocumentation(), and DirDef::subDirs().
Referenced by writeDirTreeNode().
endFile()
void endFile (OutputList & ol, bool skipNavIndex, bool skipEndContents, const QCString & navPath)
Definition at line 264 of file index.cpp.
References Config_getBool, OutputList::disableAllBut(), OutputList::endContents(), OutputList::endFile(), OutputGenerator::Html, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::writeFooter(), and OutputList::writeString().
Referenced by endFileWithNavPath(), generateExampleDocs(), writeAlphabeticalIndex(), writeAnnotatedIndex(), writeClassMemberIndexFiltered(), PageDef::writeDocumentation(), GroupDef::writeDocumentation(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalIndex(), writeIndex(), ClassDef::writeMemberList(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), and writeUserGroupStubPage().
endFileWithNavPath()
void endFileWithNavPath (Definition * d, OutputList & ol)
Definition at line 283 of file index.cpp.
References Config_getBool, OutputList::disableAllBut(), endFile(), OutputGenerator::Html, Definition::navigationPathAsString(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), and OutputList::writeString().
Referenced by NamespaceDef::writeDocumentation(), PageDef::writeDocumentation(), DirDef::writeDocumentation(), FileDef::writeDocumentation(), DirRelation::writeDocumentation(), ClassDef::writeDocumentation(), MemberList::writeDocumentationPage(), and FileDef::writeSource().
endIndexHierarchy()
static void endIndexHierarchy (OutputList & ol, int level) static
Definition at line 104 of file index.cpp.
References OutputList::disable(), OutputList::enableAll(), OutputList::endIndexList(), OutputList::endItemList(), OutputGenerator::Html, OutputGenerator::Latex, OutputGenerator::Man, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), and OutputGenerator::RTF.
Referenced by writeClassHierarchy(), writeClassTree(), writeDirHierarchy(), writeDirTreeNode(), writeGroupHierarchy(), and writeGroupTreeNode().
endQuickIndexItem()
static void endQuickIndexItem (OutputList & ol) static
Definition at line 213 of file index.cpp.
References OutputList::writeString().
Referenced by writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeNamespaceMemberIndexFiltered(), and writeQuickMemberIndex().
endQuickIndexList()
static void endQuickIndexList (OutputList & ol) static
Definition at line 170 of file index.cpp.
References OutputList::writeString().
Referenced by writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeNamespaceMemberIndexFiltered(), and writeQuickMemberIndex().
endTitle()
void endTitle (OutputList & ol, const char * fileName, const char * name)
Definition at line 237 of file index.cpp.
References OutputList::endHeaderSection(), OutputList::endTitleHead(), and OutputList::popGeneratorState().
Referenced by generateExampleDocs(), writeAlphabeticalIndex(), writeAnnotatedIndex(), NamespaceDef::writeDocumentation(), PageDef::writeDocumentation(), DirDef::writeDocumentation(), FileDef::writeDocumentation(), ClassDef::writeDocumentation(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalIndex(), ClassDef::writeMemberList(), writeNamespaceIndex(), writePageIndex(), FileDef::writeSource(), and writeUserGroupStubPage().
fixSpaces()
QCString fixSpaces (const QCString & s)
Definition at line 223 of file index.cpp.
References substitute().
Referenced by renderQuickLinksAsTabs(), renderQuickLinksAsTree(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeNamespaceMemberIndexFiltered(), and writeUserGroupStubPage().
getCmhlInfo()
static const CmhlInfo* getCmhlInfo (int hl) static
Definition at line 2498 of file index.cpp.
References Config_getBool, theTranslator, Translator::trAll(), Translator::trEnumerations(), Translator::trEnumerationValues(), Translator::trEvents(), VhdlDocGen::trFunctionAndProc(), Translator::trFunctions(), Translator::trProperties(), Translator::trRelatedFunctions(), Translator::trSubprograms(), Translator::trTypedefs(), and Translator::trVariables().
Referenced by renderQuickLinksAsJs(), and writeClassMemberIndexFiltered().
getFmhlInfo()
static const FmhlInfo* getFmhlInfo (int hl) static
Definition at line 2677 of file index.cpp.
References Config_getBool, theTranslator, Translator::trAll(), Translator::trDefines(), Translator::trEnumerations(), Translator::trEnumerationValues(), VhdlDocGen::trFunctionAndProc(), Translator::trFunctions(), Translator::trSubprograms(), Translator::trTypedefs(), and Translator::trVariables().
Referenced by renderQuickLinksAsJs(), and writeFileMemberIndexFiltered().
getNmhlInfo()
static const NmhlInfo* getNmhlInfo (int hl) static
Definition at line 2845 of file index.cpp.
References Config_getBool, theTranslator, Translator::trAll(), Translator::trEnumerations(), Translator::trEnumerationValues(), VhdlDocGen::trFunctionAndProc(), Translator::trFunctions(), Translator::trSubprograms(), Translator::trTypedefs(), and Translator::trVariables().
Referenced by renderQuickLinksAsJs(), and writeNamespaceMemberIndexFiltered().
initClassMemberIndices()
void initClassMemberIndices ()
Definition at line 2255 of file index.cpp.
References SIntDict< T >::clear(), CMHL_Total, and documentedClassMembers.
Referenced by initDoxygen().
initFileMemberIndices()
void initFileMemberIndices ()
Definition at line 2397 of file index.cpp.
References SIntDict< T >::clear(), documentedFileMembers, and NMHL_Total.
Referenced by initDoxygen().
initNamespaceMemberIndices()
void initNamespaceMemberIndices ()
Definition at line 2340 of file index.cpp.
References SIntDict< T >::clear(), documentedNamespaceMembers, and NMHL_Total.
Referenced by initDoxygen().
letterToLabel()
static QCString letterToLabel (uint startLetter) static
Definition at line 1641 of file index.cpp.
References isId().
Referenced by renderMemberIndicesAsJs(), writeAlphabeticalClassList(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeMemberList(), writeNamespaceMemberIndexFiltered(), and writeQuickMemberIndex().
mainPageHasOwnTitle()
static bool mainPageHasOwnTitle () static
Definition at line 3096 of file index.cpp.
References Config_getString, filterTitle(), Doxygen::mainPage, and mainPageHasTitle().
Referenced by writePages().
quickLinkVisible()
static bool quickLinkVisible (LayoutNavEntry::Kind kind) static
Definition at line 4290 of file index.cpp.
References annotatedClasses, LayoutNavEntry::Classes, LayoutNavEntry::ClassHierarchy, LayoutNavEntry::ClassIndex, LayoutNavEntry::ClassList, LayoutNavEntry::ClassMembers, CMHL_All, Config_getBool, SDict< T >::count(), documentedClassMembers, documentedFileMembers, documentedGroups, documentedHtmlFiles, documentedNamespaceMembers, documentedNamespaces, LayoutNavEntry::Examples, Doxygen::exampleSDict, LayoutNavEntry::FileGlobals, LayoutNavEntry::FileList, LayoutNavEntry::Files, FMHL_All, hierarchyClasses, indexedPages, LayoutNavEntry::MainPage, LayoutNavEntry::Modules, LayoutNavEntry::NamespaceList, LayoutNavEntry::NamespaceMembers, LayoutNavEntry::Namespaces, NMHL_All, LayoutNavEntry::Pages, LayoutNavEntry::User, and LayoutNavEntry::UserGroup.
Referenced by renderQuickLinksAsJs().
renderMemberIndicesAsJs()
template<class T > void renderMemberIndicesAsJs (FTextStream & t, int total, const int * numDocumented, const LetterToIndexMap< MemberIndexList > * memberLists, const T *(*)(int hl) getInfo)
Definition at line 4319 of file index.cpp.
References convertToJSString(), SIntDict< T >::Iterator::current(), endl(), Doxygen::htmlFileExtension, MemberIndexList::letter(), letterToLabel(), MAX_ITEMS_BEFORE_MULTIPAGE_INDEX, maxItemsBeforeQuickIndex, and SIntDict< T >::Iterator::toFirst().
Referenced by renderQuickLinksAsJs().
renderQuickLinksAsJs()
static bool renderQuickLinksAsJs (FTextStream & t, LayoutNavEntry * root, bool first) static
Definition at line 4380 of file index.cpp.
References LayoutNavEntry::children(), LayoutNavEntry::ClassMembers, CMHL_Total, convertToJSString(), documentedClassMembers, documentedFileMembers, documentedNamespaceMembers, endl(), LayoutNavEntry::FileGlobals, FMHL_Total, getCmhlInfo(), getFmhlInfo(), getNmhlInfo(), LayoutNavEntry::NamespaceMembers, NMHL_Total, quickLinkVisible(), and renderMemberIndicesAsJs().
Referenced by writeMenuData().
startFile()
void startFile (OutputList & ol, const char * name, const char * manName, const char * title, HighlightedItem hli, bool additionalIndices, const char * altSidebarName)
Definition at line 244 of file index.cpp.
References Config_getBool, OutputList::endQuickIndices(), resetDotNodeNumbering(), OutputList::startFile(), OutputList::startQuickIndices(), OutputList::writeQuickLinks(), OutputList::writeSearchInfo(), and OutputList::writeSplitBar().
Referenced by generateExampleDocs(), writeAlphabeticalIndex(), writeAnnotatedIndex(), NamespaceDef::writeDocumentation(), PageDef::writeDocumentation(), GroupDef::writeDocumentation(), DirDef::writeDocumentation(), FileDef::writeDocumentation(), DirRelation::writeDocumentation(), ClassDef::writeDocumentation(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalIndex(), writeIndex(), ClassDef::writeMemberList(), writeNamespaceIndex(), writePageIndex(), FileDef::writeSource(), and writeUserGroupStubPage().
startIndexHierarchy()
static void startIndexHierarchy (OutputList & ol, int level) static
Definition at line 91 of file index.cpp.
References OutputList::disable(), OutputList::enableAll(), OutputGenerator::Html, OutputGenerator::Latex, OutputGenerator::Man, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startIndexList(), and OutputList::startItemList().
Referenced by writeClassTree(), writeClassTreeForList(), writeDirHierarchy(), writeDirTreeNode(), writeGroupHierarchy(), and writeGroupTreeNode().
startQuickIndexItem()
static void startQuickIndexItem (OutputList & ol, const char * l, bool hl, bool compact, bool & first) static
Definition at line 180 of file index.cpp.
References OutputList::writeString().
Referenced by writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeNamespaceMemberIndexFiltered(), and writeQuickMemberIndex().
startQuickIndexList()
static void startQuickIndexList (OutputList & ol, bool letterTabs = FALSE) static
Definition at line 149 of file index.cpp.
References OutputList::writeString().
Referenced by writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeNamespaceMemberIndexFiltered(), and writeQuickMemberIndex().
startTitle()
void startTitle (OutputList & ol, const char * fileName, Definition * def)
Definition at line 228 of file index.cpp.
References OutputList::disable(), OutputGenerator::Man, OutputList::pushGeneratorState(), OutputList::startHeaderSection(), OutputList::startTitleHead(), and Definition::writeSummaryLinks().
Referenced by generateExampleDocs(), writeAlphabeticalIndex(), writeAnnotatedIndex(), NamespaceDef::writeDocumentation(), PageDef::writeDocumentation(), DirDef::writeDocumentation(), FileDef::writeDocumentation(), ClassDef::writeDocumentation(), writeExampleIndex(), writeFileIndex(), writeGraphicalClassHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalIndex(), ClassDef::writeMemberList(), writeNamespaceIndex(), writePageIndex(), FileDef::writeSource(), and writeUserGroupStubPage().
writeAlphabeticalClassList()
static void writeAlphabeticalClassList (OutputList & ol) static
Definition at line 1761 of file index.cpp.
References UsedIndexLetters::add(), ClassDef::anchor(), annotatedClasses, LetterToIndexMap< T >::append(), AlphaIndexTableCell::classDef(), ClassDef::className(), Doxygen::classSDict, Config_getInt, SIntDict< T >::Iterator::current(), OutputList::docify(), VhdlDocGen::ENTITYCLASS, extractNamespaceName(), Definition::getLanguage(), getLanguageSpecificSeparator(), NamespaceDef::getOutputFileBase(), ClassDef::getOutputFileBase(), getPrefixIndex(), ClassDef::getReference(), Definition::getReference(), getResolvedNamespace(), getUtf8CodeToLower(), NamespaceDef::isLinkable(), ClassDef::isLinkableInProject(), SDict< ClassDef >::Iterator, PrefixIgnoreClassList::letter(), AlphaIndexTableCell::letter(), letterToLabel(), Definition::name(), NEXT_ROW, ClassDef::protection(), AlphaIndexTableCell::row(), SIntDict< T >::sort(), SrcLangExt_VHDL, substitute(), ClassDef::templateMaster(), SIntDict< T >::Iterator::toFirst(), OutputList::writeNonBreakableSpace(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writeAlphabeticalIndex().
writeAlphabeticalIndex()
static void writeAlphabeticalIndex (OutputList & ol) static
Definition at line 2009 of file index.cpp.
References IndexList::addContentsItem(), annotatedClasses, LayoutNavEntry::ClassIndex, OutputList::disableAllBut(), endFile(), endTitle(), LayoutNavEntry::find(), HLI_Classes, OutputGenerator::Html, Doxygen::indexList, LayoutDocManager::instance(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputList::startContents(), startFile(), startTitle(), theTranslator, LayoutNavEntry::title(), Translator::trCompoundIndex(), LayoutNavEntry::visible(), and writeAlphabeticalClassList().
Referenced by writeIndexHierarchyEntries().
writeAnnotatedClassList()
static void writeAnnotatedClassList (OutputList & ol) static
Definition at line 1578 of file index.cpp.
References ClassDef::anchor(), Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Doxygen::classSDict, OutputList::disable(), ClassDef::displayName(), OutputList::docify(), OutputList::endIndexKey(), OutputList::endIndexList(), OutputList::endIndexValue(), OutputList::generateDoc(), Definition::getLanguage(), ClassDef::getOutputFileBase(), VhdlDocGen::getProtectionName(), ClassDef::isEmbeddedInOuterScope(), ClassDef::isLinkableInProject(), SDict< ClassDef >::Iterator, OutputGenerator::Latex, VhdlDocGen::PACKAGECLASS, VhdlDocGen::PACKBODYCLASS, OutputList::popGeneratorState(), ClassDef::protection(), OutputList::pushGeneratorState(), OutputGenerator::RTF, SrcLangExt_VHDL, OutputList::startIndexKey(), OutputList::startIndexList(), OutputList::startIndexValue(), ClassDef::templateMaster(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writeAnnotatedIndex().
writeAnnotatedIndex()
static void writeAnnotatedIndex (OutputList & ol) static
Definition at line 2038 of file index.cpp.
References IndexList::addContentsItem(), annotatedClasses, annotatedClassesPrinted, LayoutNavEntry::Classes, LayoutNavEntry::ClassList, Doxygen::classSDict, IndexList::decContentsDepth(), OutputList::disable(), IndexList::disable(), OutputList::disableAllBut(), IndexList::enable(), endFile(), OutputList::endTextBlock(), endTitle(), LayoutNavEntry::find(), FTVHelp::generateTreeViewInline(), HLI_Annotated, OutputGenerator::Html, IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::intro(), OutputGenerator::Latex, OutputGenerator::Man, Doxygen::namespaceSDict, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputGenerator::RTF, OutputList::startContents(), startFile(), OutputList::startTextBlock(), startTitle(), theTranslator, LayoutNavEntry::title(), Translator::trCompoundList(), Translator::trCompoundListDescription(), LayoutNavEntry::visible(), writeAnnotatedClassList(), writeClassTree(), writeNamespaceTree(), and OutputList::writeString().
Referenced by writeIndexHierarchyEntries().
writeClassHierarchy()
static void writeClassHierarchy (OutputList & ol, FTVHelp * ftv, bool addToIndex) static
Definition at line 895 of file index.cpp.
References Doxygen::classSDict, IndexList::decContentsDepth(), OutputList::disable(), endIndexHierarchy(), Doxygen::hiddenClasses, OutputGenerator::Html, Doxygen::indexList, initClassHierarchy(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), and writeClassTreeForList().
Referenced by writeHierarchicalIndex().
writeClassLinkForMember()
static void writeClassLinkForMember (OutputList & ol, MemberDef * md, const char * separator, QCString & prevClassName) static
Definition at line 2115 of file index.cpp.
References MemberDef::anchor(), ClassDef::displayName(), OutputList::docify(), MemberDef::getClassDef(), MemberDef::getOutputFileBase(), MemberDef::getReference(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writeMemberList().
writeClassMemberIndex()
static void writeClassMemberIndex (OutputList & ol) static
Definition at line 2641 of file index.cpp.
References IndexList::addContentsItem(), LayoutNavEntry::ClassMembers, CMHL_All, CMHL_Enums, CMHL_EnumValues, CMHL_Events, CMHL_Functions, CMHL_Properties, CMHL_Related, CMHL_Typedefs, CMHL_Variables, IndexList::decContentsDepth(), documentedClassMembers, LayoutNavEntry::find(), IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutDocManager::rootNavEntry(), theTranslator, LayoutNavEntry::title(), Translator::trCompoundMembers(), LayoutNavEntry::visible(), and writeClassMemberIndexFiltered().
Referenced by writeIndexHierarchyEntries().
writeClassMemberIndexFiltered()
static void writeClassMemberIndexFiltered (OutputList & ol, ClassMemberHighlight hl) static
Definition at line 2520 of file index.cpp.
References IndexList::addContentsItem(), LayoutNavEntry::ClassMembers, CMHL_All, CMHL_Total, Config_getBool, SIntDict< T >::Iterator::current(), IndexList::decContentsDepth(), OutputList::disableAllBut(), documentedClassMembers, endFile(), endQuickIndexItem(), endQuickIndexList(), OutputList::endQuickIndices(), OutputList::endTextBlock(), LayoutNavEntry::find(), fixSpaces(), CmhlInfo::fname, getCmhlInfo(), HLI_Functions, OutputGenerator::Html, Doxygen::htmlFileExtension, IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::intro(), MemberIndexList::letter(), letterToLabel(), MAX_ITEMS_BEFORE_MULTIPAGE_INDEX, maxItemsBeforeQuickIndex, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputList::startContents(), OutputList::startFile(), startQuickIndexItem(), startQuickIndexList(), OutputList::startQuickIndices(), OutputList::startTextBlock(), theTranslator, LayoutNavEntry::title(), CmhlInfo::title, SIntDict< T >::Iterator::toFirst(), Translator::trCompoundMembers(), Translator::trCompoundMembersDescription(), DefinitionIntf::TypeClass, LayoutNavEntry::visible(), writeMemberList(), OutputList::writeQuickLinks(), writeQuickMemberIndex(), OutputList::writeSearchInfo(), OutputList::writeSplitBar(), and OutputList::writeString().
Referenced by writeClassMemberIndex().
writeClassTree() [1/2]
static void writeClassTree (OutputList & ol, const BaseClassList * bcl, bool hideSuper, int level, FTVHelp * ftv, bool addToIndex) static
Generates HTML Help tree of classes
Definition at line 424 of file index.cpp.
References FTVHelp::addContentsItem(), IndexList::addContentsItem(), ClassDef::anchor(), ClassDef::baseClasses(), classHasVisibleChildren(), FTVHelp::decContentsDepth(), IndexList::decContentsDepth(), ClassDef::displayName(), OutputList::docify(), endIndexHierarchy(), OutputList::endIndexItem(), OutputList::endIndexListItem(), OutputList::endTypewriter(), VhdlDocGen::ENTITYCLASS, Definition::getLanguage(), ClassDef::getOutputFileBase(), ClassDef::getReference(), hasVisibleRoot(), FTVHelp::incContentsDepth(), IndexList::incContentsDepth(), Doxygen::indexList, ClassDef::isLinkable(), ClassDef::isReference(), ClassDef::isVisibleInHierarchy(), Definition::name(), OutputList::parseText(), ClassDef::protection(), SrcLangExt_VHDL, startIndexHierarchy(), OutputList::startIndexItem(), OutputList::startIndexListItem(), OutputList::startTypewriter(), ClassDef::subClasses(), and ClassDef::visited.
Referenced by writeAnnotatedIndex(), writeClassTree(), writeClassTreeForList(), and writeNamespaceTree().
writeClassTree() [2/2]
void writeClassTree (ClassSDict * clDict, FTVHelp * ftv, bool addToIndex, bool globalOnly)
Definition at line 1320 of file index.cpp.
References FTVHelp::addContentsItem(), addMembersToIndex(), ClassDef::anchor(), VhdlDocGen::ARCHITECTURECLASS, LayoutDocManager::Class, classVisibleInIndex(), FTVHelp::decContentsDepth(), DefinitionIntf::definitionType(), ClassDef::displayName(), ClassDef::getClassSDict(), Definition::getLanguage(), Definition::getOuterScope(), ClassDef::getOutputFileBase(), ClassDef::getReference(), Doxygen::globalScope, FTVHelp::incContentsDepth(), ClassDef::isSimple(), SDict< ClassDef >::Iterator, Definition::name(), VhdlDocGen::PACKAGECLASS, VhdlDocGen::PACKBODYCLASS, Definition::partOfGroups(), ClassDef::protection(), ClassDef::setClassName(), SrcLangExt_VHDL, ClassDef::templateMaster(), DefinitionIntf::TypeClass, and writeClassTree().
writeClassTreeForList()
static void writeClassTreeForList (OutputList & ol, ClassSDict * cl, bool & started, FTVHelp * ftv, bool addToIndex) static
Definition at line 801 of file index.cpp.
References FTVHelp::addContentsItem(), IndexList::addContentsItem(), ClassDef::anchor(), ClassDef::baseClasses(), classHasVisibleChildren(), ClassDef::displayName(), OutputList::docify(), OutputList::endIndexItem(), OutputList::endIndexListItem(), OutputList::endTypewriter(), VhdlDocGen::ENTITYCLASS, Definition::getLanguage(), ClassDef::getOutputFileBase(), ClassDef::getReference(), hasVisibleRoot(), IndexList::incContentsDepth(), Doxygen::indexList, ClassDef::isLinkable(), ClassDef::isReference(), ClassDef::isVisibleInHierarchy(), SDict< ClassDef >::Iterator, OutputList::parseText(), ClassDef::protection(), SrcLangExt_VHDL, startIndexHierarchy(), OutputList::startIndexItem(), OutputList::startIndexListItem(), OutputList::startTypewriter(), ClassDef::subClasses(), ClassDef::visited, and writeClassTree().
Referenced by writeClassHierarchy().
writeDirHierarchy()
static void writeDirHierarchy (OutputList & ol, FTVHelp * ftv, bool addToIndex) static
Definition at line 726 of file index.cpp.
References FTVHelp::addContentsItem(), IndexList::addContentsItem(), addMembersToIndex(), Config_getBool, convertToHtml(), Doxygen::directories, OutputList::disable(), FileDef::displayName(), doc, endIndexHierarchy(), LayoutDocManager::File, fileVisibleInIndex(), FileDef::getDirDef(), Definition::getOuterScope(), FileDef::getOutputFileBase(), Definition::getReference(), FileDef::getSourceFileBase(), Doxygen::globalScope, OutputGenerator::Html, Doxygen::indexList, Doxygen::inputNameList, FileDef::name(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), startIndexHierarchy(), and writeDirTreeNode().
Referenced by writeFileIndex().
writeDirTreeNode()
static void writeDirTreeNode (OutputList & ol, DirDef * dd, int level, FTVHelp * ftv, bool addToIndex) static
Definition at line 573 of file index.cpp.
References FTVHelp::addContentsItem(), IndexList::addContentsItem(), addMembersToIndex(), convertToHtml(), FTVHelp::decContentsDepth(), IndexList::decContentsDepth(), dirHasVisibleChildren(), FileDef::displayName(), doc, OutputList::docify(), endIndexHierarchy(), OutputList::endIndexItem(), OutputList::endIndexListItem(), OutputList::endTypewriter(), LayoutDocManager::File, fileVisibleInIndex(), Definition::getDefFileName(), Definition::getDefLine(), DirDef::getFiles(), DirDef::getOutputFileBase(), FileDef::getOutputFileBase(), Definition::getReference(), FileDef::getSourceFileBase(), FTVHelp::incContentsDepth(), IndexList::incContentsDepth(), Doxygen::indexList, Definition::isReference(), FileDef::name(), Definition::name(), OutputList::parseText(), DirDef::shortName(), startIndexHierarchy(), OutputList::startIndexItem(), OutputList::startIndexListItem(), OutputList::startTypewriter(), DirDef::subDirs(), and warn().
Referenced by writeDirHierarchy().
writeExampleIndex()
static void writeExampleIndex (OutputList & ol) static
Definition at line 3010 of file index.cpp.
References IndexList::addContentsItem(), IndexList::decContentsDepth(), OutputList::disable(), endFile(), OutputList::endItemList(), OutputList::endItemListItem(), OutputList::endTextBlock(), endTitle(), LayoutNavEntry::Examples, Doxygen::exampleSDict, filterTitle(), LayoutNavEntry::find(), PageDef::getOutputFileBase(), Definition::getReference(), HLI_Examples, IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::intro(), SDict< PageDef >::Iterator, OutputGenerator::Man, Definition::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputList::startContents(), startFile(), OutputList::startItemList(), OutputList::startItemListItem(), OutputList::startTextBlock(), startTitle(), theTranslator, PageDef::title(), LayoutNavEntry::title(), Translator::trExamples(), Translator::trExamplesDescription(), LayoutNavEntry::visible(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writeIndexHierarchyEntries().
writeFileIndex()
static void writeFileIndex (OutputList & ol) static
Definition at line 1167 of file index.cpp.
References IndexList::addContentsItem(), Config_getBool, IndexList::decContentsDepth(), OutputList::disable(), OutputList::disableAllBut(), documentedFiles, documentedHtmlFiles, endFile(), OutputList::endIndexList(), OutputList::endTextBlock(), endTitle(), LayoutNavEntry::FileList, LayoutNavEntry::Files, LayoutNavEntry::find(), FTVHelp::generateTreeViewInline(), FileDef::getPath(), HLI_Files, OutputGenerator::Html, IndexList::incContentsDepth(), Doxygen::indexList, Doxygen::inputNameList, LayoutDocManager::instance(), LayoutNavEntry::intro(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputList::startContents(), startFile(), OutputList::startIndexList(), OutputList::startTextBlock(), startTitle(), theTranslator, LayoutNavEntry::title(), Translator::trFileList(), Translator::trFileListDescription(), LayoutNavEntry::visible(), writeDirHierarchy(), writeSingleFileIndex(), and OutputList::writeString().
Referenced by writeIndexHierarchyEntries().
writeFileLinkForMember()
static void writeFileLinkForMember (OutputList & ol, MemberDef * md, const char * separator, QCString & prevFileName) static
Definition at line 2129 of file index.cpp.
References MemberDef::anchor(), OutputList::docify(), MemberDef::getFileDef(), MemberDef::getOutputFileBase(), MemberDef::getReference(), FileDef::name(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writeMemberList().
writeFileMemberIndex()
static void writeFileMemberIndex (OutputList & ol) static
Definition at line 2812 of file index.cpp.
References IndexList::addContentsItem(), IndexList::decContentsDepth(), documentedFileMembers, LayoutNavEntry::FileGlobals, LayoutNavEntry::find(), FMHL_All, FMHL_Defines, FMHL_Enums, FMHL_EnumValues, FMHL_Functions, FMHL_Typedefs, FMHL_Variables, IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutDocManager::rootNavEntry(), theTranslator, LayoutNavEntry::title(), Translator::trFileMembers(), LayoutNavEntry::visible(), and writeFileMemberIndexFiltered().
Referenced by writeIndexHierarchyEntries().
writeFileMemberIndexFiltered()
static void writeFileMemberIndexFiltered (OutputList & ol, FileMemberHighlight hl) static
Definition at line 2697 of file index.cpp.
References IndexList::addContentsItem(), Config_getBool, SIntDict< T >::Iterator::current(), IndexList::decContentsDepth(), OutputList::disableAllBut(), documentedFileMembers, endFile(), endQuickIndexItem(), endQuickIndexList(), OutputList::endQuickIndices(), OutputList::endTextBlock(), LayoutNavEntry::FileGlobals, LayoutNavEntry::find(), fixSpaces(), FMHL_All, FMHL_Total, FmhlInfo::fname, getFmhlInfo(), HLI_Globals, OutputGenerator::Html, Doxygen::htmlFileExtension, IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::intro(), MemberIndexList::letter(), letterToLabel(), MAX_ITEMS_BEFORE_MULTIPAGE_INDEX, maxItemsBeforeQuickIndex, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputList::startContents(), OutputList::startFile(), startQuickIndexItem(), startQuickIndexList(), OutputList::startQuickIndices(), OutputList::startTextBlock(), theTranslator, LayoutNavEntry::title(), SIntDict< T >::Iterator::toFirst(), Translator::trFileMembers(), Translator::trFileMembersDescription(), DefinitionIntf::TypeFile, LayoutNavEntry::visible(), writeMemberList(), OutputList::writeQuickLinks(), writeQuickMemberIndex(), OutputList::writeSearchInfo(), OutputList::writeSplitBar(), and OutputList::writeString().
Referenced by writeFileMemberIndex().
writeGraphicalClassHierarchy()
static void writeGraphicalClassHierarchy (OutputList & ol) static
Definition at line 1037 of file index.cpp.
References LayoutNavEntry::ClassHierarchy, OutputList::disableAllBut(), OutputList::enableAll(), endFile(), OutputList::endParagraph(), OutputList::endTextBlock(), OutputList::endTextLink(), endTitle(), LayoutNavEntry::find(), hierarchyClasses, HLI_Hierarchy, OutputGenerator::Html, LayoutDocManager::instance(), OutputList::parseText(), LayoutDocManager::rootNavEntry(), OutputList::startContents(), startFile(), OutputList::startParagraph(), OutputList::startTextBlock(), OutputList::startTextLink(), startTitle(), theTranslator, LayoutNavEntry::title(), Translator::trClassHierarchy(), Translator::trGotoTextualHierarchy(), and OutputList::writeGraphicalHierarchy().
Referenced by writeIndexHierarchyEntries().
writeGraphInfo()
void writeGraphInfo (OutputList & ol)
Definition at line 3256 of file index.cpp.
References Config_getBool, Config_getString, OutputList::disableAllBut(), endFile(), endTitle(), OutputList::generateDoc(), generateGraphLegend(), getDotImageExtension(), OutputGenerator::Html, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startContents(), startFile(), startTitle(), theTranslator, Translator::trLegendDocs(), and Translator::trLegendTitle().
Referenced by generateOutput().
writeGroupHierarchy()
static void writeGroupHierarchy (OutputList & ol, FTVHelp * ftv, bool addToIndex) static
Definition at line 3550 of file index.cpp.
References OutputList::disable(), endIndexHierarchy(), Doxygen::groupSDict, OutputGenerator::Html, SDict< GroupDef >::Iterator, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), startIndexHierarchy(), and writeGroupTreeNode().
Referenced by writeGroupIndex().
writeGroupIndex()
static void writeGroupIndex (OutputList & ol) static
Definition at line 3608 of file index.cpp.
References IndexList::addContentsItem(), IndexList::decContentsDepth(), OutputList::disable(), IndexList::disable(), OutputList::disableAllBut(), documentedGroups, IndexList::enable(), endFile(), OutputList::endTextBlock(), endTitle(), LayoutNavEntry::find(), FTVHelp::generateTreeViewInline(), HLI_Modules, OutputGenerator::Html, IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::intro(), OutputGenerator::Man, LayoutNavEntry::Modules, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputList::startContents(), startFile(), OutputList::startTextBlock(), startTitle(), theTranslator, LayoutNavEntry::title(), Translator::trModules(), Translator::trModulesDescription(), LayoutNavEntry::visible(), writeGroupHierarchy(), and OutputList::writeString().
Referenced by writeIndexHierarchyEntries().
writeGroupTreeNode()
static void writeGroupTreeNode (OutputList & ol, GroupDef * gd, int level, FTVHelp * ftv, bool addToIndex) static
write groups as hierarchical trees
gd->visited &&
Definition at line 3303 of file index.cpp.
References FTVHelp::addContentsItem(), IndexList::addContentsItem(), addMembersToIndex(), MemberDef::anchor(), LayoutDocManager::Class, Config_getBool, convertToHtml(), MemberList::count(), SDict< T >::count(), FTVHelp::decContentsDepth(), IndexList::decContentsDepth(), OutputList::docify(), endIndexHierarchy(), OutputList::endIndexItem(), OutputList::endIndexListItem(), OutputList::endTypewriter(), MemberDef::enumFieldList(), GroupDef::getClasses(), Definition::getDefFileName(), Definition::getDefLine(), GroupDef::getDirs(), GroupDef::getFiles(), GroupDef::getMemberList(), GroupDef::getMemberLists(), GroupDef::getNamespaces(), GroupDef::getOutputFileBase(), MemberDef::getOutputFileBase(), GroupDef::getPages(), MemberDef::getReference(), Definition::getReference(), GroupDef::getSubGroups(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, GroupDef::groupTitle(), FTVHelp::incContentsDepth(), IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), GroupDef::isASubGroup(), MemberDef::isEnumerate(), Definition::isReference(), Definition::isVisible(), SDict< ClassDef >::Iterator, SDict< NamespaceDef >::Iterator, LayoutDocEntry::kind(), SectionInfo::label, LayoutDocEntry::MemberDef, MemberListType_documentationLists, Definition::name(), OutputList::parseText(), Doxygen::sectionDict, startIndexHierarchy(), OutputList::startIndexItem(), OutputList::startIndexListItem(), OutputList::startTypewriter(), LayoutDocEntryMemberDef::type, warn(), and writePages().
Referenced by writeGroupHierarchy().
writeHierarchicalIndex()
static void writeHierarchicalIndex (OutputList & ol) static
Definition at line 956 of file index.cpp.
References IndexList::addContentsItem(), LayoutNavEntry::ClassHierarchy, Config_getBool, OutputList::disable(), IndexList::disable(), OutputList::disableAllBut(), OutputList::enable(), IndexList::enable(), endFile(), OutputList::endParagraph(), OutputList::endTextBlock(), OutputList::endTextLink(), endTitle(), LayoutNavEntry::find(), FTVHelp::generateTreeViewInline(), hierarchyClasses, HLI_Hierarchy, OutputGenerator::Html, Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::intro(), OutputGenerator::Latex, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputGenerator::RTF, OutputList::startContents(), startFile(), OutputList::startParagraph(), OutputList::startTextBlock(), OutputList::startTextLink(), startTitle(), theTranslator, LayoutNavEntry::title(), Translator::trClassHierarchy(), Translator::trClassHierarchyDescription(), Translator::trGotoGraphicalHierarchy(), LayoutNavEntry::visible(), writeClassHierarchy(), and OutputList::writeString().
Referenced by writeIndexHierarchyEntries().
writeIndex()
static void writeIndex (OutputList & ol) static
Definition at line 3772 of file index.cpp.
References IndexList::addContentsItem(), annotatedClassesPrinted, Config_getBool, Config_getString, OutputList::disable(), OutputList::disableAllBut(), Definition::docFile(), Definition::docLine(), documentedFiles, documentedGroups, documentedNamespaces, documentedPages, OutputList::enable(), endFile(), OutputList::endHeaderSection(), OutputList::endIndexSection(), OutputList::endProjectNumber(), OutputList::endQuickIndices(), OutputList::endTextBlock(), OutputList::endTitleHead(), Doxygen::exampleSDict, filterTitle(), OutputList::generateDoc(), PageDef::getGroupDef(), Definition::getOuterScope(), PageDef::getOutputFileBase(), PageDef::hasParentPage(), hierarchyClasses, HLI_Main, OutputGenerator::Html, Doxygen::indexList, Doxygen::insideMainPage, isClassDocumentation, isClassHierarchyIndex, isCompoundIndex, isEndIndex, isExampleDocumentation, isFileDocumentation, isFileIndex, isMainPage, isModuleDocumentation, isModuleIndex, isNamespaceDocumentation, isNamespaceIndex, isPageDocumentation, isPageDocumentation2, Definition::isReference(), isTitlePageAuthor, isTitlePageStart, SDict< PageDef >::Iterator, OutputList::lastIndexPage(), OutputGenerator::Latex, Doxygen::mainPage, mainPageHasTitle(), OutputGenerator::Man, Definition::name(), Doxygen::pageSDict, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startContents(), OutputList::startFile(), startFile(), OutputList::startHeaderSection(), OutputList::startIndexSection(), OutputList::startProjectNumber(), OutputList::startQuickIndices(), OutputList::startTextBlock(), OutputList::startTitleHead(), theTranslator, PageDef::title(), Translator::trClassDocumentation(), Translator::trCompoundIndex(), Translator::trCompoundIndexFortran(), VhdlDocGen::trDesignUnitIndex(), Translator::trDocumentation(), Translator::trExampleDocumentation(), Translator::trFileDocumentation(), Translator::trFileIndex(), Translator::trGeneratedBy(), Translator::trHierarchicalIndex(), Translator::trMainPage(), Translator::trModuleDocumentation(), Translator::trModuleIndex(), Translator::trModulesIndex(), Translator::trNamespaceDocumentation(), Translator::trNamespaceIndex(), Translator::trReferenceManual(), Translator::trTypeDocumentation(), OutputList::writeAnchor(), OutputList::writePageLink(), writePages(), OutputList::writeQuickLinks(), OutputList::writeSearchInfo(), OutputList::writeSplitBar(), and Definition::writeToc().
Referenced by writeIndexHierarchyEntries().
writeIndexHierarchy()
void writeIndexHierarchy (OutputList & ol)
Definition at line 4463 of file index.cpp.
References LayoutNavEntry::children(), LayoutDocManager::instance(), LayoutDocManager::rootNavEntry(), writeIndexHierarchyEntries(), and writeMenuData().
Referenced by generateOutput().
writeIndexHierarchyEntries()
static void writeIndexHierarchyEntries (OutputList & ol, const QList< LayoutNavEntry > & entries) static
Definition at line 4083 of file index.cpp.
References IndexList::addContentsItem(), annotatedClasses, LayoutNavEntry::baseFile(), LayoutNavEntry::children(), LayoutNavEntry::Classes, LayoutNavEntry::ClassHierarchy, LayoutNavEntry::ClassIndex, LayoutNavEntry::ClassList, LayoutNavEntry::ClassMembers, Config_getBool, correctURL(), IndexList::decContentsDepth(), documentedHtmlFiles, documentedNamespaces, LayoutNavEntry::Examples, LayoutNavEntry::FileGlobals, LayoutNavEntry::FileList, LayoutNavEntry::Files, IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::kind(), LayoutNavEntry::MainPage, LayoutNavEntry::Modules, msg(), LayoutNavEntry::NamespaceList, LayoutNavEntry::NamespaceMembers, LayoutNavEntry::Namespaces, LayoutNavEntry::Pages, LayoutNavEntry::title(), LayoutNavEntry::url(), LayoutNavEntry::User, LayoutNavEntry::UserGroup, LayoutNavEntry::visible(), writeAlphabeticalIndex(), writeAnnotatedIndex(), writeClassMemberIndex(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeGraphicalClassHierarchy(), writeGroupIndex(), writeHierarchicalIndex(), writeIndex(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writePageIndex(), and writeUserGroupStubPage().
Referenced by writeIndexHierarchy().
writeMemberList()
static void writeMemberList (OutputList & ol, bool useSections, int page, const LetterToIndexMap< MemberIndexList > & memberLists, DefinitionIntf::DefType type) static
Definition at line 2157 of file index.cpp.
References SIntDict< T >::Iterator::current(), getPrefixIndex(), MemberDef::isFunction(), MemberDef::isObjCMethod(), MemberDef::isSignal(), MemberDef::isSlot(), MemberIndexList::letter(), letterToLabel(), Definition::name(), SectionInfo::Subsection, SIntDict< T >::Iterator::toFirst(), SIntDict< T >::Iterator::toLast(), writeClassLinkForMember(), writeFileLinkForMember(), and writeNamespaceLinkForMember().
Referenced by writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), and writeNamespaceMemberIndexFiltered().
writeMenuData()
static void writeMenuData () static
Definition at line 4431 of file index.cpp.
References Config_getBool, endl(), LayoutDocManager::instance(), renderQuickLinksAsJs(), and LayoutDocManager::rootNavEntry().
Referenced by writeIndexHierarchy().
writeNamespaceIndex()
static void writeNamespaceIndex (OutputList & ol) static
Definition at line 1448 of file index.cpp.
References IndexList::addContentsItem(), Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, IndexList::decContentsDepth(), OutputList::disable(), OutputList::disableAllBut(), NamespaceDef::displayName(), documentedNamespaces, endFile(), OutputList::endIndexKey(), OutputList::endIndexList(), OutputList::endIndexValue(), OutputList::endTextBlock(), endTitle(), LayoutNavEntry::find(), OutputList::generateDoc(), FTVHelp::generateTreeViewInline(), Definition::getLanguage(), NamespaceDef::getOutputFileBase(), HLI_Namespaces, OutputGenerator::Html, IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::intro(), NamespaceDef::isLinkableInProject(), SDict< NamespaceDef >::Iterator, OutputGenerator::Man, LayoutNavEntry::NamespaceList, LayoutNavEntry::Namespaces, Doxygen::namespaceSDict, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), SrcLangExt_VHDL, OutputList::startContents(), startFile(), OutputList::startIndexKey(), OutputList::startIndexList(), OutputList::startIndexValue(), OutputList::startTextBlock(), startTitle(), theTranslator, LayoutNavEntry::title(), Translator::trNamespaceList(), Translator::trNamespaceListDescription(), LayoutNavEntry::visible(), writeNamespaceTree(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writeIndexHierarchyEntries().
writeNamespaceLinkForMember()
static void writeNamespaceLinkForMember (OutputList & ol, MemberDef * md, const char * separator, QCString & prevNamespaceName) static
Definition at line 2143 of file index.cpp.
References MemberDef::anchor(), NamespaceDef::displayName(), OutputList::docify(), MemberDef::getNamespaceDef(), MemberDef::getOutputFileBase(), MemberDef::getReference(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by writeMemberList().
writeNamespaceMemberIndex()
static void writeNamespaceMemberIndex (OutputList & ol) static
Definition at line 2983 of file index.cpp.
References IndexList::addContentsItem(), IndexList::decContentsDepth(), documentedNamespaceMembers, LayoutNavEntry::find(), IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::NamespaceMembers, NMHL_All, NMHL_Enums, NMHL_EnumValues, NMHL_Functions, NMHL_Typedefs, NMHL_Variables, LayoutDocManager::rootNavEntry(), theTranslator, LayoutNavEntry::title(), Translator::trNamespaceMembers(), LayoutNavEntry::visible(), and writeNamespaceMemberIndexFiltered().
Referenced by writeIndexHierarchyEntries().
writeNamespaceMemberIndexFiltered()
static void writeNamespaceMemberIndexFiltered (OutputList & ol, NamespaceMemberHighlight hl) static
Definition at line 2866 of file index.cpp.
References IndexList::addContentsItem(), Config_getBool, SIntDict< T >::Iterator::current(), IndexList::decContentsDepth(), OutputList::disableAllBut(), documentedNamespaceMembers, endFile(), endQuickIndexItem(), endQuickIndexList(), OutputList::endQuickIndices(), OutputList::endTextBlock(), LayoutNavEntry::find(), fixSpaces(), NmhlInfo::fname, getNmhlInfo(), HLI_NamespaceMembers, OutputGenerator::Html, Doxygen::htmlFileExtension, IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), LayoutNavEntry::intro(), MemberIndexList::letter(), letterToLabel(), MAX_ITEMS_BEFORE_MULTIPAGE_INDEX, maxItemsBeforeQuickIndex, LayoutNavEntry::NamespaceMembers, NMHL_All, NMHL_Total, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputList::startContents(), OutputList::startFile(), startQuickIndexItem(), startQuickIndexList(), OutputList::startQuickIndices(), OutputList::startTextBlock(), theTranslator, LayoutNavEntry::title(), SIntDict< T >::Iterator::toFirst(), Translator::trNamespaceMemberDescription(), Translator::trNamespaceMembers(), DefinitionIntf::TypeNamespace, LayoutNavEntry::visible(), writeMemberList(), OutputList::writeQuickLinks(), writeQuickMemberIndex(), OutputList::writeSearchInfo(), OutputList::writeSplitBar(), and OutputList::writeString().
Referenced by writeNamespaceMemberIndex().
writeNamespaceTree()
static void writeNamespaceTree (NamespaceSDict * nsDict, FTVHelp * ftv, bool rootOnly, bool showClasses, bool addToIndex) static
Definition at line 1389 of file index.cpp.
References FTVHelp::addContentsItem(), IndexList::addContentsItem(), FTVHelp::decContentsDepth(), IndexList::decContentsDepth(), NamespaceDef::getClassSDict(), Definition::getLanguage(), NamespaceDef::getNamespaceSDict(), Definition::getOuterScope(), NamespaceDef::getOutputFileBase(), Definition::getReference(), Doxygen::globalScope, FTVHelp::incContentsDepth(), IndexList::incContentsDepth(), Doxygen::indexList, NamespaceDef::isLinkableInProject(), SDict< NamespaceDef >::Iterator, NamespaceDef::localName(), namespaceHasVisibleChild(), SrcLangExt_VHDL, and writeClassTree().
Referenced by writeAnnotatedIndex(), and writeNamespaceIndex().
writePageIndex()
static void writePageIndex (OutputList & ol) static
Definition at line 3173 of file index.cpp.
References DefinitionIntf::definitionType(), OutputList::disableAllBut(), endFile(), OutputList::endTextBlock(), endTitle(), LayoutNavEntry::find(), FTVHelp::generateTreeViewInline(), Definition::getOuterScope(), HLI_Pages, OutputGenerator::Html, indexedPages, LayoutDocManager::instance(), LayoutNavEntry::intro(), Definition::isReference(), SDict< PageDef >::Iterator, LayoutNavEntry::Pages, Doxygen::pageSDict, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocManager::rootNavEntry(), OutputList::startContents(), startFile(), OutputList::startTextBlock(), startTitle(), theTranslator, LayoutNavEntry::title(), Translator::trRelatedPages(), Translator::trRelatedPagesDescription(), DefinitionIntf::TypePage, writePages(), and OutputList::writeString().
Referenced by writeIndexHierarchyEntries().
writePages()
static void writePages (PageDef * pd, FTVHelp * ftv) static
Definition at line 3107 of file index.cpp.
References FTVHelp::addContentsItem(), IndexList::addContentsItem(), Definition::addSectionsToIndex(), FTVHelp::decContentsDepth(), IndexList::decContentsDepth(), filterTitle(), LayoutNavEntry::find(), PageDef::getOutputFileBase(), Definition::getReference(), PageDef::getSubPages(), Definition::hasSections(), PageDef::hasSubPages(), FTVHelp::incContentsDepth(), IndexList::incContentsDepth(), Doxygen::indexList, LayoutDocManager::instance(), SDict< PageDef >::Iterator, Doxygen::mainPage, mainPageHasOwnTitle(), Definition::name(), LayoutNavEntry::Pages, LayoutDocManager::rootNavEntry(), PageDef::title(), LayoutNavEntry::visible(), and PageDef::visibleInIndex().
Referenced by writeGroupTreeNode(), writeIndex(), and writePageIndex().
writeQuickMemberIndex()
static void writeQuickMemberIndex (OutputList & ol, const LetterToIndexMap< MemberIndexList > & charUsed, uint page, QCString fullName, bool multiPage) static
Definition at line 2459 of file index.cpp.
References SIntDict< T >::Iterator::current(), endQuickIndexItem(), endQuickIndexList(), Doxygen::htmlFileExtension, MemberIndexList::letter(), letterToLabel(), startQuickIndexItem(), startQuickIndexList(), SIntDict< T >::Iterator::toFirst(), and OutputList::writeString().
Referenced by writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), and writeNamespaceMemberIndexFiltered().
writeSingleFileIndex()
static void writeSingleFileIndex (OutputList & ol, FileDef * fd) static
Definition at line 1089 of file index.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::disableAllBut(), doc, OutputList::docify(), OutputList::endBold(), OutputList::endIndexKey(), OutputList::endIndexValue(), OutputList::endTextLink(), OutputList::generateDoc(), FileDef::generateSourceFile(), FileDef::getOutputFileBase(), FileDef::getPath(), OutputGenerator::Html, FileDef::includeName(), FileDef::isDocumentationFile(), FileDef::isLinkableInProject(), Definition::isReference(), FileDef::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startBold(), OutputList::startIndexKey(), OutputList::startIndexValue(), OutputList::startTextLink(), stripFromPath(), theTranslator, Translator::trCode(), and OutputList::writeObjectLink().
Referenced by writeFileIndex().
writeUserGroupStubPage()
static void writeUserGroupStubPage (OutputList & ol, LayoutNavEntry * lne) static
Definition at line 3733 of file index.cpp.
References LayoutNavEntry::baseFile(), LayoutNavEntry::children(), OutputList::disableAllBut(), endFile(), endTitle(), fixSpaces(), HLI_UserGroup, OutputGenerator::Html, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startContents(), startFile(), startTitle(), LayoutNavEntry::title(), and OutputList::writeString().
Referenced by writeIndexHierarchyEntries().
Variable Documentation
annotatedClasses
int annotatedClasses
Definition at line 55 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeAlphabeticalClassList(), writeAlphabeticalIndex(), writeAnnotatedIndex(), and writeIndexHierarchyEntries().
annotatedClassesPrinted
int annotatedClassesPrinted
Definition at line 56 of file index.cpp.
Referenced by countDataStructures(), writeAnnotatedIndex(), and writeIndex().
documentedClassMembers
int documentedClassMembers[CMHL_Total]
Definition at line 62 of file index.cpp.
Referenced by addClassMemberNameToIndex(), initClassMemberIndices(), quickLinkVisible(), renderQuickLinksAsJs(), writeClassMemberIndex(), and writeClassMemberIndexFiltered().
documentedDirs
int documentedDirs
Definition at line 67 of file index.cpp.
Referenced by countDataStructures().
documentedFileMembers
int documentedFileMembers[FMHL_Total]
Definition at line 63 of file index.cpp.
Referenced by addFileMemberNameToIndex(), initFileMemberIndices(), quickLinkVisible(), renderQuickLinksAsJs(), writeFileMemberIndex(), and writeFileMemberIndexFiltered().
documentedFiles
int documentedFiles
Definition at line 58 of file index.cpp.
Referenced by countDataStructures(), writeFileIndex(), and writeIndex().
documentedGroups
int documentedGroups
Definition at line 59 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeGroupIndex(), and writeIndex().
documentedHtmlFiles
int documentedHtmlFiles
Definition at line 65 of file index.cpp.
Referenced by countDataStructures(), generateFileDocs(), quickLinkVisible(), writeFileIndex(), and writeIndexHierarchyEntries().
documentedNamespaceMembers
int documentedNamespaceMembers[NMHL_Total]
Definition at line 64 of file index.cpp.
Referenced by addNamespaceMemberNameToIndex(), initNamespaceMemberIndices(), quickLinkVisible(), renderQuickLinksAsJs(), writeNamespaceMemberIndex(), and writeNamespaceMemberIndexFiltered().
documentedNamespaces
int documentedNamespaces
Definition at line 60 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeIndex(), writeIndexHierarchyEntries(), and writeNamespaceIndex().
documentedPages
int documentedPages
Definition at line 66 of file index.cpp.
Referenced by countDataStructures(), generatePageDocs(), and writeIndex().
g_fileIndexLetterUsed
LetterToIndexMap<MemberIndexList> g_fileIndexLetterUsed[FMHL_Total] static
Definition at line 140 of file index.cpp.
g_memberIndexLetterUsed
LetterToIndexMap<MemberIndexList> g_memberIndexLetterUsed[CMHL_Total] static
Definition at line 139 of file index.cpp.
g_namespaceIndexLetterUsed
LetterToIndexMap<MemberIndexList> g_namespaceIndexLetterUsed[NMHL_Total] static
Definition at line 141 of file index.cpp.
hierarchyClasses
int hierarchyClasses
Definition at line 57 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), writeGraphicalClassHierarchy(), writeHierarchicalIndex(), and writeIndex().
indexedPages
int indexedPages
Definition at line 61 of file index.cpp.
Referenced by countDataStructures(), quickLinkVisible(), and writePageIndex().
indexWritten
QArray<bool> indexWritten static
Definition at line 4081 of file index.cpp.
maxItemsBeforeQuickIndex
const int maxItemsBeforeQuickIndex = MAX_ITEMS_BEFORE_QUICK_INDEX
Definition at line 143 of file index.cpp.
Referenced by renderMemberIndicesAsJs(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), and writeNamespaceMemberIndexFiltered().