Doxygen: GenericNodeListContext Class Reference
GenericNodeListContext Class Reference
standard template list implementation
Public Member Functions
GenericNodeListContext ()
int count () const
Returns the number of elements in the list.
TemplateVariant at (int index) const
Returns the element at index position index.
TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
void append (const TemplateVariant &ctn)
bool isEmpty () const
int addRef ()
Increase object's reference count.
int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static GenericNodeListContext * alloc ()
Private Attributes
QList< TemplateVariant > m_children
int m_refCount
Detailed Description
standard template list implementation
Definition at line 164 of file context.cpp.
Constructor & Destructor Documentation
GenericNodeListContext()
GenericNodeListContext::GenericNodeListContext () inline
Definition at line 167 of file context.cpp.
References m_children.
Referenced by alloc().
Member Function Documentation
addRef()
int GenericNodeListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 203 of file context.cpp.
References m_refCount.
alloc()
static GenericNodeListContext* GenericNodeListContext::alloc () inline static
Definition at line 171 of file context.cpp.
References GenericNodeListContext().
append()
void GenericNodeListContext::append (const TemplateVariant & ctn) inline
Definition at line 195 of file context.cpp.
References m_children.
Referenced by ArgumentListContext::Private::addArgument(), InheritanceListContext::Private::addClass(), ClassListContext::Private::addClasses(), NestingContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), NestingContext::Private::addDerivedClasses(), NestingContext::Private::addDirs(), UsedFilesContext::Private::addFile(), NestingContext::Private::addFiles(), FileListContext::Private::addFiles(), InheritedMemberInfoListContext::Private::addInheritedMembers(), MemberListContext::Private::addMember(), MemberGroupListContext::Private::addMemberGroup(), NestingContext::Private::addModules(), ModuleListContext::Private::addModules(), NestingContext::Private::addNamespaces(), NamespaceListContext::Private::addNamespaces(), NestingContext::Private::addPages(), PageListContext::Private::addPages(), IncludeInfoListContext::Private::Private(), DirListContext::Private::Private(), ExampleListContext::Private::Private(), AllMembersListContext::Private::Private(), SymbolListContext::Private::Private(), SymbolGroupListContext::Private::Private(), SymbolIndicesContext::Private::Private(), and SearchIndicesContext::Private::Private().
at()
TemplateVariant GenericNodeListContext::at (int index) const inline virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 181 of file context.cpp.
References count(), and m_children.
Referenced by UsedFilesContext::at(), IncludeInfoListContext::at(), ClassListContext::at(), NestingContext::at(), NamespaceListContext::at(), DirListContext::at(), FileListContext::at(), PageListContext::at(), ModuleListContext::at(), ExampleListContext::at(), InheritanceListContext::at(), MemberListContext::at(), MemberGroupListContext::at(), InheritedMemberInfoListContext::at(), AllMembersListContext::at(), ArgumentListContext::at(), SymbolListContext::at(), SymbolGroupListContext::at(), SymbolIndicesContext::at(), and SearchIndicesContext::at().
count()
int GenericNodeListContext::count () const inline virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 177 of file context.cpp.
References m_children.
Referenced by InheritedMemberInfoListContext::Private::addInheritedMembers(), at(), UsedFilesContext::count(), IncludeInfoListContext::count(), ClassListContext::count(), NestingContext::count(), NamespaceListContext::count(), DirListContext::count(), FileListContext::count(), PageListContext::count(), ModuleListContext::count(), ExampleListContext::count(), InheritanceListContext::count(), MemberListContext::count(), MemberGroupListContext::count(), InheritedMemberInfoListContext::count(), AllMembersListContext::count(), ArgumentListContext::count(), SymbolListContext::count(), SymbolGroupListContext::count(), SymbolIndicesContext::count(), SearchIndicesContext::count(), and release().
createIterator()
TemplateListIntf::ConstIterator* GenericNodeListContext::createIterator () const inline virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 190 of file context.cpp.
References m_children.
Referenced by UsedFilesContext::createIterator(), IncludeInfoListContext::createIterator(), ClassListContext::createIterator(), NestingContext::createIterator(), NamespaceListContext::createIterator(), DirListContext::createIterator(), FileListContext::createIterator(), PageListContext::createIterator(), ModuleListContext::createIterator(), ExampleListContext::createIterator(), InheritanceListContext::createIterator(), MemberListContext::createIterator(), MemberGroupListContext::createIterator(), InheritedMemberInfoListContext::createIterator(), AllMembersListContext::createIterator(), ArgumentListContext::createIterator(), SymbolListContext::createIterator(), SymbolGroupListContext::createIterator(), SymbolIndicesContext::createIterator(), and SearchIndicesContext::createIterator().
isEmpty()
bool GenericNodeListContext::isEmpty () const inline
Definition at line 199 of file context.cpp.
References m_children.
release()
int GenericNodeListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 207 of file context.cpp.
References count(), and m_refCount.
Member Data Documentation
m_children
QList<TemplateVariant> GenericNodeListContext::m_children mutable private
Definition at line 217 of file context.cpp.
Referenced by append(), at(), count(), createIterator(), GenericNodeListContext(), and isEmpty().
m_refCount
int GenericNodeListContext::m_refCount private
Definition at line 218 of file context.cpp.
Referenced by addRef(), and release().
The documentation for this class was generated from the following file:
src/context.cpp