Doxygen: TemplateAutoRef< T > Class Template Reference
TemplateAutoRef< T > Class Template Reference
Template API
#include <template.h>
Public Member Functions
TemplateAutoRef (T *obj)
~TemplateAutoRef ()
T & operator* () const
T * operator-> () const
T * get () const
Private Attributes
T * m_obj
Detailed Description
template<class T>
class TemplateAutoRef< T >
Definition at line 305 of file template.h.
Constructor & Destructor Documentation
TemplateAutoRef()
template<class T> TemplateAutoRef< T >::TemplateAutoRef (T * obj) inline
Definition at line 308 of file template.h.
~TemplateAutoRef()
template<class T> TemplateAutoRef< T >::~TemplateAutoRef () inline
Definition at line 312 of file template.h.
Member Function Documentation
get()
template<class T> T* TemplateAutoRef< T >::get () const inline
Definition at line 318 of file template.h.
Referenced by TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeBlock::render(), TemplateNodeMarkers::render(), and TemplateContextImpl::TemplateContextImpl().
operator*()
template<class T> T& TemplateAutoRef< T >::operator* () const inline
Definition at line 316 of file template.h.
operator->()
template<class T> T* TemplateAutoRef< T >::operator-> () const inline
Definition at line 317 of file template.h.
Member Data Documentation
m_obj
template<class T> T* TemplateAutoRef< T >::m_obj private
Definition at line 321 of file template.h.
Referenced by TemplateAutoRef< TemplateStruct >::get(), TemplateAutoRef< TemplateStruct >::operator*(), TemplateAutoRef< TemplateStruct >::operator->(), TemplateAutoRef< TemplateStruct >::TemplateAutoRef(), and TemplateAutoRef< TemplateStruct >::~TemplateAutoRef().
The documentation for this class was generated from the following file:
src/template.h