Doxygen: TranslatorBrazilian Class Reference
TranslatorBrazilian Class Reference
#include <translator_br.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const char *s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trPageDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const char *date, const char *projName)
virtual QCString trClassDiagram (const char *clName)
virtual QCString trForInternalUseOnly ()
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const char *clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const char *fileName)
virtual QCString trNamespaceReference (const char *namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const char *clName)
virtual QCString trInclDepGraph (const char *fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const char *name)
virtual QCString trPackageList ()
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageMembers ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirDescription ()
virtual QCString trDirReference (const char *dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const char *clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const char *namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const char *name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const char *name)
virtual QCString trIncludesFileIn (const char *name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
Compiles a date string.
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const char *name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const char *name)
virtual QCString trInheritedFrom (const char *members, const char *what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trDesignOverview ()
virtual QCString trInterfaces ()
old style UNO IDL services: implemented interfaces
virtual QCString trServices ()
old style UNO IDL services: inherited services
virtual QCString trConstantGroups ()
UNO IDL constant groups.
virtual QCString trConstantGroupReference (const char *namespaceName)
UNO IDL constant groups.
virtual QCString trServiceReference (const char *sName)
UNO IDL service page title.
virtual QCString trSingletonReference (const char *sName)
UNO IDL singleton page title.
virtual QCString trServiceGeneratedFromFiles (bool single)
UNO IDL service page.
virtual QCString trSingletonGeneratedFromFiles (bool single)
UNO IDL singleton page.
Public Member Functions inherited from Translator
virtual QCString updateNeededMessage ()
virtual ~Translator ()
Detailed Description
Definition at line 48 of file translator_br.h.
Member Function Documentation
idLanguage()
virtual QCString TranslatorBrazilian::idLanguage () inline virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 60 of file translator_br.h.
latexLanguageSupportCommand()
virtual QCString TranslatorBrazilian::latexLanguageSupportCommand () inline virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
 "\\usepackage[latin2]{inputenc}\n"
 "\\usepackage[T1]{fontenc}\n"
The English LaTeX does not use such commands. Because of this the empty string is returned in this implementation.
Implements Translator.
Definition at line 79 of file translator_br.h.
trAdditionalInheritedMembers()
virtual QCString TranslatorBrazilian::trAdditionalInheritedMembers () inline virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1952 of file translator_br.h.
trAll()
virtual QCString TranslatorBrazilian::trAll () inline virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1458 of file translator_br.h.
trAndMore()
virtual QCString TranslatorBrazilian::trAndMore (const QCString & number) inline virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1924 of file translator_br.h.
trAttention()
virtual QCString TranslatorBrazilian::trAttention () inline virtual
Implements Translator.
Definition at line 1014 of file translator_br.h.
trAuthor()
virtual QCString TranslatorBrazilian::trAuthor (bool first_capital, bool singular) inline virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1333 of file translator_br.h.
trBug()
virtual QCString TranslatorBrazilian::trBug () inline virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1187 of file translator_br.h.
trBugList()
virtual QCString TranslatorBrazilian::trBugList () inline virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1192 of file translator_br.h.
trCallerGraph()
virtual QCString TranslatorBrazilian::trCallerGraph () inline virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1589 of file translator_br.h.
trCallGraph()
virtual QCString TranslatorBrazilian::trCallGraph () inline virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1463 of file translator_br.h.
trCiteReferences()
virtual QCString TranslatorBrazilian::trCiteReferences () inline virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1896 of file translator_br.h.
trClass()
virtual QCString TranslatorBrazilian::trClass (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1250 of file translator_br.h.
trClassDiagram()
virtual QCString TranslatorBrazilian::trClassDiagram (const char * clName) inline virtual
this text is put before a class diagram
Implements Translator.
Definition at line 526 of file translator_br.h.
trClassDocumentation()
virtual QCString TranslatorBrazilian::trClassDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 399 of file translator_br.h.
References Config_getBool.
trClasses()
virtual QCString TranslatorBrazilian::trClasses () inline virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1145 of file translator_br.h.
References Config_getBool.
trClassHierarchy()
virtual QCString TranslatorBrazilian::trClassHierarchy () inline virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 183 of file translator_br.h.
trClassHierarchyDescription()
virtual QCString TranslatorBrazilian::trClassHierarchyDescription () inline virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 242 of file translator_br.h.
trClassMethods()
virtual QCString TranslatorBrazilian::trClassMethods () inline virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 1990 of file translator_br.h.
trCode()
virtual QCString TranslatorBrazilian::trCode () inline virtual
Text used the source code in the file index
Implements Translator.
Definition at line 914 of file translator_br.h.
trCollaborationDiagram()
virtual QCString TranslatorBrazilian::trCollaborationDiagram (const char * clName) inline virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 869 of file translator_br.h.
trCompoundIndex()
virtual QCString TranslatorBrazilian::trCompoundIndex () inline virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 372 of file translator_br.h.
References Config_getBool.
trCompoundIndexFortran()
virtual QCString TranslatorBrazilian::trCompoundIndexFortran () inline virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1641 of file translator_br.h.
trCompoundList()
virtual QCString TranslatorBrazilian::trCompoundList () inline virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 187 of file translator_br.h.
References Config_getBool.
trCompoundListDescription()
virtual QCString TranslatorBrazilian::trCompoundListDescription () inline virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 255 of file translator_br.h.
References Config_getBool.
trCompoundListDescriptionFortran()
virtual QCString TranslatorBrazilian::trCompoundListDescriptionFortran () inline virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1618 of file translator_br.h.
trCompoundListFortran()
virtual QCString TranslatorBrazilian::trCompoundListFortran () inline virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1610 of file translator_br.h.
trCompoundMembers()
virtual QCString TranslatorBrazilian::trCompoundMembers () inline virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 204 of file translator_br.h.
References Config_getBool.
trCompoundMembersDescription()
virtual QCString TranslatorBrazilian::trCompoundMembersDescription (bool extractAll) inline virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 268 of file translator_br.h.
References Config_getBool.
trCompoundMembersDescriptionFortran()
virtual QCString TranslatorBrazilian::trCompoundMembersDescriptionFortran (bool extractAll) inline virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1622 of file translator_br.h.
trCompoundMembersFortran()
virtual QCString TranslatorBrazilian::trCompoundMembersFortran () inline virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1614 of file translator_br.h.
trCompoundReference()
virtual QCString TranslatorBrazilian::trCompoundReference (const char * clName, ClassDef::CompoundType compType, bool isTemplate) inline virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 605 of file translator_br.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
virtual QCString TranslatorBrazilian::trCompoundReferenceFortran (const char * clName, ClassDef::CompoundType compType, bool isTemplate) inline virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1682 of file translator_br.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
virtual QCString TranslatorBrazilian::trCompounds () inline virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 502 of file translator_br.h.
References Config_getBool.
trConstantGroupReference()
virtual QCString TranslatorBrazilian::trConstantGroupReference (const char * namespaceName) inline virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2036 of file translator_br.h.
trConstantGroups()
virtual QCString TranslatorBrazilian::trConstantGroups () inline virtual
UNO IDL constant groups.
Implements Translator.
Definition at line 2032 of file translator_br.h.
trConstructorDocumentation()
virtual QCString TranslatorBrazilian::trConstructorDocumentation () inline virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 879 of file translator_br.h.
trCopyright()
virtual QCString TranslatorBrazilian::trCopyright () inline virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1900 of file translator_br.h.
trDataTypes()
virtual QCString TranslatorBrazilian::trDataTypes () inline virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1665 of file translator_br.h.
trDate()
virtual QCString TranslatorBrazilian::trDate () inline virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 544 of file translator_br.h.
trDateTime()
virtual QCString TranslatorBrazilian::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) inline virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1874 of file translator_br.h.
trDefinedAtLineInSourceFile()
virtual QCString TranslatorBrazilian::trDefinedAtLineInSourceFile () inline virtual
Implements Translator.
Definition at line 846 of file translator_br.h.
trDefinedIn()
virtual QCString TranslatorBrazilian::trDefinedIn () inline virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 171 of file translator_br.h.
trDefinedInSourceFile()
virtual QCString TranslatorBrazilian::trDefinedInSourceFile () inline virtual
Implements Translator.
Definition at line 850 of file translator_br.h.
trDefineDocumentation()
virtual QCString TranslatorBrazilian::trDefineDocumentation () inline virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 472 of file translator_br.h.
trDefines()
virtual QCString TranslatorBrazilian::trDefines () inline virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 436 of file translator_br.h.
trDefineValue()
virtual QCString TranslatorBrazilian::trDefineValue () inline virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1177 of file translator_br.h.
trDeprecated()
virtual QCString TranslatorBrazilian::trDeprecated () inline virtual
Implements Translator.
Definition at line 859 of file translator_br.h.
trDeprecatedList()
virtual QCString TranslatorBrazilian::trDeprecatedList () inline virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1390 of file translator_br.h.
trDesignOverview()
virtual QCString TranslatorBrazilian::trDesignOverview () inline virtual
Used as the title of the design overview picture created for the VHDL output.
Implements Translator.
Definition at line 2013 of file translator_br.h.
trDetailedDescription()
virtual QCString TranslatorBrazilian::trDetailedDescription () inline virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 95 of file translator_br.h.
trDetailLevel()
virtual QCString TranslatorBrazilian::trDetailLevel () inline virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1916 of file translator_br.h.
trDir()
virtual QCString TranslatorBrazilian::trDir (bool first_capital, bool singular) inline virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1563 of file translator_br.h.
trDirDepGraph()
virtual QCString TranslatorBrazilian::trDirDepGraph (const char * name) inline virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1908 of file translator_br.h.
trDirDescription()
virtual QCString TranslatorBrazilian::trDirDescription () inline virtual
This returns a sentences that introduces the directory hierarchy. and the fact that it is sorted alphabetically per level
Implements Translator.
Definition at line 1547 of file translator_br.h.
trDirDocumentation()
virtual QCString TranslatorBrazilian::trDirDocumentation () inline virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1535 of file translator_br.h.
trDirectories()
virtual QCString TranslatorBrazilian::trDirectories () inline virtual
This is used as the title of the directory index and also in the Quick links of a HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1541 of file translator_br.h.
trDirIndex()
virtual QCString TranslatorBrazilian::trDirIndex () inline virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1529 of file translator_br.h.
trDirReference()
virtual QCString TranslatorBrazilian::trDirReference (const char * dirName) inline virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1553 of file translator_br.h.
trDirRelation()
virtual QCString TranslatorBrazilian::trDirRelation (const char * name) inline virtual
directory relation for name
Implements Translator.
Definition at line 1813 of file translator_br.h.
trDocumentation()
virtual QCString TranslatorBrazilian::trDocumentation () inline virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 349 of file translator_br.h.
trEnumerations()
virtual QCString TranslatorBrazilian::trEnumerations () inline virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 448 of file translator_br.h.
trEnumerationTypeDocumentation()
virtual QCString TranslatorBrazilian::trEnumerationTypeDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 484 of file translator_br.h.
trEnumerationValueDocumentation()
virtual QCString TranslatorBrazilian::trEnumerationValueDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1597 of file translator_br.h.
trEnumerationValues()
virtual QCString TranslatorBrazilian::trEnumerationValues () inline virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 466 of file translator_br.h.
trEnumGeneratedFromFiles()
virtual QCString TranslatorBrazilian::trEnumGeneratedFromFiles (bool single) inline virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1928 of file translator_br.h.
trEnumName()
virtual QCString TranslatorBrazilian::trEnumName () inline virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 163 of file translator_br.h.
trEnumReference()
virtual QCString TranslatorBrazilian::trEnumReference (const char * name) inline virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1939 of file translator_br.h.
trEnumValue()
virtual QCString TranslatorBrazilian::trEnumValue () inline virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 167 of file translator_br.h.
trEventDocumentation()
virtual QCString TranslatorBrazilian::trEventDocumentation () inline virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1407 of file translator_br.h.
trEvents()
virtual QCString TranslatorBrazilian::trEvents () inline virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1402 of file translator_br.h.
trExampleDocumentation()
virtual QCString TranslatorBrazilian::trExampleDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 420 of file translator_br.h.
trExamples()
virtual QCString TranslatorBrazilian::trExamples () inline virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 234 of file translator_br.h.
trExamplesDescription()
virtual QCString TranslatorBrazilian::trExamplesDescription () inline virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 337 of file translator_br.h.
trExceptions()
virtual QCString TranslatorBrazilian::trExceptions () inline virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 560 of file translator_br.h.
trExtendsClass()
virtual QCString TranslatorBrazilian::trExtendsClass () inline virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 1982 of file translator_br.h.
trFile()
virtual QCString TranslatorBrazilian::trFile (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1261 of file translator_br.h.
trFileDocumentation()
virtual QCString TranslatorBrazilian::trFileDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 414 of file translator_br.h.
trFileIn()
virtual QCString TranslatorBrazilian::trFileIn (const char * name) inline virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1850 of file translator_br.h.
trFileIndex()
virtual QCString TranslatorBrazilian::trFileIndex () inline virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 387 of file translator_br.h.
trFileList()
virtual QCString TranslatorBrazilian::trFileList () inline virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 200 of file translator_br.h.
trFileListDescription()
virtual QCString TranslatorBrazilian::trFileListDescription (bool extractAll) inline virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 246 of file translator_br.h.
trFileMembers()
virtual QCString TranslatorBrazilian::trFileMembers () inline virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 217 of file translator_br.h.
References Config_getBool.
trFileMembersDescription()
virtual QCString TranslatorBrazilian::trFileMembersDescription (bool extractAll) inline virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 315 of file translator_br.h.
References Config_getBool.
trFileReference()
virtual QCString TranslatorBrazilian::trFileReference (const char * fileName) inline virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 635 of file translator_br.h.
trForInternalUseOnly()
virtual QCString TranslatorBrazilian::trForInternalUseOnly () inline virtual
this text is generated when the \internal command is used.
Implements Translator.
Definition at line 532 of file translator_br.h.
trFriends()
virtual QCString TranslatorBrazilian::trFriends () inline virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 587 of file translator_br.h.
trFunctionDocumentation()
virtual QCString TranslatorBrazilian::trFunctionDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 490 of file translator_br.h.
trFunctions()
virtual QCString TranslatorBrazilian::trFunctions () inline virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 454 of file translator_br.h.
trGeneratedAt()
virtual QCString TranslatorBrazilian::trGeneratedAt (const char * date, const char * projName) inline virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 517 of file translator_br.h.
trGeneratedAutomatically()
virtual QCString TranslatorBrazilian::trGeneratedAutomatically (const char * s) inline virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 155 of file translator_br.h.
trGeneratedBy()
virtual QCString TranslatorBrazilian::trGeneratedBy () inline virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 564 of file translator_br.h.
trGeneratedFromFiles()
virtual QCString TranslatorBrazilian::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 791 of file translator_br.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
virtual QCString TranslatorBrazilian::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1754 of file translator_br.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
virtual QCString TranslatorBrazilian::trGlobal (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1316 of file translator_br.h.
trGlobalNamespace()
virtual QCString TranslatorBrazilian::trGlobalNamespace () inline virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1825 of file translator_br.h.
trGotoDocumentation()
virtual QCString TranslatorBrazilian::trGotoDocumentation () inline virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 889 of file translator_br.h.
trGotoGraphicalHierarchy()
virtual QCString TranslatorBrazilian::trGotoGraphicalHierarchy () inline virtual
Implements Translator.
Definition at line 922 of file translator_br.h.
trGotoSourceCode()
virtual QCString TranslatorBrazilian::trGotoSourceCode () inline virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 884 of file translator_br.h.
trGotoTextualHierarchy()
virtual QCString TranslatorBrazilian::trGotoTextualHierarchy () inline virtual
Implements Translator.
Definition at line 926 of file translator_br.h.
trGraphicalHierarchy()
virtual QCString TranslatorBrazilian::trGraphicalHierarchy () inline virtual
Implements Translator.
Definition at line 918 of file translator_br.h.
trGroup()
virtual QCString TranslatorBrazilian::trGroup (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1283 of file translator_br.h.
trHierarchicalIndex()
virtual QCString TranslatorBrazilian::trHierarchicalIndex () inline virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 366 of file translator_br.h.
trImplementedFromList()
virtual QCString TranslatorBrazilian::trImplementedFromList (int numEntries) inline virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1358 of file translator_br.h.
References trWriteList().
trImplementedInList()
virtual QCString TranslatorBrazilian::trImplementedInList (int numEntries) inline virtual
used in member documentation blocks to produce a list of all members that implementation this member.
Implements Translator.
Definition at line 1366 of file translator_br.h.
References trWriteList().
trInclByDepGraph()
virtual QCString TranslatorBrazilian::trInclByDepGraph () inline virtual
Implements Translator.
Definition at line 1018 of file translator_br.h.
trInclDepGraph()
virtual QCString TranslatorBrazilian::trInclDepGraph (const char * fName) inline virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 874 of file translator_br.h.
trIncludesFileIn()
virtual QCString TranslatorBrazilian::trIncludesFileIn (const char * name) inline virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1859 of file translator_br.h.
trIncludingInheritedMembers()
virtual QCString TranslatorBrazilian::trIncludingInheritedMembers () inline virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 149 of file translator_br.h.
trInheritedByList()
virtual QCString TranslatorBrazilian::trInheritedByList (int numEntries) inline virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 725 of file translator_br.h.
References trWriteList().
trInheritedFrom()
virtual QCString TranslatorBrazilian::trInheritedFrom (const char * members, const char * what) inline virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1946 of file translator_br.h.
trInheritsList()
virtual QCString TranslatorBrazilian::trInheritsList (int numEntries) inline virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 717 of file translator_br.h.
References trWriteList().
trInitialValue()
virtual QCString TranslatorBrazilian::trInitialValue () inline virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 909 of file translator_br.h.
trInstanceMethods()
virtual QCString TranslatorBrazilian::trInstanceMethods () inline virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 1998 of file translator_br.h.
trInterfaces()
virtual QCString TranslatorBrazilian::trInterfaces () inline virtual
old style UNO IDL services: implemented interfaces
Implements Translator.
Definition at line 2024 of file translator_br.h.
trInvariant()
virtual QCString TranslatorBrazilian::trInvariant () inline virtual
Text for the \invariant command
Implements Translator.
Definition at line 904 of file translator_br.h.
trLegend()
virtual QCString TranslatorBrazilian::trLegend () inline virtual
text for the link to the legend page
Implements Translator.
Definition at line 1105 of file translator_br.h.
trLegendDocs()
virtual QCString TranslatorBrazilian::trLegendDocs () inline virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1039 of file translator_br.h.
References getDotImageExtension().
trLegendTitle()
virtual QCString TranslatorBrazilian::trLegendTitle () inline virtual
title of the graph legend page
Implements Translator.
Definition at line 1032 of file translator_br.h.
trListOfAllMembers()
virtual QCString TranslatorBrazilian::trListOfAllMembers () inline virtual
put in the class documentation
Implements Translator.
Definition at line 137 of file translator_br.h.
trLoading()
virtual QCString TranslatorBrazilian::trLoading () inline virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1819 of file translator_br.h.
trMainPage()
virtual QCString TranslatorBrazilian::trMainPage () inline virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 830 of file translator_br.h.
trMember()
virtual QCString TranslatorBrazilian::trMember (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1305 of file translator_br.h.
trMemberDataDocumentation()
virtual QCString TranslatorBrazilian::trMemberDataDocumentation () inline virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 120 of file translator_br.h.
References Config_getBool.
trMemberEnumerationDocumentation()
virtual QCString TranslatorBrazilian::trMemberEnumerationDocumentation () inline virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 103 of file translator_br.h.
trMemberFunctionDocumentation()
virtual QCString TranslatorBrazilian::trMemberFunctionDocumentation () inline virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 107 of file translator_br.h.
References Config_getBool.
trMemberFunctionDocumentationFortran()
virtual QCString TranslatorBrazilian::trMemberFunctionDocumentationFortran () inline virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1606 of file translator_br.h.
trMemberList()
virtual QCString TranslatorBrazilian::trMemberList () inline virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 141 of file translator_br.h.
trMemberTypedefDocumentation()
virtual QCString TranslatorBrazilian::trMemberTypedefDocumentation () inline virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 99 of file translator_br.h.
trMethodDocumentation()
virtual QCString TranslatorBrazilian::trMethodDocumentation () inline virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2005 of file translator_br.h.
trModule()
virtual QCString TranslatorBrazilian::trModule (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1744 of file translator_br.h.
trModuleDocumentation()
virtual QCString TranslatorBrazilian::trModuleDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 393 of file translator_br.h.
trModuleIndex()
virtual QCString TranslatorBrazilian::trModuleIndex () inline virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 360 of file translator_br.h.
trModuleReference()
virtual QCString TranslatorBrazilian::trModuleReference (const char * namespaceName) inline virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1706 of file translator_br.h.
trModules()
virtual QCString TranslatorBrazilian::trModules () inline virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 179 of file translator_br.h.
trModulesDescription()
virtual QCString TranslatorBrazilian::trModulesDescription () inline virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 345 of file translator_br.h.
trModulesIndex()
virtual QCString TranslatorBrazilian::trModulesIndex () inline virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1737 of file translator_br.h.
trModulesList()
virtual QCString TranslatorBrazilian::trModulesList () inline virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1669 of file translator_br.h.
trModulesListDescription()
virtual QCString TranslatorBrazilian::trModulesListDescription (bool extractAll) inline virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1673 of file translator_br.h.
trModulesMemberDescription()
virtual QCString TranslatorBrazilian::trModulesMemberDescription (bool extractAll) inline virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1718 of file translator_br.h.
trModulesMembers()
virtual QCString TranslatorBrazilian::trModulesMembers () inline virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1714 of file translator_br.h.
trMore()
virtual QCString TranslatorBrazilian::trMore () inline virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 133 of file translator_br.h.
trNamespace()
virtual QCString TranslatorBrazilian::trNamespace (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1272 of file translator_br.h.
trNamespaceDocumentation()
virtual QCString TranslatorBrazilian::trNamespaceDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 771 of file translator_br.h.
trNamespaceIndex()
virtual QCString TranslatorBrazilian::trNamespaceIndex () inline virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 765 of file translator_br.h.
trNamespaceList()
virtual QCString TranslatorBrazilian::trNamespaceList () inline virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 572 of file translator_br.h.
trNamespaceListDescription()
virtual QCString TranslatorBrazilian::trNamespaceListDescription (bool extractAll) inline virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 576 of file translator_br.h.
trNamespaceMemberDescription()
virtual QCString TranslatorBrazilian::trNamespaceMemberDescription (bool extractAll) inline virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 751 of file translator_br.h.
trNamespaceMembers()
virtual QCString TranslatorBrazilian::trNamespaceMembers () inline virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 747 of file translator_br.h.
trNamespaceReference()
virtual QCString TranslatorBrazilian::trNamespaceReference (const char * namespaceName) inline virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 643 of file translator_br.h.
trNamespaces()
virtual QCString TranslatorBrazilian::trNamespaces () inline virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 781 of file translator_br.h.
trNoMatches()
virtual QCString TranslatorBrazilian::trNoMatches () inline virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1837 of file translator_br.h.
trNote()
virtual QCString TranslatorBrazilian::trNote () inline virtual
Implements Translator.
Definition at line 939 of file translator_br.h.
trOverloadText()
virtual QCString TranslatorBrazilian::trOverloadText () inline virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1577 of file translator_br.h.
trPackage()
virtual QCString TranslatorBrazilian::trPackage (const char * name) inline virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1157 of file translator_br.h.
trPackageAttribs()
virtual QCString TranslatorBrazilian::trPackageAttribs () inline virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1439 of file translator_br.h.
trPackageList()
virtual QCString TranslatorBrazilian::trPackageList () inline virtual
Title of the package index page
Implements Translator.
Definition at line 1162 of file translator_br.h.
trPackageListDescription()
virtual QCString TranslatorBrazilian::trPackageListDescription () inline virtual
The description of the package index page
Implements Translator.
Definition at line 1167 of file translator_br.h.
trPackageMembers()
virtual QCString TranslatorBrazilian::trPackageMembers () inline virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1425 of file translator_br.h.
trPackages()
virtual QCString TranslatorBrazilian::trPackages () inline virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1172 of file translator_br.h.
trPackageTypes()
virtual QCString TranslatorBrazilian::trPackageTypes () inline virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1418 of file translator_br.h.
trPage()
virtual QCString TranslatorBrazilian::trPage (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1294 of file translator_br.h.
trPageAbbreviation()
virtual QCString TranslatorBrazilian::trPageAbbreviation () inline virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 836 of file translator_br.h.
trPageDocumentation()
virtual QCString TranslatorBrazilian::trPageDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all related pages.
Implements Translator.
Definition at line 426 of file translator_br.h.
trPageIndex()
virtual QCString TranslatorBrazilian::trPageIndex () inline virtual
Implements Translator.
Definition at line 930 of file translator_br.h.
trPanelSynchronisationTooltip()
virtual QCString TranslatorBrazilian::trPanelSynchronisationTooltip (bool enable) inline virtual
Used as a tooltip for the toggle button that appears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1963 of file translator_br.h.
trParameters()
virtual QCString TranslatorBrazilian::trParameters () inline virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 556 of file translator_br.h.
trPostcondition()
virtual QCString TranslatorBrazilian::trPostcondition () inline virtual
Text for the \post command
Implements Translator.
Definition at line 899 of file translator_br.h.
trPrecondition()
virtual QCString TranslatorBrazilian::trPrecondition () inline virtual
Text for the \pre command
Implements Translator.
Definition at line 894 of file translator_br.h.
trPrivateAttribs()
virtual QCString TranslatorBrazilian::trPrivateAttribs () inline virtual
Implements Translator.
Definition at line 978 of file translator_br.h.
trPrivateMembers()
virtual QCString TranslatorBrazilian::trPrivateMembers () inline virtual
Implements Translator.
Definition at line 680 of file translator_br.h.
trPrivateSlots()
virtual QCString TranslatorBrazilian::trPrivateSlots () inline virtual
Implements Translator.
Definition at line 683 of file translator_br.h.
trPrivateTypes()
virtual QCString TranslatorBrazilian::trPrivateTypes () inline virtual
Implements Translator.
Definition at line 974 of file translator_br.h.
trProperties()
virtual QCString TranslatorBrazilian::trProperties () inline virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1130 of file translator_br.h.
trPropertyDocumentation()
virtual QCString TranslatorBrazilian::trPropertyDocumentation () inline virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1135 of file translator_br.h.
trProtectedAttribs()
virtual QCString TranslatorBrazilian::trProtectedAttribs () inline virtual
Implements Translator.
Definition at line 966 of file translator_br.h.
trProtectedMembers()
virtual QCString TranslatorBrazilian::trProtectedMembers () inline virtual
Implements Translator.
Definition at line 671 of file translator_br.h.
trProtectedSlots()
virtual QCString TranslatorBrazilian::trProtectedSlots () inline virtual
Implements Translator.
Definition at line 674 of file translator_br.h.
trProtectedTypes()
virtual QCString TranslatorBrazilian::trProtectedTypes () inline virtual
Implements Translator.
Definition at line 962 of file translator_br.h.
trProvidedByCategory()
virtual QCString TranslatorBrazilian::trProvidedByCategory () inline virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 1973 of file translator_br.h.
trPublicAttribs()
virtual QCString TranslatorBrazilian::trPublicAttribs () inline virtual
Implements Translator.
Definition at line 947 of file translator_br.h.
References Config_getBool.
trPublicMembers()
virtual QCString TranslatorBrazilian::trPublicMembers () inline virtual
Implements Translator.
Definition at line 650 of file translator_br.h.
References Config_getBool.
trPublicSlots()
virtual QCString TranslatorBrazilian::trPublicSlots () inline virtual
Implements Translator.
Definition at line 662 of file translator_br.h.
trPublicTypes()
virtual QCString TranslatorBrazilian::trPublicTypes () inline virtual
Implements Translator.
Definition at line 943 of file translator_br.h.
trReferencedBy()
virtual QCString TranslatorBrazilian::trReferencedBy () inline virtual
Implements Translator.
Definition at line 1006 of file translator_br.h.
trReferenceManual()
virtual QCString TranslatorBrazilian::trReferenceManual () inline virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 430 of file translator_br.h.
trReferences()
virtual QCString TranslatorBrazilian::trReferences () inline virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1346 of file translator_br.h.
trReimplementedFromList()
virtual QCString TranslatorBrazilian::trReimplementedFromList (int numEntries) inline virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 733 of file translator_br.h.
References trWriteList().
trReimplementedInList()
virtual QCString TranslatorBrazilian::trReimplementedInList (int numEntries) inline virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 741 of file translator_br.h.
References trWriteList().
trRelatedFunctionDocumentation()
virtual QCString TranslatorBrazilian::trRelatedFunctionDocumentation () inline virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 597 of file translator_br.h.
trRelatedFunctions()
virtual QCString TranslatorBrazilian::trRelatedFunctions () inline virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 87 of file translator_br.h.
trRelatedPages()
virtual QCString TranslatorBrazilian::trRelatedPages () inline virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 230 of file translator_br.h.
trRelatedPagesDescription()
virtual QCString TranslatorBrazilian::trRelatedPagesDescription () inline virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 341 of file translator_br.h.
trRelatedSubscript()
virtual QCString TranslatorBrazilian::trRelatedSubscript () inline virtual
subscript for the related functions.
Implements Translator.
Definition at line 91 of file translator_br.h.
trRemarks()
virtual QCString TranslatorBrazilian::trRemarks () inline virtual
Implements Translator.
Definition at line 1010 of file translator_br.h.
trReturns()
virtual QCString TranslatorBrazilian::trReturns () inline virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 548 of file translator_br.h.
trReturnValues()
virtual QCString TranslatorBrazilian::trReturnValues () inline virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 825 of file translator_br.h.
trRTFansicp()
virtual QCString TranslatorBrazilian::trRTFansicp () inline virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 1226 of file translator_br.h.
trRTFCharSet()
virtual QCString TranslatorBrazilian::trRTFCharSet () inline virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1235 of file translator_br.h.
trRTFGeneralIndex()
virtual QCString TranslatorBrazilian::trRTFGeneralIndex () inline virtual
Used as header RTF general index
Implements Translator.
Definition at line 1241 of file translator_br.h.
trRTFTableOfContents()
virtual QCString TranslatorBrazilian::trRTFTableOfContents () inline virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1378 of file translator_br.h.
trSearch()
virtual QCString TranslatorBrazilian::trSearch () inline virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 238 of file translator_br.h.
trSearching()
virtual QCString TranslatorBrazilian::trSearching () inline virtual
Message shown while searching
Implements Translator.
Definition at line 1831 of file translator_br.h.
trSearchMatches()
virtual QCString TranslatorBrazilian::trSearchMatches () inline virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1506 of file translator_br.h.
trSearchResults()
virtual QCString TranslatorBrazilian::trSearchResults (int numDocuments) inline virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1487 of file translator_br.h.
trSearchResultsTitle()
virtual QCString TranslatorBrazilian::trSearchResultsTitle () inline virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1475 of file translator_br.h.
trSeeAlso()
virtual QCString TranslatorBrazilian::trSeeAlso () inline virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 552 of file translator_br.h.
trServiceGeneratedFromFiles()
virtual QCString TranslatorBrazilian::trServiceGeneratedFromFiles (bool single) inline virtual
UNO IDL service page.
Implements Translator.
Definition at line 2059 of file translator_br.h.
trServiceReference()
virtual QCString TranslatorBrazilian::trServiceReference (const char * sName) inline virtual
UNO IDL service page title.
Implements Translator.
Definition at line 2043 of file translator_br.h.
trServices()
virtual QCString TranslatorBrazilian::trServices () inline virtual
old style UNO IDL services: inherited services
Implements Translator.
Definition at line 2028 of file translator_br.h.
trSignals()
virtual QCString TranslatorBrazilian::trSignals () inline virtual
Implements Translator.
Definition at line 665 of file translator_br.h.
trSince()
virtual QCString TranslatorBrazilian::trSince () inline virtual
Implements Translator.
Definition at line 1022 of file translator_br.h.
trSingletonGeneratedFromFiles()
virtual QCString TranslatorBrazilian::trSingletonGeneratedFromFiles (bool single) inline virtual
UNO IDL singleton page.
Implements Translator.
Definition at line 2072 of file translator_br.h.
trSingletonReference()
virtual QCString TranslatorBrazilian::trSingletonReference (const char * sName) inline virtual
UNO IDL singleton page title.
Implements Translator.
Definition at line 2050 of file translator_br.h.
trSourceFile()
virtual QCString TranslatorBrazilian::trSourceFile (QCString & filename) inline virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1517 of file translator_br.h.
trStaticPackageAttribs()
virtual QCString TranslatorBrazilian::trStaticPackageAttribs () inline virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1446 of file translator_br.h.
trStaticPackageMembers()
virtual QCString TranslatorBrazilian::trStaticPackageMembers () inline virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1432 of file translator_br.h.
trStaticPrivateAttribs()
virtual QCString TranslatorBrazilian::trStaticPrivateAttribs () inline virtual
Implements Translator.
Definition at line 982 of file translator_br.h.
trStaticPrivateMembers()
virtual QCString TranslatorBrazilian::trStaticPrivateMembers () inline virtual
Implements Translator.
Definition at line 686 of file translator_br.h.
trStaticProtectedAttribs()
virtual QCString TranslatorBrazilian::trStaticProtectedAttribs () inline virtual
Implements Translator.
Definition at line 970 of file translator_br.h.
trStaticProtectedMembers()
virtual QCString TranslatorBrazilian::trStaticProtectedMembers () inline virtual
Implements Translator.
Definition at line 677 of file translator_br.h.
trStaticPublicAttribs()
virtual QCString TranslatorBrazilian::trStaticPublicAttribs () inline virtual
Implements Translator.
Definition at line 958 of file translator_br.h.
trStaticPublicMembers()
virtual QCString TranslatorBrazilian::trStaticPublicMembers () inline virtual
Implements Translator.
Definition at line 668 of file translator_br.h.
trSubprogram()
virtual QCString TranslatorBrazilian::trSubprogram (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1795 of file translator_br.h.
trSubprogramDocumentation()
virtual QCString TranslatorBrazilian::trSubprogramDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1659 of file translator_br.h.
trSubprograms()
virtual QCString TranslatorBrazilian::trSubprograms () inline virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1653 of file translator_br.h.
trTemplateParameters()
virtual QCString TranslatorBrazilian::trTemplateParameters () inline virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1920 of file translator_br.h.
trTest()
virtual QCString TranslatorBrazilian::trTest () inline virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1115 of file translator_br.h.
trTestList()
virtual QCString TranslatorBrazilian::trTestList () inline virtual
Used as the header of the test list
Implements Translator.
Definition at line 1120 of file translator_br.h.
trThisIsTheListOfAllMembers()
virtual QCString TranslatorBrazilian::trThisIsTheListOfAllMembers () inline virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 145 of file translator_br.h.
trTodo()
virtual QCString TranslatorBrazilian::trTodo () inline virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 992 of file translator_br.h.
trTodoList()
virtual QCString TranslatorBrazilian::trTodoList () inline virtual
Used as the header of the todo list
Implements Translator.
Definition at line 997 of file translator_br.h.
trType()
virtual QCString TranslatorBrazilian::trType (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1784 of file translator_br.h.
trTypeConstraints()
virtual QCString TranslatorBrazilian::trTypeConstraints () inline virtual
C# Type Contraint list
Implements Translator.
Definition at line 1803 of file translator_br.h.
trTypedefDocumentation()
virtual QCString TranslatorBrazilian::trTypedefDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 478 of file translator_br.h.
trTypedefs()
virtual QCString TranslatorBrazilian::trTypedefs () inline virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 442 of file translator_br.h.
trTypeDocumentation()
virtual QCString TranslatorBrazilian::trTypeDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1647 of file translator_br.h.
trVariableDocumentation()
virtual QCString TranslatorBrazilian::trVariableDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 496 of file translator_br.h.
trVariables()
virtual QCString TranslatorBrazilian::trVariables () inline virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 460 of file translator_br.h.
trVersion()
virtual QCString TranslatorBrazilian::trVersion () inline virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 540 of file translator_br.h.
trWarning()
virtual QCString TranslatorBrazilian::trWarning () inline virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 536 of file translator_br.h.
trWriteList()
virtual QCString TranslatorBrazilian::trWriteList (int numEntries) inline virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 692 of file translator_br.h.
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_br.h