Doxygen: IndexWord Class Reference
IndexWord Class Reference
#include <searchindex.h>
Public Member Functions
IndexWord (const char *word)
void addUrlIndex (int, bool)
const QIntDict< URLInfo > & urls () const
QCString word () const
Private Attributes
QCString m_word
QIntDict< URLInfo > m_urls
Detailed Description
Definition at line 56 of file searchindex.h.
Constructor & Destructor Documentation
IndexWord()
IndexWord::IndexWord (const char * word)
Definition at line 56 of file searchindex.cpp.
References m_urls.
Member Function Documentation
addUrlIndex()
void IndexWord::addUrlIndex (int idx, bool hiPriority)
Definition at line 62 of file searchindex.cpp.
References URLInfo::freq, and m_urls.
Referenced by SearchIndex::addWord().
urls()
const QIntDict<URLInfo>& IndexWord::urls () const inline
Definition at line 61 of file searchindex.h.
References m_urls.
Referenced by SearchIndex::write().
word()
QCString IndexWord::word () const inline
Definition at line 62 of file searchindex.h.
References m_word.
Referenced by SearchIndex::write().
Member Data Documentation
m_urls
QIntDict<URLInfo> IndexWord::m_urls private
Definition at line 66 of file searchindex.h.
Referenced by addUrlIndex(), IndexWord(), and urls().
m_word
QCString IndexWord::m_word private
Definition at line 65 of file searchindex.h.
Referenced by word().
The documentation for this class was generated from the following files:
src/searchindex.h
src/searchindex.cpp