Doxygen: src/doxygen.cpp File Reference
doxygen.cpp File Reference
#include <locale.h>
#include <qfileinfo.h>
#include <qfile.h>
#include <qdir.h>
#include <qdict.h>
#include <qregexp.h>
#include <qstrlist.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <qtextcodec.h>
#include <errno.h>
#include <qptrdict.h>
#include <qtextstream.h>
#include "version.h"
#include "doxygen.h"
#include "scanner.h"
#include "entry.h"
#include "index.h"
#include "logos.h"
#include "message.h"
#include "config.h"
#include "util.h"
#include "pre.h"
#include "tagreader.h"
#include "dot.h"
#include "msc.h"
#include "docparser.h"
#include "dirdef.h"
#include "outputlist.h"
#include "declinfo.h"
#include "htmlgen.h"
#include "latexgen.h"
#include "mangen.h"
#include "language.h"
#include "debug.h"
#include "htmlhelp.h"
#include "qhp.h"
#include "ftvhelp.h"
#include "defargs.h"
#include "rtfgen.h"
#include "sqlite3gen.h"
#include "xmlgen.h"
#include "docbookgen.h"
#include "defgen.h"
#include "perlmodgen.h"
#include "reflist.h"
#include "pagedef.h"
#include "bufstr.h"
#include "commentcnv.h"
#include "cmdmapper.h"
#include "searchindex.h"
#include "parserintf.h"
#include "htags.h"
#include "pyscanner.h"
#include "fortranscanner.h"
#include "xmlscanner.h"
#include "sqlscanner.h"
#include "tclscanner.h"
#include "code.h"
#include "objcache.h"
#include "store.h"
#include "marshal.h"
#include "portable.h"
#include "vhdljjparser.h"
#include "vhdldocgen.h"
#include "eclipsehelp.h"
#include "cite.h"
#include "filestorage.h"
#include "markdown.h"
#include "arguments.h"
#include "memberlist.h"
#include "layout.h"
#include "groupdef.h"
#include "classlist.h"
#include "namespacedef.h"
#include "filename.h"
#include "membername.h"
#include "membergroup.h"
#include "docsets.h"
#include "formula.h"
#include "settings.h"
#include "context.h"
#include "fileparser.h"
#include <signal.h>
Classes
class Statistics
struct Statistics::stat
struct STLInfo
A struct contained the data for an STL class.
Macros
#define RECURSE_ENTRYTREE(func, var)
#define HAS_SIGNALS
Enumerations
enum FindBaseClassRelation_Mode { TemplateInstances, DocumentedOnly, Undocumented }
Functions
void initResources ()
static QDict< EntryNav > g_classEntries (1009)
static QDict< void > g_compoundKeywordDict (7)
static QDict< FileDef > g_usingDeclarations (1009)
void clearAll ()
void statistics ()
static void addMemberDocs (EntryNav *rootNav, MemberDef *md, const char *funcDecl, ArgumentList *al, bool over_load, NamespaceSDict *nl=0)
static void findMember (EntryNav *rootNav, QCString funcDecl, bool overloaded, bool isFunc)
static bool findClassRelation (EntryNav *rootNav, Definition *context, ClassDef *cd, BaseInfo *bi, QDict< int > *templateNames, FindBaseClassRelation_Mode mode, bool isArtificial)
static void addSTLMember (EntryNav *rootNav, const char *type, const char *name)
static void addSTLIterator (EntryNav *classEntryNav, const char *name)
static void addSTLClasses (EntryNav *rootNav)
static Definition * findScopeFromQualifiedName (Definition *startScope, const QCString &n, FileDef *fileScope, TagInfo *tagInfo)
static void addPageToContext (PageDef *pd, EntryNav *rootNav)
static void addRelatedPage (EntryNav *rootNav)
static void buildGroupListFiltered (EntryNav *rootNav, bool additional, bool includeExternal)
static void buildGroupList (EntryNav *rootNav)
static void findGroupScope (EntryNav *rootNav)
static void organizeSubGroupsFiltered (EntryNav *rootNav, bool additional)
static void organizeSubGroups (EntryNav *rootNav)
static void buildFileList (EntryNav *rootNav)
static void addIncludeFile (ClassDef *cd, FileDef *ifd, Entry *root)
static Definition * buildScopeFromQualifiedName (const QCString name, int level, SrcLangExt lang, TagInfo *tagInfo)
ArgumentList * getTemplateArgumentsFromName (const QCString &name, const QList< ArgumentList > *tArgLists)
static ClassDef::CompoundType convertToCompoundType (int section, uint64 specifier)
static void addClassToContext (EntryNav *rootNav)
static void buildClassList (EntryNav *rootNav)
static void buildClassDocList (EntryNav *rootNav)
static void resolveClassNestingRelations ()
void distributeClassGroupRelations ()
static ClassDef * createTagLessInstance (ClassDef *rootCd, ClassDef *templ, const QCString &fieldName)
static void processTagLessClasses (ClassDef *rootCd, ClassDef *cd, ClassDef *tagParentCd, const QCString &prefix, int count)
Look through the members of class cd and its public members.
static void findTagLessClasses (ClassDef *cd)
static void findTagLessClasses ()
static void buildNamespaceList (EntryNav *rootNav)
static NamespaceDef * findUsedNamespace (NamespaceSDict *unl, const QCString &name)
static void findUsingDirectives (EntryNav *rootNav)
static void buildListOfUsingDecls (EntryNav *rootNav)
static void findUsingDeclarations (EntryNav *rootNav)
static void findUsingDeclImports (EntryNav *rootNav)
static void findIncludedUsingDirectives ()
static MemberDef * addVariableToClass (EntryNav *rootNav, ClassDef *cd, MemberType mtype, const QCString &name, bool fromAnnScope, MemberDef *fromAnnMemb, Protection prot, Relationship related)
static MemberDef * addVariableToFile (EntryNav *rootNav, MemberType mtype, const QCString &scope, const QCString &name, bool fromAnnScope, MemberDef *fromAnnMemb)
static int findFunctionPtr (const QCString &type, int lang, int *pLength=0)
static bool isVarWithConstructor (EntryNav *rootNav)
static void addVariable (EntryNav *rootNav, int isFuncPtr=-1)
static void buildTypedefList (EntryNav *rootNav)
static void buildVarList (EntryNav *rootNav)
static void addInterfaceOrServiceToServiceOrSingleton (EntryNav *const rootNav, ClassDef *const cd, QCString const &rname)
static void buildInterfaceAndServiceList (EntryNav *const rootNav)
static void addMethodToClass (EntryNav *rootNav, ClassDef *cd, const QCString &rname, bool isFriend)
static void buildFunctionList (EntryNav *rootNav)
static void findFriends ()
static void transferFunctionDocumentation ()
static void transferFunctionReferences ()
static void transferRelatedFunctionDocumentation ()
static QDict< int > * getTemplateArgumentsInName (ArgumentList *templateArguments, const QCString &name)
static ClassDef * findClassWithinClassContext (Definition *context, ClassDef *cd, const QCString &name)
static void findUsedClassesForClass (EntryNav *rootNav, Definition *context, ClassDef *masterCd, ClassDef *instanceCd, bool isArtificial, ArgumentList *actualArgs=0, QDict< int > *templateNames=0)
static void findBaseClassesForClass (EntryNav *rootNav, Definition *context, ClassDef *masterCd, ClassDef *instanceCd, FindBaseClassRelation_Mode mode, bool isArtificial, ArgumentList *actualArgs=0, QDict< int > *templateNames=0)
static bool findTemplateInstanceRelation (Entry *root, Definition *context, ClassDef *templateClass, const QCString &templSpec, QDict< int > *templateNames, bool isArtificial)
static bool isRecursiveBaseClass (const QCString &scope, const QCString &name)
static int findEndOfTemplate (const QCString &s, int startPos)
static bool isClassSection (EntryNav *rootNav)
static void findClassEntries (EntryNav *rootNav)
static QCString extractClassName (EntryNav *rootNav)
static void findInheritedTemplateInstances ()
static void findUsedTemplateInstances ()
static void computeClassRelations ()
static void computeTemplateClassRelations ()
static void computeMemberReferences ()
static void addListReferences ()
static void generateXRefPages ()
static ClassDef * findClassDefinition (FileDef *fd, NamespaceDef *nd, const char *scopeName)
static bool findGlobalMember (EntryNav *rootNav, const QCString &namespaceName, const char *type, const char *name, const char *tempArg, const char *, const char *decl)
static bool isSpecialization (const QList< ArgumentList > &srcTempArgLists, const QList< ArgumentList > &dstTempArgLists)
static bool scopeIsTemplate (Definition *d)
static QCString substituteTemplatesInString (const QList< ArgumentList > &srcTempArgLists, const QList< ArgumentList > &dstTempArgLists, ArgumentList *funcTempArgList, const QCString &src)
static void substituteTemplatesInArgList (const QList< ArgumentList > &srcTempArgLists, const QList< ArgumentList > &dstTempArgLists, ArgumentList *src, ArgumentList *dst, ArgumentList *funcTempArgs=0)
static void filterMemberDocumentation (EntryNav *rootNav)
static void findMemberDocumentation (EntryNav *rootNav)
static void findObjCMethodDefinitions (EntryNav *rootNav)
static void findEnums (EntryNav *rootNav)
static void addEnumValuesToEnums (EntryNav *rootNav)
static void findEnumDocumentation (EntryNav *rootNav)
static void findDEV (const MemberNameSDict &mnsd)
static void findDocumentedEnumValues ()
static void addMembersToIndex ()
static void computeMemberRelations ()
static void createTemplateInstanceMembers ()
static void mergeCategories ()
static void buildCompleteMemberLists ()
static void generateFileSources ()
static void generateFileDocs ()
static void addSourceReferences ()
static void sortMemberLists ()
static void generateClassList (ClassSDict &classSDict)
static void generateClassDocs ()
static void inheritDocumentation ()
static void combineUsingRelations ()
static void addMembersToMemberGroup ()
static void distributeMemberGroupDocumentation ()
static void findSectionsInDocumentation ()
static void flushCachedTemplateRelations ()
static void flushUnresolvedRelations ()
static void findDefineDocumentation (EntryNav *rootNav)
static void findDirDocumentation (EntryNav *rootNav)
static void buildPageList (EntryNav *rootNav)
static void findMainPage (EntryNav *rootNav)
static void findMainPageTagFiles (EntryNav *rootNav)
static void computePageRelations (EntryNav *rootNav)
static void checkPageRelations ()
static void resolveUserReferences ()
static void generatePageDocs ()
static void buildExampleList (EntryNav *rootNav)
void printNavTree (EntryNav *rootNav, int indent)
static void generateExampleDocs ()
static void generateGroupDocs ()
static void generateNamespaceDocs ()
static void generateConfigFile (const char *configFile, bool shortList, bool updateOnly=FALSE)
static void readTagFile (Entry *root, const char *tl)
static void copyLatexStyleSheet ()
static void copyStyleSheet ()
static void copyLogo (const QCString &outputOption)
static void copyExtraFiles (QStrList files, const QString &filesOption, const QCString &outputOption)
static ParserInterface * getParserForFile (const char *fn)
static void parseFile (ParserInterface *parser, Entry *root, EntryNav *rootNav, FileDef *fd, const char *fn, bool sameTu, QStrList &filesInSameTu)
static void parseFiles (Entry *root, EntryNav *rootNav)
parse the list of input files
static QCString resolveSymlink (QCString path)
static QDict< void > g_pathsVisited (1009)
int readDir (QFileInfo *fi, FileNameList *fnList, FileNameDict *fnDict, StringDict *exclDict, QStrList *patList, QStrList *exclPatList, StringList *resultList, StringDict *resultDict, bool errorIfNotExist, bool recursive, QDict< void > *killDict, QDict< void > *paths)
int readFileOrDirectory (const char *s, FileNameList *fnList, FileNameDict *fnDict, StringDict *exclDict, QStrList *patList, QStrList *exclPatList, StringList *resultList, StringDict *resultDict, bool recursive, bool errorIfNotExist, QDict< void > *killDict, QDict< void > *paths)
void readFormulaRepository ()
static void expandAliases ()
static void escapeAliases ()
void readAliases ()
static void dumpSymbol (FTextStream &t, Definition *d)
static void dumpSymbolMap ()
static void devUsage ()
static void usage (const char *name)
static const char * getArg (int argc, char **argv, int &optind)
void initDoxygen ()
void cleanUpDoxygen ()
static int computeIdealCacheParam (uint v)
void readConfiguration (int argc, char **argv)
void checkConfiguration ()
check and resolve config options
void adjustConfiguration ()
adjust globals that depend on configuration settings.
static void stopDoxygen (int)
static void writeTagFile ()
static void exitDoxygen ()
static QCString createOutputDirectory (const QCString &baseDirName, QCString &formatDirName, const char *defaultDirName)
static QCString getQchFileName ()
void searchInputFiles ()
void parseInput ()
void generateOutput ()
Variables
static StringList g_inputFiles
static OutputList * g_outputList = 0
static FileStorage * g_storage = 0
static bool g_successfulRun = FALSE
static bool g_dumpSymbolMap = FALSE
static bool g_useOutputTemplate = FALSE
class Statistics g_s
static STLInfo g_stlinfo []
Macro Definition Documentation
HAS_SIGNALS
#define HAS_SIGNALS
Definition at line 115 of file doxygen.cpp.
RECURSE_ENTRYTREE
#define RECURSE_ENTRYTREE (func, var)
Value:
do { if (var->children()) { \
    EntryNavListIterator eli(*var->children()); \
    for (;eli.current();++eli) func(eli.current()); \
  } } while(0)
Definition at line 106 of file doxygen.cpp.
Referenced by addEnumValuesToEnums(), buildClassDocList(), buildClassList(), buildExampleList(), buildFileList(), buildFunctionList(), buildInterfaceAndServiceList(), buildListOfUsingDecls(), buildNamespaceList(), buildPageList(), computePageRelations(), findClassEntries(), findDefineDocumentation(), findDirDocumentation(), findEnumDocumentation(), findEnums(), findGroupScope(), findMainPage(), findMainPageTagFiles(), findUsingDeclarations(), findUsingDeclImports(), and findUsingDirectives().
Enumeration Type Documentation
FindBaseClassRelation_Mode
enum FindBaseClassRelation_Mode
Enumerator
TemplateInstances
DocumentedOnly
Undocumented
Definition at line 305 of file doxygen.cpp.
Function Documentation
addClassToContext()
static void addClassToContext (EntryNav * rootNav) static
Definition at line 1237 of file doxygen.cpp.
References addClassToGroups(), addIncludeFile(), Definition::addSectionsToDefinition(), Entry::anchors, SDict< T >::append(), Entry::artificial, Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, buildScopeFromQualifiedName(), Debug::Classes, Entry::COMPOUND_MASK, convertToCompoundType(), Entry::doc, Entry::docFile, Entry::docLine, Entry::endBodyLine, EntryNav::entry(), Entry::Enum, extractNamespaceName(), EntryNav::fileDef(), TagInfo::fileName, Entry::fileName, Entry::ForwardDecl, getClass(), Definition::getStartBodyLine(), getTemplateArgumentsFromName(), ClassDef::hasDocumentation(), Entry::hidden, Entry::id, GenericsSDict::insert(), FileDef::insertClass(), ClassDef::insertUsedFile(), ClassDef::isForwardDeclared(), ClassDef::isGeneric(), Entry::lang, leftScopeMatch(), EntryNav::loadEntry(), Definition::name(), Entry::name, EntryNav::name(), EntryNav::parent(), Debug::print(), Entry::protection, EntryNav::releaseEntry(), Entry::SCOPE_MASK, Entry::section, EntryNav::section(), Definition::setArtificial(), Definition::setBodyDef(), Definition::setBodySegment(), Definition::setBriefDescription(), ClassDef::setClassSpecifier(), ClassDef::setCompoundType(), Definition::setDocumentation(), ClassDef::setFileDef(), Definition::setHidden(), Definition::setId(), ClassDef::setIsStatic(), Definition::setLanguage(), ClassDef::setProtection(), Definition::setRefItems(), ClassDef::setSubGrouping(), ClassDef::setTemplateArguments(), ClassDef::setTypeConstraints(), Entry::sli, Entry::spec, SrcLangExt_CSharp, SrcLangExt_Java, Entry::startColumn, Entry::startLine, Entry::stat, stringToArgumentList(), stripTemplateSpecifiersFromScope(), Entry::subGrouping, EntryNav::tagInfo(), TagInfo::tagName, Entry::tArgLists, ClassDef::templateArguments(), and Entry::typeConstr.
Referenced by buildClassDocList(), and buildClassList().
addEnumValuesToEnums()
static void addEnumValuesToEnums (EntryNav * rootNav) static
Definition at line 7216 of file doxygen.cpp.
References Definition::addSectionsToDefinition(), Entry::anchors, SDict< T >::append(), Entry::args, Entry::brief, Entry::briefFile, Entry::briefLine, EntryNav::children(), Entry::doc, Entry::docFile, Entry::docLine, EntryNav::entry(), Entry::ENUM_SEC, Entry::explicitExternal, EntryNav::fileDef(), Entry::fileName, SDict< T >::find(), Doxygen::functionNameSDict, getClass(), MemberDef::getClassDef(), MemberDef::getFileDef(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), getResolvedNamespace(), Entry::id, Entry::initializer, Entry::initLines, MemberDef::insertEnumField(), ClassDef::insertMember(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), Entry::lang, EntryNav::lang(), EntryNav::loadEntry(), MemberDef::makeRelated(), Member, Doxygen::memberNameSDict, MemberType_EnumValue, mergeScopes(), Entry::mGrpId, Definition::name(), Entry::name, EntryNav::name(), Normal, EntryNav::parent(), Entry::protection, MemberDef::qualifiedName(), RECURSE_ENTRYTREE, Entry::relates, EntryNav::releaseEntry(), Entry::SCOPE_MASK, EntryNav::section(), MemberDef::setAnchor(), MemberDef::setBriefDescription(), MemberDef::setDocumentation(), MemberDef::setEnumClassScope(), MemberDef::setEnumScope(), MemberDef::setExplicitExternal(), MemberDef::setFileDef(), Definition::setId(), MemberDef::setInitializer(), Definition::setLanguage(), MemberDef::setMaxInitLines(), MemberDef::setMemberClass(), MemberDef::setMemberGroupId(), MemberDef::setNamespace(), Definition::setOuterScope(), Definition::setRefItems(), MemberDef::setTagInfo(), Entry::sli, Entry::spec, SrcLangExt_CSharp, SrcLangExt_Java, SrcLangExt_XML, Entry::startColumn, Entry::startLine, Entry::stat, Entry::Strong, substitute(), EntryNav::tagInfo(), TagInfo::tagName, and Entry::type.
Referenced by parseInput().
addIncludeFile()
static void addIncludeFile (ClassDef * cd, FileDef * ifd, Entry * root) static
Definition at line 844 of file doxygen.cpp.
References FileDef::absFilePath(), Entry::brief, Config_getBool, Config_getList, Entry::doc, Entry::fileName, findFileDef(), FileDef::generateSourceFile(), guessSection(), Entry::HEADER_SEC, Entry::includeFile, Entry::includeName, FileDef::name(), Private, Entry::protection, ClassDef::setIncludeFile(), showFileDefMatches(), Entry::startLine, stripFromIncludePath(), and warn().
Referenced by addClassToContext().
addInterfaceOrServiceToServiceOrSingleton()
static void addInterfaceOrServiceToServiceOrSingleton (EntryNav *const rootNav, ClassDef *const cd, QCString const & rname) static
Definition at line 3095 of file doxygen.cpp.
References addMemberToGroups(), Definition::addSectionsToDefinition(), Entry::anchors, SDict< T >::append(), Entry::argList, Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, EntryNav::changeSection(), Entry::doc, Entry::docFile, Entry::docLine, DocumentedOnly, Entry::EMPTY_SEC, MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), Entry::endBodyLine, EntryNav::entry(), Entry::EXPORTED_INTERFACE_SEC, EntryNav::fileDef(), Entry::fileName, findClassRelation(), Debug::Functions, Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, ClassDef::insertMember(), ClassDef::insertUsedFile(), Entry::lang, Member, MemberType_Interface, MemberType_Service, Entry::mGrpId, Normal, Entry::Optional, Debug::print(), Protected, Entry::protection, Entry::proto, Public, EntryNav::section(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDefinition(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setFileDef(), MemberDef::setInbodyDocumentation(), Definition::setLanguage(), MemberDef::setMemberClass(), MemberDef::setMemberGroupId(), MemberDef::setMemberSpecifiers(), Definition::setRefItems(), MemberDef::setTagInfo(), MemberDef::setTypeConstraints(), Entry::sli, Entry::spec, Entry::startColumn, Entry::startLine, Entry::stat, EntryNav::tagInfo(), TagInfo::tagName, Entry::type, Entry::typeConstr, Undocumented, and Entry::virt.
Referenced by buildInterfaceAndServiceList().
addListReferences()
static void addListReferences () static
Definition at line 5197 of file doxygen.cpp.
References GroupDef::addListReferences(), NamespaceDef::addListReferences(), FileDef::addListReferences(), ClassDef::addListReferences(), addRefItem(), DirDef::displayName(), PageDef::getGroupDef(), PageDef::getOutputFileBase(), GroupDef::getOutputFileBase(), DirDef::getOutputFileBase(), SDict< MemberName >::Iterator, SDict< GroupDef >::Iterator, SDict< PageDef >::Iterator, SDict< NamespaceDef >::Iterator, SDict< DirDef >::Iterator, SDict< ClassDef >::Iterator, theTranslator, PageDef::title(), Translator::trDir(), Translator::trPage(), MemberDef::visited, and Definition::xrefListItems().
Referenced by parseInput().
addMemberDocs()
static void addMemberDocs (EntryNav * rootNav, MemberDef * md, const char * funcDecl, ArgumentList * al, bool over_load, NamespaceSDict * nl = 0) static
Definition at line 5306 of file doxygen.cpp.
References addMemberToGroups(), Definition::addSectionsToDefinition(), Entry::anchors, Entry::argList, MemberDef::argumentList(), Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, doc, Entry::doc, Entry::docFile, Entry::docLine, MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), Entry::endBodyLine, EntryNav::entry(), EntryNav::fileDef(), Entry::fileName, MemberDef::getClassDef(), MemberDef::getFileDef(), MemberDef::getMemberGroupId(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), getOverloadDocs(), Definition::getStartBodyLine(), MemberDef::hasCallerGraph(), MemberDef::hasCallGraph(), Entry::inbodyDocs, Definition::inbodyDocumentation(), Entry::inbodyFile, Entry::inbodyLine, MemberDef::initializer(), Entry::initializer, Entry::initLines, ClassDef::insertUsedFile(), matchArguments2(), mergeArguments(), MemberDef::mergeMemberSpecifiers(), Entry::mGrpId, Definition::name(), EntryNav::name(), EntryNav::parent(), Entry::proto, Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDefinition(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setInbodyDocumentation(), MemberDef::setInitializer(), MemberDef::setMaxInitLines(), MemberDef::setMemberGroupId(), Definition::setRefItems(), Entry::sli, Entry::spec, Entry::startLine, and warn().
Referenced by addVariableToClass(), addVariableToFile(), findGlobalMember(), and findMember().
addMembersToIndex()
static void addMembersToIndex () static
Definition at line 7631 of file doxygen.cpp.
References addClassMemberNameToIndex(), addFileMemberNameToIndex(), addNamespaceMemberNameToIndex(), MemberDef::getNamespaceDef(), and SDict< MemberName >::Iterator.
Referenced by parseInput().
addMembersToMemberGroup()
static void addMembersToMemberGroup () static
Definition at line 8228 of file doxygen.cpp.
References NamespaceDef::addMembersToMemberGroup(), GroupDef::addMembersToMemberGroup(), FileDef::addMembersToMemberGroup(), ClassDef::addMembersToMemberGroup(), SDict< NamespaceDef >::Iterator, SDict< ClassDef >::Iterator, and SDict< GroupDef >::Iterator.
Referenced by parseInput().
addMethodToClass()
static void addMethodToClass (EntryNav * rootNav, ClassDef * cd, const QCString & rname, bool isFriend) static
Definition at line 3242 of file doxygen.cpp.
References addMemberToGroups(), Definition::addSectionsToDefinition(), Entry::Alias, Entry::anchors, SDict< T >::append(), Entry::argList, Entry::args, Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, EntryNav::changeSection(), Config_getBool, DCOP, Entry::doc, Entry::docFile, Entry::docLine, Entry::EMPTY_SEC, MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), Entry::endBodyLine, EntryNav::entry(), Entry::exception, EntryNav::fileDef(), Entry::fileName, Foreign, Debug::Functions, Definition::getLanguage(), getLanguageSpecificSeparator(), Entry::id, Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, ClassDef::insertMember(), ClassDef::insertUsedFile(), Entry::lang, Member, MemberOf, MemberType_DCOP, MemberType_Friend, MemberType_Function, MemberType_Signal, MemberType_Slot, Entry::mGrpId, Entry::mtype, Debug::print(), Entry::protection, Entry::proto, ClassDef::qualifiedNameWithTemplateParameters(), Related, Entry::relates, Entry::relatesType, removeRedundantWhiteSpace(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDefinition(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setFileDef(), Definition::setId(), MemberDef::setInbodyDocumentation(), Definition::setLanguage(), MemberDef::setMemberClass(), MemberDef::setMemberGroupId(), MemberDef::setMemberSpecifiers(), Definition::setRefItems(), MemberDef::setTagInfo(), MemberDef::setTypeConstraints(), Signal, Entry::sli, Slot, Entry::spec, SrcLangExt_Cpp, SrcLangExt_PHP, Entry::startColumn, Entry::startLine, Entry::stat, substitute(), EntryNav::tagInfo(), TagInfo::tagName, Entry::tArgLists, Entry::type, Entry::typeConstr, and Entry::virt.
Referenced by buildFunctionList(), and findMember().
addPageToContext()
static void addPageToContext (PageDef * pd, EntryNav * rootNav) static
Definition at line 559 of file doxygen.cpp.
References findScopeFromQualifiedName(), Definition::name(), EntryNav::name(), Entry::PACKAGEDOC_SEC, EntryNav::parent(), EntryNav::section(), PageDef::setPageScope(), stripAnonymousNamespaceScope(), substitute(), and EntryNav::tagInfo().
Referenced by addRelatedPage(), and findMainPage().
addRelatedPage()
static void addRelatedPage (EntryNav * rootNav) static
Definition at line 578 of file doxygen.cpp.
References addPageToContext(), Definition::addSectionsToDefinition(), Entry::anchors, Entry::args, Entry::brief, Entry::briefFile, Entry::briefLine, doc, Entry::doc, Entry::docFile, Entry::docLine, EntryNav::entry(), SDict< T >::find(), Grouping::groupname, Entry::groups, Entry::inbodyDocs, Entry::lang, Entry::name, Definition::setBriefDescription(), PageDef::setShowToc(), Entry::sli, Entry::stat, and EntryNav::tagInfo().
Referenced by buildPageList(), CiteDict::generatePage(), and RefList::generatePage().
addSourceReferences()
static void addSourceReferences () static
Definition at line 7991 of file doxygen.cpp.
References FileDef::addSourceRef(), FileDef::generateSourceFile(), Definition::getBodyDef(), Definition::getOuterScope(), Definition::getStartBodyLine(), NamespaceDef::isLinkableInProject(), ClassDef::isLinkableInProject(), MemberDef::isLinkableInProject(), SDict< NamespaceDef >::Iterator, SDict< ClassDef >::Iterator, SDict< MemberName >::Iterator, and Doxygen::parseSourcesNeeded.
Referenced by parseInput().
addSTLClasses()
static void addSTLClasses (EntryNav * rootNav) static
Definition at line 452 of file doxygen.cpp.
References EntryNav::addChild(), addSTLIterator(), addSTLMember(), Entry::args, Entry::artificial, STLInfo::baseClass1, STLInfo::baseClass2, Entry::brief, Entry::CLASS_SEC, STLInfo::className, Entry::extends, Entry::fileName, Entry::FUNCTION_SEC, g_stlinfo, Entry::hidden, STLInfo::iterators, Argument::name, Entry::name, Entry::NAMESPACE_SEC, Normal, Entry::protection, Public, Entry::section, EntryNav::setEntry(), Entry::startLine, Entry::tArgLists, STLInfo::templName1, STLInfo::templName2, STLInfo::templType1, STLInfo::templType2, Argument::type, Entry::type, Virtual, and STLInfo::virtualInheritance.
Referenced by parseInput().
addSTLIterator()
static void addSTLIterator (EntryNav * classEntryNav, const char * name) static
Definition at line 436 of file doxygen.cpp.
References EntryNav::addChild(), Entry::artificial, Entry::brief, Entry::CLASS_SEC, Entry::fileName, Entry::hidden, Entry::name, Entry::section, EntryNav::setEntry(), and Entry::startLine.
Referenced by addSTLClasses().
addSTLMember()
static void addSTLMember (EntryNav * rootNav, const char * type, const char * name) static
Definition at line 419 of file doxygen.cpp.
References EntryNav::addChild(), Entry::artificial, Entry::brief, Entry::hidden, Entry::name, Entry::protection, Public, Entry::section, EntryNav::setEntry(), Entry::type, and Entry::VARIABLE_SEC.
Referenced by addSTLClasses().
addVariable()
static void addVariable (EntryNav * rootNav, int isFuncPtr = -1) static
Definition at line 2818 of file doxygen.cpp.
References addVariableToClass(), addVariableToFile(), Entry::Alias, Entry::args, Entry::bodyLine, Config_getBool, EntryNav::entry(), Event, findFunctionPtr(), Foreign, getClass(), Entry::lang, EntryNav::loadEntry(), Member, MemberOf, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Property, MemberType_Typedef, MemberType_Variable, mergeScopes(), Entry::mGrpId, Entry::mtype, Entry::name, EntryNav::name(), EntryNav::parent(), Debug::print(), Property, Entry::protection, Public, Related, Entry::relates, Entry::relatesType, EntryNav::releaseEntry(), removeRedundantWhiteSpace(), Entry::SCOPE_MASK, EntryNav::section(), Entry::spec, stripAnonymousNamespaceScope(), stripTemplateSpecifiersFromScope(), Entry::type, and Debug::Variables.
Referenced by buildTypedefList(), and buildVarList().
addVariableToClass()
static MemberDef* addVariableToClass (EntryNav * rootNav, ClassDef * cd, MemberType mtype, const QCString & name, bool fromAnnScope, MemberDef * fromAnnMemb, Protection prot, Relationship related) static
Definition at line 2245 of file doxygen.cpp.
References addMemberDocs(), addMemberToGroups(), Definition::addSectionsToDefinition(), Entry::Alias, Entry::anchors, SDict< T >::append(), Entry::args, Entry::artificial, Entry::bitfields, Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, EntryNav::changeSection(), Config_getBool, Entry::doc, Entry::docFile, Entry::docLine, Entry::EMPTY_SEC, MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), Entry::endBodyLine, EntryNav::entry(), Entry::exception, EntryNav::fileDef(), Entry::fileName, SDict< T >::find(), MemberDef::getClassDef(), Definition::getLanguage(), Entry::hidden, Entry::id, Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, Entry::initializer, Entry::initLines, ClassDef::insertMember(), ClassDef::insertUsedFile(), Entry::lang, MemberDef::memberType(), MemberType_Friend, MemberType_Property, MemberType_Variable, Entry::mGrpId, Entry::mtype, Normal, Debug::print(), Property, Entry::protection, ClassDef::qualifiedNameWithTemplateParameters(), Entry::read, ClassDef::reclassifyMember(), removeRedundantWhiteSpace(), Definition::setArtificial(), MemberDef::setBitfields(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDefinition(), MemberDef::setDocumentation(), MemberDef::setFromAnonymousMember(), MemberDef::setFromAnonymousScope(), MemberDef::setHidden(), Definition::setId(), MemberDef::setInbodyDocumentation(), MemberDef::setInitializer(), Definition::setLanguage(), MemberDef::setMaxInitLines(), MemberDef::setMemberClass(), MemberDef::setMemberGroupId(), MemberDef::setMemberSpecifiers(), MemberDef::setProtection(), MemberDef::setReadAccessor(), Definition::setRefItems(), MemberDef::setTagInfo(), MemberDef::setWriteAccessor(), Entry::sli, Entry::spec, SrcLangExt_CSharp, SrcLangExt_Java, SrcLangExt_ObjC, Entry::startColumn, Entry::startLine, Entry::stat, substitute(), EntryNav::tagInfo(), TagInfo::tagName, Entry::tArgLists, Entry::type, MemberDef::typeString(), Debug::Variables, and Entry::write.
Referenced by addVariable().
addVariableToFile()
static MemberDef* addVariableToFile (EntryNav * rootNav, MemberType mtype, const QCString & scope, const QCString & name, bool fromAnnScope, MemberDef * fromAnnMemb) static
Definition at line 2422 of file doxygen.cpp.
References FileDef::absFilePath(), addMemberDocs(), addMemberToGroups(), Entry::Alias, Entry::anchors, SDict< T >::append(), Entry::args, MemberDef::argsString(), Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, EntryNav::changeSection(), Config_getBool, Entry::doc, Entry::docFile, Entry::docLine, Entry::EMPTY_SEC, Entry::endBodyLine, EntryNav::entry(), Entry::explicitExternal, EntryNav::fileDef(), Entry::fileName, SDict< T >::find(), getClass(), Definition::getDefFileName(), MemberDef::getFileDef(), Definition::getLanguage(), getLanguageSpecificSeparator(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), getResolvedNamespace(), Entry::id, Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, Entry::initializer, Entry::initLines, NamespaceDef::insertMember(), FileDef::insertMember(), MemberDef::isDefine(), MemberDef::isEnumerate(), MemberDef::isStatic(), Entry::lang, Member, MemberType_Typedef, Entry::mGrpId, Definition::name(), Entry::name, Normal, Debug::print(), Entry::protection, Definition::setBriefDescription(), ClassDef::setClassName(), Definition::setDocumentation(), Definition::setRefItems(), MemberDef::setTagInfo(), Entry::sli, Entry::spec, SrcLangExt_PHP, Entry::startColumn, Entry::startLine, Entry::stat, EntryNav::tagInfo(), TagInfo::tagName, Entry::tArgLists, Entry::type, and Debug::Variables.
Referenced by addVariable().
adjustConfiguration()
void adjustConfiguration ()
adjust globals that depend on configuration settings.
Definition at line 10503 of file doxygen.cpp.
References addSearchDir(), Config_getBool, Config_getEnum, Config_getInt, Config_getList, Config_getString, err(), Doxygen::expandAsDefinedDict, Doxygen::htmlFileExtension, Doxygen::markdownSupport, msg(), Doxygen::parseSourcesNeeded, readAliases(), setTranslator(), Doxygen::spaces, updateLanguageMapping(), warn_uncond(), and Doxygen::xrefLists.
Referenced by main().
buildClassDocList()
static void buildClassDocList (EntryNav * rootNav) static
Definition at line 1418 of file doxygen.cpp.
References addClassToContext(), Entry::COMPOUNDDOC_MASK, EntryNav::name(), RECURSE_ENTRYTREE, and EntryNav::section().
Referenced by parseInput().
buildClassList()
static void buildClassList (EntryNav * rootNav) static
Definition at line 1406 of file doxygen.cpp.
References addClassToContext(), Entry::COMPOUND_MASK, EntryNav::name(), Entry::OBJCIMPL_SEC, RECURSE_ENTRYTREE, and EntryNav::section().
Referenced by parseInput().
buildCompleteMemberLists()
static void buildCompleteMemberLists () static
Definition at line 7798 of file doxygen.cpp.
References ClassDef::baseClasses(), SDict< ClassDef >::Iterator, ClassDef::memberNameInfoSDict(), ClassDef::mergeMembers(), SDict< T >::sort(), and ClassDef::subClasses().
Referenced by parseInput().
buildExampleList()
static void buildExampleList (EntryNav * rootNav) static
Definition at line 8923 of file doxygen.cpp.
References Definition::addSectionsToDefinition(), Entry::anchors, Entry::args, Entry::brief, Entry::briefFile, Entry::briefLine, convertNameToFile(), Entry::doc, EntryNav::entry(), Entry::EXAMPLE_SEC, Entry::fileName, Entry::inbodyDocs, SDict< T >::inSort(), Entry::lang, EntryNav::loadEntry(), Definition::name(), Entry::name, EntryNav::name(), RECURSE_ENTRYTREE, EntryNav::releaseEntry(), EntryNav::section(), Definition::setBriefDescription(), PageDef::setFileName(), Definition::setLanguage(), Entry::startLine, and warn().
Referenced by parseInput().
buildFileList()
static void buildFileList (EntryNav * rootNav) static
Definition at line 767 of file doxygen.cpp.
References GroupDef::addFile(), Definition::addSectionsToDefinition(), Entry::anchors, Entry::brief, Definition::briefDescription(), Entry::briefFile, Entry::briefLine, Config_getBool, Entry::doc, Entry::docFile, Entry::docLine, Definition::documentation(), EntryNav::entry(), Entry::FILE_MASK, Entry::FILEDOC_SEC, Entry::fileName, SDict< T >::find(), findFileDef(), Grouping::groupname, Entry::groups, EntryNav::loadEntry(), Definition::makePartOfGroup(), Entry::name, EntryNav::name(), RECURSE_ENTRYTREE, EntryNav::releaseEntry(), EntryNav::section(), Definition::setBriefDescription(), Definition::setDocumentation(), Definition::setRefItems(), showFileDefMatches(), Entry::sli, Entry::startLine, EntryNav::tagInfo(), and warn().
Referenced by parseInput().
buildFunctionList()
static void buildFunctionList (EntryNav * rootNav) static
Definition at line 3422 of file doxygen.cpp.
References FileDef::absFilePath(), addMemberToGroups(), addMethodToClass(), Definition::addSectionsToDefinition(), Entry::anchors, SDict< T >::append(), Entry::argList, Entry::args, Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, EntryNav::changeSection(), Entry::COMPOUND_MASK, Entry::doc, Entry::docFile, Entry::docLine, Duplicate, Entry::EMPTY_SEC, MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), Entry::endBodyLine, EntryNav::entry(), Entry::exception, EntryNav::fileDef(), Entry::fileName, SDict< T >::find(), Entry::FUNCTION_SEC, Debug::Functions, getClass(), Definition::getLanguage(), getLanguageSpecificSeparator(), getResolvedNamespace(), Doxygen::globalScope, Entry::groups, Entry::id, Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, NamespaceDef::insertMember(), FileDef::insertMember(), Entry::lang, leftScopeMatch(), EntryNav::loadEntry(), matchArguments2(), Member, MemberType_Function, mergeArguments(), Entry::mGrpId, Definition::name(), Entry::name, EntryNav::name(), Entry::NAMESPACE_SEC, Entry::OBJCIMPL_SEC, EntryNav::parent(), Debug::print(), Entry::protection, Entry::proto, RECURSE_ENTRYTREE, Entry::relates, Entry::relatesType, EntryNav::releaseEntry(), removeRedundantWhiteSpace(), EntryNav::section(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDefinition(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setFileDef(), Definition::setId(), MemberDef::setInbodyDocumentation(), Definition::setLanguage(), MemberDef::setMemberGroupId(), MemberDef::setMemberSpecifiers(), MemberDef::setNamespace(), MemberDef::setPrototype(), Definition::setRefItems(), MemberDef::setTagInfo(), MemberDef::setTypeConstraints(), Simple, Entry::sli, Entry::spec, SrcLangExt_Cpp, Entry::startColumn, Entry::startLine, Entry::stat, stringToArgumentList(), stripTemplateSpecifiersFromScope(), substitute(), EntryNav::tagInfo(), Entry::tArgLists, Entry::type, Entry::typeConstr, Entry::virt, and warn().
Referenced by parseInput().
buildGroupList()
static void buildGroupList (EntryNav * rootNav) static
Definition at line 684 of file doxygen.cpp.
References buildGroupListFiltered().
Referenced by parseInput().
buildGroupListFiltered()
static void buildGroupListFiltered (EntryNav * rootNav, bool additional, bool includeExternal) static
Definition at line 613 of file doxygen.cpp.
References Definition::addSectionsToDefinition(), Entry::anchors, SDict< T >::append(), Entry::brief, Entry::briefFile, Entry::briefLine, EntryNav::children(), Entry::doc, Entry::docFile, Entry::docLine, EntryNav::entry(), TagInfo::fileName, Entry::fileName, SDict< T >::find(), Entry::GROUPDOC_NORMAL, Entry::GROUPDOC_SEC, Entry::groupDocType, GroupDef::groupTitle(), GroupDef::hasGroupTitle(), Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, Entry::lang, EntryNav::loadEntry(), Entry::name, EntryNav::name(), EntryNav::releaseEntry(), EntryNav::section(), Definition::setBriefDescription(), Definition::setDocumentation(), GroupDef::setGroupTitle(), Definition::setInbodyDocumentation(), Definition::setLanguage(), Definition::setReference(), Definition::setRefItems(), Entry::sli, Entry::startLine, EntryNav::tagInfo(), TagInfo::tagName, Entry::type, and warn().
Referenced by buildGroupList().
buildInterfaceAndServiceList()
static void buildInterfaceAndServiceList (EntryNav *const rootNav) static
Definition at line 3172 of file doxygen.cpp.
References addInterfaceOrServiceToServiceOrSingleton(), Entry::args, Entry::bodyLine, ClassDef::compoundType(), Entry::docFile, EntryNav::entry(), Entry::EXPORTED_INTERFACE_SEC, Entry::fileName, Debug::Functions, getClass(), Entry::INCLUDED_SERVICE_SEC, ClassDef::Interface, EntryNav::lang(), EntryNav::loadEntry(), Entry::mGrpId, Entry::name, EntryNav::name(), EntryNav::parent(), Debug::print(), Entry::proto, RECURSE_ENTRYTREE, Entry::relates, Entry::relatesType, EntryNav::releaseEntry(), removeRedundantWhiteSpace(), EntryNav::section(), ClassDef::Service, ClassDef::Singleton, Entry::spec, SrcLangExt_IDL, SrcLangExt_Unknown, Entry::startLine, Entry::tArgLists, Entry::type, and warn().
Referenced by parseInput().
buildListOfUsingDecls()
static void buildListOfUsingDecls (EntryNav * rootNav) static
Definition at line 1993 of file doxygen.cpp.
References Entry::COMPOUND_MASK, EntryNav::entry(), EntryNav::fileDef(), g_usingDeclarations(), EntryNav::loadEntry(), Entry::name, EntryNav::parent(), RECURSE_ENTRYTREE, EntryNav::releaseEntry(), EntryNav::section(), substitute(), and Entry::USINGDECL_SEC.
Referenced by parseInput().
buildNamespaceList()
static void buildNamespaceList (EntryNav * rootNav) static
Definition at line 1712 of file doxygen.cpp.
References Definition::addInnerCompound(), addNamespaceToGroups(), Definition::addSectionsToDefinition(), Entry::anchors, Entry::artificial, Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, buildScopeFromQualifiedName(), Entry::doc, Entry::docFile, Entry::docLine, Entry::endBodyLine, EntryNav::entry(), EntryNav::fileDef(), TagInfo::fileName, Entry::fileName, findScopeFromQualifiedName(), Definition::getLanguage(), Entry::hidden, Entry::id, FileDef::insertNamespace(), NamespaceDef::insertUsedFile(), SDict< T >::inSort(), Entry::lang, EntryNav::loadEntry(), Entry::name, EntryNav::name(), Entry::NAMESPACE_SEC, Entry::NAMESPACEDOC_SEC, Entry::PACKAGEDOC_SEC, Entry::Published, RECURSE_ENTRYTREE, EntryNav::releaseEntry(), Entry::section, EntryNav::section(), Definition::setArtificial(), Definition::setBodyDef(), Definition::setBodySegment(), Definition::setBriefDescription(), Definition::setDocumentation(), NamespaceDef::setFileName(), Definition::setHidden(), Definition::setId(), Definition::setLanguage(), Definition::setName(), Definition::setOuterScope(), Definition::setReference(), Definition::setRefItems(), Entry::sli, Entry::spec, SrcLangExt_Unknown, Entry::startColumn, Entry::startLine, stripAnonymousNamespaceScope(), substitute(), EntryNav::tagInfo(), TagInfo::tagName, and Entry::type.
Referenced by parseInput().
buildPageList()
static void buildPageList (EntryNav * rootNav) static
Definition at line 8660 of file doxygen.cpp.
References addRefItem(), addRelatedPage(), Entry::args, EntryNav::entry(), EntryNav::loadEntry(), Entry::MAINPAGEDOC_SEC, Entry::name, Entry::PAGEDOC_SEC, RECURSE_ENTRYTREE, EntryNav::releaseEntry(), EntryNav::section(), Entry::sli, theTranslator, and Translator::trMainPage().
Referenced by parseInput().
buildScopeFromQualifiedName()
static Definition* buildScopeFromQualifiedName (const QCString name, int level, SrcLangExt lang, TagInfo * tagInfo) static
returns the Definition object belonging to the first level levels of full qualified name name. Creates an artificial scope if the scope is not found and set the parent/child scope relation if the scope is found.
Definition at line 1002 of file doxygen.cpp.
References Definition::addInnerCompound(), TagInfo::fileName, SDict< T >::find(), getClass(), getScopeFragment(), Doxygen::globalScope, SDict< T >::inSort(), Definition::setLanguage(), Definition::setOuterScope(), and TagInfo::tagName.
Referenced by addClassToContext(), buildNamespaceList(), findScopeFromQualifiedName(), and resolveClassNestingRelations().
buildTypedefList()
static void buildTypedefList (EntryNav * rootNav) static
Definition at line 3028 of file doxygen.cpp.
References addVariable(), EntryNav::children(), Entry::ENUM_SEC, EntryNav::name(), EntryNav::section(), EntryNav::type(), and Entry::VARIABLE_SEC.
Referenced by parseInput().
buildVarList()
static void buildVarList (EntryNav * rootNav) static
Definition at line 3056 of file doxygen.cpp.
References addVariable(), EntryNav::children(), Entry::ENUM_SEC, findFunctionPtr(), Entry::FUNCTION_SEC, g_compoundKeywordDict(), isVarWithConstructor(), EntryNav::lang(), EntryNav::name(), EntryNav::section(), EntryNav::type(), and Entry::VARIABLE_SEC.
Referenced by parseInput().
checkConfiguration()
void checkConfiguration ()
check and resolve config options
Definition at line 10494 of file doxygen.cpp.
References Config::checkAndCorrect(), initWarningFormat(), and Config::postProcess().
Referenced by main().
checkPageRelations()
static void checkPageRelations () static
Definition at line 8807 of file doxygen.cpp.
References Definition::docFile(), Definition::docLine(), err(), Definition::getOuterScope(), SDict< PageDef >::Iterator, and Definition::name().
Referenced by parseInput().
cleanUpDoxygen()
void cleanUpDoxygen ()
Definition at line 10077 of file doxygen.cpp.
References Doxygen::classSDict, cleanUpPreprocessor(), codeFreeScanner(), DefinitionIntf::definitionType(), Doxygen::diaFileNameDict, Doxygen::directories, Doxygen::dotFileNameDict, Doxygen::exampleNameDict, Doxygen::exampleSDict, Doxygen::formulaDict, Doxygen::formulaList, Doxygen::formulaNameDict, Mappers::freeMappers(), Doxygen::functionNameSDict, g_outputList, Doxygen::genericsDict, Doxygen::globalScope, Doxygen::groupSDict, Doxygen::hiddenClasses, Doxygen::imageNameDict, Doxygen::includeNameDict, Doxygen::indexList, Doxygen::inputNameDict, Doxygen::inputNameList, Doxygen::mainPage, Doxygen::memberNameSDict, Doxygen::mscFileNameDict, Doxygen::namespaceSDict, Doxygen::pageSDict, Doxygen::parserManager, Doxygen::sectionDict, Doxygen::symbolMap, theTranslator, DefinitionIntf::TypeSymbolList, and Doxygen::xrefLists.
Referenced by createOutputDirectory(), generateOutput(), parseInput(), and readConfiguration().
clearAll()
void clearAll ()
Definition at line 186 of file doxygen.cpp.
References Doxygen::citeDict, SDict< T >::clear(), g_inputFiles, Doxygen::mainPage, and Doxygen::tagDestinationDict.
combineUsingRelations()
static void combineUsingRelations () static
Definition at line 8189 of file doxygen.cpp.
References NamespaceDef::combineUsingRelations(), FileDef::combineUsingRelations(), SDict< NamespaceDef >::Iterator, NamespaceDef::visited, and FileDef::visited.
Referenced by parseInput().
computeClassRelations()
static void computeClassRelations () static
Definition at line 5041 of file doxygen.cpp.
References Debug::Classes, Config_getBool, SDict< T >::count(), DocumentedOnly, EntryNav::entry(), extractClassName(), Entry::fileName, findBaseClassesForClass(), g_classEntries(), getClass(), guessSection(), ClassDef::hasDocumentation(), Entry::HEADER_SEC, ClassDef::isReference(), SDict< ClassDef >::Iterator, EntryNav::loadEntry(), ClassDef::memberNameInfoSDict(), Entry::name, Debug::print(), Entry::protection, protectionLevelVisible(), EntryNav::releaseEntry(), Entry::startLine, and warn_undoc().
Referenced by parseInput().
computeIdealCacheParam()
static int computeIdealCacheParam (uint v) static
Definition at line 10139 of file doxygen.cpp.
Referenced by generateOutput().
computeMemberReferences()
static void computeMemberReferences () static
Definition at line 5162 of file doxygen.cpp.
References NamespaceDef::computeAnchors(), GroupDef::computeAnchors(), FileDef::computeAnchors(), ClassDef::computeAnchors(), SDict< NamespaceDef >::Iterator, SDict< ClassDef >::Iterator, and SDict< GroupDef >::Iterator.
Referenced by parseInput().
computeMemberRelations()
static void computeMemberRelations () static
Definition at line 7672 of file doxygen.cpp.
References MemberDef::argumentList(), ClassDef::baseClasses(), ClassDef::compoundType(), MemberDef::getClassDef(), MemberDef::getFileDef(), Definition::getOuterScope(), MemberDef::insertReimplementedBy(), ClassDef::Interface, ClassDef::isBaseClass(), MemberDef::isFunction(), ClassDef::isLinkable(), SDict< MemberName >::Iterator, matchArguments2(), minClassDistance(), Normal, ClassDef::Protocol, MemberDef::reimplements(), MemberDef::setReimplements(), and MemberDef::virtualness().
Referenced by parseInput().
computePageRelations()
static void computePageRelations (EntryNav * rootNav) static
Definition at line 8772 of file doxygen.cpp.
References PageDef::addInnerCompound(), EntryNav::entry(), Entry::extends, SDict< T >::find(), EntryNav::loadEntry(), Doxygen::mainPage, Entry::MAINPAGEDOC_SEC, BaseInfo::name, Entry::name, EntryNav::name(), Entry::PAGEDOC_SEC, RECURSE_ENTRYTREE, EntryNav::releaseEntry(), Entry::section, and EntryNav::section().
Referenced by parseInput().
computeTemplateClassRelations()
static void computeTemplateClassRelations () static
Definition at line 5080 of file doxygen.cpp.
References Debug::Classes, DocumentedOnly, EntryNav::entry(), Entry::extends, findClassRelation(), g_classEntries(), getClass(), getTemplateArgumentsInName(), ClassDef::getTemplateBaseClassNames(), ClassDef::getTemplateInstances(), EntryNav::loadEntry(), BaseInfo::name, Definition::name(), Entry::name, Debug::print(), BaseInfo::prot, EntryNav::releaseEntry(), stringToArgumentList(), stripAnonymousNamespaceScope(), stripTemplateSpecifiersFromScope(), substituteTemplateArgumentsInString(), ClassDef::templateArguments(), Argument::type, Undocumented, and BaseInfo::virt.
Referenced by parseInput().
convertToCompoundType()
static ClassDef::CompoundType convertToCompoundType (int section, uint64 specifier) static
Definition at line 1180 of file doxygen.cpp.
References ClassDef::Category, Entry::Category, Entry::CATEGORYDOC_SEC, ClassDef::Class, ClassDef::Exception, Entry::Exception, Entry::EXCEPTIONDOC_SEC, ClassDef::Interface, Entry::Interface, Entry::INTERFACEDOC_SEC, ClassDef::Protocol, Entry::Protocol, Entry::PROTOCOLDOC_SEC, ClassDef::Service, Entry::Service, Entry::SERVICEDOC_SEC, ClassDef::Singleton, Entry::Singleton, Entry::SINGLETONDOC_SEC, ClassDef::Struct, Entry::Struct, Entry::STRUCTDOC_SEC, ClassDef::Union, Entry::Union, and Entry::UNIONDOC_SEC.
Referenced by addClassToContext().
copyExtraFiles()
static void copyExtraFiles (QStrList files, const QString & filesOption, const QCString & outputOption) static
Definition at line 9283 of file doxygen.cpp.
References IndexList::addImageFile(), copyFile(), and err().
Referenced by generateOutput().
copyLatexStyleSheet()
static void copyLatexStyleSheet () static
Definition at line 9195 of file doxygen.cpp.
References checkExtension(), Config_getList, Config_getString, copyFile(), err(), and latexStyleExtension.
Referenced by generateOutput().
copyLogo()
static void copyLogo (const QCString & outputOption) static
Definition at line 9263 of file doxygen.cpp.
References IndexList::addImageFile(), Config_getString, copyFile(), and err().
Referenced by generateOutput().
copyStyleSheet()
static void copyStyleSheet () static
Definition at line 9222 of file doxygen.cpp.
References Config_getList, Config_getString, copyFile(), and err().
Referenced by generateOutput().
createOutputDirectory()
static QCString createOutputDirectory (const QCString & baseDirName, QCString & formatDirName, const char * defaultDirName) static
Definition at line 10712 of file doxygen.cpp.
References cleanUpDoxygen(), and err().
Referenced by parseInput().
createTagLessInstance()
static ClassDef* createTagLessInstance (ClassDef * rootCd, ClassDef * templ, const QCString & fieldName) static
Definition at line 1530 of file doxygen.cpp.
References GroupDef::addClass(), Definition::addInnerCompound(), SDict< T >::append(), MemberDef::argsString(), MemberDef::bitfieldString(), Definition::briefDescription(), MemberDef::briefDescription(), Definition::briefFile(), Definition::briefLine(), ClassDef::compoundType(), Definition::docFile(), Definition::docLine(), Definition::documentation(), MemberDef::documentation(), MemberDef::excpString(), Definition::getBodyDef(), Definition::getDefColumn(), Definition::getDefFileName(), Definition::getDefLine(), Definition::getEndBodyLine(), ClassDef::getFileDef(), Definition::getLanguage(), MemberDef::getMemberGroupId(), ClassDef::getMemberList(), MemberDef::getMemberSpecifiers(), Definition::getOuterScope(), Definition::getStartBodyLine(), Doxygen::globalScope, Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), MemberDef::initializer(), MemberDef::initializerLines(), FileDef::insertClass(), ClassDef::insertMember(), MemberDef::isStatic(), Definition::makePartOfGroup(), Member, MemberListType_pubAttribs, MemberDef::memberType(), Definition::name(), Definition::partOfGroups(), MemberDef::protection(), removeAnonymousScopes(), MemberDef::setBitfields(), Definition::setBodyDef(), Definition::setBodySegment(), Definition::setBriefDescription(), MemberDef::setBriefDescription(), Definition::setDocumentation(), MemberDef::setDocumentation(), ClassDef::setFileDef(), MemberDef::setInbodyDocumentation(), MemberDef::setInitializer(), Definition::setLanguage(), MemberDef::setMaxInitLines(), MemberDef::setMemberClass(), MemberDef::setMemberGroupId(), MemberDef::setMemberSpecifiers(), Definition::setOuterScope(), MemberDef::typeString(), and MemberDef::virtualness().
Referenced by processTagLessClasses().
createTemplateInstanceMembers()
static void createTemplateInstanceMembers () static
Definition at line 7750 of file doxygen.cpp.
References ClassDef::addMembersToTemplateInstance(), ClassDef::getTemplateInstances(), and SDict< ClassDef >::Iterator.
Referenced by parseInput().
devUsage()
static void devUsage () static
Definition at line 9926 of file doxygen.cpp.
References msg(), and Debug::printFlags().
Referenced by readConfiguration().
distributeClassGroupRelations()
void distributeClassGroupRelations ()
Definition at line 1493 of file doxygen.cpp.
References GroupDef::addClass(), ClassDef::getClassSDict(), SDict< ClassDef >::Iterator, Definition::partOfGroups(), and ClassDef::visited.
distributeMemberGroupDocumentation()
static void distributeMemberGroupDocumentation () static
Definition at line 8267 of file doxygen.cpp.
References NamespaceDef::distributeMemberGroupDocumentation(), GroupDef::distributeMemberGroupDocumentation(), FileDef::distributeMemberGroupDocumentation(), ClassDef::distributeMemberGroupDocumentation(), SDict< NamespaceDef >::Iterator, SDict< ClassDef >::Iterator, and SDict< GroupDef >::Iterator.
Referenced by parseInput().
dumpSymbol()
static void dumpSymbol (FTextStream & t, Definition * d) static
Definition at line 9874 of file doxygen.cpp.
References MemberDef::anchor(), DefinitionIntf::definitionType(), endl(), Definition::getDefFileName(), Definition::getDefLine(), Definition::getOuterScope(), Definition::getOutputFileBase(), Doxygen::globalScope, Doxygen::htmlFileExtension, Definition::name(), and DefinitionIntf::TypeMember.
Referenced by dumpSymbolMap().
dumpSymbolMap()
static void dumpSymbolMap () static
Definition at line 9896 of file doxygen.cpp.
References DefinitionIntf::definitionType(), dumpSymbol(), Doxygen::symbolMap, and DefinitionIntf::TypeSymbolList.
Referenced by generateOutput().
escapeAliases()
static void escapeAliases () static
Definition at line 9800 of file doxygen.cpp.
References Doxygen::aliasDict.
Referenced by readAliases().
exitDoxygen()
static void exitDoxygen () static
Definition at line 10695 of file doxygen.cpp.
References Doxygen::entryDBFileName, g_successfulRun, msg(), and Doxygen::objDBFileName.
Referenced by parseInput().
expandAliases()
static void expandAliases () static
Definition at line 9788 of file doxygen.cpp.
References Doxygen::aliasDict, and expandAlias().
Referenced by readAliases().
extractClassName()
static QCString extractClassName (EntryNav * rootNav) static
Definition at line 4978 of file doxygen.cpp.
References EntryNav::lang(), EntryNav::name(), SrcLangExt_CSharp, SrcLangExt_Java, stripAnonymousNamespaceScope(), and stripTemplateSpecifiersFromScope().
Referenced by computeClassRelations(), findInheritedTemplateInstances(), and findUsedTemplateInstances().
filterMemberDocumentation()
static void filterMemberDocumentation (EntryNav * rootNav) static
Definition at line 6847 of file doxygen.cpp.
References Entry::args, Entry::DEFINE_SEC, Duplicate, EntryNav::entry(), Entry::exception, Entry::EXPORTED_INTERFACE_SEC, findFunctionPtr(), findMember(), Debug::FindMembers, Entry::FUNCTION_SEC, g_compoundKeywordDict(), Entry::INCLUDED_SERVICE_SEC, Entry::inside, Entry::lang, Entry::MEMBERDOC_SEC, Entry::mGrpId, Entry::name, Entry::OVERLOADDOC_SEC, Debug::print(), Entry::relates, Entry::relatesType, Entry::section, Entry::spec, Entry::type, Entry::VARIABLE_SEC, and Entry::VARIABLEDOC_SEC.
Referenced by findMemberDocumentation().
findBaseClassesForClass()
static void findBaseClassesForClass (EntryNav * rootNav, Definition * context, ClassDef * masterCd, ClassDef * instanceCd, FindBaseClassRelation_Mode mode, bool isArtificial, ArgumentList * actualArgs = 0, QDict< int > * templateNames = 0) static
Definition at line 4347 of file doxygen.cpp.
References Config_getBool, DocumentedOnly, EntryNav::entry(), Entry::extends, findClassRelation(), getTemplateArgumentsInName(), BaseInfo::name, BaseInfo::prot, substituteTemplateArgumentsInString(), ClassDef::templateArguments(), TemplateInstances, Undocumented, BaseInfo::virt, and ClassDef::visited.
Referenced by computeClassRelations(), findInheritedTemplateInstances(), and findTemplateInstanceRelation().
findClassDefinition()
static ClassDef* findClassDefinition (FileDef * fd, NamespaceDef * nd, const char * scopeName) static
Definition at line 5446 of file doxygen.cpp.
References getResolvedClass().
Referenced by findMember().
findClassEntries()
static void findClassEntries (EntryNav * rootNav) static
Builds a dictionary of all entry nodes in the tree starting with root
Definition at line 4969 of file doxygen.cpp.
References g_classEntries(), isClassSection(), EntryNav::name(), and RECURSE_ENTRYTREE.
Referenced by parseInput().
findClassRelation()
static bool findClassRelation (EntryNav * rootNav, Definition * context, ClassDef * cd, BaseInfo * bi, QDict< int > * templateNames, FindBaseClassRelation_Mode mode, bool isArtificial) static
Definition at line 4587 of file doxygen.cpp.
References SDict< T >::append(), ClassDef::Class, Debug::Classes, Config_getBool, DocumentedOnly, EntryNav::entry(), Entry::EXPORTED_INTERFACE_SEC, EntryNav::fileDef(), Entry::fileName, GenericsSDict::find(), SDict< T >::find(), findClassWithinClassContext(), findEndOfTemplate(), findScopeFromQualifiedName(), findTemplateInstanceRelation(), getClass(), ClassDef::getFileDef(), getResolvedClass(), Entry::INCLUDED_SERVICE_SEC, ClassDef::insertBaseClass(), ClassDef::insertSubClass(), ClassDef::insertUsedFile(), ClassDef::isCSharp(), isRecursiveBaseClass(), ClassDef::isSubClass(), Entry::lang, EntryNav::lang(), BaseInfo::name, Definition::name(), Entry::name, EntryNav::name(), Doxygen::namespaceAliasDict, Normal, EntryNav::parent(), Debug::print(), Private, BaseInfo::prot, Protected, ClassDef::Protocol, Public, removeRedundantWhiteSpace(), replaceNamespaceAliases(), EntryNav::section(), Definition::setArtificial(), ClassDef::setCompoundType(), Definition::setLanguage(), Definition::setOuterScope(), SrcLangExt_CSharp, SrcLangExt_IDL, SrcLangExt_Java, Entry::startColumn, Entry::startLine, EntryNav::tagInfo(), TemplateInstances, Undocumented, BaseInfo::virt, and warn().
Referenced by addInterfaceOrServiceToServiceOrSingleton(), computeTemplateClassRelations(), findBaseClassesForClass(), and findUsedClassesForClass().
findClassWithinClassContext()
static ClassDef* findClassWithinClassContext (Definition * context, ClassDef * cd, const QCString & name) static
Searches a class from within context and cd and returns its definition if found (otherwise 0 is returned).
Definition at line 4141 of file doxygen.cpp.
References GenericsSDict::find(), getClass(), ClassDef::getFileDef(), Definition::getLanguage(), getResolvedClass(), SrcLangExt_CSharp, and SrcLangExt_Java.
Referenced by findClassRelation(), and findUsedClassesForClass().
findDefineDocumentation()
static void findDefineDocumentation (EntryNav * rootNav) static
Definition at line 8449 of file doxygen.cpp.
References FileDef::absFilePath(), addMemberToGroups(), Definition::addSectionsToDefinition(), Entry::anchors, SDict< T >::append(), Entry::args, Entry::bodyLine, Entry::brief, MemberDef::briefDescription(), Entry::briefFile, Entry::briefLine, Config_getBool, Entry::DEFINE_SEC, Entry::DEFINEDOC_SEC, Entry::doc, Entry::docFile, Entry::docLine, MemberDef::documentation(), Entry::endBodyLine, EntryNav::entry(), EntryNav::fileDef(), Entry::fileName, SDict< T >::find(), MemberDef::getFileDef(), Entry::inbodyDocs, Definition::inbodyDocumentation(), Entry::inbodyFile, Entry::inbodyLine, Entry::initLines, Entry::lang, EntryNav::loadEntry(), Member, MemberDef::memberType(), MemberType_Define, Entry::mGrpId, Entry::name, EntryNav::name(), Normal, EntryNav::parent(), Entry::proto, Public, RECURSE_ENTRYTREE, EntryNav::releaseEntry(), EntryNav::section(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setFileDef(), MemberDef::setInbodyDocumentation(), Definition::setLanguage(), MemberDef::setMaxInitLines(), MemberDef::setMemberGroupId(), Definition::setRefItems(), MemberDef::setTagInfo(), Entry::sli, Entry::startLine, EntryNav::tagInfo(), TagInfo::tagName, and warn().
Referenced by parseInput().
findDEV()
static void findDEV (const MemberNameSDict & mnsd) static
Definition at line 7588 of file doxygen.cpp.
References MemberDef::enumFieldList(), MemberDef::isEnumerate(), MemberDef::isLinkableInProject(), SDict< MemberName >::Iterator, and MemberDef::setDocumentedEnumValues().
Referenced by findDocumentedEnumValues().
findDirDocumentation()
static void findDirDocumentation (EntryNav * rootNav) static
Definition at line 8593 of file doxygen.cpp.
References addDirToGroups(), Entry::brief, Entry::briefFile, Entry::briefLine, Entry::DIRDOC_SEC, Entry::doc, Entry::docFile, Entry::docLine, EntryNav::entry(), Entry::fileName, EntryNav::loadEntry(), Definition::name(), Entry::name, RECURSE_ENTRYTREE, EntryNav::releaseEntry(), EntryNav::section(), Definition::setBriefDescription(), Definition::setDocumentation(), Definition::setRefItems(), Entry::sli, Entry::startLine, substitute(), and warn().
Referenced by parseInput().
findDocumentedEnumValues()
static void findDocumentedEnumValues () static
Definition at line 7623 of file doxygen.cpp.
References findDEV().
Referenced by parseInput().
findEndOfTemplate()
static int findEndOfTemplate (const QCString & s, int startPos) static
Searches for the end of a template in prototype s starting from character position startPos. If the end was found the position of the closing > is returned, otherwise -1 is returned.
Handles exotic cases such as
Class<(id<0)>
Class<bits<<2>
Class<"<">
Class<'<'>
Class<(")<")>
Definition at line 4521 of file doxygen.cpp.
Referenced by findClassRelation().
findEnumDocumentation()
static void findEnumDocumentation (EntryNav * rootNav) static
Definition at line 7445 of file doxygen.cpp.
References addMemberToGroups(), Definition::addSectionsToDefinition(), Entry::anchors, Entry::brief, MemberDef::briefDescription(), Entry::briefFile, Entry::briefLine, Entry::doc, Entry::docFile, Entry::docLine, MemberDef::documentation(), EntryNav::entry(), Entry::ENUMDOC_SEC, Entry::fileName, SDict< T >::find(), getClass(), MemberDef::getClassDef(), MemberDef::getGroupDef(), MemberDef::getMemberGroupId(), Entry::groups, Entry::inbodyDocs, Definition::inbodyDocumentation(), Entry::inbodyFile, Entry::inbodyLine, MemberDef::isEnumerate(), EntryNav::loadEntry(), Entry::mGrpId, Definition::name(), Entry::name, EntryNav::name(), EntryNav::parent(), Entry::proto, RECURSE_ENTRYTREE, EntryNav::releaseEntry(), Entry::SCOPE_MASK, EntryNav::section(), MemberDef::setBriefDescription(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setInbodyDocumentation(), MemberDef::setMemberGroupId(), Definition::setRefItems(), Entry::sli, Entry::startLine, and warn().
Referenced by parseInput().
findEnums()
static void findEnums (EntryNav * rootNav) static
Definition at line 7035 of file doxygen.cpp.
References addMemberToGroups(), Definition::addSectionsToDefinition(), Entry::anchors, SDict< T >::append(), Entry::args, Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, Config_getBool, Entry::doc, Entry::docFile, Entry::docLine, MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), Entry::endBodyLine, EntryNav::entry(), Entry::ENUM_SEC, EntryNav::fileDef(), Entry::fileName, Foreign, Doxygen::functionNameSDict, getClass(), getResolvedNamespace(), Entry::id, Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, NamespaceDef::insertMember(), FileDef::insertMember(), ClassDef::insertMember(), ClassDef::insertUsedFile(), Entry::lang, EntryNav::loadEntry(), Member, Doxygen::memberNameSDict, MemberOf, MemberType_Enumeration, mergeScopes(), Entry::mGrpId, Definition::name(), Entry::name, EntryNav::name(), Normal, EntryNav::parent(), Entry::protection, Entry::proto, RECURSE_ENTRYTREE, Related, Entry::relates, Entry::relatesType, EntryNav::releaseEntry(), Entry::SCOPE_MASK, EntryNav::section(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDefinition(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setEnumBaseType(), MemberDef::setFileDef(), Definition::setId(), MemberDef::setInbodyDocumentation(), Definition::setLanguage(), MemberDef::setMemberClass(), MemberDef::setMemberGroupId(), MemberDef::setMemberSpecifiers(), MemberDef::setNamespace(), Definition::setRefItems(), MemberDef::setTagInfo(), Entry::sli, Entry::spec, Entry::startColumn, Entry::startLine, and EntryNav::tagInfo().
Referenced by parseInput().
findFriends()
static void findFriends () static
Definition at line 3845 of file doxygen.cpp.
References MemberDef::argumentList(), MemberDef::briefDescription(), Definition::briefFile(), Definition::briefLine(), Definition::docFile(), Definition::docLine(), MemberDef::documentation(), MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), Definition::getBodyDef(), Definition::getEndBodyLine(), MemberDef::getFileDef(), Definition::getOuterScope(), Definition::getStartBodyLine(), MemberDef::hasCallerGraph(), MemberDef::hasCallGraph(), Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), MemberDef::isDocsForDefinition(), MemberDef::isFriend(), MemberDef::isFunction(), MemberDef::isRelated(), SDict< MemberName >::Iterator, matchArguments2(), MemberName::memberName(), mergeArguments(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), and MemberDef::setInbodyDocumentation().
Referenced by parseInput().
findFunctionPtr()
static int findFunctionPtr (const QCString & type, int lang, int * pLength = 0) static
See if the return type string type is that of a function pointer
Returns
-1 if this is not a function pointer variable or the index at which the closing brace of (...*name) was found.
Definition at line 2662 of file doxygen.cpp.
References SrcLangExt_Fortran, and SrcLangExt_VHDL.
Referenced by addVariable(), buildVarList(), and filterMemberDocumentation().
findGlobalMember()
static bool findGlobalMember (EntryNav * rootNav, const QCString & namespaceName, const char * type, const char * name, const char * tempArg, const char * , const char * decl) static
Definition at line 5459 of file doxygen.cpp.
References addMemberDocs(), Entry::argList, argListToString(), MemberDef::argumentList(), Config_getBool, MemberDef::declaration(), Duplicate, EntryNav::entry(), EntryNav::fileDef(), Entry::fileName, SDict< T >::find(), Debug::FindMembers, Entry::FUNCTION_SEC, Definition::getDefFileName(), Definition::getDefLine(), MemberDef::getFileDef(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), FileDef::getUsedNamespaces(), Doxygen::globalScope, MemberDef::isStatic(), MemberDef::isTypedef(), MemberDef::isVariable(), matchArguments2(), Definition::name(), Debug::print(), Definition::qualifiedName(), Entry::relatesType, Entry::section, Entry::startLine, substitute(), Entry::tArgLists, MemberDef::templateArguments(), Entry::type, MemberDef::typeString(), and warn().
Referenced by findMember().
findGroupScope()
static void findGroupScope (EntryNav * rootNav) static
Definition at line 699 of file doxygen.cpp.
References findScopeFromQualifiedName(), Entry::GROUPDOC_SEC, Definition::name(), EntryNav::name(), Entry::PACKAGEDOC_SEC, EntryNav::parent(), RECURSE_ENTRYTREE, EntryNav::section(), GroupDef::setGroupScope(), stripAnonymousNamespaceScope(), substitute(), and EntryNav::tagInfo().
Referenced by parseInput().
findIncludedUsingDirectives()
static void findIncludedUsingDirectives () static
Definition at line 2212 of file doxygen.cpp.
References FileDef::addIncludedUsingDirectives(), and FileDef::visited.
Referenced by parseInput().
findInheritedTemplateInstances()
static void findInheritedTemplateInstances () static
Using the dictionary build by findClassEntries(), this function will look for additional template specialization that exists as inheritance relations only. These instances will be added to the template they are derived from.
Definition at line 4999 of file doxygen.cpp.
References Debug::Classes, extractClassName(), findBaseClassesForClass(), g_classEntries(), getClass(), SDict< ClassDef >::Iterator, EntryNav::loadEntry(), Debug::print(), EntryNav::releaseEntry(), and TemplateInstances.
Referenced by parseInput().
findMainPage()
static void findMainPage (EntryNav * rootNav) static
Definition at line 8697 of file doxygen.cpp.
References addPageToContext(), Definition::addSectionsToDefinition(), Entry::anchors, SDict< T >::append(), Entry::args, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::doc, Definition::docFile(), Entry::docFile, Definition::docLine(), Entry::docLine, EntryNav::entry(), SectionInfo::fileName, Entry::fileName, SDict< T >::find(), Entry::inbodyDocs, SectionInfo::lineNr, EntryNav::loadEntry(), Entry::MAINPAGEDOC_SEC, Definition::name(), SectionInfo::Page, RECURSE_ENTRYTREE, EntryNav::releaseEntry(), EntryNav::section(), Definition::setBriefDescription(), PageDef::setFileName(), PageDef::setShowToc(), Entry::startLine, Entry::stat, EntryNav::tagInfo(), PageDef::title(), and warn().
Referenced by parseInput().
findMainPageTagFiles()
static void findMainPageTagFiles (EntryNav * rootNav) static
Definition at line 8757 of file doxygen.cpp.
References Definition::addSectionsToDefinition(), Entry::anchors, EntryNav::entry(), EntryNav::loadEntry(), Entry::MAINPAGEDOC_SEC, RECURSE_ENTRYTREE, EntryNav::section(), and EntryNav::tagInfo().
Referenced by parseInput().
findMember()
static void findMember (EntryNav * rootNav, QCString funcDecl, bool overloaded, bool isFunc) static
This function tries to find a member (in a documented class/file/namespace) that corresponds to the function/variable declaration given in funcDecl.
The boolean overloaded is used to specify whether or not a standard overload documentation line should be generated.
The boolean isFunc is a hint that indicates that this is a function instead of a variable or typedef.
Definition at line 5777 of file doxygen.cpp.
References addMemberDocs(), addMemberToGroups(), addMethodToClass(), Definition::addSectionsToDefinition(), Entry::anchors, SDict< T >::append(), Entry::argList, argListToString(), MemberDef::argsString(), MemberDef::argumentList(), Entry::bodyLine, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::callerGraph, Entry::callGraph, Config_getBool, DCOP, doc, Entry::doc, Entry::docFile, Entry::docLine, Duplicate, MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), Entry::endBodyLine, EntryNav::entry(), Entry::Explicit, extractNamespaceName(), EntryNav::fileDef(), Entry::fileName, SDict< T >::find(), findClassDefinition(), findGlobalMember(), Debug::FindMembers, Foreign, Entry::FUNCTION_SEC, Definition::getBodyDef(), getClass(), MemberDef::getClassDef(), Definition::getEndBodyLine(), MemberDef::getFileDef(), Definition::getOuterScope(), getOverloadDocs(), getResolvedNamespace(), Definition::getStartBodyLine(), getTemplateArgumentsFromName(), ClassDef::getTemplateParameterLists(), FileDef::getUsedNamespaces(), Entry::id, Entry::inbodyDocs, Entry::inbodyFile, Entry::inbodyLine, MemberDef::initializer(), Entry::Inline, ClassDef::insertMember(), ClassDef::insertUsedFile(), MemberDef::isDefine(), isSpecialization(), SDict< NamespaceDef >::Iterator, Entry::lang, MemberDef::makeImplementationDetail(), matchArguments2(), Member, Entry::MEMBERDOC_SEC, MemberOf, MemberType_DCOP, MemberType_Define, MemberType_Function, MemberType_Signal, MemberType_Slot, mergeScopes(), Entry::mGrpId, Entry::mtype, Entry::Mutable, Definition::name(), Entry::name, EntryNav::name(), Entry::OBJCIMPL_SEC, EntryNav::parent(), parseFuncDecl(), Debug::print(), MemberDef::protection(), Entry::protection, Entry::proto, ClassDef::qualifiedNameWithTemplateParameters(), Related, Entry::relates, Entry::relatesType, removeRedundantWhiteSpace(), rightScopeMatch(), Entry::SCOPE_MASK, scopeIsTemplate(), Entry::section, EntryNav::section(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDefinition(), MemberDef::setDefinitionTemplateParameterLists(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setHidden(), Definition::setId(), MemberDef::setInbodyDocumentation(), MemberDef::setInitializer(), Definition::setLanguage(), MemberDef::setMemberClass(), MemberDef::setMemberGroupId(), MemberDef::setMemberSpecifiers(), MemberDef::setPrototype(), Definition::setRefItems(), MemberDef::setRelatedAlso(), MemberDef::setTagInfo(), MemberDef::setTemplateSpecialization(), MemberDef::setTypeConstraints(), Signal, Entry::sli, Slot, Entry::spec, SrcLangExt_ObjC, Entry::startColumn, Entry::startLine, Entry::stat, stripAnonymousNamespaceScope(), stripTemplateSpecifiersFromScope(), substitute(), substituteTemplatesInArgList(), EntryNav::tagInfo(), Entry::tArgLists, tempArgListToString(), Entry::typeConstr, Entry::virt, warn(), warn_simple(), and warn_undoc().
Referenced by filterMemberDocumentation(), and findObjCMethodDefinitions().
findMemberDocumentation()
static void findMemberDocumentation (EntryNav * rootNav) static
Definition at line 6969 of file doxygen.cpp.
References EntryNav::children(), Entry::DEFINE_SEC, Entry::ENUM_SEC, Entry::EXPORTED_INTERFACE_SEC, filterMemberDocumentation(), Entry::FUNCTION_SEC, Entry::INCLUDED_SERVICE_SEC, EntryNav::loadEntry(), Entry::MEMBERDOC_SEC, Entry::OVERLOADDOC_SEC, EntryNav::releaseEntry(), EntryNav::section(), Entry::VARIABLE_SEC, and Entry::VARIABLEDOC_SEC.
Referenced by parseInput().
findObjCMethodDefinitions()
static void findObjCMethodDefinitions (EntryNav * rootNav) static
Definition at line 7000 of file doxygen.cpp.
References Entry::args, EntryNav::children(), Entry::EMPTY_SEC, findMember(), Entry::FUNCTION_SEC, EntryNav::loadEntry(), Entry::name, Entry::OBJCIMPL_SEC, Entry::section, and Entry::type.
Referenced by parseInput().
findScopeFromQualifiedName()
static Definition * findScopeFromQualifiedName (Definition * startScope, const QCString & n, FileDef * fileScope, TagInfo * tagInfo) static
Definition at line 1061 of file doxygen.cpp.
References buildScopeFromQualifiedName(), Definition::findInnerCompound(), g_usingDeclarations(), Definition::getLanguage(), getScopeFragment(), FileDef::getUsedNamespaces(), Doxygen::globalScope, SDict< NamespaceDef >::Iterator, Definition::name(), rightScopeMatch(), and stripTemplateSpecifiersFromScope().
Referenced by addPageToContext(), buildNamespaceList(), findClassRelation(), findGroupScope(), and resolveClassNestingRelations().
findSectionsInDocumentation()
static void findSectionsInDocumentation () static
Definition at line 8306 of file doxygen.cpp.
References PageDef::findSectionsInDocumentation(), NamespaceDef::findSectionsInDocumentation(), GroupDef::findSectionsInDocumentation(), FileDef::findSectionsInDocumentation(), ClassDef::findSectionsInDocumentation(), SDict< ClassDef >::Iterator, SDict< NamespaceDef >::Iterator, SDict< GroupDef >::Iterator, and SDict< PageDef >::Iterator.
Referenced by parseInput().
findTagLessClasses() [1/2]
static void findTagLessClasses (ClassDef * cd) static
Definition at line 1676 of file doxygen.cpp.
References ClassDef::getClassSDict(), SDict< ClassDef >::Iterator, and processTagLessClasses().
Referenced by findTagLessClasses(), and parseInput().
findTagLessClasses() [2/2]
static void findTagLessClasses () static
Definition at line 1694 of file doxygen.cpp.
References DefinitionIntf::definitionType(), findTagLessClasses(), Definition::getOuterScope(), SDict< ClassDef >::Iterator, and DefinitionIntf::TypeClass.
findTemplateInstanceRelation()
static bool findTemplateInstanceRelation (Entry * root, Definition * context, ClassDef * templateClass, const QCString & templSpec, QDict< int > * templateNames, bool isArtificial) static
Definition at line 4411 of file doxygen.cpp.
References SDict< T >::append(), Debug::Classes, EntryNav::entry(), Entry::fileName, findBaseClassesForClass(), findUsedClassesForClass(), g_classEntries(), ClassDef::insertTemplateInstance(), Entry::lang, EntryNav::loadEntry(), Definition::name(), Entry::name, Debug::print(), EntryNav::releaseEntry(), Definition::setArtificial(), Definition::setLanguage(), ClassDef::setTemplateBaseClassNames(), Entry::startColumn, Entry::startLine, stringToArgumentList(), tempArgListToString(), ClassDef::templateArguments(), and TemplateInstances.
Referenced by findClassRelation().
findUsedClassesForClass()
static void findUsedClassesForClass (EntryNav * rootNav, Definition * context, ClassDef * masterCd, ClassDef * instanceCd, bool isArtificial, ArgumentList * actualArgs = 0, QDict< int > * templateNames = 0) static
Definition at line 4178 of file doxygen.cpp.
References ClassDef::addUsedByClass(), ClassDef::addUsedClass(), SDict< T >::append(), MemberDef::argsString(), ClassDef::Class, Debug::Classes, Config_getBool, extractClassNameFromType(), SDict< T >::find(), findClassRelation(), findClassWithinClassContext(), Definition::getDefColumn(), Definition::getDefFileName(), Definition::getDefLine(), ClassDef::getFileDef(), Definition::getLanguage(), getResolvedClass(), getTemplateArgumentsInName(), MemberDef::isObjCProperty(), MemberDef::isVariable(), SDict< MemberNameInfo >::Iterator, EntryNav::lang(), ClassDef::makeTemplateArgument(), MemberInfo::memberDef, ClassDef::memberNameInfoSDict(), Definition::name(), Normal, normalizeNonTemplateArgumentsInString(), Debug::print(), MemberDef::protection(), Public, removeRedundantWhiteSpace(), replaceNamespaceAliases(), resolveTypeDef(), Definition::setArtificial(), Definition::setLanguage(), ClassDef::setUsedOnly(), substituteTemplateArgumentsInString(), ClassDef::templateArguments(), TemplateInstances, MemberDef::typeString(), and ClassDef::visited.
Referenced by findTemplateInstanceRelation(), and findUsedTemplateInstances().
findUsedNamespace()
static NamespaceDef* findUsedNamespace (NamespaceSDict * unl, const QCString & name) static
Definition at line 1830 of file doxygen.cpp.
References getResolvedNamespace(), SDict< NamespaceDef >::Iterator, and Definition::name().
Referenced by findUsingDirectives().
findUsedTemplateInstances()
static void findUsedTemplateInstances () static
Definition at line 5020 of file doxygen.cpp.
References ClassDef::addTypeConstraints(), Debug::Classes, extractClassName(), findUsedClassesForClass(), g_classEntries(), getClass(), SDict< ClassDef >::Iterator, EntryNav::loadEntry(), Debug::print(), and EntryNav::releaseEntry().
Referenced by parseInput().
findUsingDeclarations()
static void findUsingDeclarations (EntryNav * rootNav) static
Definition at line 2019 of file doxygen.cpp.
References NamespaceDef::addUsingDeclaration(), FileDef::addUsingDeclaration(), SDict< T >::append(), ClassDef::Class, Debug::Classes, Entry::COMPOUND_MASK, EntryNav::entry(), EntryNav::fileDef(), SDict< T >::find(), getClass(), getResolvedClass(), getResolvedNamespace(), Entry::lang, EntryNav::loadEntry(), FileDef::name(), Definition::name(), Entry::name, EntryNav::name(), Entry::NAMESPACE_SEC, EntryNav::parent(), Debug::print(), RECURSE_ENTRYTREE, EntryNav::releaseEntry(), Entry::section, EntryNav::section(), substitute(), Entry::tArgLists, and Entry::USINGDECL_SEC.
Referenced by parseInput().
findUsingDeclImports()
static void findUsingDeclImports (EntryNav * rootNav) static
Definition at line 2109 of file doxygen.cpp.
References Definition::addSectionsToDefinition(), Entry::anchors, MemberDef::argsString(), MemberDef::bitfieldString(), Entry::brief, MemberDef::briefDescription(), Definition::briefFile(), Entry::briefFile, Definition::briefLine(), Entry::briefLine, Entry::callerGraph, Entry::callGraph, Entry::COMPOUND_MASK, MemberDef::definition(), Entry::doc, Definition::docFile(), Entry::docFile, Definition::docLine(), Entry::docLine, MemberDef::documentation(), MemberDef::enableCallerGraph(), MemberDef::enableCallGraph(), EntryNav::entry(), MemberDef::excpString(), Entry::fileName, SDict< T >::find(), Definition::getBodyDef(), getClass(), Definition::getEndBodyLine(), MemberDef::getMemberSpecifiers(), getResolvedClass(), Definition::getStartBodyLine(), Entry::id, Entry::inbodyDocs, Definition::inbodyDocumentation(), Definition::inbodyFile(), Entry::inbodyFile, Definition::inbodyLine(), Entry::inbodyLine, MemberDef::initializer(), MemberDef::initializerLines(), ClassDef::insertMember(), MemberDef::isStatic(), Entry::lang, EntryNav::loadEntry(), Member, MemberInfo::memberDef, ClassDef::memberNameInfoSDict(), MemberDef::memberType(), Entry::mGrpId, EntryNav::name(), EntryNav::parent(), Private, MemberDef::protection(), Entry::protection, RECURSE_ENTRYTREE, EntryNav::releaseEntry(), removeRedundantWhiteSpace(), EntryNav::section(), MemberDef::setBitfields(), Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDefinition(), MemberDef::setDocumentation(), Definition::setId(), MemberDef::setInbodyDocumentation(), MemberDef::setInitializer(), Definition::setLanguage(), MemberDef::setMaxInitLines(), MemberDef::setMemberClass(), MemberDef::setMemberGroupId(), MemberDef::setMemberSpecifiers(), Entry::startColumn, Entry::startLine, stripAnonymousNamespaceScope(), stripTemplateSpecifiersFromScope(), EntryNav::tagInfo(), TagInfo::tagName, MemberDef::templateArguments(), MemberDef::typeString(), Entry::USINGDECL_SEC, and Entry::virt.
Referenced by parseInput().
findUsingDirectives()
static void findUsingDirectives (EntryNav * rootNav) static
Definition at line 1849 of file doxygen.cpp.
References GroupDef::addNamespace(), Definition::addSectionsToDefinition(), NamespaceDef::addUsingDirective(), Entry::anchors, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::doc, Entry::docFile, Entry::docLine, EntryNav::entry(), EntryNav::fileDef(), Entry::fileName, SDict< T >::find(), findUsedNamespace(), Definition::getLanguage(), Definition::getOuterScope(), getResolvedNamespace(), NamespaceDef::getUsedNamespaces(), Grouping::groupname, Entry::groups, Entry::hidden, Entry::id, NamespaceDef::insertUsedFile(), SDict< T >::inSort(), Entry::lang, EntryNav::loadEntry(), Entry::name, EntryNav::name(), Entry::NAMESPACE_SEC, EntryNav::parent(), RECURSE_ENTRYTREE, EntryNav::releaseEntry(), EntryNav::section(), Definition::setArtificial(), Definition::setBriefDescription(), Definition::setDocumentation(), Definition::setHidden(), Definition::setId(), Definition::setLanguage(), Definition::setRefItems(), Entry::sli, SrcLangExt_Java, Entry::startColumn, Entry::startLine, stripAnonymousNamespaceScope(), substitute(), DefinitionIntf::TypeNamespace, and Entry::USINGDIR_SEC.
Referenced by parseInput().
flushCachedTemplateRelations()
static void flushCachedTemplateRelations () static
Definition at line 8351 of file doxygen.cpp.
References LookupInfo::classDef, MemberDef::getCachedTypedefVal(), MemberDef::invalidateTypedefValCache(), ClassDef::isTemplate(), MemberDef::isTypedefValCached(), SDict< MemberName >::Iterator, and Doxygen::lookupCache.
Referenced by parseInput().
flushUnresolvedRelations()
static void flushUnresolvedRelations () static
Definition at line 8401 of file doxygen.cpp.
References LookupInfo::classDef, MemberDef::invalidateCachedArgumentTypes(), SDict< MemberName >::Iterator, Doxygen::lookupCache, and LookupInfo::typeDef.
Referenced by parseInput().
g_classEntries()
static QDict<EntryNav> g_classEntries (1009) static
Referenced by computeClassRelations(), computeTemplateClassRelations(), findClassEntries(), findInheritedTemplateInstances(), findTemplateInstanceRelation(), findUsedTemplateInstances(), and parseInput().
g_compoundKeywordDict()
static QDict<void> g_compoundKeywordDict (7) static
Referenced by buildVarList(), filterMemberDocumentation(), initDoxygen(), and statistics().
g_pathsVisited()
static QDict<void> g_pathsVisited (1009) static
Referenced by readDir().
g_usingDeclarations()
static QDict<FileDef> g_usingDeclarations (1009) static
Referenced by buildListOfUsingDecls(), findScopeFromQualifiedName(), and parseInput().
generateClassDocs()
static void generateClassDocs () static
Definition at line 8143 of file doxygen.cpp.
References generateClassList().
Referenced by generateOutput().
generateClassList()
static void generateClassList (ClassSDict & classSDict) static
Definition at line 8114 of file doxygen.cpp.
References Definition::getOuterScope(), ClassDef::isEmbeddedInOuterScope(), Definition::isHidden(), ClassDef::isLinkableInProject(), SDict< ClassDef >::Iterator, msg(), Definition::name(), ClassDef::templateMaster(), ClassDef::writeDocumentation(), ClassDef::writeDocumentationForInnerClasses(), and ClassDef::writeMemberList().
Referenced by generateClassDocs().
generateConfigFile()
static void generateConfigFile (const char * configFile, bool shortList, bool updateOnly = FALSE) static
Generate a template version of the configuration file. If the shortList parameter is TRUE a configuration file without comments will be generated.
Definition at line 9111 of file doxygen.cpp.
References err(), msg(), openOutputFile(), and Config::writeTemplate().
Referenced by readConfiguration().
generateExampleDocs()
static void generateExampleDocs () static
Definition at line 8980 of file doxygen.cpp.
References OutputList::disable(), Definition::docFile(), OutputList::docify(), Definition::docLine(), Definition::documentation(), OutputList::enable(), endFile(), endTitle(), OutputList::generateDoc(), PageDef::getOutputFileBase(), SDict< PageDef >::Iterator, OutputGenerator::Man, msg(), Definition::name(), resetCCodeParserState(), OutputList::startContents(), startFile(), and startTitle().
Referenced by generateOutput().
generateFileDocs()
static void generateFileDocs () static
Definition at line 7964 of file doxygen.cpp.
References doc, FileDef::docName(), documentedHtmlFiles, FileDef::isLinkableInProject(), msg(), and FileDef::writeDocumentation().
Referenced by generateOutput().
generateFileSources()
static void generateFileSources () static
Definition at line 7822 of file doxygen.cpp.
References FileDef::absFilePath(), Config_getBool, FileDef::docName(), findFileDef(), FileDef::finishParsing(), g_useOutputTemplate, FileDef::generateSourceFile(), FileDef::getAllIncludeFilesRecursively(), Definition::isReference(), FileDef::isSource(), msg(), FileDef::parseSource(), Doxygen::parseSourcesNeeded, FileDef::startParsing(), and FileDef::writeSource().
Referenced by generateOutput().
generateGroupDocs()
static void generateGroupDocs () static
Definition at line 9012 of file doxygen.cpp.
References Definition::isReference(), SDict< GroupDef >::Iterator, and GroupDef::writeDocumentation().
Referenced by generateOutput().
generateNamespaceDocs()
static void generateNamespaceDocs () static
Definition at line 9045 of file doxygen.cpp.
References NamespaceDef::getClassSDict(), NamespaceDef::isLinkableInProject(), SDict< NamespaceDef >::Iterator, SDict< ClassDef >::Iterator, msg(), Definition::name(), and NamespaceDef::writeDocumentation().
Referenced by generateOutput().
generateOutput()
void generateOutput ()
add extra languages for which we can only produce syntax highlighted code
Definition at line 11390 of file doxygen.cpp.
References OutputList::add(), addCodeOnlyMappings(), IndexList::addIndex(), Statistics::begin(), Doxygen::clangUsrMap, cleanUpDoxygen(), Store::close(), computeIdealCacheParam(), Config_getBool, Config_getInt, Config_getList, Config_getString, copyExtraFiles(), copyLatexStyleSheet(), copyLogo(), copyStyleSheet(), OutputList::count(), createJavascriptSearchIndex(), Config::deinit(), dumpSymbolMap(), Statistics::end(), err(), Htags::execute(), Debug::ExtCmd, IndexList::finalize(), finializeSearchIndexer(), g_dumpSymbolMap, g_s, g_successfulRun, g_useOutputTemplate, FormulaList::generateBitmaps(), generateClassDocs(), generateDEF(), generateDirDocs(), generateDocbook(), generateExampleDocs(), generateFileDocs(), generateFileSources(), generateGroupDocs(), generateNamespaceDocs(), generateOutputViaTemplate(), generatePageDocs(), generatePerlMod(), generateSqlite3(), FTVHelp::generateTreeViewImages(), generateXML(), Doxygen::generatingXmlOutput, getQchFileName(), Qhp::getQhpFileName(), RTFGenerator::init(), ManGenerator::init(), LatexGenerator::init(), HtmlGenerator::init(), IndexList::initialize(), initSearchIndexer(), DotManager::instance(), SearchIndexIntf::Internal, Debug::isFlagSet(), SDict< GroupDef >::Iterator, Htags::loadFilemap(), Doxygen::lookupCache, msg(), Doxygen::objDBFileName, portable_getSysElapsedTime(), portable_isAbsolutePath(), portable_system(), portable_sysTimerStart(), portable_sysTimerStop(), RTFGenerator::preProcessFileInplace(), Statistics::print(), removeDoxFont(), DotManager::run(), Doxygen::runningTime, SDict< T >::sort(), GroupDef::sortSubGroups(), Doxygen::symbolMap, Doxygen::symbolStorage, Debug::Time, Htags::useHtags, SearchIndexIntf::write(), writeDoxFont(), HtmlGenerator::writeExternalSearchPage(), writeGraphInfo(), writeIndexHierarchy(), writeJavascriptSearchIndex(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), OutputList::writeStyleInfo(), HtmlGenerator::writeTabData(), and writeTagFile().
Referenced by main().
generatePageDocs()
static void generatePageDocs () static
Definition at line 8902 of file doxygen.cpp.
References documentedPages, PageDef::getGroupDef(), Doxygen::insideMainPage, Definition::isReference(), SDict< PageDef >::Iterator, msg(), Definition::name(), and PageDef::writeDocumentation().
Referenced by generateOutput().
generateXRefPages()
static void generateXRefPages () static
Definition at line 5291 of file doxygen.cpp.
References RefList::generatePage(), and Doxygen::xrefLists.
Referenced by parseInput().
getArg()
static const char* getArg (int argc, char ** argv, int & optind) static
Definition at line 9971 of file doxygen.cpp.
Referenced by readConfiguration().
getParserForFile()
static ParserInterface* getParserForFile (const char * fn) static
Definition at line 9309 of file doxygen.cpp.
References ParserManager::getParser().
Referenced by parseFiles().
getQchFileName()
static QCString getQchFileName () static
Definition at line 10735 of file doxygen.cpp.
References Config_getString.
Referenced by generateOutput().
getTemplateArgumentsFromName()
ArgumentList* getTemplateArgumentsFromName (const QCString & name, const QList< ArgumentList > * tArgLists)
Definition at line 1150 of file doxygen.cpp.
References SDict< T >::find(), getClass(), and ClassDef::templateArguments().
Referenced by addClassToContext(), and findMember().
getTemplateArgumentsInName()
static QDict<int>* getTemplateArgumentsInName (ArgumentList * templateArguments, const QCString & name) static
make a dictionary of all template arguments of class cd that are part of the base class name. Example: A template class A with template arguments <R,S,T> that inherits from B<T,T,S> will have T and S in the dictionary.
Definition at line 4108 of file doxygen.cpp.
References Argument::name.
Referenced by computeTemplateClassRelations(), findBaseClassesForClass(), and findUsedClassesForClass().
inheritDocumentation()
static void inheritDocumentation () static
Definition at line 8151 of file doxygen.cpp.
References MemberDef::briefDescription(), Definition::briefFile(), Definition::briefLine(), MemberDef::copyArgumentNames(), Definition::docFile(), Definition::docLine(), MemberDef::documentation(), Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), MemberDef::isDocsForDefinition(), SDict< MemberName >::Iterator, MemberDef::reimplements(), MemberDef::setBriefDescription(), MemberDef::setDocsForDefinition(), MemberDef::setDocumentation(), MemberDef::setInbodyDocumentation(), and MemberDef::setInheritsDocsFrom().
Referenced by parseInput().
initDoxygen()
void initDoxygen ()
Definition at line 9983 of file doxygen.cpp.
References Doxygen::clangUsrMap, Doxygen::dirRelations, g_compoundKeywordDict(), initClassMemberIndices(), initDefaultExtensionMapping(), initFileMemberIndices(), initNamespaceMemberIndices(), initPreprocessor(), initResources(), Doxygen::memGrpInfoDict, portable_correct_path(), portable_getenv(), portable_setenv(), ParserManager::registerDefaultParser(), ParserManager::registerParser(), Doxygen::runningTime, SDict< T >::setAutoDelete(), Doxygen::symbolMap, and Doxygen::tagDestinationDict.
Referenced by main().
initResources()
void initResources ()
Referenced by initDoxygen().
isClassSection()
static bool isClassSection (EntryNav * rootNav) static
Definition at line 4944 of file doxygen.cpp.
References Entry::COMPOUND_MASK, Entry::COMPOUNDDOC_MASK, EntryNav::entry(), Entry::extends, EntryNav::loadEntry(), EntryNav::name(), EntryNav::releaseEntry(), and EntryNav::section().
Referenced by findClassEntries().
isRecursiveBaseClass()
static bool isRecursiveBaseClass (const QCString & scope, const QCString & name) static
Definition at line 4496 of file doxygen.cpp.
References rightScopeMatch().
Referenced by findClassRelation().
isSpecialization()
static bool isSpecialization (const QList< ArgumentList > & srcTempArgLists, const QList< ArgumentList > & dstTempArgLists) static
Definition at line 5610 of file doxygen.cpp.
Referenced by findMember(), ClassDef::qualifiedNameWithTemplateParameters(), and searchTemplateSpecs().
isVarWithConstructor()
static bool isVarWithConstructor (EntryNav * rootNav) static
Returns TRUE iff type is a class within scope context. Used to detect variable declarations that look like function prototypes.
Definition at line 2695 of file doxygen.cpp.
References Entry::argList, checkIfTypedef(), Entry::COMPOUND_MASK, Argument::defval, EntryNav::entry(), EntryNav::fileDef(), SDict< T >::find(), findAndRemoveWord(), getResolvedClass(), EntryNav::loadEntry(), Argument::name, FileDef::name(), EntryNav::name(), EntryNav::parent(), EntryNav::releaseEntry(), resolveTypeDef(), EntryNav::section(), Argument::type, and Entry::type.
Referenced by buildVarList().
mergeCategories()
static void mergeCategories () static
Definition at line 7774 of file doxygen.cpp.
References SDict< T >::find(), SDict< ClassDef >::Iterator, ClassDef::mergeCategory(), and Definition::name().
Referenced by parseInput().
organizeSubGroups()
static void organizeSubGroups (EntryNav * rootNav) static
Definition at line 755 of file doxygen.cpp.
References organizeSubGroupsFiltered().
Referenced by parseInput().
organizeSubGroupsFiltered()
static void organizeSubGroupsFiltered (EntryNav * rootNav, bool additional) static
Definition at line 724 of file doxygen.cpp.
References addGroupToGroups(), EntryNav::children(), EntryNav::entry(), Entry::GROUPDOC_NORMAL, Entry::GROUPDOC_SEC, Entry::groupDocType, EntryNav::loadEntry(), Entry::name, EntryNav::name(), EntryNav::releaseEntry(), and EntryNav::section().
Referenced by organizeSubGroups().
parseFile()
static void parseFile (ParserInterface * parser, Entry * root, EntryNav * rootNav, FileDef * fd, const char * fn, bool sameTu, QStrList & filesInSameTu) static
Definition at line 9327 of file doxygen.cpp.
References Config_getBool, convertCppComments(), Entry::createNavigationIndex(), FileDef::getAllIncludeFilesRecursively(), msg(), ParserInterface::needsPreprocessing(), ParserInterface::parseInput(), preprocessFile(), and readInputFile().
Referenced by parseFiles().
parseFiles()
static void parseFiles (Entry * root, EntryNav * rootNav) static
parse the list of input files
Definition at line 9391 of file doxygen.cpp.
References Config_getBool, findFileDef(), ParserInterface::finishTranslationUnit(), g_inputFiles, getParserForFile(), Definition::isReference(), FileDef::isSource(), parseFile(), and ParserInterface::startTranslationUnit().
Referenced by parseInput().
parseInput()
void parseInput ()
Definition at line 10889 of file doxygen.cpp.
References addEnumValuesToEnums(), addListReferences(), addMembersToIndex(), addMembersToMemberGroup(), addSourceReferences(), addSTLClasses(), Statistics::begin(), buildClassDocList(), buildClassList(), buildCompleteMemberLists(), buildDirectories(), buildExampleList(), buildFileList(), buildFunctionList(), buildGroupList(), buildInterfaceAndServiceList(), buildListOfUsingDecls(), buildNamespaceList(), buildPageList(), buildTypedefList(), buildVarList(), checkPageRelations(), cleanUpDoxygen(), FileStorage::close(), combineUsingRelations(), computeClassRelations(), computeDirDependencies(), computeMemberReferences(), computeMemberRelations(), computePageRelations(), computeTemplateClassRelations(), VhdlDocGen::computeVhdlComponentRelations(), Config_getBool, Config_getInt, Config_getList, Config_getString, countDataStructures(), Entry::createNavigationIndex(), createOutputDirectory(), createTemplateInstanceMembers(), distributeMemberGroupDocumentation(), Statistics::end(), Doxygen::entryDBFileName, err(), exitDoxygen(), findClassEntries(), findDefineDocumentation(), findDirDocumentation(), findDocumentedEnumValues(), findEnumDocumentation(), findEnums(), findFriends(), findGroupScope(), findIncludedUsingDirectives(), findInheritedTemplateInstances(), findMainPage(), findMainPageTagFiles(), findMemberDocumentation(), findObjCMethodDefinitions(), findSectionsInDocumentation(), findTagLessClasses(), findUsedTemplateInstances(), findUsingDeclarations(), findUsingDeclImports(), findUsingDirectives(), flushCachedTemplateRelations(), flushUnresolvedRelations(), g_classEntries(), g_s, g_storage, g_useOutputTemplate, g_usingDeclarations(), FileNameList::generateDiskNames(), generateDocbook(), CiteDict::generatePage(), generateXRefPages(), inheritDocumentation(), LayoutDocManager::init(), LayoutDocManager::instance(), Doxygen::lookupCache, mergeCategories(), msg(), Doxygen::objDBFileName, FileStorage::open(), organizeSubGroups(), LayoutDocManager::parse(), parseFiles(), portable_getenv(), portable_pathListSeparator(), portable_pid(), portable_setenv(), preFreeScanner(), pyscanFreeScanner(), readFormulaRepository(), readTagFile(), resolveClassNestingRelations(), resolveUserReferences(), scanFreeScanner(), searchInputFiles(), EntryNav::setEntry(), FileStorage::setName(), SDict< T >::sort(), sortMemberLists(), stopDoxygen(), transferFunctionDocumentation(), transferFunctionReferences(), transferRelatedFunctionDocumentation(), and warn_uncond().
Referenced by main().
printNavTree()
void printNavTree (EntryNav * rootNav, int indent)
Definition at line 8961 of file doxygen.cpp.
References EntryNav::children(), msg(), EntryNav::name(), and EntryNav::section().
processTagLessClasses()
static void processTagLessClasses (ClassDef * rootCd, ClassDef * cd, ClassDef * tagParentCd, const QCString & prefix, int count) static
Look through the members of class cd and its public members.
If there is a member m of a tag less struct/union, then we create a duplicate of the struct/union with the name of the member to identify it. So if cd has name S, then the tag less struct/union will get name S.m Since tag less structs can be nested we need to call this function recursively. Later on we need to patch the member types so we keep track of the hierarchy of classes we create.
Definition at line 1610 of file doxygen.cpp.
References ClassDef::addTaggedInnerClass(), createTagLessInstance(), ClassDef::getClassSDict(), ClassDef::getMemberList(), SDict< ClassDef >::Iterator, MemberListType_pubAttribs, Definition::name(), MemberDef::setAccessorType(), ClassDef::setTagLessReference(), substitute(), and MemberDef::typeString().
Referenced by findTagLessClasses().
readAliases()
void readAliases ()
Definition at line 9835 of file doxygen.cpp.
References Doxygen::aliasDict, Config_getList, escapeAliases(), and expandAliases().
Referenced by adjustConfiguration().
readConfiguration()
void readConfiguration (int argc, char ** argv)
Definition at line 10151 of file doxygen.cpp.
References Config::checkAndCorrect(), cleanUpDoxygen(), Config_getEnum, devUsage(), err(), g_dumpSymbolMap, g_useOutputTemplate, generateConfigFile(), generateTemplateFiles(), getArg(), Config::init(), msg(), openOutputFile(), Doxygen::outputToWizard, Config::parse(), Config::postProcess(), Debug::setFlag(), setPerlModDoxyfile(), setTranslator(), usage(), versionString, warn_uncond(), writeDefaultLayoutFile(), RTFGenerator::writeExtensionsFile(), LatexGenerator::writeFooterFile(), HtmlGenerator::writeFooterFile(), LatexGenerator::writeHeaderFile(), HtmlGenerator::writeHeaderFile(), RTFGenerator::writeStyleSheetFile(), LatexGenerator::writeStyleSheetFile(), and HtmlGenerator::writeStyleSheetFile().
Referenced by main().
readDir()
int readDir (QFileInfo * fi, FileNameList * fnList, FileNameDict * fnDict, StringDict * exclDict, QStrList * patList, QStrList * exclPatList, StringList * resultList, StringDict * resultDict, bool errorIfNotExist, bool recursive, QDict< void > * killDict, QDict< void > * paths)
Definition at line 9555 of file doxygen.cpp.
References Config_getBool, g_pathsVisited(), msg(), patternMatch(), resolveSymlink(), and warn_uncond().
Referenced by readFileOrDirectory().
readFileOrDirectory()
int readFileOrDirectory (const char * s, FileNameList * fnList, FileNameDict * fnDict, StringDict * exclDict, QStrList * patList, QStrList * exclPatList, StringList * resultList, StringDict * resultDict, bool recursive, bool errorIfNotExist, QDict< void > * killDict, QDict< void > * paths)
Definition at line 9663 of file doxygen.cpp.
References Config_getBool, readDir(), and warn_uncond().
Referenced by searchInputFiles().
readFormulaRepository()
void readFormulaRepository ()
Definition at line 9755 of file doxygen.cpp.
References Config_getString, msg(), and warn_uncond().
Referenced by parseInput().
readTagFile()
static void readTagFile (Entry * root, const char * tl) static
Definition at line 9159 of file doxygen.cpp.
References err(), msg(), parseTagFile(), and Doxygen::tagDestinationDict.
Referenced by parseInput().
resolveClassNestingRelations()
static void resolveClassNestingRelations () static
create the scope artificially
Definition at line 1429 of file doxygen.cpp.
References Definition::addInnerCompound(), buildScopeFromQualifiedName(), findScopeFromQualifiedName(), Definition::getDefFileName(), Definition::getDefLine(), ClassDef::getFileDef(), Definition::getLanguage(), SDict< ClassDef >::Iterator, Definition::name(), Definition::setOuterScope(), stripAnonymousNamespaceScope(), ClassDef::visited, and warn().
Referenced by parseInput().
resolveSymlink()
static QCString resolveSymlink (QCString path) static
Definition at line 9481 of file doxygen.cpp.
Referenced by readDir().
resolveUserReferences()
static void resolveUserReferences () static
Definition at line 8830 of file doxygen.cpp.
References SectionInfo::definition, DefinitionIntf::definitionType(), SectionInfo::fileName, SDict< T >::find(), SectionInfo::generated, PageDef::getGroupDef(), GroupDef::getOutputFileBase(), SectionInfo::label, RefList::listName(), DefinitionIntf::TypeMember, and Doxygen::xrefLists.
Referenced by parseInput().
scopeIsTemplate()
static bool scopeIsTemplate (Definition * d) static
Definition at line 5626 of file doxygen.cpp.
References DefinitionIntf::definitionType(), Definition::getOuterScope(), and DefinitionIntf::TypeClass.
Referenced by findMember().
searchInputFiles()
void searchInputFiles ()
Definition at line 10752 of file doxygen.cpp.
References Statistics::begin(), Config_getBool, Config_getList, Statistics::end(), g_inputFiles, g_s, Doxygen::inputPaths, and readFileOrDirectory().
Referenced by parseInput().
sortMemberLists()
static void sortMemberLists () static
Definition at line 8071 of file doxygen.cpp.
References SDict< ClassDef >::Iterator, SDict< NamespaceDef >::Iterator, SDict< GroupDef >::Iterator, NamespaceDef::sortMemberLists(), GroupDef::sortMemberLists(), FileDef::sortMemberLists(), and ClassDef::sortMemberLists().
Referenced by parseInput().
statistics()
void statistics ()
Definition at line 258 of file doxygen.cpp.
References Doxygen::aliasDict, Doxygen::expandAsDefinedDict, g_compoundKeywordDict(), Doxygen::memGrpInfoDict, Doxygen::namespaceAliasDict, and Doxygen::tagDestinationDict.
stopDoxygen()
static void stopDoxygen (int) static
Definition at line 10597 of file doxygen.cpp.
References Doxygen::entryDBFileName, msg(), and Doxygen::objDBFileName.
Referenced by parseInput().
substituteTemplatesInArgList()
static void substituteTemplatesInArgList (const QList< ArgumentList > & srcTempArgLists, const QList< ArgumentList > & dstTempArgLists, ArgumentList * src, ArgumentList * dst, ArgumentList * funcTempArgs = 0) static
Definition at line 5718 of file doxygen.cpp.
References Argument::array, ArgumentList::constSpecifier, ArgumentList::pureSpecifier, substituteTemplatesInString(), ArgumentList::trailingReturnType, Argument::type, and ArgumentList::volatileSpecifier.
Referenced by findMember().
substituteTemplatesInString()
static QCString substituteTemplatesInString (const QList< ArgumentList > & srcTempArgLists, const QList< ArgumentList > & dstTempArgLists, ArgumentList * funcTempArgList, const QCString & src) static
Definition at line 5636 of file doxygen.cpp.
References Argument::name.
Referenced by substituteTemplatesInArgList().
transferFunctionDocumentation()
static void transferFunctionDocumentation () static
Definition at line 3932 of file doxygen.cpp.
References combineDeclarationAndDefinition(), and SDict< MemberName >::Iterator.
Referenced by parseInput().
transferFunctionReferences()
static void transferFunctionReferences () static
Definition at line 3963 of file doxygen.cpp.
References Definition::addSourceReferencedBy(), Definition::addSourceReferences(), MemberDef::argumentList(), SDict< T >::find(), MemberDef::getFileDef(), Definition::getOuterScope(), Definition::getReferencedByMembers(), Definition::getReferencesMembers(), MemberDef::isExternal(), MemberDef::isFunction(), MemberDef::isPrototype(), MemberDef::isStatic(), MemberDef::isVariable(), SDict< MemberName >::Iterator, SDict< MemberDef >::IteratorDict, matchArguments2(), and Definition::name().
Referenced by parseInput().
transferRelatedFunctionDocumentation()
static void transferRelatedFunctionDocumentation () static
Definition at line 4055 of file doxygen.cpp.
References MemberDef::argumentList(), MemberDef::getFileDef(), Definition::getOuterScope(), MemberDef::isForeign(), MemberDef::isRelated(), SDict< MemberName >::Iterator, MemberDef::makeForeign(), MemberDef::makeRelated(), matchArguments2(), Definition::name(), MemberDef::relatedAlso(), and MemberDef::setRelatedAlso().
Referenced by parseInput().
usage()
static void usage (const char * name) static
Definition at line 9940 of file doxygen.cpp.
References msg(), and versionString.
Referenced by readConfiguration().
writeTagFile()
static void writeTagFile () static
Definition at line 10614 of file doxygen.cpp.
References Config_getString, endl(), err(), PageDef::isLinkableInProject(), GroupDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), FileDef::isLinkableInProject(), ClassDef::isLinkableInProject(), SDict< ClassDef >::Iterator, SDict< NamespaceDef >::Iterator, SDict< PageDef >::Iterator, SDict< GroupDef >::Iterator, NamespaceDef::writeTagFile(), PageDef::writeTagFile(), GroupDef::writeTagFile(), FileDef::writeTagFile(), and ClassDef::writeTagFile().
Referenced by generateOutput().
Variable Documentation
g_dumpSymbolMap
bool g_dumpSymbolMap = FALSE static
Definition at line 183 of file doxygen.cpp.
Referenced by generateOutput(), and readConfiguration().
g_inputFiles
StringList g_inputFiles static
Definition at line 177 of file doxygen.cpp.
Referenced by clearAll(), parseFiles(), and searchInputFiles().
g_outputList
OutputList* g_outputList = 0 static
Definition at line 179 of file doxygen.cpp.
Referenced by cleanUpDoxygen().
g_s
class Statistics g_s
Referenced by generateOutput(), parseInput(), and searchInputFiles().
g_stlinfo
STLInfo g_stlinfo[] static
Definition at line 337 of file doxygen.cpp.
Referenced by addSTLClasses().
g_storage
FileStorage* g_storage = 0 static
Definition at line 181 of file doxygen.cpp.
Referenced by parseInput().
g_successfulRun
bool g_successfulRun = FALSE static
Definition at line 182 of file doxygen.cpp.
Referenced by exitDoxygen(), and generateOutput().
g_useOutputTemplate
bool g_useOutputTemplate = FALSE static
Definition at line 184 of file doxygen.cpp.
Referenced by generateFileSources(), generateOutput(), parseInput(), and readConfiguration().