Doxygen: FileName Class Reference
FileName Class Reference
Class representing all files with a certain base name.
#include <filename.h>
Public Member Functions
FileName (const char *fn, const char *name)
~FileName ()
const char * fileName () const
const char * fullName () const
void generateDiskNames ()
Public Member Functions inherited from FileList
FileList ()
FileList (const char *path)
~FileList ()
QCString path () const
Private Member Functions
int compareValues (const FileDef *item1, const FileDef *item2) const
Private Attributes
QCString name
QCString fName
Detailed Description
Class representing all files with a certain base name.
Definition at line 26 of file filename.h.
Constructor & Destructor Documentation
FileName()
FileName::FileName (const char * fn, const char * name)
Definition at line 22 of file filename.cpp.
References fName, and name.
~FileName()
FileName::~FileName ()
Definition at line 29 of file filename.cpp.
Member Function Documentation
compareValues()
int FileName::compareValues (const FileDef * item1, const FileDef * item2) const private
Definition at line 105 of file filename.cpp.
References FileDef::fileName().
fileName()
const char* FileName::fileName () const inline
Definition at line 31 of file filename.h.
References name.
Referenced by FileNameList::compareValues().
fullName()
const char* FileName::fullName () const inline
Definition at line 32 of file filename.h.
References fName.
Referenced by FileNameList::compareValues().
generateDiskNames()
void FileName::generateDiskNames ()
Definition at line 34 of file filename.cpp.
References FileDef::getPath(), Definition::isReference(), name, FileList::path(), FileDef::setDiskName(), and Definition::setName().
Referenced by FileNameList::generateDiskNames().
Member Data Documentation
fName
QCString FileName::fName private
Definition at line 38 of file filename.h.
Referenced by FileName(), and fullName().
name
QCString FileName::name private
Definition at line 37 of file filename.h.
Referenced by FileName(), fileName(), and generateDiskNames().
The documentation for this class was generated from the following files:
src/filename.h
src/filename.cpp