Doxygen: TranslatorDanish Class Reference
TranslatorDanish Class Reference
#include <translator_dk.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const char *s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trPageDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const char *date, const char *projName)
virtual QCString trClassDiagram (const char *clName)
virtual QCString trForInternalUseOnly ()
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const char *clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const char *fileName)
virtual QCString trNamespaceReference (const char *namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const char *clName)
virtual QCString trInclDepGraph (const char *fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const char *name)
virtual QCString trPackageList ()
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageMembers ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirDescription ()
virtual QCString trDirReference (const char *dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const char *clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const char *namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const char *name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const char *name)
virtual QCString trIncludesFileIn (const char *name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
Compiles a date string.
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const char *name)
Public Member Functions inherited from TranslatorAdapter_1_8_0
virtual QCString updateNeededMessage ()
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const char *name)
virtual QCString trInheritedFrom (const char *members, const char *what)
virtual QCString trAdditionalInheritedMembers ()
Public Member Functions inherited from TranslatorAdapter_1_8_2
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trDesignOverview ()
Public Member Functions inherited from TranslatorAdapter_1_8_4
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const char *namespaceName)
virtual QCString trServiceReference (const char *sName)
virtual QCString trSingletonReference (const char *sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Public Member Functions inherited from Translator
virtual ~Translator ()
Protected Member Functions
QCString createNoun (bool first_capital, bool singular, const char *base, const char *plurSuffix)
Protected Member Functions inherited from TranslatorAdapterBase
virtual ~TranslatorAdapterBase ()
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Additional Inherited Members
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 90 of file translator_dk.h.
Member Function Documentation
createNoun()
QCString TranslatorDanish::createNoun (bool first_capital, bool singular, const char * base, const char * plurSuffix) inline protected
For easy flexible-noun implementation.
Definition at line 1775 of file translator_dk.h.
Referenced by trAuthor(), trClass(), trDir(), trFile(), trGlobal(), trGroup(), trMember(), trNamespace(), and trPage().
idLanguage()
virtual QCString TranslatorDanish::idLanguage () inline virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 102 of file translator_dk.h.
latexLanguageSupportCommand()
virtual QCString TranslatorDanish::latexLanguageSupportCommand () inline virtual
Used to get the LaTeX command(s) for the language support. This method should return string with commands that switch LaTeX to the desired language. For example
"\\usepackage[german]{babel}\n"
or
"\\usepackage{polski}\n"
"\\usepackage[latin2]{inputenc}\n"
"\\usepackage[T1]{fontenc}\n"
Implements Translator.
Definition at line 116 of file translator_dk.h.
trAll()
virtual QCString TranslatorDanish::trAll () inline virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1317 of file translator_dk.h.
trAttention()
virtual QCString TranslatorDanish::trAttention () inline virtual
Implements Translator.
Definition at line 935 of file translator_dk.h.
trAuthor()
virtual QCString TranslatorDanish::trAuthor (bool first_capital, bool singular) inline virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1217 of file translator_dk.h.
References createNoun().
trBug()
virtual QCString TranslatorDanish::trBug () inline virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1109 of file translator_dk.h.
trBugList()
virtual QCString TranslatorDanish::trBugList () inline virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1114 of file translator_dk.h.
trCallerGraph()
virtual QCString TranslatorDanish::trCallerGraph () inline virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1446 of file translator_dk.h.
trCallGraph()
virtual QCString TranslatorDanish::trCallGraph () inline virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1323 of file translator_dk.h.
trCiteReferences()
virtual QCString TranslatorDanish::trCiteReferences () inline virtual
Implements Translator.
Definition at line 1754 of file translator_dk.h.
trClass()
virtual QCString TranslatorDanish::trClass (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1152 of file translator_dk.h.
References createNoun().
trClassDiagram()
virtual QCString TranslatorDanish::trClassDiagram (const char * clName) inline virtual
this text is put before a class diagram
Implements Translator.
Definition at line 520 of file translator_dk.h.
trClassDocumentation()
virtual QCString TranslatorDanish::trClassDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 393 of file translator_dk.h.
References Config_getBool.
trClasses()
virtual QCString TranslatorDanish::trClasses () inline virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1068 of file translator_dk.h.
References Config_getBool.
trClassHierarchy()
virtual QCString TranslatorDanish::trClassHierarchy () inline virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 212 of file translator_dk.h.
trClassHierarchyDescription()
virtual QCString TranslatorDanish::trClassHierarchyDescription () inline virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 263 of file translator_dk.h.
trCode()
virtual QCString TranslatorDanish::trCode () inline virtual
Text used the source code in the file index
Implements Translator.
Definition at line 864 of file translator_dk.h.
trCollaborationDiagram()
virtual QCString TranslatorDanish::trCollaborationDiagram (const char * clName) inline virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 826 of file translator_dk.h.
trCompoundIndex()
virtual QCString TranslatorDanish::trCompoundIndex () inline virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 369 of file translator_dk.h.
References Config_getBool.
trCompoundIndexFortran()
virtual QCString TranslatorDanish::trCompoundIndexFortran () inline virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1507 of file translator_dk.h.
trCompoundList()
virtual QCString TranslatorDanish::trCompoundList () inline virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 216 of file translator_dk.h.
References Config_getBool.
trCompoundListDescription()
virtual QCString TranslatorDanish::trCompoundListDescription () inline virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 278 of file translator_dk.h.
References Config_getBool.
trCompoundListDescriptionFortran()
virtual QCString TranslatorDanish::trCompoundListDescriptionFortran () inline virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1480 of file translator_dk.h.
trCompoundListFortran()
virtual QCString TranslatorDanish::trCompoundListFortran () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1472 of file translator_dk.h.
trCompoundMembers()
virtual QCString TranslatorDanish::trCompoundMembers () inline virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 230 of file translator_dk.h.
References Config_getBool.
trCompoundMembersDescription()
virtual QCString TranslatorDanish::trCompoundMembersDescription (bool extractAll) inline virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 290 of file translator_dk.h.
References Config_getBool.
trCompoundMembersDescriptionFortran()
virtual QCString TranslatorDanish::trCompoundMembersDescriptionFortran (bool extractAll) inline virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1484 of file translator_dk.h.
trCompoundMembersFortran()
virtual QCString TranslatorDanish::trCompoundMembersFortran () inline virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1476 of file translator_dk.h.
trCompoundReference()
virtual QCString TranslatorDanish::trCompoundReference (const char * clName, ClassDef::CompoundType compType, bool isTemplate) inline virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 599 of file translator_dk.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
virtual QCString TranslatorDanish::trCompoundReferenceFortran (const char * clName, ClassDef::CompoundType compType, bool isTemplate) inline virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1548 of file translator_dk.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
virtual QCString TranslatorDanish::trCompounds () inline virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 499 of file translator_dk.h.
References Config_getBool.
trConstructorDocumentation()
virtual QCString TranslatorDanish::trConstructorDocumentation () inline virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 836 of file translator_dk.h.
trCopyright()
virtual QCString TranslatorDanish::trCopyright () inline virtual
Implements Translator.
Definition at line 1759 of file translator_dk.h.
trDataTypes()
virtual QCString TranslatorDanish::trDataTypes () inline virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1531 of file translator_dk.h.
trDate()
virtual QCString TranslatorDanish::trDate () inline virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 538 of file translator_dk.h.
trDateTime()
virtual QCString TranslatorDanish::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) inline virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1733 of file translator_dk.h.
trDefinedAtLineInSourceFile()
virtual QCString TranslatorDanish::trDefinedAtLineInSourceFile () inline virtual
Implements Translator.
Definition at line 801 of file translator_dk.h.
trDefinedIn()
virtual QCString TranslatorDanish::trDefinedIn () inline virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 200 of file translator_dk.h.
trDefinedInSourceFile()
virtual QCString TranslatorDanish::trDefinedInSourceFile () inline virtual
Implements Translator.
Definition at line 806 of file translator_dk.h.
trDefineDocumentation()
virtual QCString TranslatorDanish::trDefineDocumentation () inline virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 463 of file translator_dk.h.
trDefines()
virtual QCString TranslatorDanish::trDefines () inline virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 427 of file translator_dk.h.
trDefineValue()
virtual QCString TranslatorDanish::trDefineValue () inline virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1099 of file translator_dk.h.
trDeprecated()
virtual QCString TranslatorDanish::trDeprecated () inline virtual
Implements Translator.
Definition at line 815 of file translator_dk.h.
trDeprecatedList()
virtual QCString TranslatorDanish::trDeprecatedList () inline virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1272 of file translator_dk.h.
trDetailedDescription()
virtual QCString TranslatorDanish::trDetailedDescription () inline virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 135 of file translator_dk.h.
trDir()
virtual QCString TranslatorDanish::trDir (bool first_capital, bool singular) inline virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1421 of file translator_dk.h.
References createNoun().
trDirDepGraph()
virtual QCString TranslatorDanish::trDirDepGraph (const char * name) inline virtual
Implements Translator.
Definition at line 1764 of file translator_dk.h.
trDirDescription()
virtual QCString TranslatorDanish::trDirDescription () inline virtual
This returns a sentences that introduces the directory hierarchy. and the fact that it is sorted alphabetically per level
Implements Translator.
Definition at line 1407 of file translator_dk.h.
trDirDocumentation()
virtual QCString TranslatorDanish::trDirDocumentation () inline virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1395 of file translator_dk.h.
trDirectories()
virtual QCString TranslatorDanish::trDirectories () inline virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1401 of file translator_dk.h.
trDirIndex()
virtual QCString TranslatorDanish::trDirIndex () inline virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1389 of file translator_dk.h.
trDirReference()
virtual QCString TranslatorDanish::trDirReference (const char * dirName) inline virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1415 of file translator_dk.h.
trDirRelation()
virtual QCString TranslatorDanish::trDirRelation (const char * name) inline virtual
directory relation for name
Implements Translator.
Definition at line 1672 of file translator_dk.h.
trDocumentation()
virtual QCString TranslatorDanish::trDocumentation () inline virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 351 of file translator_dk.h.
trEnumerations()
virtual QCString TranslatorDanish::trEnumerations () inline virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 439 of file translator_dk.h.
trEnumerationTypeDocumentation()
virtual QCString TranslatorDanish::trEnumerationTypeDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 475 of file translator_dk.h.
trEnumerationValueDocumentation()
virtual QCString TranslatorDanish::trEnumerationValueDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 481 of file translator_dk.h.
trEnumerationValues()
virtual QCString TranslatorDanish::trEnumerationValues () inline virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 457 of file translator_dk.h.
trEnumName()
virtual QCString TranslatorDanish::trEnumName () inline virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 192 of file translator_dk.h.
trEnumValue()
virtual QCString TranslatorDanish::trEnumValue () inline virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 196 of file translator_dk.h.
trEventDocumentation()
virtual QCString TranslatorDanish::trEventDocumentation () inline virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1289 of file translator_dk.h.
trEvents()
virtual QCString TranslatorDanish::trEvents () inline virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1284 of file translator_dk.h.
trExampleDocumentation()
virtual QCString TranslatorDanish::trExampleDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 411 of file translator_dk.h.
trExamples()
virtual QCString TranslatorDanish::trExamples () inline virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 255 of file translator_dk.h.
trExamplesDescription()
virtual QCString TranslatorDanish::trExamplesDescription () inline virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 339 of file translator_dk.h.
trExceptions()
virtual QCString TranslatorDanish::trExceptions () inline virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 554 of file translator_dk.h.
trFile()
virtual QCString TranslatorDanish::trFile (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1161 of file translator_dk.h.
References createNoun().
trFileDocumentation()
virtual QCString TranslatorDanish::trFileDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 405 of file translator_dk.h.
trFileIn()
virtual QCString TranslatorDanish::trFileIn (const char * name) inline virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1709 of file translator_dk.h.
trFileIndex()
virtual QCString TranslatorDanish::trFileIndex () inline virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 381 of file translator_dk.h.
trFileList()
virtual QCString TranslatorDanish::trFileList () inline virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 226 of file translator_dk.h.
trFileListDescription()
virtual QCString TranslatorDanish::trFileListDescription (bool extractAll) inline virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 269 of file translator_dk.h.
trFileMembers()
virtual QCString TranslatorDanish::trFileMembers () inline virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 240 of file translator_dk.h.
References Config_getBool.
trFileMembersDescription()
virtual QCString TranslatorDanish::trFileMembersDescription (bool extractAll) inline virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 319 of file translator_dk.h.
References Config_getBool.
trFileReference()
virtual QCString TranslatorDanish::trFileReference (const char * fileName) inline virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 621 of file translator_dk.h.
trForInternalUseOnly()
virtual QCString TranslatorDanish::trForInternalUseOnly () inline virtual
this text is generated when the \internal command is used.
Implements Translator.
Definition at line 526 of file translator_dk.h.
trFriends()
virtual QCString TranslatorDanish::trFriends () inline virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 581 of file translator_dk.h.
trFunctionDocumentation()
virtual QCString TranslatorDanish::trFunctionDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 487 of file translator_dk.h.
trFunctions()
virtual QCString TranslatorDanish::trFunctions () inline virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 445 of file translator_dk.h.
trGeneratedAt()
virtual QCString TranslatorDanish::trGeneratedAt (const char * date, const char * projName) inline virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 511 of file translator_dk.h.
trGeneratedAutomatically()
virtual QCString TranslatorDanish::trGeneratedAutomatically (const char * s) inline virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 184 of file translator_dk.h.
trGeneratedBy()
virtual QCString TranslatorDanish::trGeneratedBy () inline virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 558 of file translator_dk.h.
trGeneratedFromFiles()
virtual QCString TranslatorDanish::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 757 of file translator_dk.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
virtual QCString TranslatorDanish::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1618 of file translator_dk.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
virtual QCString TranslatorDanish::trGlobal (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1206 of file translator_dk.h.
References createNoun().
trGlobalNamespace()
virtual QCString TranslatorDanish::trGlobalNamespace () inline virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1684 of file translator_dk.h.
trGotoDocumentation()
virtual QCString TranslatorDanish::trGotoDocumentation () inline virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 846 of file translator_dk.h.
trGotoGraphicalHierarchy()
virtual QCString TranslatorDanish::trGotoGraphicalHierarchy () inline virtual
Implements Translator.
Definition at line 868 of file translator_dk.h.
trGotoSourceCode()
virtual QCString TranslatorDanish::trGotoSourceCode () inline virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 843 of file translator_dk.h.
trGotoTextualHierarchy()
virtual QCString TranslatorDanish::trGotoTextualHierarchy () inline virtual
Implements Translator.
Definition at line 870 of file translator_dk.h.
trGraphicalHierarchy()
virtual QCString TranslatorDanish::trGraphicalHierarchy () inline virtual
Implements Translator.
Definition at line 866 of file translator_dk.h.
trGroup()
virtual QCString TranslatorDanish::trGroup (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1179 of file translator_dk.h.
References createNoun().
trHierarchicalIndex()
virtual QCString TranslatorDanish::trHierarchicalIndex () inline virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 363 of file translator_dk.h.
trImplementedFromList()
virtual QCString TranslatorDanish::trImplementedFromList (int numEntries) inline virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1240 of file translator_dk.h.
References trWriteList().
trImplementedInList()
virtual QCString TranslatorDanish::trImplementedInList (int numEntries) inline virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1248 of file translator_dk.h.
References trWriteList().
trInclByDepGraph()
virtual QCString TranslatorDanish::trInclByDepGraph () inline virtual
Implements Translator.
Definition at line 939 of file translator_dk.h.
trInclDepGraph()
virtual QCString TranslatorDanish::trInclDepGraph (const char * fName) inline virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 831 of file translator_dk.h.
trIncludesFileIn()
virtual QCString TranslatorDanish::trIncludesFileIn (const char * name) inline virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1718 of file translator_dk.h.
trIncludingInheritedMembers()
virtual QCString TranslatorDanish::trIncludingInheritedMembers () inline virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 178 of file translator_dk.h.
trInheritedByList()
virtual QCString TranslatorDanish::trInheritedByList (int numEntries) inline virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 691 of file translator_dk.h.
References trWriteList().
trInheritsList()
virtual QCString TranslatorDanish::trInheritsList (int numEntries) inline virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 683 of file translator_dk.h.
References trWriteList().
trInitialValue()
virtual QCString TranslatorDanish::trInitialValue () inline virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 860 of file translator_dk.h.
trInvariant()
virtual QCString TranslatorDanish::trInvariant () inline virtual
Text for the \invariant command
Implements Translator.
Definition at line 856 of file translator_dk.h.
trLegend()
virtual QCString TranslatorDanish::trLegend () inline virtual
text for the link to the legend page
Implements Translator.
Definition at line 1028 of file translator_dk.h.
trLegendDocs()
virtual QCString TranslatorDanish::trLegendDocs () inline virtual
page explaining how the dot graph's should be interpreted
Implements Translator.
Definition at line 960 of file translator_dk.h.
References getDotImageExtension().
trLegendTitle()
virtual QCString TranslatorDanish::trLegendTitle () inline virtual
title of the graph legend page
Implements Translator.
Definition at line 955 of file translator_dk.h.
trListOfAllMembers()
virtual QCString TranslatorDanish::trListOfAllMembers () inline virtual
put in the class documentation
Implements Translator.
Definition at line 166 of file translator_dk.h.
trLoading()
virtual QCString TranslatorDanish::trLoading () inline virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1678 of file translator_dk.h.
trMainPage()
virtual QCString TranslatorDanish::trMainPage () inline virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 788 of file translator_dk.h.
trMember()
virtual QCString TranslatorDanish::trMember (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1197 of file translator_dk.h.
References createNoun().
trMemberDataDocumentation()
virtual QCString TranslatorDanish::trMemberDataDocumentation () inline virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 152 of file translator_dk.h.
References Config_getBool.
trMemberEnumerationDocumentation()
virtual QCString TranslatorDanish::trMemberEnumerationDocumentation () inline virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 143 of file translator_dk.h.
trMemberFunctionDocumentation()
virtual QCString TranslatorDanish::trMemberFunctionDocumentation () inline virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 148 of file translator_dk.h.
trMemberFunctionDocumentationFortran()
virtual QCString TranslatorDanish::trMemberFunctionDocumentationFortran () inline virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1455 of file translator_dk.h.
trMemberList()
virtual QCString TranslatorDanish::trMemberList () inline virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 170 of file translator_dk.h.
trMemberTypedefDocumentation()
virtual QCString TranslatorDanish::trMemberTypedefDocumentation () inline virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 139 of file translator_dk.h.
trModule()
virtual QCString TranslatorDanish::trModule (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1608 of file translator_dk.h.
trModuleDocumentation()
virtual QCString TranslatorDanish::trModuleDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 387 of file translator_dk.h.
trModuleIndex()
virtual QCString TranslatorDanish::trModuleIndex () inline virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 357 of file translator_dk.h.
trModuleReference()
virtual QCString TranslatorDanish::trModuleReference (const char * namespaceName) inline virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1570 of file translator_dk.h.
trModules()
virtual QCString TranslatorDanish::trModules () inline virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 208 of file translator_dk.h.
trModulesDescription()
virtual QCString TranslatorDanish::trModulesDescription () inline virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 347 of file translator_dk.h.
trModulesIndex()
virtual QCString TranslatorDanish::trModulesIndex () inline virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1601 of file translator_dk.h.
trModulesList()
virtual QCString TranslatorDanish::trModulesList () inline virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1535 of file translator_dk.h.
trModulesListDescription()
virtual QCString TranslatorDanish::trModulesListDescription (bool extractAll) inline virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1539 of file translator_dk.h.
trModulesMemberDescription()
virtual QCString TranslatorDanish::trModulesMemberDescription (bool extractAll) inline virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1582 of file translator_dk.h.
trModulesMembers()
virtual QCString TranslatorDanish::trModulesMembers () inline virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1578 of file translator_dk.h.
trMore()
virtual QCString TranslatorDanish::trMore () inline virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 162 of file translator_dk.h.
trNamespace()
virtual QCString TranslatorDanish::trNamespace (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1170 of file translator_dk.h.
References createNoun().
trNamespaceDocumentation()
virtual QCString TranslatorDanish::trNamespaceDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 737 of file translator_dk.h.
trNamespaceIndex()
virtual QCString TranslatorDanish::trNamespaceIndex () inline virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 731 of file translator_dk.h.
trNamespaceList()
virtual QCString TranslatorDanish::trNamespaceList () inline virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 566 of file translator_dk.h.
trNamespaceListDescription()
virtual QCString TranslatorDanish::trNamespaceListDescription (bool extractAll) inline virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 570 of file translator_dk.h.
trNamespaceMemberDescription()
virtual QCString TranslatorDanish::trNamespaceMemberDescription (bool extractAll) inline virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 717 of file translator_dk.h.
trNamespaceMembers()
virtual QCString TranslatorDanish::trNamespaceMembers () inline virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 713 of file translator_dk.h.
trNamespaceReference()
virtual QCString TranslatorDanish::trNamespaceReference (const char * namespaceName) inline virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 629 of file translator_dk.h.
trNamespaces()
virtual QCString TranslatorDanish::trNamespaces () inline virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 747 of file translator_dk.h.
trNoMatches()
virtual QCString TranslatorDanish::trNoMatches () inline virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1696 of file translator_dk.h.
trNote()
virtual QCString TranslatorDanish::trNote () inline virtual
Implements Translator.
Definition at line 879 of file translator_dk.h.
trOverloadText()
virtual QCString TranslatorDanish::trOverloadText () inline virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1433 of file translator_dk.h.
trPackage()
virtual QCString TranslatorDanish::trPackage (const char * name) inline virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1077 of file translator_dk.h.
trPackageAttribs()
virtual QCString TranslatorDanish::trPackageAttribs () inline virtual
Implements Translator.
Definition at line 1305 of file translator_dk.h.
trPackageList()
virtual QCString TranslatorDanish::trPackageList () inline virtual
Title of the package index page
Implements Translator.
Definition at line 1082 of file translator_dk.h.
trPackageListDescription()
virtual QCString TranslatorDanish::trPackageListDescription () inline virtual
The description of the package index page
Implements Translator.
Definition at line 1087 of file translator_dk.h.
trPackageMembers()
virtual QCString TranslatorDanish::trPackageMembers () inline virtual
Implements Translator.
Definition at line 1301 of file translator_dk.h.
trPackages()
virtual QCString TranslatorDanish::trPackages () inline virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1094 of file translator_dk.h.
trPackageTypes()
virtual QCString TranslatorDanish::trPackageTypes () inline virtual
Implements Translator.
Definition at line 1299 of file translator_dk.h.
trPage()
virtual QCString TranslatorDanish::trPage (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1188 of file translator_dk.h.
References createNoun().
trPageAbbreviation()
virtual QCString TranslatorDanish::trPageAbbreviation () inline virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 794 of file translator_dk.h.
trPageDocumentation()
virtual QCString TranslatorDanish::trPageDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all related pages.
Implements Translator.
Definition at line 417 of file translator_dk.h.
trPageIndex()
virtual QCString TranslatorDanish::trPageIndex () inline virtual
Implements Translator.
Definition at line 872 of file translator_dk.h.
trParameters()
virtual QCString TranslatorDanish::trParameters () inline virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 550 of file translator_dk.h.
trPostcondition()
virtual QCString TranslatorDanish::trPostcondition () inline virtual
Text for the \post command
Implements Translator.
Definition at line 853 of file translator_dk.h.
trPrecondition()
virtual QCString TranslatorDanish::trPrecondition () inline virtual
Text for the \pre command
Implements Translator.
Definition at line 850 of file translator_dk.h.
trPrivateAttribs()
virtual QCString TranslatorDanish::trPrivateAttribs () inline virtual
Implements Translator.
Definition at line 903 of file translator_dk.h.
trPrivateMembers()
virtual QCString TranslatorDanish::trPrivateMembers () inline virtual
Implements Translator.
Definition at line 650 of file translator_dk.h.
trPrivateSlots()
virtual QCString TranslatorDanish::trPrivateSlots () inline virtual
Implements Translator.
Definition at line 652 of file translator_dk.h.
trPrivateTypes()
virtual QCString TranslatorDanish::trPrivateTypes () inline virtual
Implements Translator.
Definition at line 901 of file translator_dk.h.
trProperties()
virtual QCString TranslatorDanish::trProperties () inline virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1053 of file translator_dk.h.
trPropertyDocumentation()
virtual QCString TranslatorDanish::trPropertyDocumentation () inline virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1058 of file translator_dk.h.
trProtectedAttribs()
virtual QCString TranslatorDanish::trProtectedAttribs () inline virtual
Implements Translator.
Definition at line 897 of file translator_dk.h.
trProtectedMembers()
virtual QCString TranslatorDanish::trProtectedMembers () inline virtual
Implements Translator.
Definition at line 644 of file translator_dk.h.
trProtectedSlots()
virtual QCString TranslatorDanish::trProtectedSlots () inline virtual
Implements Translator.
Definition at line 646 of file translator_dk.h.
trProtectedTypes()
virtual QCString TranslatorDanish::trProtectedTypes () inline virtual
Implements Translator.
Definition at line 895 of file translator_dk.h.
trPublicAttribs()
virtual QCString TranslatorDanish::trPublicAttribs () inline virtual
Implements Translator.
Definition at line 884 of file translator_dk.h.
References Config_getBool.
trPublicMembers()
virtual QCString TranslatorDanish::trPublicMembers () inline virtual
Implements Translator.
Definition at line 636 of file translator_dk.h.
trPublicSlots()
virtual QCString TranslatorDanish::trPublicSlots () inline virtual
Implements Translator.
Definition at line 638 of file translator_dk.h.
trPublicTypes()
virtual QCString TranslatorDanish::trPublicTypes () inline virtual
Implements Translator.
Definition at line 881 of file translator_dk.h.
trReferencedBy()
virtual QCString TranslatorDanish::trReferencedBy () inline virtual
Implements Translator.
Definition at line 927 of file translator_dk.h.
trReferenceManual()
virtual QCString TranslatorDanish::trReferenceManual () inline virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 421 of file translator_dk.h.
trReferences()
virtual QCString TranslatorDanish::trReferences () inline virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1228 of file translator_dk.h.
trReimplementedFromList()
virtual QCString TranslatorDanish::trReimplementedFromList (int numEntries) inline virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 699 of file translator_dk.h.
References trWriteList().
trReimplementedInList()
virtual QCString TranslatorDanish::trReimplementedInList (int numEntries) inline virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 707 of file translator_dk.h.
References trWriteList().
trRelatedFunctionDocumentation()
virtual QCString TranslatorDanish::trRelatedFunctionDocumentation () inline virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 591 of file translator_dk.h.
trRelatedFunctions()
virtual QCString TranslatorDanish::trRelatedFunctions () inline virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 126 of file translator_dk.h.
trRelatedPages()
virtual QCString TranslatorDanish::trRelatedPages () inline virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 251 of file translator_dk.h.
trRelatedPagesDescription()
virtual QCString TranslatorDanish::trRelatedPagesDescription () inline virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 343 of file translator_dk.h.
trRelatedSubscript()
virtual QCString TranslatorDanish::trRelatedSubscript () inline virtual
subscript for the related functions.
Implements Translator.
Definition at line 130 of file translator_dk.h.
trRemarks()
virtual QCString TranslatorDanish::trRemarks () inline virtual
Implements Translator.
Definition at line 931 of file translator_dk.h.
trReturns()
virtual QCString TranslatorDanish::trReturns () inline virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 542 of file translator_dk.h.
trReturnValues()
virtual QCString TranslatorDanish::trReturnValues () inline virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 783 of file translator_dk.h.
trRTFansicp()
virtual QCString TranslatorDanish::trRTFansicp () inline virtual
Used as ansicpg for RTF file (used table extract:)
Charset Name       Charset Value(hex)  Codepage number
ANSI_CHARSET              0 (x00)            1252
Implements Translator.
Definition at line 1131 of file translator_dk.h.
trRTFCharSet()
virtual QCString TranslatorDanish::trRTFCharSet () inline virtual
Used as ansicpg for RTF fcharset
Implements Translator.
Definition at line 1137 of file translator_dk.h.
trRTFGeneralIndex()
virtual QCString TranslatorDanish::trRTFGeneralIndex () inline virtual
Used as header RTF general index
Implements Translator.
Definition at line 1143 of file translator_dk.h.
trRTFTableOfContents()
virtual QCString TranslatorDanish::trRTFTableOfContents () inline virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1260 of file translator_dk.h.
trSearch()
virtual QCString TranslatorDanish::trSearch () inline virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 259 of file translator_dk.h.
trSearching()
virtual QCString TranslatorDanish::trSearching () inline virtual
Message shown while searching
Implements Translator.
Definition at line 1690 of file translator_dk.h.
trSearchMatches()
virtual QCString TranslatorDanish::trSearchMatches () inline virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1364 of file translator_dk.h.
trSearchResults()
virtual QCString TranslatorDanish::trSearchResults (int numDocuments) inline virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1348 of file translator_dk.h.
trSearchResultsTitle()
virtual QCString TranslatorDanish::trSearchResultsTitle () inline virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1335 of file translator_dk.h.
trSeeAlso()
virtual QCString TranslatorDanish::trSeeAlso () inline virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 546 of file translator_dk.h.
trSignals()
virtual QCString TranslatorDanish::trSignals () inline virtual
Implements Translator.
Definition at line 640 of file translator_dk.h.
trSince()
virtual QCString TranslatorDanish::trSince () inline virtual
Implements Translator.
Definition at line 945 of file translator_dk.h.
trSourceFile()
virtual QCString TranslatorDanish::trSourceFile (QCString & filename) inline virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1376 of file translator_dk.h.
trStaticPackageAttribs()
virtual QCString TranslatorDanish::trStaticPackageAttribs () inline virtual
Implements Translator.
Definition at line 1307 of file translator_dk.h.
trStaticPackageMembers()
virtual QCString TranslatorDanish::trStaticPackageMembers () inline virtual
Implements Translator.
Definition at line 1303 of file translator_dk.h.
trStaticPrivateAttribs()
virtual QCString TranslatorDanish::trStaticPrivateAttribs () inline virtual
Implements Translator.
Definition at line 905 of file translator_dk.h.
trStaticPrivateMembers()
virtual QCString TranslatorDanish::trStaticPrivateMembers () inline virtual
Implements Translator.
Definition at line 654 of file translator_dk.h.
trStaticProtectedAttribs()
virtual QCString TranslatorDanish::trStaticProtectedAttribs () inline virtual
Implements Translator.
Definition at line 899 of file translator_dk.h.
trStaticProtectedMembers()
virtual QCString TranslatorDanish::trStaticProtectedMembers () inline virtual
Implements Translator.
Definition at line 648 of file translator_dk.h.
trStaticPublicAttribs()
virtual QCString TranslatorDanish::trStaticPublicAttribs () inline virtual
Implements Translator.
Definition at line 893 of file translator_dk.h.
trStaticPublicMembers()
virtual QCString TranslatorDanish::trStaticPublicMembers () inline virtual
Implements Translator.
Definition at line 642 of file translator_dk.h.
trSubprogram()
virtual QCString TranslatorDanish::trSubprogram (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1654 of file translator_dk.h.
trSubprogramDocumentation()
virtual QCString TranslatorDanish::trSubprogramDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1525 of file translator_dk.h.
trSubprograms()
virtual QCString TranslatorDanish::trSubprograms () inline virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1519 of file translator_dk.h.
trTest()
virtual QCString TranslatorDanish::trTest () inline virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1038 of file translator_dk.h.
trTestList()
virtual QCString TranslatorDanish::trTestList () inline virtual
Used as the header of the test list
Implements Translator.
Definition at line 1043 of file translator_dk.h.
trThisIsTheListOfAllMembers()
virtual QCString TranslatorDanish::trThisIsTheListOfAllMembers () inline virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 174 of file translator_dk.h.
trTodo()
virtual QCString TranslatorDanish::trTodo () inline virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 913 of file translator_dk.h.
trTodoList()
virtual QCString TranslatorDanish::trTodoList () inline virtual
Used as the header of the todo list
Implements Translator.
Definition at line 918 of file translator_dk.h.
trType()
virtual QCString TranslatorDanish::trType (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1643 of file translator_dk.h.
trTypeConstraints()
virtual QCString TranslatorDanish::trTypeConstraints () inline virtual
C# Type Constraint list
Implements Translator.
Definition at line 1662 of file translator_dk.h.
trTypedefDocumentation()
virtual QCString TranslatorDanish::trTypedefDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 469 of file translator_dk.h.
trTypedefs()
virtual QCString TranslatorDanish::trTypedefs () inline virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 433 of file translator_dk.h.
trTypeDocumentation()
virtual QCString TranslatorDanish::trTypeDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1513 of file translator_dk.h.
trVariableDocumentation()
virtual QCString TranslatorDanish::trVariableDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 493 of file translator_dk.h.
trVariables()
virtual QCString TranslatorDanish::trVariables () inline virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 451 of file translator_dk.h.
trVersion()
virtual QCString TranslatorDanish::trVersion () inline virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 534 of file translator_dk.h.
trWarning()
virtual QCString TranslatorDanish::trWarning () inline virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 530 of file translator_dk.h.
trWriteList()
virtual QCString TranslatorDanish::trWriteList (int numEntries) inline virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 660 of file translator_dk.h.
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_dk.h