Doxygen: ExprAstFilter Class Reference
ExprAstFilter Class Reference
Class representing a filter in the AST.
Public Member Functions
ExprAstFilter (const char *name, ExprAst *arg)
~ExprAstFilter ()
const QCString & name () const
TemplateVariant apply (const TemplateVariant &v, TemplateContext *c)
Public Member Functions inherited from ExprAst
virtual ~ExprAst ()
virtual TemplateVariant resolve (TemplateContext *)
Private Attributes
QCString m_name
ExprAst * m_arg
Detailed Description
Class representing a filter in the AST.
Definition at line 1505 of file template.cpp.
Constructor & Destructor Documentation
ExprAstFilter()
ExprAstFilter::ExprAstFilter (const char * name, ExprAst * arg) inline
Definition at line 1508 of file template.cpp.
References TRACE.
~ExprAstFilter()
ExprAstFilter::~ExprAstFilter () inline
Definition at line 1510 of file template.cpp.
References m_arg.
Member Function Documentation
apply()
TemplateVariant ExprAstFilter::apply (const TemplateVariant & v, TemplateContext * c) inline
Definition at line 1512 of file template.cpp.
References TemplateFilterFactory::apply(), TemplateFilterFactory::instance(), TemplateContextImpl::line(), m_arg, m_name, ExprAst::resolve(), TemplateContextImpl::templateName(), TemplateVariant::toString(), TRACE, TemplateVariant::type(), and TemplateContextImpl::warn().
Referenced by ExprAstFilterAppl::resolve().
name()
const QCString& ExprAstFilter::name () const inline
Definition at line 1511 of file template.cpp.
References m_name.
Member Data Documentation
m_arg
ExprAst* ExprAstFilter::m_arg private
Definition at line 1529 of file template.cpp.
Referenced by apply(), and ~ExprAstFilter().
m_name
QCString ExprAstFilter::m_name private
Definition at line 1528 of file template.cpp.
Referenced by apply(), and name().
The documentation for this class was generated from the following file:
src/template.cpp