Doxygen: vhdl::parser::CharStream Class Reference
vhdl::parser::CharStream Class Reference
This class describes a character stream that maintains line and column number positions of the characters.
#include <CharStream.h>
Public Member Functions
void setTabSize (int i)
int getTabSize (int i)
virtual int getColumn ()
virtual int getLine ()
virtual int getEndColumn ()
virtual int getEndLine ()
virtual int getBeginColumn ()
virtual int getBeginLine ()
virtual bool getTrackLineColumn ()
virtual void setTrackLineColumn (bool val)
virtual void backup (int amount)
Backs up the input stream by amount steps.
virtual JAVACC_CHAR_TYPE BeginToken ()
Returns the next character that marks the beginning of the next token.
virtual JAVACC_CHAR_TYPE readChar ()
Returns the next character from the selected input.
virtual void ExpandBuff (bool wrapAround)
virtual void FillBuff ()
virtual JAVACC_STRING_TYPE GetImage ()
Returns a string made up of characters from the marked token beginning to the current buffer position.
virtual JAVACC_STRING_TYPE GetSuffix (int len)
Returns an array of characters that make up the suffix of length 'len' for the currently matched token.
virtual void DeleteBuffers ()
The lexer calls this function to indicate that it is done with the stream and hence implementations can free any resources held by this class.
virtual ~CharStream ()
bool endOfInput ()
CharStream (const JAVACC_CHAR_TYPE *buf, int sz, int startline, int startcolumn, int buffersize)
CharStream (const JAVACC_CHAR_TYPE *buf, int sz, int startline, int startcolumn)
CharStream (const JAVACC_STRING_TYPE &str, int startline, int startcolumn, int buffersize)
CharStream (const JAVACC_STRING_TYPE &str, int startline, int startcolumn)
CharStream (ReaderStream *input_stream, int startline, int startcolumn, int buffersize)
CharStream (ReaderStream *input_stream, int startline, int startcolumn)
CharStream (ReaderStream *input_stream)
virtual void ReInit (ReaderStream *input_stream, int startline, int startcolumn, int buffersize)
virtual void ReInit (ReaderStream *input_stream, int startline, int startcolumn)
virtual void ReInit (ReaderStream *input_stream)
virtual void ReInit (const JAVACC_STRING_TYPE &str, int startline, int startcolumn, int buffersize)
virtual void ReInit (const JAVACC_STRING_TYPE &str, int startline, int startcolumn)
virtual void adjustBeginLineColumn (int newLine, int newCol)
Protected Member Functions
virtual void UpdateLineColumn (JAVACC_CHAR_TYPE c)
Protected Attributes
int * bufline
int * bufcolumn
JAVACC_CHAR_TYPE * buffer
int bufpos
int bufsize
int tokenBegin
int column
int line
bool prevCharIsCR
bool prevCharIsLF
int available
int maxNextCharInd
int inBuf
int tabSize
bool trackLineColumn
ReaderStream * inputStream
bool deleteStream
Private Member Functions
int getBufcolumn (int pos)
int getBufline (int pos)
Detailed Description
This class describes a character stream that maintains line and column number positions of the characters.
It also has the capability to backup the stream to some extent. An implementation of this class is used in the TokenManager implementation generated by JavaCCParser.
All the methods except backup can be implemented in any fashion. backup needs to be implemented correctly for the correct operation of the lexer. Rest of the methods are all used to get information like line number, column number and the string that constitutes a token and are not used by the lexer. Hence their implementation won't affect the generated lexer's operation.
Definition at line 30 of file CharStream.h.
Constructor & Destructor Documentation
~CharStream()
virtual vhdl::parser::CharStream::~CharStream () inline virtual
Definition at line 152 of file CharStream.h.
References DeleteBuffers(), deleteStream, and inputStream.
CharStream() [1/7]
vhdl::parser::CharStream::CharStream (const JAVACC_CHAR_TYPE * buf, int sz, int startline, int startcolumn, int buffersize) inline
Definition at line 163 of file CharStream.h.
References JAVACC_STRING_TYPE, and ReInit().
CharStream() [2/7]
vhdl::parser::CharStream::CharStream (const JAVACC_CHAR_TYPE * buf, int sz, int startline, int startcolumn) inline
Definition at line 172 of file CharStream.h.
References INITIAL_BUFFER_SIZE, JAVACC_STRING_TYPE, and ReInit().
CharStream() [3/7]
vhdl::parser::CharStream::CharStream (const JAVACC_STRING_TYPE & str, int startline, int startcolumn, int buffersize) inline
Definition at line 180 of file CharStream.h.
References ReInit().
CharStream() [4/7]
vhdl::parser::CharStream::CharStream (const JAVACC_STRING_TYPE & str, int startline, int startcolumn) inline
Definition at line 189 of file CharStream.h.
References INITIAL_BUFFER_SIZE, and ReInit().
CharStream() [5/7]
vhdl::parser::CharStream::CharStream (ReaderStream * input_stream, int startline, int startcolumn, int buffersize) inline
Definition at line 197 of file CharStream.h.
References INITIAL_BUFFER_SIZE, and ReInit().
CharStream() [6/7]
vhdl::parser::CharStream::CharStream (ReaderStream * input_stream, int startline, int startcolumn) inline
Definition at line 206 of file CharStream.h.
References INITIAL_BUFFER_SIZE, and ReInit().
CharStream() [7/7]
vhdl::parser::CharStream::CharStream (ReaderStream * input_stream) inline
Definition at line 214 of file CharStream.h.
References INITIAL_BUFFER_SIZE, and ReInit().
Member Function Documentation
adjustBeginLineColumn()
virtual void vhdl::parser::CharStream::adjustBeginLineColumn (int newLine, int newCol) virtual
backup()
virtual void vhdl::parser::CharStream::backup (int amount) inline virtual
Backs up the input stream by amount steps.
Lexer calls this method if it had already read some characters, but could not use them to match a (longer) token. So, they will be used again as the prefix of the next token and it is the implemetation's responsibility to do this right.
Definition at line 66 of file CharStream.h.
References bufpos, bufsize, and inBuf.
BeginToken()
virtual JAVACC_CHAR_TYPE vhdl::parser::CharStream::BeginToken () inline virtual
Returns the next character that marks the beginning of the next token.
All characters must remain in the buffer between two successive calls to this method to implement backup correctly.
Definition at line 79 of file CharStream.h.
References bufpos, JAVACC_CHAR_TYPE, readChar(), and tokenBegin.
DeleteBuffers()
virtual void vhdl::parser::CharStream::DeleteBuffers () virtual
The lexer calls this function to indicate that it is done with the stream and hence implementations can free any resources held by this class.
Referenced by ~CharStream().
endOfInput()
bool vhdl::parser::CharStream::endOfInput () inline
Definition at line 159 of file CharStream.h.
References bufpos, ReaderStream::endOfInput(), inBuf, inputStream, and maxNextCharInd.
ExpandBuff()
virtual void vhdl::parser::CharStream::ExpandBuff (bool wrapAround) virtual
FillBuff()
virtual void vhdl::parser::CharStream::FillBuff () virtual
Referenced by readChar().
getBeginColumn()
virtual int vhdl::parser::CharStream::getBeginColumn () inline virtual
Definition at line 54 of file CharStream.h.
References getBufcolumn(), and tokenBegin.
getBeginLine()
virtual int vhdl::parser::CharStream::getBeginLine () inline virtual
Definition at line 55 of file CharStream.h.
References getBufline(), and tokenBegin.
getBufcolumn()
int vhdl::parser::CharStream::getBufcolumn (int pos) inline private
Definition at line 35 of file CharStream.h.
References bufcolumn, and trackLineColumn.
Referenced by getBeginColumn(), getColumn(), and getEndColumn().
getBufline()
int vhdl::parser::CharStream::getBufline (int pos) inline private
Definition at line 42 of file CharStream.h.
References bufline, and trackLineColumn.
Referenced by getBeginLine(), getEndLine(), and getLine().
getColumn()
virtual int vhdl::parser::CharStream::getColumn () inline virtual
Definition at line 50 of file CharStream.h.
References bufpos, and getBufcolumn().
getEndColumn()
virtual int vhdl::parser::CharStream::getEndColumn () inline virtual
Definition at line 52 of file CharStream.h.
References bufpos, and getBufcolumn().
getEndLine()
virtual int vhdl::parser::CharStream::getEndLine () inline virtual
Definition at line 53 of file CharStream.h.
References bufpos, and getBufline().
GetImage()
virtual JAVACC_STRING_TYPE vhdl::parser::CharStream::GetImage () inline virtual
Returns a string made up of characters from the marked token beginning to the current buffer position.
Implementations can return anything that they want to. For example, for efficiency, one might decide to just return NULL, which is a valid implementation.
Definition at line 126 of file CharStream.h.
References buffer, bufpos, bufsize, JAVACC_STRING_TYPE, and tokenBegin.
getLine()
virtual int vhdl::parser::CharStream::getLine () inline virtual
Definition at line 51 of file CharStream.h.
References bufpos, and getBufline().
GetSuffix()
virtual JAVACC_STRING_TYPE vhdl::parser::CharStream::GetSuffix (int len) inline virtual
Returns an array of characters that make up the suffix of length 'len' for the currently matched token.
This is used to build up the matched string for use in actions in the case of MORE. A simple and inefficient implementation of this is as follows :
Definition at line 139 of file CharStream.h.
References buffer, bufpos, bufsize, and JAVACC_STRING_TYPE.
getTabSize()
int vhdl::parser::CharStream::getTabSize (int i) inline
Definition at line 33 of file CharStream.h.
References tabSize.
getTrackLineColumn()
virtual bool vhdl::parser::CharStream::getTrackLineColumn () inline virtual
Definition at line 57 of file CharStream.h.
References trackLineColumn.
readChar()
virtual JAVACC_CHAR_TYPE vhdl::parser::CharStream::readChar () inline virtual
Returns the next character from the selected input.
The method of selecting the input is the responsibility of the class implementing this class.
Definition at line 92 of file CharStream.h.
References buffer, bufpos, bufsize, FillBuff(), inBuf, JAVACC_CHAR_TYPE, maxNextCharInd, trackLineColumn, and UpdateLineColumn().
Referenced by BeginToken().
ReInit() [1/5]
virtual void vhdl::parser::CharStream::ReInit (ReaderStream * input_stream, int startline, int startcolumn, int buffersize) virtual
Referenced by CharStream(), and ReInit().
ReInit() [2/5]
virtual void vhdl::parser::CharStream::ReInit (ReaderStream * input_stream, int startline, int startcolumn) inline virtual
Definition at line 224 of file CharStream.h.
References INITIAL_BUFFER_SIZE, and ReInit().
ReInit() [3/5]
virtual void vhdl::parser::CharStream::ReInit (ReaderStream * input_stream) inline virtual
Definition at line 228 of file CharStream.h.
References INITIAL_BUFFER_SIZE, and ReInit().
ReInit() [4/5]
virtual void vhdl::parser::CharStream::ReInit (const JAVACC_STRING_TYPE & str, int startline, int startcolumn, int buffersize) virtual
ReInit() [5/5]
virtual void vhdl::parser::CharStream::ReInit (const JAVACC_STRING_TYPE & str, int startline, int startcolumn) inline virtual
Definition at line 235 of file CharStream.h.
References INITIAL_BUFFER_SIZE, and ReInit().
setTabSize()
void vhdl::parser::CharStream::setTabSize (int i) inline
Definition at line 32 of file CharStream.h.
References tabSize.
setTrackLineColumn()
virtual void vhdl::parser::CharStream::setTrackLineColumn (bool val) inline virtual
Definition at line 58 of file CharStream.h.
References trackLineColumn.
UpdateLineColumn()
virtual void vhdl::parser::CharStream::UpdateLineColumn (JAVACC_CHAR_TYPE c) protected virtual
Referenced by readChar().
Member Data Documentation
available
int vhdl::parser::CharStream::available protected
Definition at line 255 of file CharStream.h.
bufcolumn
int* vhdl::parser::CharStream::bufcolumn protected
Definition at line 246 of file CharStream.h.
Referenced by getBufcolumn().
buffer
JAVACC_CHAR_TYPE* vhdl::parser::CharStream::buffer protected
Definition at line 247 of file CharStream.h.
Referenced by GetImage(), GetSuffix(), and readChar().
bufline
int* vhdl::parser::CharStream::bufline protected
Definition at line 245 of file CharStream.h.
Referenced by getBufline().
bufpos
int vhdl::parser::CharStream::bufpos protected
Definition at line 248 of file CharStream.h.
Referenced by backup(), BeginToken(), endOfInput(), getColumn(), getEndColumn(), getEndLine(), GetImage(), getLine(), GetSuffix(), and readChar().
bufsize
int vhdl::parser::CharStream::bufsize protected
Definition at line 249 of file CharStream.h.
Referenced by backup(), GetImage(), GetSuffix(), and readChar().
column
int vhdl::parser::CharStream::column protected
Definition at line 251 of file CharStream.h.
deleteStream
bool vhdl::parser::CharStream::deleteStream protected
Definition at line 261 of file CharStream.h.
Referenced by ~CharStream().
inBuf
int vhdl::parser::CharStream::inBuf protected
Definition at line 257 of file CharStream.h.
Referenced by backup(), endOfInput(), and readChar().
inputStream
ReaderStream* vhdl::parser::CharStream::inputStream protected
Definition at line 260 of file CharStream.h.
Referenced by endOfInput(), and ~CharStream().
line
int vhdl::parser::CharStream::line protected
Definition at line 252 of file CharStream.h.
maxNextCharInd
int vhdl::parser::CharStream::maxNextCharInd protected
Definition at line 256 of file CharStream.h.
Referenced by endOfInput(), and readChar().
prevCharIsCR
bool vhdl::parser::CharStream::prevCharIsCR protected
Definition at line 253 of file CharStream.h.
prevCharIsLF
bool vhdl::parser::CharStream::prevCharIsLF protected
Definition at line 254 of file CharStream.h.
tabSize
int vhdl::parser::CharStream::tabSize protected
Definition at line 258 of file CharStream.h.
Referenced by getTabSize(), and setTabSize().
tokenBegin
int vhdl::parser::CharStream::tokenBegin protected
Definition at line 250 of file CharStream.h.
Referenced by BeginToken(), getBeginColumn(), getBeginLine(), and GetImage().
trackLineColumn
bool vhdl::parser::CharStream::trackLineColumn protected
Definition at line 259 of file CharStream.h.
Referenced by getBufcolumn(), getBufline(), getTrackLineColumn(), readChar(), and setTrackLineColumn().
The documentation for this class was generated from the following file:
vhdlparser/CharStream.h