Doxygen: DotGfxHierarchyTable Class Reference
DotGfxHierarchyTable Class Reference
Represents a graphical class hierarchy.
#include <dot.h>
Public Member Functions
DotGfxHierarchyTable ()
~DotGfxHierarchyTable ()
void writeGraph (FTextStream &t, const char *path, const char *fileName) const
void createGraph (DotNode *rootNode, FTextStream &t, const char *path, const char *fileName, int id) const
const DotNodeList * subGraphs () const
Private Member Functions
void addHierarchy (DotNode *n, ClassDef *cd, bool hide)
void addClassList (ClassSDict *cl)
Private Attributes
QList< DotNode > * m_rootNodes
QDict< DotNode > * m_usedNodes
int m_curNodeNumber
DotNodeList * m_rootSubgraphs
Detailed Description
Represents a graphical class hierarchy.
Definition at line 149 of file dot.h.
Constructor & Destructor Documentation
DotGfxHierarchyTable()
DotGfxHierarchyTable::DotGfxHierarchyTable ()
Definition at line 2480 of file dot.cpp.
References addClassList(), Doxygen::classSDict, DotNode::colorConnectedNodes(), DotNode::findDocNode(), Doxygen::hiddenClasses, initClassHierarchy(), m_rootNodes, m_rootSubgraphs, DotNode::m_subgraphId, m_usedNodes, DotNode::markAsVisible(), and DotNode::renumberNodes().
~DotGfxHierarchyTable()
DotGfxHierarchyTable::~DotGfxHierarchyTable ()
Definition at line 2536 of file dot.cpp.
References m_rootNodes, m_rootSubgraphs, and m_usedNodes.
Member Function Documentation
addClassList()
void DotGfxHierarchyTable::addClassList (ClassSDict * cl) private
Definition at line 2435 of file dot.cpp.
References addHierarchy(), ClassDef::anchor(), ClassDef::baseClasses(), Definition::briefDescriptionAsTooltip(), ClassDef::displayName(), VhdlDocGen::ENTITYCLASS, Definition::getLanguage(), ClassDef::getOutputFileBase(), ClassDef::getReference(), hasVisibleRoot(), Definition::isHidden(), ClassDef::isLinkable(), ClassDef::isVisibleInHierarchy(), SDict< ClassDef >::Iterator, m_curNodeNumber, m_rootNodes, m_usedNodes, Definition::name(), ClassDef::protection(), SrcLangExt_VHDL, ClassDef::subClasses(), and ClassDef::visited.
Referenced by DotGfxHierarchyTable().
addHierarchy()
void DotGfxHierarchyTable::addHierarchy (DotNode * n, ClassDef * cd, bool hide) private
Definition at line 2361 of file dot.cpp.
References DotNode::addChild(), DotNode::addParent(), ClassDef::anchor(), ClassDef::baseClasses(), Definition::briefDescriptionAsTooltip(), ClassDef::displayName(), ClassDef::getOutputFileBase(), ClassDef::getReference(), hasVisibleRoot(), Definition::isHidden(), ClassDef::isLinkable(), ClassDef::isVisibleInHierarchy(), DotNode::m_children, m_curNodeNumber, m_usedNodes, Definition::name(), ClassDef::subClasses(), and ClassDef::visited.
Referenced by addClassList().
createGraph()
void DotGfxHierarchyTable::createGraph (DotNode * rootNode, FTextStream & t, const char * path, const char * fileName, int id) const
Definition at line 2238 of file dot.cpp.
References IndexList::addImageFile(), DotRunner::addJob(), DotManager::addMap(), DotManager::addRun(), DotManager::addSVGConversion(), DotManager::addSVGObject(), checkAndUpdateMd5Signature(), checkDeliverables(), DotNode::clearWriteFlag(), Config_getEnum, endl(), escapeCharsInString(), getDotImageExtension(), GOF_BITMAP, DotNode::Hierarchy, Doxygen::indexList, insertMapFile(), DotManager::instance(), DotNode::m_label, m_rootNodes, DotNode::m_subgraphId, MAP_CMD, removeDotGraph(), theTranslator, Translator::trGraphicalHierarchy(), DotNode::write(), writeGraphFooter(), writeGraphHeader(), and writeSVGFigureLink().
Referenced by InheritanceGraphContext::Private::graph(), and writeGraph().
subGraphs()
const DotNodeList* DotGfxHierarchyTable::subGraphs () const inline
Definition at line 156 of file dot.h.
References m_rootSubgraphs.
Referenced by ClassHierarchyContext::Private::diagrams().
writeGraph()
void DotGfxHierarchyTable::writeGraph (FTextStream & t, const char * path, const char * fileName) const
Definition at line 2331 of file dot.cpp.
References createGraph(), endl(), err(), and m_rootSubgraphs.
Referenced by HtmlGenerator::writeGraphicalHierarchy().
Member Data Documentation
m_curNodeNumber
int DotGfxHierarchyTable::m_curNodeNumber private
Definition at line 164 of file dot.h.
Referenced by addClassList(), and addHierarchy().
m_rootNodes
QList<DotNode>* DotGfxHierarchyTable::m_rootNodes private
Definition at line 162 of file dot.h.
Referenced by addClassList(), createGraph(), DotGfxHierarchyTable(), and ~DotGfxHierarchyTable().
m_rootSubgraphs
DotNodeList* DotGfxHierarchyTable::m_rootSubgraphs private
Definition at line 165 of file dot.h.
Referenced by DotGfxHierarchyTable(), subGraphs(), writeGraph(), and ~DotGfxHierarchyTable().
m_usedNodes
QDict<DotNode>* DotGfxHierarchyTable::m_usedNodes private
Definition at line 163 of file dot.h.
Referenced by addClassList(), addHierarchy(), DotGfxHierarchyTable(), and ~DotGfxHierarchyTable().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp