Doxygen: src/filedef.cpp File Reference
filedef.cpp File Reference
#include "memberlist.h"
#include "classlist.h"
#include "filedef.h"
#include "doxygen.h"
#include "memberdef.h"
#include "classdef.h"
#include "namespacedef.h"
#include "util.h"
#include "language.h"
#include "outputlist.h"
#include "dot.h"
#include "message.h"
#include "docparser.h"
#include "searchindex.h"
#include "htags.h"
#include "parserintf.h"
#include "portable.h"
#include "vhdldocgen.h"
#include "debug.h"
#include "layout.h"
#include "entry.h"
#include "groupdef.h"
#include "filename.h"
#include "membergroup.h"
#include "dirdef.h"
#include "config.h"
#include "clangparser.h"
#include "settings.h"
Classes
class DevNullCodeDocInterface
Class implementing CodeOutputInterface by throwing away everything.
Functions
static int findMatchingPart (const QCString &path, const QCString dir)
static Directory * findDirNode (Directory *root, const QCString &name)
static void mergeFileDef (Directory *root, FileDef *fd)
static void addDirsAsGroups (Directory *root, GroupDef *parent, int level)
void generateFileTree ()
static void getAllIncludeFilesRecursively (QDict< void > *filesVisited, const FileDef *fd, QStrList &incFiles)
Function Documentation
addDirsAsGroups()
static void addDirsAsGroups (Directory * root, GroupDef * parent, int level) static
Definition at line 1656 of file filedef.cpp.
References GroupDef::addGroup(), SDict< T >::append(), Directory::children(), DirEntry::Dir, Doxygen::groupSDict, DirEntry::kind(), Definition::makePartOfGroup(), DirEntry::name(), and DirEntry::path().
Referenced by generateFileTree().
findDirNode()
static Directory* findDirNode (Directory * root, const QCString & name) static
Definition at line 1490 of file filedef.cpp.
References Directory::addChild(), Directory::children(), DirEntry::Dir, findMatchingPart(), DirEntry::name(), Directory::rename(), Directory::reParent(), and DirEntry::setLast().
Referenced by mergeFileDef().
findMatchingPart()
static int findMatchingPart (const QCString & path, const QCString dir) static
Definition at line 1467 of file filedef.cpp.
Referenced by findDirNode().
generateFileTree()
void generateFileTree ()
Definition at line 1687 of file filedef.cpp.
References addDirsAsGroups(), Doxygen::inputNameList, mergeFileDef(), and DirEntry::setLast().
getAllIncludeFilesRecursively()
static void getAllIncludeFilesRecursively (QDict< void > * filesVisited, const FileDef * fd, QStrList & incFiles) static
Definition at line 1911 of file filedef.cpp.
References FileDef::includeFileList().
mergeFileDef()
static void mergeFileDef (Directory * root, FileDef * fd) static
Definition at line 1565 of file filedef.cpp.
References FileDef::absFilePath(), Directory::addChild(), Directory::children(), and findDirNode().
Referenced by generateFileTree().