Doxygen: ClassDiagram Class Reference
ClassDiagram Class Reference
Class representing a built-in class diagram.
#include <diagram.h>
Public Member Functions
ClassDiagram (ClassDef *root)
~ClassDiagram ()
void writeFigure (FTextStream &t, const char *path, const char *file) const
void writeImage (FTextStream &t, const char *path, const char *relPath, const char *file, bool generateMap=TRUE) const
Private Attributes
TreeDiagram * base
TreeDiagram * super
Detailed Description
Class representing a built-in class diagram.
Definition at line 29 of file diagram.h.
Constructor & Destructor Documentation
ClassDiagram()
ClassDiagram::ClassDiagram (ClassDef * root)
Definition at line 1027 of file diagram.cpp.
References base, clearVisitFlags(), TreeDiagram::computeLayout(), DiagramItem::move(), TreeDiagram::moveChildren(), super, and DiagramItem::xPos().
~ClassDiagram()
ClassDiagram::~ClassDiagram ()
Definition at line 1051 of file diagram.cpp.
References base, and super.
Member Function Documentation
writeFigure()
void ClassDiagram::writeFigure (FTextStream & t, const char * path, const char * file) const
Definition at line 1057 of file diagram.cpp.
References base, TreeDiagram::computeExtremes(), TreeDiagram::computeRows(), Config_getBool, TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), endl(), err(), gridWidth, DiagramItem::isInList(), DiagramItem::label(), portable_system(), portable_sysTimerStart(), portable_sysTimerStop(), and super.
Referenced by LatexGenerator::endClassDiagram(), and ClassContext::Private::inheritanceDiagram().
writeImage()
void ClassDiagram::writeImage (FTextStream & t, const char * path, const char * relPath, const char * file, bool generateMap = TRUE) const
Definition at line 1353 of file diagram.cpp.
References IndexList::addImageFile(), base, TreeDiagram::computeExtremes(), TreeDiagram::computeRows(), TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), endl(), fontHeight, gridWidth, IMAGE_EXT, Doxygen::indexList, labelHorMargin, labelHorSpacing, labelVertSpacing, and super.
Referenced by RTFGenerator::endClassDiagram(), HtmlGenerator::endClassDiagram(), and ClassContext::Private::inheritanceDiagram().
Member Data Documentation
base
TreeDiagram* ClassDiagram::base private
Definition at line 39 of file diagram.h.
Referenced by ClassDiagram(), writeFigure(), writeImage(), and ~ClassDiagram().
super
TreeDiagram* ClassDiagram::super private
Definition at line 40 of file diagram.h.
Referenced by ClassDiagram(), writeFigure(), writeImage(), and ~ClassDiagram().
The documentation for this class was generated from the following files:
src/diagram.h
src/diagram.cpp