Doxygen: InheritanceNodeContext::Private Class Reference
InheritanceNodeContext::Private Class Reference
Public Member Functions
Private (ClassDef *cd, const QCString &name)
TemplateVariant get (const char *n) const
TemplateVariant getClass () const
TemplateVariant name () const
Private Attributes
ClassDef * m_classDef
SharedPtr< ClassContext > m_classContext
QCString m_name
Static Private Attributes
static PropertyMapper< InheritanceNodeContext::Private > s_inst
Detailed Description
Definition at line 8377 of file context.cpp.
Constructor & Destructor Documentation
Private()
InheritanceNodeContext::Private::Private (ClassDef * cd, const QCString & name) inline
Definition at line 8380 of file context.cpp.
References PropertyMapper< T >::addProperty(), getClass(), Config::init(), name(), and s_inst.
Member Function Documentation
get()
TemplateVariant InheritanceNodeContext::Private::get (const char * n) const inline
Definition at line 8390 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by InheritanceNodeContext::get().
getClass()
TemplateVariant InheritanceNodeContext::Private::getClass () const inline
Definition at line 8394 of file context.cpp.
References ClassContext::alloc(), SharedPtr< T >::get(), m_classContext, m_classDef, and SharedPtr< T >::reset().
Referenced by Private().
name()
TemplateVariant InheritanceNodeContext::Private::name () const inline
Definition at line 8402 of file context.cpp.
References m_name.
Referenced by Private().
Member Data Documentation
m_classContext
SharedPtr<ClassContext> InheritanceNodeContext::Private::m_classContext mutable private
Definition at line 8408 of file context.cpp.
Referenced by getClass().
m_classDef
ClassDef* InheritanceNodeContext::Private::m_classDef private
Definition at line 8407 of file context.cpp.
Referenced by getClass().
m_name
QCString InheritanceNodeContext::Private::m_name private
Definition at line 8409 of file context.cpp.
Referenced by name().
s_inst
PropertyMapper< InheritanceNodeContext::Private > InheritanceNodeContext::Private::s_inst static private
Definition at line 8410 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp