Doxygen: src/docbookgen.cpp File Reference
docbookgen.cpp File Reference
#include <stdlib.h>
#include <qdir.h>
#include <qfile.h>
#include <qtextstream.h>
#include <qintdict.h>
#include "docbookgen.h"
#include "doxygen.h"
#include "message.h"
#include "config.h"
#include "classlist.h"
#include "util.h"
#include "defargs.h"
#include "outputgen.h"
#include "dot.h"
#include "pagedef.h"
#include "filename.h"
#include "version.h"
#include "docbookvisitor.h"
#include "docparser.h"
#include "language.h"
#include "parserintf.h"
#include "arguments.h"
#include "memberlist.h"
#include "groupdef.h"
#include "memberdef.h"
#include "namespacedef.h"
#include "membername.h"
#include "membergroup.h"
#include "dirdef.h"
#include "section.h"
Classes
class DocbookSectionMapper
class TextGeneratorDocbookImpl
class DocbookCodeGenerator
Macros
#define Docbook_DB(x) do {} while(0)
Functions
void writeDocbookString (FTextStream &t, const char *s)
void writeDocbookCodeString (FTextStream &t, const char *s, int &col)
static void writeDocbookHeaderMainpage (FTextStream &t)
static void writeDocbookHeader_ID (FTextStream &t, QCString id)
void writeDocbookLink (FTextStream &t, const char *, const char *compoundId, const char *anchorId, const char *text, const char *)
static void writeTemplateArgumentList (ArgumentList *al, FTextStream &t, Definition *scope, FileDef *fileScope, int indent)
static void writeTemplateList (ClassDef *cd, FTextStream &t)
static void writeDocbookDocBlock (FTextStream &t, const QCString &fileName, int lineNr, Definition *scope, MemberDef *md, const QCString &text)
void writeDocbookCodeBlock (FTextStream &t, FileDef *fd)
static QCString classOutputFileBase (ClassDef *cd)
static QCString memberOutputFileBase (MemberDef *md)
static void generateDocbookForMember (MemberDef *md, FTextStream &t, Definition *def, bool detailed=0)
static void generateDocbookSection (Definition *d, FTextStream &t, MemberList *ml, const char *, bool detailed=0, const char *header=0, const char *documentation=0)
static void writeInnerClasses (const ClassSDict *cl, FTextStream &t)
static void writeInnerNamespaces (const NamespaceSDict *nl, FTextStream &t)
static void writeInnerFiles (const FileList *fl, FTextStream &t)
static void writeInnerPages (const PageSDict *pl, FTextStream &t)
static void writeInnerGroups (const GroupList *gl, FTextStream &t)
static void writeInnerDirs (const DirList *dl, FTextStream &t)
static void writeInnerGroupFiles (const GroupList *gl, FTextStream &t)
static void generateDocbookForClass (ClassDef *cd, FTextStream &ti)
static void generateDocbookForNamespace (NamespaceDef *nd, FTextStream &ti)
static void generateDocbookForFile (FileDef *fd, FTextStream &ti)
static void generateDocbookForGroup (GroupDef *gd, FTextStream &ti)
static void generateDocbookForDir (DirDef *dd, FTextStream &ti)
static void generateDocbookForPage (PageDef *pd, FTextStream &ti, bool isExample)
void generateDocbook ()
Variables
static DocbookSectionMapper g_docbookSectionMapper
Macro Definition Documentation
Docbook_DB
#define Docbook_DB (x) do {} while(0)
Definition at line 51 of file docbookgen.cpp.
Referenced by DocbookCodeGenerator::codify(), DocbookCodeGenerator::endCodeLine(), DocbookCodeGenerator::endFontClass(), DocbookCodeGenerator::startCodeLine(), DocbookCodeGenerator::startFontClass(), DocbookCodeGenerator::writeCodeAnchor(), DocbookCodeGenerator::writeCodeLink(), DocbookCodeGenerator::writeLineNumber(), and DocbookCodeGenerator::writeTooltip().
Function Documentation
classOutputFileBase()
static QCString classOutputFileBase (ClassDef * cd) static
Definition at line 373 of file docbookgen.cpp.
References ClassDef::getOutputFileBase().
Referenced by generateDocbookForClass(), and writeInnerClasses().
generateDocbook()
void generateDocbook ()
MAINPAGE DOCUMENTATION
MODULE GROUP DOCUMENTATION
Definition at line 1760 of file docbookgen.cpp.
References Doxygen::classSDict, Config_getBool, Config_getString, createSubDirs(), Doxygen::directories, endl(), err(), Doxygen::exampleSDict, generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForNamespace(), generateDocbookForPage(), Doxygen::groupSDict, Doxygen::inputNameList, SDict< DirDef >::Iterator, SDict< ClassDef >::Iterator, SDict< GroupDef >::Iterator, SDict< PageDef >::Iterator, SDict< NamespaceDef >::Iterator, Doxygen::mainPage, msg(), FileDef::name(), Definition::name(), Doxygen::namespaceSDict, Doxygen::pageSDict, theTranslator, Translator::trClassDocumentation(), Translator::trDirDocumentation(), Translator::trExampleDocumentation(), Translator::trFileDocumentation(), and Translator::trModuleDocumentation().
Referenced by generateOutput(), and parseInput().
generateDocbookForClass()
static void generateDocbookForClass (ClassDef * cd, FTextStream & ti) static
Definition at line 1111 of file docbookgen.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), classOutputFileBase(), DotNode::Collaboration, ClassDef::compoundTypeString(), Config_getBool, Config_getString, convertToXML(), Definition::docFile(), Definition::docLine(), FileDef::docName(), Definition::documentation(), endl(), EOF_DocBook, err(), IncludeInfo::fileDef, generateDocbookSection(), ClassDef::getClassSDict(), Definition::getDefFileName(), Definition::getDefLine(), ClassDef::getMemberGroupSDict(), ClassDef::getMemberLists(), FileDef::getOutputFileBase(), ClassDef::getOutputFileBase(), GOF_BITMAP, ClassDef::includeInfo(), IncludeInfo::includeName, DotNode::Inheritance, Definition::isHidden(), ClassDef::isReference(), Definition::isReference(), SIntDict< MemberGroup >::Iterator, IncludeInfo::local, MemberListType_detailedLists, msg(), Definition::name(), relativePathToRoot(), stripPath(), ClassDef::templateMaster(), theTranslator, Translator::trDetailedDescription(), writeDocbookDocBlock(), writeDocbookHeader_ID(), writeDocbookString(), writeInnerClasses(), and writeTemplateList().
Referenced by generateDocbook().
generateDocbookForDir()
static void generateDocbookForDir (DirDef * dd, FTextStream & ti) static
Definition at line 1625 of file docbookgen.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, Config_getString, convertToXML(), DirDef::displayName(), Definition::docFile(), Definition::docLine(), Definition::documentation(), endl(), EOF_DocBook, err(), DirDef::getFiles(), DirDef::getOutputFileBase(), GOF_BITMAP, Definition::isReference(), Definition::name(), relativePathToRoot(), DirDef::subDirs(), theTranslator, Translator::trDetailedDescription(), Translator::trDirReference(), writeDocbookDocBlock(), writeDocbookHeader_ID(), writeInnerDirs(), and writeInnerFiles().
Referenced by generateDocbook().
generateDocbookForFile()
static void generateDocbookForFile (FileDef * fd, FTextStream & ti) static
Definition at line 1383 of file docbookgen.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, Config_getString, convertToXML(), Definition::docFile(), Definition::docLine(), Definition::documentation(), endl(), EOF_DocBook, err(), generateDocbookSection(), FileDef::getClassSDict(), Definition::getDefFileName(), FileDef::getMemberGroupSDict(), FileDef::getMemberLists(), FileDef::getNamespaceSDict(), FileDef::getOutputFileBase(), GOF_BITMAP, FileDef::includeFileList(), IncludeInfo::includeName, Definition::isReference(), SIntDict< MemberGroup >::Iterator, IncludeInfo::local, MemberListType_declarationLists, FileDef::name(), relativePathToRoot(), stripPath(), theTranslator, Translator::trDetailedDescription(), writeDocbookCodeBlock(), writeDocbookDocBlock(), writeDocbookHeader_ID(), writeDocbookString(), writeInnerClasses(), and writeInnerNamespaces().
Referenced by generateDocbook().
generateDocbookForGroup()
static void generateDocbookForGroup (GroupDef * gd, FTextStream & ti) static
Definition at line 1522 of file docbookgen.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, Config_getString, convertToXML(), Definition::docFile(), Definition::docLine(), Definition::documentation(), endl(), EOF_DocBook, err(), generateDocbookSection(), GroupDef::getClasses(), GroupDef::getFiles(), GroupDef::getMemberGroupSDict(), GroupDef::getMemberLists(), GroupDef::getNamespaces(), GroupDef::getOutputFileBase(), GroupDef::getPages(), GroupDef::getSubGroups(), GOF_BITMAP, GroupDef::groupTitle(), GroupDef::isASubGroup(), Definition::isReference(), SIntDict< MemberGroup >::Iterator, MemberListType_declarationLists, relativePathToRoot(), theTranslator, Translator::trDetailedDescription(), writeDocbookDocBlock(), writeDocbookHeader_ID(), writeInnerClasses(), writeInnerFiles(), writeInnerGroupFiles(), writeInnerGroups(), writeInnerNamespaces(), and writeInnerPages().
Referenced by generateDocbook().
generateDocbookForMember()
static void generateDocbookForMember (MemberDef * md, FTextStream & t, Definition * def, bool detailed = 0) static
Definition at line 393 of file docbookgen.cpp.
References MemberDef::anchor(), MemberDef::argsString(), MemberDef::briefDescription(), Config_getBool, convertToXML(), MemberDef::declaration(), MemberDef::declArgumentList(), MemberDef::definition(), DefinitionIntf::definitionType(), Definition::docFile(), Definition::docLine(), MemberDef::documentation(), endl(), MemberDef::enumFieldList(), Definition::getBodyDef(), MemberDef::getClassDef(), Definition::getDefFileName(), Definition::getDefLine(), MemberDef::getGroupDef(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), GroupDef::getOutputFileBase(), MemberDef::initializer(), Definition::isHidden(), linkifyText(), memberOutputFileBase(), MemberDef::memberType(), MemberType_DCOP, MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Argument::name, Definition::name(), stripPath(), theTranslator, Translator::trEnumerationValues(), Argument::type, DefinitionIntf::TypeGroup, MemberDef::typeString(), writeDocbookDocBlock(), and writeDocbookString().
Referenced by generateDocbookSection().
generateDocbookForNamespace()
static void generateDocbookForNamespace (NamespaceDef * nd, FTextStream & ti) static
Definition at line 1302 of file docbookgen.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, Config_getString, Definition::docFile(), Definition::docLine(), Definition::documentation(), endl(), err(), generateDocbookSection(), NamespaceDef::getClassSDict(), Definition::getDefFileName(), Definition::getDefLine(), NamespaceDef::getMemberGroupSDict(), NamespaceDef::getMemberLists(), NamespaceDef::getNamespaceSDict(), NamespaceDef::getOutputFileBase(), Definition::isHidden(), Definition::isReference(), SIntDict< MemberGroup >::Iterator, MemberListType_declarationLists, Definition::name(), stripPath(), theTranslator, Translator::trDetailedDescription(), writeDocbookDocBlock(), writeDocbookHeader_ID(), writeDocbookString(), writeInnerClasses(), and writeInnerNamespaces().
Referenced by generateDocbook().
generateDocbookForPage()
static void generateDocbookForPage (PageDef * pd, FTextStream & ti, bool isExample) static
Definition at line 1671 of file docbookgen.cpp.
References Config_getString, convertToXML(), Definition::docFile(), Definition::docLine(), Definition::documentation(), endl(), err(), SDict< T >::find(), PageDef::getGroupDef(), PageDef::getOutputFileBase(), PageDef::getSubPages(), PageDef::hasParentPage(), Definition::isReference(), Definition::name(), Doxygen::sectionDict, SectionInfo::title, writeDocbookDocBlock(), writeDocbookHeader_ID(), writeDocbookHeaderMainpage(), and writeInnerPages().
Referenced by generateDocbook().
generateDocbookSection()
static void generateDocbookSection (Definition * d, FTextStream & t, MemberList * ml, const char * , bool detailed = 0, const char * header = 0, const char * documentation = 0) static
Definition at line 813 of file docbookgen.cpp.
References Config_getBool, convertToXML(), DefinitionIntf::definitionType(), Definition::docFile(), Definition::docLine(), MemberDef::documentation(), endl(), generateDocbookForMember(), MemberDef::getNamespaceDef(), MemberList::listType(), MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decFuncMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_priAttribs, MemberListType_proAttribs, MemberListType_pubAttribs, theTranslator, Translator::trDefineDocumentation(), Translator::trDefines(), Translator::trEnumerations(), Translator::trEnumerationTypeDocumentation(), Translator::trFunctionDocumentation(), Translator::trFunctions(), Translator::trMemberDataDocumentation(), Translator::trPrivateAttribs(), Translator::trProtectedAttribs(), Translator::trPublicAttribs(), Translator::trTypedefDocumentation(), Translator::trTypedefs(), Translator::trVariableDocumentation(), Translator::trVariables(), DefinitionIntf::TypeFile, and writeDocbookDocBlock().
Referenced by generateDocbookForClass(), generateDocbookForFile(), generateDocbookForGroup(), and generateDocbookForNamespace().
memberOutputFileBase()
static QCString memberOutputFileBase (MemberDef * md) static
Definition at line 382 of file docbookgen.cpp.
References MemberDef::getOutputFileBase().
Referenced by generateDocbookForMember().
writeDocbookCodeBlock()
void writeDocbookCodeBlock (FTextStream & t, FileDef * fd)
Definition at line 350 of file docbookgen.cpp.
References FileDef::absFilePath(), Config_getBool, fileToString(), DocbookCodeGenerator::finish(), Definition::getDefFileExtension(), getLanguageFromFileName(), ParserManager::getParser(), ParserInterface::parseCode(), Doxygen::parserManager, and ParserInterface::resetCodeParserState().
Referenced by generateDocbookForFile().
writeDocbookCodeString()
void writeDocbookCodeString (FTextStream & t, const char * s, int & col) inline
Definition at line 110 of file docbookgen.cpp.
References Config_getInt.
Referenced by DocbookCodeGenerator::codify().
writeDocbookDocBlock()
static void writeDocbookDocBlock (FTextStream & t, const QCString & fileName, int lineNr, Definition * scope, MemberDef * md, const QCString & text) static
Definition at line 327 of file docbookgen.cpp.
References DocNode::accept(), and validatingParseDoc().
Referenced by generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForMember(), generateDocbookForNamespace(), generateDocbookForPage(), and generateDocbookSection().
writeDocbookHeader_ID()
static void writeDocbookHeader_ID (FTextStream & t, QCString id) static
Definition at line 142 of file docbookgen.cpp.
References endl().
Referenced by generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForNamespace(), and generateDocbookForPage().
writeDocbookHeaderMainpage()
static void writeDocbookHeaderMainpage (FTextStream & t) static
Definition at line 136 of file docbookgen.cpp.
References endl().
Referenced by generateDocbookForPage().
writeDocbookLink()
void writeDocbookLink (FTextStream & t, const char * , const char * compoundId, const char * anchorId, const char * text, const char *)
Definition at line 148 of file docbookgen.cpp.
References writeDocbookString().
Referenced by DocbookCodeGenerator::writeCodeLink(), and TextGeneratorDocbookImpl::writeLink().
writeDocbookString()
void writeDocbookString (FTextStream & t, const char * s) inline
Definition at line 105 of file docbookgen.cpp.
References convertToXML().
Referenced by generateDocbookForClass(), generateDocbookForFile(), generateDocbookForMember(), generateDocbookForNamespace(), writeDocbookLink(), writeInnerClasses(), and TextGeneratorDocbookImpl::writeString().
writeInnerClasses()
static void writeInnerClasses (const ClassSDict * cl, FTextStream & t) static
Definition at line 916 of file docbookgen.cpp.
References Definition::briefDescription(), classOutputFileBase(), convertToXML(), endl(), Definition::isHidden(), SDict< ClassDef >::Iterator, Definition::name(), theTranslator, Translator::trClasses(), and writeDocbookString().
Referenced by generateDocbookForClass(), generateDocbookForFile(), generateDocbookForGroup(), and generateDocbookForNamespace().
writeInnerDirs()
static void writeInnerDirs (const DirList * dl, FTextStream & t) static
Definition at line 1067 of file docbookgen.cpp.
References convertToXML(), DirDef::displayName(), endl(), DirDef::getOutputFileBase(), theTranslator, and Translator::trDirectories().
Referenced by generateDocbookForDir().
writeInnerFiles()
static void writeInnerFiles (const FileList * fl, FTextStream & t) static
Definition at line 990 of file docbookgen.cpp.
References convertToXML(), endl(), FileDef::getOutputFileBase(), FileDef::name(), theTranslator, and Translator::trFile().
Referenced by generateDocbookForDir(), and generateDocbookForGroup().
writeInnerGroupFiles()
static void writeInnerGroupFiles (const GroupList * gl, FTextStream & t) static
Definition at line 1097 of file docbookgen.cpp.
References endl(), and GroupDef::getOutputFileBase().
Referenced by generateDocbookForGroup().
writeInnerGroups()
static void writeInnerGroups (const GroupList * gl, FTextStream & t) static
Definition at line 1035 of file docbookgen.cpp.
References convertToXML(), endl(), GroupDef::getOutputFileBase(), GroupDef::groupTitle(), theTranslator, and Translator::trModules().
Referenced by generateDocbookForGroup().
writeInnerNamespaces()
static void writeInnerNamespaces (const NamespaceSDict * nl, FTextStream & t) static
Definition at line 956 of file docbookgen.cpp.
References convertToXML(), endl(), NamespaceDef::getOutputFileBase(), Definition::isHidden(), SDict< NamespaceDef >::Iterator, Definition::name(), theTranslator, and Translator::trNamespaces().
Referenced by generateDocbookForFile(), generateDocbookForGroup(), and generateDocbookForNamespace().
writeInnerPages()
static void writeInnerPages (const PageSDict * pl, FTextStream & t) static
Definition at line 1021 of file docbookgen.cpp.
References endl(), PageDef::getOutputFileBase(), and SDict< PageDef >::Iterator.
Referenced by generateDocbookForGroup(), and generateDocbookForPage().
writeTemplateArgumentList()
static void writeTemplateArgumentList (ArgumentList * al, FTextStream & t, Definition * scope, FileDef * fileScope, int indent) static
Definition at line 283 of file docbookgen.cpp.
References Argument::defval, endl(), linkifyText(), Argument::name, and Argument::type.
Referenced by writeTemplateList().
writeTemplateList()
static void writeTemplateList (ClassDef * cd, FTextStream & t) static
Definition at line 322 of file docbookgen.cpp.
References ClassDef::templateArguments(), and writeTemplateArgumentList().
Referenced by generateDocbookForClass().
Variable Documentation
g_docbookSectionMapper
DocbookSectionMapper g_docbookSectionMapper static
Definition at line 102 of file docbookgen.cpp.