Doxygen: ConfigContext Class Reference
ConfigContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static ConfigContext * alloc ()
Private Member Functions
ConfigContext ()
~ConfigContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 129 of file context.h.
Constructor & Destructor Documentation
ConfigContext()
ConfigContext::ConfigContext () private
Definition at line 320 of file context.cpp.
References p, and Private.
Referenced by alloc().
~ConfigContext()
ConfigContext::~ConfigContext () private
Definition at line 325 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int ConfigContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 136 of file context.h.
References RefCountedContext::addRef().
alloc()
static ConfigContext* ConfigContext::alloc () inline static
Definition at line 132 of file context.h.
References ConfigContext().
Referenced by generateOutputViaTemplate().
get()
TemplateVariant ConfigContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 330 of file context.cpp.
References ConfigContext::Private::fetchList(), and p.
release()
virtual int ConfigContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 137 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ConfigContext::p private
Definition at line 142 of file context.h.
Referenced by ConfigContext(), get(), and ~ConfigContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp