Doxygen: GroupDef Class Reference
GroupDef Class Reference
A model of a group of symbols.
#include <groupdef.h>
Public Member Functions
GroupDef (const char *fileName, int line, const char *name, const char *title, const char *refFileName=0)
~GroupDef ()
DefType definitionType () const
QCString getOutputFileBase () const
QCString anchor () const
QCString displayName (bool=TRUE) const
const char * groupTitle () const
void setGroupTitle (const char *newtitle)
bool hasGroupTitle () const
void addFile (const FileDef *def)
bool addClass (const ClassDef *def)
bool addNamespace (const NamespaceDef *def)
void addGroup (const GroupDef *def)
void addParentGroup (const GroupDef *def)
void addPage (PageDef *def)
void addExample (const PageDef *def)
void addDir (const DirDef *dd)
bool insertMember (MemberDef *def, bool docOnly=FALSE)
void removeMember (MemberDef *md)
bool findGroup (const GroupDef *def) const
void writeDocumentation (OutputList &ol)
void writeMemberPages (OutputList &ol)
void writeQuickMemberLinks (OutputList &ol, MemberDef *currentMd) const
void writeTagFile (FTextStream &)
int countMembers () const
bool isLinkableInProject () const
bool isLinkable () const
bool isASubGroup () const
void computeAnchors ()
void addMembersToMemberGroup ()
void distributeMemberGroupDocumentation ()
void findSectionsInDocumentation ()
void addListReferences ()
void sortMemberLists ()
bool subGrouping () const
void setGroupScope (Definition *d)
Definition * getGroupScope () const
MemberList * getMemberList (MemberListType lt) const
const QList< MemberList > & getMemberLists () const
MemberGroupSDict * getMemberGroupSDict () const
FileList * getFiles () const
ClassSDict * getClasses () const
NamespaceSDict * getNamespaces () const
GroupList * getSubGroups () const
PageSDict * getPages () const
DirList * getDirs () const
PageSDict * getExamples () const
bool hasDetailedDescription () const
void sortSubGroups ()
Public Member Functions inherited from Definition
Definition (const char *defFileName, int defLine, int defColumn, const char *name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~Definition ()
const QCString & name () const
QCString localName () const
virtual QCString qualifiedName () const
QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
int docLine () const
QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
bool isHidden () const
bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
QCString externalReference (const QCString &relPath) const
int getStartBodyLine () const
int getEndBodyLine () const
FileDef * getBodyDef () const
SrcLangExt getLanguage () const
Returns the programming language this definition was written in.
GroupList * partOfGroups () const
bool isLinkableViaGroup () const
QList< ListItemInfo > * xrefListItems () const
virtual Definition * findInnerCompound (const char *name)
virtual Definition * getOuterScope () const
MemberSDict * getReferencesMembers () const
MemberSDict * getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
returns TRUE if this class has a brief description
QCString id () const
virtual void setName (const char *name)
void setId (const char *name)
virtual void setDocumentation (const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const char *b, const char *briefFile, int briefLine)
virtual void setInbodyDocumentation (const char *d, const char *docFile, int docLine)
void setReference (const char *r)
void addSectionsToDefinition (QList< SectionInfo > *anchorList)
void setBodySegment (int bls, int ble)
void setBodyDef (FileDef *fd)
void addSourceReferencedBy (MemberDef *d)
void addSourceReferences (MemberDef *d)
void setRefItems (const QList< ListItemInfo > *sli)
void mergeRefItems (Definition *d)
virtual void addInnerCompound (Definition *d)
virtual void setOuterScope (Definition *d)
virtual void setHidden (bool b)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const char *scopeName)
void writeInlineCode (OutputList &ol, const char *scopeName)
void writeSourceRefs (OutputList &ol, const char *scopeName)
void writeSourceReffedBy (OutputList &ol, const char *scopeName)
void makePartOfGroup (GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
QCString pathFragment () const
void writeDocAnchorsToTagFile (FTextStream &)
void setLocalName (const QCString name)
void addSectionsToIndex ()
void writeToc (OutputList &ol)
void setCookie (Cookie *cookie)
Cookie * cookie () const
Public Member Functions inherited from DefinitionIntf
DefinitionIntf ()
virtual ~DefinitionIntf ()
Public Attributes
bool visited
Protected Member Functions
void addMemberListToGroup (MemberList *, bool(MemberDef::*)() const)
Protected Member Functions inherited from Definition
Definition (const Definition &d)
Private Member Functions
MemberList * createMemberList (MemberListType lt)
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void removeMemberFromList (MemberListType lt, MemberDef *md)
void writeGroupGraph (OutputList &ol)
void writeFiles (OutputList &ol, const QCString &title)
void writeNamespaces (OutputList &ol, const QCString &title)
void writeNestedGroups (OutputList &ol, const QCString &title)
void writeDirs (OutputList &ol, const QCString &title)
void writeClasses (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void writePageDocumentation (OutputList &ol)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void writeSummaryLinks (OutputList &ol)
void updateLanguage (const Definition *)
Private Attributes
QCString title
bool titleSet
QCString fileName
FileList * fileList
ClassSDict * classSDict
NamespaceSDict * namespaceSDict
GroupList * groupList
PageSDict * pageDict
PageSDict * exampleDict
DirList * dirList
MemberList * allMemberList
MemberNameInfoSDict * allMemberNameInfoSDict
Definition * groupScope
QList< MemberList > m_memberLists
MemberGroupSDict * memberGroupSDict
bool m_subGrouping
Additional Inherited Members
Public Types inherited from DefinitionIntf
enum DefType {
TypeClass = 0, TypeFile = 1, TypeNamespace = 2, TypeMember = 3,
TypeGroup = 4, TypePackage = 5, TypePage = 6, TypeDir = 7,
TypeSymbolList = 8
}
Detailed Description
A model of a group of symbols.
Definition at line 45 of file groupdef.h.
Constructor & Destructor Documentation
GroupDef()
GroupDef::GroupDef (const char * fileName, int line, const char * name, const char * title, const char * refFileName = 0)
Definition at line 46 of file groupdef.cpp.
References allMemberList, allMemberNameInfoSDict, classSDict, Config_getBool, convertNameToFile(), dirList, exampleDict, fileList, fileName, groupList, groupScope, m_subGrouping, memberGroupSDict, MemberListType_allMembersList, namespaceSDict, pageDict, SDict< T >::setAutoDelete(), SIntDict< T >::setAutoDelete(), setGroupTitle(), stripExtension(), and visited.
~GroupDef()
GroupDef::~GroupDef ()
Definition at line 77 of file groupdef.cpp.
References allMemberList, allMemberNameInfoSDict, classSDict, dirList, exampleDict, fileList, groupList, memberGroupSDict, namespaceSDict, and pageDict.
Member Function Documentation
addClass()
bool GroupDef::addClass (const ClassDef * def)
Definition at line 149 of file groupdef.cpp.
References SDict< T >::append(), SDict< T >::at(), classSDict, Config_getBool, SDict< T >::count(), SDict< T >::find(), SDict< T >::findAt(), SDict< T >::insertAt(), SDict< T >::inSort(), Definition::isHidden(), Definition::name(), Definition::qualifiedName(), and updateLanguage().
Referenced by addClassToGroups(), createTagLessInstance(), distributeClassGroupRelations(), and ClassDef::setGroupDefForAllMembers().
addDir()
void GroupDef::addDir (const DirDef * dd)
Definition at line 213 of file groupdef.cpp.
References Config_getBool, dirList, and Definition::isHidden().
Referenced by addDirToGroups().
addExample()
void GroupDef::addExample (const PageDef * def)
Definition at line 230 of file groupdef.cpp.
References SDict< T >::append(), exampleDict, Definition::isHidden(), and Definition::name().
Referenced by addExampleToGroups().
addFile()
void GroupDef::addFile (const FileDef * def)
Definition at line 138 of file groupdef.cpp.
References Config_getBool, fileList, Definition::isHidden(), and updateLanguage().
Referenced by buildFileList().
addGroup()
void GroupDef::addGroup (const GroupDef * def)
Definition at line 532 of file groupdef.cpp.
References groupList.
Referenced by addDirsAsGroups(), and addGroupToGroups().
addListReferences()
void GroupDef::addListReferences ()
Definition at line 1527 of file groupdef.cpp.
References MemberList::addListReferences(), MemberGroup::addListReferences(), addRefItem(), getOutputFileBase(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_memberLists, memberGroupSDict, MemberListType_documentationLists, Definition::name(), theTranslator, Translator::trGroup(), and Definition::xrefListItems().
Referenced by addListReferences().
addMemberListToGroup()
void GroupDef::addMemberListToGroup (MemberList * , bool(MemberDef::*)() const) protected
addMembersToMemberGroup()
void GroupDef::addMembersToMemberGroup ()
Definition at line 237 of file groupdef.cpp.
References SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_memberLists, memberGroupSDict, MemberListType_declarationLists, and MemberGroup::setInGroup().
Referenced by addMembersToMemberGroup().
addMemberToList()
void GroupDef::addMemberToList (MemberListType lt, MemberDef * md) private
Definition at line 1575 of file groupdef.cpp.
References MemberList::append(), Config_getBool, createMemberList(), MemberList::listType(), MemberListType_declarationLists, MemberListType_documentationLists, and MemberList::setNeedsSorting().
Referenced by insertMember().
addNamespace()
bool GroupDef::addNamespace (const NamespaceDef * def)
Definition at line 197 of file groupdef.cpp.
References SDict< T >::append(), Config_getBool, SDict< T >::find(), SDict< T >::inSort(), Definition::isHidden(), Definition::name(), namespaceSDict, and updateLanguage().
Referenced by addNamespaceToGroups(), and findUsingDirectives().
addPage()
void GroupDef::addPage (PageDef * def)
Definition at line 222 of file groupdef.cpp.
References SDict< T >::append(), Definition::isHidden(), Definition::makePartOfGroup(), Definition::name(), and pageDict.
Referenced by addRelatedPage().
addParentGroup()
void GroupDef::addParentGroup (const GroupDef * def)
anchor()
QCString GroupDef::anchor () const inline virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 52 of file groupdef.h.
Referenced by writeDocumentation().
computeAnchors()
void GroupDef::computeAnchors ()
Compute the HTML anchor names for all members in the group
Definition at line 559 of file groupdef.cpp.
References allMemberList, and setAnchors().
Referenced by computeMemberReferences().
countMembers()
int GroupDef::countMembers () const
Definition at line 547 of file groupdef.cpp.
References allMemberList, classSDict, MemberList::count(), SDict< T >::count(), exampleDict, fileList, groupList, namespaceSDict, and pageDict.
Referenced by writeDetailedDescription().
createMemberList()
MemberList * GroupDef::createMemberList (MemberListType lt) private
Definition at line 1556 of file groupdef.cpp.
References MemberList::listType(), m_memberLists, and MemberList::setInGroup().
Referenced by addMemberToList().
definitionType()
DefType GroupDef::definitionType () const inline virtual
Use this for dynamic inspection of the type of the derived class
Implements DefinitionIntf.
Definition at line 50 of file groupdef.h.
References DefinitionIntf::TypeGroup.
displayName()
QCString GroupDef::displayName (bool includeScope = TRUE) const inline virtual
Returns the name of the definition as it appears in the output
Implements Definition.
Definition at line 53 of file groupdef.h.
References hasGroupTitle(), Definition::name(), and title.
distributeMemberGroupDocumentation()
void GroupDef::distributeMemberGroupDocumentation ()
Definition at line 107 of file groupdef.cpp.
References MemberGroup::distributeMemberGroupDocumentation(), SIntDict< MemberGroup >::Iterator, and memberGroupSDict.
Referenced by distributeMemberGroupDocumentation().
endMemberDeclarations()
void GroupDef::endMemberDeclarations (OutputList & ol) private
Definition at line 1001 of file groupdef.cpp.
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDocumentation()
void GroupDef::endMemberDocumentation (OutputList & ol) private
Definition at line 1017 of file groupdef.cpp.
References Config_getBool, OutputList::popGeneratorState(), and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
findGroup()
bool GroupDef::findGroup (const GroupDef * def) const
Definition at line 511 of file groupdef.cpp.
References findGroup(), and groupList.
Referenced by addGroupToGroups(), and findGroup().
findSectionsInDocumentation()
void GroupDef::findSectionsInDocumentation ()
Definition at line 117 of file groupdef.cpp.
References Definition::docFile(), docFindSections(), Definition::documentation(), MemberGroup::findSectionsInDocumentation(), MemberList::findSectionsInDocumentation(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_memberLists, memberGroupSDict, and MemberListType_declarationLists.
Referenced by findSectionsInDocumentation().
getClasses()
ClassSDict* GroupDef::getClasses () const inline
Definition at line 101 of file groupdef.h.
References classSDict.
Referenced by DotGroupCollaboration::buildGraph(), ModuleContext::Private::classes(), generateDocbookForGroup(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), ModuleContext::Private::inlineClasses(), and writeGroupTreeNode().
getDirs()
DirList* GroupDef::getDirs () const inline
Definition at line 105 of file groupdef.h.
References dirList.
Referenced by DotGroupCollaboration::buildGraph(), ModuleContext::Private::dirs(), and writeGroupTreeNode().
getExamples()
PageSDict* GroupDef::getExamples () const inline
Definition at line 106 of file groupdef.h.
References exampleDict.
Referenced by ModuleContext::Private::examples(), and ModuleContext::Private::pages().
getFiles()
FileList* GroupDef::getFiles () const inline
Definition at line 100 of file groupdef.h.
References fileList.
Referenced by DotGroupCollaboration::buildGraph(), ModuleContext::Private::files(), generateDocbookForGroup(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), and writeGroupTreeNode().
getGroupScope()
Definition* GroupDef::getGroupScope () const inline
Definition at line 92 of file groupdef.h.
References groupScope.
getMemberGroupSDict()
MemberGroupSDict* GroupDef::getMemberGroupSDict () const inline
Definition at line 98 of file groupdef.h.
References memberGroupSDict.
Referenced by generateDocbookForGroup(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), and ModuleContext::Private::memberGroups().
getMemberList()
MemberList * GroupDef::getMemberList (MemberListType lt) const
Definition at line 1596 of file groupdef.cpp.
References MemberList::listType(), and m_memberLists.
Referenced by DotGroupCollaboration::buildGraph(), PerlModGenerator::generatePerlModForGroup(), ModuleContext::Private::getMemberList(), removeMemberFromList(), writeGroupTreeNode(), writeMemberDeclarations(), writeMemberDocumentation(), writeSummaryLinks(), and writeTagFile().
getMemberLists()
const QList<MemberList>& GroupDef::getMemberLists () const inline
Definition at line 95 of file groupdef.h.
References m_memberLists.
Referenced by generateDocbookForGroup(), generateXMLForGroup(), and writeGroupTreeNode().
getNamespaces()
NamespaceSDict* GroupDef::getNamespaces () const inline
Definition at line 102 of file groupdef.h.
References namespaceSDict.
Referenced by DotGroupCollaboration::buildGraph(), ModuleContext::Private::constantgroups(), generateDocbookForGroup(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), ModuleContext::Private::namespaces(), and writeGroupTreeNode().
getOutputFileBase()
QCString GroupDef::getOutputFileBase () const virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements Definition.
Definition at line 1522 of file groupdef.cpp.
References fileName.
Referenced by addListReferences(), addListReferences(), addRelatedPage(), DotGroupCollaboration::buildGraph(), DotGroupCollaboration::DotGroupCollaboration(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateDocbookForGroup(), generateDocbookForMember(), generateXMLForGroup(), generateXMLForMember(), PageDef::getOutputFileBase(), MemberDef::getOutputFileBase(), ModuleContext::Private::groupGraph(), recursivelyAddGroupListToTitle(), resolveUserReferences(), writeDocumentation(), writeGroupTreeNode(), writeInnerGroupFiles(), writeInnerGroups(), MemberDef::writeLink(), writeNestedGroups(), and writeTagFile().
getPages()
PageSDict* GroupDef::getPages () const inline
Definition at line 104 of file groupdef.h.
References pageDict.
Referenced by DotGroupCollaboration::buildGraph(), generateDocbookForGroup(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), ModuleContext::Private::pages(), and writeGroupTreeNode().
getSubGroups()
GroupList* GroupDef::getSubGroups () const inline
Definition at line 103 of file groupdef.h.
References groupList.
Referenced by NestingNodeContext::Private::addModules(), DotGroupCollaboration::buildGraph(), generateDocbookForGroup(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), ModuleContext::Private::modules(), and writeGroupTreeNode().
groupTitle()
const char* GroupDef::groupTitle () const inline
Definition at line 54 of file groupdef.h.
References title.
Referenced by DotGroupCollaboration::buildGraph(), buildGroupListFiltered(), GroupSDict::compareValues(), GroupList::compareValues(), createJavascriptSearchIndex(), DotGroupCollaboration::DotGroupCollaboration(), generateDocbookForGroup(), PerlModGenerator::generatePerlModForGroup(), generateXMLForGroup(), recursivelyAddGroupListToTitle(), SearchIndex::setCurrentDoc(), ModuleContext::Private::title(), validatingParseDoc(), writeGroupTreeNode(), writeInnerGroups(), and writeNestedGroups().
hasDetailedDescription()
bool GroupDef::hasDetailedDescription () const
Definition at line 1663 of file groupdef.cpp.
References Definition::briefDescription(), Config_getBool, and Definition::documentation().
Referenced by ModuleContext::Private::hasDetails().
hasGroupTitle()
bool GroupDef::hasGroupTitle () const inline
Definition at line 56 of file groupdef.h.
References titleSet.
Referenced by buildGroupListFiltered(), and displayName().
insertMember()
bool GroupDef::insertMember (MemberDef * def, bool docOnly = FALSE)
Definition at line 259 of file groupdef.cpp.
References addMemberToList(), allMemberList, allMemberNameInfoSDict, MemberList::append(), SDict< T >::append(), MemberDef::argumentList(), DefinitionIntf::definitionType(), err(), MemberDef::getClassDef(), MemberDef::getFileDef(), MemberDef::getGroupAlias(), Definition::getOuterScope(), MemberDef::isFunction(), Definition::isHidden(), matchArguments2(), MemberInfo::memberDef, MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decEnumValMembers, MemberListType_decEventMembers, MemberListType_decFriendMembers, MemberListType_decFuncMembers, MemberListType_decPriSlotMembers, MemberListType_decPropMembers, MemberListType_decProSlotMembers, MemberListType_decPubSlotMembers, MemberListType_decSignalMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docEnumMembers, MemberListType_docEnumValMembers, MemberListType_docEventMembers, MemberListType_docFriendMembers, MemberListType_docFuncMembers, MemberListType_docPriSlotMembers, MemberListType_docPropMembers, MemberListType_docProSlotMembers, MemberListType_docPubSlotMembers, MemberListType_docSignalMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberNameInfo::memberName(), MemberDef::memberType(), MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Property, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Definition::name(), Protected, MemberDef::protection(), Public, MemberDef::setGroupAlias(), MemberDef::templateArguments(), DefinitionIntf::TypeFile, updateLanguage(), and MemberDef::virtualness().
Referenced by addMemberToGroups(), MemberGroup::insertMember(), and ClassDef::setGroupDefForAllMembers().
isASubGroup()
bool GroupDef::isASubGroup () const
Definition at line 541 of file groupdef.cpp.
References Definition::partOfGroups().
Referenced by NestingContext::Private::addModules(), generateDocbookForGroup(), and writeGroupTreeNode().
isLinkable()
bool GroupDef::isLinkable () const virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements Definition.
Definition at line 1648 of file groupdef.cpp.
References Definition::hasUserDocumentation().
Referenced by addMemberToSearchIndex(), createJavascriptSearchIndex(), findMembersWithSpecificName(), getDefs(), isLinkableInProject(), and Definition::isLinkableViaGroup().
isLinkableInProject()
bool GroupDef::isLinkableInProject () const virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements Definition.
Definition at line 1643 of file groupdef.cpp.
References isLinkable(), and Definition::isReference().
Referenced by MemberDef::_computeLinkableInProject(), and writeTagFile().
removeMember()
void GroupDef::removeMember (MemberDef * md)
Definition at line 424 of file groupdef.cpp.
References allMemberNameInfoSDict, err(), SDict< T >::find(), MemberListType_allMembersList, MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decEnumValMembers, MemberListType_decEventMembers, MemberListType_decFriendMembers, MemberListType_decFuncMembers, MemberListType_decPriSlotMembers, MemberListType_decPropMembers, MemberListType_decProSlotMembers, MemberListType_decPubSlotMembers, MemberListType_decSignalMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docEnumMembers, MemberListType_docEnumValMembers, MemberListType_docEventMembers, MemberListType_docFriendMembers, MemberListType_docFuncMembers, MemberListType_docPriSlotMembers, MemberListType_docPropMembers, MemberListType_docProSlotMembers, MemberListType_docPubSlotMembers, MemberListType_docSignalMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Property, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Definition::name(), Protected, MemberDef::protection(), Public, SDict< T >::remove(), and removeMemberFromList().
Referenced by addMemberToGroups().
removeMemberFromList()
void GroupDef::removeMemberFromList (MemberListType lt, MemberDef * md) private
Definition at line 1632 of file groupdef.cpp.
References getMemberList(), and MemberList::remove().
Referenced by removeMember().
setGroupScope()
void GroupDef::setGroupScope (Definition * d) inline
Definition at line 91 of file groupdef.h.
References groupScope.
Referenced by findGroupScope().
setGroupTitle()
void GroupDef::setGroupTitle (const char * newtitle)
Definition at line 91 of file groupdef.cpp.
References Definition::name(), title, and titleSet.
Referenced by buildGroupListFiltered(), and GroupDef().
sortMemberLists()
void GroupDef::sortMemberLists ()
Definition at line 1586 of file groupdef.cpp.
References m_memberLists, MemberList::needsSorting(), MemberList::setNeedsSorting(), and MemberList::sort().
Referenced by sortMemberLists().
sortSubGroups()
void GroupDef::sortSubGroups ()
Definition at line 1638 of file groupdef.cpp.
References groupList.
Referenced by generateOutput().
startMemberDeclarations()
void GroupDef::startMemberDeclarations (OutputList & ol) private
Definition at line 996 of file groupdef.cpp.
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDocumentation()
void GroupDef::startMemberDocumentation (OutputList & ol) private
Definition at line 1006 of file groupdef.cpp.
References Config_getBool, OutputList::disable(), OutputGenerator::Html, OutputList::pushGeneratorState(), and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
subGrouping()
bool GroupDef::subGrouping () const inline
Definition at line 84 of file groupdef.h.
References m_subGrouping.
Referenced by ModuleContext::Private::memberGroups().
updateLanguage()
void GroupDef::updateLanguage (const Definition * d) private
Definition at line 1655 of file groupdef.cpp.
References Definition::getLanguage(), Definition::setLanguage(), and SrcLangExt_Unknown.
Referenced by addClass(), addFile(), addNamespace(), and insertMember().
writeAuthorSection()
void GroupDef::writeAuthorSection (OutputList & ol) private
Definition at line 1027 of file groupdef.cpp.
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), and Translator::trGeneratedAutomatically().
Referenced by writeDocumentation().
writeBriefDescription()
void GroupDef::writeBriefDescription (OutputList & ol) private
Definition at line 769 of file groupdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), Definition::documentation(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), Definition::hasBriefDescription(), OutputGenerator::Html, DocRoot::isEmpty(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeClasses()
void GroupDef::writeClasses (OutputList & ol, const QCString & title) private
Definition at line 946 of file groupdef.cpp.
References classSDict, and ClassSDict::writeDeclaration().
Referenced by writeDocumentation().
writeDetailedDescription()
void GroupDef::writeDetailedDescription (OutputList & ol, const QCString & title) private
Definition at line 708 of file groupdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, SDict< T >::count(), countMembers(), OutputList::disable(), OutputList::disableAllBut(), Definition::docFile(), Definition::docLine(), Definition::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), OutputList::generateDoc(), OutputGenerator::Html, Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), OutputGenerator::Latex, OutputGenerator::Man, pageDict, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startGroupHeader(), OutputList::writeAnchor(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDirs()
void GroupDef::writeDirs (OutputList & ol, const QCString & title) private
Definition at line 913 of file groupdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, dirList, OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), OutputList::generateDoc(), DirDef::getOutputFileBase(), Definition::getReference(), Definition::hasDocumentation(), OutputList::insertMemberAlign(), OutputList::parseText(), DirDef::shortName(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trDir(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeDocumentation()
void GroupDef::writeDocumentation (OutputList & ol)
Definition at line 1084 of file groupdef.cpp.
References addGroupListToTitle(), IndexList::addIndexItem(), SearchIndexIntf::addWord(), allMemberList, anchor(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::disable(), OutputList::disableAllBut(), endFile(), OutputList::endHeaderSection(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endTitleHead(), err(), LayoutDocEntry::FileClasses, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, Definition::getLanguage(), getOutputFileBase(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, HLI_Modules, Doxygen::indexList, LayoutDocManager::instance(), LayoutDocEntry::kind(), OutputGenerator::Man, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, Definition::name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), Doxygen::searchIndex, SearchIndexIntf::setCurrentDoc(), MemberList::sort(), OutputList::startContents(), startFile(), OutputList::startHeaderSection(), startMemberDeclarations(), startMemberDocumentation(), OutputList::startTitleHead(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), title, LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClasses(), writeDetailedDescription(), writeDirs(), writeFiles(), writeGroupGraph(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeMemberPages(), writeNamespaces(), writeNestedGroups(), writePageDocumentation(), and writeSummaryLinks().
Referenced by generateGroupDocs().
writeFiles()
void GroupDef::writeFiles (OutputList & ol, const QCString & title) private
Definition at line 825 of file groupdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::docify(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), fileList, OutputList::generateDoc(), FileDef::getOutputFileBase(), Definition::getReference(), Definition::hasDocumentation(), OutputList::insertMemberAlign(), FileDef::name(), OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trFile(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeGroupGraph()
void GroupDef::writeGroupGraph (OutputList & ol) private
Definition at line 805 of file groupdef.cpp.
References Config_getBool, OutputList::disable(), OutputList::endGroupCollaboration(), DotGroupCollaboration::isTrivial(), OutputGenerator::Man, msg(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), Definition::qualifiedName(), OutputList::startGroupCollaboration(), theTranslator, title, and Translator::trCollaborationDiagram().
Referenced by writeDocumentation().
writeInlineClasses()
void GroupDef::writeInlineClasses (OutputList & ol) private
Definition at line 952 of file groupdef.cpp.
References classSDict, and ClassSDict::writeDocumentation().
Referenced by writeDocumentation().
writeMemberDeclarations()
void GroupDef::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1610 of file groupdef.cpp.
References Config_getBool, getMemberList(), MemberList::writeDeclarations(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by writeDocumentation().
writeMemberDocumentation()
void GroupDef::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1626 of file groupdef.cpp.
References getMemberList(), Definition::name(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberGroups()
void GroupDef::writeMemberGroups (OutputList & ol) private
Definition at line 980 of file groupdef.cpp.
References SIntDict< MemberGroup >::Iterator, memberGroupSDict, SIntDict< T >::sort(), and MemberGroup::writeDeclarations().
Referenced by writeDocumentation().
writeMemberPages()
void GroupDef::writeMemberPages (OutputList & ol)
Definition at line 1255 of file groupdef.cpp.
References OutputList::disableAllBut(), OutputGenerator::Html, MemberList::listType(), m_memberLists, MemberListType_documentationLists, Definition::name(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), and MemberList::writeDocumentationPage().
Referenced by writeDocumentation().
writeNamespaces()
void GroupDef::writeNamespaces (OutputList & ol, const QCString & title) private
Definition at line 857 of file groupdef.cpp.
References namespaceSDict, and NamespaceSDict::writeDeclaration().
Referenced by writeDocumentation().
writeNestedGroups()
void GroupDef::writeNestedGroups (OutputList & ol, const QCString & title) private
Definition at line 863 of file groupdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), OutputList::endMemberList(), OutputList::generateDoc(), getOutputFileBase(), Definition::getReference(), groupList, groupTitle(), Definition::hasDocumentation(), OutputList::insertMemberAlign(), Definition::isVisible(), OutputList::parseText(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writePageDocumentation()
void GroupDef::writePageDocumentation (OutputList & ol) private
Definition at line 957 of file groupdef.cpp.
References Definition::docFile(), OutputList::docify(), Definition::docLine(), Definition::documentation(), OutputList::endSection(), OutputList::endTextBlock(), SDict< T >::find(), OutputList::generateDoc(), Definition::inbodyDocumentation(), Definition::isReference(), SDict< PageDef >::Iterator, SectionInfo::label, Definition::name(), pageDict, Doxygen::sectionDict, OutputList::startSection(), OutputList::startTextBlock(), SectionInfo::Subsection, PageDef::title(), and SectionInfo::title.
Referenced by writeDocumentation().
writeQuickMemberLinks()
void GroupDef::writeQuickMemberLinks (OutputList & ol, MemberDef * currentMd) const virtual
Reimplemented from Definition.
Definition at line 1273 of file groupdef.cpp.
References allMemberList, MemberDef::anchor(), Config_getBool, convertToHtml(), createSubDirs(), MemberDef::getGroupDef(), MemberDef::getOutputFileBase(), Doxygen::htmlFileExtension, MemberDef::isEnumValue(), MemberDef::isLinkable(), MemberDef::isLinkableInProject(), Definition::localName(), and OutputList::writeString().
writeSummaryLinks()
void GroupDef::writeSummaryLinks (OutputList & ol) private virtual
Reimplemented from Definition.
Definition at line 1039 of file groupdef.cpp.
References classSDict, ClassSDict::declVisible(), MemberList::declVisible(), NamespaceSDict::declVisible(), dirList, OutputList::disableAllBut(), fileList, Definition::getLanguage(), getMemberList(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, groupList, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, OutputGenerator::Html, LayoutDocManager::instance(), LayoutDocEntry::kind(), MemberList::listType(), MemberList::listTypeAsString(), LayoutDocEntry::MemberDecl, namespaceSDict, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
Referenced by writeDocumentation().
writeTagFile()
void GroupDef::writeTagFile (FTextStream & tagFile)
Definition at line 565 of file groupdef.cpp.
References classSDict, ClassDef::compoundTypeString(), convertToXML(), dirList, DirDef::displayName(), endl(), fileList, getMemberList(), getOutputFileBase(), PageDef::getOutputFileBase(), LayoutDocManager::Group, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, groupList, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, Doxygen::htmlFileExtension, LayoutDocManager::instance(), PageDef::isLinkableInProject(), DirDef::isLinkableInProject(), NamespaceDef::isLinkableInProject(), FileDef::isLinkableInProject(), ClassDef::isLinkableInProject(), Definition::isVisible(), SDict< PageDef >::Iterator, SIntDict< MemberGroup >::Iterator, LayoutDocEntry::kind(), LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, memberGroupSDict, FileDef::name(), Definition::name(), namespaceSDict, pageDict, title, LayoutDocEntryMemberDecl::type, Definition::writeDocAnchorsToTagFile(), MemberGroup::writeTagFile(), and MemberList::writeTagFile().
Referenced by writeTagFile().
Member Data Documentation
allMemberList
MemberList* GroupDef::allMemberList private
Definition at line 150 of file groupdef.h.
Referenced by computeAnchors(), countMembers(), GroupDef(), insertMember(), writeDocumentation(), writeQuickMemberLinks(), and ~GroupDef().
allMemberNameInfoSDict
MemberNameInfoSDict* GroupDef::allMemberNameInfoSDict private
Definition at line 151 of file groupdef.h.
Referenced by GroupDef(), insertMember(), removeMember(), and ~GroupDef().
classSDict
ClassSDict* GroupDef::classSDict private
Definition at line 143 of file groupdef.h.
Referenced by addClass(), countMembers(), getClasses(), GroupDef(), writeClasses(), writeInlineClasses(), writeSummaryLinks(), writeTagFile(), and ~GroupDef().
dirList
DirList* GroupDef::dirList private
Definition at line 148 of file groupdef.h.
Referenced by addDir(), getDirs(), GroupDef(), writeDirs(), writeSummaryLinks(), writeTagFile(), and ~GroupDef().
exampleDict
PageSDict* GroupDef::exampleDict private
Definition at line 147 of file groupdef.h.
Referenced by addExample(), countMembers(), getExamples(), GroupDef(), and ~GroupDef().
fileList
FileList* GroupDef::fileList private
Definition at line 142 of file groupdef.h.
Referenced by addFile(), countMembers(), getFiles(), GroupDef(), writeFiles(), writeSummaryLinks(), writeTagFile(), and ~GroupDef().
fileName
QCString GroupDef::fileName private
Definition at line 141 of file groupdef.h.
Referenced by getOutputFileBase(), and GroupDef().
groupList
GroupList* GroupDef::groupList private
Definition at line 145 of file groupdef.h.
Referenced by addGroup(), countMembers(), findGroup(), getSubGroups(), GroupDef(), sortSubGroups(), writeNestedGroups(), writeSummaryLinks(), writeTagFile(), and ~GroupDef().
groupScope
Definition* GroupDef::groupScope private
Definition at line 153 of file groupdef.h.
Referenced by getGroupScope(), GroupDef(), and setGroupScope().
m_memberLists
QList<MemberList> GroupDef::m_memberLists private
Definition at line 155 of file groupdef.h.
Referenced by addListReferences(), addMembersToMemberGroup(), createMemberList(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), sortMemberLists(), and writeMemberPages().
m_subGrouping
bool GroupDef::m_subGrouping private
Definition at line 157 of file groupdef.h.
Referenced by GroupDef(), and subGrouping().
memberGroupSDict
MemberGroupSDict* GroupDef::memberGroupSDict private
Definition at line 156 of file groupdef.h.
Referenced by addListReferences(), addMembersToMemberGroup(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), getMemberGroupSDict(), GroupDef(), writeMemberGroups(), writeTagFile(), and ~GroupDef().
namespaceSDict
NamespaceSDict* GroupDef::namespaceSDict private
Definition at line 144 of file groupdef.h.
Referenced by addNamespace(), countMembers(), getNamespaces(), GroupDef(), writeNamespaces(), writeSummaryLinks(), writeTagFile(), and ~GroupDef().
pageDict
PageSDict* GroupDef::pageDict private
Definition at line 146 of file groupdef.h.
Referenced by addPage(), countMembers(), getPages(), GroupDef(), writeDetailedDescription(), writePageDocumentation(), writeTagFile(), and ~GroupDef().
title
QCString GroupDef::title private
Definition at line 139 of file groupdef.h.
Referenced by displayName(), groupTitle(), setGroupTitle(), writeDocumentation(), writeGroupGraph(), and writeTagFile().
titleSet
bool GroupDef::titleSet private
Definition at line 140 of file groupdef.h.
Referenced by hasGroupTitle(), and setGroupTitle().
visited
bool GroupDef::visited
Definition at line 86 of file groupdef.h.
Referenced by countGroups(), and GroupDef().
The documentation for this class was generated from the following files:
src/groupdef.h
src/groupdef.cpp