Doxygen: GrowBuf Class Reference
GrowBuf Class Reference
Class representing a string buffer optimised for growing.
#include <growbuf.h>
Public Member Functions
GrowBuf ()
~GrowBuf ()
void clear ()
void addChar (char c)
void addStr (const char *s)
void addStr (const char *s, int n)
const char * get ()
int getPos () const
char at (int i) const
Private Attributes
char * str
int pos
int len
Detailed Description
Class representing a string buffer optimised for growing.
Definition at line 10 of file growbuf.h.
Constructor & Destructor Documentation
GrowBuf()
GrowBuf::GrowBuf () inline
Definition at line 13 of file growbuf.h.
~GrowBuf()
GrowBuf::~GrowBuf () inline
Definition at line 14 of file growbuf.h.
References len, pos, and str.
Member Function Documentation
addChar()
void GrowBuf::addChar (char c) inline
Definition at line 16 of file growbuf.h.
References GROW_AMOUNT, len, pos, and str.
Referenced by SearchIndexExternal::addWord(), convertCharEntitiesToUTF8(), convertToHtml(), convertToId(), convertToJSString(), convertToXML(), detab(), escapeCharsInString(), escapeSpecialChars(), processBlocks(), processCopyDoc(), processMarkdown(), processQuotations(), processSpecialCommand(), SearchIndexExternal::write(), and writeTableBlock().
addStr() [1/2]
void GrowBuf::addStr (const char * s) inline
Definition at line 19 of file growbuf.h.
References GROW_AMOUNT, len, pos, and str.
Referenced by SearchIndexExternal::addWord(), convertCharEntitiesToUTF8(), convertToHtml(), convertToId(), convertToJSString(), convertToXML(), escapeCharsInString(), findEndOfLine(), processBlocks(), processCodeSpan(), processCopyDoc(), processEmphasis1(), processEmphasis2(), processEmphasis3(), processHtmlTag(), processInline(), processLink(), processNmdash(), processQuotations(), processQuoted(), processSpecialCommand(), writeBlockQuote(), writeCodeBlock(), writeFencedCodeBlock(), writeOneLineHeaderOrRuler(), and writeTableBlock().
addStr() [2/2]
void GrowBuf::addStr (const char * s, int n) inline
Definition at line 28 of file growbuf.h.
References GROW_AMOUNT, len, pos, and str.
at()
char GrowBuf::at (int i) const inline
Definition at line 40 of file growbuf.h.
References str.
clear()
void GrowBuf::clear () inline
Definition at line 15 of file growbuf.h.
References pos.
Referenced by convertCharEntitiesToUTF8(), convertToHtml(), convertToId(), convertToJSString(), convertToXML(), escapeCharsInString(), and processMarkdown().
get()
const char* GrowBuf::get () inline
Definition at line 38 of file growbuf.h.
References str.
Referenced by convertCharEntitiesToUTF8(), convertToHtml(), convertToId(), convertToJSString(), convertToXML(), detab(), escapeCharsInString(), escapeSpecialChars(), processBlocks(), processCopyDoc(), processMarkdown(), processQuotations(), and SearchIndexExternal::write().
getPos()
int GrowBuf::getPos () const inline
Definition at line 39 of file growbuf.h.
References pos.
Referenced by SearchIndexExternal::addWord(), and processCopyDoc().
Member Data Documentation
len
int GrowBuf::len private
Definition at line 44 of file growbuf.h.
Referenced by addChar(), addStr(), and ~GrowBuf().
pos
int GrowBuf::pos private
Definition at line 43 of file growbuf.h.
Referenced by addChar(), addStr(), clear(), getPos(), and ~GrowBuf().
str
char* GrowBuf::str private
Definition at line 42 of file growbuf.h.
Referenced by addChar(), addStr(), at(), get(), and ~GrowBuf().
The documentation for this class was generated from the following file:
src/growbuf.h