Doxygen: DirListContext Class Reference
DirListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static DirListContext * alloc ()
Private Member Functions
DirListContext ()
~DirListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 626 of file context.h.
Constructor & Destructor Documentation
DirListContext()
DirListContext::DirListContext () private
Definition at line 7082 of file context.cpp.
References p, and Private.
Referenced by alloc().
~DirListContext()
DirListContext::~DirListContext () private
Definition at line 7087 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int DirListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 635 of file context.h.
References RefCountedContext::addRef().
alloc()
static DirListContext* DirListContext::alloc () inline static
Definition at line 629 of file context.h.
References DirListContext().
Referenced by generateOutputViaTemplate().
at()
TemplateVariant DirListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7098 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int DirListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 7093 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * DirListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7103 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int DirListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 636 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* DirListContext::p private
Definition at line 641 of file context.h.
Referenced by at(), count(), createIterator(), DirListContext(), and ~DirListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp