Doxygen: ClassDef Class Reference
ClassDef Class Reference
A class representing of a compound symbol.
#include <classdef.h>
Public Types
enum CompoundType {
Class, Struct, Union, Interface,
Protocol, Category, Exception, Service,
Singleton
}
The various compound types.
Public Types inherited from DefinitionIntf
enum DefType {
TypeClass = 0, TypeFile = 1, TypeNamespace = 2, TypeMember = 3,
TypeGroup = 4, TypePackage = 5, TypePage = 6, TypeDir = 7,
TypeSymbolList = 8
}
Public Member Functions
ClassDef (const char *fileName, int startLine, int startColumn, const char *name, CompoundType ct, const char *ref=0, const char *fName=0, bool isSymbol=TRUE, bool isJavaEnum=FALSE)
Creates a new compound definition.
~ClassDef ()
Destroys a compound definition.
DefType definitionType () const
Used for RTTI, this is a class.
QCString getOutputFileBase () const
Returns the unique base name (without extension) of the class's file on disk.
QCString getInstanceOutputFileBase () const
QCString getSourceFileBase () const
Returns the base name for the source code file.
QCString getReference () const
If this class originated from a tagfile, this will return the tag file reference.
bool isReference () const
Returns TRUE if this class is imported via a tag file.
bool isLocal () const
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES.
ClassSDict * getClassSDict ()
returns the classes nested into this class
bool hasDocumentation () const
returns TRUE if this class has documentation
bool hasDetailedDescription () const
returns TRUE if this class has a non-empty detailed description
QCString collaborationGraphFileName () const
returns the file name to use for the collaboration graph
QCString inheritanceGraphFileName () const
returns the file name to use for the inheritance graph
QCString displayName (bool includeScope=TRUE) const
Returns the name as it is appears in the documentation.
CompoundType compoundType () const
Returns the type of compound this is, i.e.
QCString compoundTypeString () const
Returns the type of compound as a string.
BaseClassList * baseClasses () const
Returns the list of base classes from which this class directly inherits.
BaseClassList * subClasses () const
Returns the list of sub classes that directly derive from this class.
MemberNameInfoSDict * memberNameInfoSDict () const
Returns a dictionary of all members.
Protection protection () const
Return the protection level (Public,Protected,Private) in which this compound was found.
bool isLinkableInProject () const
returns TRUE iff a link is possible to this item within this project.
bool isLinkable () const
return TRUE iff a link to this class is possible (either within this project, or as a cross-reference to another project).
bool isVisibleInHierarchy ()
the class is visible in a class diagram, or class hierarchy
bool visibleInParentsDeclList () const
show this class in the declaration section of its parent?
ArgumentList * templateArguments () const
Returns the template arguments of this class Will return 0 if not applicable.
NamespaceDef * getNamespaceDef () const
Returns the namespace this compound is in, or 0 if it has a global scope.
FileDef * getFileDef () const
Returns the file in which this compound's definition can be found.
MemberDef * getMemberByName (const QCString &) const
Returns the Java package this class is in or 0 if not applicable.
bool isBaseClass (ClassDef *bcd, bool followInstances, int level=0)
Returns TRUE iff bcd is a direct or indirect base class of this class.
bool isSubClass (ClassDef *bcd, int level=0)
Returns TRUE iff bcd is a direct or indirect sub class of this class.
bool isAccessibleMember (MemberDef *md)
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
QDict< ClassDef > * getTemplateInstances () const
Returns a sorted dictionary with all template instances found for this template class.
ClassDef * templateMaster () const
Returns the template master of which this class is an instance.
bool isTemplate () const
Returns TRUE if this class is a template.
IncludeInfo * includeInfo () const
UsesClassDict * usedImplementationClasses () const
UsesClassDict * usedByImplementationClasses () const
UsesClassDict * usedInterfaceClasses () const
ConstraintClassDict * templateTypeConstraints () const
bool isTemplateArgument () const
virtual Definition * findInnerCompound (const char *name)
Returns the definition of a nested compound if available, or 0 otherwise.
void getTemplateParameterLists (QList< ArgumentList > &lists) const
Returns the template parameter lists that form the template declaration of this class.
QCString qualifiedNameWithTemplateParameters (QList< ArgumentList > *actualParams=0, int *actualParamIndex=0) const
bool isAbstract () const
Returns TRUE if there is at least one pure virtual member in this class.
bool isObjectiveC () const
Returns TRUE if this class is implemented in Objective-C.
bool isCSharp () const
Returns TRUE if this class is implemented in C#.
bool isFinal () const
Returns TRUE if this class is marked as final.
bool isSealed () const
Returns TRUE if this class is marked as sealed.
bool isPublished () const
Returns TRUE if this class is marked as published.
bool isExtension () const
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
bool isForwardDeclared () const
Returns TRUE if this class represents a forward declaration of a template class.
ClassDef * categoryOf () const
Returns the class of which this is a category (Objective-C only)
QCString className () const
Returns the name of the class including outer classes, but not including namespaces.
MemberList * getMemberList (MemberListType lt)
Returns the members in the list identified by lt.
const QList< MemberList > & getMemberLists () const
Returns the list containing the list of members sorted per type.
MemberGroupSDict * getMemberGroupSDict () const
Returns the member groups defined for this class.
QDict< int > * getTemplateBaseClassNames () const
ClassDef * getVariableInstance (const char *templSpec)
bool isUsedOnly () const
QCString anchor () const
bool isEmbeddedInOuterScope () const
bool isSimple () const
const ClassList * taggedInnerClasses () const
ClassDef * tagLessReference () const
MemberDef * isSmartPointer () const
bool isJavaEnum () const
bool isGeneric () const
bool isAnonymous () const
const ClassSDict * innerClasses () const
QCString title () const
QCString generatedFromFiles () const
const FileList & usedFiles () const
const ArgumentList * typeConstraints () const
const ExampleSDict * exampleList () const
bool hasExamples () const
QCString getMemberListFileName () const
bool subGrouping () const
void insertBaseClass (ClassDef *, const char *name, Protection p, Specifier s, const char *t=0)
void insertSubClass (ClassDef *, Protection p, Specifier s, const char *t=0)
void setIncludeFile (FileDef *fd, const char *incName, bool local, bool force)
void insertMember (MemberDef *)
void insertUsedFile (FileDef *)
bool addExample (const char *anchor, const char *name, const char *file)
void mergeCategory (ClassDef *category)
void setNamespace (NamespaceDef *nd)
void setFileDef (FileDef *fd)
void setSubGrouping (bool enabled)
void setProtection (Protection p)
void setGroupDefForAllMembers (GroupDef *g, Grouping::GroupPri_t pri, const QCString &fileName, int startLine, bool hasDocs)
void addInnerCompound (Definition *d)
ClassDef * insertTemplateInstance (const QCString &fileName, int startLine, int startColumn, const QCString &templSpec, bool &freshInstance)
void addUsedClass (ClassDef *cd, const char *accessName, Protection prot)
void addUsedByClass (ClassDef *cd, const char *accessName, Protection prot)
void setIsStatic (bool b)
void setCompoundType (CompoundType t)
void setClassName (const char *name)
void setClassSpecifier (uint64 spec)
void setTemplateArguments (ArgumentList *al)
void setTemplateBaseClassNames (QDict< int > *templateNames)
void setTemplateMaster (ClassDef *tm)
void setTypeConstraints (ArgumentList *al)
void addMembersToTemplateInstance (ClassDef *cd, const char *templSpec)
void makeTemplateArgument (bool b=TRUE)
void setCategoryOf (ClassDef *cd)
void setUsedOnly (bool b)
void addTaggedInnerClass (ClassDef *cd)
void setTagLessReference (ClassDef *cd)
void setName (const char *name)
void findSectionsInDocumentation ()
void addMembersToMemberGroup ()
void addListReferences ()
void addTypeConstraints ()
void computeAnchors ()
void mergeMembers ()
void sortMemberLists ()
void distributeMemberGroupDocumentation ()
void writeDocumentation (OutputList &ol)
void writeDocumentationForInnerClasses (OutputList &ol)
void writeMemberPages (OutputList &ol)
void writeMemberList (OutputList &ol)
void writeDeclaration (OutputList &ol, MemberDef *md, bool inGroup, ClassDef *inheritedFrom, const char *inheritId)
void writeQuickMemberLinks (OutputList &ol, MemberDef *md) const
void writeSummaryLinks (OutputList &ol)
void reclassifyMember (MemberDef *md, MemberType t)
void writeInlineDocumentation (OutputList &ol)
Write class documentation inside another container (i.e.
void writeDeclarationLink (OutputList &ol, bool &found, const char *header, bool localNames)
void removeMemberFromLists (MemberDef *md)
void addGroupedInheritedMembers (OutputList &ol, MemberListType lt, ClassDef *inheritedFrom, const QCString &inheritId)
int countMembersIncludingGrouped (MemberListType lt, ClassDef *inheritedFrom, bool additional)
int countInheritanceNodes ()
void writeTagFile (FTextStream &)
Public Member Functions inherited from Definition
Definition (const char *defFileName, int defLine, int defColumn, const char *name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~Definition ()
const QCString & name () const
QCString localName () const
virtual QCString qualifiedName () const
QCString symbolName () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
int docLine () const
QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
QCString briefDescriptionAsTooltip () const
int briefLine () const
QCString inbodyDocumentation () const
QCString inbodyFile () const
int inbodyLine () const
QCString briefFile () const
QCString getDefFileName () const
QCString getDefFileExtension () const
int getDefLine () const
int getDefColumn () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
bool isHidden () const
bool isArtificial () const
QCString externalReference (const QCString &relPath) const
int getStartBodyLine () const
int getEndBodyLine () const
FileDef * getBodyDef () const
SrcLangExt getLanguage () const
Returns the programming language this definition was written in.
GroupList * partOfGroups () const
bool isLinkableViaGroup () const
QList< ListItemInfo > * xrefListItems () const
virtual Definition * getOuterScope () const
MemberSDict * getReferencesMembers () const
MemberSDict * getReferencedByMembers () const
bool hasSections () const
bool hasSources () const
bool hasBriefDescription () const
returns TRUE if this class has a brief description
QCString id () const
void setId (const char *name)
virtual void setDocumentation (const char *d, const char *docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const char *b, const char *briefFile, int briefLine)
virtual void setInbodyDocumentation (const char *d, const char *docFile, int docLine)
void setReference (const char *r)
void addSectionsToDefinition (QList< SectionInfo > *anchorList)
void setBodySegment (int bls, int ble)
void setBodyDef (FileDef *fd)
void addSourceReferencedBy (MemberDef *d)
void addSourceReferences (MemberDef *d)
void setRefItems (const QList< ListItemInfo > *sli)
void mergeRefItems (Definition *d)
virtual void setOuterScope (Definition *d)
virtual void setHidden (bool b)
void setArtificial (bool b)
void setLanguage (SrcLangExt lang)
void writeSourceDef (OutputList &ol, const char *scopeName)
void writeInlineCode (OutputList &ol, const char *scopeName)
void writeSourceRefs (OutputList &ol, const char *scopeName)
void writeSourceReffedBy (OutputList &ol, const char *scopeName)
void makePartOfGroup (GroupDef *gd)
void writeNavigationPath (OutputList &ol) const
QCString navigationPathAsString () const
QCString pathFragment () const
void writeDocAnchorsToTagFile (FTextStream &)
void setLocalName (const QCString name)
void addSectionsToIndex ()
void writeToc (OutputList &ol)
void setCookie (Cookie *cookie)
Cookie * cookie () const
Public Member Functions inherited from DefinitionIntf
DefinitionIntf ()
virtual ~DefinitionIntf ()
Public Attributes
bool visited
Protected Member Functions
void addUsedInterfaceClasses (MemberDef *md, const char *typeStr)
bool hasNonReferenceSuperClass ()
void showUsedFiles (OutputList &ol)
Protected Member Functions inherited from Definition
Definition (const Definition &d)
Private Member Functions
void writeDocumentationContents (OutputList &ol, const QCString &pageTitle)
void internalInsertMember (MemberDef *md, Protection prot, bool addToAllList)
void addMemberToList (MemberListType lt, MemberDef *md, bool isBrief)
MemberList * createMemberList (MemberListType lt)
void writeInheritedMemberDeclarations (OutputList &ol, MemberListType lt, int lt2, const QCString &title, ClassDef *inheritedFrom, bool invert, bool showAlways, QPtrDict< void > *visitedClasses)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title, const char *subTitle=0, bool showInline=FALSE, ClassDef *inheritedFrom=0, int lt2=-1, bool invert=FALSE, bool showAlways=FALSE, QPtrDict< void > *visitedClasses=0)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title, bool showInline=FALSE)
void writeSimpleMemberDocumentation (OutputList &ol, MemberListType lt)
void writePlainMemberDeclaration (OutputList &ol, MemberListType lt, bool inGroup, ClassDef *inheritedFrom, const char *inheritId)
void writeBriefDescription (OutputList &ol, bool exampleFlag)
void writeDetailedDescription (OutputList &ol, const QCString &pageType, bool exampleFlag, const QCString &title, const QCString &anchor=QCString())
void writeIncludeFiles (OutputList &ol)
void writeInheritanceGraph (OutputList &ol)
void writeCollaborationGraph (OutputList &ol)
void writeMemberGroups (OutputList &ol, bool showInline=FALSE)
void writeNestedClasses (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void writeMoreLink (OutputList &ol, const QCString &anchor)
void writeDetailedDocumentationBody (OutputList &ol)
int countAdditionalInheritedMembers ()
void writeAdditionalInheritedMembers (OutputList &ol)
void addClassAttributes (OutputList &ol)
int countMemberDeclarations (MemberListType lt, ClassDef *inheritedFrom, int lt2, bool invert, bool showAlways, QPtrDict< void > *visitedClasses)
int countInheritedDecMembers (MemberListType lt, ClassDef *inheritedFrom, bool invert, bool showAlways, QPtrDict< void > *visitedClasses)
void getTitleForMemberListType (MemberListType type, QCString &title, QCString &subtitle)
QCString includeStatement () const
void addTypeConstraint (const QCString &typeConstraint, const QCString &type)
Private Attributes
ClassDefImpl * m_impl
Detailed Description
A class representing of a compound symbol.
A compound can be a class, struct, union, interface, service, singleton, or exception.
Note
This class should be renamed to CompoundDef
Definition at line 59 of file classdef.h.
Member Enumeration Documentation
CompoundType
enum ClassDef::CompoundType
The various compound types.
Enumerator
Class
Struct
Union
Interface
Protocol
Category
Exception
Service
Singleton
Definition at line 63 of file classdef.h.
Constructor & Destructor Documentation
ClassDef()
ClassDef::ClassDef (const char * fileName, int startLine, int startColumn, const char * name, CompoundType ct, const char * ref = 0, const char * fName = 0, bool isSymbol = TRUE, bool isJavaEnum = FALSE)
Creates a new compound definition.
Parameters
fileName full path and file name in which this compound was found.
startLine line number where the definition of this compound starts.
startColumn column number where the definition of this compound starts.
name the name of this compound (including scope)
ct the kind of Compound
ref the tag file from which this compound is extracted or 0 if the compound doesn't come from a tag file
fName the file name as found in the tag file. This overwrites the file that doxygen normally generates based on the compound type & name.
isSymbol If TRUE this class name is added as a publicly visible (and referencable) symbol.
isJavaEnum If TRUE this class is actually a Java enum. I didn't add this to CompoundType to avoid having to adapt all translators.
Definition at line 295 of file classdef.cpp.
References ClassDefImpl::collabFileName, compoundTypeString(), ClassDefImpl::compType, convertNameToFile(), ClassDefImpl::fileName, ClassDefImpl::inheritFileName, ClassDefImpl::init(), ClassDefImpl::isJavaEnum, isJavaEnum(), m_impl, ClassDefImpl::memberListFileName, Definition::name(), Definition::setReference(), and visited.
Referenced by addTypeConstraint(), getVariableInstance(), and insertTemplateInstance().
~ClassDef()
ClassDef::~ClassDef ()
Destroys a compound definition.
Definition at line 318 of file classdef.cpp.
References m_impl.
Member Function Documentation
addClassAttributes()
void ClassDef::addClassAttributes (OutputList & ol) private
Definition at line 1951 of file classdef.cpp.
References OutputList::disableAllBut(), OutputList::endLabels(), Definition::getLanguage(), OutputGenerator::Html, isAbstract(), isFinal(), isPublished(), isSealed(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_IDL, OutputList::startLabels(), and OutputList::writeLabel().
Referenced by writeDocumentation().
addExample()
bool ClassDef::addExample (const char * anchor, const char * name, const char * file)
Definition at line 2522 of file classdef.cpp.
References Example::anchor, anchor(), ClassDefImpl::exampleSDict, Example::file, SDict< T >::find(), SDict< T >::inSort(), m_impl, Example::name, and SDict< T >::setAutoDelete().
addGroupedInheritedMembers()
void ClassDef::addGroupedInheritedMembers (OutputList & ol, MemberListType lt, ClassDef * inheritedFrom, const QCString & inheritId)
Definition at line 4333 of file classdef.cpp.
References MemberGroup::addGroupedInheritedMembers(), MemberGroup::allMembersInSameSection(), SIntDict< MemberGroup >::Iterator, m_impl, ClassDefImpl::memberGroupSDict, and ClassDefImpl::subGrouping.
Referenced by MemberList::writeDeclarations().
addInnerCompound()
void ClassDef::addInnerCompound (Definition * d) virtual
Reimplemented from Definition.
Definition at line 3631 of file classdef.cpp.
References DefinitionIntf::definitionType(), ClassDefImpl::innerClasses, SDict< T >::inSort(), Definition::localName(), m_impl, and DefinitionIntf::TypeClass.
addListReferences()
void ClassDef::addListReferences ()
Definition at line 3925 of file classdef.cpp.
References MemberList::addListReferences(), MemberGroup::addListReferences(), addRefItem(), displayName(), Definition::getLanguage(), getOutputFileBase(), isLinkableInProject(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_impl, ClassDefImpl::memberGroupSDict, ClassDefImpl::memberLists, MemberListType_detailedLists, Definition::qualifiedName(), SrcLangExt_Fortran, theTranslator, Translator::trClass(), Translator::trType(), and Definition::xrefListItems().
Referenced by addListReferences().
addMembersToMemberGroup()
void ClassDef::addMembersToMemberGroup ()
Definition at line 404 of file classdef.cpp.
References MemberGroup::addToDeclarationSection(), MemberGroup::allMembersInSameSection(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_impl, ClassDefImpl::memberGroupSDict, ClassDefImpl::memberLists, MemberListType_detailedLists, and ClassDefImpl::subGrouping.
Referenced by addMembersToMemberGroup().
addMembersToTemplateInstance()
void ClassDef::addMembersToTemplateInstance (ClassDef * cd, const char * templSpec)
Definition at line 3765 of file classdef.cpp.
References SDict< T >::append(), MemberDef::briefDescription(), Definition::briefFile(), Definition::briefLine(), MemberDef::createTemplateInstanceMember(), Definition::docFile(), Definition::docLine(), MemberDef::documentation(), SDict< T >::find(), MemberDef::getMemberGroupId(), MemberDef::getMemberSpecifiers(), Definition::inbodyDocumentation(), Definition::inbodyFile(), Definition::inbodyLine(), insertMember(), SDict< MemberNameInfo >::Iterator, MemberInfo::memberDef, memberNameInfoSDict(), Doxygen::memberNameSDict, Definition::name(), MemberDef::setBriefDescription(), MemberDef::setDocumentation(), MemberDef::setInbodyDocumentation(), MemberDef::setMemberClass(), MemberDef::setMemberGroupId(), MemberDef::setMemberSpecifiers(), MemberDef::setTemplateMaster(), stringToArgumentList(), and templateArguments().
Referenced by createTemplateInstanceMembers(), and getVariableInstance().
addMemberToList()
void ClassDef::addMemberToList (MemberListType lt, MemberDef * md, bool isBrief) private
Definition at line 4029 of file classdef.cpp.
References MemberList::append(), Config_getBool, createMemberList(), MemberList::listType(), MemberListType_detailedLists, MemberList::setNeedsSorting(), and MemberDef::setSectionList().
Referenced by internalInsertMember().
addTaggedInnerClass()
void ClassDef::addTaggedInnerClass (ClassDef * cd)
Definition at line 4653 of file classdef.cpp.
References m_impl, and ClassDefImpl::taggedInnerClasses.
Referenced by processTagLessClasses().
addTypeConstraint()
void ClassDef::addTypeConstraint (const QCString & typeConstraint, const QCString & type) private
Definition at line 2551 of file classdef.cpp.
References ConstraintClassDef::addAccessor(), SDict< T >::append(), Class, ClassDef(), Config_getBool, ClassDefImpl::constraintClassDict, Definition::getDefColumn(), Definition::getDefFileName(), Definition::getDefLine(), getFileDef(), Definition::getLanguage(), getResolvedClass(), Doxygen::hiddenClasses, m_impl, Definition::setLanguage(), and setUsedOnly().
Referenced by addTypeConstraints().
addTypeConstraints()
void ClassDef::addTypeConstraints ()
Definition at line 2586 of file classdef.cpp.
References addTypeConstraint(), m_impl, ClassDefImpl::tempArgs, Argument::type, and Argument::typeConstraint.
Referenced by findUsedTemplateInstances().
addUsedByClass()
void ClassDef::addUsedByClass (ClassDef * cd, const char * accessName, Protection prot)
Definition at line 3289 of file classdef.cpp.
References UsesClassDef::addAccessor(), Config_getBool, m_impl, Definition::name(), Package, Private, Protected, Public, and ClassDefImpl::usedByImplClassDict.
Referenced by findUsedClassesForClass().
addUsedClass()
void ClassDef::addUsedClass (ClassDef * cd, const char * accessName, Protection prot)
Definition at line 3255 of file classdef.cpp.
References UsesClassDef::addAccessor(), Config_getBool, m_impl, Definition::name(), Package, Private, Protected, Public, and ClassDefImpl::usesImplClassDict.
Referenced by findUsedClassesForClass().
addUsedInterfaceClasses()
void ClassDef::addUsedInterfaceClasses (MemberDef * md, const char * typeStr) protected
anchor()
QCString ClassDef::anchor () const virtual
Returns the anchor within a page where this item can be found
Implements Definition.
Definition at line 4600 of file classdef.cpp.
References ClassDefImpl::fileName, Doxygen::generatingXmlOutput, getOutputFileBase(), isEmbeddedInOuterScope(), m_impl, and ClassDefImpl::templateMaster.
Referenced by MemberDef::_writeReimplements(), DotClassGraph::addClass(), DotGfxHierarchyTable::addClassList(), addExample(), DotGfxHierarchyTable::addHierarchy(), addMembersToIndex(), DotClassGraph::DotClassGraph(), handleLinkedWord(), linkifyText(), resolveLink(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeBriefDescription(), writeClassTree(), writeClassTreeForList(), writeDeclarationLink(), MemberList::writeDeclarations(), writeDetailedDescription(), writeDocumentationContents(), writeInheritanceGraph(), writeInlineDocumentation(), writeMapArea(), MemberDef::writeMemberDocSimple(), writeMemberList(), writeMoreLink(), and writeTagFile().
baseClasses()
BaseClassList * ClassDef::baseClasses () const
Returns the list of base classes from which this class directly inherits.
Definition at line 4393 of file classdef.cpp.
References ClassDefImpl::inherits, and m_impl.
Referenced by VhdlDocGen::addBaseClass(), NestingNodeContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), NestingContext::Private::addDerivedClasses(), DotGfxHierarchyTable::addHierarchy(), buildCompleteMemberLists(), DotClassGraph::buildGraph(), classHasVisibleChildren(), classInheritedProtectionLevel(), computeMemberRelations(), countClassesInTreeList(), InheritedMemberInfoListContext::Private::findInheritedMembers(), generateDEFForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), hasVisibleRoot(), ClassContext::Private::inherits(), initBaseClassHierarchy(), initClassHierarchy(), DiagramRow::insertClass(), isBaseClass(), matchArgument(), mergeCategory(), mergeMembers(), minClassDistance(), trimBaseClassScope(), writeClassTree(), writeClassTreeForList(), and VhdlDocGen::writeOverview().
categoryOf()
ClassDef * ClassDef::categoryOf () const
Returns the class of which this is a category (Objective-C only)
Definition at line 4508 of file classdef.cpp.
References ClassDefImpl::categoryOf, and m_impl.
Referenced by MemberDef::_writeCategoryRelation(), ClassContext::Private::categoryOf(), classInheritedProtectionLevel(), and minClassDistance().
className()
QCString ClassDef::className () const
Returns the name of the class including outer classes, but not including namespaces.
Definition at line 3908 of file classdef.cpp.
References ClassDefImpl::className, Definition::localName(), and m_impl.
Referenced by PrefixIgnoreClassList::compareValue(), compItems(), displayName(), VhdlDocGen::findAllArchitectures(), VhdlDocGen::getClassName(), qualifiedNameWithTemplateParameters(), writeAlphabeticalClassList(), and VhdlDocGen::writeInlineClassLink().
collaborationGraphFileName()
QCString ClassDef::collaborationGraphFileName () const
returns the file name to use for the collaboration graph
Definition at line 4742 of file classdef.cpp.
References ClassDefImpl::collabFileName, and m_impl.
Referenced by DotClassGraph::DotClassGraph().
compoundType()
ClassDef::CompoundType ClassDef::compoundType () const
Returns the type of compound this is, i.e.
class/struct/union/..
Definition at line 4388 of file classdef.cpp.
References ClassDefImpl::compType, and m_impl.
Referenced by MemberDef::_writeReimplementedBy(), MemberDef::_writeReimplements(), DocSets::addIndexItem(), buildInterfaceAndServiceList(), computeMemberRelations(), createTagLessInstance(), ClassSDict::declVisible(), MemberContext::Private::implementedBy(), MemberContext::Private::implements(), mergeMembers(), MemberContext::Private::reimplementedBy(), MemberContext::Private::reimplements(), and ClassSDict::writeDeclaration().
compoundTypeString()
QCString ClassDef::compoundTypeString () const
Returns the type of compound as a string.
Definition at line 3521 of file classdef.cpp.
References Category, Class, ClassDefImpl::compType, Exception, Definition::getLanguage(), Interface, isJavaEnum(), m_impl, Protocol, Service, Singleton, SrcLangExt_Fortran, SrcLangExt_ObjC, Struct, and Union.
Referenced by ClassDef(), ClassContext::Private::compoundType(), generateDEFForClass(), generateDocbookForClass(), generateXMLForClass(), SearchIndex::setCurrentDoc(), validatingParseDoc(), writeDeclaration(), writeDeclarationLink(), writeDetailedDocumentationBody(), writeDocumentationContents(), writeInlineDocumentation(), NamespaceDef::writeTagFile(), GroupDef::writeTagFile(), FileDef::writeTagFile(), and writeTagFile().
computeAnchors()
void ClassDef::computeAnchors ()
Definition at line 737 of file classdef.cpp.
References SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_impl, ClassDefImpl::memberGroupSDict, ClassDefImpl::memberLists, MemberListType_detailedLists, MemberGroup::setAnchors(), and setAnchors().
Referenced by computeMemberReferences().
countAdditionalInheritedMembers()
int ClassDef::countAdditionalInheritedMembers () private
Definition at line 4161 of file classdef.cpp.
References LayoutDocManager::Class, countInheritedDecMembers(), LayoutDocManager::instance(), LayoutDocEntry::kind(), LayoutDocEntry::MemberDecl, MemberListType_friends, LayoutDocEntryMemberDecl::type, and visited.
Referenced by endMemberDeclarations().
countInheritanceNodes()
int ClassDef::countInheritanceNodes ()
Definition at line 1178 of file classdef.cpp.
References BaseClassDef::classDef, ClassDefImpl::inheritedBy, ClassDefImpl::inherits, isVisibleInHierarchy(), and m_impl.
Referenced by ClassContext::Private::numInheritanceNodes(), and writeInheritanceGraph().
countInheritedDecMembers()
int ClassDef::countInheritedDecMembers (MemberListType lt, ClassDef * inheritedFrom, bool invert, bool showAlways, QPtrDict< void > * visitedClasses) private
Definition at line 4098 of file classdef.cpp.
References BaseClassDef::classDef, convertProtectionLevel(), countMemberDeclarations(), countMembersIncludingGrouped(), ClassDefImpl::inherits, isLinkable(), m_impl, and BaseClassDef::prot.
Referenced by countAdditionalInheritedMembers(), and countMemberDeclarations().
countMemberDeclarations()
int ClassDef::countMemberDeclarations (MemberListType lt, ClassDef * inheritedFrom, int lt2, bool invert, bool showAlways, QPtrDict< void > * visitedClasses) private
Definition at line 4055 of file classdef.cpp.
References Config_getBool, MemberList::countDecMembers(), MemberGroup::countGroupedInheritedMembers(), countInheritedDecMembers(), Definition::getLanguage(), getMemberList(), SIntDict< MemberGroup >::Iterator, m_impl, ClassDefImpl::memberGroupSDict, MemberList::numDecMembers(), and SrcLangExt_VHDL.
Referenced by countInheritedDecMembers().
countMembersIncludingGrouped()
int ClassDef::countMembersIncludingGrouped (MemberListType lt, ClassDef * inheritedFrom, bool additional)
Definition at line 4207 of file classdef.cpp.
References MemberGroup::allMembersInSameSection(), MemberGroup::countGroupedInheritedMembers(), MemberList::countInheritableMembers(), getMemberList(), SIntDict< MemberGroup >::Iterator, m_impl, ClassDefImpl::memberGroupSDict, and ClassDefImpl::subGrouping.
Referenced by InheritedMemberInfoListContext::Private::addInheritedMembers(), InheritedMemberInfoListContext::addMemberList(), countInheritedDecMembers(), MemberList::writeDeclarations(), and writeInheritedMemberDeclarations().
createMemberList()
MemberList * ClassDef::createMemberList (MemberListType lt) private
Definition at line 3997 of file classdef.cpp.
References MemberList::listType(), m_impl, and ClassDefImpl::memberLists.
Referenced by addMemberToList(), and internalInsertMember().
definitionType()
DefType ClassDef::definitionType () const inline virtual
Used for RTTI, this is a class.
Implements DefinitionIntf.
Definition at line 106 of file classdef.h.
References DefinitionIntf::TypeClass.
displayName()
QCString ClassDef::displayName (bool includeScope = TRUE) const virtual
Returns the name as it is appears in the documentation.
Implements Definition.
Definition at line 328 of file classdef.cpp.
References className(), ClassDefImpl::compType, VhdlDocGen::getClassName(), Definition::getLanguage(), getLanguageSpecificSeparator(), m_impl, Protocol, qualifiedNameWithTemplateParameters(), removeAnonymousScopes(), SrcLangExt_VHDL, and substitute().
Referenced by MemberDef::_writeCategoryRelation(), MemberDef::_writeReimplementedBy(), MemberDef::_writeReimplements(), DotClassGraph::addClass(), DotGfxHierarchyTable::addClassList(), DotGfxHierarchyTable::addHierarchy(), addListReferences(), addMembersToIndex(), DotClassGraph::DotClassGraph(), MemberDef::getScopeString(), MemberContext::Private::handleNameWithContextFor(), ClassContext::Private::inheritanceDiagram(), InheritanceListContext::InheritanceListContext(), DiagramItem::label(), title(), writeAnnotatedClassList(), writeClassLinkForMember(), writeClassTree(), writeClassTreeForList(), writeCollaborationGraph(), writeDeclaration(), writeDeclarationLink(), MemberList::writeDeclarations(), MemberDef::writeDocumentation(), writeDocumentation(), writeInheritanceGraph(), MemberDef::writeLink(), writeMapArea(), writeMemberDocumentation(), writeMemberList(), and writeMemberPages().
distributeMemberGroupDocumentation()
void ClassDef::distributeMemberGroupDocumentation ()
Definition at line 763 of file classdef.cpp.
References MemberGroup::distributeMemberGroupDocumentation(), SIntDict< MemberGroup >::Iterator, m_impl, and ClassDefImpl::memberGroupSDict.
Referenced by distributeMemberGroupDocumentation().
endMemberDeclarations()
void ClassDef::endMemberDeclarations (OutputList & ol) private
Definition at line 1496 of file classdef.cpp.
References Config_getBool, countAdditionalInheritedMembers(), OutputList::endMemberHeader(), OutputList::endMemberSections(), OutputList::parseText(), OutputList::startMemberHeader(), theTranslator, Translator::trAdditionalInheritedMembers(), and writeAdditionalInheritedMembers().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
endMemberDocumentation()
void ClassDef::endMemberDocumentation (OutputList & ol) private
Definition at line 1480 of file classdef.cpp.
References Config_getBool, OutputList::enable(), OutputGenerator::Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
exampleList()
const ExampleSDict * ClassDef::exampleList () const
Definition at line 4721 of file classdef.cpp.
References ClassDefImpl::exampleSDict, and m_impl.
Referenced by ClassContext::Private::addExamples().
findInnerCompound()
Definition * ClassDef::findInnerCompound (const char * name) virtual
Returns the definition of a nested compound if available, or 0 otherwise.
Parameters
name The name of the nested compound
Reimplemented from Definition.
Definition at line 3645 of file classdef.cpp.
References SDict< T >::find(), ClassDefImpl::innerClasses, and m_impl.
findSectionsInDocumentation()
void ClassDef::findSectionsInDocumentation ()
Definition at line 776 of file classdef.cpp.
References Definition::docFile(), docFindSections(), Definition::documentation(), MemberGroup::findSectionsInDocumentation(), MemberList::findSectionsInDocumentation(), SIntDict< MemberGroup >::Iterator, MemberList::listType(), m_impl, ClassDefImpl::memberGroupSDict, ClassDefImpl::memberLists, and MemberListType_detailedLists.
Referenced by findSectionsInDocumentation().
generatedFromFiles()
QCString ClassDef::generatedFromFiles () const
Definition at line 1075 of file classdef.cpp.
References Class, ClassDefImpl::compType, ClassDefImpl::files, Definition::getLanguage(), Interface, isJavaEnum(), m_impl, Service, Singleton, SrcLangExt_Fortran, SrcLangExt_ObjC, theTranslator, Translator::trEnumGeneratedFromFiles(), Translator::trGeneratedFromFiles(), Translator::trGeneratedFromFilesFortran(), Translator::trServiceGeneratedFromFiles(), and Translator::trSingletonGeneratedFromFiles().
Referenced by ClassContext::Private::generatedFromFiles(), and showUsedFiles().
getClassSDict()
ClassSDict * ClassDef::getClassSDict ()
returns the classes nested into this class
Definition at line 4383 of file classdef.cpp.
References ClassDefImpl::innerClasses, and m_impl.
Referenced by NestingNodeContext::Private::addClasses(), ClassContext::Private::classes(), distributeClassGroupRelations(), findTagLessClasses(), generateDocbookForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), ClassContext::Private::innerClasses(), processTagLessClasses(), and writeClassTree().
getFileDef()
FileDef * ClassDef::getFileDef () const
Returns the file in which this compound's definition can be found.
Should not return 0 (but it might be a good idea to check anyway).
Definition at line 4423 of file classdef.cpp.
References ClassDefImpl::fileDef, and m_impl.
Referenced by addInstance(), addTypeConstraint(), createTagLessInstance(), findClassRelation(), findClassWithinClassContext(), findUsedClassesForClass(), getDefs(), getOutputFileBase(), isEmbeddedInOuterScope(), and resolveClassNestingRelations().
getInstanceOutputFileBase()
QCString ClassDef::getInstanceOutputFileBase () const
Definition at line 3592 of file classdef.cpp.
References ClassDefImpl::fileName, and m_impl.
getMemberByName()
MemberDef * ClassDef::getMemberByName (const QCString & name) const
Returns the Java package this class is in or 0 if not applicable.
Definition at line 3962 of file classdef.cpp.
References ClassDefImpl::allMemberNameInfoSDict, SDict< T >::find(), MemberDef::getClassDef(), isLinkable(), m_impl, maxInheritanceDepth, MemberInfo::memberDef, and minClassDistance().
getMemberGroupSDict()
MemberGroupSDict * ClassDef::getMemberGroupSDict () const
Returns the member groups defined for this class.
Definition at line 4518 of file classdef.cpp.
References m_impl, and ClassDefImpl::memberGroupSDict.
Referenced by InheritedMemberInfoListContext::Private::addMemberGroupsOfClass(), generateDocbookForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), ClassContext::Private::memberGroups(), and DotNode::writeBox().
getMemberList()
MemberList * ClassDef::getMemberList (MemberListType lt)
Returns the members in the list identified by lt.
Definition at line 4015 of file classdef.cpp.
References MemberList::listType(), m_impl, and ClassDefImpl::memberLists.
Referenced by InheritedMemberInfoListContext::Private::addInheritedMembers(), ClassContext::Private::addMembers(), countMemberDeclarations(), countMembersIncludingGrouped(), createTagLessInstance(), VhdlDocGen::findAllPackages(), VhdlDocGen::findFunction(), VhdlDocGen::findMemberDef(), generateDEFForClass(), PerlModGenerator::generatePerlModForClass(), ClassContext::Private::getMemberList(), getPorts(), processTagLessClasses(), DotNode::writeBox(), writeMemberDeclarations(), writeMemberDocumentation(), writePlainMemberDeclaration(), writeSimpleMemberDocumentation(), writeSummaryLinks(), and writeTagFile().
getMemberListFileName()
QCString ClassDef::getMemberListFileName () const
Definition at line 323 of file classdef.cpp.
References m_impl, and ClassDefImpl::memberListFileName.
Referenced by ClassContext::Private::allMembersFileName(), writeMemberList(), and writeSummaryLinks().
getMemberLists()
const QList< MemberList > & ClassDef::getMemberLists () const
Returns the list containing the list of members sorted per type.
Definition at line 4513 of file classdef.cpp.
References m_impl, and ClassDefImpl::memberLists.
Referenced by generateDEFForClass(), generateDocbookForClass(), and generateXMLForClass().
getNamespaceDef()
NamespaceDef * ClassDef::getNamespaceDef () const
Returns the namespace this compound is in, or 0 if it has a global scope.
Definition at line 4418 of file classdef.cpp.
References m_impl, and ClassDefImpl::nspace.
getOutputFileBase()
QCString ClassDef::getOutputFileBase () const virtual
Returns the unique base name (without extension) of the class's file on disk.
Implements Definition.
Definition at line 3555 of file classdef.cpp.
References Config_getBool, ClassDefImpl::fileName, Doxygen::generatingXmlOutput, getFileDef(), Definition::getOuterScope(), FileDef::getOutputFileBase(), getOutputFileBase(), Definition::getOutputFileBase(), Doxygen::globalScope, isLinkableInProject(), Definition::isLinkableInProject(), ClassDefImpl::isSimple, m_impl, Definition::partOfGroups(), and ClassDefImpl::templateMaster.
Referenced by MemberDef::_writeReimplements(), DotClassGraph::addClass(), DotGfxHierarchyTable::addClassList(), DotGfxHierarchyTable::addHierarchy(), addInstance(), addListReferences(), anchor(), classOutputFileBase(), ClassContext::Private::collaborationDiagram(), DotClassGraph::DotClassGraph(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), DiagramItem::fileName(), generateDEFForClass(), generateDocbookForClass(), MemberDef::getOutputFileBase(), getOutputFileBase(), handleLinkedWord(), InheritedMemberInfoContext::Private::id(), ClassContext::Private::inheritanceDiagram(), linkifyText(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeClassToDot(), writeClassTree(), writeClassTreeForList(), writeDeclarationLink(), MemberList::writeDeclarations(), writeDetailedDescription(), writeDocumentation(), writeInheritanceGraph(), writeInlineDocumentation(), writeMapArea(), MemberDef::writeMemberDocSimple(), writeMemberList(), writeMoreLink(), writeTagFile(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVhdlLink().
getReference()
QCString ClassDef::getReference () const virtual
If this class originated from a tagfile, this will return the tag file reference.
Reimplemented from Definition.
Definition at line 3808 of file classdef.cpp.
References getReference(), Definition::getReference(), m_impl, and ClassDefImpl::templateMaster.
Referenced by MemberDef::_writeReimplements(), DotClassGraph::addClass(), DotGfxHierarchyTable::addClassList(), DotGfxHierarchyTable::addHierarchy(), DotGroupCollaboration::buildGraph(), DotClassGraph::DotClassGraph(), MemberDef::getReference(), getReference(), handleLinkedWord(), linkifyText(), writeAlphabeticalClassList(), writeClassTree(), writeClassTreeForList(), writeDeclarationLink(), MemberList::writeDeclarations(), writeInheritanceGraph(), writeMapArea(), MemberDef::writeMemberDocSimple(), writeMemberList(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVhdlLink().
getSourceFileBase()
QCString ClassDef::getSourceFileBase () const virtual
Returns the base name for the source code file.
Reimplemented from Definition.
Definition at line 3597 of file classdef.cpp.
References getSourceFileBase(), Definition::getSourceFileBase(), m_impl, and ClassDefImpl::templateMaster.
Referenced by getSourceFileBase().
getTemplateBaseClassNames()
QDict< int > * ClassDef::getTemplateBaseClassNames () const
Definition at line 3760 of file classdef.cpp.
References m_impl, and ClassDefImpl::templBaseClassNames.
Referenced by computeTemplateClassRelations().
getTemplateInstances()
QDict< ClassDef > * ClassDef::getTemplateInstances () const
Returns a sorted dictionary with all template instances found for this template class.
Returns 0 if not a template or no instances.
Definition at line 4428 of file classdef.cpp.
References m_impl, and ClassDefImpl::templateInstances.
Referenced by DotClassGraph::buildGraph(), computeTemplateClassRelations(), createTemplateInstanceMembers(), and hasNonReferenceSuperClass().
getTemplateParameterLists()
void ClassDef::getTemplateParameterLists (QList< ArgumentList > & lists) const
Returns the template parameter lists that form the template declaration of this class.
Example: template<class T> class TC {}; will return a list with one ArgumentList containing one argument with type="class" and name="T".
Definition at line 3832 of file classdef.cpp.
References DefinitionIntf::definitionType(), Definition::getOuterScope(), getTemplateParameterLists(), templateArguments(), and DefinitionIntf::TypeClass.
Referenced by MemberContext::Private::addTemplateDecls(), findMember(), getTemplateParameterLists(), and MemberDef::writeDocumentation().
getTitleForMemberListType()
void ClassDef::getTitleForMemberListType (MemberListType type, QCString & title, QCString & subtitle) private
Definition at line 4137 of file classdef.cpp.
References LayoutDocManager::Class, Definition::getLanguage(), LayoutDocManager::instance(), LayoutDocEntry::kind(), LayoutDocEntry::MemberDecl, LayoutDocEntryMemberDecl::subtitle(), LayoutDocEntryMemberDecl::title(), and LayoutDocEntryMemberDecl::type.
getVariableInstance()
ClassDef * ClassDef::getVariableInstance (const char * templSpec)
Definition at line 3720 of file classdef.cpp.
References addMembersToTemplateInstance(), Class, ClassDef(), Debug::Classes, m_impl, Definition::name(), Debug::print(), removeRedundantWhiteSpace(), setTemplateMaster(), and ClassDefImpl::variableInstances.
hasDetailedDescription()
bool ClassDef::hasDetailedDescription () const
returns TRUE if this class has a non-empty detailed description
Definition at line 1029 of file classdef.cpp.
References Definition::briefDescription(), Config_getBool, Definition::documentation(), Definition::getBodyDef(), and Definition::getStartBodyLine().
Referenced by ClassContext::Private::hasDetails(), writeBriefDescription(), and writeDetailedDescription().
hasDocumentation()
bool ClassDef::hasDocumentation () const virtual
returns TRUE if this class has documentation
Reimplemented from Definition.
Definition at line 2789 of file classdef.cpp.
References Definition::hasDocumentation().
Referenced by addClassToContext(), computeClassRelations(), isLinkableInProject(), and isVisibleInHierarchy().
hasExamples()
bool ClassDef::hasExamples () const
Definition at line 2543 of file classdef.cpp.
References SDict< T >::count(), ClassDefImpl::exampleSDict, and m_impl.
Referenced by ClassContext::Private::addExamples(), writeDetailedDocumentationBody(), and writeDocumentationContents().
hasNonReferenceSuperClass()
bool ClassDef::hasNonReferenceSuperClass () protected
Returns TRUE iff this class or a class inheriting from this class is not defined in an external tag file.
Definition at line 2642 of file classdef.cpp.
References getTemplateInstances(), hasNonReferenceSuperClass(), ClassDefImpl::inheritedBy, Definition::isHidden(), isLinkableInProject(), isReference(), and m_impl.
Referenced by hasNonReferenceSuperClass(), and isVisibleInHierarchy().
includeInfo()
IncludeInfo * ClassDef::includeInfo () const
Definition at line 4443 of file classdef.cpp.
References ClassDefImpl::incInfo, and m_impl.
Referenced by DocSets::addIndexItem(), generateDocbookForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), and ClassContext::Private::includeInfo().
includeStatement()
QCString ClassDef::includeStatement () const private
Definition at line 1345 of file classdef.cpp.
References Definition::getLanguage(), isObjectiveC(), SrcLangExt_IDL, and SrcLangExt_Java.
Referenced by writeIncludeFiles().
inheritanceGraphFileName()
QCString ClassDef::inheritanceGraphFileName () const
returns the file name to use for the inheritance graph
Definition at line 4747 of file classdef.cpp.
References ClassDefImpl::inheritFileName, and m_impl.
Referenced by DotClassGraph::DotClassGraph().
innerClasses()
const ClassSDict * ClassDef::innerClasses () const
Definition at line 4706 of file classdef.cpp.
References ClassDefImpl::innerClasses, and m_impl.
insertBaseClass()
void ClassDef::insertBaseClass (ClassDef * cd, const char * name, Protection p, Specifier s, const char * t = 0)
Definition at line 374 of file classdef.cpp.
References ClassDefImpl::inherits, ClassDefImpl::isSimple, and m_impl.
Referenced by addInstance(), findClassRelation(), and mergeCategory().
insertMember()
void ClassDef::insertMember (MemberDef * md)
Definition at line 731 of file classdef.cpp.
References internalInsertMember(), and MemberDef::protection().
Referenced by addEnumValuesToEnums(), addInstance(), addInterfaceOrServiceToServiceOrSingleton(), addMembersToTemplateInstance(), addMethodToClass(), addVariableToClass(), createTagLessInstance(), findEnums(), findMember(), findUsingDeclImports(), and reclassifyMember().
insertSubClass()
void ClassDef::insertSubClass (ClassDef * cd, Protection p, Specifier s, const char * t = 0)
Definition at line 389 of file classdef.cpp.
References Config_getBool, ClassDefImpl::inheritedBy, ClassDefImpl::isSimple, m_impl, Private, and protection().
Referenced by addInstance(), and findClassRelation().
insertTemplateInstance()
ClassDef * ClassDef::insertTemplateInstance (const QCString & fileName, int startLine, int startColumn, const QCString & templSpec, bool & freshInstance)
Definition at line 3696 of file classdef.cpp.
References Class, ClassDef(), Debug::Classes, Definition::getOuterScope(), Definition::isHidden(), Definition::localName(), m_impl, Definition::name(), Debug::print(), removeRedundantWhiteSpace(), Definition::setHidden(), Definition::setOuterScope(), setTemplateMaster(), and ClassDefImpl::templateInstances.
Referenced by findTemplateInstanceRelation().
insertUsedFile()
void ClassDef::insertUsedFile (FileDef * fd)
Definition at line 801 of file classdef.cpp.
References ClassDefImpl::files, insertUsedFile(), m_impl, and ClassDefImpl::templateInstances.
Referenced by addClassToContext(), addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addVariableToClass(), findClassRelation(), findEnums(), findMember(), and insertUsedFile().
internalInsertMember()
void ClassDef::internalInsertMember (MemberDef * md, Protection prot, bool addToAllList) private
isReference()
Definition at line 433 of file classdef.cpp.
References addMemberToList(), ClassDefImpl::allMemberNameInfoSDict, MemberList::append(), SDict< T >::append(), ClassDefImpl::arrowOperator, Config_getBool, createMemberList(), err(), SDict< T >::find(), Definition::getLanguage(), MemberDef::getMemberSpecifiers(), ClassDefImpl::isAbstract, MemberDef::isConstructor(), MemberDef::isDestructor(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isFriend(), MemberDef::isFunctionPtr(), Definition::isHidden(), MemberDef::isRelated(), ClassDefImpl::isSimple, isSimple(), MemberDef::isStatic(), MemberDef::isTypedef(), MemberDef::isVariable(), m_impl, MemberListType_constructors, MemberListType_dcopMethods, MemberListType_enumMembers, MemberListType_enumValMembers, MemberListType_eventMembers, MemberListType_events, MemberListType_friends, MemberListType_functionMembers, MemberListType_interfaceMembers, MemberListType_interfaces, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_pacTypes, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_propertyMembers, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_relatedMembers, MemberListType_serviceMembers, MemberListType_services, MemberListType_signals, MemberListType_typedefMembers, MemberListType_variableMembers, MemberDef::memberType(), MemberType_DCOP, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Definition::name(), Package, Private, Protected, protectionLevelVisible(), Public, Pure, SDict< T >::setAutoDelete(), SrcLangExt_VHDL, title(), VhdlDocGen::trVhdlType(), MemberDef::typeString(), ClassDefImpl::vhdlSummaryTitles, and MemberDef::virtualness().
Referenced by insertMember(), mergeCategory(), and mergeMembers().
isAbstract()
bool ClassDef::isAbstract () const
Returns TRUE if there is at least one pure virtual member in this class.
Definition at line 4473 of file classdef.cpp.
References Entry::Abstract, ClassDefImpl::isAbstract, m_impl, and ClassDefImpl::spec.
Referenced by addClassAttributes(), and generateXMLForClass().
isAccessibleMember()
bool ClassDef::isAccessibleMember (MemberDef * md)
returns TRUE iff md is a member of this class or of the the public/protected members of a base class
Definition at line 3992 of file classdef.cpp.
References MemberDef::getClassDef(), and isBaseClass().
isAnonymous()
bool ClassDef::isAnonymous () const
Definition at line 4737 of file classdef.cpp.
References ClassDefImpl::isAnonymous, and m_impl.
Referenced by DotClassGraph::addClass(), isLinkableInProject(), isVisibleInHierarchy(), and visibleInParentsDeclList().
isBaseClass()
bool ClassDef::isBaseClass (ClassDef * bcd, bool followInstances, int level = 0)
Returns TRUE iff bcd is a direct or indirect base class of this class.
This function will recusively traverse all branches of the inheritance tree.
Definition at line 2799 of file classdef.cpp.
References baseClasses(), err(), isBaseClass(), Definition::name(), and templateMaster().
Referenced by addInstance(), computeMemberRelations(), isAccessibleMember(), isBaseClass(), MemberDef::isReimplementedBy(), VhdlDocGen::isSubClass(), and mergeMembers().
isCSharp()
bool ClassDef::isCSharp () const
Returns TRUE if this class is implemented in C#.
Definition at line 4503 of file classdef.cpp.
References Definition::getLanguage(), and SrcLangExt_CSharp.
Referenced by findClassRelation().
isEmbeddedInOuterScope()
bool ClassDef::isEmbeddedInOuterScope () const
Definition at line 4618 of file classdef.cpp.
References Config_getBool, getFileDef(), Definition::getOuterScope(), Doxygen::globalScope, FileDef::isLinkableInProject(), ClassDefImpl::isSimple, m_impl, and Definition::partOfGroups().
Referenced by ClassListContext::Private::addClasses(), addMembersToIndex(), anchor(), countAnnotatedClasses(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateClassList(), RTFGenerator::startIndexSection(), LatexGenerator::startIndexSection(), writeAnnotatedClassList(), ClassSDict::writeDocumentation(), writeDocumentationForInnerClasses(), and writeTagFile().
isExtension()
bool ClassDef::isExtension () const
Returns TRUE if this class represents an Objective-C 2.0 extension (nameless category)
Definition at line 4697 of file classdef.cpp.
References Definition::name().
Referenced by mergeCategory(), visibleInParentsDeclList(), and ClassSDict::writeDeclaration().
isFinal()
bool ClassDef::isFinal () const
Returns TRUE if this class is marked as final.
Definition at line 4478 of file classdef.cpp.
References Entry::Final, m_impl, and ClassDefImpl::spec.
Referenced by addClassAttributes(), and generateXMLForClass().
isForwardDeclared()
bool ClassDef::isForwardDeclared () const
Returns TRUE if this class represents a forward declaration of a template class.
Definition at line 4493 of file classdef.cpp.
References Entry::ForwardDecl, m_impl, and ClassDefImpl::spec.
Referenced by addClassToContext().
isGeneric()
bool ClassDef::isGeneric () const
Definition at line 4687 of file classdef.cpp.
References ClassDefImpl::isGeneric, and m_impl.
Referenced by addClassToContext().
isJavaEnum()
bool ClassDef::isJavaEnum () const
Definition at line 4682 of file classdef.cpp.
References ClassDefImpl::isJavaEnum, and m_impl.
Referenced by ClassDef(), compoundTypeString(), generatedFromFiles(), title(), and MemberList::writeSimpleDocumentation().
isLinkable()
bool ClassDef::isLinkable () const virtual
return TRUE iff a link to this class is possible (either within this project, or as a cross-reference to another project).
Implements Definition.
Definition at line 2751 of file classdef.cpp.
References isLinkable(), isLinkableInProject(), isReference(), m_impl, and ClassDefImpl::templateMaster.
Referenced by MemberDef::_writeReimplementedBy(), MemberDef::_writeReimplements(), DotClassGraph::addClass(), DotGfxHierarchyTable::addClassList(), DotGfxHierarchyTable::addHierarchy(), addMembersToIndex(), addMemberToSearchIndex(), classVisibleInIndex(), computeMemberRelations(), countInheritedDecMembers(), createJavascriptSearchIndex(), ClassSDict::declVisible(), DotClassGraph::DotClassGraph(), TreeDiagram::drawBoxes(), InheritedMemberInfoListContext::Private::findInheritedMembers(), getDefs(), getMemberByName(), getResolvedClass(), getScopeDefs(), MemberDef::isDocumentedFriendClass(), isLinkable(), linkifyText(), AllMembersListContext::Private::Private(), visibleInParentsDeclList(), writeClassTree(), writeClassTreeForList(), writeDeclaration(), writeDeclarationLink(), writeInheritanceGraph(), writeInheritedMemberDeclarations(), writeMapArea(), writeMemberList(), and writeTagFile().
isLinkableInProject()
bool ClassDef::isLinkableInProject () const virtual
returns TRUE iff a link is possible to this item within this project.
a link to this class is possible within this project
Implements Definition.
Definition at line 2729 of file classdef.cpp.
References Config_getBool, hasDocumentation(), isAnonymous(), Definition::isArtificial(), Definition::isHidden(), isLinkableInProject(), ClassDefImpl::isLocal, isReference(), ClassDefImpl::isStatic, m_impl, Definition::name(), ClassDefImpl::prot, protectionLevelVisible(), and ClassDefImpl::templateMaster.
Referenced by MemberDef::_computeLinkableInProject(), MemberDef::_writeReimplements(), ClassListContext::Private::addClasses(), addClassMemberNameToIndex(), addListReferences(), addSourceReferences(), classVisibleInIndex(), countAnnotatedClasses(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateClassList(), ClassMembersIndexContext::Private::getMembersFiltered(), getOutputFileBase(), hasNonReferenceSuperClass(), isLinkable(), isLinkableInProject(), linkifyText(), ClassIndexContext::Private::list(), RTFGenerator::startIndexSection(), LatexGenerator::startIndexSection(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeDeclarationLink(), ClassSDict::writeDocumentation(), writeDocumentationForInnerClasses(), NamespaceDef::writeTagFile(), GroupDef::writeTagFile(), FileDef::writeTagFile(), writeTagFile(), and writeTagFile().
isLocal()
bool ClassDef::isLocal () const
Returns TRUE if this is a local class definition, see EXTRACT_LOCAL_CLASSES.
Definition at line 4378 of file classdef.cpp.
References ClassDefImpl::isLocal, and m_impl.
Referenced by ClassSDict::declVisible(), mergeCategory(), and visibleInParentsDeclList().
isObjectiveC()
bool ClassDef::isObjectiveC () const
Returns TRUE if this class is implemented in Objective-C.
Definition at line 4498 of file classdef.cpp.
References Definition::getLanguage(), and SrcLangExt_ObjC.
Referenced by MemberDef::displayDefinition(), includeStatement(), MemberDef::isObjCMethod(), MemberDef::isObjCProperty(), MemberDef::writeDocumentation(), writeMemberList(), and writeTagFile().
isPublished()
bool ClassDef::isPublished () const
Returns TRUE if this class is marked as published.
Definition at line 4488 of file classdef.cpp.
References m_impl, Entry::Published, and ClassDefImpl::spec.
Referenced by addClassAttributes().
isReference()
bool ClassDef::isReference () const virtual
Returns TRUE if this class is imported via a tag file.
Reimplemented from Definition.
Definition at line 3820 of file classdef.cpp.
References isReference(), Definition::isReference(), m_impl, and ClassDefImpl::templateMaster.
Referenced by computeClassRelations(), generateDEFForClass(), generateDocbookForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), hasNonReferenceSuperClass(), isLinkable(), isLinkableInProject(), isReference(), isVisibleInHierarchy(), writeClassTree(), and writeClassTreeForList().
isSealed()
bool ClassDef::isSealed () const
Returns TRUE if this class is marked as sealed.
Definition at line 4483 of file classdef.cpp.
References m_impl, Entry::Sealed, and ClassDefImpl::spec.
Referenced by addClassAttributes(), and generateXMLForClass().
isSimple()
bool ClassDef::isSimple () const
Definition at line 4578 of file classdef.cpp.
References ClassDefImpl::isSimple, and m_impl.
Referenced by addMembersToIndex(), MemberDef::getOutputFileBase(), internalInsertMember(), MemberDef::isDetailedSectionVisible(), ClassContext::Private::isSimple(), writeClassTree(), and writeInlineDocumentation().
isSmartPointer()
MemberDef * ClassDef::isSmartPointer () const
Definition at line 4583 of file classdef.cpp.
References ClassDefImpl::arrowOperator, and m_impl.
isSubClass()
bool ClassDef::isSubClass (ClassDef * bcd, int level = 0)
Returns TRUE iff bcd is a direct or indirect sub class of this class.
Definition at line 2829 of file classdef.cpp.
References err(), isSubClass(), Definition::name(), and subClasses().
Referenced by findClassRelation(), and isSubClass().
isTemplate()
bool ClassDef::isTemplate () const
Returns TRUE if this class is a template.
Definition at line 4438 of file classdef.cpp.
References m_impl, and ClassDefImpl::tempArgs.
Referenced by DocSets::addIndexItem(), flushCachedTemplateRelations(), getCanonicalTypeForIdentifier(), and newResolveTypedef().
isTemplateArgument()
bool ClassDef::isTemplateArgument () const
Definition at line 4468 of file classdef.cpp.
References ClassDefImpl::isTemplArg, and m_impl.
Referenced by getResolvedSymbol().
isUsedOnly()
bool ClassDef::isUsedOnly () const
Definition at line 4573 of file classdef.cpp.
References m_impl, and ClassDefImpl::usedOnly.
Referenced by getCanonicalTypeForIdentifier().
isVisibleInHierarchy()
bool ClassDef::isVisibleInHierarchy ()
the class is visible in a class diagram, or class hierarchy
the class is visible in a class diagram, or class hierarchy
isArtificial() &&
Definition at line 2765 of file classdef.cpp.
References Config_getBool, hasDocumentation(), hasNonReferenceSuperClass(), isAnonymous(), isReference(), ClassDefImpl::isStatic, m_impl, ClassDefImpl::prot, protectionLevelVisible(), and ClassDefImpl::templateMaster.
Referenced by NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), NestingContext::Private::addDerivedClasses(), DotGfxHierarchyTable::addHierarchy(), countClassesInTreeList(), countInheritanceNodes(), hasVisibleRoot(), DiagramRow::insertClass(), writeClassTree(), and writeClassTreeForList().
makeTemplateArgument()
void ClassDef::makeTemplateArgument (bool b = TRUE)
Definition at line 4558 of file classdef.cpp.
References ClassDefImpl::isTemplArg, and m_impl.
Referenced by findUsedClassesForClass().
memberNameInfoSDict()
MemberNameInfoSDict * ClassDef::memberNameInfoSDict () const
Returns a dictionary of all members.
This includes any inherited members. Members are sorted alphabetically.
Definition at line 4403 of file classdef.cpp.
References ClassDefImpl::allMemberNameInfoSDict, and m_impl.
Referenced by PerlModGenerator::addListOfAllMembers(), addMembersToTemplateInstance(), ClassContext::Private::allMembersList(), buildCompleteMemberLists(), computeClassRelations(), findUsedClassesForClass(), findUsingDeclImports(), mergeCategory(), mergeMembers(), and writeListOfAllMembers().
mergeCategory()
void ClassDef::mergeCategory (ClassDef * category)
Merges the members of a Objective-C category into this class.
Definition at line 3117 of file classdef.cpp.
References ClassDefImpl::allMemberNameInfoSDict, MemberInfo::ambigClass, MemberInfo::ambiguityResolutionScope, SDict< T >::append(), baseClasses(), BaseClassDef::classDef, combineDeclarationAndDefinition(), Config_getBool, MemberDef::deepCopy(), SDict< T >::find(), MemberInfo::inherited, insertBaseClass(), internalInsertMember(), isExtension(), isLocal(), SDict< MemberNameInfo >::Iterator, m_impl, MemberDef::makeImplementationDetail(), MemberInfo::memberDef, MemberNameInfo::memberName(), memberNameInfoSDict(), Doxygen::memberNameSDict, MemberDef::moveTo(), Definition::name(), MemberInfo::prot, MemberInfo::scopePath, Definition::setArtificial(), MemberDef::setCategory(), setCategoryOf(), MemberDef::setCategoryRelation(), and MemberInfo::virt.
Referenced by mergeCategories().
mergeMembers()
void ClassDef::mergeMembers ()
recusively merges the `all members' lists of a class base with that of this class. Must only be called for classes without subclasses!
Definition at line 2866 of file classdef.cpp.
References ClassDefImpl::allMemberNameInfoSDict, MemberInfo::ambigClass, MemberInfo::ambiguityResolutionScope, SDict< T >::append(), MemberDef::argumentList(), baseClasses(), BaseClassDef::classDef, compoundType(), Config_getBool, SDict< T >::find(), MemberDef::getClassDef(), MemberDef::getFileDef(), Definition::getLanguage(), getLanguageSpecificSeparator(), Definition::getOuterScope(), Interface, internalInsertMember(), isBaseClass(), MemberDef::isFriend(), isStandardFunc(), SDict< MemberNameInfo >::Iterator, m_impl, matchArguments2(), MemberInfo::memberDef, MemberNameInfo::memberName(), memberNameInfoSDict(), ClassDefImpl::membersMerged, mergeMembers(), Definition::name(), Normal, Private, MemberInfo::prot, BaseClassDef::prot, Protected, MemberDef::protection(), Public, MemberInfo::scopePath, SDict< T >::setAutoDelete(), MemberInfo::virt, and BaseClassDef::virt.
Referenced by buildCompleteMemberLists(), and mergeMembers().
protection()
Protection ClassDef::protection () const
Return the protection level (Public,Protected,Private) in which this compound was found.
Definition at line 4408 of file classdef.cpp.
References m_impl, and ClassDefImpl::prot.
Referenced by ClassListContext::Private::addClasses(), NestingContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), NestingContext::Private::addDerivedClasses(), VhdlDocGen::findMember(), generateXMLForClass(), VhdlDocGen::getClassName(), VhdlDocGen::getClassTitle(), insertSubClass(), ClassIndexContext::Private::list(), visibleInParentsDeclList(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeClassTree(), writeClassTreeForList(), VhdlDocGen::writeClassType(), ClassSDict::writeDeclaration(), writeDeclarationLink(), writeDocumentationForInnerClasses(), VhdlDocGen::writeInlineClassLink(), writeInnerClasses(), VhdlDocGen::writeOverview(), writeTagFile(), and VhdlDocGen::writeVHDLDeclaration().
qualifiedNameWithTemplateParameters()
QCString ClassDef::qualifiedNameWithTemplateParameters (QList< ArgumentList > * actualParams = 0, int * actualParamIndex = 0) const
Definition at line 3849 of file classdef.cpp.
References className(), Config_getBool, DefinitionIntf::definitionType(), Definition::getLanguage(), getLanguageSpecificSeparator(), Definition::getOuterScope(), isSpecialization(), Definition::localName(), Definition::qualifiedName(), qualifiedNameWithTemplateParameters(), tempArgListToString(), templateArguments(), and DefinitionIntf::TypeClass.
Referenced by addMethodToClass(), addVariableToClass(), displayName(), findMember(), getCanonicalTypeForIdentifier(), qualifiedNameWithTemplateParameters(), and trimTemplateSpecifiers().
reclassifyMember()
void ClassDef::reclassifyMember (MemberDef * md, MemberType t)
Definition at line 4588 of file classdef.cpp.
References insertMember(), m_impl, ClassDefImpl::memberLists, MemberList::remove(), and MemberDef::setMemberType().
Referenced by addVariableToClass().
removeMemberFromLists()
void ClassDef::removeMemberFromLists (MemberDef * md)
Definition at line 4672 of file classdef.cpp.
References m_impl, ClassDefImpl::memberLists, and MemberList::remove().
setCategoryOf()
void ClassDef::setCategoryOf (ClassDef * cd)
Definition at line 4563 of file classdef.cpp.
References ClassDefImpl::categoryOf, and m_impl.
Referenced by mergeCategory().
setClassName()
void ClassDef::setClassName (const char * name)
Definition at line 3920 of file classdef.cpp.
References ClassDefImpl::className, m_impl, and Definition::name().
Referenced by addVariableToFile(), and writeClassTree().
setClassSpecifier()
void ClassDef::setClassSpecifier (uint64 spec)
Definition at line 4692 of file classdef.cpp.
References m_impl, and ClassDefImpl::spec.
Referenced by addClassToContext().
setCompoundType()
void ClassDef::setCompoundType (CompoundType t)
Definition at line 4548 of file classdef.cpp.
References ClassDefImpl::compType, and m_impl.
Referenced by addClassToContext(), and findClassRelation().
setFileDef()
void ClassDef::setFileDef (FileDef * fd)
Definition at line 4528 of file classdef.cpp.
References ClassDefImpl::fileDef, and m_impl.
Referenced by addClassToContext(), and createTagLessInstance().
setGroupDefForAllMembers()
void ClassDef::setGroupDefForAllMembers (GroupDef * g, Grouping::GroupPri_t pri, const QCString & fileName, int startLine, bool hasDocs)
Definition at line 3609 of file classdef.cpp.
References GroupDef::addClass(), ClassDefImpl::allMemberNameInfoSDict, MemberDef::getClassDefOfAnonymousType(), GroupDef::insertMember(), SDict< MemberNameInfo >::Iterator, m_impl, MemberInfo::memberDef, MemberDef::setGroupDef(), and setGroupDefForAllMembers().
Referenced by addMemberToGroups(), and setGroupDefForAllMembers().
setIncludeFile()
void ClassDef::setIncludeFile (FileDef * fd, const char * incName, bool local, bool force)
Definition at line 838 of file classdef.cpp.
References IncludeInfo::fileDef, ClassDefImpl::incInfo, IncludeInfo::includeName, IncludeInfo::local, and m_impl.
Referenced by addIncludeFile().
setIsStatic()
void ClassDef::setIsStatic (bool b)
Definition at line 4543 of file classdef.cpp.
References ClassDefImpl::isStatic, and m_impl.
Referenced by addClassToContext().
setName()
void ClassDef::setName (const char * name) virtual
Sets a new name for the definition
Reimplemented from Definition.
Definition at line 4731 of file classdef.cpp.
References ClassDefImpl::isAnonymous, m_impl, and Definition::setName().
setNamespace()
void ClassDef::setNamespace (NamespaceDef * nd)
Definition at line 4523 of file classdef.cpp.
References m_impl, and ClassDefImpl::nspace.
setProtection()
void ClassDef::setProtection (Protection p)
Definition at line 4538 of file classdef.cpp.
References m_impl, and ClassDefImpl::prot.
Referenced by addClassToContext().
setSubGrouping()
void ClassDef::setSubGrouping (bool enabled)
Definition at line 4533 of file classdef.cpp.
References m_impl, and ClassDefImpl::subGrouping.
Referenced by addClassToContext().
setTagLessReference()
void ClassDef::setTagLessReference (ClassDef * cd)
Definition at line 4667 of file classdef.cpp.
References m_impl, and ClassDefImpl::tagLessRef.
Referenced by processTagLessClasses().
setTemplateArguments()
void ClassDef::setTemplateArguments (ArgumentList * al)
Definition at line 2625 of file classdef.cpp.
References m_impl, and ClassDefImpl::tempArgs.
Referenced by addClassToContext().
setTemplateBaseClassNames()
void ClassDef::setTemplateBaseClassNames (QDict< int > * templateNames)
Definition at line 3741 of file classdef.cpp.
References m_impl, and ClassDefImpl::templBaseClassNames.
Referenced by findTemplateInstanceRelation().
setTemplateMaster()
void ClassDef::setTemplateMaster (ClassDef * tm)
Definition at line 4553 of file classdef.cpp.
References m_impl, and ClassDefImpl::templateMaster.
Referenced by getVariableInstance(), and insertTemplateInstance().
setTypeConstraints()
void ClassDef::setTypeConstraints (ArgumentList * al)
Definition at line 2612 of file classdef.cpp.
References m_impl, and ClassDefImpl::typeConstraints.
Referenced by addClassToContext().
setUsedOnly()
void ClassDef::setUsedOnly (bool b)
Definition at line 4568 of file classdef.cpp.
References m_impl, and ClassDefImpl::usedOnly.
Referenced by addTypeConstraint(), and findUsedClassesForClass().
showUsedFiles()
void ClassDef::showUsedFiles (OutputList & ol) protected
Definition at line 1106 of file classdef.cpp.
References Config_getBool, OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::endItemList(), OutputList::endItemListItem(), ClassDefImpl::files, generatedFromFiles(), FileDef::generateSourceFile(), FileDef::getOutputFileBase(), FileDef::getPath(), Definition::getReference(), FileDef::getSourceFileBase(), FileDef::getVersion(), OutputGenerator::Html, FileDef::isLinkable(), m_impl, OutputGenerator::Man, FileDef::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startItemList(), OutputList::startItemListItem(), stripFromPath(), OutputList::writeObjectLink(), and OutputList::writeRuler().
Referenced by writeDocumentationContents().
sortMemberLists()
void ClassDef::sortMemberLists ()
Definition at line 4041 of file classdef.cpp.
References ClassDefImpl::innerClasses, m_impl, ClassDefImpl::memberLists, MemberList::needsSorting(), MemberList::setNeedsSorting(), MemberList::sort(), and SDict< T >::sort().
Referenced by sortMemberLists().
startMemberDeclarations()
void ClassDef::startMemberDeclarations (OutputList & ol) private
Definition at line 1490 of file classdef.cpp.
References OutputList::startMemberSections().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
startMemberDocumentation()
void ClassDef::startMemberDocumentation (OutputList & ol) private
Definition at line 1470 of file classdef.cpp.
References Config_getBool, OutputList::disable(), OutputGenerator::Html, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
subClasses()
BaseClassList * ClassDef::subClasses () const
Returns the list of sub classes that directly derive from this class.
Definition at line 4398 of file classdef.cpp.
References ClassDefImpl::inheritedBy, and m_impl.
Referenced by NestingNodeContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), NestingContext::Private::addDerivedClasses(), DotGfxHierarchyTable::addHierarchy(), buildCompleteMemberLists(), DotClassGraph::buildGraph(), classHasVisibleChildren(), countClassesInTreeList(), generateDEFForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), ClassContext::Private::inheritedBy(), DiagramRow::insertClass(), VhdlDocGen::isSubClass(), isSubClass(), writeClassTree(), and writeClassTreeForList().
subGrouping()
bool ClassDef::subGrouping () const
Definition at line 4726 of file classdef.cpp.
References m_impl, and ClassDefImpl::subGrouping.
Referenced by InheritedMemberInfoListContext::Private::addMemberGroupsOfClass(), and ClassContext::Private::memberGroups().
taggedInnerClasses()
const ClassList * ClassDef::taggedInnerClasses () const
Definition at line 4648 of file classdef.cpp.
References m_impl, and ClassDefImpl::taggedInnerClasses.
tagLessReference()
ClassDef * ClassDef::tagLessReference () const
Definition at line 4662 of file classdef.cpp.
References m_impl, and ClassDefImpl::tagLessRef.
templateArguments()
ArgumentList * ClassDef::templateArguments () const
Returns the template arguments of this class Will return 0 if not applicable.
Definition at line 4413 of file classdef.cpp.
References m_impl, and ClassDefImpl::tempArgs.
Referenced by addClassToContext(), addMembersToTemplateInstance(), ClassContext::Private::addTemplateDecls(), addTemplateList(), computeTemplateClassRelations(), findBaseClassesForClass(), findTemplateInstanceRelation(), findUsedClassesForClass(), getTemplateArgumentsFromName(), getTemplateParameterLists(), insertTemplateSpecifierInScope(), newResolveTypedef(), qualifiedNameWithTemplateParameters(), searchTemplateSpecs(), and writeTemplateList().
templateMaster()
ClassDef * ClassDef::templateMaster () const
Returns the template master of which this class is an instance.
Returns 0 if not applicable.
Definition at line 4433 of file classdef.cpp.
References m_impl, and ClassDefImpl::templateMaster.
Referenced by ClassListContext::Private::addClasses(), NestingContext::Private::addClasses(), addClassMemberNameToIndex(), addMemberToSearchIndex(), DotClassGraph::buildGraph(), countAnnotatedClasses(), RTFGenerator::endIndexSection(), LatexGenerator::endIndexSection(), generateClassList(), generateDEFForClass(), generateDocbookForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), ClassMembersIndexContext::Private::getMembersFiltered(), isBaseClass(), VhdlDocGen::isSubClass(), ClassIndexContext::Private::list(), RTFGenerator::startIndexSection(), LatexGenerator::startIndexSection(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeClassTree(), writeDocumentationForInnerClasses(), and writeTagFile().
templateTypeConstraints()
ConstraintClassDict * ClassDef::templateTypeConstraints () const
Definition at line 4463 of file classdef.cpp.
References ClassDefImpl::constraintClassDict, and m_impl.
Referenced by DotClassGraph::buildGraph().
title()
QCString ClassDef::title () const
Definition at line 2098 of file classdef.cpp.
References Class, ClassDefImpl::compType, Config_getBool, displayName(), VhdlDocGen::getClassTitle(), Definition::getLanguage(), Interface, isJavaEnum(), m_impl, Service, Singleton, SrcLangExt_Fortran, SrcLangExt_ObjC, SrcLangExt_VHDL, ClassDefImpl::tempArgs, theTranslator, Translator::trCompoundReference(), Translator::trCompoundReferenceFortran(), Translator::trEnumReference(), Translator::trServiceReference(), and Translator::trSingletonReference().
Referenced by internalInsertMember(), ClassContext::Private::title(), writeDocumentation(), and writeMemberDeclarations().
typeConstraints()
const ArgumentList * ClassDef::typeConstraints () const
Definition at line 4716 of file classdef.cpp.
References m_impl, and ClassDefImpl::typeConstraints.
Referenced by ClassContext::Private::typeConstraints().
usedByImplementationClasses()
UsesClassDict * ClassDef::usedByImplementationClasses () const
Definition at line 4453 of file classdef.cpp.
References m_impl, and ClassDefImpl::usedByImplClassDict.
Referenced by DotClassGraph::buildGraph().
usedFiles()
const FileList & ClassDef::usedFiles () const
Definition at line 4711 of file classdef.cpp.
References ClassDefImpl::files, and m_impl.
Referenced by UsedFilesContext::UsedFilesContext().
usedImplementationClasses()
UsesClassDict * ClassDef::usedImplementationClasses () const
Definition at line 4448 of file classdef.cpp.
References m_impl, and ClassDefImpl::usesImplClassDict.
Referenced by DotClassGraph::buildGraph().
usedInterfaceClasses()
UsesClassDict * ClassDef::usedInterfaceClasses () const
Definition at line 4458 of file classdef.cpp.
References m_impl, and ClassDefImpl::usesIntfClassDict.
visibleInParentsDeclList()
bool ClassDef::visibleInParentsDeclList () const
show this class in the declaration section of its parent?
Definition at line 1857 of file classdef.cpp.
References Config_getBool, isAnonymous(), isExtension(), isLinkable(), isLocal(), Private, and protection().
Referenced by writeDeclarationLink().
writeAdditionalInheritedMembers()
void ClassDef::writeAdditionalInheritedMembers (OutputList & ol) private
Definition at line 4187 of file classdef.cpp.
References LayoutDocManager::Class, Definition::getLanguage(), LayoutDocManager::instance(), LayoutDocEntry::kind(), LayoutDocEntry::MemberDecl, MemberListType_friends, LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDecl::type, visited, and writeInheritedMemberDeclarations().
Referenced by endMemberDeclarations().
writeAuthorSection()
void ClassDef::writeAuthorSection (OutputList & ol) private
Definition at line 1510 of file classdef.cpp.
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and OutputList::writeString().
Referenced by writeDocumentationContents().
writeBriefDescription()
void ClassDef::writeBriefDescription (OutputList & ol, bool exampleFlag) private
Definition at line 954 of file classdef.cpp.
References anchor(), Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), OutputList::generateDoc(), Definition::hasBriefDescription(), hasDetailedDescription(), OutputGenerator::Man, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startParagraph(), writeMoreLink(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentationContents().
writeCollaborationGraph()
void ClassDef::writeCollaborationGraph (OutputList & ol) private
Definition at line 1328 of file classdef.cpp.
References DotNode::Collaboration, Config_getBool, OutputList::disable(), displayName(), OutputList::endDotGraph(), DotClassGraph::isTrivial(), OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startDotGraph(), theTranslator, and Translator::trCollaborationDiagram().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeDeclaration()
void ClassDef::writeDeclaration (OutputList & ol, MemberDef * md, bool inGroup, ClassDef * inheritedFrom, const char * inheritId)
called from MemberDef::writeDeclaration() to (recusively) write the definition of an anonymous struct, union or class.
Definition at line 2679 of file classdef.cpp.
References MemberDef::anchor(), LayoutDocManager::Class, compoundTypeString(), displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberItem(), LayoutDocManager::instance(), isLinkable(), SIntDict< MemberGroup >::Iterator, LayoutDocEntry::kind(), m_impl, LayoutDocEntry::MemberDecl, ClassDefImpl::memberGroupSDict, MemberGroup::setInGroup(), OutputList::startBold(), LayoutDocEntryMemberDecl::type, OutputList::writeObjectLink(), MemberGroup::writePlainDeclarations(), and writePlainMemberDeclaration().
Referenced by MemberDef::writeDeclaration().
writeDeclarationLink()
void ClassDef::writeDeclarationLink (OutputList & ol, bool & found, const char * header, bool localNames)
Definition at line 1869 of file classdef.cpp.
References anchor(), VhdlDocGen::ARCHITECTURE, Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), compoundTypeString(), Config_getBool, displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), Definition::getLanguage(), getOutputFileBase(), VhdlDocGen::getProtectionName(), getReference(), OutputList::insertMemberAlign(), DocRoot::isEmpty(), isLinkable(), isLinkableInProject(), OutputList::parseText(), protection(), SrcLangExt_Fortran, SrcLangExt_VHDL, OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trCompounds(), Translator::trDataTypes(), VhdlDocGen::trVhdlType(), validatingParseDoc(), visibleInParentsDeclList(), OutputList::writeDoc(), writeMoreLink(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by ClassSDict::writeDeclaration().
writeDetailedDescription()
void ClassDef::writeDetailedDescription (OutputList & ol, const QCString & pageType, bool exampleFlag, const QCString & title, const QCString & anchor = QCString()) private
Definition at line 1039 of file classdef.cpp.
References anchor(), OutputList::disable(), OutputList::disableAllBut(), OutputList::endGroupHeader(), getOutputFileBase(), hasDetailedDescription(), OutputGenerator::Html, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), OutputList::writeAnchor(), writeDetailedDocumentationBody(), and OutputList::writeRuler().
Referenced by writeDocumentationContents().
writeDetailedDocumentationBody()
void ClassDef::writeDetailedDocumentationBody (OutputList & ol) private
Definition at line 981 of file classdef.cpp.
References Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), compoundTypeString(), Config_getBool, OutputList::disable(), Definition::docFile(), Definition::docLine(), Definition::documentation(), OutputList::endDescForItem(), OutputList::endSimpleSect(), OutputList::endTextBlock(), BaseOutputDocInterface::Examples, ClassDefImpl::exampleSDict, OutputList::generateDoc(), Definition::getLanguage(), hasExamples(), OutputGenerator::Html, m_impl, Definition::name(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_Cpp, OutputList::startDescForItem(), OutputList::startSimpleSect(), OutputList::startTextBlock(), theTranslator, Translator::trExamples(), ClassDefImpl::typeConstraints, writeExample(), Definition::writeSourceDef(), OutputList::writeString(), writeTemplateSpec(), and writeTypeConstraints().
Referenced by writeDetailedDescription(), and writeInlineDocumentation().
writeDocumentation()
void ClassDef::writeDocumentation (OutputList & ol)
Definition at line 2142 of file classdef.cpp.
References addClassAttributes(), addGroupListToTitle(), Config_getBool, displayName(), endFileWithNavPath(), OutputList::endQuickIndices(), endTitle(), Definition::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, HLI_ClassVisible, Definition::name(), OutputList::parseText(), startFile(), startTitle(), title(), writeDocumentationContents(), writeMemberPages(), and Definition::writeNavigationPath().
Referenced by generateClassList(), and writeDocumentationForInnerClasses().
writeDocumentationContents()
void ClassDef::writeDocumentationContents (OutputList & ol, const QCString & pageTitle) private
Definition at line 1976 of file classdef.cpp.
References IndexList::addIndexItem(), SearchIndexIntf::addWord(), anchor(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocManager::Class, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, compoundTypeString(), LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, OutputList::endContents(), endMemberDeclarations(), endMemberDocumentation(), err(), LayoutDocEntry::FileClasses, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, Definition::getLanguage(), LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, hasExamples(), Doxygen::indexList, LayoutDocManager::instance(), LayoutDocEntry::kind(), Definition::localName(), LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, Doxygen::searchIndex, SearchIndexIntf::setCurrentDoc(), showUsedFiles(), OutputList::startContents(), startMemberDeclarations(), startMemberDocumentation(), LayoutDocEntryMemberDecl::subtitle(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeCollaborationGraph(), writeDetailedDescription(), writeIncludeFiles(), writeInheritanceGraph(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), and writeNestedClasses().
Referenced by writeDocumentation().
writeDocumentationForInnerClasses()
void ClassDef::writeDocumentationForInnerClasses (OutputList & ol)
Definition at line 2247 of file classdef.cpp.
References ClassDefImpl::innerClasses, isEmbeddedInOuterScope(), isLinkableInProject(), SDict< ClassDef >::Iterator, m_impl, msg(), Definition::name(), protection(), protectionLevelVisible(), templateMaster(), writeDocumentation(), writeDocumentationForInnerClasses(), and writeMemberList().
Referenced by generateClassList(), and writeDocumentationForInnerClasses().
writeIncludeFiles()
void ClassDef::writeIncludeFiles (OutputList & ol) private
Definition at line 1363 of file classdef.cpp.
References OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), FileDef::docName(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTypewriter(), IncludeInfo::fileDef, Definition::getLanguage(), OutputGenerator::Html, ClassDefImpl::incInfo, IncludeInfo::includeName, FileDef::includeName(), includeStatement(), IncludeInfo::local, m_impl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_IDL, SrcLangExt_Java, OutputList::startParagraph(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentationContents().
writeInheritanceGraph()
void ClassDef::writeInheritanceGraph (OutputList & ol) private
Definition at line 1203 of file classdef.cpp.
References anchor(), BaseClassDef::classDef, Config_getBool, countInheritanceNodes(), OutputList::disable(), OutputList::disableAllBut(), displayName(), OutputList::docify(), OutputList::enable(), OutputList::enableAll(), OutputList::endClassDiagram(), OutputList::endDotGraph(), OutputList::endParagraph(), err(), getOutputFileBase(), getReference(), DotNode::Inheritance, ClassDefImpl::inheritedBy, ClassDefImpl::inherits, insertTemplateSpecifierInScope(), isLinkable(), DotClassGraph::isTooBig(), DotClassGraph::isTrivial(), m_impl, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startClassDiagram(), OutputList::startDotGraph(), OutputList::startParagraph(), BaseClassDef::templSpecifiers, theTranslator, Translator::trClassDiagram(), Translator::trInheritedByList(), Translator::trInheritsList(), writeInheritanceSpecifier(), and OutputList::writeObjectLink().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeInheritedMemberDeclarations()
void ClassDef::writeInheritedMemberDeclarations (OutputList & ol, MemberListType lt, int lt2, const QCString & title, ClassDef * inheritedFrom, bool invert, bool showAlways, QPtrDict< void > * visitedClasses) private
Definition at line 4236 of file classdef.cpp.
References BaseClassDef::classDef, convertProtectionLevel(), countMembersIncludingGrouped(), OutputList::disableAllBut(), OutputGenerator::Html, ClassDefImpl::inherits, isLinkable(), m_impl, OutputList::popGeneratorState(), BaseClassDef::prot, OutputList::pushGeneratorState(), and writeMemberDeclarations().
Referenced by writeAdditionalInheritedMembers(), and writeMemberDeclarations().
writeInlineClasses()
void ClassDef::writeInlineClasses (OutputList & ol) private
Definition at line 1462 of file classdef.cpp.
References ClassDefImpl::innerClasses, m_impl, and ClassSDict::writeDocumentation().
Referenced by writeDocumentationContents().
writeInlineDocumentation()
void ClassDef::writeInlineDocumentation (OutputList & ol)
Write class documentation inside another container (i.e.
a group)
Definition at line 1697 of file classdef.cpp.
References OutputList::addIndexItem(), anchor(), LayoutDocEntry::BriefDesc, LayoutDocManager::Class, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassInheritanceGraph, compoundTypeString(), OutputList::disable(), OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputList::endIndent(), endMemberDeclarations(), OutputList::endMemberDoc(), OutputList::endMemberDocName(), endMemberDocumentation(), Definition::getLanguage(), getOutputFileBase(), OutputGenerator::Html, LayoutDocManager::instance(), ClassDefImpl::isSimple, isSimple(), LayoutDocEntry::kind(), m_impl, OutputGenerator::Man, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, Definition::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), OutputList::startIndent(), startMemberDeclarations(), OutputList::startMemberDoc(), OutputList::startMemberDocName(), startMemberDocumentation(), LayoutDocEntryMemberDecl::subtitle(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, OutputList::writeAnchor(), writeCollaborationGraph(), writeDetailedDocumentationBody(), writeInheritanceGraph(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeSimpleMemberDocumentation(), and OutputList::writeString().
Referenced by ClassSDict::writeDocumentation().
writeMemberDeclarations()
void ClassDef::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title, const char * subTitle = 0, bool showInline = FALSE, ClassDef * inheritedFrom = 0, int lt2 = -1, bool invert = FALSE, bool showAlways = FALSE, QPtrDict< void > * visitedClasses = 0) private
Definition at line 4285 of file classdef.cpp.
References Config_getBool, Definition::getLanguage(), getMemberList(), SrcLangExt_VHDL, title(), visited, MemberList::writeDeclarations(), writeInheritedMemberDeclarations(), VhdlDocGen::writeInlineClassLink(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by writeDocumentationContents(), writeInheritedMemberDeclarations(), and writeInlineDocumentation().
writeMemberDocumentation()
void ClassDef::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title, bool showInline = FALSE) private
Definition at line 4351 of file classdef.cpp.
References displayName(), getMemberList(), and MemberList::writeDocumentation().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeMemberGroups()
void ClassDef::writeMemberGroups (OutputList & ol, bool showInline = FALSE) private
Definition at line 1430 of file classdef.cpp.
References MemberGroup::allMembersInSameSection(), SIntDict< MemberGroup >::Iterator, m_impl, ClassDefImpl::memberGroupSDict, SIntDict< T >::sort(), ClassDefImpl::subGrouping, and MemberGroup::writeDeclarations().
Referenced by writeDocumentationContents(), and writeInlineDocumentation().
writeMemberList()
void ClassDef::writeMemberList (OutputList & ol)
Definition at line 2272 of file classdef.cpp.
References ClassDefImpl::allMemberNameInfoSDict, MemberInfo::ambiguityResolutionScope, MemberDef::anchor(), anchor(), MemberDef::argsString(), MemberDef::category(), Config_getBool, OutputList::disableAllBut(), displayName(), OutputList::docify(), OutputList::endBold(), endFile(), OutputList::endParagraph(), OutputList::endQuickIndices(), endTitle(), MemberDef::getClassDef(), Definition::getLanguage(), getMemberListFileName(), MemberDef::getMemberSpecifiers(), Definition::getOuterScope(), MemberDef::getOutputFileBase(), getOutputFileBase(), MemberDef::getReference(), getReference(), Doxygen::globalScope, HLI_ClassVisible, OutputGenerator::Html, Definition::isArtificial(), MemberDef::isAttribute(), MemberDef::isBound(), MemberDef::isConstrained(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isExplicit(), MemberDef::isFriend(), MemberDef::isFunction(), MemberDef::isInline(), isLinkable(), MemberDef::isLinkable(), MemberDef::isMaybeAmbiguous(), MemberDef::isMaybeDefault(), MemberDef::isMaybeVoid(), MemberDef::isMutable(), MemberDef::isObjCMethod(), isObjectiveC(), MemberDef::isOptional(), MemberDef::isReadonly(), MemberDef::isRelated(), MemberDef::isRemovable(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isStatic(), MemberDef::isTransient(), MemberDef::isTypedef(), MemberDef::isUNOProperty(), SDict< MemberNameInfo >::Iterator, m_impl, MemberInfo::memberDef, Definition::name(), Normal, Package, OutputList::parseText(), OutputList::popGeneratorState(), Private, MemberInfo::prot, Protected, MemberDef::protection(), protectionLevelVisible(), Public, Pure, OutputList::pushGeneratorState(), SrcLangExt_IDL, SrcLangExt_ObjC, SrcLangExt_VHDL, OutputList::startBold(), OutputList::startContents(), startFile(), OutputList::startParagraph(), startTitle(), theTranslator, Translator::trDefinedIn(), Translator::trEnumName(), Translator::trEnumValue(), Translator::trIncludingInheritedMembers(), Translator::trMemberList(), Translator::trThisIsTheListOfAllMembers(), VhdlDocGen::trVhdlType(), MemberDef::typeString(), Virtual, MemberDef::virtualness(), Definition::writeNavigationPath(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by generateClassList(), and writeDocumentationForInnerClasses().
writeMemberPages()
void ClassDef::writeMemberPages (OutputList & ol)
Definition at line 2174 of file classdef.cpp.
References MemberList::countDocMembers(), OutputList::disableAllBut(), displayName(), OutputGenerator::Html, MemberList::listType(), m_impl, ClassDefImpl::memberLists, MemberListType_detailedLists, MemberList::numDocMembers(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), and MemberList::writeDocumentationPage().
Referenced by writeDocumentation().
writeMoreLink()
void ClassDef::writeMoreLink (OutputList & ol, const QCString & anchor) private
Definition at line 1814 of file classdef.cpp.
References anchor(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::endTextLink(), getOutputFileBase(), OutputGenerator::Html, OutputGenerator::Latex, OutputGenerator::Man, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, OutputList::startTextLink(), theTranslator, Translator::trMore(), and OutputList::writeString().
Referenced by writeBriefDescription(), and writeDeclarationLink().
writeNestedClasses()
void ClassDef::writeNestedClasses (OutputList & ol, const QCString & title) private
Definition at line 1453 of file classdef.cpp.
References ClassDefImpl::innerClasses, m_impl, and ClassSDict::writeDeclaration().
Referenced by writeDocumentationContents().
writePlainMemberDeclaration()
void ClassDef::writePlainMemberDeclaration (OutputList & ol, MemberListType lt, bool inGroup, ClassDef * inheritedFrom, const char * inheritId) private
Definition at line 4365 of file classdef.cpp.
References getMemberList(), MemberList::setInGroup(), and MemberList::writePlainDeclarations().
Referenced by writeDeclaration().
writeQuickMemberLinks()
void ClassDef::writeQuickMemberLinks (OutputList & ol, MemberDef * md) const virtual
Reimplemented from Definition.
Definition at line 2197 of file classdef.cpp.
References ClassDefImpl::allMemberNameInfoSDict, MemberDef::anchor(), Config_getBool, convertToHtml(), createSubDirs(), MemberDef::getClassDef(), MemberDef::getOutputFileBase(), Doxygen::htmlFileExtension, MemberDef::isEnumValue(), MemberDef::isLinkable(), MemberDef::isLinkableInProject(), SDict< MemberNameInfo >::Iterator, m_impl, MemberInfo::memberDef, Definition::name(), and OutputList::writeString().
writeSimpleMemberDocumentation()
void ClassDef::writeSimpleMemberDocumentation (OutputList & ol, MemberListType lt) private
Definition at line 4358 of file classdef.cpp.
References getMemberList(), and MemberList::writeSimpleDocumentation().
Referenced by writeInlineDocumentation().
writeSummaryLinks()
void ClassDef::writeSummaryLinks (OutputList & ol) virtual
Reimplemented from Definition.
Definition at line 1523 of file classdef.cpp.
References ClassDefImpl::allMemberNameInfoSDict, LayoutDocManager::Class, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassNestedClasses, Config_getBool, ClassSDict::declVisible(), MemberList::declVisible(), OutputList::disableAllBut(), Definition::getLanguage(), getMemberList(), getMemberListFileName(), OutputGenerator::Html, ClassDefImpl::innerClasses, LayoutDocManager::instance(), LayoutDocEntry::kind(), MemberList::listType(), MemberList::listTypeAsString(), m_impl, LayoutDocEntry::MemberDecl, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_VHDL, theTranslator, LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), Translator::trListOfAllMembers(), LayoutDocEntryMemberDecl::type, ClassDefImpl::vhdlSummaryTitles, OutputList::writeString(), and OutputList::writeSummaryLink().
writeTagFile()
void ClassDef::writeTagFile (FTextStream & tagFile)
Definition at line 1582 of file classdef.cpp.
References anchor(), LayoutDocManager::Class, BaseClassDef::classDef, LayoutDocEntry::ClassNestedClasses, compoundTypeString(), Config_getString, convertToXML(), endl(), getMemberList(), getOutputFileBase(), Doxygen::htmlFileExtension, Definition::id(), ClassDefImpl::inherits, ClassDefImpl::innerClasses, LayoutDocManager::instance(), isEmbeddedInOuterScope(), isLinkable(), isLinkableInProject(), isObjectiveC(), SDict< ClassDef >::Iterator, SIntDict< MemberGroup >::Iterator, LayoutDocEntry::kind(), m_impl, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, ClassDefImpl::memberGroupSDict, Argument::name, Definition::name(), Private, BaseClassDef::prot, Protected, protection(), protectionLevelVisible(), ClassDefImpl::tempArgs, templateMaster(), LayoutDocEntryMemberDecl::type, BaseClassDef::virt, Virtual, Definition::writeDocAnchorsToTagFile(), MemberGroup::writeTagFile(), and MemberList::writeTagFile().
Referenced by writeTagFile().
Member Data Documentation
m_impl
ClassDefImpl* ClassDef::m_impl private
Definition at line 456 of file classdef.h.
Referenced by addExample(), addGroupedInheritedMembers(), addInnerCompound(), addListReferences(), addMembersToMemberGroup(), addTaggedInnerClass(), addTypeConstraint(), addTypeConstraints(), addUsedByClass(), addUsedClass(), anchor(), baseClasses(), categoryOf(), ClassDef(), className(), collaborationGraphFileName(), compoundType(), compoundTypeString(), computeAnchors(), countInheritanceNodes(), countInheritedDecMembers(), countMemberDeclarations(), countMembersIncludingGrouped(), createMemberList(), displayName(), distributeMemberGroupDocumentation(), exampleList(), findInnerCompound(), findSectionsInDocumentation(), generatedFromFiles(), getClassSDict(), getFileDef(), getInstanceOutputFileBase(), getMemberByName(), getMemberGroupSDict(), getMemberList(), getMemberListFileName(), getMemberLists(), getNamespaceDef(), getOutputFileBase(), getReference(), getSourceFileBase(), getTemplateBaseClassNames(), getTemplateInstances(), getVariableInstance(), hasExamples(), hasNonReferenceSuperClass(), includeInfo(), inheritanceGraphFileName(), innerClasses(), insertBaseClass(), insertSubClass(), insertTemplateInstance(), insertUsedFile(), internalInsertMember(), isAbstract(), isAnonymous(), isEmbeddedInOuterScope(), isFinal(), isForwardDeclared(), isGeneric(), isJavaEnum(), isLinkable(), isLinkableInProject(), isLocal(), isPublished(), isReference(), isSealed(), isSimple(), isSmartPointer(), isTemplate(), isTemplateArgument(), isUsedOnly(), isVisibleInHierarchy(), makeTemplateArgument(), memberNameInfoSDict(), mergeCategory(), mergeMembers(), protection(), reclassifyMember(), removeMemberFromLists(), setCategoryOf(), setClassName(), setClassSpecifier(), setCompoundType(), setFileDef(), setGroupDefForAllMembers(), setIncludeFile(), setIsStatic(), setName(), setNamespace(), setProtection(), setSubGrouping(), setTagLessReference(), setTemplateArguments(), setTemplateBaseClassNames(), setTemplateMaster(), setTypeConstraints(), setUsedOnly(), showUsedFiles(), sortMemberLists(), subClasses(), subGrouping(), taggedInnerClasses(), tagLessReference(), templateArguments(), templateMaster(), templateTypeConstraints(), title(), typeConstraints(), usedByImplementationClasses(), usedFiles(), usedImplementationClasses(), usedInterfaceClasses(), writeDeclaration(), writeDetailedDocumentationBody(), writeDocumentationForInnerClasses(), writeIncludeFiles(), writeInheritanceGraph(), writeInheritedMemberDeclarations(), writeInlineClasses(), writeInlineDocumentation(), writeMemberGroups(), writeMemberList(), writeMemberPages(), writeNestedClasses(), writeQuickMemberLinks(), writeSummaryLinks(), writeTagFile(), and ~ClassDef().
visited
bool ClassDef::visited
Definition at line 407 of file classdef.h.
Referenced by NestingNodeContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), DotGfxHierarchyTable::addHierarchy(), ClassDef(), clearVisitFlags(), countAdditionalInheritedMembers(), distributeClassGroupRelations(), findBaseClassesForClass(), findUsedClassesForClass(), initBaseClassHierarchy(), initClassHierarchy(), resolveClassNestingRelations(), writeAdditionalInheritedMembers(), writeClassTree(), writeClassTreeForList(), and writeMemberDeclarations().
The documentation for this class was generated from the following files:
src/classdef.h
src/classdef.cpp