Doxygen: TemplateNodeTree Class Reference
TemplateNodeTree Class Reference
Class representing an 'tree' tag in a template.
Classes
struct TreeContext
Public Member Functions
TemplateNodeTree (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeTree ()
QCString renderChildren (const TreeContext *ctx)
void render (FTextStream &ts, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeTree >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Static Public Member Functions
static TemplateVariant renderChildrenStub (const void *ctx, const QValueList< TemplateVariant > &)
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeTree >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Private Attributes
ExprAst * m_treeExpr
TemplateNodeList m_treeNodes
Additional Inherited Members
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeTree >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeTree >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'tree' tag in a template.
Definition at line 3734 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeTree()
TemplateNodeTree::TemplateNodeTree (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 3745 of file template.cpp.
References TemplateNodeCreator< TemplateNodeTree >::m_templateName, m_treeExpr, m_treeNodes, TemplateParser::parse(), ExpressionParser::parse(), TemplateParser::removeNextToken(), TRACE, and TemplateParser::warn().
~TemplateNodeTree()
TemplateNodeTree::~TemplateNodeTree () inline
Definition at line 3761 of file template.cpp.
References m_treeExpr.
Member Function Documentation
render()
void TemplateNodeTree::render (FTextStream & ts, TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 3822 of file template.cpp.
References TemplateNodeCreator< TemplateNodeTree >::m_line, TemplateNodeCreator< TemplateNodeTree >::m_templateName, m_treeExpr, renderChildren(), ExprAst::resolve(), TemplateContextImpl::setLocation(), TemplateVariant::toList(), and TemplateContextImpl::warn().
renderChildren()
QCString TemplateNodeTree::renderChildren (const TreeContext * ctx) inline
Definition at line 3770 of file template.cpp.
References TemplateListIntf::count(), TemplateListIntf::createIterator(), TemplateListIntf::ConstIterator::current(), TemplateVariant::Delegate::fromFunction(), TemplateStructIntf::get(), TemplateVariant::isValid(), TemplateNodeTree::TreeContext::list, TemplateNodeCreator< TemplateNodeTree >::m_line, TemplateNodeCreator< TemplateNodeTree >::m_templateName, m_treeNodes, TemplateContext::pop(), TemplateContext::push(), TemplateNodeList::render(), renderChildrenStub(), TemplateContext::set(), TemplateVariant::setRaw(), TemplateNodeTree::TreeContext::templateCtx, TemplateListIntf::ConstIterator::toFirst(), TemplateVariant::toList(), TemplateListIntf::ConstIterator::toNext(), TemplateVariant::toStruct(), TemplateVariant::typeAsString(), and TemplateContextImpl::warn().
Referenced by render(), and renderChildrenStub().
renderChildrenStub()
static TemplateVariant TemplateNodeTree::renderChildrenStub (const void * ctx, const QValueList< TemplateVariant > &) inline static
Definition at line 3765 of file template.cpp.
References renderChildren().
Referenced by renderChildren().
Member Data Documentation
m_treeExpr
ExprAst* TemplateNodeTree::m_treeExpr private
Definition at line 3842 of file template.cpp.
Referenced by render(), TemplateNodeTree(), and ~TemplateNodeTree().
m_treeNodes
TemplateNodeList TemplateNodeTree::m_treeNodes private
Definition at line 3843 of file template.cpp.
Referenced by renderChildren(), and TemplateNodeTree().
The documentation for this class was generated from the following file:
src/template.cpp