Doxygen: TreeDiagram Class Reference
TreeDiagram Class Reference
Class represeting the tree layout for the built-in class diagram.
Public Member Functions
TreeDiagram (ClassDef *root, bool doBases)
~TreeDiagram ()
void computeLayout ()
uint computeRows ()
void moveChildren (DiagramItem *root, int dx)
void computeExtremes (uint *labelWidth, uint *xpos)
void drawBoxes (FTextStream &t, Image *image, bool doBase, bool bitmap, uint baseRows, uint superRows, uint cellWidth, uint cellHeight, QCString relPath="", bool generateMap=TRUE)
void drawConnectors (FTextStream &t, Image *image, bool doBase, bool bitmap, uint baseRows, uint superRows, uint cellWidth, uint cellheight)
Private Member Functions
bool layoutTree (DiagramItem *root, int row)
TreeDiagram & operator= (const TreeDiagram &)
TreeDiagram (const TreeDiagram &)
Detailed Description
Class represeting the tree layout for the built-in class diagram.
Definition at line 111 of file diagram.cpp.
Constructor & Destructor Documentation
TreeDiagram() [1/2]
TreeDiagram::TreeDiagram (ClassDef * root, bool doBases)
Definition at line 409 of file diagram.cpp.
References DiagramRow::insertClass(), Normal, and Public.
~TreeDiagram()
TreeDiagram::~TreeDiagram ()
Definition at line 417 of file diagram.cpp.
TreeDiagram() [2/2]
TreeDiagram::TreeDiagram (const TreeDiagram &) private
Member Function Documentation
computeExtremes()
void TreeDiagram::computeExtremes (uint * labelWidth, uint * xpos)
Definition at line 555 of file diagram.cpp.
References DiagramItem::isInList(), DiagramItem::label(), Image::stringLength, and DiagramItem::xPos().
Referenced by ClassDiagram::writeFigure(), and ClassDiagram::writeImage().
computeLayout()
void TreeDiagram::computeLayout ()
Definition at line 475 of file diagram.cpp.
References DiagramItem::getChildren(), gridWidth, layoutTree(), maxTreeWidth, DiagramItem::move(), DiagramItem::parentItem(), and DiagramItem::putInList().
Referenced by ClassDiagram::ClassDiagram().
computeRows()
uint TreeDiagram::computeRows ()
Definition at line 525 of file diagram.cpp.
References DiagramItem::parentItem().
Referenced by ClassDiagram::writeFigure(), and ClassDiagram::writeImage().
drawBoxes()
void TreeDiagram::drawBoxes (FTextStream & t, Image * image, bool doBase, bool bitmap, uint baseRows, uint superRows, uint cellWidth, uint cellHeight, QCString relPath = "", bool generateMap = TRUE)
Definition at line 576 of file diagram.cpp.
References DiagramItem::getChildren(), DiagramItem::getClassDef(), Image::getHeight(), gridHeight, gridWidth, DiagramItem::isInList(), ClassDef::isLinkable(), labelHorSpacing, labelVertSpacing, DiagramItem::parentItem(), writeBitmapBox(), writeMapArea(), writeVectorBox(), DiagramItem::xPos(), and DiagramItem::yPos().
Referenced by ClassDiagram::writeFigure(), and ClassDiagram::writeImage().
drawConnectors()
void TreeDiagram::drawConnectors (FTextStream & t, Image * image, bool doBase, bool bitmap, uint baseRows, uint superRows, uint cellWidth, uint cellheight)
Definition at line 706 of file diagram.cpp.
References Image::drawHorzArrow(), Image::drawHorzLine(), Image::drawVertArrow(), Image::drawVertLine(), endl(), DiagramItem::getChildren(), Image::getHeight(), getMinProtectionLevel(), gridHeight, gridWidth, DiagramItem::isInList(), labelHorSpacing, labelVertSpacing, DiagramItem::parentItem(), DiagramItem::protection(), protToColor(), protToMask(), protToString(), DiagramItem::xPos(), and DiagramItem::yPos().
Referenced by ClassDiagram::writeFigure(), and ClassDiagram::writeImage().
layoutTree()
bool TreeDiagram::layoutTree (DiagramItem * root, int row) private
Definition at line 434 of file diagram.cpp.
References DiagramItem::avgChildPos(), DiagramItem::getChildren(), DiagramItem::isInList(), DiagramItem::number(), and DiagramItem::xPos().
Referenced by computeLayout().
moveChildren()
void TreeDiagram::moveChildren (DiagramItem * root, int dx)
Definition at line 422 of file diagram.cpp.
References DiagramItem::getChildren(), and DiagramItem::move().
Referenced by ClassDiagram::ClassDiagram().
operator=()
TreeDiagram& TreeDiagram::operator= (const TreeDiagram &) private
The documentation for this class was generated from the following file:
src/diagram.cpp