Doxygen: src/dirdef.h File Reference
dirdef.h File Reference
#include "sortdict.h"
#include "definition.h"
#include <qlist.h>
Classes
class DirList
A list of directories.
class DirDef
A model of a directory symbol.
class FilePair
Class representing a pair of FileDef objects.
class FilePairDict
A sorted dictionary of FilePair objects.
class UsedDir
Usage information of a directory.
class DirRelation
A usage relation between two directories.
class DirSDict
A sorted dictionary of DirDef objects.
Functions
void buildDirectories ()
void generateDirDocs (OutputList &ol)
void computeDirDependencies ()
void writeDirDependencyGraph (const char *file)
Function Documentation
buildDirectories()
void buildDirectories ()
Definition at line 921 of file dirdef.cpp.
References DirDef::addFile(), DirDef::addSubDir(), computeCommonDirPrefix(), Doxygen::directories, SDict< T >::find(), FileDef::getPath(), Definition::getReference(), Doxygen::inputNameList, FileDef::isDocumentationFile(), SDict< DirDef >::Iterator, DirDef::mergeDirectoryInTree(), Definition::name(), DirDef::sort(), and SDict< T >::sort().
Referenced by parseInput().
computeDirDependencies()
void computeDirDependencies ()
Definition at line 977 of file dirdef.cpp.
References DirDef::computeDependencies(), Doxygen::directories, SDict< DirDef >::Iterator, and DirDef::setLevel().
Referenced by parseInput().
generateDirDocs()
void generateDirDocs (OutputList & ol)
Definition at line 995 of file dirdef.cpp.
References Config_getBool, Doxygen::directories, Doxygen::dirRelations, SDict< DirDef >::Iterator, DirDef::writeDocumentation(), and DirRelation::writeDocumentation().
Referenced by generateOutput().
writeDirDependencyGraph()
void writeDirDependencyGraph (const char * file)