Doxygen: src/doctokenizer.h File Reference
doctokenizer.h File Reference
#include <qcstring.h>
#include <qlist.h>
#include <stdio.h>
#include "htmlattrib.h"
Classes
struct TokenInfo
Data associated with a token used by the comment block parser.
Enumerations
enum Tokens {
TK_WORD = 1, TK_LNKWORD = 2, TK_WHITESPACE = 3, TK_LISTITEM = 4,
TK_ENDLIST = 5, TK_COMMAND = 6, TK_HTMLTAG = 7, TK_SYMBOL = 8,
TK_NEWPARA = 9, TK_RCSTAG = 10, TK_URL = 11, RetVal_OK = 0x10000,
RetVal_SimpleSec = 0x10001, RetVal_ListItem = 0x10002, RetVal_Section = 0x10003, RetVal_Subsection = 0x10004,
RetVal_Subsubsection = 0x10005, RetVal_Paragraph = 0x10006, RetVal_SubParagraph = 0x10007, RetVal_EndList = 0x10008,
RetVal_EndPre = 0x10009, RetVal_DescData = 0x1000A, RetVal_DescTitle = 0x1000B, RetVal_EndDesc = 0x1000C,
RetVal_TableRow = 0x1000D, RetVal_TableCell = 0x1000E, RetVal_TableHCell = 0x1000F, RetVal_EndTable = 0x10010,
RetVal_Internal = 0x10011, RetVal_SwitchLang = 0x10012, RetVal_CloseXml = 0x10013, RetVal_EndBlockQuote = 0x10014,
RetVal_CopyDoc = 0x10015, RetVal_EndInternal = 0x10016, RetVal_EndParBlock = 0x10017
}
Functions
const char * tokToString (int token)
void doctokenizerYYFindSections (const char *input, Definition *d, MemberGroup *mg, const char *fileName)
void doctokenizerYYinit (const char *input, const char *fileName)
void doctokenizerYYcleanup ()
void doctokenizerYYpushContext ()
bool doctokenizerYYpopContext ()
int doctokenizerYYlex ()
void doctokenizerYYsetStatePara ()
void doctokenizerYYsetStateTitle ()
void doctokenizerYYsetStateTitleAttrValue ()
void doctokenizerYYsetStateCode ()
void doctokenizerYYsetStateXmlCode ()
void doctokenizerYYsetStateHtmlOnly ()
void doctokenizerYYsetStateManOnly ()
void doctokenizerYYsetStateLatexOnly ()
void doctokenizerYYsetStateXmlOnly ()
void doctokenizerYYsetStateDbOnly ()
void doctokenizerYYsetStateRtfOnly ()
void doctokenizerYYsetStateVerbatim ()
void doctokenizerYYsetStateDot ()
void doctokenizerYYsetStateMsc ()
void doctokenizerYYsetStateParam ()
void doctokenizerYYsetStateXRefItem ()
void doctokenizerYYsetStateFile ()
void doctokenizerYYsetStatePattern ()
void doctokenizerYYsetStateLink ()
void doctokenizerYYsetStateCite ()
void doctokenizerYYsetStateRef ()
void doctokenizerYYsetStateInternalRef ()
void doctokenizerYYsetStateText ()
void doctokenizerYYsetStateSkipTitle ()
void doctokenizerYYsetStateAnchor ()
void doctokenizerYYsetInsidePre (bool b)
void doctokenizerYYpushBackHtmlTag (const char *tag)
void doctokenizerYYsetStateSnippet ()
void doctokenizerYYstartAutoList ()
void doctokenizerYYendAutoList ()
void doctokenizerYYsetStatePlantUML ()
void doctokenizerYYsetStateSetScope ()
void doctokenizerYYsetStatePlantUMLOpt ()
Variables
TokenInfo * g_token
int doctokenizerYYlineno
FILE * doctokenizerYYin
Enumeration Type Documentation
Tokens
enum Tokens
Enumerator
TK_WORD
TK_LNKWORD
TK_WHITESPACE
TK_LISTITEM
TK_ENDLIST
TK_COMMAND
TK_HTMLTAG
TK_SYMBOL
TK_NEWPARA
TK_RCSTAG
TK_URL
RetVal_OK
RetVal_SimpleSec
RetVal_ListItem
RetVal_Section
RetVal_Subsection
RetVal_Subsubsection
RetVal_Paragraph
RetVal_SubParagraph
RetVal_EndList
RetVal_EndPre
RetVal_DescData
RetVal_DescTitle
RetVal_EndDesc
RetVal_TableRow
RetVal_TableCell
RetVal_TableHCell
RetVal_EndTable
RetVal_Internal
RetVal_SwitchLang
RetVal_CloseXml
RetVal_EndBlockQuote
RetVal_CopyDoc
RetVal_EndInternal
RetVal_EndParBlock
Definition at line 30 of file doctokenizer.h.
Function Documentation
doctokenizerYYcleanup()
void doctokenizerYYcleanup ()
doctokenizerYYendAutoList()
void doctokenizerYYendAutoList ()
Referenced by DocAutoList::parse().
doctokenizerYYFindSections()
void doctokenizerYYFindSections (const char * input, Definition * d, MemberGroup * mg, const char * fileName)
Referenced by docFindSections().
doctokenizerYYinit()
void doctokenizerYYinit (const char * input, const char * fileName)
Referenced by internalValidatingParseDoc(), validatingParseDoc(), and validatingParseText().
doctokenizerYYlex()
int doctokenizerYYlex ()
Referenced by defaultHandleTitleAndSize(), defaultHandleToken(), handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), handleInternalRef(), DocPara::handleLink(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleStartCode(), handleStyleArgument(), DocPara::handleXRefItem(), DocIndexEntry::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocHtmlList::parse(), DocPara::parse(), DocParamList::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocText::parse(), DocHtmlList::parseXml(), DocHtmlRow::parseXml(), and DocHtmlTable::parseXml().
doctokenizerYYpopContext()
bool doctokenizerYYpopContext ()
Referenced by docParserPopContext().
doctokenizerYYpushBackHtmlTag()
void doctokenizerYYpushBackHtmlTag (const char * tag)
Referenced by DocHtmlDescList::parse(), DocHtmlList::parse(), DocHtmlRow::parse(), DocHtmlList::parseXml(), and DocHtmlRow::parseXml().
doctokenizerYYpushContext()
void doctokenizerYYpushContext ()
Referenced by docParserPushContext().
doctokenizerYYsetInsidePre()
void doctokenizerYYsetInsidePre (bool b)
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
doctokenizerYYsetStateAnchor()
void doctokenizerYYsetStateAnchor ()
Referenced by handleAnchor().
doctokenizerYYsetStateCite()
void doctokenizerYYsetStateCite ()
Referenced by DocPara::handleCite().
doctokenizerYYsetStateCode()
void doctokenizerYYsetStateCode ()
Referenced by DocPara::handleCommand().
doctokenizerYYsetStateDbOnly()
void doctokenizerYYsetStateDbOnly ()
Referenced by defaultHandleToken(), and DocPara::handleCommand().
doctokenizerYYsetStateDot()
void doctokenizerYYsetStateDot ()
Referenced by DocPara::handleCommand().
doctokenizerYYsetStateFile()
void doctokenizerYYsetStateFile ()
Referenced by DocPara::handleFile(), DocPara::handleImage(), and DocPara::handleInclude().
doctokenizerYYsetStateHtmlOnly()
void doctokenizerYYsetStateHtmlOnly ()
Referenced by defaultHandleToken(), and DocPara::handleCommand().
doctokenizerYYsetStateInternalRef()
void doctokenizerYYsetStateInternalRef ()
Referenced by handleInternalRef().
doctokenizerYYsetStateLatexOnly()
void doctokenizerYYsetStateLatexOnly ()
Referenced by defaultHandleToken(), and DocPara::handleCommand().
doctokenizerYYsetStateLink()
void doctokenizerYYsetStateLink ()
Referenced by DocPara::handleLink(), and DocHtmlDescTitle::parse().
doctokenizerYYsetStateManOnly()
void doctokenizerYYsetStateManOnly ()
Referenced by defaultHandleToken(), and DocPara::handleCommand().
doctokenizerYYsetStateMsc()
void doctokenizerYYsetStateMsc ()
Referenced by DocPara::handleCommand().
doctokenizerYYsetStatePara()
void doctokenizerYYsetStatePara ()
Referenced by defaultHandleTitleAndSize(), defaultHandleToken(), handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleHtmlStartTag(), DocPara::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocPara::handleLink(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleStartCode(), DocPara::handleXRefItem(), DocIndexEntry::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocHtmlDescTitle::parse(), DocSecRefItem::parse(), DocParamList::parse(), and DocRoot::parse().
doctokenizerYYsetStateParam()
void doctokenizerYYsetStateParam ()
Referenced by DocParamList::parse().
doctokenizerYYsetStatePattern()
void doctokenizerYYsetStatePattern ()
Referenced by DocPara::handleIncludeOperator().
doctokenizerYYsetStatePlantUML()
void doctokenizerYYsetStatePlantUML ()
Referenced by DocPara::handleCommand().
doctokenizerYYsetStatePlantUMLOpt()
void doctokenizerYYsetStatePlantUMLOpt ()
Referenced by DocPara::handleCommand().
doctokenizerYYsetStateRef()
void doctokenizerYYsetStateRef ()
Referenced by DocPara::handleRef(), and DocHtmlDescTitle::parse().
doctokenizerYYsetStateRtfOnly()
void doctokenizerYYsetStateRtfOnly ()
Referenced by defaultHandleToken(), and DocPara::handleCommand().
doctokenizerYYsetStateSetScope()
void doctokenizerYYsetStateSetScope ()
Referenced by defaultHandleToken().
doctokenizerYYsetStateSkipTitle()
void doctokenizerYYsetStateSkipTitle ()
Referenced by DocPara::handleSection().
doctokenizerYYsetStateSnippet()
void doctokenizerYYsetStateSnippet ()
Referenced by DocPara::handleInclude().
doctokenizerYYsetStateText()
void doctokenizerYYsetStateText ()
Referenced by DocText::parse().
doctokenizerYYsetStateTitle()
void doctokenizerYYsetStateTitle ()
Referenced by defaultHandleTitleAndSize(), DocIndexEntry::parse(), DocTitle::parse(), DocVhdlFlow::parse(), and DocSecRefItem::parse().
doctokenizerYYsetStateTitleAttrValue()
void doctokenizerYYsetStateTitleAttrValue ()
Referenced by defaultHandleTitleAndSize().
doctokenizerYYsetStateVerbatim()
void doctokenizerYYsetStateVerbatim ()
Referenced by DocPara::handleCommand().
doctokenizerYYsetStateXmlCode()
void doctokenizerYYsetStateXmlCode ()
Referenced by DocPara::handleHtmlStartTag().
doctokenizerYYsetStateXmlOnly()
void doctokenizerYYsetStateXmlOnly ()
Referenced by defaultHandleToken(), and DocPara::handleCommand().
doctokenizerYYsetStateXRefItem()
void doctokenizerYYsetStateXRefItem ()
Referenced by DocPara::handleXRefItem().
doctokenizerYYstartAutoList()
void doctokenizerYYstartAutoList ()
Referenced by DocAutoList::parse().
tokToString()
const char* tokToString (int token)
Referenced by defaultHandleTitleAndSize(), defaultHandleToken(), handleAnchor(), DocPara::handleCite(), DocPara::handleFile(), DocPara::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), handleInternalRef(), DocPara::handleLink(), DocPara::handleRef(), DocPara::handleSection(), handleStyleArgument(), DocIndexEntry::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocText::parse(), DocHtmlList::parseXml(), and DocHtmlRow::parseXml().
Variable Documentation
doctokenizerYYin
FILE* doctokenizerYYin
doctokenizerYYlineno
int doctokenizerYYlineno
Referenced by defaultHandleTitleAndSize(), defaultHandleToken(), detectNoDocumentedParams(), DocAnchor::DocAnchor(), DocCite::DocCite(), DocFormula::DocFormula(), DocHtmlCaption::DocHtmlCaption(), DocLink::DocLink(), docParserPopContext(), docParserPushContext(), DocRef::DocRef(), findAndCopyImage(), handleAHref(), handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocPara::handleImage(), handleImg(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), handleInternalRef(), DocPara::handleLink(), handleLinkedWord(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleStartCode(), handleStyleArgument(), handleStyleLeave(), handleUnclosedStyleCommands(), DocInclude::parse(), DocIndexEntry::parse(), DocCopy::parse(), DocTitle::parse(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocInternal::parse(), DocHtmlList::parse(), DocPara::parse(), DocParamList::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocText::parse(), DocRoot::parse(), DocHtmlList::parseXml(), DocParamList::parseXml(), DocHtmlRow::parseXml(), processCopyDoc(), readTextFileByName(), validatingParseDoc(), and validatingParseText().
g_token
TokenInfo* g_token
Referenced by defaultHandleTitleAndSize(), defaultHandleToken(), docParserPopContext(), docParserPushContext(), handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), DocPara::handleFile(), DocPara::handleHtmlStartTag(), DocPara::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), handleInternalRef(), DocPara::handleLink(), handleLinkedWord(), handleParameterType(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleStartCode(), handleStyleArgument(), DocPara::handleXRefItem(), DocPara::injectToken(), DocIndexEntry::parse(), DocAutoList::parse(), DocAutoListItem::parse(), DocTitle::parse(), DocVhdlFlow::parse(), DocLink::parse(), DocRef::parse(), DocInternalRef::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocInternal::parse(), DocHtmlList::parse(), DocPara::parse(), DocParamList::parse(), DocHtmlDescData::parse(), DocHtmlCell::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocText::parse(), DocRoot::parse(), DocSimpleSect::parseRcs(), DocHtmlList::parseXml(), DocParamList::parseXml(), DocHtmlCell::parseXml(), DocHtmlRow::parseXml(), and DocHtmlTable::parseXml().