Doxygen: ObjCache Class Reference
ObjCache Class Reference
Cache for objects.
#include <objcache.h>
Classes
struct CacheNode
struct HashNode
Public Member Functions
ObjCache (unsigned int logSize)
~ObjCache ()
int add (void *obj, void **victim)
void use (int handle)
void del (int handle)
void printLRU ()
void printStats ()
int size () const
int count () const
int hits () const
int misses () const
Private Member Functions
void moveToFront (int index)
unsigned int hash (void *addr)
HashNode * hashFind (void *obj)
HashNode * hashInsert (void *obj)
void hashRemove (void *obj)
Private Attributes
CacheNode * m_cache
HashNode * m_hash
int m_head
int m_tail
int m_size
int m_count
int m_freeHashNodes
int m_freeCacheNodes
int m_lastHandle
int m_misses
int m_hits
Detailed Description
Cache for objects.
This cache is used to decide which objects should remain in memory. It uses a least recently used policy (LRU) to decide which object should make room for a new object when the cache is full. An object should be added using add(), and then use() should be called when the object is used.
Definition at line 33 of file objcache.h.
Constructor & Destructor Documentation
ObjCache()
ObjCache::ObjCache (unsigned int logSize)
Creates the cache. The number of elements in the cache is 2 to the power of logSize.
Definition at line 28 of file objcache.cpp.
References m_cache, m_hash, m_hits, m_misses, m_size, ObjCache::CacheNode::next, and ObjCache::HashNode::nextHash.
~ObjCache()
ObjCache::~ObjCache ()
Deletes the cache and free all internal data-structures used.
Definition at line 46 of file objcache.cpp.
References m_cache, and m_hash.
Member Function Documentation
add()
int ObjCache::add (void * obj, void ** victim)
Adds obj to the cache. When victim is not null, this object is removed from the cache to make room for obj. Returns a handle to the object, which can be used by the use() function, each time the object is used.
Definition at line 52 of file objcache.cpp.
References hashFind(), hashInsert(), hashRemove(), ObjCache::HashNode::index, m_cache, m_count, m_freeCacheNodes, m_head, m_hits, m_misses, m_tail, moveToFront(), ObjCache::CacheNode::next, ObjCache::CacheNode::obj, and ObjCache::CacheNode::prev.
count()
int ObjCache::count () const inline
number of elements in the cache
Definition at line 94 of file objcache.h.
References m_count.
del()
void ObjCache::del (int handle)
Removes the item identified by handle from the cache.
See also
add()
Definition at line 105 of file objcache.cpp.
References hashRemove(), m_cache, m_count, m_freeCacheNodes, m_head, m_tail, moveToFront(), ObjCache::CacheNode::next, ObjCache::CacheNode::obj, and ObjCache::CacheNode::prev.
hash()
unsigned int ObjCache::hash (void * addr) private
Definition at line 175 of file objcache.cpp.
References m_size.
Referenced by hashFind(), hashInsert(), and hashRemove().
hashFind()
ObjCache::HashNode * ObjCache::hashFind (void * obj) private
Definition at line 206 of file objcache.cpp.
References hash(), ObjCache::HashNode::head, m_hash, and ObjCache::HashNode::nextHash.
Referenced by add().
hashInsert()
ObjCache::HashNode * ObjCache::hashInsert (void * obj) private
Definition at line 225 of file objcache.cpp.
References hash(), ObjCache::HashNode::head, m_freeHashNodes, m_hash, ObjCache::HashNode::nextHash, and ObjCache::HashNode::obj.
Referenced by add().
hashRemove()
void ObjCache::hashRemove (void * obj) private
Definition at line 255 of file objcache.cpp.
References hash(), ObjCache::HashNode::head, ObjCache::HashNode::index, m_freeHashNodes, m_hash, ObjCache::HashNode::nextHash, and ObjCache::HashNode::obj.
Referenced by add(), and del().
hits()
int ObjCache::hits () const inline
Definition at line 96 of file objcache.h.
References m_hits.
misses()
int ObjCache::misses () const inline
Definition at line 100 of file objcache.h.
References m_misses.
moveToFront()
void ObjCache::moveToFront (int index) private
Definition at line 155 of file objcache.cpp.
References m_cache, m_head, m_tail, ObjCache::CacheNode::next, and ObjCache::CacheNode::prev.
Referenced by add(), del(), and use().
printLRU()
void ObjCache::printLRU ()
Debug function. Prints the LRU list
printStats()
void ObjCache::printStats ()
Print miss/hits statistics
Definition at line 149 of file objcache.cpp.
References cache_stats_printf, m_hits, and m_misses.
size()
int ObjCache::size () const inline
total size of the cache
Definition at line 91 of file objcache.h.
References m_size.
use()
void ObjCache::use (int handle) inline
Indicates that this object is used. This will move the object to the front of the internal LRU list to make sure it is removed last. The parameter handle is returned when called add().
Definition at line 72 of file objcache.h.
References m_hits, m_lastHandle, and moveToFront().
Member Data Documentation
m_cache
CacheNode* ObjCache::m_cache private
Definition at line 113 of file objcache.h.
Referenced by add(), del(), moveToFront(), ObjCache(), and ~ObjCache().
m_count
int ObjCache::m_count private
Definition at line 118 of file objcache.h.
Referenced by add(), count(), and del().
m_freeCacheNodes
int ObjCache::m_freeCacheNodes private
Definition at line 120 of file objcache.h.
Referenced by add(), and del().
m_freeHashNodes
int ObjCache::m_freeHashNodes private
Definition at line 119 of file objcache.h.
Referenced by hashInsert(), and hashRemove().
m_hash
HashNode* ObjCache::m_hash private
Definition at line 114 of file objcache.h.
Referenced by hashFind(), hashInsert(), hashRemove(), ObjCache(), and ~ObjCache().
m_head
int ObjCache::m_head private
Definition at line 115 of file objcache.h.
Referenced by add(), del(), and moveToFront().
m_hits
int ObjCache::m_hits private
Definition at line 123 of file objcache.h.
Referenced by add(), hits(), ObjCache(), printStats(), and use().
m_lastHandle
int ObjCache::m_lastHandle private
Definition at line 121 of file objcache.h.
Referenced by use().
m_misses
int ObjCache::m_misses private
Definition at line 122 of file objcache.h.
Referenced by add(), misses(), ObjCache(), and printStats().
m_size
int ObjCache::m_size private
Definition at line 117 of file objcache.h.
Referenced by hash(), ObjCache(), and size().
m_tail
int ObjCache::m_tail private
Definition at line 116 of file objcache.h.
Referenced by add(), del(), and moveToFront().
The documentation for this class was generated from the following files:
src/objcache.h
src/objcache.cpp