Doxygen: UsedIndexLetters Class Reference
UsedIndexLetters Class Reference
Public Member Functions
UsedIndexLetters ()
void add (uint letter)
Public Member Functions inherited from SIntDict< uint >
SIntDict (int size=17)
virtual ~SIntDict ()
void append (int key, const uint *d)
void prepend (int key, const uint *d)
bool remove (int key)
void sort ()
void inSort (int key, const uint *d)
void setAutoDelete (bool val)
uint * find (int key)
uint * operator[] (int key) const
uint * at (uint i)
void clear ()
int count () const
Private Member Functions
int compareValues (const uint *p1, const uint *p2) const
Detailed Description
Definition at line 1741 of file index.cpp.
Constructor & Destructor Documentation
UsedIndexLetters()
UsedIndexLetters::UsedIndexLetters () inline
Definition at line 1744 of file index.cpp.
References SIntDict< uint >::setAutoDelete().
Member Function Documentation
add()
void UsedIndexLetters::add (uint letter) inline
Definition at line 1745 of file index.cpp.
References SIntDict< uint >::append(), and SIntDict< uint >::find().
Referenced by writeAlphabeticalClassList().
compareValues()
int UsedIndexLetters::compareValues (const uint * item1, const uint * item2) const inline private virtual
Function that is used to compare two items when sorting. Overload this to properly sort items.
See also
inSort()
Reimplemented from SIntDict< uint >.
Definition at line 1754 of file index.cpp.
The documentation for this class was generated from the following file:
src/index.cpp