Doxygen: ClassMembersIndexContext::Private Class Reference
ClassMembersIndexContext::Private Class Reference
Classes
struct Cachable
Public Types
typedef bool(MemberDef::* MemberFunc) () const
Public Member Functions
Private ()
TemplateVariant get (const char *n) const
TemplateVariant getMembersFiltered (SharedPtr< TemplateList > &listRef, MemberFunc filter) const
TemplateVariant all () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant enumValues () const
TemplateVariant macros () const
TemplateVariant properties () const
TemplateVariant events () const
TemplateVariant related () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
Private Attributes
Cachable m_cache
Static Private Attributes
static PropertyMapper< ClassMembersIndexContext::Private > s_inst
Detailed Description
Definition at line 7999 of file context.cpp.
Member Typedef Documentation
MemberFunc
typedef bool(MemberDef::* ClassMembersIndexContext::Private::MemberFunc) () const
Definition at line 8029 of file context.cpp.
Constructor & Destructor Documentation
Private()
ClassMembersIndexContext::Private::Private () inline
Definition at line 8002 of file context.cpp.
References PropertyMapper< T >::addProperty(), all(), enums(), enumValues(), events(), fileName(), functions(), highlight(), Config::init(), macros(), properties(), related(), relPath(), s_inst, subhighlight(), title(), typedefs(), and variables().
Member Function Documentation
all()
TemplateVariant ClassMembersIndexContext::Private::all () const inline
Definition at line 8058 of file context.cpp.
References ClassMembersIndexContext::Private::Cachable::all, getMembersFiltered(), MemberDef::isNotFriend(), and m_cache.
Referenced by Private().
enums()
TemplateVariant ClassMembersIndexContext::Private::enums () const inline
Definition at line 8074 of file context.cpp.
References ClassMembersIndexContext::Private::Cachable::enums, getMembersFiltered(), MemberDef::isEnumerate(), and m_cache.
Referenced by Private().
enumValues()
TemplateVariant ClassMembersIndexContext::Private::enumValues () const inline
Definition at line 8078 of file context.cpp.
References ClassMembersIndexContext::Private::Cachable::enumValues, getMembersFiltered(), MemberDef::isEnumValue(), and m_cache.
Referenced by Private().
events()
TemplateVariant ClassMembersIndexContext::Private::events () const inline
Definition at line 8090 of file context.cpp.
References ClassMembersIndexContext::Private::Cachable::events, getMembersFiltered(), MemberDef::isEvent(), and m_cache.
Referenced by Private().
fileName()
TemplateVariant ClassMembersIndexContext::Private::fileName () const inline
Definition at line 8098 of file context.cpp.
Referenced by Private().
functions()
TemplateVariant ClassMembersIndexContext::Private::functions () const inline
Definition at line 8062 of file context.cpp.
References ClassMembersIndexContext::Private::Cachable::functions, getMembersFiltered(), MemberDef::isFunctionOrSignalSlot(), and m_cache.
Referenced by Private().
get()
TemplateVariant ClassMembersIndexContext::Private::get (const char * n) const inline
Definition at line 8025 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by ClassMembersIndexContext::get().
getMembersFiltered()
TemplateVariant ClassMembersIndexContext::Private::getMembersFiltered (SharedPtr< TemplateList > & listRef, MemberFunc filter) const inline
Definition at line 8030 of file context.cpp.
References MemberContext::alloc(), TemplateList::alloc(), TemplateList::append(), SharedPtr< T >::get(), MemberDef::getClassDef(), ClassDef::isLinkableInProject(), MemberDef::isLinkableInProject(), SDict< MemberName >::Iterator, Doxygen::memberNameSDict, Definition::name(), SharedPtr< T >::reset(), and ClassDef::templateMaster().
Referenced by all(), enums(), enumValues(), events(), functions(), properties(), related(), typedefs(), and variables().
highlight()
TemplateVariant ClassMembersIndexContext::Private::highlight () const inline
Definition at line 8106 of file context.cpp.
Referenced by Private().
macros()
TemplateVariant ClassMembersIndexContext::Private::macros () const inline
Definition at line 8082 of file context.cpp.
Referenced by Private().
properties()
TemplateVariant ClassMembersIndexContext::Private::properties () const inline
Definition at line 8086 of file context.cpp.
References getMembersFiltered(), MemberDef::isProperty(), m_cache, and ClassMembersIndexContext::Private::Cachable::properties.
Referenced by Private().
related()
TemplateVariant ClassMembersIndexContext::Private::related () const inline
Definition at line 8094 of file context.cpp.
References getMembersFiltered(), MemberDef::isRelated(), m_cache, and ClassMembersIndexContext::Private::Cachable::related.
Referenced by Private().
relPath()
TemplateVariant ClassMembersIndexContext::Private::relPath () const inline
Definition at line 8102 of file context.cpp.
Referenced by Private().
subhighlight()
TemplateVariant ClassMembersIndexContext::Private::subhighlight () const inline
Definition at line 8110 of file context.cpp.
Referenced by Private().
title()
TemplateVariant ClassMembersIndexContext::Private::title () const inline
Definition at line 8114 of file context.cpp.
References theTranslator, and Translator::trCompoundMembers().
Referenced by Private().
typedefs()
TemplateVariant ClassMembersIndexContext::Private::typedefs () const inline
Definition at line 8070 of file context.cpp.
References getMembersFiltered(), MemberDef::isTypedef(), m_cache, and ClassMembersIndexContext::Private::Cachable::typedefs.
Referenced by Private().
variables()
TemplateVariant ClassMembersIndexContext::Private::variables () const inline
Definition at line 8066 of file context.cpp.
References getMembersFiltered(), MemberDef::isVariable(), m_cache, and ClassMembersIndexContext::Private::Cachable::variables.
Referenced by Private().
Member Data Documentation
m_cache
Cachable ClassMembersIndexContext::Private::m_cache mutable private
Definition at line 8132 of file context.cpp.
Referenced by all(), enums(), enumValues(), events(), functions(), properties(), related(), typedefs(), and variables().
s_inst
PropertyMapper< ClassMembersIndexContext::Private > ClassMembersIndexContext::Private::s_inst static private
Definition at line 8133 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp