Doxygen: MemberList Class Reference
MemberList Class Reference
A list of MemberDef objects.
#include <memberlist.h>
Public Member Functions
MemberList ()
MemberList (MemberListType lt)
~MemberList ()
MemberListType listType () const
void inSort (const MemberDef *md)
void append (const MemberDef *md)
void remove (const MemberDef *md)
void sort ()
uint count () const
int findRef (const MemberDef *md) const
MemberDef * getFirst () const
MemberDef * take (uint index)
int varCount () const
int funcCount () const
int enumCount () const
int enumValueCount () const
int typedefCount () const
int protoCount () const
int defineCount () const
int friendCount () const
int numDecMembers () const
int numDocMembers () const
bool needsSorting () const
void countDecMembers (bool countEnumValues=FALSE, GroupDef *gd=0)
void countDocMembers (bool countEnumValues=FALSE)
int countInheritableMembers (ClassDef *inheritedFrom) const
void writePlainDeclarations (OutputList &ol, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, ClassDef *inheritedFrom, const char *inheritId)
void writeDeclarations (OutputList &ol, ClassDef *cd, NamespaceDef *nd, FileDef *fd, GroupDef *gd, const char *title, const char *subtitle, bool showEnumValues=FALSE, bool showInline=FALSE, ClassDef *inheritedFrom=0, MemberListType lt=MemberListType_pubMethods)
Writes the list of members to the output.
void writeDocumentation (OutputList &ol, const char *scopeName, Definition *container, const char *title, bool showEnumValues=FALSE, bool showInline=FALSE)
void writeSimpleDocumentation (OutputList &ol, Definition *container)
void writeDocumentationPage (OutputList &ol, const char *scopeName, Definition *container)
void writeTagFile (FTextStream &)
bool declVisible () const
void addMemberGroup (MemberGroup *mg)
void setInGroup (bool inGroup)
void setInFile (bool inFile)
void addListReferences (Definition *def)
void findSectionsInDocumentation ()
void setNeedsSorting (bool b)
MemberGroupList * getMemberGroupList () const
void marshal (StorageIntf *s)
void unmarshal (StorageIntf *s)
Static Public Member Functions
static QCString listTypeAsString (MemberListType type)
Private Member Functions
int compareValues (const MemberDef *item1, const MemberDef *item2) const
int countEnumValues (MemberDef *md, bool setAnonEnumType) const
Private Attributes
int m_varCnt
int m_funcCnt
int m_enumCnt
int m_enumValCnt
int m_typeCnt
int m_protoCnt
int m_defCnt
int m_friendCnt
int m_numDecMembers
int m_numDocMembers
MemberGroupList * memberGroupList
bool m_inGroup
bool m_inFile
MemberListType m_listType
bool m_needsSorting
QDict< int > m_overloadCount
Friends
class MemberListIterator
Detailed Description
A list of MemberDef objects.
Definition at line 32 of file memberlist.h.
Constructor & Destructor Documentation
MemberList() [1/2]
MemberList::MemberList ()
Definition at line 36 of file memberlist.cpp.
References m_defCnt, m_enumCnt, m_enumValCnt, m_friendCnt, m_funcCnt, m_inFile, m_inGroup, m_needsSorting, m_numDecMembers, m_numDocMembers, m_protoCnt, m_typeCnt, m_varCnt, and memberGroupList.
MemberList() [2/2]
MemberList::MemberList (MemberListType lt)
Definition at line 54 of file memberlist.cpp.
References m_defCnt, m_enumCnt, m_enumValCnt, m_friendCnt, m_funcCnt, m_inFile, m_inGroup, m_needsSorting, m_numDecMembers, m_numDocMembers, m_protoCnt, m_typeCnt, m_varCnt, and memberGroupList.
~MemberList()
MemberList::~MemberList ()
Definition at line 72 of file memberlist.cpp.
References memberGroupList.
Member Function Documentation
addListReferences()
void MemberList::addListReferences (Definition * def)
Definition at line 863 of file memberlist.cpp.
References MemberDef::addListReference(), MemberGroup::addListReferences(), DefinitionIntf::definitionType(), MemberDef::enumFieldList(), MemberDef::getGroupDef(), memberGroupList, MemberDef::memberType(), MemberType_Enumeration, and DefinitionIntf::TypeGroup.
Referenced by GroupDef::addListReferences(), NamespaceDef::addListReferences(), MemberGroup::addListReferences(), FileDef::addListReferences(), and ClassDef::addListReferences().
addMemberGroup()
void MemberList::addMemberGroup (MemberGroup * mg)
Definition at line 853 of file memberlist.cpp.
References memberGroupList.
Referenced by MemberGroup::addToDeclarationSection().
append()
void MemberList::append (const MemberDef * md)
Definition at line 241 of file memberlist.cpp.
Referenced by MemberGroup::addGroupedInheritedMembers(), InheritedMemberInfoListContext::Private::addMemberGroupsOfClass(), InheritedMemberInfoListContext::Private::addMemberList(), ClassContext::Private::addMembers(), NamespaceDef::addMemberToList(), GroupDef::addMemberToList(), FileDef::addMemberToList(), ClassDef::addMemberToList(), MemberDef::insertEnumField(), MemberGroup::insertMember(), NamespaceDef::insertMember(), GroupDef::insertMember(), FileDef::insertMember(), ClassDef::internalInsertMember(), and unmarshalMemberList().
compareValues()
int MemberList::compareValues (const MemberDef * item1, const MemberDef * item2) const private
Definition at line 77 of file memberlist.cpp.
References Config_getBool, Definition::getDefLine(), MemberDef::isConstructor(), MemberDef::isDestructor(), and Definition::name().
count()
uint MemberList::count () const
Definition at line 256 of file memberlist.cpp.
Referenced by DotGroupCollaboration::addMemberList(), countInheritableMembers(), GroupDef::countMembers(), generateDEFClassSection(), generateDEFForClass(), generateDEFSection(), marshalMemberList(), unmarshal(), and writeGroupTreeNode().
countDecMembers()
void MemberList::countDecMembers (bool countEnumValues = FALSE, GroupDef * gd = 0)
Count the number of members in this list that are visible in the declaration part of a compound's documentation page.
Definition at line 136 of file memberlist.cpp.
References MemberDef::argsString(), Config_getBool, MemberGroup::countDecMembers(), MemberGroup::defineCount(), MemberGroup::enumCount(), MemberGroup::enumValueCount(), err(), MemberGroup::friendCount(), MemberGroup::funcCount(), MemberDef::getClassDef(), MemberDef::hasDocumentation(), MemberDef::initializer(), MemberDef::isBriefSectionVisible(), MemberDef::isRelated(), m_defCnt, m_enumCnt, m_enumValCnt, m_friendCnt, m_funcCnt, m_numDecMembers, m_protoCnt, m_typeCnt, m_varCnt, memberGroupList, MemberDef::memberType(), MemberType_DCOP, MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Definition::name(), MemberGroup::numDecMembers(), MemberGroup::protoCount(), MemberGroup::typedefCount(), and MemberGroup::varCount().
Referenced by MemberGroup::countDecMembers(), ClassDef::countMemberDeclarations(), writeDeclarations(), and writePlainDeclarations().
countDocMembers()
void MemberList::countDocMembers (bool countEnumValues = FALSE)
Definition at line 208 of file memberlist.cpp.
References MemberGroup::countDocMembers(), MemberDef::isDetailedSectionVisible(), m_inFile, m_inGroup, m_numDocMembers, memberGroupList, MemberDef::memberType(), MemberType_EnumValue, and MemberGroup::numDocMembers().
Referenced by MemberGroup::countDocMembers(), NamespaceDef::countMembers(), writeDocumentation(), ClassDef::writeMemberPages(), and writeSimpleDocumentation().
countEnumValues()
int MemberList::countEnumValues (MemberDef * md, bool setAnonEnumType) const private
Definition at line 281 of file memberlist.cpp.
References Definition::name(), MemberDef::setAnonymousEnumType(), and MemberDef::typeString().
Referenced by declVisible(), and writePlainDeclarations().
countInheritableMembers()
int MemberList::countInheritableMembers (ClassDef * inheritedFrom) const
Definition at line 92 of file memberlist.cpp.
References count(), MemberGroup::countInheritableMembers(), MemberDef::isBriefSectionVisible(), MemberDef::isReimplementedBy(), memberGroupList, MemberDef::memberType(), MemberType_EnumValue, MemberType_Friend, and MemberType_Function.
Referenced by MemberGroup::countInheritableMembers(), and ClassDef::countMembersIncludingGrouped().
declVisible()
bool MemberList::declVisible () const
Definition at line 307 of file memberlist.cpp.
References countEnumValues(), MemberDef::isBriefSectionVisible(), m_inGroup, MemberDef::memberType(), MemberType_DCOP, MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, and MemberType_Variable.
Referenced by NamespaceDef::writeSummaryLinks(), GroupDef::writeSummaryLinks(), FileDef::writeSummaryLinks(), and ClassDef::writeSummaryLinks().
defineCount()
int MemberList::defineCount () const inline
Definition at line 59 of file memberlist.h.
References m_defCnt, and m_numDecMembers.
Referenced by MemberGroup::defineCount().
enumCount()
int MemberList::enumCount () const inline
Definition at line 55 of file memberlist.h.
References m_enumCnt, and m_numDecMembers.
Referenced by MemberGroup::enumCount().
enumValueCount()
int MemberList::enumValueCount () const inline
Definition at line 56 of file memberlist.h.
References m_enumValCnt, and m_numDecMembers.
Referenced by MemberGroup::enumValueCount().
findRef()
int MemberList::findRef (const MemberDef * md) const
Definition at line 261 of file memberlist.cpp.
Referenced by FileDef::insertMember(), and MemberDef::insertReimplementedBy().
findSectionsInDocumentation()
void MemberList::findSectionsInDocumentation ()
Definition at line 897 of file memberlist.cpp.
References MemberGroup::findSectionsInDocumentation(), MemberDef::findSectionsInDocumentation(), and memberGroupList.
Referenced by MemberGroup::findSectionsInDocumentation(), NamespaceDef::findSectionsInDocumentation(), GroupDef::findSectionsInDocumentation(), FileDef::findSectionsInDocumentation(), and ClassDef::findSectionsInDocumentation().
friendCount()
int MemberList::friendCount () const inline
Definition at line 60 of file memberlist.h.
References m_friendCnt, and m_numDecMembers.
Referenced by MemberGroup::friendCount().
funcCount()
int MemberList::funcCount () const inline
Definition at line 54 of file memberlist.h.
References m_funcCnt, and m_numDecMembers.
Referenced by MemberGroup::funcCount().
getFirst()
MemberDef * MemberList::getFirst () const
Definition at line 266 of file memberlist.cpp.
Referenced by MemberGroup::insertMember().
getMemberGroupList()
MemberGroupList* MemberList::getMemberGroupList () const inline
Definition at line 88 of file memberlist.h.
References memberGroupList.
Referenced by InheritedMemberInfoListContext::Private::addMemberListIncludingGrouped(), MemberListInfoContext::Private::memberGroups(), membersHaveSpecificType(), writeBoxMemberList(), and VhdlDocGen::writeVHDLDeclarations().
inSort()
void MemberList::inSort (const MemberDef * md)
Definition at line 236 of file memberlist.cpp.
Referenced by NamespaceDef::addMemberToList(), FileDef::addMemberToList(), and MemberDef::insertReimplementedBy().
listType()
MemberListType MemberList::listType () const inline
Definition at line 39 of file memberlist.h.
References m_listType.
Referenced by MemberGroup::addGroupedInheritedMembers(), GroupDef::addListReferences(), NamespaceDef::addListReferences(), FileDef::addListReferences(), ClassDef::addListReferences(), NamespaceDef::addMembersToMemberGroup(), GroupDef::addMembersToMemberGroup(), FileDef::addMembersToMemberGroup(), ClassDef::addMembersToMemberGroup(), NamespaceDef::addMemberToList(), GroupDef::addMemberToList(), FileDef::addMemberToList(), ClassDef::addMemberToList(), MemberListInfoContext::Private::anchor(), ClassDef::computeAnchors(), MemberGroup::countGroupedInheritedMembers(), NamespaceDef::createMemberList(), GroupDef::createMemberList(), FileDef::createMemberList(), ClassDef::createMemberList(), NamespaceDef::findSectionsInDocumentation(), GroupDef::findSectionsInDocumentation(), FileDef::findSectionsInDocumentation(), ClassDef::findSectionsInDocumentation(), generateDocbookSection(), NamespaceDef::getMemberList(), GroupDef::getMemberList(), FileDef::getMemberList(), ClassDef::getMemberList(), InheritedMemberInfoContext::Private::id(), MemberListInfoContext::Private::inherited(), MemberListContext::MemberListContext(), NamespaceDef::writeMemberPages(), GroupDef::writeMemberPages(), FileDef::writeMemberPages(), ClassDef::writeMemberPages(), NamespaceDef::writeSummaryLinks(), GroupDef::writeSummaryLinks(), FileDef::writeSummaryLinks(), and ClassDef::writeSummaryLinks().
listTypeAsString()
QCString MemberList::listTypeAsString (MemberListType type) static
Definition at line 986 of file memberlist.cpp.
References MemberListType_dcopMethods, MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decEnumValMembers, MemberListType_decEventMembers, MemberListType_decFriendMembers, MemberListType_decFuncMembers, MemberListType_decPriSlotMembers, MemberListType_decPropMembers, MemberListType_decProSlotMembers, MemberListType_decProtoMembers, MemberListType_decPubSlotMembers, MemberListType_decSignalMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_enumFields, MemberListType_events, MemberListType_friends, MemberListType_interfaces, MemberListType_memberGroup, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_pacTypes, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_services, and MemberListType_signals.
Referenced by MemberListInfoContext::Private::anchor(), InheritedMemberInfoContext::Private::id(), writeDeclarations(), NamespaceDef::writeSummaryLinks(), GroupDef::writeSummaryLinks(), FileDef::writeSummaryLinks(), and ClassDef::writeSummaryLinks().
marshal()
void MemberList::marshal (StorageIntf * s)
Definition at line 916 of file memberlist.cpp.
References m_defCnt, m_enumCnt, m_enumValCnt, m_friendCnt, m_funcCnt, m_inFile, m_inGroup, m_listType, m_needsSorting, m_numDecMembers, m_numDocMembers, m_protoCnt, m_typeCnt, m_varCnt, MemberGroup::marshal(), marshalBool(), marshalInt(), marshalUInt(), memberGroupList, and NULL_LIST.
Referenced by marshalMemberList().
needsSorting()
bool MemberList::needsSorting () const inline
Definition at line 63 of file memberlist.h.
References m_needsSorting.
Referenced by NamespaceDef::addMemberToList(), FileDef::addMemberToList(), NamespaceDef::sortMemberLists(), GroupDef::sortMemberLists(), FileDef::sortMemberLists(), and ClassDef::sortMemberLists().
numDecMembers()
int MemberList::numDecMembers () const inline
Definition at line 61 of file memberlist.h.
References m_numDecMembers.
Referenced by MemberGroup::countDecMembers(), ClassDef::countMemberDeclarations(), MemberGroup::numDecMembers(), writeDeclarations(), and writePlainDeclarations().
numDocMembers()
int MemberList::numDocMembers () const inline
Definition at line 62 of file memberlist.h.
References m_numDocMembers.
Referenced by MemberGroup::countDocMembers(), NamespaceDef::countMembers(), MemberGroup::numDocMembers(), writeDocumentation(), ClassDef::writeMemberPages(), and writeSimpleDocumentation().
protoCount()
int MemberList::protoCount () const inline
Definition at line 58 of file memberlist.h.
References m_numDecMembers, and m_protoCnt.
Referenced by MemberGroup::protoCount().
remove()
void MemberList::remove (const MemberDef * md)
Definition at line 246 of file memberlist.cpp.
Referenced by ClassDef::reclassifyMember(), GroupDef::removeMemberFromList(), and ClassDef::removeMemberFromLists().
setInFile()
void MemberList::setInFile (bool inFile) inline
Definition at line 84 of file memberlist.h.
References m_inFile.
Referenced by FileDef::addMemberToList().
setInGroup()
void MemberList::setInGroup (bool inGroup) inline
Definition at line 83 of file memberlist.h.
References m_inGroup.
Referenced by GroupDef::createMemberList(), MemberGroup::setInGroup(), and ClassDef::writePlainMemberDeclaration().
setNeedsSorting()
void MemberList::setNeedsSorting (bool b)
Definition at line 981 of file memberlist.cpp.
References m_needsSorting.
Referenced by NamespaceDef::addMemberToList(), GroupDef::addMemberToList(), FileDef::addMemberToList(), ClassDef::addMemberToList(), NamespaceDef::sortMemberLists(), GroupDef::sortMemberLists(), FileDef::sortMemberLists(), and ClassDef::sortMemberLists().
sort()
void MemberList::sort ()
Definition at line 251 of file memberlist.cpp.
Referenced by NamespaceDef::sortMemberLists(), GroupDef::sortMemberLists(), FileDef::sortMemberLists(), ClassDef::sortMemberLists(), NamespaceDef::writeDocumentation(), GroupDef::writeDocumentation(), and FileDef::writeDocumentation().
take()
MemberDef * MemberList::take (uint index)
Definition at line 271 of file memberlist.cpp.
Referenced by addMembersToMemberGroup().
typedefCount()
int MemberList::typedefCount () const inline
Definition at line 57 of file memberlist.h.
References m_numDecMembers, and m_typeCnt.
Referenced by MemberGroup::typedefCount().
unmarshal()
void MemberList::unmarshal (StorageIntf * s)
Definition at line 948 of file memberlist.cpp.
References count(), m_defCnt, m_enumCnt, m_enumValCnt, m_friendCnt, m_funcCnt, m_inFile, m_inGroup, m_listType, m_needsSorting, m_numDecMembers, m_numDocMembers, m_protoCnt, m_typeCnt, m_varCnt, memberGroupList, NULL_LIST, MemberGroup::unmarshal(), unmarshalBool(), unmarshalInt(), and unmarshalUInt().
Referenced by unmarshalMemberList().
varCount()
int MemberList::varCount () const inline
Definition at line 53 of file memberlist.h.
References m_numDecMembers, and m_varCnt.
Referenced by MemberGroup::varCount().
writeDeclarations()
void MemberList::writeDeclarations (OutputList & ol, ClassDef * cd, NamespaceDef * nd, FileDef * fd, GroupDef * gd, const char * title, const char * subtitle, bool showEnumValues = FALSE, bool showInline = FALSE, ClassDef * inheritedFrom = 0, MemberListType lt = MemberListType_pubMethods)
Writes the list of members to the output.
Parameters
ol Output list to write to
cd non-null if this list is part of class documentation.
nd non-null if this list is part of namespace documentation.
fd non-null if this list is part of file documentation.
gd non-null if this list is part of group documentation.
title Title to use for the member list.
subtitle Sub title to use for the member list.
showEnumValues Obsolete, always set to FALSE.
showInline if set to TRUE if title is rendered differently
inheritedFrom if not 0, the list is shown inside the given class as inherited members, parameter cd points to the class containing the members.
lt Type of list that is inherited from.
Definition at line 535 of file memberlist.cpp.
References ClassDef::addGroupedInheritedMembers(), ClassDef::anchor(), Config_getBool, countDecMembers(), ClassDef::countMembersIncludingGrouped(), OutputList::disableAllBut(), ClassDef::displayName(), MemberGroup::docFile(), MemberGroup::docLine(), MemberGroup::documentation(), OutputList::endInlineHeader(), OutputList::endMemberGroup(), OutputList::endMemberGroupDocs(), OutputList::endMemberGroupHeader(), OutputList::endMemberHeader(), OutputList::endMemberSubtitle(), OutputList::generateDoc(), ClassDef::getOutputFileBase(), ClassDef::getReference(), MemberGroup::header(), OutputGenerator::Html, listTypeAsString(), m_listType, memberGroupList, numDecMembers(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startInlineHeader(), OutputList::startMemberGroup(), OutputList::startMemberGroupDocs(), OutputList::startMemberGroupHeader(), OutputList::startMemberHeader(), OutputList::startMemberSubtitle(), stripPath(), substitute(), OutputList::writeInheritedSectionTitle(), MemberGroup::writePlainDeclarations(), writePlainDeclarations(), and VhdlDocGen::writeVhdlDeclarations().
Referenced by MemberGroup::writeDeclarations(), NamespaceDef::writeMemberDeclarations(), GroupDef::writeMemberDeclarations(), FileDef::writeMemberDeclarations(), and ClassDef::writeMemberDeclarations().
writeDocumentation()
void MemberList::writeDocumentation (OutputList & ol, const char * scopeName, Definition * container, const char * title, bool showEnumValues = FALSE, bool showInline = FALSE)
Definition at line 671 of file memberlist.cpp.
References countDocMembers(), DefinitionIntf::definitionType(), OutputList::disable(), OutputList::endGroupHeader(), OutputList::endMemberDocList(), OutputGenerator::Html, MemberDef::isDetailedSectionVisible(), MemberDef::isEnumValue(), m_inGroup, memberGroupList, Definition::name(), numDocMembers(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), OutputList::startMemberDocList(), DefinitionIntf::TypeFile, MemberGroup::writeDocumentation(), MemberDef::writeDocumentation(), and OutputList::writeRuler().
Referenced by MemberGroup::writeDocumentation(), NamespaceDef::writeMemberDocumentation(), GroupDef::writeMemberDocumentation(), FileDef::writeMemberDocumentation(), and ClassDef::writeMemberDocumentation().
writeDocumentationPage()
void MemberList::writeDocumentationPage (OutputList & ol, const char * scopeName, Definition * container)
Definition at line 767 of file memberlist.cpp.
References Config_getBool, OutputList::endContents(), endFile(), endFileWithNavPath(), OutputList::endQuickIndices(), MemberDef::getOutputFileBase(), HLI_None, MemberDef::isDetailedSectionLinkable(), m_inGroup, memberGroupList, Definition::name(), MemberDef::qualifiedName(), OutputList::startContents(), startFile(), MemberDef::writeDocumentation(), MemberGroup::writeDocumentationPage(), Definition::writeNavigationPath(), Definition::writeQuickMemberLinks(), and OutputList::writeString().
Referenced by MemberGroup::writeDocumentationPage(), NamespaceDef::writeMemberPages(), GroupDef::writeMemberPages(), FileDef::writeMemberPages(), and ClassDef::writeMemberPages().
writePlainDeclarations()
void MemberList::writePlainDeclarations (OutputList & ol, ClassDef * cd, NamespaceDef * nd, FileDef * fd, GroupDef * gd, ClassDef * inheritedFrom, const char * inheritId)
Definition at line 355 of file memberlist.cpp.
References MemberDef::anchor(), MemberDef::anonymousDeclShown(), MemberDef::briefDescription(), Definition::briefFile(), Definition::briefLine(), Config_getBool, countDecMembers(), countEnumValues(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enableAll(), OutputList::endDoxyAnchor(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberItem(), OutputList::endMemberList(), OutputList::endTextLink(), MemberDef::fromAnonymousScope(), MemberDef::getOutputFileBase(), OutputGenerator::Html, OutputList::insertMemberAlign(), MemberDef::isBriefSectionVisible(), MemberDef::isDetailedSectionLinkable(), DocRoot::isEmpty(), MemberDef::isReimplementedBy(), m_inGroup, MemberDef::memberType(), MemberType_DCOP, MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Definition::name(), numDecMembers(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), MemberDef::setFromAnonymousScope(), OutputList::startDoxyAnchor(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberItem(), OutputList::startMemberList(), OutputList::startTextLink(), theTranslator, Translator::trMore(), validatingParseDoc(), MemberDef::warnIfUndocumented(), MemberDef::writeDeclaration(), OutputList::writeDoc(), MemberDef::writeEnumDeclaration(), and OutputList::writeString().
Referenced by MemberGroup::addGroupedInheritedMembers(), writeDeclarations(), MemberGroup::writePlainDeclarations(), and ClassDef::writePlainMemberDeclaration().
writeSimpleDocumentation()
void MemberList::writeSimpleDocumentation (OutputList & ol, Definition * container)
Definition at line 744 of file memberlist.cpp.
References countDocMembers(), DefinitionIntf::definitionType(), OutputList::endMemberDocSimple(), ClassDef::isJavaEnum(), numDocMembers(), OutputList::startMemberDocSimple(), DefinitionIntf::TypeClass, and MemberDef::writeMemberDocSimple().
Referenced by ClassDef::writeSimpleMemberDocumentation().
writeTagFile()
void MemberList::writeTagFile (FTextStream & tagFile)
Definition at line 1042 of file memberlist.cpp.
References MemberDef::enumFieldList(), Definition::getLanguage(), MemberDef::isStrong(), memberGroupList, MemberDef::memberType(), MemberType_Enumeration, SrcLangExt_VHDL, MemberGroup::writeTagFile(), VhdlDocGen::writeTagFile(), and MemberDef::writeTagFile().
Referenced by NamespaceDef::writeTagFile(), MemberGroup::writeTagFile(), GroupDef::writeTagFile(), FileDef::writeTagFile(), and ClassDef::writeTagFile().
Friends And Related Function Documentation
MemberListIterator
friend class MemberListIterator friend
Definition at line 34 of file memberlist.h.
Member Data Documentation
m_defCnt
int MemberList::m_defCnt private
Definition at line 102 of file memberlist.h.
Referenced by countDecMembers(), defineCount(), marshal(), MemberList(), and unmarshal().
m_enumCnt
int MemberList::m_enumCnt private
Definition at line 98 of file memberlist.h.
Referenced by countDecMembers(), enumCount(), marshal(), MemberList(), and unmarshal().
m_enumValCnt
int MemberList::m_enumValCnt private
Definition at line 99 of file memberlist.h.
Referenced by countDecMembers(), enumValueCount(), marshal(), MemberList(), and unmarshal().
m_friendCnt
int MemberList::m_friendCnt private
Definition at line 103 of file memberlist.h.
Referenced by countDecMembers(), friendCount(), marshal(), MemberList(), and unmarshal().
m_funcCnt
int MemberList::m_funcCnt private
Definition at line 97 of file memberlist.h.
Referenced by countDecMembers(), funcCount(), marshal(), MemberList(), and unmarshal().
m_inFile
bool MemberList::m_inFile private
Definition at line 108 of file memberlist.h.
Referenced by countDocMembers(), marshal(), MemberList(), setInFile(), and unmarshal().
m_inGroup
bool MemberList::m_inGroup private
Definition at line 107 of file memberlist.h.
Referenced by countDocMembers(), declVisible(), marshal(), MemberList(), setInGroup(), unmarshal(), writeDocumentation(), writeDocumentationPage(), and writePlainDeclarations().
m_listType
MemberListType MemberList::m_listType private
Definition at line 109 of file memberlist.h.
Referenced by listType(), marshal(), unmarshal(), and writeDeclarations().
m_needsSorting
bool MemberList::m_needsSorting private
Definition at line 110 of file memberlist.h.
Referenced by marshal(), MemberList(), needsSorting(), setNeedsSorting(), and unmarshal().
m_numDecMembers
int MemberList::m_numDecMembers private
Definition at line 104 of file memberlist.h.
Referenced by countDecMembers(), defineCount(), enumCount(), enumValueCount(), friendCount(), funcCount(), marshal(), MemberList(), numDecMembers(), protoCount(), typedefCount(), unmarshal(), and varCount().
m_numDocMembers
int MemberList::m_numDocMembers private
Definition at line 105 of file memberlist.h.
Referenced by countDocMembers(), marshal(), MemberList(), numDocMembers(), and unmarshal().
m_overloadCount
QDict<int> MemberList::m_overloadCount private
Definition at line 111 of file memberlist.h.
m_protoCnt
int MemberList::m_protoCnt private
Definition at line 101 of file memberlist.h.
Referenced by countDecMembers(), marshal(), MemberList(), protoCount(), and unmarshal().
m_typeCnt
int MemberList::m_typeCnt private
Definition at line 100 of file memberlist.h.
Referenced by countDecMembers(), marshal(), MemberList(), typedefCount(), and unmarshal().
m_varCnt
int MemberList::m_varCnt private
Definition at line 96 of file memberlist.h.
Referenced by countDecMembers(), marshal(), MemberList(), unmarshal(), and varCount().
memberGroupList
MemberGroupList* MemberList::memberGroupList private
Definition at line 106 of file memberlist.h.
Referenced by addListReferences(), addMemberGroup(), countDecMembers(), countDocMembers(), countInheritableMembers(), findSectionsInDocumentation(), getMemberGroupList(), marshal(), MemberList(), unmarshal(), writeDeclarations(), writeDocumentation(), writeDocumentationPage(), writeTagFile(), and ~MemberList().
The documentation for this class was generated from the following files:
src/memberlist.h
src/memberlist.cpp