Doxygen: src/dot.h File Reference
dot.h File Reference
#include <qlist.h>
#include <qdict.h>
#include <qwaitcondition.h>
#include <qmutex.h>
#include <qqueue.h>
#include <qthread.h>
#include "sortdict.h"
Classes
struct EdgeInfo
Attributes of an edge of a dot graph.
class DotNode
A node in a dot graph.
class DotNodeList
Class representing a list of DotNode objects.
class DotGfxHierarchyTable
Represents a graphical class hierarchy.
class DotClassGraph
Representation of a class inheritance or dependency graph.
class DotInclDepGraph
Representation of an include dependency graph.
class DotCallGraph
Representation of an call graph.
class DotDirDeps
Representation of an directory dependency graph.
class DotGroupCollaboration
Representation of a group collaboration graph.
class DotGroupCollaboration::Link
class DotGroupCollaboration::Edge
class DotConstString
Minimal constant string class that is thread safe, once initialized.
class DotRunner
Helper class to run dot from doxygen.
struct DotRunner::CleanupItem
class DotFilePatcher
Helper class to insert a set of map file into an output file.
struct DotFilePatcher::Map
class DotRunnerQueue
Queue of dot jobs to run.
class DotWorkerThread
Worker thread to execute a dot run.
class DotManager
Singleton that manages dot relation actions.
Enumerations
enum GraphOutputFormat { GOF_BITMAP, GOF_EPS }
enum EmbeddedOutputFormat { EOF_Html, EOF_LaTeX, EOF_Rtf, EOF_DocBook }
Functions
void generateGraphLegend (const char *path)
Generated a graphs legend page.
void writeDotGraphFromFile (const char *inFile, const char *outDir, const char *outFile, GraphOutputFormat format)
void writeDotImageMapFromFile (FTextStream &t, const QCString &inFile, const QCString &outDir, const QCString &relPath, const QCString &baseName, const QCString &context, int graphId=-1)
void resetDotNodeNumbering ()
Enumeration Type Documentation
EmbeddedOutputFormat
enum EmbeddedOutputFormat
Enumerator
EOF_Html
EOF_LaTeX
EOF_Rtf
EOF_DocBook
Definition at line 43 of file dot.h.
GraphOutputFormat
enum GraphOutputFormat
Enumerator
GOF_BITMAP
GOF_EPS
Definition at line 42 of file dot.h.
Function Documentation
generateGraphLegend()
void generateGraphLegend (const char * path)
Generated a graphs legend page.
Definition at line 4072 of file dot.cpp.
References IndexList::addImageFile(), DotRunner::addJob(), DotManager::addRun(), DotManager::addSVGObject(), checkAndUpdateMd5Signature(), checkDeliverables(), Config_getEnum, Config_getString, err(), FONTNAME, FONTSIZE, getDotImageExtension(), Doxygen::htmlFileExtension, Doxygen::indexList, DotManager::instance(), removeDotGraph(), theTranslator, Translator::trLegendTitle(), writeGraphFooter(), and writeGraphHeader().
Referenced by writeGraphInfo().
resetDotNodeNumbering()
void resetDotNodeNumbering ()
Definition at line 4866 of file dot.cpp.
References DotClassGraph::resetNumbering(), DotInclDepGraph::resetNumbering(), DotCallGraph::resetNumbering(), and DotGroupCollaboration::resetNumbering().
Referenced by startFile().
writeDotGraphFromFile()
void writeDotGraphFromFile (const char * inFile, const char * outDir, const char * outFile, GraphOutputFormat format)
Definition at line 4148 of file dot.cpp.
References IndexList::addImageFile(), DotRunner::addJob(), checkDotResult(), Config_getBool, Config_getEnum, err(), getDotImageExtension(), GOF_BITMAP, and Doxygen::indexList.
Referenced by DocbookDocVisitor::startDotFile(), LatexDocVisitor::startDotFile(), HtmlDocVisitor::writeDotFile(), RTFDocVisitor::writeDotFile(), and DocbookDocVisitor::writeDotFile().
writeDotImageMapFromFile()
void writeDotImageMapFromFile (FTextStream & t, const QCString & inFile, const QCString & outDir, const QCString & relPath, const QCString & baseName, const QCString & context, int graphId)
Writes user defined image map to the output.
Parameters
t text stream to write to
inFile just the basename part of the filename
outDir output directory
relPath relative path the to root of the output dir
baseName the base name of the output files
context the scope in which this graph is found (for resolving links)
graphId a unique id for this graph, use for dynamic sections
Definition at line 4200 of file dot.cpp.
References DotRunner::addJob(), DotFilePatcher::addSVGConversion(), Config_getEnum, convertMapFile(), endl(), err(), getDotImageExtension(), MAP_CMD, DotFilePatcher::run(), and writeSVGFigureLink().
Referenced by HtmlDocVisitor::writeDotFile().