Doxygen: SymbolContext Class Reference
SymbolContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static SymbolContext * alloc (const Definition *def, const Definition *prev, const Definition *next)
Private Member Functions
SymbolContext (const Definition *def, const Definition *prev, const Definition *next)
~SymbolContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1182 of file context.h.
Constructor & Destructor Documentation
SymbolContext()
SymbolContext::SymbolContext (const Definition * def, const Definition * prev, const Definition * next) private
Definition at line 9561 of file context.cpp.
References p, and Private.
Referenced by alloc().
~SymbolContext()
SymbolContext::~SymbolContext () private
Definition at line 9567 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int SymbolContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 1190 of file context.h.
References RefCountedContext::addRef().
alloc()
static SymbolContext* SymbolContext::alloc (const Definition * def, const Definition * prev, const Definition * next) inline static
Definition at line 1185 of file context.h.
References SymbolContext().
Referenced by SymbolListContext::Private::Private().
get()
TemplateVariant SymbolContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 9572 of file context.cpp.
References SymbolContext::Private::get(), and p.
release()
virtual int SymbolContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 1191 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* SymbolContext::p private
Definition at line 1196 of file context.h.
Referenced by get(), SymbolContext(), and ~SymbolContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp