Doxygen: ExprAstVariable Class Reference
ExprAstVariable Class Reference
Class representing a variable in the AST.
Public Member Functions
ExprAstVariable (const char *name)
const QCString & name () const
virtual TemplateVariant resolve (TemplateContext *c)
Public Member Functions inherited from ExprAst
virtual ~ExprAst ()
Private Attributes
QCString m_name
Detailed Description
Class representing a variable in the AST.
Definition at line 1452 of file template.cpp.
Constructor & Destructor Documentation
ExprAstVariable()
ExprAstVariable::ExprAstVariable (const char * name) inline
Definition at line 1455 of file template.cpp.
References TRACE.
Member Function Documentation
name()
const QCString& ExprAstVariable::name () const inline
Definition at line 1457 of file template.cpp.
References m_name.
resolve()
virtual TemplateVariant ExprAstVariable::resolve (TemplateContext * c) inline virtual
Reimplemented from ExprAst.
Definition at line 1458 of file template.cpp.
References TemplateContext::get(), TemplateVariant::isValid(), TemplateContextImpl::line(), m_name, TemplateContextImpl::templateName(), and TemplateContextImpl::warn().
Member Data Documentation
m_name
QCString ExprAstVariable::m_name private
Definition at line 1469 of file template.cpp.
Referenced by name(), and resolve().
The documentation for this class was generated from the following file:
src/template.cpp