Doxygen: ModuleNodeContext Class Reference
ModuleNodeContext Class Reference
#include <context.h>
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static ModuleNodeContext * alloc (GroupDef *gd)
Private Member Functions
ModuleNodeContext (GroupDef *)
~ModuleNodeContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 729 of file context.h.
Constructor & Destructor Documentation
ModuleNodeContext()
ModuleNodeContext::ModuleNodeContext (GroupDef *) private
Referenced by alloc().
~ModuleNodeContext()
ModuleNodeContext::~ModuleNodeContext () private
Member Function Documentation
addRef()
virtual int ModuleNodeContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 736 of file context.h.
References RefCountedContext::addRef().
alloc()
static ModuleNodeContext* ModuleNodeContext::alloc (GroupDef * gd) inline static
Definition at line 732 of file context.h.
References ModuleNodeContext().
get()
virtual TemplateVariant ModuleNodeContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
release()
virtual int ModuleNodeContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 737 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ModuleNodeContext::p private
Definition at line 742 of file context.h.
The documentation for this class was generated from the following file:
src/context.h