Doxygen: FormulaList Class Reference
FormulaList Class Reference
A list of Formula objects.
#include <formula.h>
Public Member Functions
void generateBitmaps (const char *path)
Detailed Description
A list of Formula objects.
Definition at line 39 of file formula.h.
Member Function Documentation
generateBitmaps()
void FormulaList::generateBitmaps (const char * path)
Definition at line 49 of file formula.cpp.
References IndexList::addImageFile(), Config_getBool, Config_getInt, Config_getString, endl(), err(), fileToString(), Formula::getFormulaText(), Image::getHeight(), Formula::getId(), Image::getWidth(), Doxygen::indexList, msg(), portable_ghostScriptCommand(), portable_system(), portable_sysTimerStart(), portable_sysTimerStop(), Image::save(), Image::setPixel(), and writeExtraLatexPackages().
Referenced by generateOutput().
The documentation for this class was generated from the following files:
src/formula.h
src/formula.cpp