Doxygen: TemplateNodeResource Class Reference
TemplateNodeResource Class Reference
Class representing an 'markers' tag in a template.
Public Member Functions
TemplateNodeResource (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeResource ()
void render (FTextStream &, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeResource >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Private Attributes
ExprAst * m_resExpr
ExprAst * m_asExpr
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeResource >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeResource >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeResource >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'markers' tag in a template.
Definition at line 4363 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeResource()
TemplateNodeResource::TemplateNodeResource (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 4366 of file template.cpp.
References m_asExpr, m_resExpr, TemplateNodeCreator< TemplateNodeResource >::m_templateName, ExpressionParser::parse(), TRACE, and TemplateParser::warn().
~TemplateNodeResource()
TemplateNodeResource::~TemplateNodeResource () inline
Definition at line 4390 of file template.cpp.
References m_asExpr, and m_resExpr.
Member Function Documentation
render()
void TemplateNodeResource::render (FTextStream & , TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 4395 of file template.cpp.
References ResourceMgr::copyResource(), ResourceMgr::copyResourceAs(), ResourceMgr::instance(), m_asExpr, TemplateNodeCreator< TemplateNodeResource >::m_line, m_resExpr, TemplateNodeCreator< TemplateNodeResource >::m_templateName, TemplateNodeCreator< TemplateNodeResource >::mkpath(), TemplateContextImpl::outputDirectory(), ExprAst::resolve(), TemplateContextImpl::setLocation(), TemplateVariant::toString(), and TemplateContextImpl::warn().
Member Data Documentation
m_asExpr
ExprAst* TemplateNodeResource::m_asExpr private
Definition at line 4431 of file template.cpp.
Referenced by render(), TemplateNodeResource(), and ~TemplateNodeResource().
m_resExpr
ExprAst* TemplateNodeResource::m_resExpr private
Definition at line 4430 of file template.cpp.
Referenced by render(), TemplateNodeResource(), and ~TemplateNodeResource().
The documentation for this class was generated from the following file:
src/template.cpp