Doxygen: FileNameList Class Reference
FileNameList Class Reference
Class representing a list of FileName objects.
#include <filename.h>
Public Member Functions
FileNameList ()
~FileNameList ()
void generateDiskNames ()
Private Member Functions
int compareValues (const FileName *item1, const FileName *item2) const
Detailed Description
Class representing a list of FileName objects.
Definition at line 49 of file filename.h.
Constructor & Destructor Documentation
FileNameList()
FileNameList::FileNameList ()
Definition at line 115 of file filename.cpp.
~FileNameList()
FileNameList::~FileNameList ()
Definition at line 119 of file filename.cpp.
Member Function Documentation
compareValues()
int FileNameList::compareValues (const FileName * item1, const FileName * item2) const private
Definition at line 133 of file filename.cpp.
References Config_getBool, FileName::fileName(), and FileName::fullName().
generateDiskNames()
void FileNameList::generateDiskNames ()
Definition at line 123 of file filename.cpp.
References FileName::generateDiskNames().
Referenced by parseInput().
The documentation for this class was generated from the following files:
src/filename.h
src/filename.cpp