Doxygen: src/latexgen.cpp File Reference
latexgen.cpp File Reference
#include <stdlib.h>
#include <qdir.h>
#include "latexgen.h"
#include "config.h"
#include "message.h"
#include "doxygen.h"
#include "util.h"
#include "diagram.h"
#include "language.h"
#include "version.h"
#include "dot.h"
#include "pagedef.h"
#include "docparser.h"
#include "latexdocvisitor.h"
#include "dirdef.h"
#include "cite.h"
#include "groupdef.h"
#include "classlist.h"
#include "namespacedef.h"
#include "filename.h"
#include "resourcemgr.h"
Macros
#define COPYCHAR()
Functions
static void writeLatexMakefile ()
static void writeMakeBat ()
static void writeDefaultHeaderPart1 (FTextStream &t)
static void writeDefaultHeaderPart2 (FTextStream &t)
static void writeDefaultHeaderPart3 (FTextStream &t)
static void writeDefaultStyleSheet (FTextStream &t)
static void writeDefaultFooter (FTextStream &t)
Macro Definition Documentation
COPYCHAR
#define COPYCHAR ()
Value:
do {                                           \
                     result[i++]=c; p++;                          \
                     if (c<0) /* multibyte utf-8 character */     \
                     {                                            \
                       /* 1xxx.xxxx: >=2 byte character */        \
                       result[i++]=*p++;                          \
                       if (((uchar)c&0xE0)==0xE0)                 \
                       {                                          \
                         /* 111x.xxxx: >=3 byte character */      \
                         result[i++]=*p++;                        \
                       }                                          \
                       if (((uchar)c&0xF0)==0xF0)                 \
                       {                                          \
                         /* 1111.xxxx: 4 byte character */        \
                         result[i++]=*p++;                        \
                       }                                          \
                     }                                            \
                     m_col++;                                       \
                   } while(0)
Referenced by LatexCodeGenerator::codify().
Function Documentation
writeDefaultFooter()
static void writeDefaultFooter (FTextStream & t) static
Definition at line 728 of file latexgen.cpp.
References Doxygen::citeDict, Config_getBool, theTranslator, Translator::trRTFGeneralIndex(), and CiteDict::writeLatexBibliography().
Referenced by LatexGenerator::endIndexSection(), and LatexGenerator::writeFooterFile().
writeDefaultHeaderPart1()
static void writeDefaultHeaderPart1 (FTextStream & t) static
Definition at line 454 of file latexgen.cpp.
References checkExtension(), Config_getBool, Config_getEnum, Config_getList, Config_getString, dateToString(), filterLatexString(), Translator::idLanguage(), Translator::latexLanguageSupportCommand(), latexStyleExtension, stripExtensionGeneral(), theTranslator, Translator::trGeneratedAt(), Translator::trGeneratedBy(), and writeExtraLatexPackages().
Referenced by LatexGenerator::startIndexSection(), and LatexGenerator::writeHeaderFile().
writeDefaultHeaderPart2()
static void writeDefaultHeaderPart2 (FTextStream & t) static
Definition at line 683 of file latexgen.cpp.
Referenced by LatexGenerator::startIndexSection(), and LatexGenerator::writeHeaderFile().
writeDefaultHeaderPart3()
static void writeDefaultHeaderPart3 (FTextStream & t) static
Definition at line 692 of file latexgen.cpp.
References Config_getBool, dateToString(), and versionString.
Referenced by LatexGenerator::endIndexSection(), and LatexGenerator::writeHeaderFile().
writeDefaultStyleSheet()
static void writeDefaultStyleSheet (FTextStream & t) static
Definition at line 723 of file latexgen.cpp.
References ResourceMgr::getAsString(), and ResourceMgr::instance().
Referenced by LatexGenerator::writeStyleInfo(), and LatexGenerator::writeStyleSheetFile().
writeLatexMakefile()
static void writeLatexMakefile () static
Definition at line 262 of file latexgen.cpp.
References Doxygen::citeDict, Config_getBool, Config_getString, endl(), err(), and CiteDict::isEmpty().
Referenced by LatexGenerator::init().
writeMakeBat()
static void writeMakeBat () static
Definition at line 354 of file latexgen.cpp.
References Doxygen::citeDict, Config_getBool, Config_getString, endl(), err(), and CiteDict::isEmpty().
Referenced by LatexGenerator::init().