Doxygen: DocHRef Class Reference
DocHRef Class Reference
Node representing a Hypertext reference.
#include <docparser.h>
Public Member Functions
DocHRef (DocNode *parent, const HtmlAttribList &attribs, const QCString &url, const QCString &relPath)
int parse ()
QCString url () const
QCString relPath () const
Kind kind () const
void accept (DocVisitor *v)
const HtmlAttribList & attribs () const
Public Member Functions inherited from CompAccept< DocHRef >
CompAccept ()
virtual ~CompAccept ()
void accept (DocHRef *obj, DocVisitor *v)
const QList< DocNode > & children () const
QList< DocNode > & children ()
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
QCString m_url
QCString m_relPath
Additional Inherited Members
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from CompAccept< DocHRef >
QList< DocNode > m_children
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Node representing a Hypertext reference.
Definition at line 870 of file docparser.h.
Constructor & Destructor Documentation
DocHRef()
DocHRef::DocHRef (DocNode * parent, const HtmlAttribList & attribs, const QCString & url, const QCString & relPath) inline
Definition at line 873 of file docparser.h.
References DocNode::m_parent, and DocNode::parent().
Member Function Documentation
accept()
void DocHRef::accept (DocVisitor * v) inline virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 880 of file docparser.h.
References CompAccept< T >::accept().
attribs()
const HtmlAttribList& DocHRef::attribs () const inline
Definition at line 881 of file docparser.h.
References m_attribs.
Referenced by HtmlDocVisitor::visitPre().
kind()
Kind DocHRef::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 879 of file docparser.h.
References DocNode::Kind_HRef.
parse()
int DocHRef::parse ()
Definition at line 3071 of file docparser.cpp.
References DBG, defaultHandleToken(), doctokenizerYYlex(), doctokenizerYYlineno, TokenInfo::endTag, g_fileName, g_nodeStack, g_token, handlePendingStyleCommands(), HTML_A, Mappers::htmlTagMapper, CompAccept< DocHRef >::m_children, Mapper::map(), TokenInfo::name, RetVal_OK, TK_COMMAND, TK_HTMLTAG, TK_SYMBOL, tokToString(), and warn_doc_error().
Referenced by handleAHref().
relPath()
QCString DocHRef::relPath () const inline
Definition at line 878 of file docparser.h.
References m_relPath.
Referenced by HtmlDocVisitor::visitPre().
url()
QCString DocHRef::url () const inline
Definition at line 877 of file docparser.h.
References m_url.
Referenced by DocbookDocVisitor::visitPre(), RTFDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), XmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
Member Data Documentation
m_attribs
HtmlAttribList DocHRef::m_attribs private
Definition at line 884 of file docparser.h.
Referenced by attribs().
m_relPath
QCString DocHRef::m_relPath private
Definition at line 886 of file docparser.h.
Referenced by relPath().
m_url
QCString DocHRef::m_url private
Definition at line 885 of file docparser.h.
Referenced by url().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp