Doxygen: src/definition.cpp File Reference
definition.cpp File Reference
#include <ctype.h>
#include <qregexp.h>
#include "md5.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "config.h"
#include "definition.h"
#include "doxygen.h"
#include "language.h"
#include "message.h"
#include "outputlist.h"
#include "code.h"
#include "util.h"
#include "groupdef.h"
#include "pagedef.h"
#include "section.h"
#include "htags.h"
#include "parserintf.h"
#include "marshal.h"
#include "debug.h"
#include "vhdldocgen.h"
#include "memberlist.h"
#include "namespacedef.h"
#include "filedef.h"
#include "dirdef.h"
Classes
class DefinitionImpl
Private data associated with a Symbol Definition object.
Macros
#define START_MARKER 0x4445465B
#define END_MARKER 0x4445465D
#define uni_isupper(c) (QChar(c).category()==QChar::Letter_Uppercase)
Functions
static bool matchExcludedSymbols (const char *name)
static bool lastCharIsMultibyte (const QCString &s)
bool readCodeFragment (const char *fileName, int &startLine, int &endLine, QCString &result)
Reads a fragment from file fileName starting with line startLine and ending with line endLine.
static bool stripWord (QCString &s, QCString w)
QCString abbreviate (const char *s, const char *name)
Macro Definition Documentation
END_MARKER
#define END_MARKER 0x4445465D
Definition at line 46 of file definition.cpp.
START_MARKER
#define START_MARKER 0x4445465B
Definition at line 45 of file definition.cpp.
uni_isupper
#define uni_isupper (c) (QChar(c).category()==QChar::Letter_Uppercase)
Definition at line 618 of file definition.cpp.
Referenced by Definition::_setBriefDescription().
Function Documentation
abbreviate()
QCString abbreviate (const char * s, const char * name)
Definition at line 1720 of file definition.cpp.
References Config_getList, and stripWord().
Referenced by Definition::briefDescription().
lastCharIsMultibyte()
static bool lastCharIsMultibyte (const QCString & s) static
Definition at line 622 of file definition.cpp.
References nextUtf8CharPosition().
Referenced by Definition::_setBriefDescription().
matchExcludedSymbols()
static bool matchExcludedSymbols (const char * name) static
Definition at line 150 of file definition.cpp.
References Config_getList, isId(), and substitute().
Referenced by Definition::Definition().
readCodeFragment()
bool readCodeFragment (const char * fileName, int & startLine, int & endLine, QCString & result)
Reads a fragment from file fileName starting with line startLine and ending with line endLine.
Reads a fragment of code from file fileName starting at line startLine and ending at line endLine (inclusive). The fragment is stored in result. If FALSE is returned the code fragment could not be found.
The file is scanned for a opening bracket ('{') from startLine onward The line actually containing the bracket is returned via startLine. The file is scanned for a closing bracket ('}') from endLine backward. The line actually containing the bracket is returned via endLine. Note that for VHDL code the bracket search is not done.
Definition at line 728 of file definition.cpp.
References Config_getBool, Config_getInt, Debug::ExtCmd, Debug::FilterOutput, getFileFilter(), getLanguageFromFileName(), portable_fopen(), portable_pclose(), portable_popen(), Debug::print(), SrcLangExt_Fortran, SrcLangExt_Python, SrcLangExt_Tcl, SrcLangExt_VHDL, and transcodeCharacterStringToUTF8().
Referenced by VhdlDocGen::createFlowChart(), MemberContext::Private::sourceCode(), and Definition::writeInlineCode().
stripWord()
static bool stripWord (QCString & s, QCString w) static
Definition at line 1707 of file definition.cpp.
Referenced by abbreviate().