Doxygen: LayoutDocManager Class Reference
LayoutDocManager Class Reference
Singleton providing access to the (user configurable) layout of the documentation.
#include <layout.h>
Classes
class Private
Public Types
enum LayoutPart {
Class, Namespace, File, Group,
Directory, NrParts
}
Public Member Functions
const QList< LayoutDocEntry > & docEntries (LayoutPart part) const
Returns the list of LayoutDocEntry's in representation order for a given page identified by part.
LayoutNavEntry * rootNavEntry () const
returns the (invisible) root of the navigation tree.
void parse (QTextStream &t, const char *fileName)
Parses a user provided layout.
void init ()
Static Public Member Functions
static LayoutDocManager & instance ()
Returns a reference to this singleton.
Private Member Functions
void addEntry (LayoutPart p, LayoutDocEntry *e)
void clear (LayoutPart p)
LayoutDocManager ()
~LayoutDocManager ()
Private Attributes
Private * d
Friends
class LayoutParser
Detailed Description
Singleton providing access to the (user configurable) layout of the documentation.
Definition at line 173 of file layout.h.
Member Enumeration Documentation
LayoutPart
enum LayoutDocManager::LayoutPart
Enumerator
Class
Namespace
File
Group
Directory
NrParts
Definition at line 177 of file layout.h.
Constructor & Destructor Documentation
LayoutDocManager()
LayoutDocManager::LayoutDocManager () private
Definition at line 1328 of file layout.cpp.
References d, LayoutDocManager::Private::docEntries, LayoutParser::init(), LayoutParser::instance(), NrParts, Private, and LayoutDocManager::Private::rootNav.
Referenced by instance().
~LayoutDocManager()
LayoutDocManager::~LayoutDocManager () private
Definition at line 1353 of file layout.cpp.
References d, and LayoutDocManager::Private::rootNav.
Member Function Documentation
addEntry()
void LayoutDocManager::addEntry (LayoutDocManager::LayoutPart p, LayoutDocEntry * e) private
Definition at line 1375 of file layout.cpp.
References d, and LayoutDocManager::Private::docEntries.
Referenced by LayoutParser::endMemberDecl(), LayoutParser::endMemberDef(), LayoutParser::startMemberDecl(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDef(), LayoutParser::startMemberDefEntry(), LayoutParser::startSectionEntry(), and LayoutParser::startSimpleEntry().
clear()
void LayoutDocManager::clear (LayoutDocManager::LayoutPart p) private
Definition at line 1380 of file layout.cpp.
References d, and LayoutDocManager::Private::docEntries.
Referenced by LayoutParser::startClass(), LayoutParser::startDirectory(), LayoutParser::startFile(), LayoutParser::startGroup(), and LayoutParser::startNamespace().
docEntries()
const QList< LayoutDocEntry > & LayoutDocManager::docEntries (LayoutDocManager::LayoutPart part) const
Returns the list of LayoutDocEntry's in representation order for a given page identified by part.
Definition at line 1365 of file layout.cpp.
References d, and LayoutDocManager::Private::docEntries.
init()
void LayoutDocManager::init ()
Definition at line 1341 of file layout.cpp.
References LayoutParser::instance(), and layout_default.
Referenced by parseInput().
instance()
LayoutDocManager & LayoutDocManager::instance () static
Returns a reference to this singleton.
Definition at line 1359 of file layout.cpp.
References LayoutDocManager().
Referenced by addMembersToIndex(), ClassDef::countAdditionalInheritedMembers(), LayoutParser::endMemberDecl(), LayoutParser::endMemberDef(), generateJSNavTree(), ClassDef::getTitleForMemberListType(), parseInput(), renderQuickLinksAsTabs(), LayoutParser::startClass(), LayoutParser::startDirectory(), LayoutParser::startFile(), LayoutParser::startGroup(), LayoutParser::startMemberDecl(), LayoutParser::startMemberDeclEntry(), LayoutParser::startMemberDef(), LayoutParser::startMemberDefEntry(), LayoutParser::startNamespace(), LayoutParser::startNavEntry(), LayoutParser::startNavIndex(), LayoutParser::startSectionEntry(), LayoutParser::startSimpleEntry(), ClassDef::writeAdditionalInheritedMembers(), writeAlphabeticalIndex(), writeAnnotatedIndex(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), ClassDef::writeDeclaration(), writeDefaultQuickLinks(), NamespaceDef::writeDocumentation(), GroupDef::writeDocumentation(), DirDef::writeDocumentation(), FileDef::writeDocumentation(), ClassDef::writeDocumentationContents(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGroupIndex(), writeGroupTreeNode(), writeHierarchicalIndex(), writeIndexHierarchy(), writeIndexHierarchyEntries(), ClassDef::writeInlineDocumentation(), writeMenuData(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), writePages(), NamespaceDef::writeSummaryLinks(), GroupDef::writeSummaryLinks(), FileDef::writeSummaryLinks(), ClassDef::writeSummaryLinks(), NamespaceDef::writeTagFile(), GroupDef::writeTagFile(), DirDef::writeTagFile(), FileDef::writeTagFile(), and ClassDef::writeTagFile().
parse()
void LayoutDocManager::parse (QTextStream & t, const char * fileName)
Parses a user provided layout.
Definition at line 1385 of file layout.cpp.
References LayoutParser::instance().
Referenced by parseInput().
rootNavEntry()
LayoutNavEntry * LayoutDocManager::rootNavEntry () const
returns the (invisible) root of the navigation tree.
Definition at line 1370 of file layout.cpp.
References d, and LayoutDocManager::Private::rootNav.
Referenced by generateJSNavTree(), renderQuickLinksAsTabs(), LayoutParser::startNavEntry(), LayoutParser::startNavIndex(), writeAlphabeticalIndex(), writeAnnotatedIndex(), writeClassMemberIndex(), writeClassMemberIndexFiltered(), writeDefaultQuickLinks(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGroupIndex(), writeHierarchicalIndex(), writeIndexHierarchy(), writeMenuData(), writeNamespaceIndex(), writeNamespaceMemberIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), and writePages().
Friends And Related Function Documentation
LayoutParser
friend class LayoutParser friend
Definition at line 200 of file layout.h.
Member Data Documentation
d
Private* LayoutDocManager::d private
Definition at line 199 of file layout.h.
Referenced by addEntry(), clear(), docEntries(), LayoutDocManager(), rootNavEntry(), and ~LayoutDocManager().
The documentation for this class was generated from the following files:
src/layout.h
src/layout.cpp