Doxygen: TemplateNodeFor Class Reference
TemplateNodeFor Class Reference
Class representing a 'for' tag in a template.
Public Member Functions
TemplateNodeFor (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeFor ()
void render (FTextStream &ts, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeFor >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Private Attributes
bool m_reversed
ExprAst * m_expr
QValueList< QCString > m_vars
TemplateNodeList m_loopNodes
TemplateNodeList m_emptyNodes
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeFor >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeFor >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeFor >
QCString m_templateName
int m_line
Detailed Description
Class representing a 'for' tag in a template.
Definition at line 3188 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeFor()
TemplateNodeFor::TemplateNodeFor (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 3191 of file template.cpp.
References TemplateToken::data, m_emptyNodes, m_expr, m_loopNodes, m_reversed, TemplateNodeCreator< TemplateNodeFor >::m_templateName, m_vars, TemplateParser::parse(), ExpressionParser::parse(), TemplateParser::removeNextToken(), split(), TemplateParser::takeNextToken(), TRACE, and TemplateParser::warn().
~TemplateNodeFor()
TemplateNodeFor::~TemplateNodeFor () inline
Definition at line 3251 of file template.cpp.
References m_expr.
Member Function Documentation
render()
void TemplateNodeFor::render (FTextStream & ts, TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 3256 of file template.cpp.
References TemplateStruct::alloc(), TemplateVariant::call(), TemplateListIntf::count(), TemplateListIntf::createIterator(), TemplateListIntf::ConstIterator::current(), TemplateVariant::Function, TemplateAutoRef< T >::get(), TemplateStructIntf::get(), TemplateContext::getRef(), m_emptyNodes, m_expr, TemplateNodeCreator< TemplateNodeFor >::m_line, m_loopNodes, m_reversed, TemplateNodeCreator< TemplateNodeFor >::m_templateName, m_vars, TemplateContext::pop(), TemplateContext::push(), TemplateNodeList::render(), ExprAst::resolve(), TemplateStruct::set(), TemplateContext::set(), TemplateContextImpl::setLocation(), TemplateVariant::Struct, TemplateListIntf::ConstIterator::toFirst(), TemplateListIntf::ConstIterator::toLast(), TemplateVariant::toList(), TemplateListIntf::ConstIterator::toNext(), TemplateListIntf::ConstIterator::toPrev(), TemplateVariant::toStruct(), TemplateVariant::type(), TemplateVariant::typeAsString(), and TemplateContextImpl::warn().
Member Data Documentation
m_emptyNodes
TemplateNodeList TemplateNodeFor::m_emptyNodes private
Definition at line 3339 of file template.cpp.
Referenced by render(), and TemplateNodeFor().
m_expr
ExprAst* TemplateNodeFor::m_expr private
Definition at line 3336 of file template.cpp.
Referenced by render(), TemplateNodeFor(), and ~TemplateNodeFor().
m_loopNodes
TemplateNodeList TemplateNodeFor::m_loopNodes private
Definition at line 3338 of file template.cpp.
Referenced by render(), and TemplateNodeFor().
m_reversed
bool TemplateNodeFor::m_reversed private
Definition at line 3335 of file template.cpp.
Referenced by render(), and TemplateNodeFor().
m_vars
QValueList<QCString> TemplateNodeFor::m_vars private
Definition at line 3337 of file template.cpp.
Referenced by render(), and TemplateNodeFor().
The documentation for this class was generated from the following file:
src/template.cpp