Doxygen: ClangParser Class Reference
ClangParser Class Reference
Wrapper for to let libclang assisted parsing.
#include <clangparser.h>
Public Member Functions
void start (const char *fileName, QStrList &filesInTranslationUnit)
Start parsing a file.
void switchToFile (const char *fileName)
Switches to another file within the translation unit started with start().
void finish ()
Finishes parsing a translation unit.
QCString lookup (uint line, const char *symbol)
Looks for symbol which should be found at line and returns a clang unique reference to the symbol.
void writeSources (CodeOutputInterface &ol, FileDef *fd)
writes the syntax highlighted source code for a file
Static Public Member Functions
static ClangParser * instance ()
Returns the one and only instance of the class.
Private Member Functions
void linkIdentifier (CodeOutputInterface &ol, FileDef *fd, uint &line, uint &column, const char *text, int tokenIndex)
void linkMacro (CodeOutputInterface &ol, FileDef *fd, uint &line, uint &column, const char *text)
void linkInclude (CodeOutputInterface &ol, FileDef *fd, uint &line, uint &column, const char *text)
void determineInputFilesInSameTu (QStrList &filesInTranslationUnit)
ClangParser ()
virtual ~ClangParser ()
Private Attributes
Private * p
Static Private Attributes
static ClangParser * s_instance = 0
Detailed Description
Wrapper for to let libclang assisted parsing.
Definition at line 11 of file clangparser.h.
Constructor & Destructor Documentation
ClangParser()
ClangParser::ClangParser () private
Definition at line 931 of file clangparser.cpp.
Referenced by instance().
~ClangParser()
ClangParser::~ClangParser () private virtual
Definition at line 935 of file clangparser.cpp.
Member Function Documentation
determineInputFilesInSameTu()
void ClangParser::determineInputFilesInSameTu (QStrList & filesInTranslationUnit) private
finish()
void ClangParser::finish ()
Finishes parsing a translation unit.
Free any resources that were needed for parsing.
Definition at line 918 of file clangparser.cpp.
Referenced by FileDef::finishParsing().
instance()
ClangParser * ClangParser::instance () static
Returns the one and only instance of the class.
Definition at line 30 of file clangparser.cpp.
References ClangParser(), and s_instance.
Referenced by FileDef::finishParsing(), FileDef::parseSource(), and FileDef::writeSource().
linkIdentifier()
void ClangParser::linkIdentifier (CodeOutputInterface & ol, FileDef * fd, uint & line, uint & column, const char * text, int tokenIndex) private
linkInclude()
void ClangParser::linkInclude (CodeOutputInterface & ol, FileDef * fd, uint & line, uint & column, const char * text) private
linkMacro()
void ClangParser::linkMacro (CodeOutputInterface & ol, FileDef * fd, uint & line, uint & column, const char * text) private
lookup()
QCString ClangParser::lookup (uint line, const char * symbol)
Looks for symbol which should be found at line and returns a clang unique reference to the symbol.
Definition at line 922 of file clangparser.cpp.
start()
void ClangParser::start (const char * fileName, QStrList & filesInTranslationUnit)
Start parsing a file.
Parameters
[in] fileName The name of the file to parse.
[in,out] filesInTranslationUnit Other files that are part of the input and included by the file. The function will return a subset of the files, only including the onces that were actually found during parsing.
Definition at line 910 of file clangparser.cpp.
Referenced by FileDef::parseSource(), and FileDef::writeSource().
switchToFile()
void ClangParser::switchToFile (const char * fileName)
Switches to another file within the translation unit started with start().
Parameters
[in] fileName The name of the file to switch to.
Definition at line 914 of file clangparser.cpp.
Referenced by FileDef::parseSource(), and FileDef::writeSource().
writeSources()
void ClangParser::writeSources (CodeOutputInterface & ol, FileDef * fd)
writes the syntax highlighted source code for a file
Parameters
[out] ol The output generator list to write to.
[in] fd The file to write sources for.
Definition at line 927 of file clangparser.cpp.
Referenced by FileDef::parseSource(), and FileDef::writeSource().
Member Data Documentation
p
Private* ClangParser::p private
Definition at line 60 of file clangparser.h.
s_instance
ClangParser * ClangParser::s_instance = 0 static private
Definition at line 64 of file clangparser.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/clangparser.h
src/clangparser.cpp