Doxygen: ClassContext Class Reference
ClassContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static ClassContext * alloc (ClassDef *cd)
Private Member Functions
ClassContext (ClassDef *)
~ClassContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 253 of file context.h.
Constructor & Destructor Documentation
ClassContext()
ClassContext::ClassContext (ClassDef * cd) private
Definition at line 2643 of file context.cpp.
References p, and Private.
Referenced by alloc().
~ClassContext()
ClassContext::~ClassContext () private
Definition at line 2649 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int ClassContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 260 of file context.h.
References RefCountedContext::addRef().
alloc()
static ClassContext* ClassContext::alloc (ClassDef * cd) inline static
Definition at line 256 of file context.h.
References ClassContext().
Referenced by ClassListContext::Private::addClasses(), MemberContext::Private::anonymousType(), MemberContext::Private::category(), ClassContext::Private::categoryOf(), ClassContext::Private::classes(), NamespaceContext::Private::classes(), FileContext::Private::classes(), ModuleContext::Private::classes(), MemberContext::Private::getClass(), NestingNodeContext::Private::getClass(), InheritanceNodeContext::Private::getClass(), InheritedMemberInfoContext::Private::getClass(), NamespaceContext::Private::inlineClasses(), FileContext::Private::inlineClasses(), ModuleContext::Private::inlineClasses(), ClassContext::Private::innerClasses(), and ClassIndexContext::Private::list().
get()
TemplateVariant ClassContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 2654 of file context.cpp.
References ClassContext::Private::get(), and p.
release()
virtual int ClassContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 261 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ClassContext::p private
Definition at line 266 of file context.h.
Referenced by ClassContext(), get(), and ~ClassContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp