Doxygen: NamespaceMembersIndexContext Class Reference
NamespaceMembersIndexContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static NamespaceMembersIndexContext * alloc ()
Private Member Functions
NamespaceMembersIndexContext ()
~NamespaceMembersIndexContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 870 of file context.h.
Constructor & Destructor Documentation
NamespaceMembersIndexContext()
NamespaceMembersIndexContext::NamespaceMembersIndexContext () private
Definition at line 8295 of file context.cpp.
References p, and Private.
Referenced by alloc().
~NamespaceMembersIndexContext()
NamespaceMembersIndexContext::~NamespaceMembersIndexContext () private
Definition at line 8300 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int NamespaceMembersIndexContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 877 of file context.h.
References RefCountedContext::addRef().
alloc()
static NamespaceMembersIndexContext* NamespaceMembersIndexContext::alloc () inline static
Definition at line 873 of file context.h.
References NamespaceMembersIndexContext().
Referenced by generateOutputViaTemplate().
get()
TemplateVariant NamespaceMembersIndexContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 8305 of file context.cpp.
References NamespaceMembersIndexContext::Private::get(), and p.
release()
virtual int NamespaceMembersIndexContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 878 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* NamespaceMembersIndexContext::p private
Definition at line 883 of file context.h.
Referenced by get(), NamespaceMembersIndexContext(), and ~NamespaceMembersIndexContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp