Doxygen: NestingContext Class Reference
NestingContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
void addNamespaces (const NamespaceSDict &nsDict, bool rootOnly, bool addClasses)
void addClasses (const ClassSDict &clDict, bool rootOnly)
void addDirs (const DirSDict &)
void addDirs (const DirList &)
void addFiles (const FileNameList &)
void addFiles (const FileList &)
void addPages (const PageSDict &pages, bool rootOnly)
void addModules (const GroupSDict &modules)
void addModules (const GroupList &modules)
void addClassHierarchy (const ClassSDict &clDict, bool rootOnly)
void addDerivedClasses (const BaseClassList *bcl, bool hideSuper)
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static NestingContext * alloc (const NestingNodeContext *parent, int level)
Private Member Functions
NestingContext (const NestingNodeContext *parent, int level)
~NestingContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 533 of file context.h.
Constructor & Destructor Documentation
NestingContext()
NestingContext::NestingContext (const NestingNodeContext * parent, int level) private
Definition at line 6635 of file context.cpp.
References p, and Private.
Referenced by alloc().
~NestingContext()
NestingContext::~NestingContext () private
Definition at line 6640 of file context.cpp.
References p.
Member Function Documentation
addClasses()
void NestingContext::addClasses (const ClassSDict & clDict, bool rootOnly)
Definition at line 6661 of file context.cpp.
References NestingContext::Private::addClasses(), and p.
Referenced by NestingNodeContext::Private::addClasses(), NestingNodeContext::Private::addNamespaces(), and ClassTreeContext::Private::Private().
addClassHierarchy()
void NestingContext::addClassHierarchy (const ClassSDict & clDict, bool rootOnly)
Definition at line 6706 of file context.cpp.
References NestingContext::Private::addClassHierarchy(), and p.
Referenced by ClassHierarchyContext::Private::Private().
addDerivedClasses()
void NestingContext::addDerivedClasses (const BaseClassList * bcl, bool hideSuper)
Definition at line 6711 of file context.cpp.
References NestingContext::Private::addDerivedClasses(), and p.
Referenced by NestingNodeContext::Private::addClasses().
addDirs() [1/2]
void NestingContext::addDirs (const DirSDict & dirs)
Definition at line 6671 of file context.cpp.
References NestingContext::Private::addDirs(), and p.
Referenced by NestingNodeContext::Private::addDirFiles(), and FileTreeContext::Private::Private().
addDirs() [2/2]
void NestingContext::addDirs (const DirList & dirs)
Definition at line 6676 of file context.cpp.
References NestingContext::Private::addDirs(), and p.
addFiles() [1/2]
void NestingContext::addFiles (const FileNameList & files)
Definition at line 6681 of file context.cpp.
References NestingContext::Private::addFiles(), and p.
Referenced by NestingNodeContext::Private::addDirFiles(), and FileTreeContext::Private::Private().
addFiles() [2/2]
void NestingContext::addFiles (const FileList & files)
Definition at line 6686 of file context.cpp.
References NestingContext::Private::addFiles(), and p.
addModules() [1/2]
void NestingContext::addModules (const GroupSDict & modules)
Definition at line 6696 of file context.cpp.
References NestingContext::Private::addModules(), and p.
Referenced by NestingNodeContext::Private::addModules(), and ModuleTreeContext::Private::Private().
addModules() [2/2]
void NestingContext::addModules (const GroupList & modules)
Definition at line 6701 of file context.cpp.
References NestingContext::Private::addModules(), and p.
addNamespaces()
void NestingContext::addNamespaces (const NamespaceSDict & nsDict, bool rootOnly, bool addClasses)
Definition at line 6666 of file context.cpp.
References NestingContext::Private::addNamespaces(), and p.
Referenced by NestingNodeContext::Private::addNamespaces(), ClassTreeContext::Private::Private(), and NamespaceTreeContext::Private::Private().
addPages()
void NestingContext::addPages (const PageSDict & pages, bool rootOnly)
Definition at line 6691 of file context.cpp.
References NestingContext::Private::addPages(), and p.
Referenced by NestingNodeContext::Private::addPages(), PageTreeContext::Private::Private(), and ExampleTreeContext::Private::Private().
addRef()
virtual int NestingContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 543 of file context.h.
References RefCountedContext::addRef().
alloc()
static NestingContext* NestingContext::alloc (const NestingNodeContext * parent, int level) inline static
Definition at line 536 of file context.h.
References NestingContext().
Referenced by ClassHierarchyContext::Private::Private(), NestingNodeContext::Private::Private(), ClassTreeContext::Private::Private(), NamespaceTreeContext::Private::Private(), FileTreeContext::Private::Private(), PageTreeContext::Private::Private(), ModuleTreeContext::Private::Private(), and ExampleTreeContext::Private::Private().
at()
TemplateVariant NestingContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6651 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int NestingContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 6646 of file context.cpp.
References GenericNodeListContext::count(), and p.
Referenced by NestingNodeContext::Private::isLeafNode().
createIterator()
TemplateListIntf::ConstIterator * NestingContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6656 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int NestingContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 544 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* NestingContext::p private
Definition at line 561 of file context.h.
Referenced by addClasses(), addClassHierarchy(), addDerivedClasses(), addDirs(), addFiles(), addModules(), addNamespaces(), addPages(), at(), count(), createIterator(), NestingContext(), and ~NestingContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp