Doxygen: TemplateNodeList Class Reference
TemplateNodeList Class Reference
Class representing a list of AST nodes in a template.
Public Member Functions
TemplateNodeList ()
void render (FTextStream &ts, TemplateContext *c)
Detailed Description
Class representing a list of AST nodes in a template.
Definition at line 2307 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeList()
TemplateNodeList::TemplateNodeList () inline
Definition at line 2310 of file template.cpp.
Member Function Documentation
render()
void TemplateNodeList::render (FTextStream & ts, TemplateContext * c) inline
Definition at line 2314 of file template.cpp.
References TemplateNode::render(), and TRACE.
Referenced by TemplateImpl::render(), TemplateNodeIf::render(), TemplateNodeRepeat::render(), TemplateNodeRange::render(), TemplateNodeFor::render(), TemplateNodeMsg::render(), TemplateNodeBlock::render(), TemplateNodeWith::render(), TemplateNodeSpaceless::render(), TemplateNodeMarkers::render(), TemplateNodeTabbing::render(), TemplateNodeEncoding::render(), and TemplateNodeTree::renderChildren().
The documentation for this class was generated from the following file:
src/template.cpp