Doxygen: FileContext Class Reference
FileContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static FileContext * alloc (FileDef *fd)
Private Member Functions
FileContext (FileDef *)
~FileContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 291 of file context.h.
Constructor & Destructor Documentation
FileContext()
FileContext::FileContext (FileDef * fd) private
Definition at line 3365 of file context.cpp.
References p, and Private.
Referenced by alloc().
~FileContext()
FileContext::~FileContext () private
Definition at line 3370 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int FileContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 298 of file context.h.
References RefCountedContext::addRef().
alloc()
static FileContext* FileContext::alloc (FileDef * fd) inline static
Definition at line 294 of file context.h.
References FileContext().
Referenced by UsedFilesContext::Private::addFile(), FileListContext::Private::addFiles(), IncludeInfoContext::Private::file(), DirContext::Private::files(), ModuleContext::Private::files(), MemberContext::Private::getFile(), and NestingNodeContext::Private::getFile().
get()
TemplateVariant FileContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 3375 of file context.cpp.
References FileContext::Private::get(), and p.
release()
virtual int FileContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 299 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* FileContext::p private
Definition at line 304 of file context.h.
Referenced by FileContext(), get(), and ~FileContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp