Doxygen: ExprAstFunctionVariable Class Reference
ExprAstFunctionVariable Class Reference
Public Member Functions
ExprAstFunctionVariable (ExprAst *var, const QList< ExprAst > &args)
~ExprAstFunctionVariable ()
virtual TemplateVariant resolve (TemplateContext *c)
Public Member Functions inherited from ExprAst
virtual ~ExprAst ()
Private Attributes
ExprAst * m_var
QList< ExprAst > m_args
Detailed Description
Definition at line 1472 of file template.cpp.
Constructor & Destructor Documentation
ExprAstFunctionVariable()
ExprAstFunctionVariable::ExprAstFunctionVariable (ExprAst * var, const QList< ExprAst > & args) inline
Definition at line 1475 of file template.cpp.
References m_args, and TRACE.
~ExprAstFunctionVariable()
ExprAstFunctionVariable::~ExprAstFunctionVariable () inline
Definition at line 1480 of file template.cpp.
References m_var.
Member Function Documentation
resolve()
virtual TemplateVariant ExprAstFunctionVariable::resolve (TemplateContext * c) inline virtual
Reimplemented from ExprAst.
Definition at line 1484 of file template.cpp.
References TemplateVariant::call(), TemplateVariant::Function, m_args, m_var, ExprAst::resolve(), and TemplateVariant::type().
Member Data Documentation
m_args
QList<ExprAst> ExprAstFunctionVariable::m_args private
Definition at line 1501 of file template.cpp.
Referenced by ExprAstFunctionVariable(), and resolve().
m_var
ExprAst* ExprAstFunctionVariable::m_var private
Definition at line 1500 of file template.cpp.
Referenced by resolve(), and ~ExprAstFunctionVariable().
The documentation for this class was generated from the following file:
src/template.cpp