Doxygen: DotCallGraph Class Reference
DotCallGraph Class Reference
Representation of an call graph.
#include <dot.h>
Public Member Functions
DotCallGraph (MemberDef *md, bool inverse)
~DotCallGraph ()
QCString writeGraph (FTextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const char *path, const char *fileName, const char *relPath, bool writeImageMap=TRUE, int graphId=-1) const
void buildGraph (DotNode *n, MemberDef *md, int distance)
bool isTrivial () const
bool isTooBig () const
void determineVisibleNodes (QList< DotNode > &queue, int &maxNodes)
void determineTruncatedNodes (QList< DotNode > &queue)
Static Public Member Functions
static void resetNumbering ()
Private Attributes
DotNode * m_startNode
QDict< DotNode > * m_usedNodes
bool m_inverse
QCString m_diskName
Definition * m_scope
Static Private Attributes
static int m_curNodeNumber = 0
Detailed Description
Representation of an call graph.
Definition at line 232 of file dot.h.
Constructor & Destructor Documentation
DotCallGraph()
DotCallGraph::DotCallGraph (MemberDef * md, bool inverse)
Definition at line 3721 of file dot.cpp.
References MemberDef::anchor(), buildGraph(), Config_getBool, Config_getInt, determineTruncatedNodes(), determineVisibleNodes(), Definition::getLanguage(), Definition::getOuterScope(), MemberDef::getOutputFileBase(), MemberDef::getReference(), linkToText(), m_curNodeNumber, m_diskName, m_inverse, m_scope, m_startNode, m_usedNodes, Definition::name(), MemberDef::qualifiedName(), and DotNode::setDistance().
~DotCallGraph()
DotCallGraph::~DotCallGraph ()
Definition at line 3763 of file dot.cpp.
References deleteNodes(), m_startNode, and m_usedNodes.
Member Function Documentation
buildGraph()
void DotCallGraph::buildGraph (DotNode * n, MemberDef * md, int distance)
Definition at line 3612 of file dot.cpp.
References DotNode::addChild(), DotNode::addParent(), MemberDef::anchor(), Definition::briefDescriptionAsTooltip(), Config_getBool, Definition::getLanguage(), Definition::getOuterScope(), MemberDef::getOutputFileBase(), MemberDef::getReference(), Definition::getReferencedByMembers(), Definition::getReferencesMembers(), SDict< MemberDef >::Iterator, linkToText(), m_curNodeNumber, m_inverse, m_scope, m_usedNodes, Definition::name(), MemberDef::qualifiedName(), DotNode::setDistance(), and MemberDef::showInCallGraph().
Referenced by DotCallGraph().
determineTruncatedNodes()
void DotCallGraph::determineTruncatedNodes (QList< DotNode > & queue)
Definition at line 3689 of file dot.cpp.
References DotNode::isTruncated(), DotNode::isVisible(), DotNode::m_children, DotNode::markAsTruncated(), and DotNode::Unknown.
Referenced by DotCallGraph().
determineVisibleNodes()
void DotCallGraph::determineVisibleNodes (QList< DotNode > & queue, int & maxNodes)
Definition at line 3665 of file dot.cpp.
References Config_getInt, DotNode::distance(), DotNode::isVisible(), DotNode::m_children, and DotNode::markAsVisible().
Referenced by DotCallGraph().
isTooBig()
bool DotCallGraph::isTooBig () const
Definition at line 3904 of file dot.cpp.
References Config_getInt, DotNode::m_children, and m_startNode.
Referenced by MemberDef::_writeCallerGraph(), MemberDef::_writeCallGraph(), MemberContext::Private::hasCallerGraph(), and MemberContext::Private::hasCallGraph().
isTrivial()
bool DotCallGraph::isTrivial () const
Definition at line 3899 of file dot.cpp.
References DotNode::m_children, and m_startNode.
Referenced by MemberDef::_writeCallerGraph(), MemberDef::_writeCallGraph(), MemberContext::Private::hasCallerGraph(), and MemberContext::Private::hasCallGraph().
resetNumbering()
void DotCallGraph::resetNumbering () static
Definition at line 3716 of file dot.cpp.
References m_curNodeNumber.
Referenced by resetDotNodeNumbering().
writeGraph()
QCString DotCallGraph::writeGraph (FTextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const char * path, const char * fileName, const char * relPath, bool writeImageMap = TRUE, int graphId = -1) const
Definition at line 3769 of file dot.cpp.
References DotManager::addFigure(), IndexList::addImageFile(), DotRunner::addJob(), DotManager::addMap(), DotManager::addRun(), DotManager::addSVGConversion(), DotManager::addSVGObject(), DotNode::CallGraph, checkDeliverables(), Config_getBool, Config_getEnum, endl(), EOF_DocBook, err(), getDotImageExtension(), GOF_BITMAP, GOF_EPS, Doxygen::indexList, insertMapFile(), DotManager::instance(), DotNode::label(), m_diskName, m_inverse, m_startNode, MAP_CMD, removeDotGraph(), updateDotGraph(), writeSVGFigureLink(), and writeVecGfxFigure().
Referenced by MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), RTFGenerator::endCallGraph(), LatexGenerator::endCallGraph(), and HtmlGenerator::endCallGraph().
Member Data Documentation
m_curNodeNumber
int DotCallGraph::m_curNodeNumber = 0 static private
Definition at line 250 of file dot.h.
Referenced by buildGraph(), DotCallGraph(), and resetNumbering().
m_diskName
QCString DotCallGraph::m_diskName private
Definition at line 253 of file dot.h.
Referenced by DotCallGraph(), and writeGraph().
m_inverse
bool DotCallGraph::m_inverse private
Definition at line 252 of file dot.h.
Referenced by buildGraph(), DotCallGraph(), and writeGraph().
m_scope
Definition* DotCallGraph::m_scope private
Definition at line 254 of file dot.h.
Referenced by buildGraph(), and DotCallGraph().
m_startNode
DotNode* DotCallGraph::m_startNode private
Definition at line 249 of file dot.h.
Referenced by DotCallGraph(), isTooBig(), isTrivial(), writeGraph(), and ~DotCallGraph().
m_usedNodes
QDict<DotNode>* DotCallGraph::m_usedNodes private
Definition at line 251 of file dot.h.
Referenced by buildGraph(), DotCallGraph(), and ~DotCallGraph().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp