Doxygen: DefinitionIntf Class Reference
DefinitionIntf Class Reference abstract
Abstract interface for a Definition or DefinitionList.
#include <definition.h>
Public Types
enum DefType {
TypeClass = 0, TypeFile = 1, TypeNamespace = 2, TypeMember = 3,
TypeGroup = 4, TypePackage = 5, TypePage = 6, TypeDir = 7,
TypeSymbolList = 8
}
Public Member Functions
DefinitionIntf ()
virtual ~DefinitionIntf ()
virtual DefType definitionType () const =0
Detailed Description
Abstract interface for a Definition or DefinitionList.
Definition at line 65 of file definition.h.
Member Enumeration Documentation
DefType
enum DefinitionIntf::DefType
Types of derived classes
Enumerator
TypeClass
TypeFile
TypeNamespace
TypeMember
TypeGroup
TypePackage
TypePage
TypeDir
TypeSymbolList
Definition at line 71 of file definition.h.
Constructor & Destructor Documentation
DefinitionIntf()
DefinitionIntf::DefinitionIntf () inline
Definition at line 68 of file definition.h.
~DefinitionIntf()
virtual DefinitionIntf::~DefinitionIntf () inline virtual
Definition at line 69 of file definition.h.
Member Function Documentation
definitionType()
virtual DefType DefinitionIntf::definitionType () const pure virtual
Use this for dynamic inspection of the type of the derived class
Implemented in DefinitionList, ClassDef, FileDef, MemberDef, DirDef, GroupDef, NamespaceDef, and PageDef.
Referenced by NestingNodeContext::Private::addClasses(), NestingNodeContext::Private::addDirFiles(), DocSets::addIndexItem(), PageDef::addInnerCompound(), NamespaceDef::addInnerCompound(), ClassDef::addInnerCompound(), MemberDef::addListReference(), MemberList::addListReferences(), NestingNodeContext::Private::addModules(), NestingNodeContext::Private::addNamespaces(), NestingNodeContext::Private::addPages(), NestingContext::Private::addPages(), ClassContext::Private::addTemplateDecls(), Definition::addToMap(), SearchIndexList::append(), Definition::briefDescriptionAsTooltip(), DefinitionContext< T >::Cachable< NamespaceContext::Private >::Cachable(), cleanUpDoxygen(), DefinitionContext< FileContext::Private >::compoundKind(), definitionToName(), DocLink::DocLink(), DocRef::DocRef(), dumpSymbol(), dumpSymbolMap(), DefinitionContext< FileContext::Private >::fillPath(), findTagLessClasses(), followPath(), generateDocbookForMember(), generateDocbookSection(), generateJSTree(), generateLink(), generateOutputViaTemplate(), FTVHelp::generateTree(), generateXMLForMember(), generateXMLSection(), NestingNodeContext::Private::getClass(), NestingNodeContext::Private::getDir(), NestingNodeContext::Private::getFile(), MemberDef::getLabels(), getMemberFromSymbol(), NestingNodeContext::Private::getModule(), NestingNodeContext::Private::getNamespace(), NestingNodeContext::Private::getPage(), getResolvedClass(), getResolvedClassRec(), getResolvedSymbol(), Definition::getSourceFileBase(), ClassDef::getTemplateParameterLists(), handleLinkedWord(), PageDef::hasParentPage(), MemberListInfoContext::Private::inherited(), GroupDef::insertMember(), isAccessibleFrom(), isAccessibleFromWithExpScope(), linkifyText(), MemberDef::moveTo(), DefinitionContext< FileContext::Private >::navigationPath(), Definition::navigationPathAsString(), node2URL(), DocCopy::parse(), Definition::pathFragment(), ClassDef::qualifiedNameWithTemplateParameters(), resolveTypeDef(), resolveUserReferences(), SymbolContext::Private::scope(), scopeIsTemplate(), searchTemplateSpecs(), SearchIndex::setCurrentDoc(), substTypedef(), NavPathElemContext::Private::text(), validatingParseDoc(), writeClassTree(), writeDefArgumentList(), Definition::writeDocAnchorsToTagFile(), MemberList::writeDocumentation(), MemberDef::writeDocumentation(), Definition::writeInlineCode(), writeJavascriptSearchIndex(), MemberDef::writeMemberDocSimple(), writePageIndex(), MemberList::writeSimpleDocumentation(), and TooltipManager::writeTooltips().
The documentation for this class was generated from the following file:
src/definition.h