Doxygen: src/lodepng.h File Reference
lodepng.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Classes
struct LodeZlib_DeflateSettings
struct LodePNG_InfoColor
struct LodePNG_InfoPng
struct LodePNG_InfoRaw
struct LodePNG_EncodeSettings
struct LodePNG_Encoder
Macros
#define LODEPNG_COMPILE_ZLIB /*deflate&zlib encoder and deflate&zlib decoder*/
#define LODEPNG_COMPILE_PNG /*png encoder and png decoder*/
#define LODEPNG_COMPILE_ENCODER /*deflate&zlib encoder and png encoder*/
#define LODEPNG_COMPILE_DISK /*the optional built in harddisk file loading and saving functions*/
Typedefs
typedef struct LodeZlib_DeflateSettings LodeZlib_DeflateSettings
typedef struct LodePNG_InfoColor LodePNG_InfoColor
typedef struct LodePNG_InfoPng LodePNG_InfoPng
typedef struct LodePNG_InfoRaw LodePNG_InfoRaw
typedef struct LodePNG_EncodeSettings LodePNG_EncodeSettings
typedef struct LodePNG_Encoder LodePNG_Encoder
Functions
void LodeZlib_DeflateSettings_init (LodeZlib_DeflateSettings *settings)
unsigned LodeZlib_compress (unsigned char **out, size_t *outsize, const unsigned char *in, size_t insize, const LodeZlib_DeflateSettings *settings)
unsigned LodePNG_chunk_length (const unsigned char *chunk)
void LodePNG_chunk_type (char type[5], const unsigned char *chunk)
unsigned char LodePNG_chunk_type_equals (const unsigned char *chunk, const char *type)
unsigned char LodePNG_chunk_critical (const unsigned char *chunk)
unsigned char LodePNG_chunk_private (const unsigned char *chunk)
unsigned char LodePNG_chunk_safetocopy (const unsigned char *chunk)
unsigned char * LodePNG_chunk_data (unsigned char *chunk)
const unsigned char * LodePNG_chunk_data_const (const unsigned char *chunk)
unsigned LodePNG_chunk_check_crc (const unsigned char *chunk)
void LodePNG_chunk_generate_crc (unsigned char *chunk)
unsigned char * LodePNG_chunk_next (unsigned char *chunk)
const unsigned char * LodePNG_chunk_next_const (const unsigned char *chunk)
unsigned LodePNG_append_chunk (unsigned char **out, size_t *outlength, const unsigned char *chunk)
unsigned LodePNG_create_chunk (unsigned char **out, size_t *outlength, unsigned length, const char *type, const unsigned char *data)
void LodePNG_InfoColor_init (LodePNG_InfoColor *info)
void LodePNG_InfoColor_cleanup (LodePNG_InfoColor *info)
unsigned LodePNG_InfoColor_copy (LodePNG_InfoColor *dest, const LodePNG_InfoColor *source)
void LodePNG_InfoColor_clearPalette (LodePNG_InfoColor *info)
unsigned LodePNG_InfoColor_addPalette (LodePNG_InfoColor *info, unsigned char r, unsigned char g, unsigned char b, unsigned char a)
unsigned LodePNG_InfoColor_getBpp (const LodePNG_InfoColor *info)
unsigned LodePNG_InfoColor_getChannels (const LodePNG_InfoColor *info)
unsigned LodePNG_InfoColor_isGreyscaleType (const LodePNG_InfoColor *info)
unsigned LodePNG_InfoColor_isAlphaType (const LodePNG_InfoColor *info)
void LodePNG_InfoPng_init (LodePNG_InfoPng *info)
void LodePNG_InfoPng_cleanup (LodePNG_InfoPng *info)
unsigned LodePNG_InfoPng_copy (LodePNG_InfoPng *dest, const LodePNG_InfoPng *source)
void LodePNG_InfoRaw_init (LodePNG_InfoRaw *info)
void LodePNG_InfoRaw_cleanup (LodePNG_InfoRaw *info)
unsigned LodePNG_InfoRaw_copy (LodePNG_InfoRaw *dest, const LodePNG_InfoRaw *source)
unsigned LodePNG_convert (unsigned char *out, const unsigned char *in, LodePNG_InfoColor *infoOut, LodePNG_InfoColor *infoIn, unsigned w, unsigned h)
void LodePNG_EncodeSettings_init (LodePNG_EncodeSettings *settings)
void LodePNG_Encoder_init (LodePNG_Encoder *encoder)
void LodePNG_Encoder_cleanup (LodePNG_Encoder *encoder)
void LodePNG_Encoder_copy (LodePNG_Encoder *dest, const LodePNG_Encoder *source)
void LodePNG_encode (LodePNG_Encoder *encoder, unsigned char **out, size_t *outsize, const unsigned char *image, unsigned w, unsigned h)
unsigned LodePNG_encode32 (unsigned char **out, size_t *outsize, const unsigned char *image, unsigned w, unsigned h)
unsigned LodePNG_encode32f (const char *filename, const unsigned char *image, unsigned w, unsigned h)
unsigned LodePNG_loadFile (unsigned char **out, size_t *outsize, const char *filename)
unsigned LodePNG_saveFile (const unsigned char *buffer, size_t buffersize, const char *filename)
Variables
const LodeZlib_DeflateSettings LodeZlib_defaultDeflateSettings
Macro Definition Documentation
LODEPNG_COMPILE_DISK
#define LODEPNG_COMPILE_DISK /*the optional built in harddisk file loading and saving functions*/
Definition at line 43 of file lodepng.h.
LODEPNG_COMPILE_ENCODER
#define LODEPNG_COMPILE_ENCODER /*deflate&zlib encoder and png encoder*/
Definition at line 42 of file lodepng.h.
LODEPNG_COMPILE_PNG
#define LODEPNG_COMPILE_PNG /*png encoder and png decoder*/
Definition at line 40 of file lodepng.h.
LODEPNG_COMPILE_ZLIB
#define LODEPNG_COMPILE_ZLIB /*deflate&zlib encoder and deflate&zlib decoder*/
Definition at line 39 of file lodepng.h.
Typedef Documentation
LodePNG_Encoder
typedef struct LodePNG_Encoder LodePNG_Encoder
LodePNG_EncodeSettings
typedef struct LodePNG_EncodeSettings LodePNG_EncodeSettings
LodePNG_InfoColor
typedef struct LodePNG_InfoColor LodePNG_InfoColor
LodePNG_InfoPng
typedef struct LodePNG_InfoPng LodePNG_InfoPng
LodePNG_InfoRaw
typedef struct LodePNG_InfoRaw LodePNG_InfoRaw
LodeZlib_DeflateSettings
typedef struct LodeZlib_DeflateSettings LodeZlib_DeflateSettings
Function Documentation
LodePNG_append_chunk()
unsigned LodePNG_append_chunk (unsigned char ** out, size_t * outlength, const unsigned char * chunk)
LodePNG_chunk_check_crc()
unsigned LodePNG_chunk_check_crc (const unsigned char * chunk)
LodePNG_chunk_critical()
unsigned char LodePNG_chunk_critical (const unsigned char * chunk)
LodePNG_chunk_data()
unsigned char* LodePNG_chunk_data (unsigned char * chunk)
LodePNG_chunk_data_const()
const unsigned char* LodePNG_chunk_data_const (const unsigned char * chunk)
LodePNG_chunk_generate_crc()
void LodePNG_chunk_generate_crc (unsigned char * chunk)
LodePNG_chunk_length()
unsigned LodePNG_chunk_length (const unsigned char * chunk)
LodePNG_chunk_next()
unsigned char* LodePNG_chunk_next (unsigned char * chunk)
LodePNG_chunk_next_const()
const unsigned char* LodePNG_chunk_next_const (const unsigned char * chunk)
LodePNG_chunk_private()
unsigned char LodePNG_chunk_private (const unsigned char * chunk)
LodePNG_chunk_safetocopy()
unsigned char LodePNG_chunk_safetocopy (const unsigned char * chunk)
LodePNG_chunk_type()
void LodePNG_chunk_type (char type[5], const unsigned char * chunk)
LodePNG_chunk_type_equals()
unsigned char LodePNG_chunk_type_equals (const unsigned char * chunk, const char * type)
LodePNG_convert()
unsigned LodePNG_convert (unsigned char * out, const unsigned char * in, LodePNG_InfoColor * infoOut, LodePNG_InfoColor * infoIn, unsigned w, unsigned h)
LodePNG_create_chunk()
unsigned LodePNG_create_chunk (unsigned char ** out, size_t * outlength, unsigned length, const char * type, const unsigned char * data)
LodePNG_encode()
void LodePNG_encode (LodePNG_Encoder * encoder, unsigned char ** out, size_t * outsize, const unsigned char * image, unsigned w, unsigned h)
Referenced by Image::save(), and ColoredImage::save().
LodePNG_encode32()
unsigned LodePNG_encode32 (unsigned char ** out, size_t * outsize, const unsigned char * image, unsigned w, unsigned h)
LodePNG_encode32f()
unsigned LodePNG_encode32f (const char * filename, const unsigned char * image, unsigned w, unsigned h)
LodePNG_Encoder_cleanup()
void LodePNG_Encoder_cleanup (LodePNG_Encoder * encoder)
Referenced by Image::save(), and ColoredImage::save().
LodePNG_Encoder_copy()
void LodePNG_Encoder_copy (LodePNG_Encoder * dest, const LodePNG_Encoder * source)
LodePNG_Encoder_init()
void LodePNG_Encoder_init (LodePNG_Encoder * encoder)
Referenced by Image::save(), and ColoredImage::save().
LodePNG_EncodeSettings_init()
void LodePNG_EncodeSettings_init (LodePNG_EncodeSettings * settings)
LodePNG_InfoColor_addPalette()
unsigned LodePNG_InfoColor_addPalette (LodePNG_InfoColor * info, unsigned char r, unsigned char g, unsigned char b, unsigned char a)
Referenced by Image::save().
LodePNG_InfoColor_cleanup()
void LodePNG_InfoColor_cleanup (LodePNG_InfoColor * info)
LodePNG_InfoColor_clearPalette()
void LodePNG_InfoColor_clearPalette (LodePNG_InfoColor * info)
LodePNG_InfoColor_copy()
unsigned LodePNG_InfoColor_copy (LodePNG_InfoColor * dest, const LodePNG_InfoColor * source)
LodePNG_InfoColor_getBpp()
unsigned LodePNG_InfoColor_getBpp (const LodePNG_InfoColor * info)
LodePNG_InfoColor_getChannels()
unsigned LodePNG_InfoColor_getChannels (const LodePNG_InfoColor * info)
LodePNG_InfoColor_init()
void LodePNG_InfoColor_init (LodePNG_InfoColor * info)
LodePNG_InfoColor_isAlphaType()
unsigned LodePNG_InfoColor_isAlphaType (const LodePNG_InfoColor * info)
LodePNG_InfoColor_isGreyscaleType()
unsigned LodePNG_InfoColor_isGreyscaleType (const LodePNG_InfoColor * info)
LodePNG_InfoPng_cleanup()
void LodePNG_InfoPng_cleanup (LodePNG_InfoPng * info)
LodePNG_InfoPng_copy()
unsigned LodePNG_InfoPng_copy (LodePNG_InfoPng * dest, const LodePNG_InfoPng * source)
LodePNG_InfoPng_init()
void LodePNG_InfoPng_init (LodePNG_InfoPng * info)
LodePNG_InfoRaw_cleanup()
void LodePNG_InfoRaw_cleanup (LodePNG_InfoRaw * info)
LodePNG_InfoRaw_copy()
unsigned LodePNG_InfoRaw_copy (LodePNG_InfoRaw * dest, const LodePNG_InfoRaw * source)
LodePNG_InfoRaw_init()
void LodePNG_InfoRaw_init (LodePNG_InfoRaw * info)
LodePNG_loadFile()
unsigned LodePNG_loadFile (unsigned char ** out, size_t * outsize, const char * filename)
LodePNG_saveFile()
unsigned LodePNG_saveFile (const unsigned char * buffer, size_t buffersize, const char * filename)
Referenced by Image::save(), and ColoredImage::save().
LodeZlib_compress()
unsigned LodeZlib_compress (unsigned char ** out, size_t * outsize, const unsigned char * in, size_t insize, const LodeZlib_DeflateSettings * settings)
LodeZlib_DeflateSettings_init()
void LodeZlib_DeflateSettings_init (LodeZlib_DeflateSettings * settings)
Variable Documentation
LodeZlib_defaultDeflateSettings
const LodeZlib_DeflateSettings LodeZlib_defaultDeflateSettings