Doxygen: FTextStream Class Reference
FTextStream Class Reference
Simplified and optimized version of QTextStream.
#include <ftextstream.h>
Public Member Functions
FTextStream ()
FTextStream (QIODevice *)
FTextStream (QGString *)
FTextStream (FILE *)
virtual ~FTextStream ()
QIODevice * device () const
void setDevice (QIODevice *)
void unsetDevice ()
FTextStream & operator<< (char)
FTextStream & operator<< (const char *)
FTextStream & operator<< (const QString &)
FTextStream & operator<< (const QCString &)
FTextStream & operator<< (signed short)
FTextStream & operator<< (unsigned short)
FTextStream & operator<< (signed int)
FTextStream & operator<< (unsigned int)
FTextStream & operator<< (signed long)
FTextStream & operator<< (unsigned long)
FTextStream & operator<< (float)
FTextStream & operator<< (double)
Private Member Functions
FTextStream & output_int (ulong n, bool neg)
FTextStream (const FTextStream &)
FTextStream & operator= (const FTextStream &)
Private Attributes
QIODevice * m_dev
bool m_owndev
Detailed Description
Simplified and optimized version of QTextStream.
Definition at line 11 of file ftextstream.h.
Constructor & Destructor Documentation
FTextStream() [1/5]
FTextStream::FTextStream ()
Definition at line 145 of file ftextstream.cpp.
References m_dev, and m_owndev.
FTextStream() [2/5]
FTextStream::FTextStream (QIODevice * dev)
Definition at line 151 of file ftextstream.cpp.
References m_dev, and m_owndev.
FTextStream() [3/5]
FTextStream::FTextStream (QGString * s)
Definition at line 157 of file ftextstream.cpp.
References m_dev, and m_owndev.
FTextStream() [4/5]
FTextStream::FTextStream (FILE * fh)
Definition at line 164 of file ftextstream.cpp.
References m_dev, and m_owndev.
~FTextStream()
FTextStream::~FTextStream () virtual
Definition at line 171 of file ftextstream.cpp.
References m_dev, and m_owndev.
FTextStream() [5/5]
FTextStream::FTextStream (const FTextStream &) private
Member Function Documentation
device()
QIODevice * FTextStream::device () const
Definition at line 177 of file ftextstream.cpp.
References m_dev.
Referenced by LatexCodeGenerator::setTextStream(), and HtmlCodeGenerator::setTextStream().
operator<<() [1/12]
FTextStream & FTextStream::operator<< (char c) inline
Definition at line 49 of file ftextstream.h.
References m_dev.
Referenced by operator<<(), and output_int().
operator<<() [2/12]
FTextStream & FTextStream::operator<< (const char * s) inline
Definition at line 55 of file ftextstream.h.
References m_dev.
operator<<() [3/12]
FTextStream & FTextStream::operator<< (const QString & s) inline
Definition at line 62 of file ftextstream.h.
References operator<<().
operator<<() [4/12]
FTextStream & FTextStream::operator<< (const QCString & s) inline
Definition at line 67 of file ftextstream.h.
References operator<<().
operator<<() [5/12]
FTextStream & FTextStream::operator<< (signed short i)
Definition at line 215 of file ftextstream.cpp.
References output_int().
operator<<() [6/12]
FTextStream & FTextStream::operator<< (unsigned short i)
Definition at line 220 of file ftextstream.cpp.
References output_int().
operator<<() [7/12]
FTextStream & FTextStream::operator<< (signed int i)
Definition at line 225 of file ftextstream.cpp.
References output_int().
operator<<() [8/12]
FTextStream & FTextStream::operator<< (unsigned int i)
Definition at line 230 of file ftextstream.cpp.
References output_int().
operator<<() [9/12]
FTextStream & FTextStream::operator<< (signed long i)
Definition at line 235 of file ftextstream.cpp.
References output_int().
operator<<() [10/12]
FTextStream & FTextStream::operator<< (unsigned long i)
Definition at line 240 of file ftextstream.cpp.
References output_int().
operator<<() [11/12]
FTextStream & FTextStream::operator<< (float f)
Definition at line 245 of file ftextstream.cpp.
operator<<() [12/12]
FTextStream & FTextStream::operator<< (double d)
Definition at line 250 of file ftextstream.cpp.
operator=()
FTextStream& FTextStream::operator= (const FTextStream &) private
output_int()
FTextStream & FTextStream::output_int (ulong n, bool neg) private
Definition at line 197 of file ftextstream.cpp.
References operator<<().
Referenced by operator<<().
setDevice()
void FTextStream::setDevice (QIODevice * dev)
Definition at line 182 of file ftextstream.cpp.
References m_dev, and m_owndev.
Referenced by generateJSNavTree(), DocSets::initialize(), EclipseHelp::initialize(), HtmlHelp::initialize(), LatexCodeGenerator::setTextStream(), HtmlCodeGenerator::setTextStream(), ManGenerator::startDoxyAnchor(), OutputGenerator::startPlainFile(), and unsetDevice().
unsetDevice()
void FTextStream::unsetDevice ()
Definition at line 192 of file ftextstream.cpp.
References setDevice().
Referenced by OutputGenerator::endPlainFile(), EclipseHelp::finalize(), and HtmlHelp::finalize().
Member Data Documentation
m_dev
QIODevice* FTextStream::m_dev private
Definition at line 38 of file ftextstream.h.
Referenced by device(), FTextStream(), operator<<(), setDevice(), and ~FTextStream().
m_owndev
bool FTextStream::m_owndev private
Definition at line 39 of file ftextstream.h.
Referenced by FTextStream(), setDevice(), and ~FTextStream().
The documentation for this class was generated from the following files:
src/ftextstream.h
src/ftextstream.cpp