Doxygen: src/htmlgen.cpp File Reference
htmlgen.cpp File Reference
#include <stdlib.h>
#include <qdir.h>
#include <qregexp.h>
#include "message.h"
#include "htmlgen.h"
#include "config.h"
#include "util.h"
#include "doxygen.h"
#include "logos.h"
#include "diagram.h"
#include "version.h"
#include "dot.h"
#include "language.h"
#include "htmlhelp.h"
#include "docparser.h"
#include "htmldocvisitor.h"
#include "searchindex.h"
#include "pagedef.h"
#include "debug.h"
#include "dirdef.h"
#include "vhdldocgen.h"
#include "layout.h"
#include "image.h"
#include "ftvhelp.h"
#include "bufstr.h"
#include "resourcemgr.h"
Macros
#define DBG_HTML(x)
Functions
static void writeClientSearchBox (FTextStream &t, const char *relPath)
static void writeServerSearchBox (FTextStream &t, const char *relPath, bool highlightSearch)
QCString clearBlock (const char *s, const char *begin, const char *end)
Clear a text block s from begin to end markers.
QCString selectBlock (const QCString &s, const QCString &name, bool enable)
static QCString getSearchBox (bool serverSide, QCString relPath, bool highlightSearch)
static QCString removeEmptyLines (const QCString &s)
static QCString substituteHtmlKeywords (const QCString &s, const QCString &title, const QCString &relPath, const QCString &navPath=QCString())
static void startSectionHeader (FTextStream &t, const QCString &relPath, int sectionCount)
static void endSectionHeader (FTextStream &t)
static void startSectionSummary (FTextStream &t, int sectionCount)
static void endSectionSummary (FTextStream &t)
static void startSectionContent (FTextStream &t, int sectionCount)
static void endSectionContent (FTextStream &t)
static void startQuickIndexList (FTextStream &t, bool compact, bool topLevel=TRUE)
static void endQuickIndexList (FTextStream &t, bool compact)
static void startQuickIndexItem (FTextStream &t, const char *l, bool hl, bool, const QCString &relPath)
static void endQuickIndexItem (FTextStream &t, const char *l)
static bool quickLinkVisible (LayoutNavEntry::Kind kind)
static void renderQuickLinksAsTree (FTextStream &t, const QCString &relPath, LayoutNavEntry *root)
static void renderQuickLinksAsTabs (FTextStream &t, const QCString &relPath, LayoutNavEntry *hlEntry, LayoutNavEntry::Kind kind, bool highlightParent, bool highlightSearch)
static void writeDefaultQuickLinks (FTextStream &t, bool compact, HighlightedItem hli, const char *file, const QCString &relPath)
Variables
static QCString g_header
static QCString g_footer
static QCString g_mathjax_code
Macro Definition Documentation
DBG_HTML
#define DBG_HTML (x)
Definition at line 48 of file htmlgen.cpp.
Referenced by HtmlGenerator::endIndent(), HtmlGenerator::endInlineMemberDoc(), HtmlGenerator::endInlineMemberName(), HtmlGenerator::endInlineMemberType(), HtmlGenerator::endLabels(), HtmlGenerator::endMemberDescription(), HtmlGenerator::endMemberDoc(), HtmlGenerator::endMemberDocList(), HtmlGenerator::endMemberDocName(), HtmlGenerator::endMemberDocPrefixItem(), HtmlGenerator::endMemberDocSimple(), HtmlGenerator::endMemberHeader(), HtmlGenerator::endMemberList(), HtmlGenerator::endMemberSections(), HtmlGenerator::endMemberSubtitle(), HtmlGenerator::endParameterList(), HtmlGenerator::endParameterName(), HtmlGenerator::endParameterType(), HtmlGenerator::exceptionEntry(), HtmlGenerator::insertMemberAlign(), HtmlGenerator::startIndent(), HtmlGenerator::startInlineMemberDoc(), HtmlGenerator::startInlineMemberName(), HtmlGenerator::startInlineMemberType(), HtmlGenerator::startLabels(), HtmlGenerator::startMemberDescription(), HtmlGenerator::startMemberDoc(), HtmlGenerator::startMemberDocList(), HtmlGenerator::startMemberDocName(), HtmlGenerator::startMemberDocPrefixItem(), HtmlGenerator::startMemberDocSimple(), HtmlGenerator::startMemberHeader(), HtmlGenerator::startMemberItem(), HtmlGenerator::startMemberList(), HtmlGenerator::startMemberSections(), HtmlGenerator::startMemberSubtitle(), HtmlGenerator::startParameterList(), HtmlGenerator::startParameterName(), HtmlGenerator::startParameterType(), HtmlGenerator::writeInheritedSectionTitle(), and HtmlGenerator::writeLabel().
Function Documentation
clearBlock()
QCString clearBlock (const char * s, const char * begin, const char * end)
Clear a text block s from begin to end markers.
Definition at line 110 of file htmlgen.cpp.
Referenced by selectBlock().
endQuickIndexItem()
static void endQuickIndexItem (FTextStream & t, const char * l) static
Definition at line 2024 of file htmlgen.cpp.
Referenced by renderQuickLinksAsTabs().
endQuickIndexList()
static void endQuickIndexList (FTextStream & t, bool compact) static
Definition at line 1997 of file htmlgen.cpp.
Referenced by renderQuickLinksAsTabs(), and renderQuickLinksAsTree().
endSectionContent()
static void endSectionContent (FTextStream & t) static
Definition at line 1366 of file htmlgen.cpp.
References endl().
Referenced by HtmlGenerator::endCallGraph(), HtmlGenerator::endClassDiagram(), HtmlGenerator::endDirDepGraph(), HtmlGenerator::endDotGraph(), HtmlGenerator::endGroupCollaboration(), and HtmlGenerator::endInclDepGraph().
endSectionHeader()
static void endSectionHeader (FTextStream & t) static
Definition at line 1322 of file htmlgen.cpp.
References endl().
Referenced by HtmlGenerator::endCallGraph(), HtmlGenerator::endClassDiagram(), HtmlGenerator::endDirDepGraph(), HtmlGenerator::endDotGraph(), HtmlGenerator::endGroupCollaboration(), and HtmlGenerator::endInclDepGraph().
endSectionSummary()
static void endSectionSummary (FTextStream & t) static
Definition at line 1340 of file htmlgen.cpp.
References Config_getBool, and endl().
Referenced by HtmlGenerator::endCallGraph(), HtmlGenerator::endClassDiagram(), HtmlGenerator::endDirDepGraph(), HtmlGenerator::endDotGraph(), HtmlGenerator::endGroupCollaboration(), and HtmlGenerator::endInclDepGraph().
getSearchBox()
static QCString getSearchBox (bool serverSide, QCString relPath, bool highlightSearch) static
Definition at line 175 of file htmlgen.cpp.
References writeClientSearchBox(), and writeServerSearchBox().
Referenced by substituteHtmlKeywords().
quickLinkVisible()
static bool quickLinkVisible (LayoutNavEntry::Kind kind) static
Definition at line 2031 of file htmlgen.cpp.
References annotatedClasses, LayoutNavEntry::Classes, LayoutNavEntry::ClassHierarchy, LayoutNavEntry::ClassIndex, LayoutNavEntry::ClassList, LayoutNavEntry::ClassMembers, CMHL_All, Config_getBool, SDict< T >::count(), documentedClassMembers, documentedFileMembers, documentedGroups, documentedHtmlFiles, documentedNamespaceMembers, documentedNamespaces, LayoutNavEntry::Examples, Doxygen::exampleSDict, LayoutNavEntry::FileGlobals, LayoutNavEntry::FileList, LayoutNavEntry::Files, FMHL_All, hierarchyClasses, indexedPages, LayoutNavEntry::MainPage, LayoutNavEntry::Modules, LayoutNavEntry::NamespaceList, LayoutNavEntry::NamespaceMembers, LayoutNavEntry::Namespaces, NMHL_All, LayoutNavEntry::Pages, LayoutNavEntry::User, and LayoutNavEntry::UserGroup.
Referenced by renderQuickLinksAsTabs(), and renderQuickLinksAsTree().
removeEmptyLines()
static QCString removeEmptyLines (const QCString & s) static
Definition at line 190 of file htmlgen.cpp.
References BufStr::data().
Referenced by substituteHtmlKeywords().
renderQuickLinksAsTabs()
static void renderQuickLinksAsTabs (FTextStream & t, const QCString & relPath, LayoutNavEntry * hlEntry, LayoutNavEntry::Kind kind, bool highlightParent, bool highlightSearch) static
Definition at line 2090 of file htmlgen.cpp.
References LayoutNavEntry::children(), Config_getBool, endQuickIndexItem(), endQuickIndexList(), fixSpaces(), LayoutDocManager::instance(), LayoutNavEntry::parent(), quickLinkVisible(), LayoutDocManager::rootNavEntry(), startQuickIndexItem(), startQuickIndexList(), writeClientSearchBox(), and writeServerSearchBox().
Referenced by writeDefaultQuickLinks().
renderQuickLinksAsTree()
static void renderQuickLinksAsTree (FTextStream & t, const QCString & relPath, LayoutNavEntry * root) static
Definition at line 2059 of file htmlgen.cpp.
References LayoutNavEntry::children(), endQuickIndexList(), fixSpaces(), quickLinkVisible(), and startQuickIndexList().
Referenced by writeDefaultQuickLinks().
selectBlock()
QCString selectBlock (const QCString & s, const QCString & name, bool enable)
Definition at line 150 of file htmlgen.cpp.
References clearBlock(), and substitute().
Referenced by substituteHtmlKeywords().
startQuickIndexItem()
static void startQuickIndexItem (FTextStream & t, const char * l, bool hl, bool , const QCString & relPath) static
Definition at line 2010 of file htmlgen.cpp.
References correctURL().
Referenced by renderQuickLinksAsTabs().
startQuickIndexList()
static void startQuickIndexList (FTextStream & t, bool compact, bool topLevel = TRUE) static
Definition at line 1977 of file htmlgen.cpp.
Referenced by renderQuickLinksAsTabs(), and renderQuickLinksAsTree().
startSectionContent()
static void startSectionContent (FTextStream & t, int sectionCount) static
Definition at line 1350 of file htmlgen.cpp.
References Config_getBool, and endl().
Referenced by HtmlGenerator::endCallGraph(), HtmlGenerator::endClassDiagram(), HtmlGenerator::endDirDepGraph(), HtmlGenerator::endDotGraph(), HtmlGenerator::endGroupCollaboration(), and HtmlGenerator::endInclDepGraph().
startSectionHeader()
static void startSectionHeader (FTextStream & t, const QCString & relPath, int sectionCount) static
Definition at line 1302 of file htmlgen.cpp.
References Config_getBool, and endl().
Referenced by HtmlGenerator::startCallGraph(), HtmlGenerator::startClassDiagram(), HtmlGenerator::startDirDepGraph(), HtmlGenerator::startDotGraph(), HtmlGenerator::startGroupCollaboration(), and HtmlGenerator::startInclDepGraph().
startSectionSummary()
static void startSectionSummary (FTextStream & t, int sectionCount) static
Definition at line 1328 of file htmlgen.cpp.
References Config_getBool, and endl().
Referenced by HtmlGenerator::endCallGraph(), HtmlGenerator::endClassDiagram(), HtmlGenerator::endDirDepGraph(), HtmlGenerator::endDotGraph(), HtmlGenerator::endGroupCollaboration(), and HtmlGenerator::endInclDepGraph().
substituteHtmlKeywords()
static QCString substituteHtmlKeywords (const QCString & s, const QCString & title, const QCString & relPath, const QCString & navPath = QCString()) static
Definition at line 220 of file htmlgen.cpp.
References Config_getBool, Config_getEnum, Config_getList, Config_getString, convertToHtml(), dateToString(), g_mathjax_code, getSearchBox(), removeEmptyLines(), selectBlock(), stripPath(), substitute(), substituteKeywords(), theTranslator, Translator::trGeneratedAt(), and Translator::trGeneratedBy().
Referenced by HtmlGenerator::startFile(), HtmlGenerator::writeExternalSearchPage(), HtmlGenerator::writePageFooter(), and HtmlGenerator::writeSearchPage().
writeClientSearchBox()
static void writeClientSearchBox (FTextStream & t, const char * relPath) static
Definition at line 57 of file htmlgen.cpp.
References theTranslator, and Translator::trSearch().
Referenced by getSearchBox(), and renderQuickLinksAsTabs().
writeDefaultQuickLinks()
static void writeDefaultQuickLinks (FTextStream & t, bool compact, HighlightedItem hli, const char * file, const QCString & relPath) static
Definition at line 2162 of file htmlgen.cpp.
References LayoutNavEntry::children(), LayoutNavEntry::Classes, LayoutNavEntry::ClassHierarchy, LayoutNavEntry::ClassIndex, LayoutNavEntry::ClassList, LayoutNavEntry::ClassMembers, Config_getBool, endl(), LayoutNavEntry::Examples, LayoutNavEntry::FileGlobals, LayoutNavEntry::FileList, LayoutNavEntry::Files, LayoutNavEntry::find(), HLI_Annotated, HLI_Classes, HLI_ClassVisible, HLI_Examples, HLI_Files, HLI_FileVisible, HLI_Functions, HLI_Globals, HLI_Hierarchy, HLI_Main, HLI_Modules, HLI_NamespaceMembers, HLI_Namespaces, HLI_NamespaceVisible, HLI_None, HLI_Pages, HLI_Search, HLI_UserGroup, Doxygen::htmlFileExtension, LayoutDocManager::instance(), LayoutNavEntry::MainPage, LayoutNavEntry::Modules, LayoutNavEntry::NamespaceList, LayoutNavEntry::NamespaceMembers, LayoutNavEntry::Namespaces, LayoutNavEntry::Pages, renderQuickLinksAsTabs(), renderQuickLinksAsTree(), LayoutDocManager::rootNavEntry(), theTranslator, Translator::trSearch(), and LayoutNavEntry::UserGroup.
Referenced by HtmlGenerator::writeExternalSearchPage(), HtmlGenerator::writeQuickLinks(), and HtmlGenerator::writeSearchPage().
writeServerSearchBox()
static void writeServerSearchBox (FTextStream & t, const char * relPath, bool highlightSearch) static
Definition at line 79 of file htmlgen.cpp.
References Config_getBool, Doxygen::htmlFileExtension, theTranslator, and Translator::trSearch().
Referenced by getSearchBox(), and renderQuickLinksAsTabs().
Variable Documentation
g_footer
QCString g_footer static
Definition at line 51 of file htmlgen.cpp.
Referenced by HtmlGenerator::init(), and HtmlGenerator::writePageFooter().
g_header
QCString g_header static
Definition at line 50 of file htmlgen.cpp.
Referenced by HtmlGenerator::init(), HtmlGenerator::startFile(), HtmlGenerator::writeExternalSearchPage(), and HtmlGenerator::writeSearchPage().
g_mathjax_code
QCString g_mathjax_code static
Definition at line 52 of file htmlgen.cpp.
Referenced by HtmlGenerator::init(), and substituteHtmlKeywords().