Doxygen: SymbolListContext Class Reference
SymbolListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static SymbolListContext * alloc (const SearchDefinitionList *sdl)
Private Member Functions
SymbolListContext (const SearchDefinitionList *sdl)
~SymbolListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1202 of file context.h.
Constructor & Destructor Documentation
SymbolListContext()
SymbolListContext::SymbolListContext (const SearchDefinitionList * sdl) private
Definition at line 9598 of file context.cpp.
References p, and Private.
Referenced by alloc().
~SymbolListContext()
SymbolListContext::~SymbolListContext () private
Definition at line 9604 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int SymbolListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 1212 of file context.h.
References RefCountedContext::addRef().
alloc()
static SymbolListContext* SymbolListContext::alloc (const SearchDefinitionList * sdl) inline static
Definition at line 1205 of file context.h.
References SymbolListContext().
Referenced by SymbolGroupContext::Private::symbolList().
at()
TemplateVariant SymbolListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 9615 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int SymbolListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 9610 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * SymbolListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 9620 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int SymbolListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 1213 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* SymbolListContext::p private
Definition at line 1218 of file context.h.
Referenced by at(), count(), createIterator(), SymbolListContext(), and ~SymbolListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp