Doxygen: XmlDocVisitor Class Reference
XmlDocVisitor Class Reference
Concrete visitor implementation for XML output.
#include <xmldocvisitor.h>
Public Member Functions
XmlDocVisitor (FTextStream &t, CodeOutputInterface &ci)
void visit (DocWord *)
void visit (DocLinkedWord *)
void visit (DocWhiteSpace *)
void visit (DocSymbol *)
void visit (DocURL *)
void visit (DocLineBreak *)
void visit (DocHorRuler *)
void visit (DocStyleChange *)
void visit (DocVerbatim *)
void visit (DocAnchor *)
void visit (DocInclude *)
void visit (DocIncOperator *)
void visit (DocFormula *)
void visit (DocIndexEntry *)
void visit (DocSimpleSectSep *)
void visit (DocCite *)
void visitPre (DocAutoList *)
void visitPost (DocAutoList *)
void visitPre (DocAutoListItem *)
void visitPost (DocAutoListItem *)
void visitPre (DocPara *)
void visitPost (DocPara *)
void visitPre (DocRoot *)
void visitPost (DocRoot *)
void visitPre (DocSimpleSect *)
void visitPost (DocSimpleSect *)
void visitPre (DocTitle *)
void visitPost (DocTitle *)
void visitPre (DocSimpleList *)
void visitPost (DocSimpleList *)
void visitPre (DocSimpleListItem *)
void visitPost (DocSimpleListItem *)
void visitPre (DocSection *)
void visitPost (DocSection *)
void visitPre (DocHtmlList *)
void visitPost (DocHtmlList *)
void visitPre (DocHtmlListItem *)
void visitPost (DocHtmlListItem *)
void visitPre (DocHtmlDescList *)
void visitPost (DocHtmlDescList *)
void visitPre (DocHtmlDescTitle *)
void visitPost (DocHtmlDescTitle *)
void visitPre (DocHtmlDescData *)
void visitPost (DocHtmlDescData *)
void visitPre (DocHtmlTable *)
void visitPost (DocHtmlTable *)
void visitPre (DocHtmlRow *)
void visitPost (DocHtmlRow *)
void visitPre (DocHtmlCell *)
void visitPost (DocHtmlCell *)
void visitPre (DocHtmlCaption *)
void visitPost (DocHtmlCaption *)
void visitPre (DocInternal *)
void visitPost (DocInternal *)
void visitPre (DocHRef *)
void visitPost (DocHRef *)
void visitPre (DocHtmlHeader *)
void visitPost (DocHtmlHeader *)
void visitPre (DocImage *)
void visitPost (DocImage *)
void visitPre (DocDotFile *)
void visitPost (DocDotFile *)
void visitPre (DocMscFile *)
void visitPost (DocMscFile *)
void visitPre (DocDiaFile *)
void visitPost (DocDiaFile *)
void visitPre (DocLink *)
void visitPost (DocLink *)
void visitPre (DocRef *)
void visitPost (DocRef *)
void visitPre (DocSecRefItem *)
void visitPost (DocSecRefItem *)
void visitPre (DocSecRefList *)
void visitPost (DocSecRefList *)
void visitPre (DocParamSect *)
void visitPost (DocParamSect *)
void visitPre (DocParamList *)
void visitPost (DocParamList *)
void visitPre (DocXRefItem *)
void visitPost (DocXRefItem *)
void visitPre (DocInternalRef *)
void visitPost (DocInternalRef *)
void visitPre (DocCopy *)
void visitPost (DocCopy *)
void visitPre (DocText *)
void visitPost (DocText *)
void visitPre (DocHtmlBlockQuote *)
void visitPost (DocHtmlBlockQuote *)
void visitPre (DocVhdlFlow *)
void visitPost (DocVhdlFlow *)
void visitPre (DocParBlock *)
void visitPost (DocParBlock *)
Public Member Functions inherited from DocVisitor
DocVisitor (int id)
virtual ~DocVisitor ()
int id () const
Private Member Functions
void filter (const char *str)
void startLink (const QCString &ref, const QCString &file, const QCString &anchor)
void endLink ()
void pushEnabled ()
void popEnabled ()
Private Attributes
FTextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre
bool m_hide
QStack< bool > m_enabled
QCString m_langExt
Detailed Description
Concrete visitor implementation for XML output.
Definition at line 31 of file xmldocvisitor.h.
Constructor & Destructor Documentation
XmlDocVisitor()
XmlDocVisitor::XmlDocVisitor (FTextStream & t, CodeOutputInterface & ci)
Definition at line 86 of file xmldocvisitor.cpp.
Member Function Documentation
endLink()
void XmlDocVisitor::endLink () private
Definition at line 1090 of file xmldocvisitor.cpp.
References m_t.
Referenced by visit(), and visitPost().
filter()
void XmlDocVisitor::filter (const char * str) private
Definition at line 1073 of file xmldocvisitor.cpp.
References convertToXML(), and m_t.
Referenced by visit(), and visitPre().
popEnabled()
void XmlDocVisitor::popEnabled () private
Definition at line 1100 of file xmldocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit().
pushEnabled()
void XmlDocVisitor::pushEnabled () private
Definition at line 1095 of file xmldocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit().
startLink()
void XmlDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & anchor) private
Definition at line 1078 of file xmldocvisitor.cpp.
References m_t.
Referenced by visit(), and visitPre().
visit() [1/16]
void XmlDocVisitor::visit (DocWord * w) virtual
Implements DocVisitor.
Definition at line 95 of file xmldocvisitor.cpp.
References filter(), m_hide, and DocWord::word().
Referenced by visitPre().
visit() [2/16]
void XmlDocVisitor::visit (DocLinkedWord * w) virtual
Implements DocVisitor.
Definition at line 101 of file xmldocvisitor.cpp.
References DocLinkedWord::anchor(), endLink(), DocLinkedWord::file(), filter(), m_hide, DocLinkedWord::ref(), startLink(), and DocLinkedWord::word().
visit() [3/16]
void XmlDocVisitor::visit (DocWhiteSpace * w) virtual
Implements DocVisitor.
Definition at line 109 of file xmldocvisitor.cpp.
References DocWhiteSpace::chars(), m_hide, m_insidePre, and m_t.
visit() [4/16]
void XmlDocVisitor::visit (DocSymbol * s) virtual
Implements DocVisitor.
Definition at line 122 of file xmldocvisitor.cpp.
References err(), HtmlEntityMapper::instance(), m_hide, m_t, DocSymbol::symbol(), and HtmlEntityMapper::xml().
visit() [5/16]
void XmlDocVisitor::visit (DocURL * u) virtual
Implements DocVisitor.
Definition at line 136 of file xmldocvisitor.cpp.
References filter(), DocURL::isEmail(), m_hide, m_t, and DocURL::url().
visit() [6/16]
void XmlDocVisitor::visit (DocLineBreak *) virtual
Implements DocVisitor.
Definition at line 147 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visit() [7/16]
void XmlDocVisitor::visit (DocHorRuler *) virtual
Implements DocVisitor.
Definition at line 153 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visit() [8/16]
void XmlDocVisitor::visit (DocStyleChange * s) virtual
Implements DocVisitor.
Definition at line 159 of file xmldocvisitor.cpp.
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Code, DocStyleChange::Div, DocStyleChange::enable(), DocStyleChange::Italic, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::style(), DocStyleChange::Subscript, and DocStyleChange::Superscript.
visit() [9/16]
void XmlDocVisitor::visit (DocVerbatim * s) virtual
Implements DocVisitor.
Definition at line 202 of file xmldocvisitor.cpp.
References DocVerbatim::children(), DocVerbatim::Code, DocVerbatim::context(), DocVerbatim::DocbookOnly, DocVerbatim::Dot, DocVerbatim::exampleFile(), filter(), getLanguageFromFileName(), ParserManager::getParser(), DocVerbatim::hasCaption(), DocVerbatim::height(), DocImage::Html, DocVerbatim::HtmlOnly, DocVerbatim::isExample(), DocVerbatim::language(), DocVerbatim::LatexOnly, m_ci, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, ParserInterface::parseCode(), Doxygen::parserManager, DocVerbatim::PlantUML, DocVerbatim::RtfOnly, DocVerbatim::text(), DocVerbatim::type(), DocVerbatim::Verbatim, visitPostEnd(), visitPreStart(), DocVerbatim::width(), and DocVerbatim::XmlOnly.
visit() [10/16]
void XmlDocVisitor::visit (DocAnchor * anc) virtual
Implements DocVisitor.
Definition at line 253 of file xmldocvisitor.cpp.
References DocAnchor::anchor(), DocAnchor::file(), m_hide, and m_t.
visit() [11/16]
void XmlDocVisitor::visit (DocInclude * inc) virtual
Implements DocVisitor.
Definition at line 259 of file xmldocvisitor.cpp.
References DocInclude::blockId(), DocInclude::context(), DocInclude::DontInclude, err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), DocInclude::file(), filter(), getLanguageFromFileName(), ParserManager::getParser(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_hide, m_t, parseCode(), Doxygen::parserManager, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::text(), DocInclude::type(), and DocInclude::VerbInclude.
visit() [12/16]
void XmlDocVisitor::visit (DocIncOperator * op) virtual
Implements DocVisitor.
Definition at line 362 of file xmldocvisitor.cpp.
References DocIncOperator::context(), endl(), DocIncOperator::exampleFile(), getLanguageFromFileName(), ParserManager::getParser(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), m_ci, m_hide, m_langExt, m_t, ParserInterface::parseCode(), Doxygen::parserManager, popEnabled(), pushEnabled(), DocIncOperator::Skip, DocIncOperator::text(), and DocIncOperator::type().
visit() [13/16]
void XmlDocVisitor::visit (DocFormula * f) virtual
Implements DocVisitor.
Definition at line 400 of file xmldocvisitor.cpp.
References filter(), DocFormula::id(), m_hide, m_t, and DocFormula::text().
visit() [14/16]
void XmlDocVisitor::visit (DocIndexEntry * ie) virtual
Implements DocVisitor.
Definition at line 408 of file xmldocvisitor.cpp.
References DocIndexEntry::entry(), filter(), m_hide, and m_t.
visit() [15/16]
void XmlDocVisitor::visit (DocSimpleSectSep * sep) virtual
Implements DocVisitor.
Definition at line 419 of file xmldocvisitor.cpp.
References DocNode::kind(), DocNode::Kind_SimpleSect, DocNode::parent(), visitPost(), and visitPre().
visit() [16/16]
void XmlDocVisitor::visit (DocCite * cite) virtual
Implements DocVisitor.
Definition at line 428 of file xmldocvisitor.cpp.
References DocCite::anchor(), endLink(), DocCite::file(), filter(), m_hide, DocCite::ref(), startLink(), and DocCite::text().
visitPost() [1/38]
void XmlDocVisitor::visitPost (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 453 of file xmldocvisitor.cpp.
References DocAutoList::isEnumList(), m_hide, and m_t.
Referenced by visit().
visitPost() [2/38]
void XmlDocVisitor::visitPost (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 472 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [3/38]
void XmlDocVisitor::visitPost (DocPara *) virtual
Implements DocVisitor.
Definition at line 484 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [4/38]
void XmlDocVisitor::visitPost (DocRoot *) virtual
Implements DocVisitor.
Definition at line 495 of file xmldocvisitor.cpp.
visitPost() [5/38]
void XmlDocVisitor::visitPost (DocSimpleSect *) virtual
Implements DocVisitor.
Definition at line 545 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [6/38]
void XmlDocVisitor::visitPost (DocTitle *) virtual
Implements DocVisitor.
Definition at line 557 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [7/38]
void XmlDocVisitor::visitPost (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 569 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [8/38]
void XmlDocVisitor::visitPost (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 581 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [9/38]
void XmlDocVisitor::visitPost (DocSection * s) virtual
Implements DocVisitor.
Definition at line 598 of file xmldocvisitor.cpp.
References DocSection::level(), and m_t.
visitPost() [10/38]
void XmlDocVisitor::visitPost (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 612 of file xmldocvisitor.cpp.
References m_hide, m_t, DocHtmlList::Ordered, and DocHtmlList::type().
visitPost() [11/38]
void XmlDocVisitor::visitPost (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 627 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [12/38]
void XmlDocVisitor::visitPost (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 639 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [13/38]
void XmlDocVisitor::visitPost (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 651 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [14/38]
void XmlDocVisitor::visitPost (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 663 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [15/38]
void XmlDocVisitor::visitPost (DocHtmlTable *) virtual
Implements DocVisitor.
Definition at line 676 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [16/38]
void XmlDocVisitor::visitPost (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 688 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [17/38]
void XmlDocVisitor::visitPost (DocHtmlCell *) virtual
Implements DocVisitor.
Definition at line 700 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [18/38]
void XmlDocVisitor::visitPost (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 712 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [19/38]
void XmlDocVisitor::visitPost (DocInternal *) virtual
Implements DocVisitor.
Definition at line 724 of file xmldocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [20/38]
void XmlDocVisitor::visitPost (DocHRef *) virtual
Implements DocVisitor.
Definition at line 738 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [21/38]
void XmlDocVisitor::visitPost (DocHtmlHeader *) virtual
Implements DocVisitor.
Definition at line 750 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [22/38]
void XmlDocVisitor::visitPost (DocImage *) virtual
Implements DocVisitor.
Definition at line 784 of file xmldocvisitor.cpp.
References m_hide, m_t, and visitPostEnd().
visitPost() [23/38]
void XmlDocVisitor::visitPost (DocDotFile *) virtual
Implements DocVisitor.
Definition at line 796 of file xmldocvisitor.cpp.
References m_hide, m_t, and visitPostEnd().
visitPost() [24/38]
void XmlDocVisitor::visitPost (DocMscFile *) virtual
Implements DocVisitor.
Definition at line 808 of file xmldocvisitor.cpp.
References m_hide, m_t, and visitPostEnd().
visitPost() [25/38]
void XmlDocVisitor::visitPost (DocDiaFile *) virtual
Implements DocVisitor.
Definition at line 820 of file xmldocvisitor.cpp.
References m_hide, m_t, and visitPostEnd().
visitPost() [26/38]
void XmlDocVisitor::visitPost (DocLink *) virtual
Implements DocVisitor.
Definition at line 832 of file xmldocvisitor.cpp.
References endLink(), and m_hide.
visitPost() [27/38]
void XmlDocVisitor::visitPost (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 848 of file xmldocvisitor.cpp.
References endLink(), DocRef::file(), and m_hide.
visitPost() [28/38]
void XmlDocVisitor::visitPost (DocSecRefItem *) virtual
Implements DocVisitor.
Definition at line 861 of file xmldocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [29/38]
void XmlDocVisitor::visitPost (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 873 of file xmldocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [30/38]
void XmlDocVisitor::visitPost (DocParamSect *) virtual
Implements DocVisitor.
Definition at line 911 of file xmldocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [31/38]
void XmlDocVisitor::visitPost (DocParamList *) virtual
Implements DocVisitor.
Definition at line 979 of file xmldocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [32/38]
void XmlDocVisitor::visitPost (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 999 of file xmldocvisitor.cpp.
References m_hide, m_t, and DocXRefItem::title().
visitPost() [33/38]
void XmlDocVisitor::visitPost (DocInternalRef *) virtual
Implements DocVisitor.
Definition at line 1013 of file xmldocvisitor.cpp.
References endLink(), m_hide, and m_t.
visitPost() [34/38]
void XmlDocVisitor::visitPost (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1026 of file xmldocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [35/38]
void XmlDocVisitor::visitPost (DocText *) virtual
Implements DocVisitor.
Definition at line 1036 of file xmldocvisitor.cpp.
visitPost() [36/38]
void XmlDocVisitor::visitPost (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1046 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [37/38]
void XmlDocVisitor::visitPost (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1056 of file xmldocvisitor.cpp.
visitPost() [38/38]
void XmlDocVisitor::visitPost (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1066 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [1/38]
void XmlDocVisitor::visitPre (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 440 of file xmldocvisitor.cpp.
References DocAutoList::isEnumList(), m_hide, and m_t.
Referenced by visit().
visitPre() [2/38]
void XmlDocVisitor::visitPre (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 466 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [3/38]
void XmlDocVisitor::visitPre (DocPara *) virtual
Implements DocVisitor.
Definition at line 478 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [4/38]
void XmlDocVisitor::visitPre (DocRoot *) virtual
Implements DocVisitor.
Definition at line 490 of file xmldocvisitor.cpp.
visitPre() [5/38]
void XmlDocVisitor::visitPre (DocSimpleSect * s) virtual
Implements DocVisitor.
Definition at line 500 of file xmldocvisitor.cpp.
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, DocSimpleSect::Invar, m_hide, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, DocSimpleSect::See, DocSimpleSect::Since, DocSimpleSect::type(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
visitPre() [6/38]
void XmlDocVisitor::visitPre (DocTitle *) virtual
Implements DocVisitor.
Definition at line 551 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [7/38]
void XmlDocVisitor::visitPre (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 563 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [8/38]
void XmlDocVisitor::visitPre (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 575 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [9/38]
void XmlDocVisitor::visitPre (DocSection * s) virtual
Implements DocVisitor.
Definition at line 587 of file xmldocvisitor.cpp.
References DocSection::anchor(), convertCharEntitiesToUTF8(), endl(), DocSection::file(), filter(), DocSection::level(), m_hide, m_t, and DocSection::title().
visitPre() [10/38]
void XmlDocVisitor::visitPre (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 603 of file xmldocvisitor.cpp.
References m_hide, m_t, DocHtmlList::Ordered, and DocHtmlList::type().
visitPre() [11/38]
void XmlDocVisitor::visitPre (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 621 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [12/38]
void XmlDocVisitor::visitPre (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 633 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [13/38]
void XmlDocVisitor::visitPre (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 645 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [14/38]
void XmlDocVisitor::visitPre (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 657 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [15/38]
void XmlDocVisitor::visitPre (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 669 of file xmldocvisitor.cpp.
References m_hide, m_t, DocHtmlTable::numColumns(), and DocHtmlTable::numRows().
visitPre() [16/38]
void XmlDocVisitor::visitPre (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 682 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [17/38]
void XmlDocVisitor::visitPre (DocHtmlCell * c) virtual
Implements DocVisitor.
Definition at line 694 of file xmldocvisitor.cpp.
References DocHtmlCell::isHeading(), m_hide, and m_t.
visitPre() [18/38]
void XmlDocVisitor::visitPre (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 706 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [19/38]
void XmlDocVisitor::visitPre (DocInternal *) virtual
Implements DocVisitor.
Definition at line 718 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [20/38]
void XmlDocVisitor::visitPre (DocHRef * href) virtual
Implements DocVisitor.
Definition at line 730 of file xmldocvisitor.cpp.
References filter(), m_hide, m_t, and DocHRef::url().
visitPre() [21/38]
void XmlDocVisitor::visitPre (DocHtmlHeader * header) virtual
Implements DocVisitor.
Definition at line 744 of file xmldocvisitor.cpp.
References DocHtmlHeader::level(), m_hide, and m_t.
visitPre() [22/38]
void XmlDocVisitor::visitPre (DocImage * img) virtual
Implements DocVisitor.
Definition at line 756 of file xmldocvisitor.cpp.
References CompAccept< T >::children(), Config_getString, DocImage::height(), m_hide, m_t, DocImage::name(), DocImage::type(), visitPreStart(), and DocImage::width().
visitPre() [23/38]
void XmlDocVisitor::visitPre (DocDotFile * df) virtual
Implements DocVisitor.
Definition at line 790 of file xmldocvisitor.cpp.
References CompAccept< T >::children(), DocDotFile::file(), DocDotFile::height(), DocImage::Html, m_hide, m_t, visitPreStart(), and DocDotFile::width().
visitPre() [24/38]
void XmlDocVisitor::visitPre (DocMscFile * df) virtual
Implements DocVisitor.
Definition at line 802 of file xmldocvisitor.cpp.
References CompAccept< T >::children(), DocMscFile::file(), DocMscFile::height(), DocImage::Html, m_hide, m_t, visitPreStart(), and DocMscFile::width().
visitPre() [25/38]
void XmlDocVisitor::visitPre (DocDiaFile * df) virtual
Implements DocVisitor.
Definition at line 814 of file xmldocvisitor.cpp.
References CompAccept< T >::children(), DocDiaFile::file(), DocDiaFile::height(), DocImage::Html, m_hide, m_t, visitPreStart(), and DocDiaFile::width().
visitPre() [26/38]
void XmlDocVisitor::visitPre (DocLink * lnk) virtual
Implements DocVisitor.
Definition at line 826 of file xmldocvisitor.cpp.
References DocLink::anchor(), DocLink::file(), m_hide, DocLink::ref(), and startLink().
visitPre() [27/38]
void XmlDocVisitor::visitPre (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 838 of file xmldocvisitor.cpp.
References DocRef::anchor(), DocRef::file(), filter(), DocRef::hasLinkText(), DocRef::isSubPage(), m_hide, DocRef::ref(), startLink(), and DocRef::targetTitle().
visitPre() [28/38]
void XmlDocVisitor::visitPre (DocSecRefItem * ref) virtual
Implements DocVisitor.
Definition at line 855 of file xmldocvisitor.cpp.
References DocSecRefItem::anchor(), DocSecRefItem::file(), m_hide, and m_t.
visitPre() [29/38]
void XmlDocVisitor::visitPre (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 867 of file xmldocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPre() [30/38]
void XmlDocVisitor::visitPre (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 891 of file xmldocvisitor.cpp.
References DocParamSect::Exception, m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, and DocParamSect::type().
visitPre() [31/38]
void XmlDocVisitor::visitPre (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 917 of file xmldocvisitor.cpp.
References DocParamList::direction(), endl(), DocParamSect::In, DocParamSect::InOut, DocNode::Kind_LinkedWord, DocNode::Kind_Word, m_hide, m_t, DocParamSect::Out, DocParamList::parameters(), DocParamList::paramTypes(), DocParamSect::Unspecified, and visit().
visitPre() [32/38]
void XmlDocVisitor::visitPre (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 986 of file xmldocvisitor.cpp.
References DocXRefItem::anchor(), DocXRefItem::file(), filter(), m_hide, m_t, and DocXRefItem::title().
visitPre() [33/38]
void XmlDocVisitor::visitPre (DocInternalRef * ref) virtual
Implements DocVisitor.
Definition at line 1007 of file xmldocvisitor.cpp.
References DocInternalRef::anchor(), DocInternalRef::file(), m_hide, and startLink().
visitPre() [34/38]
void XmlDocVisitor::visitPre (DocCopy * c) virtual
Implements DocVisitor.
Definition at line 1020 of file xmldocvisitor.cpp.
References convertToXML(), DocCopy::link(), m_hide, and m_t.
visitPre() [35/38]
void XmlDocVisitor::visitPre (DocText *) virtual
Implements DocVisitor.
Definition at line 1032 of file xmldocvisitor.cpp.
visitPre() [36/38]
void XmlDocVisitor::visitPre (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1040 of file xmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [37/38]
void XmlDocVisitor::visitPre (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1052 of file xmldocvisitor.cpp.
visitPre() [38/38]
void XmlDocVisitor::visitPre (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1060 of file xmldocvisitor.cpp.
References m_hide, and m_t.
Member Data Documentation
m_ci
CodeOutputInterface& XmlDocVisitor::m_ci private
Definition at line 162 of file xmldocvisitor.h.
Referenced by visit().
m_enabled
QStack<bool> XmlDocVisitor::m_enabled private
Definition at line 165 of file xmldocvisitor.h.
Referenced by popEnabled(), and pushEnabled().
m_hide
bool XmlDocVisitor::m_hide private
Definition at line 164 of file xmldocvisitor.h.
Referenced by popEnabled(), pushEnabled(), visit(), visitPost(), and visitPre().
m_insidePre
bool XmlDocVisitor::m_insidePre private
Definition at line 163 of file xmldocvisitor.h.
Referenced by visit().
m_langExt
QCString XmlDocVisitor::m_langExt private
Definition at line 166 of file xmldocvisitor.h.
Referenced by visit().
m_t
FTextStream& XmlDocVisitor::m_t private
Definition at line 161 of file xmldocvisitor.h.
Referenced by endLink(), filter(), startLink(), visit(), visitPost(), and visitPre().
The documentation for this class was generated from the following files:
src/xmldocvisitor.h
src/xmldocvisitor.cpp