Doxygen: Directory Class Reference
Directory Class Reference
Class representing a directory tree of DirEntry objects.
#include <filedef.h>
Public Member Functions
Directory (Directory *parent, const QCString &name)
virtual ~Directory ()
void addChild (DirEntry *d)
QList< DirEntry > & children ()
void rename (const QCString &name)
void reParent (Directory *parent)
Public Member Functions inherited from DirEntry
DirEntry (DirEntry *parent, FileDef *fd)
DirEntry (DirEntry *parent, QCString name)
virtual ~DirEntry ()
EntryKind kind () const
FileDef * file () const
bool isLast () const
void setLast (bool b)
DirEntry * parent () const
QCString name () const
QCString path () const
Private Attributes
QList< DirEntry > m_children
Additional Inherited Members
Public Types inherited from DirEntry
enum EntryKind { Dir, File }
Protected Attributes inherited from DirEntry
DirEntry * m_parent
QCString m_name
Detailed Description
Class representing a directory tree of DirEntry objects.
Definition at line 307 of file filedef.h.
Constructor & Destructor Documentation
Directory()
Directory::Directory (Directory * parent, const QCString & name) inline
Definition at line 310 of file filedef.h.
References m_children.
~Directory()
virtual Directory::~Directory () inline virtual
Definition at line 313 of file filedef.h.
Member Function Documentation
addChild()
void Directory::addChild (DirEntry * d) inline
Definition at line 314 of file filedef.h.
References m_children, and DirEntry::setLast().
Referenced by findDirNode(), and mergeFileDef().
children()
QList<DirEntry>& Directory::children () inline
Definition at line 315 of file filedef.h.
References m_children.
Referenced by addDirsAsGroups(), findDirNode(), and mergeFileDef().
rename()
void Directory::rename (const QCString & name) inline
Definition at line 316 of file filedef.h.
References DirEntry::m_name, and DirEntry::name().
Referenced by findDirNode().
reParent()
void Directory::reParent (Directory * parent) inline
Definition at line 317 of file filedef.h.
References DirEntry::m_parent, and DirEntry::parent().
Referenced by findDirNode().
Member Data Documentation
m_children
QList<DirEntry> Directory::m_children private
Definition at line 320 of file filedef.h.
Referenced by addChild(), children(), and Directory().
The documentation for this class was generated from the following file:
src/filedef.h