Doxygen: NamespaceContext::Private Class Reference
NamespaceContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (NamespaceDef *nd)
virtual ~Private ()
TemplateVariant get (const char *n) const
TemplateVariant title () const
TemplateVariant highlight () const
TemplateVariant subHighlight () const
TemplateVariant compoundType () const
TemplateVariant hasDetails () const
TemplateVariant classes () const
TemplateVariant namespaces () const
TemplateVariant constantgroups () const
TemplateVariant getMemberList (SharedPtr< MemberListInfoContext > &list, MemberListType type, const char *title, bool detailed=FALSE) const
TemplateVariant typedefs () const
TemplateVariant enums () const
TemplateVariant functions () const
TemplateVariant variables () const
TemplateVariant memberGroups () const
TemplateVariant detailedTypedefs () const
TemplateVariant detailedEnums () const
TemplateVariant detailedFunctions () const
TemplateVariant detailedVariables () const
TemplateVariant inlineClasses () const
Public Member Functions inherited from DefinitionContext< NamespaceContext::Private >
DefinitionContext (Definition *d)
void addBaseProperties (PropertyMapper< NamespaceContext::Private > &inst)
TemplateVariant fileName () const
TemplateVariant anchor () const
TemplateVariant sourceFileName () const
TemplateVariant isLinkable () const
TemplateVariant isLinkableInProject () const
TemplateVariant name () const
TemplateVariant bareName () const
QCString relPathAsString () const
virtual TemplateVariant relPath () const
TemplateVariant details () const
TemplateVariant brief () const
TemplateVariant inbodyDocs () const
TemplateVariant dynSectionId () const
TemplateVariant language () const
TemplateVariant compoundKind () const
TemplateVariant sourceDef () const
void fillPath (Definition *def, TemplateList *list) const
TemplateVariant navigationPath () const
TemplateVariant isReference () const
TemplateVariant externalReference () const
Private Member Functions
Cachable & getCache () const
Private Attributes
NamespaceDef * m_namespaceDef
Static Private Attributes
static PropertyMapper< NamespaceContext::Private > s_inst
Detailed Description
Definition at line 2663 of file context.cpp.
Constructor & Destructor Documentation
Private()
NamespaceContext::Private::Private (NamespaceDef * nd) inline
Definition at line 2666 of file context.cpp.
References DefinitionContext< NamespaceContext::Private >::addBaseProperties(), PropertyMapper< T >::addProperty(), classes(), compoundType(), constantgroups(), Definition::cookie(), detailedEnums(), detailedFunctions(), detailedTypedefs(), detailedVariables(), enums(), functions(), hasDetails(), highlight(), Config::init(), inlineClasses(), memberGroups(), namespaces(), s_inst, Definition::setCookie(), subHighlight(), title(), typedefs(), and variables().
~Private()
virtual NamespaceContext::Private::~Private () inline virtual
Definition at line 2695 of file context.cpp.
Member Function Documentation
classes()
TemplateVariant NamespaceContext::Private::classes () const inline
Definition at line 2720 of file context.cpp.
References ClassContext::alloc(), TemplateList::alloc(), TemplateList::append(), NamespaceContext::Private::Cachable::classes, SharedPtr< T >::get(), getCache(), NamespaceDef::getClassSDict(), SDict< ClassDef >::Iterator, m_namespaceDef, and SharedPtr< T >::reset().
Referenced by Private().
compoundType()
TemplateVariant NamespaceContext::Private::compoundType () const inline
Definition at line 2712 of file context.cpp.
References NamespaceDef::compoundTypeString(), and m_namespaceDef.
Referenced by Private().
constantgroups()
TemplateVariant NamespaceContext::Private::constantgroups () const inline
Definition at line 2764 of file context.cpp.
References NamespaceContext::alloc(), TemplateList::alloc(), TemplateList::append(), NamespaceContext::Private::Cachable::constantgroups, SharedPtr< T >::get(), getCache(), NamespaceDef::getNamespaceSDict(), SDict< NamespaceDef >::Iterator, m_namespaceDef, and SharedPtr< T >::reset().
Referenced by Private().
detailedEnums()
TemplateVariant NamespaceContext::Private::detailedEnums () const inline
Definition at line 2846 of file context.cpp.
References getCache(), getMemberList(), MemberListType_docEnumMembers, theTranslator, and Translator::trEnumerationTypeDocumentation().
Referenced by Private().
detailedFunctions()
TemplateVariant NamespaceContext::Private::detailedFunctions () const inline
Definition at line 2850 of file context.cpp.
References getCache(), Definition::getLanguage(), getMemberList(), m_namespaceDef, MemberListType_docFuncMembers, SrcLangExt_Fortran, theTranslator, title(), Translator::trFunctionDocumentation(), and Translator::trSubprogramDocumentation().
Referenced by Private().
detailedTypedefs()
TemplateVariant NamespaceContext::Private::detailedTypedefs () const inline
Definition at line 2842 of file context.cpp.
References getCache(), getMemberList(), MemberListType_docTypedefMembers, theTranslator, and Translator::trTypedefDocumentation().
Referenced by Private().
detailedVariables()
TemplateVariant NamespaceContext::Private::detailedVariables () const inline
Definition at line 2857 of file context.cpp.
References getCache(), getMemberList(), MemberListType_docVarMembers, theTranslator, and Translator::trVariableDocumentation().
Referenced by Private().
enums()
TemplateVariant NamespaceContext::Private::enums () const inline
Definition at line 2810 of file context.cpp.
References getCache(), getMemberList(), MemberListType_decEnumMembers, theTranslator, and Translator::trEnumerations().
Referenced by Private().
functions()
TemplateVariant NamespaceContext::Private::functions () const inline
Definition at line 2814 of file context.cpp.
References getCache(), Definition::getLanguage(), getMemberList(), m_namespaceDef, MemberListType_decFuncMembers, SrcLangExt_Fortran, SrcLangExt_VHDL, theTranslator, title(), VhdlDocGen::trFunctionAndProc(), Translator::trFunctions(), and Translator::trSubprograms().
Referenced by Private().
get()
TemplateVariant NamespaceContext::Private::get (const char * n) const inline
Definition at line 2696 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by NamespaceContext::get().
getCache()
Cachable& NamespaceContext::Private::getCache () const inline private
Definition at line 2905 of file context.cpp.
References Definition::cookie().
Referenced by classes(), constantgroups(), detailedEnums(), detailedFunctions(), detailedTypedefs(), detailedVariables(), enums(), functions(), inlineClasses(), memberGroups(), namespaces(), typedefs(), and variables().
getMemberList()
TemplateVariant NamespaceContext::Private::getMemberList (SharedPtr< MemberListInfoContext > & list, MemberListType type, const char * title, bool detailed = FALSE) const inline
Definition at line 2786 of file context.cpp.
References MemberListInfoContext::alloc(), SharedPtr< T >::get(), NamespaceDef::getMemberList(), m_namespaceDef, DefinitionContext< NamespaceContext::Private >::relPathAsString(), and SharedPtr< T >::reset().
Referenced by detailedEnums(), detailedFunctions(), detailedTypedefs(), detailedVariables(), enums(), functions(), typedefs(), and variables().
hasDetails()
TemplateVariant NamespaceContext::Private::hasDetails () const inline
Definition at line 2716 of file context.cpp.
References NamespaceDef::hasDetailedDescription(), and m_namespaceDef.
Referenced by Private().
highlight()
TemplateVariant NamespaceContext::Private::highlight () const inline
Definition at line 2704 of file context.cpp.
Referenced by Private().
inlineClasses()
TemplateVariant NamespaceContext::Private::inlineClasses () const inline
Definition at line 2861 of file context.cpp.
References ClassContext::alloc(), TemplateList::alloc(), TemplateList::append(), SharedPtr< T >::get(), getCache(), NamespaceDef::getClassSDict(), NamespaceContext::Private::Cachable::inlineClasses, SDict< ClassDef >::Iterator, m_namespaceDef, and SharedPtr< T >::reset().
Referenced by Private().
memberGroups()
TemplateVariant NamespaceContext::Private::memberGroups () const inline
Definition at line 2826 of file context.cpp.
References MemberGroupListContext::alloc(), SharedPtr< T >::get(), getCache(), NamespaceDef::getMemberGroupSDict(), m_namespaceDef, NamespaceContext::Private::Cachable::memberGroups, DefinitionContext< NamespaceContext::Private >::relPathAsString(), SharedPtr< T >::reset(), and NamespaceDef::subGrouping().
Referenced by Private().
namespaces()
TemplateVariant NamespaceContext::Private::namespaces () const inline
Definition at line 2742 of file context.cpp.
References NamespaceContext::alloc(), TemplateList::alloc(), TemplateList::append(), SharedPtr< T >::get(), getCache(), NamespaceDef::getNamespaceSDict(), SDict< NamespaceDef >::Iterator, m_namespaceDef, NamespaceContext::Private::Cachable::namespaces, and SharedPtr< T >::reset().
Referenced by Private().
subHighlight()
TemplateVariant NamespaceContext::Private::subHighlight () const inline
Definition at line 2708 of file context.cpp.
Referenced by Private().
title()
TemplateVariant NamespaceContext::Private::title () const inline
Definition at line 2700 of file context.cpp.
References m_namespaceDef, and NamespaceDef::title().
Referenced by detailedFunctions(), functions(), and Private().
typedefs()
TemplateVariant NamespaceContext::Private::typedefs () const inline
Definition at line 2806 of file context.cpp.
References getCache(), getMemberList(), MemberListType_decTypedefMembers, theTranslator, and Translator::trTypedefs().
Referenced by Private().
variables()
TemplateVariant NamespaceContext::Private::variables () const inline
Definition at line 2822 of file context.cpp.
References getCache(), getMemberList(), MemberListType_decVarMembers, theTranslator, and Translator::trVariables().
Referenced by Private().
Member Data Documentation
m_namespaceDef
NamespaceDef* NamespaceContext::Private::m_namespaceDef private
Definition at line 2887 of file context.cpp.
Referenced by classes(), compoundType(), constantgroups(), detailedFunctions(), functions(), getMemberList(), hasDetails(), inlineClasses(), memberGroups(), namespaces(), and title().
s_inst
PropertyMapper< NamespaceContext::Private > NamespaceContext::Private::s_inst static private
Definition at line 2911 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp