Doxygen: ManDocVisitor Class Reference
ManDocVisitor Class Reference
Concrete visitor implementation for LaTeX output.
#include <mandocvisitor.h>
Public Member Functions
ManDocVisitor (FTextStream &t, CodeOutputInterface &ci, const char *langExt)
void visit (DocWord *)
void visit (DocLinkedWord *)
void visit (DocWhiteSpace *)
void visit (DocSymbol *)
void visit (DocURL *)
void visit (DocLineBreak *)
void visit (DocHorRuler *)
void visit (DocStyleChange *)
void visit (DocVerbatim *)
void visit (DocAnchor *)
void visit (DocInclude *)
void visit (DocIncOperator *)
void visit (DocFormula *)
void visit (DocIndexEntry *)
void visit (DocSimpleSectSep *)
void visit (DocCite *)
void visitPre (DocAutoList *)
void visitPost (DocAutoList *)
void visitPre (DocAutoListItem *)
void visitPost (DocAutoListItem *)
void visitPre (DocPara *)
void visitPost (DocPara *)
void visitPre (DocRoot *)
void visitPost (DocRoot *)
void visitPre (DocSimpleSect *)
void visitPost (DocSimpleSect *)
void visitPre (DocTitle *)
void visitPost (DocTitle *)
void visitPre (DocSimpleList *)
void visitPost (DocSimpleList *)
void visitPre (DocSimpleListItem *)
void visitPost (DocSimpleListItem *)
void visitPre (DocSection *s)
void visitPost (DocSection *)
void visitPre (DocHtmlList *s)
void visitPost (DocHtmlList *s)
void visitPre (DocHtmlListItem *)
void visitPost (DocHtmlListItem *)
void visitPre (DocHtmlDescList *)
void visitPost (DocHtmlDescList *)
void visitPre (DocHtmlDescTitle *)
void visitPost (DocHtmlDescTitle *)
void visitPre (DocHtmlDescData *)
void visitPost (DocHtmlDescData *)
void visitPre (DocHtmlTable *t)
void visitPost (DocHtmlTable *t)
void visitPre (DocHtmlCaption *)
void visitPost (DocHtmlCaption *)
void visitPre (DocHtmlRow *)
void visitPost (DocHtmlRow *)
void visitPre (DocHtmlCell *)
void visitPost (DocHtmlCell *)
void visitPre (DocInternal *)
void visitPost (DocInternal *)
void visitPre (DocHRef *)
void visitPost (DocHRef *)
void visitPre (DocHtmlHeader *)
void visitPost (DocHtmlHeader *)
void visitPre (DocImage *)
void visitPost (DocImage *)
void visitPre (DocDotFile *)
void visitPost (DocDotFile *)
void visitPre (DocMscFile *)
void visitPost (DocMscFile *)
void visitPre (DocDiaFile *)
void visitPost (DocDiaFile *)
void visitPre (DocLink *lnk)
void visitPost (DocLink *)
void visitPre (DocRef *ref)
void visitPost (DocRef *)
void visitPre (DocSecRefItem *)
void visitPost (DocSecRefItem *)
void visitPre (DocSecRefList *)
void visitPost (DocSecRefList *)
void visitPre (DocParamSect *)
void visitPost (DocParamSect *)
void visitPre (DocParamList *)
void visitPost (DocParamList *)
void visitPre (DocXRefItem *)
void visitPost (DocXRefItem *)
void visitPre (DocInternalRef *)
void visitPost (DocInternalRef *)
void visitPre (DocCopy *)
void visitPost (DocCopy *)
void visitPre (DocText *)
void visitPost (DocText *)
void visitPre (DocHtmlBlockQuote *)
void visitPost (DocHtmlBlockQuote *)
void visitPre (DocVhdlFlow *)
void visitPost (DocVhdlFlow *)
void visitPre (DocParBlock *)
void visitPost (DocParBlock *)
Public Member Functions inherited from DocVisitor
DocVisitor (int id)
virtual ~DocVisitor ()
int id () const
Private Member Functions
void filter (const char *str)
void pushEnabled ()
void popEnabled ()
Private Attributes
FTextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre
bool m_hide
bool m_firstCol
int m_indent
QStack< bool > m_enabled
QCString m_langExt
Detailed Description
Concrete visitor implementation for LaTeX output.
Definition at line 30 of file mandocvisitor.h.
Constructor & Destructor Documentation
ManDocVisitor()
ManDocVisitor::ManDocVisitor (FTextStream & t, CodeOutputInterface & ci, const char * langExt)
Definition at line 34 of file mandocvisitor.cpp.
Member Function Documentation
filter()
void ManDocVisitor::filter (const char * str) private
Definition at line 1046 of file mandocvisitor.cpp.
References m_t.
Referenced by visit(), and visitPre().
popEnabled()
void ManDocVisitor::popEnabled () private
Definition at line 1070 of file mandocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit().
pushEnabled()
void ManDocVisitor::pushEnabled () private
Definition at line 1065 of file mandocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit().
visit() [1/16]
void ManDocVisitor::visit (DocWord * w) virtual
Implements DocVisitor.
Definition at line 45 of file mandocvisitor.cpp.
References filter(), m_firstCol, m_hide, and DocWord::word().
Referenced by visitPre().
visit() [2/16]
void ManDocVisitor::visit (DocLinkedWord * w) virtual
Implements DocVisitor.
Definition at line 52 of file mandocvisitor.cpp.
References filter(), m_firstCol, m_hide, m_t, and DocLinkedWord::word().
visit() [3/16]
void ManDocVisitor::visit (DocWhiteSpace * w) virtual
Implements DocVisitor.
Definition at line 61 of file mandocvisitor.cpp.
References DocWhiteSpace::chars(), m_firstCol, m_hide, m_insidePre, and m_t.
visit() [4/16]
void ManDocVisitor::visit (DocSymbol * s) virtual
Implements DocVisitor.
Definition at line 76 of file mandocvisitor.cpp.
References HtmlEntityMapper::instance(), m_firstCol, m_hide, m_t, HtmlEntityMapper::man(), and DocSymbol::symbol().
visit() [5/16]
void ManDocVisitor::visit (DocURL * u) virtual
Implements DocVisitor.
Definition at line 92 of file mandocvisitor.cpp.
References m_firstCol, m_hide, m_t, and DocURL::url().
visit() [6/16]
void ManDocVisitor::visit (DocLineBreak *) virtual
Implements DocVisitor.
Definition at line 99 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visit() [7/16]
void ManDocVisitor::visit (DocHorRuler *) virtual
Implements DocVisitor.
Definition at line 106 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visit() [8/16]
void ManDocVisitor::visit (DocStyleChange * s) virtual
Implements DocVisitor.
Definition at line 114 of file mandocvisitor.cpp.
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Code, DocStyleChange::Div, DocStyleChange::enable(), endl(), DocStyleChange::Italic, m_firstCol, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::style(), DocStyleChange::Subscript, and DocStyleChange::Superscript.
visit() [9/16]
void ManDocVisitor::visit (DocVerbatim * s) virtual
Implements DocVisitor.
Definition at line 167 of file mandocvisitor.cpp.
References DocVerbatim::Code, DocVerbatim::context(), DocVerbatim::DocbookOnly, DocVerbatim::Dot, endl(), DocVerbatim::exampleFile(), getLanguageFromFileName(), ParserManager::getParser(), DocVerbatim::HtmlOnly, DocVerbatim::isExample(), DocVerbatim::language(), DocVerbatim::LatexOnly, m_ci, m_firstCol, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, ParserInterface::parseCode(), Doxygen::parserManager, DocVerbatim::PlantUML, DocVerbatim::RtfOnly, DocVerbatim::text(), DocVerbatim::type(), DocVerbatim::Verbatim, and DocVerbatim::XmlOnly.
visit() [10/16]
void ManDocVisitor::visit (DocAnchor *) virtual
Implements DocVisitor.
Definition at line 217 of file mandocvisitor.cpp.
visit() [11/16]
void ManDocVisitor::visit (DocInclude * inc) virtual
Implements DocVisitor.
Definition at line 222 of file mandocvisitor.cpp.
References DocInclude::blockId(), DocInclude::context(), DocInclude::DontInclude, endl(), err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), DocInclude::file(), getLanguageFromFileName(), ParserManager::getParser(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_firstCol, m_hide, m_t, parseCode(), Doxygen::parserManager, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::text(), DocInclude::type(), and DocInclude::VerbInclude.
visit() [12/16]
void ManDocVisitor::visit (DocIncOperator * op) virtual
Implements DocVisitor.
Definition at line 344 of file mandocvisitor.cpp.
References DocIncOperator::context(), endl(), DocIncOperator::exampleFile(), getLanguageFromFileName(), ParserManager::getParser(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), m_ci, m_firstCol, m_hide, m_langExt, m_t, ParserInterface::parseCode(), Doxygen::parserManager, popEnabled(), pushEnabled(), DocIncOperator::Skip, DocIncOperator::text(), and DocIncOperator::type().
visit() [13/16]
void ManDocVisitor::visit (DocFormula * f) virtual
Implements DocVisitor.
Definition at line 389 of file mandocvisitor.cpp.
References m_hide, m_t, and DocFormula::text().
visit() [14/16]
void ManDocVisitor::visit (DocIndexEntry *) virtual
Implements DocVisitor.
Definition at line 395 of file mandocvisitor.cpp.
visit() [15/16]
void ManDocVisitor::visit (DocSimpleSectSep *) virtual
Implements DocVisitor.
Definition at line 399 of file mandocvisitor.cpp.
visit() [16/16]
void ManDocVisitor::visit (DocCite * cite) virtual
Implements DocVisitor.
Definition at line 403 of file mandocvisitor.cpp.
References DocCite::file(), filter(), m_hide, m_t, and DocCite::text().
visitPost() [1/38]
void ManDocVisitor::visitPost (DocAutoList *) virtual
Implements DocVisitor.
Definition at line 424 of file mandocvisitor.cpp.
References endl(), m_hide, m_indent, and m_t.
visitPost() [2/38]
void ManDocVisitor::visitPost (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 450 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPost() [3/38]
void ManDocVisitor::visitPost (DocPara * p) virtual
Implements DocVisitor.
Definition at line 461 of file mandocvisitor.cpp.
References endl(), DocPara::isLast(), DocNode::kind(), DocNode::Kind_ParamSect, m_firstCol, m_hide, m_t, and DocNode::parent().
visitPost() [4/38]
void ManDocVisitor::visitPost (DocRoot *) virtual
Implements DocVisitor.
Definition at line 480 of file mandocvisitor.cpp.
visitPost() [5/38]
void ManDocVisitor::visitPost (DocSimpleSect *) virtual
Implements DocVisitor.
Definition at line 538 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPost() [6/38]
void ManDocVisitor::visitPost (DocTitle *) virtual
Implements DocVisitor.
Definition at line 551 of file mandocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [7/38]
void ManDocVisitor::visitPost (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 566 of file mandocvisitor.cpp.
References endl(), m_hide, m_indent, and m_t.
visitPost() [8/38]
void ManDocVisitor::visitPost (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 583 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPost() [9/38]
void ManDocVisitor::visitPost (DocSection *) virtual
Implements DocVisitor.
Definition at line 602 of file mandocvisitor.cpp.
visitPost() [10/38]
void ManDocVisitor::visitPost (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 614 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, m_indent, and m_t.
visitPost() [11/38]
void ManDocVisitor::visitPost (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 641 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPost() [12/38]
void ManDocVisitor::visitPost (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 669 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPost() [13/38]
void ManDocVisitor::visitPost (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 685 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPost() [14/38]
void ManDocVisitor::visitPost (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 696 of file mandocvisitor.cpp.
visitPost() [15/38]
void ManDocVisitor::visitPost (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 704 of file mandocvisitor.cpp.
visitPost() [16/38]
void ManDocVisitor::visitPost (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 712 of file mandocvisitor.cpp.
visitPost() [17/38]
void ManDocVisitor::visitPost (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 720 of file mandocvisitor.cpp.
visitPost() [18/38]
void ManDocVisitor::visitPost (DocHtmlCell *) virtual
Implements DocVisitor.
Definition at line 728 of file mandocvisitor.cpp.
visitPost() [19/38]
void ManDocVisitor::visitPost (DocInternal *) virtual
Implements DocVisitor.
Definition at line 741 of file mandocvisitor.cpp.
References m_hide.
visitPost() [20/38]
void ManDocVisitor::visitPost (DocHRef *) virtual
Implements DocVisitor.
Definition at line 756 of file mandocvisitor.cpp.
References m_hide, and m_t.
visitPost() [21/38]
void ManDocVisitor::visitPost (DocHtmlHeader * header) virtual
Implements DocVisitor.
Definition at line 770 of file mandocvisitor.cpp.
References endl(), DocHtmlHeader::level(), m_firstCol, m_hide, and m_t.
visitPost() [22/38]
void ManDocVisitor::visitPost (DocImage *) virtual
Implements DocVisitor.
Definition at line 782 of file mandocvisitor.cpp.
visitPost() [23/38]
void ManDocVisitor::visitPost (DocDotFile *) virtual
Implements DocVisitor.
Definition at line 790 of file mandocvisitor.cpp.
visitPost() [24/38]
void ManDocVisitor::visitPost (DocMscFile *) virtual
Implements DocVisitor.
Definition at line 797 of file mandocvisitor.cpp.
visitPost() [25/38]
void ManDocVisitor::visitPost (DocDiaFile *) virtual
Implements DocVisitor.
Definition at line 805 of file mandocvisitor.cpp.
visitPost() [26/38]
void ManDocVisitor::visitPost (DocLink *) virtual
Implements DocVisitor.
Definition at line 815 of file mandocvisitor.cpp.
References m_hide, and m_t.
visitPost() [27/38]
void ManDocVisitor::visitPost (DocRef *) virtual
Implements DocVisitor.
Definition at line 828 of file mandocvisitor.cpp.
References m_hide, and m_t.
visitPost() [28/38]
void ManDocVisitor::visitPost (DocSecRefItem *) virtual
Implements DocVisitor.
Definition at line 844 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPost() [29/38]
void ManDocVisitor::visitPost (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 857 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, m_indent, and m_t.
visitPost() [30/38]
void ManDocVisitor::visitPost (DocParamSect *) virtual
Implements DocVisitor.
Definition at line 913 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPost() [31/38]
void ManDocVisitor::visitPost (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 946 of file mandocvisitor.cpp.
References endl(), DocParamList::isLast(), m_firstCol, m_hide, and m_t.
visitPost() [32/38]
void ManDocVisitor::visitPost (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 971 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, m_t, and DocXRefItem::title().
visitPost() [33/38]
void ManDocVisitor::visitPost (DocInternalRef *) virtual
Implements DocVisitor.
Definition at line 987 of file mandocvisitor.cpp.
References m_hide, and m_t.
visitPost() [34/38]
void ManDocVisitor::visitPost (DocCopy *) virtual
Implements DocVisitor.
Definition at line 997 of file mandocvisitor.cpp.
visitPost() [35/38]
void ManDocVisitor::visitPost (DocText *) virtual
Implements DocVisitor.
Definition at line 1005 of file mandocvisitor.cpp.
visitPost() [36/38]
void ManDocVisitor::visitPost (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1020 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPost() [37/38]
void ManDocVisitor::visitPost (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1033 of file mandocvisitor.cpp.
visitPost() [38/38]
void ManDocVisitor::visitPost (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1041 of file mandocvisitor.cpp.
visitPre() [1/38]
void ManDocVisitor::visitPre (DocAutoList *) virtual
Implements DocVisitor.
Definition at line 418 of file mandocvisitor.cpp.
References m_hide, and m_indent.
visitPre() [2/38]
void ManDocVisitor::visitPre (DocAutoListItem * li) virtual
Implements DocVisitor.
Definition at line 431 of file mandocvisitor.cpp.
References endl(), DocAutoListItem::itemNumber(), m_firstCol, m_hide, m_indent, m_t, and DocNode::parent().
visitPre() [3/38]
void ManDocVisitor::visitPre (DocPara *) virtual
Implements DocVisitor.
Definition at line 457 of file mandocvisitor.cpp.
visitPre() [4/38]
void ManDocVisitor::visitPre (DocRoot *) virtual
Implements DocVisitor.
Definition at line 476 of file mandocvisitor.cpp.
visitPre() [5/38]
void ManDocVisitor::visitPre (DocSimpleSect * s) virtual
Implements DocVisitor.
Definition at line 484 of file mandocvisitor.cpp.
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, endl(), DocSimpleSect::Invar, m_firstCol, m_hide, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), Translator::trVersion(), Translator::trWarning(), DocSimpleSect::type(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
visitPre() [6/38]
void ManDocVisitor::visitPre (DocTitle *) virtual
Implements DocVisitor.
Definition at line 547 of file mandocvisitor.cpp.
visitPre() [7/38]
void ManDocVisitor::visitPre (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 558 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, m_indent, and m_t.
visitPre() [8/38]
void ManDocVisitor::visitPre (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 573 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, m_indent, and m_t.
visitPre() [9/38]
void ManDocVisitor::visitPre (DocSection * s) virtual
Implements DocVisitor.
Definition at line 590 of file mandocvisitor.cpp.
References endl(), filter(), DocSection::level(), m_firstCol, m_hide, m_t, and DocSection::title().
visitPre() [10/38]
void ManDocVisitor::visitPre (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 606 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, m_indent, and m_t.
visitPre() [11/38]
void ManDocVisitor::visitPre (DocHtmlListItem * li) virtual
Implements DocVisitor.
Definition at line 622 of file mandocvisitor.cpp.
References endl(), DocHtmlListItem::itemNumber(), m_firstCol, m_hide, m_indent, m_t, DocHtmlList::Ordered, and DocNode::parent().
visitPre() [12/38]
void ManDocVisitor::visitPre (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 665 of file mandocvisitor.cpp.
visitPre() [13/38]
void ManDocVisitor::visitPre (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 677 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPre() [14/38]
void ManDocVisitor::visitPre (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 692 of file mandocvisitor.cpp.
visitPre() [15/38]
void ManDocVisitor::visitPre (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 700 of file mandocvisitor.cpp.
visitPre() [16/38]
void ManDocVisitor::visitPre (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 708 of file mandocvisitor.cpp.
visitPre() [17/38]
void ManDocVisitor::visitPre (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 716 of file mandocvisitor.cpp.
visitPre() [18/38]
void ManDocVisitor::visitPre (DocHtmlCell *) virtual
Implements DocVisitor.
Definition at line 724 of file mandocvisitor.cpp.
visitPre() [19/38]
void ManDocVisitor::visitPre (DocInternal *) virtual
Implements DocVisitor.
Definition at line 732 of file mandocvisitor.cpp.
References m_hide.
visitPre() [20/38]
void ManDocVisitor::visitPre (DocHRef *) virtual
Implements DocVisitor.
Definition at line 750 of file mandocvisitor.cpp.
References m_hide, and m_t.
visitPre() [21/38]
void ManDocVisitor::visitPre (DocHtmlHeader * header) virtual
Implements DocVisitor.
Definition at line 762 of file mandocvisitor.cpp.
References endl(), DocHtmlHeader::level(), m_firstCol, m_hide, and m_t.
visitPre() [22/38]
void ManDocVisitor::visitPre (DocImage *) virtual
Implements DocVisitor.
Definition at line 778 of file mandocvisitor.cpp.
visitPre() [23/38]
void ManDocVisitor::visitPre (DocDotFile *) virtual
Implements DocVisitor.
Definition at line 786 of file mandocvisitor.cpp.
visitPre() [24/38]
void ManDocVisitor::visitPre (DocMscFile *) virtual
Implements DocVisitor.
Definition at line 793 of file mandocvisitor.cpp.
visitPre() [25/38]
void ManDocVisitor::visitPre (DocDiaFile *) virtual
Implements DocVisitor.
Definition at line 801 of file mandocvisitor.cpp.
visitPre() [26/38]
void ManDocVisitor::visitPre (DocLink * lnk) virtual
Implements DocVisitor.
Definition at line 809 of file mandocvisitor.cpp.
References m_hide, and m_t.
visitPre() [27/38]
void ManDocVisitor::visitPre (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 821 of file mandocvisitor.cpp.
References filter(), DocRef::hasLinkText(), m_hide, m_t, and DocRef::targetTitle().
visitPre() [28/38]
void ManDocVisitor::visitPre (DocSecRefItem *) virtual
Implements DocVisitor.
Definition at line 834 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, m_indent, and m_t.
visitPre() [29/38]
void ManDocVisitor::visitPre (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 851 of file mandocvisitor.cpp.
References m_hide, and m_indent.
visitPre() [30/38]
void ManDocVisitor::visitPre (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 884 of file mandocvisitor.cpp.
References endl(), DocParamSect::Exception, m_firstCol, m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), and DocParamSect::type().
visitPre() [31/38]
void ManDocVisitor::visitPre (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 922 of file mandocvisitor.cpp.
References DocNode::Kind_LinkedWord, DocNode::Kind_Word, m_hide, m_t, DocParamList::parameters(), and visit().
visitPre() [32/38]
void ManDocVisitor::visitPre (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 956 of file mandocvisitor.cpp.
References endl(), filter(), m_firstCol, m_hide, m_t, and DocXRefItem::title().
visitPre() [33/38]
void ManDocVisitor::visitPre (DocInternalRef *) virtual
Implements DocVisitor.
Definition at line 981 of file mandocvisitor.cpp.
References m_hide, and m_t.
visitPre() [34/38]
void ManDocVisitor::visitPre (DocCopy *) virtual
Implements DocVisitor.
Definition at line 993 of file mandocvisitor.cpp.
visitPre() [35/38]
void ManDocVisitor::visitPre (DocText *) virtual
Implements DocVisitor.
Definition at line 1001 of file mandocvisitor.cpp.
visitPre() [36/38]
void ManDocVisitor::visitPre (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1009 of file mandocvisitor.cpp.
References endl(), m_firstCol, m_hide, and m_t.
visitPre() [37/38]
void ManDocVisitor::visitPre (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1029 of file mandocvisitor.cpp.
visitPre() [38/38]
void ManDocVisitor::visitPre (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1037 of file mandocvisitor.cpp.
Member Data Documentation
m_ci
CodeOutputInterface& ManDocVisitor::m_ci private
Definition at line 157 of file mandocvisitor.h.
Referenced by visit().
m_enabled
QStack<bool> ManDocVisitor::m_enabled private
Definition at line 162 of file mandocvisitor.h.
Referenced by popEnabled(), and pushEnabled().
m_firstCol
bool ManDocVisitor::m_firstCol private
Definition at line 160 of file mandocvisitor.h.
Referenced by visit(), visitPost(), and visitPre().
m_hide
bool ManDocVisitor::m_hide private
Definition at line 159 of file mandocvisitor.h.
Referenced by popEnabled(), pushEnabled(), visit(), visitPost(), and visitPre().
m_indent
int ManDocVisitor::m_indent private
Definition at line 161 of file mandocvisitor.h.
Referenced by visitPost(), and visitPre().
m_insidePre
bool ManDocVisitor::m_insidePre private
Definition at line 158 of file mandocvisitor.h.
Referenced by visit().
m_langExt
QCString ManDocVisitor::m_langExt private
Definition at line 163 of file mandocvisitor.h.
Referenced by visit().
m_t
FTextStream& ManDocVisitor::m_t private
Definition at line 156 of file mandocvisitor.h.
Referenced by filter(), visit(), visitPost(), and visitPre().
The documentation for this class was generated from the following files:
src/mandocvisitor.h
src/mandocvisitor.cpp