Doxygen: NamespaceListContext Class Reference
NamespaceListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static NamespaceListContext * alloc ()
Private Member Functions
NamespaceListContext ()
~NamespaceListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 586 of file context.h.
Constructor & Destructor Documentation
NamespaceListContext()
NamespaceListContext::NamespaceListContext () private
Definition at line 6861 of file context.cpp.
References NamespaceListContext::Private::addNamespaces(), Doxygen::namespaceSDict, p, and Private.
Referenced by alloc().
~NamespaceListContext()
NamespaceListContext::~NamespaceListContext () private
Definition at line 6867 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int NamespaceListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 595 of file context.h.
References RefCountedContext::addRef().
alloc()
static NamespaceListContext* NamespaceListContext::alloc () inline static
Definition at line 589 of file context.h.
References NamespaceListContext().
Referenced by generateOutputViaTemplate().
at()
TemplateVariant NamespaceListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 6878 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int NamespaceListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 6873 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * NamespaceListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 6883 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int NamespaceListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 596 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* NamespaceListContext::p private
Definition at line 601 of file context.h.
Referenced by at(), count(), createIterator(), NamespaceListContext(), and ~NamespaceListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp