Doxygen: src/vhdldocgen.cpp File Reference
vhdldocgen.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <qcstring.h>
#include <qfileinfo.h>
#include <qstringlist.h>
#include <qmap.h>
#include "vhdldocgen.h"
#include "message.h"
#include "config.h"
#include "doxygen.h"
#include "util.h"
#include "language.h"
#include "commentscan.h"
#include "index.h"
#include "definition.h"
#include "searchindex.h"
#include "outputlist.h"
#include "parserintf.h"
#include "layout.h"
#include "arguments.h"
#include "portable.h"
#include "memberlist.h"
#include "memberdef.h"
#include "groupdef.h"
#include "classlist.h"
#include "namespacedef.h"
#include "filename.h"
#include "membergroup.h"
#include "plantuml.h"
#include "vhdljjparser.h"
#include "VhdlParser.h"
#include "vhdlcode.h"
Macros
#define theTranslator_vhdlType VhdlDocGen::trVhdlType
#define STARTL
#define DECLN
#define STARTFIN (FlowChart::START_NO | FlowChart::END_NO)
#define LOOP
#define ENDCL (FlowChart::END_CASE | FlowChart::END_LOOP)
#define EEND (FlowChart::ENDIF_NO | FlowChart::ELSE_NO)
#define IFF (FlowChart::ELSIF_NO | FlowChart::IF_NO)
#define EXITNEXT (FlowChart::EXIT_NO | FlowChart::NEXT_NO)
#define EMPTY (EEND | FlowChart::ELSIF_NO)
#define EE (FlowChart::ELSE_NO | FlowChart::ELSIF_NO)
#define EMPTNODE (ENDCL | EEND | FlowChart::ELSIF_NO)
#define FLOWLEN (flowList.count()-1)
Functions
static QDict< QCString > g_vhdlKeyDict0 (17, FALSE)
static QDict< QCString > g_vhdlKeyDict1 (17, FALSE)
static QDict< QCString > g_vhdlKeyDict2 (17, FALSE)
static QDict< QCString > g_vhdlKeyDict3 (17, FALSE)
static void initUCF (Entry *root, const char *type, QCString &qcs, int line, QCString &fileName, QCString &brief)
static void writeUCFLink (const MemberDef *mdef, OutputList &ol)
static void assignBinding (VhdlConfNode *conf)
static void addInstance (ClassDef *entity, ClassDef *arch, ClassDef *inst, Entry *cur, ClassDef *archBind=NULL)
static void createSVG ()
static void startDot (FTextStream &t)
static void startTable (FTextStream &t, const QCString &className)
static QList< MemberDef > * getPorts (ClassDef *cd)
static void writeVhdlEntityToolTip (FTextStream &t, ClassDef *cd)
static void endDot (FTextStream &t)
static void writeTable (QList< MemberDef > *port, FTextStream &t)
static void endTabel (FTextStream &t)
static void writeClassToDot (FTextStream &t, ClassDef *cd)
static void writeVhdlDotLink (FTextStream &t, const QCString &a, const QCString &b, const QCString &style)
static void codify (FTextStream &t, const char *str)
static void writeLink (const MemberDef *mdef, OutputList &ol)
static void startFonts (const QCString &q, const char *keyword, OutputList &ol)
static QCString splitString (QCString &str, char c)
static int compareString (const QCString &s1, const QCString &s2)
static QCString formatBriefNote (const QCString &brief, ClassDef *cd)
static void writeColumn (FTextStream &t, MemberDef *md, bool start)
static void setGlobalType (MemberList *ml)
static bool membersHaveSpecificType (MemberList *ml, uint64 type)
static MemberDef * findMemFlow (const MemberDef *mdef)
void alignText (QCString &q)
Variables
static const MemberDef * flowMember =0
static QMap< QCString, MemberDef * > varMap
static QList< ClassDef > qli
static QMap< ClassDef *, QList< ClassDef > > packages
static int recordCounter =0
static QList< MemberDef > mdList
static int ifcounter =0
static int nodeCounter =0
struct {
const char * textNodeLink
const char * yesNodeLink
const char * noNodeLink
const char * comment
const char * decisionNode
const char * varNode
const char * startEndNode
const char * textNode
} flowCol
Macro Definition Documentation
DECLN
#define DECLN
Value:
(FlowChart::WHEN_NO      | \
                  FlowChart::ELSIF_NO     | FlowChart::IF_NO    | \
                  FlowChart::FOR_NO       | FlowChart::WHILE_NO | \
                  FlowChart::CASE_NO      | FlowChart::LOOP_NO )
Definition at line 3419 of file vhdldocgen.cpp.
Referenced by FlowChart::writeShape().
EE
#define EE (FlowChart::ELSE_NO | FlowChart::ELSIF_NO)
Definition at line 3431 of file vhdldocgen.cpp.
EEND
#define EEND (FlowChart::ENDIF_NO | FlowChart::ELSE_NO)
Definition at line 3427 of file vhdldocgen.cpp.
Referenced by FlowChart::writeFlowLinks(), and FlowChart::writeShape().
EMPTNODE
#define EMPTNODE (ENDCL | EEND | FlowChart::ELSIF_NO)
Definition at line 3432 of file vhdldocgen.cpp.
Referenced by FlowChart::printNode().
EMPTY
#define EMPTY (EEND | FlowChart::ELSIF_NO)
Definition at line 3430 of file vhdldocgen.cpp.
Referenced by FlowChart::colTextNodes().
ENDCL
#define ENDCL (FlowChart::END_CASE | FlowChart::END_LOOP)
Definition at line 3426 of file vhdldocgen.cpp.
Referenced by FlowChart::writeShape().
EXITNEXT
#define EXITNEXT (FlowChart::EXIT_NO | FlowChart::NEXT_NO)
Definition at line 3429 of file vhdldocgen.cpp.
Referenced by FlowChart::writeShape().
FLOWLEN
#define FLOWLEN (flowList.count()-1)
Definition at line 3433 of file vhdldocgen.cpp.
Referenced by FlowChart::buildCommentNodes(), FlowChart::getNextNode(), and FlowChart::printUmlTree().
IFF
#define IFF (FlowChart::ELSIF_NO | FlowChart::IF_NO)
Definition at line 3428 of file vhdldocgen.cpp.
Referenced by FlowChart::colTextNodes(), FlowChart::writeFlowLinks(), and FlowChart::writeShape().
LOOP
#define LOOP
Value:
(FlowChart::FOR_NO       | FlowChart::WHILE_NO | \
                  FlowChart::LOOP_NO )
Definition at line 3424 of file vhdldocgen.cpp.
Referenced by FlowChart::findLabel(), FlowChart::findPrevLoop(), and FlowChart::writeShape().
STARTFIN
#define STARTFIN (FlowChart::START_NO | FlowChart::END_NO)
Definition at line 3423 of file vhdldocgen.cpp.
Referenced by FlowChart::writeShape().
STARTL
#define STARTL
Value:
(FlowChart::WHILE_NO     | FlowChart::IF_NO    | \
                  FlowChart::FOR_NO       | FlowChart::CASE_NO  | \
                  FlowChart::LOOP_NO      | WHEN_NO)
Definition at line 3416 of file vhdldocgen.cpp.
Referenced by FlowChart::FlowChart(), FlowChart::printNode(), and FlowChart::writeEdge().
theTranslator_vhdlType
#define theTranslator_vhdlType VhdlDocGen::trVhdlType
Definition at line 64 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::getClassTitle(), VhdlDocGen::writeInlineClassLink(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVhdlDeclarations().
Function Documentation
addInstance()
static void addInstance (ClassDef * entity, ClassDef * arch, ClassDef * inst, Entry * cur, ClassDef * archBind = NULL) static
Definition at line 3107 of file vhdldocgen.cpp.
References VhdlDocGen::addBaseClass(), TagInfo::anchor, Entry::brief, Entry::briefFile, Entry::briefLine, Entry::doc, Entry::docFile, Entry::docLine, TagInfo::fileName, FileDef::fileName(), Definition::getDefFileName(), ClassDef::getFileDef(), ClassDef::getOutputFileBase(), ClassDef::insertBaseClass(), ClassDef::insertMember(), ClassDef::insertSubClass(), VhdlDocGen::INSTANTIATION, ClassDef::isBaseClass(), VhdlDocGen::isSubClass(), Member, MemberDef::MemberDef(), MemberType_Variable, Definition::name(), Entry::name, Normal, Public, Definition::setBodyDef(), Definition::setBodySegment(), MemberDef::setBriefDescription(), MemberDef::setDocumentation(), Definition::setLanguage(), MemberDef::setMemberSpecifiers(), MemberDef::setTagInfo(), SrcLangExt_VHDL, Entry::startColumn, Entry::startLine, Entry::stat, TagInfo::tagName, Entry::type, and Entry::write.
Referenced by assignBinding(), and VhdlDocGen::computeVhdlComponentRelations().
alignText()
void alignText (QCString & q)
Definition at line 3468 of file vhdldocgen.cpp.
Referenced by FlowChart::writeShape().
assignBinding()
void assignBinding (VhdlConfNode * conf) static
Definition at line 2918 of file vhdldocgen.cpp.
References addInstance(), VhdlConfNode::arch, VhdlConfNode::binding, VhdlConfNode::compSpec, VhdlConfNode::confVhdl, Entry::exception, VhdlDocGen::findVhdlClass(), VhdlDocGen::getIndexWord(), getVhdlConfiguration(), getVhdlInstList(), VhdlConfNode::isInlineConf, Definition::name(), Entry::name, VhdlDocGen::parseForBinding(), split(), Entry::stat, and Entry::type.
Referenced by VhdlDocGen::computeVhdlComponentRelations().
codify()
static void codify (FTextStream & t, const char * str) static
Definition at line 103 of file vhdldocgen.cpp.
Referenced by writeColumn().
compareString()
static int compareString (const QCString & s1, const QCString & s2) static
Definition at line 158 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findFunction().
createSVG()
static void createSVG () static
Definition at line 163 of file vhdldocgen.cpp.
References Config_getString, err(), and portable_system().
Referenced by VhdlDocGen::writeOverview().
endDot()
static void endDot (FTextStream & t) static
Definition at line 270 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::writeOverview().
endTabel()
static void endTabel (FTextStream & t) static
Definition at line 450 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::writeOverview().
findMemFlow()
static MemberDef* findMemFlow (const MemberDef * mdef) static
Definition at line 3305 of file vhdldocgen.cpp.
References Definition::getStartBodyLine(), mdList, and Definition::name().
Referenced by VhdlDocGen::createFlowChart().
formatBriefNote()
static QCString formatBriefNote (const QCString & brief, ClassDef * cd) static
Definition at line 293 of file vhdldocgen.cpp.
References Definition::briefLine(), Definition::getDefFileName(), parseCommentAsText(), and split().
Referenced by writeVhdlEntityToolTip().
g_vhdlKeyDict0()
static QDict<QCString> g_vhdlKeyDict0 (17 , FALSE) static
Referenced by VhdlDocGen::findKeyWord(), and VhdlDocGen::init().
g_vhdlKeyDict1()
static QDict<QCString> g_vhdlKeyDict1 (17 , FALSE) static
Referenced by VhdlDocGen::findKeyWord(), and VhdlDocGen::init().
g_vhdlKeyDict2()
static QDict<QCString> g_vhdlKeyDict2 (17 , FALSE) static
Referenced by VhdlDocGen::findKeyWord(), and VhdlDocGen::init().
g_vhdlKeyDict3()
static QDict<QCString> g_vhdlKeyDict3 (17 , FALSE) static
Referenced by VhdlDocGen::findKeyWord(), and VhdlDocGen::init().
getPorts()
static QList< MemberDef > * getPorts (ClassDef * cd) static
Definition at line 470 of file vhdldocgen.cpp.
References ClassDef::getMemberList(), MemberDef::getMemberSpecifiers(), MemberListType_variableMembers, and VhdlDocGen::PORT.
Referenced by VhdlDocGen::writeOverview().
initUCF()
static void initUCF (Entry * root, const char * type, QCString & qcs, int line, QCString & fileName, QCString & brief) static
Definition at line 2709 of file vhdldocgen.cpp.
References Entry::addSubEntry(), Entry::args, Entry::bodyLine, brief, Entry::brief, Entry::briefFile, Entry::briefLine, VhdlDocGen::deleteAllChars(), Entry::fileName, VhdlDocGen::getRecordNumber(), Entry::lang, Entry::name, Entry::section, Entry::spec, SrcLangExt_VHDL, Entry::type, VhdlDocGen::UCF_CONST, and Entry::VARIABLE_SEC.
Referenced by VhdlDocGen::parseUCF().
membersHaveSpecificType()
static bool membersHaveSpecificType (MemberList * ml, uint64 type) static
Definition at line 2330 of file vhdldocgen.cpp.
References MemberList::getMemberGroupList(), and MemberDef::getMemberSpecifiers().
Referenced by VhdlDocGen::writeVHDLDeclarations().
setGlobalType()
static void setGlobalType (MemberList * ml) static
Definition at line 1801 of file vhdldocgen.cpp.
References MemberDef::argsString(), VhdlDocGen::CONFIG, VhdlDocGen::INSTANTIATION, VhdlDocGen::LIBRARY, VhdlDocGen::MISCELLANEOUS, MemberDef::setMemberSpecifiers(), MemberDef::typeString(), VhdlDocGen::UCF_CONST, and VhdlDocGen::USE.
Referenced by VhdlDocGen::writeVHDLDeclarations().
splitString()
static QCString splitString (QCString & str, char c) static
Definition at line 146 of file vhdldocgen.cpp.
Referenced by writeUCFLink().
startDot()
static void startDot (FTextStream & t) static
Definition at line 262 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::writeOverview().
startFonts()
static void startFonts (const QCString & q, const char * keyword, OutputList & ol) static
Definition at line 139 of file vhdldocgen.cpp.
References OutputList::docify(), OutputList::endFontClass(), and OutputList::startFontClass().
Referenced by VhdlDocGen::writeFormatString(), VhdlDocGen::writeFuncProcDocu(), VhdlDocGen::writeFunctionProto(), VhdlDocGen::writeProcedureProto(), and VhdlDocGen::writeStringLink().
startTable()
static void startTable (FTextStream & t, const QCString & className) static
Definition at line 275 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::writeOverview().
writeClassToDot()
static void writeClassToDot (FTextStream & t, ClassDef * cd) static
Definition at line 456 of file vhdldocgen.cpp.
References ClassDef::getOutputFileBase(), Doxygen::htmlFileExtension, and Definition::name().
Referenced by VhdlDocGen::writeOverview().
writeColumn()
static void writeColumn (FTextStream & t, MemberDef * md, bool start) static
Definition at line 364 of file vhdldocgen.cpp.
References MemberDef::anchor(), MemberDef::argsString(), Definition::briefDescriptionAsTooltip(), codify(), MemberDef::getOutputFileBase(), Doxygen::htmlFileExtension, Definition::name(), and MemberDef::typeString().
Referenced by writeTable().
writeLink()
static void writeLink (const MemberDef * mdef, OutputList & ol) static
Definition at line 131 of file vhdldocgen.cpp.
References MemberDef::anchor(), MemberDef::getOutputFileBase(), MemberDef::getReference(), Definition::name(), and OutputList::writeObjectLink().
Referenced by VhdlDocGen::writeSource(), VhdlDocGen::writeStringLink(), writeUCFLink(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLTypeDocumentation().
writeTable()
static void writeTable (QList< MemberDef > * port, FTextStream & t) static
Definition at line 497 of file vhdldocgen.cpp.
References MemberDef::typeString(), and writeColumn().
Referenced by VhdlDocGen::writeOverview().
writeUCFLink()
static void writeUCFLink (const MemberDef * mdef, OutputList & ol) static
Definition at line 2767 of file vhdldocgen.cpp.
References MemberDef::argsString(), OutputList::docify(), VhdlDocGen::formatString(), OutputList::insertMemberAlign(), Definition::name(), splitString(), writeLink(), and OutputList::writeString().
Referenced by VhdlDocGen::writeVHDLDeclaration().
writeVhdlDotLink()
static void writeVhdlDotLink (FTextStream & t, const QCString & a, const QCString & b, const QCString & style) static
Definition at line 281 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::writeOverview(), and writeVhdlEntityToolTip().
writeVhdlEntityToolTip()
static void writeVhdlEntityToolTip (FTextStream & t, ClassDef * cd) static
Definition at line 343 of file vhdldocgen.cpp.
References brief, Definition::briefDescription(), formatBriefNote(), VhdlDocGen::getRecordNumber(), Definition::name(), and writeVhdlDotLink().
Referenced by VhdlDocGen::writeOverview().
Variable Documentation
comment
const char* comment
Definition at line 3446 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::parseUCF().
decisionNode
const char* decisionNode
Definition at line 3447 of file vhdldocgen.cpp.
flowCol
struct { ... } flowCol
Initial value:
=
{ "green",
  "red",
  "black",
  "khaki",
  "0.7 0.3 1.0",
  "lightyellow",
  "white",
  "lightcyan"
}
Referenced by FlowChart::buildCommentNodes(), FlowChart::writeEdge(), and FlowChart::writeShape().
flowMember
const MemberDef* flowMember =0 static
Definition at line 88 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::getFlowMember().
ifcounter
int ifcounter =0 static
Definition at line 3435 of file vhdldocgen.cpp.
Referenced by FlowChart::delFlowList(), FlowChart::FlowChart(), and FlowChart::moveToPrevLevel().
mdList
QList<MemberDef> mdList static
Definition at line 3303 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::createFlowChart(), and findMemFlow().
nodeCounter
int nodeCounter =0 static
Definition at line 3436 of file vhdldocgen.cpp.
Referenced by FlowChart::delFlowList(), and FlowChart::FlowChart().
noNodeLink
const char* noNodeLink
Definition at line 3443 of file vhdldocgen.cpp.
packages
QMap<ClassDef*,QList<ClassDef> > packages static
Definition at line 715 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findAllPackages(), VhdlDocGen::findMember(), and VhdlDocGen::resetCodeVhdlParserState().
qli
QList<ClassDef> qli static
Definition at line 714 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findMemberDef(), and VhdlDocGen::resetCodeVhdlParserState().
recordCounter
int recordCounter =0 static
Definition at line 1308 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::getRecordNumber().
startEndNode
const char* startEndNode
Definition at line 3449 of file vhdldocgen.cpp.
textNode
const char* textNode
Definition at line 3450 of file vhdldocgen.cpp.
textNodeLink
const char* textNodeLink
Definition at line 3441 of file vhdldocgen.cpp.
varMap
QMap<QCString,MemberDef*> varMap static
Definition at line 713 of file vhdldocgen.cpp.
Referenced by VhdlDocGen::findMemberDef(), and VhdlDocGen::resetCodeVhdlParserState().
varNode
const char* varNode
Definition at line 3448 of file vhdldocgen.cpp.
yesNodeLink
const char* yesNodeLink
Definition at line 3442 of file vhdldocgen.cpp.