Doxygen: NamespaceContext Class Reference
NamespaceContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static NamespaceContext * alloc (NamespaceDef *nd)
Private Member Functions
NamespaceContext (NamespaceDef *)
~NamespaceContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 272 of file context.h.
Constructor & Destructor Documentation
NamespaceContext()
NamespaceContext::NamespaceContext (NamespaceDef * nd) private
Definition at line 2917 of file context.cpp.
References p, and Private.
Referenced by alloc().
~NamespaceContext()
NamespaceContext::~NamespaceContext () private
Definition at line 2922 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int NamespaceContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 279 of file context.h.
References RefCountedContext::addRef().
alloc()
static NamespaceContext* NamespaceContext::alloc (NamespaceDef * nd) inline static
Definition at line 275 of file context.h.
References NamespaceContext().
Referenced by NamespaceListContext::Private::addNamespaces(), NamespaceContext::Private::constantgroups(), FileContext::Private::constantgroups(), ModuleContext::Private::constantgroups(), MemberContext::Private::getNamespace(), NestingNodeContext::Private::getNamespace(), NamespaceContext::Private::namespaces(), FileContext::Private::namespaces(), and ModuleContext::Private::namespaces().
get()
TemplateVariant NamespaceContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 2927 of file context.cpp.
References NamespaceContext::Private::get(), and p.
release()
virtual int NamespaceContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 280 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* NamespaceContext::p private
Definition at line 285 of file context.h.
Referenced by get(), NamespaceContext(), and ~NamespaceContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp