Doxygen: TemplateEngine Class Reference
TemplateEngine Class Reference
Template API
Engine to create templates and template contexts.
#include <template.h>
Classes
class Private
Private data of the template engine.
Public Member Functions
TemplateEngine ()
Create a template engine.
~TemplateEngine ()
Destroys the template engine.
TemplateContext * createContext () const
Creates a new context that can be using to render a template.
void destroyContext (TemplateContext *ctx)
Destroys a context created via createContext().
Template * loadByName (const QCString &fileName, int fromLine)
Creates a new template whose contents are in a file.
void unload (Template *t)
Indicates that template t is no longer needed.
void printIncludeContext (const char *fileName, int line) const
Prints the current template file include stack.
void setTemplateDir (const char *dirName)
Sets the search directory where to look for template files.
Private Member Functions
void enterBlock (const QCString &fileName, const QCString &blockName, int line)
void leaveBlock ()
void setOutputExtension (const char *extension)
Sets the extension of the output file.
QCString outputExtension () const
Returns the output extension, set via setOutputExtension()
Private Attributes
Private * p
Friends
class TemplateNodeBlock
class TemplateNodeCreate
Detailed Description
Engine to create templates and template contexts.
Definition at line 559 of file template.h.
Constructor & Destructor Documentation
TemplateEngine()
TemplateEngine::TemplateEngine ()
Create a template engine.
Definition at line 5194 of file template.cpp.
References p, and Private.
~TemplateEngine()
TemplateEngine::~TemplateEngine ()
Destroys the template engine.
Definition at line 5199 of file template.cpp.
References p.
Member Function Documentation
createContext()
TemplateContext * TemplateEngine::createContext () const
Creates a new context that can be using to render a template.
See also
Template::render()
Definition at line 5204 of file template.cpp.
Referenced by generateOutputViaTemplate().
destroyContext()
void TemplateEngine::destroyContext (TemplateContext * ctx)
Destroys a context created via createContext().
Parameters
[in] ctx The context.
Definition at line 5209 of file template.cpp.
Referenced by generateOutputViaTemplate().
enterBlock()
void TemplateEngine::enterBlock (const QCString & fileName, const QCString & blockName, int line) private
Definition at line 5224 of file template.cpp.
References TemplateEngine::Private::enterBlock(), and p.
Referenced by TemplateNodeBlock::render().
leaveBlock()
void TemplateEngine::leaveBlock () private
Definition at line 5229 of file template.cpp.
References TemplateEngine::Private::leaveBlock(), and p.
Referenced by TemplateNodeBlock::render().
loadByName()
Template * TemplateEngine::loadByName (const QCString & fileName, int fromLine)
Creates a new template whose contents are in a file.
Parameters
[in] fileName The name of the file containing the template data
[in] fromLine The line number of the statement that triggered the load
Returns
the new template, the engine will keep ownership of the object.
Definition at line 5214 of file template.cpp.
References TemplateEngine::Private::loadByName(), and p.
Referenced by generateOutputViaTemplate(), TemplateNodeExtend::render(), TemplateNodeInclude::render(), and TemplateNodeCreate::render().
outputExtension()
QCString TemplateEngine::outputExtension () const private
Returns the output extension, set via setOutputExtension()
Definition at line 5244 of file template.cpp.
References TemplateEngine::Private::outputExtension(), and p.
printIncludeContext()
void TemplateEngine::printIncludeContext (const char * fileName, int line) const
Prints the current template file include stack.
Definition at line 5234 of file template.cpp.
References p, and TemplateEngine::Private::printIncludeContext().
Referenced by TemplateLexer::tokenize(), TemplateContextImpl::warn(), and TemplateParser::warn().
setOutputExtension()
void TemplateEngine::setOutputExtension (const char * extension) private
Sets the extension of the output file.
This is used to control the format of 'special' tags in the template
Definition at line 5239 of file template.cpp.
References p, and TemplateEngine::Private::setOutputExtension().
Referenced by TemplateNodeCreate::render().
setTemplateDir()
void TemplateEngine::setTemplateDir (const char * dirName)
Sets the search directory where to look for template files.
Definition at line 5249 of file template.cpp.
References p, and TemplateEngine::Private::setTemplateDir().
Referenced by generateOutputViaTemplate().
unload()
void TemplateEngine::unload (Template * t)
Indicates that template t is no longer needed.
The engine may decide to delete it.
Definition at line 5219 of file template.cpp.
References p, and TemplateEngine::Private::unload().
Referenced by generateOutputViaTemplate(), TemplateNodeExtend::render(), TemplateNodeInclude::render(), and TemplateNodeCreate::render().
Friends And Related Function Documentation
TemplateNodeBlock
friend class TemplateNodeBlock friend
Definition at line 597 of file template.h.
TemplateNodeCreate
friend class TemplateNodeCreate friend
Definition at line 598 of file template.h.
Member Data Documentation
p
Private* TemplateEngine::p private
Definition at line 611 of file template.h.
Referenced by enterBlock(), leaveBlock(), loadByName(), outputExtension(), printIncludeContext(), setOutputExtension(), setTemplateDir(), TemplateEngine(), unload(), and ~TemplateEngine().
The documentation for this class was generated from the following files:
src/template.h
src/template.cpp