Doxygen: DotNode Class Reference
DotNode Class Reference
A node in a dot graph.
#include <dot.h>
Public Types
enum GraphType {
Dependency, Inheritance, Collaboration, Hierarchy,
CallGraph
}
enum TruncState { Unknown, Truncated, Untruncated }
Public Member Functions
DotNode (int n, const char *lab, const char *tip, const char *url, bool rootNode=FALSE, ClassDef *cd=0)
~DotNode ()
void addChild (DotNode *n, int edgeColor=EdgeInfo::Purple, int edgeStyle=EdgeInfo::Solid, const char *edgeLab=0, const char *edgeURL=0, int edgeLabCol=-1)
void addParent (DotNode *n)
void deleteNode (DotNodeList &deletedList, SDict< DotNode > *skipNodes=0)
void removeChild (DotNode *n)
void removeParent (DotNode *n)
int findParent (DotNode *n)
void write (FTextStream &t, GraphType gt, GraphOutputFormat f, bool topDown, bool toChildren, bool backArrows)
void clearWriteFlag ()
void writeXML (FTextStream &t, bool isClassGraph)
void writeDocbook (FTextStream &t, bool isClassGraph)
void writeDEF (FTextStream &t)
QCString label () const
int number () const
bool isVisible () const
TruncState isTruncated () const
int distance () const
void renumberNodes (int &number)
Public Attributes
int m_subgraphId
Private Member Functions
void colorConnectedNodes (int curColor)
void writeBox (FTextStream &t, GraphType gt, GraphOutputFormat f, bool hasNonReachableChildren)
void writeArrow (FTextStream &t, GraphType gt, GraphOutputFormat f, DotNode *cn, EdgeInfo *ei, bool topDown, bool pointBack=TRUE)
void setDistance (int distance)
const DotNode * findDocNode () const
void markAsVisible (bool b=TRUE)
void markAsTruncated (bool b=TRUE)
Private Attributes
int m_number
QCString m_label
label text
QCString m_tooltip
node's tooltip
QCString m_url
url of the node (format: remote$local)
QList< DotNode > * m_parents
list of parent nodes (incoming arrows)
QList< DotNode > * m_children
list of child nodes (outgoing arrows)
QList< EdgeInfo > * m_edgeInfo
edge info for each child
bool m_deleted
used to mark a node as deleted
bool m_written
used to mark a node as written
bool m_hasDoc
used to mark a node as documented
bool m_isRoot
indicates if this is a root node
ClassDef * m_classDef
class representing this node (can be 0)
bool m_visible
is the node visible in the output
TruncState m_truncated
does the node have non-visible children/parents
int m_distance
shortest path to the root node
Friends
class DotGfxHierarchyTable
class DotClassGraph
class DotInclDepGraph
class DotNodeList
class DotCallGraph
class DotGroupCollaboration
class DotInheritanceGraph
QCString computeMd5Signature (DotNode *root, GraphType gt, GraphOutputFormat f, bool lrRank, bool renderParents, bool backArrows, const QCString &title, QCString &graphStr)
Detailed Description
A node in a dot graph.
Definition at line 60 of file dot.h.
Member Enumeration Documentation
GraphType
enum DotNode::GraphType
Enumerator
Dependency
Inheritance
Collaboration
Hierarchy
CallGraph
Definition at line 63 of file dot.h.
TruncState
enum DotNode::TruncState
Enumerator
Unknown
Truncated
Untruncated
Definition at line 64 of file dot.h.
Constructor & Destructor Documentation
DotNode()
DotNode::DotNode (int n, const char * lab, const char * tip, const char * url, bool rootNode = FALSE, ClassDef * cd = 0)
Definition at line 1410 of file dot.cpp.
~DotNode()
DotNode::~DotNode ()
Definition at line 1431 of file dot.cpp.
References m_children, m_edgeInfo, and m_parents.
Member Function Documentation
addChild()
void DotNode::addChild (DotNode * n, int edgeColor = EdgeInfo::Purple, int edgeStyle = EdgeInfo::Solid, const char * edgeLab = 0, const char * edgeURL = 0, int edgeLabCol = -1)
Definition at line 1438 of file dot.cpp.
References m_children, EdgeInfo::m_color, m_edgeInfo, EdgeInfo::m_labColor, EdgeInfo::m_label, EdgeInfo::m_style, and EdgeInfo::m_url.
Referenced by DotClassGraph::addClass(), DotGfxHierarchyTable::addHierarchy(), DotInclDepGraph::buildGraph(), and DotCallGraph::buildGraph().
addParent()
void DotNode::addParent (DotNode * n)
Definition at line 1465 of file dot.cpp.
References m_parents.
Referenced by DotClassGraph::addClass(), DotGfxHierarchyTable::addHierarchy(), DotInclDepGraph::buildGraph(), and DotCallGraph::buildGraph().
clearWriteFlag()
void DotNode::clearWriteFlag ()
Definition at line 2123 of file dot.cpp.
References clearWriteFlag(), m_children, m_parents, and m_written.
Referenced by clearWriteFlag(), computeMd5Signature(), DotGfxHierarchyTable::createGraph(), and DotGroupCollaboration::writeGraph().
colorConnectedNodes()
void DotNode::colorConnectedNodes (int curColor) private
Definition at line 2152 of file dot.cpp.
References colorConnectedNodes(), m_children, m_parents, m_subgraphId, and markAsVisible().
Referenced by colorConnectedNodes(), and DotGfxHierarchyTable::DotGfxHierarchyTable().
deleteNode()
void DotNode::deleteNode (DotNodeList & deletedList, SDict< DotNode > * skipNodes = 0)
Definition at line 1484 of file dot.cpp.
References deleteNode(), SDict< T >::find(), m_children, m_deleted, and m_parents.
Referenced by deleteNode(), and deleteNodes().
distance()
int DotNode::distance () const inline
Definition at line 91 of file dot.h.
References m_distance.
Referenced by DotClassGraph::determineVisibleNodes(), DotInclDepGraph::determineVisibleNodes(), DotCallGraph::determineVisibleNodes(), and setDistance().
findDocNode()
const DotNode * DotNode::findDocNode () const private
Definition at line 2201 of file dot.cpp.
References findDocNode(), m_children, m_hasDoc, m_parents, and m_url.
Referenced by DotGfxHierarchyTable::DotGfxHierarchyTable(), and findDocNode().
findParent()
int DotNode::findParent (DotNode * n) inline
Definition at line 736 of file dot.cpp.
References m_parents.
isTruncated()
TruncState DotNode::isTruncated () const inline
Definition at line 90 of file dot.h.
References m_truncated.
Referenced by DotClassGraph::determineTruncatedNodes(), DotInclDepGraph::determineTruncatedNodes(), and DotCallGraph::determineTruncatedNodes().
isVisible()
bool DotNode::isVisible () const inline
Definition at line 89 of file dot.h.
References m_visible.
Referenced by computeMd5Signature(), DotClassGraph::determineTruncatedNodes(), DotInclDepGraph::determineTruncatedNodes(), DotCallGraph::determineTruncatedNodes(), DotClassGraph::determineVisibleNodes(), DotInclDepGraph::determineVisibleNodes(), DotCallGraph::determineVisibleNodes(), and write().
label()
QCString DotNode::label () const inline
Definition at line 87 of file dot.h.
References m_label.
Referenced by DotClassGraph::determineVisibleNodes(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), and DotGroupCollaboration::writeGraph().
markAsTruncated()
void DotNode::markAsTruncated (bool b = TRUE) inline private
Definition at line 103 of file dot.h.
References m_truncated, Truncated, and Untruncated.
Referenced by DotClassGraph::determineTruncatedNodes(), DotInclDepGraph::determineTruncatedNodes(), and DotCallGraph::determineTruncatedNodes().
markAsVisible()
void DotNode::markAsVisible (bool b = TRUE) inline private
Definition at line 102 of file dot.h.
References m_visible.
Referenced by DotGroupCollaboration::addCollaborationMember(), DotGroupCollaboration::buildGraph(), colorConnectedNodes(), DotClassGraph::determineVisibleNodes(), DotInclDepGraph::determineVisibleNodes(), DotCallGraph::determineVisibleNodes(), DotGfxHierarchyTable::DotGfxHierarchyTable(), and DotGroupCollaboration::DotGroupCollaboration().
number()
int DotNode::number () const inline
Definition at line 88 of file dot.h.
References m_number.
Referenced by DotGroupCollaboration::Edge::write(), and writeArrow().
removeChild()
void DotNode::removeChild (DotNode * n)
Definition at line 1474 of file dot.cpp.
References m_children.
removeParent()
void DotNode::removeParent (DotNode * n)
Definition at line 1479 of file dot.cpp.
References m_parents.
renumberNodes()
void DotNode::renumberNodes (int & number)
Definition at line 2187 of file dot.cpp.
References m_children, m_number, and renumberNodes().
Referenced by DotGfxHierarchyTable::DotGfxHierarchyTable(), and renumberNodes().
setDistance()
void DotNode::setDistance (int distance) private
Definition at line 1517 of file dot.cpp.
References distance(), and m_distance.
Referenced by DotClassGraph::addClass(), DotInclDepGraph::buildGraph(), DotCallGraph::buildGraph(), DotCallGraph::DotCallGraph(), DotClassGraph::DotClassGraph(), and DotInclDepGraph::DotInclDepGraph().
write()
void DotNode::write (FTextStream & t, GraphType gt, GraphOutputFormat f, bool topDown, bool toChildren, bool backArrows)
Definition at line 1863 of file dot.cpp.
References isVisible(), m_children, m_edgeInfo, m_parents, m_truncated, m_visible, m_written, Truncated, write(), writeArrow(), and writeBox().
Referenced by computeMd5Signature(), DotGfxHierarchyTable::createGraph(), write(), and DotGroupCollaboration::writeGraph().
writeArrow()
void DotNode::writeArrow (FTextStream & t, GraphType gt, GraphOutputFormat f, DotNode * cn, EdgeInfo * ei, bool topDown, bool pointBack = TRUE) private
Definition at line 1812 of file dot.cpp.
References EdgeProperties::arrowStyleMap, Collaboration, Config_getBool, convertLabel(), EdgeProperties::edgeColorMap, EdgeProperties::edgeStyleMap, endl(), FONTNAME, FONTSIZE, GOF_BITMAP, Inheritance, EdgeInfo::m_color, EdgeInfo::m_label, m_number, EdgeInfo::m_style, normalEdgeProps, number(), and umlEdgeProps.
Referenced by computeMd5Signature(), and write().
writeBox()
void DotNode::writeBox (FTextStream & t, GraphType gt, GraphOutputFormat f, bool hasNonReachableChildren) private
Definition at line 1680 of file dot.cpp.
References Collaboration, Config_getBool, convertLabel(), endl(), escapeTooltip(), Definition::getLanguage(), ClassDef::getMemberGroupSDict(), ClassDef::getMemberList(), Doxygen::htmlFileExtension, Inheritance, SIntDict< MemberGroup >::Iterator, m_classDef, m_edgeInfo, m_isRoot, EdgeInfo::m_label, m_label, m_number, m_tooltip, m_url, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, SrcLangExt_Fortran, stripProtectionPrefix(), and writeBoxMemberList().
Referenced by write().
writeDEF()
void DotNode::writeDEF (FTextStream & t)
Definition at line 2058 of file dot.cpp.
References EdgeInfo::Blue, endl(), EdgeInfo::Green, EdgeInfo::Grey, m_children, EdgeInfo::m_color, m_edgeInfo, EdgeInfo::m_label, m_label, m_number, m_url, EdgeInfo::Orange, EdgeInfo::Orange2, EdgeInfo::Purple, and EdgeInfo::Red.
Referenced by DotClassGraph::writeDEF().
writeDocbook()
void DotNode::writeDocbook (FTextStream & t, bool isClassGraph)
Definition at line 1988 of file dot.cpp.
References EdgeInfo::Blue, convertToXML(), endl(), EdgeInfo::Green, EdgeInfo::Grey, m_children, EdgeInfo::m_color, m_edgeInfo, EdgeInfo::m_label, m_label, m_number, m_url, EdgeInfo::Orange, EdgeInfo::Orange2, EdgeInfo::Purple, and EdgeInfo::Red.
Referenced by DotClassGraph::writeDocbook(), and DotInclDepGraph::writeDocbook().
writeXML()
void DotNode::writeXML (FTextStream & t, bool isClassGraph)
Definition at line 1919 of file dot.cpp.
References EdgeInfo::Blue, convertToXML(), endl(), EdgeInfo::Green, EdgeInfo::Grey, m_children, EdgeInfo::m_color, m_edgeInfo, EdgeInfo::m_label, m_label, m_number, m_url, EdgeInfo::Orange, EdgeInfo::Orange2, EdgeInfo::Purple, and EdgeInfo::Red.
Referenced by DotClassGraph::writeXML(), and DotInclDepGraph::writeXML().
Friends And Related Function Documentation
computeMd5Signature
QCString computeMd5Signature (DotNode * root, DotNode::GraphType gt, GraphOutputFormat f, bool lrRank, bool renderParents, bool backArrows, const QCString & title, QCString & graphStr) friend
Computes a 16 byte md5 checksum for a given dot graph. The md5 checksum is returned as a 32 character ASCII string.
Definition at line 2990 of file dot.cpp.
DotCallGraph
friend class DotCallGraph friend
Definition at line 124 of file dot.h.
DotClassGraph
friend class DotClassGraph friend
Definition at line 121 of file dot.h.
DotGfxHierarchyTable
friend class DotGfxHierarchyTable friend
Definition at line 120 of file dot.h.
DotGroupCollaboration
friend class DotGroupCollaboration friend
Definition at line 125 of file dot.h.
DotInclDepGraph
friend class DotInclDepGraph friend
Definition at line 122 of file dot.h.
DotInheritanceGraph
friend class DotInheritanceGraph friend
Definition at line 126 of file dot.h.
DotNodeList
friend class DotNodeList friend
Definition at line 123 of file dot.h.
Member Data Documentation
m_children
QList<DotNode>* DotNode::m_children private
list of child nodes (outgoing arrows)
Definition at line 109 of file dot.h.
Referenced by addChild(), DotGfxHierarchyTable::addHierarchy(), clearWriteFlag(), colorConnectedNodes(), computeMd5Signature(), deleteNode(), DotClassGraph::determineTruncatedNodes(), DotInclDepGraph::determineTruncatedNodes(), DotCallGraph::determineTruncatedNodes(), DotClassGraph::determineVisibleNodes(), DotInclDepGraph::determineVisibleNodes(), DotCallGraph::determineVisibleNodes(), findDocNode(), DotClassGraph::isTooBig(), DotInclDepGraph::isTooBig(), DotCallGraph::isTooBig(), DotClassGraph::isTrivial(), DotInclDepGraph::isTrivial(), DotCallGraph::isTrivial(), removeChild(), renumberNodes(), write(), writeDEF(), writeDocbook(), writeXML(), and ~DotNode().
m_classDef
ClassDef* DotNode::m_classDef private
class representing this node (can be 0)
Definition at line 115 of file dot.h.
Referenced by writeBox().
m_deleted
bool DotNode::m_deleted private
used to mark a node as deleted
Definition at line 111 of file dot.h.
Referenced by deleteNode().
m_distance
int DotNode::m_distance private
shortest path to the root node
Definition at line 118 of file dot.h.
Referenced by distance(), and setDistance().
m_edgeInfo
QList<EdgeInfo>* DotNode::m_edgeInfo private
edge info for each child
Definition at line 110 of file dot.h.
Referenced by addChild(), computeMd5Signature(), write(), writeBox(), writeDEF(), writeDocbook(), writeXML(), and ~DotNode().
m_hasDoc
bool DotNode::m_hasDoc private
used to mark a node as documented
Definition at line 113 of file dot.h.
Referenced by findDocNode().
m_isRoot
bool DotNode::m_isRoot private
indicates if this is a root node
Definition at line 114 of file dot.h.
Referenced by writeBox().
m_label
QCString DotNode::m_label private
label text
Definition at line 105 of file dot.h.
Referenced by DotNodeList::compareValues(), DotGfxHierarchyTable::createGraph(), label(), writeBox(), writeDEF(), writeDocbook(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), and writeXML().
m_number
int DotNode::m_number private
Definition at line 104 of file dot.h.
Referenced by number(), renumberNodes(), writeArrow(), writeBox(), writeDEF(), writeDocbook(), and writeXML().
m_parents
QList<DotNode>* DotNode::m_parents private
list of parent nodes (incoming arrows)
Definition at line 108 of file dot.h.
Referenced by addParent(), clearWriteFlag(), colorConnectedNodes(), computeMd5Signature(), deleteNode(), DotClassGraph::determineTruncatedNodes(), DotClassGraph::determineVisibleNodes(), findDocNode(), findParent(), DotClassGraph::isTooBig(), DotClassGraph::isTrivial(), removeParent(), write(), and ~DotNode().
m_subgraphId
int DotNode::m_subgraphId
Definition at line 82 of file dot.h.
Referenced by colorConnectedNodes(), DotGfxHierarchyTable::createGraph(), and DotGfxHierarchyTable::DotGfxHierarchyTable().
m_tooltip
QCString DotNode::m_tooltip private
node's tooltip
Definition at line 106 of file dot.h.
Referenced by writeBox().
m_truncated
TruncState DotNode::m_truncated private
does the node have non-visible children/parents
Definition at line 117 of file dot.h.
Referenced by isTruncated(), markAsTruncated(), and write().
m_url
QCString DotNode::m_url private
url of the node (format: remote$local)
Definition at line 107 of file dot.h.
Referenced by findDocNode(), writeBox(), writeDEF(), writeDocbook(), and writeXML().
m_visible
bool DotNode::m_visible private
is the node visible in the output
Definition at line 116 of file dot.h.
Referenced by isVisible(), markAsVisible(), and write().
m_written
bool DotNode::m_written private
used to mark a node as written
Definition at line 112 of file dot.h.
Referenced by clearWriteFlag(), and write().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp