Doxygen: src/plantuml.cpp File Reference
plantuml.cpp File Reference
#include "plantuml.h"
#include "portable.h"
#include "config.h"
#include "doxygen.h"
#include "index.h"
#include "message.h"
#include <qdir.h>
Functions
QCString writePlantUMLSource (const QCString &outDir, const QCString &fileName, const QCString &content)
Write a PlantUML compatible file.
void generatePlantUMLOutput (const char *baseName, const char *outDir, PlantUMLOutputFormat format)
Convert a PlantUML file to an image.
Variables
static const int maxCmdLine = 40960
Function Documentation
generatePlantUMLOutput()
void generatePlantUMLOutput (const char * baseName, const char * outDir, PlantUMLOutputFormat format)
Convert a PlantUML file to an image.
Parameters
[in] baseName the name of the generated file (as returned by writePlantUMLSource())
[in] outDir the directory to write the resulting image into.
[in] format the image format to generate.
Definition at line 56 of file plantuml.cpp.
References IndexList::addImageFile(), Config_getBool, Config_getList, Config_getString, err(), Doxygen::indexList, maxCmdLine, msg(), portable_pathListSeparator(), portable_system(), portable_sysTimerStart(), portable_sysTimerStop(), PUML_BITMAP, PUML_EPS, and PUML_SVG.
Referenced by FlowChart::printUmlTree(), HtmlDocVisitor::writePlantUMLFile(), DocbookDocVisitor::writePlantUMLFile(), RTFDocVisitor::writePlantUMLFile(), and LatexDocVisitor::writePlantUMLFile().
writePlantUMLSource()
QCString writePlantUMLSource (const QCString & outDir, const QCString & fileName, const QCString & content)
Write a PlantUML compatible file.
Parameters
[in] outDir the output directory to write the file to.
[in] fileName the name of the file. If empty a name will be chosen automatically.
[in] content the contents of the PlantUML file.
Returns
The name of the generated file.
Definition at line 27 of file plantuml.cpp.
References err().
Referenced by FlowChart::printUmlTree(), DocbookDocVisitor::visit(), RTFDocVisitor::visit(), LatexDocVisitor::visit(), and HtmlDocVisitor::visit().
Variable Documentation
maxCmdLine
const int maxCmdLine = 40960 static
Definition at line 25 of file plantuml.cpp.
Referenced by generatePlantUMLOutput().