Doxygen: SearchIndexContext Class Reference
SearchIndexContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static SearchIndexContext * alloc (const SearchIndexInfo *info)
Private Member Functions
SearchIndexContext (const SearchIndexInfo *info)
~SearchIndexContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1308 of file context.h.
Constructor & Destructor Documentation
SearchIndexContext()
SearchIndexContext::SearchIndexContext (const SearchIndexInfo * info) private
Definition at line 9899 of file context.cpp.
References p, and Private.
Referenced by alloc().
~SearchIndexContext()
SearchIndexContext::~SearchIndexContext () private
Definition at line 9905 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int SearchIndexContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 1316 of file context.h.
References RefCountedContext::addRef().
alloc()
static SearchIndexContext* SearchIndexContext::alloc (const SearchIndexInfo * info) inline static
Definition at line 1311 of file context.h.
References SearchIndexContext().
Referenced by SearchIndicesContext::Private::Private().
get()
TemplateVariant SearchIndexContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 9910 of file context.cpp.
References SearchIndexContext::Private::get(), and p.
release()
virtual int SearchIndexContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 1317 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* SearchIndexContext::p private
Definition at line 1322 of file context.h.
Referenced by get(), SearchIndexContext(), and ~SearchIndexContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp