Doxygen: DiagramRow Class Reference
DiagramRow Class Reference
Class representing a row in the built-in class diagram.
Public Member Functions
DiagramRow (TreeDiagram *d, int l)
void insertClass (DiagramItem *parent, ClassDef *cd, bool doBases, Protection prot, Specifier virt, const char *ts)
uint number ()
Private Attributes
TreeDiagram * diagram
uint level
Detailed Description
Class representing a row in the built-in class diagram.
Definition at line 85 of file diagram.cpp.
Constructor & Destructor Documentation
DiagramRow()
DiagramRow::DiagramRow (TreeDiagram * d, int l) inline
Definition at line 88 of file diagram.cpp.
References diagram, and level.
Referenced by insertClass().
Member Function Documentation
insertClass()
void DiagramRow::insertClass (DiagramItem * parent, ClassDef * cd, bool doBases, Protection prot, Specifier virt, const char * ts)
Definition at line 357 of file diagram.cpp.
References DiagramItem::addChild(), ClassDef::baseClasses(), BaseClassDef::classDef, diagram, DiagramRow(), gridHeight, gridWidth, insertClass(), ClassDef::isVisibleInHierarchy(), level, DiagramItem::move(), Normal, Private, BaseClassDef::prot, ClassDef::subClasses(), BaseClassDef::templSpecifiers, and BaseClassDef::virt.
Referenced by insertClass(), and TreeDiagram::TreeDiagram().
number()
uint DiagramRow::number () inline
Definition at line 96 of file diagram.cpp.
References level.
Member Data Documentation
diagram
TreeDiagram* DiagramRow::diagram private
Definition at line 98 of file diagram.cpp.
Referenced by DiagramRow(), and insertClass().
level
uint DiagramRow::level private
Definition at line 99 of file diagram.cpp.
Referenced by DiagramRow(), insertClass(), and number().
The documentation for this class was generated from the following file:
src/diagram.cpp