Doxygen: LayoutParser Class Reference
LayoutParser Class Reference
Classes
class EndElementHandler
class StartElementHandler
class StartElementHandlerKind
class StartElementHandlerMember
class StartElementHandlerNavEntry
class StartElementHandlerSection
Public Member Functions
void init ()
void startSimpleEntry (LayoutDocEntry::Kind k, const QXmlAttributes &attrib)
void startSectionEntry (LayoutDocEntry::Kind k, const QXmlAttributes &attrib, const QCString &title)
void startMemberDeclEntry (const QXmlAttributes &attrib, MemberListType type, const QCString &title, const QCString &subscript)
void startMemberDefEntry (const QXmlAttributes &attrib, MemberListType type, const QCString &title, const QCString &)
void startLayout (const QXmlAttributes &)
void endLayout ()
void startNavIndex (const QXmlAttributes &)
void endNavIndex ()
void startNavEntry (const QXmlAttributes &attrib)
void endNavEntry ()
void startClass (const QXmlAttributes &)
void endClass ()
void startNamespace (const QXmlAttributes &)
void endNamespace ()
void startFile (const QXmlAttributes &)
void endFile ()
void startGroup (const QXmlAttributes &)
void endGroup ()
void startDirectory (const QXmlAttributes &)
void endDirectory ()
void startMemberDef (const QXmlAttributes &)
void endMemberDef ()
void startMemberDecl (const QXmlAttributes &)
void endMemberDecl ()
bool startElement (const QString &, const QString &, const QString &name, const QXmlAttributes &attrib)
bool endElement (const QString &, const QString &, const QString &name)
bool startDocument ()
Static Public Member Functions
static LayoutParser & instance ()
Private Member Functions
LayoutParser ()
~LayoutParser ()
Private Attributes
QDict< StartElementHandler > m_sHandler
QDict< EndElementHandler > m_eHandler
QCString m_scope
int m_part
LayoutNavEntry * m_rootNav
bool m_invalidEntry
Static Private Attributes
static int m_userGroupCount =0
Detailed Description
Definition at line 132 of file layout.cpp.
Constructor & Destructor Documentation
LayoutParser()
LayoutParser::LayoutParser () inline private
Definition at line 1271 of file layout.cpp.
Referenced by instance().
~LayoutParser()
LayoutParser::~LayoutParser () inline private
Definition at line 1272 of file layout.cpp.
References m_rootNav.
Member Function Documentation
endClass()
void LayoutParser::endClass () inline
Definition at line 1124 of file layout.cpp.
References m_part, and m_scope.
Referenced by init().
endDirectory()
void LayoutParser::endDirectory () inline
Definition at line 1176 of file layout.cpp.
References m_part, and m_scope.
Referenced by init().
endElement()
bool LayoutParser::endElement (const QString & , const QString & , const QString & name) inline
Definition at line 1247 of file layout.cpp.
References m_eHandler, and m_scope.
endFile()
void LayoutParser::endFile () inline
Definition at line 1150 of file layout.cpp.
References m_part, and m_scope.
Referenced by init().
endGroup()
void LayoutParser::endGroup () inline
Definition at line 1163 of file layout.cpp.
References m_part, and m_scope.
Referenced by init().
endLayout()
void LayoutParser::endLayout () inline
Definition at line 872 of file layout.cpp.
Referenced by init().
endMemberDecl()
void LayoutParser::endMemberDecl () inline
Definition at line 1216 of file layout.cpp.
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, m_scope, and LayoutDocEntry::MemberDeclEnd.
Referenced by init().
endMemberDef()
void LayoutParser::endMemberDef () inline
Definition at line 1192 of file layout.cpp.
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, m_scope, and LayoutDocEntry::MemberDefEnd.
Referenced by init().
endNamespace()
void LayoutParser::endNamespace () inline
Definition at line 1137 of file layout.cpp.
References m_part, and m_scope.
Referenced by init().
endNavEntry()
void LayoutParser::endNavEntry () inline
Definition at line 1110 of file layout.cpp.
References m_invalidEntry, m_rootNav, and LayoutNavEntry::parent().
Referenced by init().
endNavIndex()
void LayoutParser::endNavIndex () inline
Definition at line 883 of file layout.cpp.
References LayoutNavEntry::find(), m_rootNav, m_scope, LayoutNavEntry::MainPage, theTranslator, and Translator::trMainPage().
Referenced by init().
init()
void LayoutParser::init () inline
Definition at line 258 of file layout.cpp.
References LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, COMPILE_FOR_1_OPTION, COMPILE_FOR_2_OPTIONS, COMPILE_FOR_3_OPTIONS, COMPILE_FOR_4_OPTIONS, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, endClass(), endDirectory(), endFile(), endGroup(), endLayout(), endMemberDecl(), endMemberDef(), endNamespace(), endNavEntry(), endNavIndex(), VhdlDocGen::ENTITY, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, m_eHandler, m_part, m_rootNav, m_sHandler, LayoutDocEntry::MemberGroups, MemberListType_constructors, MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decEnumValMembers, MemberListType_decEventMembers, MemberListType_decFriendMembers, MemberListType_decFuncMembers, MemberListType_decPriSlotMembers, MemberListType_decPropMembers, MemberListType_decProSlotMembers, MemberListType_decPubSlotMembers, MemberListType_decSignalMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docEnumMembers, MemberListType_docEnumValMembers, MemberListType_docEventMembers, MemberListType_docFriendMembers, MemberListType_docFuncMembers, MemberListType_docPriSlotMembers, MemberListType_docPropMembers, MemberListType_docProSlotMembers, MemberListType_docPubSlotMembers, MemberListType_docSignalMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberListType_enumMembers, MemberListType_eventMembers, MemberListType_events, MemberListType_friends, MemberListType_functionMembers, MemberListType_interfaceMembers, MemberListType_interfaces, MemberListType_pacAttribs, MemberListType_pacMethods, MemberListType_pacStaticAttribs, MemberListType_pacStaticMethods, MemberListType_pacTypes, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_propertyMembers, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_relatedMembers, MemberListType_serviceMembers, MemberListType_services, MemberListType_signals, MemberListType_typedefMembers, MemberListType_variableMembers, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, SrcLangExt_Fortran, SrcLangExt_IDL, SrcLangExt_Java, SrcLangExt_ObjC, SrcLangExt_VHDL, startClass(), startDirectory(), startFile(), startGroup(), startLayout(), startMemberDecl(), startMemberDeclEntry(), startMemberDef(), startMemberDefEntry(), startNamespace(), startNavEntry(), startNavIndex(), startSectionEntry(), startSimpleEntry(), theTranslator, Translator::trClassDocumentation(), Translator::trClassMethods(), Translator::trCompounds(), Translator::trConstantGroups(), Translator::trConstructorDocumentation(), Translator::trDataTypes(), Translator::trDefineDocumentation(), Translator::trDefines(), Translator::trDetailedDescription(), Translator::trDirectories(), Translator::trEnumerations(), Translator::trEnumerationTypeDocumentation(), Translator::trEnumerationValueDocumentation(), Translator::trEnumerationValues(), Translator::trEventDocumentation(), Translator::trEvents(), Translator::trFile(), Translator::trFriends(), VhdlDocGen::trFunctionAndProc(), Translator::trFunctionDocumentation(), Translator::trFunctions(), Translator::trInstanceMethods(), Translator::trInterfaces(), Translator::trMemberDataDocumentation(), Translator::trMemberEnumerationDocumentation(), Translator::trMemberFunctionDocumentation(), Translator::trMemberFunctionDocumentationFortran(), Translator::trMemberTypedefDocumentation(), Translator::trMethodDocumentation(), Translator::trModules(), Translator::trNamespaces(), Translator::trPackageAttribs(), Translator::trPackageMembers(), Translator::trPackages(), Translator::trPackageTypes(), Translator::trPrivateAttribs(), Translator::trPrivateMembers(), Translator::trPrivateSlots(), Translator::trPrivateTypes(), Translator::trProperties(), Translator::trPropertyDocumentation(), Translator::trProtectedAttribs(), Translator::trProtectedMembers(), Translator::trProtectedSlots(), Translator::trProtectedTypes(), Translator::trPublicAttribs(), Translator::trPublicMembers(), Translator::trPublicSlots(), Translator::trPublicTypes(), Translator::trRelatedFunctionDocumentation(), Translator::trRelatedFunctions(), Translator::trRelatedSubscript(), Translator::trServices(), Translator::trSignals(), Translator::trStaticPackageAttribs(), Translator::trStaticPackageMembers(), Translator::trStaticPrivateAttribs(), Translator::trStaticPrivateMembers(), Translator::trStaticProtectedAttribs(), Translator::trStaticProtectedMembers(), Translator::trStaticPublicAttribs(), Translator::trStaticPublicMembers(), Translator::trSubprogramDocumentation(), Translator::trSubprograms(), Translator::trTypedefDocumentation(), Translator::trTypedefs(), Translator::trTypeDocumentation(), Translator::trVariableDocumentation(), Translator::trVariables(), and VhdlDocGen::trVhdlType().
Referenced by LayoutDocManager::LayoutDocManager().
instance()
static LayoutParser& LayoutParser::instance () inline static
Definition at line 253 of file layout.cpp.
References LayoutParser().
Referenced by LayoutDocManager::init(), LayoutDocManager::LayoutDocManager(), and LayoutDocManager::parse().
startClass()
void LayoutParser::startClass (const QXmlAttributes &) inline
Definition at line 1117 of file layout.cpp.
References LayoutDocManager::Class, LayoutDocManager::clear(), LayoutDocManager::instance(), m_part, and m_scope.
Referenced by init().
startDirectory()
void LayoutParser::startDirectory (const QXmlAttributes &) inline
Definition at line 1169 of file layout.cpp.
References LayoutDocManager::clear(), LayoutDocManager::Directory, LayoutDocManager::instance(), m_part, and m_scope.
Referenced by init().
startDocument()
bool LayoutParser::startDocument () inline
Definition at line 1265 of file layout.cpp.
startElement()
bool LayoutParser::startElement (const QString & , const QString & , const QString & name, const QXmlAttributes & attrib) inline
Definition at line 1231 of file layout.cpp.
References err(), m_scope, and m_sHandler.
startFile()
void LayoutParser::startFile (const QXmlAttributes &) inline
Definition at line 1143 of file layout.cpp.
References LayoutDocManager::clear(), LayoutDocManager::File, LayoutDocManager::instance(), m_part, and m_scope.
Referenced by init().
startGroup()
void LayoutParser::startGroup (const QXmlAttributes &) inline
Definition at line 1156 of file layout.cpp.
References LayoutDocManager::clear(), LayoutDocManager::Group, LayoutDocManager::instance(), m_part, and m_scope.
Referenced by init().
startLayout()
void LayoutParser::startLayout (const QXmlAttributes &) inline
Definition at line 868 of file layout.cpp.
Referenced by init().
startMemberDecl()
void LayoutParser::startMemberDecl (const QXmlAttributes &) inline
Definition at line 1206 of file layout.cpp.
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, m_scope, and LayoutDocEntry::MemberDeclStart.
Referenced by init().
startMemberDeclEntry()
void LayoutParser::startMemberDeclEntry (const QXmlAttributes & attrib, MemberListType type, const QCString & title, const QCString & subscript) inline
Definition at line 838 of file layout.cpp.
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), and m_part.
Referenced by init().
startMemberDef()
void LayoutParser::startMemberDef (const QXmlAttributes &) inline
Definition at line 1182 of file layout.cpp.
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), m_part, m_scope, and LayoutDocEntry::MemberDefStart.
Referenced by init().
startMemberDefEntry()
void LayoutParser::startMemberDefEntry (const QXmlAttributes & attrib, MemberListType type, const QCString & title, const QCString &) inline
Definition at line 855 of file layout.cpp.
References LayoutDocManager::addEntry(), LayoutDocManager::instance(), and m_part.
Referenced by init().
startNamespace()
void LayoutParser::startNamespace (const QXmlAttributes &) inline
Definition at line 1130 of file layout.cpp.
References LayoutDocManager::clear(), LayoutDocManager::instance(), m_part, m_scope, and LayoutDocManager::Namespace.
Referenced by init().
startNavEntry()
void LayoutParser::startNavEntry (const QXmlAttributes & attrib) inline
Definition at line 895 of file layout.cpp.
References LayoutNavEntry::Classes, LayoutNavEntry::ClassHierarchy, LayoutNavEntry::ClassIndex, LayoutNavEntry::ClassList, LayoutNavEntry::ClassMembers, Config_getBool, elemIsVisible(), err(), LayoutNavEntry::Examples, LayoutNavEntry::FileGlobals, LayoutNavEntry::FileList, LayoutNavEntry::Files, LayoutDocManager::instance(), m_invalidEntry, m_rootNav, m_userGroupCount, LayoutNavEntry::MainPage, LayoutNavEntry::Modules, LayoutNavEntry::NamespaceList, LayoutNavEntry::NamespaceMembers, LayoutNavEntry::Namespaces, LayoutNavEntry::Pages, LayoutDocManager::rootNavEntry(), theTranslator, Translator::trClasses(), Translator::trClassHierarchy(), Translator::trClassHierarchyDescription(), Translator::trCompoundIndex(), Translator::trCompoundList(), Translator::trCompoundListDescription(), Translator::trCompoundListDescriptionFortran(), Translator::trCompoundListFortran(), Translator::trCompoundMembers(), Translator::trCompoundMembersDescription(), Translator::trCompoundMembersDescriptionFortran(), Translator::trCompoundMembersFortran(), Translator::trDataTypes(), VhdlDocGen::trDesignUnitHierarchy(), VhdlDocGen::trDesignUnitList(), VhdlDocGen::trDesignUnitListDescription(), VhdlDocGen::trDesignUnitMembers(), VhdlDocGen::trDesignUnits(), Translator::trExamples(), Translator::trExamplesDescription(), Translator::trFile(), Translator::trFileList(), Translator::trFileListDescription(), Translator::trFileMembers(), Translator::trFileMembersDescription(), Translator::trMainPage(), Translator::trModules(), Translator::trModulesDescription(), Translator::trModulesList(), Translator::trModulesListDescription(), Translator::trModulesMemberDescription(), Translator::trModulesMembers(), Translator::trNamespaceList(), Translator::trNamespaceListDescription(), Translator::trNamespaceMemberDescription(), Translator::trNamespaceMembers(), Translator::trNamespaces(), Translator::trPackageListDescription(), Translator::trPackageMembers(), Translator::trPackages(), Translator::trRelatedPages(), Translator::trRelatedPagesDescription(), LayoutNavEntry::User, and LayoutNavEntry::UserGroup.
Referenced by init().
startNavIndex()
void LayoutParser::startNavIndex (const QXmlAttributes &) inline
Definition at line 876 of file layout.cpp.
References LayoutNavEntry::clear(), LayoutDocManager::instance(), m_rootNav, m_scope, and LayoutDocManager::rootNavEntry().
Referenced by init().
startSectionEntry()
void LayoutParser::startSectionEntry (LayoutDocEntry::Kind k, const QXmlAttributes & attrib, const QCString & title) inline
Definition at line 822 of file layout.cpp.
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), and m_part.
Referenced by init().
startSimpleEntry()
void LayoutParser::startSimpleEntry (LayoutDocEntry::Kind k, const QXmlAttributes & attrib) inline
Definition at line 812 of file layout.cpp.
References LayoutDocManager::addEntry(), elemIsVisible(), LayoutDocManager::instance(), and m_part.
Referenced by init().
Member Data Documentation
m_eHandler
QDict<EndElementHandler> LayoutParser::m_eHandler private
Definition at line 1275 of file layout.cpp.
Referenced by endElement(), and init().
m_invalidEntry
bool LayoutParser::m_invalidEntry private
Definition at line 1279 of file layout.cpp.
Referenced by endNavEntry(), and startNavEntry().
m_part
int LayoutParser::m_part private
Definition at line 1277 of file layout.cpp.
Referenced by endClass(), endDirectory(), endFile(), endGroup(), endMemberDecl(), endMemberDef(), endNamespace(), init(), startClass(), startDirectory(), startFile(), startGroup(), startMemberDecl(), startMemberDeclEntry(), startMemberDef(), startMemberDefEntry(), startNamespace(), startSectionEntry(), and startSimpleEntry().
m_rootNav
LayoutNavEntry* LayoutParser::m_rootNav private
Definition at line 1278 of file layout.cpp.
Referenced by endNavEntry(), endNavIndex(), init(), startNavEntry(), startNavIndex(), and ~LayoutParser().
m_scope
QCString LayoutParser::m_scope private
Definition at line 1276 of file layout.cpp.
Referenced by endClass(), endDirectory(), endElement(), endFile(), endGroup(), endMemberDecl(), endMemberDef(), endNamespace(), endNavIndex(), startClass(), startDirectory(), startElement(), startFile(), startGroup(), startMemberDecl(), startMemberDef(), startNamespace(), and startNavIndex().
m_sHandler
QDict<StartElementHandler> LayoutParser::m_sHandler private
Definition at line 1274 of file layout.cpp.
Referenced by init(), and startElement().
m_userGroupCount
int LayoutParser::m_userGroupCount =0 static private
Definition at line 1280 of file layout.cpp.
Referenced by startNavEntry().
The documentation for this class was generated from the following file:
src/layout.cpp