Doxygen: src/commentscan.h File Reference
commentscan.h File Reference
Interface for the comment block parser.
#include "types.h"
Functions
bool parseCommentBlock (ParserInterface *parser, Entry *curEntry, const QCString &comment, const QCString &fileName, int &lineNr, bool isBrief, bool isJavaDocStyle, bool isInbody, Protection &prot, int &position, bool &newEntryNeeded)
Invokes the comment block parser with the request to parse a single comment block.
void groupEnterFile (const char *file, int line)
void groupLeaveFile (const char *file, int line)
void groupLeaveCompound (const char *file, int line, const char *name)
void groupEnterCompound (const char *file, int line, const char *name)
void openGroup (Entry *e, const char *file, int line)
void closeGroup (Entry *, const char *file, int line, bool foundInline=FALSE)
void initGroupInfo (Entry *e)
Detailed Description
Interface for the comment block parser.
Definition in file commentscan.h.
Function Documentation
closeGroup()
void closeGroup (Entry * , const char * file, int line, bool foundInline = FALSE)
groupEnterCompound()
void groupEnterCompound (const char * file, int line, const char * name)
groupEnterFile()
void groupEnterFile (const char * file, int line)
Referenced by VHDLLanguageScanner::parseInput().
groupLeaveCompound()
void groupLeaveCompound (const char * file, int line, const char * name)
groupLeaveFile()
void groupLeaveFile (const char * file, int line)
initGroupInfo()
void initGroupInfo (Entry * e)
Referenced by vhdl::parser::VhdlParser::initEntry().
openGroup()
void openGroup (Entry * e, const char * file, int line)
parseCommentBlock()
bool parseCommentBlock (ParserInterface * parser, Entry * curEntry, const QCString & comment, const QCString & fileName, int & lineNr, bool isBrief, bool isJavaDocStyle, bool isInbody, Protection & prot, int & position, bool & newEntryNeeded)
Invokes the comment block parser with the request to parse a single comment block.
Parameters
[in] parser The language parse that invoked this function. The comment block parse may invoke ParserInterface::parsePrototype() in order to parse the argument of a @fn command.
[in] curEntry The Entry to which the comment block belongs. Any information (like documentation) that is found in the comment block will be stored in this entry.
[in] comment A string representing the actual comment block. Note that leading *'s are already stripped from the comment block.
[in] fileName The name of the file in which the comment is found. Mainly used for producing warnings.
[in,out] lineNr The line number at which the comment block was found. When the function returns it will be set to the last line parsed.
[in] isBrief TRUE iff this comment block represents a brief description.
[in] isJavaDocStyle TRUE iff this comment block is in "JavaDoc" style. This means that it starts as a brief description until the end of the sentences is found and then proceeds as a detailed description.
[in] isInbody TRUE iff this comment block is located in the body of a function.
[in,out] prot The protection level in which this comment block was found. Commands in the comment block may override this.
[in,out] position The character position within comment where the comment block starts. Typically used in case the comment block contains multiple structural commands.
[out] newEntryNeeded Boolean that is TRUE if the comment block parser finds that a the comment block finishes the entry and a new one needs to be started.
Returns
TRUE if the comment requires further processing. The parameter newEntryNeeded will typically be true in this case and position will indicate the offset inside the comment string where to proceed parsing. FALSE indicates no further processing is needed.
Referenced by vhdl::parser::VhdlParser::handleCommentBlock(), and MarkdownFileParser::parseInput().