Doxygen: src/docparser.h File Reference
docparser.h File Reference
#include <stdio.h>
#include <qlist.h>
#include <qcstring.h>
#include "docvisitor.h"
#include "htmlattrib.h"
Classes
class DocNode
Abstract node interface with type information.
class CompAccept< T >
Default accept implementation for compound nodes in the abstract syntax tree.
class DocWord
Node representing a word.
class DocLinkedWord
Node representing a word that can be linked to something.
class DocURL
Node representing an URL (or email address)
class DocLineBreak
Node representing a line break.
class DocHorRuler
Node representing a horizonal ruler.
class DocAnchor
Node representing an anchor.
class DocCite
Node representing a citation of some bibliographic reference.
class DocStyleChange
Node representing a style change.
class DocSymbol
Node representing a special symbol.
struct DocSymbol::PerlSymb
class DocWhiteSpace
Node representing some amount of white space.
class DocVerbatim
Node representing a verbatim, unparsed text fragment.
class DocInclude
Node representing an included text block from file.
class DocIncOperator
Node representing a include/dontinclude operator block.
class DocFormula
Node representing an item of a cross-referenced list.
class DocIndexEntry
Node representing an entry in the index.
class DocCopy
Node representing a copy of documentation block.
class DocAutoList
Node representing an auto List.
class DocAutoListItem
Node representing an item of a auto list.
class DocTitle
Node representing a simple section title.
class DocXRefItem
Node representing an item of a cross-referenced list.
class DocImage
Node representing an image.
class DocDotFile
Node representing a dot file.
class DocMscFile
Node representing a msc file.
class DocDiaFile
Node representing a dia file.
class DocVhdlFlow
Node representing a VHDL flow chart.
class DocLink
Node representing a link to some item.
class DocRef
Node representing a reference to some item.
class DocInternalRef
Node representing an internal reference to some item.
class DocHRef
Node representing a Hypertext reference.
class DocHtmlHeader
Node Html heading.
class DocHtmlDescTitle
Node representing a Html description item.
class DocHtmlDescList
Node representing a Html description list.
class DocSection
Node representing a normal section.
class DocSecRefItem
Node representing a reference to a section.
class DocSecRefList
Node representing a list of section references.
class DocInternal
Node representing an internal section of documentation.
class DocParBlock
Node representing an block of paragraphs.
class DocSimpleList
Node representing a simple list.
class DocHtmlList
Node representing a Html list.
class DocSimpleSect
Node representing a simple section.
class DocSimpleSectSep
Node representing a separator between two simple sections of the same type.
class DocParamSect
Node representing a parameter section.
class DocPara
Node representing a paragraph in the documentation tree.
class DocParamList
Node representing a parameter list.
class DocSimpleListItem
Node representing a simple list item.
class DocHtmlListItem
Node representing a HTML list item.
class DocHtmlDescData
Node representing a HTML description data.
class DocHtmlCell
Node representing a HTML table cell.
class DocHtmlCaption
Node representing a HTML table caption.
class DocHtmlRow
Node representing a HTML table row.
class DocHtmlTable
Node representing a HTML table.
class DocHtmlBlockQuote
Node representing an HTML blockquote.
class DocText
Root node of a text fragment.
class DocRoot
Root node of documentation tree.
Functions
DocRoot * validatingParseDoc (const char *fileName, int startLine, Definition *context, MemberDef *md, const char *input, bool indexWords, bool isExample, const char *exampleName=0, bool singleLine=FALSE, bool linkFromIndex=FALSE)
DocText * validatingParseText (const char *input)
void docFindSections (const char *input, Definition *d, MemberGroup *m, const char *fileName)
Function Documentation
docFindSections()
void docFindSections (const char * input, Definition * d, MemberGroup * m, const char * fileName)
Searches for section and anchor commands in the input
Definition at line 7479 of file docparser.cpp.
References doctokenizerYYFindSections().
Referenced by PageDef::findSectionsInDocumentation(), MemberGroup::findSectionsInDocumentation(), GroupDef::findSectionsInDocumentation(), NamespaceDef::findSectionsInDocumentation(), FileDef::findSectionsInDocumentation(), ClassDef::findSectionsInDocumentation(), and MemberDef::findSectionsInDocumentation().
validatingParseDoc()
DocRoot* validatingParseDoc (const char * fileName, int startLine, Definition * context, MemberDef * md, const char * input, bool indexWords, bool isExample, const char * exampleName = 0, bool singleLine = FALSE, bool linkFromIndex = FALSE)
Main entry point for the documentation parser.
Parameters
fileName File in which the documentation block is found (or the name of the example file in case isExample is TRUE).
startLine Line at which the documentation block is found.
context Class or namespace to which this block belongs.
md Member definition to which the documentation belongs. Can be 0.
input String representation of the documentation block.
indexWords Indicates whether or not words should be put in the search index.
isExample TRUE if the documentation belongs to an example.
exampleName Base name of the example file (0 if isExample is FALSE).
singleLine Output should be presented on a single line, so without starting a new paragraph at the end.
linkFromIndex TRUE if the documentation is generated from an index page. In this case context is not used to determine the relative path when making a link.
Returns
Root node of the abstract syntax tree. Ownership of the pointer is handed over to the caller.
Definition at line 7224 of file docparser.cpp.
References DocRoot::accept(), MemberDef::anchor(), Definition::anchor(), checkUndocumentedParams(), ClassDef::compoundTypeString(), DefinitionIntf::definitionType(), detectNoDocumentedParams(), docParserPopContext(), docParserPushContext(), doctokenizerYYinit(), doctokenizerYYlineno, g_context, g_exampleName, g_fileName, g_hasParamCommand, g_hasReturnCommand, g_includeFileLength, g_includeFileOffset, g_includeFileText, g_initialStyleStack, g_inSeeBlock, g_insideHtmlLink, g_isExample, g_nodeStack, g_paramsFound, g_relPath, g_searchUrl, g_styleStack, g_xmlComment, Definition::getLanguage(), getLanguageSpecificSeparator(), MemberDef::getOutputFileBase(), Definition::getOutputFileBase(), Doxygen::globalScope, GroupDef::groupTitle(), Debug::isFlagSet(), Definition::name(), DocRoot::parse(), Debug::PrintTree, processCopyDoc(), MemberDef::qualifiedName(), Definition::qualifiedName(), relativePathToRoot(), Doxygen::searchIndex, SearchIndexIntf::setCurrentDoc(), SrcLangExt_CSharp, SrcLangExt_Fortran, SrcLangExt_Java, substitute(), theTranslator, PageDef::title(), Translator::trGroup(), Translator::trMember(), Translator::trModule(), Translator::trNamespace(), Translator::trPackage(), Translator::trPage(), Translator::trSubprogram(), DefinitionIntf::TypeClass, DefinitionIntf::TypeGroup, DefinitionIntf::TypeNamespace, and DefinitionIntf::TypePage.
Referenced by addPerlModDocBlock(), generateBriefDoc(), OutputList::generateDoc(), parseCommentAsText(), parseDoc(), DirDef::writeBriefDescription(), NamespaceDef::writeBriefDescription(), GroupDef::writeBriefDescription(), FileDef::writeBriefDescription(), MemberDef::writeDeclaration(), ClassDef::writeDeclarationLink(), writeDocbookDocBlock(), MemberList::writePlainDeclarations(), and writeXMLDocBlock().
validatingParseText()
DocText* validatingParseText (const char * input)
Main entry point for parsing simple text fragments. These fragments are limited to words, whitespace and symbols.
Definition at line 7426 of file docparser.cpp.
References DocText::accept(), docParserPopContext(), docParserPushContext(), doctokenizerYYinit(), doctokenizerYYlineno, g_context, g_exampleName, g_fileName, g_hasParamCommand, g_hasReturnCommand, g_includeFileLength, g_includeFileOffset, g_includeFileText, g_initialStyleStack, g_inSeeBlock, g_insideHtmlLink, g_isExample, g_nodeStack, g_paramsFound, g_relPath, g_searchUrl, g_styleStack, g_xmlComment, Debug::isFlagSet(), DocText::parse(), and Debug::PrintTree.
Referenced by RTFGenerator::endIndexSection(), and OutputList::parseText().