Doxygen: VHDLLanguageScanner Class Reference
VHDLLanguageScanner Class Reference
VHDL parser using state-based lexical scanning.
#include <vhdljjparser.h>
Public Member Functions
virtual ~VHDLLanguageScanner ()
void startTranslationUnit (const char *)
Starts processing a translation unit (source files + headers).
void finishTranslationUnit ()
Called after all files in a translation unit have been processed.
void parseInput (const char *fileName, const char *fileBuf, Entry *root, bool sameTranslationUnit, QStrList &filesInSameTranslationUnit)
Parses a single input file with the goal to build an Entry tree.
void parseCode (CodeOutputInterface &codeOutIntf, const char *scopeName, const QCString &input, SrcLangExt lang, bool isExampleBlock, const char *exampleName=0, FileDef *fileDef=0, int startLine=-1, int endLine=-1, bool inlineFragment=FALSE, MemberDef *memberDef=0, bool showLineNumbers=TRUE, Definition *searchCtx=0, bool collectXRefs=TRUE)
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
bool needsPreprocessing (const QCString &)
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
void resetCodeParserState ()
Resets the state of the code parser.
void parsePrototype (const char *text)
Callback function called by the comment block scanner.
Public Member Functions inherited from ParserInterface
virtual ~ParserInterface ()
Detailed Description
VHDL parser using state-based lexical scanning.
This is the VHDL language parser for doxygen.
Definition at line 41 of file vhdljjparser.h.
Constructor & Destructor Documentation
~VHDLLanguageScanner()
virtual VHDLLanguageScanner::~VHDLLanguageScanner () inline virtual
Definition at line 44 of file vhdljjparser.h.
Member Function Documentation
finishTranslationUnit()
void VHDLLanguageScanner::finishTranslationUnit () inline virtual
Called after all files in a translation unit have been processed.
Implements ParserInterface.
Definition at line 46 of file vhdljjparser.h.
Referenced by VhdlDocGen::createFlowChart().
needsPreprocessing()
bool VHDLLanguageScanner::needsPreprocessing (const QCString & extension) inline virtual
Returns TRUE if the language identified by extension needs the C preprocessor to be run before feed the result to the input parser.
See also
parseInput()
Implements ParserInterface.
Definition at line 68 of file vhdljjparser.h.
parseCode()
void VHDLLanguageScanner::parseCode (CodeOutputInterface & codeOutIntf, const char * scopeName, const QCString & input, SrcLangExt lang, bool isExampleBlock, const char * exampleName = 0, FileDef * fileDef = 0, int startLine = -1, int endLine = -1, bool inlineFragment = FALSE, MemberDef * memberDef = 0, bool showLineNumbers = TRUE, Definition * searchCtx = 0, bool collectXRefs = TRUE) virtual
Parses a source file or fragment with the goal to produce highlighted and cross-referenced output.
Parameters
[in] codeOutIntf Abstract interface for writing the result.
[in] lang The programming language of the code fragment.
[in] scopeName Name of scope to which the code belongs.
[in] input Actual code in the form of a string
[in] isExampleBlock TRUE iff the code is part of an example.
[in] exampleName Name of the example.
[in] fileDef File definition to which the code is associated.
[in] startLine Starting line in case of a code fragment.
[in] endLine Ending line of the code fragment.
[in] inlineFragment Code fragment that is to be shown inline as part of the documentation.
[in] memberDef Member definition to which the code is associated (non null in case of an inline fragment for a member).
[in] showLineNumbers if set to TRUE and also fileDef is not 0, line numbers will be added to the source fragement
[in] searchCtx context under which search data has to be stored.
[in] collectXRefs collect cross-reference relations.
Implements ParserInterface.
Definition at line 4523 of file vhdldocgen.cpp.
References parseVhdlCode().
parseInput()
void VHDLLanguageScanner::parseInput (const char * fileName, const char * fileBuf, Entry * root, bool sameTranslationUnit, QStrList & filesInSameTranslationUnit) virtual
Parses a single input file with the goal to build an Entry tree.
Parameters
[in] fileName The full name of the file.
[in] fileBuf The contents of the file (zero terminated).
[in,out] root The root of the tree of Entry *nodes representing the information extracted from the file.
[in] sameTranslationUnit TRUE if this file was found in the same translation unit (in the filesInSameTranslationUnit list returned for another file).
[in,out] filesInSameTranslationUnit other files expected to be found in the same translation unit (used for libclang)
Implements ParserInterface.
Definition at line 161 of file vhdljjparser.cpp.
References vhdl::parser::VhdlParser::current, groupEnterFile(), vhdl::parser::VhdlParser::initEntry(), inputString, isConstraintFile(), libUse, lineParse, vhdl::parser::VhdlParser::mapLibPackage(), VhdlDocGen::parseUCF(), VhdlParserIF::parseVhdlfile(), VhdlDocGen::resetCodeVhdlParserState(), yyFileName, and yyLineNr.
Referenced by VhdlDocGen::createFlowChart().
parsePrototype()
void VHDLLanguageScanner::parsePrototype (const char * text) virtual
Callback function called by the comment block scanner.
It provides a string text containing the prototype of a function or variable. The parser should parse this and store the information in the Entry node that corresponds with the node for which the comment block parser was invoked.
Implements ParserInterface.
Definition at line 407 of file vhdljjparser.cpp.
References varName, and varr.
resetCodeParserState()
void VHDLLanguageScanner::resetCodeParserState () inline virtual
Resets the state of the code parser.
Since multiple code fragments can together form a single example, an explicit function is used to reset the code parser state.
See also
parseCode()
Implements ParserInterface.
Definition at line 69 of file vhdljjparser.h.
startTranslationUnit()
void VHDLLanguageScanner::startTranslationUnit (const char * fileName) inline virtual
Starts processing a translation unit (source files + headers).
After this call parseInput() is called with sameTranslationUnit set to FALSE. If parseInput() returns additional include files, these are also processed using parseInput() with sameTranslationUnit set to TRUE. After that finishTranslationUnit() is called.
Implements ParserInterface.
Definition at line 45 of file vhdljjparser.h.
Referenced by VhdlDocGen::createFlowChart().
The documentation for this class was generated from the following files:
src/vhdljjparser.h
src/vhdldocgen.cpp
src/vhdljjparser.cpp