Doxygen: Mapper Class Reference
Mapper Class Reference
Class representing a mapping from command names to command IDs.
#include <cmdmapper.h>
Public Member Functions
int map (const char *n)
QString find (const int n)
Mapper (const CommandMap *cm, bool caseSensitive)
Private Attributes
QDict< int > m_map
bool m_cs
Detailed Description
Class representing a mapping from command names to command IDs.
Definition at line 207 of file cmdmapper.h.
Constructor & Destructor Documentation
Mapper()
Mapper::Mapper (const CommandMap * cm, bool caseSensitive)
Definition at line 246 of file cmdmapper.cpp.
References CommandMap::cmdId, CommandMap::cmdName, and m_map.
Member Function Documentation
find()
QString Mapper::find (const int n)
Definition at line 236 of file cmdmapper.cpp.
References m_map, and SIMPLESECT_BIT.
Referenced by defaultHandleTitleAndSize().
map()
int Mapper::map (const char * n)
Definition at line 228 of file cmdmapper.cpp.
References m_cs, and m_map.
Referenced by DocPara::handleCommand(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlCell::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlList::parseXml(), DocParamList::parseXml(), DocHtmlCell::parseXml(), DocHtmlRow::parseXml(), and DocHtmlTable::parseXml().
Member Data Documentation
m_cs
bool Mapper::m_cs private
Definition at line 215 of file cmdmapper.h.
Referenced by map().
m_map
QDict<int> Mapper::m_map private
Definition at line 214 of file cmdmapper.h.
Referenced by find(), map(), and Mapper().
The documentation for this class was generated from the following files:
src/cmdmapper.h
src/cmdmapper.cpp