Doxygen: PrefixIgnoreClassList Class Reference
PrefixIgnoreClassList Class Reference
Special class list where sorting takes IGNORE_PREFIX into account.
Public Types
typedef ClassDef ElementType
Public Member Functions
PrefixIgnoreClassList (uint letter)
uint letter () const
Public Member Functions inherited from ClassList
ClassList ()
~ClassList ()
Private Member Functions
virtual int compareValue (const ClassDef *c1, const ClassDef *c2) const
Private Attributes
uint m_letter
Detailed Description
Special class list where sorting takes IGNORE_PREFIX into account.
Definition at line 1681 of file index.cpp.
Member Typedef Documentation
ElementType
typedef ClassDef PrefixIgnoreClassList::ElementType
Definition at line 1684 of file index.cpp.
Constructor & Destructor Documentation
PrefixIgnoreClassList()
PrefixIgnoreClassList::PrefixIgnoreClassList (uint letter) inline
Definition at line 1685 of file index.cpp.
Member Function Documentation
compareValue()
virtual int PrefixIgnoreClassList::compareValue (const ClassDef * c1, const ClassDef * c2) const inline private virtual
Definition at line 1688 of file index.cpp.
References ClassDef::className(), and getPrefixIndex().
letter()
uint PrefixIgnoreClassList::letter () const inline
Definition at line 1686 of file index.cpp.
References m_letter.
Referenced by writeAlphabeticalClassList().
Member Data Documentation
m_letter
uint PrefixIgnoreClassList::m_letter private
Definition at line 1694 of file index.cpp.
Referenced by letter().
The documentation for this class was generated from the following file:
src/index.cpp