Doxygen: GlobalsIndexContext Class Reference
GlobalsIndexContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static GlobalsIndexContext * alloc ()
Private Member Functions
GlobalsIndexContext ()
~GlobalsIndexContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 832 of file context.h.
Constructor & Destructor Documentation
GlobalsIndexContext()
GlobalsIndexContext::GlobalsIndexContext () private
Definition at line 7980 of file context.cpp.
References p, and Private.
Referenced by alloc().
~GlobalsIndexContext()
GlobalsIndexContext::~GlobalsIndexContext () private
Definition at line 7985 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int GlobalsIndexContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 839 of file context.h.
References RefCountedContext::addRef().
alloc()
static GlobalsIndexContext* GlobalsIndexContext::alloc () inline static
Definition at line 835 of file context.h.
References GlobalsIndexContext().
Referenced by generateOutputViaTemplate().
get()
TemplateVariant GlobalsIndexContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 7990 of file context.cpp.
References GlobalsIndexContext::Private::get(), and p.
release()
virtual int GlobalsIndexContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 840 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* GlobalsIndexContext::p private
Definition at line 845 of file context.h.
Referenced by get(), GlobalsIndexContext(), and ~GlobalsIndexContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp