Doxygen: DocHtmlTable Class Reference
DocHtmlTable Class Reference
Node representing a HTML table.
#include <docparser.h>
Public Member Functions
DocHtmlTable (DocNode *parent, const HtmlAttribList &attribs)
~DocHtmlTable ()
Kind kind () const
uint numRows () const
bool hasCaption ()
const HtmlAttribList & attribs () const
int parse ()
int parseXml ()
uint numColumns () const
void accept (DocVisitor *v)
DocHtmlCaption * caption () const
DocHtmlRow * firstRow () const
Public Member Functions inherited from CompAccept< DocHtmlTable >
CompAccept ()
virtual ~CompAccept ()
void accept (DocHtmlTable *obj, DocVisitor *v)
const QList< DocNode > & children () const
QList< DocNode > & children ()
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Member Functions
void computeTableGrid ()
determines the location of all cells in a grid, resolving row and column spans.
Private Attributes
DocHtmlCaption * m_caption
HtmlAttribList m_attribs
int m_numCols
Additional Inherited Members
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from CompAccept< DocHtmlTable >
QList< DocNode > m_children
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Node representing a HTML table.
Definition at line 1346 of file docparser.h.
Constructor & Destructor Documentation
DocHtmlTable()
DocHtmlTable::DocHtmlTable (DocNode * parent, const HtmlAttribList & attribs) inline
Definition at line 1349 of file docparser.h.
References m_caption, DocNode::m_parent, and DocNode::parent().
~DocHtmlTable()
DocHtmlTable::~DocHtmlTable () inline
Definition at line 1351 of file docparser.h.
References m_caption.
Member Function Documentation
accept()
void DocHtmlTable::accept (DocVisitor * v) virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 3819 of file docparser.cpp.
References DocNode::accept(), DocHtmlCaption::accept(), m_caption, CompAccept< DocHtmlTable >::m_children, DocVisitor::visitPost(), and DocVisitor::visitPre().
attribs()
const HtmlAttribList& DocHtmlTable::attribs () const inline
Definition at line 1355 of file docparser.h.
References m_attribs.
Referenced by HtmlDocVisitor::visitPre().
caption()
DocHtmlCaption* DocHtmlTable::caption () const inline
Definition at line 1360 of file docparser.h.
References m_caption.
Referenced by HtmlDocVisitor::visitPre(), and LatexDocVisitor::visitPre().
computeTableGrid()
void DocHtmlTable::computeTableGrid () private
determines the location of all cells in a grid, resolving row and column spans.
For each the total number of visible cells is computed, and the total number of visible columns over all rows is stored.
Definition at line 3762 of file docparser.cpp.
References CompAccept< DocHtmlTable >::children(), CompAccept< T >::children(), DocHtmlCell::colSpan(), DocNode::kind(), DocNode::Kind_HtmlCell, DocNode::Kind_HtmlRow, m_numCols, DocHtmlCell::rowSpan(), DocHtmlCell::setColumnIndex(), DocHtmlCell::setRowIndex(), DocHtmlRow::setRowIndex(), and DocHtmlRow::setVisibleCells().
Referenced by parse(), and parseXml().
firstRow()
DocHtmlRow* DocHtmlTable::firstRow () const inline
Definition at line 1361 of file docparser.h.
References DocNode::kind(), DocNode::Kind_HtmlRow, and CompAccept< DocHtmlTable >::m_children.
Referenced by LatexDocVisitor::visitPre().
hasCaption()
bool DocHtmlTable::hasCaption () inline
Definition at line 1354 of file docparser.h.
References m_caption.
Referenced by HtmlDocVisitor::visitPre(), and LatexDocVisitor::visitPre().
kind()
Kind DocHtmlTable::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 1352 of file docparser.h.
References DocNode::Kind_HtmlTable.
numColumns()
uint DocHtmlTable::numColumns () const inline
Definition at line 1358 of file docparser.h.
References m_numCols.
Referenced by DocbookDocVisitor::visitPre(), XmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
numRows()
uint DocHtmlTable::numRows () const inline
Definition at line 1353 of file docparser.h.
References CompAccept< DocHtmlTable >::m_children.
Referenced by XmlDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
parse()
int DocHtmlTable::parse ()
Definition at line 3632 of file docparser.cpp.
References TokenInfo::attribs, computeTableGrid(), DBG, doctokenizerYYlex(), doctokenizerYYlineno, TokenInfo::endTag, g_fileName, g_nodeStack, g_token, HTML_CAPTION, HTML_TR, Mappers::htmlTagMapper, m_caption, CompAccept< DocHtmlTable >::m_children, Mapper::map(), TokenInfo::name, DocHtmlCaption::parse(), DocHtmlRow::parse(), RetVal_EndTable, RetVal_OK, RetVal_TableRow, TK_HTMLTAG, TK_NEWPARA, TK_WHITESPACE, tokToString(), and warn_doc_error().
Referenced by DocPara::handleHtmlStartTag().
parseXml()
int DocHtmlTable::parseXml ()
Definition at line 3702 of file docparser.cpp.
References TokenInfo::attribs, computeTableGrid(), DBG, doctokenizerYYlex(), TokenInfo::endTag, g_nodeStack, g_token, Mappers::htmlTagMapper, CompAccept< DocHtmlTable >::m_children, Mapper::map(), TokenInfo::name, DocHtmlRow::parseXml(), RetVal_OK, RetVal_TableRow, TK_HTMLTAG, TK_NEWPARA, TK_WHITESPACE, XML_ITEM, XML_LIST, and XML_LISTHEADER.
Referenced by DocPara::handleHtmlStartTag().
Member Data Documentation
m_attribs
HtmlAttribList DocHtmlTable::m_attribs private
Definition at line 1370 of file docparser.h.
Referenced by attribs().
m_caption
DocHtmlCaption* DocHtmlTable::m_caption private
Definition at line 1369 of file docparser.h.
Referenced by accept(), caption(), DocHtmlTable(), hasCaption(), parse(), and ~DocHtmlTable().
m_numCols
int DocHtmlTable::m_numCols private
Definition at line 1371 of file docparser.h.
Referenced by computeTableGrid(), and numColumns().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp