Doxygen: src/ftvhelp.cpp File Reference
ftvhelp.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <qlist.h>
#include <qdict.h>
#include <qfileinfo.h>
#include "ftvhelp.h"
#include "config.h"
#include "message.h"
#include "doxygen.h"
#include "language.h"
#include "htmlgen.h"
#include "layout.h"
#include "pagedef.h"
#include "docparser.h"
#include "htmldocvisitor.h"
#include "filedef.h"
#include "util.h"
#include "resourcemgr.h"
Classes
struct FTVNode
struct NavIndexEntry
class NavIndexEntryList
Macros
#define MAX_INDENT 1024
Functions
static QCString node2URL (FTVNode *n, bool overruleFile=FALSE, bool srcLink=FALSE)
static void generateBriefDoc (FTextStream &t, Definition *def)
static QCString pathToNode (FTVNode *leaf, FTVNode *n)
static bool dupOfParent (const FTVNode *n)
static void generateJSLink (FTextStream &t, FTVNode *n)
static QCString convertFileId2Var (const QCString &fileId)
static bool generateJSTree (NavIndexEntryList &navIndex, FTextStream &t, const QList< FTVNode > &nl, int level, bool &first)
static void generateJSNavTree (const QList< FTVNode > &nodeList)
Variables
static int folderId =1
Macro Definition Documentation
MAX_INDENT
#define MAX_INDENT 1024
Definition at line 41 of file ftvhelp.cpp.
Referenced by FTVHelp::FTVHelp(), and FTVHelp::incContentsDepth().
Function Documentation
convertFileId2Var()
static QCString convertFileId2Var (const QCString & fileId) static
Definition at line 482 of file ftvhelp.cpp.
References substitute().
Referenced by generateJSTree().
dupOfParent()
static bool dupOfParent (const FTVNode * n) static
Definition at line 460 of file ftvhelp.cpp.
References FTVNode::file, and FTVNode::parent.
Referenced by generateJSTree().
generateBriefDoc()
static void generateBriefDoc (FTextStream & t, Definition * def) static
Definition at line 308 of file ftvhelp.cpp.
References DocNode::accept(), brief, Definition::briefDescription(), Definition::briefFile(), Definition::briefLine(), Definition::getOutputFileBase(), relativePathToRoot(), and validatingParseDoc().
Referenced by FTVHelp::generateTree().
generateJSLink()
static void generateJSLink (FTextStream & t, FTVNode * n) static
Definition at line 467 of file ftvhelp.cpp.
References convertToJSString(), externalRef(), FTVNode::file, FTVNode::name, node2URL(), and FTVNode::ref.
Referenced by generateJSTree().
generateJSNavTree()
static void generateJSNavTree (const QList< FTVNode > & nodeList) static
Definition at line 580 of file ftvhelp.cpp.
References Config_getString, convertToJSString(), ResourceMgr::copyResource(), endl(), LayoutNavEntry::find(), generateJSTree(), Doxygen::htmlFileExtension, ResourceMgr::instance(), LayoutDocManager::instance(), Doxygen::mainPage, LayoutNavEntry::MainPage, NavIndexEntry::path, LayoutDocManager::rootNavEntry(), FTextStream::setDevice(), theTranslator, LayoutNavEntry::title(), Translator::trPanelSynchronisationTooltip(), and NavIndexEntry::url.
Referenced by FTVHelp::generateTreeViewScripts().
generateJSTree()
static bool generateJSTree (NavIndexEntryList & navIndex, FTextStream & t, const QList< FTVNode > & nl, int level, bool & first) static
Definition at line 490 of file ftvhelp.cpp.
References FTVNode::addToNavIndex, FTVNode::anchor, FTVNode::children, Config_getString, convertFileId2Var(), FTVNode::def, DefinitionIntf::definitionType(), doc, dupOfParent(), endl(), FTVNode::file, fileVisibleInIndex(), generateJSLink(), node2URL(), pathToNode(), FTVNode::separateIndex, and DefinitionIntf::TypeFile.
Referenced by generateJSNavTree().
node2URL()
static QCString node2URL (FTVNode * n, bool overruleFile = FALSE, bool srcLink = FALSE) static
Definition at line 210 of file ftvhelp.cpp.
References FTVNode::anchor, FTVNode::def, DefinitionIntf::definitionType(), FTVNode::file, FileDef::getOutputFileBase(), FileDef::getSourceFileBase(), Doxygen::htmlFileExtension, and DefinitionIntf::TypeFile.
Referenced by generateJSLink(), generateJSTree(), and FTVHelp::generateLink().
pathToNode()
static QCString pathToNode (FTVNode * leaf, FTVNode * n) static
Definition at line 448 of file ftvhelp.cpp.
References FTVNode::index, and FTVNode::parent.
Referenced by generateJSTree().
Variable Documentation
folderId
int folderId =1 static
Definition at line 43 of file ftvhelp.cpp.
Referenced by FTVHelp::generateTree().