Doxygen: TemplateNodeRepeat Class Reference
TemplateNodeRepeat Class Reference
Class representing a 'for' tag in a template.
Public Member Functions
TemplateNodeRepeat (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeRepeat ()
void render (FTextStream &ts, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeRepeat >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Private Attributes
TemplateNodeList m_repeatNodes
ExprAst * m_expr
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeRepeat >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeRepeat >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeRepeat >
QCString m_templateName
int m_line
Detailed Description
Class representing a 'for' tag in a template.
Definition at line 2963 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeRepeat()
TemplateNodeRepeat::TemplateNodeRepeat (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 2966 of file template.cpp.
References m_expr, m_repeatNodes, TemplateParser::parse(), ExpressionParser::parse(), TemplateParser::removeNextToken(), and TRACE.
~TemplateNodeRepeat()
TemplateNodeRepeat::~TemplateNodeRepeat () inline
Definition at line 2978 of file template.cpp.
References m_expr.
Member Function Documentation
render()
void TemplateNodeRepeat::render (FTextStream & ts, TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 2982 of file template.cpp.
References TemplateStruct::alloc(), TemplateAutoRef< T >::get(), TemplateVariant::Integer, m_expr, TemplateNodeCreator< TemplateNodeRepeat >::m_line, m_repeatNodes, TemplateNodeCreator< TemplateNodeRepeat >::m_templateName, TemplateNodeList::render(), ExprAst::resolve(), TemplateStruct::set(), TemplateContext::set(), TemplateContextImpl::setLocation(), TemplateVariant::toInt(), and TemplateContextImpl::warn().
Member Data Documentation
m_expr
ExprAst* TemplateNodeRepeat::m_expr private
Definition at line 3012 of file template.cpp.
Referenced by render(), TemplateNodeRepeat(), and ~TemplateNodeRepeat().
m_repeatNodes
TemplateNodeList TemplateNodeRepeat::m_repeatNodes private
Definition at line 3011 of file template.cpp.
Referenced by render(), and TemplateNodeRepeat().
The documentation for this class was generated from the following file:
src/template.cpp