Doxygen: PageTreeContext::Private Class Reference
PageTreeContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (const PageSDict *pages)
TemplateVariant get (const char *n) const
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
Private Attributes
SharedPtr< NestingContext > m_pageTree
Cachable m_cache
Static Private Attributes
static PropertyMapper< PageTreeContext::Private > s_inst
Detailed Description
Definition at line 7278 of file context.cpp.
Constructor & Destructor Documentation
Private()
PageTreeContext::Private::Private (const PageSDict * pages) inline
Definition at line 7281 of file context.cpp.
References NestingContext::addPages(), PropertyMapper< T >::addProperty(), NestingContext::alloc(), fileName(), highlight(), Config::init(), m_pageTree, maxDepth(), preferredDepth(), relPath(), SharedPtr< T >::reset(), s_inst, subhighlight(), title(), and tree().
Member Function Documentation
fileName()
TemplateVariant PageTreeContext::Private::fileName () const inline
Definition at line 7313 of file context.cpp.
Referenced by Private().
get()
TemplateVariant PageTreeContext::Private::get (const char * n) const inline
Definition at line 7305 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by PageTreeContext::get().
highlight()
TemplateVariant PageTreeContext::Private::highlight () const inline
Definition at line 7321 of file context.cpp.
Referenced by Private().
maxDepth()
TemplateVariant PageTreeContext::Private::maxDepth () const inline
Definition at line 7333 of file context.cpp.
References computeMaxDepth(), SharedPtr< T >::get(), m_cache, m_pageTree, PageTreeContext::Private::Cachable::maxDepth, and PageTreeContext::Private::Cachable::maxDepthComputed.
Referenced by preferredDepth(), and Private().
preferredDepth()
TemplateVariant PageTreeContext::Private::preferredDepth () const inline
Definition at line 7342 of file context.cpp.
References computePreferredDepth(), SharedPtr< T >::get(), m_cache, m_pageTree, maxDepth(), PageTreeContext::Private::Cachable::preferredDepth, PageTreeContext::Private::Cachable::preferredDepthComputed, and TemplateVariant::toInt().
Referenced by Private().
relPath()
TemplateVariant PageTreeContext::Private::relPath () const inline
Definition at line 7317 of file context.cpp.
Referenced by Private().
subhighlight()
TemplateVariant PageTreeContext::Private::subhighlight () const inline
Definition at line 7325 of file context.cpp.
Referenced by Private().
title()
TemplateVariant PageTreeContext::Private::title () const inline
Definition at line 7329 of file context.cpp.
References theTranslator, and Translator::trRelatedPages().
Referenced by Private().
tree()
TemplateVariant PageTreeContext::Private::tree () const inline
Definition at line 7309 of file context.cpp.
References SharedPtr< T >::get(), and m_pageTree.
Referenced by Private().
Member Data Documentation
m_cache
Cachable PageTreeContext::Private::m_cache mutable private
Definition at line 7361 of file context.cpp.
Referenced by maxDepth(), and preferredDepth().
m_pageTree
SharedPtr<NestingContext> PageTreeContext::Private::m_pageTree private
Definition at line 7352 of file context.cpp.
Referenced by maxDepth(), preferredDepth(), Private(), and tree().
s_inst
PropertyMapper< PageTreeContext::Private > PageTreeContext::Private::s_inst static private
Definition at line 7362 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp