Doxygen: ArgumentContext Class Reference
ArgumentContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static ArgumentContext * alloc (const Argument *arg, Definition *def, const QCString &relPath)
Private Member Functions
ArgumentContext (const Argument *arg, Definition *def, const QCString &relPath)
~ArgumentContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1138 of file context.h.
Constructor & Destructor Documentation
ArgumentContext()
ArgumentContext::ArgumentContext (const Argument * arg, Definition * def, const QCString & relPath) private
Definition at line 9362 of file context.cpp.
References p, and Private.
Referenced by alloc().
~ArgumentContext()
ArgumentContext::~ArgumentContext () private
Definition at line 9367 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int ArgumentContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 1146 of file context.h.
References RefCountedContext::addRef().
alloc()
static ArgumentContext* ArgumentContext::alloc (const Argument * arg, Definition * def, const QCString & relPath) inline static
Definition at line 1141 of file context.h.
References ArgumentContext().
Referenced by ArgumentListContext::Private::addArgument().
get()
TemplateVariant ArgumentContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 9372 of file context.cpp.
References ArgumentContext::Private::get(), and p.
release()
virtual int ArgumentContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 1147 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ArgumentContext::p private
Definition at line 1152 of file context.h.
Referenced by ArgumentContext(), get(), and ~ArgumentContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp