Doxygen: AlphaIndexTableCell Class Reference
AlphaIndexTableCell Class Reference
Class representing a cell in the alphabetical class index.
Public Member Functions
AlphaIndexTableCell (int row, int col, uint letter, ClassDef *cd)
ClassDef * classDef () const
uint letter () const
int row () const
int column () const
Private Attributes
uint m_letter
ClassDef * m_class
int m_row
int m_col
Detailed Description
Class representing a cell in the alphabetical class index.
Definition at line 1698 of file index.cpp.
Constructor & Destructor Documentation
AlphaIndexTableCell()
AlphaIndexTableCell::AlphaIndexTableCell (int row, int col, uint letter, ClassDef * cd) inline
Definition at line 1701 of file index.cpp.
Member Function Documentation
classDef()
ClassDef* AlphaIndexTableCell::classDef () const inline
Definition at line 1707 of file index.cpp.
References m_class.
Referenced by writeAlphabeticalClassList().
column()
int AlphaIndexTableCell::column () const inline
Definition at line 1710 of file index.cpp.
References m_col.
letter()
uint AlphaIndexTableCell::letter () const inline
Definition at line 1708 of file index.cpp.
References m_letter.
Referenced by writeAlphabeticalClassList().
row()
int AlphaIndexTableCell::row () const inline
Definition at line 1709 of file index.cpp.
References m_row.
Referenced by writeAlphabeticalClassList().
Member Data Documentation
m_class
ClassDef* AlphaIndexTableCell::m_class private
Definition at line 1714 of file index.cpp.
Referenced by classDef().
m_col
int AlphaIndexTableCell::m_col private
Definition at line 1716 of file index.cpp.
Referenced by column().
m_letter
uint AlphaIndexTableCell::m_letter private
Definition at line 1713 of file index.cpp.
Referenced by letter().
m_row
int AlphaIndexTableCell::m_row private
Definition at line 1715 of file index.cpp.
Referenced by row().
The documentation for this class was generated from the following file:
src/index.cpp