Doxygen: TranslatorGerman Class Reference
TranslatorGerman Class Reference
#include <translator_de.h>
Public Member Functions
virtual QCString idLanguage ()
virtual QCString latexLanguageSupportCommand ()
virtual QCString trRelatedFunctions ()
virtual QCString trRelatedSubscript ()
virtual QCString trDetailedDescription ()
virtual QCString trMemberTypedefDocumentation ()
virtual QCString trMemberEnumerationDocumentation ()
virtual QCString trMemberFunctionDocumentation ()
virtual QCString trMemberDataDocumentation ()
virtual QCString trMore ()
virtual QCString trListOfAllMembers ()
virtual QCString trMemberList ()
virtual QCString trThisIsTheListOfAllMembers ()
virtual QCString trIncludingInheritedMembers ()
virtual QCString trGeneratedAutomatically (const char *s)
virtual QCString trEnumName ()
virtual QCString trEnumValue ()
virtual QCString trDefinedIn ()
virtual QCString trModules ()
virtual QCString trClassHierarchy ()
virtual QCString trCompoundList ()
virtual QCString trFileList ()
virtual QCString trCompoundMembers ()
virtual QCString trFileMembers ()
virtual QCString trRelatedPages ()
virtual QCString trExamples ()
virtual QCString trSearch ()
virtual QCString trClassHierarchyDescription ()
virtual QCString trFileListDescription (bool extractAll)
virtual QCString trCompoundListDescription ()
virtual QCString trCompoundMembersDescription (bool extractAll)
virtual QCString trFileMembersDescription (bool extractAll)
virtual QCString trExamplesDescription ()
virtual QCString trRelatedPagesDescription ()
virtual QCString trModulesDescription ()
virtual QCString trDocumentation ()
virtual QCString trModuleIndex ()
virtual QCString trHierarchicalIndex ()
virtual QCString trCompoundIndex ()
virtual QCString trFileIndex ()
virtual QCString trModuleDocumentation ()
virtual QCString trClassDocumentation ()
virtual QCString trFileDocumentation ()
virtual QCString trExampleDocumentation ()
virtual QCString trPageDocumentation ()
virtual QCString trReferenceManual ()
virtual QCString trDefines ()
virtual QCString trTypedefs ()
virtual QCString trEnumerations ()
virtual QCString trFunctions ()
virtual QCString trVariables ()
virtual QCString trEnumerationValues ()
virtual QCString trDefineDocumentation ()
virtual QCString trTypedefDocumentation ()
virtual QCString trEnumerationTypeDocumentation ()
virtual QCString trFunctionDocumentation ()
virtual QCString trVariableDocumentation ()
virtual QCString trCompounds ()
virtual QCString trGeneratedAt (const char *date, const char *projName)
virtual QCString trClassDiagram (const char *clName)
virtual QCString trForInternalUseOnly ()
virtual QCString trWarning ()
virtual QCString trVersion ()
virtual QCString trDate ()
virtual QCString trReturns ()
virtual QCString trSeeAlso ()
virtual QCString trParameters ()
virtual QCString trExceptions ()
virtual QCString trGeneratedBy ()
virtual QCString trNamespaceList ()
virtual QCString trNamespaceListDescription (bool extractAll)
virtual QCString trFriends ()
virtual QCString trRelatedFunctionDocumentation ()
virtual QCString trCompoundReference (const char *clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trFileReference (const char *fileName)
virtual QCString trNamespaceReference (const char *namespaceName)
virtual QCString trPublicMembers ()
virtual QCString trPublicSlots ()
virtual QCString trSignals ()
virtual QCString trStaticPublicMembers ()
virtual QCString trProtectedMembers ()
virtual QCString trProtectedSlots ()
virtual QCString trStaticProtectedMembers ()
virtual QCString trPrivateMembers ()
virtual QCString trPrivateSlots ()
virtual QCString trStaticPrivateMembers ()
virtual QCString trWriteList (int numEntries)
virtual QCString trInheritsList (int numEntries)
virtual QCString trInheritedByList (int numEntries)
virtual QCString trReimplementedFromList (int numEntries)
virtual QCString trReimplementedInList (int numEntries)
virtual QCString trNamespaceMembers ()
virtual QCString trNamespaceMemberDescription (bool extractAll)
virtual QCString trNamespaceIndex ()
virtual QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
virtual QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
virtual QCString trReturnValues ()
virtual QCString trMainPage ()
virtual QCString trPageAbbreviation ()
virtual QCString trDefinedAtLineInSourceFile ()
virtual QCString trDefinedInSourceFile ()
virtual QCString trDeprecated ()
virtual QCString trCollaborationDiagram (const char *clName)
virtual QCString trInclDepGraph (const char *fName)
virtual QCString trConstructorDocumentation ()
virtual QCString trGotoSourceCode ()
virtual QCString trGotoDocumentation ()
virtual QCString trPrecondition ()
virtual QCString trPostcondition ()
virtual QCString trInvariant ()
virtual QCString trInitialValue ()
virtual QCString trCode ()
virtual QCString trGraphicalHierarchy ()
virtual QCString trGotoGraphicalHierarchy ()
virtual QCString trGotoTextualHierarchy ()
virtual QCString trPageIndex ()
virtual QCString trNote ()
virtual QCString trPublicTypes ()
virtual QCString trPublicAttribs ()
virtual QCString trStaticPublicAttribs ()
virtual QCString trProtectedTypes ()
virtual QCString trProtectedAttribs ()
virtual QCString trStaticProtectedAttribs ()
virtual QCString trPrivateTypes ()
virtual QCString trPrivateAttribs ()
virtual QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const char *name)
virtual QCString trPackageList ()
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool, bool singular)
virtual QCString trFile (bool, bool singular)
virtual QCString trNamespace (bool, bool singular)
virtual QCString trGroup (bool, bool singular)
virtual QCString trPage (bool, bool singular)
virtual QCString trMember (bool, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageMembers ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirDescription ()
virtual QCString trDirReference (const char *dirName)
virtual QCString trDir (bool, bool singular)
virtual QCString trOverloadText ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const char *clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const char *namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool, bool singular)
virtual QCString trSubprogram (bool, bool singular)
virtual QCString trTypeConstraints ()
virtual QCString trDirRelation (const char *name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
virtual QCString trFileIn (const char *name)
virtual QCString trIncludesFileIn (const char *name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
Compiles a date string.
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const char *name)
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const char *name)
virtual QCString trInheritedFrom (const char *members, const char *what)
virtual QCString trAdditionalInheritedMembers ()
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trDesignOverview ()
virtual QCString trInterfaces ()
old style UNO IDL services: implemented interfaces
virtual QCString trServices ()
old style UNO IDL services: inherited services
virtual QCString trConstantGroups ()
UNO IDL constant groups.
virtual QCString trConstantGroupReference (const char *namespaceName)
UNO IDL constant groups.
virtual QCString trServiceReference (const char *sName)
UNO IDL service page title.
virtual QCString trSingletonReference (const char *sName)
UNO IDL singleton page title.
virtual QCString trServiceGeneratedFromFiles (bool single)
UNO IDL service page.
virtual QCString trSingletonGeneratedFromFiles (bool single)
UNO IDL singleton page.
Public Member Functions inherited from TranslatorAdapter_1_8_4
virtual QCString updateNeededMessage ()
Public Member Functions inherited from Translator
virtual ~Translator ()
Additional Inherited Members
Protected Member Functions inherited from TranslatorAdapterBase
virtual ~TranslatorAdapterBase ()
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 139 of file translator_de.h.
Member Function Documentation
idLanguage()
virtual QCString TranslatorGerman::idLanguage () inline virtual
Used for identification of the language. The identification should not be translated. It should be replaced by the name of the language in English using lower-case characters only (e.g. "czech", "japanese", "russian", etc.). It should be equal to the identification used in language.cpp.
Implements Translator.
Definition at line 151 of file translator_de.h.
latexLanguageSupportCommand()
virtual QCString TranslatorGerman::latexLanguageSupportCommand () inline virtual
Used to get the LaTeX command(s) for the language support. This method was designed for languages which do wish to use a babel package.
Implements Translator.
Definition at line 157 of file translator_de.h.
trAdditionalInheritedMembers()
virtual QCString TranslatorGerman::trAdditionalInheritedMembers () inline virtual
Header of the sections with inherited members specific for the base class(es)
Implements Translator.
Definition at line 1979 of file translator_de.h.
trAll()
virtual QCString TranslatorGerman::trAll () inline virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1496 of file translator_de.h.
trAndMore()
virtual QCString TranslatorGerman::trAndMore (const QCString & number) inline virtual
Used in dot graph when UML_LOOK is enabled and there are many fields
Implements Translator.
Definition at line 1954 of file translator_de.h.
trAttention()
virtual QCString TranslatorGerman::trAttention () inline virtual
Implements Translator.
Definition at line 1059 of file translator_de.h.
trAuthor()
virtual QCString TranslatorGerman::trAuthor (bool , bool singular) inline virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 1366 of file translator_de.h.
trBug()
virtual QCString TranslatorGerman::trBug () inline virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 1243 of file translator_de.h.
trBugList()
virtual QCString TranslatorGerman::trBugList () inline virtual
Used as the header of the bug list
Implements Translator.
Definition at line 1249 of file translator_de.h.
trCallerGraph()
virtual QCString TranslatorGerman::trCallerGraph () inline virtual
This is used to introduce a caller (or called-by) graph
Implements Translator.
Definition at line 1625 of file translator_de.h.
trCallGraph()
virtual QCString TranslatorGerman::trCallGraph () inline virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1501 of file translator_de.h.
trCiteReferences()
virtual QCString TranslatorGerman::trCiteReferences () inline virtual
Header for the page with bibliographic citations
Implements Translator.
Definition at line 1930 of file translator_de.h.
trClass()
virtual QCString TranslatorGerman::trClass (bool , bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1286 of file translator_de.h.
trClassDiagram()
virtual QCString TranslatorGerman::trClassDiagram (const char * clName) inline virtual
this text is put before a class diagram
Implements Translator.
Definition at line 571 of file translator_de.h.
trClassDocumentation()
virtual QCString TranslatorGerman::trClassDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all classes, structs and unions.
Implements Translator.
Definition at line 444 of file translator_de.h.
References Config_getBool.
trClasses()
virtual QCString TranslatorGerman::trClasses () inline virtual
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 1200 of file translator_de.h.
References Config_getBool.
trClassHierarchy()
virtual QCString TranslatorGerman::trClassHierarchy () inline virtual
This is put above each page as a link to the class hierarchy
Implements Translator.
Definition at line 245 of file translator_de.h.
trClassHierarchyDescription()
virtual QCString TranslatorGerman::trClassHierarchyDescription () inline virtual
This is an introduction to the class hierarchy.
Implements Translator.
Definition at line 296 of file translator_de.h.
trClassMethods()
virtual QCString TranslatorGerman::trClassMethods () inline virtual
Used as the header of a list of class methods in Objective-C. These are similar to static public member functions in C++.
Implements Translator.
Definition at line 2017 of file translator_de.h.
trCode()
virtual QCString TranslatorGerman::trCode () inline virtual
Text used the source code in the file index
Implements Translator.
Definition at line 942 of file translator_de.h.
trCollaborationDiagram()
virtual QCString TranslatorGerman::trCollaborationDiagram (const char * clName) inline virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 888 of file translator_de.h.
trCompoundIndex()
virtual QCString TranslatorGerman::trCompoundIndex () inline virtual
This is used in LaTeX as the title of the chapter with the annotated compound index.
Implements Translator.
Definition at line 421 of file translator_de.h.
References Config_getBool.
trCompoundIndexFortran()
virtual QCString TranslatorGerman::trCompoundIndexFortran () inline virtual
This is used in LaTeX as the title of the chapter with the annotated compound index (Fortran).
Implements Translator.
Definition at line 1680 of file translator_de.h.
trCompoundList()
virtual QCString TranslatorGerman::trCompoundList () inline virtual
This is put above each page as a link to the list of annotated classes
Implements Translator.
Definition at line 249 of file translator_de.h.
References Config_getBool.
trCompoundListDescription()
virtual QCString TranslatorGerman::trCompoundListDescription () inline virtual
This is an introduction to the annotated compound list.
Implements Translator.
Definition at line 311 of file translator_de.h.
References Config_getBool.
trCompoundListDescriptionFortran()
virtual QCString TranslatorGerman::trCompoundListDescriptionFortran () inline virtual
This is an introduction to the annotated compound list (Fortran).
Implements Translator.
Definition at line 1653 of file translator_de.h.
trCompoundListFortran()
virtual QCString TranslatorGerman::trCompoundListFortran () inline virtual
This is put above each page as a link to the list of annotated data types (Fortran).
Implements Translator.
Definition at line 1645 of file translator_de.h.
trCompoundMembers()
virtual QCString TranslatorGerman::trCompoundMembers () inline virtual
This is put above each page as a link to all members of compounds.
Implements Translator.
Definition at line 266 of file translator_de.h.
References Config_getBool.
trCompoundMembersDescription()
virtual QCString TranslatorGerman::trCompoundMembersDescription (bool extractAll) inline virtual
This is an introduction to the page with all class members.
Implements Translator.
Definition at line 326 of file translator_de.h.
References Config_getBool.
trCompoundMembersDescriptionFortran()
virtual QCString TranslatorGerman::trCompoundMembersDescriptionFortran (bool extractAll) inline virtual
This is an introduction to the page with all data types (Fortran).
Implements Translator.
Definition at line 1657 of file translator_de.h.
trCompoundMembersFortran()
virtual QCString TranslatorGerman::trCompoundMembersFortran () inline virtual
This is put above each page as a link to all members of compounds (Fortran).
Implements Translator.
Definition at line 1649 of file translator_de.h.
trCompoundReference()
virtual QCString TranslatorGerman::trCompoundReference (const char * clName, ClassDef::CompoundType compType, bool isTemplate) inline virtual
used as the title of the HTML page of a class/struct/union
Implements Translator.
Definition at line 651 of file translator_de.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompoundReferenceFortran()
virtual QCString TranslatorGerman::trCompoundReferenceFortran (const char * clName, ClassDef::CompoundType compType, bool isTemplate) inline virtual
used as the title of the HTML page of a module/type (Fortran)
Implements Translator.
Definition at line 1721 of file translator_de.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
virtual QCString TranslatorGerman::trCompounds () inline virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds
Implements Translator.
Definition at line 547 of file translator_de.h.
References Config_getBool.
trConstantGroupReference()
virtual QCString TranslatorGerman::trConstantGroupReference (const char * namespaceName) inline virtual
UNO IDL constant groups.
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 2060 of file translator_de.h.
trConstantGroups()
virtual QCString TranslatorGerman::trConstantGroups () inline virtual
UNO IDL constant groups.
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 2056 of file translator_de.h.
trConstructorDocumentation()
virtual QCString TranslatorGerman::trConstructorDocumentation () inline virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 900 of file translator_de.h.
trCopyright()
virtual QCString TranslatorGerman::trCopyright () inline virtual
Text for copyright paragraph
Implements Translator.
Definition at line 1934 of file translator_de.h.
trDataTypes()
virtual QCString TranslatorGerman::trDataTypes () inline virtual
This is used in the documentation of a file/namespace/group before the list of links to documented compounds (Fortran)
Implements Translator.
Definition at line 1704 of file translator_de.h.
trDate()
virtual QCString TranslatorGerman::trDate () inline virtual
this text is generated when the \date command is used.
Implements Translator.
Definition at line 589 of file translator_de.h.
trDateTime()
virtual QCString TranslatorGerman::trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime) inline virtual
Compiles a date string.
Parameters
year Year in 4 digits
month Month of the year: 1=January
day Day of the Month: 1..31
dayOfWeek Day of the week: 1=Monday..7=Sunday
hour Hour of the day: 0..23
minutes Minutes in the hour: 0..59
seconds Seconds within the minute: 0..59
includeTime Include time in the result string?
Implements Translator.
Definition at line 1908 of file translator_de.h.
trDefinedAtLineInSourceFile()
virtual QCString TranslatorGerman::trDefinedAtLineInSourceFile () inline virtual
Implements Translator.
Definition at line 864 of file translator_de.h.
trDefinedIn()
virtual QCString TranslatorGerman::trDefinedIn () inline virtual
put after an undocumented member in the list of all members
Implements Translator.
Definition at line 233 of file translator_de.h.
trDefinedInSourceFile()
virtual QCString TranslatorGerman::trDefinedInSourceFile () inline virtual
Implements Translator.
Definition at line 869 of file translator_de.h.
trDefineDocumentation()
virtual QCString TranslatorGerman::trDefineDocumentation () inline virtual
This is used in the documentation of a file before the list of documentation blocks for defines
Implements Translator.
Definition at line 517 of file translator_de.h.
trDefines()
virtual QCString TranslatorGerman::trDefines () inline virtual
This is used in the documentation of a file as a header before the list of defines
Implements Translator.
Definition at line 481 of file translator_de.h.
trDefineValue()
virtual QCString TranslatorGerman::trDefineValue () inline virtual
Text shown before a multi-line define
Implements Translator.
Definition at line 1233 of file translator_de.h.
trDeprecated()
virtual QCString TranslatorGerman::trDeprecated () inline virtual
Implements Translator.
Definition at line 878 of file translator_de.h.
trDeprecatedList()
virtual QCString TranslatorGerman::trDeprecatedList () inline virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1423 of file translator_de.h.
trDesignOverview()
virtual QCString TranslatorGerman::trDesignOverview () inline virtual
Used as the title of the design overview picture created for the VHDL output.
Implements Translator.
Definition at line 2040 of file translator_de.h.
trDetailedDescription()
virtual QCString TranslatorGerman::trDetailedDescription () inline virtual
header that is put before the detailed description of files, classes and namespaces.
Implements Translator.
Definition at line 173 of file translator_de.h.
trDetailLevel()
virtual QCString TranslatorGerman::trDetailLevel () inline virtual
Detail level selector shown for hierarchical indices
Implements Translator.
Definition at line 1946 of file translator_de.h.
trDir()
virtual QCString TranslatorGerman::trDir (bool , bool singular) inline virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1599 of file translator_de.h.
trDirDepGraph()
virtual QCString TranslatorGerman::trDirDepGraph (const char * name) inline virtual
Header for the graph showing the directory dependencies
Implements Translator.
Definition at line 1938 of file translator_de.h.
trDirDescription()
virtual QCString TranslatorGerman::trDirDescription () inline virtual
This returns a sentences that introduces the directory hierarchy. and the fact that it is sorted alphabetically per level
Implements Translator.
Definition at line 1585 of file translator_de.h.
trDirDocumentation()
virtual QCString TranslatorGerman::trDirDocumentation () inline virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1573 of file translator_de.h.
trDirectories()
virtual QCString TranslatorGerman::trDirectories () inline virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1579 of file translator_de.h.
trDirIndex()
virtual QCString TranslatorGerman::trDirIndex () inline virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1567 of file translator_de.h.
trDirReference()
virtual QCString TranslatorGerman::trDirReference (const char * dirName) inline virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1593 of file translator_de.h.
trDirRelation()
virtual QCString TranslatorGerman::trDirRelation (const char * name) inline virtual
directory relation for name
Implements Translator.
Definition at line 1847 of file translator_de.h.
trDocumentation()
virtual QCString TranslatorGerman::trDocumentation () inline virtual
This is used in HTML as the title of index.html.
Implements Translator.
Definition at line 403 of file translator_de.h.
trEnumerations()
virtual QCString TranslatorGerman::trEnumerations () inline virtual
This is used in the documentation of a file as a header before the list of enumerations
Implements Translator.
Definition at line 493 of file translator_de.h.
trEnumerationTypeDocumentation()
virtual QCString TranslatorGerman::trEnumerationTypeDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration types
Implements Translator.
Definition at line 529 of file translator_de.h.
trEnumerationValueDocumentation()
virtual QCString TranslatorGerman::trEnumerationValueDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for enumeration values
Implements Translator.
Definition at line 1633 of file translator_de.h.
trEnumerationValues()
virtual QCString TranslatorGerman::trEnumerationValues () inline virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 511 of file translator_de.h.
trEnumGeneratedFromFiles()
virtual QCString TranslatorGerman::trEnumGeneratedFromFiles (bool single) inline virtual
Used file list for a Java enum
Implements Translator.
Definition at line 1958 of file translator_de.h.
trEnumName()
virtual QCString TranslatorGerman::trEnumName () inline virtual
put after an enum name in the list of all members
Implements Translator.
Definition at line 225 of file translator_de.h.
trEnumReference()
virtual QCString TranslatorGerman::trEnumReference (const char * name) inline virtual
Header of a Java enum page (Java enums are represented as classes).
Implements Translator.
Definition at line 1969 of file translator_de.h.
trEnumValue()
virtual QCString TranslatorGerman::trEnumValue () inline virtual
put after an enum value in the list of all members
Implements Translator.
Definition at line 229 of file translator_de.h.
trEventDocumentation()
virtual QCString TranslatorGerman::trEventDocumentation () inline virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1441 of file translator_de.h.
trEvents()
virtual QCString TranslatorGerman::trEvents () inline virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1435 of file translator_de.h.
trExampleDocumentation()
virtual QCString TranslatorGerman::trExampleDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all examples.
Implements Translator.
Definition at line 465 of file translator_de.h.
trExamples()
virtual QCString TranslatorGerman::trExamples () inline virtual
This is put above each page as a link to all examples.
Implements Translator.
Definition at line 288 of file translator_de.h.
trExamplesDescription()
virtual QCString TranslatorGerman::trExamplesDescription () inline virtual
This is an introduction to the page with the list of all examples
Implements Translator.
Definition at line 389 of file translator_de.h.
trExceptions()
virtual QCString TranslatorGerman::trExceptions () inline virtual
this text is generated when the \exception command is used.
Implements Translator.
Definition at line 605 of file translator_de.h.
trExtendsClass()
virtual QCString TranslatorGerman::trExtendsClass () inline virtual
Used in a method of an Objective-C category that extends a class. Note that the @1 marker is required and is replaced by a link to the class method.
Implements Translator.
Definition at line 2009 of file translator_de.h.
trFile()
virtual QCString TranslatorGerman::trFile (bool , bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1297 of file translator_de.h.
trFileDocumentation()
virtual QCString TranslatorGerman::trFileDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all files.
Implements Translator.
Definition at line 459 of file translator_de.h.
trFileIn()
virtual QCString TranslatorGerman::trFileIn (const char * name) inline virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the first column mentions the source file that has a relation to another file.
Implements Translator.
Definition at line 1884 of file translator_de.h.
trFileIndex()
virtual QCString TranslatorGerman::trFileIndex () inline virtual
This is used in LaTeX as the title of the chapter with the list of all files.
Implements Translator.
Definition at line 432 of file translator_de.h.
trFileList()
virtual QCString TranslatorGerman::trFileList () inline virtual
This is put above each page as a link to the list of documented files
Implements Translator.
Definition at line 262 of file translator_de.h.
trFileListDescription()
virtual QCString TranslatorGerman::trFileListDescription (bool extractAll) inline virtual
This is an introduction to the list with all files.
Implements Translator.
Definition at line 302 of file translator_de.h.
trFileMembers()
virtual QCString TranslatorGerman::trFileMembers () inline virtual
This is put above each page as a link to all members of files.
Implements Translator.
Definition at line 279 of file translator_de.h.
trFileMembersDescription()
virtual QCString TranslatorGerman::trFileMembersDescription (bool extractAll) inline virtual
This is an introduction to the page with all file members.
Implements Translator.
Definition at line 368 of file translator_de.h.
References Config_getBool.
trFileReference()
virtual QCString TranslatorGerman::trFileReference (const char * fileName) inline virtual
used as the title of the HTML page of a file
Implements Translator.
Definition at line 673 of file translator_de.h.
trForInternalUseOnly()
virtual QCString TranslatorGerman::trForInternalUseOnly () inline virtual
this text is generated when the \internal command is used.
Implements Translator.
Definition at line 577 of file translator_de.h.
trFriends()
virtual QCString TranslatorGerman::trFriends () inline virtual
used in the class documentation as a header before the list of all friends of a class
Implements Translator.
Definition at line 633 of file translator_de.h.
trFunctionDocumentation()
virtual QCString TranslatorGerman::trFunctionDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for functions
Implements Translator.
Definition at line 535 of file translator_de.h.
trFunctions()
virtual QCString TranslatorGerman::trFunctions () inline virtual
This is used in the documentation of a file as a header before the list of (global) functions
Implements Translator.
Definition at line 499 of file translator_de.h.
trGeneratedAt()
virtual QCString TranslatorGerman::trGeneratedAt (const char * date, const char * projName) inline virtual
This is used in the standard footer of each page and indicates when the page was generated
Implements Translator.
Definition at line 562 of file translator_de.h.
trGeneratedAutomatically()
virtual QCString TranslatorGerman::trGeneratedAutomatically (const char * s) inline virtual
this is put at the author sections at the bottom of man pages. parameter s is name of the project name.
Implements Translator.
Definition at line 217 of file translator_de.h.
trGeneratedBy()
virtual QCString TranslatorGerman::trGeneratedBy () inline virtual
this text is used in the title page of a LaTeX document.
Implements Translator.
Definition at line 609 of file translator_de.h.
trGeneratedFromFiles()
virtual QCString TranslatorGerman::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 821 of file translator_de.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGeneratedFromFilesFortran()
virtual QCString TranslatorGerman::trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single) inline virtual
This is put at the bottom of a module documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 1791 of file translator_de.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
virtual QCString TranslatorGerman::trGlobal (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1352 of file translator_de.h.
trGlobalNamespace()
virtual QCString TranslatorGerman::trGlobalNamespace () inline virtual
Label used for search results in the global namespace
Implements Translator.
Definition at line 1859 of file translator_de.h.
trGotoDocumentation()
virtual QCString TranslatorGerman::trGotoDocumentation () inline virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 912 of file translator_de.h.
trGotoGraphicalHierarchy()
virtual QCString TranslatorGerman::trGotoGraphicalHierarchy () inline virtual
Implements Translator.
Definition at line 952 of file translator_de.h.
trGotoSourceCode()
virtual QCString TranslatorGerman::trGotoSourceCode () inline virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 906 of file translator_de.h.
trGotoTextualHierarchy()
virtual QCString TranslatorGerman::trGotoTextualHierarchy () inline virtual
Implements Translator.
Definition at line 957 of file translator_de.h.
trGraphicalHierarchy()
virtual QCString TranslatorGerman::trGraphicalHierarchy () inline virtual
Implements Translator.
Definition at line 947 of file translator_de.h.
trGroup()
virtual QCString TranslatorGerman::trGroup (bool , bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1319 of file translator_de.h.
trHierarchicalIndex()
virtual QCString TranslatorGerman::trHierarchicalIndex () inline virtual
This is used in LaTeX as the title of the chapter with the class hierarchy.
Implements Translator.
Definition at line 415 of file translator_de.h.
trImplementedFromList()
virtual QCString TranslatorGerman::trImplementedFromList (int numEntries) inline virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 1391 of file translator_de.h.
References trWriteList().
trImplementedInList()
virtual QCString TranslatorGerman::trImplementedInList (int numEntries) inline virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 1399 of file translator_de.h.
References trWriteList().
trInclByDepGraph()
virtual QCString TranslatorGerman::trInclByDepGraph () inline virtual
Implements Translator.
Definition at line 1064 of file translator_de.h.
trInclDepGraph()
virtual QCString TranslatorGerman::trInclDepGraph (const char * fName) inline virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 894 of file translator_de.h.
trIncludesFileIn()
virtual QCString TranslatorGerman::trIncludesFileIn (const char * name) inline virtual
when clicking a directory dependency label, a page with a table is shown. The heading for the second column mentions the destination file that is included.
Implements Translator.
Definition at line 1893 of file translator_de.h.
trIncludingInheritedMembers()
virtual QCString TranslatorGerman::trIncludingInheritedMembers () inline virtual
this is the remainder of the sentence after the class name
Implements Translator.
Definition at line 211 of file translator_de.h.
trInheritedByList()
virtual QCString TranslatorGerman::trInheritedByList (int numEntries) inline virtual
used in class documentation to produce a list of super classes, if class diagrams are disabled.
Implements Translator.
Definition at line 754 of file translator_de.h.
References trWriteList().
trInheritedFrom()
virtual QCString TranslatorGerman::trInheritedFrom (const char * members, const char * what) inline virtual
Used for a section containing inherited members
Implements Translator.
Definition at line 1973 of file translator_de.h.
trInheritsList()
virtual QCString TranslatorGerman::trInheritsList (int numEntries) inline virtual
used in class documentation to produce a list of base classes, if class diagrams are disabled.
Implements Translator.
Definition at line 746 of file translator_de.h.
References trWriteList().
trInitialValue()
virtual QCString TranslatorGerman::trInitialValue () inline virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 936 of file translator_de.h.
trInstanceMethods()
virtual QCString TranslatorGerman::trInstanceMethods () inline virtual
Used as the header of a list of instance methods in Objective-C. These are similar to public member functions in C++.
Implements Translator.
Definition at line 2025 of file translator_de.h.
trInterfaces()
virtual QCString TranslatorGerman::trInterfaces () inline virtual
old style UNO IDL services: implemented interfaces
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 2048 of file translator_de.h.
trInvariant()
virtual QCString TranslatorGerman::trInvariant () inline virtual
Text for the \invariant command
Implements Translator.
Definition at line 930 of file translator_de.h.
trLegend()
virtual QCString TranslatorGerman::trLegend () inline virtual
text for the link to the legend page
Implements Translator.
Definition at line 1158 of file translator_de.h.
trLegendDocs()
virtual QCString TranslatorGerman::trLegendDocs () inline virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 1088 of file translator_de.h.
References getDotImageExtension().
trLegendTitle()
virtual QCString TranslatorGerman::trLegendTitle () inline virtual
title of the graph legend page
Implements Translator.
Definition at line 1080 of file translator_de.h.
trListOfAllMembers()
virtual QCString TranslatorGerman::trListOfAllMembers () inline virtual
put in the class documentation
Implements Translator.
Definition at line 199 of file translator_de.h.
trLoading()
virtual QCString TranslatorGerman::trLoading () inline virtual
Loading message shown when loading search results
Implements Translator.
Definition at line 1853 of file translator_de.h.
trMainPage()
virtual QCString TranslatorGerman::trMainPage () inline virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 851 of file translator_de.h.
trMember()
virtual QCString TranslatorGerman::trMember (bool , bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1341 of file translator_de.h.
trMemberDataDocumentation()
virtual QCString TranslatorGerman::trMemberDataDocumentation () inline virtual
header that is put before the list of member attributes.
Implements Translator.
Definition at line 189 of file translator_de.h.
trMemberEnumerationDocumentation()
virtual QCString TranslatorGerman::trMemberEnumerationDocumentation () inline virtual
header that is put before the list of enumerations.
Implements Translator.
Definition at line 181 of file translator_de.h.
trMemberFunctionDocumentation()
virtual QCString TranslatorGerman::trMemberFunctionDocumentation () inline virtual
header that is put before the list of member functions.
Implements Translator.
Definition at line 185 of file translator_de.h.
trMemberFunctionDocumentationFortran()
virtual QCString TranslatorGerman::trMemberFunctionDocumentationFortran () inline virtual
header that is put before the list of member subprograms (Fortran).
Implements Translator.
Definition at line 1641 of file translator_de.h.
trMemberList()
virtual QCString TranslatorGerman::trMemberList () inline virtual
used as the title of the "list of all members" page of a class
Implements Translator.
Definition at line 203 of file translator_de.h.
trMemberTypedefDocumentation()
virtual QCString TranslatorGerman::trMemberTypedefDocumentation () inline virtual
header that is put before the list of typedefs.
Implements Translator.
Definition at line 177 of file translator_de.h.
trMethodDocumentation()
virtual QCString TranslatorGerman::trMethodDocumentation () inline virtual
Used as the header of the member functions of an Objective-C class.
Implements Translator.
Definition at line 2032 of file translator_de.h.
trModule()
virtual QCString TranslatorGerman::trModule (bool , bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1781 of file translator_de.h.
trModuleDocumentation()
virtual QCString TranslatorGerman::trModuleDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all groups.
Implements Translator.
Definition at line 438 of file translator_de.h.
trModuleIndex()
virtual QCString TranslatorGerman::trModuleIndex () inline virtual
This is used in LaTeX as the title of the chapter with the index of all groups.
Implements Translator.
Definition at line 409 of file translator_de.h.
trModuleReference()
virtual QCString TranslatorGerman::trModuleReference (const char * namespaceName) inline virtual
used as the title of the HTML page of a module (Fortran)
Implements Translator.
Definition at line 1743 of file translator_de.h.
trModules()
virtual QCString TranslatorGerman::trModules () inline virtual
This is put above each page as a link to the list of all groups of compounds or files (see the \group command).
Implements Translator.
Definition at line 241 of file translator_de.h.
trModulesDescription()
virtual QCString TranslatorGerman::trModulesDescription () inline virtual
This is an introduction to the page with the list of class/file groups
Implements Translator.
Definition at line 397 of file translator_de.h.
trModulesIndex()
virtual QCString TranslatorGerman::trModulesIndex () inline virtual
This is used in LaTeX as the title of the chapter with the index of all modules (Fortran).
Implements Translator.
Definition at line 1774 of file translator_de.h.
trModulesList()
virtual QCString TranslatorGerman::trModulesList () inline virtual
used as the title of page containing all the index of all modules (Fortran).
Implements Translator.
Definition at line 1708 of file translator_de.h.
trModulesListDescription()
virtual QCString TranslatorGerman::trModulesListDescription (bool extractAll) inline virtual
used as an introduction to the modules list (Fortran)
Implements Translator.
Definition at line 1712 of file translator_de.h.
trModulesMemberDescription()
virtual QCString TranslatorGerman::trModulesMemberDescription (bool extractAll) inline virtual
This is an introduction to the page with all modules members (Fortran)
Implements Translator.
Definition at line 1755 of file translator_de.h.
trModulesMembers()
virtual QCString TranslatorGerman::trModulesMembers () inline virtual
This is put above each page as a link to all members of modules. (Fortran)
Implements Translator.
Definition at line 1751 of file translator_de.h.
trMore()
virtual QCString TranslatorGerman::trMore () inline virtual
this is the text of a link put after brief descriptions.
Implements Translator.
Definition at line 195 of file translator_de.h.
trNamespace()
virtual QCString TranslatorGerman::trNamespace (bool , bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1308 of file translator_de.h.
trNamespaceDocumentation()
virtual QCString TranslatorGerman::trNamespaceDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all namespaces.
Implements Translator.
Definition at line 801 of file translator_de.h.
trNamespaceIndex()
virtual QCString TranslatorGerman::trNamespaceIndex () inline virtual
This is used in LaTeX as the title of the chapter with the index of all namespaces.
Implements Translator.
Definition at line 795 of file translator_de.h.
trNamespaceList()
virtual QCString TranslatorGerman::trNamespaceList () inline virtual
used as the title of page containing all the index of all namespaces.
Implements Translator.
Definition at line 618 of file translator_de.h.
trNamespaceListDescription()
virtual QCString TranslatorGerman::trNamespaceListDescription (bool extractAll) inline virtual
used as an introduction to the namespace list
Implements Translator.
Definition at line 622 of file translator_de.h.
trNamespaceMemberDescription()
virtual QCString TranslatorGerman::trNamespaceMemberDescription (bool extractAll) inline virtual
This is an introduction to the page with all namespace members
Implements Translator.
Definition at line 780 of file translator_de.h.
trNamespaceMembers()
virtual QCString TranslatorGerman::trNamespaceMembers () inline virtual
This is put above each page as a link to all members of namespaces.
Implements Translator.
Definition at line 776 of file translator_de.h.
trNamespaceReference()
virtual QCString TranslatorGerman::trNamespaceReference (const char * namespaceName) inline virtual
used as the title of the HTML page of a namespace
Implements Translator.
Definition at line 681 of file translator_de.h.
trNamespaces()
virtual QCString TranslatorGerman::trNamespaces () inline virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 811 of file translator_de.h.
trNoMatches()
virtual QCString TranslatorGerman::trNoMatches () inline virtual
Text shown when no search results are found
Implements Translator.
Definition at line 1871 of file translator_de.h.
trNote()
virtual QCString TranslatorGerman::trNote () inline virtual
Implements Translator.
Definition at line 972 of file translator_de.h.
trOverloadText()
virtual QCString TranslatorGerman::trOverloadText () inline virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1613 of file translator_de.h.
trPackage()
virtual QCString TranslatorGerman::trPackage (const char * name) inline virtual
Used as the title of a Java package
Implements Translator.
Definition at line 1209 of file translator_de.h.
trPackageAttribs()
virtual QCString TranslatorGerman::trPackageAttribs () inline virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1476 of file translator_de.h.
trPackageList()
virtual QCString TranslatorGerman::trPackageList () inline virtual
Title of the package index page
Implements Translator.
Definition at line 1215 of file translator_de.h.
trPackageListDescription()
virtual QCString TranslatorGerman::trPackageListDescription () inline virtual
The description of the package index page
Implements Translator.
Definition at line 1221 of file translator_de.h.
trPackageMembers()
virtual QCString TranslatorGerman::trPackageMembers () inline virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1460 of file translator_de.h.
trPackages()
virtual QCString TranslatorGerman::trPackages () inline virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 1227 of file translator_de.h.
trPackageTypes()
virtual QCString TranslatorGerman::trPackageTypes () inline virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1452 of file translator_de.h.
trPage()
virtual QCString TranslatorGerman::trPage (bool , bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1330 of file translator_de.h.
trPageAbbreviation()
virtual QCString TranslatorGerman::trPageAbbreviation () inline virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 857 of file translator_de.h.
trPageDocumentation()
virtual QCString TranslatorGerman::trPageDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all related pages.
Implements Translator.
Definition at line 471 of file translator_de.h.
trPageIndex()
virtual QCString TranslatorGerman::trPageIndex () inline virtual
Implements Translator.
Definition at line 962 of file translator_de.h.
trPanelSynchronisationTooltip()
virtual QCString TranslatorGerman::trPanelSynchronisationTooltip (bool enable) inline virtual
Used as a tooltip for the toggle button thatappears in the navigation tree in the HTML output when GENERATE_TREEVIEW is enabled. This tooltip explains the meaning of the button.
Implements Translator.
Definition at line 1990 of file translator_de.h.
trParameters()
virtual QCString TranslatorGerman::trParameters () inline virtual
this text is generated when the \param command is used.
Implements Translator.
Definition at line 601 of file translator_de.h.
trPostcondition()
virtual QCString TranslatorGerman::trPostcondition () inline virtual
Text for the \post command
Implements Translator.
Definition at line 924 of file translator_de.h.
trPrecondition()
virtual QCString TranslatorGerman::trPrecondition () inline virtual
Text for the \pre command
Implements Translator.
Definition at line 918 of file translator_de.h.
trPrivateAttribs()
virtual QCString TranslatorGerman::trPrivateAttribs () inline virtual
Implements Translator.
Definition at line 1019 of file translator_de.h.
trPrivateMembers()
virtual QCString TranslatorGerman::trPrivateMembers () inline virtual
Implements Translator.
Definition at line 709 of file translator_de.h.
trPrivateSlots()
virtual QCString TranslatorGerman::trPrivateSlots () inline virtual
Implements Translator.
Definition at line 712 of file translator_de.h.
trPrivateTypes()
virtual QCString TranslatorGerman::trPrivateTypes () inline virtual
Implements Translator.
Definition at line 1014 of file translator_de.h.
trProperties()
virtual QCString TranslatorGerman::trProperties () inline virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 1184 of file translator_de.h.
trPropertyDocumentation()
virtual QCString TranslatorGerman::trPropertyDocumentation () inline virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 1190 of file translator_de.h.
trProtectedAttribs()
virtual QCString TranslatorGerman::trProtectedAttribs () inline virtual
Implements Translator.
Definition at line 1004 of file translator_de.h.
trProtectedMembers()
virtual QCString TranslatorGerman::trProtectedMembers () inline virtual
Implements Translator.
Definition at line 700 of file translator_de.h.
trProtectedSlots()
virtual QCString TranslatorGerman::trProtectedSlots () inline virtual
Implements Translator.
Definition at line 703 of file translator_de.h.
trProtectedTypes()
virtual QCString TranslatorGerman::trProtectedTypes () inline virtual
Implements Translator.
Definition at line 999 of file translator_de.h.
trProvidedByCategory()
virtual QCString TranslatorGerman::trProvidedByCategory () inline virtual
Used in a method of an Objective-C class that is declared in a a category. Note that the @1 marker is required and is replaced by a link.
Implements Translator.
Definition at line 2000 of file translator_de.h.
trPublicAttribs()
virtual QCString TranslatorGerman::trPublicAttribs () inline virtual
Implements Translator.
Definition at line 982 of file translator_de.h.
References Config_getBool.
trPublicMembers()
virtual QCString TranslatorGerman::trPublicMembers () inline virtual
Implements Translator.
Definition at line 688 of file translator_de.h.
trPublicSlots()
virtual QCString TranslatorGerman::trPublicSlots () inline virtual
Implements Translator.
Definition at line 691 of file translator_de.h.
trPublicTypes()
virtual QCString TranslatorGerman::trPublicTypes () inline virtual
Implements Translator.
Definition at line 977 of file translator_de.h.
trReferencedBy()
virtual QCString TranslatorGerman::trReferencedBy () inline virtual
Implements Translator.
Definition at line 1049 of file translator_de.h.
trReferenceManual()
virtual QCString TranslatorGerman::trReferenceManual () inline virtual
This is used in LaTeX as the title of the document
Implements Translator.
Definition at line 475 of file translator_de.h.
trReferences()
virtual QCString TranslatorGerman::trReferences () inline virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 1379 of file translator_de.h.
trReimplementedFromList()
virtual QCString TranslatorGerman::trReimplementedFromList (int numEntries) inline virtual
used in member documentation blocks to produce a list of members that are hidden by this one.
Implements Translator.
Definition at line 762 of file translator_de.h.
References trWriteList().
trReimplementedInList()
virtual QCString TranslatorGerman::trReimplementedInList (int numEntries) inline virtual
used in member documentation blocks to produce a list of all member that overwrite the implementation of this member.
Implements Translator.
Definition at line 770 of file translator_de.h.
References trWriteList().
trRelatedFunctionDocumentation()
virtual QCString TranslatorGerman::trRelatedFunctionDocumentation () inline virtual
used in the class documentation as a header before the list of all related classes
Implements Translator.
Definition at line 643 of file translator_de.h.
trRelatedFunctions()
virtual QCString TranslatorGerman::trRelatedFunctions () inline virtual
used in the compound documentation before a list of related functions.
Implements Translator.
Definition at line 165 of file translator_de.h.
trRelatedPages()
virtual QCString TranslatorGerman::trRelatedPages () inline virtual
This is put above each page as a link to all related pages.
Implements Translator.
Definition at line 284 of file translator_de.h.
trRelatedPagesDescription()
virtual QCString TranslatorGerman::trRelatedPagesDescription () inline virtual
This is an introduction to the page with the list of related pages
Implements Translator.
Definition at line 393 of file translator_de.h.
trRelatedSubscript()
virtual QCString TranslatorGerman::trRelatedSubscript () inline virtual
subscript for the related functions.
Implements Translator.
Definition at line 169 of file translator_de.h.
trRemarks()
virtual QCString TranslatorGerman::trRemarks () inline virtual
Implements Translator.
Definition at line 1054 of file translator_de.h.
trReturns()
virtual QCString TranslatorGerman::trReturns () inline virtual
this text is generated when the \return command is used.
Implements Translator.
Definition at line 593 of file translator_de.h.
trReturnValues()
virtual QCString TranslatorGerman::trReturnValues () inline virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 846 of file translator_de.h.
trRTFansicp()
virtual QCString TranslatorGerman::trRTFansicp () inline virtual
Used as ansicpg for RTF file. See translator_en.h for details.
Implements Translator.
Definition at line 1259 of file translator_de.h.
trRTFCharSet()
virtual QCString TranslatorGerman::trRTFCharSet () inline virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 1267 of file translator_de.h.
trRTFGeneralIndex()
virtual QCString TranslatorGerman::trRTFGeneralIndex () inline virtual
Used as header RTF general index
Implements Translator.
Definition at line 1273 of file translator_de.h.
trRTFTableOfContents()
virtual QCString TranslatorGerman::trRTFTableOfContents () inline virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1411 of file translator_de.h.
trSearch()
virtual QCString TranslatorGerman::trSearch () inline virtual
This is put above each page as a link to the search engine.
Implements Translator.
Definition at line 292 of file translator_de.h.
trSearching()
virtual QCString TranslatorGerman::trSearching () inline virtual
Message shown while searching
Implements Translator.
Definition at line 1865 of file translator_de.h.
trSearchMatches()
virtual QCString TranslatorGerman::trSearchMatches () inline virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1544 of file translator_de.h.
trSearchResults()
virtual QCString TranslatorGerman::trSearchResults (int numDocuments) inline virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1525 of file translator_de.h.
trSearchResultsTitle()
virtual QCString TranslatorGerman::trSearchResultsTitle () inline virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1513 of file translator_de.h.
trSeeAlso()
virtual QCString TranslatorGerman::trSeeAlso () inline virtual
this text is generated when the \sa command is used.
Implements Translator.
Definition at line 597 of file translator_de.h.
trServiceGeneratedFromFiles()
virtual QCString TranslatorGerman::trServiceGeneratedFromFiles (bool single) inline virtual
UNO IDL service page.
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 2082 of file translator_de.h.
trServiceReference()
virtual QCString TranslatorGerman::trServiceReference (const char * sName) inline virtual
UNO IDL service page title.
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 2068 of file translator_de.h.
trServices()
virtual QCString TranslatorGerman::trServices () inline virtual
old style UNO IDL services: inherited services
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 2052 of file translator_de.h.
trSignals()
virtual QCString TranslatorGerman::trSignals () inline virtual
Implements Translator.
Definition at line 694 of file translator_de.h.
trSince()
virtual QCString TranslatorGerman::trSince () inline virtual
Implements Translator.
Definition at line 1070 of file translator_de.h.
trSingletonGeneratedFromFiles()
virtual QCString TranslatorGerman::trSingletonGeneratedFromFiles (bool single) inline virtual
UNO IDL singleton page.
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 2090 of file translator_de.h.
trSingletonReference()
virtual QCString TranslatorGerman::trSingletonReference (const char * sName) inline virtual
UNO IDL singleton page title.
Reimplemented from TranslatorAdapter_1_8_4.
Definition at line 2075 of file translator_de.h.
trSourceFile()
virtual QCString TranslatorGerman::trSourceFile (QCString & filename) inline virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1555 of file translator_de.h.
trStaticPackageAttribs()
virtual QCString TranslatorGerman::trStaticPackageAttribs () inline virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1484 of file translator_de.h.
trStaticPackageMembers()
virtual QCString TranslatorGerman::trStaticPackageMembers () inline virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1468 of file translator_de.h.
trStaticPrivateAttribs()
virtual QCString TranslatorGerman::trStaticPrivateAttribs () inline virtual
Implements Translator.
Definition at line 1024 of file translator_de.h.
trStaticPrivateMembers()
virtual QCString TranslatorGerman::trStaticPrivateMembers () inline virtual
Implements Translator.
Definition at line 715 of file translator_de.h.
trStaticProtectedAttribs()
virtual QCString TranslatorGerman::trStaticProtectedAttribs () inline virtual
Implements Translator.
Definition at line 1009 of file translator_de.h.
trStaticProtectedMembers()
virtual QCString TranslatorGerman::trStaticProtectedMembers () inline virtual
Implements Translator.
Definition at line 706 of file translator_de.h.
trStaticPublicAttribs()
virtual QCString TranslatorGerman::trStaticPublicAttribs () inline virtual
Implements Translator.
Definition at line 994 of file translator_de.h.
trStaticPublicMembers()
virtual QCString TranslatorGerman::trStaticPublicMembers () inline virtual
Implements Translator.
Definition at line 697 of file translator_de.h.
trSubprogram()
virtual QCString TranslatorGerman::trSubprogram (bool , bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1829 of file translator_de.h.
trSubprogramDocumentation()
virtual QCString TranslatorGerman::trSubprogramDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for subprograms (Fortran)
Implements Translator.
Definition at line 1698 of file translator_de.h.
trSubprograms()
virtual QCString TranslatorGerman::trSubprograms () inline virtual
This is used in the documentation of a file as a header before the list of (global) subprograms (Fortran).
Implements Translator.
Definition at line 1692 of file translator_de.h.
trTemplateParameters()
virtual QCString TranslatorGerman::trTemplateParameters () inline virtual
Section header for list of template parameters
Implements Translator.
Definition at line 1950 of file translator_de.h.
trTest()
virtual QCString TranslatorGerman::trTest () inline virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 1168 of file translator_de.h.
trTestList()
virtual QCString TranslatorGerman::trTestList () inline virtual
Used as the header of the test list
Implements Translator.
Definition at line 1174 of file translator_de.h.
trThisIsTheListOfAllMembers()
virtual QCString TranslatorGerman::trThisIsTheListOfAllMembers () inline virtual
this is the first part of a sentence that is followed by a class name
Implements Translator.
Definition at line 207 of file translator_de.h.
trTodo()
virtual QCString TranslatorGerman::trTodo () inline virtual
Used as a marker that is put before a \todo item
Implements Translator.
Definition at line 1034 of file translator_de.h.
trTodoList()
virtual QCString TranslatorGerman::trTodoList () inline virtual
Used as the header of the todo list
Implements Translator.
Definition at line 1040 of file translator_de.h.
trType()
virtual QCString TranslatorGerman::trType (bool , bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 1818 of file translator_de.h.
trTypeConstraints()
virtual QCString TranslatorGerman::trTypeConstraints () inline virtual
C# Type Constraint list
Implements Translator.
Definition at line 1837 of file translator_de.h.
trTypedefDocumentation()
virtual QCString TranslatorGerman::trTypedefDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for typedefs
Implements Translator.
Definition at line 523 of file translator_de.h.
trTypedefs()
virtual QCString TranslatorGerman::trTypedefs () inline virtual
This is used in the documentation of a file as a header before the list of typedefs
Implements Translator.
Definition at line 487 of file translator_de.h.
trTypeDocumentation()
virtual QCString TranslatorGerman::trTypeDocumentation () inline virtual
This is used in LaTeX as the title of the chapter containing the documentation of all data types (Fortran).
Implements Translator.
Definition at line 1686 of file translator_de.h.
trVariableDocumentation()
virtual QCString TranslatorGerman::trVariableDocumentation () inline virtual
This is used in the documentation of a file/namespace before the list of documentation blocks for variables
Implements Translator.
Definition at line 541 of file translator_de.h.
trVariables()
virtual QCString TranslatorGerman::trVariables () inline virtual
This is used in the documentation of a file as a header before the list of (global) variables
Implements Translator.
Definition at line 505 of file translator_de.h.
trVersion()
virtual QCString TranslatorGerman::trVersion () inline virtual
this text is generated when the \version command is used.
Implements Translator.
Definition at line 585 of file translator_de.h.
trWarning()
virtual QCString TranslatorGerman::trWarning () inline virtual
this text is generated when the \warning command is used.
Implements Translator.
Definition at line 581 of file translator_de.h.
trWriteList()
virtual QCString TranslatorGerman::trWriteList (int numEntries) inline virtual
this function is used to produce a comma-separated list of items. use generateMarker(i) to indicate where item i should be put.
Implements Translator.
Definition at line 721 of file translator_de.h.
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
The documentation for this class was generated from the following file:
src/translator_de.h