Doxygen: SymbolContext::Private Class Reference
SymbolContext::Private Class Reference
Public Member Functions
Private (const Definition *d, const Definition *prev, const Definition *next)
TemplateVariant get (const char *n) const
TemplateVariant fileName () const
TemplateVariant anchor () const
TemplateVariant scope () const
TemplateVariant relPath () const
Private Attributes
const Definition * m_def
const Definition * m_prevDef
const Definition * m_nextDef
Static Private Attributes
static PropertyMapper< SymbolContext::Private > s_inst
Detailed Description
Definition at line 9451 of file context.cpp.
Constructor & Destructor Documentation
Private()
SymbolContext::Private::Private (const Definition * d, const Definition * prev, const Definition * next) inline
Definition at line 9454 of file context.cpp.
References PropertyMapper< T >::addProperty(), anchor(), fileName(), Config::init(), relPath(), s_inst, and scope().
Member Function Documentation
anchor()
TemplateVariant SymbolContext::Private::anchor () const inline
Definition at line 9475 of file context.cpp.
References Definition::anchor(), and m_def.
Referenced by Private().
fileName()
TemplateVariant SymbolContext::Private::fileName () const inline
Definition at line 9471 of file context.cpp.
References Definition::getOutputFileBase(), and m_def.
Referenced by Private().
get()
TemplateVariant SymbolContext::Private::get (const char * n) const inline
Definition at line 9467 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by SymbolContext::get().
relPath()
TemplateVariant SymbolContext::Private::relPath () const inline
Definition at line 9547 of file context.cpp.
References externalRef(), Definition::getReference(), and m_def.
Referenced by Private().
scope()
TemplateVariant SymbolContext::Private::scope () const inline
Definition at line 9479 of file context.cpp.
References MemberDef::argsString(), convertToXML(), DefinitionIntf::definitionType(), Definition::displayName(), Definition::getBodyDef(), MemberDef::getClassDef(), MemberDef::getFileDef(), Definition::getLanguage(), getLanguageSpecificSeparator(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), Doxygen::globalScope, MemberDef::isFunction(), MemberDef::isSignal(), MemberDef::isSlot(), Definition::localName(), m_def, m_nextDef, m_prevDef, Definition::name(), Definition::qualifiedName(), theTranslator, Translator::trGlobalNamespace(), DefinitionIntf::TypeClass, DefinitionIntf::TypeMember, and DefinitionIntf::TypeNamespace.
Referenced by Private().
Member Data Documentation
m_def
const Definition* SymbolContext::Private::m_def private
Definition at line 9552 of file context.cpp.
Referenced by anchor(), fileName(), relPath(), and scope().
m_nextDef
const Definition* SymbolContext::Private::m_nextDef private
Definition at line 9554 of file context.cpp.
Referenced by scope().
m_prevDef
const Definition* SymbolContext::Private::m_prevDef private
Definition at line 9553 of file context.cpp.
Referenced by scope().
s_inst
PropertyMapper< SymbolContext::Private > SymbolContext::Private::s_inst static private
Definition at line 9555 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp