Doxygen: Config Namespace Reference
Config Namespace Reference
Public function to deal with the configuration file.
Functions
void init ()
void writeTemplate (FTextStream &t, bool shortList, bool updateOnly=FALSE)
bool parse (const char *fileName, bool update=FALSE)
void postProcess (bool clearHeaderAndFooter)
void checkAndCorrect ()
void deinit ()
Detailed Description
Public function to deal with the configuration file.
Function Documentation
checkAndCorrect()
void Config::checkAndCorrect ()
Check the validity of the parsed options and correct or warn the user where needed.
Referenced by checkConfiguration(), and readConfiguration().
deinit()
void Config::deinit ()
Clean up any data
Referenced by generateOutput().
init()
void Config::init ()
Initialize configuration variables to their default value
Referenced by DoxygenContext::Private::Private(), TranslateContext::Private::Private(), IncludeInfoContext::Private::Private(), ClassContext::Private::Private(), NamespaceContext::Private::Private(), FileContext::Private::Private(), DirContext::Private::Private(), PageContext::Private::Private(), MemberContext::Private::Private(), ModuleContext::Private::Private(), ClassIndexContext::Private::Private(), ClassHierarchyContext::Private::Private(), NestingNodeContext::Private::Private(), ClassTreeContext::Private::Private(), NamespaceTreeContext::Private::Private(), FileTreeContext::Private::Private(), PageTreeContext::Private::Private(), ModuleTreeContext::Private::Private(), NavPathElemContext::Private::Private(), ExampleTreeContext::Private::Private(), GlobalsIndexContext::Private::Private(), ClassMembersIndexContext::Private::Private(), NamespaceMembersIndexContext::Private::Private(), InheritanceGraphContext::Private::Private(), InheritanceNodeContext::Private::Private(), MemberInfoContext::Private::Private(), MemberGroupInfoContext::Private::Private(), MemberListInfoContext::Private::Private(), InheritedMemberInfoContext::Private::Private(), ArgumentContext::Private::Private(), SymbolContext::Private::Private(), SymbolGroupContext::Private::Private(), SymbolIndexContext::Private::Private(), SearchIndexContext::Private::Private(), processMarkdown(), readConfiguration(), and MemberDef::writeDocumentation().
parse()
bool Config::parse (const char * fileName, bool update = FALSE)
Parses a configuration file with name fn.
Returns
TRUE if successful, FALSE if the file could not be opened or read.
Referenced by readConfiguration().
postProcess()
void Config::postProcess (bool clearHeaderAndFooter)
Post processed the parsed data. Replaces raw string values by the actual values. and replaces environment variables.
Parameters
clearHeaderAndFooter set to TRUE when writing header and footer templates.
Referenced by checkConfiguration(), and readConfiguration().
writeTemplate()
void Config::writeTemplate (FTextStream & t, bool shortList, bool updateOnly = FALSE)
Writes a template configuration to stream t. If shortList is TRUE the description of each configuration option will be omitted.
Referenced by generateConfigFile().