Doxygen: TagFileParser Class Reference
TagFileParser Class Reference
Tag file parser.
Classes
class EndElementHandler
class StartElementHandler
Public Member Functions
TagFileParser (const char *tagName)
void setDocumentLocator (QXmlLocator *locator)
void setFileName (const QString &fileName)
void warn (const char *fmt)
void warn (const char *fmt, const char *s)
void startCompound (const QXmlAttributes &attrib)
void endCompound ()
void startMember (const QXmlAttributes &attrib)
void endMember ()
void startEnumValue (const QXmlAttributes &attrib)
void endEnumValue ()
void endDocAnchor ()
void endClass ()
void endNamespace ()
void endFile ()
void endPage ()
void endDir ()
void startStringValue (const QXmlAttributes &)
void startDocAnchor (const QXmlAttributes &attrib)
void endType ()
void endName ()
void startBase (const QXmlAttributes &attrib)
void endBase ()
void startIncludes (const QXmlAttributes &attrib)
void endIncludes ()
void endTemplateArg ()
void endFilename ()
void endPath ()
void endAnchor ()
void endClangId ()
void endAnchorFile ()
void endArglist ()
void endTitle ()
void endSubgroup ()
void startIgnoreElement (const QXmlAttributes &)
void endIgnoreElement ()
bool startDocument ()
bool startElement (const QString &, const QString &, const QString &name, const QXmlAttributes &attrib)
bool endElement (const QString &, const QString &, const QString &name)
bool characters (const QString &ch)
void dump ()
void buildLists (Entry *root)
void addIncludes ()
Private Types
enum State {
Invalid, InClass, InFile, InNamespace,
InGroup, InPage, InMember, InEnumValue,
InPackage, InDir, InTempArgList
}
Private Member Functions
void buildMemberList (Entry *ce, QList< TagMemberInfo > &members)
void addDocAnchors (Entry *e, const TagAnchorInfoList &l)
Private Attributes
QList< TagClassInfo > m_tagFileClasses
QList< TagFileInfo > m_tagFileFiles
QList< TagNamespaceInfo > m_tagFileNamespaces
QList< TagGroupInfo > m_tagFileGroups
QList< TagPageInfo > m_tagFilePages
QList< TagPackageInfo > m_tagFilePackages
QList< TagDirInfo > m_tagFileDirs
QDict< StartElementHandler > m_startElementHandlers
QDict< EndElementHandler > m_endElementHandlers
TagClassInfo * m_curClass
TagFileInfo * m_curFile
TagNamespaceInfo * m_curNamespace
TagPackageInfo * m_curPackage
TagGroupInfo * m_curGroup
TagPageInfo * m_curPage
TagDirInfo * m_curDir
TagMemberInfo * m_curMember
TagEnumValueInfo * m_curEnumValue
TagIncludeInfo * m_curIncludes
QCString m_curString
QCString m_tagName
QCString m_fileName
QCString m_title
State m_state
QStack< State > m_stateStack
QXmlLocator * m_locator
QCString m_inputFileName
Detailed Description
Tag file parser.
Reads an XML-structured tagfile and builds up the structure in memory. The method buildLists() is used to transfer/translate the structures to the doxygen engine.
Definition at line 211 of file tagreader.cpp.
Member Enumeration Documentation
State
enum TagFileParser::State private
Enumerator
Invalid
InClass
InFile
InNamespace
InGroup
InPage
InMember
InEnumValue
InPackage
InDir
InTempArgList
Definition at line 213 of file tagreader.cpp.
Constructor & Destructor Documentation
TagFileParser()
TagFileParser::TagFileParser (const char * tagName) inline
Definition at line 248 of file tagreader.cpp.
References Invalid, m_curClass, m_curDir, m_curEnumValue, m_curFile, m_curGroup, m_curIncludes, m_curMember, m_curNamespace, m_curPackage, m_curPage, m_endElementHandlers, m_locator, m_startElementHandlers, and m_state.
Member Function Documentation
addDocAnchors()
void TagFileParser::addDocAnchors (Entry * e, const TagAnchorInfoList & l) private
Definition at line 1143 of file tagreader.cpp.
References SectionInfo::Anchor, Entry::anchors, SDict< T >::append(), TagAnchorInfo::fileName, TagAnchorInfo::label, m_tagName, Doxygen::sectionDict, TagAnchorInfo::title, and warn().
Referenced by buildLists(), and buildMemberList().
addIncludes()
void TagFileParser::addIncludes ()
Definition at line 1480 of file tagreader.cpp.
References FileDef::addIncludeDependency(), FileDef::getOutputFileBase(), FileDef::getPath(), TagIncludeInfo::id, TagFileInfo::includes, Doxygen::inputNameDict, TagIncludeInfo::isImported, TagIncludeInfo::isLocal, m_tagFileFiles, m_tagName, TagIncludeInfo::name, TagFileInfo::name, TagFileInfo::path, and TagIncludeInfo::text.
Referenced by parseTagFile().
buildLists()
void TagFileParser::buildLists (Entry * root)
Injects the info gathered by the XML parser into the Entry tree. This tree contains the information extracted from the input in a "unrelated" form.
Definition at line 1304 of file tagreader.cpp.
References addDocAnchors(), Entry::addSubEntry(), Entry::args, TagClassInfo::bases, buildMemberList(), TagClassInfo::Category, Entry::Category, TagClassInfo::clangId, TagNamespaceInfo::clangId, TagClassInfo::Class, Entry::CLASS_SEC, TagClassInfo::docAnchors, TagNamespaceInfo::docAnchors, TagPackageInfo::docAnchors, TagFileInfo::docAnchors, TagGroupInfo::docAnchors, TagPageInfo::docAnchors, TagClassInfo::Enum, Entry::Enum, TagClassInfo::Exception, Entry::Exception, Entry::extends, TagInfo::fileName, TagClassInfo::filename, TagNamespaceInfo::filename, TagPackageInfo::filename, TagFileInfo::filename, TagGroupInfo::filename, TagPageInfo::filename, Entry::fileName, Entry::GROUPDOC_SEC, guessSection(), Entry::id, Doxygen::inputNameDict, Doxygen::inputNameList, TagClassInfo::Interface, Entry::Interface, TagClassInfo::isObjC, TagClassInfo::kind, Entry::lang, m_tagFileClasses, m_tagFileFiles, m_tagFileGroups, m_tagFileNamespaces, m_tagFilePackages, m_tagFilePages, m_tagName, Entry::MAINPAGEDOC_SEC, TagClassInfo::members, TagNamespaceInfo::members, TagPackageInfo::members, TagFileInfo::members, TagGroupInfo::members, Argument::name, TagClassInfo::name, TagNamespaceInfo::name, TagPackageInfo::name, TagFileInfo::name, TagGroupInfo::name, TagPageInfo::name, Entry::name, Entry::NAMESPACE_SEC, Entry::PACKAGE_SEC, Entry::PAGEDOC_SEC, TagFileInfo::path, TagClassInfo::Protocol, Entry::Protocol, Entry::section, TagClassInfo::Service, Entry::Service, TagClassInfo::Singleton, Entry::Singleton, Entry::spec, SrcLangExt_ObjC, SrcLangExt_Unknown, stripPath(), TagClassInfo::Struct, Entry::Struct, Entry::tagInfo, TagInfo::tagName, Entry::tArgLists, TagClassInfo::templateArguments, TagGroupInfo::title, TagPageInfo::title, Argument::type, Entry::type, TagClassInfo::Union, and Entry::Union.
Referenced by parseTagFile().
buildMemberList()
void TagFileParser::buildMemberList (Entry * ce, QList< TagMemberInfo > & members) private
Definition at line 1165 of file tagreader.cpp.
References addDocAnchors(), Entry::addSubEntry(), TagInfo::anchor, TagEnumValueInfo::anchor, TagMemberInfo::anchor, TagMemberInfo::anchorFile, TagMemberInfo::arglist, Entry::argList, Entry::args, TagEnumValueInfo::clangid, TagMemberInfo::clangId, DCOP, Entry::DEFINE_SEC, TagMemberInfo::docAnchors, Entry::ENUM_SEC, TagMemberInfo::enumValues, Event, TagEnumValueInfo::file, TagInfo::fileName, Entry::fileName, Entry::FUNCTION_SEC, Entry::GROUPDOC_SEC, Grouping::GROUPING_INGROUP, Entry::groups, Entry::id, TagMemberInfo::isStatic, TagMemberInfo::kind, m_tagName, Method, Entry::mtype, TagEnumValueInfo::name, TagMemberInfo::name, Entry::name, Property, TagMemberInfo::prot, Entry::protection, Entry::section, Signal, Slot, Entry::spec, Entry::stat, stringToArgumentList(), Entry::Strong, Entry::tagInfo, TagInfo::tagName, TagMemberInfo::type, Entry::type, Entry::VARIABLE_SEC, TagMemberInfo::virt, and Entry::virt.
Referenced by buildLists().
characters()
bool TagFileParser::characters (const QString & ch) inline
Definition at line 901 of file tagreader.cpp.
References m_curString.
dump()
void TagFileParser::dump ()
Dumps the internal structures. For debugging only!
Definition at line 973 of file tagreader.cpp.
References TagMemberInfo::anchor, TagMemberInfo::arglist, TagClassInfo::bases, TagNamespaceInfo::classList, TagFileInfo::classList, TagGroupInfo::classList, TagGroupInfo::fileList, TagDirInfo::fileList, TagClassInfo::filename, TagNamespaceInfo::filename, TagFileInfo::filename, TagGroupInfo::filename, TagPageInfo::filename, TagIncludeInfo::id, TagFileInfo::includes, TagMemberInfo::kind, m_tagFileClasses, m_tagFileDirs, m_tagFileFiles, m_tagFileGroups, m_tagFileNamespaces, m_tagFilePages, TagClassInfo::members, TagNamespaceInfo::members, TagFileInfo::members, TagGroupInfo::members, msg(), BaseInfo::name, TagMemberInfo::name, TagClassInfo::name, TagNamespaceInfo::name, TagIncludeInfo::name, TagFileInfo::name, TagGroupInfo::name, TagPageInfo::name, TagDirInfo::name, TagFileInfo::namespaceList, TagGroupInfo::namespaceList, TagGroupInfo::pageList, TagDirInfo::path, TagDirInfo::subdirList, TagGroupInfo::subgroupList, and TagPageInfo::title.
endAnchor()
void TagFileParser::endAnchor () inline
Definition at line 711 of file tagreader.cpp.
References TagMemberInfo::anchor, InMember, m_curMember, m_curString, m_state, and warn().
Referenced by startDocument().
endAnchorFile()
void TagFileParser::endAnchorFile () inline
Definition at line 745 of file tagreader.cpp.
References TagMemberInfo::anchorFile, InMember, m_curMember, m_curString, m_state, and warn().
Referenced by startDocument().
endArglist()
void TagFileParser::endArglist () inline
Definition at line 757 of file tagreader.cpp.
References TagMemberInfo::arglist, InMember, m_curMember, m_curString, m_state, and warn().
Referenced by startDocument().
endBase()
void TagFileParser::endBase () inline
Definition at line 634 of file tagreader.cpp.
References TagClassInfo::bases, InClass, m_curClass, m_curString, m_state, and warn().
Referenced by startDocument().
endClangId()
void TagFileParser::endClangId () inline
Definition at line 723 of file tagreader.cpp.
References TagMemberInfo::clangId, TagClassInfo::clangId, TagNamespaceInfo::clangId, InClass, InMember, InNamespace, m_curClass, m_curMember, m_curNamespace, m_curString, m_state, and warn().
Referenced by startDocument().
endClass()
void TagFileParser::endClass () inline
Definition at line 508 of file tagreader.cpp.
References TagClassInfo::classList, TagNamespaceInfo::classList, TagPackageInfo::classList, TagFileInfo::classList, TagGroupInfo::classList, InClass, InFile, InGroup, InNamespace, InPackage, m_curClass, m_curFile, m_curGroup, m_curNamespace, m_curPackage, m_curString, m_state, and warn().
Referenced by startDocument().
endCompound()
void TagFileParser::endCompound () inline
Definition at line 393 of file tagreader.cpp.
References InClass, InDir, InFile, InGroup, InNamespace, InPackage, InPage, m_curClass, m_curDir, m_curFile, m_curGroup, m_curNamespace, m_curPackage, m_curPage, m_state, m_tagFileClasses, m_tagFileDirs, m_tagFileFiles, m_tagFileGroups, m_tagFileNamespaces, m_tagFilePackages, m_tagFilePages, and warn().
Referenced by startDocument().
endDir()
void TagFileParser::endDir () inline
Definition at line 551 of file tagreader.cpp.
References InDir, m_curDir, m_curString, m_state, TagDirInfo::subdirList, and warn().
Referenced by startDocument().
endDocAnchor()
void TagFileParser::endDocAnchor () inline
Definition at line 492 of file tagreader.cpp.
References TagMemberInfo::docAnchors, TagClassInfo::docAnchors, TagNamespaceInfo::docAnchors, TagPackageInfo::docAnchors, TagFileInfo::docAnchors, TagGroupInfo::docAnchors, TagPageInfo::docAnchors, TagDirInfo::docAnchors, InClass, InDir, InFile, InGroup, InMember, InNamespace, InPackage, InPage, m_curClass, m_curDir, m_curFile, m_curGroup, m_curMember, m_curNamespace, m_curPackage, m_curPage, m_curString, m_fileName, m_state, m_title, and warn().
Referenced by startDocument().
endElement()
bool TagFileParser::endElement (const QString & , const QString & , const QString & name) inline
Definition at line 886 of file tagreader.cpp.
References m_endElementHandlers, and warn().
endEnumValue()
void TagFileParser::endEnumValue () inline
Definition at line 480 of file tagreader.cpp.
References TagMemberInfo::enumValues, InMember, m_curEnumValue, m_curMember, m_curString, m_state, m_stateStack, and TagEnumValueInfo::name.
Referenced by startDocument().
endFile()
void TagFileParser::endFile () inline
Definition at line 532 of file tagreader.cpp.
References TagGroupInfo::fileList, TagDirInfo::fileList, InDir, InGroup, m_curDir, m_curGroup, m_curString, m_state, and warn().
Referenced by startDocument().
endFilename()
void TagFileParser::endFilename () inline
Definition at line 686 of file tagreader.cpp.
References TagClassInfo::filename, TagNamespaceInfo::filename, TagPackageInfo::filename, TagFileInfo::filename, TagGroupInfo::filename, TagPageInfo::filename, TagDirInfo::filename, InClass, InDir, InFile, InGroup, InNamespace, InPackage, InPage, m_curClass, m_curDir, m_curFile, m_curGroup, m_curNamespace, m_curPackage, m_curPage, m_curString, m_state, and warn().
Referenced by startDocument().
endIgnoreElement()
void TagFileParser::endIgnoreElement () inline
Definition at line 794 of file tagreader.cpp.
Referenced by startDocument().
endIncludes()
void TagFileParser::endIncludes () inline
Definition at line 664 of file tagreader.cpp.
References m_curIncludes, m_curString, and TagIncludeInfo::text.
Referenced by startDocument().
endMember()
void TagFileParser::endMember () inline
Definition at line 447 of file tagreader.cpp.
References InClass, InFile, InGroup, InNamespace, InPackage, m_curClass, m_curFile, m_curGroup, m_curMember, m_curNamespace, m_curPackage, m_state, m_stateStack, TagClassInfo::members, TagNamespaceInfo::members, TagPackageInfo::members, TagFileInfo::members, TagGroupInfo::members, and warn().
Referenced by startDocument().
endName()
void TagFileParser::endName () inline
Definition at line 584 of file tagreader.cpp.
References InClass, InDir, InFile, InGroup, InMember, InNamespace, InPackage, InPage, m_curClass, m_curDir, m_curFile, m_curGroup, m_curMember, m_curNamespace, m_curPackage, m_curPage, m_curString, m_state, TagMemberInfo::name, TagClassInfo::name, TagNamespaceInfo::name, TagPackageInfo::name, TagFileInfo::name, TagGroupInfo::name, TagPageInfo::name, TagDirInfo::name, and warn().
Referenced by startDocument().
endNamespace()
void TagFileParser::endNamespace () inline
Definition at line 521 of file tagreader.cpp.
References TagNamespaceInfo::classList, InFile, InGroup, InNamespace, m_curFile, m_curGroup, m_curNamespace, m_curString, m_state, TagFileInfo::namespaceList, TagGroupInfo::namespaceList, and warn().
Referenced by startDocument().
endPage()
void TagFileParser::endPage () inline
Definition at line 542 of file tagreader.cpp.
References TagGroupInfo::fileList, InGroup, m_curGroup, m_curString, m_state, and warn().
Referenced by startDocument().
endPath()
void TagFileParser::endPath () inline
Definition at line 701 of file tagreader.cpp.
References InDir, InFile, m_curDir, m_curFile, m_curString, m_state, TagFileInfo::path, TagDirInfo::path, and warn().
Referenced by startDocument().
endSubgroup()
void TagFileParser::endSubgroup () inline
Definition at line 778 of file tagreader.cpp.
References InGroup, m_curGroup, m_curString, m_state, TagGroupInfo::subgroupList, and warn().
Referenced by startDocument().
endTemplateArg()
void TagFileParser::endTemplateArg () inline
Definition at line 669 of file tagreader.cpp.
References InClass, m_curClass, m_curString, m_state, TagClassInfo::templateArguments, and warn().
Referenced by startDocument().
endTitle()
void TagFileParser::endTitle () inline
Definition at line 768 of file tagreader.cpp.
References InGroup, InPage, m_curGroup, m_curPage, m_curString, m_state, TagGroupInfo::title, TagPageInfo::title, and warn().
Referenced by startDocument().
endType()
void TagFileParser::endType () inline
Definition at line 572 of file tagreader.cpp.
References InMember, m_curMember, m_curString, m_state, TagMemberInfo::type, and warn().
Referenced by startDocument().
setDocumentLocator()
void TagFileParser::setDocumentLocator (QXmlLocator * locator) inline
Definition at line 268 of file tagreader.cpp.
References m_locator.
setFileName()
void TagFileParser::setFileName (const QString & fileName) inline
Definition at line 273 of file tagreader.cpp.
References m_inputFileName.
Referenced by parseTagFile().
startBase()
void TagFileParser::startBase (const QXmlAttributes & attrib) inline
Definition at line 600 of file tagreader.cpp.
References TagClassInfo::bases, InClass, m_curClass, m_curString, m_state, Normal, Private, Protected, Public, Virtual, and warn().
Referenced by startDocument().
startCompound()
void TagFileParser::startCompound (const QXmlAttributes & attrib) inline
Definition at line 287 of file tagreader.cpp.
References TagClassInfo::Category, TagClassInfo::Class, TagClassInfo::Enum, TagClassInfo::Exception, InClass, InDir, InFile, InGroup, InNamespace, InPackage, InPage, TagClassInfo::Interface, Invalid, TagClassInfo::isObjC, TagClassInfo::kind, m_curClass, m_curDir, m_curFile, m_curGroup, m_curNamespace, m_curPackage, m_curPage, m_curString, m_state, TagClassInfo::Protocol, TagClassInfo::Service, TagClassInfo::Singleton, TagClassInfo::Struct, TagClassInfo::Union, and warn().
Referenced by startDocument().
startDocAnchor()
void TagFileParser::startDocAnchor (const QXmlAttributes & attrib) inline
Definition at line 565 of file tagreader.cpp.
References m_curString, m_fileName, and m_title.
Referenced by startDocument().
startDocument()
bool TagFileParser::startDocument () inline
Definition at line 798 of file tagreader.cpp.
References endAnchor(), endAnchorFile(), endArglist(), endBase(), endClangId(), endClass(), endCompound(), endDir(), endDocAnchor(), endEnumValue(), endFile(), endFilename(), endIgnoreElement(), endIncludes(), endMember(), endName(), endNamespace(), endPage(), endPath(), endSubgroup(), endTemplateArg(), endTitle(), endType(), Invalid, m_curClass, m_curDir, m_curFile, m_curGroup, m_curNamespace, m_curPackage, m_curPage, m_endElementHandlers, m_startElementHandlers, m_state, m_stateStack, m_tagFileClasses, m_tagFileDirs, m_tagFileFiles, m_tagFileGroups, m_tagFileNamespaces, m_tagFilePackages, m_tagFilePages, startBase(), startCompound(), startDocAnchor(), startEnumValue(), startIgnoreElement(), startIncludes(), startMember(), and startStringValue().
startElement()
bool TagFileParser::startElement (const QString & , const QString & , const QString & name, const QXmlAttributes & attrib) inline
Definition at line 870 of file tagreader.cpp.
References m_startElementHandlers, and warn().
startEnumValue()
void TagFileParser::startEnumValue (const QXmlAttributes & attrib) inline
Definition at line 462 of file tagreader.cpp.
References TagEnumValueInfo::anchor, TagEnumValueInfo::clangid, TagEnumValueInfo::file, InEnumValue, InMember, m_curEnumValue, m_curString, m_state, m_stateStack, and warn().
Referenced by startDocument().
startIgnoreElement()
void TagFileParser::startIgnoreElement (const QXmlAttributes &) inline
Definition at line 790 of file tagreader.cpp.
Referenced by startDocument().
startIncludes()
void TagFileParser::startIncludes (const QXmlAttributes & attrib) inline
Definition at line 646 of file tagreader.cpp.
References TagIncludeInfo::id, TagFileInfo::includes, InFile, TagIncludeInfo::isImported, TagIncludeInfo::isLocal, m_curFile, m_curIncludes, m_curString, m_state, TagIncludeInfo::name, and warn().
Referenced by startDocument().
startMember()
void TagFileParser::startMember (const QXmlAttributes & attrib) inline
Definition at line 416 of file tagreader.cpp.
References InMember, TagMemberInfo::isStatic, TagMemberInfo::kind, m_curMember, m_state, m_stateStack, Private, TagMemberInfo::prot, Protected, Pure, TagMemberInfo::virt, and Virtual.
Referenced by startDocument().
startStringValue()
void TagFileParser::startStringValue (const QXmlAttributes &) inline
Definition at line 560 of file tagreader.cpp.
References m_curString.
Referenced by startDocument().
warn() [1/2]
void TagFileParser::warn (const char * fmt) inline
Definition at line 278 of file tagreader.cpp.
References m_inputFileName, and m_locator.
Referenced by addDocAnchors(), endAnchor(), endAnchorFile(), endArglist(), endBase(), endClangId(), endClass(), endCompound(), endDir(), endDocAnchor(), endElement(), endFile(), endFilename(), endMember(), endName(), endNamespace(), endPage(), endPath(), endSubgroup(), endTemplateArg(), endTitle(), endType(), startBase(), startCompound(), startElement(), startEnumValue(), startIncludes(), and warn().
warn() [2/2]
void TagFileParser::warn (const char * fmt, const char * s) inline
Definition at line 282 of file tagreader.cpp.
References m_inputFileName, m_locator, and warn().
Member Data Documentation
m_curClass
TagClassInfo* TagFileParser::m_curClass private
Definition at line 923 of file tagreader.cpp.
Referenced by endBase(), endClangId(), endClass(), endCompound(), endDocAnchor(), endFilename(), endMember(), endName(), endTemplateArg(), startBase(), startCompound(), startDocument(), and TagFileParser().
m_curDir
TagDirInfo* TagFileParser::m_curDir private
Definition at line 929 of file tagreader.cpp.
Referenced by endCompound(), endDir(), endDocAnchor(), endFile(), endFilename(), endName(), endPath(), startCompound(), startDocument(), and TagFileParser().
m_curEnumValue
TagEnumValueInfo* TagFileParser::m_curEnumValue private
Definition at line 931 of file tagreader.cpp.
Referenced by endEnumValue(), startEnumValue(), and TagFileParser().
m_curFile
TagFileInfo* TagFileParser::m_curFile private
Definition at line 924 of file tagreader.cpp.
Referenced by endClass(), endCompound(), endDocAnchor(), endFilename(), endMember(), endName(), endNamespace(), endPath(), startCompound(), startDocument(), startIncludes(), and TagFileParser().
m_curGroup
TagGroupInfo* TagFileParser::m_curGroup private
Definition at line 927 of file tagreader.cpp.
Referenced by endClass(), endCompound(), endDocAnchor(), endFile(), endFilename(), endMember(), endName(), endNamespace(), endPage(), endSubgroup(), endTitle(), startCompound(), startDocument(), and TagFileParser().
m_curIncludes
TagIncludeInfo* TagFileParser::m_curIncludes private
Definition at line 932 of file tagreader.cpp.
Referenced by endIncludes(), startIncludes(), and TagFileParser().
m_curMember
TagMemberInfo* TagFileParser::m_curMember private
Definition at line 930 of file tagreader.cpp.
Referenced by endAnchor(), endAnchorFile(), endArglist(), endClangId(), endDocAnchor(), endEnumValue(), endMember(), endName(), endType(), startMember(), and TagFileParser().
m_curNamespace
TagNamespaceInfo* TagFileParser::m_curNamespace private
Definition at line 925 of file tagreader.cpp.
Referenced by endClangId(), endClass(), endCompound(), endDocAnchor(), endFilename(), endMember(), endName(), endNamespace(), startCompound(), startDocument(), and TagFileParser().
m_curPackage
TagPackageInfo* TagFileParser::m_curPackage private
Definition at line 926 of file tagreader.cpp.
Referenced by endClass(), endCompound(), endDocAnchor(), endFilename(), endMember(), endName(), startCompound(), startDocument(), and TagFileParser().
m_curPage
TagPageInfo* TagFileParser::m_curPage private
Definition at line 928 of file tagreader.cpp.
Referenced by endCompound(), endDocAnchor(), endFilename(), endName(), endTitle(), startCompound(), startDocument(), and TagFileParser().
m_curString
QCString TagFileParser::m_curString private
Definition at line 933 of file tagreader.cpp.
Referenced by characters(), endAnchor(), endAnchorFile(), endArglist(), endBase(), endClangId(), endClass(), endDir(), endDocAnchor(), endEnumValue(), endFile(), endFilename(), endIncludes(), endName(), endNamespace(), endPage(), endPath(), endSubgroup(), endTemplateArg(), endTitle(), endType(), startBase(), startCompound(), startDocAnchor(), startEnumValue(), startIncludes(), and startStringValue().
m_endElementHandlers
QDict<EndElementHandler> TagFileParser::m_endElementHandlers private
Definition at line 922 of file tagreader.cpp.
Referenced by endElement(), startDocument(), and TagFileParser().
m_fileName
QCString TagFileParser::m_fileName private
Definition at line 935 of file tagreader.cpp.
Referenced by endDocAnchor(), and startDocAnchor().
m_inputFileName
QCString TagFileParser::m_inputFileName private
Definition at line 940 of file tagreader.cpp.
Referenced by setFileName(), and warn().
m_locator
QXmlLocator* TagFileParser::m_locator private
Definition at line 939 of file tagreader.cpp.
Referenced by setDocumentLocator(), TagFileParser(), and warn().
m_startElementHandlers
QDict<StartElementHandler> TagFileParser::m_startElementHandlers private
Definition at line 921 of file tagreader.cpp.
Referenced by startDocument(), startElement(), and TagFileParser().
m_state
State TagFileParser::m_state private
Definition at line 937 of file tagreader.cpp.
Referenced by endAnchor(), endAnchorFile(), endArglist(), endBase(), endClangId(), endClass(), endCompound(), endDir(), endDocAnchor(), endEnumValue(), endFile(), endFilename(), endMember(), endName(), endNamespace(), endPage(), endPath(), endSubgroup(), endTemplateArg(), endTitle(), endType(), startBase(), startCompound(), startDocument(), startEnumValue(), startIncludes(), startMember(), and TagFileParser().
m_stateStack
QStack<State> TagFileParser::m_stateStack private
Definition at line 938 of file tagreader.cpp.
Referenced by endEnumValue(), endMember(), startDocument(), startEnumValue(), and startMember().
m_tagFileClasses
QList<TagClassInfo> TagFileParser::m_tagFileClasses private
Definition at line 914 of file tagreader.cpp.
Referenced by buildLists(), dump(), endCompound(), and startDocument().
m_tagFileDirs
QList<TagDirInfo> TagFileParser::m_tagFileDirs private
Definition at line 920 of file tagreader.cpp.
Referenced by dump(), endCompound(), and startDocument().
m_tagFileFiles
QList<TagFileInfo> TagFileParser::m_tagFileFiles private
Definition at line 915 of file tagreader.cpp.
Referenced by addIncludes(), buildLists(), dump(), endCompound(), and startDocument().
m_tagFileGroups
QList<TagGroupInfo> TagFileParser::m_tagFileGroups private
Definition at line 917 of file tagreader.cpp.
Referenced by buildLists(), dump(), endCompound(), and startDocument().
m_tagFileNamespaces
QList<TagNamespaceInfo> TagFileParser::m_tagFileNamespaces private
Definition at line 916 of file tagreader.cpp.
Referenced by buildLists(), dump(), endCompound(), and startDocument().
m_tagFilePackages
QList<TagPackageInfo> TagFileParser::m_tagFilePackages private
Definition at line 919 of file tagreader.cpp.
Referenced by buildLists(), endCompound(), and startDocument().
m_tagFilePages
QList<TagPageInfo> TagFileParser::m_tagFilePages private
Definition at line 918 of file tagreader.cpp.
Referenced by buildLists(), dump(), endCompound(), and startDocument().
m_tagName
QCString TagFileParser::m_tagName private
Definition at line 934 of file tagreader.cpp.
Referenced by addDocAnchors(), addIncludes(), buildLists(), and buildMemberList().
m_title
QCString TagFileParser::m_title private
Definition at line 936 of file tagreader.cpp.
Referenced by endDocAnchor(), and startDocAnchor().
The documentation for this class was generated from the following file:
src/tagreader.cpp