Doxygen: src/xmldocvisitor.cpp File Reference
xmldocvisitor.cpp File Reference
#include <qfileinfo.h>
#include "xmldocvisitor.h"
#include "docparser.h"
#include "language.h"
#include "doxygen.h"
#include "outputgen.h"
#include "xmlgen.h"
#include "dot.h"
#include "message.h"
#include "util.h"
#include "parserintf.h"
#include "filename.h"
#include "config.h"
#include "htmlentity.h"
Functions
static void visitCaption (XmlDocVisitor *parent, QList< DocNode > children)
static void visitPreStart (FTextStream &t, const char *cmd, const bool doCaption, XmlDocVisitor *parent, QList< DocNode > children, const QCString &name, bool writeType, DocImage::Type type, const QCString &width, const QCString &height)
static void visitPostEnd (FTextStream &t, const char *cmd)
Function Documentation
visitCaption()
static void visitCaption (XmlDocVisitor * parent, QList< DocNode > children) static
Definition at line 35 of file xmldocvisitor.cpp.
References DocNode::accept().
Referenced by visitPreStart().
visitPostEnd()
static void visitPostEnd (FTextStream & t, const char * cmd) static
Definition at line 81 of file xmldocvisitor.cpp.
References endl().
Referenced by XmlDocVisitor::visit(), and XmlDocVisitor::visitPost().
visitPreStart()
static void visitPreStart (FTextStream & t, const char * cmd, const bool doCaption, XmlDocVisitor * parent, QList< DocNode > children, const QCString & name, bool writeType, DocImage::Type type, const QCString & width, const QCString & height) static
Definition at line 42 of file xmldocvisitor.cpp.
References convertToXML(), DocImage::DocBook, DocImage::Html, DocImage::Latex, DocImage::Rtf, and visitCaption().
Referenced by XmlDocVisitor::visit(), and XmlDocVisitor::visitPre().