Doxygen: PageContext Class Reference
PageContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static PageContext * alloc (PageDef *pd, bool isMainPage, bool isExample)
Private Member Functions
PageContext (PageDef *, bool isMainPage, bool isExample)
~PageContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 329 of file context.h.
Constructor & Destructor Documentation
PageContext()
PageContext::PageContext (PageDef * pd, bool isMainPage, bool isExample) private
Definition at line 3697 of file context.cpp.
References p, and Private.
Referenced by alloc().
~PageContext()
PageContext::~PageContext () private
Definition at line 3702 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int PageContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 336 of file context.h.
References RefCountedContext::addRef().
alloc()
static PageContext* PageContext::alloc (PageDef * pd, bool isMainPage, bool isExample) inline static
Definition at line 332 of file context.h.
References PageContext().
Referenced by PageListContext::Private::addPages(), ModuleContext::Private::examples(), generateOutputViaTemplate(), NestingNodeContext::Private::getPage(), ModuleContext::Private::pages(), and ExampleListContext::Private::Private().
get()
TemplateVariant PageContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 3707 of file context.cpp.
References PageContext::Private::get(), and p.
release()
virtual int PageContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 337 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* PageContext::p private
Definition at line 342 of file context.h.
Referenced by get(), PageContext(), and ~PageContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp