Doxygen: DocImage Class Reference
DocImage Class Reference
Node representing an image.
#include <docparser.h>
Public Types
enum Type { Html, Latex, Rtf, DocBook }
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Public Member Functions
DocImage (DocNode *parent, const HtmlAttribList &attribs, const QCString &name, Type t, const QCString &url=QCString())
Kind kind () const
Type type () const
QCString name () const
bool hasCaption () const
QCString width () const
QCString height () const
QCString relPath () const
QCString url () const
const HtmlAttribList & attribs () const
void accept (DocVisitor *v)
void parse ()
Public Member Functions inherited from CompAccept< DocImage >
CompAccept ()
virtual ~CompAccept ()
void accept (DocImage *obj, DocVisitor *v)
const QList< DocNode > & children () const
QList< DocNode > & children ()
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Attributes
HtmlAttribList m_attribs
QCString m_name
Type m_type
QCString m_width
QCString m_height
QCString m_relPath
QCString m_url
Additional Inherited Members
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from CompAccept< DocImage >
QList< DocNode > m_children
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Node representing an image.
Definition at line 688 of file docparser.h.
Member Enumeration Documentation
Type
enum DocImage::Type
Enumerator
Html
Latex
Rtf
DocBook
Definition at line 691 of file docparser.h.
Constructor & Destructor Documentation
DocImage()
DocImage::DocImage (DocNode * parent, const HtmlAttribList & attribs, const QCString & name, Type t, const QCString & url = QCString())
Definition at line 2934 of file docparser.cpp.
References DocNode::m_parent, and DocNode::parent().
Member Function Documentation
accept()
void DocImage::accept (DocVisitor * v) inline virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 703 of file docparser.h.
References CompAccept< T >::accept().
attribs()
const HtmlAttribList& DocImage::attribs () const inline
Definition at line 702 of file docparser.h.
References m_attribs.
Referenced by HtmlDocVisitor::visitPre().
hasCaption()
bool DocImage::hasCaption () const inline
Definition at line 697 of file docparser.h.
References CompAccept< DocImage >::m_children.
Referenced by RTFDocVisitor::visitPost(), HtmlDocVisitor::visitPost(), LatexDocVisitor::visitPost(), RTFDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), and LatexDocVisitor::visitPre().
height()
QCString DocImage::height () const inline
Definition at line 699 of file docparser.h.
References m_height.
Referenced by HtmlDocVisitor::visitPre(), XmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
kind()
Kind DocImage::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 694 of file docparser.h.
References DocNode::Kind_Image.
name()
QCString DocImage::name () const inline
Definition at line 696 of file docparser.h.
References m_name.
Referenced by DocbookDocVisitor::visitPost(), DocbookDocVisitor::visitPre(), RTFDocVisitor::visitPre(), XmlDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
parse()
void DocImage::parse ()
Definition at line 2943 of file docparser.cpp.
References CMD_IMAGE, defaultHandleTitleAndSize(), CompAccept< DocImage >::m_children, m_height, and m_width.
Referenced by DocPara::handleImage().
relPath()
QCString DocImage::relPath () const inline
Definition at line 700 of file docparser.h.
References m_relPath.
Referenced by HtmlDocVisitor::visitPre().
type()
Type DocImage::type () const inline
Definition at line 695 of file docparser.h.
References m_type.
Referenced by DocbookDocVisitor::visitPost(), RTFDocVisitor::visitPost(), HtmlDocVisitor::visitPost(), LatexDocVisitor::visitPost(), DocbookDocVisitor::visitPre(), RTFDocVisitor::visitPre(), XmlDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
url()
QCString DocImage::url () const inline
Definition at line 701 of file docparser.h.
References m_url.
Referenced by HtmlDocVisitor::visitPre().
width()
QCString DocImage::width () const inline
Definition at line 698 of file docparser.h.
References m_width.
Referenced by HtmlDocVisitor::visitPre(), XmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), and PrintDocVisitor::visitPre().
Member Data Documentation
m_attribs
HtmlAttribList DocImage::m_attribs private
Definition at line 707 of file docparser.h.
Referenced by attribs().
m_height
QCString DocImage::m_height private
Definition at line 711 of file docparser.h.
Referenced by height(), and parse().
m_name
QCString DocImage::m_name private
Definition at line 708 of file docparser.h.
Referenced by name().
m_relPath
QCString DocImage::m_relPath private
Definition at line 712 of file docparser.h.
Referenced by relPath().
m_type
Type DocImage::m_type private
Definition at line 709 of file docparser.h.
Referenced by type().
m_url
QCString DocImage::m_url private
Definition at line 713 of file docparser.h.
Referenced by url().
m_width
QCString DocImage::m_width private
Definition at line 710 of file docparser.h.
Referenced by parse(), and width().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp