Doxygen: TranslatorSlovene Class Reference
TranslatorSlovene Class Reference
#include <translator_si.h>
Public Member Functions
QCString idLanguage ()
QCString latexLanguageSupportCommand ()
QCString trRelatedFunctions ()
QCString trRelatedSubscript ()
QCString trDetailedDescription ()
QCString trMemberTypedefDocumentation ()
QCString trMemberEnumerationDocumentation ()
QCString trMemberFunctionDocumentation ()
QCString trMemberDataDocumentation ()
QCString trMore ()
QCString trListOfAllMembers ()
QCString trMemberList ()
QCString trThisIsTheListOfAllMembers ()
QCString trIncludingInheritedMembers ()
QCString trGeneratedAutomatically (const char *s)
QCString trEnumName ()
QCString trEnumValue ()
QCString trDefinedIn ()
QCString trModules ()
QCString trClassHierarchy ()
QCString trCompoundList ()
QCString trFileList ()
QCString trCompoundMembers ()
QCString trFileMembers ()
QCString trRelatedPages ()
QCString trExamples ()
QCString trSearch ()
QCString trClassHierarchyDescription ()
QCString trFileListDescription (bool extractAll)
QCString trCompoundListDescription ()
QCString trCompoundMembersDescription (bool extractAll)
QCString trFileMembersDescription (bool extractAll)
QCString trExamplesDescription ()
QCString trRelatedPagesDescription ()
QCString trModulesDescription ()
QCString trDocumentation ()
QCString trModuleIndex ()
QCString trHierarchicalIndex ()
QCString trCompoundIndex ()
QCString trFileIndex ()
QCString trModuleDocumentation ()
QCString trClassDocumentation ()
QCString trFileDocumentation ()
QCString trExampleDocumentation ()
QCString trPageDocumentation ()
QCString trReferenceManual ()
QCString trDefines ()
QCString trTypedefs ()
QCString trEnumerations ()
QCString trFunctions ()
QCString trVariables ()
QCString trEnumerationValues ()
QCString trDefineDocumentation ()
QCString trTypedefDocumentation ()
QCString trEnumerationTypeDocumentation ()
QCString trFunctionDocumentation ()
QCString trVariableDocumentation ()
QCString trCompounds ()
QCString trGeneratedAt (const char *date, const char *projName)
QCString trClassDiagram (const char *clName)
QCString trForInternalUseOnly ()
QCString trWarning ()
QCString trVersion ()
QCString trDate ()
QCString trReturns ()
QCString trSeeAlso ()
QCString trParameters ()
QCString trExceptions ()
QCString trGeneratedBy ()
QCString trNamespaceList ()
QCString trNamespaceListDescription (bool extractAll)
QCString trFriends ()
QCString trRelatedFunctionDocumentation ()
QCString trCompoundReference (const char *clName, ClassDef::CompoundType compType, bool)
QCString trFileReference (const char *fileName)
QCString trNamespaceReference (const char *namespaceName)
QCString trPublicMembers ()
QCString trPublicSlots ()
QCString trSignals ()
QCString trStaticPublicMembers ()
QCString trProtectedMembers ()
QCString trProtectedSlots ()
QCString trStaticProtectedMembers ()
QCString trPrivateMembers ()
QCString trPrivateSlots ()
QCString trStaticPrivateMembers ()
QCString trWriteList (int numEntries)
QCString trInheritsList (int numEntries)
QCString trInheritedByList (int numEntries)
QCString trReimplementedFromList (int numEntries)
QCString trReimplementedInList (int numEntries)
QCString trNamespaceMembers ()
QCString trNamespaceMemberDescription (bool extractAll)
QCString trNamespaceIndex ()
QCString trNamespaceDocumentation ()
virtual QCString trNamespaces ()
QCString trGeneratedFromFiles (ClassDef::CompoundType compType, bool single)
QCString trReturnValues ()
QCString trMainPage ()
QCString trPageAbbreviation ()
QCString trDefinedAtLineInSourceFile ()
QCString trDefinedInSourceFile ()
QCString trDeprecated ()
QCString trCollaborationDiagram (const char *clName)
QCString trInclDepGraph (const char *fName)
QCString trConstructorDocumentation ()
QCString trGotoSourceCode ()
QCString trGotoDocumentation ()
QCString trPrecondition ()
QCString trPostcondition ()
QCString trInvariant ()
QCString trInitialValue ()
QCString trCode ()
QCString trGraphicalHierarchy ()
QCString trGotoGraphicalHierarchy ()
QCString trGotoTextualHierarchy ()
QCString trPageIndex ()
QCString trNote ()
QCString trPublicTypes ()
QCString trPublicAttribs ()
QCString trStaticPublicAttribs ()
QCString trProtectedTypes ()
QCString trProtectedAttribs ()
QCString trStaticProtectedAttribs ()
QCString trPrivateTypes ()
QCString trPrivateAttribs ()
QCString trStaticPrivateAttribs ()
virtual QCString trTodo ()
virtual QCString trTodoList ()
virtual QCString trReferencedBy ()
virtual QCString trRemarks ()
virtual QCString trAttention ()
virtual QCString trInclByDepGraph ()
virtual QCString trSince ()
virtual QCString trLegendTitle ()
virtual QCString trLegendDocs ()
virtual QCString trLegend ()
virtual QCString trTest ()
virtual QCString trTestList ()
virtual QCString trProperties ()
virtual QCString trPropertyDocumentation ()
virtual QCString trClasses ()
virtual QCString trPackage (const char *name)
virtual QCString trPackageList ()
virtual QCString trPackageListDescription ()
virtual QCString trPackages ()
virtual QCString trDefineValue ()
virtual QCString trBug ()
virtual QCString trBugList ()
virtual QCString trRTFansicp ()
virtual QCString trRTFCharSet ()
virtual QCString trRTFGeneralIndex ()
virtual QCString trClass (bool first_capital, bool singular)
virtual QCString trFile (bool first_capital, bool singular)
virtual QCString trNamespace (bool first_capital, bool singular)
virtual QCString trGroup (bool first_capital, bool singular)
virtual QCString trPage (bool first_capital, bool singular)
virtual QCString trMember (bool first_capital, bool singular)
virtual QCString trGlobal (bool first_capital, bool singular)
virtual QCString trAuthor (bool first_capital, bool singular)
virtual QCString trReferences ()
virtual QCString trImplementedFromList (int numEntries)
virtual QCString trImplementedInList (int numEntries)
virtual QCString trRTFTableOfContents ()
virtual QCString trDeprecatedList ()
virtual QCString trEvents ()
virtual QCString trEventDocumentation ()
virtual QCString trPackageTypes ()
virtual QCString trPackageMembers ()
virtual QCString trStaticPackageMembers ()
virtual QCString trPackageAttribs ()
virtual QCString trStaticPackageAttribs ()
virtual QCString trAll ()
virtual QCString trCallGraph ()
virtual QCString trSearchResultsTitle ()
virtual QCString trSearchResults (int numDocuments)
virtual QCString trSearchMatches ()
virtual QCString trSourceFile (QCString &filename)
virtual QCString trDirIndex ()
virtual QCString trDirDocumentation ()
virtual QCString trDirectories ()
virtual QCString trDirDescription ()
virtual QCString trDirReference (const char *dirName)
virtual QCString trDir (bool first_capital, bool singular)
virtual QCString trOverloadText ()
Public Member Functions inherited from TranslatorAdapter_1_4_6
virtual QCString updateNeededMessage ()
virtual QCString trCallerGraph ()
virtual QCString trEnumerationValueDocumentation ()
Public Member Functions inherited from TranslatorAdapter_1_5_4
virtual QCString trMemberFunctionDocumentationFortran ()
virtual QCString trCompoundListFortran ()
virtual QCString trCompoundMembersFortran ()
virtual QCString trCompoundListDescriptionFortran ()
virtual QCString trCompoundMembersDescriptionFortran (bool extractAll)
virtual QCString trCompoundIndexFortran ()
virtual QCString trTypeDocumentation ()
virtual QCString trSubprograms ()
virtual QCString trSubprogramDocumentation ()
virtual QCString trDataTypes ()
virtual QCString trModulesList ()
virtual QCString trModulesListDescription (bool extractAll)
virtual QCString trCompoundReferenceFortran (const char *clName, ClassDef::CompoundType compType, bool isTemplate)
virtual QCString trModuleReference (const char *namespaceName)
virtual QCString trModulesMembers ()
virtual QCString trModulesMemberDescription (bool extractAll)
virtual QCString trModulesIndex ()
virtual QCString trModule (bool first_capital, bool singular)
virtual QCString trGeneratedFromFilesFortran (ClassDef::CompoundType compType, bool single)
virtual QCString trType (bool first_capital, bool singular)
virtual QCString trSubprogram (bool first_capital, bool singular)
virtual QCString trTypeConstraints ()
Public Member Functions inherited from TranslatorAdapter_1_6_0
virtual QCString trDirRelation (const char *name)
virtual QCString trLoading ()
virtual QCString trGlobalNamespace ()
virtual QCString trSearching ()
virtual QCString trNoMatches ()
Public Member Functions inherited from TranslatorAdapter_1_6_3
virtual QCString trFileIn (const char *name)
virtual QCString trIncludesFileIn (const char *name)
virtual QCString trDateTime (int year, int month, int day, int dayOfWeek, int hour, int minutes, int seconds, bool includeTime)
Public Member Functions inherited from TranslatorAdapter_1_7_5
virtual QCString trCiteReferences ()
virtual QCString trCopyright ()
virtual QCString trDirDepGraph (const char *name)
Public Member Functions inherited from TranslatorAdapter_1_8_0
virtual QCString trDetailLevel ()
virtual QCString trTemplateParameters ()
virtual QCString trAndMore (const QCString &number)
virtual QCString trEnumGeneratedFromFiles (bool single)
virtual QCString trEnumReference (const char *name)
virtual QCString trInheritedFrom (const char *members, const char *what)
virtual QCString trAdditionalInheritedMembers ()
Public Member Functions inherited from TranslatorAdapter_1_8_2
virtual QCString trPanelSynchronisationTooltip (bool enable)
virtual QCString trProvidedByCategory ()
virtual QCString trExtendsClass ()
virtual QCString trClassMethods ()
virtual QCString trInstanceMethods ()
virtual QCString trMethodDocumentation ()
virtual QCString trDesignOverview ()
Public Member Functions inherited from TranslatorAdapter_1_8_4
virtual QCString trInterfaces ()
virtual QCString trServices ()
virtual QCString trConstantGroups ()
virtual QCString trConstantGroupReference (const char *namespaceName)
virtual QCString trServiceReference (const char *sName)
virtual QCString trSingletonReference (const char *sName)
virtual QCString trServiceGeneratedFromFiles (bool single)
virtual QCString trSingletonGeneratedFromFiles (bool single)
Public Member Functions inherited from Translator
virtual ~Translator ()
Protected Member Functions
virtual ~TranslatorSlovene ()
Protected Member Functions inherited from TranslatorAdapterBase
virtual ~TranslatorAdapterBase ()
QCString createUpdateNeededMessage (const QCString &languageName, const QCString &versionString)
Friends
class TranslatorAdapterBase
Additional Inherited Members
Protected Attributes inherited from TranslatorAdapterBase
TranslatorEnglish english
Detailed Description
Definition at line 24 of file translator_si.h.
Constructor & Destructor Documentation
~TranslatorSlovene()
virtual TranslatorSlovene::~TranslatorSlovene () inline protected virtual
Definition at line 28 of file translator_si.h.
Member Function Documentation
idLanguage()
QCString TranslatorSlovene::idLanguage () inline virtual
Implements Translator.
Definition at line 30 of file translator_si.h.
latexLanguageSupportCommand()
QCString TranslatorSlovene::latexLanguageSupportCommand () inline virtual
Used to get the command(s) for the language support. This method was designed for languages which do not prefer babel package. If this methods returns empty string, then the latexBabelPackage() method is used to generate the command for using the babel package.
Implements Translator.
Definition at line 37 of file translator_si.h.
trAll()
virtual QCString TranslatorSlovene::trAll () inline virtual
Used in the quick index of a class/file/namespace member list page to link to the unfiltered list of all members.
Implements Translator.
Definition at line 1081 of file translator_si.h.
trAttention()
virtual QCString TranslatorSlovene::trAttention () inline virtual
Implements Translator.
Definition at line 618 of file translator_si.h.
trAuthor()
virtual QCString TranslatorSlovene::trAuthor (bool first_capital, bool singular) inline virtual
This text is generated when the \author command is used and for the author section in man pages.
Implements Translator.
Definition at line 958 of file translator_si.h.
trBug()
virtual QCString TranslatorSlovene::trBug () inline virtual
Used as a marker that is put before a \bug item
Implements Translator.
Definition at line 803 of file translator_si.h.
trBugList()
virtual QCString TranslatorSlovene::trBugList () inline virtual
Used as the header of the bug list
Implements Translator.
Definition at line 808 of file translator_si.h.
trCallGraph()
virtual QCString TranslatorSlovene::trCallGraph () inline virtual
Put in front of the call graph for a function.
Implements Translator.
Definition at line 1086 of file translator_si.h.
trClass()
virtual QCString TranslatorSlovene::trClass (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 866 of file translator_si.h.
trClassDiagram()
QCString TranslatorSlovene::trClassDiagram (const char * clName) inline virtual
Implements Translator.
Definition at line 196 of file translator_si.h.
trClassDocumentation()
QCString TranslatorSlovene::trClassDocumentation () inline virtual
Implements Translator.
Definition at line 154 of file translator_si.h.
trClasses()
virtual QCString TranslatorSlovene::trClasses () inline virtual
Used for Java interfaces in the summary section of Java packages
Used for Java classes in the summary section of Java packages
Implements Translator.
Definition at line 756 of file translator_si.h.
References Config_getBool.
trClassHierarchy()
QCString TranslatorSlovene::trClassHierarchy () inline virtual
Implements Translator.
Definition at line 81 of file translator_si.h.
trClassHierarchyDescription()
QCString TranslatorSlovene::trClassHierarchyDescription () inline virtual
Implements Translator.
Definition at line 99 of file translator_si.h.
trCode()
QCString TranslatorSlovene::trCode () inline virtual
Text used the source code in the file index
Implements Translator.
Definition at line 526 of file translator_si.h.
trCollaborationDiagram()
QCString TranslatorSlovene::trCollaborationDiagram (const char * clName) inline virtual
this text is put before a collaboration diagram
Implements Translator.
Definition at line 475 of file translator_si.h.
trCompoundIndex()
QCString TranslatorSlovene::trCompoundIndex () inline virtual
Implements Translator.
Definition at line 148 of file translator_si.h.
trCompoundList()
QCString TranslatorSlovene::trCompoundList () inline virtual
Implements Translator.
Definition at line 83 of file translator_si.h.
trCompoundListDescription()
QCString TranslatorSlovene::trCompoundListDescription () inline virtual
Implements Translator.
Definition at line 109 of file translator_si.h.
trCompoundMembers()
QCString TranslatorSlovene::trCompoundMembers () inline virtual
Implements Translator.
Definition at line 89 of file translator_si.h.
trCompoundMembersDescription()
QCString TranslatorSlovene::trCompoundMembersDescription (bool extractAll) inline virtual
Implements Translator.
Definition at line 113 of file translator_si.h.
trCompoundReference()
QCString TranslatorSlovene::trCompoundReference (const char * clName, ClassDef::CompoundType compType, bool) inline virtual
Implements Translator.
Definition at line 252 of file translator_si.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trCompounds()
QCString TranslatorSlovene::trCompounds () inline virtual
Implements Translator.
Definition at line 187 of file translator_si.h.
trConstructorDocumentation()
QCString TranslatorSlovene::trConstructorDocumentation () inline virtual
header that is put before the list of constructor/destructors.
Implements Translator.
Definition at line 491 of file translator_si.h.
trDate()
QCString TranslatorSlovene::trDate () inline virtual
Implements Translator.
Definition at line 212 of file translator_si.h.
trDefinedAtLineInSourceFile()
QCString TranslatorSlovene::trDefinedAtLineInSourceFile () inline virtual
Implements Translator.
Definition at line 452 of file translator_si.h.
trDefinedIn()
QCString TranslatorSlovene::trDefinedIn () inline virtual
Implements Translator.
Definition at line 77 of file translator_si.h.
trDefinedInSourceFile()
QCString TranslatorSlovene::trDefinedInSourceFile () inline virtual
Implements Translator.
Definition at line 456 of file translator_si.h.
trDefineDocumentation()
QCString TranslatorSlovene::trDefineDocumentation () inline virtual
Implements Translator.
Definition at line 177 of file translator_si.h.
trDefines()
QCString TranslatorSlovene::trDefines () inline virtual
Implements Translator.
Definition at line 165 of file translator_si.h.
trDefineValue()
virtual QCString TranslatorSlovene::trDefineValue () inline virtual
Used as a chapter title for Latex & RTF output
Text shown before a multi-line define
Implements Translator.
Definition at line 793 of file translator_si.h.
trDeprecated()
QCString TranslatorSlovene::trDeprecated () inline virtual
Implements Translator.
Definition at line 465 of file translator_si.h.
trDeprecatedList()
virtual QCString TranslatorSlovene::trDeprecatedList () inline virtual
Used as the header of the list of item that have been flagged deprecated
Implements Translator.
Definition at line 1013 of file translator_si.h.
trDetailedDescription()
QCString TranslatorSlovene::trDetailedDescription () inline virtual
Implements Translator.
Definition at line 45 of file translator_si.h.
trDir()
virtual QCString TranslatorSlovene::trDir (bool first_capital, bool singular) inline virtual
This returns the word directory with or without starting capital (first_capital) and in sigular or plural form (singular).
Implements Translator.
Definition at line 1190 of file translator_si.h.
trDirDescription()
virtual QCString TranslatorSlovene::trDirDescription () inline virtual
This returns a sentences that introduces the directory hierarchy. and the fact that it is sorted alphabetically per level
Implements Translator.
Definition at line 1174 of file translator_si.h.
trDirDocumentation()
virtual QCString TranslatorSlovene::trDirDocumentation () inline virtual
This is used as the name of the chapter containing the documentation of the directories.
Implements Translator.
Definition at line 1162 of file translator_si.h.
trDirectories()
virtual QCString TranslatorSlovene::trDirectories () inline virtual
This is used as the title of the directory index and also in the Quick links of an HTML page, to link to the directory hierarchy.
Implements Translator.
Definition at line 1168 of file translator_si.h.
trDirIndex()
virtual QCString TranslatorSlovene::trDirIndex () inline virtual
This is used as the name of the chapter containing the directory hierarchy.
Implements Translator.
Definition at line 1156 of file translator_si.h.
trDirReference()
virtual QCString TranslatorSlovene::trDirReference (const char * dirName) inline virtual
This returns the title of a directory page. The name of the directory is passed via dirName.
Implements Translator.
Definition at line 1181 of file translator_si.h.
trDocumentation()
QCString TranslatorSlovene::trDocumentation () inline virtual
Implements Translator.
Definition at line 142 of file translator_si.h.
trEnumerations()
QCString TranslatorSlovene::trEnumerations () inline virtual
Implements Translator.
Definition at line 169 of file translator_si.h.
trEnumerationTypeDocumentation()
QCString TranslatorSlovene::trEnumerationTypeDocumentation () inline virtual
Implements Translator.
Definition at line 181 of file translator_si.h.
trEnumerationValues()
QCString TranslatorSlovene::trEnumerationValues () inline virtual
Implements Translator.
Definition at line 175 of file translator_si.h.
trEnumName()
QCString TranslatorSlovene::trEnumName () inline virtual
Implements Translator.
Definition at line 73 of file translator_si.h.
trEnumValue()
QCString TranslatorSlovene::trEnumValue () inline virtual
Implements Translator.
Definition at line 75 of file translator_si.h.
trEventDocumentation()
virtual QCString TranslatorSlovene::trEventDocumentation () inline virtual
Header used for the documentation section of a class' events.
Implements Translator.
Definition at line 1030 of file translator_si.h.
trEvents()
virtual QCString TranslatorSlovene::trEvents () inline virtual
Used as a header for declaration section of the events found in a C# program
Implements Translator.
Definition at line 1025 of file translator_si.h.
trExampleDocumentation()
QCString TranslatorSlovene::trExampleDocumentation () inline virtual
Implements Translator.
Definition at line 158 of file translator_si.h.
trExamples()
QCString TranslatorSlovene::trExamples () inline virtual
Implements Translator.
Definition at line 95 of file translator_si.h.
trExamplesDescription()
QCString TranslatorSlovene::trExamplesDescription () inline virtual
Implements Translator.
Definition at line 133 of file translator_si.h.
trExceptions()
QCString TranslatorSlovene::trExceptions () inline virtual
Implements Translator.
Definition at line 220 of file translator_si.h.
trFile()
virtual QCString TranslatorSlovene::trFile (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 877 of file translator_si.h.
trFileDocumentation()
QCString TranslatorSlovene::trFileDocumentation () inline virtual
Implements Translator.
Definition at line 156 of file translator_si.h.
trFileIndex()
QCString TranslatorSlovene::trFileIndex () inline virtual
Implements Translator.
Definition at line 150 of file translator_si.h.
trFileList()
QCString TranslatorSlovene::trFileList () inline virtual
Implements Translator.
Definition at line 85 of file translator_si.h.
trFileListDescription()
QCString TranslatorSlovene::trFileListDescription (bool extractAll) inline virtual
Implements Translator.
Definition at line 102 of file translator_si.h.
trFileMembers()
QCString TranslatorSlovene::trFileMembers () inline virtual
Implements Translator.
Definition at line 91 of file translator_si.h.
trFileMembersDescription()
QCString TranslatorSlovene::trFileMembersDescription (bool extractAll) inline virtual
Implements Translator.
Definition at line 122 of file translator_si.h.
trFileReference()
QCString TranslatorSlovene::trFileReference (const char * fileName) inline virtual
Implements Translator.
Definition at line 273 of file translator_si.h.
trForInternalUseOnly()
QCString TranslatorSlovene::trForInternalUseOnly () inline virtual
Implements Translator.
Definition at line 200 of file translator_si.h.
trFriends()
QCString TranslatorSlovene::trFriends () inline virtual
Implements Translator.
Definition at line 238 of file translator_si.h.
trFunctionDocumentation()
QCString TranslatorSlovene::trFunctionDocumentation () inline virtual
Implements Translator.
Definition at line 183 of file translator_si.h.
trFunctions()
QCString TranslatorSlovene::trFunctions () inline virtual
Implements Translator.
Definition at line 171 of file translator_si.h.
trGeneratedAt()
QCString TranslatorSlovene::trGeneratedAt (const char * date, const char * projName) inline virtual
Implements Translator.
Definition at line 189 of file translator_si.h.
trGeneratedAutomatically()
QCString TranslatorSlovene::trGeneratedAutomatically (const char * s) inline virtual
Implements Translator.
Definition at line 67 of file translator_si.h.
trGeneratedBy()
QCString TranslatorSlovene::trGeneratedBy () inline virtual
Implements Translator.
Definition at line 222 of file translator_si.h.
trGeneratedFromFiles()
QCString TranslatorSlovene::trGeneratedFromFiles (ClassDef::CompoundType compType, bool single) inline virtual
This is put at the bottom of a class documentation page and is followed by a list of files that were used to generate the page.
Implements Translator.
Definition at line 402 of file translator_si.h.
References ClassDef::Category, ClassDef::Class, ClassDef::Exception, ClassDef::Interface, ClassDef::Protocol, ClassDef::Struct, and ClassDef::Union.
trGlobal()
virtual QCString TranslatorSlovene::trGlobal (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 945 of file translator_si.h.
trGotoDocumentation()
QCString TranslatorSlovene::trGotoDocumentation () inline virtual
Used in the file sources to point to the corresponding documentation.
Implements Translator.
Definition at line 501 of file translator_si.h.
trGotoGraphicalHierarchy()
QCString TranslatorSlovene::trGotoGraphicalHierarchy () inline virtual
Implements Translator.
Definition at line 534 of file translator_si.h.
trGotoSourceCode()
QCString TranslatorSlovene::trGotoSourceCode () inline virtual
Used in the file documentation to point to the corresponding sources.
Implements Translator.
Definition at line 496 of file translator_si.h.
trGotoTextualHierarchy()
QCString TranslatorSlovene::trGotoTextualHierarchy () inline virtual
Implements Translator.
Definition at line 538 of file translator_si.h.
trGraphicalHierarchy()
QCString TranslatorSlovene::trGraphicalHierarchy () inline virtual
Implements Translator.
Definition at line 530 of file translator_si.h.
trGroup()
virtual QCString TranslatorSlovene::trGroup (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 900 of file translator_si.h.
trHierarchicalIndex()
QCString TranslatorSlovene::trHierarchicalIndex () inline virtual
Implements Translator.
Definition at line 146 of file translator_si.h.
trImplementedFromList()
virtual QCString TranslatorSlovene::trImplementedFromList (int numEntries) inline virtual
used in member documentation blocks to produce a list of members that are implemented by this one.
Implements Translator.
Definition at line 981 of file translator_si.h.
References trWriteList().
trImplementedInList()
virtual QCString TranslatorSlovene::trImplementedInList (int numEntries) inline virtual
used in member documentation blocks to produce a list of all members that implement this abstract member.
Implements Translator.
Definition at line 989 of file translator_si.h.
References trWriteList().
trInclByDepGraph()
virtual QCString TranslatorSlovene::trInclByDepGraph () inline virtual
Implements Translator.
Definition at line 622 of file translator_si.h.
trInclDepGraph()
QCString TranslatorSlovene::trInclDepGraph (const char * fName) inline virtual
this text is put before an include dependency graph
Implements Translator.
Definition at line 480 of file translator_si.h.
trIncludingInheritedMembers()
QCString TranslatorSlovene::trIncludingInheritedMembers () inline virtual
Implements Translator.
Definition at line 65 of file translator_si.h.
trInheritedByList()
QCString TranslatorSlovene::trInheritedByList (int numEntries) inline virtual
Implements Translator.
Definition at line 342 of file translator_si.h.
References trWriteList().
trInheritsList()
QCString TranslatorSlovene::trInheritsList (int numEntries) inline virtual
Implements Translator.
Definition at line 336 of file translator_si.h.
References trWriteList().
trInitialValue()
QCString TranslatorSlovene::trInitialValue () inline virtual
Text shown before a multi-line variable/enum initialization
Implements Translator.
Definition at line 521 of file translator_si.h.
trInvariant()
QCString TranslatorSlovene::trInvariant () inline virtual
Text for the
Invariant
command
Implements Translator.
Definition at line 516 of file translator_si.h.
trLegend()
virtual QCString TranslatorSlovene::trLegend () inline virtual
text for the link to the legend page
Implements Translator.
Definition at line 711 of file translator_si.h.
trLegendDocs()
virtual QCString TranslatorSlovene::trLegendDocs () inline virtual
page explaining how the dot graph's should be interpreted The A in the text below are to prevent link to classes called "A".
Implements Translator.
Definition at line 651 of file translator_si.h.
References getDotImageExtension().
trLegendTitle()
virtual QCString TranslatorSlovene::trLegendTitle () inline virtual
title of the graph legend page
Implements Translator.
Definition at line 644 of file translator_si.h.
trListOfAllMembers()
QCString TranslatorSlovene::trListOfAllMembers () inline virtual
Implements Translator.
Definition at line 59 of file translator_si.h.
trMainPage()
QCString TranslatorSlovene::trMainPage () inline virtual
This is in the (quick) index as a link to the main page (index.html)
Implements Translator.
Definition at line 435 of file translator_si.h.
trMember()
virtual QCString TranslatorSlovene::trMember (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 922 of file translator_si.h.
trMemberDataDocumentation()
QCString TranslatorSlovene::trMemberDataDocumentation () inline virtual
Implements Translator.
Definition at line 55 of file translator_si.h.
trMemberEnumerationDocumentation()
QCString TranslatorSlovene::trMemberEnumerationDocumentation () inline virtual
Implements Translator.
Definition at line 49 of file translator_si.h.
trMemberFunctionDocumentation()
QCString TranslatorSlovene::trMemberFunctionDocumentation () inline virtual
Implements Translator.
Definition at line 53 of file translator_si.h.
trMemberList()
QCString TranslatorSlovene::trMemberList () inline virtual
Implements Translator.
Definition at line 61 of file translator_si.h.
trMemberTypedefDocumentation()
QCString TranslatorSlovene::trMemberTypedefDocumentation () inline virtual
Implements Translator.
Definition at line 47 of file translator_si.h.
trModuleDocumentation()
QCString TranslatorSlovene::trModuleDocumentation () inline virtual
Implements Translator.
Definition at line 152 of file translator_si.h.
trModuleIndex()
QCString TranslatorSlovene::trModuleIndex () inline virtual
Implements Translator.
Definition at line 144 of file translator_si.h.
trModules()
QCString TranslatorSlovene::trModules () inline virtual
Implements Translator.
Definition at line 79 of file translator_si.h.
trModulesDescription()
QCString TranslatorSlovene::trModulesDescription () inline virtual
Implements Translator.
Definition at line 137 of file translator_si.h.
trMore()
QCString TranslatorSlovene::trMore () inline virtual
Implements Translator.
Definition at line 57 of file translator_si.h.
trNamespace()
virtual QCString TranslatorSlovene::trNamespace (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 889 of file translator_si.h.
trNamespaceDocumentation()
QCString TranslatorSlovene::trNamespaceDocumentation () inline virtual
Implements Translator.
Definition at line 380 of file translator_si.h.
trNamespaceIndex()
QCString TranslatorSlovene::trNamespaceIndex () inline virtual
Implements Translator.
Definition at line 376 of file translator_si.h.
trNamespaceList()
QCString TranslatorSlovene::trNamespaceList () inline virtual
Implements Translator.
Definition at line 229 of file translator_si.h.
trNamespaceListDescription()
QCString TranslatorSlovene::trNamespaceListDescription (bool extractAll) inline virtual
Implements Translator.
Definition at line 231 of file translator_si.h.
trNamespaceMemberDescription()
QCString TranslatorSlovene::trNamespaceMemberDescription (bool extractAll) inline virtual
Implements Translator.
Definition at line 364 of file translator_si.h.
trNamespaceMembers()
QCString TranslatorSlovene::trNamespaceMembers () inline virtual
Implements Translator.
Definition at line 361 of file translator_si.h.
trNamespaceReference()
QCString TranslatorSlovene::trNamespaceReference (const char * namespaceName) inline virtual
Implements Translator.
Definition at line 280 of file translator_si.h.
trNamespaces()
virtual QCString TranslatorSlovene::trNamespaces () inline virtual
This is used in the documentation before the list of all namespaces in a file.
Implements Translator.
Definition at line 391 of file translator_si.h.
trNote()
QCString TranslatorSlovene::trNote () inline virtual
Implements Translator.
Definition at line 551 of file translator_si.h.
trOverloadText()
virtual QCString TranslatorSlovene::trOverloadText () inline virtual
This text is added to the documentation when the \overload command is used for a overloaded function.
Implements Translator.
Definition at line 1204 of file translator_si.h.
trPackage()
virtual QCString TranslatorSlovene::trPackage (const char * name) inline virtual
Used as the title of a Java package
Implements Translator.
Definition at line 768 of file translator_si.h.
trPackageAttribs()
virtual QCString TranslatorSlovene::trPackageAttribs () inline virtual
Used as a heading for a list of Java class variables with package scope.
Implements Translator.
Definition at line 1062 of file translator_si.h.
trPackageList()
virtual QCString TranslatorSlovene::trPackageList () inline virtual
Title of the package index page
Implements Translator.
Definition at line 773 of file translator_si.h.
trPackageListDescription()
virtual QCString TranslatorSlovene::trPackageListDescription () inline virtual
The description of the package index page
Implements Translator.
Definition at line 778 of file translator_si.h.
trPackageMembers()
virtual QCString TranslatorSlovene::trPackageMembers () inline virtual
Used as a heading for a list of Java class functions with package scope.
Implements Translator.
Definition at line 1048 of file translator_si.h.
trPackages()
virtual QCString TranslatorSlovene::trPackages () inline virtual
The link name in the Quick links header for each page
Implements Translator.
Definition at line 783 of file translator_si.h.
trPackageTypes()
virtual QCString TranslatorSlovene::trPackageTypes () inline virtual
Used as a heading for a list of Java class types with package scope.
Implements Translator.
Definition at line 1041 of file translator_si.h.
trPage()
virtual QCString TranslatorSlovene::trPage (bool first_capital, bool singular) inline virtual
This is used for translation of the word that will possibly be followed by a single name or by a list of names of the category.
Implements Translator.
Definition at line 911 of file translator_si.h.
trPageAbbreviation()
QCString TranslatorSlovene::trPageAbbreviation () inline virtual
This is used in references to page that are put in the LaTeX documentation. It should be an abbreviation of the word page.
Implements Translator.
Definition at line 441 of file translator_si.h.
trPageDocumentation()
QCString TranslatorSlovene::trPageDocumentation () inline virtual
Implements Translator.
Definition at line 160 of file translator_si.h.
trPageIndex()
QCString TranslatorSlovene::trPageIndex () inline virtual
Implements Translator.
Definition at line 542 of file translator_si.h.
trParameters()
QCString TranslatorSlovene::trParameters () inline virtual
Implements Translator.
Definition at line 218 of file translator_si.h.
trPostcondition()
QCString TranslatorSlovene::trPostcondition () inline virtual
Text for the
Postcondition
command
Implements Translator.
Definition at line 511 of file translator_si.h.
trPrecondition()
QCString TranslatorSlovene::trPrecondition () inline virtual
Text for the
Precondition
command
Implements Translator.
Definition at line 506 of file translator_si.h.
trPrivateAttribs()
QCString TranslatorSlovene::trPrivateAttribs () inline virtual
Implements Translator.
Definition at line 583 of file translator_si.h.
trPrivateMembers()
QCString TranslatorSlovene::trPrivateMembers () inline virtual
Implements Translator.
Definition at line 304 of file translator_si.h.
trPrivateSlots()
QCString TranslatorSlovene::trPrivateSlots () inline virtual
Implements Translator.
Definition at line 306 of file translator_si.h.
trPrivateTypes()
QCString TranslatorSlovene::trPrivateTypes () inline virtual
Implements Translator.
Definition at line 579 of file translator_si.h.
trProperties()
virtual QCString TranslatorSlovene::trProperties () inline virtual
Used as a section header for IDL properties
Implements Translator.
Definition at line 736 of file translator_si.h.
trPropertyDocumentation()
virtual QCString TranslatorSlovene::trPropertyDocumentation () inline virtual
Used as a section header for IDL property documentation
Implements Translator.
Definition at line 741 of file translator_si.h.
trProtectedAttribs()
QCString TranslatorSlovene::trProtectedAttribs () inline virtual
Implements Translator.
Definition at line 571 of file translator_si.h.
trProtectedMembers()
QCString TranslatorSlovene::trProtectedMembers () inline virtual
Implements Translator.
Definition at line 298 of file translator_si.h.
trProtectedSlots()
QCString TranslatorSlovene::trProtectedSlots () inline virtual
Implements Translator.
Definition at line 300 of file translator_si.h.
trProtectedTypes()
QCString TranslatorSlovene::trProtectedTypes () inline virtual
Implements Translator.
Definition at line 567 of file translator_si.h.
trPublicAttribs()
QCString TranslatorSlovene::trPublicAttribs () inline virtual
Implements Translator.
Definition at line 559 of file translator_si.h.
trPublicMembers()
QCString TranslatorSlovene::trPublicMembers () inline virtual
Implements Translator.
Definition at line 290 of file translator_si.h.
trPublicSlots()
QCString TranslatorSlovene::trPublicSlots () inline virtual
Implements Translator.
Definition at line 292 of file translator_si.h.
trPublicTypes()
QCString TranslatorSlovene::trPublicTypes () inline virtual
Implements Translator.
Definition at line 555 of file translator_si.h.
trReferencedBy()
virtual QCString TranslatorSlovene::trReferencedBy () inline virtual
Implements Translator.
Definition at line 610 of file translator_si.h.
trReferenceManual()
QCString TranslatorSlovene::trReferenceManual () inline virtual
Implements Translator.
Definition at line 162 of file translator_si.h.
trReferences()
virtual QCString TranslatorSlovene::trReferences () inline virtual
This text is put before the list of members referenced by a member
Implements Translator.
Definition at line 970 of file translator_si.h.
trReimplementedFromList()
QCString TranslatorSlovene::trReimplementedFromList (int numEntries) inline virtual
Implements Translator.
Definition at line 348 of file translator_si.h.
References trWriteList().
trReimplementedInList()
QCString TranslatorSlovene::trReimplementedInList (int numEntries) inline virtual
Implements Translator.
Definition at line 354 of file translator_si.h.
References trWriteList().
trRelatedFunctionDocumentation()
QCString TranslatorSlovene::trRelatedFunctionDocumentation () inline virtual
Implements Translator.
Definition at line 245 of file translator_si.h.
trRelatedFunctions()
QCString TranslatorSlovene::trRelatedFunctions () inline virtual
Implements Translator.
Definition at line 41 of file translator_si.h.
trRelatedPages()
QCString TranslatorSlovene::trRelatedPages () inline virtual
Implements Translator.
Definition at line 93 of file translator_si.h.
trRelatedPagesDescription()
QCString TranslatorSlovene::trRelatedPagesDescription () inline virtual
Implements Translator.
Definition at line 135 of file translator_si.h.
trRelatedSubscript()
QCString TranslatorSlovene::trRelatedSubscript () inline virtual
Implements Translator.
Definition at line 43 of file translator_si.h.
trRemarks()
virtual QCString TranslatorSlovene::trRemarks () inline virtual
Implements Translator.
Definition at line 614 of file translator_si.h.
trReturns()
QCString TranslatorSlovene::trReturns () inline virtual
Implements Translator.
Definition at line 214 of file translator_si.h.
trReturnValues()
QCString TranslatorSlovene::trReturnValues () inline virtual
This is used as the heading text for the retval command.
Implements Translator.
Definition at line 430 of file translator_si.h.
trRTFansicp()
virtual QCString TranslatorSlovene::trRTFansicp () inline virtual
Used as ansicpg for RTF file
The following table shows the correlation of Charset name, Charset Value and
Codepage number:
Charset Name       Charset Value(hex)  Codepage number
DEFAULT_CHARSET           1 (x01)
SYMBOL_CHARSET            2 (x02)
OEM_CHARSET             255 (xFF)
ANSI_CHARSET              0 (x00)            1252
RUSSIAN_CHARSET         204 (xCC)            1251
EE_CHARSET              238 (xEE)            1250
GREEK_CHARSET           161 (xA1)            1253
TURKISH_CHARSET         162 (xA2)            1254
BALTIC_CHARSET          186 (xBA)            1257
HEBREW_CHARSET          177 (xB1)            1255
ARABIC _CHARSET         178 (xB2)            1256
SHIFTJIS_CHARSET        128 (x80)             932
HANGEUL_CHARSET         129 (x81)             949
GB2313_CHARSET          134 (x86)             936
CHINESEBIG5_CHARSET     136 (x88)             950
Implements Translator.
Definition at line 842 of file translator_si.h.
trRTFCharSet()
virtual QCString TranslatorSlovene::trRTFCharSet () inline virtual
Used as ansicpg for RTF fcharset
See also
trRTFansicp() for a table of possible values.
Implements Translator.
Definition at line 851 of file translator_si.h.
trRTFGeneralIndex()
virtual QCString TranslatorSlovene::trRTFGeneralIndex () inline virtual
Used as header RTF general index
Implements Translator.
Definition at line 857 of file translator_si.h.
trRTFTableOfContents()
virtual QCString TranslatorSlovene::trRTFTableOfContents () inline virtual
used in RTF documentation as a heading for the Table of Contents.
Implements Translator.
Definition at line 1001 of file translator_si.h.
trSearch()
QCString TranslatorSlovene::trSearch () inline virtual
Implements Translator.
Definition at line 97 of file translator_si.h.
trSearchMatches()
virtual QCString TranslatorSlovene::trSearchMatches () inline virtual
This string is put before the list of matched words, for each search result. What follows is the list of words that matched the query.
Implements Translator.
Definition at line 1133 of file translator_si.h.
trSearchResults()
virtual QCString TranslatorSlovene::trSearchResults (int numDocuments) inline virtual
This string is put just before listing the search results. The text can be different depending on the number of documents found. Inside the text you can put the special marker $num to insert the number representing the actual number of search results. The numDocuments parameter can be either 0, 1 or 2, where the value 2 represents 2 or more matches. HTML markup is allowed inside the returned string.
Implements Translator.
Definition at line 1110 of file translator_si.h.
trSearchResultsTitle()
virtual QCString TranslatorSlovene::trSearchResultsTitle () inline virtual
This string is used as the title for the page listing the search results.
Implements Translator.
Definition at line 1098 of file translator_si.h.
trSeeAlso()
QCString TranslatorSlovene::trSeeAlso () inline virtual
Implements Translator.
Definition at line 216 of file translator_si.h.
trSignals()
QCString TranslatorSlovene::trSignals () inline virtual
Implements Translator.
Definition at line 294 of file translator_si.h.
trSince()
virtual QCString TranslatorSlovene::trSince () inline virtual
Implements Translator.
Definition at line 634 of file translator_si.h.
trSourceFile()
virtual QCString TranslatorSlovene::trSourceFile (QCString & filename) inline virtual
This is used in HTML as the title of page with source code for file filename
Implements Translator.
Definition at line 1144 of file translator_si.h.
trStaticPackageAttribs()
virtual QCString TranslatorSlovene::trStaticPackageAttribs () inline virtual
Used as a heading for a list of static Java class variables with package scope.
Implements Translator.
Definition at line 1069 of file translator_si.h.
trStaticPackageMembers()
virtual QCString TranslatorSlovene::trStaticPackageMembers () inline virtual
Used as a heading for a list of static Java class functions with package scope.
Implements Translator.
Definition at line 1055 of file translator_si.h.
trStaticPrivateAttribs()
QCString TranslatorSlovene::trStaticPrivateAttribs () inline virtual
Implements Translator.
Definition at line 587 of file translator_si.h.
trStaticPrivateMembers()
QCString TranslatorSlovene::trStaticPrivateMembers () inline virtual
Implements Translator.
Definition at line 308 of file translator_si.h.
trStaticProtectedAttribs()
QCString TranslatorSlovene::trStaticProtectedAttribs () inline virtual
Implements Translator.
Definition at line 575 of file translator_si.h.
trStaticProtectedMembers()
QCString TranslatorSlovene::trStaticProtectedMembers () inline virtual
Implements Translator.
Definition at line 302 of file translator_si.h.
trStaticPublicAttribs()
QCString TranslatorSlovene::trStaticPublicAttribs () inline virtual
Implements Translator.
Definition at line 563 of file translator_si.h.
trStaticPublicMembers()
QCString TranslatorSlovene::trStaticPublicMembers () inline virtual
Implements Translator.
Definition at line 296 of file translator_si.h.
trTest()
virtual QCString TranslatorSlovene::trTest () inline virtual
Used as a marker that is put before a test item
Implements Translator.
Definition at line 721 of file translator_si.h.
trTestList()
virtual QCString TranslatorSlovene::trTestList () inline virtual
Used as the header of the test list
Implements Translator.
Definition at line 726 of file translator_si.h.
trThisIsTheListOfAllMembers()
QCString TranslatorSlovene::trThisIsTheListOfAllMembers () inline virtual
Implements Translator.
Definition at line 63 of file translator_si.h.
trTodo()
virtual QCString TranslatorSlovene::trTodo () inline virtual
Used as a marker that is put before a todo item
Implements Translator.
Definition at line 596 of file translator_si.h.
trTodoList()
virtual QCString TranslatorSlovene::trTodoList () inline virtual
Used as the header of the todo list
Implements Translator.
Definition at line 601 of file translator_si.h.
trTypedefDocumentation()
QCString TranslatorSlovene::trTypedefDocumentation () inline virtual
Implements Translator.
Definition at line 179 of file translator_si.h.
trTypedefs()
QCString TranslatorSlovene::trTypedefs () inline virtual
Implements Translator.
Definition at line 167 of file translator_si.h.
trVariableDocumentation()
QCString TranslatorSlovene::trVariableDocumentation () inline virtual
Implements Translator.
Definition at line 185 of file translator_si.h.
trVariables()
QCString TranslatorSlovene::trVariables () inline virtual
Implements Translator.
Definition at line 173 of file translator_si.h.
trVersion()
QCString TranslatorSlovene::trVersion () inline virtual
Implements Translator.
Definition at line 210 of file translator_si.h.
trWarning()
QCString TranslatorSlovene::trWarning () inline virtual
Implements Translator.
Definition at line 206 of file translator_si.h.
trWriteList()
QCString TranslatorSlovene::trWriteList (int numEntries) inline virtual
Implements Translator.
Definition at line 312 of file translator_si.h.
References generateMarker().
Referenced by trImplementedFromList(), trImplementedInList(), trInheritedByList(), trInheritsList(), trReimplementedFromList(), and trReimplementedInList().
Friends And Related Function Documentation
TranslatorAdapterBase
friend class TranslatorAdapterBase friend
Definition at line 27 of file translator_si.h.
The documentation for this class was generated from the following file:
src/translator_si.h