Doxygen: src/searchindex.cpp File Reference
searchindex.cpp File Reference
#include <ctype.h>
#include <assert.h>
#include <qfile.h>
#include <qregexp.h>
#include "searchindex.h"
#include "config.h"
#include "util.h"
#include "doxygen.h"
#include "language.h"
#include "pagedef.h"
#include "growbuf.h"
#include "message.h"
#include "version.h"
#include "groupdef.h"
#include "classlist.h"
#include "filedef.h"
#include "memberdef.h"
#include "filename.h"
#include "membername.h"
#include "resourcemgr.h"
#include "namespacedef.h"
#include "classdef.h"
Classes
struct SearchDocEntry
struct SearchIndexExternal::Private
Functions
static int charsToIndex (const char *word)
static void writeInt (QFile &f, int index)
static void writeString (QFile &f, const char *s)
static QCString definitionToName (Definition *ctx)
static void addMemberToSearchIndex (MemberDef *md)
static QCString searchId (const QCString &s)
void createJavascriptSearchIndex ()
void writeJavascriptSearchIndex ()
const SearchIndexInfo * getSearchIndices ()
void initSearchIndexer ()
void finializeSearchIndexer ()
Variables
const int numIndexEntries = 256*256
static SearchIndexInfo g_searchIndexInfo [NUM_SEARCH_INDICES]
Function Documentation
addMemberToSearchIndex()
static void addMemberToSearchIndex (MemberDef * md) static
Definition at line 588 of file searchindex.cpp.
References LetterToIndexMap< T >::append(), Config_getBool, MemberDef::getClassDef(), MemberDef::getFileDef(), MemberDef::getGroupDef(), MemberDef::getNamespaceDef(), getUtf8CodeToLower(), MemberDef::isDefine(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isEvent(), MemberDef::isForeign(), MemberDef::isFriend(), MemberDef::isFunction(), GroupDef::isLinkable(), NamespaceDef::isLinkable(), FileDef::isLinkable(), ClassDef::isLinkable(), MemberDef::isLinkable(), MemberDef::isProperty(), MemberDef::isRelated(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isTypedef(), MemberDef::isVariable(), Definition::name(), SEARCH_INDEX_ALL, SEARCH_INDEX_DEFINES, SEARCH_INDEX_ENUMS, SEARCH_INDEX_ENUMVALUES, SEARCH_INDEX_EVENTS, SEARCH_INDEX_FUNCTIONS, SEARCH_INDEX_PROPERTIES, SEARCH_INDEX_RELATED, SEARCH_INDEX_TYPEDEFS, SEARCH_INDEX_VARIABLES, SearchIndexInfo::symbolList, ClassDef::templateMaster(), and MemberDef::typeString().
Referenced by createJavascriptSearchIndex().
charsToIndex()
static int charsToIndex (const char * word) static
Definition at line 183 of file searchindex.cpp.
Referenced by SearchIndex::addWord().
createJavascriptSearchIndex()
void createJavascriptSearchIndex ()
Definition at line 718 of file searchindex.cpp.
References addMemberToSearchIndex(), LetterToIndexMap< T >::append(), Doxygen::classSDict, Doxygen::functionNameSDict, getUtf8CodeToLower(), Doxygen::groupSDict, GroupDef::groupTitle(), Doxygen::inputNameList, isId(), PageDef::isLinkable(), GroupDef::isLinkable(), NamespaceDef::isLinkable(), FileDef::isLinkable(), ClassDef::isLinkable(), SDict< ClassDef >::Iterator, SDict< NamespaceDef >::Iterator, SDict< MemberName >::Iterator, SDict< GroupDef >::Iterator, SDict< PageDef >::Iterator, Definition::localName(), Doxygen::mainPage, Doxygen::memberNameSDict, FileDef::name(), Definition::name(), SearchIndexInfo::name, Doxygen::namespaceSDict, NUM_SEARCH_INDICES, Doxygen::pageSDict, SEARCH_INDEX_ALL, SEARCH_INDEX_CLASSES, SEARCH_INDEX_DEFINES, SEARCH_INDEX_ENUMS, SEARCH_INDEX_ENUMVALUES, SEARCH_INDEX_EVENTS, SEARCH_INDEX_FILES, SEARCH_INDEX_FUNCTIONS, SEARCH_INDEX_GROUPS, SEARCH_INDEX_NAMESPACES, SEARCH_INDEX_PAGES, SEARCH_INDEX_PROPERTIES, SEARCH_INDEX_RELATED, SEARCH_INDEX_TYPEDEFS, SEARCH_INDEX_VARIABLES, SDict< T >::sort(), SearchIndexInfo::symbolList, SearchIndexInfo::text, theTranslator, PageDef::title(), Translator::trAll(), Translator::trClasses(), Translator::trDefines(), Translator::trEnumerations(), Translator::trEnumerationValues(), Translator::trEvents(), Translator::trFile(), Translator::trFriends(), Translator::trFunctions(), Translator::trGroup(), Translator::trNamespace(), Translator::trPage(), Translator::trProperties(), Translator::trTypedefs(), and Translator::trVariables().
Referenced by generateOutput().
definitionToName()
static QCString definitionToName (Definition * ctx) static
Definition at line 445 of file searchindex.cpp.
References DefinitionIntf::definitionType(), MemberDef::isDefine(), MemberDef::isEnumerate(), MemberDef::isEnumValue(), MemberDef::isEvent(), MemberDef::isForeign(), MemberDef::isFriend(), MemberDef::isFunction(), MemberDef::isProperty(), MemberDef::isRelated(), MemberDef::isSignal(), MemberDef::isSlot(), MemberDef::isTypedef(), MemberDef::isVariable(), DefinitionIntf::TypeClass, DefinitionIntf::TypeDir, DefinitionIntf::TypeFile, DefinitionIntf::TypeGroup, DefinitionIntf::TypeMember, DefinitionIntf::TypeNamespace, DefinitionIntf::TypePackage, and DefinitionIntf::TypePage.
Referenced by SearchIndexExternal::setCurrentDoc().
finializeSearchIndexer()
void finializeSearchIndexer ()
Cleanup the search indexer
Definition at line 1324 of file searchindex.cpp.
References Doxygen::searchIndex.
Referenced by generateOutput().
getSearchIndices()
const SearchIndexInfo* getSearchIndices ()
Definition at line 1251 of file searchindex.cpp.
References g_searchIndexInfo.
Referenced by SearchIndicesContext::Private::Private().
initSearchIndexer()
void initSearchIndexer ()
Initialize the search indexer
Definition at line 1302 of file searchindex.cpp.
References Config_getBool, and Doxygen::searchIndex.
Referenced by generateOutput().
searchId()
static QCString searchId (const QCString & s) static
Definition at line 692 of file searchindex.cpp.
Referenced by SearchIndexList::append().
writeInt()
static void writeInt (QFile & f, int index) static
Definition at line 247 of file searchindex.cpp.
Referenced by SearchIndex::write().
writeJavascriptSearchIndex()
void writeJavascriptSearchIndex ()
Definition at line 903 of file searchindex.cpp.
References IndexList::addStyleSheetFile(), Definition::anchor(), MemberDef::argsString(), Config_getBool, Config_getString, convertToXML(), ResourceMgr::copyResource(), DefinitionIntf::definitionType(), endl(), err(), externalRef(), Definition::getBodyDef(), MemberDef::getClassDef(), MemberDef::getFileDef(), Definition::getLanguage(), getLanguageSpecificSeparator(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), Definition::getOutputFileBase(), Definition::getReference(), Doxygen::globalScope, Doxygen::htmlFileExtension, SearchDefinitionList::id(), Doxygen::indexList, ResourceMgr::instance(), MemberDef::isFunction(), MemberDef::isSlot(), SearchIndexList::letter(), Definition::localName(), Definition::name(), SearchDefinitionList::name(), SearchIndexInfo::name, NUM_SEARCH_INDICES, Definition::qualifiedName(), theTranslator, Translator::trGlobalNamespace(), Translator::trLoading(), Translator::trNoMatches(), Translator::trSearching(), DefinitionIntf::TypeClass, DefinitionIntf::TypeMember, DefinitionIntf::TypeNamespace, and versionString.
Referenced by generateOutput().
writeString()
static void writeString (QFile & f, const char * s) static
Definition at line 255 of file searchindex.cpp.
Referenced by SearchIndex::write().
Variable Documentation
g_searchIndexInfo
SearchIndexInfo g_searchIndexInfo[NUM_SEARCH_INDICES] static
Definition at line 586 of file searchindex.cpp.
Referenced by getSearchIndices().
numIndexEntries
const int numIndexEntries = 256*256
Definition at line 52 of file searchindex.cpp.
Referenced by SearchIndex::SearchIndex(), and SearchIndex::write().