Doxygen: NestingNodeContext Class Reference
NestingNodeContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
QCString id () const
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static NestingNodeContext * alloc (const NestingNodeContext *parent, Definition *def, int index, int level, bool addClasses, bool inherit, bool hideSuper)
Private Member Functions
NestingNodeContext (const NestingNodeContext *parent, Definition *, int index, int level, bool addClasses, bool inherit, bool hideSuper)
~NestingNodeContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 509 of file context.h.
Constructor & Destructor Documentation
NestingNodeContext()
NestingNodeContext::NestingNodeContext (const NestingNodeContext * parent, Definition * d, int index, int level, bool addClasses, bool inherit, bool hideSuper) private
Definition at line 6391 of file context.cpp.
References p, and Private.
Referenced by alloc().
~NestingNodeContext()
NestingNodeContext::~NestingNodeContext () private
Definition at line 6398 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int NestingNodeContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 520 of file context.h.
References RefCountedContext::addRef().
alloc()
static NestingNodeContext* NestingNodeContext::alloc (const NestingNodeContext * parent, Definition * def, int index, int level, bool addClasses, bool inherit, bool hideSuper) inline static
Definition at line 512 of file context.h.
References NestingNodeContext().
Referenced by NestingContext::Private::addClasses(), NestingContext::Private::addClassHierarchy(), NestingContext::Private::addDerivedClasses(), NestingContext::Private::addDirs(), NestingContext::Private::addFiles(), NestingContext::Private::addModules(), NestingContext::Private::addNamespaces(), and NestingContext::Private::addPages().
get()
TemplateVariant NestingNodeContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 6403 of file context.cpp.
References NestingNodeContext::Private::get(), and p.
id()
QCString NestingNodeContext::id () const
Definition at line 6408 of file context.cpp.
References NestingNodeContext::Private::id(), p, and TemplateVariant::toString().
Referenced by NestingNodeContext::Private::id().
release()
virtual int NestingNodeContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 521 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* NestingNodeContext::p private
Definition at line 527 of file context.h.
Referenced by get(), id(), NestingNodeContext(), and ~NestingNodeContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp