Doxygen: PageListContext Class Reference
PageListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
void addPages (const PageSDict &pages)
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static PageListContext * alloc (const PageSDict *pages)
Private Member Functions
PageListContext (const PageSDict *pages)
~PageListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 687 of file context.h.
Constructor & Destructor Documentation
PageListContext()
PageListContext::PageListContext (const PageSDict * pages) private
Definition at line 7403 of file context.cpp.
References PageListContext::Private::addPages(), p, and Private.
Referenced by alloc().
~PageListContext()
PageListContext::~PageListContext () private
Definition at line 7409 of file context.cpp.
References p.
Member Function Documentation
addPages()
void PageListContext::addPages (const PageSDict & pages)
addRef()
virtual int PageListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 696 of file context.h.
References RefCountedContext::addRef().
alloc()
static PageListContext* PageListContext::alloc (const PageSDict * pages) inline static
Definition at line 690 of file context.h.
References PageListContext().
Referenced by generateOutputViaTemplate().
at()
TemplateVariant PageListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7420 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int PageListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 7415 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * PageListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7425 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int PageListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 697 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* PageListContext::p private
Definition at line 704 of file context.h.
Referenced by at(), count(), createIterator(), PageListContext(), and ~PageListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp