Doxygen: TranslateContext Class Reference
TranslateContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static TranslateContext * alloc ()
Private Member Functions
TranslateContext ()
~TranslateContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 167 of file context.h.
Constructor & Destructor Documentation
TranslateContext()
TranslateContext::TranslateContext () private
Definition at line 1227 of file context.cpp.
References p, and Private.
Referenced by alloc().
~TranslateContext()
TranslateContext::~TranslateContext () private
Definition at line 1232 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int TranslateContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 174 of file context.h.
References RefCountedContext::addRef().
alloc()
static TranslateContext* TranslateContext::alloc () inline static
Definition at line 170 of file context.h.
References TranslateContext().
Referenced by generateOutputViaTemplate().
get()
TemplateVariant TranslateContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 1237 of file context.cpp.
References TranslateContext::Private::get(), and p.
release()
virtual int TranslateContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 175 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* TranslateContext::p private
Definition at line 180 of file context.h.
Referenced by get(), TranslateContext(), and ~TranslateContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp