Doxygen: src/groupdef.cpp File Reference
groupdef.cpp File Reference
#include <ctype.h>
#include <qregexp.h>
#include "groupdef.h"
#include "classdef.h"
#include "filedef.h"
#include "classlist.h"
#include "outputlist.h"
#include "namespacedef.h"
#include "language.h"
#include "util.h"
#include "memberlist.h"
#include "message.h"
#include "membergroup.h"
#include "doxygen.h"
#include "pagedef.h"
#include "docparser.h"
#include "searchindex.h"
#include "dot.h"
#include "vhdldocgen.h"
#include "layout.h"
#include "arguments.h"
#include "entry.h"
#include "membername.h"
#include "dirdef.h"
#include "config.h"
Functions
void addClassToGroups (Entry *root, ClassDef *cd)
void addNamespaceToGroups (Entry *root, NamespaceDef *nd)
void addDirToGroups (Entry *root, DirDef *dd)
void addGroupToGroups (Entry *root, GroupDef *subGroup)
void addMemberToGroups (Entry *root, MemberDef *md)
void addExampleToGroups (Entry *root, PageDef *eg)
Function Documentation
addClassToGroups()
void addClassToGroups (Entry * root, ClassDef * cd)
Definition at line 1316 of file groupdef.cpp.
References GroupDef::addClass(), SDict< T >::find(), Grouping::groupname, Entry::groups, Doxygen::groupSDict, and Definition::makePartOfGroup().
Referenced by addClassToContext().
addDirToGroups()
void addDirToGroups (Entry * root, DirDef * dd)
Definition at line 1351 of file groupdef.cpp.
References GroupDef::addDir(), SDict< T >::find(), Grouping::groupname, Entry::groups, Doxygen::groupSDict, and Definition::makePartOfGroup().
Referenced by findDirDocumentation().
addExampleToGroups()
void addExampleToGroups (Entry * root, PageDef * eg)
Definition at line 1506 of file groupdef.cpp.
References GroupDef::addExample(), SDict< T >::find(), Grouping::groupname, Entry::groups, Doxygen::groupSDict, and Definition::makePartOfGroup().
addGroupToGroups()
void addGroupToGroups (Entry * root, GroupDef * subGroup)
Definition at line 1369 of file groupdef.cpp.
References GroupDef::addGroup(), Entry::fileName, SDict< T >::find(), GroupDef::findGroup(), Grouping::groupname, Entry::groups, Doxygen::groupSDict, Definition::makePartOfGroup(), Definition::name(), Entry::startLine, and warn().
Referenced by organizeSubGroupsFiltered().
addMemberToGroups()
void addMemberToGroups (Entry * root, MemberDef * md)
Add a member to the group with the highest priority
Definition at line 1400 of file groupdef.cpp.
References Entry::doc, Entry::fileName, SDict< T >::find(), MemberDef::getClassDefOfAnonymousType(), MemberDef::getGroupDef(), MemberDef::getGroupFileName(), MemberDef::getGroupHasDocs(), MemberDef::getGroupPri(), Grouping::getGroupPriName(), MemberDef::getGroupStartLine(), Grouping::GROUPING_LOWEST, Grouping::groupname, Entry::groups, Doxygen::groupSDict, GroupDef::insertMember(), Definition::name(), Grouping::pri, GroupDef::removeMember(), MemberDef::setGroupDef(), ClassDef::setGroupDefForAllMembers(), Entry::startLine, and warn().
Referenced by addInterfaceOrServiceToServiceOrSingleton(), addMemberDocs(), addMethodToClass(), addVariableToClass(), addVariableToFile(), buildFunctionList(), findDefineDocumentation(), findEnumDocumentation(), findEnums(), and findMember().
addNamespaceToGroups()
void addNamespaceToGroups (Entry * root, NamespaceDef * nd)
Definition at line 1334 of file groupdef.cpp.
References GroupDef::addNamespace(), SDict< T >::find(), Grouping::groupname, Entry::groups, Doxygen::groupSDict, and Definition::makePartOfGroup().
Referenced by buildNamespaceList().