Doxygen: DirRelation Class Reference
DirRelation Class Reference
A usage relation between two directories.
#include <dirdef.h>
Public Member Functions
DirRelation (const QCString &name, DirDef *src, UsedDir *dst)
DirDef * source () const
UsedDir * destination () const
void writeDocumentation (OutputList &ol)
QCString getOutputFileBase () const
Private Attributes
QCString m_name
DirDef * m_src
UsedDir * m_dst
Detailed Description
A usage relation between two directories.
Definition at line 151 of file dirdef.h.
Constructor & Destructor Documentation
DirRelation()
DirRelation::DirRelation (const QCString & name, DirDef * src, UsedDir * dst) inline
Definition at line 154 of file dirdef.h.
Member Function Documentation
destination()
UsedDir* DirRelation::destination () const inline
Definition at line 157 of file dirdef.h.
References m_dst.
getOutputFileBase()
QCString DirRelation::getOutputFileBase () const inline
Definition at line 159 of file dirdef.h.
References m_name.
Referenced by writeDocumentation().
source()
DirDef* DirRelation::source () const inline
Definition at line 156 of file dirdef.h.
References m_src.
writeDocumentation()
void DirRelation::writeDocumentation (OutputList & ol)
Definition at line 781 of file dirdef.cpp.
References Config_getBool, UsedDir::dir(), OutputList::disableAllBut(), DirDef::displayName(), OutputList::endContents(), endFileWithNavPath(), OutputList::endQuickIndices(), UsedDir::filePairs(), DirDef::getOutputFileBase(), getOutputFileBase(), HLI_None, OutputGenerator::Html, m_dst, m_src, OutputList::parseText(), Definition::pathFragment(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), DirDef::shortName(), OutputList::startContents(), startFile(), theTranslator, Translator::trDirRelation(), Translator::trFileIn(), Translator::trIncludesFileIn(), Definition::writeNavigationPath(), writePartialFilePath(), and OutputList::writeString().
Referenced by generateDirDocs().
Member Data Documentation
m_dst
UsedDir* DirRelation::m_dst private
Definition at line 164 of file dirdef.h.
Referenced by destination(), and writeDocumentation().
m_name
QCString DirRelation::m_name private
Definition at line 162 of file dirdef.h.
Referenced by getOutputFileBase().
m_src
DirDef* DirRelation::m_src private
Definition at line 163 of file dirdef.h.
Referenced by source(), and writeDocumentation().
The documentation for this class was generated from the following files:
src/dirdef.h
src/dirdef.cpp