Doxygen: PrintDocVisitor Class Reference
PrintDocVisitor Class Reference
#include <printdocvisitor.h>
Public Member Functions
PrintDocVisitor ()
void visit (DocWord *w)
void visit (DocLinkedWord *w)
void visit (DocWhiteSpace *w)
void visit (DocSymbol *s)
void visit (DocURL *u)
void visit (DocLineBreak *)
void visit (DocHorRuler *)
void visit (DocStyleChange *s)
void visit (DocVerbatim *s)
void visit (DocAnchor *a)
void visit (DocInclude *inc)
void visit (DocIncOperator *op)
void visit (DocFormula *f)
void visit (DocIndexEntry *i)
void visit (DocSimpleSectSep *)
void visit (DocCite *cite)
void visitPre (DocAutoList *l)
void visitPost (DocAutoList *l)
void visitPre (DocAutoListItem *)
void visitPost (DocAutoListItem *)
void visitPre (DocPara *)
void visitPost (DocPara *)
void visitPre (DocRoot *)
void visitPost (DocRoot *)
void visitPre (DocSimpleSect *s)
void visitPost (DocSimpleSect *)
void visitPre (DocTitle *)
void visitPost (DocTitle *)
void visitPre (DocSimpleList *)
void visitPost (DocSimpleList *)
void visitPre (DocSimpleListItem *)
void visitPost (DocSimpleListItem *)
void visitPre (DocSection *s)
void visitPost (DocSection *s)
void visitPre (DocHtmlList *s)
void visitPost (DocHtmlList *s)
void visitPre (DocHtmlListItem *)
void visitPost (DocHtmlListItem *)
void visitPre (DocHtmlDescList *)
void visitPost (DocHtmlDescList *)
void visitPre (DocHtmlDescTitle *)
void visitPost (DocHtmlDescTitle *)
void visitPre (DocHtmlDescData *)
void visitPost (DocHtmlDescData *)
void visitPre (DocHtmlTable *t)
void visitPost (DocHtmlTable *)
void visitPre (DocHtmlRow *)
void visitPost (DocHtmlRow *)
void visitPre (DocHtmlCell *c)
void visitPost (DocHtmlCell *c)
void visitPre (DocHtmlCaption *)
void visitPost (DocHtmlCaption *)
void visitPre (DocInternal *)
void visitPost (DocInternal *)
void visitPre (DocHRef *href)
void visitPost (DocHRef *)
void visitPre (DocHtmlHeader *header)
void visitPost (DocHtmlHeader *header)
void visitPre (DocImage *img)
void visitPost (DocImage *)
void visitPre (DocDotFile *df)
void visitPost (DocDotFile *)
void visitPre (DocMscFile *df)
void visitPost (DocMscFile *)
void visitPre (DocDiaFile *df)
void visitPost (DocDiaFile *)
void visitPre (DocLink *lnk)
void visitPost (DocLink *)
void visitPre (DocRef *ref)
void visitPost (DocRef *)
void visitPre (DocSecRefItem *ref)
void visitPost (DocSecRefItem *)
void visitPre (DocSecRefList *)
void visitPost (DocSecRefList *)
void visitPre (DocParamList *pl)
void visitPost (DocParamList *)
void visitPre (DocParamSect *ps)
void visitPost (DocParamSect *)
void visitPre (DocXRefItem *x)
void visitPost (DocXRefItem *)
void visitPre (DocInternalRef *r)
void visitPost (DocInternalRef *)
void visitPre (DocCopy *c)
void visitPost (DocCopy *)
void visitPre (DocText *)
void visitPost (DocText *)
void visitPre (DocHtmlBlockQuote *)
void visitPost (DocHtmlBlockQuote *)
void visitPre (DocVhdlFlow *)
void visitPost (DocVhdlFlow *)
void visitPre (DocParBlock *)
void visitPost (DocParBlock *)
Public Member Functions inherited from DocVisitor
DocVisitor (int id)
virtual ~DocVisitor ()
int id () const
Private Member Functions
void indent ()
void indent_leaf ()
void indent_pre ()
void indent_post ()
Private Attributes
int m_indent
bool m_needsEnter
bool m_insidePre
Detailed Description
Concrete visitor implementation for pretty printing
Definition at line 28 of file printdocvisitor.h.
Constructor & Destructor Documentation
PrintDocVisitor()
PrintDocVisitor::PrintDocVisitor () inline
Definition at line 31 of file printdocvisitor.h.
Member Function Documentation
indent()
void PrintDocVisitor::indent () inline private
Definition at line 708 of file printdocvisitor.h.
References m_indent, and m_needsEnter.
Referenced by indent_leaf(), indent_post(), and indent_pre().
indent_leaf()
void PrintDocVisitor::indent_leaf () inline private
Definition at line 714 of file printdocvisitor.h.
References indent(), and m_needsEnter.
Referenced by visit().
indent_post()
void PrintDocVisitor::indent_post () inline private
Definition at line 724 of file printdocvisitor.h.
References indent(), and m_indent.
Referenced by visitPost().
indent_pre()
void PrintDocVisitor::indent_pre () inline private
Definition at line 719 of file printdocvisitor.h.
References indent(), and m_indent.
Referenced by visitPre().
visit() [1/16]
void PrintDocVisitor::visit (DocWord * w) inline virtual
Implements DocVisitor.
Definition at line 36 of file printdocvisitor.h.
References indent_leaf(), and DocWord::word().
Referenced by visitPre().
visit() [2/16]
void PrintDocVisitor::visit (DocLinkedWord * w) inline virtual
Implements DocVisitor.
Definition at line 41 of file printdocvisitor.h.
References indent_leaf(), and DocLinkedWord::word().
visit() [3/16]
void PrintDocVisitor::visit (DocWhiteSpace * w) inline virtual
Implements DocVisitor.
Definition at line 46 of file printdocvisitor.h.
References DocWhiteSpace::chars(), indent_leaf(), and m_insidePre.
visit() [4/16]
void PrintDocVisitor::visit (DocSymbol * s) inline virtual
Implements DocVisitor.
Definition at line 58 of file printdocvisitor.h.
References indent_leaf(), HtmlEntityMapper::instance(), DocSymbol::symbol(), and HtmlEntityMapper::utf8().
visit() [5/16]
void PrintDocVisitor::visit (DocURL * u) inline virtual
Implements DocVisitor.
Definition at line 71 of file printdocvisitor.h.
References indent_leaf(), and DocURL::url().
visit() [6/16]
void PrintDocVisitor::visit (DocLineBreak *) inline virtual
Implements DocVisitor.
Definition at line 76 of file printdocvisitor.h.
References indent_leaf().
visit() [7/16]
void PrintDocVisitor::visit (DocHorRuler *) inline virtual
Implements DocVisitor.
Definition at line 81 of file printdocvisitor.h.
References indent_leaf().
visit() [8/16]
void PrintDocVisitor::visit (DocStyleChange * s) inline virtual
Implements DocVisitor.
Definition at line 86 of file printdocvisitor.h.
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Code, DocStyleChange::Div, DocStyleChange::enable(), indent_leaf(), DocStyleChange::Italic, DocStyleChange::Preformatted, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::style(), DocStyleChange::Subscript, and DocStyleChange::Superscript.
visit() [9/16]
void PrintDocVisitor::visit (DocVerbatim * s) inline virtual
Implements DocVisitor.
Definition at line 123 of file printdocvisitor.h.
References DocVerbatim::Code, DocVerbatim::DocbookOnly, DocVerbatim::Dot, DocVerbatim::HtmlOnly, indent_leaf(), DocVerbatim::LatexOnly, DocVerbatim::ManOnly, DocVerbatim::Msc, DocVerbatim::PlantUML, DocVerbatim::RtfOnly, DocVerbatim::text(), DocVerbatim::type(), DocVerbatim::Verbatim, and DocVerbatim::XmlOnly.
visit() [10/16]
void PrintDocVisitor::visit (DocAnchor * a) inline virtual
Implements DocVisitor.
Definition at line 156 of file printdocvisitor.h.
References DocAnchor::anchor(), and indent_leaf().
visit() [11/16]
void PrintDocVisitor::visit (DocInclude * inc) inline virtual
Implements DocVisitor.
Definition at line 161 of file printdocvisitor.h.
References DocInclude::DontInclude, err(), DocInclude::file(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, indent_leaf(), DocInclude::LatexInclude, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::type(), and DocInclude::VerbInclude.
visit() [12/16]
void PrintDocVisitor::visit (DocIncOperator * op) inline virtual
Implements DocVisitor.
Definition at line 183 of file printdocvisitor.h.
References indent_leaf(), DocIncOperator::Line, DocIncOperator::pattern(), DocIncOperator::Skip, DocIncOperator::SkipLine, DocIncOperator::type(), and DocIncOperator::Until.
visit() [13/16]
void PrintDocVisitor::visit (DocFormula * f) inline virtual
Implements DocVisitor.
Definition at line 196 of file printdocvisitor.h.
References indent_leaf(), DocFormula::name(), and DocFormula::text().
visit() [14/16]
void PrintDocVisitor::visit (DocIndexEntry * i) inline virtual
Implements DocVisitor.
Definition at line 201 of file printdocvisitor.h.
References DocIndexEntry::entry(), and indent_leaf().
visit() [15/16]
void PrintDocVisitor::visit (DocSimpleSectSep *) inline virtual
Implements DocVisitor.
Definition at line 206 of file printdocvisitor.h.
References indent_leaf().
visit() [16/16]
void PrintDocVisitor::visit (DocCite * cite) inline virtual
Implements DocVisitor.
Definition at line 211 of file printdocvisitor.h.
References DocCite::anchor(), DocCite::file(), indent_leaf(), DocCite::ref(), and DocCite::text().
visitPost() [1/38]
void PrintDocVisitor::visitPost (DocAutoList * l) inline virtual
Implements DocVisitor.
Definition at line 235 of file printdocvisitor.h.
References indent_post(), and DocAutoList::isEnumList().
visitPost() [2/38]
void PrintDocVisitor::visitPost (DocAutoListItem *) inline virtual
Implements DocVisitor.
Definition at line 252 of file printdocvisitor.h.
References indent_post().
visitPost() [3/38]
void PrintDocVisitor::visitPost (DocPara *) inline virtual
Implements DocVisitor.
Definition at line 262 of file printdocvisitor.h.
References indent_post().
visitPost() [4/38]
void PrintDocVisitor::visitPost (DocRoot *) inline virtual
Implements DocVisitor.
Definition at line 272 of file printdocvisitor.h.
References indent_post().
visitPost() [5/38]
void PrintDocVisitor::visitPost (DocSimpleSect *) inline virtual
Implements DocVisitor.
Definition at line 304 of file printdocvisitor.h.
References indent_post().
visitPost() [6/38]
void PrintDocVisitor::visitPost (DocTitle *) inline virtual
Implements DocVisitor.
Definition at line 314 of file printdocvisitor.h.
References indent_post().
visitPost() [7/38]
void PrintDocVisitor::visitPost (DocSimpleList *) inline virtual
Implements DocVisitor.
Definition at line 324 of file printdocvisitor.h.
References indent_post().
visitPost() [8/38]
void PrintDocVisitor::visitPost (DocSimpleListItem *) inline virtual
Implements DocVisitor.
Definition at line 334 of file printdocvisitor.h.
References indent_post().
visitPost() [9/38]
void PrintDocVisitor::visitPost (DocSection * s) inline virtual
Implements DocVisitor.
Definition at line 344 of file printdocvisitor.h.
References indent_post(), and DocSection::level().
visitPost() [10/38]
void PrintDocVisitor::visitPost (DocHtmlList * s) inline virtual
Implements DocVisitor.
Definition at line 354 of file printdocvisitor.h.
References indent_post(), DocHtmlList::Ordered, and DocHtmlList::type().
visitPost() [11/38]
void PrintDocVisitor::visitPost (DocHtmlListItem *) inline virtual
Implements DocVisitor.
Definition at line 364 of file printdocvisitor.h.
References indent_post().
visitPost() [12/38]
void PrintDocVisitor::visitPost (DocHtmlDescList *) inline virtual
Implements DocVisitor.
Definition at line 386 of file printdocvisitor.h.
References indent_post().
visitPost() [13/38]
void PrintDocVisitor::visitPost (DocHtmlDescTitle *) inline virtual
Implements DocVisitor.
Definition at line 396 of file printdocvisitor.h.
References indent_post().
visitPost() [14/38]
void PrintDocVisitor::visitPost (DocHtmlDescData *) inline virtual
Implements DocVisitor.
Definition at line 406 of file printdocvisitor.h.
References indent_post().
visitPost() [15/38]
void PrintDocVisitor::visitPost (DocHtmlTable *) inline virtual
Implements DocVisitor.
Definition at line 417 of file printdocvisitor.h.
References indent_post().
visitPost() [16/38]
void PrintDocVisitor::visitPost (DocHtmlRow *) inline virtual
Implements DocVisitor.
Definition at line 427 of file printdocvisitor.h.
References indent_post().
visitPost() [17/38]
void PrintDocVisitor::visitPost (DocHtmlCell * c) inline virtual
Implements DocVisitor.
Definition at line 437 of file printdocvisitor.h.
References indent_post(), and DocHtmlCell::isHeading().
visitPost() [18/38]
void PrintDocVisitor::visitPost (DocHtmlCaption *) inline virtual
Implements DocVisitor.
Definition at line 447 of file printdocvisitor.h.
References indent_post().
visitPost() [19/38]
void PrintDocVisitor::visitPost (DocInternal *) inline virtual
Implements DocVisitor.
Definition at line 457 of file printdocvisitor.h.
References indent_post().
visitPost() [20/38]
void PrintDocVisitor::visitPost (DocHRef *) inline virtual
Implements DocVisitor.
Definition at line 467 of file printdocvisitor.h.
References indent_post().
visitPost() [21/38]
void PrintDocVisitor::visitPost (DocHtmlHeader * header) inline virtual
Implements DocVisitor.
Definition at line 477 of file printdocvisitor.h.
References indent_post(), and DocHtmlHeader::level().
visitPost() [22/38]
void PrintDocVisitor::visitPost (DocImage *) inline virtual
Implements DocVisitor.
Definition at line 495 of file printdocvisitor.h.
References indent_post().
visitPost() [23/38]
void PrintDocVisitor::visitPost (DocDotFile *) inline virtual
Implements DocVisitor.
Definition at line 505 of file printdocvisitor.h.
References indent_post().
visitPost() [24/38]
void PrintDocVisitor::visitPost (DocMscFile *) inline virtual
Implements DocVisitor.
Definition at line 515 of file printdocvisitor.h.
References indent_post().
visitPost() [25/38]
void PrintDocVisitor::visitPost (DocDiaFile *) inline virtual
Implements DocVisitor.
Definition at line 525 of file printdocvisitor.h.
References indent_post().
visitPost() [26/38]
void PrintDocVisitor::visitPost (DocLink *) inline virtual
Implements DocVisitor.
Definition at line 536 of file printdocvisitor.h.
References indent_post().
visitPost() [27/38]
void PrintDocVisitor::visitPost (DocRef *) inline virtual
Implements DocVisitor.
Definition at line 552 of file printdocvisitor.h.
References indent_post().
visitPost() [28/38]
void PrintDocVisitor::visitPost (DocSecRefItem *) inline virtual
Implements DocVisitor.
Definition at line 562 of file printdocvisitor.h.
References indent_post().
visitPost() [29/38]
void PrintDocVisitor::visitPost (DocSecRefList *) inline virtual
Implements DocVisitor.
Definition at line 572 of file printdocvisitor.h.
References indent_post().
visitPost() [30/38]
void PrintDocVisitor::visitPost (DocParamList *) inline virtual
Implements DocVisitor.
Definition at line 610 of file printdocvisitor.h.
References indent_post().
visitPost() [31/38]
void PrintDocVisitor::visitPost (DocParamSect *) inline virtual
Implements DocVisitor.
Definition at line 629 of file printdocvisitor.h.
References indent_post().
visitPost() [32/38]
void PrintDocVisitor::visitPost (DocXRefItem *) inline virtual
Implements DocVisitor.
Definition at line 640 of file printdocvisitor.h.
References indent_post().
visitPost() [33/38]
void PrintDocVisitor::visitPost (DocInternalRef *) inline virtual
Implements DocVisitor.
Definition at line 650 of file printdocvisitor.h.
References indent_post().
visitPost() [34/38]
void PrintDocVisitor::visitPost (DocCopy *) inline virtual
Implements DocVisitor.
Definition at line 660 of file printdocvisitor.h.
References indent_post().
visitPost() [35/38]
void PrintDocVisitor::visitPost (DocText *) inline virtual
Implements DocVisitor.
Definition at line 670 of file printdocvisitor.h.
References indent_post().
visitPost() [36/38]
void PrintDocVisitor::visitPost (DocHtmlBlockQuote *) inline virtual
Implements DocVisitor.
Definition at line 680 of file printdocvisitor.h.
References indent_post().
visitPost() [37/38]
void PrintDocVisitor::visitPost (DocVhdlFlow *) inline virtual
Implements DocVisitor.
Definition at line 690 of file printdocvisitor.h.
References indent_post().
visitPost() [38/38]
void PrintDocVisitor::visitPost (DocParBlock *) inline virtual
Implements DocVisitor.
Definition at line 700 of file printdocvisitor.h.
References indent_post().
visitPre() [1/38]
void PrintDocVisitor::visitPre (DocAutoList * l) inline virtual
Implements DocVisitor.
Definition at line 223 of file printdocvisitor.h.
References indent_pre(), and DocAutoList::isEnumList().
visitPre() [2/38]
void PrintDocVisitor::visitPre (DocAutoListItem *) inline virtual
Implements DocVisitor.
Definition at line 247 of file printdocvisitor.h.
References indent_pre().
visitPre() [3/38]
void PrintDocVisitor::visitPre (DocPara *) inline virtual
Implements DocVisitor.
Definition at line 257 of file printdocvisitor.h.
References indent_pre().
visitPre() [4/38]
void PrintDocVisitor::visitPre (DocRoot *) inline virtual
Implements DocVisitor.
Definition at line 267 of file printdocvisitor.h.
References indent_pre().
visitPre() [5/38]
void PrintDocVisitor::visitPre (DocSimpleSect * s) inline virtual
Implements DocVisitor.
Definition at line 277 of file printdocvisitor.h.
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, indent_pre(), DocSimpleSect::Invar, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, DocSimpleSect::See, DocSimpleSect::Since, DocSimpleSect::type(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
visitPre() [6/38]
void PrintDocVisitor::visitPre (DocTitle *) inline virtual
Implements DocVisitor.
Definition at line 309 of file printdocvisitor.h.
References indent_pre().
visitPre() [7/38]
void PrintDocVisitor::visitPre (DocSimpleList *) inline virtual
Implements DocVisitor.
Definition at line 319 of file printdocvisitor.h.
References indent_pre().
visitPre() [8/38]
void PrintDocVisitor::visitPre (DocSimpleListItem *) inline virtual
Implements DocVisitor.
Definition at line 329 of file printdocvisitor.h.
References indent_pre().
visitPre() [9/38]
void PrintDocVisitor::visitPre (DocSection * s) inline virtual
Implements DocVisitor.
Definition at line 339 of file printdocvisitor.h.
References indent_pre(), and DocSection::level().
visitPre() [10/38]
void PrintDocVisitor::visitPre (DocHtmlList * s) inline virtual
Implements DocVisitor.
Definition at line 349 of file printdocvisitor.h.
References indent_pre(), DocHtmlList::Ordered, and DocHtmlList::type().
visitPre() [11/38]
void PrintDocVisitor::visitPre (DocHtmlListItem *) inline virtual
Implements DocVisitor.
Definition at line 359 of file printdocvisitor.h.
References indent_pre().
visitPre() [12/38]
void PrintDocVisitor::visitPre (DocHtmlDescList *) inline virtual
Implements DocVisitor.
Definition at line 381 of file printdocvisitor.h.
References indent_pre().
visitPre() [13/38]
void PrintDocVisitor::visitPre (DocHtmlDescTitle *) inline virtual
Implements DocVisitor.
Definition at line 391 of file printdocvisitor.h.
References indent_pre().
visitPre() [14/38]
void PrintDocVisitor::visitPre (DocHtmlDescData *) inline virtual
Implements DocVisitor.
Definition at line 401 of file printdocvisitor.h.
References indent_pre().
visitPre() [15/38]
void PrintDocVisitor::visitPre (DocHtmlTable * t) inline virtual
Implements DocVisitor.
Definition at line 411 of file printdocvisitor.h.
References indent_pre(), DocHtmlTable::numColumns(), and DocHtmlTable::numRows().
visitPre() [16/38]
void PrintDocVisitor::visitPre (DocHtmlRow *) inline virtual
Implements DocVisitor.
Definition at line 422 of file printdocvisitor.h.
References indent_pre().
visitPre() [17/38]
void PrintDocVisitor::visitPre (DocHtmlCell * c) inline virtual
Implements DocVisitor.
Definition at line 432 of file printdocvisitor.h.
References indent_pre(), and DocHtmlCell::isHeading().
visitPre() [18/38]
void PrintDocVisitor::visitPre (DocHtmlCaption *) inline virtual
Implements DocVisitor.
Definition at line 442 of file printdocvisitor.h.
References indent_pre().
visitPre() [19/38]
void PrintDocVisitor::visitPre (DocInternal *) inline virtual
Implements DocVisitor.
Definition at line 452 of file printdocvisitor.h.
References indent_pre().
visitPre() [20/38]
void PrintDocVisitor::visitPre (DocHRef * href) inline virtual
Implements DocVisitor.
Definition at line 462 of file printdocvisitor.h.
References indent_pre(), and DocHRef::url().
visitPre() [21/38]
void PrintDocVisitor::visitPre (DocHtmlHeader * header) inline virtual
Implements DocVisitor.
Definition at line 472 of file printdocvisitor.h.
References indent_pre(), and DocHtmlHeader::level().
visitPre() [22/38]
void PrintDocVisitor::visitPre (DocImage * img) inline virtual
Implements DocVisitor.
Definition at line 482 of file printdocvisitor.h.
References DocImage::DocBook, DocImage::height(), DocImage::Html, indent_pre(), DocImage::Latex, DocImage::name(), DocImage::Rtf, DocImage::type(), and DocImage::width().
visitPre() [23/38]
void PrintDocVisitor::visitPre (DocDotFile * df) inline virtual
Implements DocVisitor.
Definition at line 500 of file printdocvisitor.h.
References indent_pre(), and DocDotFile::name().
visitPre() [24/38]
void PrintDocVisitor::visitPre (DocMscFile * df) inline virtual
Implements DocVisitor.
Definition at line 510 of file printdocvisitor.h.
References indent_pre(), and DocMscFile::name().
visitPre() [25/38]
void PrintDocVisitor::visitPre (DocDiaFile * df) inline virtual
Implements DocVisitor.
Definition at line 520 of file printdocvisitor.h.
References indent_pre(), and DocDiaFile::name().
visitPre() [26/38]
void PrintDocVisitor::visitPre (DocLink * lnk) inline virtual
Implements DocVisitor.
Definition at line 530 of file printdocvisitor.h.
References DocLink::anchor(), DocLink::file(), indent_pre(), and DocLink::ref().
visitPre() [27/38]
void PrintDocVisitor::visitPre (DocRef * ref) inline virtual
Implements DocVisitor.
Definition at line 541 of file printdocvisitor.h.
References DocRef::anchor(), DocRef::file(), DocRef::hasLinkText(), indent_pre(), DocRef::ref(), DocRef::refToAnchor(), DocRef::refToSection(), DocRef::refToTable(), and DocRef::targetTitle().
visitPre() [28/38]
void PrintDocVisitor::visitPre (DocSecRefItem * ref) inline virtual
Implements DocVisitor.
Definition at line 557 of file printdocvisitor.h.
References indent_pre(), and DocSecRefItem::target().
visitPre() [29/38]
void PrintDocVisitor::visitPre (DocSecRefList *) inline virtual
Implements DocVisitor.
Definition at line 567 of file printdocvisitor.h.
References indent_pre().
visitPre() [30/38]
void PrintDocVisitor::visitPre (DocParamList * pl) inline virtual
Implements DocVisitor.
Definition at line 587 of file printdocvisitor.h.
References indent_pre(), DocNode::Kind_LinkedWord, DocNode::Kind_Word, DocParamList::parameters(), and visit().
visitPre() [31/38]
void PrintDocVisitor::visitPre (DocParamSect * ps) inline virtual
Implements DocVisitor.
Definition at line 615 of file printdocvisitor.h.
References DocParamSect::Exception, indent_pre(), DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, DocParamSect::type(), and DocParamSect::Unknown.
visitPre() [32/38]
void PrintDocVisitor::visitPre (DocXRefItem * x) inline virtual
Implements DocVisitor.
Definition at line 634 of file printdocvisitor.h.
References DocXRefItem::anchor(), DocXRefItem::file(), indent_pre(), and DocXRefItem::title().
visitPre() [33/38]
void PrintDocVisitor::visitPre (DocInternalRef * r) inline virtual
Implements DocVisitor.
Definition at line 645 of file printdocvisitor.h.
References DocInternalRef::anchor(), DocInternalRef::file(), and indent_pre().
visitPre() [34/38]
void PrintDocVisitor::visitPre (DocCopy * c) inline virtual
Implements DocVisitor.
Definition at line 655 of file printdocvisitor.h.
References indent_pre(), and DocCopy::link().
visitPre() [35/38]
void PrintDocVisitor::visitPre (DocText *) inline virtual
Implements DocVisitor.
Definition at line 665 of file printdocvisitor.h.
References indent_pre().
visitPre() [36/38]
void PrintDocVisitor::visitPre (DocHtmlBlockQuote *) inline virtual
Implements DocVisitor.
Definition at line 675 of file printdocvisitor.h.
References indent_pre().
visitPre() [37/38]
void PrintDocVisitor::visitPre (DocVhdlFlow *) inline virtual
Implements DocVisitor.
Definition at line 685 of file printdocvisitor.h.
References indent_pre().
visitPre() [38/38]
void PrintDocVisitor::visitPre (DocParBlock *) inline virtual
Implements DocVisitor.
Definition at line 695 of file printdocvisitor.h.
References indent_pre().
Member Data Documentation
m_indent
int PrintDocVisitor::m_indent private
Definition at line 731 of file printdocvisitor.h.
Referenced by indent(), indent_post(), and indent_pre().
m_insidePre
bool PrintDocVisitor::m_insidePre private
Definition at line 733 of file printdocvisitor.h.
Referenced by visit().
m_needsEnter
bool PrintDocVisitor::m_needsEnter private
Definition at line 732 of file printdocvisitor.h.
Referenced by indent(), and indent_leaf().
The documentation for this class was generated from the following file:
src/printdocvisitor.h