Doxygen: HtmlGenerator Class Reference
HtmlGenerator Class Reference
Generator for HTML output.
#include <htmlgen.h>
Public Member Functions
HtmlGenerator ()
virtual ~HtmlGenerator ()
void enable ()
void disable ()
void enableIf (OutputType o)
void disableIf (OutputType o)
void disableIfNot (OutputType o)
bool isEnabled (OutputType o)
OutputGenerator * get (OutputType o)
void codify (const char *text)
void writeCodeLink (const char *ref, const char *file, const char *anchor, const char *name, const char *tooltip)
void writeLineNumber (const char *ref, const char *file, const char *anchor, int lineNumber)
void writeTooltip (const char *id, const DocLinkInfo &docInfo, const char *decl, const char *desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void startFontClass (const char *s)
void endFontClass ()
void writeCodeAnchor (const char *anchor)
void setCurrentDoc (Definition *context, const char *anchor, bool isSourceFile)
void addWord (const char *word, bool hiPriority)
void writeDoc (DocNode *, Definition *, MemberDef *)
void startFile (const char *name, const char *manName, const char *title)
void writeFooter (const char *navPath)
void endFile ()
void clearBuffer ()
void writeSearchInfo ()
void startIndexSection (IndexSections)
void endIndexSection (IndexSections)
void writePageLink (const char *, bool)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startTitleHead (const char *)
void endTitleHead (const char *, const char *)
void startTitle ()
void endTitle ()
void startParagraph (const char *classDef)
void endParagraph ()
void writeString (const char *text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool)
void endIndexValue (const char *, bool)
void startItemList ()
void endItemList ()
void startIndexItem (const char *ref, const char *file)
void endIndexItem (const char *ref, const char *file)
void docify (const char *text)
void writeObjectLink (const char *ref, const char *file, const char *anchor, const char *name)
void startTextLink (const char *file, const char *anchor)
void endTextLink ()
void startHtmlLink (const char *url)
void endHtmlLink ()
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int)
void endGroupHeader (int)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const char *)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int)
void endAnonTypeScope (int)
void startMemberItem (const char *anchor, int, const char *inheritId)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const char *anchor, const char *inheritId)
void startMemberGroupHeader (bool)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool)
void insertMemberAlign (bool)
void startMemberDescription (const char *anchor, const char *inheritId)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const char *anchor, const char *inheritId)
void writeInheritedSectionTitle (const char *id, const char *ref, const char *file, const char *anchor, const char *title, const char *name)
void writeRuler ()
void writeAnchor (const char *, const char *name)
void startCodeFragment ()
void endCodeFragment ()
void startEmphasis ()
void endEmphasis ()
void startBold ()
void endBold ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void startDescForItem ()
void endDescForItem ()
void lineBreak (const char *style)
void writeChar (char c)
void startMemberDoc (const char *clName, const char *memName, const char *anchor, const char *title, int memCount, int memTotal, bool showInline)
void endMemberDoc (bool)
void startDoxyAnchor (const char *fName, const char *manName, const char *anchor, const char *name, const char *args)
void endDoxyAnchor (const char *fName, const char *anchor)
void writeLatexSpacing ()
void writeStartAnnoItem (const char *type, const char *file, const char *path, const char *name)
void writeEndAnnoItem (const char *)
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void startSimpleSect (SectionTypes, const char *, const char *, const char *)
void endSimpleSect ()
void startParamList (ParamListTypes, const char *)
void endParamList ()
void startSection (const char *, const char *, SectionInfo::SectionType)
void endSection (const char *, SectionInfo::SectionType)
void addIndexItem (const char *, const char *)
void startIndent ()
void endIndent ()
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &, const char *, const char *)
void startPageRef ()
void endPageRef (const char *, const char *)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const char *name)
void writeNavigationPath (const char *s)
void writeLogo ()
void writeQuickLinks (bool compact, HighlightedItem hli, const char *file)
void writeSummaryLink (const char *file, const char *anchor, const char *title, bool first)
void startContents ()
void endContents ()
void writeNonBreakableSpace (int)
void startDescTable (const char *title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (const DotClassGraph &g)
void startInclDepGraph ()
void endInclDepGraph (const DotInclDepGraph &g)
void startGroupCollaboration ()
void endGroupCollaboration (const DotGroupCollaboration &g)
void startCallGraph ()
void endCallGraph (const DotCallGraph &g)
void startDirDepGraph ()
void endDirDepGraph (const DotDirDeps &g)
void writeGraphicalHierarchy (const DotGfxHierarchyTable &g)
void startTextBlock (bool)
void endTextBlock (bool)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool)
void endMemberDocName ()
void startParameterType (bool first, const char *key)
void endParameterType ()
void startParameterName (bool)
void endParameterName (bool last, bool emptyList, bool closeBracket)
void startParameterList (bool)
void endParameterList ()
virtual void exceptionEntry (const char *, bool)
void startConstraintList (const char *)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool)
void endMemberDocSimple (bool)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const char *l, bool isLast)
void endLabels ()
Public Member Functions inherited from OutputGenerator
OutputGenerator ()
virtual ~OutputGenerator ()
void startPlainFile (const char *name)
void endPlainFile ()
bool isEnabled () const
void pushGeneratorState ()
void popGeneratorState ()
Public Member Functions inherited from BaseOutputDocInterface
virtual ~BaseOutputDocInterface ()
virtual bool parseText (const QCString &s)
Public Member Functions inherited from CodeOutputInterface
virtual ~CodeOutputInterface ()
Static Public Member Functions
static void init ()
static void writeStyleSheetFile (QFile &f)
static void writeHeaderFile (QFile &f, const char *cssname)
static void writeFooterFile (QFile &f)
static void writeTabData ()
Additional initialization after indices have been created.
static void writeSearchInfo (FTextStream &t, const QCString &relPath)
static void writeSearchData (const char *dir)
static void writeSearchPage ()
static void writeExternalSearchPage ()
static QCString writeLogoAsString (const char *path)
static QCString writeSplitBarAsString (const char *name, const char *relpath)
Private Member Functions
void docify (const char *text, bool inHtmlComment)
HtmlGenerator & operator= (const HtmlGenerator &g)
HtmlGenerator (const HtmlGenerator &g)
Static Private Member Functions
static void writePageFooter (FTextStream &t, const QCString &, const QCString &, const QCString &)
Private Attributes
QCString lastTitle
QCString lastFile
QCString relPath
int m_sectionCount
bool m_emptySection
HtmlCodeGenerator m_codeGen
Additional Inherited Members
Public Types inherited from OutputGenerator
enum OutputType {
Html, Latex, Man, RTF,
XML, DEF, Perl
}
Public Types inherited from BaseOutputDocInterface
enum ParamListTypes { Param, RetVal, Exception }
enum SectionTypes { EnumValues, Examples }
Protected Attributes inherited from OutputGenerator
FTextStream t
QFile * file
QCString fileName
QCString dir
bool active
QStack< bool > * genStack
Detailed Description
Generator for HTML output.
Definition at line 71 of file htmlgen.h.
Constructor & Destructor Documentation
HtmlGenerator() [1/2]
HtmlGenerator::HtmlGenerator ()
Definition at line 681 of file htmlgen.cpp.
References Config_getString, OutputGenerator::dir, and m_emptySection.
~HtmlGenerator()
HtmlGenerator::~HtmlGenerator () virtual
Definition at line 687 of file htmlgen.cpp.
HtmlGenerator() [2/2]
HtmlGenerator::HtmlGenerator (const HtmlGenerator & g) private
Member Function Documentation
addIndexItem()
void HtmlGenerator::addIndexItem (const char * , const char *) virtual
Implements BaseOutputDocInterface.
Definition at line 1873 of file htmlgen.cpp.
addWord()
void HtmlGenerator::addWord (const char * word, bool hiPriority) virtual
Implements CodeOutputInterface.
Definition at line 2744 of file htmlgen.cpp.
References SearchIndexIntf::addWord(), and Doxygen::searchIndex.
clearBuffer()
void HtmlGenerator::clearBuffer ()
codify()
void HtmlGenerator::codify (const char * s) inline virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 98 of file htmlgen.h.
References HtmlCodeGenerator::codify(), and m_codeGen.
disable()
void HtmlGenerator::disable () inline virtual
Implements OutputGenerator.
Definition at line 90 of file htmlgen.h.
References OutputGenerator::active.
Referenced by disableIf(), and disableIfNot().
disableIf()
void HtmlGenerator::disableIf (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 92 of file htmlgen.h.
References disable(), and OutputGenerator::Html.
disableIfNot()
void HtmlGenerator::disableIfNot (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 93 of file htmlgen.h.
References disable(), and OutputGenerator::Html.
docify() [1/2]
void HtmlGenerator::docify (const char * s) virtual
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 1249 of file htmlgen.cpp.
Referenced by startParamList(), startSimpleSect(), writeChar(), writeObjectLink(), and writeStartAnnoItem().
docify() [2/2]
void HtmlGenerator::docify (const char * text, bool inHtmlComment) private
Definition at line 1254 of file htmlgen.cpp.
References OutputGenerator::t.
enable()
void HtmlGenerator::enable () inline virtual
Implements OutputGenerator.
Definition at line 88 of file htmlgen.h.
References OutputGenerator::active, and OutputGenerator::genStack.
Referenced by enableIf().
enableIf()
void HtmlGenerator::enableIf (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 91 of file htmlgen.h.
References enable(), and OutputGenerator::Html.
endAnonTypeScope()
void HtmlGenerator::endAnonTypeScope (int) inline virtual
Implements OutputGenerator.
Definition at line 189 of file htmlgen.h.
endBold()
void HtmlGenerator::endBold () inline virtual
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 219 of file htmlgen.h.
endCallGraph()
void HtmlGenerator::endCallGraph (const DotCallGraph & g) virtual
Implements OutputGenerator.
Definition at line 1796 of file htmlgen.cpp.
References OutputGenerator::dir, endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName, GOF_BITMAP, m_sectionCount, startSectionContent(), startSectionSummary(), OutputGenerator::t, and DotCallGraph::writeGraph().
endCenter()
void HtmlGenerator::endCenter () inline virtual
Implements BaseOutputDocInterface.
Definition at line 245 of file htmlgen.h.
References endl().
endClassDiagram()
void HtmlGenerator::endClassDiagram (const ClassDiagram & d, const char * fileName, const char * name) virtual
Implements OutputGenerator.
Definition at line 1371 of file htmlgen.cpp.
References convertToId(), OutputGenerator::dir, endl(), endSectionContent(), endSectionHeader(), endSectionSummary(), m_sectionCount, startSectionContent(), startSectionSummary(), OutputGenerator::t, and ClassDiagram::writeImage().
endCodeFragment()
void HtmlGenerator::endCodeFragment () inline virtual
Ends a source code fragment
Implements BaseOutputDocInterface.
Definition at line 215 of file htmlgen.h.
References PREFRAG_END.
endCodeLine()
void HtmlGenerator::endCodeLine () inline virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 112 of file htmlgen.h.
References HtmlCodeGenerator::endCodeLine(), and m_codeGen.
endConstraintDocs()
void HtmlGenerator::endConstraintDocs () virtual
Implements OutputGenerator.
Definition at line 2541 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endConstraintList()
void HtmlGenerator::endConstraintList () virtual
Implements OutputGenerator.
Definition at line 2546 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endConstraintParam()
void HtmlGenerator::endConstraintParam () virtual
Implements OutputGenerator.
Definition at line 2521 of file htmlgen.cpp.
References OutputGenerator::t.
endConstraintType()
void HtmlGenerator::endConstraintType () virtual
Implements OutputGenerator.
Definition at line 2531 of file htmlgen.cpp.
References OutputGenerator::t.
endContents()
void HtmlGenerator::endContents () virtual
Implements OutputGenerator.
Definition at line 2308 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endDescForItem()
void HtmlGenerator::endDescForItem () inline virtual
Implements BaseOutputDocInterface.
Definition at line 225 of file htmlgen.h.
endDescItem()
void HtmlGenerator::endDescItem () inline virtual
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 223 of file htmlgen.h.
endDescription()
void HtmlGenerator::endDescription () inline virtual
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 221 of file htmlgen.h.
References endl().
endDescTable()
void HtmlGenerator::endDescTable () virtual
Implements BaseOutputDocInterface.
Definition at line 1891 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endDescTableData()
void HtmlGenerator::endDescTableData () virtual
Implements BaseOutputDocInterface.
Definition at line 1921 of file htmlgen.cpp.
References OutputGenerator::t.
endDescTableRow()
void HtmlGenerator::endDescTableRow () virtual
Implements BaseOutputDocInterface.
Definition at line 1901 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endDescTableTitle()
void HtmlGenerator::endDescTableTitle () virtual
Implements BaseOutputDocInterface.
Definition at line 1911 of file htmlgen.cpp.
References OutputGenerator::t.
endDirDepGraph()
void HtmlGenerator::endDirDepGraph (const DotDirDeps & g) virtual
Implements OutputGenerator.
Definition at line 1814 of file htmlgen.cpp.
References OutputGenerator::dir, endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName, GOF_BITMAP, m_sectionCount, startSectionContent(), startSectionSummary(), OutputGenerator::t, and DotDirDeps::writeGraph().
endDotGraph()
void HtmlGenerator::endDotGraph (const DotClassGraph & g) virtual
Implements OutputGenerator.
Definition at line 1732 of file htmlgen.cpp.
References Config_getBool, OutputGenerator::dir, endHtmlLink(), endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName, GOF_BITMAP, Doxygen::htmlFileExtension, m_sectionCount, startHtmlLink(), startSectionContent(), startSectionSummary(), OutputGenerator::t, theTranslator, Translator::trLegend(), and DotClassGraph::writeGraph().
endDoxyAnchor()
void HtmlGenerator::endDoxyAnchor (const char * fName, const char * anchor) virtual
Implements OutputGenerator.
Definition at line 1057 of file htmlgen.cpp.
endEmphasis()
void HtmlGenerator::endEmphasis () inline virtual
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 217 of file htmlgen.h.
endFile()
void HtmlGenerator::endFile () virtual
Implements OutputGenerator.
Definition at line 975 of file htmlgen.cpp.
References OutputGenerator::endPlainFile().
endFontClass()
void HtmlGenerator::endFontClass () inline virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 116 of file htmlgen.h.
References HtmlCodeGenerator::endFontClass(), and m_codeGen.
endGroupCollaboration()
void HtmlGenerator::endGroupCollaboration (const DotGroupCollaboration & g) virtual
Implements OutputGenerator.
Definition at line 1778 of file htmlgen.cpp.
References OutputGenerator::dir, endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName, GOF_BITMAP, m_sectionCount, startSectionContent(), startSectionSummary(), OutputGenerator::t, and DotGroupCollaboration::writeGraph().
endGroupHeader()
void HtmlGenerator::endGroupHeader (int extraIndentLevel) virtual
Implements OutputGenerator.
Definition at line 1206 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endHeaderSection()
void HtmlGenerator::endHeaderSection () virtual
Implements OutputGenerator.
Definition at line 2583 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endHtmlLink()
void HtmlGenerator::endHtmlLink () virtual
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 1185 of file htmlgen.cpp.
References OutputGenerator::t.
Referenced by endDotGraph().
endInclDepGraph()
void HtmlGenerator::endInclDepGraph (const DotInclDepGraph & g) virtual
Implements OutputGenerator.
Definition at line 1760 of file htmlgen.cpp.
References OutputGenerator::dir, endSectionContent(), endSectionHeader(), endSectionSummary(), EOF_Html, OutputGenerator::fileName, GOF_BITMAP, m_sectionCount, startSectionContent(), startSectionSummary(), OutputGenerator::t, and DotInclDepGraph::writeGraph().
endIndent()
void HtmlGenerator::endIndent () virtual
Implements OutputGenerator.
Definition at line 1867 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endIndexItem()
void HtmlGenerator::endIndexItem (const char * ref, const char * file) virtual
Implements OutputGenerator.
Definition at line 1118 of file htmlgen.cpp.
References OutputGenerator::t.
endIndexKey()
void HtmlGenerator::endIndexKey () virtual
Implements OutputGenerator.
Definition at line 1552 of file htmlgen.cpp.
References OutputGenerator::t.
endIndexList()
void HtmlGenerator::endIndexList () virtual
Implements OutputGenerator.
Definition at line 1541 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endIndexListItem()
void HtmlGenerator::endIndexListItem () virtual
Implements OutputGenerator.
Definition at line 1089 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endIndexSection()
void HtmlGenerator::endIndexSection (IndexSections) inline virtual
Implements OutputGenerator.
Definition at line 133 of file htmlgen.h.
endIndexValue()
void HtmlGenerator::endIndexValue (const char * , bool) virtual
Implements OutputGenerator.
Definition at line 1563 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endInlineHeader()
void HtmlGenerator::endInlineHeader () virtual
Implements OutputGenerator.
Definition at line 2598 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endInlineMemberDoc()
void HtmlGenerator::endInlineMemberDoc () virtual
Implements OutputGenerator.
Definition at line 2648 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endInlineMemberName()
void HtmlGenerator::endInlineMemberName () virtual
Implements OutputGenerator.
Definition at line 2636 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endInlineMemberType()
void HtmlGenerator::endInlineMemberType () virtual
Implements OutputGenerator.
Definition at line 2624 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endItemList()
void HtmlGenerator::endItemList () inline virtual
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 155 of file htmlgen.h.
References endl().
endItemListItem()
void HtmlGenerator::endItemListItem () inline virtual
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 172 of file htmlgen.h.
endLabels()
void HtmlGenerator::endLabels () virtual
Implements OutputGenerator.
Definition at line 2668 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberDeclaration()
void HtmlGenerator::endMemberDeclaration (const char * anchor, const char * inheritId) virtual
Implements OutputGenerator.
Definition at line 2726 of file htmlgen.cpp.
References OutputGenerator::t.
endMemberDescription()
void HtmlGenerator::endMemberDescription () virtual
Implements OutputGenerator.
Definition at line 1475 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberDoc()
void HtmlGenerator::endMemberDoc (bool hasArgs) virtual
Implements OutputGenerator.
Definition at line 1716 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberDocList()
void HtmlGenerator::endMemberDocList () virtual
Implements OutputGenerator.
Definition at line 1573 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberDocName()
void HtmlGenerator::endMemberDocName () virtual
Implements OutputGenerator.
Definition at line 1618 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberDocPrefixItem()
void HtmlGenerator::endMemberDocPrefixItem () virtual
Implements OutputGenerator.
Definition at line 1602 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberDocSimple()
void HtmlGenerator::endMemberDocSimple (bool) virtual
Implements OutputGenerator.
Definition at line 2612 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberGroup()
void HtmlGenerator::endMemberGroup (bool) virtual
Implements OutputGenerator.
Definition at line 1856 of file htmlgen.cpp.
endMemberGroupDocs()
void HtmlGenerator::endMemberGroupDocs () virtual
Implements OutputGenerator.
Definition at line 1847 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endMemberGroupHeader()
void HtmlGenerator::endMemberGroupHeader () virtual
Implements OutputGenerator.
Definition at line 1837 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endMemberHeader()
void HtmlGenerator::endMemberHeader () virtual
Implements OutputGenerator.
Definition at line 1518 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberItem()
void HtmlGenerator::endMemberItem () virtual
Implements OutputGenerator.
Definition at line 1430 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endMemberList()
void HtmlGenerator::endMemberList () virtual
Implements OutputGenerator.
Definition at line 1398 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberSections()
void HtmlGenerator::endMemberSections () virtual
Implements OutputGenerator.
Definition at line 1489 of file htmlgen.cpp.
References DBG_HTML, endl(), m_emptySection, and OutputGenerator::t.
endMemberSubtitle()
void HtmlGenerator::endMemberSubtitle () virtual
Implements OutputGenerator.
Definition at line 1530 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endMemberTemplateParams()
void HtmlGenerator::endMemberTemplateParams (const char * anchor, const char * inheritId) virtual
Implements OutputGenerator.
Definition at line 1440 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endPageRef()
void HtmlGenerator::endPageRef (const char * , const char *) inline virtual
Implements BaseOutputDocInterface.
Definition at line 264 of file htmlgen.h.
endParagraph()
void HtmlGenerator::endParagraph () virtual
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 1074 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endParameterList()
void HtmlGenerator::endParameterList () virtual
Implements OutputGenerator.
Definition at line 1693 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endParameterName()
void HtmlGenerator::endParameterName (bool last, bool emptyList, bool closeBracket) virtual
Implements OutputGenerator.
Definition at line 1663 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endParameterType()
void HtmlGenerator::endParameterType () virtual
Implements OutputGenerator.
Definition at line 1651 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
endParamList()
void HtmlGenerator::endParamList () virtual
Implements BaseOutputDocInterface.
Definition at line 1955 of file htmlgen.cpp.
References OutputGenerator::t.
endProjectNumber()
void HtmlGenerator::endProjectNumber () virtual
Implements OutputGenerator.
Definition at line 985 of file htmlgen.cpp.
References OutputGenerator::t.
endQuickIndices()
void HtmlGenerator::endQuickIndices () virtual
Implements OutputGenerator.
Definition at line 2259 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
endSection()
void HtmlGenerator::endSection (const char * , SectionInfo::SectionType type) virtual
Implements BaseOutputDocInterface.
Definition at line 1236 of file htmlgen.cpp.
References SectionInfo::Page, SectionInfo::Paragraph, SectionInfo::Section, SectionInfo::Subsection, SectionInfo::Subsubsection, and OutputGenerator::t.
endSimpleSect()
void HtmlGenerator::endSimpleSect () virtual
Implements BaseOutputDocInterface.
Definition at line 1942 of file htmlgen.cpp.
References OutputGenerator::t.
endSmall()
void HtmlGenerator::endSmall () inline virtual
Implements BaseOutputDocInterface.
Definition at line 247 of file htmlgen.h.
References endl().
endSubsection()
void HtmlGenerator::endSubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 241 of file htmlgen.h.
References endl().
endSubsubsection()
void HtmlGenerator::endSubsubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 243 of file htmlgen.h.
References endl().
endTextBlock()
void HtmlGenerator::endTextBlock (bool) inline virtual
Implements OutputGenerator.
Definition at line 299 of file htmlgen.h.
endTextLink()
void HtmlGenerator::endTextLink () virtual
Implements BaseOutputDocInterface.
Definition at line 1170 of file htmlgen.cpp.
References OutputGenerator::t.
endTitle()
void HtmlGenerator::endTitle () inline virtual
Implements BaseOutputDocInterface.
Definition at line 141 of file htmlgen.h.
Referenced by endTitleHead().
endTitleHead()
void HtmlGenerator::endTitleHead (const char * , const char *) virtual
Implements OutputGenerator.
Definition at line 2577 of file htmlgen.cpp.
References endl(), endTitle(), and OutputGenerator::t.
endTypewriter()
void HtmlGenerator::endTypewriter () inline virtual
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 168 of file htmlgen.h.
exceptionEntry()
void HtmlGenerator::exceptionEntry (const char * prefix, bool closeBracket) virtual
Implements OutputGenerator.
Definition at line 1700 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
get()
OutputGenerator* HtmlGenerator::get (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 95 of file htmlgen.h.
References OutputGenerator::Html.
init()
void HtmlGenerator::init () static
Definition at line 692 of file htmlgen.cpp.
References Config_getBool, Config_getString, ResourceMgr::copyResource(), ResourceMgr::copyResourceAs(), createSubDirs(), endl(), err(), fileToString(), g_footer, g_header, g_mathjax_code, ResourceMgr::getAsString(), ResourceMgr::instance(), and OutputGenerator::t.
Referenced by generateOutput().
insertMemberAlign()
void HtmlGenerator::insertMemberAlign (bool templ) virtual
Implements OutputGenerator.
Definition at line 1452 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
isEnabled()
bool HtmlGenerator::isEnabled (OutputType o) inline virtual
Implements OutputGenerator.
Definition at line 94 of file htmlgen.h.
References OutputGenerator::active, and OutputGenerator::Html.
lastIndexPage()
void HtmlGenerator::lastIndexPage () inline virtual
Implements OutputGenerator.
Definition at line 301 of file htmlgen.h.
lineBreak()
void HtmlGenerator::lineBreak (const char * style) virtual
Implements BaseOutputDocInterface.
Definition at line 2554 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
operator=()
HtmlGenerator& HtmlGenerator::operator= (const HtmlGenerator & g) private
setCurrentDoc()
void HtmlGenerator::setCurrentDoc (Definition * context, const char * anchor, bool isSourceFile) virtual
Implements CodeOutputInterface.
Definition at line 2736 of file htmlgen.cpp.
References Doxygen::searchIndex, and SearchIndexIntf::setCurrentDoc().
startAnonTypeScope()
void HtmlGenerator::startAnonTypeScope (int) inline virtual
Implements OutputGenerator.
Definition at line 188 of file htmlgen.h.
startBold()
void HtmlGenerator::startBold () inline virtual
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 218 of file htmlgen.h.
startCallGraph()
void HtmlGenerator::startCallGraph () virtual
Implements OutputGenerator.
Definition at line 1791 of file htmlgen.cpp.
References m_sectionCount, startSectionHeader(), and OutputGenerator::t.
startCenter()
void HtmlGenerator::startCenter () inline virtual
Implements BaseOutputDocInterface.
Definition at line 244 of file htmlgen.h.
References endl().
startClassDiagram()
void HtmlGenerator::startClassDiagram () virtual
Implements OutputGenerator.
Definition at line 1366 of file htmlgen.cpp.
References m_sectionCount, startSectionHeader(), and OutputGenerator::t.
startCodeFragment()
void HtmlGenerator::startCodeFragment () inline virtual
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Implements BaseOutputDocInterface.
Definition at line 214 of file htmlgen.h.
References PREFRAG_START.
startCodeLine()
void HtmlGenerator::startCodeLine (bool hasLineNumbers) inline virtual
Implements CodeOutputInterface.
Definition at line 110 of file htmlgen.h.
References m_codeGen, and HtmlCodeGenerator::startCodeLine().
startConstraintDocs()
void HtmlGenerator::startConstraintDocs () virtual
Implements OutputGenerator.
Definition at line 2536 of file htmlgen.cpp.
References OutputGenerator::t.
startConstraintList()
void HtmlGenerator::startConstraintList (const char * header) virtual
Implements OutputGenerator.
Definition at line 2509 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
startConstraintParam()
void HtmlGenerator::startConstraintParam () virtual
Implements OutputGenerator.
Definition at line 2516 of file htmlgen.cpp.
References OutputGenerator::t.
startConstraintType()
void HtmlGenerator::startConstraintType () virtual
Implements OutputGenerator.
Definition at line 2526 of file htmlgen.cpp.
References OutputGenerator::t.
startContents()
void HtmlGenerator::startContents () virtual
Implements OutputGenerator.
Definition at line 2303 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
startDescForItem()
void HtmlGenerator::startDescForItem () inline virtual
Implements BaseOutputDocInterface.
Definition at line 224 of file htmlgen.h.
startDescItem()
void HtmlGenerator::startDescItem () inline virtual
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 222 of file htmlgen.h.
startDescription()
void HtmlGenerator::startDescription () inline virtual
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 220 of file htmlgen.h.
References endl().
startDescTable()
void HtmlGenerator::startDescTable (const char * title) virtual
Implements BaseOutputDocInterface.
Definition at line 1886 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
startDescTableData()
void HtmlGenerator::startDescTableData () virtual
Implements BaseOutputDocInterface.
Definition at line 1916 of file htmlgen.cpp.
References OutputGenerator::t.
startDescTableRow()
void HtmlGenerator::startDescTableRow () virtual
Implements BaseOutputDocInterface.
Definition at line 1896 of file htmlgen.cpp.
References OutputGenerator::t.
startDescTableTitle()
void HtmlGenerator::startDescTableTitle () virtual
Implements BaseOutputDocInterface.
Definition at line 1906 of file htmlgen.cpp.
References OutputGenerator::t.
startDirDepGraph()
void HtmlGenerator::startDirDepGraph () virtual
Implements OutputGenerator.
Definition at line 1809 of file htmlgen.cpp.
References m_sectionCount, startSectionHeader(), and OutputGenerator::t.
startDotGraph()
void HtmlGenerator::startDotGraph () virtual
Implements OutputGenerator.
Definition at line 1727 of file htmlgen.cpp.
References m_sectionCount, startSectionHeader(), and OutputGenerator::t.
startDoxyAnchor()
void HtmlGenerator::startDoxyAnchor (const char * fName, const char * manName, const char * anchor, const char * name, const char * args) virtual
Implements OutputGenerator.
Definition at line 1050 of file htmlgen.cpp.
References OutputGenerator::t.
startEmphasis()
void HtmlGenerator::startEmphasis () inline virtual
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 216 of file htmlgen.h.
startFile()
void HtmlGenerator::startFile (const char * name, const char * manName, const char * title) virtual
Implements OutputGenerator.
Definition at line 870 of file htmlgen.cpp.
References IndexList::addIndexFile(), Config_getBool, convertToHtml(), endl(), OutputGenerator::fileName, filterTitle(), g_header, Doxygen::htmlFileExtension, Doxygen::indexList, lastFile, lastTitle, m_codeGen, m_sectionCount, relativePathToRoot(), HtmlCodeGenerator::setRelativePath(), HtmlCodeGenerator::setTextStream(), OutputGenerator::startPlainFile(), substituteHtmlKeywords(), OutputGenerator::t, theTranslator, Translator::trGeneratedBy(), Translator::trSearch(), and versionString.
startFontClass()
void HtmlGenerator::startFontClass (const char * clsName) inline virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 114 of file htmlgen.h.
References m_codeGen, and HtmlCodeGenerator::startFontClass().
startGroupCollaboration()
void HtmlGenerator::startGroupCollaboration () virtual
Implements OutputGenerator.
Definition at line 1773 of file htmlgen.cpp.
References m_sectionCount, startSectionHeader(), and OutputGenerator::t.
startGroupHeader()
void HtmlGenerator::startGroupHeader (int extraIndentLevel) virtual
Implements OutputGenerator.
Definition at line 1190 of file htmlgen.cpp.
References OutputGenerator::t.
startHeaderSection()
void HtmlGenerator::startHeaderSection () virtual
Implements OutputGenerator.
Definition at line 2566 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
startHtmlLink()
void HtmlGenerator::startHtmlLink (const char * url) virtual
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 1175 of file htmlgen.cpp.
References Config_getBool, and OutputGenerator::t.
Referenced by endDotGraph().
startInclDepGraph()
void HtmlGenerator::startInclDepGraph () virtual
Implements OutputGenerator.
Definition at line 1755 of file htmlgen.cpp.
References m_sectionCount, startSectionHeader(), and OutputGenerator::t.
startIndent()
void HtmlGenerator::startIndent () virtual
Implements OutputGenerator.
Definition at line 1860 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startIndexItem()
void HtmlGenerator::startIndexItem (const char * ref, const char * file) virtual
Implements OutputGenerator.
Definition at line 1094 of file htmlgen.cpp.
References externalLinkTarget(), externalRef(), Doxygen::htmlFileExtension, and OutputGenerator::t.
startIndexKey()
void HtmlGenerator::startIndexKey () virtual
Implements OutputGenerator.
Definition at line 1546 of file htmlgen.cpp.
References OutputGenerator::t.
startIndexList()
void HtmlGenerator::startIndexList () virtual
Implements OutputGenerator.
Definition at line 1536 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
startIndexListItem()
void HtmlGenerator::startIndexListItem () virtual
Implements OutputGenerator.
Definition at line 1084 of file htmlgen.cpp.
References OutputGenerator::t.
startIndexSection()
void HtmlGenerator::startIndexSection (IndexSections) inline virtual
Implements OutputGenerator.
Definition at line 132 of file htmlgen.h.
startIndexValue()
void HtmlGenerator::startIndexValue (bool) virtual
Implements OutputGenerator.
Definition at line 1557 of file htmlgen.cpp.
References OutputGenerator::t.
startInlineHeader()
void HtmlGenerator::startInlineHeader () virtual
Implements OutputGenerator.
Definition at line 2588 of file htmlgen.cpp.
References endl(), m_emptySection, and OutputGenerator::t.
startInlineMemberDoc()
void HtmlGenerator::startInlineMemberDoc () virtual
Implements OutputGenerator.
Definition at line 2642 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startInlineMemberName()
void HtmlGenerator::startInlineMemberName () virtual
Implements OutputGenerator.
Definition at line 2630 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startInlineMemberType()
void HtmlGenerator::startInlineMemberType () virtual
Implements OutputGenerator.
Definition at line 2618 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startItemList()
void HtmlGenerator::startItemList () inline virtual
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 154 of file htmlgen.h.
References endl().
startItemListItem()
void HtmlGenerator::startItemListItem () inline virtual
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 171 of file htmlgen.h.
startLabels()
void HtmlGenerator::startLabels () virtual
Implements OutputGenerator.
Definition at line 2654 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startMemberDeclaration()
void HtmlGenerator::startMemberDeclaration () inline virtual
Implements OutputGenerator.
Definition at line 205 of file htmlgen.h.
startMemberDescription()
void HtmlGenerator::startMemberDescription (const char * anchor, const char * inheritId) virtual
Implements OutputGenerator.
Definition at line 1459 of file htmlgen.cpp.
References DBG_HTML, endl(), m_emptySection, and OutputGenerator::t.
startMemberDoc()
void HtmlGenerator::startMemberDoc (const char * clName, const char * memName, const char * anchor, const char * title, int memCount, int memTotal, bool showInline) virtual
Implements OutputGenerator.
Definition at line 1578 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startMemberDocList()
void HtmlGenerator::startMemberDocList () virtual
Implements OutputGenerator.
Definition at line 1568 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startMemberDocName()
void HtmlGenerator::startMemberDocName (bool) virtual
Implements OutputGenerator.
Definition at line 1608 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startMemberDocPrefixItem()
void HtmlGenerator::startMemberDocPrefixItem () virtual
Implements OutputGenerator.
Definition at line 1596 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startMemberDocSimple()
void HtmlGenerator::startMemberDocSimple (bool isEnum) virtual
Implements OutputGenerator.
Definition at line 2603 of file htmlgen.cpp.
References DBG_HTML, endl(), OutputGenerator::t, theTranslator, Translator::trCompoundMembers(), and Translator::trEnumerationValues().
startMemberGroup()
void HtmlGenerator::startMemberGroup () virtual
Implements OutputGenerator.
Definition at line 1852 of file htmlgen.cpp.
startMemberGroupDocs()
void HtmlGenerator::startMemberGroupDocs () virtual
Implements OutputGenerator.
Definition at line 1842 of file htmlgen.cpp.
References OutputGenerator::t.
startMemberGroupHeader()
void HtmlGenerator::startMemberGroupHeader (bool) virtual
Implements OutputGenerator.
Definition at line 1832 of file htmlgen.cpp.
References OutputGenerator::t.
startMemberHeader()
void HtmlGenerator::startMemberHeader (const char * anchor) virtual
Implements OutputGenerator.
Definition at line 1498 of file htmlgen.cpp.
References DBG_HTML, endl(), m_emptySection, and OutputGenerator::t.
startMemberItem()
void HtmlGenerator::startMemberItem (const char * anchor, int annoType, const char * inheritId) virtual
Implements OutputGenerator.
Definition at line 1407 of file htmlgen.cpp.
References DBG_HTML, endl(), m_emptySection, and OutputGenerator::t.
startMemberList()
void HtmlGenerator::startMemberList () virtual
Implements OutputGenerator.
Definition at line 1393 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startMemberSections()
void HtmlGenerator::startMemberSections () virtual
Implements OutputGenerator.
Definition at line 1481 of file htmlgen.cpp.
References DBG_HTML, endl(), m_emptySection, and OutputGenerator::t.
startMemberSubtitle()
void HtmlGenerator::startMemberSubtitle () virtual
Implements OutputGenerator.
Definition at line 1524 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startMemberTemplateParams()
void HtmlGenerator::startMemberTemplateParams () virtual
Implements OutputGenerator.
Definition at line 1436 of file htmlgen.cpp.
startPageRef()
void HtmlGenerator::startPageRef () inline virtual
Implements BaseOutputDocInterface.
Definition at line 263 of file htmlgen.h.
startParagraph()
void HtmlGenerator::startParagraph (const char * classDef) virtual
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 1066 of file htmlgen.cpp.
References endl(), and OutputGenerator::t.
startParameterList()
void HtmlGenerator::startParameterList (bool openBracket) virtual
Implements OutputGenerator.
Definition at line 1624 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startParameterName()
void HtmlGenerator::startParameterName (bool) virtual
Implements OutputGenerator.
Definition at line 1657 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startParameterType()
void HtmlGenerator::startParameterType (bool first, const char * key) virtual
Implements OutputGenerator.
Definition at line 1632 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
startParamList()
void HtmlGenerator::startParamList (ParamListTypes , const char * title) virtual
Implements BaseOutputDocInterface.
Definition at line 1947 of file htmlgen.cpp.
References docify(), and OutputGenerator::t.
startProjectNumber()
void HtmlGenerator::startProjectNumber () virtual
Implements OutputGenerator.
Definition at line 980 of file htmlgen.cpp.
References OutputGenerator::t.
startQuickIndices()
void HtmlGenerator::startQuickIndices () inline virtual
Implements OutputGenerator.
Definition at line 265 of file htmlgen.h.
startSection()
void HtmlGenerator::startSection (const char * lab, const char * , SectionInfo::SectionType type) virtual
Implements BaseOutputDocInterface.
Definition at line 1222 of file htmlgen.cpp.
References SectionInfo::Page, SectionInfo::Paragraph, SectionInfo::Section, SectionInfo::Subsection, SectionInfo::Subsubsection, and OutputGenerator::t.
startSimpleSect()
void HtmlGenerator::startSimpleSect (SectionTypes , const char * filename, const char * anchor, const char * title) virtual
Implements BaseOutputDocInterface.
Definition at line 1926 of file htmlgen.cpp.
References docify(), OutputGenerator::t, and writeObjectLink().
startSmall()
void HtmlGenerator::startSmall () inline virtual
Implements BaseOutputDocInterface.
Definition at line 246 of file htmlgen.h.
References endl().
startSubsection()
void HtmlGenerator::startSubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 240 of file htmlgen.h.
startSubsubsection()
void HtmlGenerator::startSubsubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 242 of file htmlgen.h.
startTextBlock()
void HtmlGenerator::startTextBlock (bool) inline virtual
Implements OutputGenerator.
Definition at line 297 of file htmlgen.h.
startTextLink()
void HtmlGenerator::startTextLink (const char * file, const char * anchor) virtual
Implements BaseOutputDocInterface.
Definition at line 1162 of file htmlgen.cpp.
References Doxygen::htmlFileExtension, and OutputGenerator::t.
startTitle()
void HtmlGenerator::startTitle () inline virtual
Implements BaseOutputDocInterface.
Definition at line 140 of file htmlgen.h.
Referenced by startTitleHead().
startTitleHead()
void HtmlGenerator::startTitleHead (const char *) virtual
Implements OutputGenerator.
Definition at line 2571 of file htmlgen.cpp.
References endl(), startTitle(), and OutputGenerator::t.
startTypewriter()
void HtmlGenerator::startTypewriter () inline virtual
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 167 of file htmlgen.h.
writeAnchor()
void HtmlGenerator::writeAnchor (const char * , const char * name) inline virtual
Implements BaseOutputDocInterface.
Definition at line 212 of file htmlgen.h.
writeChar()
void HtmlGenerator::writeChar (char c) virtual
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 1284 of file htmlgen.cpp.
References docify().
writeCodeAnchor()
void HtmlGenerator::writeCodeAnchor (const char * name) inline virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 118 of file htmlgen.h.
References m_codeGen, and HtmlCodeGenerator::writeCodeAnchor().
writeCodeLink()
void HtmlGenerator::writeCodeLink (const char * ref, const char * file, const char * anchor, const char * name, const char * tooltip) inline virtual
Writes a link to an object in a code fragment.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 100 of file htmlgen.h.
References m_codeGen, and HtmlCodeGenerator::writeCodeLink().
writeDoc()
void HtmlGenerator::writeDoc (DocNode * n, Definition * ctx, MemberDef *) virtual
Implements OutputGenerator.
Definition at line 1960 of file htmlgen.cpp.
References DocNode::accept(), m_codeGen, and OutputGenerator::t.
writeEndAnnoItem()
void HtmlGenerator::writeEndAnnoItem (const char *) inline virtual
Implements OutputGenerator.
Definition at line 239 of file htmlgen.h.
References endl().
writeExternalSearchPage()
void HtmlGenerator::writeExternalSearchPage () static
Definition at line 2405 of file htmlgen.cpp.
References Config_getBool, Config_getList, Config_getString, endl(), err(), OutputGenerator::fileName, g_header, ResourceMgr::getAsString(), HLI_Search, Doxygen::htmlFileExtension, ResourceMgr::instance(), substituteHtmlKeywords(), OutputGenerator::t, theTranslator, Translator::trGeneratedBy(), Translator::trSearch(), Translator::trSearchResults(), Translator::trSearchResultsTitle(), versionString, writeDefaultQuickLinks(), writePageFooter(), and writeSplitBarAsString().
Referenced by generateOutput().
writeFooter()
void HtmlGenerator::writeFooter (const char * navPath) virtual
Implements OutputGenerator.
Definition at line 970 of file htmlgen.cpp.
References lastTitle, OutputGenerator::t, and writePageFooter().
writeFooterFile()
void HtmlGenerator::writeFooterFile (QFile & f) static
Definition at line 863 of file htmlgen.cpp.
References endl(), ResourceMgr::getAsString(), ResourceMgr::instance(), OutputGenerator::t, and versionString.
Referenced by readConfiguration().
writeGraphicalHierarchy()
void HtmlGenerator::writeGraphicalHierarchy (const DotGfxHierarchyTable & g) virtual
Implements OutputGenerator.
Definition at line 1827 of file htmlgen.cpp.
References OutputGenerator::dir, OutputGenerator::fileName, OutputGenerator::t, and DotGfxHierarchyTable::writeGraph().
writeHeaderFile()
void HtmlGenerator::writeHeaderFile (QFile & f, const char * cssname) static
Definition at line 856 of file htmlgen.cpp.
References endl(), ResourceMgr::getAsString(), ResourceMgr::instance(), OutputGenerator::t, and versionString.
Referenced by readConfiguration().
writeInheritedSectionTitle()
void HtmlGenerator::writeInheritedSectionTitle (const char * id, const char * ref, const char * file, const char * anchor, const char * title, const char * name) virtual
Implements OutputGenerator.
Definition at line 2674 of file htmlgen.cpp.
References convertToHtml(), DBG_HTML, endl(), externalLinkTarget(), externalRef(), Doxygen::htmlFileExtension, relPath, OutputGenerator::t, theTranslator, and Translator::trInheritedFrom().
writeLabel()
void HtmlGenerator::writeLabel (const char * l, bool isLast) virtual
Implements OutputGenerator.
Definition at line 2660 of file htmlgen.cpp.
References DBG_HTML, endl(), and OutputGenerator::t.
writeLatexSpacing()
void HtmlGenerator::writeLatexSpacing () inline virtual
Implements OutputGenerator.
Definition at line 236 of file htmlgen.h.
writeLineNumber()
void HtmlGenerator::writeLineNumber (const char * ref, const char * file, const char * anchor, int lineNumber) inline virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
Implements CodeOutputInterface.
Definition at line 104 of file htmlgen.h.
References m_codeGen, and HtmlCodeGenerator::writeLineNumber().
writeLogo()
void HtmlGenerator::writeLogo () virtual
Implements OutputGenerator.
Definition at line 959 of file htmlgen.cpp.
References OutputGenerator::t, and writeLogoAsString().
writeLogoAsString()
QCString HtmlGenerator::writeLogoAsString (const char * path) static
Definition at line 935 of file htmlgen.cpp.
References Config_getBool, Config_getString, dateToString(), theTranslator, Translator::trGeneratedAt(), Translator::trGeneratedBy(), and versionString.
Referenced by writeLogo(), and writeSearchPage().
writeNavigationPath()
void HtmlGenerator::writeNavigationPath (const char * s) virtual
Implements OutputGenerator.
Definition at line 2298 of file htmlgen.cpp.
References substitute(), and OutputGenerator::t.
writeNonBreakableSpace()
void HtmlGenerator::writeNonBreakableSpace (int n) virtual
Implements BaseOutputDocInterface.
Definition at line 1877 of file htmlgen.cpp.
References OutputGenerator::t.
writeObjectLink()
void HtmlGenerator::writeObjectLink (const char * ref, const char * file, const char * anchor, const char * name) virtual
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 1141 of file htmlgen.cpp.
References docify(), externalLinkTarget(), externalRef(), Doxygen::htmlFileExtension, and OutputGenerator::t.
Referenced by startSimpleSect().
writePageFooter()
void HtmlGenerator::writePageFooter (FTextStream & t, const QCString & lastTitle, const QCString & relPath, const QCString & navPath) static private
Definition at line 964 of file htmlgen.cpp.
References convertToHtml(), g_footer, and substituteHtmlKeywords().
Referenced by writeExternalSearchPage(), writeFooter(), and writeSearchPage().
writePageLink()
void HtmlGenerator::writePageLink (const char * , bool) inline virtual
Implements OutputGenerator.
Definition at line 134 of file htmlgen.h.
writeQuickLinks()
void HtmlGenerator::writeQuickLinks (bool compact, HighlightedItem hli, const char * file) virtual
Implements OutputGenerator.
Definition at line 2313 of file htmlgen.cpp.
References OutputGenerator::t, and writeDefaultQuickLinks().
writeRuler()
void HtmlGenerator::writeRuler () inline virtual
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 211 of file htmlgen.h.
writeSearchData()
void HtmlGenerator::writeSearchData (const char * dir) static
Definition at line 801 of file htmlgen.cpp.
References IndexList::addImageFile(), IndexList::addStyleSheetFile(), Config_getBool, Config_getString, ResourceMgr::copyResource(), ResourceMgr::getAsString(), Doxygen::indexList, ResourceMgr::instance(), replaceColorMarkers(), substitute(), OutputGenerator::t, and versionString.
Referenced by generateOutput().
writeSearchInfo() [1/2]
void HtmlGenerator::writeSearchInfo (FTextStream & t, const QCString & relPath) static
Definition at line 905 of file htmlgen.cpp.
References Config_getBool.
writeSearchInfo() [2/2]
void HtmlGenerator::writeSearchInfo () virtual
Implements OutputGenerator.
Definition at line 929 of file htmlgen.cpp.
References OutputGenerator::t.
writeSearchPage()
void HtmlGenerator::writeSearchPage () static
Definition at line 2319 of file htmlgen.cpp.
References Config_getBool, Config_getString, convertToHtml(), ResourceMgr::copyResource(), endl(), err(), OutputGenerator::fileName, g_header, ResourceMgr::getAsString(), HLI_Search, ResourceMgr::instance(), substitute(), substituteHtmlKeywords(), OutputGenerator::t, theTranslator, Translator::trGeneratedBy(), Translator::trSearch(), Translator::trSearchMatches(), Translator::trSearchResults(), Translator::trSearchResultsTitle(), versionString, writeDefaultQuickLinks(), writeLogoAsString(), writePageFooter(), and writeSplitBarAsString().
Referenced by generateOutput().
writeSplitBar()
void HtmlGenerator::writeSplitBar (const char * name) virtual
Implements OutputGenerator.
Definition at line 2293 of file htmlgen.cpp.
References OutputGenerator::t, and writeSplitBarAsString().
writeSplitBarAsString()
QCString HtmlGenerator::writeSplitBarAsString (const char * name, const char * relpath) static
Definition at line 2264 of file htmlgen.cpp.
References Config_getBool, and Doxygen::htmlFileExtension.
Referenced by writeExternalSearchPage(), writeSearchPage(), and writeSplitBar().
writeStartAnnoItem()
void HtmlGenerator::writeStartAnnoItem (const char * type, const char * file, const char * path, const char * name) virtual
Implements OutputGenerator.
Definition at line 1131 of file htmlgen.cpp.
References docify(), Doxygen::htmlFileExtension, and OutputGenerator::t.
writeString()
void HtmlGenerator::writeString (const char * text) virtual
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 1079 of file htmlgen.cpp.
References OutputGenerator::t.
writeStyleInfo()
void HtmlGenerator::writeStyleInfo (int part) virtual
Implements OutputGenerator.
Definition at line 990 of file htmlgen.cpp.
References IndexList::addStyleSheetFile(), Config_getBool, Config_getList, Config_getString, OutputGenerator::endPlainFile(), err(), OutputGenerator::fileName, fileToString(), Doxygen::indexList, ResourceMgr::instance(), replaceColorMarkers(), OutputGenerator::startPlainFile(), substitute(), OutputGenerator::t, and versionString.
writeStyleSheetFile()
void HtmlGenerator::writeStyleSheetFile (QFile & f) static
Definition at line 850 of file htmlgen.cpp.
References ResourceMgr::instance(), replaceColorMarkers(), substitute(), OutputGenerator::t, and versionString.
Referenced by readConfiguration().
writeSummaryLink()
void HtmlGenerator::writeSummaryLink (const char * file, const char * anchor, const char * title, bool first) virtual
Implements OutputGenerator.
Definition at line 2700 of file htmlgen.cpp.
References OutputGenerator::file, Doxygen::htmlFileExtension, and OutputGenerator::t.
writeSynopsis()
void HtmlGenerator::writeSynopsis () inline virtual
Implements OutputGenerator.
Definition at line 260 of file htmlgen.h.
writeTabData()
void HtmlGenerator::writeTabData () static
Additional initialization after indices have been created.
Definition at line 772 of file htmlgen.cpp.
References IndexList::addStyleSheetFile(), Config_getString, ResourceMgr::copyResource(), Doxygen::indexList, and ResourceMgr::instance().
Referenced by generateOutput().
writeTooltip()
void HtmlGenerator::writeTooltip (const char * id, const DocLinkInfo & docInfo, const char * decl, const char * desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) inline virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 106 of file htmlgen.h.
References m_codeGen, and HtmlCodeGenerator::writeTooltip().
Member Data Documentation
lastFile
QCString HtmlGenerator::lastFile private
Definition at line 343 of file htmlgen.h.
Referenced by startFile().
lastTitle
QCString HtmlGenerator::lastTitle private
Definition at line 342 of file htmlgen.h.
Referenced by startFile(), and writeFooter().
m_codeGen
HtmlCodeGenerator HtmlGenerator::m_codeGen private
Definition at line 352 of file htmlgen.h.
Referenced by codify(), endCodeLine(), endFontClass(), startCodeLine(), startFile(), startFontClass(), writeCodeAnchor(), writeCodeLink(), writeDoc(), writeLineNumber(), and writeTooltip().
m_emptySection
bool HtmlGenerator::m_emptySection private
Definition at line 351 of file htmlgen.h.
Referenced by endMemberSections(), HtmlGenerator(), startInlineHeader(), startMemberDescription(), startMemberHeader(), startMemberItem(), and startMemberSections().
m_sectionCount
int HtmlGenerator::m_sectionCount private
Definition at line 350 of file htmlgen.h.
Referenced by endCallGraph(), endClassDiagram(), endDirDepGraph(), endDotGraph(), endGroupCollaboration(), endInclDepGraph(), startCallGraph(), startClassDiagram(), startDirDepGraph(), startDotGraph(), startFile(), startGroupCollaboration(), and startInclDepGraph().
relPath
QCString HtmlGenerator::relPath private
Definition at line 344 of file htmlgen.h.
Referenced by writeInheritedSectionTitle().
The documentation for this class was generated from the following files:
src/htmlgen.h
src/htmlgen.cpp