Doxygen: src/docbookvisitor.cpp File Reference
docbookvisitor.cpp File Reference
#include <qfileinfo.h>
#include "docbookvisitor.h"
#include "docparser.h"
#include "language.h"
#include "doxygen.h"
#include "outputgen.h"
#include "docbookgen.h"
#include "dot.h"
#include "message.h"
#include "util.h"
#include "parserintf.h"
#include "filename.h"
#include "config.h"
#include "filedef.h"
#include "msc.h"
#include "dia.h"
#include "htmlentity.h"
#include "plantuml.h"
Functions
static void visitPreStart (FTextStream &t, const bool hasCaption, QCString name, QCString width, QCString height)
static void visitPostEnd (FTextStream &t, const bool hasCaption)
static void visitCaption (DocbookDocVisitor *parent, QList< DocNode > children)
Function Documentation
visitCaption()
static void visitCaption (DocbookDocVisitor * parent, QList< DocNode > children) static
Definition at line 79 of file docbookvisitor.cpp.
References DocNode::accept().
Referenced by DocbookDocVisitor::writeDiaFile(), DocbookDocVisitor::writeDotFile(), DocbookDocVisitor::writeMscFile(), and DocbookDocVisitor::writePlantUMLFile().
visitPostEnd()
static void visitPostEnd (FTextStream & t, const bool hasCaption) static
Definition at line 68 of file docbookvisitor.cpp.
References endl().
Referenced by DocbookDocVisitor::endDiaFile(), DocbookDocVisitor::endDotFile(), DocbookDocVisitor::endMscFile(), DocbookDocVisitor::visitPost(), DocbookDocVisitor::writeDiaFile(), DocbookDocVisitor::writeDotFile(), DocbookDocVisitor::writeMscFile(), and DocbookDocVisitor::writePlantUMLFile().
visitPreStart()
static void visitPreStart (FTextStream & t, const bool hasCaption, QCString name, QCString width, QCString height) static
Definition at line 39 of file docbookvisitor.cpp.
References convertToXML(), and endl().
Referenced by DocbookDocVisitor::startDiaFile(), DocbookDocVisitor::startDotFile(), DocbookDocVisitor::startMscFile(), DocbookDocVisitor::visitPre(), DocbookDocVisitor::writeDiaFile(), DocbookDocVisitor::writeDotFile(), DocbookDocVisitor::writeMscFile(), and DocbookDocVisitor::writePlantUMLFile().