Doxygen: InheritedMemberInfoContext Class Reference
InheritedMemberInfoContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static InheritedMemberInfoContext * alloc (ClassDef *cd, MemberList *ml, const QCString &title)
Private Member Functions
InheritedMemberInfoContext (ClassDef *cd, MemberList *ml, const QCString &title)
~InheritedMemberInfoContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1071 of file context.h.
Constructor & Destructor Documentation
InheritedMemberInfoContext()
InheritedMemberInfoContext::InheritedMemberInfoContext (ClassDef * cd, MemberList * ml, const QCString & title) private
Definition at line 9100 of file context.cpp.
References p, and Private.
Referenced by alloc().
~InheritedMemberInfoContext()
InheritedMemberInfoContext::~InheritedMemberInfoContext () private
Definition at line 9106 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int InheritedMemberInfoContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 1079 of file context.h.
References RefCountedContext::addRef().
alloc()
static InheritedMemberInfoContext* InheritedMemberInfoContext::alloc (ClassDef * cd, MemberList * ml, const QCString & title) inline static
Definition at line 1074 of file context.h.
References InheritedMemberInfoContext().
Referenced by InheritedMemberInfoListContext::Private::addInheritedMembers().
get()
TemplateVariant InheritedMemberInfoContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 9111 of file context.cpp.
References InheritedMemberInfoContext::Private::get(), and p.
release()
virtual int InheritedMemberInfoContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 1080 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* InheritedMemberInfoContext::p private
Definition at line 1085 of file context.h.
Referenced by get(), InheritedMemberInfoContext(), and ~InheritedMemberInfoContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp