Doxygen: DocNode Class Reference
DocNode Class Reference abstract
Abstract node interface with type information.
#include <docparser.h>
Inherited by DocAnchor, DocAutoList, DocAutoListItem, DocCite, DocCopy, DocDiaFile, DocDotFile, DocFormula, DocHorRuler, DocHRef, DocHtmlBlockQuote, DocHtmlCaption, DocHtmlCell, DocHtmlDescData, DocHtmlDescList, DocHtmlDescTitle, DocHtmlHeader, DocHtmlList, DocHtmlListItem, DocHtmlRow, DocHtmlTable, DocImage, DocInclude, DocIncOperator, DocIndexEntry, DocInternal, DocInternalRef, DocLineBreak, DocLink, DocLinkedWord, DocMscFile, DocPara, DocParamList, DocParamSect, DocParBlock, DocRef, DocRoot, DocSecRefItem, DocSecRefList, DocSection, DocSimpleList, DocSimpleListItem, DocSimpleSect, DocSimpleSectSep, DocStyleChange, DocSymbol, DocText, DocTitle, DocURL, DocVerbatim, DocVhdlFlow, DocWhiteSpace, DocWord, and DocXRefItem.
Public Types
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Public Member Functions
DocNode ()
virtual ~DocNode ()
virtual Kind kind () const =0
DocNode * parent () const
void setParent (DocNode *parent)
virtual void accept (DocVisitor *v)=0
bool isPreformatted () const
Protected Member Functions
void setInsidePreformatted (bool p)
Protected Attributes
DocNode * m_parent
Private Attributes
bool m_insidePre
Detailed Description
Abstract node interface with type information.
Definition at line 79 of file docparser.h.
Member Enumeration Documentation
Kind
enum DocNode::Kind
Available node types.
Enumerator
Kind_Root
Kind_Word
Kind_WhiteSpace
Kind_Para
Kind_AutoList
Kind_AutoListItem
Kind_Symbol
Kind_URL
Kind_StyleChange
Kind_SimpleSect
Kind_Title
Kind_SimpleList
Kind_SimpleListItem
Kind_Section
Kind_Verbatim
Kind_XRefItem
Kind_HtmlList
Kind_HtmlListItem
Kind_HtmlDescList
Kind_HtmlDescData
Kind_HtmlDescTitle
Kind_HtmlTable
Kind_HtmlRow
Kind_HtmlCell
Kind_HtmlCaption
Kind_LineBreak
Kind_HorRuler
Kind_Anchor
Kind_IndexEntry
Kind_Internal
Kind_HRef
Kind_Include
Kind_IncOperator
Kind_HtmlHeader
Kind_Image
Kind_DotFile
Kind_Link
Kind_Ref
Kind_Formula
Kind_SecRefItem
Kind_SecRefList
Kind_SimpleSectSep
Kind_LinkedWord
Kind_ParamSect
Kind_ParamList
Kind_InternalRef
Kind_Copy
Kind_Text
Kind_MscFile
Kind_HtmlBlockQuote
Kind_VhdlFlow
Kind_ParBlock
Kind_DiaFile
Definition at line 83 of file docparser.h.
Constructor & Destructor Documentation
DocNode()
DocNode::DocNode () inline
Creates a new node
Definition at line 138 of file docparser.h.
~DocNode()
virtual DocNode::~DocNode () inline virtual
Destroys a node.
Definition at line 141 of file docparser.h.
Member Function Documentation
accept()
virtual void DocNode::accept (DocVisitor * v) pure virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implemented in DocRoot, DocText, DocHtmlBlockQuote, DocHtmlTable, DocHtmlRow, DocHtmlCaption, DocHtmlCell, DocHtmlDescData, DocHtmlListItem, DocSimpleListItem, DocParamList, DocPara, DocParamSect, DocSimpleSectSep, DocSimpleSect, DocHtmlList, DocSimpleList, DocParBlock, DocInternal, DocSecRefList, DocSecRefItem, DocSection, DocHtmlDescList, DocHtmlDescTitle, DocHtmlHeader, DocHRef, DocInternalRef, DocRef, DocLink, DocVhdlFlow, DocDiaFile, DocMscFile, DocDotFile, DocImage, DocXRefItem, DocTitle, DocAutoListItem, DocAutoList, DocCopy, DocIndexEntry, DocFormula, DocIncOperator, DocInclude, DocVerbatim, DocWhiteSpace, DocSymbol, DocStyleChange, DocCite, DocAnchor, DocHorRuler, DocLineBreak, DocURL, DocLinkedWord, and DocWord.
Referenced by CompAccept< DocHtmlTable >::accept(), DocSimpleSect::accept(), DocParamList::accept(), DocHtmlTable::accept(), addPerlModDocBlock(), generateBriefDoc(), parseCommentAsText(), PerlModDocVisitor::visit(), visitCaption(), RTFGenerator::writeDoc(), ManGenerator::writeDoc(), LatexGenerator::writeDoc(), HtmlGenerator::writeDoc(), writeDocbookDocBlock(), and writeXMLDocBlock().
isPreformatted()
bool DocNode::isPreformatted () const inline
Returns TRUE iff this node is inside a preformatted section
Definition at line 158 of file docparser.h.
References m_insidePre.
Referenced by insidePRE(), HtmlDocVisitor::visitPost(), and HtmlDocVisitor::visitPre().
kind()
virtual Kind DocNode::kind () const pure virtual
Returns the kind of node. Provides runtime type information
Implemented in DocRoot, DocText, DocHtmlBlockQuote, DocHtmlTable, DocHtmlRow, DocHtmlCaption, DocHtmlCell, DocHtmlDescData, DocHtmlListItem, DocSimpleListItem, DocParamList, DocPara, DocParamSect, DocSimpleSectSep, DocSimpleSect, DocHtmlList, DocSimpleList, DocParBlock, DocInternal, DocSecRefList, DocSecRefItem, DocSection, DocHtmlDescList, DocHtmlDescTitle, DocHtmlHeader, DocHRef, DocInternalRef, DocRef, DocLink, DocVhdlFlow, DocDiaFile, DocMscFile, DocDotFile, DocImage, DocXRefItem, DocTitle, DocAutoListItem, DocAutoList, DocCopy, DocIndexEntry, DocFormula, DocIncOperator, DocInclude, DocVerbatim, DocWhiteSpace, DocSymbol, DocStyleChange, DocCite, DocAnchor, DocHorRuler, DocLineBreak, DocURL, DocLinkedWord, and DocWord.
Referenced by DocHtmlTable::computeTableGrid(), DocHtmlTable::firstRow(), flattenParagraphs(), HtmlDocVisitor::forceEndParagraph(), HtmlDocVisitor::forceStartParagraph(), getParagraphContext(), DocPara::handleHtmlStartTag(), DocPara::handleIncludeOperator(), insideLI(), insideOL(), insideStyleChangeThatIsOutsideParagraph(), insideTable(), insideUL(), DocHtmlRow::isHeading(), mustBeOutsideParagraph(), DocPara::parse(), tableIsNested(), XmlDocVisitor::visit(), RTFDocVisitor::visitPost(), ManDocVisitor::visitPost(), HtmlDocVisitor::visitPost(), LatexDocVisitor::visitPost(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), RTFDocVisitor::visitPre(), and PerlModDocVisitor::visitPre().
parent()
DocNode* DocNode::parent () const inline
Returns the parent of this node or 0 for the root node.
Definition at line 147 of file docparser.h.
References m_parent.
Referenced by DocAnchor::DocAnchor(), DocAutoList::DocAutoList(), DocAutoListItem::DocAutoListItem(), DocCite::DocCite(), DocCopy::DocCopy(), DocDiaFile::DocDiaFile(), DocDotFile::DocDotFile(), DocFormula::DocFormula(), DocHorRuler::DocHorRuler(), DocHRef::DocHRef(), DocHtmlBlockQuote::DocHtmlBlockQuote(), DocHtmlCaption::DocHtmlCaption(), DocHtmlCell::DocHtmlCell(), DocHtmlDescData::DocHtmlDescData(), DocHtmlDescList::DocHtmlDescList(), DocHtmlDescTitle::DocHtmlDescTitle(), DocHtmlHeader::DocHtmlHeader(), DocHtmlList::DocHtmlList(), DocHtmlListItem::DocHtmlListItem(), DocHtmlRow::DocHtmlRow(), DocHtmlTable::DocHtmlTable(), DocImage::DocImage(), DocInclude::DocInclude(), DocIncOperator::DocIncOperator(), DocIndexEntry::DocIndexEntry(), DocInternal::DocInternal(), DocInternalRef::DocInternalRef(), DocLineBreak::DocLineBreak(), DocLink::DocLink(), DocLinkedWord::DocLinkedWord(), DocMscFile::DocMscFile(), DocPara::DocPara(), DocParamList::DocParamList(), DocParamSect::DocParamSect(), DocParBlock::DocParBlock(), DocRef::DocRef(), DocSecRefItem::DocSecRefItem(), DocSecRefList::DocSecRefList(), DocSection::DocSection(), DocSimpleList::DocSimpleList(), DocSimpleListItem::DocSimpleListItem(), DocSimpleSect::DocSimpleSect(), DocSimpleSectSep::DocSimpleSectSep(), DocStyleChange::DocStyleChange(), DocSymbol::DocSymbol(), DocTitle::DocTitle(), DocURL::DocURL(), DocVerbatim::DocVerbatim(), DocVhdlFlow::DocVhdlFlow(), DocWhiteSpace::DocWhiteSpace(), DocWord::DocWord(), DocXRefItem::DocXRefItem(), HtmlDocVisitor::forceEndParagraph(), HtmlDocVisitor::forceStartParagraph(), getParagraphContext(), insideLI(), insidePRE(), insideTable(), DocPara::parse(), DocParamList::parse(), setParent(), tableIsNested(), XmlDocVisitor::visit(), RTFDocVisitor::visitPost(), ManDocVisitor::visitPost(), HtmlDocVisitor::visitPost(), LatexDocVisitor::visitPost(), ManDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), RTFDocVisitor::visitPre(), and PerlModDocVisitor::visitPre().
setInsidePreformatted()
void DocNode::setInsidePreformatted (bool p) inline protected
Sets whether or not this item is inside a preformatted section
Definition at line 162 of file docparser.h.
References m_insidePre.
Referenced by DocPara::handleHtmlEndTag(), and DocPara::handleHtmlStartTag().
setParent()
void DocNode::setParent (DocNode * parent) inline
Sets a new parent for this node.
Definition at line 150 of file docparser.h.
References m_parent, and parent().
Referenced by flattenParagraphs().
Member Data Documentation
m_insidePre
bool DocNode::m_insidePre private
Definition at line 166 of file docparser.h.
Referenced by isPreformatted(), and setInsidePreformatted().
m_parent
DocNode* DocNode::m_parent protected
Definition at line 163 of file docparser.h.
Referenced by DocAnchor::DocAnchor(), DocAutoList::DocAutoList(), DocAutoListItem::DocAutoListItem(), DocCite::DocCite(), DocCopy::DocCopy(), DocDiaFile::DocDiaFile(), DocDotFile::DocDotFile(), DocFormula::DocFormula(), DocHorRuler::DocHorRuler(), DocHRef::DocHRef(), DocHtmlBlockQuote::DocHtmlBlockQuote(), DocHtmlCaption::DocHtmlCaption(), DocHtmlCell::DocHtmlCell(), DocHtmlDescData::DocHtmlDescData(), DocHtmlDescList::DocHtmlDescList(), DocHtmlDescTitle::DocHtmlDescTitle(), DocHtmlHeader::DocHtmlHeader(), DocHtmlList::DocHtmlList(), DocHtmlListItem::DocHtmlListItem(), DocHtmlRow::DocHtmlRow(), DocHtmlTable::DocHtmlTable(), DocImage::DocImage(), DocInclude::DocInclude(), DocIncOperator::DocIncOperator(), DocIndexEntry::DocIndexEntry(), DocInternal::DocInternal(), DocInternalRef::DocInternalRef(), DocLineBreak::DocLineBreak(), DocLink::DocLink(), DocLinkedWord::DocLinkedWord(), DocMscFile::DocMscFile(), DocPara::DocPara(), DocParamList::DocParamList(), DocParamSect::DocParamSect(), DocParBlock::DocParBlock(), DocRef::DocRef(), DocSecRefItem::DocSecRefItem(), DocSecRefList::DocSecRefList(), DocSection::DocSection(), DocSimpleList::DocSimpleList(), DocSimpleListItem::DocSimpleListItem(), DocSimpleSect::DocSimpleSect(), DocSimpleSectSep::DocSimpleSectSep(), DocStyleChange::DocStyleChange(), DocSymbol::DocSymbol(), DocTitle::DocTitle(), DocURL::DocURL(), DocVerbatim::DocVerbatim(), DocVhdlFlow::DocVhdlFlow(), DocWhiteSpace::DocWhiteSpace(), DocWord::DocWord(), DocXRefItem::DocXRefItem(), parent(), DocCopy::parse(), and setParent().
The documentation for this class was generated from the following file:
src/docparser.h