Doxygen: TextDocVisitor Class Reference
TextDocVisitor Class Reference
Concrete visitor implementation for TEXT output.
#include <textdocvisitor.h>
Public Member Functions
TextDocVisitor (FTextStream &t)
void visit (DocWord *w)
void visit (DocLinkedWord *w)
void visit (DocWhiteSpace *)
void visit (DocSymbol *)
void visit (DocURL *u)
void visit (DocLineBreak *)
void visit (DocHorRuler *)
void visit (DocStyleChange *)
void visit (DocVerbatim *s)
void visit (DocAnchor *)
void visit (DocInclude *)
void visit (DocIncOperator *)
void visit (DocFormula *)
void visit (DocIndexEntry *)
void visit (DocSimpleSectSep *)
void visit (DocCite *)
void visitPre (DocAutoList *)
void visitPost (DocAutoList *)
void visitPre (DocAutoListItem *)
void visitPost (DocAutoListItem *)
void visitPre (DocPara *)
void visitPost (DocPara *)
void visitPre (DocRoot *)
void visitPost (DocRoot *)
void visitPre (DocSimpleSect *)
void visitPost (DocSimpleSect *)
void visitPre (DocTitle *)
void visitPost (DocTitle *)
void visitPre (DocSimpleList *)
void visitPost (DocSimpleList *)
void visitPre (DocSimpleListItem *)
void visitPost (DocSimpleListItem *)
void visitPre (DocSection *)
void visitPost (DocSection *)
void visitPre (DocHtmlList *)
void visitPost (DocHtmlList *)
void visitPre (DocHtmlListItem *)
void visitPost (DocHtmlListItem *)
void visitPre (DocHtmlDescList *)
void visitPost (DocHtmlDescList *)
void visitPre (DocHtmlDescTitle *)
void visitPost (DocHtmlDescTitle *)
void visitPre (DocHtmlDescData *)
void visitPost (DocHtmlDescData *)
void visitPre (DocHtmlTable *)
void visitPost (DocHtmlTable *)
void visitPre (DocHtmlRow *)
void visitPost (DocHtmlRow *)
void visitPre (DocHtmlCell *)
void visitPost (DocHtmlCell *)
void visitPre (DocHtmlCaption *)
void visitPost (DocHtmlCaption *)
void visitPre (DocInternal *)
void visitPost (DocInternal *)
void visitPre (DocHRef *)
void visitPost (DocHRef *)
void visitPre (DocHtmlHeader *)
void visitPost (DocHtmlHeader *)
void visitPre (DocImage *)
void visitPost (DocImage *)
void visitPre (DocDotFile *)
void visitPost (DocDotFile *)
void visitPre (DocMscFile *)
void visitPost (DocMscFile *)
void visitPre (DocDiaFile *)
void visitPost (DocDiaFile *)
void visitPre (DocLink *)
void visitPost (DocLink *)
void visitPre (DocRef *)
void visitPost (DocRef *)
void visitPre (DocSecRefItem *)
void visitPost (DocSecRefItem *)
void visitPre (DocSecRefList *)
void visitPost (DocSecRefList *)
void visitPre (DocParamSect *)
void visitPost (DocParamSect *)
void visitPre (DocParamList *)
void visitPost (DocParamList *)
void visitPre (DocXRefItem *)
void visitPost (DocXRefItem *)
void visitPre (DocInternalRef *)
void visitPost (DocInternalRef *)
void visitPre (DocCopy *)
void visitPost (DocCopy *)
void visitPre (DocText *)
void visitPost (DocText *)
void visitPre (DocHtmlBlockQuote *)
void visitPost (DocHtmlBlockQuote *)
void visitPre (DocVhdlFlow *)
void visitPost (DocVhdlFlow *)
void visitPre (DocParBlock *)
void visitPost (DocParBlock *)
Public Member Functions inherited from DocVisitor
DocVisitor (int id)
virtual ~DocVisitor ()
int id () const
Private Member Functions
void filter (const char *str)
Private Attributes
FTextStream & m_t
Detailed Description
Concrete visitor implementation for TEXT output.
Definition at line 30 of file textdocvisitor.h.
Constructor & Destructor Documentation
TextDocVisitor()
TextDocVisitor::TextDocVisitor (FTextStream & t) inline
Definition at line 33 of file textdocvisitor.h.
Member Function Documentation
filter()
void TextDocVisitor::filter (const char * str) private
Definition at line 41 of file textdocvisitor.cpp.
References m_t.
Referenced by visit().
visit() [1/16]
void TextDocVisitor::visit (DocWord * w) inline virtual
Implements DocVisitor.
Definition at line 39 of file textdocvisitor.h.
References filter(), and DocWord::word().
visit() [2/16]
void TextDocVisitor::visit (DocLinkedWord * w) inline virtual
Implements DocVisitor.
Definition at line 40 of file textdocvisitor.h.
References filter(), and DocLinkedWord::word().
visit() [3/16]
void TextDocVisitor::visit (DocWhiteSpace *) inline virtual
Implements DocVisitor.
Definition at line 41 of file textdocvisitor.h.
References m_t.
visit() [4/16]
void TextDocVisitor::visit (DocSymbol * s) virtual
Implements DocVisitor.
Definition at line 27 of file textdocvisitor.cpp.
References err(), HtmlEntityMapper::html(), HtmlEntityMapper::instance(), m_t, and DocSymbol::symbol().
visit() [5/16]
void TextDocVisitor::visit (DocURL * u) inline virtual
Implements DocVisitor.
Definition at line 43 of file textdocvisitor.h.
References filter(), and DocURL::url().
visit() [6/16]
void TextDocVisitor::visit (DocLineBreak *) inline virtual
Implements DocVisitor.
Definition at line 44 of file textdocvisitor.h.
References m_t.
visit() [7/16]
void TextDocVisitor::visit (DocHorRuler *) inline virtual
Implements DocVisitor.
Definition at line 45 of file textdocvisitor.h.
visit() [8/16]
void TextDocVisitor::visit (DocStyleChange *) inline virtual
Implements DocVisitor.
Definition at line 46 of file textdocvisitor.h.
visit() [9/16]
void TextDocVisitor::visit (DocVerbatim * s) inline virtual
Implements DocVisitor.
Definition at line 47 of file textdocvisitor.h.
References filter(), and DocVerbatim::text().
visit() [10/16]
void TextDocVisitor::visit (DocAnchor *) inline virtual
Implements DocVisitor.
Definition at line 48 of file textdocvisitor.h.
visit() [11/16]
void TextDocVisitor::visit (DocInclude *) inline virtual
Implements DocVisitor.
Definition at line 49 of file textdocvisitor.h.
visit() [12/16]
void TextDocVisitor::visit (DocIncOperator *) inline virtual
Implements DocVisitor.
Definition at line 50 of file textdocvisitor.h.
visit() [13/16]
void TextDocVisitor::visit (DocFormula *) inline virtual
Implements DocVisitor.
Definition at line 51 of file textdocvisitor.h.
visit() [14/16]
void TextDocVisitor::visit (DocIndexEntry *) inline virtual
Implements DocVisitor.
Definition at line 52 of file textdocvisitor.h.
visit() [15/16]
void TextDocVisitor::visit (DocSimpleSectSep *) inline virtual
Implements DocVisitor.
Definition at line 53 of file textdocvisitor.h.
visit() [16/16]
void TextDocVisitor::visit (DocCite *) inline virtual
Implements DocVisitor.
Definition at line 54 of file textdocvisitor.h.
visitPost() [1/38]
void TextDocVisitor::visitPost (DocAutoList *) inline virtual
Implements DocVisitor.
Definition at line 61 of file textdocvisitor.h.
visitPost() [2/38]
void TextDocVisitor::visitPost (DocAutoListItem *) inline virtual
Implements DocVisitor.
Definition at line 63 of file textdocvisitor.h.
visitPost() [3/38]
void TextDocVisitor::visitPost (DocPara *) inline virtual
Implements DocVisitor.
Definition at line 65 of file textdocvisitor.h.
visitPost() [4/38]
void TextDocVisitor::visitPost (DocRoot *) inline virtual
Implements DocVisitor.
Definition at line 67 of file textdocvisitor.h.
visitPost() [5/38]
void TextDocVisitor::visitPost (DocSimpleSect *) inline virtual
Implements DocVisitor.
Definition at line 69 of file textdocvisitor.h.
visitPost() [6/38]
void TextDocVisitor::visitPost (DocTitle *) inline virtual
Implements DocVisitor.
Definition at line 71 of file textdocvisitor.h.
visitPost() [7/38]
void TextDocVisitor::visitPost (DocSimpleList *) inline virtual
Implements DocVisitor.
Definition at line 73 of file textdocvisitor.h.
visitPost() [8/38]
void TextDocVisitor::visitPost (DocSimpleListItem *) inline virtual
Implements DocVisitor.
Definition at line 75 of file textdocvisitor.h.
visitPost() [9/38]
void TextDocVisitor::visitPost (DocSection *) inline virtual
Implements DocVisitor.
Definition at line 77 of file textdocvisitor.h.
visitPost() [10/38]
void TextDocVisitor::visitPost (DocHtmlList *) inline virtual
Implements DocVisitor.
Definition at line 79 of file textdocvisitor.h.
visitPost() [11/38]
void TextDocVisitor::visitPost (DocHtmlListItem *) inline virtual
Implements DocVisitor.
Definition at line 81 of file textdocvisitor.h.
visitPost() [12/38]
void TextDocVisitor::visitPost (DocHtmlDescList *) inline virtual
Implements DocVisitor.
Definition at line 83 of file textdocvisitor.h.
visitPost() [13/38]
void TextDocVisitor::visitPost (DocHtmlDescTitle *) inline virtual
Implements DocVisitor.
Definition at line 85 of file textdocvisitor.h.
visitPost() [14/38]
void TextDocVisitor::visitPost (DocHtmlDescData *) inline virtual
Implements DocVisitor.
Definition at line 87 of file textdocvisitor.h.
visitPost() [15/38]
void TextDocVisitor::visitPost (DocHtmlTable *) inline virtual
Implements DocVisitor.
Definition at line 89 of file textdocvisitor.h.
visitPost() [16/38]
void TextDocVisitor::visitPost (DocHtmlRow *) inline virtual
Implements DocVisitor.
Definition at line 91 of file textdocvisitor.h.
visitPost() [17/38]
void TextDocVisitor::visitPost (DocHtmlCell *) inline virtual
Implements DocVisitor.
Definition at line 93 of file textdocvisitor.h.
visitPost() [18/38]
void TextDocVisitor::visitPost (DocHtmlCaption *) inline virtual
Implements DocVisitor.
Definition at line 95 of file textdocvisitor.h.
visitPost() [19/38]
void TextDocVisitor::visitPost (DocInternal *) inline virtual
Implements DocVisitor.
Definition at line 97 of file textdocvisitor.h.
visitPost() [20/38]
void TextDocVisitor::visitPost (DocHRef *) inline virtual
Implements DocVisitor.
Definition at line 99 of file textdocvisitor.h.
visitPost() [21/38]
void TextDocVisitor::visitPost (DocHtmlHeader *) inline virtual
Implements DocVisitor.
Definition at line 101 of file textdocvisitor.h.
visitPost() [22/38]
void TextDocVisitor::visitPost (DocImage *) inline virtual
Implements DocVisitor.
Definition at line 103 of file textdocvisitor.h.
visitPost() [23/38]
void TextDocVisitor::visitPost (DocDotFile *) inline virtual
Implements DocVisitor.
Definition at line 105 of file textdocvisitor.h.
visitPost() [24/38]
void TextDocVisitor::visitPost (DocMscFile *) inline virtual
Implements DocVisitor.
Definition at line 108 of file textdocvisitor.h.
visitPost() [25/38]
void TextDocVisitor::visitPost (DocDiaFile *) inline virtual
Implements DocVisitor.
Definition at line 110 of file textdocvisitor.h.
visitPost() [26/38]
void TextDocVisitor::visitPost (DocLink *) inline virtual
Implements DocVisitor.
Definition at line 112 of file textdocvisitor.h.
visitPost() [27/38]
void TextDocVisitor::visitPost (DocRef *) inline virtual
Implements DocVisitor.
Definition at line 114 of file textdocvisitor.h.
visitPost() [28/38]
void TextDocVisitor::visitPost (DocSecRefItem *) inline virtual
Implements DocVisitor.
Definition at line 116 of file textdocvisitor.h.
visitPost() [29/38]
void TextDocVisitor::visitPost (DocSecRefList *) inline virtual
Implements DocVisitor.
Definition at line 118 of file textdocvisitor.h.
visitPost() [30/38]
void TextDocVisitor::visitPost (DocParamSect *) inline virtual
Implements DocVisitor.
Definition at line 120 of file textdocvisitor.h.
visitPost() [31/38]
void TextDocVisitor::visitPost (DocParamList *) inline virtual
Implements DocVisitor.
Definition at line 122 of file textdocvisitor.h.
visitPost() [32/38]
void TextDocVisitor::visitPost (DocXRefItem *) inline virtual
Implements DocVisitor.
Definition at line 124 of file textdocvisitor.h.
visitPost() [33/38]
void TextDocVisitor::visitPost (DocInternalRef *) inline virtual
Implements DocVisitor.
Definition at line 126 of file textdocvisitor.h.
visitPost() [34/38]
void TextDocVisitor::visitPost (DocCopy *) inline virtual
Implements DocVisitor.
Definition at line 128 of file textdocvisitor.h.
visitPost() [35/38]
void TextDocVisitor::visitPost (DocText *) inline virtual
Implements DocVisitor.
Definition at line 130 of file textdocvisitor.h.
visitPost() [36/38]
void TextDocVisitor::visitPost (DocHtmlBlockQuote *) inline virtual
Implements DocVisitor.
Definition at line 132 of file textdocvisitor.h.
visitPost() [37/38]
void TextDocVisitor::visitPost (DocVhdlFlow *) inline virtual
Implements DocVisitor.
Definition at line 134 of file textdocvisitor.h.
visitPost() [38/38]
void TextDocVisitor::visitPost (DocParBlock *) inline virtual
Implements DocVisitor.
Definition at line 136 of file textdocvisitor.h.
visitPre() [1/38]
void TextDocVisitor::visitPre (DocAutoList *) inline virtual
Implements DocVisitor.
Definition at line 60 of file textdocvisitor.h.
visitPre() [2/38]
void TextDocVisitor::visitPre (DocAutoListItem *) inline virtual
Implements DocVisitor.
Definition at line 62 of file textdocvisitor.h.
visitPre() [3/38]
void TextDocVisitor::visitPre (DocPara *) inline virtual
Implements DocVisitor.
Definition at line 64 of file textdocvisitor.h.
visitPre() [4/38]
void TextDocVisitor::visitPre (DocRoot *) inline virtual
Implements DocVisitor.
Definition at line 66 of file textdocvisitor.h.
visitPre() [5/38]
void TextDocVisitor::visitPre (DocSimpleSect *) inline virtual
Implements DocVisitor.
Definition at line 68 of file textdocvisitor.h.
visitPre() [6/38]
void TextDocVisitor::visitPre (DocTitle *) inline virtual
Implements DocVisitor.
Definition at line 70 of file textdocvisitor.h.
visitPre() [7/38]
void TextDocVisitor::visitPre (DocSimpleList *) inline virtual
Implements DocVisitor.
Definition at line 72 of file textdocvisitor.h.
visitPre() [8/38]
void TextDocVisitor::visitPre (DocSimpleListItem *) inline virtual
Implements DocVisitor.
Definition at line 74 of file textdocvisitor.h.
visitPre() [9/38]
void TextDocVisitor::visitPre (DocSection *) inline virtual
Implements DocVisitor.
Definition at line 76 of file textdocvisitor.h.
visitPre() [10/38]
void TextDocVisitor::visitPre (DocHtmlList *) inline virtual
Implements DocVisitor.
Definition at line 78 of file textdocvisitor.h.
visitPre() [11/38]
void TextDocVisitor::visitPre (DocHtmlListItem *) inline virtual
Implements DocVisitor.
Definition at line 80 of file textdocvisitor.h.
visitPre() [12/38]
void TextDocVisitor::visitPre (DocHtmlDescList *) inline virtual
Implements DocVisitor.
Definition at line 82 of file textdocvisitor.h.
visitPre() [13/38]
void TextDocVisitor::visitPre (DocHtmlDescTitle *) inline virtual
Implements DocVisitor.
Definition at line 84 of file textdocvisitor.h.
visitPre() [14/38]
void TextDocVisitor::visitPre (DocHtmlDescData *) inline virtual
Implements DocVisitor.
Definition at line 86 of file textdocvisitor.h.
visitPre() [15/38]
void TextDocVisitor::visitPre (DocHtmlTable *) inline virtual
Implements DocVisitor.
Definition at line 88 of file textdocvisitor.h.
visitPre() [16/38]
void TextDocVisitor::visitPre (DocHtmlRow *) inline virtual
Implements DocVisitor.
Definition at line 90 of file textdocvisitor.h.
visitPre() [17/38]
void TextDocVisitor::visitPre (DocHtmlCell *) inline virtual
Implements DocVisitor.
Definition at line 92 of file textdocvisitor.h.
visitPre() [18/38]
void TextDocVisitor::visitPre (DocHtmlCaption *) inline virtual
Implements DocVisitor.
Definition at line 94 of file textdocvisitor.h.
visitPre() [19/38]
void TextDocVisitor::visitPre (DocInternal *) inline virtual
Implements DocVisitor.
Definition at line 96 of file textdocvisitor.h.
visitPre() [20/38]
void TextDocVisitor::visitPre (DocHRef *) inline virtual
Implements DocVisitor.
Definition at line 98 of file textdocvisitor.h.
visitPre() [21/38]
void TextDocVisitor::visitPre (DocHtmlHeader *) inline virtual
Implements DocVisitor.
Definition at line 100 of file textdocvisitor.h.
visitPre() [22/38]
void TextDocVisitor::visitPre (DocImage *) inline virtual
Implements DocVisitor.
Definition at line 102 of file textdocvisitor.h.
visitPre() [23/38]
void TextDocVisitor::visitPre (DocDotFile *) inline virtual
Implements DocVisitor.
Definition at line 104 of file textdocvisitor.h.
visitPre() [24/38]
void TextDocVisitor::visitPre (DocMscFile *) inline virtual
Implements DocVisitor.
Definition at line 107 of file textdocvisitor.h.
visitPre() [25/38]
void TextDocVisitor::visitPre (DocDiaFile *) inline virtual
Implements DocVisitor.
Definition at line 109 of file textdocvisitor.h.
visitPre() [26/38]
void TextDocVisitor::visitPre (DocLink *) inline virtual
Implements DocVisitor.
Definition at line 111 of file textdocvisitor.h.
visitPre() [27/38]
void TextDocVisitor::visitPre (DocRef *) inline virtual
Implements DocVisitor.
Definition at line 113 of file textdocvisitor.h.
visitPre() [28/38]
void TextDocVisitor::visitPre (DocSecRefItem *) inline virtual
Implements DocVisitor.
Definition at line 115 of file textdocvisitor.h.
visitPre() [29/38]
void TextDocVisitor::visitPre (DocSecRefList *) inline virtual
Implements DocVisitor.
Definition at line 117 of file textdocvisitor.h.
visitPre() [30/38]
void TextDocVisitor::visitPre (DocParamSect *) inline virtual
Implements DocVisitor.
Definition at line 119 of file textdocvisitor.h.
visitPre() [31/38]
void TextDocVisitor::visitPre (DocParamList *) inline virtual
Implements DocVisitor.
Definition at line 121 of file textdocvisitor.h.
visitPre() [32/38]
void TextDocVisitor::visitPre (DocXRefItem *) inline virtual
Implements DocVisitor.
Definition at line 123 of file textdocvisitor.h.
visitPre() [33/38]
void TextDocVisitor::visitPre (DocInternalRef *) inline virtual
Implements DocVisitor.
Definition at line 125 of file textdocvisitor.h.
visitPre() [34/38]
void TextDocVisitor::visitPre (DocCopy *) inline virtual
Implements DocVisitor.
Definition at line 127 of file textdocvisitor.h.
visitPre() [35/38]
void TextDocVisitor::visitPre (DocText *) inline virtual
Implements DocVisitor.
Definition at line 129 of file textdocvisitor.h.
visitPre() [36/38]
void TextDocVisitor::visitPre (DocHtmlBlockQuote *) inline virtual
Implements DocVisitor.
Definition at line 131 of file textdocvisitor.h.
visitPre() [37/38]
void TextDocVisitor::visitPre (DocVhdlFlow *) inline virtual
Implements DocVisitor.
Definition at line 133 of file textdocvisitor.h.
visitPre() [38/38]
void TextDocVisitor::visitPre (DocParBlock *) inline virtual
Implements DocVisitor.
Definition at line 135 of file textdocvisitor.h.
Member Data Documentation
m_t
FTextStream& TextDocVisitor::m_t private
Definition at line 142 of file textdocvisitor.h.
Referenced by filter(), and visit().
The documentation for this class was generated from the following files:
src/textdocvisitor.h
src/textdocvisitor.cpp