Doxygen: ClassInheritanceContext Class Reference
ClassInheritanceContext Class Reference
#include <context.h>
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static ClassInheritanceContext * alloc ()
Private Member Functions
ClassInheritanceContext ()
~ClassInheritanceContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 469 of file context.h.
Constructor & Destructor Documentation
ClassInheritanceContext()
ClassInheritanceContext::ClassInheritanceContext () private
Referenced by alloc().
~ClassInheritanceContext()
ClassInheritanceContext::~ClassInheritanceContext () private
Member Function Documentation
addRef()
virtual int ClassInheritanceContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 478 of file context.h.
References RefCountedContext::addRef().
alloc()
static ClassInheritanceContext* ClassInheritanceContext::alloc () inline static
Definition at line 472 of file context.h.
References ClassInheritanceContext().
at()
virtual TemplateVariant ClassInheritanceContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
count()
virtual int ClassInheritanceContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
createIterator()
virtual TemplateListIntf::ConstIterator* ClassInheritanceContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
release()
virtual int ClassInheritanceContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 479 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ClassInheritanceContext::p private
Definition at line 484 of file context.h.
The documentation for this class was generated from the following file:
src/context.h