Doxygen: ClassMembersIndexContext Class Reference
ClassMembersIndexContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static ClassMembersIndexContext * alloc ()
Private Member Functions
ClassMembersIndexContext ()
~ClassMembersIndexContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 851 of file context.h.
Constructor & Destructor Documentation
ClassMembersIndexContext()
ClassMembersIndexContext::ClassMembersIndexContext () private
Definition at line 8139 of file context.cpp.
References p, and Private.
Referenced by alloc().
~ClassMembersIndexContext()
ClassMembersIndexContext::~ClassMembersIndexContext () private
Definition at line 8144 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int ClassMembersIndexContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 858 of file context.h.
References RefCountedContext::addRef().
alloc()
static ClassMembersIndexContext* ClassMembersIndexContext::alloc () inline static
Definition at line 854 of file context.h.
References ClassMembersIndexContext().
Referenced by generateOutputViaTemplate().
get()
TemplateVariant ClassMembersIndexContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 8149 of file context.cpp.
References ClassMembersIndexContext::Private::get(), and p.
release()
virtual int ClassMembersIndexContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 859 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ClassMembersIndexContext::p private
Definition at line 864 of file context.h.
Referenced by ClassMembersIndexContext(), get(), and ~ClassMembersIndexContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp