Doxygen: Qhp Class Reference
Qhp Class Reference
#include <qhp.h>
Public Member Functions
Qhp ()
~Qhp ()
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const char *name, const char *ref, const char *file, const char *anchor, bool separateIndex, bool addToNavIndex, Definition *def)
void addIndexItem (Definition *context, MemberDef *md, const char *sectionAnchor, const char *title)
void addIndexFile (const char *name)
void addImageFile (const char *name)
void addStyleSheetFile (const char *name)
Public Member Functions inherited from IndexIntf
virtual ~IndexIntf ()
Static Public Member Functions
static QCString getQhpFileName ()
Private Member Functions
void handlePrevSection ()
void clearPrevSection ()
void setPrevSection (const char *title, const char *basename, const char *anchor, int level)
void addFile (const char *fileName)
Static Private Member Functions
static QCString getFullProjectName ()
Private Attributes
QhpXmlWriter m_doc
QhpXmlWriter m_toc
QhpXmlWriter m_index
QhpXmlWriter m_files
QCString m_prevSectionTitle
QCString m_prevSectionBaseName
QCString m_prevSectionAnchor
int m_prevSectionLevel
int m_sectionLevel
bool m_skipMainPageSection
Detailed Description
Definition at line 23 of file qhp.h.
Constructor & Destructor Documentation
Qhp()
Qhp::Qhp ()
Definition at line 56 of file qhp.cpp.
References m_doc, m_files, m_index, m_toc, and QhpXmlWriter::setIndentLevel().
~Qhp()
Qhp::~Qhp ()
Definition at line 64 of file qhp.cpp.
References clearPrevSection().
Member Function Documentation
addContentsItem()
void Qhp::addContentsItem (bool isDir, const char * name, const char * ref, const char * file, const char * anchor, bool separateIndex, bool addToNavIndex, Definition * def) virtual
Implements IndexIntf.
Definition at line 192 of file qhp.cpp.
References QhpXmlWriter::close(), handlePrevSection(), m_prevSectionLevel, m_sectionLevel, m_toc, and setPrevSection().
addFile()
void Qhp::addFile (const char * fileName) private
Definition at line 357 of file qhp.cpp.
References m_files, and QhpXmlWriter::openCloseContent().
Referenced by addImageFile(), addIndexFile(), and addStyleSheetFile().
addImageFile()
void Qhp::addImageFile (const char * name) virtual
Implements IndexIntf.
Definition at line 362 of file qhp.cpp.
References addFile().
addIndexFile()
void Qhp::addIndexFile (const char * name) virtual
Implements IndexIntf.
Definition at line 275 of file qhp.cpp.
References addFile().
addIndexItem()
void Qhp::addIndexItem (Definition * context, MemberDef * md, const char * sectionAnchor, const char * title) virtual
Implements IndexIntf.
Definition at line 217 of file qhp.cpp.
References MemberDef::anchor(), Config_getBool, MemberDef::getFileDef(), MemberDef::getGroupDef(), MemberDef::getOutputFileBase(), Definition::getOutputFileBase(), m_index, makeRef(), Definition::name(), and QhpXmlWriter::openClose().
addStyleSheetFile()
void Qhp::addStyleSheetFile (const char * name) virtual
Implements IndexIntf.
Definition at line 367 of file qhp.cpp.
References addFile().
clearPrevSection()
void Qhp::clearPrevSection () private
Definition at line 350 of file qhp.cpp.
References m_prevSectionAnchor, m_prevSectionBaseName, and m_prevSectionTitle.
Referenced by handlePrevSection(), and ~Qhp().
decContentsDepth()
void Qhp::decContentsDepth () virtual
Implements IndexIntf.
Definition at line 182 of file qhp.cpp.
References m_sectionLevel, and m_skipMainPageSection.
finalize()
void Qhp::finalize () virtual
Implements IndexIntf.
Definition at line 145 of file qhp.cpp.
References QhpXmlWriter::close(), Config_getString, QhpXmlWriter::dumpTo(), err(), getQhpFileName(), handlePrevSection(), QhpXmlWriter::insert(), m_doc, m_files, m_index, m_prevSectionLevel, and m_toc.
getFullProjectName()
QCString Qhp::getFullProjectName () static private
Definition at line 285 of file qhp.cpp.
References Config_getString.
Referenced by handlePrevSection(), and initialize().
getQhpFileName()
QCString Qhp::getQhpFileName () static
Definition at line 280 of file qhp.cpp.
Referenced by finalize(), and generateOutput().
handlePrevSection()
void Qhp::handlePrevSection () private
Definition at line 295 of file qhp.cpp.
References clearPrevSection(), getFullProjectName(), m_prevSectionAnchor, m_prevSectionBaseName, m_prevSectionLevel, m_prevSectionTitle, m_sectionLevel, m_skipMainPageSection, m_toc, makeRef(), QhpXmlWriter::open(), and QhpXmlWriter::openClose().
Referenced by addContentsItem(), and finalize().
incContentsDepth()
void Qhp::incContentsDepth () virtual
Implements IndexIntf.
Definition at line 177 of file qhp.cpp.
References m_sectionLevel.
initialize()
void Qhp::initialize () virtual
Implements IndexIntf.
Definition at line 69 of file qhp.cpp.
References QhpXmlWriter::close(), Config_getString, QhpXmlWriter::declaration(), getFullProjectName(), Doxygen::htmlFileExtension, m_doc, m_files, m_index, m_prevSectionLevel, m_prevSectionTitle, m_sectionLevel, m_toc, QhpXmlWriter::open(), QhpXmlWriter::openCloseContent(), and split().
setPrevSection()
void Qhp::setPrevSection (const char * title, const char * basename, const char * anchor, int level) private
Definition at line 342 of file qhp.cpp.
References m_prevSectionAnchor, m_prevSectionBaseName, m_prevSectionLevel, and m_prevSectionTitle.
Referenced by addContentsItem().
Member Data Documentation
m_doc
QhpXmlWriter Qhp::m_doc private
Definition at line 55 of file qhp.h.
Referenced by finalize(), initialize(), and Qhp().
m_files
QhpXmlWriter Qhp::m_files private
Definition at line 58 of file qhp.h.
Referenced by addFile(), finalize(), initialize(), and Qhp().
m_index
QhpXmlWriter Qhp::m_index private
Definition at line 57 of file qhp.h.
Referenced by addIndexItem(), finalize(), initialize(), and Qhp().
m_prevSectionAnchor
QCString Qhp::m_prevSectionAnchor private
Definition at line 62 of file qhp.h.
Referenced by clearPrevSection(), handlePrevSection(), and setPrevSection().
m_prevSectionBaseName
QCString Qhp::m_prevSectionBaseName private
Definition at line 61 of file qhp.h.
Referenced by clearPrevSection(), handlePrevSection(), and setPrevSection().
m_prevSectionLevel
int Qhp::m_prevSectionLevel private
Definition at line 64 of file qhp.h.
Referenced by addContentsItem(), finalize(), handlePrevSection(), initialize(), and setPrevSection().
m_prevSectionTitle
QCString Qhp::m_prevSectionTitle private
Definition at line 60 of file qhp.h.
Referenced by clearPrevSection(), handlePrevSection(), initialize(), and setPrevSection().
m_sectionLevel
int Qhp::m_sectionLevel private
Definition at line 65 of file qhp.h.
Referenced by addContentsItem(), decContentsDepth(), handlePrevSection(), incContentsDepth(), and initialize().
m_skipMainPageSection
bool Qhp::m_skipMainPageSection private
Definition at line 67 of file qhp.h.
Referenced by decContentsDepth(), and handlePrevSection().
m_toc
QhpXmlWriter Qhp::m_toc private
Definition at line 56 of file qhp.h.
Referenced by addContentsItem(), finalize(), handlePrevSection(), initialize(), and Qhp().
The documentation for this class was generated from the following files:
src/qhp.h
src/qhp.cpp