Doxygen: src/cppvalue.cpp File Reference
cppvalue.cpp File Reference
#include <stdlib.h>
#include "cppvalue.h"
#include "constexp.h"
Functions
CPPValue parseOctal ()
CPPValue parseDecimal ()
CPPValue parseHexadecimal ()
CPPValue parseCharacter ()
CPPValue parseFloat ()
Function Documentation
parseCharacter()
CPPValue parseCharacter ()
Definition at line 57 of file cppvalue.cpp.
References g_strToken, parseHexadecimal(), and parseOctal().
parseDecimal()
CPPValue parseDecimal ()
Definition at line 34 of file cppvalue.cpp.
References g_strToken.
parseFloat()
CPPValue parseFloat ()
Definition at line 92 of file cppvalue.cpp.
References g_strToken.
parseHexadecimal()
CPPValue parseHexadecimal ()
Definition at line 44 of file cppvalue.cpp.
References g_strToken.
Referenced by parseCharacter().
parseOctal()
CPPValue parseOctal ()
Definition at line 24 of file cppvalue.cpp.
References g_strToken.
Referenced by parseCharacter().