Doxygen: HtmlHelp Class Reference
HtmlHelp Class Reference
A class that generated the HTML Help specific files.
#include <htmlhelp.h>
Public Member Functions
HtmlHelp ()
~HtmlHelp ()
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const char *name, const char *ref, const char *file, const char *anchor, bool separateIndex, bool addToNavIndex, Definition *def)
void addIndexItem (Definition *context, MemberDef *md, const char *sectionAnchor, const char *title)
void addIndexFile (const char *name)
void addImageFile (const char *)
void addStyleSheetFile (const char *)
Public Member Functions inherited from IndexIntf
virtual ~IndexIntf ()
Static Public Member Functions
static QCString getLanguageString ()
Private Types
enum ImageNumber {
BOOK_CLOSED =1, BOOK_OPEN, BOOK_CLOSED_NEW, BOOK_OPEN_NEW,
FOLDER_CLOSED, FOLDER_OPEN, FOLDER_CLOSED_NEW, FOLDER_OPEN_NEW,
QUERY, QUERY_NEW, TEXT, TEXT_NEW,
WEB_DOC, WEB_DOC_NEW, WEB_LINK, WEB_LINK_NEW,
INFO, INFO_NEW, LINK, LINK_NEW,
BOOKLET, BOOKLET_NEW, EMAIL, EMAIL_NEW,
EMAIL2, EMAIL2_NEW, IMAGE, IMAGE_NEW,
AUDIO, AUDIO_NEW, MUSIC, MUSIC_NEW,
VIDEO, VIDEO_NEW, INDEX, INDEX_NEW,
IDEA, IDEA_NEW, NOTE, NOTE_NEW,
TOOL, TOOL_NEW
}
Private Member Functions
void createProjectFile ()
QCString recode (const QCString &s)
Private Attributes
QFile * cf
QFile * kf
FTextStream cts
FTextStream kts
HtmlHelpIndex * index
int dc
QStrList indexFiles
QStrList imageFiles
QDict< void > indexFileDict
void * m_fromUtf8
Static Private Attributes
static HtmlHelp * theInstance = 0
Friends
class HtmlHelpIndex
Detailed Description
A class that generated the HTML Help specific files.
These files can be used with the Microsoft HTML Help workshop to generate compressed HTML files (.chm).
Definition at line 38 of file htmlhelp.h.
Member Enumeration Documentation
ImageNumber
enum HtmlHelp::ImageNumber private
used in imageNumber param of HTMLHelp::addContentsItem() function to specify document icon in tree view. Writes <param name="ImageNumber" value="xx"> in .HHC file.
Enumerator
BOOK_CLOSED
BOOK_OPEN
BOOK_CLOSED_NEW
BOOK_OPEN_NEW
FOLDER_CLOSED
FOLDER_OPEN
FOLDER_CLOSED_NEW
FOLDER_OPEN_NEW
QUERY
QUERY_NEW
TEXT
TEXT_NEW
WEB_DOC
WEB_DOC_NEW
WEB_LINK
WEB_LINK_NEW
INFO
INFO_NEW
LINK
LINK_NEW
BOOKLET
BOOKLET_NEW
EMAIL
EMAIL_NEW
EMAIL2
EMAIL2_NEW
IMAGE
IMAGE_NEW
AUDIO
AUDIO_NEW
MUSIC
MUSIC_NEW
VIDEO
VIDEO_NEW
INDEX
INDEX_NEW
IDEA
IDEA_NEW
NOTE
NOTE_NEW
TOOL
TOOL_NEW
Definition at line 43 of file htmlhelp.h.
Constructor & Destructor Documentation
HtmlHelp()
HtmlHelp::HtmlHelp ()
Constructs an html object. The object has to be initialized before it can be used.
Definition at line 273 of file htmlhelp.cpp.
References cf, dc, HtmlHelpIndex, index, kf, and m_fromUtf8.
~HtmlHelp()
HtmlHelp::~HtmlHelp ()
Definition at line 282 of file htmlhelp.cpp.
References index, m_fromUtf8, and portable_iconv_close().
Member Function Documentation
addContentsItem()
void HtmlHelp::addContentsItem (bool isDir, const char * name, const char * ref, const char * file, const char * anchor, bool separateIndex, bool addToNavIndex, Definition * def) virtual
Add an list item to the contents file.
Parameters
isDir boolean indicating if this is a dir or file entry
name the name of the item.
ref the URL of to the item.
file the file in which the item is defined.
anchor the anchor of the item.
separateIndex not used.
addToNavIndex not used.
def not used.
Implements IndexIntf.
Definition at line 628 of file htmlhelp.cpp.
References BOOK_CLOSED, convertToHtml(), cts, dc, Doxygen::htmlFileExtension, recode(), and TEXT.
addImageFile()
void HtmlHelp::addImageFile (const char * fileName) virtual
Implements IndexIntf.
Definition at line 712 of file htmlhelp.cpp.
References imageFiles.
addIndexFile()
void HtmlHelp::addIndexFile (const char * name) virtual
Implements IndexIntf.
Definition at line 537 of file htmlhelp.cpp.
References indexFileDict, and indexFiles.
addIndexItem()
void HtmlHelp::addIndexItem (Definition * context, MemberDef * md, const char * sectionAnchor, const char * title) virtual
Implements IndexIntf.
Definition at line 680 of file htmlhelp.cpp.
References HtmlHelpIndex::addItem(), MemberDef::anchor(), Config_getBool, MemberDef::getFileDef(), MemberDef::getGroupDef(), MemberDef::getOutputFileBase(), Definition::getOutputFileBase(), index, and Definition::name().
addStyleSheetFile()
void HtmlHelp::addStyleSheetFile (const char *) inline virtual
Implements IndexIntf.
Definition at line 86 of file htmlhelp.h.
createProjectFile()
void HtmlHelp::createProjectFile () private
Definition at line 466 of file htmlhelp.cpp.
References Config_getBool, Config_getString, endl(), err(), getLanguageString(), Doxygen::htmlFileExtension, imageFiles, indexFiles, and recode().
Referenced by finalize().
decContentsDepth()
void HtmlHelp::decContentsDepth () virtual
Decrease the level of the contents hierarchy. This will end the unnumber HTML list.
See also
incContentsDepth()
Implements IndexIntf.
Definition at line 589 of file htmlhelp.cpp.
References cts, and dc.
finalize()
void HtmlHelp::finalize () virtual
Finalizes the HTML help. This will finish and close the contents file (index.hhc) and the index file (index.hhk).
See also
initialize()
Implements IndexIntf.
Definition at line 550 of file htmlhelp.cpp.
References cf, createProjectFile(), cts, index, kf, kts, FTextStream::unsetDevice(), and HtmlHelpIndex::writeFields().
getLanguageString()
QCString HtmlHelp::getLanguageString () static
Definition at line 450 of file htmlhelp.cpp.
References Translator::idLanguage(), and theTranslator.
Referenced by createProjectFile(), and TranslateContext::Private::langString().
incContentsDepth()
void HtmlHelp::incContentsDepth () virtual
Increase the level of the contents hierarchy. This will start a new unnumbered HTML list in contents file.
See also
decContentsDepth()
Implements IndexIntf.
Definition at line 578 of file htmlhelp.cpp.
References cts, and dc.
initialize()
void HtmlHelp::initialize () virtual
This will create a contents file (index.hhc) and a index file (index.hhk) and write the header of those files. It also creates a project file (index.hhp)
See also
finalize()
Implements IndexIntf.
Definition at line 304 of file htmlhelp.cpp.
References cf, Config_getString, cts, err(), kf, kts, m_fromUtf8, portable_iconv_open(), and FTextStream::setDevice().
recode()
QCString HtmlHelp::recode (const QCString & s) private
Definition at line 596 of file htmlhelp.cpp.
References m_fromUtf8, and portable_iconv().
Referenced by addContentsItem(), createProjectFile(), and HtmlHelpIndex::writeFields().
Friends And Related Function Documentation
HtmlHelpIndex
friend class HtmlHelpIndex friend
Definition at line 90 of file htmlhelp.h.
Referenced by HtmlHelp().
Member Data Documentation
cf
QFile* HtmlHelp::cf private
Definition at line 93 of file htmlhelp.h.
Referenced by finalize(), HtmlHelp(), and initialize().
cts
FTextStream HtmlHelp::cts private
Definition at line 94 of file htmlhelp.h.
Referenced by addContentsItem(), decContentsDepth(), finalize(), incContentsDepth(), and initialize().
dc
int HtmlHelp::dc private
Definition at line 96 of file htmlhelp.h.
Referenced by addContentsItem(), decContentsDepth(), HtmlHelp(), and incContentsDepth().
imageFiles
QStrList HtmlHelp::imageFiles private
Definition at line 98 of file htmlhelp.h.
Referenced by addImageFile(), and createProjectFile().
index
HtmlHelpIndex* HtmlHelp::index private
Definition at line 95 of file htmlhelp.h.
Referenced by addIndexItem(), finalize(), HtmlHelp(), and ~HtmlHelp().
indexFileDict
QDict<void> HtmlHelp::indexFileDict private
Definition at line 99 of file htmlhelp.h.
Referenced by addIndexFile().
indexFiles
QStrList HtmlHelp::indexFiles private
Definition at line 97 of file htmlhelp.h.
Referenced by addIndexFile(), and createProjectFile().
kf
QFile * HtmlHelp::kf private
Definition at line 93 of file htmlhelp.h.
Referenced by finalize(), HtmlHelp(), and initialize().
kts
FTextStream HtmlHelp::kts private
Definition at line 94 of file htmlhelp.h.
Referenced by finalize(), and initialize().
m_fromUtf8
void* HtmlHelp::m_fromUtf8 private
Definition at line 102 of file htmlhelp.h.
Referenced by HtmlHelp(), initialize(), recode(), and ~HtmlHelp().
theInstance
HtmlHelp * HtmlHelp::theInstance = 0 static private
Definition at line 100 of file htmlhelp.h.
The documentation for this class was generated from the following files:
src/htmlhelp.h
src/htmlhelp.cpp