Doxygen: LayoutDocEntry Struct Reference
LayoutDocEntry Struct Reference abstract
Base class representing a piece of a documentation page.
#include <layout.h>
Public Types
enum Kind {
MemberGroups, MemberDeclStart, MemberDeclEnd, MemberDecl,
MemberDefStart, MemberDefEnd, MemberDef, BriefDesc,
DetailedDesc, AuthorSection, ClassIncludes, ClassInlineClasses,
ClassInheritanceGraph, ClassNestedClasses, ClassCollaborationGraph, ClassAllMembersLink,
ClassUsedFiles, NamespaceNestedNamespaces, NamespaceNestedConstantGroups, NamespaceClasses,
NamespaceInlineClasses, FileClasses, FileNamespaces, FileConstantGroups,
FileIncludes, FileIncludeGraph, FileIncludedByGraph, FileSourceLink,
FileInlineClasses, GroupClasses, GroupInlineClasses, GroupNamespaces,
GroupDirs, GroupNestedGroups, GroupFiles, GroupGraph,
GroupPageDocs, DirSubDirs, DirFiles, DirGraph
}
Public Member Functions
virtual ~LayoutDocEntry ()
virtual Kind kind () const =0
Detailed Description
Base class representing a piece of a documentation page.
Definition at line 30 of file layout.h.
Member Enumeration Documentation
Kind
enum LayoutDocEntry::Kind
Enumerator
MemberGroups
MemberDeclStart
MemberDeclEnd
MemberDecl
MemberDefStart
MemberDefEnd
MemberDef
BriefDesc
DetailedDesc
AuthorSection
ClassIncludes
ClassInlineClasses
ClassInheritanceGraph
ClassNestedClasses
ClassCollaborationGraph
ClassAllMembersLink
ClassUsedFiles
NamespaceNestedNamespaces
NamespaceNestedConstantGroups
NamespaceClasses
NamespaceInlineClasses
FileClasses
FileNamespaces
FileConstantGroups
FileIncludes
FileIncludeGraph
FileIncludedByGraph
FileSourceLink
FileInlineClasses
GroupClasses
GroupInlineClasses
GroupNamespaces
GroupDirs
GroupNestedGroups
GroupFiles
GroupGraph
GroupPageDocs
DirSubDirs
DirFiles
DirGraph
Definition at line 33 of file layout.h.
Constructor & Destructor Documentation
~LayoutDocEntry()
virtual LayoutDocEntry::~LayoutDocEntry () inline virtual
Definition at line 32 of file layout.h.
Member Function Documentation
kind()
virtual Kind LayoutDocEntry::kind () const pure virtual
Implemented in LayoutDocEntryMemberDef, LayoutDocEntryMemberDecl, and LayoutDocEntrySimple.
Referenced by addMembersToIndex(), ClassDef::countAdditionalInheritedMembers(), ClassDef::getTitleForMemberListType(), ClassDef::writeAdditionalInheritedMembers(), ClassDef::writeDeclaration(), NamespaceDef::writeDocumentation(), GroupDef::writeDocumentation(), DirDef::writeDocumentation(), FileDef::writeDocumentation(), ClassDef::writeDocumentationContents(), writeGroupTreeNode(), ClassDef::writeInlineDocumentation(), NamespaceDef::writeSummaryLinks(), GroupDef::writeSummaryLinks(), FileDef::writeSummaryLinks(), ClassDef::writeSummaryLinks(), NamespaceDef::writeTagFile(), GroupDef::writeTagFile(), DirDef::writeTagFile(), FileDef::writeTagFile(), and ClassDef::writeTagFile().
The documentation for this struct was generated from the following file:
src/layout.h