Doxygen: AccessStack Class Reference
AccessStack Class Reference
Helper class representing the stack of items considered while resolving the scope.
Classes
struct AccessElem
Element in the stack.
Public Member Functions
AccessStack ()
void push (Definition *scope, FileDef *fileScope, Definition *item)
void push (Definition *scope, FileDef *fileScope, Definition *item, const QCString &expScope)
void pop ()
bool find (Definition *scope, FileDef *fileScope, Definition *item)
bool find (Definition *scope, FileDef *fileScope, Definition *item, const QCString &expScope)
Private Attributes
int m_index
AccessElem m_elements [MAX_STACK_SIZE]
Detailed Description
Helper class representing the stack of items considered while resolving the scope.
Definition at line 877 of file util.cpp.
Constructor & Destructor Documentation
AccessStack()
AccessStack::AccessStack () inline
Definition at line 880 of file util.cpp.
Member Function Documentation
find() [1/2]
bool AccessStack::find (Definition * scope, FileDef * fileScope, Definition * item) inline
Definition at line 906 of file util.cpp.
References AccessStack::AccessElem::fileScope, AccessStack::AccessElem::item, m_elements, m_index, and AccessStack::AccessElem::scope.
Referenced by isAccessibleFrom(), and isAccessibleFromWithExpScope().
find() [2/2]
bool AccessStack::find (Definition * scope, FileDef * fileScope, Definition * item, const QCString & expScope) inline
Definition at line 919 of file util.cpp.
References AccessStack::AccessElem::expScope, AccessStack::AccessElem::fileScope, AccessStack::AccessElem::item, m_elements, m_index, and AccessStack::AccessElem::scope.
pop()
void AccessStack::pop () inline
Definition at line 902 of file util.cpp.
References m_index.
Referenced by isAccessibleFrom(), and isAccessibleFromWithExpScope().
push() [1/2]
void AccessStack::push (Definition * scope, FileDef * fileScope, Definition * item) inline
Definition at line 881 of file util.cpp.
References AccessStack::AccessElem::fileScope, AccessStack::AccessElem::item, m_elements, m_index, MAX_STACK_SIZE, and AccessStack::AccessElem::scope.
Referenced by isAccessibleFrom(), and isAccessibleFromWithExpScope().
push() [2/2]
void AccessStack::push (Definition * scope, FileDef * fileScope, Definition * item, const QCString & expScope) inline
Definition at line 891 of file util.cpp.
References AccessStack::AccessElem::expScope, AccessStack::AccessElem::fileScope, AccessStack::AccessElem::item, m_elements, m_index, MAX_STACK_SIZE, and AccessStack::AccessElem::scope.
Member Data Documentation
m_elements
AccessElem AccessStack::m_elements[MAX_STACK_SIZE] private
Definition at line 943 of file util.cpp.
Referenced by find(), and push().
m_index
int AccessStack::m_index private
Definition at line 942 of file util.cpp.
Referenced by find(), pop(), and push().
The documentation for this class was generated from the following file:
src/util.cpp