Doxygen: src/context.cpp File Reference
context.cpp File Reference
#include <assert.h>
#include <qdir.h>
#include "context.h"
#include "config.h"
#include "index.h"
#include "classlist.h"
#include "doxygen.h"
#include "namespacedef.h"
#include "filedef.h"
#include "pagedef.h"
#include "groupdef.h"
#include "util.h"
#include "version.h"
#include "language.h"
#include "message.h"
#include "vhdldocgen.h"
#include "filename.h"
#include "dirdef.h"
#include "docparser.h"
#include "htmlgen.h"
#include "htmldocvisitor.h"
#include "htmlhelp.h"
#include "latexgen.h"
#include "latexdocvisitor.h"
#include "dot.h"
#include "diagram.h"
#include "example.h"
#include "membername.h"
#include "parserintf.h"
#include "portable.h"
#include "arguments.h"
#include "searchindex.h"
#include "resourcemgr.h"
Classes
struct ContextGlobals
class ScopedPtr< T >
Scoped smart pointer.
class SharedPtr< T >
Reference counting smart pointer.
class GenericConstIterator
Template List iterator support.
class GenericNodeListContext
standard template list implementation
class PropertyMapper< T >
Helper class to map a property name to a handler member function.
struct PropertyMapper< T >::PropertyFuncIntf
struct PropertyMapper< T >::PropertyFunc
class ConfigContext::Private
class DoxygenContext::Private
struct DoxygenContext::Private::Cachable
class TranslateContext::Private
class DefinitionContext< T >
struct DefinitionContext< T >::Cachable
class IncludeInfoContext::Private
class IncludeInfoListContext::Private
class ClassContext::Private
struct ClassContext::Private::Cachable
class NamespaceContext::Private
struct NamespaceContext::Private::Cachable
class FileContext::Private
struct FileContext::Private::Cachable
class DirContext::Private
struct DirContext::Private::Cachable
class PageContext::Private
struct PageContext::Private::Cachable
class TextGeneratorHtml
class TextGeneratorLatex
class TextGeneratorFactory
class MemberContext::Private
struct MemberContext::Private::Cachable
class ModuleContext::Private
struct ModuleContext::Private::Cachable
class ClassListContext::Private
class ClassIndexContext::Private
struct ClassIndexContext::Private::Cachable
class ClassHierarchyContext::Private
struct ClassHierarchyContext::Private::Cachable
class NestingNodeContext::Private
struct NestingNodeContext::Private::Cachable
class NestingContext::Private
class ClassTreeContext::Private
struct ClassTreeContext::Private::Cachable
class NamespaceListContext::Private
class NamespaceTreeContext::Private
struct NamespaceTreeContext::Private::Cachable
class FileListContext::Private
class DirListContext::Private
class UsedFilesContext::Private
class FileTreeContext::Private
struct FileTreeContext::Private::Cachable
class PageTreeContext::Private
struct PageTreeContext::Private::Cachable
class PageListContext::Private
class ExampleListContext::Private
class ModuleListContext::Private
class ModuleTreeContext::Private
struct ModuleTreeContext::Private::Cachable
class NavPathElemContext::Private
class ExampleTreeContext::Private
struct ExampleTreeContext::Private::Cachable
class GlobalsIndexContext::Private
struct GlobalsIndexContext::Private::Cachable
class ClassMembersIndexContext::Private
struct ClassMembersIndexContext::Private::Cachable
class NamespaceMembersIndexContext::Private
struct NamespaceMembersIndexContext::Private::Cachable
class InheritanceGraphContext::Private
class InheritanceNodeContext::Private
class InheritanceListContext::Private
class MemberListContext::Private
class MemberInfoContext::Private
class AllMembersListContext::Private
class MemberGroupInfoContext::Private
struct MemberGroupInfoContext::Private::Cachable
class MemberGroupListContext::Private
class MemberListInfoContext::Private
struct MemberListInfoContext::Private::Cachable
class InheritedMemberInfoContext::Private
class InheritedMemberInfoListContext::Private
class ArgumentContext::Private
struct ArgumentContext::Private::Cachable
class ArgumentListContext::Private
class SymbolContext::Private
class SymbolListContext::Private
class SymbolGroupContext::Private
struct SymbolGroupContext::Private::Cachable
class SymbolGroupListContext::Private
class SymbolIndexContext::Private
struct SymbolIndexContext::Private::Cachable
class SymbolIndicesContext::Private
class SearchIndexContext::Private
struct SearchIndexContext::Private::Cachable
class SearchIndicesContext::Private
class HtmlEscaper
class LatexSpaceless
class HtmlSpaceless
class LatexEscaper
Enumerations
enum ContextOutputFormat {
ContextOutputFormat_Unspecified =0, ContextOutputFormat_Html, ContextOutputFormat_Latex, ContextOutputFormat_Rtf,
ContextOutputFormat_ManPage, ContextOutputFormat_DocBook, ContextOutputFormat_Xml, ContextOutputFormat_TagFile
}
Functions
static TemplateVariant parseDoc (Definition *def, const QCString &file, int line, const QCString &relPath, const QCString &docStr, bool isBrief)
static TemplateVariant parseCode (MemberDef *md, const QCString &scopeName, const QCString &relPath, const QCString &code, int startLine=-1, int endLine=-1, bool showLineNumbers=FALSE)
static TemplateVariant parseCode (FileDef *fd, const QCString &relPath)
TemplateVariant createLinkedText (Definition *def, const QCString &relPath, const QCString &text)
static int computeMaxDepth (const TemplateListIntf *list)
static int computeNumNodesAtLevel (const TemplateStructIntf *s, int level, int maxLevel)
static int computePreferredDepth (const TemplateListIntf *list, int maxDepth)
void generateOutputViaTemplate ()
void generateTemplateFiles (const char *templateDir)
Variables
struct ContextGlobals g_globals
Enumeration Type Documentation
ContextOutputFormat
enum ContextOutputFormat
Enumerator
ContextOutputFormat_Unspecified
ContextOutputFormat_Html
ContextOutputFormat_Latex
ContextOutputFormat_Rtf
ContextOutputFormat_ManPage
ContextOutputFormat_DocBook
ContextOutputFormat_Xml
ContextOutputFormat_TagFile
Definition at line 55 of file context.cpp.
Function Documentation
computeMaxDepth()
static int computeMaxDepth (const TemplateListIntf * list) static
Definition at line 5868 of file context.cpp.
References TemplateListIntf::createIterator(), TemplateListIntf::ConstIterator::current(), TemplateStructIntf::get(), TemplateListIntf::ConstIterator::toFirst(), TemplateVariant::toList(), TemplateListIntf::ConstIterator::toNext(), and TemplateVariant::toStruct().
Referenced by ClassHierarchyContext::Private::maxDepth(), ClassTreeContext::Private::maxDepth(), NamespaceTreeContext::Private::maxDepth(), FileTreeContext::Private::maxDepth(), PageTreeContext::Private::maxDepth(), ModuleTreeContext::Private::maxDepth(), and ExampleTreeContext::Private::maxDepth().
computeNumNodesAtLevel()
static int computeNumNodesAtLevel (const TemplateStructIntf * s, int level, int maxLevel) static
Definition at line 5887 of file context.cpp.
References TemplateListIntf::createIterator(), TemplateListIntf::ConstIterator::current(), TemplateStructIntf::get(), TemplateListIntf::ConstIterator::toFirst(), TemplateVariant::toList(), TemplateListIntf::ConstIterator::toNext(), and TemplateVariant::toStruct().
Referenced by computePreferredDepth().
computePreferredDepth()
static int computePreferredDepth (const TemplateListIntf * list, int maxDepth) static
Definition at line 5908 of file context.cpp.
References computeNumNodesAtLevel(), Config_getInt, TemplateListIntf::createIterator(), TemplateListIntf::ConstIterator::current(), TemplateListIntf::ConstIterator::toFirst(), TemplateListIntf::ConstIterator::toNext(), and TemplateVariant::toStruct().
Referenced by ClassHierarchyContext::Private::preferredDepth(), ClassTreeContext::Private::preferredDepth(), NamespaceTreeContext::Private::preferredDepth(), FileTreeContext::Private::preferredDepth(), PageTreeContext::Private::preferredDepth(), ModuleTreeContext::Private::preferredDepth(), and ExampleTreeContext::Private::preferredDepth().
createLinkedText()
TemplateVariant createLinkedText (Definition * def, const QCString & relPath, const QCString & text)
Definition at line 3856 of file context.cpp.
References TextGeneratorFactory::create(), Definition::getBodyDef(), Definition::getOuterScope(), TextGeneratorFactory::instance(), and linkifyText().
Referenced by MemberContext::Private::bitfields(), MemberContext::Private::declArgs(), MemberContext::Private::declType(), MemberContext::Private::definition(), ArgumentContext::Private::defVal(), MemberContext::Private::exception(), MemberContext::Private::fieldType(), MemberContext::Private::initializer(), MemberContext::Private::templateAlias(), MemberContext::Private::trailingReturnType(), and ArgumentContext::Private::type().
generateOutputViaTemplate()
void generateOutputViaTemplate ()
Definition at line 10096 of file context.cpp.
References ConfigContext::alloc(), DoxygenContext::alloc(), TranslateContext::alloc(), PageContext::alloc(), ClassListContext::alloc(), ClassIndexContext::alloc(), ClassHierarchyContext::alloc(), ClassTreeContext::alloc(), NamespaceListContext::alloc(), NamespaceTreeContext::alloc(), DirListContext::alloc(), FileListContext::alloc(), FileTreeContext::alloc(), PageListContext::alloc(), PageTreeContext::alloc(), ModuleListContext::alloc(), ModuleTreeContext::alloc(), ExampleListContext::alloc(), ExampleTreeContext::alloc(), GlobalsIndexContext::alloc(), ClassMembersIndexContext::alloc(), NamespaceMembersIndexContext::alloc(), SearchIndicesContext::alloc(), Config_getString, ContextOutputFormat_Html, ContextOutputFormat_Latex, TemplateEngine::createContext(), createSubDirs(), DefinitionIntf::definitionType(), TemplateEngine::destroyContext(), ContextGlobals::dynSectionId, g_globals, SharedPtr< T >::get(), TemplateEngine::loadByName(), Doxygen::mainPage, msg(), ContextGlobals::outputDir, ContextGlobals::outputFormat, Doxygen::pageSDict, Template::render(), TemplateContext::set(), Definition::setCookie(), TemplateContext::setEscapeIntf(), PageDef::setFileName(), TemplateContext::setOutputDirectory(), TemplateContext::setSpacelessIntf(), TemplateEngine::setTemplateDir(), Doxygen::symbolMap, theTranslator, Translator::trMainPage(), DefinitionIntf::TypeSymbolList, and TemplateEngine::unload().
Referenced by generateOutput().
generateTemplateFiles()
void generateTemplateFiles (const char * templateDir)
Definition at line 10265 of file context.cpp.
References err(), ResourceMgr::instance(), and ResourceMgr::writeCategory().
Referenced by readConfiguration().
parseCode() [1/2]
static TemplateVariant parseCode (MemberDef * md, const QCString & scopeName, const QCString & relPath, const QCString & code, int startLine = -1, int endLine = -1, bool showLineNumbers = FALSE) static
Definition at line 1281 of file context.cpp.
References ContextOutputFormat_Html, ContextOutputFormat_Latex, Definition::docFile(), err(), g_globals, Definition::getBodyDef(), Definition::getDefFileExtension(), Definition::getLanguage(), ParserManager::getParser(), ContextGlobals::outputFormat, ParserInterface::parseCode(), Doxygen::parserManager, and ParserInterface::resetCodeParserState().
Referenced by MemberContext::Private::initializerAsCode(), MemberContext::Private::sourceCode(), FileContext::Private::sources(), DocbookDocVisitor::visit(), RTFDocVisitor::visit(), ManDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), LatexDocVisitor::visit(), and PerlModDocVisitor::visit().
parseCode() [2/2]
static TemplateVariant parseCode (FileDef * fd, const QCString & relPath) static
Definition at line 1312 of file context.cpp.
References FileDef::absFilePath(), Config_getBool, ContextOutputFormat_Html, ContextOutputFormat_Latex, Definition::docFile(), err(), fileToString(), g_globals, Definition::getDefFileExtension(), Definition::getLanguage(), ParserManager::getParser(), ContextGlobals::outputFormat, ParserInterface::parseCode(), Doxygen::parserManager, and ParserInterface::resetCodeParserState().
parseDoc()
static TemplateVariant parseDoc (Definition * def, const QCString & file, int line, const QCString & relPath, const QCString & docStr, bool isBrief) static
Definition at line 1242 of file context.cpp.
References DocRoot::accept(), ContextOutputFormat_Html, ContextOutputFormat_Latex, err(), g_globals, Definition::getDefFileExtension(), DocRoot::isEmpty(), ContextGlobals::outputFormat, and validatingParseDoc().
Referenced by DefinitionContext< FileContext::Private >::brief(), NestingNodeContext::Private::brief(), DefinitionContext< FileContext::Private >::details(), MemberGroupInfoContext::Private::docs(), ArgumentContext::Private::docs(), PageContext::Private::example(), DefinitionContext< FileContext::Private >::inbodyDocs(), and MemberContext::Private::paramDocs().
Variable Documentation
g_globals
struct ContextGlobals g_globals
Referenced by DefinitionContext< FileContext::Private >::brief(), MemberContext::Private::callerGraph(), MemberContext::Private::callGraph(), ClassContext::Private::collaborationDiagram(), TextGeneratorFactory::create(), DefinitionContext< FileContext::Private >::details(), DirContext::Private::dirGraph(), DefinitionContext< FileContext::Private >::dynSectionId(), PageContext::Private::example(), generateOutputViaTemplate(), InheritanceGraphContext::Private::graph(), ModuleContext::Private::groupGraph(), DefinitionContext< FileContext::Private >::inbodyDocs(), FileContext::Private::includedByGraph(), FileContext::Private::includeGraph(), ClassContext::Private::inheritanceDiagram(), parseCode(), and parseDoc().