Doxygen: DotConstString Class Reference
DotConstString Class Reference
Minimal constant string class that is thread safe, once initialized.
#include <dot.h>
Public Member Functions
DotConstString ()
~DotConstString ()
DotConstString (const QCString &s)
DotConstString (const DotConstString &s)
const char * data () const
bool isEmpty () const
void set (const QCString &s)
Private Member Functions
DotConstString & operator= (const DotConstString &)
Private Attributes
char * m_str
Detailed Description
Minimal constant string class that is thread safe, once initialized.
Definition at line 338 of file dot.h.
Constructor & Destructor Documentation
DotConstString() [1/3]
DotConstString::DotConstString () inline
Definition at line 341 of file dot.h.
References m_str.
~DotConstString()
DotConstString::~DotConstString () inline
Definition at line 342 of file dot.h.
References m_str.
DotConstString() [2/3]
DotConstString::DotConstString (const QCString & s) inline
Definition at line 343 of file dot.h.
DotConstString() [3/3]
DotConstString::DotConstString (const DotConstString & s) inline
Definition at line 344 of file dot.h.
References data().
Member Function Documentation
data()
const char* DotConstString::data () const inline
Definition at line 345 of file dot.h.
References m_str.
Referenced by DotWorkerThread::cleanup(), DotConstString(), and DotRunner::run().
isEmpty()
bool DotConstString::isEmpty () const inline
Definition at line 346 of file dot.h.
References m_str.
Referenced by DotRunner::run(), and DotWorkerThread::run().
operator=()
DotConstString& DotConstString::operator= (const DotConstString &) private
set()
void DotConstString::set (const QCString & s) inline
Definition at line 347 of file dot.h.
References m_str.
Referenced by DotRunner::addPostProcessing(), and DotRunner::run().
Member Data Documentation
m_str
char* DotConstString::m_str private
Definition at line 359 of file dot.h.
Referenced by data(), DotConstString(), isEmpty(), set(), and ~DotConstString().
The documentation for this class was generated from the following file:
src/dot.h