Doxygen: src/defgen.cpp File Reference
defgen.cpp File Reference
#include <stdlib.h>
#include "defgen.h"
#include "doxygen.h"
#include "message.h"
#include "config.h"
#include "classlist.h"
#include "util.h"
#include "defargs.h"
#include "outputgen.h"
#include "dot.h"
#include "arguments.h"
#include "memberlist.h"
#include "namespacedef.h"
#include "filedef.h"
#include "filename.h"
#include <qdir.h>
#include <qfile.h>
#include <qtextstream.h>
Macros
#define DEF_DB(x)
Functions
void writeDEFString (FTextStream &t, const char *s)
void generateDEFForMember (MemberDef *md, FTextStream &t, Definition *def, const char *Prefix)
void generateDEFClassSection (ClassDef *cd, FTextStream &t, MemberList *ml, const char *kind)
void generateDEFForClass (ClassDef *cd, FTextStream &t)
void generateDEFSection (Definition *d, FTextStream &t, MemberList *ml, const char *kind)
void generateDEFForNamespace (NamespaceDef *nd, FTextStream &t)
void generateDEFForFile (FileDef *fd, FTextStream &t)
void generateDEF ()
Macro Definition Documentation
DEF_DB
#define DEF_DB (x)
Definition at line 40 of file defgen.cpp.
Function Documentation
generateDEF()
void generateDEF ()
Definition at line 558 of file defgen.cpp.
References Doxygen::classSDict, Config_getString, endl(), err(), generateDEFForClass(), generateDEFForFile(), Doxygen::inputNameList, SDict< ClassDef >::Iterator, and msg().
Referenced by generateOutput().
generateDEFClassSection()
void generateDEFClassSection (ClassDef * cd, FTextStream & t, MemberList * ml, const char * kind)
Definition at line 320 of file defgen.cpp.
References MemberList::count(), endl(), and generateDEFForMember().
Referenced by generateDEFForClass().
generateDEFForClass()
void generateDEFForClass (ClassDef * cd, FTextStream & t)
Definition at line 340 of file defgen.cpp.
References ClassDef::baseClasses(), Definition::briefDescription(), DotNode::Collaboration, ClassDef::compoundTypeString(), MemberList::count(), Definition::documentation(), endl(), generateDEFClassSection(), Definition::getDefFileName(), Definition::getDefLine(), ClassDef::getMemberList(), ClassDef::getMemberLists(), ClassDef::getOutputFileBase(), DotNode::Inheritance, ClassDef::isReference(), DotClassGraph::isTrivial(), MemberListType_dcopMethods, MemberListType_detailedLists, MemberListType_friends, MemberListType_interfaces, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_properties, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, MemberListType_related, MemberListType_services, MemberListType_signals, Definition::name(), Normal, Package, Private, Protected, Public, Pure, ClassDef::subClasses(), ClassDef::templateMaster(), Virtual, and DotClassGraph::writeDEF().
Referenced by generateDEF().
generateDEFForFile()
void generateDEFForFile (FileDef * fd, FTextStream & t)
Definition at line 528 of file defgen.cpp.
References Definition::briefDescription(), Definition::documentation(), endl(), generateDEFSection(), Definition::getDefFileName(), Definition::getDefLine(), FileDef::getMemberList(), FileDef::getOutputFileBase(), Definition::isReference(), MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decFuncMembers, MemberListType_decProtoMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, FileDef::name(), and writeDEFString().
Referenced by generateDEF().
generateDEFForMember()
void generateDEFForMember (MemberDef * md, FTextStream & t, Definition * def, const char * Prefix)
Definition at line 57 of file defgen.cpp.
References MemberDef::anchor(), MemberDef::argsString(), MemberDef::argumentList(), Argument::array, Argument::attrib, MemberDef::briefDescription(), Argument::defval, MemberDef::documentation(), endl(), MemberDef::enumFieldList(), Definition::getBodyDef(), MemberDef::getClassDef(), Definition::getDefFileName(), Definition::getDefLine(), MemberDef::getNamespaceDef(), MemberDef::getOutputFileBase(), FileDef::getOutputFileBase(), Definition::getReferencedByMembers(), Definition::getReferencesMembers(), MemberDef::getScopeString(), Definition::getStartBodyLine(), MemberDef::initializer(), SDict< MemberDef >::Iterator, MemberDef::memberType(), MemberType_DCOP, MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, Argument::name, Definition::name(), Normal, Package, Private, Protected, MemberDef::protection(), Public, Pure, replaceAnonymousScopes(), stringToArgumentList(), Argument::type, MemberDef::typeString(), Virtual, MemberDef::virtualness(), and writeDEFString().
Referenced by generateDEFClassSection(), and generateDEFSection().
generateDEFForNamespace()
void generateDEFForNamespace (NamespaceDef * nd, FTextStream & t)
Definition at line 502 of file defgen.cpp.
References Definition::briefDescription(), Definition::documentation(), endl(), generateDEFSection(), Definition::getDefFileName(), Definition::getDefLine(), NamespaceDef::getMemberList(), NamespaceDef::getOutputFileBase(), Definition::isReference(), MemberListType_decDefineMembers, MemberListType_decEnumMembers, MemberListType_decFuncMembers, MemberListType_decProtoMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, Definition::name(), and writeDEFString().
generateDEFSection()
void generateDEFSection (Definition * d, FTextStream & t, MemberList * ml, const char * kind)
Definition at line 484 of file defgen.cpp.
References MemberList::count(), endl(), and generateDEFForMember().
Referenced by generateDEFForFile(), and generateDEFForNamespace().
writeDEFString()
void writeDEFString (FTextStream & t, const char * s) inline
Definition at line 42 of file defgen.cpp.
Referenced by generateDEFForFile(), generateDEFForMember(), and generateDEFForNamespace().