Doxygen: VhdlParserIF Class Reference
VhdlParserIF Class Reference
#include <VhdlParserIF.h>
Static Public Member Functions
static void parseVhdlfile (const char *inputBuffer, bool inLine)
Detailed Description
Definition at line 6 of file VhdlParserIF.h.
Member Function Documentation
parseVhdlfile()
void VhdlParserIF::parseVhdlfile (const char * inputBuffer, bool inLine) static
Definition at line 12 of file VhdlParserIF.cpp.
References vhdl::parser::VhdlParser::design_file(), JAVACC_STRING_TYPE, myParser, vhdl::parser::VhdlParser::parseInline(), and vhdl::parser::VhdlParser::setErrorHandler().
Referenced by VHDLLanguageScanner::parseInput().
The documentation for this class was generated from the following files:
vhdlparser/VhdlParserIF.h
vhdlparser/VhdlParserIF.cpp