Doxygen: ClassTreeContext Class Reference
ClassTreeContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static ClassTreeContext * alloc ()
Private Member Functions
ClassTreeContext ()
~ClassTreeContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 567 of file context.h.
Constructor & Destructor Documentation
ClassTreeContext()
ClassTreeContext::ClassTreeContext () private
Definition at line 6826 of file context.cpp.
References p, and Private.
Referenced by alloc().
~ClassTreeContext()
ClassTreeContext::~ClassTreeContext () private
Definition at line 6831 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int ClassTreeContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 574 of file context.h.
References RefCountedContext::addRef().
alloc()
static ClassTreeContext* ClassTreeContext::alloc () inline static
Definition at line 570 of file context.h.
References ClassTreeContext().
Referenced by generateOutputViaTemplate().
get()
TemplateVariant ClassTreeContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 6836 of file context.cpp.
References ClassTreeContext::Private::get(), and p.
release()
virtual int ClassTreeContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 575 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ClassTreeContext::p private
Definition at line 580 of file context.h.
Referenced by ClassTreeContext(), get(), and ~ClassTreeContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp