Doxygen: src/classdef.cpp File Reference
classdef.cpp File Reference
#include <stdio.h>
#include <qfile.h>
#include <qregexp.h>
#include "classdef.h"
#include "classlist.h"
#include "entry.h"
#include "doxygen.h"
#include "membername.h"
#include "message.h"
#include "config.h"
#include "util.h"
#include "diagram.h"
#include "language.h"
#include "htmlhelp.h"
#include "example.h"
#include "outputlist.h"
#include "dot.h"
#include "defargs.h"
#include "debug.h"
#include "docparser.h"
#include "searchindex.h"
#include "vhdldocgen.h"
#include "layout.h"
#include "arguments.h"
#include "memberlist.h"
#include "groupdef.h"
#include "filedef.h"
#include "namespacedef.h"
#include "membergroup.h"
Classes
class ClassDefImpl
Private data associated with a ClassDef object.
Functions
static void writeInheritanceSpecifier (OutputList &ol, BaseClassDef *bcd)
static void searchTemplateSpecs (Definition *d, QList< ArgumentList > &result, QCString &name, SrcLangExt lang)
static void writeTemplateSpec (OutputList &ol, Definition *d, const QCString &type, SrcLangExt lang)
static bool isStandardFunc (MemberDef *md)
Function Documentation
isStandardFunc()
static bool isStandardFunc (MemberDef * md) static
Definition at line 2854 of file classdef.cpp.
References MemberDef::isConstructor(), MemberDef::isDestructor(), and Definition::name().
Referenced by ClassDef::mergeMembers().
searchTemplateSpecs()
static void searchTemplateSpecs (Definition * d, QList< ArgumentList > & result, QCString & name, SrcLangExt lang) static
Definition at line 877 of file classdef.cpp.
References DefinitionIntf::definitionType(), Definition::getOuterScope(), isSpecialization(), Definition::localName(), Definition::qualifiedName(), tempArgListToString(), ClassDef::templateArguments(), and DefinitionIntf::TypeClass.
Referenced by writeTemplateSpec().
writeInheritanceSpecifier()
static void writeInheritanceSpecifier (OutputList & ol, BaseClassDef * bcd) static
Definition at line 816 of file classdef.cpp.
References OutputList::docify(), OutputList::endTypewriter(), Normal, Private, BaseClassDef::prot, Protected, Public, OutputList::startTypewriter(), BaseClassDef::virt, and Virtual.
Referenced by ClassDef::writeInheritanceGraph().
writeTemplateSpec()
static void writeTemplateSpec (OutputList & ol, Definition * d, const QCString & type, SrcLangExt lang) static
Definition at line 912 of file classdef.cpp.
References Argument::defval, OutputList::docify(), OutputList::endSubsubsection(), OutputList::lineBreak(), Argument::name, searchTemplateSpecs(), OutputList::startSubsubsection(), Argument::type, and OutputList::writeString().
Referenced by ClassDef::writeDetailedDocumentationBody().