Doxygen: MemberName Class Reference
MemberName Class Reference
Class representing all MemberDef objects with the same name.
#include <membername.h>
Public Member Functions
MemberName (const char *name)
~MemberName ()
const char * memberName () const
Private Member Functions
int compareValues (const MemberDef *item1, const MemberDef *item2) const
Private Attributes
QCString name
Detailed Description
Class representing all MemberDef objects with the same name.
Definition at line 26 of file membername.h.
Constructor & Destructor Documentation
MemberName()
MemberName::MemberName (const char * name)
Definition at line 23 of file membername.cpp.
References name.
~MemberName()
MemberName::~MemberName ()
Definition at line 29 of file membername.cpp.
Member Function Documentation
compareValues()
int MemberName::compareValues (const MemberDef * item1, const MemberDef * item2) const private
Definition at line 33 of file membername.cpp.
References MemberDef::getClassDef(), MemberDef::getFileDef(), FileDef::name(), and Definition::name().
memberName()
const char* MemberName::memberName () const inline
Definition at line 31 of file membername.h.
References name.
Referenced by MemberNameSDict::compareValues(), and findFriends().
Member Data Documentation
name
QCString MemberName::name private
Definition at line 35 of file membername.h.
Referenced by MemberName(), and memberName().
The documentation for this class was generated from the following files:
src/membername.h
src/membername.cpp