Doxygen: DocbookDocVisitor Class Reference
DocbookDocVisitor Class Reference
Concrete visitor implementation for Docbook output.
#include <docbookvisitor.h>
Public Member Functions
DocbookDocVisitor (FTextStream &t, CodeOutputInterface &ci)
void visit (DocWord *)
void visit (DocLinkedWord *)
void visit (DocWhiteSpace *)
void visit (DocSymbol *)
void visit (DocURL *)
void visit (DocLineBreak *)
void visit (DocHorRuler *)
void visit (DocStyleChange *)
void visit (DocVerbatim *)
void visit (DocAnchor *)
void visit (DocInclude *)
void visit (DocIncOperator *)
void visit (DocFormula *)
void visit (DocIndexEntry *)
void visit (DocSimpleSectSep *)
void visit (DocCite *)
void visitPre (DocAutoList *)
void visitPost (DocAutoList *)
void visitPre (DocAutoListItem *)
void visitPost (DocAutoListItem *)
void visitPre (DocPara *)
void visitPost (DocPara *)
void visitPre (DocRoot *)
void visitPost (DocRoot *)
void visitPre (DocSimpleSect *)
void visitPost (DocSimpleSect *)
void visitPre (DocTitle *)
void visitPost (DocTitle *)
void visitPre (DocSimpleList *)
void visitPost (DocSimpleList *)
void visitPre (DocSimpleListItem *)
void visitPost (DocSimpleListItem *)
void visitPre (DocSection *)
void visitPost (DocSection *)
void visitPre (DocHtmlList *)
void visitPost (DocHtmlList *)
void visitPre (DocHtmlListItem *)
void visitPost (DocHtmlListItem *)
void visitPre (DocHtmlDescList *)
void visitPost (DocHtmlDescList *)
void visitPre (DocHtmlDescTitle *)
void visitPost (DocHtmlDescTitle *)
void visitPre (DocHtmlDescData *)
void visitPost (DocHtmlDescData *)
void visitPre (DocHtmlTable *)
void visitPost (DocHtmlTable *)
void visitPre (DocHtmlRow *)
void visitPost (DocHtmlRow *)
void visitPre (DocHtmlCell *)
void visitPost (DocHtmlCell *)
void visitPre (DocHtmlCaption *)
void visitPost (DocHtmlCaption *)
void visitPre (DocInternal *)
void visitPost (DocInternal *)
void visitPre (DocHRef *)
void visitPost (DocHRef *)
void visitPre (DocHtmlHeader *)
void visitPost (DocHtmlHeader *)
void visitPre (DocImage *)
void visitPost (DocImage *)
void visitPre (DocDotFile *)
void visitPost (DocDotFile *)
void visitPre (DocMscFile *)
void visitPost (DocMscFile *)
void visitPre (DocDiaFile *)
void visitPost (DocDiaFile *)
void visitPre (DocLink *)
void visitPost (DocLink *)
void visitPre (DocRef *)
void visitPost (DocRef *)
void visitPre (DocSecRefItem *)
void visitPost (DocSecRefItem *)
void visitPre (DocSecRefList *)
void visitPost (DocSecRefList *)
void visitPre (DocParamSect *)
void visitPost (DocParamSect *)
void visitPre (DocParamList *)
void visitPost (DocParamList *)
void visitPre (DocXRefItem *)
void visitPost (DocXRefItem *)
void visitPre (DocInternalRef *)
void visitPost (DocInternalRef *)
void visitPre (DocCopy *)
void visitPost (DocCopy *)
void visitPre (DocText *)
void visitPost (DocText *)
void visitPre (DocHtmlBlockQuote *)
void visitPost (DocHtmlBlockQuote *)
void visitPre (DocVhdlFlow *)
void visitPost (DocVhdlFlow *)
void visitPre (DocParBlock *)
void visitPost (DocParBlock *)
Public Member Functions inherited from DocVisitor
DocVisitor (int id)
virtual ~DocVisitor ()
int id () const
Private Member Functions
void filter (const char *str)
void startLink (const QCString &file, const QCString &anchor)
void endLink ()
void pushEnabled ()
void popEnabled ()
void startMscFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption)
void endMscFile (bool hasCaption)
void writeMscFile (const QCString &fileName, DocVerbatim *s)
void startDiaFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption)
void endDiaFile (bool hasCaption)
void writeDiaFile (const QCString &fileName, DocVerbatim *s)
void startDotFile (const QCString &fileName, const QCString &width, const QCString &height, bool hasCaption)
void endDotFile (bool hasCaption)
void writeDotFile (const QCString &fileName, DocVerbatim *s)
void writePlantUMLFile (const QCString &fileName, DocVerbatim *s)
Private Attributes
FTextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre
bool m_hide
QStack< bool > m_enabled
QCString m_langExt
Detailed Description
Concrete visitor implementation for Docbook output.
Definition at line 30 of file docbookvisitor.h.
Constructor & Destructor Documentation
DocbookDocVisitor()
DocbookDocVisitor::DocbookDocVisitor (FTextStream & t, CodeOutputInterface & ci)
Definition at line 86 of file docbookvisitor.cpp.
Member Function Documentation
endDiaFile()
void DocbookDocVisitor::endDiaFile (bool hasCaption) private
Definition at line 1340 of file docbookvisitor.cpp.
References endl(), m_hide, m_t, and visitPostEnd().
Referenced by visitPost().
endDotFile()
void DocbookDocVisitor::endDotFile (bool hasCaption) private
Definition at line 1386 of file docbookvisitor.cpp.
References endl(), m_hide, m_t, and visitPostEnd().
Referenced by visitPost().
endLink()
void DocbookDocVisitor::endLink () private
Definition at line 1224 of file docbookvisitor.cpp.
References m_t.
Referenced by visit(), and visitPost().
endMscFile()
void DocbookDocVisitor::endMscFile (bool hasCaption) private
Definition at line 1295 of file docbookvisitor.cpp.
References endl(), m_hide, m_t, and visitPostEnd().
Referenced by visitPost().
filter()
void DocbookDocVisitor::filter (const char * str) private
Definition at line 1212 of file docbookvisitor.cpp.
References convertToXML(), and m_t.
Referenced by visit(), and visitPre().
popEnabled()
void DocbookDocVisitor::popEnabled () private
Definition at line 1234 of file docbookvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit(), and visitPost().
pushEnabled()
void DocbookDocVisitor::pushEnabled () private
Definition at line 1229 of file docbookvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit(), and visitPre().
startDiaFile()
void DocbookDocVisitor::startDiaFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption) private
Definition at line 1317 of file docbookvisitor.cpp.
References Config_getString, DIA_BITMAP, endl(), m_t, visitPreStart(), and writeDiaGraphFromFile().
Referenced by visitPre().
startDotFile()
void DocbookDocVisitor::startDotFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption) private
Definition at line 1362 of file docbookvisitor.cpp.
References Config_getString, endl(), getDotImageExtension(), GOF_BITMAP, m_t, visitPreStart(), and writeDotGraphFromFile().
Referenced by visitPre().
startLink()
void DocbookDocVisitor::startLink (const QCString & file, const QCString & anchor) private
Definition at line 1217 of file docbookvisitor.cpp.
References m_t.
Referenced by visit(), and visitPre().
startMscFile()
void DocbookDocVisitor::startMscFile (const QCString & fileName, const QCString & width, const QCString & height, bool hasCaption) private
Definition at line 1272 of file docbookvisitor.cpp.
References Config_getString, endl(), m_t, MSC_BITMAP, visitPreStart(), and writeMscGraphFromFile().
Referenced by visitPre().
visit() [1/16]
void DocbookDocVisitor::visit (DocWord * w) virtual
Implements DocVisitor.
Definition at line 95 of file docbookvisitor.cpp.
References filter(), m_hide, and DocWord::word().
Referenced by visitPre().
visit() [2/16]
void DocbookDocVisitor::visit (DocLinkedWord * w) virtual
Implements DocVisitor.
Definition at line 101 of file docbookvisitor.cpp.
References DocLinkedWord::anchor(), endLink(), DocLinkedWord::file(), filter(), m_hide, startLink(), and DocLinkedWord::word().
visit() [3/16]
void DocbookDocVisitor::visit (DocWhiteSpace * w) virtual
Implements DocVisitor.
Definition at line 109 of file docbookvisitor.cpp.
References DocWhiteSpace::chars(), m_hide, m_insidePre, and m_t.
visit() [4/16]
void DocbookDocVisitor::visit (DocSymbol * s) virtual
Implements DocVisitor.
Definition at line 122 of file docbookvisitor.cpp.
References HtmlEntityMapper::docbook(), err(), HtmlEntityMapper::instance(), m_hide, m_t, and DocSymbol::symbol().
visit() [5/16]
void DocbookDocVisitor::visit (DocURL * u) virtual
Implements DocVisitor.
Definition at line 136 of file docbookvisitor.cpp.
References filter(), DocURL::isEmail(), m_hide, m_t, and DocURL::url().
visit() [6/16]
void DocbookDocVisitor::visit (DocLineBreak *) virtual
Implements DocVisitor.
Definition at line 147 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visit() [7/16]
void DocbookDocVisitor::visit (DocHorRuler *) virtual
Implements DocVisitor.
Definition at line 153 of file docbookvisitor.cpp.
References m_hide, and m_t.
visit() [8/16]
void DocbookDocVisitor::visit (DocStyleChange * s) virtual
Implements DocVisitor.
Definition at line 160 of file docbookvisitor.cpp.
References DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Code, DocStyleChange::Div, DocStyleChange::enable(), DocStyleChange::Italic, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::style(), DocStyleChange::Subscript, and DocStyleChange::Superscript.
visit() [9/16]
void DocbookDocVisitor::visit (DocVerbatim * s) virtual
Implements DocVisitor.
Definition at line 204 of file docbookvisitor.cpp.
References DocVerbatim::Code, Config_getString, DocVerbatim::context(), DocVerbatim::DocbookOnly, DocVerbatim::Dot, endl(), err(), DocVerbatim::exampleFile(), filter(), getLanguageFromFileName(), ParserManager::getParser(), DocVerbatim::HtmlOnly, DocVerbatim::isExample(), DocVerbatim::LatexOnly, m_ci, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, ParserInterface::parseCode(), Doxygen::parserManager, DocVerbatim::PlantUML, DocVerbatim::RtfOnly, DocVerbatim::text(), DocVerbatim::type(), DocVerbatim::Verbatim, writeDotFile(), writeMscFile(), writePlantUMLFile(), writePlantUMLSource(), and DocVerbatim::XmlOnly.
visit() [10/16]
void DocbookDocVisitor::visit (DocAnchor * anc) virtual
Implements DocVisitor.
Definition at line 303 of file docbookvisitor.cpp.
References DocAnchor::anchor(), DocAnchor::file(), m_hide, and m_t.
visit() [11/16]
void DocbookDocVisitor::visit (DocInclude * inc) virtual
Implements DocVisitor.
Definition at line 309 of file docbookvisitor.cpp.
References DocInclude::blockId(), DocInclude::context(), DocInclude::DontInclude, err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), DocInclude::file(), filter(), getLanguageFromFileName(), ParserManager::getParser(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_hide, m_t, parseCode(), Doxygen::parserManager, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::text(), DocInclude::type(), and DocInclude::VerbInclude.
visit() [12/16]
void DocbookDocVisitor::visit (DocIncOperator * op) virtual
Implements DocVisitor.
Definition at line 392 of file docbookvisitor.cpp.
References DocIncOperator::context(), endl(), DocIncOperator::exampleFile(), getLanguageFromFileName(), ParserManager::getParser(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), m_ci, m_hide, m_langExt, m_t, ParserInterface::parseCode(), Doxygen::parserManager, popEnabled(), pushEnabled(), DocIncOperator::Skip, DocIncOperator::text(), and DocIncOperator::type().
visit() [13/16]
void DocbookDocVisitor::visit (DocFormula * f) virtual
Implements DocVisitor.
Definition at line 428 of file docbookvisitor.cpp.
References filter(), m_hide, m_t, DocFormula::name(), and DocFormula::text().
visit() [14/16]
void DocbookDocVisitor::visit (DocIndexEntry * ie) virtual
Implements DocVisitor.
Definition at line 436 of file docbookvisitor.cpp.
References endl(), DocIndexEntry::entry(), filter(), m_hide, and m_t.
visit() [15/16]
void DocbookDocVisitor::visit (DocSimpleSectSep *) virtual
Implements DocVisitor.
Definition at line 444 of file docbookvisitor.cpp.
References m_t.
visit() [16/16]
void DocbookDocVisitor::visit (DocCite * cite) virtual
Implements DocVisitor.
Definition at line 449 of file docbookvisitor.cpp.
References DocCite::anchor(), endLink(), DocCite::file(), filter(), m_hide, startLink(), and DocCite::text().
visitPost() [1/38]
void DocbookDocVisitor::visitPost (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 474 of file docbookvisitor.cpp.
References DocAutoList::isEnumList(), m_hide, and m_t.
visitPost() [2/38]
void DocbookDocVisitor::visitPost (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 493 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [3/38]
void DocbookDocVisitor::visitPost (DocPara *) virtual
Implements DocVisitor.
Definition at line 506 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [4/38]
void DocbookDocVisitor::visitPost (DocRoot *) virtual
Implements DocVisitor.
Definition at line 518 of file docbookvisitor.cpp.
visitPost() [5/38]
void DocbookDocVisitor::visitPost (DocSimpleSect *) virtual
Implements DocVisitor.
Definition at line 688 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [6/38]
void DocbookDocVisitor::visitPost (DocTitle *) virtual
Implements DocVisitor.
Definition at line 700 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [7/38]
void DocbookDocVisitor::visitPost (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 712 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [8/38]
void DocbookDocVisitor::visitPost (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 724 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [9/38]
void DocbookDocVisitor::visitPost (DocSection *) virtual
Implements DocVisitor.
Definition at line 741 of file docbookvisitor.cpp.
References m_t.
visitPost() [10/38]
void DocbookDocVisitor::visitPost (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 755 of file docbookvisitor.cpp.
References m_hide, m_t, DocHtmlList::Ordered, and DocHtmlList::type().
visitPost() [11/38]
void DocbookDocVisitor::visitPost (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 770 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [12/38]
void DocbookDocVisitor::visitPost (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 782 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [13/38]
void DocbookDocVisitor::visitPost (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 794 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [14/38]
void DocbookDocVisitor::visitPost (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 806 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [15/38]
void DocbookDocVisitor::visitPost (DocHtmlTable *) virtual
Implements DocVisitor.
Definition at line 821 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [16/38]
void DocbookDocVisitor::visitPost (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 835 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [17/38]
void DocbookDocVisitor::visitPost (DocHtmlCell *) virtual
Implements DocVisitor.
Definition at line 847 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [18/38]
void DocbookDocVisitor::visitPost (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 859 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [19/38]
void DocbookDocVisitor::visitPost (DocInternal *) virtual
Implements DocVisitor.
Definition at line 871 of file docbookvisitor.cpp.
References m_hide.
visitPost() [20/38]
void DocbookDocVisitor::visitPost (DocHRef *) virtual
Implements DocVisitor.
Definition at line 883 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [21/38]
void DocbookDocVisitor::visitPost (DocHtmlHeader *) virtual
Implements DocVisitor.
Definition at line 895 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [22/38]
void DocbookDocVisitor::visitPost (DocImage * img) virtual
Implements DocVisitor.
Definition at line 922 of file docbookvisitor.cpp.
References FileDef::absFilePath(), Config_getString, DocImage::DocBook, findFileDef(), Doxygen::imageNameDict, m_hide, m_t, DocImage::name(), popEnabled(), DocImage::type(), and visitPostEnd().
visitPost() [23/38]
void DocbookDocVisitor::visitPost (DocDotFile * df) virtual
Implements DocVisitor.
Definition at line 968 of file docbookvisitor.cpp.
References endDotFile(), DocDotFile::hasCaption(), and m_hide.
visitPost() [24/38]
void DocbookDocVisitor::visitPost (DocMscFile * df) virtual
Implements DocVisitor.
Definition at line 980 of file docbookvisitor.cpp.
References endMscFile(), DocMscFile::hasCaption(), and m_hide.
visitPost() [25/38]
void DocbookDocVisitor::visitPost (DocDiaFile * df) virtual
Implements DocVisitor.
Definition at line 991 of file docbookvisitor.cpp.
References endDiaFile(), DocDiaFile::hasCaption(), and m_hide.
visitPost() [26/38]
void DocbookDocVisitor::visitPost (DocLink *) virtual
Implements DocVisitor.
Definition at line 1003 of file docbookvisitor.cpp.
References endLink(), and m_hide.
visitPost() [27/38]
void DocbookDocVisitor::visitPost (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 1016 of file docbookvisitor.cpp.
References endLink(), DocRef::file(), and m_hide.
visitPost() [28/38]
void DocbookDocVisitor::visitPost (DocSecRefItem *) virtual
Implements DocVisitor.
Definition at line 1028 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [29/38]
void DocbookDocVisitor::visitPost (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 1040 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [30/38]
void DocbookDocVisitor::visitPost (DocParamSect *) virtual
Implements DocVisitor.
Definition at line 1070 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [31/38]
void DocbookDocVisitor::visitPost (DocParamList *) virtual
Implements DocVisitor.
Definition at line 1115 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [32/38]
void DocbookDocVisitor::visitPost (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1134 of file docbookvisitor.cpp.
References m_hide, m_t, and DocXRefItem::title().
visitPost() [33/38]
void DocbookDocVisitor::visitPost (DocInternalRef *) virtual
Implements DocVisitor.
Definition at line 1147 of file docbookvisitor.cpp.
References endLink(), m_hide, and m_t.
visitPost() [34/38]
void DocbookDocVisitor::visitPost (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1161 of file docbookvisitor.cpp.
References m_hide.
visitPost() [35/38]
void DocbookDocVisitor::visitPost (DocText *) virtual
Implements DocVisitor.
Definition at line 1174 of file docbookvisitor.cpp.
visitPost() [36/38]
void DocbookDocVisitor::visitPost (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1186 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPost() [37/38]
void DocbookDocVisitor::visitPost (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1198 of file docbookvisitor.cpp.
visitPost() [38/38]
void DocbookDocVisitor::visitPost (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1207 of file docbookvisitor.cpp.
visitPre() [1/38]
void DocbookDocVisitor::visitPre (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 461 of file docbookvisitor.cpp.
References DocAutoList::isEnumList(), m_hide, and m_t.
visitPre() [2/38]
void DocbookDocVisitor::visitPre (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 487 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [3/38]
void DocbookDocVisitor::visitPre (DocPara *) virtual
Implements DocVisitor.
Definition at line 499 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visitPre() [4/38]
void DocbookDocVisitor::visitPre (DocRoot *) virtual
Implements DocVisitor.
Definition at line 513 of file docbookvisitor.cpp.
visitPre() [5/38]
void DocbookDocVisitor::visitPre (DocSimpleSect * s) virtual
Implements DocVisitor.
Definition at line 523 of file docbookvisitor.cpp.
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, convertToXML(), DocSimpleSect::Copyright, DocSimpleSect::Date, endl(), DocSimpleSect::Invar, m_hide, m_insidePre, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), Translator::trVersion(), Translator::trWarning(), DocSimpleSect::type(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
visitPre() [6/38]
void DocbookDocVisitor::visitPre (DocTitle *) virtual
Implements DocVisitor.
Definition at line 694 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [7/38]
void DocbookDocVisitor::visitPre (DocSimpleList *) virtual
Implements DocVisitor.
Definition at line 706 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [8/38]
void DocbookDocVisitor::visitPre (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 718 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [9/38]
void DocbookDocVisitor::visitPre (DocSection * s) virtual
Implements DocVisitor.
Definition at line 730 of file docbookvisitor.cpp.
References DocSection::anchor(), endl(), DocSection::file(), filter(), m_hide, m_t, and DocSection::title().
visitPre() [10/38]
void DocbookDocVisitor::visitPre (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 746 of file docbookvisitor.cpp.
References m_hide, m_t, DocHtmlList::Ordered, and DocHtmlList::type().
visitPre() [11/38]
void DocbookDocVisitor::visitPre (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 764 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [12/38]
void DocbookDocVisitor::visitPre (DocHtmlDescList *) virtual
Implements DocVisitor.
Definition at line 776 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [13/38]
void DocbookDocVisitor::visitPre (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 788 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [14/38]
void DocbookDocVisitor::visitPre (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 800 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [15/38]
void DocbookDocVisitor::visitPre (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 812 of file docbookvisitor.cpp.
References endl(), m_hide, m_t, and DocHtmlTable::numColumns().
visitPre() [16/38]
void DocbookDocVisitor::visitPre (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 829 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [17/38]
void DocbookDocVisitor::visitPre (DocHtmlCell *) virtual
Implements DocVisitor.
Definition at line 841 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [18/38]
void DocbookDocVisitor::visitPre (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 853 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [19/38]
void DocbookDocVisitor::visitPre (DocInternal *) virtual
Implements DocVisitor.
Definition at line 865 of file docbookvisitor.cpp.
References m_hide.
visitPre() [20/38]
void DocbookDocVisitor::visitPre (DocHRef * href) virtual
Implements DocVisitor.
Definition at line 877 of file docbookvisitor.cpp.
References m_hide, m_t, and DocHRef::url().
visitPre() [21/38]
void DocbookDocVisitor::visitPre (DocHtmlHeader *) virtual
Implements DocVisitor.
Definition at line 889 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [22/38]
void DocbookDocVisitor::visitPre (DocImage * img) virtual
Implements DocVisitor.
Definition at line 901 of file docbookvisitor.cpp.
References DocImage::DocBook, endl(), m_hide, m_t, DocImage::name(), pushEnabled(), DocImage::type(), and visitPreStart().
visitPre() [23/38]
void DocbookDocVisitor::visitPre (DocDotFile * df) virtual
Implements DocVisitor.
Definition at line 962 of file docbookvisitor.cpp.
References DocDotFile::file(), DocDotFile::hasCaption(), DocDotFile::height(), m_hide, startDotFile(), and DocDotFile::width().
visitPre() [24/38]
void DocbookDocVisitor::visitPre (DocMscFile * df) virtual
Implements DocVisitor.
Definition at line 974 of file docbookvisitor.cpp.
References DocMscFile::file(), DocMscFile::hasCaption(), DocMscFile::height(), m_hide, startMscFile(), and DocMscFile::width().
visitPre() [25/38]
void DocbookDocVisitor::visitPre (DocDiaFile * df) virtual
Implements DocVisitor.
Definition at line 985 of file docbookvisitor.cpp.
References DocDiaFile::file(), DocDiaFile::hasCaption(), DocDiaFile::height(), m_hide, startDiaFile(), and DocDiaFile::width().
visitPre() [26/38]
void DocbookDocVisitor::visitPre (DocLink * lnk) virtual
Implements DocVisitor.
Definition at line 997 of file docbookvisitor.cpp.
References DocLink::anchor(), DocLink::file(), m_hide, and startLink().
visitPre() [27/38]
void DocbookDocVisitor::visitPre (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 1009 of file docbookvisitor.cpp.
References DocRef::anchor(), DocRef::file(), filter(), DocRef::hasLinkText(), m_hide, startLink(), and DocRef::targetTitle().
visitPre() [28/38]
void DocbookDocVisitor::visitPre (DocSecRefItem * ref) virtual
Implements DocVisitor.
Definition at line 1022 of file docbookvisitor.cpp.
References DocSecRefItem::anchor(), DocSecRefItem::file(), m_hide, and m_t.
visitPre() [29/38]
void DocbookDocVisitor::visitPre (DocSecRefList *) virtual
Implements DocVisitor.
Definition at line 1034 of file docbookvisitor.cpp.
References endl(), m_hide, and m_t.
visitPre() [30/38]
void DocbookDocVisitor::visitPre (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 1046 of file docbookvisitor.cpp.
References endl(), DocParamSect::Exception, m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), Translator::trTemplateParameters(), and DocParamSect::type().
visitPre() [31/38]
void DocbookDocVisitor::visitPre (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 1080 of file docbookvisitor.cpp.
References endl(), DocNode::Kind_LinkedWord, DocNode::Kind_Word, m_hide, m_t, DocParamList::parameters(), and visit().
visitPre() [32/38]
void DocbookDocVisitor::visitPre (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1122 of file docbookvisitor.cpp.
References DocXRefItem::anchor(), DocXRefItem::file(), filter(), m_hide, m_t, and DocXRefItem::title().
visitPre() [33/38]
void DocbookDocVisitor::visitPre (DocInternalRef * ref) virtual
Implements DocVisitor.
Definition at line 1141 of file docbookvisitor.cpp.
References DocInternalRef::anchor(), DocInternalRef::file(), m_hide, and startLink().
visitPre() [34/38]
void DocbookDocVisitor::visitPre (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1154 of file docbookvisitor.cpp.
References m_hide.
visitPre() [35/38]
void DocbookDocVisitor::visitPre (DocText *) virtual
Implements DocVisitor.
Definition at line 1168 of file docbookvisitor.cpp.
visitPre() [36/38]
void DocbookDocVisitor::visitPre (DocHtmlBlockQuote *) virtual
Implements DocVisitor.
Definition at line 1180 of file docbookvisitor.cpp.
References m_hide, and m_t.
visitPre() [37/38]
void DocbookDocVisitor::visitPre (DocVhdlFlow *) virtual
Implements DocVisitor.
Definition at line 1192 of file docbookvisitor.cpp.
visitPre() [38/38]
void DocbookDocVisitor::visitPre (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1203 of file docbookvisitor.cpp.
writeDiaFile()
void DocbookDocVisitor::writeDiaFile (const QCString & fileName, DocVerbatim * s) private
Definition at line 1302 of file docbookvisitor.cpp.
References DocVerbatim::children(), Config_getString, DIA_BITMAP, DocVerbatim::hasCaption(), DocVerbatim::height(), m_t, visitCaption(), visitPostEnd(), visitPreStart(), DocVerbatim::width(), and writeDiaGraphFromFile().
writeDotFile()
void DocbookDocVisitor::writeDotFile (const QCString & fileName, DocVerbatim * s) private
Definition at line 1347 of file docbookvisitor.cpp.
References DocVerbatim::children(), Config_getString, GOF_BITMAP, DocVerbatim::hasCaption(), DocVerbatim::height(), m_t, visitCaption(), visitPostEnd(), visitPreStart(), DocVerbatim::width(), and writeDotGraphFromFile().
Referenced by visit().
writeMscFile()
void DocbookDocVisitor::writeMscFile (const QCString & fileName, DocVerbatim * s) private
Definition at line 1242 of file docbookvisitor.cpp.
References DocVerbatim::children(), Config_getString, DocVerbatim::hasCaption(), DocVerbatim::height(), m_t, MSC_BITMAP, visitCaption(), visitPostEnd(), visitPreStart(), DocVerbatim::width(), and writeMscGraphFromFile().
Referenced by visit().
writePlantUMLFile()
void DocbookDocVisitor::writePlantUMLFile (const QCString & fileName, DocVerbatim * s) private
Definition at line 1257 of file docbookvisitor.cpp.
References DocVerbatim::children(), Config_getString, generatePlantUMLOutput(), DocVerbatim::hasCaption(), DocVerbatim::height(), m_t, PUML_BITMAP, visitCaption(), visitPostEnd(), visitPreStart(), and DocVerbatim::width().
Referenced by visit().
Member Data Documentation
m_ci
CodeOutputInterface& DocbookDocVisitor::m_ci private
Definition at line 164 of file docbookvisitor.h.
Referenced by visit().
m_enabled
QStack<bool> DocbookDocVisitor::m_enabled private
Definition at line 167 of file docbookvisitor.h.
Referenced by popEnabled(), and pushEnabled().
m_hide
bool DocbookDocVisitor::m_hide private
Definition at line 166 of file docbookvisitor.h.
Referenced by endDiaFile(), endDotFile(), endMscFile(), popEnabled(), pushEnabled(), visit(), visitPost(), and visitPre().
m_insidePre
bool DocbookDocVisitor::m_insidePre private
Definition at line 165 of file docbookvisitor.h.
Referenced by visit(), and visitPre().
m_langExt
QCString DocbookDocVisitor::m_langExt private
Definition at line 168 of file docbookvisitor.h.
Referenced by visit().
m_t
FTextStream& DocbookDocVisitor::m_t private
Definition at line 163 of file docbookvisitor.h.
Referenced by endDiaFile(), endDotFile(), endLink(), endMscFile(), filter(), startDiaFile(), startDotFile(), startLink(), startMscFile(), visit(), visitPost(), visitPre(), writeDiaFile(), writeDotFile(), writeMscFile(), and writePlantUMLFile().
The documentation for this class was generated from the following files:
src/docbookvisitor.h
src/docbookvisitor.cpp