Doxygen: SymbolIndexContext Class Reference
SymbolIndexContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static SymbolIndexContext * alloc (const SearchIndexList *sl, const QCString &name)
Private Member Functions
SymbolIndexContext (const SearchIndexList *sl, const QCString &name)
~SymbolIndexContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1266 of file context.h.
Constructor & Destructor Documentation
SymbolIndexContext()
SymbolIndexContext::SymbolIndexContext (const SearchIndexList * sl, const QCString & name) private
Definition at line 9788 of file context.cpp.
References p, and Private.
Referenced by alloc().
~SymbolIndexContext()
SymbolIndexContext::~SymbolIndexContext () private
Definition at line 9794 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int SymbolIndexContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 1274 of file context.h.
References RefCountedContext::addRef().
alloc()
static SymbolIndexContext* SymbolIndexContext::alloc (const SearchIndexList * sl, const QCString & name) inline static
Definition at line 1269 of file context.h.
References SymbolIndexContext().
Referenced by SymbolIndicesContext::Private::Private().
get()
TemplateVariant SymbolIndexContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 9799 of file context.cpp.
References SymbolIndexContext::Private::get(), and p.
release()
virtual int SymbolIndexContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 1275 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* SymbolIndexContext::p private
Definition at line 1280 of file context.h.
Referenced by get(), SymbolIndexContext(), and ~SymbolIndexContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp