Doxygen: TextGeneratorOLImpl Class Reference
TextGeneratorOLImpl Class Reference
Implements TextGeneratorIntf for an OutputDocInterface stream.
#include <util.h>
Public Member Functions
virtual ~TextGeneratorOLImpl ()
TextGeneratorOLImpl (OutputDocInterface &od)
void writeString (const char *s, bool keepSpaces) const
void writeBreak (int indent) const
void writeLink (const char *extRef, const char *file, const char *anchor, const char *text) const
Public Member Functions inherited from TextGeneratorIntf
virtual ~TextGeneratorIntf ()
Private Attributes
OutputDocInterface & m_od
Detailed Description
Implements TextGeneratorIntf for an OutputDocInterface stream.
Definition at line 77 of file util.h.
Constructor & Destructor Documentation
~TextGeneratorOLImpl()
virtual TextGeneratorOLImpl::~TextGeneratorOLImpl () inline virtual
Definition at line 80 of file util.h.
TextGeneratorOLImpl()
TextGeneratorOLImpl::TextGeneratorOLImpl (OutputDocInterface & od)
Definition at line 97 of file util.cpp.
Member Function Documentation
writeBreak()
void TextGeneratorOLImpl::writeBreak (int indent) const virtual
Implements TextGeneratorIntf.
Definition at line 126 of file util.cpp.
References BaseOutputDocInterface::lineBreak(), m_od, and BaseOutputDocInterface::writeNonBreakableSpace().
writeLink()
void TextGeneratorOLImpl::writeLink (const char * extRef, const char * file, const char * anchor, const char * text) const virtual
Implements TextGeneratorIntf.
Definition at line 136 of file util.cpp.
References m_od, and BaseOutputDocInterface::writeObjectLink().
writeString()
void TextGeneratorOLImpl::writeString (const char * s, bool keepSpaces) const virtual
Implements TextGeneratorIntf.
Definition at line 101 of file util.cpp.
References BaseOutputDocInterface::docify(), m_od, and BaseOutputDocInterface::writeNonBreakableSpace().
Member Data Documentation
m_od
OutputDocInterface& TextGeneratorOLImpl::m_od private
Definition at line 88 of file util.h.
Referenced by writeBreak(), writeLink(), and writeString().
The documentation for this class was generated from the following files:
src/util.h
src/util.cpp