Doxygen: TemplateNodeExtend Class Reference
TemplateNodeExtend Class Reference
Class representing a 'extend' tag in a template.
Public Member Functions
TemplateNodeExtend (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeExtend ()
void render (FTextStream &ts, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeExtend >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Private Attributes
ExprAst * m_extendExpr
TemplateNodeList m_nodes
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeExtend >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeExtend >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeExtend >
QCString m_templateName
int m_line
Detailed Description
Class representing a 'extend' tag in a template.
Definition at line 3459 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeExtend()
TemplateNodeExtend::TemplateNodeExtend (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 3462 of file template.cpp.
References m_extendExpr, m_nodes, TemplateNodeCreator< TemplateNodeExtend >::m_templateName, TemplateParser::parse(), ExpressionParser::parse(), TRACE, and TemplateParser::warn().
~TemplateNodeExtend()
TemplateNodeExtend::~TemplateNodeExtend () inline
Definition at line 3476 of file template.cpp.
References m_extendExpr.
Member Function Documentation
render()
void TemplateNodeExtend::render (FTextStream & ts, TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 3481 of file template.cpp.
References TemplateBlockContext::add(), TemplateContextImpl::blockContext(), TemplateBlockContext::clear(), TemplateImpl::engine(), TemplateNodeCreator< TemplateNodeExtend >::getTemplate(), TemplateEngine::loadByName(), m_extendExpr, TemplateNodeCreator< TemplateNodeExtend >::m_line, m_nodes, TemplateNodeCreator< TemplateNodeExtend >::m_templateName, msg(), TemplateImpl::render(), TemplateNodeMsg::render(), ExprAst::resolve(), TemplateContextImpl::setLocation(), TemplateVariant::toString(), TemplateEngine::unload(), and TemplateContextImpl::warn().
Member Data Documentation
m_extendExpr
ExprAst* TemplateNodeExtend::m_extendExpr private
Definition at line 3537 of file template.cpp.
Referenced by render(), TemplateNodeExtend(), and ~TemplateNodeExtend().
m_nodes
TemplateNodeList TemplateNodeExtend::m_nodes private
Definition at line 3538 of file template.cpp.
Referenced by render(), and TemplateNodeExtend().
The documentation for this class was generated from the following file:
src/template.cpp