Doxygen: FileStorage Class Reference
FileStorage Class Reference
Store implementation based on a file.
#include <filestorage.h>
Public Member Functions
FileStorage ()
FileStorage (const QString &name)
int read (char *buf, uint size)
int write (const char *buf, uint size)
bool open (int m)
bool seek (int64 pos)
int64 pos () const
void close ()
void setName (const char *name)
Public Member Functions inherited from StorageIntf
virtual ~StorageIntf ()
Private Attributes
bool m_readOnly
QFile m_file
Detailed Description
Store implementation based on a file.
Writing is linear, after that the file is re-opened for reading. Reading is random (seek+read).
Definition at line 28 of file filestorage.h.
Constructor & Destructor Documentation
FileStorage() [1/2]
FileStorage::FileStorage () inline
Definition at line 31 of file filestorage.h.
FileStorage() [2/2]
FileStorage::FileStorage (const QString & name) inline
Definition at line 32 of file filestorage.h.
References m_file.
Member Function Documentation
close()
void FileStorage::close () inline
Definition at line 39 of file filestorage.h.
References m_file.
Referenced by parseInput().
open()
bool FileStorage::open (int m) inline
Definition at line 36 of file filestorage.h.
References m_file, and m_readOnly.
Referenced by parseInput().
pos()
int64 FileStorage::pos () const inline
Definition at line 38 of file filestorage.h.
References m_file.
Referenced by EntryNav::saveEntry().
read()
int FileStorage::read (char * buf, uint size) inline virtual
Read size bytes from the store into buf.
Implements StorageIntf.
Definition at line 34 of file filestorage.h.
References m_file.
seek()
bool FileStorage::seek (int64 pos) inline
Definition at line 37 of file filestorage.h.
References m_file.
Referenced by EntryNav::loadEntry().
setName()
void FileStorage::setName (const char * name) inline
Definition at line 40 of file filestorage.h.
References m_file.
Referenced by parseInput().
write()
int FileStorage::write (const char * buf, uint size) inline virtual
Write size bytes from buf into the store.
Implements StorageIntf.
Definition at line 35 of file filestorage.h.
References m_file, and m_readOnly.
Member Data Documentation
m_file
QFile FileStorage::m_file private
Definition at line 43 of file filestorage.h.
Referenced by close(), FileStorage(), open(), pos(), read(), seek(), setName(), and write().
m_readOnly
bool FileStorage::m_readOnly private
Definition at line 42 of file filestorage.h.
Referenced by open(), and write().
The documentation for this class was generated from the following file:
src/filestorage.h