Doxygen: TemplateEngine::Private Class Reference
TemplateEngine::Private Class Reference
Private data of the template engine.
Classes
class IncludeEntry
Public Member Functions
Private (TemplateEngine *engine)
Template * loadByName (const QCString &fileName, int line)
void unload (Template *)
void enterBlock (const QCString &fileName, const QCString &blockName, int line)
void leaveBlock ()
void printIncludeContext (const char *fileName, int line) const
void setOutputExtension (const char *extension)
QCString outputExtension () const
void setTemplateDir (const char *dirName)
Private Attributes
QDict< Template > m_templateCache
TemplateEngine * m_engine
QList< IncludeEntry > m_includeStack
QCString m_extension
QCString m_templateDirName
Detailed Description
Private data of the template engine.
Definition at line 5059 of file template.cpp.
Constructor & Destructor Documentation
Private()
TemplateEngine::Private::Private (TemplateEngine * engine) inline
Definition at line 5079 of file template.cpp.
References m_includeStack, and m_templateCache.
Member Function Documentation
enterBlock()
void TemplateEngine::Private::enterBlock (const QCString & fileName, const QCString & blockName, int line) inline
Definition at line 5130 of file template.cpp.
References TemplateEngine::Private::IncludeEntry::Block, and m_includeStack.
Referenced by TemplateEngine::enterBlock().
leaveBlock()
void TemplateEngine::Private::leaveBlock () inline
Definition at line 5138 of file template.cpp.
References m_includeStack.
Referenced by TemplateEngine::leaveBlock().
loadByName()
Template* TemplateEngine::Private::loadByName (const QCString & fileName, int line) inline
Definition at line 5084 of file template.cpp.
References err(), ResourceMgr::getAsString(), ResourceMgr::instance(), m_engine, m_extension, m_includeStack, m_templateCache, m_templateDirName, and TemplateEngine::Private::IncludeEntry::Template.
Referenced by TemplateEngine::loadByName().
outputExtension()
QCString TemplateEngine::Private::outputExtension () const inline
Definition at line 5175 of file template.cpp.
References m_extension.
Referenced by TemplateEngine::outputExtension().
printIncludeContext()
void TemplateEngine::Private::printIncludeContext (const char * fileName, int line) const inline
Definition at line 5146 of file template.cpp.
References TemplateEngine::Private::IncludeEntry::blockName(), TemplateEngine::Private::IncludeEntry::fileName(), TemplateEngine::Private::IncludeEntry::line(), m_includeStack, TemplateEngine::Private::IncludeEntry::Template, TemplateEngine::Private::IncludeEntry::type(), and warn().
Referenced by TemplateEngine::printIncludeContext().
setOutputExtension()
void TemplateEngine::Private::setOutputExtension (const char * extension) inline
Definition at line 5170 of file template.cpp.
References m_extension.
Referenced by TemplateEngine::setOutputExtension().
setTemplateDir()
void TemplateEngine::Private::setTemplateDir (const char * dirName) inline
Definition at line 5180 of file template.cpp.
References m_templateDirName.
Referenced by TemplateEngine::setTemplateDir().
unload()
void TemplateEngine::Private::unload (Template *) inline
Definition at line 5121 of file template.cpp.
References m_includeStack.
Referenced by TemplateEngine::unload().
Member Data Documentation
m_engine
TemplateEngine* TemplateEngine::Private::m_engine private
Definition at line 5188 of file template.cpp.
Referenced by loadByName().
m_extension
QCString TemplateEngine::Private::m_extension private
Definition at line 5190 of file template.cpp.
Referenced by loadByName(), outputExtension(), and setOutputExtension().
m_includeStack
QList<IncludeEntry> TemplateEngine::Private::m_includeStack private
Definition at line 5189 of file template.cpp.
Referenced by enterBlock(), leaveBlock(), loadByName(), printIncludeContext(), Private(), and unload().
m_templateCache
QDict<Template> TemplateEngine::Private::m_templateCache private
Definition at line 5186 of file template.cpp.
Referenced by loadByName(), and Private().
m_templateDirName
QCString TemplateEngine::Private::m_templateDirName private
Definition at line 5191 of file template.cpp.
Referenced by loadByName(), and setTemplateDir().
The documentation for this class was generated from the following file:
src/template.cpp