Doxygen: DotManager Class Reference
DotManager Class Reference
Singleton that manages dot relation actions.
#include <dot.h>
Public Member Functions
void addRun (DotRunner *run)
int addMap (const QCString &file, const QCString &mapFile, const QCString &relPath, bool urlOnly, const QCString &context, const QCString &label)
int addFigure (const QCString &file, const QCString &baseName, const QCString &figureName, bool heightCheck)
int addSVGConversion (const QCString &file, const QCString &relPath, bool urlOnly, const QCString &context, bool zoomable, int graphId)
int addSVGObject (const QCString &file, const QCString &baseName, const QCString &figureNAme, const QCString &relPath)
bool run ()
Static Public Member Functions
static DotManager * instance ()
Private Member Functions
DotManager ()
virtual ~DotManager ()
Private Attributes
QList< DotRunner > m_dotRuns
SDict< DotFilePatcher > m_dotMaps
DotRunnerQueue * m_queue
QList< DotWorkerThread > m_workers
Static Private Attributes
static DotManager * m_theInstance = 0
Detailed Description
Singleton that manages dot relation actions.
Definition at line 462 of file dot.h.
Constructor & Destructor Documentation
DotManager()
DotManager::DotManager () private
Definition at line 1188 of file dot.cpp.
References Config_getInt, m_dotMaps, m_dotRuns, m_queue, m_workers, and SDict< T >::setAutoDelete().
Referenced by instance().
~DotManager()
DotManager::~DotManager () private virtual
Definition at line 1215 of file dot.cpp.
References m_queue.
Member Function Documentation
addFigure()
int DotManager::addFigure (const QCString & file, const QCString & baseName, const QCString & figureName, bool heightCheck)
Definition at line 1238 of file dot.cpp.
References DotFilePatcher::addFigure(), SDict< T >::append(), SDict< T >::find(), and m_dotMaps.
Referenced by DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), and DotGroupCollaboration::writeGraph().
addMap()
int DotManager::addMap (const QCString & file, const QCString & mapFile, const QCString & relPath, bool urlOnly, const QCString & context, const QCString & label)
Definition at line 1225 of file dot.cpp.
References DotFilePatcher::addMap(), SDict< T >::append(), SDict< T >::find(), and m_dotMaps.
Referenced by DotGfxHierarchyTable::createGraph(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), and DotGroupCollaboration::writeGraph().
addRun()
void DotManager::addRun (DotRunner * run)
Definition at line 1220 of file dot.cpp.
References m_dotRuns.
Referenced by DotGfxHierarchyTable::createGraph(), generateGraphLegend(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), and DotGroupCollaboration::writeGraph().
addSVGConversion()
int DotManager::addSVGConversion (const QCString & file, const QCString & relPath, bool urlOnly, const QCString & context, bool zoomable, int graphId)
Definition at line 1250 of file dot.cpp.
References DotFilePatcher::addSVGConversion(), SDict< T >::append(), SDict< T >::find(), and m_dotMaps.
Referenced by DotGfxHierarchyTable::createGraph(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), and DotGroupCollaboration::writeGraph().
addSVGObject()
int DotManager::addSVGObject (const QCString & file, const QCString & baseName, const QCString & figureNAme, const QCString & relPath)
Definition at line 1263 of file dot.cpp.
References DotFilePatcher::addSVGObject(), SDict< T >::append(), SDict< T >::find(), and m_dotMaps.
Referenced by DotGfxHierarchyTable::createGraph(), generateGraphLegend(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), and DotGroupCollaboration::writeGraph().
instance()
DotManager * DotManager::instance () static
Definition at line 1179 of file dot.cpp.
References DotManager(), and m_theInstance.
Referenced by DotGfxHierarchyTable::createGraph(), generateGraphLegend(), generateOutput(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), and DotGroupCollaboration::writeGraph().
run()
bool DotManager::run ()
Definition at line 1275 of file dot.cpp.
References Config_getBool, Config_getString, SDict< T >::count(), DotRunnerQueue::count(), DotRunnerQueue::enqueue(), DotFilePatcher::file(), m_dotMaps, m_dotRuns, m_queue, m_workers, msg(), portable_sleep(), portable_sysTimerStart(), portable_sysTimerStop(), DotRunner::run(), DotFilePatcher::run(), setDotFontPath(), and unsetDotFontPath().
Referenced by generateOutput().
Member Data Documentation
m_dotMaps
SDict<DotFilePatcher> DotManager::m_dotMaps private
Definition at line 482 of file dot.h.
Referenced by addFigure(), addMap(), addSVGConversion(), addSVGObject(), DotManager(), and run().
m_dotRuns
QList<DotRunner> DotManager::m_dotRuns private
Definition at line 481 of file dot.h.
Referenced by addRun(), DotManager(), and run().
m_queue
DotRunnerQueue* DotManager::m_queue private
Definition at line 484 of file dot.h.
Referenced by DotManager(), run(), and ~DotManager().
m_theInstance
DotManager * DotManager::m_theInstance = 0 static private
Definition at line 483 of file dot.h.
Referenced by instance().
m_workers
QList<DotWorkerThread> DotManager::m_workers private
Definition at line 485 of file dot.h.
Referenced by DotManager(), and run().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp