Doxygen: NamespaceTreeContext::Private Class Reference
NamespaceTreeContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private ()
TemplateVariant get (const char *n) const
TemplateVariant tree () const
TemplateVariant fileName () const
TemplateVariant relPath () const
TemplateVariant highlight () const
TemplateVariant subhighlight () const
TemplateVariant title () const
TemplateVariant maxDepth () const
TemplateVariant preferredDepth () const
Private Attributes
SharedPtr< NestingContext > m_namespaceTree
Cachable m_cache
Static Private Attributes
static PropertyMapper< NamespaceTreeContext::Private > s_inst
Detailed Description
Definition at line 6892 of file context.cpp.
Constructor & Destructor Documentation
Private()
NamespaceTreeContext::Private::Private () inline
Definition at line 6895 of file context.cpp.
References NestingContext::addNamespaces(), PropertyMapper< T >::addProperty(), NestingContext::alloc(), fileName(), highlight(), Config::init(), m_namespaceTree, maxDepth(), Doxygen::namespaceSDict, preferredDepth(), relPath(), SharedPtr< T >::reset(), s_inst, subhighlight(), title(), and tree().
Member Function Documentation
fileName()
TemplateVariant NamespaceTreeContext::Private::fileName () const inline
Definition at line 6925 of file context.cpp.
Referenced by Private().
get()
TemplateVariant NamespaceTreeContext::Private::get (const char * n) const inline
Definition at line 6917 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by NamespaceTreeContext::get().
highlight()
TemplateVariant NamespaceTreeContext::Private::highlight () const inline
Definition at line 6933 of file context.cpp.
Referenced by Private().
maxDepth()
TemplateVariant NamespaceTreeContext::Private::maxDepth () const inline
Definition at line 6959 of file context.cpp.
References computeMaxDepth(), SharedPtr< T >::get(), m_cache, m_namespaceTree, NamespaceTreeContext::Private::Cachable::maxDepth, and NamespaceTreeContext::Private::Cachable::maxDepthComputed.
Referenced by preferredDepth(), and Private().
preferredDepth()
TemplateVariant NamespaceTreeContext::Private::preferredDepth () const inline
Definition at line 6968 of file context.cpp.
References computePreferredDepth(), SharedPtr< T >::get(), m_cache, m_namespaceTree, maxDepth(), NamespaceTreeContext::Private::Cachable::preferredDepth, NamespaceTreeContext::Private::Cachable::preferredDepthComputed, and TemplateVariant::toInt().
Referenced by Private().
relPath()
TemplateVariant NamespaceTreeContext::Private::relPath () const inline
Definition at line 6929 of file context.cpp.
Referenced by Private().
subhighlight()
TemplateVariant NamespaceTreeContext::Private::subhighlight () const inline
Definition at line 6937 of file context.cpp.
Referenced by Private().
title()
TemplateVariant NamespaceTreeContext::Private::title () const inline
Definition at line 6941 of file context.cpp.
References Config_getBool, theTranslator, Translator::trModulesList(), Translator::trNamespaceList(), and Translator::trPackages().
Referenced by Private().
tree()
TemplateVariant NamespaceTreeContext::Private::tree () const inline
Definition at line 6921 of file context.cpp.
References SharedPtr< T >::get(), and m_namespaceTree.
Referenced by Private().
Member Data Documentation
m_cache
Cachable NamespaceTreeContext::Private::m_cache mutable private
Definition at line 6987 of file context.cpp.
Referenced by maxDepth(), and preferredDepth().
m_namespaceTree
SharedPtr<NestingContext> NamespaceTreeContext::Private::m_namespaceTree private
Definition at line 6978 of file context.cpp.
Referenced by maxDepth(), preferredDepth(), Private(), and tree().
s_inst
PropertyMapper< NamespaceTreeContext::Private > NamespaceTreeContext::Private::s_inst static private
Definition at line 6988 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp