Doxygen: ScopedPtr< T > Class Template Reference
ScopedPtr< T > Class Template Reference
Scoped smart pointer.
Public Types
typedef T Type
Public Member Functions
ScopedPtr (T *p=0)
~ScopedPtr ()
T & operator* () const
T * operator-> () const
T * get () const
operator bool () const
void reset (T *p=0)
Private Member Functions
ScopedPtr (const ScopedPtr &)
ScopedPtr & operator= (const ScopedPtr &)
void operator== (const ScopedPtr &) const
void operator!= (const ScopedPtr &) const
Private Attributes
T * m_ptr
Detailed Description
template<class T>
class ScopedPtr< T >
Scoped smart pointer.
Definition at line 75 of file context.cpp.
Member Typedef Documentation
Type
template<class T> typedef T ScopedPtr< T >::Type
Definition at line 85 of file context.cpp.
Constructor & Destructor Documentation
ScopedPtr() [1/2]
template<class T> ScopedPtr< T >::ScopedPtr (const ScopedPtr< T > &) private
ScopedPtr() [2/2]
template<class T> ScopedPtr< T >::ScopedPtr (T * p = 0) inline explicit
Definition at line 86 of file context.cpp.
~ScopedPtr()
template<class T> ScopedPtr< T >::~ScopedPtr () inline
Definition at line 87 of file context.cpp.
Member Function Documentation
get()
template<class T> T* ScopedPtr< T >::get () const inline
Definition at line 90 of file context.cpp.
Referenced by MemberContext::Private::getCallerGraph(), MemberContext::Private::getCallGraph(), ClassContext::Private::getClassGraph(), ClassContext::Private::getCollaborationGraph(), DirContext::Private::getDirDepsGraph(), ModuleContext::Private::getGroupGraph(), ClassHierarchyContext::Private::getHierarchy(), FileContext::Private::getIncludedByGraph(), and FileContext::Private::getIncludeGraph().
operator bool()
template<class T> ScopedPtr< T >::operator bool () const inline
Definition at line 91 of file context.cpp.
operator!=()
template<class T> void ScopedPtr< T >::operator!= (const ScopedPtr< T > &) const private
operator*()
template<class T> T& ScopedPtr< T >::operator* () const inline
Definition at line 88 of file context.cpp.
operator->()
template<class T> T* ScopedPtr< T >::operator-> () const inline
Definition at line 89 of file context.cpp.
operator=()
template<class T> ScopedPtr& ScopedPtr< T >::operator= (const ScopedPtr< T > &) private
operator==()
template<class T> void ScopedPtr< T >::operator== (const ScopedPtr< T > &) const private
reset()
template<class T> void ScopedPtr< T >::reset (T * p = 0) inline
Definition at line 92 of file context.cpp.
Referenced by NestingNodeContext::Private::brief(), MemberGroupInfoContext::Private::docs(), ArgumentContext::Private::docs(), PageContext::Private::example(), MemberContext::Private::getCallerGraph(), MemberContext::Private::getCallGraph(), ClassContext::Private::getClassGraph(), ClassContext::Private::getCollaborationGraph(), DirContext::Private::getDirDepsGraph(), ModuleContext::Private::getGroupGraph(), ClassHierarchyContext::Private::getHierarchy(), FileContext::Private::getIncludedByGraph(), FileContext::Private::getIncludeGraph(), MemberContext::Private::paramDocs(), and FileContext::Private::sources().
Member Data Documentation
m_ptr
template<class T> T* ScopedPtr< T >::m_ptr private
Definition at line 78 of file context.cpp.
Referenced by ScopedPtr< DotDirDeps >::get(), ScopedPtr< DotDirDeps >::operator*(), ScopedPtr< DotDirDeps >::operator->(), ScopedPtr< DotDirDeps >::reset(), and ScopedPtr< DotDirDeps >::~ScopedPtr().
The documentation for this class was generated from the following file:
src/context.cpp