Doxygen: AllMembersListContext Class Reference
AllMembersListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static AllMembersListContext * alloc ()
static AllMembersListContext * alloc (const MemberNameInfoSDict *ml)
Private Member Functions
AllMembersListContext ()
AllMembersListContext (const MemberNameInfoSDict *ml)
~AllMembersListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1113 of file context.h.
Constructor & Destructor Documentation
AllMembersListContext() [1/2]
AllMembersListContext::AllMembersListContext () private
Definition at line 8696 of file context.cpp.
References p, and Private.
Referenced by alloc().
AllMembersListContext() [2/2]
AllMembersListContext::AllMembersListContext (const MemberNameInfoSDict * ml) private
Definition at line 8701 of file context.cpp.
References p, and Private.
~AllMembersListContext()
AllMembersListContext::~AllMembersListContext () private
Definition at line 8706 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int AllMembersListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 1125 of file context.h.
References RefCountedContext::addRef().
alloc() [1/2]
static AllMembersListContext* AllMembersListContext::alloc () inline static
Definition at line 1116 of file context.h.
References AllMembersListContext().
Referenced by ClassContext::Private::allMembersList().
alloc() [2/2]
static AllMembersListContext* AllMembersListContext::alloc (const MemberNameInfoSDict * ml) inline static
Definition at line 1118 of file context.h.
References AllMembersListContext().
at()
TemplateVariant AllMembersListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 8717 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int AllMembersListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 8712 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * AllMembersListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 8722 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int AllMembersListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 1126 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* AllMembersListContext::p private
Definition at line 1132 of file context.h.
Referenced by AllMembersListContext(), at(), count(), createIterator(), and ~AllMembersListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp