Doxygen: SearchIndexExternal Class Reference
SearchIndexExternal Class Reference
#include <searchindex.h>
Classes
struct Private
Public Member Functions
SearchIndexExternal ()
~SearchIndexExternal ()
void setCurrentDoc (Definition *ctx, const char *anchor, bool isSourceFile)
void addWord (const char *word, bool hiPriority)
void write (const char *file)
Public Member Functions inherited from SearchIndexIntf
SearchIndexIntf (Kind k)
virtual ~SearchIndexIntf ()
Kind kind () const
Private Attributes
Private * p
Additional Inherited Members
Public Types inherited from SearchIndexIntf
enum Kind { Internal, External }
Detailed Description
Definition at line 100 of file searchindex.h.
Constructor & Destructor Documentation
SearchIndexExternal()
SearchIndexExternal::SearchIndexExternal ()
Definition at line 432 of file searchindex.cpp.
References SearchIndexExternal::Private::current, SearchIndexExternal::Private::docEntries, p, Private, and SDict< T >::setAutoDelete().
~SearchIndexExternal()
SearchIndexExternal::~SearchIndexExternal ()
Definition at line 439 of file searchindex.cpp.
References p.
Member Function Documentation
addWord()
void SearchIndexExternal::addWord (const char * word, bool hiPriority) virtual
Implements SearchIndexIntf.
Definition at line 527 of file searchindex.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), SearchIndexExternal::Private::current, GrowBuf::getPos(), SearchDocEntry::importantText, isId(), SearchDocEntry::normalText, and p.
setCurrentDoc()
void SearchIndexExternal::setCurrentDoc (Definition * ctx, const char * anchor, bool isSourceFile) virtual
Implements SearchIndexIntf.
Definition at line 500 of file searchindex.cpp.
References SDict< T >::append(), SearchDocEntry::args, Config_getString, SearchIndexExternal::Private::current, definitionToName(), SearchIndexExternal::Private::docEntries, SearchDocEntry::extId, SDict< T >::find(), Doxygen::htmlFileExtension, SearchDocEntry::name, p, stripPath(), SearchDocEntry::type, DefinitionIntf::TypeMember, and SearchDocEntry::url.
write()
void SearchIndexExternal::write (const char * file) virtual
Implements SearchIndexIntf.
Definition at line 536 of file searchindex.cpp.
References GrowBuf::addChar(), SearchDocEntry::args, convertToXML(), doc, SearchIndexExternal::Private::docEntries, endl(), err(), SearchDocEntry::extId, GrowBuf::get(), SearchDocEntry::importantText, SearchDocEntry::name, SearchDocEntry::normalText, p, SearchDocEntry::type, and SearchDocEntry::url.
Member Data Documentation
p
Private* SearchIndexExternal::p private
Definition at line 110 of file searchindex.h.
Referenced by addWord(), SearchIndexExternal(), setCurrentDoc(), write(), and ~SearchIndexExternal().
The documentation for this class was generated from the following files:
src/searchindex.h
src/searchindex.cpp