Doxygen: HtmlDocVisitor Class Reference
HtmlDocVisitor Class Reference
Concrete visitor implementation for HTML output.
#include <htmldocvisitor.h>
Public Member Functions
HtmlDocVisitor (FTextStream &t, CodeOutputInterface &ci, Definition *ctx)
void visit (DocWord *)
void visit (DocLinkedWord *)
void visit (DocWhiteSpace *)
void visit (DocSymbol *)
void visit (DocURL *)
void visit (DocLineBreak *)
void visit (DocHorRuler *)
void visit (DocStyleChange *)
void visit (DocVerbatim *)
void visit (DocAnchor *)
void visit (DocInclude *)
void visit (DocIncOperator *)
void visit (DocFormula *)
void visit (DocIndexEntry *)
void visit (DocSimpleSectSep *)
void visit (DocCite *)
void visitPre (DocAutoList *)
void visitPost (DocAutoList *)
void visitPre (DocAutoListItem *)
void visitPost (DocAutoListItem *)
void visitPre (DocPara *)
void visitPost (DocPara *)
void visitPre (DocRoot *)
void visitPost (DocRoot *)
void visitPre (DocSimpleSect *)
void visitPost (DocSimpleSect *)
void visitPre (DocTitle *)
void visitPost (DocTitle *)
void visitPre (DocSimpleList *)
void visitPost (DocSimpleList *)
void visitPre (DocSimpleListItem *)
void visitPost (DocSimpleListItem *)
void visitPre (DocSection *)
void visitPost (DocSection *)
void visitPre (DocHtmlList *)
void visitPost (DocHtmlList *)
void visitPre (DocHtmlListItem *)
void visitPost (DocHtmlListItem *)
void visitPre (DocHtmlDescList *)
void visitPost (DocHtmlDescList *)
void visitPre (DocHtmlDescTitle *)
void visitPost (DocHtmlDescTitle *)
void visitPre (DocHtmlDescData *)
void visitPost (DocHtmlDescData *)
void visitPre (DocHtmlTable *)
void visitPost (DocHtmlTable *)
void visitPre (DocHtmlRow *)
void visitPost (DocHtmlRow *)
void visitPre (DocHtmlCell *)
void visitPost (DocHtmlCell *)
void visitPre (DocHtmlCaption *)
void visitPost (DocHtmlCaption *)
void visitPre (DocInternal *)
void visitPost (DocInternal *)
void visitPre (DocHRef *)
void visitPost (DocHRef *)
void visitPre (DocHtmlHeader *)
void visitPost (DocHtmlHeader *)
void visitPre (DocImage *)
void visitPost (DocImage *)
void visitPre (DocDotFile *)
void visitPost (DocDotFile *)
void visitPre (DocMscFile *)
void visitPost (DocMscFile *)
void visitPre (DocDiaFile *)
void visitPost (DocDiaFile *)
void visitPre (DocLink *)
void visitPost (DocLink *)
void visitPre (DocRef *)
void visitPost (DocRef *)
void visitPre (DocSecRefItem *)
void visitPost (DocSecRefItem *)
void visitPre (DocSecRefList *)
void visitPost (DocSecRefList *)
void visitPre (DocParamSect *)
void visitPost (DocParamSect *)
void visitPre (DocParamList *)
void visitPost (DocParamList *)
void visitPre (DocXRefItem *)
void visitPost (DocXRefItem *)
void visitPre (DocInternalRef *)
void visitPost (DocInternalRef *)
void visitPre (DocCopy *)
void visitPost (DocCopy *)
void visitPre (DocText *)
void visitPost (DocText *)
void visitPre (DocHtmlBlockQuote *)
void visitPost (DocHtmlBlockQuote *)
void visitPre (DocVhdlFlow *)
void visitPost (DocVhdlFlow *)
void visitPre (DocParBlock *)
void visitPost (DocParBlock *)
Public Member Functions inherited from DocVisitor
DocVisitor (int id)
virtual ~DocVisitor ()
int id () const
Private Member Functions
void writeObfuscatedMailAddress (const QCString &url)
void filter (const char *str)
void filterQuotedCdataAttr (const char *str)
Escape basic entities to produce a valid CDATA attribute value, assume that the outer quoting will be using the double quote ".
void startLink (const QCString &ref, const QCString &file, const QCString &relPath, const QCString &anchor, const QCString &tooltip="")
void endLink ()
void writeDotFile (const QCString &fileName, const QCString &relPath, const QCString &context)
void writeMscFile (const QCString &fileName, const QCString &relPath, const QCString &context)
void writeDiaFile (const QCString &fileName, const QCString &relPath, const QCString &context)
void writePlantUMLFile (const QCString &fileName, const QCString &relPath, const QCString &context)
void pushEnabled ()
void popEnabled ()
void forceEndParagraph (DocNode *n)
Used for items found inside a paragraph, which due to XHTML restrictions have to be outside of the paragraph.
void forceStartParagraph (DocNode *n)
Used for items found inside a paragraph, which due to XHTML restrictions have to be outside of the paragraph.
Private Attributes
FTextStream & m_t
CodeOutputInterface & m_ci
bool m_insidePre
bool m_hide
QStack< bool > m_enabled
Definition * m_ctx
QCString m_langExt
Detailed Description
Concrete visitor implementation for HTML output.
Definition at line 33 of file htmldocvisitor.h.
Constructor & Destructor Documentation
HtmlDocVisitor()
HtmlDocVisitor::HtmlDocVisitor (FTextStream & t, CodeOutputInterface & ci, Definition * ctx)
Definition at line 149 of file htmldocvisitor.cpp.
References Definition::getDefFileExtension(), and m_langExt.
Member Function Documentation
endLink()
void HtmlDocVisitor::endLink () private
Definition at line 1985 of file htmldocvisitor.cpp.
References m_t.
Referenced by visit(), and visitPost().
filter()
void HtmlDocVisitor::filter (const char * str) private
Definition at line 1923 of file htmldocvisitor.cpp.
References m_t.
Referenced by visit(), and visitPre().
filterQuotedCdataAttr()
void HtmlDocVisitor::filterQuotedCdataAttr (const char * str) private
Escape basic entities to produce a valid CDATA attribute value, assume that the outer quoting will be using the double quote ".
Definition at line 1943 of file htmldocvisitor.cpp.
References m_t.
Referenced by visit().
forceEndParagraph()
void HtmlDocVisitor::forceEndParagraph (DocNode * n) private
Used for items found inside a paragraph, which due to XHTML restrictions have to be outside of the paragraph.
This method will forcefully end the current paragraph and forceStartParagraph() will restart it.
Definition at line 2138 of file htmldocvisitor.cpp.
References CompAccept< T >::children(), getParagraphContext(), insideStyleChangeThatIsOutsideParagraph(), DocNode::kind(), DocNode::Kind_Para, DocNode::Kind_WhiteSpace, m_t, mustBeOutsideParagraph(), and DocNode::parent().
Referenced by visit(), and visitPre().
forceStartParagraph()
void HtmlDocVisitor::forceStartParagraph (DocNode * n) private
Used for items found inside a paragraph, which due to XHTML restrictions have to be outside of the paragraph.
This method will forcefully start the paragraph, that was previously ended by forceEndParagraph().
Definition at line 2176 of file htmldocvisitor.cpp.
References CompAccept< T >::children(), getParagraphContext(), insideStyleChangeThatIsOutsideParagraph(), DocNode::kind(), DocNode::Kind_Para, DocNode::Kind_WhiteSpace, m_t, mustBeOutsideParagraph(), and DocNode::parent().
Referenced by visit(), and visitPost().
popEnabled()
void HtmlDocVisitor::popEnabled () private
Definition at line 1995 of file htmldocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit(), and visitPost().
pushEnabled()
void HtmlDocVisitor::pushEnabled () private
Definition at line 1990 of file htmldocvisitor.cpp.
References m_enabled, and m_hide.
Referenced by visit(), and visitPre().
startLink()
void HtmlDocVisitor::startLink (const QCString & ref, const QCString & file, const QCString & relPath, const QCString & anchor, const QCString & tooltip = "") private
Definition at line 1962 of file htmldocvisitor.cpp.
References convertToHtml(), externalLinkTarget(), externalRef(), Doxygen::htmlFileExtension, and m_t.
Referenced by visit(), and visitPre().
visit() [1/16]
void HtmlDocVisitor::visit (DocWord * w) virtual
Implements DocVisitor.
Definition at line 161 of file htmldocvisitor.cpp.
References filter(), m_hide, and DocWord::word().
Referenced by visitPre().
visit() [2/16]
void HtmlDocVisitor::visit (DocLinkedWord * w) virtual
Implements DocVisitor.
Definition at line 168 of file htmldocvisitor.cpp.
References DocLinkedWord::anchor(), endLink(), DocLinkedWord::file(), filter(), m_hide, DocLinkedWord::ref(), DocLinkedWord::relPath(), startLink(), DocLinkedWord::tooltip(), and DocLinkedWord::word().
visit() [3/16]
void HtmlDocVisitor::visit (DocWhiteSpace * w) virtual
Implements DocVisitor.
Definition at line 177 of file htmldocvisitor.cpp.
References DocWhiteSpace::chars(), m_hide, m_insidePre, and m_t.
visit() [4/16]
void HtmlDocVisitor::visit (DocSymbol * s) virtual
Implements DocVisitor.
Definition at line 190 of file htmldocvisitor.cpp.
References err(), HtmlEntityMapper::html(), HtmlEntityMapper::instance(), m_hide, m_t, and DocSymbol::symbol().
visit() [5/16]
void HtmlDocVisitor::visit (DocURL * u) virtual
Implements DocVisitor.
Definition at line 218 of file htmldocvisitor.cpp.
References filter(), DocURL::isEmail(), m_hide, m_t, DocURL::url(), and writeObfuscatedMailAddress().
visit() [6/16]
void HtmlDocVisitor::visit (DocLineBreak *) virtual
Implements DocVisitor.
Definition at line 244 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visit() [7/16]
void HtmlDocVisitor::visit (DocHorRuler * hr) virtual
Implements DocVisitor.
Definition at line 250 of file htmldocvisitor.cpp.
References forceEndParagraph(), forceStartParagraph(), m_hide, and m_t.
visit() [8/16]
void HtmlDocVisitor::visit (DocStyleChange * s) virtual
Implements DocVisitor.
Definition at line 258 of file htmldocvisitor.cpp.
References DocStyleChange::attribs(), DocStyleChange::Bold, DocStyleChange::Center, DocStyleChange::Code, DocStyleChange::Div, DocStyleChange::enable(), forceEndParagraph(), forceStartParagraph(), htmlAttribsToString(), DocStyleChange::Italic, m_hide, m_insidePre, m_t, DocStyleChange::Preformatted, DocStyleChange::Small, DocStyleChange::Span, DocStyleChange::style(), DocStyleChange::Subscript, and DocStyleChange::Superscript.
visit() [9/16]
void HtmlDocVisitor::visit (DocVerbatim * s) virtual
Implements DocVisitor.
Definition at line 353 of file htmldocvisitor.cpp.
References DocVerbatim::children(), DocVerbatim::Code, Config_getBool, Config_getString, DocVerbatim::context(), DocVerbatim::DocbookOnly, DocVerbatim::Dot, endl(), err(), DocVerbatim::exampleFile(), filter(), forceEndParagraph(), forceStartParagraph(), getLanguageFromFileName(), ParserManager::getParser(), DocVerbatim::HtmlOnly, DocVerbatim::isBlock(), DocVerbatim::isExample(), DocVerbatim::language(), DocVerbatim::LatexOnly, m_ci, m_ctx, m_hide, m_langExt, m_t, DocVerbatim::ManOnly, DocVerbatim::Msc, ParserInterface::parseCode(), Doxygen::parserManager, DocVerbatim::PlantUML, PREFRAG_END, PREFRAG_START, DocVerbatim::relPath(), DocVerbatim::RtfOnly, DocVerbatim::text(), DocVerbatim::type(), DocVerbatim::Verbatim, visitCaption(), visitPostCaption(), visitPreCaption(), writeDotFile(), writeMscFile(), writePlantUMLFile(), writePlantUMLSource(), and DocVerbatim::XmlOnly.
visit() [10/16]
void HtmlDocVisitor::visit (DocAnchor * anc) virtual
Implements DocVisitor.
Definition at line 493 of file htmldocvisitor.cpp.
References DocAnchor::anchor(), m_hide, and m_t.
visit() [11/16]
void HtmlDocVisitor::visit (DocInclude * inc) virtual
Implements DocVisitor.
Definition at line 499 of file htmldocvisitor.cpp.
References DocInclude::blockId(), DocInclude::context(), DocInclude::DontInclude, err(), DocInclude::exampleFile(), DocInclude::extension(), extractBlock(), DocInclude::file(), filter(), forceEndParagraph(), forceStartParagraph(), getLanguageFromFileName(), ParserManager::getParser(), DocInclude::HtmlInclude, DocInclude::Include, DocInclude::IncludeDoc, DocInclude::IncWithLines, DocInclude::isExample(), DocInclude::LatexInclude, lineBlock(), m_ci, m_ctx, m_hide, m_t, parseCode(), Doxygen::parserManager, PREFRAG_END, PREFRAG_START, DocInclude::Snippet, DocInclude::SnippetDoc, DocInclude::SnipWithLines, DocInclude::text(), DocInclude::type(), and DocInclude::VerbInclude.
visit() [12/16]
void HtmlDocVisitor::visit (DocIncOperator * op) virtual
Implements DocVisitor.
Definition at line 621 of file htmldocvisitor.cpp.
References DocIncOperator::context(), endl(), DocIncOperator::exampleFile(), getLanguageFromFileName(), ParserManager::getParser(), DocIncOperator::isExample(), DocIncOperator::isFirst(), DocIncOperator::isLast(), m_ci, m_ctx, m_hide, m_langExt, m_t, ParserInterface::parseCode(), Doxygen::parserManager, popEnabled(), PREFRAG_END, PREFRAG_START, pushEnabled(), DocIncOperator::Skip, DocIncOperator::text(), and DocIncOperator::type().
visit() [13/16]
void HtmlDocVisitor::visit (DocFormula * f) virtual
Implements DocVisitor.
Definition at line 668 of file htmldocvisitor.cpp.
References Config_getBool, convertToHtml(), endl(), filterQuotedCdataAttr(), forceEndParagraph(), forceStartParagraph(), DocFormula::isInline(), m_hide, m_t, DocFormula::name(), DocFormula::relPath(), and DocFormula::text().
visit() [14/16]
void HtmlDocVisitor::visit (DocIndexEntry * e) virtual
Implements DocVisitor.
Definition at line 714 of file htmldocvisitor.cpp.
References IndexList::addIndexItem(), MemberDef::anchor(), convertIndexWordToAnchor(), DocIndexEntry::entry(), Doxygen::indexList, m_t, DocIndexEntry::member(), and DocIndexEntry::scope().
visit() [15/16]
void HtmlDocVisitor::visit (DocSimpleSectSep *) virtual
Implements DocVisitor.
Definition at line 730 of file htmldocvisitor.cpp.
References endl(), and m_t.
visit() [16/16]
void HtmlDocVisitor::visit (DocCite * cite) virtual
Implements DocVisitor.
Definition at line 736 of file htmldocvisitor.cpp.
References DocCite::anchor(), endLink(), DocCite::file(), filter(), m_hide, m_t, DocCite::ref(), DocCite::relPath(), startLink(), and DocCite::text().
visitPost() [1/38]
void HtmlDocVisitor::visitPost (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 788 of file htmldocvisitor.cpp.
References forceStartParagraph(), DocAutoList::isEnumList(), DocNode::isPreformatted(), m_hide, and m_t.
visitPost() [2/38]
void HtmlDocVisitor::visitPost (DocAutoListItem * li) virtual
Implements DocVisitor.
Definition at line 810 of file htmldocvisitor.cpp.
References DocNode::isPreformatted(), m_hide, and m_t.
visitPost() [3/38]
void HtmlDocVisitor::visitPost (DocPara * p) virtual
Implements DocVisitor.
Definition at line 1066 of file htmldocvisitor.cpp.
References CompAccept< T >::children(), getParagraphContext(), DocNode::kind(), DocNode::Kind_AutoListItem, DocNode::Kind_Copy, DocNode::Kind_HtmlBlockQuote, DocNode::Kind_HtmlCell, DocNode::Kind_HtmlDescData, DocNode::Kind_HtmlListItem, DocNode::Kind_Internal, DocNode::Kind_ParBlock, DocNode::Kind_Root, DocNode::Kind_Section, DocNode::Kind_SimpleListItem, DocNode::Kind_SimpleSect, DocNode::Kind_WhiteSpace, DocNode::Kind_XRefItem, m_t, mustBeOutsideParagraph(), and DocNode::parent().
visitPost() [4/38]
void HtmlDocVisitor::visitPost (DocRoot *) virtual
Implements DocVisitor.
Definition at line 1131 of file htmldocvisitor.cpp.
visitPost() [5/38]
void HtmlDocVisitor::visitPost (DocSimpleSect * s) virtual
Implements DocVisitor.
Definition at line 1184 of file htmldocvisitor.cpp.
References forceStartParagraph(), m_hide, and m_t.
visitPost() [6/38]
void HtmlDocVisitor::visitPost (DocTitle *) virtual
Implements DocVisitor.
Definition at line 1195 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [7/38]
void HtmlDocVisitor::visitPost (DocSimpleList * sl) virtual
Implements DocVisitor.
Definition at line 1210 of file htmldocvisitor.cpp.
References forceStartParagraph(), DocNode::isPreformatted(), m_hide, and m_t.
visitPost() [8/38]
void HtmlDocVisitor::visitPost (DocSimpleListItem * li) virtual
Implements DocVisitor.
Definition at line 1224 of file htmldocvisitor.cpp.
References DocNode::isPreformatted(), m_hide, and m_t.
visitPost() [9/38]
void HtmlDocVisitor::visitPost (DocSection * s) virtual
Implements DocVisitor.
Definition at line 1242 of file htmldocvisitor.cpp.
References forceStartParagraph().
visitPost() [10/38]
void HtmlDocVisitor::visitPost (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 1261 of file htmldocvisitor.cpp.
References forceStartParagraph(), DocNode::isPreformatted(), m_hide, m_t, DocHtmlList::Ordered, and DocHtmlList::type().
visitPost() [11/38]
void HtmlDocVisitor::visitPost (DocHtmlListItem *) virtual
Implements DocVisitor.
Definition at line 1283 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [12/38]
void HtmlDocVisitor::visitPost (DocHtmlDescList * dl) virtual
Implements DocVisitor.
Definition at line 1296 of file htmldocvisitor.cpp.
References forceStartParagraph(), m_hide, and m_t.
visitPost() [13/38]
void HtmlDocVisitor::visitPost (DocHtmlDescTitle *) virtual
Implements DocVisitor.
Definition at line 1309 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [14/38]
void HtmlDocVisitor::visitPost (DocHtmlDescData *) virtual
Implements DocVisitor.
Definition at line 1321 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [15/38]
void HtmlDocVisitor::visitPost (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 1349 of file htmldocvisitor.cpp.
References forceStartParagraph(), m_hide, and m_t.
visitPost() [16/38]
void HtmlDocVisitor::visitPost (DocHtmlRow *) virtual
Implements DocVisitor.
Definition at line 1362 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [17/38]
void HtmlDocVisitor::visitPost (DocHtmlCell * c) virtual
Implements DocVisitor.
Definition at line 1381 of file htmldocvisitor.cpp.
References DocHtmlCell::isHeading(), m_hide, and m_t.
visitPost() [18/38]
void HtmlDocVisitor::visitPost (DocHtmlCaption *) virtual
Implements DocVisitor.
Definition at line 1393 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [19/38]
void HtmlDocVisitor::visitPost (DocInternal *) virtual
Implements DocVisitor.
Definition at line 1406 of file htmldocvisitor.cpp.
References m_hide.
visitPost() [20/38]
void HtmlDocVisitor::visitPost (DocHRef *) virtual
Implements DocVisitor.
Definition at line 1427 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [21/38]
void HtmlDocVisitor::visitPost (DocHtmlHeader * header) virtual
Implements DocVisitor.
Definition at line 1441 of file htmldocvisitor.cpp.
References forceStartParagraph(), DocHtmlHeader::level(), m_hide, and m_t.
visitPost() [22/38]
void HtmlDocVisitor::visitPost (DocImage * img) virtual
Implements DocVisitor.
Definition at line 1512 of file htmldocvisitor.cpp.
References endl(), forceStartParagraph(), DocImage::hasCaption(), DocImage::Html, m_hide, m_t, popEnabled(), and DocImage::type().
visitPost() [23/38]
void HtmlDocVisitor::visitPost (DocDotFile * df) virtual
Implements DocVisitor.
Definition at line 1541 of file htmldocvisitor.cpp.
References endl(), DocDotFile::hasCaption(), m_hide, and m_t.
visitPost() [24/38]
void HtmlDocVisitor::visitPost (DocMscFile * df) virtual
Implements DocVisitor.
Definition at line 1561 of file htmldocvisitor.cpp.
References endl(), DocMscFile::hasCaption(), m_hide, and m_t.
visitPost() [25/38]
void HtmlDocVisitor::visitPost (DocDiaFile * df) virtual
Implements DocVisitor.
Definition at line 1581 of file htmldocvisitor.cpp.
References endl(), DocDiaFile::hasCaption(), m_hide, and m_t.
visitPost() [26/38]
void HtmlDocVisitor::visitPost (DocLink *) virtual
Implements DocVisitor.
Definition at line 1597 of file htmldocvisitor.cpp.
References endLink(), and m_hide.
visitPost() [27/38]
void HtmlDocVisitor::visitPost (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 1615 of file htmldocvisitor.cpp.
References endLink(), DocRef::file(), and m_hide.
visitPost() [28/38]
void HtmlDocVisitor::visitPost (DocSecRefItem *) virtual
Implements DocVisitor.
Definition at line 1635 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPost() [29/38]
void HtmlDocVisitor::visitPost (DocSecRefList * s) virtual
Implements DocVisitor.
Definition at line 1649 of file htmldocvisitor.cpp.
References endl(), forceStartParagraph(), m_hide, and m_t.
visitPost() [30/38]
void HtmlDocVisitor::visitPost (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 1709 of file htmldocvisitor.cpp.
References endl(), forceStartParagraph(), m_hide, and m_t.
visitPost() [31/38]
void HtmlDocVisitor::visitPost (DocParamList *) virtual
Implements DocVisitor.
Definition at line 1791 of file htmldocvisitor.cpp.
References endl(), m_hide, and m_t.
visitPost() [32/38]
void HtmlDocVisitor::visitPost (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1821 of file htmldocvisitor.cpp.
References endl(), forceStartParagraph(), m_hide, m_t, and DocXRefItem::title().
visitPost() [33/38]
void HtmlDocVisitor::visitPost (DocInternalRef *) virtual
Implements DocVisitor.
Definition at line 1835 of file htmldocvisitor.cpp.
References endLink(), m_hide, and m_t.
visitPost() [34/38]
void HtmlDocVisitor::visitPost (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1846 of file htmldocvisitor.cpp.
visitPost() [35/38]
void HtmlDocVisitor::visitPost (DocText *) virtual
Implements DocVisitor.
Definition at line 1854 of file htmldocvisitor.cpp.
visitPost() [36/38]
void HtmlDocVisitor::visitPost (DocHtmlBlockQuote * b) virtual
Implements DocVisitor.
Definition at line 1873 of file htmldocvisitor.cpp.
References endl(), forceStartParagraph(), m_hide, and m_t.
visitPost() [37/38]
void HtmlDocVisitor::visitPost (DocVhdlFlow * vf) virtual
Implements DocVisitor.
Definition at line 1901 of file htmldocvisitor.cpp.
References forceStartParagraph(), VhdlDocGen::getFlowMember(), m_hide, and m_t.
visitPost() [38/38]
void HtmlDocVisitor::visitPost (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1916 of file htmldocvisitor.cpp.
References m_hide.
visitPre() [1/38]
void HtmlDocVisitor::visitPre (DocAutoList * l) virtual
Implements DocVisitor.
Definition at line 764 of file htmldocvisitor.cpp.
References DocAutoList::depth(), forceEndParagraph(), DocAutoList::isEnumList(), DocNode::isPreformatted(), m_hide, m_t, NUM_HTML_LIST_TYPES, and types.
visitPre() [2/38]
void HtmlDocVisitor::visitPre (DocAutoListItem *) virtual
Implements DocVisitor.
Definition at line 804 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [3/38]
void HtmlDocVisitor::visitPre (DocPara * p) virtual
Implements DocVisitor.
Definition at line 987 of file htmldocvisitor.cpp.
References CompAccept< T >::children(), getParagraphContext(), DocNode::kind(), DocNode::Kind_AutoListItem, DocNode::Kind_Copy, DocNode::Kind_HtmlBlockQuote, DocNode::Kind_HtmlCell, DocNode::Kind_HtmlDescData, DocNode::Kind_HtmlListItem, DocNode::Kind_Internal, DocNode::Kind_ParBlock, DocNode::Kind_Root, DocNode::Kind_Section, DocNode::Kind_SimpleListItem, DocNode::Kind_SimpleSect, DocNode::Kind_WhiteSpace, DocNode::Kind_XRefItem, m_hide, m_t, mustBeOutsideParagraph(), and DocNode::parent().
visitPre() [4/38]
void HtmlDocVisitor::visitPre (DocRoot *) virtual
Implements DocVisitor.
Definition at line 1127 of file htmldocvisitor.cpp.
visitPre() [5/38]
void HtmlDocVisitor::visitPre (DocSimpleSect * s) virtual
Implements DocVisitor.
Definition at line 1135 of file htmldocvisitor.cpp.
References DocSimpleSect::Attention, DocSimpleSect::Author, DocSimpleSect::Authors, DocSimpleSect::Copyright, DocSimpleSect::Date, forceEndParagraph(), DocSimpleSect::Invar, m_hide, m_t, DocSimpleSect::Note, DocSimpleSect::Post, DocSimpleSect::Pre, DocSimpleSect::Rcs, DocSimpleSect::Remark, DocSimpleSect::Return, DocSimpleSect::See, DocSimpleSect::Since, theTranslator, Translator::trAttention(), Translator::trAuthor(), Translator::trCopyright(), Translator::trDate(), Translator::trInvariant(), Translator::trNote(), Translator::trPostcondition(), Translator::trPrecondition(), Translator::trRemarks(), Translator::trReturns(), Translator::trSeeAlso(), Translator::trSince(), Translator::trVersion(), Translator::trWarning(), DocSimpleSect::type(), DocSimpleSect::typeString(), DocSimpleSect::Unknown, DocSimpleSect::User, DocSimpleSect::Version, and DocSimpleSect::Warning.
visitPre() [6/38]
void HtmlDocVisitor::visitPre (DocTitle *) virtual
Implements DocVisitor.
Definition at line 1191 of file htmldocvisitor.cpp.
visitPre() [7/38]
void HtmlDocVisitor::visitPre (DocSimpleList * sl) virtual
Implements DocVisitor.
Definition at line 1201 of file htmldocvisitor.cpp.
References forceEndParagraph(), DocNode::isPreformatted(), m_hide, and m_t.
visitPre() [8/38]
void HtmlDocVisitor::visitPre (DocSimpleListItem *) virtual
Implements DocVisitor.
Definition at line 1218 of file htmldocvisitor.cpp.
References m_hide, and m_t.
visitPre() [9/38]
void HtmlDocVisitor::visitPre (DocSection * s) virtual
Implements DocVisitor.
Definition at line 1231 of file htmldocvisitor.cpp.
References DocSection::anchor(), convertCharEntitiesToUTF8(), endl(), filter(), forceEndParagraph(), DocSection::level(), m_hide, m_t, and DocSection::title().
visitPre() [10/38]
void HtmlDocVisitor::visitPre (DocHtmlList * s) virtual
Implements DocVisitor.
Definition at line 1247 of file htmldocvisitor.cpp.
References DocHtmlList::attribs(), forceEndParagraph(), htmlAttribsToString(), m_hide, m_t, DocHtmlList::Ordered, and DocHtmlList::type().
visitPre() [11/38]
void HtmlDocVisitor::visitPre (DocHtmlListItem * i) virtual
Implements DocVisitor.
Definition at line 1276 of file htmldocvisitor.cpp.
References DocHtmlListItem::attribs(), htmlAttribsToString(), DocNode::isPreformatted(), m_hide, and m_t.
visitPre() [12/38]
void HtmlDocVisitor::visitPre (DocHtmlDescList * dl) virtual
Implements DocVisitor.
Definition at line 1289 of file htmldocvisitor.cpp.
References DocHtmlDescList::attribs(), forceEndParagraph(), htmlAttribsToString(), m_hide, and m_t.
visitPre() [13/38]
void HtmlDocVisitor::visitPre (DocHtmlDescTitle * dt) virtual
Implements DocVisitor.
Definition at line 1303 of file htmldocvisitor.cpp.
References DocHtmlDescTitle::attribs(), htmlAttribsToString(), m_hide, and m_t.
visitPre() [14/38]
void HtmlDocVisitor::visitPre (DocHtmlDescData * dd) virtual
Implements DocVisitor.
Definition at line 1315 of file htmldocvisitor.cpp.
References DocHtmlDescData::attribs(), htmlAttribsToString(), m_hide, and m_t.
visitPre() [15/38]
void HtmlDocVisitor::visitPre (DocHtmlTable * t) virtual
Implements DocVisitor.
Definition at line 1327 of file htmldocvisitor.cpp.
References DocHtmlCaption::anchor(), DocHtmlTable::attribs(), DocHtmlTable::caption(), forceEndParagraph(), DocHtmlTable::hasCaption(), htmlAttribsToString(), m_hide, and m_t.
visitPre() [16/38]
void HtmlDocVisitor::visitPre (DocHtmlRow * tr) virtual
Implements DocVisitor.
Definition at line 1356 of file htmldocvisitor.cpp.
References DocHtmlRow::attribs(), htmlAttribsToString(), m_hide, and m_t.
visitPre() [17/38]
void HtmlDocVisitor::visitPre (DocHtmlCell * c) virtual
Implements DocVisitor.
Definition at line 1368 of file htmldocvisitor.cpp.
References DocHtmlCell::attribs(), htmlAttribsToString(), DocHtmlCell::isHeading(), m_hide, and m_t.
visitPre() [18/38]
void HtmlDocVisitor::visitPre (DocHtmlCaption * c) virtual
Implements DocVisitor.
Definition at line 1387 of file htmldocvisitor.cpp.
References DocHtmlCaption::attribs(), htmlAttribsToString(), m_hide, and m_t.
visitPre() [19/38]
void HtmlDocVisitor::visitPre (DocInternal *) virtual
Implements DocVisitor.
Definition at line 1399 of file htmldocvisitor.cpp.
References m_hide.
visitPre() [20/38]
void HtmlDocVisitor::visitPre (DocHRef * href) virtual
Implements DocVisitor.
Definition at line 1412 of file htmldocvisitor.cpp.
References DocHRef::attribs(), convertToXML(), correctURL(), htmlAttribsToString(), m_hide, m_t, DocHRef::relPath(), DocHRef::url(), and writeObfuscatedMailAddress().
visitPre() [21/38]
void HtmlDocVisitor::visitPre (DocHtmlHeader * header) virtual
Implements DocVisitor.
Definition at line 1433 of file htmldocvisitor.cpp.
References DocHtmlHeader::attribs(), forceEndParagraph(), htmlAttribsToString(), DocHtmlHeader::level(), m_hide, and m_t.
visitPre() [22/38]
void HtmlDocVisitor::visitPre (DocImage * img) virtual
Implements DocVisitor.
Definition at line 1448 of file htmldocvisitor.cpp.
References DocImage::attribs(), correctURL(), endl(), forceEndParagraph(), DocImage::hasCaption(), DocImage::height(), DocImage::Html, htmlAttribsToString(), m_hide, m_t, DocImage::name(), pushEnabled(), DocImage::relPath(), DocImage::type(), DocImage::url(), and DocImage::width().
visitPre() [23/38]
void HtmlDocVisitor::visitPre (DocDotFile * df) virtual
Implements DocVisitor.
Definition at line 1530 of file htmldocvisitor.cpp.
References DocDotFile::context(), endl(), DocDotFile::file(), DocDotFile::hasCaption(), m_hide, m_t, DocDotFile::relPath(), and writeDotFile().
visitPre() [24/38]
void HtmlDocVisitor::visitPre (DocMscFile * df) virtual
Implements DocVisitor.
Definition at line 1551 of file htmldocvisitor.cpp.
References DocMscFile::context(), endl(), DocMscFile::file(), DocMscFile::hasCaption(), m_hide, m_t, DocMscFile::relPath(), and writeMscFile().
visitPre() [25/38]
void HtmlDocVisitor::visitPre (DocDiaFile * df) virtual
Implements DocVisitor.
Definition at line 1571 of file htmldocvisitor.cpp.
References DocDiaFile::context(), endl(), DocDiaFile::file(), DocDiaFile::hasCaption(), m_hide, m_t, DocDiaFile::relPath(), and writeDiaFile().
visitPre() [26/38]
void HtmlDocVisitor::visitPre (DocLink * lnk) virtual
Implements DocVisitor.
Definition at line 1591 of file htmldocvisitor.cpp.
References DocLink::anchor(), DocLink::file(), m_hide, DocLink::ref(), DocLink::relPath(), and startLink().
visitPre() [27/38]
void HtmlDocVisitor::visitPre (DocRef * ref) virtual
Implements DocVisitor.
Definition at line 1603 of file htmldocvisitor.cpp.
References DocRef::anchor(), DocRef::file(), filter(), DocRef::hasLinkText(), DocRef::isSubPage(), m_hide, DocRef::ref(), DocRef::relPath(), startLink(), and DocRef::targetTitle().
visitPre() [28/38]
void HtmlDocVisitor::visitPre (DocSecRefItem * ref) virtual
Implements DocVisitor.
Definition at line 1622 of file htmldocvisitor.cpp.
References DocSecRefItem::anchor(), DocSecRefItem::file(), Doxygen::htmlFileExtension, m_hide, and m_t.
visitPre() [29/38]
void HtmlDocVisitor::visitPre (DocSecRefList * s) virtual
Implements DocVisitor.
Definition at line 1641 of file htmldocvisitor.cpp.
References endl(), forceEndParagraph(), m_hide, and m_t.
visitPre() [30/38]
void HtmlDocVisitor::visitPre (DocParamSect * s) virtual
Implements DocVisitor.
Definition at line 1676 of file htmldocvisitor.cpp.
References endl(), DocParamSect::Exception, forceEndParagraph(), m_hide, m_t, DocParamSect::Param, DocParamSect::RetVal, DocParamSect::TemplateParam, theTranslator, Translator::trExceptions(), Translator::trParameters(), Translator::trReturnValues(), Translator::trTemplateParameters(), and DocParamSect::type().
visitPre() [31/38]
void HtmlDocVisitor::visitPre (DocParamList * pl) virtual
Implements DocVisitor.
Definition at line 1718 of file htmldocvisitor.cpp.
References DocParamList::direction(), DocParamSect::hasInOutSpecifier(), DocParamSect::hasTypeSpecifier(), DocParamSect::In, DocParamSect::InOut, DocNode::kind(), DocNode::Kind_LinkedWord, DocNode::Kind_ParamSect, DocNode::Kind_Word, m_hide, m_t, DocParamSect::Out, DocParamList::parameters(), DocParamList::paramTypes(), DocNode::parent(), DocParamSect::Unspecified, and visit().
visitPre() [32/38]
void HtmlDocVisitor::visitPre (DocXRefItem * x) virtual
Implements DocVisitor.
Definition at line 1798 of file htmldocvisitor.cpp.
References DocXRefItem::anchor(), DocXRefItem::file(), filter(), forceEndParagraph(), Doxygen::htmlFileExtension, DocXRefItem::key(), m_hide, m_t, DocXRefItem::relPath(), and DocXRefItem::title().
visitPre() [33/38]
void HtmlDocVisitor::visitPre (DocInternalRef * ref) virtual
Implements DocVisitor.
Definition at line 1829 of file htmldocvisitor.cpp.
References DocInternalRef::anchor(), DocInternalRef::file(), m_hide, DocInternalRef::relPath(), and startLink().
visitPre() [34/38]
void HtmlDocVisitor::visitPre (DocCopy *) virtual
Implements DocVisitor.
Definition at line 1842 of file htmldocvisitor.cpp.
visitPre() [35/38]
void HtmlDocVisitor::visitPre (DocText *) virtual
Implements DocVisitor.
Definition at line 1850 of file htmldocvisitor.cpp.
visitPre() [36/38]
void HtmlDocVisitor::visitPre (DocHtmlBlockQuote * b) virtual
Implements DocVisitor.
Definition at line 1858 of file htmldocvisitor.cpp.
References DocHtmlBlockQuote::attribs(), forceEndParagraph(), htmlAttribsToString(), m_hide, and m_t.
visitPre() [37/38]
void HtmlDocVisitor::visitPre (DocVhdlFlow * vf) virtual
Implements DocVisitor.
Definition at line 1880 of file htmldocvisitor.cpp.
References FlowChart::convertNameToFileName(), forceEndParagraph(), VhdlDocGen::getFlowMember(), DocVhdlFlow::hasCaption(), m_hide, m_t, and Definition::name().
visitPre() [38/38]
void HtmlDocVisitor::visitPre (DocParBlock *) virtual
Implements DocVisitor.
Definition at line 1911 of file htmldocvisitor.cpp.
References m_hide.
writeDiaFile()
void HtmlDocVisitor::writeDiaFile (const QCString & fileName, const QCString & relPath, const QCString & context) private
Definition at line 2046 of file htmldocvisitor.cpp.
References Config_getString, DIA_BITMAP, endl(), m_t, and writeDiaGraphFromFile().
Referenced by visitPre().
writeDotFile()
void HtmlDocVisitor::writeDotFile (const QCString & fileName, const QCString & relPath, const QCString & context) private
Definition at line 2003 of file htmldocvisitor.cpp.
References Config_getString, GOF_BITMAP, m_t, writeDotGraphFromFile(), and writeDotImageMapFromFile().
Referenced by visit(), and visitPre().
writeMscFile()
void HtmlDocVisitor::writeMscFile (const QCString & fileName, const QCString & relPath, const QCString & context) private
Definition at line 2022 of file htmldocvisitor.cpp.
References Config_getString, getDotImageExtension(), m_t, MSC_BITMAP, MSC_SVG, writeMscGraphFromFile(), and writeMscImageMapFromFile().
Referenced by visit(), and visitPre().
writeObfuscatedMailAddress()
void HtmlDocVisitor::writeObfuscatedMailAddress (const QCString & url) private
Definition at line 204 of file htmldocvisitor.cpp.
References m_t.
Referenced by visit(), and visitPre().
writePlantUMLFile()
void HtmlDocVisitor::writePlantUMLFile (const QCString & fileName, const QCString & relPath, const QCString & context) private
Definition at line 2067 of file htmldocvisitor.cpp.
References Config_getString, endl(), generatePlantUMLOutput(), getDotImageExtension(), m_t, PUML_BITMAP, and PUML_SVG.
Referenced by visit().
Member Data Documentation
m_ci
CodeOutputInterface& HtmlDocVisitor::m_ci private
Definition at line 169 of file htmldocvisitor.h.
Referenced by visit().
m_ctx
Definition* HtmlDocVisitor::m_ctx private
Definition at line 173 of file htmldocvisitor.h.
Referenced by visit().
m_enabled
QStack<bool> HtmlDocVisitor::m_enabled private
Definition at line 172 of file htmldocvisitor.h.
Referenced by popEnabled(), and pushEnabled().
m_hide
bool HtmlDocVisitor::m_hide private
Definition at line 171 of file htmldocvisitor.h.
Referenced by popEnabled(), pushEnabled(), visit(), visitPost(), and visitPre().
m_insidePre
bool HtmlDocVisitor::m_insidePre private
Definition at line 170 of file htmldocvisitor.h.
Referenced by visit().
m_langExt
QCString HtmlDocVisitor::m_langExt private
Definition at line 174 of file htmldocvisitor.h.
Referenced by HtmlDocVisitor(), and visit().
m_t
FTextStream& HtmlDocVisitor::m_t private
Definition at line 168 of file htmldocvisitor.h.
Referenced by endLink(), filter(), filterQuotedCdataAttr(), forceEndParagraph(), forceStartParagraph(), startLink(), visit(), visitPost(), visitPre(), writeDiaFile(), writeDotFile(), writeMscFile(), writeObfuscatedMailAddress(), and writePlantUMLFile().
The documentation for this class was generated from the following files:
src/htmldocvisitor.h
src/htmldocvisitor.cpp