Doxygen: src/htmldocvisitor.cpp File Reference
htmldocvisitor.cpp File Reference
#include <qdir.h>
#include "htmldocvisitor.h"
#include "docparser.h"
#include "language.h"
#include "doxygen.h"
#include "outputgen.h"
#include "dot.h"
#include "message.h"
#include "config.h"
#include "htmlgen.h"
#include "parserintf.h"
#include "msc.h"
#include "dia.h"
#include "util.h"
#include "vhdldocgen.h"
#include "filedef.h"
#include "memberdef.h"
#include "htmlentity.h"
#include "plantuml.h"
Functions
static QCString convertIndexWordToAnchor (const QString &word)
static bool mustBeOutsideParagraph (DocNode *n)
static QString htmlAttribsToString (const HtmlAttribList &attribs)
static void visitPreCaption (FTextStream &t, DocVerbatim *s)
static void visitPostCaption (FTextStream &t, DocVerbatim *s)
static void visitCaption (HtmlDocVisitor *parent, QList< DocNode > children)
template<class T >
bool isFirstChildNode (T *parent, DocNode *node)
template<class T >
bool isLastChildNode (T *parent, DocNode *node)
bool isSeparatedParagraph (DocSimpleSect *parent, DocPara *par)
static int getParagraphContext (DocPara *p, bool &isFirst, bool &isLast)
static bool insideStyleChangeThatIsOutsideParagraph (DocPara *para, int nodeIndex)
Returns TRUE if the child nodes in paragraph para until nodeIndex contain a style change node that is still active and that style change is one that must be located outside of a paragraph, i.e.
Variables
static const int NUM_HTML_LIST_TYPES = 4
static const char types [][NUM_HTML_LIST_TYPES] = {"1", "a", "i", "A"}
Function Documentation
convertIndexWordToAnchor()
static QCString convertIndexWordToAnchor (const QString & word) static
Definition at line 42 of file htmldocvisitor.cpp.
Referenced by HtmlDocVisitor::visit().
getParagraphContext()
static int getParagraphContext (DocPara * p, bool & isFirst, bool & isLast) static
Definition at line 860 of file htmldocvisitor.cpp.
References isFirstChildNode(), isLastChildNode(), isSeparatedParagraph(), DocNode::kind(), DocNode::Kind_AutoListItem, DocNode::Kind_HtmlCell, DocNode::Kind_HtmlDescData, DocNode::Kind_HtmlListItem, DocNode::Kind_Para, DocNode::Kind_ParamList, DocNode::Kind_ParBlock, DocNode::Kind_SecRefItem, DocNode::Kind_SimpleListItem, DocNode::Kind_SimpleSect, DocNode::Kind_XRefItem, and DocNode::parent().
Referenced by HtmlDocVisitor::forceEndParagraph(), HtmlDocVisitor::forceStartParagraph(), HtmlDocVisitor::visitPost(), and HtmlDocVisitor::visitPre().
htmlAttribsToString()
static QString htmlAttribsToString (const HtmlAttribList & attribs) static
Definition at line 129 of file htmldocvisitor.cpp.
References convertToXML(), HtmlAttrib::name, and HtmlAttrib::value.
Referenced by HtmlDocVisitor::visit(), and HtmlDocVisitor::visitPre().
insideStyleChangeThatIsOutsideParagraph()
static bool insideStyleChangeThatIsOutsideParagraph (DocPara * para, int nodeIndex) static
Returns TRUE if the child nodes in paragraph para until nodeIndex contain a style change node that is still active and that style change is one that must be located outside of a paragraph, i.e.
it is a center, div, or pre tag. See also bug746162.
Definition at line 2103 of file htmldocvisitor.cpp.
References DocStyleChange::Center, CompAccept< T >::children(), DocStyleChange::Div, DocStyleChange::enable(), DocNode::kind(), DocNode::Kind_StyleChange, DocStyleChange::Preformatted, and DocStyleChange::style().
Referenced by HtmlDocVisitor::forceEndParagraph(), and HtmlDocVisitor::forceStartParagraph().
isFirstChildNode()
template<class T > bool isFirstChildNode (T * parent, DocNode * node)
Definition at line 818 of file htmldocvisitor.cpp.
Referenced by getParagraphContext().
isLastChildNode()
template<class T > bool isLastChildNode (T * parent, DocNode * node)
Definition at line 824 of file htmldocvisitor.cpp.
Referenced by getParagraphContext().
isSeparatedParagraph()
bool isSeparatedParagraph (DocSimpleSect * parent, DocPara * par)
Definition at line 829 of file htmldocvisitor.cpp.
References CompAccept< T >::children(), and DocNode::Kind_SimpleSectSep.
Referenced by getParagraphContext().
mustBeOutsideParagraph()
static bool mustBeOutsideParagraph (DocNode * n) static
Definition at line 76 of file htmldocvisitor.cpp.
References DocStyleChange::Center, DocStyleChange::Div, DocVerbatim::HtmlOnly, DocVerbatim::isBlock(), DocNode::kind(), DocNode::Kind_AutoList, DocNode::Kind_Copy, DocNode::Kind_Formula, DocNode::Kind_HorRuler, DocNode::Kind_HtmlBlockQuote, DocNode::Kind_HtmlDescList, DocNode::Kind_HtmlHeader, DocNode::Kind_HtmlList, DocNode::Kind_HtmlTable, DocNode::Kind_Image, DocNode::Kind_Include, DocNode::Kind_Internal, DocNode::Kind_ParamSect, DocNode::Kind_ParBlock, DocNode::Kind_SecRefList, DocNode::Kind_Section, DocNode::Kind_SimpleList, DocNode::Kind_SimpleSect, DocNode::Kind_StyleChange, DocNode::Kind_Verbatim, DocNode::Kind_XRefItem, DocStyleChange::Preformatted, and DocVerbatim::type().
Referenced by HtmlDocVisitor::forceEndParagraph(), HtmlDocVisitor::forceStartParagraph(), HtmlDocVisitor::visitPost(), and HtmlDocVisitor::visitPre().
visitCaption()
static void visitCaption (HtmlDocVisitor * parent, QList< DocNode > children) static
Definition at line 345 of file htmldocvisitor.cpp.
References DocNode::accept().
Referenced by HtmlDocVisitor::visit().
visitPostCaption()
static void visitPostCaption (FTextStream & t, DocVerbatim * s) static
Definition at line 336 of file htmldocvisitor.cpp.
References endl(), and DocVerbatim::hasCaption().
Referenced by HtmlDocVisitor::visit().
visitPreCaption()
static void visitPreCaption (FTextStream & t, DocVerbatim * s) static
Definition at line 327 of file htmldocvisitor.cpp.
References endl(), and DocVerbatim::hasCaption().
Referenced by HtmlDocVisitor::visit().
Variable Documentation
NUM_HTML_LIST_TYPES
const int NUM_HTML_LIST_TYPES = 4 static
Definition at line 39 of file htmldocvisitor.cpp.
Referenced by HtmlDocVisitor::visitPre().
types
const char types[][NUM_HTML_LIST_TYPES] = {"1", "a", "i", "A"} static
Definition at line 40 of file htmldocvisitor.cpp.
Referenced by HtmlDocVisitor::visitPre().