Doxygen: ExprAstUnary Class Reference
ExprAstUnary Class Reference
Public Member Functions
ExprAstUnary (Operator::Type op, ExprAst *exp)
~ExprAstUnary ()
virtual TemplateVariant resolve (TemplateContext *c)
Public Member Functions inherited from ExprAst
virtual ~ExprAst ()
Private Attributes
Operator::Type m_operator
ExprAst * m_exp
Detailed Description
Definition at line 1574 of file template.cpp.
Constructor & Destructor Documentation
ExprAstUnary()
ExprAstUnary::ExprAstUnary (Operator::Type op, ExprAst * exp) inline
Definition at line 1577 of file template.cpp.
References Operator::toString(), and TRACE.
~ExprAstUnary()
ExprAstUnary::~ExprAstUnary () inline
Definition at line 1579 of file template.cpp.
References m_exp.
Member Function Documentation
resolve()
virtual TemplateVariant ExprAstUnary::resolve (TemplateContext * c) inline virtual
Reimplemented from ExprAst.
Definition at line 1580 of file template.cpp.
References m_exp, m_operator, Operator::Minus, ExprAst::resolve(), and TemplateVariant::toInt().
Member Data Documentation
m_exp
ExprAst* ExprAstUnary::m_exp private
Definition at line 1593 of file template.cpp.
Referenced by resolve(), and ~ExprAstUnary().
m_operator
Operator::Type ExprAstUnary::m_operator private
Definition at line 1592 of file template.cpp.
Referenced by resolve().
The documentation for this class was generated from the following file:
src/template.cpp