Doxygen: DocIncOperator Class Reference
DocIncOperator Class Reference
Node representing a include/dontinclude operator block.
#include <docparser.h>
Public Types
enum Type { Line, SkipLine, Skip, Until }
Public Types inherited from DocNode
enum Kind {
Kind_Root = 0, Kind_Word = 1, Kind_WhiteSpace = 2, Kind_Para = 3,
Kind_AutoList = 4, Kind_AutoListItem = 5, Kind_Symbol = 6, Kind_URL = 7,
Kind_StyleChange = 8, Kind_SimpleSect = 9, Kind_Title = 10, Kind_SimpleList = 11,
Kind_SimpleListItem = 12, Kind_Section = 13, Kind_Verbatim = 14, Kind_XRefItem = 15,
Kind_HtmlList = 16, Kind_HtmlListItem = 17, Kind_HtmlDescList = 18, Kind_HtmlDescData = 19,
Kind_HtmlDescTitle = 20, Kind_HtmlTable = 21, Kind_HtmlRow = 22, Kind_HtmlCell = 23,
Kind_HtmlCaption = 24, Kind_LineBreak = 25, Kind_HorRuler = 26, Kind_Anchor = 27,
Kind_IndexEntry = 28, Kind_Internal = 29, Kind_HRef = 30, Kind_Include = 31,
Kind_IncOperator = 32, Kind_HtmlHeader = 33, Kind_Image = 34, Kind_DotFile = 35,
Kind_Link = 36, Kind_Ref = 37, Kind_Formula = 38, Kind_SecRefItem = 39,
Kind_SecRefList = 40, Kind_SimpleSectSep = 41, Kind_LinkedWord = 42, Kind_ParamSect = 43,
Kind_ParamList = 44, Kind_InternalRef = 45, Kind_Copy = 46, Kind_Text = 47,
Kind_MscFile = 48, Kind_HtmlBlockQuote = 49, Kind_VhdlFlow = 50, Kind_ParBlock = 51,
Kind_DiaFile = 52
}
Public Member Functions
DocIncOperator (DocNode *parent, Type t, const QCString &pat, const QCString &context, bool isExample, const QCString &exampleFile)
Kind kind () const
Type type () const
QCString text () const
QCString pattern () const
QCString context () const
void accept (DocVisitor *v)
bool isFirst () const
bool isLast () const
void markFirst (bool v=TRUE)
void markLast (bool v=TRUE)
bool isExample () const
QCString exampleFile () const
void parse ()
Public Member Functions inherited from DocNode
DocNode ()
virtual ~DocNode ()
DocNode * parent () const
void setParent (DocNode *parent)
bool isPreformatted () const
Private Attributes
Type m_type
QCString m_text
QCString m_pattern
QCString m_context
bool m_isFirst
bool m_isLast
bool m_isExample
QCString m_exampleFile
Additional Inherited Members
Protected Member Functions inherited from DocNode
void setInsidePreformatted (bool p)
Protected Attributes inherited from DocNode
DocNode * m_parent
Detailed Description
Node representing a include/dontinclude operator block.
Definition at line 523 of file docparser.h.
Member Enumeration Documentation
Type
enum DocIncOperator::Type
Enumerator
Line
SkipLine
Skip
Until
Definition at line 526 of file docparser.h.
Constructor & Destructor Documentation
DocIncOperator()
DocIncOperator::DocIncOperator (DocNode * parent, Type t, const QCString & pat, const QCString & context, bool isExample, const QCString & exampleFile) inline
Definition at line 527 of file docparser.h.
References DocNode::m_parent, and DocNode::parent().
Member Function Documentation
accept()
void DocIncOperator::accept (DocVisitor * v) inline virtual
Acceptor function for node visitors. Part of the visitor pattern.
Parameters
v Abstract visitor.
Implements DocNode.
Definition at line 537 of file docparser.h.
References DocVisitor::visit().
context()
QCString DocIncOperator::context () const inline
Definition at line 536 of file docparser.h.
References m_context.
Referenced by DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), and LatexDocVisitor::visit().
exampleFile()
QCString DocIncOperator::exampleFile () const inline
Definition at line 543 of file docparser.h.
References m_exampleFile.
Referenced by DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), and LatexDocVisitor::visit().
isExample()
bool DocIncOperator::isExample () const inline
Definition at line 542 of file docparser.h.
References m_isExample.
Referenced by DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), and LatexDocVisitor::visit().
isFirst()
bool DocIncOperator::isFirst () const inline
Definition at line 538 of file docparser.h.
References m_isFirst.
Referenced by DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), and LatexDocVisitor::visit().
isLast()
bool DocIncOperator::isLast () const inline
Definition at line 539 of file docparser.h.
References m_isLast.
Referenced by DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), and LatexDocVisitor::visit().
kind()
Kind DocIncOperator::kind () const inline virtual
Returns the kind of node. Provides runtime type information
Implements DocNode.
Definition at line 532 of file docparser.h.
References DocNode::Kind_IncOperator.
markFirst()
void DocIncOperator::markFirst (bool v = TRUE) inline
Definition at line 540 of file docparser.h.
References m_isFirst.
Referenced by DocPara::handleIncludeOperator().
markLast()
void DocIncOperator::markLast (bool v = TRUE) inline
Definition at line 541 of file docparser.h.
References m_isLast.
Referenced by DocPara::handleIncludeOperator().
parse()
void DocIncOperator::parse ()
Definition at line 1955 of file docparser.cpp.
References DBG, g_includeFileLength, g_includeFileOffset, g_includeFileText, Line, m_pattern, m_text, Skip, SkipLine, type(), and Until.
Referenced by DocPara::handleIncludeOperator().
pattern()
QCString DocIncOperator::pattern () const inline
Definition at line 535 of file docparser.h.
References m_pattern.
Referenced by PrintDocVisitor::visit().
text()
QCString DocIncOperator::text () const inline
Definition at line 534 of file docparser.h.
References m_text.
Referenced by DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), and LatexDocVisitor::visit().
type()
Type DocIncOperator::type () const inline
Definition at line 533 of file docparser.h.
References m_type.
Referenced by parse(), DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), LatexDocVisitor::visit(), and PrintDocVisitor::visit().
Member Data Documentation
m_context
QCString DocIncOperator::m_context private
Definition at line 550 of file docparser.h.
Referenced by context().
m_exampleFile
QCString DocIncOperator::m_exampleFile private
Definition at line 554 of file docparser.h.
Referenced by exampleFile().
m_isExample
bool DocIncOperator::m_isExample private
Definition at line 553 of file docparser.h.
Referenced by isExample().
m_isFirst
bool DocIncOperator::m_isFirst private
Definition at line 551 of file docparser.h.
Referenced by isFirst(), and markFirst().
m_isLast
bool DocIncOperator::m_isLast private
Definition at line 552 of file docparser.h.
Referenced by isLast(), and markLast().
m_pattern
QCString DocIncOperator::m_pattern private
Definition at line 549 of file docparser.h.
Referenced by parse(), and pattern().
m_text
QCString DocIncOperator::m_text private
Definition at line 548 of file docparser.h.
Referenced by parse(), and text().
m_type
Type DocIncOperator::m_type private
Definition at line 547 of file docparser.h.
Referenced by type().
The documentation for this class was generated from the following files:
src/docparser.h
src/docparser.cpp