Doxygen: src/perlmodgen.cpp File Reference
perlmodgen.cpp File Reference
#include <stdlib.h>
#include <qdir.h>
#include <qstack.h>
#include <qdict.h>
#include <qfile.h>
#include "perlmodgen.h"
#include "docparser.h"
#include "message.h"
#include "doxygen.h"
#include "pagedef.h"
#include "memberlist.h"
#include "ftextstream.h"
#include "arguments.h"
#include "config.h"
#include "groupdef.h"
#include "classdef.h"
#include "classlist.h"
#include "filename.h"
#include "membername.h"
#include "namespacedef.h"
#include "membergroup.h"
#include "section.h"
#include "util.h"
#include "htmlentity.h"
Classes
class PerlModOutputStream
class PerlModOutput
class PerlModDocVisitor
Concrete visitor implementation for PerlMod output.
class PerlModGenerator
Macros
#define PERLOUTPUT_MAX_INDENTATION 40
Functions
static void addTemplateArgumentList (ArgumentList *al, PerlModOutput &output, const char *)
static void addTemplateList (ClassDef *cd, PerlModOutput &output)
static void addPerlModDocBlock (PerlModOutput &output, const char *name, const QCString &fileName, int lineNr, Definition *scope, MemberDef *md, const QCString &text)
static const char * getProtectionName (Protection prot)
static const char * getVirtualnessName (Specifier virt)
void setPerlModDoxyfile (const QCString &qs)
void generatePerlMod ()
Variables
static QCString pathDoxyfile
static QCString pathDoxyExec
Macro Definition Documentation
PERLOUTPUT_MAX_INDENTATION
#define PERLOUTPUT_MAX_INDENTATION 40
Definition at line 47 of file perlmodgen.cpp.
Referenced by PerlModOutput::decIndent(), and PerlModOutput::incIndent().
Function Documentation
addPerlModDocBlock()
static void addPerlModDocBlock (PerlModOutput & output, const char * name, const QCString & fileName, int lineNr, Definition * scope, MemberDef * md, const QCString & text) static
Definition at line 1450 of file perlmodgen.cpp.
References DocNode::accept(), PerlModOutput::add(), PerlModOutput::addField(), PerlModOutput::closeHash(), PerlModDocVisitor::finish(), PerlModOutput::openHash(), and validatingParseDoc().
Referenced by PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), and PerlModGenerator::generatePerlModForPage().
addTemplateArgumentList()
static void addTemplateArgumentList (ArgumentList * al, PerlModOutput & output, const char *) static
Definition at line 1413 of file perlmodgen.cpp.
References PerlModOutput::addFieldQuotedString(), PerlModOutput::closeHash(), PerlModOutput::closeList(), Argument::defval, Argument::name, PerlModOutput::openHash(), PerlModOutput::openList(), and Argument::type.
Referenced by addTemplateList().
addTemplateList()
static void addTemplateList (ClassDef * cd, PerlModOutput & output) static
Definition at line 1445 of file perlmodgen.cpp.
References addTemplateArgumentList(), Definition::name(), and ClassDef::templateArguments().
Referenced by PerlModGenerator::generatePerlModForClass().
generatePerlMod()
void generatePerlMod ()
Definition at line 3001 of file perlmodgen.cpp.
References Config_getBool, and PerlModGenerator::generate().
Referenced by generateOutput().
getProtectionName()
static const char* getProtectionName (Protection prot) static
Definition at line 1473 of file perlmodgen.cpp.
References Package, Private, Protected, and Public.
Referenced by PerlModGenerator::addListOfAllMembers(), PerlModGenerator::generatePerlModForClass(), and PerlModGenerator::generatePerlModForMember().
getVirtualnessName()
static const char* getVirtualnessName (Specifier virt) static
Definition at line 1485 of file perlmodgen.cpp.
References Normal, Pure, and Virtual.
Referenced by PerlModGenerator::addListOfAllMembers(), PerlModGenerator::generatePerlModForClass(), and PerlModGenerator::generatePerlModForMember().
setPerlModDoxyfile()
void setPerlModDoxyfile (const QCString & qs)
Definition at line 1499 of file perlmodgen.cpp.
Referenced by readConfiguration().
Variable Documentation
pathDoxyExec
QCString pathDoxyExec static
Definition at line 1497 of file perlmodgen.cpp.
pathDoxyfile
QCString pathDoxyfile static
Definition at line 1496 of file perlmodgen.cpp.