Doxygen: ExampleListContext Class Reference
ExampleListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static ExampleListContext * alloc ()
Private Member Functions
ExampleListContext ()
~ExampleListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 791 of file context.h.
Constructor & Destructor Documentation
ExampleListContext()
ExampleListContext::ExampleListContext () private
Definition at line 7453 of file context.cpp.
References p, and Private.
Referenced by alloc().
~ExampleListContext()
ExampleListContext::~ExampleListContext () private
Definition at line 7458 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int ExampleListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 800 of file context.h.
References RefCountedContext::addRef().
alloc()
static ExampleListContext* ExampleListContext::alloc () inline static
Definition at line 794 of file context.h.
References ExampleListContext().
Referenced by generateOutputViaTemplate().
at()
TemplateVariant ExampleListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7469 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int ExampleListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 7464 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * ExampleListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7474 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int ExampleListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 801 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* ExampleListContext::p private
Definition at line 806 of file context.h.
Referenced by at(), count(), createIterator(), ExampleListContext(), and ~ExampleListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp