Doxygen: MemberGroupInfoContext::Private Class Reference
MemberGroupInfoContext::Private Class Reference
Classes
struct Cachable
Public Member Functions
Private (Definition *def, const QCString &relPath, const MemberGroup *mg)
TemplateVariant get (const char *n) const
TemplateVariant members () const
TemplateVariant groupTitle () const
TemplateVariant groupSubtitle () const
TemplateVariant groupAnchor () const
TemplateVariant memberGroups () const
TemplateVariant docs () const
TemplateVariant inherited () const
Private Attributes
Definition * m_def
QCString m_relPath
const MemberGroup * m_memberGroup
Cachable m_cache
Static Private Attributes
static PropertyMapper< MemberGroupInfoContext::Private > s_inst
Detailed Description
Definition at line 8731 of file context.cpp.
Constructor & Destructor Documentation
Private()
MemberGroupInfoContext::Private::Private (Definition * def, const QCString & relPath, const MemberGroup * mg) inline
Definition at line 8734 of file context.cpp.
References PropertyMapper< T >::addProperty(), docs(), groupAnchor(), groupSubtitle(), groupTitle(), inherited(), Config::init(), memberGroups(), members(), and s_inst.
Member Function Documentation
docs()
TemplateVariant MemberGroupInfoContext::Private::docs () const inline
Definition at line 8784 of file context.cpp.
References MemberGroupInfoContext::Private::Cachable::docs, MemberGroup::documentation(), m_cache, m_def, m_memberGroup, m_relPath, parseDoc(), and ScopedPtr< T >::reset().
Referenced by Private().
get()
TemplateVariant MemberGroupInfoContext::Private::get (const char * n) const inline
Definition at line 8752 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by MemberGroupInfoContext::get().
groupAnchor()
TemplateVariant MemberGroupInfoContext::Private::groupAnchor () const inline
Definition at line 8772 of file context.cpp.
References MemberGroup::anchor(), and m_memberGroup.
Referenced by Private().
groupSubtitle()
TemplateVariant MemberGroupInfoContext::Private::groupSubtitle () const inline
Definition at line 8768 of file context.cpp.
Referenced by Private().
groupTitle()
TemplateVariant MemberGroupInfoContext::Private::groupTitle () const inline
Definition at line 8764 of file context.cpp.
References MemberGroup::header(), and m_memberGroup.
Referenced by Private().
inherited()
TemplateVariant MemberGroupInfoContext::Private::inherited () const inline
Definition at line 8803 of file context.cpp.
Referenced by Private().
memberGroups()
TemplateVariant MemberGroupInfoContext::Private::memberGroups () const inline
Definition at line 8776 of file context.cpp.
References MemberGroupListContext::alloc(), SharedPtr< T >::get(), m_cache, m_def, m_relPath, MemberGroupInfoContext::Private::Cachable::memberGroups, and SharedPtr< T >::reset().
Referenced by Private().
members()
TemplateVariant MemberGroupInfoContext::Private::members () const inline
Definition at line 8756 of file context.cpp.
References MemberListContext::alloc(), SharedPtr< T >::get(), m_cache, m_memberGroup, MemberGroupInfoContext::Private::Cachable::memberListContext, MemberGroup::members(), and SharedPtr< T >::reset().
Referenced by Private().
Member Data Documentation
m_cache
Cachable MemberGroupInfoContext::Private::m_cache mutable private
Definition at line 8817 of file context.cpp.
Referenced by docs(), memberGroups(), and members().
m_def
Definition* MemberGroupInfoContext::Private::m_def private
Definition at line 8808 of file context.cpp.
Referenced by docs(), and memberGroups().
m_memberGroup
const MemberGroup* MemberGroupInfoContext::Private::m_memberGroup private
Definition at line 8810 of file context.cpp.
Referenced by docs(), groupAnchor(), groupTitle(), and members().
m_relPath
QCString MemberGroupInfoContext::Private::m_relPath private
Definition at line 8809 of file context.cpp.
Referenced by docs(), and memberGroups().
s_inst
PropertyMapper< MemberGroupInfoContext::Private > MemberGroupInfoContext::Private::s_inst static private
Definition at line 8818 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp