Doxygen: DocSets Class Reference
DocSets Class Reference
A class that generates docset files.
#include <docsets.h>
Classes
struct NodeDef
Public Member Functions
DocSets ()
~DocSets ()
void initialize ()
void finalize ()
void incContentsDepth ()
void decContentsDepth ()
void addContentsItem (bool isDir, const char *name, const char *ref, const char *file, const char *anchor, bool separateIndex, bool addToNavIndex, Definition *def)
void addIndexItem (Definition *context, MemberDef *md, const char *sectionAnchor, const char *title)
void addIndexFile (const char *name)
void addImageFile (const char *)
void addStyleSheetFile (const char *)
Public Member Functions inherited from IndexIntf
virtual ~IndexIntf ()
Private Member Functions
void writeToken (FTextStream &t, const Definition *d, const QCString &type, const QCString &lang, const char *scope=0, const char *anchor=0, const char *decl=0)
QCString indent ()
Private Attributes
QFile * m_nf
QFile * m_tf
FTextStream m_nts
FTextStream m_tts
int m_dc
int m_id
QArray< bool > m_firstNode
SDict< NodeDef > m_nodes
SDict< void > m_scopes
Detailed Description
A class that generates docset files.
These files can be used to create context help for use within Apple's Xcode 3.0 development environment
Definition at line 31 of file docsets.h.
Constructor & Destructor Documentation
DocSets()
DocSets::DocSets ()
Definition at line 28 of file docsets.cpp.
References m_dc, m_id, m_nf, m_nodes, and m_tf.
~DocSets()
DocSets::~DocSets ()
Definition at line 37 of file docsets.cpp.
References m_nf, and m_tf.
Member Function Documentation
addContentsItem()
void DocSets::addContentsItem (bool isDir, const char * name, const char * ref, const char * file, const char * anchor, bool separateIndex, bool addToNavIndex, Definition * def) virtual
Implements IndexIntf.
Definition at line 232 of file docsets.cpp.
References convertToXML(), endl(), Doxygen::htmlFileExtension, indent(), m_dc, m_firstNode, and m_nts.
addImageFile()
void DocSets::addImageFile (const char *) inline virtual
Implements IndexIntf.
Definition at line 53 of file docsets.h.
addIndexFile()
void DocSets::addIndexFile (const char * name) virtual
Implements IndexIntf.
Definition at line 531 of file docsets.cpp.
addIndexItem()
void DocSets::addIndexItem (Definition * context, MemberDef * md, const char * sectionAnchor, const char * title) virtual
Implements IndexIntf.
Definition at line 277 of file docsets.cpp.
References MemberDef::anchor(), SDict< T >::append(), ClassDef::Category, ClassDef::Class, ClassDef::compoundType(), DefinitionIntf::definitionType(), SDict< T >::find(), MemberDef::getClassDef(), MemberDef::getFileDef(), MemberDef::getGroupDef(), Definition::getLanguage(), MemberDef::getNamespaceDef(), Definition::getOutputFileBase(), ClassDef::includeInfo(), IncludeInfo::includeName, ClassDef::Interface, MemberDef::isLinkable(), Definition::isLinkable(), MemberDef::isObjCMethod(), MemberDef::isObjCProperty(), MemberDef::isStatic(), ClassDef::isTemplate(), m_scopes, m_tts, MemberDef::memberDeclaration(), MemberDef::memberType(), MemberType_DCOP, MemberType_Define, MemberType_Enumeration, MemberType_EnumValue, MemberType_Event, MemberType_Friend, MemberType_Function, MemberType_Interface, MemberType_Property, MemberType_Service, MemberType_Signal, MemberType_Slot, MemberType_Typedef, MemberType_Variable, FileDef::name(), Definition::name(), ClassDef::Protocol, Definition::qualifiedName(), SrcLangExt_Cpp, SrcLangExt_CSharp, SrcLangExt_D, SrcLangExt_Fortran, SrcLangExt_IDL, SrcLangExt_Java, SrcLangExt_JS, SrcLangExt_Markdown, SrcLangExt_ObjC, SrcLangExt_PHP, SrcLangExt_Python, SrcLangExt_SQL, SrcLangExt_Tcl, SrcLangExt_Unknown, SrcLangExt_VHDL, SrcLangExt_XML, DefinitionIntf::TypeClass, DefinitionIntf::TypeFile, DefinitionIntf::TypeNamespace, and writeToken().
addStyleSheetFile()
void DocSets::addStyleSheetFile (const char *) inline virtual
Implements IndexIntf.
Definition at line 54 of file docsets.h.
decContentsDepth()
void DocSets::decContentsDepth () virtual
Implements IndexIntf.
Definition at line 221 of file docsets.cpp.
References endl(), indent(), m_dc, m_firstNode, and m_nts.
finalize()
void DocSets::finalize () virtual
Implements IndexIntf.
Definition at line 181 of file docsets.cpp.
References endl(), indent(), m_dc, m_firstNode, m_nf, m_nts, m_tf, and m_tts.
incContentsDepth()
void DocSets::incContentsDepth () virtual
Implements IndexIntf.
Definition at line 209 of file docsets.cpp.
References endl(), indent(), m_dc, m_firstNode, and m_nts.
indent()
QCString DocSets::indent () private
Definition at line 202 of file docsets.cpp.
References m_dc.
Referenced by addContentsItem(), decContentsDepth(), finalize(), and incContentsDepth().
initialize()
void DocSets::initialize () virtual
Implements IndexIntf.
Definition at line 43 of file docsets.cpp.
References Config_getString, endl(), err(), Doxygen::htmlFileExtension, m_dc, m_firstNode, m_nf, m_nts, m_tf, m_tts, and FTextStream::setDevice().
writeToken()
void DocSets::writeToken (FTextStream & t, const Definition * d, const QCString & type, const QCString & lang, const char * scope = 0, const char * anchor = 0, const char * decl = 0) private
Definition at line 487 of file docsets.cpp.
References Definition::briefDescriptionAsTooltip(), convertToXML(), endl(), Definition::getOutputFileBase(), Doxygen::htmlFileExtension, and Definition::name().
Referenced by addIndexItem().
Member Data Documentation
m_dc
int DocSets::m_dc private
Definition at line 78 of file docsets.h.
Referenced by addContentsItem(), decContentsDepth(), DocSets(), finalize(), incContentsDepth(), indent(), and initialize().
m_firstNode
QArray<bool> DocSets::m_firstNode private
Definition at line 80 of file docsets.h.
Referenced by addContentsItem(), decContentsDepth(), finalize(), incContentsDepth(), and initialize().
m_id
int DocSets::m_id private
Definition at line 79 of file docsets.h.
Referenced by DocSets().
m_nf
QFile* DocSets::m_nf private
Definition at line 74 of file docsets.h.
Referenced by DocSets(), finalize(), initialize(), and ~DocSets().
m_nodes
SDict<NodeDef> DocSets::m_nodes private
Definition at line 81 of file docsets.h.
Referenced by DocSets().
m_nts
FTextStream DocSets::m_nts private
Definition at line 76 of file docsets.h.
Referenced by addContentsItem(), decContentsDepth(), finalize(), incContentsDepth(), and initialize().
m_scopes
SDict<void> DocSets::m_scopes private
Definition at line 82 of file docsets.h.
Referenced by addIndexItem().
m_tf
QFile* DocSets::m_tf private
Definition at line 75 of file docsets.h.
Referenced by DocSets(), finalize(), initialize(), and ~DocSets().
m_tts
FTextStream DocSets::m_tts private
Definition at line 77 of file docsets.h.
Referenced by addIndexItem(), finalize(), and initialize().
The documentation for this class was generated from the following files:
src/docsets.h
src/docsets.cpp