Doxygen: TooltipManager Class Reference
TooltipManager Class Reference
#include <tooltip.h>
Classes
class Private
Public Member Functions
void clearTooltips ()
void addTooltip (Definition *d)
void writeTooltips (CodeOutputInterface &ol)
Static Public Member Functions
static TooltipManager * instance ()
Private Member Functions
TooltipManager ()
~TooltipManager ()
Private Attributes
Private * p
Static Private Attributes
static TooltipManager * s_theInstance = 0
Detailed Description
Definition at line 21 of file tooltip.h.
Constructor & Destructor Documentation
TooltipManager()
TooltipManager::TooltipManager () private
Definition at line 35 of file tooltip.cpp.
References p, and Private.
Referenced by instance().
~TooltipManager()
TooltipManager::~TooltipManager () private
Definition at line 40 of file tooltip.cpp.
References p.
Member Function Documentation
addTooltip()
void TooltipManager::addTooltip (Definition * d)
Definition at line 71 of file tooltip.cpp.
References Definition::anchor(), Config_getBool, escapeId(), Definition::getOutputFileBase(), Doxygen::htmlFileExtension, p, and TooltipManager::Private::tooltipInfo.
clearTooltips()
void TooltipManager::clearTooltips ()
Definition at line 54 of file tooltip.cpp.
References p, and TooltipManager::Private::tooltipInfo.
instance()
TooltipManager * TooltipManager::instance () static
Definition at line 45 of file tooltip.cpp.
References s_theInstance, and TooltipManager().
writeTooltips()
void TooltipManager::writeTooltips (CodeOutputInterface & ol)
Definition at line 93 of file tooltip.cpp.
References DocLinkInfo::anchor, SourceLinkInfo::anchor, Definition::anchor(), Definition::briefDescriptionAsTooltip(), MemberDef::declaration(), DefinitionIntf::definitionType(), SourceLinkInfo::file, Definition::getBodyDef(), Definition::getOutputFileBase(), Definition::getReference(), Definition::getSourceAnchor(), Definition::getSourceFileBase(), Definition::getStartBodyLine(), SourceLinkInfo::line, DocLinkInfo::name, FileDef::name(), p, Definition::qualifiedName(), DocLinkInfo::ref, TooltipManager::Private::tooltipInfo, DefinitionIntf::TypeMember, DocLinkInfo::url, SourceLinkInfo::url, and CodeOutputInterface::writeTooltip().
Member Data Documentation
p
Private* TooltipManager::p private
Definition at line 30 of file tooltip.h.
Referenced by addTooltip(), clearTooltips(), TooltipManager(), writeTooltips(), and ~TooltipManager().
s_theInstance
TooltipManager * TooltipManager::s_theInstance = 0 static private
Definition at line 34 of file tooltip.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/tooltip.h
src/tooltip.cpp