Doxygen: src/util.cpp File Reference
util.cpp File Reference
#include <stdlib.h>
#include <ctype.h>
#include <errno.h>
#include <math.h>
#include <limits.h>
#include "md5.h"
#include <qregexp.h>
#include <qfileinfo.h>
#include <qdir.h>
#include <qdatetime.h>
#include <qcache.h>
#include "util.h"
#include "message.h"
#include "classdef.h"
#include "filedef.h"
#include "doxygen.h"
#include "outputlist.h"
#include "defargs.h"
#include "language.h"
#include "config.h"
#include "htmlhelp.h"
#include "example.h"
#include "version.h"
#include "groupdef.h"
#include "reflist.h"
#include "pagedef.h"
#include "debug.h"
#include "searchindex.h"
#include "textdocvisitor.h"
#include "portable.h"
#include "parserintf.h"
#include "bufstr.h"
#include "image.h"
#include "growbuf.h"
#include "entry.h"
#include "arguments.h"
#include "memberlist.h"
#include "classlist.h"
#include "namespacedef.h"
#include "membername.h"
#include "filename.h"
#include "membergroup.h"
#include "dirdef.h"
#include "htmlentity.h"
Classes
class AccessStack
Helper class representing the stack of items considered while resolving the scope.
struct AccessStack::AccessElem
Element in the stack.
struct CharAroundSpace
struct CharAroundSpace::CharElem
struct FindFileCacheElem
Cache element for the file name to FileDef mapping cache.
struct Lang2ExtMap
struct Marker
Macros
#define ENABLE_TRACINGSUPPORT 0
#define ALGO_COUNT 1
#define ALGO_CRC16 2
#define ALGO_MD5 3
#define MAP_ALGO ALGO_MD5
#define REL_PATH_TO_ROOT "../../"
#define MATCH
#define NOMATCH
#define HEXTONUM(x)
Functions
QCString removeAnonymousScopes (const QCString &s)
QCString replaceAnonymousScopes (const QCString &s, const char *replacement)
QCString stripAnonymousNamespaceScope (const QCString &s)
void writePageRef (OutputDocInterface &od, const char *cn, const char *mn)
QCString generateMarker (int id)
static QCString stripFromPath (const QCString &path, QStrList &l)
QCString stripFromPath (const QCString &path)
QCString stripFromIncludePath (const QCString &path)
int guessSection (const char *name)
QCString resolveTypeDef (Definition *context, const QCString &qualifiedName, Definition **typedefContext)
ClassDef * getClass (const char *n)
NamespaceDef * getResolvedNamespace (const char *name)
static ClassDef * getResolvedClassRec (Definition *scope, FileDef *fileScope, const char *n, MemberDef **pTypeDef, QCString *pTemplSpec, QCString *pResolvedType)
int isAccessibleFromWithExpScope (Definition *scope, FileDef *fileScope, Definition *item, const QCString &explicitScopePart)
ClassDef * newResolveTypedef (FileDef *fileScope, MemberDef *md, MemberDef **pMemType, QCString *pTemplSpec, QCString *pResolvedType, ArgumentList *actTemplParams)
static QCString substTypedef (Definition *scope, FileDef *fileScope, const QCString &name, MemberDef **pTypeDef=0)
static Definition * endOfPathIsUsedClass (SDict< Definition > *cl, const QCString &localName)
static Definition * followPath (Definition *start, FileDef *fileScope, const QCString &path)
bool accessibleViaUsingClass (const SDict< Definition > *cl, FileDef *fileScope, Definition *item, const QCString &explicitScopePart="")
bool accessibleViaUsingNamespace (const NamespaceSDict *nl, FileDef *fileScope, Definition *item, const QCString &explicitScopePart="")
int isAccessibleFrom (Definition *scope, FileDef *fileScope, Definition *item)
int computeQualifiedIndex (const QCString &name)
static void getResolvedSymbol (Definition *scope, FileDef *fileScope, Definition *d, const QCString &explicitScopePart, ArgumentList *actTemplParams, int &minDistance, ClassDef *&bestMatch, MemberDef *&bestTypedef, QCString &bestTemplSpec, QCString &bestResolvedType)
ClassDef * getResolvedClass (Definition *scope, FileDef *fileScope, const char *n, MemberDef **pTypeDef, QCString *pTemplSpec, bool mayBeUnlinkable, bool mayBeHidden, QCString *pResolvedType)
static bool findOperator (const QCString &s, int i)
static bool findOperator2 (const QCString &s, int i)
QCString removeRedundantWhiteSpace (const QCString &s)
int findParameterList (const QCString &name)
Returns the position in the string where a function parameter list begins, or -1 if one is not found.
bool rightScopeMatch (const QCString &scope, const QCString &name)
bool leftScopeMatch (const QCString &scope, const QCString &name)
void linkifyText (const TextGeneratorIntf &out, Definition *scope, FileDef *fileScope, Definition *self, const char *text, bool autoBreak, bool external, bool keepSpaces, int indentLevel)
void writeExample (OutputList &ol, ExampleSDict *ed)
QCString argListToString (ArgumentList *al, bool useCanonicalType, bool showDefVals)
QCString tempArgListToString (ArgumentList *al, SrcLangExt lang)
void setAnchors (MemberList *ml)
int filterCRLF (char *buf, int len)
static QCString getFilterFromList (const char *name, const QStrList &filterList, bool &found)
QCString getFileFilter (const char *name, bool isSourceCode)
QCString transcodeCharacterStringToUTF8 (const QCString &input)
QCString fileToString (const char *name, bool filter, bool isSourceCode)
QCString dateToString (bool includeTime)
QCString yearToString ()
int minClassDistance (const ClassDef *cd, const ClassDef *bcd, int level)
Protection classInheritedProtectionLevel (ClassDef *cd, ClassDef *bcd, Protection prot, int level)
static QCString trimTemplateSpecifiers (const QCString &namespaceName, const QCString &className, const QCString &s)
static int findScopePattern (const QCString &pattern, const QCString &s, int p, int *len)
static QCString trimScope (const QCString &name, const QCString &s)
void trimBaseClassScope (BaseClassList *bcl, QCString &s, int level=0)
static void stripIrrelevantString (QCString &target, const QCString &str)
void stripIrrelevantConstVolatile (QCString &s)
static bool matchArgument (const Argument *srcA, const Argument *dstA, const QCString &className, const QCString &namespaceName, NamespaceSDict *usingNamespaces, SDict< Definition > *usingClasses)
bool matchArguments (ArgumentList *srcAl, ArgumentList *dstAl, const char *cl, const char *ns, bool checkCV, NamespaceSDict *usingNamespaces, SDict< Definition > *usingClasses)
static QCString stripDeclKeywords (const QCString &s)
static QCString extractCanonicalType (Definition *d, FileDef *fs, QCString type)
QCString getCanonicalTemplateSpec (Definition *d, FileDef *fs, const QCString &spec)
static QCString getCanonicalTypeForIdentifier (Definition *d, FileDef *fs, const QCString &word, QCString *tSpec, int count=0)
static QCString extractCanonicalArgType (Definition *d, FileDef *fs, const Argument *arg)
static bool matchArgument2 (Definition *srcScope, FileDef *srcFileScope, Argument *srcA, Definition *dstScope, FileDef *dstFileScope, Argument *dstA)
bool matchArguments2 (Definition *srcScope, FileDef *srcFileScope, ArgumentList *srcAl, Definition *dstScope, FileDef *dstFileScope, ArgumentList *dstAl, bool checkCV)
void mergeArguments (ArgumentList *srcAl, ArgumentList *dstAl, bool forceNameOverwrite)
static void findMembersWithSpecificName (MemberName *mn, const char *args, bool checkStatics, FileDef *currentFile, bool checkCV, const char *forceTagFile, QList< MemberDef > &members)
bool getDefs (const QCString &scName, const QCString &mbName, const char *args, MemberDef *&md, ClassDef *&cd, FileDef *&fd, NamespaceDef *&nd, GroupDef *&gd, bool forceEmptyScope, FileDef *currentFile, bool checkCV, const char *forceTagFile)
static bool getScopeDefs (const char *docScope, const char *scope, ClassDef *&cd, NamespaceDef *&nd)
static bool isLowerCase (QCString &s)
bool resolveRef (const char *scName, const char *name, bool inSeeBlock, Definition **resContext, MemberDef **resMember, bool lookForSpecialization, FileDef *currentFile, bool checkScope)
QCString linkToText (SrcLangExt lang, const char *link, bool isFileName)
bool resolveLink (const char *scName, const char *lr, bool, Definition **resContext, QCString &resAnchor)
bool generateLink (OutputDocInterface &od, const char *clName, const char *lr, bool inSeeBlock, const char *lt)
void generateFileRef (OutputDocInterface &od, const char *name, const char *text)
static QCache< FindFileCacheElem > g_findFileDefCache (5000)
FileDef * findFileDef (const FileNameDict *fnDict, const char *n, bool &ambig)
QCString showFileDefMatches (const FileNameDict *fnDict, const char *n)
QCString substitute (const QCString &s, const QCString &src, const QCString &dst)
substitute all occurrences of src in s by dst
QCString substituteKeywords (const QCString &s, const char *title, const char *projName, const char *projNum, const char *projBrief)
int getPrefixIndex (const QCString &name)
static void initBaseClassHierarchy (BaseClassList *bcl)
bool classHasVisibleChildren (ClassDef *cd)
void initClassHierarchy (ClassSDict *cl)
bool hasVisibleRoot (BaseClassList *bcl)
QCString escapeCharsInString (const char *name, bool allowDots, bool allowUnderscore)
QCString convertNameToFile (const char *name, bool allowDots, bool allowUnderscore)
QCString relativePathToRoot (const char *name)
void createSubDirs (QDir &d)
void extractNamespaceName (const QCString &scopeName, QCString &className, QCString &namespaceName, bool allowEmptyClass)
QCString insertTemplateSpecifierInScope (const QCString &scope, const QCString &templ)
QCString stripScope (const char *name)
QCString convertToId (const char *s)
QCString convertToXML (const char *s)
QCString convertToHtml (const char *s, bool keepEntities)
QCString convertToJSString (const char *s)
QCString convertToLaTeX (const QCString &s, bool insideTabbing, bool keepSpaces)
QCString convertCharEntitiesToUTF8 (const QCString &s)
QCString getOverloadDocs ()
void addMembersToMemberGroup (MemberList *ml, MemberGroupSDict **ppMemberGroupSDict, Definition *context)
int extractClassNameFromType (const QCString &type, int &pos, QCString &name, QCString &templSpec, SrcLangExt lang)
QCString normalizeNonTemplateArgumentsInString (const QCString &name, Definition *context, const ArgumentList *formalArgs)
QCString substituteTemplateArgumentsInString (const QCString &name, ArgumentList *formalArgs, ArgumentList *actualArgs)
QList< ArgumentList > * copyArgumentLists (const QList< ArgumentList > *srcLists)
QCString stripTemplateSpecifiersFromScope (const QCString &fullName, bool parentOnly, QCString *pLastScopeStripped)
QCString mergeScopes (const QCString &leftScope, const QCString &rightScope)
int getScopeFragment (const QCString &s, int p, int *l)
PageDef * addRelatedPage (const char *name, const QCString &ptitle, const QCString &doc, QList< SectionInfo > *, const char *fileName, int startLine, const QList< ListItemInfo > *sli, GroupDef *gd, TagInfo *tagInfo, SrcLangExt lang)
void addRefItem (const QList< ListItemInfo > *sli, const char *key, const char *prefix, const char *name, const char *title, const char *args, Definition *scope)
bool recursivelyAddGroupListToTitle (OutputList &ol, Definition *d, bool root)
void addGroupListToTitle (OutputList &ol, Definition *d)
void filterLatexString (FTextStream &t, const char *str, bool insideTabbing, bool insidePre, bool insideItem, bool keepSpaces)
QCString latexEscapeLabelName (const char *s, bool insideTabbing)
QCString latexEscapeIndexChars (const char *s, bool insideTabbing)
QCString latexEscapePDFString (const char *s)
QCString rtfFormatBmkStr (const char *name)
bool checkExtension (const char *fName, const char *ext)
QCString stripExtensionGeneral (const char *fName, const char *ext)
QCString stripExtension (const char *fName)
void replaceNamespaceAliases (QCString &scope, int i)
QCString stripPath (const char *s)
bool containsWord (const QCString &s, const QCString &word)
returns TRUE iff string s contains word w
bool findAndRemoveWord (QCString &s, const QCString &word)
QCString stripLeadingAndTrailingEmptyLines (const QCString &s, int &docLine)
Special version of QCString::stripWhiteSpace() that only strips completely blank lines.
bool updateLanguageMapping (const QCString &extension, const QCString &language)
void initDefaultExtensionMapping ()
void addCodeOnlyMappings ()
SrcLangExt getLanguageFromFileName (const QCString fileName)
MemberDef * getMemberFromSymbol (Definition *scope, FileDef *fileScope, const char *n)
bool checkIfTypedef (Definition *scope, FileDef *fileScope, const char *n)
const char * writeUtf8Char (FTextStream &t, const char *s)
int nextUtf8CharPosition (const QCString &utf8Str, int len, int startPos)
QCString parseCommentAsText (const Definition *scope, const MemberDef *md, const QCString &doc, const QCString &fileName, int lineNr)
static QCString expandAliasRec (const QCString s, bool allowRecursion=FALSE)
static int findEndOfCommand (const char *s)
For a string s that starts with a command name, returns the character offset within that string representing the first character after the command.
static QCString replaceAliasArguments (const QCString &aliasValue, const QCString &argList)
Replaces the markers in an alias definition aliasValue with the corresponding values found in the comma separated argument list argList and the returns the result after recursive alias expansion.
static QCString escapeCommas (const QCString &s)
int countAliasArguments (const QCString argList)
QCString extractAliasArgs (const QCString &args, int pos)
QCString resolveAliasCmd (const QCString aliasCmd)
QCString expandAlias (const QCString &aliasName, const QCString &aliasValue)
void writeTypeConstraints (OutputList &ol, Definition *d, ArgumentList *al)
void stackTrace ()
static int transcodeCharacterBuffer (const char *fileName, BufStr &srcBuf, int size, const char *inputEncoding, const char *outputEncoding)
bool readInputFile (const char *fileName, BufStr &inBuf, bool filter, bool isSourceCode)
read a file name fileName and optionally filter and transcode it
QCString filterTitle (const QCString &title)
bool patternMatch (const QFileInfo &fi, const QStrList *patList)
QCString externalLinkTarget ()
QCString externalRef (const QCString &relPath, const QCString &ref, bool href)
void writeColoredImgData (const char *dir, ColoredImgDataItem data[])
Writes the intensity only bitmap representated by data as an image to directory dir using the colors defined by HTML_COLORSTYLE_*.
QCString replaceColorMarkers (const char *str)
Replaces any markers of the form ##AA in input string str by new markers of the form #AABBCC, where #AABBCC represents a valid color, based on the intensity represented by hex number AA and the current HTML_COLORSTYLE_* settings.
bool copyFile (const QCString &src, const QCString &dest)
Copies the contents of file with name src to the newly created file with name dest.
QCString extractBlock (const QCString text, const QCString marker)
Returns the section of text, in between a pair of markers.
int lineBlock (const QCString text, const QCString marker)
Returns the line number of the line following the line with the marker.
QCString langToString (SrcLangExt lang)
Returns a string representation of lang.
QCString getLanguageSpecificSeparator (SrcLangExt lang, bool classScope)
Returns the scope separator to use given the programming language lang.
QCString correctURL (const QCString &url, const QCString &relPath)
Corrects URL url according to the relative path relPath.
bool protectionLevelVisible (Protection prot)
QCString stripIndentation (const QCString &s)
bool fileVisibleInIndex (FileDef *fd, bool &genSourceFile)
void addDocCrossReference (MemberDef *src, MemberDef *dst)
uint getUtf8Code (const QCString &s, int idx)
Get one unicode character as an unsigned integer from utf-8 string.
uint getUtf8CodeToLower (const QCString &s, int idx)
Returns one unicode character as an unsigned integer from utf-8 string, making the character lower case if it was upper case.
uint getUtf8CodeToUpper (const QCString &s, int idx)
Returns one unicode character as an unsigned integer from utf-8 string, making the character upper case if it was lower case.
bool namespaceHasVisibleChild (NamespaceDef *nd, bool includeClasses)
bool classVisibleInIndex (ClassDef *cd)
QCString extractDirection (QCString &docs)
void convertProtectionLevel (MemberListType inListType, Protection inProt, int *outListType1, int *outListType2)
Computes for a given list type inListType, which are the the corresponding list type(s) in the base class that are to be added to this list.
bool mainPageHasTitle ()
QCString getDotImageExtension (void)
bool openOutputFile (const char *outFile, QFile &f)
void writeExtraLatexPackages (FTextStream &t)
Variables
const int maxInheritanceDepth = 100000
static QDict< MemberDef > g_resolvedTypedefs
static QDict< Definition > g_visitedNamespaces
const int MAX_STACK_SIZE = 1000
static const char constScope [] = { 'c', 'o', 'n', 's', 't', ':' }
static const char virtualScope [] = { 'v', 'i', 'r', 't', 'u', 'a', 'l', ':' }
static const char operatorScope [] = { 'o', 'p', 'e', 'r', 'a', 't', 'o', 'r', '?', '?', '?' }
static CharAroundSpace g_charAroundSpace
static QDict< int > g_extLookup
static struct Lang2ExtMap g_lang2extMap []
static QDict< void > aliasesProcessed
Macro Definition Documentation
ALGO_COUNT
#define ALGO_COUNT 1
Definition at line 83 of file util.cpp.
ALGO_CRC16
#define ALGO_CRC16 2
Definition at line 84 of file util.cpp.
ALGO_MD5
#define ALGO_MD5 3
Definition at line 85 of file util.cpp.
ENABLE_TRACINGSUPPORT
#define ENABLE_TRACINGSUPPORT 0
Definition at line 66 of file util.cpp.
HEXTONUM
#define HEXTONUM (x)
Value:
(((x)>='0' && (x)<='9') ? ((x)-'0') :       \
                     ((x)>='a' && (x)<='f') ? ((x)-'a'+10) :    \
                     ((x)>='A' && (x)<='F') ? ((x)-'A'+10) : 0)
Referenced by replaceColorMarkers().
MAP_ALGO
#define MAP_ALGO ALGO_MD5
Definition at line 89 of file util.cpp.
MATCH
#define MATCH
Definition at line 3009 of file util.cpp.
Referenced by matchArgument(), matchArgument2(), matchArguments(), and matchArguments2().
NOMATCH
#define NOMATCH
Definition at line 3010 of file util.cpp.
Referenced by matchArgument(), matchArgument2(), matchArguments(), and matchArguments2().
REL_PATH_TO_ROOT
#define REL_PATH_TO_ROOT "../../"
Definition at line 91 of file util.cpp.
Referenced by relativePathToRoot().
Function Documentation
accessibleViaUsingClass()
bool accessibleViaUsingClass (const SDict< Definition > * cl, FileDef * fileScope, Definition * item, const QCString & explicitScopePart = "")
Definition at line 809 of file util.cpp.
References followPath().
Referenced by isAccessibleFrom().
accessibleViaUsingNamespace()
bool accessibleViaUsingNamespace (const NamespaceSDict * nl, FileDef * fileScope, Definition * item, const QCString & explicitScopePart = "")
Definition at line 832 of file util.cpp.
References SDict< T >::find(), followPath(), Definition::getOuterScope(), NamespaceDef::getUsedNamespaces(), SDict< NamespaceDef >::Iterator, and Definition::name().
Referenced by isAccessibleFrom(), and isAccessibleFromWithExpScope().
addCodeOnlyMappings()
void addCodeOnlyMappings ()
Definition at line 7166 of file util.cpp.
References updateLanguageMapping().
Referenced by generateOutput().
addDocCrossReference()
void addDocCrossReference (MemberDef * src, MemberDef * dst)
Definition at line 8325 of file util.cpp.
References Definition::addSourceReferencedBy(), Definition::addSourceReferences(), Config_getBool, MemberDef::hasCallerGraph(), MemberDef::hasCallGraph(), MemberDef::isEnumerate(), MemberDef::isTypedef(), MemberDef::memberDeclaration(), MemberDef::memberDefinition(), and MemberDef::showInCallGraph().
addGroupListToTitle()
void addGroupListToTitle (OutputList & ol, Definition * d)
Definition at line 6631 of file util.cpp.
References recursivelyAddGroupListToTitle().
Referenced by NamespaceDef::writeDocumentation(), GroupDef::writeDocumentation(), FileDef::writeDocumentation(), and ClassDef::writeDocumentation().
addMembersToMemberGroup()
void addMembersToMemberGroup (MemberList * ml, MemberGroupSDict ** ppMemberGroupSDict, Definition * context)
Definition at line 5970 of file util.cpp.
References MemberGroupInfo::doc, MemberGroupInfo::docFile, MemberGroupInfo::docLine, MemberDef::enumFieldList(), MemberDef::getMemberGroupId(), MemberGroupInfo::header, MemberGroup::insertMember(), MemberDef::isEnumerate(), MemberGroupInfo::m_sli, Doxygen::memGrpInfoDict, SIntDict< T >::setAutoDelete(), MemberDef::setMemberGroup(), MemberGroup::setRefItems(), and MemberList::take().
addRefItem()
void addRefItem (const QList< ListItemInfo > * sli, const char * key, const char * prefix, const char * name, const char * title, const char * args, Definition * scope)
Definition at line 6559 of file util.cpp.
References RefItem::args, Config_getBool, RefList::getRefItem(), RefList::insertIntoList(), ListItemInfo::itemId, RefItem::name, RefItem::prefix, RefItem::scope, RefItem::title, ListItemInfo::type, and Doxygen::xrefLists.
Referenced by MemberDef::addListReference(), GroupDef::addListReferences(), NamespaceDef::addListReferences(), MemberGroup::addListReferences(), FileDef::addListReferences(), ClassDef::addListReferences(), addListReferences(), and buildPageList().
addRelatedPage()
PageDef* addRelatedPage (const char * name, const QCString & ptitle, const QCString & doc, QList< SectionInfo > * , const char * fileName, int startLine, const QList< ListItemInfo > * sli, GroupDef * gd, TagInfo * tagInfo, SrcLangExt lang)
Definition at line 6472 of file util.cpp.
References GroupDef::addPage(), SDict< T >::append(), TagInfo::fileName, SectionInfo::fileName, SDict< T >::find(), GroupDef::getOutputFileBase(), PageDef::getOutputFileBase(), Definition::getReference(), Doxygen::htmlFileExtension, SectionInfo::lineNr, Definition::name(), SectionInfo::Page, Doxygen::pageSDict, Doxygen::sectionDict, Definition::setDocumentation(), PageDef::setFileName(), Definition::setLanguage(), Definition::setReference(), Definition::setRefItems(), TagInfo::tagName, PageDef::title(), and warn().
argListToString()
QCString argListToString (ArgumentList * al, bool useCanonicalType, bool showDefVals)
Definition at line 2231 of file util.cpp.
References Argument::array, Argument::attrib, Argument::canType, ArgumentList::constSpecifier, Argument::defval, Argument::name, ArgumentList::pureSpecifier, ArgumentList::refQualifier, RefQualifierLValue, RefQualifierRValue, removeRedundantWhiteSpace(), ArgumentList::trailingReturnType, Argument::type, and ArgumentList::volatileSpecifier.
Referenced by checkArgumentName(), checkUndocumentedParams(), findGlobalMember(), and findMember().
checkExtension()
bool checkExtension (const char * fName, const char * ext)
Definition at line 6890 of file util.cpp.
Referenced by copyLatexStyleSheet(), and writeDefaultHeaderPart1().
checkIfTypedef()
bool checkIfTypedef (Definition * scope, FileDef * fileScope, const char * n)
Returns true iff the given name string appears to be a typedef in scope.
Definition at line 7266 of file util.cpp.
References getMemberFromSymbol(), and MemberDef::isTypedef().
Referenced by isVarWithConstructor().
classHasVisibleChildren()
bool classHasVisibleChildren (ClassDef * cd)
Definition at line 5284 of file util.cpp.
References ClassDef::baseClasses(), Definition::getLanguage(), SrcLangExt_VHDL, and ClassDef::subClasses().
Referenced by NestingNodeContext::Private::addClasses(), writeClassTree(), and writeClassTreeForList().
classInheritedProtectionLevel()
Protection classInheritedProtectionLevel (ClassDef * cd, ClassDef * bcd, Protection prot, int level)
Definition at line 2644 of file util.cpp.
References ClassDef::baseClasses(), ClassDef::categoryOf(), classInheritedProtectionLevel(), err(), Definition::name(), Private, and Protected.
Referenced by classInheritedProtectionLevel().
classVisibleInIndex()
bool classVisibleInIndex (ClassDef * cd)
Definition at line 8470 of file util.cpp.
References Config_getBool, ClassDef::isLinkable(), and ClassDef::isLinkableInProject().
Referenced by NestingContext::Private::addClasses(), and writeClassTree().
computeQualifiedIndex()
int computeQualifiedIndex (const QCString & name)
Definition at line 1204 of file util.cpp.
Referenced by Definition::addToMap(), getMemberFromSymbol(), and getResolvedClassRec().
containsWord()
bool containsWord (const QCString & s, const QCString & word)
returns TRUE iff string s contains word w
Definition at line 6942 of file util.cpp.
convertCharEntitiesToUTF8()
QCString convertCharEntitiesToUTF8 (const QCString & s)
Definition at line 5925 of file util.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::clear(), GrowBuf::get(), HtmlEntityMapper::instance(), HtmlEntityMapper::name2sym(), and DocSymbol::Sym_Unknown.
Referenced by convertToJSString(), generateXMLForPage(), parseCommentAsText(), XmlDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), and LatexDocVisitor::visitPre().
convertNameToFile()
QCString convertNameToFile (const char * name, bool allowDots, bool allowUnderscore)
This function determines the file name on disk of an item given its name, which could be a class name with template arguments, so special characters need to be escaped.
Definition at line 5456 of file util.cpp.
References Config_getBool, escapeCharsInString(), and Doxygen::htmlDirMap.
Referenced by buildExampleList(), ClassDef::ClassDef(), DocAnchor::DocAnchor(), DocCite::DocCite(), VhdlDocGen::findConstraintFile(), GroupDef::GroupDef(), NamespaceDef::NamespaceDef(), PageDef::PageDef(), RefList::RefList(), FileDef::setDiskName(), and NamespaceDef::setFileName().
convertProtectionLevel()
void convertProtectionLevel (MemberListType inListType, Protection inProt, int * outListType1, int * outListType2)
Computes for a given list type inListType, which are the the corresponding list type(s) in the base class that are to be added to this list.
So for public inheritance, the mapping is 1-1, so outListType1=inListType Private members are to be hidden completely.
For protected inheritance, both protected and public members of the base class should be joined in the protected member section.
For private inheritance, both protected and public members of the base class should be joined in the private member section.
Definition at line 8514 of file util.cpp.
References Config_getBool, MemberListType_priAttribs, MemberListType_priMethods, MemberListType_priSlots, MemberListType_priStaticAttribs, MemberListType_priStaticMethods, MemberListType_priTypes, MemberListType_proAttribs, MemberListType_proMethods, MemberListType_proSlots, MemberListType_proStaticAttribs, MemberListType_proStaticMethods, MemberListType_proTypes, MemberListType_pubAttribs, MemberListType_pubMethods, MemberListType_pubSlots, MemberListType_pubStaticAttribs, MemberListType_pubStaticMethods, MemberListType_pubTypes, Private, Protected, and Public.
Referenced by ClassDef::countInheritedDecMembers(), InheritedMemberInfoListContext::Private::findInheritedMembers(), and ClassDef::writeInheritedMemberDeclarations().
convertToHtml()
QCString convertToHtml (const char * s, bool keepEntities)
Converts a string to a HTML-encoded string
Definition at line 5849 of file util.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::clear(), GrowBuf::get(), and isId().
Referenced by HtmlCodeGenerator::_writeCodeLink(), HtmlHelp::addContentsItem(), HtmlEscaper::escape(), FTVHelp::generateLink(), ClassContext::Private::inheritanceDiagram(), Definition::navigationPathAsString(), HtmlGenerator::startFile(), HtmlDocVisitor::startLink(), substituteHtmlKeywords(), HtmlDocVisitor::visit(), writeDirHierarchy(), writeDirTreeNode(), writeGroupTreeNode(), HtmlGenerator::writeInheritedSectionTitle(), TextGeneratorHtml::writeLink(), writeMapArea(), HtmlGenerator::writePageFooter(), NamespaceDef::writeQuickMemberLinks(), GroupDef::writeQuickMemberLinks(), FileDef::writeQuickMemberLinks(), ClassDef::writeQuickMemberLinks(), HtmlGenerator::writeSearchPage(), TextGeneratorHtml::writeString(), and Definition::writeToc().
convertToId()
QCString convertToId (const char * s)
Converts a string to a HTML id string
Definition at line 5788 of file util.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::clear(), and GrowBuf::get().
Referenced by HtmlGenerator::endClassDiagram(), and ClassContext::Private::inheritanceDiagram().
convertToJSString()
QCString convertToJSString (const char * s)
Definition at line 5895 of file util.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::clear(), convertCharEntitiesToUTF8(), and GrowBuf::get().
Referenced by generateJSLink(), generateJSNavTree(), renderMemberIndicesAsJs(), and renderQuickLinksAsJs().
convertToLaTeX()
QCString convertToLaTeX (const QCString & s, bool insideTabbing, bool keepSpaces)
Definition at line 5915 of file util.cpp.
References filterLatexString().
Referenced by LatexGenerator::endIndexSection(), LatexEscaper::escape(), LatexGenerator::startIndexSection(), and TextGeneratorLatex::writeString().
convertToXML()
QCString convertToXML (const char * s)
Converts a string to an XML-encoded string
Definition at line 5820 of file util.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::clear(), and GrowBuf::get().
Referenced by DocSets::addContentsItem(), EclipseHelp::addContentsItem(), DocbookDocVisitor::filter(), XmlDocVisitor::filter(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), generateDocbookForMember(), generateDocbookForPage(), generateDocbookSection(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), generateXMLSection(), htmlAttribsToString(), EclipseHelp::initialize(), QhpXmlWriter::openCloseContent(), QhpXmlWriter::openPureHelper(), SymbolContext::Private::scope(), DocbookDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), XmlDocVisitor::visitPre(), visitPreStart(), SearchIndexExternal::write(), Definition::writeDocAnchorsToTagFile(), DotNode::writeDocbook(), writeDocbookString(), DotDirDeps::writeGraph(), writeGraphHeader(), DotGroupCollaboration::writeGraphHeader(), writeInnerClasses(), writeInnerDirs(), writeInnerFiles(), writeInnerGroups(), writeInnerNamespaces(), writeInnerPages(), writeJavascriptSearchIndex(), writeListOfAllMembers(), writeMapArea(), writeMemberReference(), NamespaceDef::writeTagFile(), PageDef::writeTagFile(), GroupDef::writeTagFile(), DirDef::writeTagFile(), VhdlDocGen::writeTagFile(), FileDef::writeTagFile(), MemberDef::writeTagFile(), ClassDef::writeTagFile(), DocSets::writeToken(), DotNode::writeXML(), writeXMLLink(), and writeXMLString().
copyArgumentLists()
QList<ArgumentList>* copyArgumentLists (const QList< ArgumentList > * srcLists)
Makes a deep copy of the list of argument lists srcLists. Will allocate memory, that is owned by the caller.
Definition at line 6308 of file util.cpp.
References ArgumentList::deepCopy().
Referenced by Entry::Entry(), and MemberDef::setDefinitionTemplateParameterLists().
copyFile()
bool copyFile (const QCString & src, const QCString & dest)
Copies the contents of file with name src to the newly created file with name dest.
Returns TRUE if successful.
Definition at line 8077 of file util.cpp.
References err().
Referenced by copyExtraFiles(), copyLatexStyleSheet(), copyLogo(), copyStyleSheet(), and CiteDict::generatePage().
correctURL()
QCString correctURL (const QCString & url, const QCString & relPath)
Corrects URL url according to the relative path relPath.
Returns the corrected URL. For absolute URLs no correction will be done.
Definition at line 8220 of file util.cpp.
Referenced by startQuickIndexItem(), HtmlDocVisitor::visitPre(), and writeIndexHierarchyEntries().
countAliasArguments()
int countAliasArguments (const QCString argList)
Definition at line 7624 of file util.cpp.
References findEndOfCommand().
Referenced by expandAliasRec().
createSubDirs()
void createSubDirs (QDir & d)
Definition at line 5561 of file util.cpp.
References Config_getBool.
Referenced by generateDocbook(), generateOutputViaTemplate(), generateXML(), RTFGenerator::init(), ManGenerator::init(), LatexGenerator::init(), HtmlGenerator::init(), NamespaceDef::writeQuickMemberLinks(), GroupDef::writeQuickMemberLinks(), FileDef::writeQuickMemberLinks(), and ClassDef::writeQuickMemberLinks().
dateToString()
QCString dateToString (bool includeTime)
Definition at line 2561 of file util.cpp.
References portable_getenv(), theTranslator, Translator::trDateTime(), and warn_uncond().
Referenced by DoxygenContext::Private::date(), RTFGenerator::endIndexSection(), ManGenerator::endTitleHead(), substituteHtmlKeywords(), substituteKeywords(), writeDefaultHeaderPart1(), writeDefaultHeaderPart3(), and HtmlGenerator::writeLogoAsString().
endOfPathIsUsedClass()
static Definition* endOfPathIsUsedClass (SDict< Definition > * cl, const QCString & localName) static
Definition at line 731 of file util.cpp.
References Definition::localName().
Referenced by followPath().
escapeCharsInString()
QCString escapeCharsInString (const char * name, bool allowDots, bool allowUnderscore)
Definition at line 5344 of file util.cpp.
References GrowBuf::addChar(), GrowBuf::addStr(), GrowBuf::clear(), Config_getBool, and GrowBuf::get().
Referenced by convertNameToFile(), DotGfxHierarchyTable::createGraph(), PageDef::writeDocumentation(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotDirDeps::writeGraph(), and DotGroupCollaboration::writeGraph().
escapeCommas()
static QCString escapeCommas (const QCString & s) static
Definition at line 7539 of file util.cpp.
Referenced by expandAliasRec().
expandAlias()
QCString expandAlias (const QCString & aliasName, const QCString & aliasValue)
Definition at line 7683 of file util.cpp.
References expandAliasRec().
Referenced by expandAliases().
expandAliasRec()
static QCString expandAliasRec (const QCString s, bool allowRecursion = FALSE) static
Definition at line 7561 of file util.cpp.
References Doxygen::aliasDict, countAliasArguments(), escapeCommas(), extractAliasArgs(), and replaceAliasArguments().
Referenced by expandAlias(), replaceAliasArguments(), and resolveAliasCmd().
externalLinkTarget()
QCString externalLinkTarget ()
Definition at line 7961 of file util.cpp.
References Config_getBool.
Referenced by HtmlCodeGenerator::_writeCodeLink(), FTVHelp::generateLink(), replaceRef(), HtmlGenerator::startIndexItem(), HtmlDocVisitor::startLink(), HtmlGenerator::writeInheritedSectionTitle(), TextGeneratorHtml::writeLink(), writeMapArea(), and HtmlGenerator::writeObjectLink().
externalRef()
QCString externalRef (const QCString & relPath, const QCString & ref, bool href)
Definition at line 7967 of file util.cpp.
References Doxygen::tagDestinationDict.
Referenced by HtmlCodeGenerator::_writeCodeLink(), convertMapFile(), generateJSLink(), FTVHelp::generateLink(), SymbolContext::Private::relPath(), replaceRef(), HtmlGenerator::startIndexItem(), HtmlDocVisitor::startLink(), HtmlGenerator::writeInheritedSectionTitle(), writeJavascriptSearchIndex(), TextGeneratorHtml::writeLink(), writeMapArea(), HtmlGenerator::writeObjectLink(), and HtmlCodeGenerator::writeTooltip().
extractAliasArgs()
QCString extractAliasArgs (const QCString & args, int pos)
Definition at line 7643 of file util.cpp.
Referenced by expandAliasRec(), and findEndOfCommand().
extractBlock()
QCString extractBlock (const QCString text, const QCString marker)
Returns the section of text, in between a pair of markers.
Full lines are returned, excluding the lines on which the markers appear.
See also
routine lineBlock
Definition at line 8110 of file util.cpp.
Referenced by DocPara::handleInclude(), DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), and LatexDocVisitor::visit().
extractCanonicalArgType()
static QCString extractCanonicalArgType (Definition * d, FileDef * fs, const Argument * arg) static
Definition at line 3659 of file util.cpp.
References Argument::array, extractCanonicalType(), Argument::name, and Argument::type.
Referenced by matchArgument2().
extractCanonicalType()
static QCString extractCanonicalType (Definition * d, FileDef * fs, QCString type) static
Definition at line 3589 of file util.cpp.
References extractClassNameFromType(), getCanonicalTypeForIdentifier(), removeRedundantWhiteSpace(), and stripIrrelevantConstVolatile().
Referenced by extractCanonicalArgType(), and getCanonicalTemplateSpec().
extractClassNameFromType()
int extractClassNameFromType (const QCString & type, int & pos, QCString & name, QCString & templSpec, SrcLangExt lang)
Extracts a (sub-)string from type starting at pos that could form a class. The index of the match is returned and the found class name and a template argument list templSpec. If -1 is returned there are no more matches.
Definition at line 6066 of file util.cpp.
References SrcLangExt_Fortran.
Referenced by extractCanonicalType(), and findUsedClassesForClass().
extractDirection()
QCString extractDirection (QCString & docs)
Definition at line 8478 of file util.cpp.
Referenced by MemberContext::Private::paramDocs(), and MemberDef::writeDocumentation().
extractNamespaceName()
void extractNamespaceName (const QCString & scopeName, QCString & className, QCString & namespaceName, bool allowEmptyClass)
Input is a scopeName, output is the scopename split into a namespace part (as large as possible) and a classname part.
Definition at line 5581 of file util.cpp.
References getClass(), getResolvedNamespace(), and Definition::name().
Referenced by addClassToContext(), findMember(), and writeAlphabeticalClassList().
fileToString()
QCString fileToString (const char * name, bool filter, bool isSourceCode)
reads a file with name name and returns it as a string. If filter is TRUE the file will be filtered by any user specified input filter. If name is "-" the string will be read from standard input.
Definition at line 2506 of file util.cpp.
References err(), filterCRLF(), and readInputFile().
Referenced by DoxygenContext::Private::Cachable::Cachable(), LatexGenerator::endIndexSection(), FormulaList::generateBitmaps(), HtmlGenerator::init(), parseCode(), FileDef::parseSource(), readTextFileByName(), LatexGenerator::startIndexSection(), writeDocbookCodeBlock(), FileDef::writeSource(), HtmlGenerator::writeStyleInfo(), and writeXMLCodeBlock().
fileVisibleInIndex()
bool fileVisibleInIndex (FileDef * fd, bool & genSourceFile)
Definition at line 8313 of file util.cpp.
References Config_getBool, FileDef::generateSourceFile(), FileDef::isDocumentationFile(), FileDef::isLinkable(), and FileDef::isLinkableInProject().
Referenced by countFiles(), dirHasVisibleChildren(), generateJSTree(), writeDirHierarchy(), and writeDirTreeNode().
filterCRLF()
int filterCRLF (char * buf, int len)
takes the buf of the given length len and converts CR LF (DOS) or CR (MAC) line ending to LF (Unix). Returns the length of the converted content (i.e. the same as len (Unix, MAC) or smaller (DOS).
Definition at line 2366 of file util.cpp.
Referenced by fileToString(), and readInputFile().
filterLatexString()
void filterLatexString (FTextStream & t, const char * str, bool insideTabbing, bool insidePre, bool insideItem, bool keepSpaces)
Definition at line 6636 of file util.cpp.
References Config_getBool, HtmlEntityMapper::instance(), isId(), HtmlEntityMapper::latex(), HtmlEntityMapper::name2sym(), and DocSymbol::Sym_Unknown.
Referenced by LatexCodeGenerator::codify(), convertToLaTeX(), LatexGenerator::docify(), LatexDocVisitor::filter(), latexEscapeIndexChars(), latexEscapeLabelName(), writeDefaultHeaderPart1(), and TextGeneratorLatex::writeLink().
filterTitle()
QCString filterTitle (const QCString & title)
Definition at line 7876 of file util.cpp.
Referenced by PerlModGenerator::generatePerlModForPage(), generateXMLForPage(), mainPageHasOwnTitle(), HtmlGenerator::startFile(), PageDef::writeDocumentation(), writeExampleIndex(), writeIndex(), and writePages().
findAndRemoveWord()
bool findAndRemoveWord (QCString & s, const QCString & word)
Definition at line 6954 of file util.cpp.
Referenced by isVarWithConstructor().
findEndOfCommand()
static int findEndOfCommand (const char * s) static
For a string s that starts with a command name, returns the character offset within that string representing the first character after the command.
For an alias with argument, this is the offset to the character just after the argument list.
Examples:
s=="a b" returns 1
s=="a{2,3} b" returns 6 = s=="#" returns 0
Definition at line 7420 of file util.cpp.
References extractAliasArgs(), and isId().
Referenced by countAliasArguments(), and replaceAliasArguments().
findFileDef()
FileDef* findFileDef (const FileNameDict * fnDict, const char * n, bool & ambig)
Definition at line 5065 of file util.cpp.
References FindFileCacheElem::fileDef, g_findFileDefCache(), FileDef::getPath(), FindFileCacheElem::isAmbig, and stripFromIncludePath().
Referenced by addIncludeFile(), buildFileList(), findAndCopyImage(), findDocsForMemberOrCompound(), format_warn(), generateFileRef(), generateFileSources(), handleLinkedWord(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), parseFiles(), processLink(), readTextFileByName(), resolveLink(), resolveRef(), and DocbookDocVisitor::visitPost().
findMembersWithSpecificName()
static void findMembersWithSpecificName (MemberName * mn, const char * args, bool checkStatics, FileDef * currentFile, bool checkCV, const char * forceTagFile, QList< MemberDef > & members) static
Definition at line 3966 of file util.cpp.
References MemberDef::argumentList(), MemberDef::getFileDef(), MemberDef::getGroupDef(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), MemberDef::getReference(), Doxygen::globalScope, MemberDef::isDefine(), GroupDef::isLinkable(), FileDef::isLinkable(), MemberDef::isLinkable(), MemberDef::isReference(), MemberDef::isStatic(), matchArguments2(), and stringToArgumentList().
Referenced by getDefs().
findOperator()
static bool findOperator (const QCString & s, int i) static
Definition at line 1624 of file util.cpp.
findOperator2()
static bool findOperator2 (const QCString & s, int i) static
Definition at line 1638 of file util.cpp.
References isId().
findParameterList()
int findParameterList (const QCString & name)
Returns the position in the string where a function parameter list begins, or -1 if one is not found.
Definition at line 1928 of file util.cpp.
Referenced by resolveRef().
findScopePattern()
static int findScopePattern (const QCString & pattern, const QCString & s, int p, int * len) static
Parameters
pattern pattern to look for
s string to search in
p position to start
len resulting pattern length
Returns
position on which string is found, or -1 if not found
Definition at line 2766 of file util.cpp.
Referenced by trimScope().
followPath()
static Definition* followPath (Definition * start, FileDef * fileScope, const QCString & path) static
Starting with scope start, the string path is interpreted as a part of a qualified scope name (e.g. A::B::C), and the scope is searched. If found the scope definition is returned, otherwise 0 is returned.
Definition at line 753 of file util.cpp.
References DefinitionIntf::definitionType(), endOfPathIsUsedClass(), Definition::findInnerCompound(), getScopeFragment(), newResolveTypedef(), substTypedef(), DefinitionIntf::TypeFile, and DefinitionIntf::TypeNamespace.
Referenced by accessibleViaUsingClass(), accessibleViaUsingNamespace(), and isAccessibleFromWithExpScope().
g_findFileDefCache()
static QCache<FindFileCacheElem> g_findFileDefCache (5000) static
Referenced by findFileDef().
generateFileRef()
void generateFileRef (OutputDocInterface & od, const char * name, const char * text)
Definition at line 5010 of file util.cpp.
References BaseOutputDocInterface::docify(), findFileDef(), FileDef::getOutputFileBase(), Definition::getReference(), Doxygen::inputNameDict, FileDef::isLinkable(), and BaseOutputDocInterface::writeObjectLink().
generateLink()
bool generateLink (OutputDocInterface & od, const char * clName, const char * lr, bool inSeeBlock, const char * lt)
Definition at line 4968 of file util.cpp.
References DefinitionIntf::definitionType(), BaseOutputDocInterface::docify(), err(), Definition::getLanguage(), Definition::getOutputFileBase(), Definition::getReference(), Definition::isReference(), linkToText(), resolveLink(), SrcLangExt_Unknown, DefinitionIntf::TypeFile, DefinitionIntf::TypeGroup, BaseOutputDocInterface::writeObjectLink(), and writePageRef().
generateMarker()
QCString generateMarker (int id)
Generate a place holder for a position in a list. Used for translators to be able to specify different elements orders depending on whether text flows from left to right or visa versa.
Definition at line 266 of file util.cpp.
Referenced by TranslatorDutch::trWriteList(), TranslatorSlovene::trWriteList(), TranslatorCroatian::trWriteList(), TranslatorChinese::trWriteList(), TranslatorUkrainian::trWriteList(), TranslatorRussian::trWriteList(), TranslatorSlovak::trWriteList(), TranslatorArmenian::trWriteList(), TranslatorHungarian::trWriteList(), TranslatorIndonesian::trWriteList(), TranslatorSerbian::trWriteList(), TranslatorAfrikaans::trWriteList(), TranslatorMacedonian::trWriteList(), TranslatorGreek::trWriteList(), TranslatorLithuanian::trWriteList(), TranslatorPolish::trWriteList(), TranslatorEnglish::trWriteList(), TranslatorTurkish::trWriteList(), TranslatorCatalan::trWriteList(), TranslatorSpanish::trWriteList(), TranslatorEsperanto::trWriteList(), TranslatorPortuguese::trWriteList(), TranslatorPersian::trWriteList(), TranslatorLatvian::trWriteList(), TranslatorChinesetraditional::trWriteList(), TranslatorVietnamese::trWriteList(), TranslatorDanish::trWriteList(), TranslatorRomanian::trWriteList(), TranslatorSerbianCyrillic::trWriteList(), TranslatorItalian::trWriteList(), TranslatorKorean::trWriteList(), TranslatorJapanese::trWriteList(), TranslatorArabic::trWriteList(), TranslatorNorwegian::trWriteList(), TranslatorCzech::trWriteList(), TranslatorBrazilian::trWriteList(), TranslatorFrench::trWriteList(), TranslatorFinnish::trWriteList(), TranslatorSwedish::trWriteList(), and TranslatorGerman::trWriteList().
getCanonicalTemplateSpec()
QCString getCanonicalTemplateSpec (Definition * d, FileDef * fs, const QCString & spec)
Definition at line 3432 of file util.cpp.
References extractCanonicalType(), and resolveTypeDef().
Referenced by getCanonicalTypeForIdentifier().
getCanonicalTypeForIdentifier()
static QCString getCanonicalTypeForIdentifier (Definition * d, FileDef * fs, const QCString & word, QCString * tSpec, int count = 0) static
Definition at line 3452 of file util.cpp.
References getCanonicalTemplateSpec(), getResolvedClass(), MemberDef::isEnumerate(), ClassDef::isTemplate(), MemberDef::isTypedef(), ClassDef::isUsedOnly(), Definition::name(), MemberDef::qualifiedName(), Definition::qualifiedName(), ClassDef::qualifiedNameWithTemplateParameters(), removeRedundantWhiteSpace(), resolveTypeDef(), stripDeclKeywords(), stripScope(), and MemberDef::typeString().
Referenced by extractCanonicalType().
getClass()
ClassDef* getClass (const char * n)
Get a class definition given its name. Returns 0 if the class is not found.
Definition at line 473 of file util.cpp.
References Doxygen::classSDict, and SDict< T >::find().
Referenced by addClassToContext(), addEnumValuesToEnums(), addVariable(), addVariableToFile(), buildFunctionList(), buildInterfaceAndServiceList(), buildScopeFromQualifiedName(), computeClassRelations(), computeTemplateClassRelations(), extractNamespaceName(), findClassRelation(), findClassWithinClassContext(), findEnumDocumentation(), findEnums(), findInheritedTemplateInstances(), findMember(), findUsedTemplateInstances(), findUsingDeclarations(), findUsingDeclImports(), MemberDef::getClassDefOfAnonymousType(), getResolvedClass(), getScopeDefs(), getTemplateArgumentsFromName(), handleLinkedWord(), insertTemplateSpecifierInScope(), MemberDef::isDocumentedFriendClass(), linkifyText(), matchArgument(), resolveLink(), resolveRef(), stripTemplateSpecifiersFromScope(), trimTemplateSpecifiers(), and MemberDef::writeDeclaration().
getDefs()
bool getDefs (const QCString & scName, const QCString & mbName, const char * args, MemberDef *& md, ClassDef *& cd, FileDef *& fd, NamespaceDef *& nd, GroupDef *& gd, bool forceEmptyScope, FileDef * currentFile, bool checkCV, const char * forceTagFile)
Searches for a member definition given its name `memberName' as a string. memberName may also include a (partial) scope to indicate the scope in which the member is located.
The parameter `scName' is a string representing the name of the scope in which the link was found.
In case of a function args contains a string representation of the argument list. Passing 0 means the member has no arguments. Passing "()" means any argument list will do, but "()" is preferred.
The function returns TRUE if the member is known and documented or FALSE if it is not. If TRUE is returned parameter `md' contains a pointer to the member definition. Furthermore exactly one of the parameter `cd', `nd', or `fd' will be non-zero:
if `cd' is non zero, the member was found in a class pointed to by cd.
if `nd' is non zero, the member was found in a namespace pointed to by nd.
if `fd' is non zero, the member was found in the global namespace of file fd.
Definition at line 4035 of file util.cpp.
References MemberDef::argumentList(), MemberDef::enumFieldList(), SDict< T >::find(), findMembersWithSpecificName(), Doxygen::functionNameSDict, MemberDef::getClassDef(), MemberDef::getEnumScope(), MemberDef::getFileDef(), ClassDef::getFileDef(), MemberDef::getGroupDef(), MemberDef::getNamespaceDef(), Definition::getOuterScope(), getResolvedClass(), Doxygen::globalScope, MemberDef::isEnumerate(), MemberDef::isForeign(), GroupDef::isLinkable(), NamespaceDef::isLinkable(), FileDef::isLinkable(), ClassDef::isLinkable(), MemberDef::isLinkable(), MemberDef::isRelated(), MemberDef::isStrong(), MemberDef::isStrongEnumValue(), Definition::localName(), matchArguments2(), maxInheritanceDepth, Doxygen::memberNameSDict, minClassDistance(), FileDef::name(), Definition::name(), Doxygen::namespaceSDict, rightScopeMatch(), stringToArgumentList(), stripTemplateSpecifiersFromScope(), and substitute().
Referenced by findDocsForMemberOrCompound(), linkifyText(), and resolveRef().
getDotImageExtension()
QCString getDotImageExtension (void)
Definition at line 8698 of file util.cpp.
References Config_getEnum.
Referenced by DotGfxHierarchyTable::createGraph(), RTFGenerator::endCallGraph(), RTFGenerator::endDirDepGraph(), RTFGenerator::endDotGraph(), RTFGenerator::endInclDepGraph(), VhdlDocGen::findConstraintFile(), generateGraphLegend(), DocbookDocVisitor::startDotFile(), TranslatorDutch::trLegendDocs(), TranslatorSlovene::trLegendDocs(), TranslatorCroatian::trLegendDocs(), TranslatorChinese::trLegendDocs(), TranslatorDanish::trLegendDocs(), TranslatorUkrainian::trLegendDocs(), TranslatorArmenian::trLegendDocs(), TranslatorHungarian::trLegendDocs(), TranslatorIndonesian::trLegendDocs(), TranslatorSerbian::trLegendDocs(), TranslatorAfrikaans::trLegendDocs(), TranslatorSlovak::trLegendDocs(), TranslatorMacedonian::trLegendDocs(), TranslatorGreek::trLegendDocs(), TranslatorRussian::trLegendDocs(), TranslatorLithuanian::trLegendDocs(), TranslatorPolish::trLegendDocs(), TranslatorEnglish::trLegendDocs(), TranslatorPersian::trLegendDocs(), TranslatorTurkish::trLegendDocs(), TranslatorPortuguese::trLegendDocs(), TranslatorEsperanto::trLegendDocs(), TranslatorLatvian::trLegendDocs(), TranslatorCatalan::trLegendDocs(), TranslatorChinesetraditional::trLegendDocs(), TranslatorVietnamese::trLegendDocs(), TranslatorRomanian::trLegendDocs(), TranslatorSerbianCyrillic::trLegendDocs(), TranslatorItalian::trLegendDocs(), TranslatorJapanese::trLegendDocs(), TranslatorKorean::trLegendDocs(), TranslatorArabic::trLegendDocs(), TranslatorSpanish::trLegendDocs(), TranslatorNorwegian::trLegendDocs(), TranslatorCzech::trLegendDocs(), TranslatorBrazilian::trLegendDocs(), TranslatorFrench::trLegendDocs(), TranslatorFinnish::trLegendDocs(), TranslatorSwedish::trLegendDocs(), TranslatorGerman::trLegendDocs(), RTFDocVisitor::writeDotFile(), writeDotGraphFromFile(), writeDotImageMapFromFile(), DotClassGraph::writeGraph(), DotInclDepGraph::writeGraph(), DotCallGraph::writeGraph(), DotDirDeps::writeGraph(), DotGroupCollaboration::writeGraph(), writeGraphInfo(), HtmlDocVisitor::writeMscFile(), and HtmlDocVisitor::writePlantUMLFile().
getFileFilter()
QCString getFileFilter (const char * name, bool isSourceCode)
looks for a filter for the file name. Returns the name of the filter if there is a match for the file name, otherwise an empty string. In case inSourceCode is TRUE then first the source filter list is considered.
Definition at line 2427 of file util.cpp.
References Config_getList, Config_getString, and getFilterFromList().
Referenced by readCodeFragment(), readInputFile(), and FileDef::writeSource().
getFilterFromList()
static QCString getFilterFromList (const char * name, const QStrList & filterList, bool & found) static
Definition at line 2390 of file util.cpp.
References portable_fileSystemIsCaseSensitive().
Referenced by getFileFilter().
getLanguageFromFileName()
SrcLangExt getLanguageFromFileName (const QCString fileName)
Definition at line 7172 of file util.cpp.
References SrcLangExt_Cpp.
Referenced by DocRef::DocRef(), FileDef::FileDef(), ClassDefImpl::init(), processLink(), readCodeFragment(), DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), LatexDocVisitor::visit(), writeDocbookCodeBlock(), and writeXMLCodeBlock().
getLanguageSpecificSeparator()
QCString getLanguageSpecificSeparator (SrcLangExt lang, bool classScope)
Returns the scope separator to use given the programming language lang.
Definition at line 8201 of file util.cpp.
References SrcLangExt_CSharp, SrcLangExt_Java, SrcLangExt_PHP, SrcLangExt_Python, and SrcLangExt_VHDL.
Referenced by Definition::_writeSourceRefList(), MemberDef::addListReference(), addMethodToClass(), addVariableToFile(), buildFunctionList(), MemberDef::displayDefinition(), NamespaceDef::displayName(), ClassDef::displayName(), MemberContext::Private::handleNameWithContextFor(), linkToText(), ClassDef::mergeMembers(), MemberDef::qualifiedName(), Definition::qualifiedName(), ClassDef::qualifiedNameWithTemplateParameters(), SymbolContext::Private::scope(), SearchIndex::setCurrentDoc(), validatingParseDoc(), writeAlphabeticalClassList(), MemberDef::writeDeclaration(), MemberDef::writeDocumentation(), writeJavascriptSearchIndex(), MemberDef::writeLink(), and writeMemberReference().
getMemberFromSymbol()
MemberDef* getMemberFromSymbol (Definition * scope, FileDef * fileScope, const char * n)
Definition at line 7194 of file util.cpp.
References computeQualifiedIndex(), DefinitionIntf::definitionType(), g_visitedNamespaces, Doxygen::globalScope, isAccessibleFromWithExpScope(), replaceNamespaceAliases(), Doxygen::symbolMap, DefinitionIntf::TypeClass, DefinitionIntf::TypeMember, DefinitionIntf::TypeNamespace, and DefinitionIntf::TypeSymbolList.
Referenced by checkIfTypedef().
getOverloadDocs()
QCString getOverloadDocs ()
Returns the standard string that is generated when the \overload command is used.
Definition at line 5962 of file util.cpp.
References theTranslator, and Translator::trOverloadText().
Referenced by addMemberDocs(), and findMember().
getPrefixIndex()
int getPrefixIndex (const QCString & name)
Returns the character index within name of the first prefix in Config_getList(IGNORE_PREFIX) that matches name at the left hand side, or zero if no match was found
Definition at line 5246 of file util.cpp.
References Config_getList.
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), addNamespaceMemberNameToIndex(), SearchIndex::addWord(), PrefixIgnoreClassList::compareValue(), MemberNameSDict::compareValues(), FilterAlphaIndex::determineSortKey(), writeAlphabeticalClassList(), and writeMemberList().
getResolvedClass()
ClassDef* getResolvedClass (Definition * scope, FileDef * fileScope, const char * n, MemberDef ** pTypeDef, QCString * pTemplSpec, bool mayBeUnlinkable, bool mayBeHidden, QCString * pResolvedType)
Definition at line 1564 of file util.cpp.
References Config_getBool, DefinitionIntf::definitionType(), g_resolvedTypedefs, getClass(), Definition::getLanguage(), getResolvedClassRec(), Doxygen::globalScope, Definition::isHidden(), ClassDef::isLinkable(), SrcLangExt_Java, DefinitionIntf::TypeClass, and DefinitionIntf::TypeNamespace.
Referenced by ClassDef::addTypeConstraint(), findClassDefinition(), findClassRelation(), findClassWithinClassContext(), findUsedClassesForClass(), findUsingDeclarations(), findUsingDeclImports(), getCanonicalTypeForIdentifier(), getDefs(), isVarWithConstructor(), linkifyText(), and normalizeNonTemplateArgumentsInString().
getResolvedClassRec()
static ClassDef * getResolvedClassRec (Definition * scope, FileDef * fileScope, const char * n, MemberDef ** pTypeDef, QCString * pTemplSpec, QCString * pResolvedType) static
Definition at line 1375 of file util.cpp.
References FileDef::absFilePath(), LookupInfo::classDef, computeQualifiedIndex(), SDict< T >::count(), DefinitionIntf::definitionType(), getResolvedSymbol(), FileDef::getUsedClasses(), FileDef::getUsedNamespaces(), Doxygen::lookupCache, Definition::name(), removeRedundantWhiteSpace(), replaceNamespaceAliases(), LookupInfo::resolvedType, stringToArgumentList(), stripTemplateSpecifiersFromScope(), Doxygen::symbolMap, LookupInfo::templSpec, LookupInfo::typeDef, and DefinitionIntf::TypeSymbolList.
Referenced by getResolvedClass(), and newResolveTypedef().
getResolvedNamespace()
NamespaceDef* getResolvedNamespace (const char * name)
Definition at line 490 of file util.cpp.
References SDict< T >::find(), Doxygen::namespaceAliasDict, Doxygen::namespaceSDict, and warn_uncond().
Referenced by addEnumValuesToEnums(), addVariableToFile(), buildFunctionList(), extractNamespaceName(), findEnums(), findMember(), findUsedNamespace(), findUsingDeclarations(), findUsingDirectives(), and writeAlphabeticalClassList().
getResolvedSymbol()
static void getResolvedSymbol (Definition * scope, FileDef * fileScope, Definition * d, const QCString & explicitScopePart, ArgumentList * actTemplParams, int & minDistance, ClassDef *& bestMatch, MemberDef *& bestTypedef, QCString & bestTemplSpec, QCString & bestResolvedType) static
Definition at line 1210 of file util.cpp.
References MemberDef::argsString(), DefinitionIntf::definitionType(), g_visitedNamespaces, Definition::getOuterScope(), FileDef::getUsedNamespaces(), Doxygen::globalScope, isAccessibleFromWithExpScope(), MemberDef::isEnumerate(), MemberDef::isReference(), ClassDef::isTemplateArgument(), MemberDef::isTypedef(), newResolveTypedef(), MemberDef::qualifiedName(), Definition::qualifiedName(), DefinitionIntf::TypeClass, DefinitionIntf::TypeMember, and DefinitionIntf::TypeNamespace.
Referenced by getResolvedClassRec().
getScopeDefs()
static bool getScopeDefs (const char * docScope, const char * scope, ClassDef *& cd, NamespaceDef *& nd) static
Searches for a scope definition given its name as a string via parameter scope.
The parameter docScope is a string representing the name of the scope in which the scope string was found.
The function returns TRUE if the scope is known and documented or FALSE if it is not. If TRUE is returned exactly one of the parameter cd, nd will be non-zero:
if cd is non zero, the scope was a class pointed to by cd.
if nd is non zero, the scope was a namespace pointed to by nd.
Definition at line 4521 of file util.cpp.
References getClass(), NamespaceDef::isLinkable(), ClassDef::isLinkable(), and Doxygen::namespaceSDict.
Referenced by resolveRef().
getScopeFragment()
int getScopeFragment (const QCString & s, int p, int * l)
Returns a fragment from scope s, starting at position p.
Parameters
s the scope name as a string.
p the start position (0 is the first).
l the resulting length of the fragment.
Returns
the location of the fragment, or -1 if non is found.
Definition at line 6425 of file util.cpp.
Referenced by buildScopeFromQualifiedName(), findScopeFromQualifiedName(), followPath(), resolveTypeDef(), stripAnonymousNamespaceScope(), and trimTemplateSpecifiers().
getUtf8Code()
uint getUtf8Code (const QCString & s, int idx)
Get one unicode character as an unsigned integer from utf-8 string.
Parameters
s utf-8 encoded string
idx byte position of given string s.
Returns
the unicode codepoint, 0 - MAX_UNICODE_CODEPOINT
See also
getNextUtf8OrToLower()
getNextUtf8OrToUpper()
Definition at line 8376 of file util.cpp.
Referenced by getUtf8CodeToLower(), and getUtf8CodeToUpper().
getUtf8CodeToLower()
uint getUtf8CodeToLower (const QCString & s, int idx)
Returns one unicode character as an unsigned integer from utf-8 string, making the character lower case if it was upper case.
Parameters
s utf-8 encoded string
idx byte position of given string s.
Returns
the unicode codepoint, 0 - MAX_UNICODE_CODEPOINT, excludes 'A'-'Z'
See also
getNextUtf8Code()
Definition at line 8412 of file util.cpp.
References getUtf8Code().
Referenced by addClassMemberNameToIndex(), addFileMemberNameToIndex(), addMemberToSearchIndex(), addNamespaceMemberNameToIndex(), createJavascriptSearchIndex(), and writeAlphabeticalClassList().
getUtf8CodeToUpper()
uint getUtf8CodeToUpper (const QCString & s, int idx)
Returns one unicode character as an unsigned integer from utf-8 string, making the character upper case if it was lower case.
Parameters
s utf-8 encoded string
idx byte position of given string s.
Returns
the unicode codepoint, 0 - MAX_UNICODE_CODEPOINT, excludes 'A'-'Z'
See also
getNextUtf8Code()
Definition at line 8427 of file util.cpp.
References getUtf8Code().
Referenced by FilterAlphaIndex::determineSortKey().
guessSection()
int guessSection (const char * name)
try to determine if name is a source or a header file name by looking at the extension. A number of variations is allowed in both upper and lower case) If anyone knows or uses another extension please let me know :-)
Definition at line 315 of file util.cpp.
References Entry::HEADER_SEC, and Entry::SOURCE_SEC.
Referenced by addIncludeFile(), TagFileParser::buildLists(), computeClassRelations(), FileDef::FileDef(), FileDef::generateSourceFile(), and ClassDefImpl::init().
hasVisibleRoot()
bool hasVisibleRoot (BaseClassList * bcl)
Definition at line 5326 of file util.cpp.
References ClassDef::baseClasses(), hasVisibleRoot(), and ClassDef::isVisibleInHierarchy().
Referenced by NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), NestingContext::Private::addDerivedClasses(), DotGfxHierarchyTable::addHierarchy(), countClassesInTreeList(), hasVisibleRoot(), writeClassTree(), and writeClassTreeForList().
initBaseClassHierarchy()
static void initBaseClassHierarchy (BaseClassList * bcl) static
Definition at line 5268 of file util.cpp.
References ClassDef::baseClasses(), and ClassDef::visited.
Referenced by initClassHierarchy().
initClassHierarchy()
void initClassHierarchy (ClassSDict * cl)
Definition at line 5313 of file util.cpp.
References ClassDef::baseClasses(), initBaseClassHierarchy(), SDict< ClassDef >::Iterator, and ClassDef::visited.
Referenced by countClassHierarchy(), DotGfxHierarchyTable::DotGfxHierarchyTable(), ClassHierarchyContext::Private::Private(), and writeClassHierarchy().
initDefaultExtensionMapping()
void initDefaultExtensionMapping ()
Definition at line 7106 of file util.cpp.
References updateLanguageMapping().
Referenced by initDoxygen().
insertTemplateSpecifierInScope()
QCString insertTemplateSpecifierInScope (const QCString & scope, const QCString & templ)
Definition at line 5630 of file util.cpp.
References getClass(), and ClassDef::templateArguments().
Referenced by DotClassGraph::addClass(), generateXMLForClass(), InheritanceListContext::InheritanceListContext(), DiagramItem::label(), and ClassDef::writeInheritanceGraph().
isAccessibleFrom()
int isAccessibleFrom (Definition * scope, FileDef * fileScope, Definition * item)
Definition at line 949 of file util.cpp.
References accessibleViaUsingClass(), accessibleViaUsingNamespace(), MemberDef::definitionType(), DefinitionIntf::definitionType(), AccessStack::find(), Definition::getOuterScope(), NamespaceDef::getUsedClasses(), FileDef::getUsedClasses(), NamespaceDef::getUsedNamespaces(), FileDef::getUsedNamespaces(), Doxygen::globalScope, isAccessibleFrom(), AccessStack::pop(), AccessStack::push(), DefinitionIntf::TypeClass, DefinitionIntf::TypeMember, and DefinitionIntf::TypeNamespace.
Referenced by isAccessibleFrom(), isAccessibleFromWithExpScope(), and resolveTypeDef().
isAccessibleFromWithExpScope()
int isAccessibleFromWithExpScope (Definition * scope, FileDef * fileScope, Definition * item, const QCString & explicitScopePart)
Definition at line 1052 of file util.cpp.
References accessibleViaUsingNamespace(), DefinitionIntf::definitionType(), AccessStack::find(), followPath(), g_visitedNamespaces, Definition::getOuterScope(), NamespaceDef::getUsedClasses(), NamespaceDef::getUsedNamespaces(), FileDef::getUsedNamespaces(), Doxygen::globalScope, isAccessibleFrom(), isAccessibleFromWithExpScope(), SDict< NamespaceDef >::Iterator, Definition::name(), AccessStack::pop(), AccessStack::push(), DefinitionIntf::TypeClass, and DefinitionIntf::TypeNamespace.
Referenced by getMemberFromSymbol(), getResolvedSymbol(), isAccessibleFromWithExpScope(), and substTypedef().
isLowerCase()
static bool isLowerCase (QCString & s) static
Definition at line 4569 of file util.cpp.
Referenced by resolveRef().
langToString()
QCString langToString (SrcLangExt lang)
Returns a string representation of lang.
Definition at line 8176 of file util.cpp.
References SrcLangExt_Cpp, SrcLangExt_CSharp, SrcLangExt_D, SrcLangExt_Fortran, SrcLangExt_IDL, SrcLangExt_Java, SrcLangExt_JS, SrcLangExt_Markdown, SrcLangExt_ObjC, SrcLangExt_PHP, SrcLangExt_Python, SrcLangExt_SQL, SrcLangExt_Tcl, SrcLangExt_Unknown, SrcLangExt_VHDL, and SrcLangExt_XML.
Referenced by generateXMLForClass(), generateXMLForFile(), and generateXMLForNamespace().
latexEscapeIndexChars()
QCString latexEscapeIndexChars (const char * s, bool insideTabbing)
Definition at line 6787 of file util.cpp.
References filterLatexString().
Referenced by LatexGenerator::addIndexItem(), FilterTexIndex::apply(), LatexGenerator::endTitleHead(), LatexGenerator::startMemberDoc(), and LatexDocVisitor::visit().
latexEscapeLabelName()
QCString latexEscapeLabelName (const char * s, bool insideTabbing)
Definition at line 6750 of file util.cpp.
References filterLatexString().
Referenced by LatexGenerator::addIndexItem(), FilterTexLabel::apply(), LatexGenerator::endTitleHead(), LatexGenerator::startMemberDoc(), and LatexDocVisitor::visit().
latexEscapePDFString()
QCString latexEscapePDFString (const char * s)
Definition at line 6825 of file util.cpp.
Referenced by LatexGenerator::startMemberDoc().
leftScopeMatch()
bool leftScopeMatch (const QCString & scope, const QCString & name)
Definition at line 1984 of file util.cpp.
Referenced by addClassToContext(), buildFunctionList(), mergeScopes(), and substituteTemplateArgumentsInString().
lineBlock()
int lineBlock (const QCString text, const QCString marker)
Returns the line number of the line following the line with the marker.
See also
routine extractBlock
Definition at line 8155 of file util.cpp.
Referenced by DocPara::handleInclude(), DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), XmlDocVisitor::visit(), HtmlDocVisitor::visit(), and LatexDocVisitor::visit().
linkifyText()
void linkifyText (const TextGeneratorIntf & out, Definition * scope, FileDef * fileScope, Definition * self, const char * text, bool autoBreak, bool external, bool keepSpaces, int indentLevel)
Definition at line 1996 of file util.cpp.
References MemberDef::anchor(), ClassDef::anchor(), DefinitionIntf::definitionType(), getClass(), getDefs(), Definition::getOuterScope(), MemberDef::getOutputFileBase(), ClassDef::getOutputFileBase(), MemberDef::getReference(), ClassDef::getReference(), getResolvedClass(), ClassDef::isLinkable(), MemberDef::isLinkable(), ClassDef::isLinkableInProject(), MemberDef::isLinkableInProject(), Definition::name(), substitute(), DefinitionIntf::TypeClass, DefinitionIntf::TypeNamespace, TextGeneratorIntf::writeBreak(), TextGeneratorIntf::writeLink(), and TextGeneratorIntf::writeString().
Referenced by createLinkedText(), generateDocbookForMember(), generateXMLForMember(), MemberDef::writeDeclaration(), writeDefArgumentList(), MemberDef::writeDocumentation(), writeExceptionListImpl(), MemberDef::writeMemberDocSimple(), writeTemplateArgumentList(), and writeTypeConstraints().
linkToText()
QCString linkToText (SrcLangExt lang, const char * link, bool isFileName)
Definition at line 4761 of file util.cpp.
References getLanguageSpecificSeparator(), and substitute().
Referenced by DotCallGraph::buildGraph(), DocRef::DocRef(), DotCallGraph::DotCallGraph(), generateLink(), and handleLinkedWord().
mainPageHasTitle()
bool mainPageHasTitle ()
Definition at line 8690 of file util.cpp.
References Doxygen::mainPage.
Referenced by mainPageHasOwnTitle(), PageContext::Private::title(), and writeIndex().
matchArgument()
static bool matchArgument (const Argument * srcA, const Argument * dstA, const QCString & className, const QCString & namespaceName, NamespaceSDict * usingNamespaces, SDict< Definition > * usingClasses) static
Definition at line 3015 of file util.cpp.
References Argument::array, ClassDef::baseClasses(), SDict< T >::count(), getClass(), isId(), SDict< NamespaceDef >::Iterator, MATCH, Argument::name, Definition::name(), NOMATCH, removeRedundantWhiteSpace(), stripIrrelevantConstVolatile(), trimBaseClassScope(), trimScope(), trimTemplateSpecifiers(), and Argument::type.
Referenced by matchArguments().
matchArgument2()
static bool matchArgument2 (Definition * srcScope, FileDef * srcFileScope, Argument * srcA, Definition * dstScope, FileDef * dstFileScope, Argument * dstA) static
Definition at line 3682 of file util.cpp.
References Argument::canType, extractCanonicalArgType(), MATCH, Argument::name, NOMATCH, stripIrrelevantConstVolatile(), and Argument::type.
Referenced by matchArguments2().
matchArguments()
bool matchArguments (ArgumentList * srcAl, ArgumentList * dstAl, const char * cl, const char * ns, bool checkCV, NamespaceSDict * usingNamespaces, SDict< Definition > * usingClasses)
Matches the arguments list srcAl with the argument list dstAl Returns TRUE if the argument lists are equal. Two argument list are considered equal if the number of arguments is equal and the types of all arguments are equal. Furthermore the const and volatile specifiers stored in the list should be equal.
Definition at line 3290 of file util.cpp.
References ArgumentList::constSpecifier, MATCH, matchArgument(), NOMATCH, ArgumentList::refQualifier, Argument::type, and ArgumentList::volatileSpecifier.
matchArguments2()
bool matchArguments2 (Definition * srcScope, FileDef * srcFileScope, ArgumentList * srcAl, Definition * dstScope, FileDef * dstFileScope, ArgumentList * dstAl, bool checkCV)
Definition at line 3744 of file util.cpp.
References ArgumentList::constSpecifier, MATCH, matchArgument2(), NOMATCH, ArgumentList::refQualifier, Argument::type, and ArgumentList::volatileSpecifier.
Referenced by addMemberDocs(), buildFunctionList(), combineDeclarationAndDefinition(), computeMemberRelations(), findFriends(), findGlobalMember(), findMember(), findMembersWithSpecificName(), getDefs(), GroupDef::insertMember(), ClassDef::mergeMembers(), transferFunctionReferences(), and transferRelatedFunctionDocumentation().
mergeArguments()
void mergeArguments (ArgumentList * srcAl, ArgumentList * dstAl, bool forceNameOverwrite)
Definition at line 3835 of file util.cpp.
References Argument::defval, Argument::docs, Argument::name, and Argument::type.
Referenced by addMemberDocs(), buildFunctionList(), and findFriends().
mergeScopes()
QCString mergeScopes (const QCString & leftScope, const QCString & rightScope)
Merges two scope parts together. The parts may (partially) overlap. Example1: A::B and B::C will result in A::B::C
Example2: A and B will be A::B
Example3: A::B and B will be A::B
Parameters
leftScope the left hand part of the scope.
rightScope the right hand part of the scope.
Returns
the merged scope.
Definition at line 6390 of file util.cpp.
References leftScopeMatch().
Referenced by addEnumValuesToEnums(), addVariable(), findEnums(), findMember(), and trimTemplateSpecifiers().
minClassDistance()
int minClassDistance (const ClassDef * cd, const ClassDef * bcd, int level)
Definition at line 2615 of file util.cpp.
References ClassDef::baseClasses(), ClassDef::categoryOf(), maxInheritanceDepth, minClassDistance(), Definition::name(), and warn_uncond().
Referenced by computeMemberRelations(), getDefs(), ClassDef::getMemberByName(), and minClassDistance().
namespaceHasVisibleChild()
bool namespaceHasVisibleChild (NamespaceDef * nd, bool includeClasses)
Definition at line 8435 of file util.cpp.
References NamespaceDef::getClassSDict(), NamespaceDef::getNamespaceSDict(), SDict< NamespaceDef >::Iterator, SDict< ClassDef >::Iterator, and namespaceHasVisibleChild().
Referenced by NestingContext::Private::addNamespaces(), namespaceHasVisibleChild(), and writeNamespaceTree().
newResolveTypedef()
ClassDef* newResolveTypedef (FileDef * fileScope, MemberDef * md, MemberDef ** pMemType, QCString * pTemplSpec, QCString * pResolvedType, ArgumentList * actTemplParams)
Returns the class representing the value of the typedef represented by md within file fileScope.
Example: typedef A T; will return the class representing A if it is a class.
Example: typedef int T; will return 0, since "int" is not a class.
Definition at line 536 of file util.cpp.
References MemberDef::cacheTypedefVal(), g_resolvedTypedefs, MemberDef::getCachedResolvedTypedef(), MemberDef::getCachedTypedefTemplSpec(), MemberDef::getCachedTypedefVal(), MemberDef::getClassDef(), Definition::getDefFileName(), Definition::getOuterScope(), getResolvedClassRec(), ClassDef::isTemplate(), MemberDef::isTypedefValCached(), newResolveTypedef(), MemberDef::qualifiedName(), Definition::qualifiedName(), stripTemplateSpecifiersFromScope(), substituteTemplateArgumentsInString(), ClassDef::templateArguments(), and MemberDef::typeString().
Referenced by followPath(), getResolvedSymbol(), and newResolveTypedef().
nextUtf8CharPosition()
int nextUtf8CharPosition (const QCString & utf8Str, int len, int startPos)
Definition at line 7306 of file util.cpp.
Referenced by lastCharIsMultibyte(), and parseCommentAsText().
normalizeNonTemplateArgumentsInString()
QCString normalizeNonTemplateArgumentsInString (const QCString & name, Definition * context, const ArgumentList * formalArgs)
Definition at line 6140 of file util.cpp.
References getResolvedClass(), Argument::name, Definition::name(), and removeRedundantWhiteSpace().
Referenced by findUsedClassesForClass().
openOutputFile()
bool openOutputFile (const char * outFile, QFile & f)
Definition at line 8705 of file util.cpp.
Referenced by generateConfigFile(), readConfiguration(), and writeDefaultLayoutFile().
parseCommentAsText()
QCString parseCommentAsText (const Definition * scope, const MemberDef * md, const QCString & doc, const QCString & fileName, int lineNr)
Definition at line 7353 of file util.cpp.
References DocNode::accept(), convertCharEntitiesToUTF8(), nextUtf8CharPosition(), and validatingParseDoc().
Referenced by Definition::briefDescriptionAsTooltip(), and formatBriefNote().
patternMatch()
bool patternMatch (const QFileInfo & fi, const QStrList * patList)
Definition at line 7895 of file util.cpp.
Referenced by readDir().
protectionLevelVisible()
bool protectionLevelVisible (Protection prot)
Definition at line 8234 of file util.cpp.
References Config_getBool, Package, and Private.
Referenced by MemberDef::_computeLinkableInProject(), computeClassRelations(), ClassDef::internalInsertMember(), MemberDef::isBriefSectionVisible(), MemberDef::isDetailedSectionLinkable(), ClassDef::isLinkableInProject(), ClassDef::isVisibleInHierarchy(), AllMembersListContext::Private::Private(), MemberDef::warnIfUndocumented(), ClassDef::writeDocumentationForInnerClasses(), ClassDef::writeMemberList(), and ClassDef::writeTagFile().
readInputFile()
bool readInputFile (const char * fileName, BufStr & inBuf, bool filter, bool isSourceCode)
read a file name fileName and optionally filter and transcode it
Definition at line 7784 of file util.cpp.
References BufStr::addArray(), BufStr::addChar(), BufStr::at(), Config_getString, BufStr::curPos(), BufStr::data(), BufStr::dropFromStart(), err(), Debug::ExtCmd, filterCRLF(), Debug::FilterOutput, getFileFilter(), portable_pclose(), portable_popen(), Debug::print(), BufStr::shrink(), BufStr::skip(), and transcodeCharacterBuffer().
Referenced by fileToString(), and parseFile().
recursivelyAddGroupListToTitle()
bool recursivelyAddGroupListToTitle (OutputList & ol, Definition * d, bool root)
Definition at line 6598 of file util.cpp.
References OutputList::disableAllBut(), GroupDef::getOutputFileBase(), Definition::getReference(), GroupDef::groupTitle(), OutputGenerator::Html, Definition::partOfGroups(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by addGroupListToTitle().
relativePathToRoot()
QCString relativePathToRoot (const char * name)
Definition at line 5539 of file util.cpp.
References Config_getBool, and REL_PATH_TO_ROOT.
Referenced by generateBriefDoc(), generateDocbookForClass(), generateDocbookForDir(), generateDocbookForFile(), generateDocbookForGroup(), RTFGenerator::startFile(), LatexGenerator::startFile(), HtmlGenerator::startFile(), and validatingParseDoc().
removeAnonymousScopes()
QCString removeAnonymousScopes (const QCString & s)
Removes all anonymous scopes from string s Possible examples:
   "bla::@10::blep"      => "bla::blep"
   "bla::@10::@11::blep" => "bla::blep"
   "@10::blep"           => "blep"
   " @10::blep"          => "blep"
   "@9::@10::blep"       => "blep"
   "bla::@1"             => "bla"
   "bla::@1::@2"         => "bla"
   "bla @1"              => "bla"
Definition at line 164 of file util.cpp.
Referenced by createTagLessInstance(), ClassDef::displayName(), simplifyTypeForTable(), and MemberDef::writeDeclaration().
removeRedundantWhiteSpace()
QCString removeRedundantWhiteSpace (const QCString & s)
Definition at line 1697 of file util.cpp.
References CharAroundSpace::CharElem::after, CharAroundSpace::CharElem::before, CharAroundSpace::charMap, Config_getBool, constScope, isId(), operatorScope, and virtualScope.
Referenced by addMethodToClass(), addVariable(), addVariableToClass(), argListToString(), buildFunctionList(), buildInterfaceAndServiceList(), extractCanonicalType(), findClassRelation(), findDocsForMemberOrCompound(), findMember(), findUsedClassesForClass(), findUsingDeclImports(), getCanonicalTypeForIdentifier(), getResolvedClassRec(), ClassDef::getVariableInstance(), MemberDefImpl::init(), ClassDef::insertTemplateInstance(), matchArgument(), normalizeNonTemplateArgumentsInString(), resolveRef(), tempArgListToString(), and writeExceptionListImpl().
replaceAliasArguments()
static QCString replaceAliasArguments (const QCString & aliasValue, const QCString & argList) static
Replaces the markers in an alias definition aliasValue with the corresponding values found in the comma separated argument list argList and the returns the result after recursive alias expansion.
Definition at line 7442 of file util.cpp.
References expandAliasRec(), findEndOfCommand(), Marker::number, Marker::pos, Marker::size, and substitute().
Referenced by expandAliasRec().
replaceAnonymousScopes()
QCString replaceAnonymousScopes (const QCString & s, const char * replacement)
Definition at line 191 of file util.cpp.
Referenced by generateDEFForMember().
replaceColorMarkers()
QCString replaceColorMarkers (const char * str)
Replaces any markers of the form ##AA in input string str by new markers of the form #AABBCC, where #AABBCC represents a valid color, based on the intensity represented by hex number AA and the current HTML_COLORSTYLE_* settings.
Definition at line 8030 of file util.cpp.
References Config_getInt, HEXTONUM, and ColoredImage::hsl2rgb().
Referenced by ResourceMgr::copyResourceAs(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeStyleInfo(), and HtmlGenerator::writeStyleSheetFile().
replaceNamespaceAliases()
void replaceNamespaceAliases (QCString & scope, int i)
Definition at line 6910 of file util.cpp.
References Doxygen::namespaceAliasDict.
Referenced by findClassRelation(), findUsedClassesForClass(), getMemberFromSymbol(), and getResolvedClassRec().
resolveAliasCmd()
QCString resolveAliasCmd (const QCString aliasCmd)
Definition at line 7673 of file util.cpp.
References expandAliasRec().
resolveLink()
bool resolveLink (const char * scName, const char * lr, bool , Definition ** resContext, QCString & resAnchor)
Definition at line 4855 of file util.cpp.
References MemberDef::anchor(), ClassDef::anchor(), SectionInfo::definition, Doxygen::directories, Doxygen::exampleSDict, findFileDef(), getClass(), PageDef::getGroupDef(), Doxygen::groupSDict, Doxygen::inputNameDict, DirDef::isLinkable(), FileDef::isLinkable(), SectionInfo::label, Definition::name(), Doxygen::namespaceSDict, Doxygen::pageSDict, resolveRef(), Doxygen::sectionDict, and stripTemplateSpecifiersFromScope().
Referenced by DocLink::DocLink(), DocRef::DocRef(), generateLink(), and LayoutNavEntry::url().
resolveRef()
bool resolveRef (const char * scName, const char * name, bool inSeeBlock, Definition ** resContext, MemberDef ** resMember, bool lookForSpecialization, FileDef * currentFile, bool checkScope)
Returns an object to reference to given its name and context
Postcondition
return value TRUE implies *resContext!=0 or *resMember!=0
Definition at line 4581 of file util.cpp.
References SDict< T >::find(), findFileDef(), findParameterList(), getClass(), getDefs(), Definition::getOuterScope(), getScopeDefs(), Doxygen::globalScope, Doxygen::groupSDict, Doxygen::inputNameDict, isLowerCase(), MemberDef::isStrongEnumValue(), removeRedundantWhiteSpace(), resolveRef(), and substitute().
Referenced by handleLinkedWord(), resolveLink(), and resolveRef().
resolveTypeDef()
QCString resolveTypeDef (Definition * context, const QCString & qualifiedName, Definition ** typedefContext)
Definition at line 347 of file util.cpp.
References MemberDef::argsString(), DefinitionIntf::definitionType(), SDict< T >::find(), Definition::findInnerCompound(), Doxygen::functionNameSDict, Definition::getOuterScope(), getScopeFragment(), isAccessibleFrom(), MemberDef::isTypedef(), Doxygen::memberNameSDict, resolveTypeDef(), DefinitionIntf::TypeClass, and MemberDef::typeString().
Referenced by findUsedClassesForClass(), getCanonicalTemplateSpec(), getCanonicalTypeForIdentifier(), isVarWithConstructor(), and resolveTypeDef().
rightScopeMatch()
bool rightScopeMatch (const QCString & scope, const QCString & name)
Definition at line 1973 of file util.cpp.
Referenced by findMember(), findScopeFromQualifiedName(), getDefs(), and isRecursiveBaseClass().
rtfFormatBmkStr()
QCString rtfFormatBmkStr (const char * name)
Definition at line 6850 of file util.cpp.
Referenced by RTFGenerator::endDoxyAnchor(), RTFDocVisitor::startLink(), RTFGenerator::startTextLink(), RTFDocVisitor::visit(), RTFDocVisitor::visitPre(), RTFGenerator::writeAnchor(), RTFGenerator::writeCodeLink(), RTFGenerator::writeObjectLink(), RTFGenerator::writeRTFReference(), and RTFGenerator::writeStartAnnoItem().
setAnchors()
void setAnchors (MemberList * ml)
Definition at line 2336 of file util.cpp.
References MemberDef::isReference(), and MemberDef::setAnchor().
Referenced by NamespaceDef::computeAnchors(), GroupDef::computeAnchors(), FileDef::computeAnchors(), and ClassDef::computeAnchors().
showFileDefMatches()
QCString showFileDefMatches (const FileNameDict * fnDict, const char * n)
Definition at line 5160 of file util.cpp.
References FileDef::absFilePath(), and FileDef::getPath().
Referenced by addIncludeFile(), buildFileList(), findAndCopyImage(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), and readTextFileByName().
stackTrace()
void stackTrace ()
Definition at line 7719 of file util.cpp.
stripAnonymousNamespaceScope()
QCString stripAnonymousNamespaceScope (const QCString & s)
Definition at line 218 of file util.cpp.
References getScopeFragment(), and Doxygen::namespaceSDict.
Referenced by addPageToContext(), addVariable(), buildNamespaceList(), computeTemplateClassRelations(), extractClassName(), findGroupScope(), findMember(), findUsingDeclImports(), findUsingDirectives(), MemberDef::getClassDefOfAnonymousType(), and resolveClassNestingRelations().
stripDeclKeywords()
static QCString stripDeclKeywords (const QCString & s) static
Definition at line 3416 of file util.cpp.
Referenced by getCanonicalTypeForIdentifier().
stripExtension()
QCString stripExtension (const char * fName)
Definition at line 6905 of file util.cpp.
References Doxygen::htmlFileExtension, and stripExtensionGeneral().
Referenced by GroupDef::GroupDef(), ClassDefImpl::init(), NamespaceDef::NamespaceDef(), and MemberDef::setTagInfo().
stripExtensionGeneral()
QCString stripExtensionGeneral (const char * fName, const char * ext)
Definition at line 6895 of file util.cpp.
Referenced by stripExtension(), writeDefaultHeaderPart1(), and LatexCodeGenerator::writeLineNumber().
stripFromIncludePath()
QCString stripFromIncludePath (const QCString & path)
strip part of path if it matches one of the paths in the Config_getList(INCLUDE_PATH) list
Definition at line 306 of file util.cpp.
References Config_getList, and stripFromPath().
Referenced by addIncludeFile(), and findFileDef().
stripFromPath() [1/2]
static QCString stripFromPath (const QCString & path, QStrList & l) static
Definition at line 274 of file util.cpp.
Referenced by DirDef::DirDef(), FileDef::FileDef(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForMember(), generateXMLForNamespace(), markdownFileNameToId(), ClassDef::showUsedFiles(), stripFromIncludePath(), stripFromPath(), and writeSingleFileIndex().
stripFromPath() [2/2]
QCString stripFromPath (const QCString & path)
strip part of path if it matches one of the paths in the Config_getList(STRIP_FROM_PATH) list
Definition at line 298 of file util.cpp.
References Config_getList, and stripFromPath().
stripIndentation()
QCString stripIndentation (const QCString & s)
Definition at line 8246 of file util.cpp.
References Config_getInt.
Referenced by DocPara::handleStartCode().
stripIrrelevantConstVolatile()
void stripIrrelevantConstVolatile (QCString & s)
According to the C++ spec and Ivan Vecerina:
Parameter declarations that differ only in the presence or absence of const and/or volatile are equivalent.
So the following example, show what is stripped by this routine for const. The same is done for volatile.
For Java code we also strip the "final" keyword, see bug 765070.
const T param     ->   T param          // not relevant
const T& param    ->   const T& param   // const needed
T* const param    ->   T* param         // not relevant
const T* param    ->   const T* param   // const needed
Definition at line 2998 of file util.cpp.
References stripIrrelevantString().
Referenced by extractCanonicalType(), matchArgument(), and matchArgument2().
stripIrrelevantString()
static void stripIrrelevantString (QCString & target, const QCString & str) static
Definition at line 2947 of file util.cpp.
References isId().
Referenced by stripIrrelevantConstVolatile().
stripLeadingAndTrailingEmptyLines()
QCString stripLeadingAndTrailingEmptyLines (const QCString & s, int & docLine)
Special version of QCString::stripWhiteSpace() that only strips completely blank lines.
Parameters
s the string to be stripped
docLine the line number corresponding to the start of the string. This will be adjusted based on the number of lines stripped from the start.
Returns
The stripped string.
Definition at line 6982 of file util.cpp.
Referenced by Definition::_setDocumentation().
stripPath()
QCString stripPath (const char * s)
Definition at line 6925 of file util.cpp.
Referenced by substituteKeywords().
stripScope()
QCString stripScope (const char * name)
Definition at line 5708 of file util.cpp.
Referenced by DotClassGraph::addClass(), getCanonicalTypeForIdentifier(), DefinitionImpl::init(), and DiagramItem::label().
stripTemplateSpecifiersFromScope()
QCString stripTemplateSpecifiersFromScope (const QCString & fullName, bool parentOnly, QCString * pLastScopeStripped)
Strips template specifiers from scope fullName, except those that make up specialized classes. The switch parentOnly determines whether or not a template "at the end" of a scope should be considered, e.g. with parentOnly is TRUE, A<T>::B<S> will try to strip <T> and not <S>, while parentOnly is FALSE will strip both unless A<T> or B<S> are specialized template classes.
Definition at line 6329 of file util.cpp.
References getClass().
Referenced by addClassToContext(), addVariable(), buildFunctionList(), computeTemplateClassRelations(), extractClassName(), findMember(), findScopeFromQualifiedName(), findUsingDeclImports(), getDefs(), getResolvedClassRec(), newResolveTypedef(), and resolveLink().
substitute()
QCString substitute (const QCString & s, const QCString & src, const QCString & dst)
substitute all occurrences of src in s by dst
Definition at line 5190 of file util.cpp.
Referenced by addEnumValuesToEnums(), addMethodToClass(), addPageToContext(), addVariableToClass(), FilterNoWrap::apply(), buildFunctionList(), buildListOfUsingDecls(), buildNamespaceList(), checkUndocumentedParams(), convertFileId2Var(), ResourceMgr::copyResourceAs(), MemberDef::displayDefinition(), NamespaceDef::displayName(), ClassDef::displayName(), RTFGenerator::endIndexSection(), field2URL(), findDirDocumentation(), findDocsForMemberOrCompound(), findGlobalMember(), findGroupScope(), findMember(), findUsingDeclarations(), findUsingDirectives(), fixSpaces(), format_warn(), VhdlDocGen::getClassName(), getDefs(), DocPara::handleStartCode(), InheritedMemberInfoContext::Private::id(), linkifyText(), linkToText(), markdownFileNameToId(), matchExcludedSymbols(), processLink(), processTagLessClasses(), replaceAliasArguments(), resolveRef(), DotFilePatcher::run(), selectBlock(), SearchIndex::setCurrentDoc(), substituteHtmlKeywords(), substituteKeywords(), unescapeCRef(), validatingParseDoc(), writeAlphabeticalClassList(), MemberDef::writeDeclaration(), MemberList::writeDeclarations(), writeDefaultLayoutFile(), MemberDef::writeDocumentation(), HtmlGenerator::writeNavigationPath(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), HtmlGenerator::writeStyleInfo(), and HtmlGenerator::writeStyleSheetFile().
substituteKeywords()
QCString substituteKeywords (const QCString & s, const char * title, const char * projName, const char * projNum, const char * projBrief)
Definition at line 5224 of file util.cpp.
References Config_getString, dateToString(), stripPath(), substitute(), versionString, and yearToString().
Referenced by LatexGenerator::endIndexSection(), LatexGenerator::startIndexSection(), and substituteHtmlKeywords().
substituteTemplateArgumentsInString()
QCString substituteTemplateArgumentsInString (const QCString & name, ArgumentList * formalArgs, ArgumentList * actualArgs)
Substitutes any occurrence of a formal argument from argument list formalArgs in name by the corresponding actual argument in argument list actualArgs. The result after substitution is returned as a string. The argument name is used to prevent recursive substitution.
Definition at line 6202 of file util.cpp.
References Argument::defval, leftScopeMatch(), Argument::name, substituteTemplateArgumentsInString(), and Argument::type.
Referenced by computeTemplateClassRelations(), MemberDef::createTemplateInstanceMember(), findBaseClassesForClass(), findUsedClassesForClass(), newResolveTypedef(), and substituteTemplateArgumentsInString().
substTypedef()
static QCString substTypedef (Definition * scope, FileDef * fileScope, const QCString & name, MemberDef ** pTypeDef = 0) static
Substitutes a simple unqualified name within scope. Returns the value of the typedef or name if no typedef was found.
Definition at line 667 of file util.cpp.
References DefinitionIntf::definitionType(), isAccessibleFromWithExpScope(), MemberDef::isTypedef(), Doxygen::symbolMap, DefinitionIntf::TypeMember, MemberDef::typeString(), and DefinitionIntf::TypeSymbolList.
Referenced by followPath().
tempArgListToString()
QCString tempArgListToString (ArgumentList * al, SrcLangExt lang)
Definition at line 2279 of file util.cpp.
References isId(), Argument::name, removeRedundantWhiteSpace(), SrcLangExt_CSharp, SrcLangExt_Java, Argument::type, and Argument::typeConstraint.
Referenced by findMember(), findTemplateInstanceRelation(), ClassDef::qualifiedNameWithTemplateParameters(), searchTemplateSpecs(), and writeDefArgumentList().
transcodeCharacterBuffer()
static int transcodeCharacterBuffer (const char * fileName, BufStr & srcBuf, int size, const char * inputEncoding, const char * outputEncoding) static
Definition at line 7746 of file util.cpp.
References BufStr::data(), err(), portable_iconv(), portable_iconv_close(), portable_iconv_open(), and BufStr::shrink().
Referenced by readInputFile().
transcodeCharacterStringToUTF8()
QCString transcodeCharacterStringToUTF8 (const QCString & input)
Definition at line 2462 of file util.cpp.
References Config_getString, err(), portable_iconv(), portable_iconv_close(), and portable_iconv_open().
Referenced by readCodeFragment().
trimBaseClassScope()
void trimBaseClassScope (BaseClassList * bcl, QCString & s, int level = 0)
Definition at line 2848 of file util.cpp.
References ClassDef::baseClasses(), BaseClassDef::classDef, and Definition::name().
Referenced by matchArgument().
trimScope()
static QCString trimScope (const QCString & name, const QCString & s) static
Definition at line 2822 of file util.cpp.
References findScopePattern().
Referenced by matchArgument().
trimTemplateSpecifiers()
static QCString trimTemplateSpecifiers (const QCString & namespaceName, const QCString & className, const QCString & s) static
Definition at line 2691 of file util.cpp.
References getClass(), getScopeFragment(), mergeScopes(), Definition::name(), and ClassDef::qualifiedNameWithTemplateParameters().
Referenced by matchArgument().
updateLanguageMapping()
bool updateLanguageMapping (const QCString & extension, const QCString & language)
Definition at line 7071 of file util.cpp.
References err(), g_lang2extMap, Lang2ExtMap::langName, Lang2ExtMap::parserId, Doxygen::parserManager, and Lang2ExtMap::parserName.
Referenced by addCodeOnlyMappings(), adjustConfiguration(), and initDefaultExtensionMapping().
writeColoredImgData()
void writeColoredImgData (const char * dir, ColoredImgDataItem data[])
Writes the intensity only bitmap representated by data as an image to directory dir using the colors defined by HTML_COLORSTYLE_*.
Definition at line 8000 of file util.cpp.
References IndexList::addImageFile(), ColoredImgDataItem::alpha, Config_getInt, ColoredImgDataItem::content, ColoredImgDataItem::height, Doxygen::indexList, ColoredImgDataItem::name, ColoredImage::save(), and ColoredImgDataItem::width.
Referenced by ResourceMgr::copyResourceAs().
writeExample()
void writeExample (OutputList & ol, ExampleSDict * ed)
Definition at line 2186 of file util.cpp.
References Example::anchor, SDict< T >::at(), SDict< T >::count(), OutputList::disable(), Example::file, OutputGenerator::Html, OutputGenerator::Latex, OutputGenerator::Man, Example::name, OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputGenerator::RTF, theTranslator, Translator::trWriteList(), OutputList::writeObjectLink(), and OutputList::writeString().
Referenced by MemberDef::_writeExamples(), and ClassDef::writeDetailedDocumentationBody().
writeExtraLatexPackages()
void writeExtraLatexPackages (FTextStream & t)
Definition at line 8730 of file util.cpp.
References Config_getList.
Referenced by FormulaList::generateBitmaps(), and writeDefaultHeaderPart1().
writePageRef()
void writePageRef (OutputDocInterface & od, const char * cn, const char * mn)
Definition at line 247 of file util.cpp.
References Config_getBool, OutputDocInterface::disable(), BaseOutputDocInterface::docify(), BaseOutputDocInterface::endPageRef(), OutputGenerator::Html, OutputGenerator::Latex, OutputGenerator::Man, OutputDocInterface::popGeneratorState(), OutputDocInterface::pushGeneratorState(), OutputGenerator::RTF, BaseOutputDocInterface::startPageRef(), theTranslator, and Translator::trPageAbbreviation().
Referenced by MemberDef::_writeReimplementedBy(), MemberDef::_writeReimplements(), and generateLink().
writeTypeConstraints()
void writeTypeConstraints (OutputList & ol, Definition * d, ArgumentList * al)
Definition at line 7696 of file util.cpp.
References Definition::docFile(), Definition::docLine(), Argument::docs, OutputList::endConstraintDocs(), OutputList::endConstraintList(), OutputList::endConstraintParam(), OutputList::endConstraintType(), OutputList::generateDoc(), linkifyText(), Argument::name, OutputList::parseText(), OutputList::startConstraintDocs(), OutputList::startConstraintList(), OutputList::startConstraintParam(), OutputList::startConstraintType(), theTranslator, Translator::trTypeConstraints(), and Argument::type.
Referenced by MemberDef::_writeTypeConstraints(), and ClassDef::writeDetailedDocumentationBody().
writeUtf8Char()
const char* writeUtf8Char (FTextStream & t, const char * s)
Definition at line 7276 of file util.cpp.
Referenced by HtmlCodeGenerator::codify(), ManGenerator::codify(), RTFGenerator::codify(), and writeXMLCodeString().
yearToString()
QCString yearToString ()
Definition at line 2603 of file util.cpp.
Referenced by substituteKeywords().
Variable Documentation
aliasesProcessed
QDict<void> aliasesProcessed static
Definition at line 7398 of file util.cpp.
constScope
const char constScope[] = { 'c', 'o', 'n', 's', 't', ':' } static
Definition at line 1652 of file util.cpp.
Referenced by removeRedundantWhiteSpace().
g_charAroundSpace
CharAroundSpace g_charAroundSpace static
Definition at line 1694 of file util.cpp.
g_extLookup
QDict<int> g_extLookup static
Definition at line 7039 of file util.cpp.
g_lang2extMap
struct Lang2ExtMap g_lang2extMap[] static
Initial value:
=
{
  { "idl",         "c",             SrcLangExt_IDL      },
  { "java",        "c",             SrcLangExt_Java     },
  { "javascript",  "c",             SrcLangExt_JS       },
  { "csharp",      "c",             SrcLangExt_CSharp   },
  { "d",           "c",             SrcLangExt_D        },
  { "php",         "c",             SrcLangExt_PHP      },
  { "objective-c", "c",             SrcLangExt_ObjC     },
  { "c",           "c",             SrcLangExt_Cpp      },
  { "c++",         "c",             SrcLangExt_Cpp      },
  { "python",      "python",        SrcLangExt_Python   },
  { "fortran",     "fortran",       SrcLangExt_Fortran  },
  { "fortranfree", "fortranfree",   SrcLangExt_Fortran  },
  { "fortranfixed", "fortranfixed", SrcLangExt_Fortran  },
  { "vhdl",        "vhdl",          SrcLangExt_VHDL     },
  { "xml",         "xml",           SrcLangExt_XML      },
  { "sql",         "sql",           SrcLangExt_SQL      },
  { "tcl",         "tcl",           SrcLangExt_Tcl      },
  { "md",          "md",            SrcLangExt_Markdown },
  { 0,             0,              (SrcLangExt)0        }
}
Referenced by updateLanguageMapping().
g_resolvedTypedefs
QDict<MemberDef> g_resolvedTypedefs static
Definition at line 515 of file util.cpp.
Referenced by getResolvedClass(), and newResolveTypedef().
g_visitedNamespaces
QDict<Definition> g_visitedNamespaces static
Definition at line 516 of file util.cpp.
Referenced by getMemberFromSymbol(), getResolvedSymbol(), and isAccessibleFromWithExpScope().
MAX_STACK_SIZE
const int MAX_STACK_SIZE = 1000
Definition at line 872 of file util.cpp.
Referenced by AccessStack::push().
maxInheritanceDepth
const int maxInheritanceDepth = 100000
Definition at line 148 of file util.cpp.
Referenced by getDefs(), ClassDef::getMemberByName(), and minClassDistance().
operatorScope
const char operatorScope[] = { 'o', 'p', 'e', 'r', 'a', 't', 'o', 'r', '?', '?', '?' } static
Definition at line 1654 of file util.cpp.
Referenced by removeRedundantWhiteSpace().
virtualScope
const char virtualScope[] = { 'v', 'i', 'r', 't', 'u', 'a', 'l', ':' } static
Definition at line 1653 of file util.cpp.
Referenced by removeRedundantWhiteSpace().