Doxygen: PerlModOutput Class Reference
PerlModOutput Class Reference
Public Member Functions
PerlModOutput (bool pretty)
virtual ~PerlModOutput ()
void setPerlModOutputStream (PerlModOutputStream *os)
PerlModOutput & openSave ()
PerlModOutput & closeSave (QCString &s)
PerlModOutput & continueBlock ()
PerlModOutput & add (char c)
PerlModOutput & add (const char *s)
PerlModOutput & add (QCString &s)
PerlModOutput & add (int n)
PerlModOutput & add (unsigned int n)
PerlModOutput & addQuoted (const char *s)
PerlModOutput & indent ()
PerlModOutput & open (char c, const char *s=0)
PerlModOutput & close (char c=0)
PerlModOutput & addField (const char *s)
PerlModOutput & addFieldQuotedChar (const char *field, char content)
PerlModOutput & addFieldQuotedString (const char *field, const char *content)
PerlModOutput & addFieldBoolean (const char *field, bool content)
PerlModOutput & openList (const char *s=0)
PerlModOutput & closeList ()
PerlModOutput & openHash (const char *s=0)
PerlModOutput & closeHash ()
Public Attributes
bool m_pretty
Protected Member Functions
void iopenSave ()
void icloseSave (QCString &)
void incIndent ()
void decIndent ()
void iaddQuoted (const char *)
void iaddFieldQuotedChar (const char *, char)
void iaddFieldQuotedString (const char *, const char *)
void iaddField (const char *)
void iopen (char, const char *)
void iclose (char)
Private Attributes
PerlModOutputStream * m_stream
int m_indentation
bool m_blockstart
QStack< PerlModOutputStream > m_saved
char m_spaces [PERLOUTPUT_MAX_INDENTATION *2+2]
Detailed Description
Definition at line 105 of file perlmodgen.cpp.
Constructor & Destructor Documentation
PerlModOutput()
PerlModOutput::PerlModOutput (bool pretty) inline
Definition at line 111 of file perlmodgen.cpp.
References m_spaces.
~PerlModOutput()
virtual PerlModOutput::~PerlModOutput () inline virtual
Definition at line 117 of file perlmodgen.cpp.
Member Function Documentation
add() [1/5]
PerlModOutput& PerlModOutput::add (char c) inline
Definition at line 134 of file perlmodgen.cpp.
References PerlModOutputStream::add(), and m_stream.
Referenced by addPerlModDocBlock(), PerlModDocVisitor::enterText(), PerlModDocVisitor::finish(), PerlModGenerator::generatePerlModOutput(), PerlModDocVisitor::leaveText(), PerlModDocVisitor::visit(), PerlModDocVisitor::visitPost(), and PerlModDocVisitor::visitPre().
add() [2/5]
PerlModOutput& PerlModOutput::add (const char * s) inline
Definition at line 135 of file perlmodgen.cpp.
References PerlModOutputStream::add(), and m_stream.
add() [3/5]
PerlModOutput& PerlModOutput::add (QCString & s) inline
Definition at line 136 of file perlmodgen.cpp.
References PerlModOutputStream::add(), and m_stream.
add() [4/5]
PerlModOutput& PerlModOutput::add (int n) inline
Definition at line 137 of file perlmodgen.cpp.
References PerlModOutputStream::add(), and m_stream.
add() [5/5]
PerlModOutput& PerlModOutput::add (unsigned int n) inline
Definition at line 138 of file perlmodgen.cpp.
References PerlModOutputStream::add(), and m_stream.
addField()
PerlModOutput& PerlModOutput::addField (const char * s) inline
Definition at line 154 of file perlmodgen.cpp.
References iaddField().
Referenced by addPerlModDocBlock(), and PerlModDocVisitor::enterText().
addFieldBoolean()
PerlModOutput& PerlModOutput::addFieldBoolean (const char * field, bool content) inline
Definition at line 163 of file perlmodgen.cpp.
References addFieldQuotedString().
Referenced by PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForMember(), and PerlModDocVisitor::visit().
addFieldQuotedChar()
PerlModOutput& PerlModOutput::addFieldQuotedChar (const char * field, char content) inline
Definition at line 155 of file perlmodgen.cpp.
References iaddFieldQuotedChar().
Referenced by PerlModDocVisitor::visit().
addFieldQuotedString()
PerlModOutput& PerlModOutput::addFieldQuotedString (const char * field, const char * content) inline
Definition at line 159 of file perlmodgen.cpp.
References iaddFieldQuotedString().
Referenced by addFieldBoolean(), PerlModDocVisitor::addLink(), PerlModGenerator::addListOfAllMembers(), addTemplateArgumentList(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), PerlModGenerator::generatePerlModSection(), PerlModDocVisitor::openItem(), PerlModDocVisitor::visit(), and PerlModDocVisitor::visitPre().
addQuoted()
PerlModOutput& PerlModOutput::addQuoted (const char * s) inline
Definition at line 140 of file perlmodgen.cpp.
References iaddQuoted().
Referenced by PerlModDocVisitor::visit(), and PerlModDocVisitor::visitPre().
close()
PerlModOutput& PerlModOutput::close (char c = 0) inline
Definition at line 152 of file perlmodgen.cpp.
References iclose().
Referenced by closeHash(), and closeList().
closeHash()
PerlModOutput& PerlModOutput::closeHash () inline
Definition at line 170 of file perlmodgen.cpp.
References close().
Referenced by addPerlModDocBlock(), addTemplateArgumentList(), PerlModDocVisitor::closeItem(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), PerlModGenerator::generatePerlModOutput(), PerlModGenerator::generatePerlModSection(), PerlModDocVisitor::leaveText(), PerlModDocVisitor::visitPost(), and PerlModDocVisitor::visitPre().
closeList()
PerlModOutput& PerlModOutput::closeList () inline
Definition at line 168 of file perlmodgen.cpp.
References close().
Referenced by PerlModGenerator::addListOfAllMembers(), addTemplateArgumentList(), PerlModDocVisitor::closeSubBlock(), PerlModDocVisitor::finish(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModOutput(), PerlModGenerator::generatePerlModSection(), PerlModDocVisitor::visitPost(), and PerlModDocVisitor::visitPre().
closeSave()
PerlModOutput& PerlModOutput::closeSave (QCString & s) inline
Definition at line 122 of file perlmodgen.cpp.
References icloseSave().
continueBlock()
PerlModOutput& PerlModOutput::continueBlock () inline
Definition at line 124 of file perlmodgen.cpp.
References PerlModOutputStream::add(), indent(), m_blockstart, and m_stream.
Referenced by iaddField(), and iopen().
decIndent()
void PerlModOutput::decIndent () protected
Definition at line 221 of file perlmodgen.cpp.
References m_indentation, m_spaces, and PERLOUTPUT_MAX_INDENTATION.
Referenced by iclose().
iaddField()
void PerlModOutput::iaddField (const char * s) protected
Definition at line 238 of file perlmodgen.cpp.
References PerlModOutputStream::add(), continueBlock(), m_pretty, and m_stream.
Referenced by addField(), iaddFieldQuotedChar(), iaddFieldQuotedString(), and iopen().
iaddFieldQuotedChar()
void PerlModOutput::iaddFieldQuotedChar (const char * field, char content) protected
Definition at line 245 of file perlmodgen.cpp.
References PerlModOutputStream::add(), iaddField(), and m_stream.
Referenced by addFieldQuotedChar().
iaddFieldQuotedString()
void PerlModOutput::iaddFieldQuotedString (const char * field, const char * content) protected
Definition at line 255 of file perlmodgen.cpp.
References PerlModOutputStream::add(), iaddField(), iaddQuoted(), and m_stream.
Referenced by addFieldQuotedString().
iaddQuoted()
void PerlModOutput::iaddQuoted (const char * s) protected
Definition at line 228 of file perlmodgen.cpp.
References PerlModOutputStream::add(), and m_stream.
Referenced by addQuoted(), and iaddFieldQuotedString().
iclose()
void PerlModOutput::iclose (char c) protected
Definition at line 276 of file perlmodgen.cpp.
References PerlModOutputStream::add(), decIndent(), indent(), m_blockstart, and m_stream.
Referenced by close().
icloseSave()
void PerlModOutput::icloseSave (QCString & s) protected
Definition at line 204 of file perlmodgen.cpp.
References PerlModOutputStream::m_s, m_saved, and m_stream.
Referenced by closeSave().
incIndent()
void PerlModOutput::incIndent () protected
Definition at line 211 of file perlmodgen.cpp.
References m_indentation, m_spaces, and PERLOUTPUT_MAX_INDENTATION.
Referenced by iopen().
indent()
PerlModOutput& PerlModOutput::indent () inline
Definition at line 142 of file perlmodgen.cpp.
References PerlModOutputStream::add(), m_spaces, and m_stream.
Referenced by continueBlock(), and iclose().
iopen()
void PerlModOutput::iopen (char c, const char * s) protected
Definition at line 265 of file perlmodgen.cpp.
References PerlModOutputStream::add(), continueBlock(), iaddField(), incIndent(), m_blockstart, and m_stream.
Referenced by open().
iopenSave()
void PerlModOutput::iopenSave () protected
Definition at line 198 of file perlmodgen.cpp.
References m_saved, and m_stream.
Referenced by openSave().
open()
PerlModOutput& PerlModOutput::open (char c, const char * s = 0) inline
Definition at line 151 of file perlmodgen.cpp.
References iopen().
Referenced by openHash(), and openList().
openHash()
PerlModOutput& PerlModOutput::openHash (const char * s = 0) inline
Definition at line 169 of file perlmodgen.cpp.
References open().
Referenced by PerlModGenerator::addListOfAllMembers(), addPerlModDocBlock(), addTemplateArgumentList(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModForPage(), PerlModGenerator::generatePerlModOutput(), PerlModGenerator::generatePerlModSection(), PerlModDocVisitor::openItem(), and PerlModDocVisitor::visitPre().
openList()
PerlModOutput& PerlModOutput::openList (const char * s = 0) inline
Definition at line 167 of file perlmodgen.cpp.
References open().
Referenced by PerlModGenerator::addListOfAllMembers(), addTemplateArgumentList(), PerlModGenerator::generatePerlModForClass(), PerlModGenerator::generatePerlModForFile(), PerlModGenerator::generatePerlModForGroup(), PerlModGenerator::generatePerlModForMember(), PerlModGenerator::generatePerlModForNamespace(), PerlModGenerator::generatePerlModOutput(), PerlModGenerator::generatePerlModSection(), PerlModDocVisitor::openSubBlock(), PerlModDocVisitor::PerlModDocVisitor(), and PerlModDocVisitor::visitPre().
openSave()
PerlModOutput& PerlModOutput::openSave () inline
Definition at line 121 of file perlmodgen.cpp.
References iopenSave().
setPerlModOutputStream()
void PerlModOutput::setPerlModOutputStream (PerlModOutputStream * os) inline
Definition at line 119 of file perlmodgen.cpp.
References m_stream.
Referenced by PerlModGenerator::generatePerlModOutput().
Member Data Documentation
m_blockstart
bool PerlModOutput::m_blockstart private
Definition at line 192 of file perlmodgen.cpp.
Referenced by continueBlock(), iclose(), and iopen().
m_indentation
int PerlModOutput::m_indentation private
Definition at line 191 of file perlmodgen.cpp.
Referenced by decIndent(), and incIndent().
m_pretty
bool PerlModOutput::m_pretty
Definition at line 109 of file perlmodgen.cpp.
Referenced by iaddField().
m_saved
QStack<PerlModOutputStream> PerlModOutput::m_saved private
Definition at line 194 of file perlmodgen.cpp.
Referenced by icloseSave(), and iopenSave().
m_spaces
char PerlModOutput::m_spaces[PERLOUTPUT_MAX_INDENTATION *2+2] private
Definition at line 195 of file perlmodgen.cpp.
Referenced by decIndent(), incIndent(), indent(), and PerlModOutput().
m_stream
PerlModOutputStream* PerlModOutput::m_stream private
Definition at line 190 of file perlmodgen.cpp.
Referenced by add(), continueBlock(), iaddField(), iaddFieldQuotedChar(), iaddFieldQuotedString(), iaddQuoted(), iclose(), icloseSave(), indent(), iopen(), iopenSave(), and setPerlModOutputStream().
The documentation for this class was generated from the following file:
src/perlmodgen.cpp