Doxygen: src/template.cpp File Reference
template.cpp File Reference
#include "template.h"
#include <stdio.h>
#include <stdarg.h>
#include <qlist.h>
#include <qarray.h>
#include <qdict.h>
#include <qstrlist.h>
#include <qvaluelist.h>
#include <qstack.h>
#include <qfile.h>
#include <qregexp.h>
#include <qcstring.h>
#include <qdir.h>
#include "sortdict.h"
#include "ftextstream.h"
#include "message.h"
#include "util.h"
#include "resourcemgr.h"
#include "portable.h"
Classes
class TemplateStruct::Private
Private data of a template struct object.
class TemplateList::Private
Private data of a template list object.
class TemplateListConstIterator
class Operator
Class representing operators that can appear in template expressions.
class TemplateBlockContext
Class holding stacks of blocks available in the context.
struct TemplateKeyValue
A container to store a key-value pair.
class TemplateContextImpl
Internal class representing the implementation of a template context.
class FilterAdd
The implementation of the "add" filter.
class FilterGet
The implementation of the "get" filter.
class FilterRaw
The implementation of the "raw" filter.
class FilterList
The implementation of the "list" filter.
class FilterTexLabel
The implementation of the "texlabel" filter.
class FilterTexIndex
The implementation of the "texindex" filter.
class FilterAppend
The implementation of the "append" filter.
class FilterPrepend
The implementation of the "prepend" filter.
class FilterLength
The implementation of the "length" filter.
class FilterDefault
The implementation of the "default" filter.
class FilterFlatten
The implementation of the "flatten" filter.
class FilterListSort
The implementation of the "listsort" filter.
struct FilterListSort::ListElem
class FilterListSort::SortList
class FilterGroupBy
The implementation of the "groupBy" filter.
struct FilterGroupBy::ListElem
class FilterGroupBy::SortList
class FilterRelative
The implementation of the "relative" filter.
class FilterPaginate
The implementation of the "paginate" filter.
class FilterAlphaIndex
The implementation of the "alphaIndex" filter.
struct FilterAlphaIndex::ListElem
class FilterAlphaIndex::SortList
class FilterStripPath
The implementation of the "default" filter.
class FilterNoWrap
The implementation of the "default" filter.
class FilterDivisibleBy
The implementation of the "divisibleby" filter.
class FilterIsRelativeURL
The implementation of the "isRelativeURL" filter.
class FilterIsAbsoluteURL
The implementation of the "isRelativeURL" filter.
class FilterDecodeURL
The implementation of the "decodeURL" filter The leading character is removed from the value in case it is a ^ or !.
class TemplateFilterFactory
Factory singleton for registering and creating filters.
class TemplateFilterFactory::AutoRegister< T >
Helper class for registering a filter function.
class ExprAst
Base class for all nodes in the abstract syntax tree of an expression.
class ExprAstNumber
Class representing a number in the AST.
class ExprAstVariable
Class representing a variable in the AST.
class ExprAstFunctionVariable
class ExprAstFilter
Class representing a filter in the AST.
class ExprAstFilterAppl
Class representing a filter applied to an expression in the AST.
class ExprAstLiteral
Class representing a string literal in the AST.
class ExprAstNegate
Class representing a negation (not) operator in the AST.
class ExprAstUnary
class ExprAstBinary
Class representing a binary operator in the AST.
class TemplateNode
Base class of all nodes in a template's AST.
class TemplateParser
Parser for templates.
class ExpressionParser
Recursive decent parser for Django style template expressions.
class ExpressionParser::ExprToken
Class representing a token within an expression.
class TemplateToken
Class representing a lexical token in a template.
class TemplateNodeList
Class representing a list of AST nodes in a template.
class TemplateImpl
Internal class representing the implementation of a template.
class TemplateStructWeakRef
Weak reference wrapper for TemplateStructIntf that provides access to the wrapped struct without holding a reference.
class TemplateNodeText
Class representing a piece of plain text in a template.
class TemplateNodeVariable
Class representing a variable in a template.
class TemplateNodeCreator< T >
Helper class for creating template AST tag nodes and returning the template for a given node.
class TemplateNodeIf
Class representing an 'if' tag in a template.
struct TemplateNodeIf::GuardedNodes
class TemplateNodeRepeat
Class representing a 'for' tag in a template.
class TemplateNodeRange
Class representing a 'range' tag in a template.
class TemplateNodeFor
Class representing a 'for' tag in a template.
class TemplateNodeMsg
Class representing an 'markers' tag in a template.
class TemplateNodeBlock
Class representing a 'block' tag in a template.
class TemplateNodeExtend
Class representing a 'extend' tag in a template.
class TemplateNodeInclude
Class representing an 'include' tag in a template.
class TemplateNodeCreate
Class representing an 'create' tag in a template.
class TemplateNodeTree
Class representing an 'tree' tag in a template.
struct TemplateNodeTree::TreeContext
class TemplateNodeIndexEntry
Class representing an 'indexentry' tag in a template.
struct TemplateNodeIndexEntry::Mapping
class TemplateNodeOpenSubIndex
Class representing an 'opensubindex' tag in a template.
class TemplateNodeCloseSubIndex
Class representing an 'closesubindex' tag in a template.
class TemplateNodeWith
Class representing an 'with' tag in a template.
struct TemplateNodeWith::Mapping
class TemplateNodeCycle
Class representing an 'cycle' tag in a template.
class TemplateNodeSet
Class representing an 'set' tag in a template.
struct TemplateNodeSet::Mapping
class TemplateNodeSpaceless
Class representing an 'spaceless' tag in a template.
class TemplateNodeMarkers
Class representing an 'markers' tag in a template.
class TemplateNodeTabbing
Class representing an 'tabbing' tag in a template.
class TemplateNodeResource
Class representing an 'markers' tag in a template.
class TemplateNodeEncoding
Class representing the 'encoding' tag in a template.
class TemplateNodeFactory
Factory class for creating tag AST nodes found in a template.
class TemplateNodeFactory::AutoRegister< T >
Helper class for registering a template AST node.
class TemplateLexer
Lexer class for turning a template into a list of tokens.
class TemplateEngine::Private
Private data of the template engine.
class TemplateEngine::Private::IncludeEntry
Macros
#define ENABLE_TRACING 0
#define TRACE(x)
Functions
static QValueList< QCString > split (const QCString &str, const QCString &sep, bool allowEmptyEntries=FALSE, bool cleanup=TRUE)
static QCString removeSpacesAroundEquals (const char *s)
Strips spaces surrounding = from string in, so foo = 10 bar=5 baz= 'hello' will become foo=10 bar=5 baz='hello'
static void getPathListFunc (TemplateStructIntf *entry, TemplateList *list)
static TemplateVariant getPathFunc (const void *ctx, const QValueList< TemplateVariant > &)
static void stripLeadingWhiteSpace (QGString &s)
Variables
static TemplateFilterFactory::AutoRegister< FilterAdd > fAdd ("add")
static TemplateFilterFactory::AutoRegister< FilterGet > fGet ("get")
static TemplateFilterFactory::AutoRegister< FilterRaw > fRaw ("raw")
static TemplateFilterFactory::AutoRegister< FilterList > fList ("list")
static TemplateFilterFactory::AutoRegister< FilterAppend > fAppend ("append")
static TemplateFilterFactory::AutoRegister< FilterLength > fLength ("length")
static TemplateFilterFactory::AutoRegister< FilterNoWrap > fNoWrap ("nowrap")
static TemplateFilterFactory::AutoRegister< FilterFlatten > fFlatten ("flatten")
static TemplateFilterFactory::AutoRegister< FilterDefault > fDefault ("default")
static TemplateFilterFactory::AutoRegister< FilterPrepend > fPrepend ("prepend")
static TemplateFilterFactory::AutoRegister< FilterGroupBy > fGroupBy ("groupBy")
static TemplateFilterFactory::AutoRegister< FilterRelative > fRelative ("relative")
static TemplateFilterFactory::AutoRegister< FilterListSort > fListSort ("listsort")
static TemplateFilterFactory::AutoRegister< FilterTexLabel > fTexLabel ("texLabel")
static TemplateFilterFactory::AutoRegister< FilterTexIndex > fTexIndex ("texIndex")
static TemplateFilterFactory::AutoRegister< FilterPaginate > fPaginate ("paginate")
static TemplateFilterFactory::AutoRegister< FilterStripPath > fStripPath ("stripPath")
static TemplateFilterFactory::AutoRegister< FilterDecodeURL > fDecodeURL ("decodeURL")
static TemplateFilterFactory::AutoRegister< FilterAlphaIndex > fAlphaIndex ("alphaIndex")
static TemplateFilterFactory::AutoRegister< FilterDivisibleBy > fDivisibleBy ("divisibleby")
static TemplateFilterFactory::AutoRegister< FilterIsRelativeURL > fIsRelativeURL ("isRelativeURL")
static TemplateFilterFactory::AutoRegister< FilterIsAbsoluteURL > fIsAbsoluteURL ("isAbsoluteURL")
static TemplateNodeFactory::AutoRegister< TemplateNodeIf > autoRefIf ("if")
static TemplateNodeFactory::AutoRegister< TemplateNodeFor > autoRefFor ("for")
static TemplateNodeFactory::AutoRegister< TemplateNodeMsg > autoRefMsg ("msg")
static TemplateNodeFactory::AutoRegister< TemplateNodeSet > autoRefSet ("set")
static TemplateNodeFactory::AutoRegister< TemplateNodeTree > autoRefTree ("recursetree")
static TemplateNodeFactory::AutoRegister< TemplateNodeWith > autoRefWith ("with")
static TemplateNodeFactory::AutoRegister< TemplateNodeBlock > autoRefBlock ("block")
static TemplateNodeFactory::AutoRegister< TemplateNodeCycle > autoRefCycle ("cycle")
static TemplateNodeFactory::AutoRegister< TemplateNodeRange > autoRefRange ("range")
static TemplateNodeFactory::AutoRegister< TemplateNodeExtend > autoRefExtend ("extend")
static TemplateNodeFactory::AutoRegister< TemplateNodeCreate > autoRefCreate ("create")
static TemplateNodeFactory::AutoRegister< TemplateNodeRepeat > autoRefRepeat ("repeat")
static TemplateNodeFactory::AutoRegister< TemplateNodeInclude > autoRefInclude ("include")
static TemplateNodeFactory::AutoRegister< TemplateNodeMarkers > autoRefMarkers ("markers")
static TemplateNodeFactory::AutoRegister< TemplateNodeTabbing > autoRefTabbing ("tabbing")
static TemplateNodeFactory::AutoRegister< TemplateNodeResource > autoRefResource ("resource")
static TemplateNodeFactory::AutoRegister< TemplateNodeEncoding > autoRefEncoding ("encoding")
static TemplateNodeFactory::AutoRegister< TemplateNodeSpaceless > autoRefSpaceless ("spaceless")
static TemplateNodeFactory::AutoRegister< TemplateNodeIndexEntry > autoRefIndexEntry ("indexentry")
static TemplateNodeFactory::AutoRegister< TemplateNodeOpenSubIndex > autoRefOpenSubIndex ("opensubindex")
static TemplateNodeFactory::AutoRegister< TemplateNodeCloseSubIndex > autoRefCloseSubIndex ("closesubindex")
Macro Definition Documentation
ENABLE_TRACING
#define ENABLE_TRACING 0
Definition at line 39 of file template.cpp.
TRACE
#define TRACE (x)
Definition at line 44 of file template.cpp.
Referenced by ExprAstFilter::apply(), ExprAstBinary::ExprAstBinary(), ExprAstFilter::ExprAstFilter(), ExprAstFilterAppl::ExprAstFilterAppl(), ExprAstFunctionVariable::ExprAstFunctionVariable(), ExprAstLiteral::ExprAstLiteral(), ExprAstNegate::ExprAstNegate(), ExprAstNumber::ExprAstNumber(), ExprAstUnary::ExprAstUnary(), ExprAstVariable::ExprAstVariable(), TemplateParser::parse(), ExpressionParser::parseAdditiveExpression(), ExpressionParser::parseAndExpression(), ExpressionParser::parseCompareExpression(), ExpressionParser::parseExpression(), ExpressionParser::parseFilter(), ExpressionParser::parseFilteredVariable(), ExpressionParser::parseIdentifier(), ExpressionParser::parseIdentifierOptionalArgs(), ExpressionParser::parseLiteral(), ExpressionParser::parseMultiplicativeExpression(), ExpressionParser::parseNotExpression(), ExpressionParser::parseNumber(), ExpressionParser::parseOrExpression(), ExpressionParser::parsePrimaryExpression(), ExpressionParser::parseUnaryExpression(), TemplateNodeList::render(), TemplateNodeBlock::TemplateNodeBlock(), TemplateNodeCloseSubIndex::TemplateNodeCloseSubIndex(), TemplateNodeCreate::TemplateNodeCreate(), TemplateNodeCycle::TemplateNodeCycle(), TemplateNodeEncoding::TemplateNodeEncoding(), TemplateNodeExtend::TemplateNodeExtend(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeIf::TemplateNodeIf(), TemplateNodeInclude::TemplateNodeInclude(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeMarkers::TemplateNodeMarkers(), TemplateNodeMsg::TemplateNodeMsg(), TemplateNodeOpenSubIndex::TemplateNodeOpenSubIndex(), TemplateNodeRange::TemplateNodeRange(), TemplateNodeRepeat::TemplateNodeRepeat(), TemplateNodeResource::TemplateNodeResource(), TemplateNodeSet::TemplateNodeSet(), TemplateNodeSpaceless::TemplateNodeSpaceless(), TemplateNodeTabbing::TemplateNodeTabbing(), TemplateNodeText::TemplateNodeText(), TemplateNodeTree::TemplateNodeTree(), TemplateNodeVariable::TemplateNodeVariable(), and TemplateNodeWith::TemplateNodeWith().
Function Documentation
getPathFunc()
static TemplateVariant getPathFunc (const void * ctx, const QValueList< TemplateVariant > &) static
Definition at line 2611 of file template.cpp.
References TemplateList::alloc(), and getPathListFunc().
Referenced by TemplateContextImpl::addIndexEntry().
getPathListFunc()
static void getPathListFunc (TemplateStructIntf * entry, TemplateList * list) static
Definition at line 2601 of file template.cpp.
References TemplateList::append(), TemplateStructIntf::get(), TemplateVariant::Struct, TemplateVariant::toStruct(), and TemplateVariant::type().
Referenced by getPathFunc().
removeSpacesAroundEquals()
static QCString removeSpacesAroundEquals (const char * s) static
Strips spaces surrounding = from string in, so foo = 10 bar=5 baz= 'hello' will become foo=10 bar=5 baz='hello'
Definition at line 105 of file template.cpp.
Referenced by TemplateNodeWith::TemplateNodeWith().
split()
static QValueList<QCString> split (const QCString & str, const QCString & sep, bool allowEmptyEntries = FALSE, bool cleanup = TRUE) static
Definition at line 51 of file template.cpp.
Referenced by vhdl::parser::VhdlParser::addProto(), vhdl::parser::VhdlParser::addVhdlType(), FlowChart::alignCommentNode(), assignBinding(), vhdl::parser::VhdlParser::createFunction(), VhdlDocGen::findAllArchitectures(), VhdlDocGen::findArchitecture(), formatBriefNote(), VhdlDocGen::getIndexWord(), Qhp::initialize(), VhdlDocGen::parseForBinding(), VhdlDocGen::parseForConfig(), TemplateNodeCycle::TemplateNodeCycle(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeWith::TemplateNodeWith(), VhdlDocGen::writeInlineClassLink(), VhdlDocGen::writeRecorUnit(), and VhdlDocGen::writeRecUnitDocu().
stripLeadingWhiteSpace()
static void stripLeadingWhiteSpace (QGString & s) static
Definition at line 3599 of file template.cpp.
Referenced by TemplateNodeCreate::render().
Variable Documentation
autoRefBlock
TemplateNodeFactory::AutoRegister<TemplateNodeBlock> autoRefBlock("block") static
autoRefCloseSubIndex
TemplateNodeFactory::AutoRegister<TemplateNodeCloseSubIndex> autoRefCloseSubIndex("closesubindex") static
autoRefCreate
TemplateNodeFactory::AutoRegister<TemplateNodeCreate> autoRefCreate("create") static
autoRefCycle
TemplateNodeFactory::AutoRegister<TemplateNodeCycle> autoRefCycle("cycle") static
autoRefEncoding
TemplateNodeFactory::AutoRegister<TemplateNodeEncoding> autoRefEncoding("encoding") static
autoRefExtend
TemplateNodeFactory::AutoRegister<TemplateNodeExtend> autoRefExtend("extend") static
autoRefFor
TemplateNodeFactory::AutoRegister<TemplateNodeFor> autoRefFor("for") static
autoRefIf
TemplateNodeFactory::AutoRegister<TemplateNodeIf> autoRefIf("if") static
autoRefInclude
TemplateNodeFactory::AutoRegister<TemplateNodeInclude> autoRefInclude("include") static
autoRefIndexEntry
TemplateNodeFactory::AutoRegister<TemplateNodeIndexEntry> autoRefIndexEntry("indexentry") static
autoRefMarkers
TemplateNodeFactory::AutoRegister<TemplateNodeMarkers> autoRefMarkers("markers") static
autoRefMsg
TemplateNodeFactory::AutoRegister<TemplateNodeMsg> autoRefMsg("msg") static
autoRefOpenSubIndex
TemplateNodeFactory::AutoRegister<TemplateNodeOpenSubIndex> autoRefOpenSubIndex("opensubindex") static
autoRefRange
TemplateNodeFactory::AutoRegister<TemplateNodeRange> autoRefRange("range") static
autoRefRepeat
TemplateNodeFactory::AutoRegister<TemplateNodeRepeat> autoRefRepeat("repeat") static
autoRefResource
TemplateNodeFactory::AutoRegister<TemplateNodeResource> autoRefResource("resource") static
autoRefSet
TemplateNodeFactory::AutoRegister<TemplateNodeSet> autoRefSet("set") static
autoRefSpaceless
TemplateNodeFactory::AutoRegister<TemplateNodeSpaceless> autoRefSpaceless("spaceless") static
autoRefTabbing
TemplateNodeFactory::AutoRegister<TemplateNodeTabbing> autoRefTabbing("tabbing") static
autoRefTree
TemplateNodeFactory::AutoRegister<TemplateNodeTree> autoRefTree("recursetree") static
autoRefWith
TemplateNodeFactory::AutoRegister<TemplateNodeWith> autoRefWith("with") static
fAdd
TemplateFilterFactory::AutoRegister<FilterAdd> fAdd("add") static
fAlphaIndex
TemplateFilterFactory::AutoRegister<FilterAlphaIndex> fAlphaIndex("alphaIndex") static
fAppend
TemplateFilterFactory::AutoRegister<FilterAppend> fAppend("append") static
fDecodeURL
TemplateFilterFactory::AutoRegister<FilterDecodeURL> fDecodeURL("decodeURL") static
fDefault
TemplateFilterFactory::AutoRegister<FilterDefault> fDefault("default") static
fDivisibleBy
TemplateFilterFactory::AutoRegister<FilterDivisibleBy> fDivisibleBy("divisibleby") static
fFlatten
TemplateFilterFactory::AutoRegister<FilterFlatten> fFlatten("flatten") static
fGet
TemplateFilterFactory::AutoRegister<FilterGet> fGet("get") static
fGroupBy
TemplateFilterFactory::AutoRegister<FilterGroupBy> fGroupBy("groupBy") static
fIsAbsoluteURL
TemplateFilterFactory::AutoRegister<FilterIsAbsoluteURL> fIsAbsoluteURL("isAbsoluteURL") static
fIsRelativeURL
TemplateFilterFactory::AutoRegister<FilterIsRelativeURL> fIsRelativeURL("isRelativeURL") static
fLength
TemplateFilterFactory::AutoRegister<FilterLength> fLength("length") static
fList
TemplateFilterFactory::AutoRegister<FilterList> fList("list") static
fListSort
TemplateFilterFactory::AutoRegister<FilterListSort> fListSort("listsort") static
fNoWrap
TemplateFilterFactory::AutoRegister<FilterNoWrap> fNoWrap("nowrap") static
fPaginate
TemplateFilterFactory::AutoRegister<FilterPaginate> fPaginate("paginate") static
fPrepend
TemplateFilterFactory::AutoRegister<FilterPrepend> fPrepend("prepend") static
fRaw
TemplateFilterFactory::AutoRegister<FilterRaw> fRaw("raw") static
fRelative
TemplateFilterFactory::AutoRegister<FilterRelative> fRelative("relative") static
fStripPath
TemplateFilterFactory::AutoRegister<FilterStripPath> fStripPath("stripPath") static
fTexIndex
TemplateFilterFactory::AutoRegister<FilterTexIndex> fTexIndex("texIndex") static
fTexLabel
TemplateFilterFactory::AutoRegister<FilterTexLabel> fTexLabel("texLabel") static