Doxygen: ClassSDict Class Reference
ClassSDict Class Reference
A sorted dictionary of ClassDef objects.
#include <classlist.h>
Public Member Functions
ClassSDict (int size=17)
~ClassSDict ()
void writeDeclaration (OutputList &ol, const ClassDef::CompoundType *filter=0, const char *header=0, bool localNames=FALSE)
void writeDocumentation (OutputList &ol, Definition *container=0)
bool declVisible (const ClassDef::CompoundType *filter=0) const
Public Member Functions inherited from SDict< ClassDef >
SDict (int size=17, bool caseSensitive=TRUE)
virtual ~SDict ()
void append (const char *key, const ClassDef *d)
void prepend (const char *key, const ClassDef *d)
bool remove (const char *key)
ClassDef * take (const char *key)
void sort ()
void inSort (const char *key, const ClassDef *d)
void insertAt (int i, const char *key, const ClassDef *d)
void setAutoDelete (bool val)
ClassDef * find (const char *key)
ClassDef * find (const QCString &key)
ClassDef * find (const QString &key)
int findAt (const QCString &key)
ClassDef * operator[] (const char *key) const
ClassDef * at (uint i)
void clear ()
int count () const
Private Member Functions
int compareValues (const ClassDef *item1, const ClassDef *item2) const
Detailed Description
A sorted dictionary of ClassDef objects.
Definition at line 56 of file classlist.h.
Constructor & Destructor Documentation
ClassSDict()
ClassSDict::ClassSDict (int size = 17) inline
Definition at line 59 of file classlist.h.
~ClassSDict()
ClassSDict::~ClassSDict () inline
Definition at line 60 of file classlist.h.
Member Function Documentation
compareValues()
int ClassSDict::compareValues (const ClassDef * item1, const ClassDef * item2) const private virtual
Function that is used to compare two items when sorting. Overload this to properly sort items.
See also
inSort()
Reimplemented from SDict< ClassDef >.
Definition at line 55 of file classlist.cpp.
References compItems().
declVisible()
bool ClassSDict::declVisible (const ClassDef::CompoundType * filter = 0) const
Definition at line 65 of file classlist.cpp.
References ClassDef::compoundType(), Config_getBool, SDict< ClassDef >::count(), ClassDef::isLinkable(), ClassDef::isLocal(), SDict< ClassDef >::Iterator, and Definition::name().
Referenced by NamespaceDef::writeSummaryLinks(), GroupDef::writeSummaryLinks(), FileDef::writeSummaryLinks(), and ClassDef::writeSummaryLinks().
writeDeclaration()
void ClassSDict::writeDeclaration (OutputList & ol, const ClassDef::CompoundType * filter = 0, const char * header = 0, bool localNames = FALSE)
Definition at line 94 of file classlist.cpp.
References ClassDef::compoundType(), Config_getBool, SDict< ClassDef >::count(), OutputList::endMemberList(), ClassDef::isExtension(), SDict< ClassDef >::Iterator, Definition::name(), Private, ClassDef::protection(), and ClassDef::writeDeclarationLink().
Referenced by NamespaceDef::writeClassDeclarations(), FileDef::writeClassDeclarations(), GroupDef::writeClasses(), and ClassDef::writeNestedClasses().
writeDocumentation()
void ClassSDict::writeDocumentation (OutputList & ol, Definition * container = 0)
Definition at line 119 of file classlist.cpp.
References Config_getBool, SDict< ClassDef >::count(), OutputList::endGroupHeader(), ClassDef::isEmbeddedInOuterScope(), ClassDef::isLinkableInProject(), SDict< ClassDef >::Iterator, Definition::name(), OutputList::parseText(), Definition::partOfGroups(), OutputList::startGroupHeader(), theTranslator, Translator::trClassDocumentation(), Translator::trTypeDocumentation(), ClassDef::writeInlineDocumentation(), and OutputList::writeRuler().
Referenced by NamespaceDef::writeInlineClasses(), GroupDef::writeInlineClasses(), FileDef::writeInlineClasses(), and ClassDef::writeInlineClasses().
The documentation for this class was generated from the following files:
src/classlist.h
src/classlist.cpp