Doxygen: FlowChart Class Reference
FlowChart Class Reference
#include <vhdldocgen.h>
Public Types
enum nodeTypes {
IF_NO = 1<<1, ELSIF_NO = 1<<2, ELSE_NO = 1<<3, CASE_NO = 1<<4,
WHEN_NO = 1<<5, EXIT_NO = 1<<6, END_NO = 1<<7, TEXT_NO = 1<<8,
START_NO = 1<<9, ENDIF_NO = 1<<10, FOR_NO = 1<<11, WHILE_NO = 1<<12,
END_LOOP = 1<<13, END_CASE = 1<<14, VARIABLE_NO = 1<<15, RETURN_NO = 1<<16,
LOOP_NO = 1<<17, NEXT_NO = 1<<18, EMPTY_NO = 1<<19, COMMENT_NO = 1<<20,
BEGIN_NO = 1<<21
}
Public Member Functions
FlowChart (int typ, const char *t, const char *ex, const char *label=0)
~FlowChart ()
Static Public Member Functions
static void createSVG ()
static void startDot (FTextStream &t)
static void endDot (FTextStream &t)
static void codify (FTextStream &t, const char *str)
static void writeShape (FTextStream &t, const FlowChart *fl)
static void writeEdge (FTextStream &t, int fl_from, int fl_to, int i, bool bFrom=FALSE, bool bTo=FALSE)
static void writeEdge (FTextStream &t, const FlowChart *fl_from, const FlowChart *fl_to, int i)
static void writeFlowLinks (FTextStream &t)
static QCString getNodeName (int n)
static void colTextNodes ()
static int getNextTextLink (const FlowChart *fl, uint index)
static int getNextIfLink (const FlowChart *, uint)
static int getNextNode (int, int)
static int findNode (int index, int stamp, int type)
static int findNode (int index, int type)
static int findNextLoop (int j, int stamp)
static int findPrevLoop (int j, int stamp, bool endif=FALSE)
static int findLabel (int j, QCString &)
static void delFlowList ()
static const char * getNodeType (int c)
static void addFlowChart (int type, const char *text, const char *exp, const char *label=0)
static void moveToPrevLevel ()
static int getTimeStamp ()
static void writeFlowChart ()
static void alignFuncProc (QCString &q, const ArgumentList *al, bool isFunc)
static QCString convertNameToFileName ()
static void printNode (const FlowChart *n)
static void printFlowTree ()
static void buildCommentNodes (FTextStream &t)
static void alignCommentNode (FTextStream &t, QCString com)
static void printUmlTree ()
static QCString printPlantUmlNode (const FlowChart *flo, bool, bool)
Static Public Attributes
static QList< FlowChart > flowList
Private Attributes
int id
int stamp
int type
int line
QCString label
QCString text
QCString exp
Detailed Description
Definition at line 267 of file vhdldocgen.h.
Member Enumeration Documentation
nodeTypes
enum FlowChart::nodeTypes
Enumerator
IF_NO
ELSIF_NO
ELSE_NO
CASE_NO
WHEN_NO
EXIT_NO
END_NO
TEXT_NO
START_NO
ENDIF_NO
FOR_NO
WHILE_NO
END_LOOP
END_CASE
VARIABLE_NO
RETURN_NO
LOOP_NO
NEXT_NO
EMPTY_NO
COMMENT_NO
BEGIN_NO
Definition at line 270 of file vhdldocgen.h.
Constructor & Destructor Documentation
FlowChart()
FlowChart::FlowChart (int typ, const char * t, const char * ex, const char * label = 0)
Definition at line 3787 of file vhdldocgen.cpp.
References ELSE_NO, ELSIF_NO, END_NO, exp, ifcounter, label, nodeCounter, stamp, START_NO, STARTL, text, type, and VARIABLE_NO.
Referenced by addFlowChart(), and colTextNodes().
~FlowChart()
FlowChart::~FlowChart ()
Definition at line 3783 of file vhdldocgen.cpp.
Member Function Documentation
addFlowChart()
void FlowChart::addFlowChart (int type, const char * text, const char * exp, const char * label = 0) static
Definition at line 3814 of file vhdldocgen.cpp.
References FlowChart(), flowList, VhdlDocGen::getFlowMember(), vhdl::parser::VhdlParser::getLine(), label, line, START_NO, MemberDef::typeString(), and VARIABLE_NO.
Referenced by vhdl::parser::VhdlParser::createFlow(), and vhdl::parser::VhdlParser::handleFlowComment().
alignCommentNode()
void FlowChart::alignCommentNode (FTextStream & t, QCString com) static
Definition at line 3642 of file vhdldocgen.cpp.
References codify(), and split().
Referenced by buildCommentNodes(), and writeShape().
alignFuncProc()
void FlowChart::alignFuncProc (QCString & q, const ArgumentList * al, bool isFunc) static
Definition at line 4219 of file vhdldocgen.cpp.
References Argument::attrib, Argument::defval, VhdlDocGen::getFlowMember(), Argument::name, Definition::name(), and Argument::type.
Referenced by vhdl::parser::VhdlParser::createFlow().
buildCommentNodes()
void FlowChart::buildCommentNodes (FTextStream & t) static
Definition at line 3678 of file vhdldocgen.cpp.
References alignCommentNode(), BEGIN_NO, COMMENT_NO, flowCol, FLOWLEN, flowList, getNodeName(), id, label, line, type, and writeEdge().
Referenced by writeFlowChart().
codify()
void FlowChart::codify (FTextStream & t, const char * str) static
Definition at line 3760 of file vhdldocgen.cpp.
Referenced by alignCommentNode().
colTextNodes()
void FlowChart::colTextNodes () static
Definition at line 3574 of file vhdldocgen.cpp.
References ELSE_NO, EMPTY, FlowChart(), flowList, IFF, stamp, text, TEXT_NO, and type.
Referenced by writeFlowChart().
convertNameToFileName()
QCString FlowChart::convertNameToFileName () static
Definition at line 3937 of file vhdldocgen.cpp.
References exp, VhdlDocGen::getFlowMember(), and Definition::name().
Referenced by createSVG(), printUmlTree(), and HtmlDocVisitor::visitPre().
createSVG()
void FlowChart::createSVG () static
Definition at line 3987 of file vhdldocgen.cpp.
References Config_getString, convertNameToFileName(), err(), and portable_system().
Referenced by writeFlowChart().
delFlowList()
void FlowChart::delFlowList () static
Definition at line 3628 of file vhdldocgen.cpp.
References flowList, ifcounter, and nodeCounter.
Referenced by writeFlowChart().
endDot()
void FlowChart::endDot (FTextStream & t) static
Definition at line 4017 of file vhdldocgen.cpp.
Referenced by writeFlowChart().
findLabel()
int FlowChart::findLabel (int j, QCString & label) static
Definition at line 4296 of file vhdldocgen.cpp.
References err(), flowList, label, LOOP, and type.
Referenced by writeFlowLinks().
findNextLoop()
int FlowChart::findNextLoop (int j, int stamp) static
Definition at line 4256 of file vhdldocgen.cpp.
References END_LOOP, flowList, stamp, and type.
Referenced by writeFlowLinks().
findNode() [1/2]
int FlowChart::findNode (int index, int stamp, int type) static
Definition at line 4310 of file vhdldocgen.cpp.
References flowList, stamp, and type.
Referenced by getNextIfLink(), getNextNode(), and writeFlowLinks().
findNode() [2/2]
static int FlowChart::findNode (int index, int type) static
findPrevLoop()
int FlowChart::findPrevLoop (int j, int stamp, bool endif = FALSE) static
Definition at line 4273 of file vhdldocgen.cpp.
References flowList, LOOP, stamp, and type.
Referenced by writeFlowLinks().
getNextIfLink()
int FlowChart::getNextIfLink (const FlowChart * fl, uint index) static
Definition at line 4364 of file vhdldocgen.cpp.
References ELSE_NO, ELSIF_NO, ENDIF_NO, findNode(), flowList, getNextNode(), and stamp.
Referenced by writeFlowLinks().
getNextNode()
int FlowChart::getNextNode (int index, int stamp) static
Definition at line 4323 of file vhdldocgen.cpp.
References ELSE_NO, ELSIF_NO, END_CASE, ENDIF_NO, findNode(), FLOWLEN, flowList, stamp, type, and WHEN_NO.
Referenced by getNextIfLink(), and writeFlowLinks().
getNextTextLink()
static int FlowChart::getNextTextLink (const FlowChart * fl, uint index) static
getNodeName()
QCString FlowChart::getNodeName (int n) static
Definition at line 3621 of file vhdldocgen.cpp.
Referenced by buildCommentNodes(), writeEdge(), and writeShape().
getNodeType()
const char * FlowChart::getNodeType (int c) static
Definition at line 3958 of file vhdldocgen.cpp.
References BEGIN_NO, CASE_NO, COMMENT_NO, ELSE_NO, ELSIF_NO, EMPTY_NO, END_CASE, END_LOOP, END_NO, ENDIF_NO, EXIT_NO, FOR_NO, IF_NO, LOOP_NO, NEXT_NO, RETURN_NO, START_NO, TEXT_NO, VARIABLE_NO, WHEN_NO, and WHILE_NO.
Referenced by printNode().
getTimeStamp()
static int FlowChart::getTimeStamp () static
moveToPrevLevel()
void FlowChart::moveToPrevLevel () static
Definition at line 3849 of file vhdldocgen.cpp.
References VhdlDocGen::getFlowMember(), and ifcounter.
printFlowTree()
void FlowChart::printFlowTree () static
Definition at line 3565 of file vhdldocgen.cpp.
References flowList, and printNode().
Referenced by writeFlowChart().
printNode()
void FlowChart::printNode (const FlowChart * n) static
Definition at line 3505 of file vhdldocgen.cpp.
References COMMENT_NO, EMPTNODE, exp, getNodeType(), id, label, stamp, STARTL, text, and type.
Referenced by printFlowTree().
printPlantUmlNode()
QCString FlowChart::printPlantUmlNode (const FlowChart * flo, bool ca, bool endL) static
Definition at line 3855 of file vhdldocgen.cpp.
References BEGIN_NO, CASE_NO, COMMENT_NO, ELSE_NO, ELSIF_NO, EMPTY_NO, END_CASE, END_LOOP, END_NO, ENDIF_NO, EXIT_NO, exp, FOR_NO, IF_NO, label, LOOP_NO, NEXT_NO, RETURN_NO, START_NO, text, TEXT_NO, type, VARIABLE_NO, WHEN_NO, and WHILE_NO.
Referenced by printUmlTree().
printUmlTree()
void FlowChart::printUmlTree () static
Definition at line 3894 of file vhdldocgen.cpp.
References CASE_NO, Config_getString, convertNameToFileName(), END_CASE, FLOWLEN, flowList, generatePlantUMLOutput(), printPlantUmlNode(), PUML_SVG, type, WHEN_NO, and writePlantUMLSource().
Referenced by writeFlowChart().
startDot()
void FlowChart::startDot (FTextStream & t) static
Definition at line 4009 of file vhdldocgen.cpp.
Referenced by writeFlowChart().
writeEdge() [1/2]
void FlowChart::writeEdge (FTextStream & t, int fl_from, int fl_to, int i, bool bFrom = FALSE, bool bTo = FALSE) static
Definition at line 4190 of file vhdldocgen.cpp.
References flowCol, getNodeName(), and label.
Referenced by buildCommentNodes(), writeEdge(), and writeFlowLinks().
writeEdge() [2/2]
void FlowChart::writeEdge (FTextStream & t, const FlowChart * fl_from, const FlowChart * fl_to, int i) static
Definition at line 4172 of file vhdldocgen.cpp.
References getNodeName(), id, STARTL, type, and writeEdge().
writeFlowChart()
void FlowChart::writeFlowChart () static
Definition at line 4022 of file vhdldocgen.cpp.
References buildCommentNodes(), colTextNodes(), Config_getString, createSVG(), delFlowList(), endDot(), err(), flowList, VhdlDocGen::getFlowMember(), MemberDef::isStatic(), printFlowTree(), printUmlTree(), startDot(), writeFlowLinks(), and writeShape().
Referenced by vhdl::parser::VhdlParser::createFlow().
writeFlowLinks()
void FlowChart::writeFlowLinks (FTextStream & t) static
Definition at line 4388 of file vhdldocgen.cpp.
References CASE_NO, EEND, END_CASE, END_LOOP, EXIT_NO, exp, findLabel(), findNextLoop(), findNode(), findPrevLoop(), flowList, FOR_NO, getNextIfLink(), getNextNode(), IFF, label, LOOP_NO, NEXT_NO, RETURN_NO, stamp, text, TEXT_NO, type, VARIABLE_NO, WHEN_NO, WHILE_NO, and writeEdge().
Referenced by writeFlowChart().
writeShape()
void FlowChart::writeShape (FTextStream & t, const FlowChart * fl) static
Definition at line 4070 of file vhdldocgen.cpp.
References alignCommentNode(), alignText(), DECLN, EEND, ENDCL, EXITNEXT, exp, flowCol, getNodeName(), id, IFF, label, LOOP, STARTFIN, text, type, and VARIABLE_NO.
Referenced by writeFlowChart().
Member Data Documentation
exp
QCString FlowChart::exp private
Definition at line 346 of file vhdldocgen.h.
Referenced by convertNameToFileName(), FlowChart(), printNode(), printPlantUmlNode(), writeFlowLinks(), and writeShape().
flowList
QList< FlowChart > FlowChart::flowList static
Definition at line 332 of file vhdldocgen.h.
Referenced by addFlowChart(), buildCommentNodes(), colTextNodes(), delFlowList(), findLabel(), findNextLoop(), findNode(), findPrevLoop(), getNextIfLink(), getNextNode(), printFlowTree(), printUmlTree(), writeFlowChart(), and writeFlowLinks().
id
int FlowChart::id private
Definition at line 338 of file vhdldocgen.h.
Referenced by buildCommentNodes(), printNode(), writeEdge(), and writeShape().
label
QCString FlowChart::label private
Definition at line 344 of file vhdldocgen.h.
Referenced by addFlowChart(), buildCommentNodes(), findLabel(), FlowChart(), printNode(), printPlantUmlNode(), writeEdge(), writeFlowLinks(), and writeShape().
line
int FlowChart::line private
Definition at line 342 of file vhdldocgen.h.
Referenced by addFlowChart(), and buildCommentNodes().
stamp
int FlowChart::stamp private
Definition at line 339 of file vhdldocgen.h.
Referenced by colTextNodes(), findNextLoop(), findNode(), findPrevLoop(), FlowChart(), getNextIfLink(), getNextNode(), printNode(), and writeFlowLinks().
text
QCString FlowChart::text private
Definition at line 345 of file vhdldocgen.h.
Referenced by colTextNodes(), FlowChart(), printNode(), printPlantUmlNode(), writeFlowLinks(), and writeShape().
type
int FlowChart::type private
Definition at line 340 of file vhdldocgen.h.
Referenced by buildCommentNodes(), colTextNodes(), findLabel(), findNextLoop(), findNode(), findPrevLoop(), FlowChart(), getNextNode(), printNode(), printPlantUmlNode(), printUmlTree(), writeEdge(), writeFlowLinks(), and writeShape().
The documentation for this class was generated from the following files:
src/vhdldocgen.h
src/vhdldocgen.cpp