Doxygen: TemplateNodeInclude Class Reference
TemplateNodeInclude Class Reference
Class representing an 'include' tag in a template.
Public Member Functions
TemplateNodeInclude (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeInclude ()
void render (FTextStream &ts, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeInclude >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Private Attributes
ExprAst * m_includeExpr
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeInclude >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeInclude >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeInclude >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'include' tag in a template.
Definition at line 3542 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeInclude()
TemplateNodeInclude::TemplateNodeInclude (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 3545 of file template.cpp.
References m_includeExpr, TemplateNodeCreator< TemplateNodeInclude >::m_templateName, ExpressionParser::parse(), TRACE, and TemplateParser::warn().
~TemplateNodeInclude()
TemplateNodeInclude::~TemplateNodeInclude () inline
Definition at line 3556 of file template.cpp.
References m_includeExpr.
Member Function Documentation
render()
void TemplateNodeInclude::render (FTextStream & ts, TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 3560 of file template.cpp.
References TemplateImpl::engine(), TemplateNodeCreator< TemplateNodeInclude >::getTemplate(), TemplateEngine::loadByName(), m_includeExpr, TemplateNodeCreator< TemplateNodeInclude >::m_line, TemplateNodeCreator< TemplateNodeInclude >::m_templateName, TemplateImpl::render(), ExprAst::resolve(), TemplateContextImpl::setLocation(), TemplateVariant::toString(), TemplateEngine::unload(), and TemplateContextImpl::warn().
Member Data Documentation
m_includeExpr
ExprAst* TemplateNodeInclude::m_includeExpr private
Definition at line 3594 of file template.cpp.
Referenced by render(), TemplateNodeInclude(), and ~TemplateNodeInclude().
The documentation for this class was generated from the following file:
src/template.cpp