Doxygen: SearchIndexList Class Reference
SearchIndexList Class Reference
#include <searchindex.h>
Public Types
typedef Definition ElementType
Public Member Functions
SearchIndexList (uint letter)
~SearchIndexList ()
void append (Definition *d)
uint letter () const
Public Member Functions inherited from SDict< SearchDefinitionList >
SDict (int size=17, bool caseSensitive=TRUE)
virtual ~SDict ()
void append (const char *key, const SearchDefinitionList *d)
void prepend (const char *key, const SearchDefinitionList *d)
bool remove (const char *key)
SearchDefinitionList * take (const char *key)
void sort ()
void inSort (const char *key, const SearchDefinitionList *d)
void insertAt (int i, const char *key, const SearchDefinitionList *d)
void setAutoDelete (bool val)
SearchDefinitionList * find (const char *key)
SearchDefinitionList * find (const QCString &key)
SearchDefinitionList * find (const QString &key)
int findAt (const QCString &key)
SearchDefinitionList * operator[] (const char *key) const
SearchDefinitionList * at (uint i)
void clear ()
int count () const
Private Member Functions
int compareValues (const SearchDefinitionList *md1, const SearchDefinitionList *md2) const
Private Attributes
uint m_letter
Detailed Description
Definition at line 143 of file searchindex.h.
Member Typedef Documentation
ElementType
typedef Definition SearchIndexList::ElementType
Definition at line 146 of file searchindex.h.
Constructor & Destructor Documentation
SearchIndexList()
SearchIndexList::SearchIndexList (uint letter)
Definition at line 1258 of file searchindex.cpp.
References SDict< SearchDefinitionList >::setAutoDelete().
~SearchIndexList()
SearchIndexList::~SearchIndexList ()
Definition at line 1264 of file searchindex.cpp.
Member Function Documentation
append()
void SearchIndexList::append (Definition * d)
Definition at line 1268 of file searchindex.cpp.
References SDict< T >::append(), DefinitionIntf::definitionType(), SDict< SearchDefinitionList >::find(), Definition::localName(), searchId(), DefinitionIntf::TypeGroup, and DefinitionIntf::TypePage.
compareValues()
int SearchIndexList::compareValues (const SearchDefinitionList * item1, const SearchDefinitionList * item2) const private virtual
Function that is used to compare two items when sorting. Overload this to properly sort items.
See also
inSort()
Reimplemented from SDict< SearchDefinitionList >.
Definition at line 1293 of file searchindex.cpp.
letter()
uint SearchIndexList::letter () const
Definition at line 1288 of file searchindex.cpp.
References m_letter.
Referenced by SymbolIndexContext::Private::letter(), and writeJavascriptSearchIndex().
Member Data Documentation
m_letter
uint SearchIndexList::m_letter private
Definition at line 153 of file searchindex.h.
Referenced by letter().
The documentation for this class was generated from the following files:
src/searchindex.h
src/searchindex.cpp