Doxygen: InheritedMemberInfoListContext::Private Class Reference
InheritedMemberInfoListContext::Private Class Reference
Public Member Functions
void addMemberList (ClassDef *inheritedFrom, MemberList *ml, MemberList *combinedList)
void addMemberListIncludingGrouped (ClassDef *inheritedFrom, MemberList *ml, MemberList *combinedList)
void addMemberGroupsOfClass (ClassDef *inheritedFrom, ClassDef *cd, MemberListType lt, MemberList *combinedList)
void addInheritedMembers (ClassDef *inheritedFrom, ClassDef *cd, MemberListType lt, MemberListType lt1, int lt2, const QCString &title, bool additionalList)
void findInheritedMembers (ClassDef *inheritedFrom, ClassDef *cd, MemberListType lt, int lt2, const QCString &title, bool additionalList, QPtrDict< void > *visitedClasses)
Public Member Functions inherited from GenericNodeListContext
GenericNodeListContext ()
int count () const
Returns the number of elements in the list.
TemplateVariant at (int index) const
Returns the element at index position index.
TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
void append (const TemplateVariant &ctn)
bool isEmpty () const
int addRef ()
Increase object's reference count.
int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Additional Inherited Members
Static Public Member Functions inherited from GenericNodeListContext
static GenericNodeListContext * alloc ()
Detailed Description
Definition at line 9119 of file context.cpp.
Member Function Documentation
addInheritedMembers()
void InheritedMemberInfoListContext::Private::addInheritedMembers (ClassDef * inheritedFrom, ClassDef * cd, MemberListType lt, MemberListType lt1, int lt2, const QCString & title, bool additionalList) inline
Definition at line 9179 of file context.cpp.
References addMemberGroupsOfClass(), addMemberListIncludingGrouped(), InheritedMemberInfoContext::alloc(), GenericNodeListContext::append(), GenericNodeListContext::count(), ClassDef::countMembersIncludingGrouped(), and ClassDef::getMemberList().
Referenced by findInheritedMembers().
addMemberGroupsOfClass()
void InheritedMemberInfoListContext::Private::addMemberGroupsOfClass (ClassDef * inheritedFrom, ClassDef * cd, MemberListType lt, MemberList * combinedList) inline
Definition at line 9153 of file context.cpp.
References MemberList::append(), ClassDef::getMemberGroupSDict(), SIntDict< MemberGroup >::Iterator, and ClassDef::subGrouping().
Referenced by addInheritedMembers().
addMemberList()
void InheritedMemberInfoListContext::Private::addMemberList (ClassDef * inheritedFrom, MemberList * ml, MemberList * combinedList) inline
Definition at line 9122 of file context.cpp.
References MemberList::append(), MemberDef::isBriefSectionVisible(), and MemberDef::isReimplementedBy().
Referenced by addMemberListIncludingGrouped().
addMemberListIncludingGrouped()
void InheritedMemberInfoListContext::Private::addMemberListIncludingGrouped (ClassDef * inheritedFrom, MemberList * ml, MemberList * combinedList) inline
Definition at line 9137 of file context.cpp.
References addMemberList(), and MemberList::getMemberGroupList().
Referenced by addInheritedMembers().
findInheritedMembers()
void InheritedMemberInfoListContext::Private::findInheritedMembers (ClassDef * inheritedFrom, ClassDef * cd, MemberListType lt, int lt2, const QCString & title, bool additionalList, QPtrDict< void > * visitedClasses) inline
Definition at line 9196 of file context.cpp.
References addInheritedMembers(), ClassDef::baseClasses(), convertProtectionLevel(), and ClassDef::isLinkable().
Referenced by InheritedMemberInfoListContext::addMemberList().
The documentation for this class was generated from the following file:
src/context.cpp