Doxygen: DotClassGraph Class Reference
DotClassGraph Class Reference
Representation of a class inheritance or dependency graph.
#include <dot.h>
Public Member Functions
DotClassGraph (ClassDef *cd, DotNode::GraphType t)
~DotClassGraph ()
bool isTrivial () const
bool isTooBig () const
QCString writeGraph (FTextStream &t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const char *path, const char *fileName, const char *relPath, bool TBRank=TRUE, bool imageMap=TRUE, int graphId=-1) const
void writeXML (FTextStream &t)
void writeDocbook (FTextStream &t)
void writeDEF (FTextStream &t)
Static Public Member Functions
static void resetNumbering ()
Private Member Functions
void buildGraph (ClassDef *cd, DotNode *n, bool base, int distance)
bool determineVisibleNodes (DotNode *rootNode, int maxNodes, bool includeParents)
void determineTruncatedNodes (QList< DotNode > &queue, bool includeParents)
void addClass (ClassDef *cd, DotNode *n, int prot, const char *label, const char *usedName, const char *templSpec, bool base, int distance)
Private Attributes
DotNode * m_startNode
QDict< DotNode > * m_usedNodes
DotNode::GraphType m_graphType
QCString m_collabFileName
QCString m_inheritFileName
bool m_lrRank
Static Private Attributes
static int m_curNodeNumber = 0
Detailed Description
Representation of a class inheritance or dependency graph.
Definition at line 169 of file dot.h.
Constructor & Destructor Documentation
DotClassGraph()
DotClassGraph::DotClassGraph (ClassDef * cd, DotNode::GraphType t)
Definition at line 2910 of file dot.cpp.
References ClassDef::anchor(), Definition::briefDescriptionAsTooltip(), buildGraph(), ClassDef::collaborationGraphFileName(), Config_getInt, determineTruncatedNodes(), determineVisibleNodes(), ClassDef::displayName(), ClassDef::getOutputFileBase(), ClassDef::getReference(), DotNode::Inheritance, ClassDef::inheritanceGraphFileName(), Definition::isHidden(), ClassDef::isLinkable(), m_collabFileName, m_curNodeNumber, m_graphType, m_inheritFileName, m_lrRank, m_startNode, m_usedNodes, and DotNode::setDistance().
~DotClassGraph()
DotClassGraph::~DotClassGraph ()
Definition at line 2981 of file dot.cpp.
References deleteNodes(), m_startNode, and m_usedNodes.
Member Function Documentation
addClass()
void DotClassGraph::addClass (ClassDef * cd, DotNode * n, int prot, const char * label, const char * usedName, const char * templSpec, bool base, int distance) private
Definition at line 2554 of file dot.cpp.
References DotNode::addChild(), DotNode::addParent(), ClassDef::anchor(), Definition::briefDescriptionAsTooltip(), buildGraph(), Config_getBool, EdgeInfo::Dashed, ClassDef::displayName(), ClassDef::getOutputFileBase(), ClassDef::getReference(), insertTemplateSpecifierInScope(), ClassDef::isAnonymous(), Definition::isHidden(), ClassDef::isLinkable(), m_curNodeNumber, m_usedNodes, Definition::name(), EdgeInfo::Orange, EdgeInfo::Orange2, DotNode::setDistance(), EdgeInfo::Solid, and stripScope().
Referenced by buildGraph().
buildGraph()
void DotClassGraph::buildGraph (ClassDef * cd, DotNode * n, bool base, int distance) private
Definition at line 2768 of file dot.cpp.
References UsesClassDef::accessors, ConstraintClassDef::accessors, addClass(), ClassDef::baseClasses(), UsesClassDef::classDef, BaseClassDef::classDef, ConstraintClassDef::classDef, DotNode::Collaboration, Config_getBool, ClassDef::getTemplateInstances(), DotNode::Inheritance, m_graphType, EdgeInfo::Orange, EdgeInfo::Orange2, BaseClassDef::prot, EdgeInfo::Purple, ClassDef::subClasses(), ClassDef::templateMaster(), ClassDef::templateTypeConstraints(), UsesClassDef::templSpecifiers, BaseClassDef::templSpecifiers, ClassDef::usedByImplementationClasses(), ClassDef::usedImplementationClasses(), and BaseClassDef::usedName.
Referenced by addClass(), and DotClassGraph().
determineTruncatedNodes()
void DotClassGraph::determineTruncatedNodes (QList< DotNode > & queue, bool includeParents) private
Definition at line 2636 of file dot.cpp.
References DotNode::isTruncated(), DotNode::isVisible(), DotNode::m_children, DotNode::m_parents, DotNode::markAsTruncated(), and DotNode::Unknown.
Referenced by DotClassGraph().
determineVisibleNodes()
bool DotClassGraph::determineVisibleNodes (DotNode * rootNode, int maxNodes, bool includeParents) private
Definition at line 2673 of file dot.cpp.
References Config_getBool, Config_getInt, DotNode::distance(), DotNode::isVisible(), DotNode::label(), DotNode::m_children, DotNode::m_parents, and DotNode::markAsVisible().
Referenced by DotClassGraph().
isTooBig()
bool DotClassGraph::isTooBig () const
Definition at line 2969 of file dot.cpp.
References Config_getInt, DotNode::Inheritance, DotNode::m_children, m_graphType, DotNode::m_parents, and m_startNode.
Referenced by ClassContext::Private::hasInheritanceDiagram(), and ClassDef::writeInheritanceGraph().
isTrivial()
bool DotClassGraph::isTrivial () const
Definition at line 2960 of file dot.cpp.
References Config_getBool, DotNode::Inheritance, DotNode::m_children, m_graphType, DotNode::m_parents, and m_startNode.
Referenced by generateDEFForClass(), PerlModGenerator::generatePerlModForClass(), generateXMLForClass(), ClassContext::Private::hasCollaborationDiagram(), ClassContext::Private::hasInheritanceDiagram(), ClassDef::writeCollaborationGraph(), and ClassDef::writeInheritanceGraph().
resetNumbering()
void DotClassGraph::resetNumbering () static
Definition at line 2905 of file dot.cpp.
References m_curNodeNumber.
Referenced by resetDotNodeNumbering().
writeDEF()
void DotClassGraph::writeDEF (FTextStream & t)
Definition at line 3270 of file dot.cpp.
References m_usedNodes, and DotNode::writeDEF().
Referenced by generateDEFForClass().
writeDocbook()
void DotClassGraph::writeDocbook (FTextStream & t)
Definition at line 3260 of file dot.cpp.
References m_usedNodes, and DotNode::writeDocbook().
writeGraph()
QCString DotClassGraph::writeGraph (FTextStream & t, GraphOutputFormat gf, EmbeddedOutputFormat ef, const char * path, const char * fileName, const char * relPath, bool TBRank = TRUE, bool imageMap = TRUE, int graphId = -1) const
Definition at line 3075 of file dot.cpp.
References DotManager::addFigure(), IndexList::addImageFile(), DotRunner::addJob(), DotManager::addMap(), DotManager::addRun(), DotManager::addSVGConversion(), DotManager::addSVGObject(), checkDeliverables(), DotNode::Collaboration, Config_getBool, Config_getEnum, endl(), EOF_DocBook, err(), escapeCharsInString(), getDotImageExtension(), GOF_BITMAP, GOF_EPS, Doxygen::indexList, DotNode::Inheritance, insertMapFile(), DotManager::instance(), DotNode::label(), m_collabFileName, m_graphType, m_inheritFileName, DotNode::m_label, m_lrRank, m_startNode, MAP_CMD, removeDotGraph(), updateDotGraph(), writeSVGFigureLink(), and writeVecGfxFigure().
Referenced by ClassContext::Private::collaborationDiagram(), RTFGenerator::endDotGraph(), LatexGenerator::endDotGraph(), HtmlGenerator::endDotGraph(), and ClassContext::Private::inheritanceDiagram().
writeXML()
void DotClassGraph::writeXML (FTextStream & t)
Definition at line 3250 of file dot.cpp.
References m_usedNodes, and DotNode::writeXML().
Referenced by generateXMLForClass().
Member Data Documentation
m_collabFileName
QCString DotClassGraph::m_collabFileName private
Definition at line 197 of file dot.h.
Referenced by DotClassGraph(), and writeGraph().
m_curNodeNumber
int DotClassGraph::m_curNodeNumber = 0 static private
Definition at line 195 of file dot.h.
Referenced by addClass(), DotClassGraph(), and resetNumbering().
m_graphType
DotNode::GraphType DotClassGraph::m_graphType private
Definition at line 196 of file dot.h.
Referenced by buildGraph(), DotClassGraph(), isTooBig(), isTrivial(), and writeGraph().
m_inheritFileName
QCString DotClassGraph::m_inheritFileName private
Definition at line 198 of file dot.h.
Referenced by DotClassGraph(), and writeGraph().
m_lrRank
bool DotClassGraph::m_lrRank private
Definition at line 199 of file dot.h.
Referenced by DotClassGraph(), and writeGraph().
m_startNode
DotNode* DotClassGraph::m_startNode private
Definition at line 193 of file dot.h.
Referenced by DotClassGraph(), isTooBig(), isTrivial(), writeGraph(), and ~DotClassGraph().
m_usedNodes
QDict<DotNode>* DotClassGraph::m_usedNodes private
Definition at line 194 of file dot.h.
Referenced by addClass(), DotClassGraph(), writeDEF(), writeDocbook(), writeXML(), and ~DotClassGraph().
The documentation for this class was generated from the following files:
src/dot.h
src/dot.cpp