Doxygen: src/vhdljjparser.h File Reference
vhdljjparser.h File Reference
#include "parserintf.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <ctype.h>
#include <qarray.h>
#include <qfile.h>
#include <qdict.h>
#include <string>
#include "types.h"
#include "entry.h"
#include "vhdldocgen.h"
#include "qstringlist.h"
#include "vhdlcode.h"
#include "memberlist.h"
#include "config.h"
Classes
class VHDLLanguageScanner
VHDL parser using state-based lexical scanning.
struct VhdlConfNode
Enumerations
enum { GEN_SEC =0x1, PARAM_SEC, CONTEXT_SEC, PROTECTED_SEC }
Functions
void parserVhdlfile (const char *inputBuffer)
void vhdlscanFreeScanner ()
QList< VhdlConfNode > & getVhdlConfiguration ()
QList< Entry > & getVhdlInstList ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GEN_SEC
PARAM_SEC
CONTEXT_SEC
PROTECTED_SEC
Definition at line 25 of file vhdljjparser.h.
Function Documentation
getVhdlConfiguration()
QList<VhdlConfNode>& getVhdlConfiguration ()
Definition at line 92 of file vhdljjparser.cpp.
References configL.
Referenced by assignBinding(), and VhdlDocGen::computeVhdlComponentRelations().
getVhdlInstList()
QList<Entry>& getVhdlInstList ()
Definition at line 93 of file vhdljjparser.cpp.
References instFiles.
Referenced by assignBinding(), and VhdlDocGen::computeVhdlComponentRelations().
parserVhdlfile()
void parserVhdlfile (const char * inputBuffer)
vhdlscanFreeScanner()
void vhdlscanFreeScanner ()