Doxygen: TemplateNodeSet Class Reference
TemplateNodeSet Class Reference
Class representing an 'set' tag in a template.
Classes
struct Mapping
Public Member Functions
TemplateNodeSet (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
~TemplateNodeSet ()
void render (FTextStream &, TemplateContext *c)
Public Member Functions inherited from TemplateNodeCreator< TemplateNodeSet >
TemplateNodeCreator (TemplateParser *parser, TemplateNode *parent, int line)
TemplateImpl * getTemplate ()
Public Member Functions inherited from TemplateNode
TemplateNode (TemplateNode *parent)
virtual ~TemplateNode ()
TemplateNode * parent ()
Private Attributes
Mapping * m_mapping
Additional Inherited Members
Static Public Member Functions inherited from TemplateNodeCreator< TemplateNodeSet >
static TemplateNode * createInstance (TemplateParser *parser, TemplateNode *parent, int line, const QCString &data)
Protected Member Functions inherited from TemplateNodeCreator< TemplateNodeSet >
void mkpath (TemplateContextImpl *ci, const QCString &fileName)
Protected Attributes inherited from TemplateNodeCreator< TemplateNodeSet >
QCString m_templateName
int m_line
Detailed Description
Class representing an 'set' tag in a template.
Definition at line 4138 of file template.cpp.
Constructor & Destructor Documentation
TemplateNodeSet()
TemplateNodeSet::TemplateNodeSet (TemplateParser * parser, TemplateNode * parent, int line, const QCString & data) inline
Definition at line 4148 of file template.cpp.
References m_mapping, ExpressionParser::parse(), and TRACE.
~TemplateNodeSet()
TemplateNodeSet::~TemplateNodeSet () inline
Definition at line 4162 of file template.cpp.
References m_mapping.
Member Function Documentation
render()
void TemplateNodeSet::render (FTextStream & , TemplateContext * c) inline virtual
Implements TemplateNode.
Definition at line 4166 of file template.cpp.
References TemplateNodeCreator< TemplateNodeSet >::m_line, m_mapping, TemplateNodeCreator< TemplateNodeSet >::m_templateName, TemplateNodeSet::Mapping::name, ExprAst::resolve(), TemplateContextImpl::set(), TemplateContextImpl::setLocation(), and TemplateNodeSet::Mapping::value.
Member Data Documentation
m_mapping
Mapping* TemplateNodeSet::m_mapping private
Definition at line 4178 of file template.cpp.
Referenced by render(), TemplateNodeSet(), and ~TemplateNodeSet().
The documentation for this class was generated from the following file:
src/template.cpp