Doxygen: FileListContext Class Reference
FileListContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static FileListContext * alloc ()
Private Member Functions
FileListContext ()
~FileListContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 647 of file context.h.
Constructor & Destructor Documentation
FileListContext()
FileListContext::FileListContext () private
Definition at line 7038 of file context.cpp.
References FileListContext::Private::addFiles(), Doxygen::inputNameList, p, and Private.
Referenced by alloc().
~FileListContext()
FileListContext::~FileListContext () private
Definition at line 7044 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int FileListContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 656 of file context.h.
References RefCountedContext::addRef().
alloc()
static FileListContext* FileListContext::alloc () inline static
Definition at line 650 of file context.h.
References FileListContext().
Referenced by generateOutputViaTemplate().
at()
TemplateVariant FileListContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 7055 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int FileListContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 7050 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * FileListContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 7060 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int FileListContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 657 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* FileListContext::p private
Definition at line 662 of file context.h.
Referenced by at(), count(), createIterator(), FileListContext(), and ~FileListContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp