Doxygen: EclipseHelp Class Reference
EclipseHelp Class Reference
Generator for Eclipse help files.
#include <eclipsehelp.h>
Public Member Functions
EclipseHelp ()
virtual ~EclipseHelp ()
virtual void initialize ()
Initialize the Eclipse generator.
virtual void finalize ()
Finish generation of the Eclipse specific help files.
virtual void incContentsDepth ()
Increase the level of content hierarchy.
virtual void decContentsDepth ()
Decrease the level of content hierarchy.
virtual void addContentsItem (bool isDir, const char *name, const char *ref, const char *file, const char *anchor, bool separateIndex, bool addToNavIndex, Definition *def)
Add an item to the content.
virtual void addIndexItem (Definition *context, MemberDef *md, const char *sectionAnchor, const char *title)
virtual void addIndexFile (const char *name)
virtual void addImageFile (const char *name)
virtual void addStyleSheetFile (const char *name)
Public Member Functions inherited from IndexIntf
virtual ~IndexIntf ()
Private Member Functions
EclipseHelp (const EclipseHelp &)
EclipseHelp & operator= (const EclipseHelp &)
void indent ()
void closedTag ()
void openedTag ()
Private Attributes
int m_depth
bool m_endtag
int m_openTags
QFile * m_tocfile
FTextStream m_tocstream
QCString m_pathprefix
Detailed Description
Generator for Eclipse help files.
This class generates the Eclipse specific help files. These files can be used to generate a help plugin readable by the Eclipse IDE.
Definition at line 40 of file eclipsehelp.h.
Constructor & Destructor Documentation
EclipseHelp() [1/2]
EclipseHelp::EclipseHelp ()
Definition at line 22 of file eclipsehelp.cpp.
~EclipseHelp()
EclipseHelp::~EclipseHelp () virtual
Definition at line 26 of file eclipsehelp.cpp.
EclipseHelp() [2/2]
EclipseHelp::EclipseHelp (const EclipseHelp &) private
Member Function Documentation
addContentsItem()
void EclipseHelp::addContentsItem (bool isDir, const char * name, const char * ref, const char * file, const char * anchor, bool separateIndex, bool addToNavIndex, Definition * def) virtual
Add an item to the content.
Parameters
isDir Flag whether the argument file is a directory or a file entry
name Name of the item
ref URL of the item
file Name of a file which the item is defined in (without extension)
anchor Name of an anchor of the item.
separateIndex not used.
addToNavIndex not used.
def not used.
Implements IndexIntf.
Definition at line 169 of file eclipsehelp.cpp.
References closedTag(), convertToXML(), Doxygen::htmlFileExtension, indent(), m_endtag, m_pathprefix, and m_tocstream.
addImageFile()
void EclipseHelp::addImageFile (const char * name) virtual
Implements IndexIntf.
Definition at line 230 of file eclipsehelp.cpp.
addIndexFile()
void EclipseHelp::addIndexFile (const char * name) virtual
Implements IndexIntf.
Definition at line 226 of file eclipsehelp.cpp.
addIndexItem()
void EclipseHelp::addIndexItem (Definition * context, MemberDef * md, const char * sectionAnchor, const char * title) virtual
Implements IndexIntf.
Definition at line 218 of file eclipsehelp.cpp.
addStyleSheetFile()
void EclipseHelp::addStyleSheetFile (const char * name) virtual
Implements IndexIntf.
Definition at line 234 of file eclipsehelp.cpp.
closedTag()
void EclipseHelp::closedTag () private
Definition at line 39 of file eclipsehelp.cpp.
References endl(), m_endtag, and m_tocstream.
Referenced by addContentsItem(), decContentsDepth(), and finalize().
decContentsDepth()
void EclipseHelp::decContentsDepth () virtual
Decrease the level of content hierarchy.
It closes currently opened topic tag.
Implements IndexIntf.
Definition at line 143 of file eclipsehelp.cpp.
References closedTag(), endl(), indent(), m_depth, m_openTags, and m_tocstream.
finalize()
void EclipseHelp::finalize () virtual
Finish generation of the Eclipse specific help files.
This method writes footers of the files and closes them.
See also
initialize()
Implements IndexIntf.
Definition at line 101 of file eclipsehelp.cpp.
References closedTag(), Config_getString, endl(), m_depth, m_tocfile, m_tocstream, and FTextStream::unsetDevice().
incContentsDepth()
void EclipseHelp::incContentsDepth () virtual
Increase the level of content hierarchy.
Implements IndexIntf.
Definition at line 132 of file eclipsehelp.cpp.
References m_depth, and openedTag().
indent()
void EclipseHelp::indent () private
Definition at line 30 of file eclipsehelp.cpp.
References m_depth, and m_tocstream.
Referenced by addContentsItem(), and decContentsDepth().
initialize()
void EclipseHelp::initialize () virtual
Initialize the Eclipse generator.
This method opens the XML TOC file and writes headers of the files.
See also
finalize()
Implements IndexIntf.
Definition at line 64 of file eclipsehelp.cpp.
References Config_getString, convertToXML(), endl(), err(), Doxygen::htmlFileExtension, m_depth, m_pathprefix, m_tocfile, m_tocstream, and FTextStream::setDevice().
openedTag()
void EclipseHelp::openedTag () private
Definition at line 48 of file eclipsehelp.cpp.
References endl(), m_endtag, m_openTags, and m_tocstream.
Referenced by incContentsDepth().
operator=()
EclipseHelp& EclipseHelp::operator= (const EclipseHelp &) private
Member Data Documentation
m_depth
int EclipseHelp::m_depth private
Definition at line 61 of file eclipsehelp.h.
Referenced by decContentsDepth(), finalize(), incContentsDepth(), indent(), and initialize().
m_endtag
bool EclipseHelp::m_endtag private
Definition at line 62 of file eclipsehelp.h.
Referenced by addContentsItem(), closedTag(), and openedTag().
m_openTags
int EclipseHelp::m_openTags private
Definition at line 63 of file eclipsehelp.h.
Referenced by decContentsDepth(), and openedTag().
m_pathprefix
QCString EclipseHelp::m_pathprefix private
Definition at line 67 of file eclipsehelp.h.
Referenced by addContentsItem(), and initialize().
m_tocfile
QFile* EclipseHelp::m_tocfile private
Definition at line 65 of file eclipsehelp.h.
Referenced by finalize(), and initialize().
m_tocstream
FTextStream EclipseHelp::m_tocstream private
Definition at line 66 of file eclipsehelp.h.
Referenced by addContentsItem(), closedTag(), decContentsDepth(), finalize(), indent(), initialize(), and openedTag().
The documentation for this class was generated from the following files:
src/eclipsehelp.h
src/eclipsehelp.cpp