Doxygen: InheritanceGraphContext::Private Class Reference
InheritanceGraphContext::Private Class Reference
Public Member Functions
Private (DotGfxHierarchyTable *hierarchy, DotNode *n, int id)
TemplateVariant get (const char *n) const
TemplateVariant graph () const
Private Attributes
DotGfxHierarchyTable * m_hierarchy
DotNode * m_node
int m_id
Static Private Attributes
static PropertyMapper< InheritanceGraphContext::Private > s_inst
Detailed Description
Definition at line 8314 of file context.cpp.
Constructor & Destructor Documentation
Private()
InheritanceGraphContext::Private::Private (DotGfxHierarchyTable * hierarchy, DotNode * n, int id) inline
Definition at line 8317 of file context.cpp.
References PropertyMapper< T >::addProperty(), graph(), Config::init(), and s_inst.
Member Function Documentation
get()
TemplateVariant InheritanceGraphContext::Private::get (const char * n) const inline
Definition at line 8326 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by InheritanceGraphContext::get().
graph()
TemplateVariant InheritanceGraphContext::Private::graph () const inline
Definition at line 8330 of file context.cpp.
References Config_getBool, DotGfxHierarchyTable::createGraph(), g_globals, Doxygen::htmlFileExtension, m_hierarchy, m_id, m_node, ContextGlobals::outputDir, and portable_pathSeparator().
Referenced by Private().
Member Data Documentation
m_hierarchy
DotGfxHierarchyTable* InheritanceGraphContext::Private::m_hierarchy private
Definition at line 8348 of file context.cpp.
Referenced by graph().
m_id
int InheritanceGraphContext::Private::m_id private
Definition at line 8350 of file context.cpp.
Referenced by graph().
m_node
DotNode* InheritanceGraphContext::Private::m_node private
Definition at line 8349 of file context.cpp.
Referenced by graph().
s_inst
PropertyMapper< InheritanceGraphContext::Private > InheritanceGraphContext::Private::s_inst static private
Definition at line 8351 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp