Doxygen: SearchIndex Class Reference
SearchIndex Class Reference
#include <searchindex.h>
Public Member Functions
SearchIndex ()
void setCurrentDoc (Definition *ctx, const char *anchor, bool isSourceFile)
void addWord (const char *word, bool hiPriority)
void write (const char *file)
Public Member Functions inherited from SearchIndexIntf
SearchIndexIntf (Kind k)
virtual ~SearchIndexIntf ()
Kind kind () const
Private Member Functions
void addWord (const char *word, bool hiPrio, bool recurse)
Private Attributes
QDict< IndexWord > m_words
QVector< QList< IndexWord > > m_index
QDict< int > m_url2IdMap
QIntDict< URL > m_urls
int m_urlIndex
Additional Inherited Members
Public Types inherited from SearchIndexIntf
enum Kind { Internal, External }
Detailed Description
Definition at line 83 of file searchindex.h.
Constructor & Destructor Documentation
SearchIndex()
SearchIndex::SearchIndex ()
Definition at line 78 of file searchindex.cpp.
References m_index, m_url2IdMap, m_urls, m_words, and numIndexEntries.
Member Function Documentation
addWord() [1/2]
void SearchIndex::addWord (const char * word, bool hiPriority) virtual
Implements SearchIndexIntf.
Definition at line 242 of file searchindex.cpp.
Referenced by addWord().
addWord() [2/2]
void SearchIndex::addWord (const char * word, bool hiPrio, bool recurse) private
Definition at line 205 of file searchindex.cpp.
References IndexWord::addUrlIndex(), addWord(), charsToIndex(), getPrefixIndex(), m_index, m_urlIndex, and m_words.
setCurrentDoc()
void SearchIndex::setCurrentDoc (Definition * ctx, const char * anchor, bool isSourceFile) virtual
Implements SearchIndexIntf.
Definition at line 89 of file searchindex.cpp.
References ClassDef::compoundTypeString(), Config_getString, DefinitionIntf::definitionType(), Definition::getLanguage(), getLanguageSpecificSeparator(), GroupDef::groupTitle(), m_url2IdMap, m_urlIndex, m_urls, Definition::name(), SrcLangExt_CSharp, SrcLangExt_Fortran, SrcLangExt_Java, substitute(), theTranslator, PageDef::title(), Translator::trGroup(), Translator::trMember(), Translator::trModule(), Translator::trNamespace(), Translator::trPackage(), Translator::trPage(), Translator::trSubprogram(), DefinitionIntf::TypeClass, DefinitionIntf::TypeFile, DefinitionIntf::TypeGroup, DefinitionIntf::TypeMember, DefinitionIntf::TypeNamespace, and DefinitionIntf::TypePage.
write()
void SearchIndex::write (const char * file) virtual
Implements SearchIndexIntf.
Definition at line 262 of file searchindex.cpp.
References m_index, m_urls, m_words, URL::name, numIndexEntries, URL::url, IndexWord::urls(), IndexWord::word(), writeInt(), and writeString().
Member Data Documentation
m_index
QVector< QList<IndexWord> > SearchIndex::m_index private
Definition at line 93 of file searchindex.h.
Referenced by addWord(), SearchIndex(), and write().
m_url2IdMap
QDict<int> SearchIndex::m_url2IdMap private
Definition at line 94 of file searchindex.h.
Referenced by SearchIndex(), and setCurrentDoc().
m_urlIndex
int SearchIndex::m_urlIndex private
Definition at line 96 of file searchindex.h.
Referenced by addWord(), and setCurrentDoc().
m_urls
QIntDict<URL> SearchIndex::m_urls private
Definition at line 95 of file searchindex.h.
Referenced by SearchIndex(), setCurrentDoc(), and write().
m_words
QDict<IndexWord> SearchIndex::m_words private
Definition at line 92 of file searchindex.h.
Referenced by addWord(), SearchIndex(), and write().
The documentation for this class was generated from the following files:
src/searchindex.h
src/searchindex.cpp