Doxygen: SearchIndicesContext Class Reference
SearchIndicesContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual int count () const
Returns the number of elements in the list.
virtual TemplateVariant at (int index) const
Returns the element at index position index.
virtual TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's referenc count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Static Public Member Functions
static SearchIndicesContext * alloc ()
Private Member Functions
SearchIndicesContext ()
~SearchIndicesContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 1328 of file context.h.
Constructor & Destructor Documentation
SearchIndicesContext()
SearchIndicesContext::SearchIndicesContext () private
Definition at line 9931 of file context.cpp.
References p, and Private.
Referenced by alloc().
~SearchIndicesContext()
SearchIndicesContext::~SearchIndicesContext () private
Definition at line 9936 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int SearchIndicesContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateListIntf.
Definition at line 1337 of file context.h.
References RefCountedContext::addRef().
alloc()
static SearchIndicesContext* SearchIndicesContext::alloc () inline static
Definition at line 1331 of file context.h.
References SearchIndicesContext().
Referenced by generateOutputViaTemplate().
at()
TemplateVariant SearchIndicesContext::at (int index) const virtual
Returns the element at index position index.
Implements TemplateListIntf.
Definition at line 9947 of file context.cpp.
References GenericNodeListContext::at(), and p.
count()
int SearchIndicesContext::count () const virtual
Returns the number of elements in the list.
Implements TemplateListIntf.
Definition at line 9942 of file context.cpp.
References GenericNodeListContext::count(), and p.
createIterator()
TemplateListIntf::ConstIterator * SearchIndicesContext::createIterator () const virtual
Creates a new iterator for this list.
Note
the user should call delete on the returned pointer.
Implements TemplateListIntf.
Definition at line 9952 of file context.cpp.
References GenericNodeListContext::createIterator(), and p.
release()
virtual int SearchIndicesContext::release () inline virtual
Decreases object's referenc count, destroy object if 0.
Implements TemplateListIntf.
Definition at line 1338 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* SearchIndicesContext::p private
Definition at line 1343 of file context.h.
Referenced by at(), count(), createIterator(), SearchIndicesContext(), and ~SearchIndicesContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp