Doxygen: FileList Class Reference
FileList Class Reference
Class representing a list of FileDef objects.
#include <filedef.h>
Public Member Functions
FileList ()
FileList (const char *path)
~FileList ()
QCString path () const
Private Member Functions
int compareValues (const FileDef *md1, const FileDef *md2) const
Private Attributes
QCString m_pathName
Detailed Description
Class representing a list of FileDef objects.
Definition at line 240 of file filedef.h.
Constructor & Destructor Documentation
FileList() [1/2]
FileList::FileList () inline
Definition at line 243 of file filedef.h.
FileList() [2/2]
FileList::FileList (const char * path) inline
Definition at line 244 of file filedef.h.
~FileList()
FileList::~FileList () inline
Definition at line 245 of file filedef.h.
Member Function Documentation
compareValues()
int FileList::compareValues (const FileDef * md1, const FileDef * md2) const inline private
Definition at line 248 of file filedef.h.
References FileDef::name().
path()
QCString FileList::path () const inline
Definition at line 246 of file filedef.h.
References m_pathName.
Referenced by OutputNameList::compareValues(), and FileName::generateDiskNames().
Member Data Documentation
m_pathName
QCString FileList::m_pathName private
Definition at line 252 of file filedef.h.
Referenced by path().
The documentation for this class was generated from the following file:
src/filedef.h