Doxygen: MemberInfoContext::Private Class Reference
MemberInfoContext::Private Class Reference
Public Member Functions
Private (const MemberInfo *mi)
TemplateVariant get (const char *n) const
TemplateVariant protection () const
TemplateVariant virtualness () const
TemplateVariant ambiguityScope () const
TemplateVariant member () const
Private Attributes
const MemberInfo * m_memberInfo
SharedPtr< MemberContext > m_member
Static Private Attributes
static PropertyMapper< MemberInfoContext::Private > s_inst
Detailed Description
Definition at line 8570 of file context.cpp.
Constructor & Destructor Documentation
Private()
MemberInfoContext::Private::Private (const MemberInfo * mi) inline
Definition at line 8573 of file context.cpp.
References PropertyMapper< T >::addProperty(), ambiguityScope(), Config::init(), member(), protection(), s_inst, and virtualness().
Member Function Documentation
ambiguityScope()
TemplateVariant MemberInfoContext::Private::ambiguityScope () const inline
Definition at line 8614 of file context.cpp.
References MemberInfo::ambiguityResolutionScope, and m_memberInfo.
Referenced by Private().
get()
TemplateVariant MemberInfoContext::Private::get (const char * n) const inline
Definition at line 8589 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by MemberInfoContext::get().
member()
TemplateVariant MemberInfoContext::Private::member () const inline
Definition at line 8618 of file context.cpp.
References MemberContext::alloc(), SharedPtr< T >::get(), m_member, m_memberInfo, MemberInfo::memberDef, and SharedPtr< T >::reset().
Referenced by Private().
protection()
TemplateVariant MemberInfoContext::Private::protection () const inline
Definition at line 8593 of file context.cpp.
References m_memberInfo, Package, Private, MemberInfo::prot, Protected, and Public.
Referenced by Private().
virtualness()
TemplateVariant MemberInfoContext::Private::virtualness () const inline
Definition at line 8604 of file context.cpp.
References m_memberInfo, Normal, Pure, MemberInfo::virt, and Virtual.
Referenced by Private().
Member Data Documentation
m_member
SharedPtr<MemberContext> MemberInfoContext::Private::m_member mutable private
Definition at line 8635 of file context.cpp.
Referenced by member().
m_memberInfo
const MemberInfo* MemberInfoContext::Private::m_memberInfo private
Definition at line 8634 of file context.cpp.
Referenced by ambiguityScope(), member(), protection(), and virtualness().
s_inst
PropertyMapper< MemberInfoContext::Private > MemberInfoContext::Private::s_inst static private
Definition at line 8636 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp