Doxygen: src/latexdocvisitor.cpp File Reference
latexdocvisitor.cpp File Reference
#include "htmlattrib.h"
#include <qfileinfo.h>
#include "latexdocvisitor.h"
#include "docparser.h"
#include "language.h"
#include "doxygen.h"
#include "outputgen.h"
#include "dot.h"
#include "util.h"
#include "message.h"
#include "parserintf.h"
#include "msc.h"
#include "dia.h"
#include "cite.h"
#include "filedef.h"
#include "config.h"
#include "htmlentity.h"
#include "plantuml.h"
Functions
static const char * getSectionName (int level)
static void visitPreStart (FTextStream &t, const bool hasCaption, QCString name, QCString width, QCString height)
static void visitPostEnd (FTextStream &t, const bool hasCaption)
static void visitCaption (LatexDocVisitor *parent, QList< DocNode > children)
static bool tableIsNested (const DocNode *n)
static void writeStartTableCommand (FTextStream &t, const DocNode *n, int cols)
static void writeEndTableCommand (FTextStream &t, const DocNode *n)
Variables
const int maxLevels =5
static const char * secLabels [maxLevels]
Function Documentation
getSectionName()
static const char* getSectionName (int level) static
Definition at line 41 of file latexdocvisitor.cpp.
References Config_getBool, Doxygen::insideMainPage, maxLevels, and secLabels.
Referenced by LatexDocVisitor::visitPre().
tableIsNested()
static bool tableIsNested (const DocNode * n) static
Definition at line 911 of file latexdocvisitor.cpp.
References DocNode::kind(), DocNode::Kind_HtmlTable, DocNode::Kind_ParamSect, and DocNode::parent().
Referenced by writeEndTableCommand(), and writeStartTableCommand().
visitCaption()
static void visitCaption (LatexDocVisitor * parent, QList< DocNode > children) static
Definition at line 112 of file latexdocvisitor.cpp.
References DocNode::accept().
Referenced by LatexDocVisitor::visit(), LatexDocVisitor::visitPre(), LatexDocVisitor::writeDiaFile(), LatexDocVisitor::writeMscFile(), and LatexDocVisitor::writePlantUMLFile().
visitPostEnd()
static void visitPostEnd (FTextStream & t, const bool hasCaption) static
Definition at line 99 of file latexdocvisitor.cpp.
Referenced by LatexDocVisitor::endDiaFile(), LatexDocVisitor::endDotFile(), LatexDocVisitor::endMscFile(), LatexDocVisitor::visitPost(), LatexDocVisitor::writeDiaFile(), LatexDocVisitor::writeMscFile(), and LatexDocVisitor::writePlantUMLFile().
visitPreStart()
static void visitPreStart (FTextStream & t, const bool hasCaption, QCString name, QCString width, QCString height) static
Definition at line 50 of file latexdocvisitor.cpp.
Referenced by LatexDocVisitor::startDiaFile(), LatexDocVisitor::startDotFile(), LatexDocVisitor::startMscFile(), LatexDocVisitor::visitPre(), LatexDocVisitor::writeDiaFile(), LatexDocVisitor::writeMscFile(), and LatexDocVisitor::writePlantUMLFile().
writeEndTableCommand()
static void writeEndTableCommand (FTextStream & t, const DocNode * n) static
Definition at line 935 of file latexdocvisitor.cpp.
References tableIsNested().
Referenced by LatexDocVisitor::visitPost().
writeStartTableCommand()
static void writeStartTableCommand (FTextStream & t, const DocNode * n, int cols) static
Definition at line 922 of file latexdocvisitor.cpp.
References tableIsNested().
Referenced by LatexDocVisitor::visitPre().
Variable Documentation
maxLevels
const int maxLevels =5
Definition at line 37 of file latexdocvisitor.cpp.
Referenced by getSectionName().
secLabels
const char* secLabels[maxLevels] static
Initial value:
=
   { "section","subsection","subsubsection","paragraph","subparagraph" }
Definition at line 38 of file latexdocvisitor.cpp.
Referenced by getSectionName().