Doxygen: NavPathElemContext::Private Class Reference
NavPathElemContext::Private Class Reference
Public Member Functions
Private (Definition *def)
TemplateVariant get (const char *n) const
TemplateVariant isLinkable () const
TemplateVariant anchor () const
TemplateVariant fileName () const
TemplateVariant text () const
TemplateVariant isReference () const
QCString relPathAsString () const
TemplateVariant externalReference () const
Private Attributes
Definition * m_def
Static Private Attributes
static PropertyMapper< NavPathElemContext::Private > s_inst
Detailed Description
Definition at line 7639 of file context.cpp.
Constructor & Destructor Documentation
Private()
NavPathElemContext::Private::Private (Definition * def) inline
Definition at line 7642 of file context.cpp.
References PropertyMapper< T >::addProperty(), anchor(), externalReference(), fileName(), Config::init(), isLinkable(), isReference(), s_inst, and text().
Member Function Documentation
anchor()
TemplateVariant NavPathElemContext::Private::anchor () const inline
Definition at line 7664 of file context.cpp.
References Definition::anchor(), and m_def.
Referenced by Private().
externalReference()
TemplateVariant NavPathElemContext::Private::externalReference () const inline
Definition at line 7702 of file context.cpp.
References Definition::externalReference(), m_def, and relPathAsString().
Referenced by Private().
fileName()
TemplateVariant NavPathElemContext::Private::fileName () const inline
Definition at line 7668 of file context.cpp.
References Definition::getOutputFileBase(), and m_def.
Referenced by Private().
get()
TemplateVariant NavPathElemContext::Private::get (const char * n) const inline
Definition at line 7656 of file context.cpp.
References PropertyMapper< T >::get(), and s_inst.
Referenced by NavPathElemContext::get().
isLinkable()
TemplateVariant NavPathElemContext::Private::isLinkable () const inline
Definition at line 7660 of file context.cpp.
References Definition::isLinkable(), and m_def.
Referenced by Private().
isReference()
TemplateVariant NavPathElemContext::Private::isReference () const inline
Definition at line 7693 of file context.cpp.
References Definition::isReference(), and m_def.
Referenced by Private().
relPathAsString()
QCString NavPathElemContext::Private::relPathAsString () const inline
Definition at line 7697 of file context.cpp.
References Config_getBool.
Referenced by externalReference().
text()
TemplateVariant NavPathElemContext::Private::text () const inline
Definition at line 7672 of file context.cpp.
References DefinitionIntf::definitionType(), Definition::localName(), m_def, DefinitionIntf::TypeClass, DefinitionIntf::TypeGroup, and DefinitionIntf::TypePage.
Referenced by Private().
Member Data Documentation
m_def
Definition* NavPathElemContext::Private::m_def private
Definition at line 7707 of file context.cpp.
Referenced by anchor(), externalReference(), fileName(), isLinkable(), isReference(), and text().
s_inst
PropertyMapper< NavPathElemContext::Private > NavPathElemContext::Private::s_inst static private
Definition at line 7708 of file context.cpp.
Referenced by get(), and Private().
The documentation for this class was generated from the following file:
src/context.cpp